### ISSUE TITLE
[UI Bug]Connection view does not centered

### ISSUE THREAD

**Issue by jack3010** [TablePlus/TablePlus#1]
Steps to reproduce: 
* Create new connection -> Connect -> Edit connection -> View connection move over the top of window. See attached file
<img width="1280" alt="screen shot 2017-06-15 at 5 06 50 pm" src="https://user-images.githubusercontent.com/9066873/27176707-cb54317c-51ed-11e7-9641-57e99664b742.png">

**Comment by huyphams** [comment]
Cool, we got it.
This bug will be fixed in the next release 🐶🐶🐶

**Comment by huyphams** [comment]
We just fixed the bug, please update the app on https://tableplus.io or TablePlus > Check for update...
Thank you.
