### ISSUE TITLE
Schema's on my DB dont appear

### ISSUE THREAD

**Issue by Jurgem** [TablePlus/TablePlus#10]
I have a lot of schemas inside my database and in each schema have a lot of tables but the program don't show the tables or schema names... it is normal?

**Comment by huyphams** [comment]
Hi @Jurgem,
It's not normal. I confirmed that TablePlus only show public schema. 
Team will support select schema in the next release.
The next build will release in couple of days with a lot of bug fixes and new features.

**Comment by huyphams** [comment]
Hi @Jurgem,
Could you go to TablePlus > Check for Update...
Upgrade to version 53.
We support switch schema since version 53.

**Comment by Jurgem** [comment]
Thanks,  now it work

pd: i love the SQL formater
