### ISSUE TITLE
Setting NULL value when editing existing row

### ISSUE THREAD

**Issue by vgoloviznin** [TablePlus/TablePlus#100]
I'm using the latest version of TablePlus with Postgres DB and I can't seem to find a way to set a NULL value when editing an existing field. 

If an existing field is a varchar and contains some value, if you remove the value it transforms into an empty string but I don't see an option to set it NULL apart from doing a direct update query in the terminal

**Comment by huyphams** [comment]
Hi @vgoloviznin
Thanks for feedback, you can set null by hold option and click on the cell, it will show quick menu and there are a null option

**Comment by vgoloviznin** [comment]
@huyphams omg, turned out to be so easy :) 

May be as an enhancement there can be some sort of a label or smth like that to indicate extra options

**Comment by huyphams** [comment]
Yup, I'm thinking about that, because no one knows this menu.
Probably, we can show a tutorial only the first time user open app.

**Comment by huyphams** [comment]
I added a tooltips when hover mouse on cell
<img width="565" alt="screen shot 2017-11-03 at 12 48 14 am" src="https://user-images.githubusercontent.com/3654622/32341660-ba7c68ea-c030-11e7-9dec-6fc5f771a7e9.png">
