### ISSUE TITLE
Copying multiple history entries doesn't work

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1000]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

195

3. The steps to reproduce this issue:

If I select several entries (each of them can be 1+ sql) in history pane and copy them, then only 1st history record (1+ sql) is copied to the clipboard.

**Comment by huyphams** [comment]
Thanks @aik099 I just fixed it!

**Comment by aik099** [comment]
Thanks. Should I be closing issues myself OR you mass-close once fix would be released (even on beta channel)?

**Comment by huyphams** [comment]
Please wait until the official release, then we can close it 👍
