### ISSUE TITLE
Version mismatch in beta build update notification

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1002]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

1.6 (195)

3. The steps to reproduce this issue:

I'm using custom build downloaded from link in https://github.com/TablePlus/TablePlus/issues/994#issuecomment-466110134 comment. When I've selected option, that I want to receive beta updates and used `Check for Updates...` menu entry, then I'm presented with this dialog (asked to downgrade to is 1.5 version even though build number is larger):

![2019-02-23_1224](https://user-images.githubusercontent.com/1277526/53285148-0618ef00-3766-11e9-97b7-ab93449fdc50.png)

It seems, that beta build (at least 197 one) have wrong version number in them.

I'm not sure if it's safe to update or I'll loose fixes, that I'll currently have from #994 task.

**Comment by huyphams** [comment]
Thanks, I fixed the XML, it's fine now.
