### ISSUE TITLE
How to disable autocomplete?

### ISSUE THREAD

**Issue by noma4i** [TablePlus/TablePlus#1004]
Autocomplete is very slow on big databases with lots of schemas(PG) how I can disable it?

**Comment by huyphams** [comment]
Hey @noma4i  you can disable it and many other options here.
<img width="527" alt="screen shot 2019-02-25 at 6 57 04 pm" src="https://user-images.githubusercontent.com/3654622/53335839-28119d80-392f-11e9-83a1-835ad5034eb7.png">

**Comment by noma4i** [comment]
Oook. Shame on me

**Comment by noma4i** [comment]
As excuse I have bought license today ;)

**Comment by huyphams** [comment]
Thanks @noma4i 👍

**Comment by itseramin** [comment]
Is there a setting to disable functions on autocomplete?

**Comment by huyphams** [comment]
It does not support @itseramin however, we added it in the hotpatch: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

It will be included in the next update too.
