### ISSUE TITLE
Can't connect to MongoDB Atlas

### ISSUE THREAD

**Issue by alizahid** [TablePlus/TablePlus#1005]
1. MongoDB 3.6
2. 194
3. Using my primary cluster hostname to connect and getting the error below;

<img width="612" alt="screenshot 2019-02-25 16 42 17" src="https://user-images.githubusercontent.com/941775/53338165-77020780-391c-11e9-916f-fa7e3580626f.png">

Here is my config

<img width="612" alt="screenshot 2019-02-25 16 45 33" src="https://user-images.githubusercontent.com/941775/53338337-d8c27180-391c-11e9-8afb-241c44affc96.png">

What am I missing?

Also, when I try to use the full connection string to _Import from URL_, it just says invalid url. What url is it expecting?

**Comment by huyphams** [comment]
Hi, if it was admin database, you don't need to specify the auth source (default auth source is admin).
I will add an option to allow connection string in the future release.

**Comment by alizahid** [comment]
Even without explicitly specifying the auth database, I still get the error.

**Comment by huyphams** [comment]
Hi @alizahid I updated the mongo support (build 200), now it allows you to connect with URL. Please try it and let me know the result.

**Comment by alizahid** [comment]
@huyphams It works!

**Comment by marcelombc** [comment]
If the password has an @ sign it will not connect. I have to change the autogenerated password to one without @ sign.

**Comment by huyphams** [comment]
It will if you follow the mongo document, encoding password guideline

**Comment by huyphams** [comment]
TablePlus do not manipulate or do any preprocess the url. It send it to mongo driver, so you have to encode it before put into the url

**Comment by nfodor** [comment]
Hi, just purchased a version of Table Plus, not working with latest version of Atlas, not the free tier but the new pay tier, URI option "loadBalanced" prohibited in TXT record.

**Comment by huyphams** [comment]
Have you tried to put those flag into the URL authSource=your_user_name&loadBalanced=true @nfodor

**Comment by nfodor** [comment]
Lemme try, thank you for the super fast answer.

**Comment by nfodor** [comment]
So you know, and before I try, MongoDB Atlas new Serverless service is where the problem is, not sure about regular Atlas. Mongo provided URL is as such (Edited private values): mongodb+srv://user:password@domain.imbgn.mongodb.net
It would be good if you could provide a similar patterned URL that works with TablePlus and Atlas Serverless, this way people will find it here and not bother you any longer.
Thank you again! Great product by the way! Works flawlessly with local mongo and simple configurations, even regular Atlas if i remember 💯

**Comment by huyphams** [comment]
Thank you @nfodor let me sign up an Atlas account and try it with TablePlus. Will update asap

**Comment by huyphams** [comment]
Hey @nfodor I can confirm that you can connect to Mongo Atlas using the connection string which is provided by Atlas
The format is similar to this

mongodb+srv://user_name:your_password@cluster_name.mongodb.net/your_database?retryWrites=true&w=majority 


and of course, you need to whitelist your IP address in Atlas dashboard.

**Comment by nfodor** [comment]
Hi @huyphams  I believe that their new offering (Serverless, u may not be aware) is does not work the same, here is my connection that works with all other apps: 
mongodb+srv://xxx:yyy@zzz.imbgn.mongodb.net
Here is the response:
`failed to look up SRV record "_mongodb._tcp.zzz.imbgn.mongodb.net?retryWrites=true&w=majority": Operation not permitted`
Believe me, you are not aware of this new feature of theirs, its a serverless option and its pay as you go so u may want to check it out as more customers will use it on the mongo side and they are promoting it heavily.

This is the recommended connection string from Atlas given on the dashboard so i edited the real login values but its per Mongo. Please note the SetServerAPIOptions chain below.
When using from nodejs i have no problem whatsoever connecting to it.

This is the nodejs example from Mongo:

```
const { MongoClient, ServerApiVersion } = require('mongodb');
--
const uri = "mongodb+srv://xxx:<password>@zzz.imbgn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority";
const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true, serverApi: ServerApiVersion.v1 });
client.connect(err => {
const collection = client.db("test").collection("devices");
// perform actions on the collection object
client.close();
});
```

This is the Go example from Mongo:

```
import "go.mongodb.org/mongo-driver/mongo"

serverAPIOptions := options.ServerAPI(options.ServerAPIVersion1)
clientOptions := options.Client().
    ApplyURI("mongodb+srv://xxx:<password>@zzz.imbgn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority").
    SetServerAPIOptions(serverAPIOptions)
ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
defer cancel()
client, err := mongo.Connect(ctx, clientOptions)
if err != nil {
    log.Fatal(err)
}
```
