### ISSUE TITLE
Need more than 100 query results tabs

### ISSUE THREAD

**Issue by franfabrizio** [TablePlus/TablePlus#1006]
(TP build 194 connected to MySQL 5.7)

I have a long list of queries (197, to be exact) that I run to produce some reports from our database. I have these saved as a favorite. Unfortunately, when I run them, I only get results tabs for the first 100 queries and there's no way to access the results of the rest of the queries. Is this configurable? If not, consider this a feature request.

Thanks,
Fran

**Comment by huyphams** [comment]
Thanks, @franfabrizio yes, currently, it limits 100 tabs but it should be configurable.

**Comment by huyphams** [comment]
From the build 200, if you turn off the feature split result into tabs, TablePlus will append result message into one tab. does it fit with your needs @franfabrizio?

**Comment by franfabrizio** [comment]
There doesn't seem to be a way to export the results of an individual
select query if I do that, which is what I need to do. Being able to
configure the max number of tabs as you suggested earlier would solve the
problem. Thanks!

**Comment by fengyunhe** [comment]
I want can see all tabs  when  i "Run All" , show all result tabs

**Comment by fengyunhe** [comment]
> I want can see all tabs when i "Run All" , show all result tabs

or stack the tabs to some row? i want quick to switch tab just click onece

**Comment by fengyunhe** [comment]
or can display a number of sql block in editor , the tab name is the number ,  result tab name is the number to match the query.

**Comment by huyphams** [comment]
We no longer limit 100 tabs in the next update, so I will close this issue for now.
