### ISSUE TITLE
Windows - crashing on connect / not remembering password

### ISSUE THREAD

**Issue by libbie86** [TablePlus/TablePlus#1008]
Hi,

When connecting to a MySQL DB via SSH the software sometime just crashes when selecting the DB I want to open.

Also the software does not seem to be storing passwords, if you forget to go to edit and enter the password and then connect. The software just crashes instead of saying access denied.

**Comment by aik099** [comment]
Thank you. Please report Windows related issues into https://github.com/TablePlus/TablePlus-Windows/issues repo.

**Comment by huyphams** [comment]
Thanks, @libbie86 and @aik099 for the feedback. Please move this issue to the Windows repo and please answer the template issue question. Without it, I can't reproduce the bug and can't fix it.

**Comment by huyphams** [comment]
I fixed it on the release 56. Thanks.
