### ISSUE TITLE
Crash on reload workspace

### ISSUE THREAD

**Issue by kfur** [TablePlus/TablePlus#1009]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redis server v=5.0.3
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 194
3. The steps to reproduce this issue:
1) Start redis server
2) Connect to it
3) Stop server
4) Reload workspace two times.
5) TablePlus crashed

**Comment by huyphams** [comment]
Hi @kfur could you please try again with this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feeback

**Comment by kfur** [comment]
@huyphams with this build all working as intended
