### ISSUE TITLE
Random column order in generated INSERT statements

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1010]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

199

3. The steps to reproduce this issue:

a) execute these SQLs to seed database with needed data:

```sql
CREATE TABLE `inp_SystemSettings` (
  `VariableId` int(11) NOT NULL AUTO_INCREMENT,
  `VariableName` varchar(255) NOT NULL DEFAULT '',
  `VariableValue` text,
  `ModuleOwner` varchar(20) DEFAULT 'In-Portal',
  `Section` varchar(255) NOT NULL DEFAULT '',
  `Heading` varchar(255) NOT NULL DEFAULT '',
  `Prompt` varchar(255) NOT NULL DEFAULT '',
  `ElementType` varchar(255) NOT NULL DEFAULT '',
  `Validation` text,
  `ValueList` text,
  `DisplayOrder` double NOT NULL DEFAULT '0',
  `GroupDisplayOrder` double NOT NULL DEFAULT '0',
  `Install` int(11) NOT NULL DEFAULT '1',
  `HintLabel` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`VariableId`),
  UNIQUE KEY `VariableName` (`VariableName`),
  KEY `DisplayOrder` (`DisplayOrder`),
  KEY `GroupDisplayOrder` (`GroupDisplayOrder`),
  KEY `Install` (`Install`),
  KEY `HintLabel` (`HintLabel`)
) ENGINE=MyISAM AUTO_INCREMENT=523 DEFAULT CHARSET=latin1;

INSERT INTO `inp_SystemSettings` (`VariableId`, `VariableName`, `VariableValue`, `ModuleOwner`, `Section`, `Heading`, `Prompt`, `ElementType`, `Validation`, `ValueList`, `DisplayOrder`, `GroupDisplayOrder`, `Install`, `HintLabel`) VALUES ('51', 'Site_Name', 'Example Site', 'In-Portal', 'in-portal:configure_general', 'la_section_SettingsWebsite', 'la_config_website_name', 'text', '', '', '10.01', '0', '1', NULL);
```

b) open database/table in TablePlus
c) select row in a table and duplicate it (Command+D)
d) populate new row with changed data
e) save changes (actually in preview pane the issue is already seen)
f) copy executed SQL from history

The order of columns in the insert statement won't match the order of columns in the table itself (column names match value names by position and it's good, the column names are randomized and it's bad):

```sql
INSERT INTO `inp_SystemSettings` (`Section`, `Validation`, `Prompt`, `Heading`, `VariableName`, `ValueList`, `GroupDisplayOrder`, `ElementType`, `VariableId`, `Install`, `VariableValue`, `DisplayOrder`, `ModuleOwner`) VALUES ('in-portal:configure_general', '', 'la_config_InactiveSubDomainRedirectURL', 'la_section_SettingsWebsite', 'InactiveSubDomainRedirectURL', '', '0', 'text', DEFAULT, '0', 'https://www.domain.com', '10.03', 'In-Portal');
```

P.S.

If I select a row and do `Copy Row As > SQL Insert Statement` from context menu, then column order would be correct.

**Comment by aik099** [comment]
Any update on this? The issue is still happening on 216 build.

**Comment by huyphams** [comment]
Thank @aik099 for reminding me, I will fix it now.

**Comment by huyphams** [comment]
Have you re-ordered  the column in the table view @aik099 ?

**Comment by aik099** [comment]
Once, but for another table in same database.

**Comment by huyphams** [comment]
Yep. because I can't reproduce the issue with the table creation above, it works as expected. it's worth it to mention that TablePus respects the current column ordering, so if you change it, it will affect the copy as Insert column ordering.

**Comment by aik099** [comment]
Shouldn't the SQL built, when you change table data use same column ordering information as SQL built from `Copy Row As > SQL Insert Statement` context menu?

**Comment by huyphams** [comment]
TablePlus only fetches information if needed. at the time you `Copy Row As > SQL Insert Statement` the table structure was not loaded, so there is no way to know the original column position.
Currently, TablePlus is using the column order in the table view.

**Comment by aik099** [comment]
I've did another try (also recorded a video: https://screencast.com/t/10NiqICLm):

1. create table using this structure:

```sql
CREATE TABLE `TestTable` (
  `VariableId` int(11) NOT NULL AUTO_INCREMENT,
  `VariableName` varchar(255) NOT NULL DEFAULT '',
  `VariableValue` text,
  `ModuleOwner` varchar(20) DEFAULT 'In-Portal',
  `Section` varchar(255) NOT NULL DEFAULT '',
  `Heading` varchar(255) NOT NULL DEFAULT '',
  `Prompt` varchar(255) NOT NULL DEFAULT '',
  `ElementType` varchar(255) NOT NULL DEFAULT '',
  `Validation` text,
  `ValueList` text,
  `DisplayOrder` double NOT NULL DEFAULT '0',
  `GroupDisplayOrder` double NOT NULL DEFAULT '0',
  `Install` int(11) NOT NULL DEFAULT '1',
  `HintLabel` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`VariableId`)
);
```
2. open that table in data view
3. click `+ Row` button in the bottom
4. as new values type this (order of columns as in definition, but some columns skipped):
- `aa` for `VariableName` field
- `bb` for `VariableValue` field
- `cc` for `ModuleOwner` field
- `1` for `DisplayOrder` field
- `2` for `GroupDisplayOrder` field
- `3` for `Install` field
5. in preview pane instead of getting `'aa', 'bb', 'cc', '1', '2', '3'` I'm getting `'2', 'bb', '3', 'cc', 'aa', '1'`
.

**Comment by huyphams** [comment]
Thanks, I fixed it!

**Comment by huyphams** [comment]
If you want to download the build, it's here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the feedback

**Comment by aik099** [comment]
Thanks.
