### ISSUE TITLE
Postgres: Allow backup and restore with --no-privileges or -x pg_dump/pg_restore flag

### ISSUE THREAD

**Issue by leonsmith** [TablePlus/TablePlus#1011]
> 1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 11.0

> 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

v 1.6 (Build 194)

> 3. The steps to reproduce this issue:

* Load TablePlus
* Choose "Backup" from the File menu
* Choose a postgres connect
* Choose a source database
* In "add options" It's not possible to dump with the `-no-privileges` or `-x` flag

**Comment by huyphams** [comment]
Hey @leonsmith have you tried to add it directly by typing in the box?

**Comment by leonsmith** [comment]
Appoligies! Didn't realise this was possible!
