### ISSUE TITLE
Takes an extremely long time to connect when it cannot connect to CrashAlytics

### ISSUE THREAD

**Issue by envygeeks** [TablePlus/TablePlus#1012]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Any
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 190
3. The steps to reproduce this issue: Block crashalytics.com

Our network blocks crashaltycs.com and other various analytics services, please do not tie a paid app to an analytics service, and then slow us down when we block said analytics service, that's not cool.

**Comment by huyphams** [comment]
Hi @envygeeks we're going to remove Fabric and Crashlytics, we also put an option out of the crash report in the next update too. Thanks for the feedback.

**Comment by envygeeks** [comment]
Awesome! Is there a beta build I can access that has this done already?

**Comment by huyphams** [comment]
Yes. there is, here is the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Preferences > Crash & Security > Disable Crash Report
Thanks!

**Comment by aik099** [comment]
@envygeeks , you can also enable automatic updating to beta builds if you like.
