### ISSUE TITLE
App freezes on "Export" with ssh connection

### ISSUE THREAD

**Issue by grechaniy** [TablePlus/TablePlus#1013]
i was trying to dump database, but after 7th failed attempts i can assume that this is an issue.

app freezes and do not responding, so i cannot either cancel export command or close it. it do not responding to user's interactions but still i can see that connection speed indictor changes values.
also i do not understand why it shows up such low connection speed (see attached image), cuz i have reliable internet connection and my db placed on aws server.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.7.25
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
version 1.6 (194)
3. The steps to reproduce this issue:
- connect to database with ssh. i use .pem file and "no password" access
- select all tables and press File -> Export

![screen shot 2019-02-28 at 19 08 18](https://user-images.githubusercontent.com/11639082/53585226-1417a700-3b8e-11e9-89d8-4488f8087d72.png)

**Comment by huyphams** [comment]
Hi @grechaniy do you have a table with millions of rows? TablePlus will try to count the number of rows first, maybe it freezes here.

**Comment by grechaniy** [comment]
nope, my whole db size is around 30-40mb

**Comment by huyphams** [comment]
But how you export without select any table? (you said that you selected all table but I can't see it or I missed something?) I tried but can't reproduce it.

**Comment by grechaniy** [comment]
@huyphams please see this video for better understanding :)

https://drive.google.com/file/d/17PQQupMyFCIhO0dJu-u56iSvricWGxEM/view?usp=sharing

**Comment by huyphams** [comment]
thanks @grechaniy it helps me a lot! I got the bug now!

**Comment by huyphams** [comment]
I have fixed the freeze bug but not sure why the connection is disconnected.
Here is the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Note: You can use backup/restore to create a full database backup. it uses database binaries so it is fully compatible with MySQL.

**Comment by grechaniy** [comment]
thanks, it is possible now to skip export task, however export itself (with method that i showed you on video previously) isn't working 😞 it is running already for half hour and progress but didn't moved yet
![screen shot 2019-03-04 at 11 20 15](https://user-images.githubusercontent.com/11639082/53723048-85e24000-3e6f-11e9-9472-620272f05c42.jpg)

and thanks for noticing, export from launch screen works, so i am able to proceed what i needed.
just keep in mind that you still have some issues with export on ssh connection.

btw, will i receive updates notifications, since i'm using now build version that you've sent me with dropbox?

**Comment by huyphams** [comment]
yep, you will receive updates notifications (or you can come back to the official release which is included the fix by downloading it again on the home page.)

**Comment by grechaniy** [comment]
thanks.
with current issue, i'm closing here
