### ISSUE TITLE
[Feature Request] Auto-expand current day in history

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1015]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

199

3. The steps to reproduce this issue:

When I first connect to a database all sections (days) on the "History" tab are collapsed. It would be useful have section matching current day by expanded default.

That would cover workflow, where just executed SQLs as a result of a schema change needs to be copied elsewhere (e.g. deployment script).

**Comment by huyphams** [comment]
let me consider this feature @aik099
