### ISSUE TITLE
[Feature Request] Case-insensitive column search in "Structure View"

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1016]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

199

3. The steps to reproduce this issue:

When table has columns named in different case, e.g. `SampleColumn` and I search for `sam`, then nothing is found. It would be great to make column search in structure view case-insensitive (and optionally with ^ and $ support) as done in database table search box.

**Comment by huyphams** [comment]
Thanks @aik099 and sure we will add it.
