### ISSUE TITLE
table scrollbar

### ISSUE THREAD

**Issue by tvalleau** [TablePlus/TablePlus#1017]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): na

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.6 (194)
3. The steps to reproduce this issue:
Try scrolling long table list.
Our WordPress site db has hundreds of tables (may more than 1000). The scroll list "thumb bar"  (scroll bar) does not appear. The only way I can scroll thru the list is with the down arrow. Once the list starts scrolling, the thumb appears and I can can click and hold on it with my mouse. Then I can release the down arrow. However once I release the mouse button, the scroll bar goes away, and I have to repeat the process. The scroll bar should -never- go away!

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @tvalleau I fixed it, thanks for the report: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by tvalleau** [comment]
Perfect!  Thank you for your prompt fix  :-)



On 2 Mar 2019, at 7:55, Huy Pham wrote:

> Hi @tvalleau I fixed it, thanks for the report: 
> https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/TablePlus/TablePlus/issues/1017#issuecomment-468932612



Tracy
www.valleau.art
