### ISSUE TITLE
Alphabetical sorting of numeric values

### ISSUE THREAD

**Issue by Patrick-Remy** [TablePlus/TablePlus#1019]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
194

3. The steps to reproduce this issue:
- Open any table with a lot of id's
- Filter by any column
- Click on the id column to sort it ascending or descending

The sorting result looks like:
495536
499116
500233
503213

instead of expected
499116
503213
495536
500233

**Comment by huyphams** [comment]
Hi @Patrick-Remy TablePlus doesn't handle this sort, it's returned by the database.
Basically, it generates a command like this one: `SELECT * FROM "public"."1mil-rows-mac" ORDER BY "id" DESC LIMIT 300 OFFSET 0;`

**Comment by huyphams** [comment]
Which data type of your id? is it varchar or integer?

**Comment by Patrick-Remy** [comment]
My fault – can be closed.
