### ISSUE TITLE
Misspelt form label

### ISSUE THREAD

**Issue by vik101** [TablePlus/TablePlus#1020]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 200

3. The steps to reproduce this issue: Create a new connection -> Tick "Use SSH key"

The word passphrase is misspelt to "passpharse" :)

![screen shot 2019-03-04 at 11 42 57](https://user-images.githubusercontent.com/2551224/53731638-52a1b000-3e73-11e9-8c10-fcfea411a4e6.png)

**Comment by huyphams** [comment]
Thanks @vik101 I fixed it.
