### ISSUE TITLE
Aggregated views and materialised view are not shown in the left side panel

### ISSUE THREAD

**Issue by andreamoro** [TablePlus/TablePlus#1026]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgresql 11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.0

3. The steps to reproduce this issue:
create either a view or a materialised view. Once done, the left side navigation menu doesn't refresh neither there is a button to allow that.
The only chance to see "changes" is to re-connect again.

**Comment by huyphams** [comment]
Hi @andreamoro  There is a refresh button on title bar. You can also refresh by pressing command + S

**Comment by andreamoro** [comment]
Hey @huyphams thanks for returning to me. 
I guess you may agree with me that a contextual menu item could simplify things. I didn't really spot that refresh button in the nav bar.
Cheers

**Comment by huyphams** [comment]
I just moved the refresh button to the left, maybe it's easier for people to discover it.
<img width="1343" alt="refresh" src="https://user-images.githubusercontent.com/3654622/53929086-237f7e80-40bf-11e9-84fa-dd141b6d6240.png">

**Comment by SeanFLynch** [comment]
Hi Guys,

I'm also having this issue. None of my views are shown in the interface, only the tables.

Which driver are you using and version of it:
Snowflake 3.16.3

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

TablePlus 2.1

**Comment by huyphams** [comment]
@SeanFLynch this build should fix your issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 Thank you
