### ISSUE TITLE
TablePlus (#56) crashes when F5 key pressed in detail view edit field

### ISSUE THREAD

**Issue by icawebdesign** [TablePlus/TablePlus#1027]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
56 (running on Windows 10 Pro, x64)

3. The steps to reproduce this issue:
Select a table, select a row, display detail panel, click in a text field to edit data, hit F5 key.

TablePlus crashes and disappears.

**Comment by huyphams** [comment]
Thanks, @icawebdesign I just fixed it, but the issue tracker of Windows version is here: https://github.com/TablePlus/TablePlus-Windows/issues
