### ISSUE TITLE
Incorrect affected row count for failed queries

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1031]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

201

3. The steps to reproduce this issue:

Run any query with an error, e.g. `TRUNCATE phabricator_worker.active_task;` and get this error back:

```
Query 1 ERROR: Table 'phabricator_worker.active_task' doesn't exist, 18446744073709551615 rows affected
```

The `Table 'phabricator_worker.active_task' doesn't exist` part is what MySQL returns, but `, 18446744073709551615 rows affected` text must be added by mistake by TablePlus itself.

**Comment by huyphams** [comment]
Hi @aik099 thanks for the feedback. I just fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
