### ISSUE TITLE
Decimal delimiter for CSV export (and copy / paste) is ignored

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1032]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 200 (macOS)

3. The steps to reproduce this issue:

Create an SQLite table with a few columns formatted as double.
Export table. Chose as decimal delimiter ','.

The resulting export file has numbers with "." as a delimiter.
The same happens when using right click > Copy Rows As > CSV / CSV With Header.

I have never been able to export a table with "," as decimal delimiter. The settings in the preferences also do not help.

Best,
Chris

**Comment by huyphams** [comment]
Hi @chrschmitz I believe that TablePlus has shown you a warning that said `Column delimiter and decimal delimiter shouldn't be the same symbol`

You can not use the same character for both column and decimal.

**Comment by chrschmitz** [comment]
I have set the column delimiter to "Tab".

**Comment by huyphams** [comment]
Thanks, @chrschmitz for the confirmation, it would be great if you can send me a table definition to my email huy @ tableplusapp.com
Thank you so much.

**Comment by chrschmitz** [comment]
I just sent you a table definition together with an SQL dump and a CSV export of the table.

**Comment by chrschmitz** [comment]
Hi Huy,

the bug is back again...

Chris
