### ISSUE TITLE
Wrong On DELETE after ALTER FK

### ISSUE THREAD

**Issue by Borkache** [TablePlus/TablePlus#1034]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7.18-16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus version 2.0 (200)

3. The steps to reproduce this issue:
Changed FK ON DELETE via UI, see this queries in log, so seems everything is fine
-- 2019-03-11 10:59:20.7290
ALTER TABLE `CheckoutPage` DROP FOREIGN KEY `CheckoutPage_ibfk_1`;
ALTER TABLE `CheckoutPage` ADD FOREIGN KEY (websiteId) REFERENCES `Website` (id) ON DELETE RESTRICT;

When I opened ui again, I saw `NO ACTION` under `ON DELETE` inside select box. Inside "definition" I see that `KEY `idx_websiteId` (`websiteId`),
  CONSTRAINT `CheckoutPage_ibfk_1` FOREIGN KEY (`websiteId`) REFERENCES `Website` (`id`),`

**Comment by huyphams** [comment]
Hi @Borkache after double check and from the MySQL document, they are the same:
https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html
```
RESTRICT: Rejects the delete or update operation for the parent table. Specifying RESTRICT (or NO ACTION) is the same as omitting the ON DELETE or ON UPDATE clause.
```
So after changing to RESTRICT, MySQL auto convert to NO ACTION as its conventions.
