### ISSUE TITLE
[Feature-Request] Allow the editing of a query while executing

### ISSUE THREAD

**Issue by dornby** [TablePlus/TablePlus#1036]
It's very common to run an *intermediate* query to get a first snap of results and wishing to continue iterating on the code of that query while it's executing.

As of today, we (the data team at Drivy) copy and paste the query in a split screen to be able to do so but those are avoidable clicks.

The issue happens when the query takes time to cancel, too. In that case you're not even in the process of iterating but in the process of fixing your code, which happens often too.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 8.0.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
200

3. The steps to reproduce this issue:
Run a query and try iterating while it's executing.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by teej** [comment]
The inability to edit while waiting for query results to return is going to force me to switch back to Postico.

**Comment by huyphams** [comment]
Hi guys, I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the feedback!

**Comment by dornby** [comment]
This is going to be life changing :)
Thanks @huyphams !
