### ISSUE TITLE
Duplicate Tables in List When Refresh Snowflake DB Workspace

### ISSUE THREAD

**Issue by rwhitten577** [TablePlus/TablePlus#1037]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake 3.16.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
200 

3. The steps to reproduce this issue:
Connect to database, select schema. Command + R to refresh workspace. Every table in the left list gets duplicated. Happens again every time data is refreshed. Only way to resolve is to close connection and re-open. 

Running on MacOS Mojave 10.14.3

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @rwhitten577 could you please give this build a try: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I've fixed it but can't test because I don't have any SnowflakeDB instance.
Thank you so much!

**Comment by rwhitten577** [comment]
@huyphams works great! Thank you for the quick fix!
