### ISSUE TITLE
Beautify should allow lowercase option

### ISSUE THREAD

**Issue by jbergstroem** [TablePlus/TablePlus#1038]
There should be an option to allow beautify to output lowercase characters for keywords/function names. Some people (weirdos like me) like it like that :-)

Thanks!

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

sqlite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

203

3. The steps to reproduce this issue:

Use beautify!

**Comment by georgexsh** [comment]
exactly! +1 for this

**Comment by huyphams** [comment]
the beautify function now respects the setting "auto uppercase keywords."
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by georgexsh** [comment]
@huyphams wonderful, hope the new version could be released soon.

**Comment by jbergstroem** [comment]
Just tried this out. Looks like offset still is in CAPS:
<img width="205" alt="Screen Shot 2019-05-03 at 11 06 26 AM" src="https://user-images.githubusercontent.com/176984/57146564-a0636780-6d93-11e9-87c3-9903c5f0657f.png">

**Comment by huyphams** [comment]
Thanks, I will fix it.
