### ISSUE TITLE
brew cask install checksum mismatch error

### ISSUE THREAD

**Issue by xuefeng-huang** [TablePlus/TablePlus#104]
I am using brew cask install tableplus (tableplus--1.0,67.zip)
the error it gave is:
Error: Checksum for Cask 'tableplus' does not match.

Expected: 6c1441e02682b205346f23e6f26a3f3b0a594bbdd41e08245d5794375ebe521f
Actual:   d8b2e99a3217291461b4a57774ce48dac85c271ec7105f2165eda0b7e574b12c

**Comment by huyphams** [comment]
Hi @xuefeng-huang 

We didn't support brew cask yet, maybe someone does. Please go to homepage and download the latest build 68.

Thanks,
Huy.
