### ISSUE TITLE
Allow INSERT/UPDATE/DELETE for views

### ISSUE THREAD

**Issue by daytonlowell** [TablePlus/TablePlus#1042]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
200

3. The steps to reproduce this issue:
Try to use the UI to add/update/delete a row from a view. You'll receive an error that it can't be done for views.

This is possible. See https://dev.mysql.com/doc/refman/5.7/en/view-updatability.html

**Comment by daytonlowell** [comment]
Is this added or just wont do?

**Comment by huyphams** [comment]
We added it recently
