### ISSUE TITLE
Completion in SQL editor not aware of schema names

### ISSUE THREAD

**Issue by erikbos** [TablePlus/TablePlus#1044]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
AWS Redshift

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 2.0 (200)

3. The steps to reproduce this issue:

Some databases require the schema name always to be provided. (see https://github.com/TablePlus/TablePlus/issues/1039)

Given this I would like the completion engine to be aware of this: in case of "SELECT COUNT(*) FROM schema." the query completion engine should suggest the relevant table names. Currently it does not.

**Comment by techniq** [comment]
This is a pretty major issue for our team as well.  We're currently using SQL Server (but also plan to connect to Oracle and MySQL instances).  Otherwise this tool has been great and solved issues we've had with others we've used.

**Comment by huyphams** [comment]
Are you using redshift @techniq? because I see it works with PostgreSQL.
Thank for reminding me. I will fix this issue and release it on the next update.

**Comment by huyphams** [comment]
I've created a Redshift Instance and it seems to be fixed on the latest release 222
<img width="902" alt="Screen Shot 2019-04-30 at 11 24 16 PM" src="https://user-images.githubusercontent.com/3654622/56977336-22d70600-6b9f-11e9-9746-365ea85e6318.png">

**Comment by techniq** [comment]
@huyphams Thanks for the quick reply.  I think the issue(s) is be more nuanced upon a deeper look:

## Schema shares name with Table
If a schema has the same name as a table, it will always show the table's columns when completing a table name (ex. I have an `Organization` schema which has an `Organization` table (along with `Department`, etc)

The completion of table names does not work, but after hand typing the table name and using an alias, the completion works on the `where` clause.

![TablePlus_Completion1](https://user-images.githubusercontent.com/177476/56978970-b4fef000-6b46-11e9-9cb6-79ec09f1d851.gif)

Bug: Completion of table names when schema is also a table name

## Schema is a keyword
If the schema has the same name as a keyword (ex. `Statistics`), the completion of the table names within the schema works, but not the columns names (similar but opposite of the the other bug)

![TablePlus_Completion2](https://user-images.githubusercontent.com/177476/56979875-cfd26400-6b48-11e9-822c-876a10f44259.gif)

Bug: Completion of column names when schema is a reserved word

**Comment by huyphams** [comment]
Made sense, thank you!

**Comment by huyphams** [comment]
Hi @techniq I've fixed this issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the feedback.

**Comment by huyphams** [comment]
Hmmm, all works except the alias case.

**Comment by huyphams** [comment]
hey guys, this build should fix all the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it.

**Comment by techniq** [comment]
Thanks @huyphams, I'm installing it now and will report back if it's still a problem.  We're also in the process of purchasing probably a 4-5 seat license.

One of the developers had a computer crash (not related to TablePlus) but he was disappointed it did not save his open query when he reopened the app.  Is there any possibility it would be saved anywhere on the disk?  I know it's supposed auto-save, but didn't know if it only did that on program close (instead of periodically).

**Comment by huyphams** [comment]
TablePlus will save the query when:
1. Close the editor (close the tab or close the workspace).
2. Execute a query (it's also recorded in the history)
3. Beautify or Uglify query.
4. Close the app (not force close).

I'm not sure, if he executed the query, please take a look at the History tab.

**Comment by techniq** [comment]
@huyphams Awesome, we found it in the History tab.  I'll work on getting some licenses purchased in the next day or two.  So far we've been very happy with the tool (coming from Azure Data Studio).

**Comment by huyphams** [comment]
Thank you! please share the hotfix build with your team, I've fixed some bug related to SQL Server on that build.
When the official is released, it will receive the update just like the normal build.

**Comment by techniq** [comment]
@huyphams Looks like `Schema shares name with Table` issue is fixed with this build (224) but `Schema shares name with keyword` doesn't appear to be.  After typing the period after the `sv` alias, I'm not getting any autocomplete (see gif up above).

**Comment by huyphams** [comment]
Hey @techniq please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the confirmation.

**Comment by techniq** [comment]
@huyphams Working now, thanks!
