### ISSUE TITLE
SQL editor and whitespace fun..

### ISSUE THREAD

**Issue by erikbos** [TablePlus/TablePlus#1045]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
AWS  Redshift

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
203

3. The steps to reproduce this issue:

[ This is a FYI not sure if this is a Tableplus issue ]

I have a number of queries in PostIco and want to migrate these to TablePlus. (Great software btw!). After cut and pasting some of them did not want to execute. 

After some investigation I noticed whitespace issues between reserved words: when I would replace the white space with these queries would run(!)

After cut-n-paste:

<img width="485" alt="Screenshot 2019-03-13 at 13 48 27" src="https://user-images.githubusercontent.com/1421163/54280195-31d60a80-4597-11e9-92b4-d66f205a6cc7.png">

Please note that FROM is not highlighted...
After replacing the whitespace before and after FROM manually:

<img width="464" alt="Screenshot 2019-03-13 at 13 55 04" src="https://user-images.githubusercontent.com/1421163/54280379-a1e49080-4597-11e9-83aa-109429b2a53f.png">

When storing the clipboard contents in a file (cat > file ; hexdump) I see an additional byte 0xc2 (!), not sure where this is coming from. PostIco is fine with it, TablePlus is more strict.

**Comment by huyphams** [comment]
is there any chance that I can have an example @erikbos a file contains the query would be great

**Comment by erikbos** [comment]
See, attachment. pbcopy < sql_weird_characters.txt puts it back on your clipboard.

[sql_weird_characters.txt](https://github.com/TablePlus/TablePlus/files/2972411/sql_weird_characters.txt)

**Comment by huyphams** [comment]
Hi @erikbos I just checked your statement with psql which is the official PostgreSQL client, and it can't execute that statement too.

So I think TablePlus will keep it as it is. Converting user input which can lead to unexpected error (when user copy a query from TablePlus to their report and it can't execute), I'm sure you will lose a lot of hair in that situation.

Any query that can run in TablePlus, will run everywhere!
