### ISSUE TITLE
Double clicking on column name bar to set column width sets a fixed width for columns

### ISSUE THREAD

**Issue by erikbos** [TablePlus/TablePlus#1046]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
AWS Redshift

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
203

3. The steps to reproduce this issue:

Double clicking on the column names separator results in setting the width for that column. Unfortunately it always results in the same width, e.g. double clicking to the right of "yearmonth":

<img width="792" alt="Screenshot 2019-03-13 at 14 35 59" src="https://user-images.githubusercontent.com/1421163/54282960-5cc35d00-459d-11e9-9e42-de68c3e98b57.png">

Better would be to asses the width of the visible values in a column and use that to discover the width to use for a column. 

(Also mentioned in https://github.com/TablePlus/TablePlus/issues/921)

**Comment by huyphams** [comment]
I have enabled it before but then I faced an issue where TablePlus could hang forever if the result contains many rows with long text, so i  disable it. if I can override this function I will re-enable it, but it has low priority than some other issues.
