### ISSUE TITLE
PHP serialize data doesn't display correctly

### ISSUE THREAD

**Issue by simonhamp** [TablePlus/TablePlus#1047]
1. Driver (Ex: PostgreSQL 10.0):
MySQL 5.x, MySQL 8.x - MariaDB 10.1.30, MySQL 5.7.22, MySQL 8.0.13

2. TablePlus build number:
200

3. The steps to reproduce this issue:
Write a PHP-serialized object to a database (e.g. `serialize(new stdClass)`). Observe the serialized string is cut off in TablePlus:
<img width="305" alt="Screenshot 2019-03-09 at 18 24 56" src="https://user-images.githubusercontent.com/31628/54075547-ac054700-4298-11e9-957f-f89bde8e6ea0.png">

But if you connect directly to mysql and query for that data, it will be complete.

**Comment by huyphams** [comment]
Hi @simonhamp which is the data type of the field? could you send me an example file via email huy@tableplusapp.com ?
Thanks

**Comment by meex** [comment]
@huyphams @simonhamp As I just encountered the issue myself, I did a quick search for a possible cause. When an object with private members is serialized in PHP, the names of the private members are prefixed with `*`, but the asterisk is surrounded by null-bytes. I think the null-bytes are causing the trouble. The PHP manual recommends to store serialized data in `Blob` instead of `Text` / `Varchar`, but it would be nice if Tableplus could handle this case anyway :-)

**Comment by huyphams** [comment]
Hi @meex thank you for clarify it, that made sense now. I've improved it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Could you guy give it a try and let me know the result?
cc @simonhamp

**Comment by dclawson** [comment]
Also having this issue with Wordpress Scheduled posts:

```
O:30:"ActionScheduler_SimpleSchedule":1{s:41:"ActionScheduler_SimpleScheduletimestamp";i:1557514373;}
```

TablePlus cuts this off at:

```
O:30:"ActionScheduler_SimpleSchedule":1:{s:41:"
```

Thanks.

**Comment by imacrayon** [comment]
Seeing this same issue, strings are cut short at the first null byte. Storing these strings as `TEXT` or `BLOB` has no affect on the way TablePlus handles them. I've attached two SQL dumps, both are the same database, one from Sequel Pro and one from TablePlus. You can see the `cart_data` column is truncated in the TablePlus dump.

[sequelpro-export.txt](https://github.com/TablePlus/TablePlus/files/3422524/sequelpro-export.txt)
[tableplus-export.txt](https://github.com/TablePlus/TablePlus/files/3422525/tableplus-export.txt)

**Comment by huyphams** [comment]
Hey, I can reproduce the issue now, and we're working on it.

**Comment by huyphams** [comment]
Hey guys, please try this build and let me know the result: https://www.dropbox.com/s/4033rlop6eov1ur/TablePlus.dmg?dl=0
cc @simonhamp @meex @dclawson

**Comment by dclawson** [comment]
Yes, perfect. Thanks @huyphams

**Comment by simonberger** [comment]
Serialized data is still truncated on null characters (\x00). In our case private/protected class properties.

**Comment by huyphams** [comment]
Hi @simonhamp could you send me a dump data example via email nick@tableplus.com ?
Thank you so much

**Comment by simonberger** [comment]
@huyphams I would need to have a close look if I can send this data to you. But I now noted this issue was created specifically for mysql.
We got it in a Redis connection. Has the very same issue maybe not been fixed for this?

**Comment by huyphams** [comment]
Hey @simonberger if you have a chance, please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know the result (on both Redis and MySQL). Thank you!

**Comment by simonberger** [comment]
@huyphams thank you for the fast new build. I tested it and can confirm that the serialized data is displayed to the end now. **But** the null-bytes are just skipped. The example data from above is displayed as:
`
O:21:"Some\Random\Namespace":1:{s:32:"Some\Random\Namespaceproperty1" ...`

This state is dangerous as the data is incomplete / corrupted.
I have just test data for Redis at the moment. But most likely the solution for Mysql looks the same?!

The console redis client itself shows it also escaped. Meaning the correct example is this:

`O:21:\"Some\\Random\\Namespace":1:{s:32:\"\x00Some\\Random\\Namespace\x00property1\" ...`

**Comment by huyphams** [comment]
Thanks, but I still want an example dump (just one row are enough for me). so I can reproduce the issue and fix it.

**Comment by huyphams** [comment]
Okie @simonhamp please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 I've escaped all the character before displaying.

**Comment by simonberger** [comment]
Hi @huyphams The displayed data is the same as the previous build.
I can't provide data today. It also wouldn't be helpful to just copy a key from redis console command. Better would be  a minimum php example whose result you could insert into your redis test instance.

Maybe @meex @dclawson or @imacrayon can double check in mysql if the null byte is gone (and maybe more), if this is an actual issue and maybe provide the needed data to test.
