### ISSUE TITLE
Cell level selection

### ISSUE THREAD

**Issue by acrodrig** [TablePlus/TablePlus#1048]
I am starting to use TablePlus as a replacement of MySQL Workbench and I really like it. One thing that I would like to have is single cell selection. In MySQL workbench you can navigate between cells using the keyboard arrows and change each field individually. In TablePlus I need to resort to the mouse to double click on a single cell ... and only then can I tab from field to field.

Hoping it makes sense. Thanks!

**Comment by huyphams** [comment]
It's supported now, thanks
