### ISSUE TITLE
Data Corruption on CQL query, which also result in corrupted CSV extract 

### ISSUE THREAD

**Issue by NoahLiot** [TablePlus/TablePlus#1049]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
Cassandra 3.11.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
build 200

3. The steps to reproduce this issue: 

Hello, when I run a filtering query asking for a specific value in a date field and it returns me invalid values which are not what I requested and also seems corrupted as those are not in my original data. 

As you can see from the screenshot, the data should be `'2018-12-31'` as this is what my query is, yet it somehow returns me `'2019-12-31'` and this weird behavior seems to be passed on when I do a CSV export as the data seems to be exported as `'2019-12-31'`.

![screenshot](https://user-images.githubusercontent.com/8589710/54355856-1b40b980-4652-11e9-90db-8d9a90c2147c.png)

Also when I query the Cassandra servers directly the corruption is not there, so the stored data is correct:

![image (1)](https://user-images.githubusercontent.com/8589710/54356368-5c859900-4653-11e9-8542-8bbd9ce34c55.png)

It is also correct on a windows version of TablePlus using the same driver.

![image (2)](https://user-images.githubusercontent.com/8589710/54356393-6d360f00-4653-11e9-9f99-2283a43f0310.png)

**Comment by huyphams** [comment]
hmm, it looks weird to me, let me check it. I'm using the same driver and the same parse function for macOS and Windows.

**Comment by huyphams** [comment]
I'm not sure why Apple Swift screwed everything.
    ```
      SQLLogger.debug("\(date)")
      let dateFormatter = DateFormatter()
      dateFormatter.dateFormat = "YYYY-MM-dd"
      value = dateFormatter.string(from: date)
```
Here is what the log looks like:
```
2018-12-31 00:00:00 +0000
2018-12-31 00:00:00 +0000
2018-10-31 00:00:00 +0000
2018-12-31 00:00:00 +0000
```
but after
      dateFormatter.dateFormat = "YYYY-MM-dd"
      value = dateFormatter.string(from: date)
it shows:
```
2019-12-31
2019-12-31
2018-10-31
2019-12-31
```

**Comment by huyphams** [comment]
Holy sh*t, turn out that `YYYY` is not `yyyy`, after changing to `yyyy` (lower case), it works now.
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feedback.

**Comment by NoahLiot** [comment]
Hey! Cool, looking forward to the patch. Thank you.

**Comment by NoahLiot** [comment]
Got the file. ;)
