### ISSUE TITLE
fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by overture8** [TablePlus/TablePlus#105]
Since upgrading to the latest version I can't seem to connect via SSH with a private key. Getting this error: `fe_sendauth: no password supplied`.

**Comment by huyphams** [comment]
Hi @overture8 

Since version 68, due to some conflict key with Pocket reader, We upgraded some keychain key-value.
Could you please right click on connection -> edit -> hit the test button?

Thanks,
Huy.

**Comment by overture8** [comment]
Yeah, I just did that now. The same error appears - `fe_sendauth: no password supplied`.

**Comment by huyphams** [comment]
This message comes from` PostgreSQL`, that mean the password was incorrect or `pg_hba.conf ` file was configured wrong.

This is mine:
<img width="612" alt="hyu" src="https://user-images.githubusercontent.com/3654622/32554768-70a16c06-c4cd-11e7-98a4-b52affe7d3e9.png">

**Comment by overture8** [comment]
Ah, ok - yeah, that was it. For some reason the password that I'd entered seemed to be lost when upgrading to the latest version. All good now.

**Comment by huyphams** [comment]
As I mentioned above, because of conflict keychain so I decided to migrate TablePlus to new key-value. Maybe the migrate was broken somewhere, I'm sorry for the inconvenient.

I have a plan when TablePlus reach version 70 (one build a head), I will spend more time to write Unit test to improve stability when release new build.

Huy.

**Comment by overture8** [comment]
No worries - thanks for the quick responses :)

**Comment by Fras999** [comment]
hello there I'm just using arch linux and when I want to connect my postgresDB to tablepluse it just send me this error : 

**### fe_sendauth: no password supplied**

 , and I see that when I press the test button  it just delete the password from the program . so what shall I do

**Comment by AYehia0** [comment]
> hello there I'm just using arch Linux and when I want to connect my PostgreSQL to tablepluse it just send me this error :
> 
> **### fe_sendauth: no password supplied**
> 
> , and I see that when I press the test button it just delete the password from the program . so what shall I do ![2023-01-25_10-51](https://user-images.githubusercontent.com/79044072/214508595-51345469-8af8-42ad-bc79-d2ff2d348d2a.png)

Same here :'(

**Comment by huyphams** [comment]
You should update the app to the version 216 @AYehia0

**Comment by AYehia0** [comment]
Hello, @huyphams 
Thanks for your quick response, I managed to fix the issue by following this : https://github.com/TablePlus/TablePlus-Linux/issues/61#issuecomment-633733860
