### ISSUE TITLE
Auth Mechanism for MongoBD Connections

### ISSUE THREAD

**Issue by merktassel** [TablePlus/TablePlus#1050]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MongoDB 4.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 205

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

I'm trying to connect to a MongoDB instance that has both an SSH tunnel and additional authentication information that must be entered. The form seems to missing a place to input the additional authentication information:

![What I See](https://user-images.githubusercontent.com/10404365/54441450-cd3bbc80-470a-11e9-9df8-dbe013cd1f71.jpg)

This results in an error when I attempt to interact with the database after connecting:

<img width="532" alt="Error After Connecting" src="https://user-images.githubusercontent.com/10404365/54441480-ddec3280-470a-11e9-8846-061cd5aa1020.png">

I found another issue similar to this that seems like it would've solved my issue, but for some reason I'm seeing a different connection setup window. I downloaded the build you specified in #929 (https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0) expecting this to include additional options for configuring authentication information:

<img width="612" alt="What I Expect to See" src="https://user-images.githubusercontent.com/10404365/54441527-f8261080-470a-11e9-9f7b-7f9c345fae60.png">

However, for some reason I still don't see these options. Any ideas?

**Comment by huyphams** [comment]
Hey @merktassel you can include password on connection URL: https://docs.mongodb.com/manual/reference/connection-string/
From the build 200 and above, TablePlus uses connection URL instead of input separated fields.

**Comment by merktassel** [comment]
Wow, thanks for the super quick response! I'll try this now.

**Comment by merktassel** [comment]
Yay, that worked perfectly! Thanks so much, just purchased a license.

**Comment by huyphams** [comment]
Thanks @merktassel ! please remember that TablePlus doesn't support Mongo Shell at the moment (beta) so you can not execute the query in Query Editor, and TablePlus doesn't support JSON view.
