### ISSUE TITLE
Missing existing data

### ISSUE THREAD

**Issue by esq0** [TablePlus/TablePlus#1051]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Azure (RTM)
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 205

3. The steps to reproduce this issue:
Install sample database (AdventureWorksLT) on azure sql database then connect to it using Tableplus. Table 'Product' exists but data cannot be viewed. Other tables work fine. As you can see there should be 295 rows.
<img width="1680" alt="Screenshot 2019-03-17 at 02 07 44" src="https://user-images.githubusercontent.com/25016478/54483886-c07aae00-485b-11e9-9678-7a503e70c602.png">

After running a query, you still can't see anything but 295 rows were affected
<img width="1680" alt="Screenshot 2019-03-17 at 02 21 43" src="https://user-images.githubusercontent.com/25016478/54483894-e6a04e00-485b-11e9-8a5b-96440c5d34d4.png">

<img width="1680" alt="Screenshot 2019-03-17 at 02 21 54" src="https://user-images.githubusercontent.com/25016478/54483910-0f284800-485c-11e9-9178-f759801e4a1a.png">

But, if you specify column names then result looks fine
<img width="1680" alt="Screenshot 2019-03-17 at 02 21 32" src="https://user-images.githubusercontent.com/25016478/54483920-33842480-485c-11e9-8cdd-e81e33fc4199.png">

**Comment by huyphams** [comment]
Hi @esq0 thanks for the feedback, I just created an Azure instance with sample data and here is the result:
<img width="1413" alt="Screen Shot 2019-03-17 at 9 05 20 AM" src="https://user-images.githubusercontent.com/3654622/54484197-e1f78c00-4893-11e9-8b5c-8a8910f8ac31.png">
<img width="1413" alt="Screen Shot 2019-03-17 at 9 06 14 AM" src="https://user-images.githubusercontent.com/3654622/54484200-ee7be480-4893-11e9-9e54-4cd0ce72d219.png">

**Comment by esq0** [comment]
I found a solution today. Changing a version in connection settings to DBVERSION_UNKNOWN fixed a problem (Checked all versions and it looks like 70 and 71 don't show the data correctly)

**Comment by huyphams** [comment]
We change the default to DBVERSION_74 by default and I think it solved this issue. So I'm closing it now.
Thanks for the feedback.
