### ISSUE TITLE
Restore data is not a great experience

### ISSUE THREAD

**Issue by ffxsam** [TablePlus/TablePlus#1052]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 10.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
200

![image](https://user-images.githubusercontent.com/12532733/54505546-5539e600-4906-11e9-8213-ced0d996b1bd.png)

This is not ideal. A $50 application like TablePlus should be able to handle a text-based SQL dump.

**Comment by ffxsam** [comment]
Actually, it won't even import a binary dump.

**Comment by huyphams** [comment]
Actually, I want to add this feature too but the psql will increase the size of the app a lot.

However it's not a big deal, the hardest part is how to detect the dump file is psql format. The message " input file appears..." was reported by pg_restore, not from TablePlus and I'm not sure how to handle it correctly.
Thanks for the feedback, I will keep thinking about this.

**Comment by jkohlin** [comment]
+1 😟 
Could you at least give us a hint on how to solve this?

**Comment by huyphams** [comment]
Hi @jkohlin have you tried the import feature?

**Comment by huyphams** [comment]
If you use PostgreSQL, I recommend you use the backup/restore feature. And the backup must use the --format=custom flag.

**Comment by jkohlin** [comment]
@huyphams Yes, it was my fault. I forgot to set the correct version on the inport. Thanks

**Comment by SpencerKaiser** [comment]
@huyphams I freakin LOVE TablePlus but oh man is the Backup/Restore flow just a nightmare... I've been trying for like 20 mins and have gotten unhelpful error after unhelpful error the entire time. If I was in a time crunch, this would be awful.

I've gotten several of the error from above and when I try the `Import > SQL Dump` option, this is what I get: 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/6445731/230939920-9987067a-fe6f-4d29-b44d-28c0e11bdc5c.png">

I genuinely have no idea how I can possibly use this feature; it just breaks every way I try it.......

**Comment by huyphams** [comment]
Hi @SpencerKaiser you can not import the format custom because it is the PostgreSQL compress format, TablePlus could not read it.

Please check your issue for the answer.

**Comment by drewg2009** [comment]
I am still running into issues and it's giving the following error

```
Restore database 'nova'
Restoring...
restore_pg_16.0: error: input file appears to be a text format dump. Please use psql.

Restore database completed
```

I ran backup with Postgres 16 as the version, selected the right database, and used `--format=custom`
