### ISSUE TITLE
Open anywhere in new tab

### ISSUE THREAD

**Issue by brtsos** [TablePlus/TablePlus#1053]
I love your app. Could you please add a feature to open in new tab when I select a table in Open Anywhere? Thanks :)

**Comment by huyphams** [comment]
very interesting @brtsos I will consider it.

**Comment by Klizzy** [comment]
> I love your app. Could you please add a feature to open in new tab when I select a table in Open Anywhere? Thanks :)

that's the only feature im missing in TablePlus! Im an heavy "open anywhere" user, because i already rely heavy on MacOS spotlight / alfred. Please consider it! ☺️

**Comment by Klizzy** [comment]
Please consider this feature 😕 
Thats the only thing that interrupts my workflow with this awesome Application.
I would do a PR myself if it would be open source.

**Comment by huyphams** [comment]
it's supported now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
If you hold the command, TablePlus will open it in a new tab (using open anything command + P).

**Comment by Klizzy** [comment]
Thank you very much, you’re awesome 🎉

**Comment by vesper8** [comment]
@huyphams thanks for adding support for this, however can't you add an option in the preference to set this as the default behaviour? I think this would be much better than having to hold CMD down
