### ISSUE TITLE
[Feature Request] Quick-look of JSON objects to either be alphabetical or maintain order from JSON

### ISSUE THREAD

**Issue by heathyboyj** [TablePlus/TablePlus#1055]
![Screenshot 2019-03-20 at 16 38 14](https://user-images.githubusercontent.com/20686879/54702381-a4faf600-4b2e-11e9-9bd9-6117f321d11b.png)

As with the attached screenshot, you can see that the fields of the quick-look JSON fields are not in the same order as the original JSON string, nor are they alphabetically sorted; we sometimes get large JSON objects and trying to find a given field in this view is a nightmare. I hate having to copy+paste the JSON out to a separate text file just to find a given field, defeats the point of the quick-look feature existing!

Ideally I'd prefer alphabetical ordering, although maybe it could be a settings toggle?

Thanks!

**Comment by huyphams** [comment]
Thanks, @heathyboyj for the feedback, I didn't know that it was random ordering!

**Comment by huyphams** [comment]
Hi @heathyboyj it's sorted a-z now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feedback

**Comment by heathyboyj** [comment]
You rock! 😍
