### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by brtsos** [TablePlus/TablePlus#1056]
Will you make Linux version? ;)

**Comment by dnl-jst** [comment]
Yes please! :-)

**Comment by jacurtis** [comment]
Linux has literally no competition for database GUIs. Really the only option is DBeaver. And that’s really hard to use

**Comment by dnl-jst** [comment]
Or Datagrip. But that’s hard to use too and very costly.

**Comment by arandilopez** [comment]
Suscribed! Hope to see a version soon

**Comment by mikejavier** [comment]
+1

**Comment by kpost** [comment]
+1

Not being able to use Tableplus is the only bad thing about switching from Macos to Linux, since there is no alternative. None to speak of anyway.

**Comment by MariusVB** [comment]
Be sure to look into universal Linux packages like:
https://snapcraft.io/
https://flatpak.org/

Then you will hit as many distributions and users as possible.

**Comment by ansarizafar** [comment]
Any update from core team on linux distribution?

**Comment by huyphams** [comment]
Not much, but it's not the final.
<img width="1336" alt="Screen Shot 2019-05-20 at 17 00 20" src="https://user-images.githubusercontent.com/3654622/58013451-d426e700-7b20-11e9-8f1e-f56205ae7c46.png">

**Comment by dexter0201** [comment]
Subscribed. Waiting for Linux version

**Comment by damiantoczek** [comment]
Subscribed, waiting for the linux version :)

**Comment by nerdo** [comment]
Awesome sauce. Waiting patiently as well...

**Comment by robclancy** [comment]
Wait wait.. we will finally have a good database tool on linux? I never thought I'd live to see the day.

**Comment by tdgroot** [comment]
Would just like to know whether it's going to happen or not. Linux could use a better db tool like TablePlus

**Comment by silentwarrior** [comment]
Make it happen! Is it in the works?

@huyphams is that TablePlus running on Linux?

**Comment by viceo** [comment]
TablePlus for Linux please!

**Comment by mysteren** [comment]
Subscribed, waiting for the linux version

**Comment by dcabrejas** [comment]
Yes please!

**Comment by willvincent** [comment]
Yes please please please!

There are no really _good_ gui DB clients on linux.. a bunch of half-assed things that have largely been abandoned, or the handful of klunky difficult expensive things others have mentioned.

**Comment by yves-bourgeois** [comment]
+1

**Comment by nerdo** [comment]
Ditto. Actually I'd even love to alpha/beta test it @huyphams if at all possible

**Comment by jonopeo** [comment]
+1 Would love to beta test Linux as this is currently my main driver on Windows & Mac. Looking into this for our company going forward as more are adopting Linux.

**Comment by JonathanSatterfield** [comment]
Also adding my +1 for a Linux release!

**Comment by jonopeo** [comment]
@huyphams How is this looking since the last screenshot 😃

**Comment by aymanbagabas** [comment]
+1

**Comment by PooWoox** [comment]
+1

**Comment by tiagocorrea** [comment]
People commenting _+1_:

Please don't. This flood the inbox of those who subscribe to the issue notifications. Just react clicking on the corresponding button in OP's issue message.

![image](https://user-images.githubusercontent.com/874101/62321434-02a63400-b479-11e9-97e0-efd9d8ce98ef.png)

**Comment by vesper8** [comment]
And if you're doing it so you receive notifications, please use the subscribe box at the top instead! This feature has been around for more than two years now!! Stop spamming everyone please : )

<img width="234" alt="Screen Shot 2019-08-01 at 6 10 31 PM" src="https://user-images.githubusercontent.com/816028/62330833-db0a9800-b487-11e9-9cce-d7b9f9d99067.png">

**Comment by tebuevd** [comment]
Subscribed :) Waiting for Linux

**Comment by wout** [comment]
I'd love to apply as beta tester. :smile:

**Comment by bmilesp** [comment]
+1

**Comment by ggolda** [comment]
Any updates when beta starts? 😄

**Comment by emtized** [comment]
any update?

**Comment by dammyammy** [comment]
any updates ?

**Comment by huyphams** [comment]
Update: Thank you guys I've bad news good news.
1. Bad news: I've decided to drop the Linux version above because it was built on the Electrons, which is not our goal. We want to build a native, fast, beautiful and consume less memory. Unfortunately, the Electron version only has one of the requirements - Beautiful.
2. Good news: We're working on a completely new version of TablePlus (The Next TablePlus), which is native (even in Linux), it also has a better UI/UX than the current TablePlus on macOS/Windows/iOS (better Editor with multiple carets, be able to custom item tree, support more NoSQL...). We build the new version from scratch so it will take time (maybe next 6 months).
If anyone interested in the new implement, please go to our homepage: https://tableplus.com scroll down, on the bottom right, there is a `SUBSCRIBE TO NEWS`.
We did not send any marketing emails at TablePlus and no more than 1 email per year except a critical announcement (security issue etc..).
I will close this issue for now.
Thank you!

**Comment by wout** [comment]
@huyphams That's excellent news, worth the wait. Looking forward to it.

**Comment by voku** [comment]
If someone still searching for a sql client for Linux, I am working with HeidiSQL + Wine and it's working pretty stable: https://appdb.winehq.org/appview.php?iAppId=3326 :+1:

**Comment by MariusVB** [comment]
Check out sequeler too. A very minimalistic SQL client for Linux.
https://github.com/Alecaddd/sequeler

**Comment by huyphams** [comment]
Hopefully, I can deliver a beta by the end of this month.
I also created a new repo for Linux (Please follow it to get updates and report/suggest issues, features): 
https://github.com/TablePlus/TablePlus-Linux

![welcome](https://user-images.githubusercontent.com/3654622/69009818-bb608800-092f-11ea-805e-2eab5e145d86.png)
![workspace](https://user-images.githubusercontent.com/3654622/69009819-bb608800-092f-11ea-8c38-e782b83e5367.png)

**Comment by jpike88** [comment]
Is there an email/waiting list for the beta?

**Comment by AnnoyingTechnology** [comment]
>    If anyone interested in the new implement, please go to our homepage: https://tableplus.com scroll down, at the bottom right, there is a `SUBSCRIBE TO NEWS`.

**Comment by huyphams** [comment]
We have an alpha release now, https://tableplus.com/linux/install

Please note that:
- This is an Alpha Release (not Beta yet)
- It's expected to HAVE A LOT OF BUGS
- It LACKS A LOT OF FEATURES

We will release a new update every week to make it better!

**Comment by razzmatazz** [comment]
> We have an alpha release now, https://tableplus.com/linux/install

Any plans for Fedora/RPM version?

**Comment by huyphams** [comment]
Yes, we will release for other distros, please create a request here: https://github.com/TablePlus/TablePlus-Linux

**Comment by dnl-jst** [comment]
> We have an alpha release now, https://tableplus.com/linux/install
> 
> Please note that:
> 
>     * This is an Alpha Release (not Beta yet)
> 
>     * It's expected to HAVE A LOT OF BUGS
> 
>     * It LACKS A LOT OF FEATURES
> 
> 
> We will release a new update every week to make it better!

Thank you for your work! I greatly appreciate it!

Unfortunately I can not install the package on Ubuntu 19.10:

![Screenshot from 2019-12-02 16-50-38](https://user-images.githubusercontent.com/712897/69973599-11365200-1524-11ea-9512-f05bdfb01116.png)

**Comment by huyphams** [comment]
Hi @dnl-jst please report it on the Linux repo: https://github.com/TablePlus/TablePlus-Linux/issues

**Comment by huyphams** [comment]
![Image](https://github.com/user-attachments/assets/1d362453-4cb7-4aa7-a56b-73b67313680a)
it is 260 version and the most recent is 4 Feb 2025
https://tableplus.com/blog/2020/01/changelogs-linux.html

**Comment by huyphams** [comment]
not sure where you get the info but the app imange portable self update version is coming next month too :/

**Comment by huyphams** [comment]
it is an auto redirect link @jpike88 btw, we still update that blog post everytime we release the version so if anyone actually click and see the content, they know it is up to date.

https://tableplus.com/osx/changelog

**Comment by huyphams** [comment]
The release number has nothing to do with features on other platforms because this is a native app. That means each platform has its own standalone version.

Users on different platforms have distinct behaviors and needs. We prioritize features based on what we consider important first, followed by user requests—so no request means low priority.

We understand that some users may leave without giving feedback, and we might miss some valuable input. However, choosing a native app over a bloated Electron-based cross-platform solution is a trade-off we made.

We hope you understand. If you truly like the app and need a specific feature, feel free to submit a request or email us. (In fact, we implement up to 90% of feature requests on Linux if that feature is already available on another platform.)

**Comment by huyphams** [comment]
Thank you, @voltuer, for understanding! We regularly update the Linux version, so if you want a feature, feel free to submit a request on the Linux issues page or email nick@tableplus.com
