### ISSUE TITLE
Describe schema objects in Cassandra

### ISSUE THREAD

**Issue by MightyPixel** [TablePlus/TablePlus#1058]
Hello!

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
[cqlsh 5.0.1 | Cassandra 3.0.15.2269 | DSE 5.0.14 | CQL spec 3.4.0 | Native protocol v4]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
205
3. The steps to reproduce this issue:
Create a schema with [materialized view](https://www.datastax.com/dev/blog/new-in-cassandra-3-0-materialized-views), UDF, UDT or index. Open the keyspace and the table. There is no UI elements indicating the existence of those objects. For some reason describe statements does not work: `DESCRIBE FULL SCHEMA;` returns `Query 1 ERROR: line 1:0 no viable alternative at input 'DESCRIBE' ([DESCRIBE]...)` 

Thanks :)

**Comment by MightyPixel** [comment]
@huyphams I think now we can view Cassandra materialised views with the latest TablePlus build. I think the feature request is to be able to describe objects in Cassandra in the SQL tab. For now the error is the same:
```
Query 1 ERROR: line 1:0 no viable alternative at input 'describe' ([describe]...)
```

**Comment by huyphams** [comment]
Hey @MightyPixel the `DESCRIBE` is only working on Cassandra client `cqlsh`, so there is no way to bring it to TablePlus.

**Comment by MightyPixel** [comment]
Thanks for the answer! I'll close this issue in that case :)
