### ISSUE TITLE
Cannot Backup (Postgres) with SSH tunnel and custom port

### ISSUE THREAD

**Issue by araines** [TablePlus/TablePlus#1059]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):  PostgreSQL 11.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): v2.1 (204)

3. The steps to reproduce this issue:
Connect to a database on a custom port as well as using SSH tunnel (successful).
Attempt to perform a backup
Error message:
```
Create tunneling...
Dumping...
dump_pg_11.0: [archiver (db)] connection to database "exampledb" failed: FATAL:  password authentication failed for user "exampleuser"
FATAL:  password authentication failed for user "exampleuser"

Backup database completed
```

From doing this manually from my local machine, I got the same error message when I failed to provide the port I got the same error from pg_dump.  I suspect this may be the problem.

**Comment by huyphams** [comment]
I'm not sure if was fixed or not, could you please check the latest build 233 @araines thank you so much!
