### ISSUE TITLE
Improve bug/error report

### ISSUE THREAD

**Issue by bdebever** [TablePlus/TablePlus#106]
Hi there, 

I really like your product. 

However, I have a few point to make: 
- the error is really poor, only error I could have so far is "Mysql has gone away" - while I knew I had different error: ssh, wrong username, wrong password. So it would be nice to have more information. 

- It's not really clear what is the selector at the bottom right-hand corner. Why not using it to switch db? 

I will keep fiddling with and provide more feedbacks. 

Thanks.

**Comment by huyphams** [comment]
Hi @bdebever 

`the error is really poor, only error I could have so far is "Mysql has gone away"` -> This is actually error response from MySQL Server. I will take a look on documents to see how to improve this message.

`It's not really clear what is the selector at the bottom right-hand corner. Why not using it to switch db?` -> TablePlus supports many drivers, and this dropdown is using for table namespace.
See the picture below.
<img width="1440" alt="nice" src="https://user-images.githubusercontent.com/3654622/32566495-b4bfd37e-c4ea-11e7-85a0-f85d5d940e80.png">

You can access to database listing by press `command + d` and right click for more option create/drop database.

**Comment by huyphams** [comment]
the error message will be improved in Build 83
<img width="612" alt="screen shot 2018-01-19 at 1 31 37 pm" src="https://user-images.githubusercontent.com/3654622/35137659-26e69856-fd1d-11e7-8e73-af9d04a8b3be.png">
