### ISSUE TITLE
Better Query Management

### ISSUE THREAD

**Issue by ashpreetbedi** [TablePlus/TablePlus#1060]
How do I better manage groups of queries?

I have a set of 400-500 queries I run across 2/3 databases and would like to be able to manage them better.
When I'm working in Tab 1, let's call it base queries, I would write my queries and be able to save them locally on disk as an .sql file. This is currently possible, thank you.

But, let's say I restart the client, I have to open the queries and then rename the tab. Is there a way to better manage different query files natively?

Ideally, I would be able to create Groups in my favorites tab and then have query documents in there instead of having single queries which is currently the case.

With 400-500 queries, I will have to save 400-500 queries as favorites, is there a way to manage an entire .sql document with a lot of queries as a favorite?

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 1.2 (182)

3. The steps to reproduce this issue: Not an issue, but question + enhancement

**Comment by huyphams** [comment]
Hi @ashpreetbedi please upgrade to build 204 (the latest build).
From build 204.
1. You will be able to add a folder/git repo to the Favorites tab.
2. The favorite will autosave during editing. You can turn off autosave and save it manually.
<img width="1458" alt="Screen Shot 2019-03-23 at 7 48 13 AM" src="https://user-images.githubusercontent.com/3654622/54859461-07771080-4d40-11e9-954d-80ac72a53c83.png">

**Comment by ashpreetbedi** [comment]
Fantastic, thank you @huyphams 
Another question, I've added the folder which contains my sql files, but whenever I double click on a file, it opens the file in another Tab. Eg:

![image](https://user-images.githubusercontent.com/22579644/54869599-4dd86980-4d58-11e9-83e7-41221d52c026.png)

Is there a way such that when i double click the query, it opens the already open tab - instead of opening a new one. In the example image above, this would mean when I click Base Queries, it doesn't open a new tab but the already open tab ?

**Comment by huyphams** [comment]
It should be fixed now!
