### ISSUE TITLE
[Feature Request] Opened connections are hard to distinguish because only DB names displayed 

### ISSUE THREAD

**Issue by sunkaiqin** [TablePlus/TablePlus#1061]
If you work with many cloud Databases in different regions, after you open these connections, it really hard to tell which database to switch. See the details in the picture below: 
![image](https://user-images.githubusercontent.com/24231989/54850870-b3781780-4cbe-11e9-9a70-7d9e17424129.png)

Although we could hover over to show the tooltip but it is slow and not intrinsic.

Could you please show more info on that connection: like group, connection name and db name?

**Comment by nickcabral** [comment]
I've run into the same issue. This would be a great improvement. Keep up the great work!

**Comment by plweil** [comment]
I would add that the text in this column is so tiny that it's virtually unreadable. And the column is too narrow, which also hurts readability. It needs to be wider or adjustable to accommodate connection/db names. Ironically, the tooltips are a lot more readable than what is actually displayed on the screen.

**Comment by nickcabral** [comment]
I'm not sure how long the feature has been there, but I realized that you can click the gear icon at the bottom of the list and change from displaying DB name to Connection Name. Much easier to use with that configuration.
![image](https://user-images.githubusercontent.com/9586778/63281923-f7217e00-c26a-11e9-96bb-1c475d49acd8.png)
