### ISSUE TITLE
Allow copy-paste a row to quickly insert a new row

### ISSUE THREAD

**Issue by yanckst** [TablePlus/TablePlus#1062]
# ℹ️ This is a feature request

### My question :

I would like to know if it would be possible to copy-paste a row to quickly insert a row.

### The context :
Run a select query, pick one row in the results and hit copy-paste shortcut keyboard (CTRL + C, CTRL + V) to quickly and a new row in "draft" mode. When you are done, just clicking clicking a save button or CTRL + S to add this "draft" row in the database.

### My purpose :
Being more productive to add new rows with current data. Sometimes I just want to change few columns values to have a similar data context. 

### Alternative :
I know I can Right-click and select "Copy as SQL Insert". It's working fine. You copy the query in the editor and execute it, but I'm not productive with this. 

![image](https://user-images.githubusercontent.com/30554401/54866535-655d2580-4d4b-11e9-9fd3-ac4fa67e77bb.png)

### My problem : 
I would like, if possible, to get rid of this. Just hitting copy paste shortcut (CTRL + C, CTRL + V) to quickly execute an insert, but if you copy and paste, it copies only the text content.

### Other Software : 
I know SQL Workbench has this feature. It copies the row and you can edit the row and hit save to save the new query in the database. 

### Specs : 
1. Which driver are you using and version of it ( MySQL 8.X):

![image](https://user-images.githubusercontent.com/30554401/54866502-dc45ee80-4d4a-11e9-8766-d4c4996858d9.png)

2. Which TablePlus build number are you using (the number on the welcome screen, build 204):

![image](https://user-images.githubusercontent.com/30554401/54866511-fb448080-4d4a-11e9-86fa-85e7459a939b.png)

3. The steps to reproduce this issue:

- Create a select query
- Take one row in the result
- Copy the row (CTRL + C)
- Paste the row (CTRL + V)

**Comment by huyphams** [comment]
Thanks, @yanckst for the suggestion.
Actually, you can copy/paste (Command + C and Command + V) rows directly in the table data, but it was disabled in the query result, let me see if I can re-enable it for the Query Result.

You can also use Command + D (Duplicate Row) it is a combine of command + C and Command + V at the same time.

![2019-03-23 20 55 52](https://user-images.githubusercontent.com/3654622/54867004-13012080-4dae-11e9-8251-a457f8efbbb3.gif)

**Comment by yanckst** [comment]
@huyphams Nice!! It would be very appreciated if you can enabled it for Query Results 😀

**Comment by huyphams** [comment]
I enabled it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Have fun!

**Comment by yanckst** [comment]
@huyphams Is it possible to update the source code for having the ability to update the software itself?

![image](https://user-images.githubusercontent.com/30554401/54951673-a192b080-4f1a-11e9-9446-34df305e2556.png)

I have few installation and it will be easier if I have the option. Thanks!

**Comment by huyphams** [comment]
It has self-update already. We release a pre-release every week (if you stick on Receive Beta Update in preferences) and 1 official every month.

**Comment by yanckst** [comment]
Okay Thanks! 👍

**Comment by huyphams** [comment]
Hi @yanckst I released it on the build 209, you can check the beta update or download it here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks
