### ISSUE TITLE
Toggle comment has surprising behaviour on multi-line selections containing comments

### ISSUE THREAD

**Issue by KaptajnKold** [TablePlus/TablePlus#1063]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Oracle v.??

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 205

3. The steps to reproduce this issue:

  * Write a multi-line query with one comment.

E.g.

    select *
    from foo
      -- Only those foo that are not FUBAR
      where foo.fubar is null

  * Select all
  * Toggle comment

Expected result:
---
    -- select *
    -- from foo
    --  -- Only those foo that are not FUBAR
    --  where foo.fubar is null

Actual result:
---
    select *
    from foo
      Only those foo that are not FUBAR
      where foo.fubar is null

**Comment by huyphams** [comment]
Hi @KaptajnKold 
I fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
thank you for the feedback!

**Comment by huyphams** [comment]
it's released on the beta build 209. Thanks.
