### ISSUE TITLE
Random column sorting after search in table structure view

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1064]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

207

3. The steps to reproduce this issue:

1. open a table with multiple columns, that share same fragment in their name
2. search columns in that table
3. note, that columns shown as search result aren't sorted according to their order

Before search (note column order):
![2019-03-26_1711](https://user-images.githubusercontent.com/1277526/55008898-66f84900-4fea-11e9-9dd7-6d423d72c2f2.png)

After search (note column order):
![2019-03-26_1712](https://user-images.githubusercontent.com/1277526/55008924-6f508400-4fea-11e9-998b-fdd97447d203.png)

**Comment by huyphams** [comment]
I think this issue is fixed on the build 222, let me know if you're still seeing it.

**Comment by aik099** [comment]
Unfortunately the issue is still there in 224 build.

**Comment by huyphams** [comment]
ah, it's expected behavior, the result is not ordered by #, it's ordered by Fuzzy score (which is used all over the app).

**Comment by aik099** [comment]
Wasn't aware of it. Then it's no bug.
