### ISSUE TITLE
CMD-ALT+arrow for navigating between open tables/databases

### ISSUE THREAD

**Issue by vesper8** [TablePlus/TablePlus#1065]
in Chrome, in Sequel Pro, in VSCode, and in lots of other software you can use the CMD-ALT (or CTRL-ALT I believe in WIndows) shortcut to switch between open tables by using the left and right arrow

I don't know if this is already possible through another shortcut.. I see a keymap is supposed to be due any day now which is great.. I think this type of keyboard navigation is crucial and kind of an 'expected' functionality at this point for dev programs. Hope to see it added or clarified soon! Thanks!!

**Comment by vesper8** [comment]
also I saw you mentioned in another thread that "90% of the times, the user only open 1 database". I don't know if you're collecting this date from usage metrics of your app or just an assumption, hopefully the first even though I don't remember agreeing to share this type of data. But I am one of those person that opens many tables from many databases. I don't know how much I am a fan of not being able to have two tabs opened of two tables on two different databases side-by-side.. I would like to have an option to "open all tables in same window" sometime in the future

But for now, at least give me a way to navigate through the opened databases with a keyboard shortcut. Actually the CMD-ALT shortcut would be perfect for this. CMD-ALT left/right for navigating between tabs of current database, and CMD-ALT up/down for navigating between currently opened databases.. that would be perfect!

Thanks!!

**Comment by huyphams** [comment]
Hi @vesper8 the default shortcut to navigate between Windows on macOS is: Control + Tab (it works for all macOS apps, which do not override the default shortcut.)
`I don't know if you're collecting this date from usage metrics of your app or just an assumption, hopefully the first even though I don't remember agreeing to share this type of data. ` => We stop tracking those metrics, and now only crash is tracked. You can out of tracking in the preferences, we respect user privacy and will not include any personal information.

**Comment by huyphams** [comment]
And you can also use the Open Anything to navigate between database.

**Comment by vesper8** [comment]
the 'open anything' is viable but it's not as quick as using a keyboard shortcut specially with longer database names or when you have many database names that begin with the same prefix such as in my case

I hope you consider adding db navigation as a key mappable action

I just tried ctrl-tab (I'm on a Mac) as well as every combination with -tab (ctrl, alt, fn, cmd, shift) and none of them cause navigation to occur between open tables

I'm pretty comfortable in saying that on Mac the default for navigating easily between tabs is cmd-alt as I mentioned above. This is how it works in Visual Studio Code (the most popular editor as of 2019) and in Google Chrome. You hold CMD-ALT and then use the left/right arrows to navigate to the tabs on the left or right. This is very convenient, much more convenient then having to do something like ctrl-tab or ctrl-shift-tab to go backwards (this doesn't work on mac anyway as I just tested)

I hope you can add this basic but crucial shortcut with the arrow keys.

Ideally, nearly everything should be mappable to a keyboard shortcut, including all context menu actions that are not currently tied to shortcuts.

Cheers!

**Comment by huyphams** [comment]
If you want to navigate between tables, you can use Command + [ and ], the shortcut Control + Tab using for navigating between Windows (databases).

<img width="1108" alt="Screen Shot 2019-03-27 at 10 20 27 AM" src="https://user-images.githubusercontent.com/3654622/55048230-0a446f00-507a-11e9-982f-9a3346ea2298.png">

I'm working mappable shortcut, so the user can change their favorite shortcut keys.

**Comment by huyphams** [comment]
Hey @vesper8 
I'm working on the custom shortcut features, now you can change the Next/Previous shortcut in the Preferences. You can download it here:

https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

I will add more custom shortcut in the upcoming release.

**Comment by huyphams** [comment]
the build 209 has been released (beta channel): https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
So I will close this issue, let me know if there is anything left.
