### ISSUE TITLE
Tab labels in Preferences not clickable

### ISSUE THREAD

**Issue by perifer** [TablePlus/TablePlus#1067]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7.24

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 

Version 2.1 (204)

3. The steps to reproduce this issue:

On OS X, open Preferences and click one of the tabs labels. Nothing happens. The clickable area should also include the labels (as on other Mac software).

<img width="540" alt="Screenshot 2019-03-27 at 07 53 32" src="https://user-images.githubusercontent.com/34488/55056336-2e965080-5066-11e9-894c-0b0aad459eb2.png">

**Comment by huyphams** [comment]
Hi @perifer thanks, I fixed it on the build 209: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
