### ISSUE TITLE
[Enhancement] Pasteable / Saveable Backup Options

### ISSUE THREAD

**Issue by mattcdavis1** [TablePlus/TablePlus#1068]
Currently, when running a backup there is an "Add Option" area on the right with a limited set of options. It would be nice to be able to edit this area more freely and save / share these settings.  

For example, a given database that i interact with has about 20 tables that i typically want to skip via `--ignore-table`.  There's not really a way to accomplish this now aside from using the export functionality and selecting each table that i want to export.

**Comment by huyphams** [comment]
Actually, you can copy and paste the text directly into the options field, have you tried it?
<img width="213" alt="Screen Shot 2019-03-28 at 10 15 36 PM" src="https://user-images.githubusercontent.com/3654622/55169254-06623b00-51a7-11e9-800b-5f5735ba33d9.png">

**Comment by mattcdavis1** [comment]
ahh - yeah i did try and it didn't seem editable because when i clicked in the options area and pressed "Enter" to create a new line it selected the existing items rather than creating a new line.  I see now that it is possible to enter text in this area now.  It would still be nice to associate settings with databases though.

**Comment by huyphams** [comment]
TablePlus now remember the last used backup options. it will be available in the next release!
