### ISSUE TITLE
[Feedback Build 209]

### ISSUE THREAD

**Issue by vesper8** [TablePlus/TablePlus#1069]
Hey hey! First of all.. I think it would be a cool idea to have a new feedback thread like this one created every time a new build is pushed. What might also be a good idea is to have a way to send feedback directly through the app.

I'm really loving the new keymap features. I was able to set the Select Next Tab / Previous Tab shortcuts to exactly what I wanted (CMD-ALT left/right)

A small request here.. when you are on the left-most tab and try to go left again.. it just blocks (does nothing) but it would be nice if you could cycle around and go to the right-most tab instead. That's how it works in Chrome/VScode. So you can go left to infinity when more than one tab is open. Small thing but I find it very useful

I also mapped the 'Select Next/Previous Workspace' to CMD-ALT up/down arrow. To my delight this does exactly what I was hoping.. it lets you cycle between opened databases in the current workspace

So those should remain there but be renamed to 'Select Next/Previous Database'

I opened a 2nd workspace (using the New Workspace) menu item, and it doesn't let you switch between workspaces actually.. but I'm glad it works for cycling through databases.

I observed some bugs when remapping my keys. Let's say you remap a key to CMD-ALT UP, then remap another key to CMD-ALT DOWN, then you realize you want to flip those two.. so first you remap the first one to a temporary key "CMD UP" for example. Then if you try to remap the other key, it will still complain that this shortcut is "already in use" even though it isn't anymore. You have to close the preference screen completely and reopen it before it will work.

Other minor nitpicks and requests. The 'Show All Tabs' menu item should be renamed to 'Show All Databases' since that's what it does. I have 6 databases opened, one of which has 4 tabs opened, when I click on 'Show All Tabs' all it does is show me 6 windows with my 6 databases.

The 'open recent' menu item never gets populated with anything.

I would like to be able to 'save my session' or 'save my workspace' so that when I close/reopen Tableplus all my opened databases and opened tables are opened at once. Right now I have to reopen everything every time.

The 'save as' menu item is always greyed out. I would expect it would let me 'save workspace as' or something.. not sure what it's for. I hope you add 'save workspace as' or 'save session as' soon :)

I would also like to have multiple saved workspaces/sessions for different projects

One other small unrelated thing, when I click on a cell inside a row that is a text cell, I would like a modal to open that shows me the full content. It could be a text cell containing a large blurb of text, or in my case, containing json. Currently it only shows me the first 2 lines and it is very hard to visualize/edit. Bonus points.. the modal could recognize that this is json and pretty-print it.

Thanks!

**Comment by vesper8** [comment]
small addendum, i'm not sure how to reproduce yet, but i've had it happen twice so far where using the back/previous workspace (database) hotkeys will correctly switch database, going up or down the databases in the right order, but the white highlight that's on the active database does not follow, it stays stuck on the same database

**Comment by huyphams** [comment]
Hi @vesper8 thanks for the feedback. I've fixed several issues after release the build 209:
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 
1. Fixed a bug where the tab is not selected after switching.
2. Switch database now "cycle around" for macOS 10.11.

-  "One other small unrelated thing, when I click on a cell inside a row that is a text cell, I would like a modal to open that shows me the full content"
You can right click and select `quick look` or simply middle click on the cell.
- save my session => We already have that feature in backlog.
- `Show All Tabs` => `Show All Database` unfortunately, this menu is generated by macOS and it not easy to override, but let me try.

**Comment by vesper8** [comment]
i've noticed one big woe for someone that uses cmd-p a lot but also has to work with a lot of different databases. each of my projects count 3-6 databases with one project having over 50!

right now cmd-P will let you search within a list of all database names, and only the database tables of the currently highlighted database

that search really needs to extend to all of the tables of all the databases.. i'm sure that's an easy one to fix.. and for me it would be a huge timesaver

**Comment by vesper8** [comment]
`You can right click and select quick look or simply middle click on the cell.`

oh very nice! didn't know.. but i have two comments about that one that i hope you consider.. first.. i don't have a middle button.. like probably half of the users I'm on a laptop with a trusty trackpad.. i would personally like it if double-clicking on a text field, especially one containing json, defaulted to opening the modal. have to right-click and use the mouse to get there is less than ideal. An option for this would be cool. I think you could add a "ux preferences" panel in the settings for all these little "it's a matter of taste" preferences

it would also work well if it defaulted to the modal if you cmd/ctrl click the field

and another one.. and this one is a big one please! I just opened a json field with 3 depths and about 50 properties, I was reallly missing a "expand all / collapse all" button.. well just expand really. Actually I think it would be very desirable to just default to all fields expanded.. don't you agree? usually when you open a json field you want to see everything

and also I think this json editor needs a lot more loving.. I mean.. I would have much preferred being able to edit the values straight inside the json tree (left part of json modal).. like I can in an app like Studio 3T, and many other json editors allow you to do. Having to fill out a form to the right.. if you want to edit multiple fields, makes it much slower

also.. right now this json editor is very hard to use.. i can't add new nodes or remove them.. i can't  edit keys, only values.. and I can't do it with the keyboard alone

especially if you're working on something like this for MongoDB.. the json tree editor will need to be a lot friendlier, again I refer to my favourite one at the moment which is Studio 3T's way.

also I don't like that the modal becomes hidden under if I alt-tab to another window and then come back to TablePlus. If a modal was on top then I think it should stay on top when I come back.

And thank you for very quickly adding/fixing :) that's always a joy to watch!

**Comment by huyphams** [comment]
Quick response: except the JSON editor, you can use the right sidebar (toggle by pressing space) to edit the content of a row/cell. I'm gonna go now, I will come back to the office in the afternoon.
Thank you a lot for the feedback 👍

**Comment by vesper8** [comment]
so can you tell i have to edit json as part of my day right now? ;)

<img width="353" alt="Screen Shot 2019-03-29 at 2 53 50 AM" src="https://user-images.githubusercontent.com/816028/55201965-0aee1a00-51ce-11e9-89ce-132a43136c64.png">

it would be nice if:

the text type cells on the row detail pane were resizable.. or if they were just made a little bigger by default

but even better.. if you could simply auto pretty-print the json in a scrollable fields in the row detail pane, and then i was able to edit it as plain text but indented as json.. just like when editing a package.json file really, then that would be perfect!

there really is no need to validate that json is json.. that's our responsibility ultimately.. for mongo it may be necessary to validate the syntax.. but when editing a text field in sql.. you can leave that on us.. just make it easy to view and edit the json as plaintext and that would be my preference personally, i'm sure a lot of devs would agree.. no need for that robust editor you've come up with in the quick view IMO

btw as a super quick fix, I think the "quick look" should be the first item in the right-click menu

**Comment by huyphams** [comment]
Hi @vesper8 

I've improved JSON print on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 (the 3rd improvement).

1. TablePlus will remember the right sidebar size so you just need to make it bigger.
2. You can toggle the right sidebar by pressing space.
3. You can pretty print the JSON by clicking the dropdown button here, it can also validate your JSON:
<img width="505" alt="Screen Shot 2019-04-09 at 10 08 28 AM" src="https://user-images.githubusercontent.com/3654622/55770680-6e6e2680-5aaf-11e9-9550-f51ff2515d84.png">

**Comment by vesper8** [comment]
very nice : )

I like that you are reducing the amount of steps needed.

I just tried it out and I have two comments.

First, I would like the ability to just pretty-print it by default. When I'm viewing JSON, I always want to see it like this.

Second, I noticed that when you pretty-print it, it asks me to confirm the modification, and after I save it, it actually saves all the spaces in the field. So it's not only pretty-printing it but it's also adding all the spaces and saving it like that in the database table. I'm not sure if this could cause problems, it certainly makes the field content bigger however.

The idea is to only display it "pretty" to make it easier to visualize and edit, but it shouldn't modify the field data (if you make no change) and if you do make a change, it should trim the whitespace again and save it as normal json, not json full of extra spaces.

**Comment by vesper8** [comment]
On a side note, I tried to use MongoDB again yesterday and I see that it's still not possible to sort columns. Even if I click on a column that contains just an integer, clicking appears to do something (it actually changes the column ordering which seems to be a bug) but it doesn't sort the results. Hope that can be added soon.. along with hopefully other things basic things like filtering/search : )

Keep up the good work!

**Comment by huyphams** [comment]
Hey @vesper8 TablePlus now supports:
1. Sorted key in the table view mode.
2. Added support sort column.
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!

**Comment by vesper8** [comment]
Hey @huyphams I was playing around some more with the JSON fields yesterday and found something else which I wish was different.

Right now if I adjust a json field to be 'pretty printed' in the sidebar, it only affects it for that one row, when I use the up/down arrows to view other rows, I have to pretty-print again and again.. as I said above I wish the pretty print was the default (or an option to set this as the default) view. But at least make it so that if I set it, I set it for the whole table, not just row-by-row

And as I mentioned above, pretty-print should only affect the visualization of the json, it shouldn't actually make changes to the contents of the cell

**Comment by vesper8** [comment]
Just tested out the new column sorting ability on MongoDB and cool! it works!

One comment though.. right now when you click a column header, it makes the pane jump back to the far left. This is very annoying when you were scrolled far to the right before clicking. It would be much preferable if clicking a column did not reset the view and the columns just stayed where they are.

**Comment by vesper8** [comment]
is the ability to save / restore session coming soon @huyphams ?

kind of annoying losing all my tabs and tables every time I update the client which is 1-2x per week

**Comment by huyphams** [comment]
Move this this issue: https://github.com/TablePlus/TablePlus/issues/1260
