### ISSUE TITLE
Shortcut changes not saved

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1071]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

209

3. The steps to reproduce this issue:

**Scenario 1:**

1. open settings dialog
2. go to `Keymap` tab
3. press `X` icon next to both `Select Next workspace` and `Select Previous Workspace` entries
4. close settings dialog
5. open settings dialog
6. go to `Keymap` tab
7. notice, that shortcuts are displayed again as if they weren't removed (bug, because I've just unassociated it)

**Scenario 2:**

1. open settings dialog
2. go to `Keymap` tab
3. press `X` icon next to both `Select Next workspace` and `Select Previous Workspace` entries
4. attempt to specify `Command+Shift+]` shortcut (was previously used for `Select Next Workspace`) for `Select Next Pane`
5. see the error message, that shortcut is already in use for `Select Next Workspace` (bug, because I've just unassociated it)

**Comment by huyphams** [comment]
it's fixed now.

**Comment by aik099** [comment]
The `Scenario 2` is fixed, but `Scenario 1` isn't fixed (removed shortcuts reappear after app restart):

![2019-04-03_2127](https://user-images.githubusercontent.com/1277526/55503459-5fbee400-5657-11e9-9425-41dce77f40ce.png)

I'm really not sure which action would be invoked now, when they both have same shortcut.
