### ISSUE TITLE
Allow for reordering of database connections/tabs

### ISSUE THREAD

**Issue by Numline1** [TablePlus/TablePlus#1072]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
204
3. The steps to reproduce this issue:
Open multiple connections (connections to multiple databases)
There's a bar on the left with all open connections
Users should be able to reorder these using drag and drop

![image](https://user-images.githubusercontent.com/12192684/55235430-d1e59200-522d-11e9-9f38-0f99d3f98a0d.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by iamtheyammer** [comment]
I'd love to see this.

**Comment by Kerfred** [comment]
Idem. It would be a good enhancement.

**Comment by n8udd** [comment]
This would be _so_ useful. Also custom colouring of the background, as well as the outline of the db would be useful!

**Comment by stiang** [comment]
@huyphams Are there any plans to implement connection reordering in the near-ish future? I’m already a paying customer, but I would like to see an official statement on this issue before truly committing to TablePlus as my main database tool on Mac, long-term.

**Comment by seliquity** [comment]
I would also love to say this, it's a pain point having to close and re-open to achieve the same thing.

**Comment by Dmitriy-teamcmp** [comment]
Me too.

**Comment by huyphams** [comment]
Please wait for the next update

![ezgif-1-7643e0b74a](https://user-images.githubusercontent.com/3654622/217159877-1c7ac78b-c144-4d6e-bdc9-91a0dff323e5.gif)
