### ISSUE TITLE
Commands out of sync; you can't run this command now.

### ISSUE THREAD

**Issue by kraken22** [TablePlus/TablePlus#1074]
Every time I try to execute a query / save modified data I get the error:
```
Commands out of sync; you can't run this command now
All changes were reverted (DDL statements can't be reverted).
```

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`Server version: 5.5.5-10.3.13-MariaDB-1:10.3.13+maria~bionic-log mariadb.org binary distribution`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`build 204`

3. The steps to reproduce this issue:
Modify / Create anything in a database 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @kraken22 thanks for the feedback but unfortunately, I can't reproduce the issue with your information.

I know it is an issue and some users have experienced but I tried everything and can't reproduce the issue, can you help me with a little bit more detail?  How to reproduce the issue?

- Does it happen every time?
- Does It happen after making a connection or after doing something?

**Comment by kraken22** [comment]
It happens every time I try to save my local changes (ie: created a new table / added data) with the remote database. I can connect to the database fine. Could it be because I am using mariadb on the backend. I can connect to the remote database and make changes from the terminal without errors. It Does not happen after connecting but after doing something

**Comment by huyphams** [comment]
I've installed the MariaDB 5.5 but still can't reproduce the issue.  Is it a local connection or server? could you make a gif (the best gif maker is Gifox https://gifox.io)
![2019-03-30 14 33 04](https://user-images.githubusercontent.com/3654622/55273082-c27f4b00-52f8-11e9-913f-31122fcd1f6f.gif)

**Comment by kraken22** [comment]
It is a remote connection. And i am on MariaDB 10.3.13. Hope it works. Thanks for the help
![2019-03-30 18 42 10](https://user-images.githubusercontent.com/24929532/55273159-9b864080-531b-11e9-82cf-5bbf59e80837.gif)

**Comment by huyphams** [comment]
I installed the MariaDB 10.3 but still the same, weird.

TablePlus will generate this statement:
```
BEGIN;
UPDATE `db_name`.`table_name` SET `email` = 'asdasd', `password` = 'dd' WHERE `id` = '1';
COMMIT;
```

Could you please do the follow steps and let me know if there is any error?
1. Open Connection but don't do anything.
2. Open SQL Editor (Command + Return or click the SQL Button button on the top left).
3. Run one by one:

```
BEGIN;
UPDATE `db_name`.`table_name` SET `email` = 'asdasd', `password` = 'dd' WHERE `id` = '1';
COMMIT;
```

**Comment by kraken22** [comment]
Yes! That works. I ran the query: 
```
INSERT INTO `db_name`.`table_name`(`email`,`password`) VALUES ('asdasd', 'asdasd'); 
```
It successfully updated the table
However when I try to do it through the GUI it still throws the same error. I did not execute the `BEGIN;` and `COMMIT;` since i only let me execute 1 query at a time.

**Comment by huyphams** [comment]
Yep, please try run it `one by one`, I meant it. I'm confused because TablePlus will run 3 statements one by one and I'm not sure which one will cause the error.

**Comment by kraken22** [comment]
Yes. There is an error on the `BEGIN;`  query. 
```
Query 1 ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
```

**Comment by huyphams** [comment]
Interesting, made sense, how about replace BEGIN; with: START TRANSACTION;
Thank you so much, I don't think that I can fix this bug without you 👍

**Comment by kraken22** [comment]
Yes. That works well. I was just looking at begin in MariaDB: 
[https://mariadb.com/kb/en/library/begin-end/](https://mariadb.com/kb/en/library/begin-end/)
That could help??

**Comment by huyphams** [comment]
that `begin` is using for block query, TablePlus uses BEGIN; (it has semicolon) to begin a transaction, I followed this blog: https://mariadb.com/kb/en/library/start-transaction/
But it looks like that I had better use the `START TRANSACTION;`
I updated the build and change BEGIN; to START TRANSACTION; 
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Could you please it a try, thanks!

**Comment by kraken22** [comment]
It works now. Thanks for your help. Can I use that build normally or is it a dev build and i should wait for an update.

**Comment by huyphams** [comment]
You can keep using it, it's a hotfix build, and can self-update when we release the official build.

**Comment by kraken22** [comment]
great thanks
