### ISSUE TITLE
Support Composite Primay Keys and Composite Foreign Keys

### ISSUE THREAD

**Issue by rvrabbit** [TablePlus/TablePlus#1076]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

9.6.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 2.1 (204)

3. The steps to reproduce this issue:

Create tables per below.

Observe that in the "Structure" view, "column_name" will appear as a string with spaces truncated, and with `","` in between names of the columns of the composite key.

Observe that in the "Structure" view, "Foreign Key" will appear as "Empty" for composite foreign keys.

Script to create example tables:

```sql
CREATE TABLE "Desk Drawers" (
	"Drawer Position" smallint NOT NULL,
	"Drawer Height" smallint NOT NULL
) ;

ALTER TABLE ONLY "Desk Drawers"
ADD CONSTRAINT "Desk Drawers_pkey" PRIMARY KEY ("Drawer Position")
;

CREATE TABLE "Pens" (
	"Manufacturer" text NOT NULL,
	"Color" text NOT NULL,
	"Ink Remaining" decimal NOT NULL
) ;

ALTER TABLE ONLY "Pens"
ADD CONSTRAINT "Pens_pkey" PRIMARY KEY ("Manufacturer", "Color")
;

CREATE TABLE "Drawer Contents" (
	"Drawer Position" smallint NOT NULL,
	"Manufacturer" text NOT NULL,
	"Color" text NOT NULL
)
;

ALTER TABLE ONLY "Drawer Contents"
ADD CONSTRAINT "Drawer Contents_pkey" PRIMARY KEY (
	"Drawer Position",
	"Manufacturer",
	"Color"
)
;

ALTER TABLE ONLY "Drawer Contents"
ADD CONSTRAINT "Drawer Contents_Desk Drawers_fkey"
FOREIGN KEY ("Drawer Position")
REFERENCES "Desk Drawers"("Drawer Position")
;

ALTER TABLE ONLY "Drawer Contents"
ADD CONSTRAINT "Drawer Contents_Pens_fkey"
FOREIGN KEY ("Manufacturer", "Color")
REFERENCES "Pens"("Manufacturer", "Color")
;
```

**Comment by huyphams** [comment]
it's already supported but it looks like that we have a bug here, thank you for the feedback let me fix it.

**Comment by huyphams** [comment]
Hi @rvrabbit I fixed the bug: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Now it should work correctly.
Thank you for the feedback.

**Comment by rvrabbit** [comment]
Excellent!  Thank you!
