### ISSUE TITLE
Changelog text is not readable in darkmode

### ISSUE THREAD

**Issue by arbus** [TablePlus/TablePlus#1080]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

NA

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 210

3. The steps to reproduce this issue:

Open tableplus after an update and the changelog window that opens up is unreadable.

![Screenshot 2019-04-04 at 12 26 04 PM](https://user-images.githubusercontent.com/2200532/55529680-29c04500-56d5-11e9-8044-33c897bd24bc.png)

**Comment by huyphams** [comment]
Hi @arbus thanks for the feedback, unfortunately, this issue has been reported server times and we can't do anything.
This came from Setapp native library and our team can't modify that component. I've feedback to Setapp team some times but it seems that they can't fix it too, let me try one more time

**Comment by arbus** [comment]
No worries, thank you for trying!
