### ISSUE TITLE
When the table structure is edited and the sql statement is generated, when the default value of the column of the bit(1) type is b'0', the syntax will have extra double quotes.

### ISSUE THREAD

**Issue by fengyunhe** [TablePlus/TablePlus#1082]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
210
3. The steps to reproduce this issue:
When the table structure is edited and the sql statement is generated, when the default value of the column of the bit(1) type is b'0', the syntax will have extra double quotes.

![image](https://user-images.githubusercontent.com/15814939/55535525-12d81d80-56ea-11e9-942d-603c4c37c58a.png)
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @fengyunhe, please use the advanced popup (Hold option + Left Click or click the brace icon):
<img width="376" alt="Screen Shot 2019-04-04 at 2 00 49 PM" src="https://user-images.githubusercontent.com/3654622/55535691-14054c80-56e2-11e9-8057-d6b1ac4450f5.png">

**Comment by fengyunhe** [comment]
@huyphams 
I mean, a syntax error occurs when you modify a column that already has a default value of b’0’ and perform  save.

**Comment by fengyunhe** [comment]
![image](https://user-images.githubusercontent.com/15814939/55567712-cfed6880-5730-11e9-89ed-d4812eeff592.png)

**Comment by huyphams** [comment]
I see, sorry @fengyunhe because of the misunderstanding. I will fix it.

**Comment by fengyunhe** [comment]
Thank you for your hard work.

**Comment by huyphams** [comment]
I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank @fengyunhe for the feedback!
