### ISSUE TITLE
Crash on backup on MacOS Mojave after last update (2.2 - 210)

### ISSUE THREAD

**Issue by david-mdmsystems** [TablePlus/TablePlus#1083]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
210

3. The steps to reproduce this issue:
Make a backup of a database and select "compress file using GZip".
It seems to crash just before start to compress the file.

**Comment by huyphams** [comment]
Hi @david-mdmsystems thanks, I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I'm going to release a patch in a few hours.
Thanks.
