### ISSUE TITLE
Incorrect UPDATE sql for Multi-column indexes in SQLite

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1085]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

211

3. The steps to reproduce this issue:

Execute these SQLs on a new database:

```sql
CREATE TABLE "Events" (
	 "EventDate" integer NOT NULL,
	 "Category" text NOT NULL,
	 "Comment" text NOT NULL,
	 "Duration" integer NOT NULL,
	 "Balance" integer,
	PRIMARY KEY("EventDate","Category")
);

INSERT INTO "Events" ("EventDate", "Category", "Comment", "Duration", "Balance") VALUES ('1553551200', 'working', 'comment 1', '-214', '-214'),
('1553551200', 'qa', 'comment 2', '-60', '0');
```

Attempt to change value of "Comment" field for one of the rows.

The SQL, that is built looks like this:

```sql
UPDATE "Events" SET "Comment" = 'new comment' WHERE "EventDate" = '1554152400';
```

Since primary key for a table has both "EventDate" and "Category" in it, but update SQL, that TablePlus builds has only "EventDate" in it the entered comment is set for 2 records instead of only one, that I've specified.

**Comment by aik099** [comment]
Also for unknown reasons, when I filter by '1554152400' value for 'EventDate' column I'm only seeing 1 of 2 records.

**Comment by huyphams** [comment]
Thanks @aik099 I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Keep up the great feedback!

**Comment by aik099** [comment]
You've fixed all 3 issues?

**Comment by huyphams** [comment]
Yep, all 3 features.
1. TablePlus fails to load the primary key which results in generating the wrong update statement.
2. I can't reproduce the issue, the EventDate value should be 1553551200 instead of 1554152400.
3. the same, the EventDate value should be 1553551200 instead of 1554152400

**Comment by aik099** [comment]
Thank you.
