### ISSUE TITLE
Feature Request: Support connecting to MySQL over SSH via remote's socket

### ISSUE THREAD

**Issue by ernstae** [TablePlus/TablePlus#1087]
# quick summary

I have a use case where remote MySQL servers use the `auth_socket` plugin for system users.  Assuming they connect through the mysqld socket on the remote host, they should be authenticated without a password.  However, in TablePlus, when you select "OVER SSH" as an option, the "use socket" checkbox disables.  

Do you have the possibility of using the socket on a remote host via SSH (or any workarounds?)

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x and MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.2 212

3. The steps to reproduce this issue:
Attempt to connect to a MySQL server via SSH and the option to connect via socket disappears and tcp appears to be the only connection method

**Comment by huyphams** [comment]
There is a workaround: https://serverfault.com/questions/127794/forward-local-port-or-socket-file-to-remote-socket-file
I will try to add it into TablePlus native SSH.
Thank you for the feedback.

**Comment by huyphams** [comment]
I'm working on it now. Just got an idea.

**Comment by huyphams** [comment]
Hi @ernstae I implemented it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the suggestion. Let me know if it works for you.

**Comment by ernstae** [comment]
Hi @huyphams - I did some initial testing, and didn't have much luck.  I verified that I can ssh to the host and run mysql on the command line. (_I purposefully configured the `auth_socket` plugin for my account in mysql for this test_)
```
 ~ » ssh redacted.server.name "mysql information_schema -e '\s'" 
Warning: Permanently added 'redacted.server.name,192.210.230.93' (ECDSA) to the list of known hosts.
--------------
mysql  Ver 14.14 Distrib 5.7.25-28, for debian-linux-gnu (x86_64) using readline 6.3

Connection id:		492166
Current database:	information_schema
Current user:		ernst@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.25-28 Percona Server (GPL), Release '28', Revision 'c335905'
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	latin1
Db     characterset:	utf8
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/var/run/mysqld/mysqld.sock
Uptime:			46 days 11 hours 14 min 51 sec

Threads: 1  Questions: 23759344  Slow queries: 0  Opens: 42575  Flush tables: 1  Open tables: 416  Queries per second avg: 5.917
--------------
```

When I configured TablePlus, the profile looked like this.  Testing verified a successful ssh connection, but then the UI hung with a "Connecting to Database..." message:
![Screen Shot 2019-05-05 at 11 33 41 AM](https://user-images.githubusercontent.com/3441274/57198661-23b6c180-6f2a-11e9-972d-579d56181346.png)

**Comment by ernstae** [comment]
Hi @huyphams - I did some initial testing, and didn't have much luck.  I verified that I can ssh to the host and run mysql on the command line. (_I purposefully configured the `auth_socket` plugin for my account in mysql for this test_)
```
 ~ » ssh redacted.server.name "mysql information_schema -e '\s'" 
Warning: Permanently added 'redacted.server.name,1.2.3.4' (ECDSA) to the list of known hosts.
--------------
mysql  Ver 14.14 Distrib 5.7.25-28, for debian-linux-gnu (x86_64) using readline 6.3

Connection id:		492166
Current database:	information_schema
Current user:		ernst@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.25-28 Percona Server (GPL), Release '28', Revision 'c335905'
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	latin1
Db     characterset:	utf8
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/var/run/mysqld/mysqld.sock
Uptime:			46 days 11 hours 14 min 51 sec

Threads: 1  Questions: 23759344  Slow queries: 0  Opens: 42575  Flush tables: 1  Open tables: 416  Queries per second avg: 5.917
--------------
```

When I configured TablePlus, the profile looked like this.  Testing verified a successful ssh connection, but then the UI hung with a "Connecting to Database..." message:
![Screen Shot 2019-05-05 at 11 33 41 AM](https://user-images.githubusercontent.com/3441274/57198661-23b6c180-6f2a-11e9-972d-579d56181346.png)

**Comment by huyphams** [comment]
Hi @ernstae could you please check the socket address again? As far as I can see the mysqld.sock is not the normal socket. Please check out my setup on centos.
![5E4F84EE-E07A-4750-9AFE-56D99FE4FCE4](https://user-images.githubusercontent.com/3654622/57201327-b6566f80-6fc1-11e9-9600-0b8519c9193f.jpeg)

**Comment by ernstae** [comment]
The host I was connecting to is running Percona Server 5.7.25 and the socket is located in that location:

```
mysql> show global variables like 'socket';
+---------------+-----------------------------+
| Variable_name | Value                       |
+---------------+-----------------------------+
| socket        | /var/run/mysqld/mysqld.sock |
+---------------+-----------------------------+
```

and the file is there:
```
/var/run/mysqld$ ls -la /var/run/mysqld/mysqld.sock
srwxrwxrwx 1 mysql mysql 0 Mar 20 02:31 /var/run/mysqld/mysqld.sock
```

The host is Ubuntu 14.04, running Percona Server 5.7.25 but there's nothing particularly special about it (_and you can see that I can access over ssh from my earlier message_)

**Comment by huyphams** [comment]
Thank you for the confirmation. I will create an instance with your information and try it out.

**Comment by ernstae** [comment]
I still haven't been able to confirm this as working, but will see if I can come up with a simpler test environment before commenting further.

**Comment by huyphams** [comment]
Hey @ernstae please try this build with `MariaDB` driver: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
let me know if you're still seeing it.
