### ISSUE TITLE
Allow read-only access to databases

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#109]
There seem to be many ways to easily edit data (actual table values, column names and types), and it's not always safe when accessing production databases. An option to read data sources in a read only fashion would be nice.
eg. https://github.com/serge-rider/dbeaver/search?q=isConnectionReadOnly

**Comment by huyphams** [comment]
Hi @bhrd 
We already have that options:
<img width="519" alt="screen shot 2017-11-10 at 1 51 04 pm" src="https://user-images.githubusercontent.com/3654622/32646243-3f7a391c-c61e-11e7-938c-0a6228e7819c.png">

This feature prevent TablePlus send queries to server without confirm you. But please remember that if you want o make sure everything working as expected, you should create an account with read-only.

Huy.

**Comment by bhrd** [comment]
Well, what I'm asking for is a little different. 
A way to issue select queries (or any read queries) without warning, but only disable queries/options that might write to the database, when on read-only mode. where writes could be anything from table/db name alterations, column value and datatype alterations. I guess it's not that easy to implement.

**Comment by huyphams** [comment]
`A way to issue select queries (or any read queries) without warning, but only disable queries/options that might write to the database, when on read-only mode` => When implement this feature,  I thought about this a lot. But as you said, it's not easy to implement. I will marked this as improvement for this feature.

**Comment by huyphams** [comment]
I added that feature, safe mode now can ignore SELECT queries:
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by vvo** [comment]
Just came here that this is an excellent feature, thanks a lot!
