### ISSUE TITLE
Missing left pane to choose database/tables

### ISSUE THREAD

**Issue by tapankavasthi** [TablePlus/TablePlus#1090]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Tried on different builds 
200, 215

3. The steps to reproduce this issue:
Connect to any database. Snapshot attached.

Noted: If the bug is related to data, please attach an example SQL data.

<details>
<summary>
See Snapshot
</summary>
<img width="1280" alt="Screenshot 2019-04-05 at 12 50 44 PM" src="https://user-images.githubusercontent.com/38013895/55610885-825d1400-57a1-11e9-8a23-29781d4c7ec4.png">
</details>

**Comment by huyphams** [comment]
It has been collapsed, could you please click the toggle button on the top right to toggle it?

**Comment by tapankavasthi** [comment]
Thanks a lot @huyphams for such a quick resolution. It worked :)
