### ISSUE TITLE
How to backup favourites and connection settings?

### ISSUE THREAD

**Issue by hyperknot** [TablePlus/TablePlus#1092]
I'd like to migrate to a clean macOS and I'd like to ask what kind of files and folders do I need to back up and how to restore them, to keep connection settings and favourites?

By doing an "rg" find in ~/Library, I found that 
```
Application Support/com.tinyapp.TablePlus/Cache/Favorite
```
contains favourites. My only problem is that it's a "Cache" folder. Is this the main folder, or it's really just a cache, with the main settings stored somewhere else?

**Comment by huyphams** [comment]
Hi @hyperknot you can use the export feature:
<img width="659" alt="Screen Shot 2019-04-08 at 7 21 47 AM" src="https://user-images.githubusercontent.com/3654622/55692108-05af7d00-59cf-11e9-8ab8-97be103fac22.png">
But it only backup the connections, if you want to backup all the data you must copy this folder
"cd ~/Library/Application Support/com.tinyapp.TabPlus"

**Comment by hyperknot** [comment]
And if I want to backup only the favourites I can just copy `Application Support/com.tinyapp.TablePlus/Cache/Favorite`? I was only a bit confused about why it's in a folder called "Cache".

**Comment by huyphams** [comment]
Yes, it's `Cache/Favorite`
