### ISSUE TITLE
Use connection name instead of database name

### ISSUE THREAD

**Issue by djibarian** [TablePlus/TablePlus#1093]
It would be good to show the connection name in the left hand connections list, instead of the database name. Sometimes you have a Dev and Prod connections with the same database name and there is no way of distinguishing them, when it wouldn’t cause any problem if the connection name would be displayed.

**Comment by huyphams** [comment]
Hi @djibarian there are some similar issues related to this issue.
We're working to improve the database sidebar. Thank you for the feedback!
