### ISSUE TITLE
Maybe a bug: Incorrect execution plan when parameters in SQL

### ISSUE THREAD

**Issue by yuqiang-yuan** [TablePlus/TablePlus#1096]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL, 5.6.16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 212

3. The steps to reproduce this issue:

Step 1: Define a query parameter in the SQL window, for example: 

`set @uid = '6496AE96-AE31-11E7-AA22-7CD30AD36C02';`

Step 2: Show the execution plan of the query sql with query parameter:

`explain select * from t_clazz_course_member where user_id = @uid`

I get "ALL" full table scan execution plan and the execution time of the sql is almost 27s

<img width="1217" alt="屏幕快照 2019-04-10 下午1 32 34" src="https://user-images.githubusercontent.com/15667885/55853798-26293400-5b95-11e9-880f-7b91e75df52c.png">

Step 3: User the user id value in the query SQL and show the execution plan:

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/15667885/55853818-3d682180-5b95-11e9-9ff7-095136757c7a.png">

It shows that the SQL use the index and the execution time is 20ms

I repeated the steps in MySQL Workbench, everything goes OK. So would you please check it?

Thanks and Regards,

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @yuqiang-yuan could you please make a gif? There is one reason that makes it does a full scan. The parameter is null (a child case of not having the same data type).

**Comment by yuqiang-yuan** [comment]
Hi, @huyphams here comes the gif FYR

![2019-04-12_12-28-43 (1)](https://user-images.githubusercontent.com/15667885/56012402-ebeb9e00-5d1e-11e9-98b8-c15556991c62.gif)

**Comment by huyphams** [comment]
Thank @yuqiang-yuan for the gif, can I have your table creation? I think the @uid from the set command is not the same data type as the user_id in the query so MySQL will not use the index. I need the table creation to reproduce the issue
Btw, can you try this: `EXPLAIN SELECT * FROM t_clazz_course_member where user_id = CAST(@uid as CHAR);`
it will force the @uid to char type.

**Comment by yuqiang-yuan** [comment]
I'm sorry, maybe I found the problem. I tried to get the DDL of the table from TablePlus, I found something strange:

```sql
CREATE TABLE `t_clazz_course_member` (
  `ID` varchar(36) CHARACTER SET utf8 NOT NULL,
  `CLAZZ_COURSE_ID` varchar(36) CHARACTER SET utf8 NOT NULL,
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time a use join a class course',
  `USER_ID` varchar(36) CHARACTER SET utf8 NOT NULL,
  `SCORE` int(11) NOT NULL DEFAULT '0',
  `SCHOOL_ID` varchar(36) CHARACTER SET utf8 DEFAULT NULL,
  `DEPARTMENT_ID` varchar(36) CHARACTER SET utf8 DEFAULT NULL,
  `MEMBER_NAME` varchar(60) CHARACTER SET utf8 DEFAULT NULL,
  `MEMBER_NO` varchar(30) CHARACTER SET utf8 DEFAULT NULL,
  `ROLE_ID` int(11) NOT NULL DEFAULT '2' COMMENT '2:member 3:assistant',
  `CARD_EDIT_FLAG` char(1) CHARACTER SET utf8 NOT NULL DEFAULT 'N',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_CLAZZ_COURSE_ID_USER_ID` (`CLAZZ_COURSE_ID`,`USER_ID`),
  KEY `IDX_UID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

You see, the table character set is `utf8mb4` but the column character set is `utf8`. Here is why the table is so strange:

I have an old database, we call it `OLD_DB`; the sql execution plan I queried on a new database, we call it `NEW_DB`. the NEW_DB is created from the OLD_DB via some tools including the table structure and the table data. 

The character set of the OLD_DB and the NEW_DB is:

|  Item | OLD_DB | NEW_DB
| ----|----|----
| Server Character Set | utf8 | utf8
| Database Character Set | utf8 | utf8mb4
| Table Character Set | utf8 | utf8mb4

Here is my migration steps:

Step 1: I created tables on the NEW_DB without the data
Step 2: I changed the table character set using SQL `ALTER TABLE XXX DEFAULT CHARACTER SET=utf8mb4`
Step 3: Load data from OLD_DB to NEW_DB

After connected to the MySQL server, TablePlus uses the database character set as the session character set, that is `utf8mb4`, so I can get the right execution plan even the SQL statement includs query parameter by:

converting the character set: `explain select * from t_clazz_course_member where user_id = convert(@uid using 'utf8')`

OR

Change the session's character set back to `utf8` using menu item `Connection > View Using Encoding`

Sorry for disturbing you, you can close this issue. It's no the TablePlus, it's my fault.

Sorry again~~

**Comment by huyphams** [comment]
Thank you for the confirmation @yuqiang-yuan 👍
