### ISSUE TITLE
Row Count Problem

### ISSUE THREAD

**Issue by volkanozyildirim** [TablePlus/TablePlus#1097]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.2(215)

3. The steps to reproduce this issue:
Any select query or view trying to get count. On tables with big amount of data this takes too long and even if i try to cancel query, ide gets stucked.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @volkanozyildirim have you disabled this option? TablePlus always estimates row count if the number of rows is bigger than a threshold.

<img width="612" alt="estimate" src="https://user-images.githubusercontent.com/3654622/55863131-22e97480-5ba4-11e9-90b4-a9266472693c.png">

**Comment by volkanozyildirim** [comment]
Hi Pham,

You are lightning fast!

No i didnt, its enabled. But problem is row count needs to be calculated. I see count(*) query takes too long.

Example query from magento project:

SELECT
*
FROM
catalog_product_entity cpe
INNER JOIN catalog_product_entity_text pet ON pet.row_id = cpe.row_id
INNER JOIN catalog_product_entity_datetime ped ON ped.row_id = cpe.row_id
INNER JOIN catalog_product_entity_int pei ON pei.row_id = cpe.row_id
INNER JOIN catalog_product_entity_varchar pev ON pev.row_id = cpe.row_id
WHERE
cpe.type_id = ‘simple’;

PS: Same problem also exists on views.

I also have a recommend on safe mode level. There may be options for query types. It would be great if an option added for excluding select query in alert/safe mode

Best regards

**Comment by huyphams** [comment]
I designed TablePlus to use this query:
`SELECT table_rows as count FROM information_schema.TABLES WHERE TABLE_SCHEMA='katonice'AND TABLE_NAME='author';`
If the returned result < the threshold then TablePlus will perform the count. Although you see the count query on the TablePlus console, it will run the estimate behind the scene.

About the safe mode level, yes, working on an advanced option which allows the user to ignore SELECT query in warning/safe mode.

**Comment by volkanozyildirim** [comment]
Here is video of problem

https://ufile.io/ak222

Best regards

**Comment by huyphams** [comment]
I think it's a misunderstanding, sorry because of my bad English. Executed Statements Count is the total number queries which were executed.
TablePlus only opens 1 connection per workspace so that's the reason you can't run the second query. The first query must be done in order to run the second query.

Maybe we should add a config that allows TablePlus to use the connection pool. Related issue: https://github.com/TablePlus/TablePlus/issues/639

**Comment by roncarino** [comment]
Hi, I am not exactly sure if it is the same problem but...... quite often I get stuck too.
Literally now I am trying to import a 15MB sql file and it stopped at 10MB.
Only thing I can see is the usual message "Can't log this query because it's too big".
