### ISSUE TITLE
Right tab doesn't show actual properties of the selected row for boolean fields

### ISSUE THREAD

**Issue by vgoloviznin** [TablePlus/TablePlus#110]
After one of the recent releases, when opening the right 'tab' and selecting a row, the tab is not showing proper property values of the selected row for boolean fields. String and number fields are updating properly when selecting

**Comment by huyphams** [comment]
Hi @vgoloviznin 
Thanks for the feedback, I got the bug, I'm fixing it now.
Huy.

**Comment by vgoloviznin** [comment]
@huyphams thanks!

**Comment by huyphams** [comment]
Hi @vgoloviznin

I just pushed the hotfix on website, if you want to update please go to https://tableplus.io and download it or wait until version 70 released.

Huy.
