### ISSUE TITLE
foregin_key only gets accepted after reload

### ISSUE THREAD

**Issue by BenjaminHoegh** [TablePlus/TablePlus#1100]
foregin_key only gets accepted after reload each time I create a new table. Is this a bug or me doing something wrong?

**Comment by huyphams** [comment]
Which database driver are you using @BenjaminHoegh ? thanks

**Comment by BenjaminHoegh** [comment]
> Which database driver are you using @BenjaminHoegh ? thanks

MySQL 5.7.25
