### ISSUE TITLE
Bug: double-clicking on a table REPLACES the current SQL 'scratch space' tab

### ISSUE THREAD

**Issue by alexgw-afr** [TablePlus/TablePlus#1101]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 8.0.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
"Version 2.2 (212)"

3. The steps to reproduce this issue:
Click the "SQL" button to make a new "scratch space" for queries.
Double click a table defintion in the sidebar at left.

Expected behavior: a new tab should open.

Actual behavior: the SQL scratch work tab is REPLACED by the table view.

This makes it incredibly difficult to use TablePlus for any exploratory work.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by alexgw-afr** [comment]
Following up, it appears to happen only if I:

* Start in one database schema
* **Switch to ANOTHER database schema** (from the pull-down menu in the bottom left of TablePlus)
* Create an SQL scratch space
* Now double-click a table at left; it REPLACES the scratch space 100% of the time.

However, if I launch from scratch and don't switch schemas, it works properly.

**Comment by huyphams** [comment]
TablePlus will not replace the SQL tab in recent builds.
