### ISSUE TITLE
Customizable quick look trigger?

### ISSUE THREAD

**Issue by UnderpantsGnome** [TablePlus/TablePlus#1102]
It would be nice if we could customize the the quick look trigger, some (many?) of us don't have a middle mouse button. 

Another possible solution would be if double clicking on cells that are text or JSON automatically opened in the quick look. 

I didn't even know quick look was a thing until I started looking for issues related to editing JSON data.

Keep up the great work, now that I know I can better edit JSON data it may be time to purchase 😀

**Comment by romikzo** [comment]
+1 would be nice, if i could open quick look window pressing some key. Many mac user dont have mouse.

**Comment by AZLisme** [comment]
+1

**Comment by ct-emil** [comment]
+1, I consider the lack of this particularly painful, as I have a need to quick view very frequently and need to use an accessibility device that does not have middle click set.

Even just having a keyboard shortcut added would be a big improvement to workflow.

**Comment by huyphams** [comment]
Hi, you can open Quicklook quickly with command + enter from this build: https://www.dropbox.com/s/1m4ro31q15kcgnj/TablePlus.dmg?dl=0
