### ISSUE TITLE
Better editing of JSON data?

### ISSUE THREAD

**Issue by UnderpantsGnome** [TablePlus/TablePlus#1103]
It would be nice if when editing JSON data you could add/remove/edit keys.

**Comment by huyphams** [comment]
I'm updating the JSON editor, but the current version allows removing key:
<img width="689" alt="Screen Shot 2019-04-12 at 7 18 39 AM" src="https://user-images.githubusercontent.com/3654622/56003911-453dd800-5cf3-11e9-8fdb-4d83adcd4ddf.png">

**Comment by huyphams** [comment]
You can edit key in the new update!
