### ISSUE TITLE
Make drivers optional

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1108]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

216

3. The steps to reproduce this issue:

When I started to use TablePlus it was below 100 MB in size, now it's 300MB in size. Addition of new frameworks and drivers caused huge increase in size. Since I'm using MySQL and SQLite only increase in size is huge for me compared to used feature set.

Would it be possible to make drivers downloadable, like done in PhpStorm:

1. drivers and support libraries aren't stored in the app itself
2. when I attempt to add new connection, but driver is missing it is downloaded in application support folder

This approach should:

1. make app update work faster, because used frameworks for specific driver never change and won't be downloaded
2. people not using specific drivers won't sacrifice disk space for unused drivers

**Comment by huyphams** [comment]
The official release is 30MB, the beta build contains the Oracle so it 300MB. You're using the beta build.

We're aware of it and it's already on our plan.

**Comment by aik099** [comment]
Great. Thank you.

**Comment by huyphams** [comment]
Fixed!
