### ISSUE TITLE
TablePlus stopped to work and don't show errors

### ISSUE THREAD

**Issue by AndreFigueredo-Multilaser** [TablePlus/TablePlus#1110]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MariaDB (10.4.4) , MSSQLServer (2017) and MongoDB (4.0.6).

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 2.2(212)

3. The steps to reproduce this issue:

I'm trying to connect with my databases and appears the message "connecting to database", but two seconds after I always get the same window and I can't see any error.  This is the window: https://imgur.com/QgkiZZB

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
HI @AndreFigueredo-Multilaser please toggle the item pane, click the button on the top right.
