### ISSUE TITLE
Exporting MySQL table with binary ID's crashes

### ISSUE THREAD

**Issue by ruudk** [TablePlus/TablePlus#1111]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
210

3. The steps to reproduce this issue:
Have a table with a `binary(16)` id. Right click the table and export it. You see a progress bar and immediately the program crashes.

**Comment by huyphams** [comment]
Hi @ruudk please try again with the newest build 212. it should fix the crash.

**Comment by ruudk** [comment]
<img width="327" alt="Screenshot 2019-04-16 at 11 15 28" src="https://user-images.githubusercontent.com/104180/56197360-f5377c00-6038-11e9-971c-fde238500634.png">
👍
