### ISSUE TITLE
Support for Mongo shell queries

### ISSUE THREAD

**Issue by darshantejani007** [TablePlus/TablePlus#1113]
I am looking for a way to enter Mongo Queries into TablePlus!
Can anyone suggest me how I can do this?
The mongo query can be as simple as this : 

`db.getCollection('users').find({phone: '8899889988'})`

<img width="1347" alt="Screenshot 2019-04-17 at 2 04 47 PM" src="https://user-images.githubusercontent.com/6480543/56273660-cdb8e000-611a-11e9-9e21-f626465a1e55.png">

Table plus build Number: 212
Platform : Mac OSX 10.14.1

**Comment by huyphams** [comment]
Hi, please press command + F and try to query via the advanced filter.

**Comment by darshantejani007** [comment]
Thanks. @huyphams  works for my use-case. :)
