### ISSUE TITLE
[Bug/Unwanted change] Double clicking a query stored in the favourites window used to insert the favourited query, now it opens it as a new SQL window (and edits in that window change the saved query)

### ISSUE THREAD

**Issue by heathyboyj** [TablePlus/TablePlus#1115]
I had a number of saved helper queries (little things like common table join lines, or converting a particular common from a unix timestamp to a human-readable datestring), but since the last patch I've had to right-click+insert the query instead of double clicking. I've also managed to overwrite a couple of those queries once or twice by unintentionally opening them and not realising that wiping+writing fresh SQL would be saved in place of the query, and had to go re-write them the next time I needed them.

Could the old functionality be re-enabled, perhaps as an option? "Double clicking a favourite ... [inserts the favourite into the open query | opens the favourite].

Thanks!

**Comment by huyphams** [comment]
Hi @heathyboyj you can turn off autosave in the preferences.
Double-clicking to insert => I added that option on the development build, it will be released on the next update.

**Comment by huyphams** [comment]
It will be released on the beta build tomorrow and official build next month.
