### ISSUE TITLE
Allow export with no "swap" character

### ISSUE THREAD

**Issue by evolarjun** [TablePlus/TablePlus#1116]
I often work with tab-delimited files. For the most part quote characters are unnecessary unless tab characters occur in fields. Most of the data I work with has this characteristic. It would save an extra step for me if TablePlus did not have mandatory quotes around field contents on export.

**Comment by huyphams** [comment]
I agreed, we should add an option "quote if needed", then TablePlus will only quote the value if it contains the delimiter.

**Comment by huyphams** [comment]
Hey, I just added an option "Quote if needed" and it's the default option when exporting a CSV.
You can download the build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

- This feature will be included in the next update.
- This build can self-update.

Thank you for the feedback.

**Comment by chrschmitz** [comment]
"Quote if needed" is shown in the preferences and when exporting one table, but not, if exporting multiple tables. Is this a bug?

**Comment by huyphams** [comment]
heck, I forgot to enable it for multiple tables 😄
