### ISSUE TITLE
Result Column Sizing Wrong

### ISSUE THREAD

**Issue by ksizemore137** [TablePlus/TablePlus#1117]
Result sets of varchar and decimal columns don't size correctly. Either the columns are much too big or too small.

_1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):_
MariaDB & SQL Server
_2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):_
TablePlus 2.2 (216)
_3. The steps to reproduce this issue:_
CREATE TABLE `test` (
  `unix_time` decimal(22,6) DEFAULT NULL,
  `inv_year` int(4) NOT NULL,
  `inv_month` int(2) NOT NULL,
  `taker` varchar(13) NOT NULL,
  `shipped` bigint(21) DEFAULT NULL,
  `profit` decimal(13,2) DEFAULT NULL,
  PRIMARY KEY (`inv_year`,`inv_month`,`taker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `test` (`unix_time`, `inv_year`, `inv_month`, `taker`, `shipped`, `profit`) VALUES ('1509519600.000000', '2019', '4', 'Other', '101', '100');

SELECT * FROM test; 
Viewing tables is the same way. The columns aren't adjusting to the size of the data fields.

![Screen Shot 2019-04-17 at 5 08 36 PM](https://user-images.githubusercontent.com/25895138/56328915-c7405d80-6146-11e9-97e2-23398ea4a9be.png)

Here you can see it is properly adjusting in Sequel Pro
![Screen Shot 2019-04-17 at 5 09 48 PM](https://user-images.githubusercontent.com/25895138/56328930-e212d200-6146-11e9-830a-fc8b7bec2c36.png)

**Comment by huyphams** [comment]
I'm working on it, thank you for the feedback!

**Comment by huyphams** [comment]
I just released the beta 2017 which includes these fixes. Let me know if you're still seeing it.
