### ISSUE TITLE
Cannot update data more than once per query

### ISSUE THREAD

**Issue by stormpat** [TablePlus/TablePlus#1119]
When updating a rows column data from the editor (not manually executing UPDATE statements) only the first update is successful. The second and nth update is never executed, this can be confirmed by turning logging on.

1. Which driver are you using and version of it: MySQL 5.5.62

2. Which TablePlus build number are you using: 2.2 212 (using OSX)

3. The steps to reproduce this issue:

Select a row from a table then manually edit a column value (in the editor), and save. This operation is successful, however trying to edit the same data again will fail. There is no log or error message, the data simply wont update.

In order to further update the same row you must first re-select the row and edit agin.

**Comment by huyphams** [comment]
Thanks, @stormpat I wonder if your table has a priamry key or not?
For example, this can table can be failed update on `every database tools`

Can I have that table creation statement?

CREATE TABLE `test` (
  `the_float` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8

INSERT INTO `test` (`the_float`) VALUES ('1.1');

**Comment by stormpat** [comment]
Yes, there is a primary key. Heres (a truncated) version of the table.

``` 
CREATE TABLE `test` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` int(11) DEFAULT NULL,
  `algo` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `uid_idx` (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=3059 DEFAULT CHARSET=latin1 AVG_ROW_LENGTH=364 ROW_FORMAT=COMPACT
```

**Comment by huyphams** [comment]
I can reproduce the issue now, it happened when you tried to edit the result of the query.

**Comment by huyphams** [comment]
Hi @stormpat I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you so much
