### ISSUE TITLE
Unable to display emojis when using JOIN between tables

### ISSUE THREAD

**Issue by phuchle2** [TablePlus/TablePlus#112]
Hi, I have a problem in rendering emojis. When I run a query on a single table, it displays the emojis just fine. Here is the result:
![screen shot 2017-11-15 at 10 31 34 pm](https://user-images.githubusercontent.com/28104592/32844649-8e14c444-ca55-11e7-9eb1-d460b7e80dee.jpg)

However, when I try to join tables (in my case, 3 tables), the emojis are not rendered and it returns NULL fields.
![screen shot 2017-11-15 at 10 33 41 pm](https://user-images.githubusercontent.com/28104592/32844721-b784ea84-ca55-11e7-9142-c0d5f0e28d19.jpg)

I'm using build 70 and Postgres.

Thanks.

**Comment by huyphams** [comment]
Hi @phuchle2 
Thanks for your feedback
Let me try to reproduce this bug, will get back to you soon.
- Huy.

**Comment by phuchle2** [comment]
@huyphams yeah I have tried on TeamSQL and it displays just fine.

**Comment by huyphams** [comment]
I think I can reproduce the bug now,
Thanks you @phuchle2  💃🏻

**Comment by huyphams** [comment]
Hi @phuchle2 
This build should fixed your problem: https://www.dropbox.com/s/kuh27p1gv82enqq/TablePlus.zip?dl=0
- Huy.
