### ISSUE TITLE
"Estimate count when table has more than..." does not always work

### ISSUE THREAD

**Issue by lexilya** [TablePlus/TablePlus#1120]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.0.12.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

2.2 (217) currently which I just updated to, but it happened in previous versions.

3. The steps to reproduce this issue:

I have _"Estimate count when table has more than X rows"_ set to 10k, but it seems that it doesn't always respect this option and tries to get the real row count anyway, and I have to kill the process in another client. The table has 150 million rows, so it's much larger than 10k.

This happens randomly when working throughout the week, so it's hard to reproduce or even give any steps on how to do it.

Is there a way for me to turn on debug so I can provide you with steps on how to reproduce it?

**Comment by huyphams** [comment]
Hi @lexilya I've refactored the estimated code, please download and try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
let me know if you're still seeing it.

**Comment by lexilya** [comment]
Thank you so much @huyphams. I will give it a go and let you know.

**Comment by lexilya** [comment]
@huyphams I am able to reproduce this issue fairly easy now, it didn't quite go away with your fix in May 2019, but it's been much better.

It's a niche issue, but if you would like to pursue it further, I have a screen recording showing it that I could send to you in private.

You can pretty much reproduce it like this:

- Set the "Estimate count when..." to something like 500k.
- The DB needs to be under heavy load.
- You should probably have some latency between you and the DB.
- Refresh a big table with a few million rows a couple of times.
- If you're unlucky, it starts doing a select count(*) for all tables in that DB.
