### ISSUE TITLE
[Bug] Snowflake columns autocomplete doesn't work

### ISSUE THREAD

**Issue by dornby** [TablePlus/TablePlus#1121]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake 3.20.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
215

3. The steps to reproduce this issue:
Try using the columns autocomplete

![Screen Recording 2019-04-18 at 05 31 PM](https://user-images.githubusercontent.com/12762571/56372757-e6e78c80-61ff-11e9-9ece-72720d59213f.gif)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by guillemettem** [comment]
Any plan to fix this in a near future ? It would really be much appreciated :) Having to explore the schema in a different pane to find the field you're looking for is slowing down our work everyday

**Comment by huyphams** [comment]
Hey @guillemettem @dornby I've fixed it here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you! let me know if you're still seeing it.
