### ISSUE TITLE
Beautify breaks JSON_ARRAYAGG function

### ISSUE THREAD

**Issue by wtchangdm** [TablePlus/TablePlus#1123]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7.25

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 2.2 build 212

3. The steps to reproduce this issue:

Type something like 
```sql
SELECT id, JSON_ARRAYAGG(some_column)
FROM  table
GROUP BY id
```
and then press beautify button, TablePlus will insert a space between JSON_ARRAYAGG and the column. This issue doesn't break JSON_ARRAY or other similar functions though.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @wtchangdm you can work around by installing this plugin: https://github.com/TablePlus/sql-formatter

**Comment by huyphams** [comment]
I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing this issue.
