### ISSUE TITLE
[Feature Request] Safe Mode for SQLite Database

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1125]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 2.2 (218)

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

It would be great if TablePlus would offer a safe mode for SQLite. Locking and unlocking a database within TablePlus would be faster and easier than doing the same within the file system.

**Comment by huyphams** [comment]
I enabled it @chrschmitz thank you for the feedback!
<img width="363" alt="Screen Shot 2019-04-21 at 6 33 05 PM" src="https://user-images.githubusercontent.com/3654622/56469428-ef400180-6463-11e9-8ae2-a39c570e32c8.png">
