### ISSUE TITLE
MySQL - Cannot create a user when password policy MEDIUM is set

### ISSUE THREAD

**Issue by Numline1** [TablePlus/TablePlus#1126]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
212

3. The steps to reproduce this issue:
MySQL has a support for password validation/policy which defines the minimal strength of a password when it's being set and blocks weak passwords. When set to MEDIUM or above, the minimal requirements are usually at least 8 characters, upper and lower case letters, special characters etc. More here: https://tecadmin.net/change-mysql-password-policy-level/

TablePlus tries to create a MySQL user via 3 steps - Creating the user, setting the password and the flushing priviledges. This fails with an error popup saying this:

![image](https://user-images.githubusercontent.com/12192684/56476136-912b1280-6493-11e9-94d7-f5e2b6de2349.png)

I suspected this is because of the fact that TablePlus first tries to create a user without a password and then tries to set it in a separate statement. This *may* (and that's purely theoretical) also have security implications (accidentally creating a user without password).

My suggestion would be to create the user with password in one step, using `IDENTIFIED BY`. This should both fix the issue and prevent potential further issues should a user be created without password.

**Comment by huyphams** [comment]
Hi @Numline1 thanks, I fixed it.

**Comment by Numline1** [comment]
@huyphams thanks a lot :)
