### ISSUE TITLE
The "Run" context menu entry from History pane executes unrelated SQLs

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1127]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

217

3. The steps to reproduce this issue:

* write some SQLs in the SQL Query editor
* select any record in History pane
* from context menu select `Run` menu entry

What happens now:

1. SQLs from history pane are appended to the bottom of query editor
2. all SQLs (from history pane + ones existed before in query editor) are executed together

What should happen

1. sqls from history pane that are added to query editor should be selected so that only they are executed and rest of SQLs are ignored

**Comment by huyphams** [comment]
It's will be released on the next update.

**Comment by aik099** [comment]
Thanks.
