### ISSUE TITLE
Auto-quotes issue for CamelCase in PG's view name via autocomplete 

### ISSUE THREAD

**Issue by UncleMiF** [TablePlus/TablePlus#1129]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PG 11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

212

3. The steps to reproduce this issue:

query editor autocomplete doesn't add auto quotes for view names in camelcase

e.g.

`select * from bpm_Traits`

where bpm_Traits entered via autocomplete tool
(must be: `select * from "bpm_Traits"`)

then I receive the error:

> Query 1 ERROR: ERROR:  relation "bpm_traits" does not exist

however for table names, auto-quotes feature works just fine

**Comment by huyphams** [comment]
Thank you, it's TablePlus bug, I fixed it. Now TablePlus autos add a double quote for the view (and the materialized view as well).

**Comment by huyphams** [comment]
You can download the hotfix build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
