### ISSUE TITLE
Make it possible to set NULL in the table view

### ISSUE THREAD

**Issue by bocharsky-bw** [TablePlus/TablePlus#1131]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 212

3. The steps to reproduce this issue:

I'd like to suggest an improvement: Make it possible to easily set NULL on the field when editing it directly in the table view. What about to add a new item, e.g. SET NULL to the menu context when I do right click on the field? I mean this:
<img width="382" alt="Screen Shot 2019-04-25 at 14 00 29" src="https://user-images.githubusercontent.com/3317635/56731484-3af3f300-6763-11e9-89bf-3b43121ea8a4.png">

And/Or what about to make the field NULL when I type "NULL" string in it - right now it just a string "NULL":
<img width="324" alt="Screen Shot 2019-04-25 at 14 06 46" src="https://user-images.githubusercontent.com/3317635/56731572-77bfea00-6763-11e9-8a88-7ce2196cd1f7.png">

Sequel Pro works this way, I just can type NULL and it understands that the field should be NULL instead of "NULL" as a string

**Comment by huyphams** [comment]
Hi @bocharsky-bw you can do it by hold option + left mouse click on any field.
TablePlus also convert empty, a null string to null value if the field datat type is a structure or numeric (JSON, number, Array... )

The NULL string is not a NULL value so we will not convert it automatically.

**Comment by bocharsky-bw** [comment]
Ah, didn't know about Option + left click, thanks! That's awesome then 👍

**Comment by plakhin** [comment]
@bocharsky-bw what about Windows? Alt + Left click seems to not doing anything. Same for ctrl and shift.

**Comment by huyphams** [comment]
On both mac and win, you can set via right click menu

**Comment by plakhin** [comment]
Yeah, see now. sorry. Didn't notice because it is disabled when you edit field contents.

**Comment by joelmellon** [comment]
Option + click is awesome. I just wanted to point out another way.

Right-click on a cell for a context menu. Hover over Set Value, then you can choose NULL, EMPTY, DEFAULT, and Add a file...

<img width="632" alt="Screen Shot 2022-01-29 at 1 24 45 PM" src="https://user-images.githubusercontent.com/13803216/151678036-b096e802-58d4-48df-bf4b-056347099e48.png">

**Comment by mike-levo** [comment]
Null should be the default or atleast have this in settings. You have no idea how many times this has caused issues.
