### ISSUE TITLE
Table definition outputs invalid SQL when using a check constraint and a comment

### ISSUE THREAD

**Issue by nesk** [TablePlus/TablePlus#1132]
Using:

- MariaDB 10.3.12
- TablePlus 2.2 (212)

Create a table using a check constraint _and_ a comment:

```sql
CREATE TABLE `my_table` (
    `my_column` longtext NOT NULL DEFAULT '[]' COMMENT 'Hello world!' CHECK (json_valid(`my_column`))
);
```

Open the table in TablePlus, go to the "structure" tab and click on "definition", you will get this:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/817508/56744106-2706bc00-6778-11e9-80dd-ba87948f74e5.png">

However, the definition is not a valid SQL query:

```sql
CREATE TABLE `my_table` (
  `my_column` longtext NOT NULL DEFAULT '[]' CHECK (json_valid(`my_column`)) COMMENT 'Hello world!'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Running this query will throw the following exception:

```
Query 1 ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COMMENT 'Hello world!'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4' at line 2
```

The query becomes valid if we swap the `CHECK` and `COMMENT` statements:

```sql
CREATE TABLE `my_table` (
  `my_column` longtext NOT NULL DEFAULT '[]' COMMENT 'Hello world!' CHECK (json_valid(`my_column`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by huyphams** [comment]
It's hard to explain because the creation statement is returned by `SHOW CREATE table_name`. TablePlus only show the result from that query. Let me investigate it.

**Comment by nesk** [comment]
Actually, this seems to be a MariaDB bug. I'm closing since you can't really fix this by yourselves.

**Comment by nesk** [comment]
For those interested, here's the bug: https://jira.mariadb.org/browse/MDEV-17654
