### ISSUE TITLE
Frequent layout issues on small tables

### ISSUE THREAD

**Issue by markuswustenberg** [TablePlus/TablePlus#1136]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

CockroachDB 2.1.16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 222.

3. The steps to reproduce this issue:

I often see tables that look like this when first clicked on in the navigation bar on the left:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/141763/56797485-16585380-6815-11e9-975a-d46d92ed1243.png">

Note how small the columns are and how much space there's available on the page. It would be nice if TablePlus could fill the space where available so all column data can be seen at once without having to resize columns manually.

I haven't noticed a consistency in when this happens.

**Comment by huyphams** [comment]
I fixed this issue, TablePlus calculate column size based on the content, but there is an arrow on the cell so it was truncated.
The reason you can't reproduce it because TablePlus remembers the column size/position, so if you open the table and change the size, it will be the same size on the next time you open that table.

**Comment by markuswustenberg** [comment]
Ah, okay. Is there a way for me to reset the table size state?

**Comment by huyphams** [comment]
You can goto the Temp folder: cd "~/Library/Application Support/com.tinyapp.TablePlus/Temp/" and delete all the .options files.
You can delete the Temp but it also removes the saved temporary queries, so please only delete the .options files.

**Comment by markuswustenberg** [comment]
Thanks, works perfectly.

**Comment by huyphams** [comment]
Where necessary.
I've improved the column sizing if the cell has an arrow or braces,
you can download here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
This is hotfix build and it can self-update as the official release. (fat binaries because it contains Oracle).
