### ISSUE TITLE
Table Plus for Linux Users

### ISSUE THREAD

**Issue by emexxRepo** [TablePlus/TablePlus#1137]
i like your software but im using ubuntu please support to linux distrubitions

**Comment by huyphams** [comment]
I'm closing it because it's duplicated: 
https://github.com/TablePlus/TablePlus/issues/1056

**Comment by huyphams** [comment]
We have an alpha release now, https://tableplus.com/linux/install

Please note that:
- This is an Alpha Release (not Beta yet)
- It's expected to HAVE A LOT OF BUGS
- It LACKS A LOT OF FEATURES

We will release a new update every week to make it better!

**Comment by torressam333** [comment]
@huyphams Any ETA on when BETA will be released? I am on Ubuntu and am eager to try out your DB client but can't afford to have bugs in an enterprise environment. LMK! Thanks.
