### ISSUE TITLE
Connection issue over SSH

### ISSUE THREAD

**Issue by neamtua** [TablePlus/TablePlus#1138]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 222

3. The steps to reproduce this issue:

Hello,

Everytime I've tried using TablePlus to connect over ssh I got a lot of "lost connection, reconnecting" messages. Basically for every action I try to make there are at least 2-3 timeouts. Even if I've barely just connected and went to view a table. This has happened on multiple servers in multiple regions.

I've been having this problem for many builds now, i've just decided now to report this.

Most annoying part is when I try to add a row to a table, I get the "Lost connection" error and then you just delete the row I was trying to save. It's annoying to have to type out all the info 4-5 times. If you can't solve the issue with the connection at least leave the draft of the row so we can press save and retry as many times until it works.

![screenshot-1556341632](https://user-images.githubusercontent.com/1029457/56845112-938ed180-68c4-11e9-8286-465f81aac091.jpg)

**Comment by huyphams** [comment]
Hi @neamtua which is the timeout value?
<img width="268" alt="Screen Shot 2019-04-27 at 1 36 50 PM" src="https://user-images.githubusercontent.com/3654622/56845840-8805cf80-68f1-11e9-8edc-fb8be9919002.png">

**Comment by huyphams** [comment]
Never mind, it's not related to it. I'm investigating.

**Comment by huyphams** [comment]
Hey, we fixed this issue recently, if you have a chance, please give it a try! Please let me know if you're still seeing it then I will reopen this issue.
