### ISSUE TITLE
new sql query editor has history filled in

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1140]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:
open a new sql query editor, it has filled with some random history.
i don’t see the logic behind this, which is annoying to me.

**Comment by huyphams** [comment]
Hi @georgexsh you can turn off this feature in the setting at bottom left of the editor.

**Comment by georgexsh** [comment]
@huyphams cool, thanks! I didnt find this option last time I check the editor settings.
