### ISSUE TITLE
show and set mysql column character set/collation

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1141]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:
there is currently no way to see or edit mysql column character set/collation. ref: 
https://dev.mysql.com/doc/refman/8.0/en/charset-conversion.html

**Comment by georgexsh** [comment]
I guess this is duplicated with https://github.com/TablePlus/TablePlus/issues/642.

**Comment by georgexsh** [comment]
hey @huyphams , at least table plus could show the character set info.

**Comment by georgexsh** [comment]
thanks, now that metadata is viewable. 
hope they could be select from a drop-down list in the future.

**Comment by hahamy** [comment]
This feature is not available up to now.
