### ISSUE TITLE
improve beautify for `between and` clause

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1142]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:
current behavior 

![CleanShot 2019-04-28 at 16 24 48](https://user-images.githubusercontent.com/32751/56861311-3e40e600-69d2-11e9-9e4a-ceb97c8df0c0.png)

expect

![CleanShot 2019-04-28 at 16 25 55](https://user-images.githubusercontent.com/32751/56861330-59135a80-69d2-11e9-9311-33178b2ad1cf.png)

**Comment by georgexsh** [comment]
besides I hope there is an option to use lower case keyword when doing sql beautify.

**Comment by huyphams** [comment]
I'm working on this. It will be fixed on the next release.

**Comment by huyphams** [comment]
it's fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing this issue. Then I will reopen this issue.
