### ISSUE TITLE
mysql auto complete missing many keywords

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1143]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:

`UNIX_TIMESTAMP`, `FROM_UNIXTIME`, etc..

**Comment by pernielsentikaer** [comment]
I can verify this, I'm not sure if its only for 5.7 but we can maybe use this list to improve it: https://dev.mysql.com/doc/refman/5.7/en/keywords.html

**Comment by huyphams** [comment]
Both TablePlus and Beautify originally are made for PostgreSQL. I've localized the syntax highlighter for each driver but still using the same beautify for all drivers. that's why you're seeing this issue. I will improve it in future updates.

**Comment by huyphams** [comment]
I've added all MySQL Keywords from this https://dev.mysql.com/doc/refman/8.0/en/keywords.html and https://dev.mysql.com/doc/refman/8.0/en/func-op-summary-ref.html
The highlight syntax is regex based, so it will take more time to complete the list, btw, it's not related to this issue.
Let me know if you're still seeing the issue.
Download the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
