### ISSUE TITLE
beautify eat part of a long query

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1145]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:

the long query sample has sent via private message.

**Comment by huyphams** [comment]
The beautify is made for various of database drivers so it can’t be perfection fit for every case. You can install the custom plugin (by pressing Command + L).

**Comment by georgexsh** [comment]
eat part of query is a **very serious bug**, it barely could not pass the baseline, very very far more from perfection. otherwise I doubt something wrong with your standard of software quality.

**Comment by georgexsh** [comment]
about the sql formatter plugin, it doest respect my indentation setting, at least last time I checked. i can not verify it right now because indentation in editor is broken here.

**Comment by huyphams** [comment]
Hi @georgexsh I rechecked the SQL and didn't see that TablePlus eat any parts of the query.
Could you please point it out? I'm sorry I missed the `eat part` when I saw this issue for the first time, I thought you have reported the formatted issue.

**Comment by georgexsh** [comment]
@huyphams sorry it is bad formatting, not a bug.

**Comment by georgexsh** [comment]
@huyphams if you have time, check the second part of `union`, the `and` conditions of `join...on`.
