### ISSUE TITLE
[feature request] adjust line height in sql editor

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1146]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:
while using larger font size, line height should be higher too, providing an option is very nice.

**Comment by huyphams** [comment]
It will be supported in the next update, thanks!

**Comment by huyphams** [comment]
<img width="712" alt="lineheight" src="https://user-images.githubusercontent.com/3654622/93672171-fd6bd480-fad2-11ea-9197-1905c42d8dfa.png">
