### ISSUE TITLE
Select count(*) doesn't show results, just saying 1 row OK

### ISSUE THREAD

**Issue by pelinswe** [TablePlus/TablePlus#1148]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by pelinswe** [comment]
Using version 2.3, connecting to MsSql database.

**Comment by pelinswe** [comment]
![image](https://user-images.githubusercontent.com/44871112/56884012-b78b1800-6a68-11e9-81fb-b33373c78e87.png)

**Comment by huyphams** [comment]
I think the result is far from the right, could you please resize the window a little bit bigger?
TablePlus remembers the column sizing, so if you change the size and then resize the Windows, the result will be overlapped

![2019-04-29 16 22 32](https://user-images.githubusercontent.com/3654622/56887155-0487e200-6a9b-11e9-9f1f-cf9baf18585d.gif)

**Comment by pelinswe** [comment]
Can't make it longer :( 
![image](https://user-images.githubusercontent.com/44871112/56888921-7ea57000-6a75-11e9-9a52-62418ca5d8fd.png)

**Comment by huyphams** [comment]
hmm, weird, can you scroll the content horizontally? or can you select the first row?

**Comment by huyphams** [comment]
it would be better if you named the count column, for example:
```
select count(*) as count from Challenger;
```

**Comment by huyphams** [comment]
Finally, I can reproduce and fix it, if you have a chance, please try this build and see how's it going:
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!
