### ISSUE TITLE
Redis Command + R ERR syntax error

### ISSUE THREAD

**Issue by retrX** [TablePlus/TablePlus#1149]
1. MacOS 10.14.4  Redis 3.1.6  

2. TablePlus 2.3(222)

3. 连接 redis 查询 键 app_*  command + R

**Comment by huyphams** [comment]
Hey @retrX I've fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the feedback.
