### ISSUE TITLE
Emojis are displayed as question mark.

### ISSUE THREAD

**Issue by theanchorsmith** [TablePlus/TablePlus#115]
Hi,

At the moment I'm using the trial version of TablePlus.
I haven't decided yet wether I should buy the full version.

On the homepage I saw examples of Emoji support (which I need for my projects).
But the emoji will not show up in the TablePlus application (at least not all emoji).
The column value is replaced by a question mark.

Below are screenshots to reproduce:

**Executing query via terminal:**
![schermafbeelding 2017-11-16 om 15 25 49](https://user-images.githubusercontent.com/1969153/32896448-4f7bcbd6-cae3-11e7-805f-09b329c3dd81.png)
**Viewing row in TablePlus:**
![schermafbeelding 2017-11-16 om 15 26 15](https://user-images.githubusercontent.com/1969153/32896452-52178f7e-cae3-11e7-9e5e-e4d8881af76e.png)
**Querying the same row via terminal:**
![schermafbeelding 2017-11-16 om 15 30 05](https://user-images.githubusercontent.com/1969153/32896456-54bde5fc-cae3-11e7-9f52-eaffb6fbce1a.png)

**Comment by huyphams** [comment]
Hi @theanchorsmith thanks for your feedback. Are you using TablePlus for MySQL?

**Comment by theanchorsmith** [comment]
@huyphams Yes I do

**Comment by huyphams** [comment]
Here is the hotfix build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

I'm working on build 72 and fixing all encoding bugs.

<img width="1003" alt="screen shot 2017-11-16 at 11 02 35 pm" src="https://user-images.githubusercontent.com/3654622/32901383-417a6418-cb22-11e7-9474-ba7a758fda10.png">

**Comment by theanchorsmith** [comment]
Thanks, I tested the built and everything works as expected.
I also tested the export functionality.

Thanks for the support.
