### ISSUE TITLE
Connect to MS sql server instantly crashes program

### ISSUE THREAD

**Issue by MrMathias** [TablePlus/TablePlus#1151]
After updating to build 222 from I think 196, testing a connection to or connecting to sql server instantly crashes the program.

I'm on MacOS 10.11.6

**Comment by huyphams** [comment]
Thanks @MrMathias I confirmed the issues. Please roll back to the old build, we will fix it on the next release.
https://tableplus.com/blog/2017/02/changelogs.html

**Comment by MrMathias** [comment]
Cool. I guess it wasn't from build 196 then? If I recall correctly the update notification said "26 updates". Do you have an idea about which build that caused the issue?

**Comment by huyphams** [comment]
I think you can download the build 200 or 212.

**Comment by huyphams** [comment]
Hey @MrMathias I've fixed the bug: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I've compiled the SQL lib on Mac OS 10.11 for backward compatible.
