### ISSUE TITLE
Duplicate entire MySQL database and content

### ISSUE THREAD

**Issue by chrisdeeming** [TablePlus/TablePlus#1152]
I still have to keep a copy of Sequel Pro installed for one particular "quality of life" improvement it has that TablePlus doesn't have.

Namely it has pretty much a "one-click" duplicate database (and content) system:

![image](https://user-images.githubusercontent.com/2158514/56973068-09649880-6b64-11e9-85d3-ebc3bc49b997.png)

As far as I know, the only way to achieve this with TablePlus currently is to do a full backup and restore, which is much more fiddly than the SequelPro process.

They also have a rename database option which can be useful.

**Comment by Cottser** [comment]
See also #986, #762. Maybe a couple of these can be closed as "duplicates" :)

**Comment by Cottser** [comment]
@huyphams since all three issues were closed is there a newer feature request issue to follow? Thanks in advance.

**Comment by huyphams** [comment]
We added it in the beta release, and it will be officially released in the next update @Cottser

**Comment by timrspratt** [comment]
@huyphams which version did this get released on, and where exactly does it live? Thanks

**Comment by plweil** [comment]
@huyphams same question: Which version did this get released on, and where exactly does it live? Thanks

**Comment by repat** [comment]
https://tableplus.com/blog/2017/02/changelogs.html

 I can't find it here either @huyphams  🤔

**Comment by plweil** [comment]
A clarification/update would be appreciated, @huyphams

**Comment by timrspratt** [comment]
@huyphams still no signs of this feature?

**Comment by harlacher** [comment]
@huyphams Any update on this? It's the only missing feature which prevents me (and probably others) from dropping Sequel Pro.

**Comment by laurentlemaire** [comment]
@huyphams any update on this?

**Comment by njbarrett** [comment]
@huyphams could you explain how this can be done? thanks
