### ISSUE TITLE
Can't reconnect to Snowflake after idle time without new connection window

### ISSUE THREAD

**Issue by rwhitten577** [TablePlus/TablePlus#1153]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake - latest

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
222

3. The steps to reproduce this issue:
- Open snowflake connection
- Put computer to sleep for n hours
- Wake computer, try to refresh tableplus connection window (still open from last session)
- Connection window cannot connect to snowflake, table names from Items list disappear 
- Only workaround I've found is to close the connection window and open a new one, but then I lose all previous tabs 

Using MacOS Mojave 10.14.4

**Comment by huyphams** [comment]
Hi @rwhitten577 you can force reconnect by pressing Command + Shift + R.

**Comment by rwhitten577** [comment]
Ah thanks @huyphams! Will give that a try.
