### ISSUE TITLE
MSSQL varbinary fields cause row not to display

### ISSUE THREAD

**Issue by lukeberry99** [TablePlus/TablePlus#1154]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
MSSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
212

3. The steps to reproduce this issue:
Have a varbinary field populated with data, it wont appear in the results.

Some of our users have avatars uploaded as a `varbinary` type in our DB, their entire record disappears from TablePlus when trying to view it.

For example, if I do a query like `SELECT * FROM Person WHERE ImageData IS NOT NULL` it says 0 records, if I do `SELECT COUNT(*) AS count FROM Person WHERE ImageData IS NOT NULL` there are in fact 50 records. I can view them using other tools (such as SQL Pro Studio).

There are in fact two issues here, one where count doesn't work unless you name it, and the other where fields using `varbinary` type do not appear at all. This is quite a serious issue, especially as we're dealing with production databases - losing confidence in TablePlus with this.

**Comment by huyphams** [comment]
Hi @lukeberry99 which version of SQL Protocol are you using? I'm testing with the default protocol and it works.
<img width="612" alt="version" src="https://user-images.githubusercontent.com/3654622/57022926-de10a500-6c5a-11e9-83a4-b0749efafb6b.png">

**Comment by huyphams** [comment]
The rows is not shown mostly because of the protocol mismatch.
<img width="1065" alt="varbinary" src="https://user-images.githubusercontent.com/3654622/57023036-38116a80-6c5b-11e9-8b5f-9020a9515dd9.png">

**Comment by huyphams** [comment]
Hi @lukeberry99 this build should fix your issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the feedback.

**Comment by huyphams** [comment]
I released the build 226 which includes this fix, thank you for the feedback.
