### ISSUE TITLE
Open Recent is always empty

### ISSUE THREAD

**Issue by BrandonBlair** [TablePlus/TablePlus#1158]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.34

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 224

3. The steps to reproduce this issue:
![Recent](https://user-images.githubusercontent.com/5199091/57090851-629c0b80-6ccd-11e9-85be-40febcc91743.gif)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by shawnhooper** [comment]
Still an issue in build 264.

**Comment by huyphams** [comment]
Hi guys, please try this hot patch and let me know the result: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!

**Comment by BrandonBlair** [comment]
@huyphams Same behavior in this build (266)
![recentBug](https://user-images.githubusercontent.com/5199091/66322947-99172b80-e8e8-11e9-9624-ef421ddec249.gif)

**Comment by huyphams** [comment]
Ah, I did not handle event `Save As...` if you open it via menu or drag drop, it will show in Open Recent.

**Comment by huyphams** [comment]
This build should solve the `save as...` issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for reporting.

**Comment by BrandonBlair** [comment]
@huyphams Appears to work now. Thank you for addressing this, I use this a lot.

**Comment by shawnhooper** [comment]
@huyphams Thank you for the quick patch!  It's working great now.
