### ISSUE TITLE
Crash running SQL 

### ISSUE THREAD

**Issue by gfesj69** [TablePlus/TablePlus#1159]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    Mysql 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    Version 2.3 (222)

3. The steps to reproduce this issue:
     Try to run SQL.

Noted: If the bug is related to data, please attach an example SQL data.

[Crash_DUMP.log](https://github.com/TablePlus/TablePlus/files/3140146/Crash_DUMP.log)

**Comment by huyphams** [comment]
Hi @gfesj69 does it happen every time or randomly? I can't reproduce the issue with my MySQL 5.6 docker container.

**Comment by huyphams** [comment]
I can't reproduce the issue, if you're still seeing this issue on the latest release, please let us know. Thank you!
