### ISSUE TITLE
small issue, check update dialog window incorrect

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#116]
Should say 'Release 72' instead of '1.0', i think

![screen shot 2017-11-18 at 2 44 00 am](https://user-images.githubusercontent.com/7946786/32979471-93090972-cc0a-11e7-877e-0098818a171f.png)

![screen shot 2017-11-18 at 2 45 56 am](https://user-images.githubusercontent.com/7946786/32979479-a18a1608-cc0a-11e7-82d4-93fe9a3b64dc.png)

**Comment by huyphams** [comment]
Yeah, this is default alert from [sparkle](https://sparkle-project.org/), let's me see how if we can change this.
Thanks you Brian 😁
