### ISSUE TITLE
SQLite problem with field Blob.

### ISSUE THREAD

**Issue by ghost** [TablePlus/TablePlus#1161]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:
```
-- ----------------------------
-- Table structure for syslog
-- ----------------------------
DROP TABLE IF EXISTS "syslog";

CREATE TABLE syslog (
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"id_comp" VARCHAR(20),
	"type" VARCHAR(20),
	"message" BLOB DEFAULT '',
	"ondate" DATE,
	"ontime" VARCHAR(8),
	"timezone" INTEGER (3) DEFAULT 0,
	"sync" BOOLEAN DEFAULT 1,
	"isDeleted" BOOLEAN DEFAULT 0
);

-- ----------------------------
-- Records of syslog
-- ----------------------------
BEGIN;

INSERT INTO "syslog"
	VALUES (1, 2019, 'warning', '{"id":"2019","user_name":"Lailton","user_mail":"lailton@harbour.com.br","report":"report 002"}', NULL, NULL, 0, 1, 0);

COMMIT;
```
So how can you see here, I have this BLOB column used to save some LOG from user device,
the old version tablePlus I was able to use Quick View JSON and now I can not see the content anymore...

<img width="1432" alt="Screen Shot 2019-05-03 at 11 11 51 AM" src="https://user-images.githubusercontent.com/39895255/57143736-ed483d80-6d95-11e9-90e6-feccc8da92e8.png">

I know.. I can download and open using an external programm to see the file saved, but it is not friendly how it was before..

Please can you review it and make it more friendly?

I think that you should offer more way to the use see the BLOB field, sometimes it can be an image/text/image base64 and is . very interesting a way to be able to see it.

Thanks

**Comment by huyphams** [comment]
Thanks @lailton let me take a look into it.

**Comment by huyphams** [comment]
Hey @lailton now you can quickly look the JSON blob: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by lailton** [comment]
Wow, @huyphams,

Thank you for the fast fix!

Just a small consideration, It is better now I am able to see the content but maybe you can make it yet better.
what about to add an option View as JSON/TEXT/IMAGE into the right side?

<img width="1421" alt="Screen Shot 2019-05-03 at 3 19 16 PM" src="https://user-images.githubusercontent.com/39895255/57157435-14633700-6db7-11e9-98d9-a87eb447130e.png">

This way if I am looking for something fast, I don't need to go one by one record and see the Quick View.
I can just move the Record by arrows and then It will update the right side.

What do you think?
