### ISSUE TITLE
Remove default

### ISSUE THREAD

**Issue by dpustovarov** [TablePlus/TablePlus#1163]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB 10.3.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.3 (222)

3. The steps to reproduce this issue:
How to remove default value from column?
In other words make "`...descriptionIsApproved` tinyint(1) unsigned NOT NULL,"
instead of "`...descriptionIsApproved` tinyint(1) unsigned NOT NULL DEFAULT 0,"

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by dpustovarov** [comment]
<img width="892" alt="Screen Shot 2019-05-03 at 22 06 50" src="https://user-images.githubusercontent.com/10797699/57159898-ef3eea80-6def-11e9-8031-7bbadd3bb2dc.png">

**Comment by huyphams** [comment]
Hi @dpustovarov please download this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
And set the value to NULL, it will remove the default.
Thank you for the feedback, let me know if you're still seeing it.

**Comment by dpustovarov** [comment]
It's Ok. Thank you.
