### ISSUE TITLE
Native OSX tabs hide SQL tabs

### ISSUE THREAD

**Issue by AlexanderElyseev** [TablePlus/TablePlus#1164]
Hi!

The problem is that when you use native OSX tabs they culd hide SQL tabs (see the screencast).

1. Which driver are you using and version of it: 5.5.43-MariaDB-37.2 (doesn't matter)
2. Which TablePlus build number are you using: 2.3 (222)
3. The steps to reproduce this issue:
    1. Open two instances of Table Plus with multiple SQL tabs
    2. Menu -> Window -> Merge All Windows

Screencast: https://www.dropbox.com/s/qzbhbio89f1ymh8/0813c4b28f41-1.gif?dl=0

**Comment by huyphams** [comment]
Thanks @AlexanderElyseev the native tab is hasn't been supported yet, we're working on it.
