### ISSUE TITLE
Auto-complete for all column names when typing *

### ISSUE THREAD

**Issue by techon** [TablePlus/TablePlus#1168]
TOAD has this feature where if you type SELECT * FROM table_name 
The auto-complete allows for changing the * to list of all column names.
This would be hugely helpful in writing custom queries.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
For OSX, SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:
Feature request

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thank @techon, I'm implementing it now.

**Comment by huyphams** [comment]
Yes it's implemented @jim256
