### ISSUE TITLE
index display order is unstable

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1170]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:
open table structure view, refresh, the index display order is changing every time. it should in the order as in `show create table` output, `primary` key should always at the top.

**Comment by huyphams** [comment]
I've updated it, since detecting the original position is much harder, I ordered it using the alphabet as the temporary solution.

**Comment by huyphams** [comment]
Please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it then I will reopen this issue. Thank you for the feedback.

**Comment by georgexsh** [comment]
no, not right, `PRIMARY` should come at the first row, now it is on the last because it is in upper case.
