### ISSUE TITLE
MSSQL XML columns error

### ISSUE THREAD

**Issue by nukem666** [TablePlus/TablePlus#1173]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL 2017

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.3(222)

3. The steps to reproduce this issue:
Execute and SELECT query which returns a XML column returns this error:
Query 1 ERROR: User attempted a dbbind with mismatched column and variable types, 0 row affected

Noted: If the bug is related to data, please attach an example SQL data.
create table mytable(x xml)
select*from mytable

**Comment by huyphams** [comment]
Thanks @nukem666 let me fix it.

**Comment by huyphams** [comment]
Hi @nukem666 it seems to be fixed on the beta build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it.

**Comment by nukem666** [comment]
@huyphams , I still see the same issue in build 225, running the test SQL above.

**Comment by huyphams** [comment]
Which is the protocol version you using?
<img width="528" alt="Screen Shot 2019-05-10 at 2 20 41 PM" src="https://user-images.githubusercontent.com/3654622/57509595-d756f180-732e-11e9-9cb7-e6fb93eba7e3.png">

**Comment by nukem666** [comment]
I am using 74

**Comment by huyphams** [comment]
Please try again with the 70, I will try with the 74 and see what will happen, thank for the confirmation.
