### ISSUE TITLE
Connection thru Cloud SQL Proxy works, except when using "Backup" feature

### ISSUE THREAD

**Issue by ncernek** [TablePlus/TablePlus#1174]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Postgres 9.6.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 2.3 (222)

3. The steps to reproduce this issue:

Connect to a postges instance on Google Cloud SQL via Cloud SQL Proxy. (I know there's a lot to it).

I am able to access, query and edit the DB without any issue. However, when I run "Backup", I get the following error:

```
Dumping...
dump_pg_10.5: [archiver (db)] connection to database "cloudsql/project-name:us-west2:pg-instance:5432/dbname" failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by huyphams** [comment]
Thank you @ncernek let me check it.

**Comment by huyphams** [comment]
Hi @ncernek I've fixed it, now TablePlus can backup via socket (and also socket over an SSH tunneling).
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it.
