### ISSUE TITLE
Dump includes virtual generated columns

### ISSUE THREAD

**Issue by zoispag** [TablePlus/TablePlus#1176]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 222

3. The steps to reproduce this issue:

```sql
CREATE TABLE `contract_2018` (
  `id` int(11) NOT NULL,
  `version` int(11) NOT NULL,
  `data` json NOT NULL,
  `contract_date` date GENERATED ALWAYS AS (`data`->>'$.contractDate') VIRTUAL,
  `commodity` int(11) GENERATED ALWAYS AS (`data`->>'$.commodityId') VIRTUAL,
  `is_confirmed` tinyint(1) GENERATED ALWAYS AS (`data`->>'$.isConfirmed' = 'true') VIRTUAL,
  `approval_required` tinyint(1) GENERATED ALWAYS AS (`data`->>'$.isNeedsApproval' = 'true') VIRTUAL,
  `confirmation_nr` varchar(80) GENERATED ALWAYS AS (`data`->>'$.confirmationNumber') VIRTUAL,
  PRIMARY KEY (`id`,`version`),
  KEY `contract_date` (`contract_date`),
  KEY `commodity` (`commodity`),
  KEY `is_confirmed` (`is_confirmed`),
  KEY `approval_required` (`approval_required`),
  KEY `confirmation_nr` (`confirmation_nr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

I have the above table, with 3 fields (id (int), version (int), data (json)) and a handful virtual generated columns. Table export to SQL includes the generated columns as well. They should not be included.

(Btw, the virtual column definition cannot be viewed or edited via the UI. It's only visible in the structure definition dialog. I think it would be useful. I can make a separate ticket if you think it's necessary).

**Comment by huyphams** [comment]
I've fixed this bug. Thank you!

**Comment by MatanYadaev** [comment]
@huyphams It still happens on v4.0.2 with STORED columns (which are almost the same as VIRTUAL columns).

**Comment by TonyKrus** [comment]
It looks like it also still happens on the Windows version build 176, MySQL 8.0.26.

**Comment by madsem** [comment]
Happens to me too, macOS 11.5,  table plus Version 4.0.2 (374), mysql 8

cannot re-import the dump generated by table plus because it contains generated column data.

**Comment by huyphams** [comment]
Have you tried the lasted release @madsem

**Comment by madsem** [comment]
Hey @huyphams thanks for your speedy reply!
I just updated to Tableplus 4.1.2 (382) and the same thing happens, half way through the import I get an error popup:
`The value specified for generated column 'unique_iodku_hash' in table 'summary_landing_page_offers' is not allowed.`

**Comment by huyphams** [comment]
There is no way to fix the old exported file because it is a apart of the queries. Please try to export a new file and then re-import it.

**Comment by madsem** [comment]
I did that haha :)
After the update I exported fresh

**Comment by huyphams** [comment]
Could you please create a new issue with step to reproduce the issue and the data like above, when we can reproduce it we can fix it. Thank you

**Comment by huyphams** [comment]
If you have a chance @madsem, you could try this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
It should fix both stored and virtual columns.
Thanks

**Comment by huyphams** [comment]
This is macOS repo @TonyKrus however, if you have a chance, you can download this patch for Windows: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
it should fix the issue.

**Comment by TonyKrus** [comment]
Sorry for posting in the wrong repo and thank you for your answer

**Comment by madsem** [comment]
@huyphams sorry, it took a bit for me to test.

I just exported & then imported the same dump from last time, and it work like a charm!

Thanks a lot :)

**Comment by madsem** [comment]
PS: I am unsure if this behavior should change, I realized the import `created_at` timestamps where all from today.
BUT, that is because the table is set up to use the current timestamp on create.

So in theory it did what it was supposed to do... Only in a dump, you'd expect to have the same data/dates as in the original.

So maybe it's an idea to change this behavior for imports?

**Comment by huyphams** [comment]
I'm not sure that I understand you correctly, but you think that TablePlus alter table creation and row timestamp?

**Comment by madsem** [comment]
@huyphams sorry, wasn't clear enough.

What I'm saying is that my timestamp columns are created like this:
```sql
`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
```

Now after importing the dump, all of the data that was created yesterday, had it's `created_at` to todays date.
Which in theory is correct according to my schema, but when you export a dump to import it locally you would of course like to have an exact replica of the data.

So might be nice to have an option or so for that, what do you think?

**Comment by huyphams** [comment]
The data will be the same with the server because TablePlus doesn't alter any queries. So could you please check the generated query and see if there are created_at and updated_at values? Could you post here an example so I can reproduce it?

**Comment by madsem** [comment]
Here is the schema for one of the tables:
```sql
CREATE TABLE `summary_landing_pages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `visits` mediumint unsigned NOT NULL,
  `impressions` mediumint unsigned NOT NULL,
  `clicks` mediumint unsigned NOT NULL,
  `conversions` mediumint unsigned NOT NULL,
  `revenue_in_app_currency` mediumint unsigned NOT NULL,
  `spend_in_app_currency` bigint unsigned NOT NULL,
  `is_bot` tinyint(1) NOT NULL,
  `bot_name` varchar(40) NOT NULL,
  `traffic_type` tinyint(1) NOT NULL,
  `utc_hour_visited` tinyint unsigned NOT NULL,
  `avg_time_on_site` int unsigned NOT NULL,
  `landing_page_id` bigint unsigned NOT NULL,
  `language` varchar(40) NOT NULL,
  `referrer` varchar(500) NOT NULL,
  `city` varchar(80) NOT NULL,
  `state_name` varchar(80) NOT NULL,
  `country_code` varchar(80) NOT NULL,
  `browser_name` varchar(80) NOT NULL,
  `browser_version` varchar(80) NOT NULL,
  `os_name` varchar(80) NOT NULL,
  `os_version` varchar(80) NOT NULL,
  `device_brand` varchar(80) NOT NULL,
  `device_model` varchar(80) NOT NULL,
  `device_type` varchar(80) NOT NULL,
  `isp_name` varchar(80) NOT NULL,
  `isp_type` varchar(15) NOT NULL,
  `utm_campaign_id` varchar(80) NOT NULL,
  `utm_ad_group_id` varchar(80) NOT NULL,
  `utm_criterion_id` varchar(80) NOT NULL,
  `utm_ad_id` varchar(80) NOT NULL,
  `landing_page_id_for_hashing` int unsigned NOT NULL,
  `unique_iodku_hash` binary(16) GENERATED ALWAYS AS (unhex(md5(concat_ws(`date`,`is_bot`,`bot_name`,`traffic_type`,`utc_hour_visited`,`language`,`referrer`,`country_code`,`city`,`state_name`,`browser_name`,`browser_version`,`os_name`,`os_version`,`device_brand`,`device_model`,`device_type`,`isp_name`,`isp_type`,`utm_campaign_id`,`utm_ad_group_id`,`utm_criterion_id`,`utm_ad_id`,`landing_page_id_for_hashing`)))) STORED,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `landing_page_summary_unique_iodku_hash` (`unique_iodku_hash`),
  KEY `landing_page_summary_where_index` (`landing_page_id`,`is_bot`,`traffic_type`,`date`),
  CONSTRAINT `summary_landing_pages_landing_page_id_foreign` FOREIGN KEY (`landing_page_id`) REFERENCES `landing_pages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4096 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

and here is a dump for just this table. 
[forhuypham.gz](https://github.com/TablePlus/TablePlus/files/7170673/forhuypham.gz)

The `created_at` field will all be from today, but in the dump file you see the data starts at the 11th.
(Running your custom tableplus version from dropbox)

**Comment by huyphams** [comment]
I see that the key `created_at` is missing in your dump file, how did you get that file, I could not reproduce the issue because my exported file has the `created_at` in the insert statement.

**Comment by madsem** [comment]
OH, yeah you're right.
I did not check if the created_at is included in the file.

It seems Tableplus does not export it, maybe because of the `DEFAULT CURRENT_TIMESTAMP,`?

The file is a direct export using TablePlus > Export > Sql > export button

**Comment by huyphams** [comment]
> It seems Tableplus does not export it, maybe because of the DEFAULT CURRENT_TIMESTAMP,?
No it does not relate to this issue.

> The file is a direct export using TablePlus > Export > Sql > export button

I did the same but my file has `created_at` value, can you make a gif? I think I missed something.

**Comment by madsem** [comment]
I've made a video for you, how I export the example table.
The resulting file does not have the `created_at` timestamp and looks exactly like the one i posted yesterday.

The table I exported in the video, is the one of which I posted the schema above...


https://user-images.githubusercontent.com/3166991/133553633-540708d4-4ed2-4651-878e-16f4696f9d2a.mov

**Comment by madsem** [comment]
<img width="1159" alt="Screen Shot 2021-09-16 at 7 18 05 AM" src="https://user-images.githubusercontent.com/3166991/133553844-97bcc9eb-df94-477e-8388-15f3748f5fa7.png">

Here's a screenshot of the file that was exported in the video, no created_at

**Comment by madsem** [comment]
<img width="420" alt="Screen Shot 2021-09-16 at 7 32 42 AM" src="https://user-images.githubusercontent.com/3166991/133555262-0f1810df-ba6b-4a11-b8b1-59cdb9f286fd.png">

And this is how the table looks like after importing (actually all tables that have current_timestamp set as column default)
All the created at timestamps are set to today, while the updated at shows the real dates.

So I still think this is because of the column default, at least related :P


<img width="1255" alt="Screen Shot 2021-09-16 at 7 34 34 AM" src="https://user-images.githubusercontent.com/3166991/133555428-c7986068-584b-45b5-824c-70662754c26a.png">

**Comment by huyphams** [comment]
Thanks for the update. It has nothing to do with the column default. The exported file is missing the field `created_at`
So that is why the database use the default value. 

So we must figure out why it does not contains the `created_at`, I can't reproduce the issue, I'm confused now.

**Comment by huyphams** [comment]
Ok, I figured out. The new MySQL 8 has a different syntax for virtual column. Please wait for the hotpatch.

**Comment by huyphams** [comment]
Please try this patch @madsem it fixes the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thank you!

**Comment by madsem** [comment]
@huyphams thanks, you're the man! :) It all works perfectly now.

PS: I meant that I was assuming that table plus doesn't export the created_at column because of the default, not that mysql doesn't dump it. 

PSPS: I'm super happy with my TablePlus subscription btw. it's an amazing product that you've created here.
