### ISSUE TITLE
ability to set/customize row detail sidebar font

### ISSUE THREAD

**Issue by necmettin** [TablePlus/TablePlus#1180]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v2.3, build 222

3. The steps to reproduce this issue:
Just open the row details sidebar in any table view. I want to be able to customize row detail sidebar's font. This is not a bug, but a feature request.

**Comment by huyphams** [comment]
Thanks, it should be the same font as table-data.

**Comment by huyphams** [comment]
Hey @necmettin it's fixed now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It will be released in the next update.
