### ISSUE TITLE
Cannot restore MySQL with multiple spaces in path

### ISSUE THREAD

**Issue by cmorbitzer** [TablePlus/TablePlus#1182]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 222

3. The steps to reproduce this issue: Try to restore a SQL dump that is located at a path with multiple spaces.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/5883755/57799828-8f144680-7715-11e9-9fb1-6f917ac7ac2a.png">

The directory above is actually "Main Street Marketing"

**Comment by huyphams** [comment]
Hey @cmorbitzer I've fixed that bug recently on the beta build, which can be downloaded here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

Let me know if you're still seeing it then I will reopen the issue. Thank you for the feedback.
