### ISSUE TITLE
MongoDB Update String ID

### ISSUE THREAD

**Issue by alexmarmon** [TablePlus/TablePlus#1183]
1. Which driver are you using and version of it: **Mongo 4.0.2**

2. Which TablePlus build number are you using: **227**

3. The steps to reproduce this issue: Attempt to update a document that has a String ID

Noted: If the bug is related to data, please attach an example SQL data.

Example query:
```
{
  "update": "collectionName",
  "updates": [
    {
      "q": { "_id": 6cf2434f },
      "u": { "$set": { "field": "value" } },
      "multi": false
    }
  ]
}
```

Error:
```
Got parse error at "c", position 68: "INVALID_NUMBER"
All changes were reverted (DDL statements can't be reverted).
```

**Comment by alexmarmon** [comment]
@huyphams Do you guys allow any contributions? Happy to try and put a PR together

**Comment by huyphams** [comment]
Thank you @alexmarmon I fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it 👍
