### ISSUE TITLE
`shift`+`tab` eat characters

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1189]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
222

3. The steps to reproduce this issue:

config as tab width 4, ident with spaces

```
  join
```
after `shift`+`tab`:
```
in
```

**Comment by huyphams** [comment]
I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks @georgexsh

**Comment by huyphams** [comment]
I released the build 226 (official) which includes this fix. The Setapp version is on its way.
