### ISSUE TITLE
"Recently open" list is empty after switching DB

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#119]
Steps:
- Open first DB, open any table - it will be added to "Recently open" list
- Press shift+cmd+d and switch to another DB
- Open any table - it will be added to "Recently open" list
- Press shift+cmd+d and switch back to first DB

Result - "Recently open" list is empty

It would be great if "Recently open" list will be unique per connection+DB pair.

Thanks

**Comment by huyphams** [comment]
Hi @PVGrad 
Yeah that's nice idea, you're correct, `Recently open list` should be unique per connection+DB pair.
I will include this fix on next release.
- Huy.

**Comment by huyphams** [comment]
Hi @PVGrad ,

This feature was done on build 73. it will be released on Monday 🎉🎉🎉

Thanks 👍.
- Huy.
