### ISSUE TITLE
Please stop doing popups for updates.

### ISSUE THREAD

**Issue by envygeeks** [TablePlus/TablePlus#1190]
I understand the need to inform me of an update, and I'm happy to get notifications about updates, but when I'm doing work, and you decide to popup and tell me about an update, or I leave the window to go do somethign and then come back and there is a popup and immediately disrupts me... I eventually get annoyed, and stop using the product.

Can we please get something more out of the way like the way that Sketch handles it?

**Comment by huyphams** [comment]
Hey @envygeeks thanks for the feedback. I see Telegram handles it pretty well. I will bring it into TablePlus. Sorry for the annoying!

**Comment by bernhard-efler** [comment]
Would be great when it can be handled without a popup! 
But maybe in the meantime the time between popups can be stretched? After "Remind me later" it reappears to soon for me.

**Comment by huyphams** [comment]
I've updated it on the build 252. TablePlus will not show a popup if you turn off update notification.

**Comment by envygeeks** [comment]
Thanks!
