### ISSUE TITLE
improve `cmd+p`

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1192]
support `ctrl+p`/`ctrl+n` to navigate up and down through the list.
besides, I want an "always open in new tab" option, maybe `ctrl+o`? :P

**Comment by georgexsh** [comment]
@huyphams any schedule on this feature?

**Comment by huyphams** [comment]
You can move between the results by pressing the arrows (Up/Down). And you can open a table in a new tab by holding command.
Download the build which supports the feature: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you have any further questions.

**Comment by georgexsh** [comment]
@huyphams <kbd>cmd</kbd>+<kbd>click</kbd> works, but no `ctrl+p/ctrl+n` support? it is very common in macOS.

**Comment by huyphams** [comment]
I've added it too and it will be available in the next update.

**Comment by georgexsh** [comment]
@huyphams thanks very much!
