### ISSUE TITLE
Can't connect to vagrant server after update

### ISSUE THREAD

**Issue by notasgoodasyou** [TablePlus/TablePlus#1194]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.4 (build 228)

3. The steps to reproduce this issue:
All was working prior to the past two updates. This was connecting "Over SSH" which worked before and now it does not. I'm able to connect to the box using terminal or another mysql client.

![Screen Shot 2019-05-20 at 8 41 25 AM](https://user-images.githubusercontent.com/27873449/58034279-1299b300-7adb-11e9-8924-d596bd60750b.png)

![Screen Shot 2019-05-20 at 8 42 18 AM](https://user-images.githubusercontent.com/27873449/58034420-686e5b00-7adb-11e9-88b3-0857fabe9860.png)

**Comment by huyphams** [comment]
Thank you @notasgoodasyou for the feedback, I will come back to this thread with a debug build shortly.
Meanwhile, you can rollback to the older build here: https://tableplus.com/blog/2017/02/changelogs.html
I apologize for any inconvenience

**Comment by huyphams** [comment]
Hi @notasgoodasyou here is the debug build: https://www.dropbox.com/s/qdijo59365vsl97/TablePlus-Debug.dmg?dl=0
If you have a chance, please follows this guide: https://tableplus.com/blog/2018/10/failed-to-connect-via-ssh-tableplus.html
 and send me the log, I appreciate your help.
My email is nick@tableplus.com

**Comment by notasgoodasyou** [comment]
I sent the log to your email.

**Comment by huyphams** [comment]
Sorted via email, the actual issue is TablePlus didn't respect the user input, end up using the wrong port (which was configured in ssh-config).
