### ISSUE TITLE
Feature Request: allow replacement of newlines within values for CSV exports

### ISSUE THREAD

**Issue by bpartridge** [TablePlus/TablePlus#1196]
Currently, when exporting a table to CSV where certain values contain newlines, the resulting CSV can be very difficult to open in other tools; for instance, Excel will interpret newlines as the start of a new row.

Other tools such as Postico allow you to export to CSV with an "allow line breaks" option - if unset, it replaces '\n' within values with ' '.

<img width="840" alt="Screenshot 2019-05-20 15 30 25" src="https://user-images.githubusercontent.com/20748/58046760-32999880-7b14-11e9-9d05-8ccd8f308510.png">

As this loses data, it's something that shouldn't be a default option for CSV exports. But it would be tremendously helpful, especially when trying to hand off exports to non-technical colleagues.

**Comment by huyphams** [comment]
Thank you for the idea, let me add it.

**Comment by huyphams** [comment]
Hey @bpartridge I've added that feature, please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
You can keep using it until the next release. It can self-update.
