### ISSUE TITLE
MSSQL unable to assign declare variable using select statement after upgrade

### ISSUE THREAD

**Issue by EugeneFoo** [TablePlus/TablePlus#1197]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Azure SQL.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Latest Version 2.4 (228)

3. The steps to reproduce this issue:

Run the following query in Azure SQL connection:

DECLARE @username nvarchar(255) = '';

SELECT @xxx = username
from users
where userid = 1;

*In previous version still working, after upgrade all my declare variable will become:
Must declare the scalar variable "@xxx".

Using Microsoft Azure Data Studio working fine for variable assigning.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I'm not sure about the example, I've tested with the build 222 (which is the previous release) and it produced the same error. but when I quoted it into a begin end
```
BEGIN
DECLARE @username nvarchar(255) = 'id';
SET @username = 'id';
SELECT @username
from Memes;
END
```
It works

**Comment by EugeneFoo** [comment]
@huyphams thanks for that, i think is this BEGIN END problem.
