### ISSUE TITLE
[Question] Mongodb query docs

### ISSUE THREAD

**Issue by alexmarmon** [TablePlus/TablePlus#1198]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
mongodb

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
229

3. The steps to reproduce this issue: N/A

Noted: If the bug is related to data, please attach an example SQL data.

Is there any documentation for using the SQL field for mongo? I was guessing I'd be able to query data somehow but nothing I've tried seems to work. This may be the wrong place for a suggestion but if I could write mongo shell queries/aggregations in that section It would be amazing.

**Comment by huyphams** [comment]
No, this is the right place for report bug/suggest feature. And yes, bringing mongo shell to TablePlus is already in our plan.

**Comment by alexmarmon** [comment]
Awesome, thank you!

**Comment by alexmarmon** [comment]
@huyphams Any idea when this feature will be slotted on the roadmap?
