### ISSUE TITLE
View structure parenthesis

### ISSUE THREAD

**Issue by volkanozyildirim** [TablePlus/TablePlus#1199]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.12
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):227

3. The steps to reproduce this issue:
- Create  a view with multiple joins and save.
- Return to structure view
- You will see many parenthesis that you didn't write

Noted: If the bug is related to data, please attach an example SQL data.

`FROM ((((((((((((((((((((((`instreet_prod`.`catalog_product_relation` `cpr`
						JOIN `instreet_prod`.`catalog_product_entity` `cpe` ON ((`cpr`.`parent_id` = `cpe`.`row_id`)))
			LEFT JOIN `instreet_prod`.`catalog_product_entity_varchar` `pev1` ON (((`pev1`.`row_id` = `cpe`.`row_id`) and(`pev1`.`attribute_id` = 73))))
	LEFT JOIN `instreet_prod`.`catalog_product_entity_varchar` `pev2` ON (((`pev2`.`row_id` = `cpe`.`row_id`) and(`pev2`.`attribute_id` = 227))))
	LEFT JOIN `instreet_prod`.`catalog_product_entity_varchar` `pev4` ON (((`pev4`.`row_id` = `cpe`.`row_id`) and(`pev4`.`attribute_id` = 219))))
	LEFT JOIN `instreet_prod`.`catalog_product_entity_int` `pei` ON (((`pei`.`row_id` = `cpe`.`row_id`) and(`pei`.`store_id` = 0) and(`pei`.`attribute_id` = 145))))
	LEFT JOIN `instreet_prod`.`eav_attribute_option_value` `eov` ON (((`eov`.`option_id` = `pei`.`value`) and(`eov`.`store_id` = 0))))
	LEFT JOIN `instreet_prod`.`catalog_product_entity_int` `pei2` ON (((`pei2`.`row_id` = `cpe`.`row_id`) and(`pei2`.`store_id` = 0) and(`pei2`.`attribute_id` = 83))))
	LEFT JOIN `instreet_prod`.`eav_attribute_option_value` `eov2` ON (((`eov2`.`option_id` = `pei2`.`value`) and(`eov2`.`store_id` = 0))))
	LEFT JOIN `instreet_prod`.`catalog_product_entity_decimal` `ped` ON (((`ped`.`row_id` = `cpe`.`row_id`) and(`ped`.`attribute_id` = 81))))
	LEFT JOIN `instreet_prod`.`catalog_product_entity_decimal` `ped2` ON (((`ped2`.`row_id` = `cpe`.`row_id`) and(`ped2`.`attribute_id` = 78))))
	LEFT JOIN `instreet_prod`.`catalog_product_entity_decimal` `ped3` ON (((`ped3`.`row_id` = `cpe`.`row_id`) and(`ped3`.`attribute_id` = 77))))
`

**Comment by huyphams** [comment]
Hi @volkanozyildirim that is the view definition which is returned by MySQL.
SHOW CREATE TABLE `your_database`.`your_view_name`;

**Comment by volkanozyildirim** [comment]
Problem is i didn't write sql with parenthesis and this only happen when i edit or create view structure in TablePlus

**Comment by volkanozyildirim** [comment]
Here is a screen record https://ufile.io/bhnb4li8

**Comment by huyphams** [comment]
Thank @volkanozyildirim for the screencast, but as I mentioned above, that query is generated by MySQL, which is converted from your view create a statement.
TablePlus didn't participate in the process.
The creation syntax which is generated by TablePlus always have this prefix:
<img width="607" alt="Screen Shot 2019-05-21 at 4 25 17 PM" src="https://user-images.githubusercontent.com/3654622/58084420-0a2d9f00-7be5-11e9-83ad-b2cac0f990ea.png">
