### ISSUE TITLE
Unable to edit row after running SELECT query

### ISSUE THREAD

**Issue by gokninski** [TablePlus/TablePlus#120]
I'm pretty sure this worked before but not 100%.

If you select a record using a select statement from the SQL query window and then try and edit a field for that record in the results panel then it will allow you to click into the field but not commit the actual change.

Running latest version Version 1.0 (72) with PostgreSQL 9.6.1.

Many thanks,

G :)

**Comment by huyphams** [comment]
Hi @gokninski 
We are not allow to edit value in the query result window. Because in this case, we didn't know the table contains that rows.

For example:
```
SELECT
    kc.ordinal_position AS ordinal_position,
    tc.table_schema AS table_schema,
    tc.table_name AS table_name,
    tc.constraint_name AS constraint_name,
    kc.column_name AS column_name
FROM
    information_schema.table_constraints tc,
    information_schema.key_column_usage kc
WHERE
    tc.constraint_type = 'PRIMARY KEY'
    AND kc.table_name = tc.table_name
    AND kc.table_schema = tc.table_schema
    AND kc.constraint_name = tc.constraint_name
ORDER BY
    kc.ordinal_position ASC;
```
The result are:
<img width="1305" alt="screen shot 2017-11-23 at 6 47 26 pm" src="https://user-images.githubusercontent.com/3654622/33171468-c73a5d18-d07e-11e7-9d55-4189f03cfa71.png">
In this case, we can't edit value of rows.

But you're right, it would be great if we can edit value from there. I'm thinking about it.

Huy.

**Comment by gokninski** [comment]
Thanks for your reply Huy.  This is how I personally use database browsers for making quick edits - in other browsers I have used they must perform a check to see whether that row is still correct as I have seen a message come up and say something along the lines of 'this row has changed, please refresh'.

Many thanks,

Greg :)

**Comment by PVGrad** [comment]
As I noticed in other apps - they allow to edit row after select if select has primary key in it, so in this case it is safe to perform edit

**Comment by huyphams** [comment]
Hi @gokninski @PVGrad 

This feature will be included in next #build74 
Thank you guys <3

- Huy.

**Comment by huyphams** [comment]
💃🏻🎉
<img width="1387" alt="screen shot 2017-11-30 at 4 41 31 pm" src="https://user-images.githubusercontent.com/3654622/33424094-585a8304-d5ed-11e7-9570-848a06eb0c6e.png">

**Comment by taylorotwell** [comment]
I still can't get this to work on latest build (downloaded today). Is there some special process to get this to work?

**Comment by huyphams** [comment]
Hi @taylorotwell 
Currently, we only supports PostgreSQL on this feature, other driver will come later. Because this feature depend on official support from database driver. Which driver are you on?

Huy.

**Comment by taylorotwell** [comment]
I use MySQL and SQLite typically. Thanks.
