### ISSUE TITLE
Structure: When a second column could not be created, the first column is still not commited.

### ISSUE THREAD

**Issue by CodeBrauer** [TablePlus/TablePlus#1201]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.35
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
228
3. The steps to reproduce this issue:

- create a table
- commit changes <kbd>cmd</kbd>+<kbd>s</kbd>
- add 2 columns
  - one named `foobar`
  - one named `date` *to produce an error*
- commit changes
- See an error that `ALTER TABLE` failed
- both columns are still green / ready for commit
- fix the error by renaming the column `date` to `date_foo`
- See an error that `alter table` failed (Because `foobar` was created already)

After commit TablePlus should check the single `ALTER TABLE` succeeded or not. So the commit shows that the first column was created successfully but the second statement failed.

![Bildschirmfoto 2019-05-22 um 11 25 23](https://user-images.githubusercontent.com/2059754/58328034-608f1d80-7e31-11e9-9a4b-51c3b8e957ac.png)

**Comment by huyphams** [comment]
This build should fix the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
