### ISSUE TITLE
highlight matching parentheses

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1202]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
226

3. The steps to reproduce this issue:

this is how parenthese highlight works in sublime:

<img width="198" alt="CleanShot 2019-05-22 at 22 38 29@2x" src="https://user-images.githubusercontent.com/32751/58183703-58749800-7ce2-11e9-9379-e631e650d0de.png">

please add this feature

**Comment by AlessandroLacroce** [comment]
+1 for this!

**Comment by fgilio** [comment]
This would be fantastic, it's really difficult to dig into complex queries without this feature and because the beautifier wont align matching parentheses either

**Comment by huyphams** [comment]
I've updated the behavior, TablePlus now will highlight the parentheses. Please wait for the next release!
<img width="1074" alt="braces" src="https://user-images.githubusercontent.com/3654622/89010291-7d2dbc00-d338-11ea-84fe-df0060c7a595.png">
