### ISSUE TITLE
Comments engage Alert/Safe Mode 2 confirmation

### ISSUE THREAD

**Issue by dom0do** [TablePlus/TablePlus#1203]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server DBVERSION_74

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.4 (228)

3. The steps to reproduce this issue:
With Alert Mode 2 or Safe Mode 2 engaged, execute a SELECT query that contains a comment (-- or /**/) or a query that is only comment. You will be prompted for confirmation though SELECT (or just a comment) is the only thing being executed.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by idris** [comment]
Yup, this is very annoying.  Also, I think `EXPLAIN` queries in Postgres should not cause the alert.

**Comment by dom0do** [comment]
Patch notes for build 233 say:

> Advanced safe mode now can ignore Explain queries.

but I have confirmed that build 233 still does not properly ignore SQL Server comments, so this issue persists.

**Comment by huyphams** [comment]
Could you please post more details with the data to reproduce the issue @dom0do thank you!

**Comment by gbrlmza** [comment]
Hi, I'm having the same issue, but as a workaround you can prepend a ; to the SELECT query. That way the ; acts as a separator and the comment is not selected.

**Comment by dom0do** [comment]
Thanks for the workaround @gbrlmza! It looks a bit funny, but it does allow me to use Safe Mode properly.

It would be cool if this were flagged as an Enhancement or Bug so it's on the radar.

**Comment by huyphams** [comment]
Hey, I fixed this bug, TablePlus will ignore the comment! (We're migrating to the Apple business account so I can't build a hotfix build at the moment.)

**Comment by huyphams** [comment]
You guys can download the hotfix build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
