### ISSUE TITLE
Feature Request: Limit indicator

### ISSUE THREAD

**Issue by DanHulton** [TablePlus/TablePlus#1205]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.2 (210)

Request description:

I have wasted probably collectively a few hours wondering what phantasm has gotten into my system and caused my inserts to not persist, when in truth the problem was that I had added a limit to my query and that's why I only saw 50 items.

Sure, this is on me for not remembering/noticing the little "1-50 of 180 rows" indicator at the bottom, but *boy* is it subtle.  It'd be nice if there were something a little bit more obvious, like a non-selectable row or blank space after the data table, indicating that there are more rows available.

**Comment by huyphams** [comment]
Thanks @DanHulton, and sure, I will add it.

**Comment by huyphams** [comment]
Hi @DanHulton now TablePlus will show `auto limited xxx rows` if you enabled auto limited feature! Let me know your thoughts.
<img width="1399" alt="limit" src="https://user-images.githubusercontent.com/3654622/58241452-39741580-7d77-11e9-9143-820d353f4392.png">

**Comment by DanHulton** [comment]
Looks great!  Thanks for the quick turnaround on this!
