### ISSUE TITLE
Invalid column name charset

### ISSUE THREAD

**Issue by xavi-dev** [TablePlus/TablePlus#1208]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server 2008

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.4 (229)

3. The steps to reproduce this issue:
The dropdown of columns to filter has invalid column name (when the name has latin characters)

The column name is **Nº order**, the dropdown shows **N¬∫ order** and the error is `Msg: 207, Line 1, State: 1, Level: 16 Invalid column name 'N¬¨‚à´ order'.`

**Comment by huyphams** [comment]
Thanks @xavi-dev I will double check it.

**Comment by huyphams** [comment]
Thank you so much @xavi-dev I fixed it if you have a chance please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it!

**Comment by xavi-dev** [comment]
It's working fine now. Thanks!
