### ISSUE TITLE
Connection info illegible when using dark theme

### ISSUE THREAD

**Issue by gokninski** [TablePlus/TablePlus#121]
Hello there,

Recently started using the dark them as its much easier on the eye but the connection info is very hard to read because its white on green, and also the text within the pop-up is broken.

<img width="756" alt="screen shot 2017-11-27 at 13 42 27" src="https://user-images.githubusercontent.com/17249667/33269570-11438aea-d379-11e7-96b5-8b7a13e8f0a0.png">

Many thanks in advance,

Greg :)

**Comment by huyphams** [comment]
Hi @gokninski 

Thank you for letting me know, I noticed that the Apple Cocoa UI didn't render the same UI on 10.11 10.12 and the newest 10.13 and some components need to restart the app to apply the dark theme completetly.
Currently, we are tuning the dark theme, we will double check for all the OSX version over again.

Huy.
