### ISSUE TITLE
TablePlus does not remember backup options

### ISSUE THREAD

**Issue by necmettin** [TablePlus/TablePlus#1210]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v2.4 build 228

3. The steps to reproduce this issue:
- Backup a database connection. Set options, for example `--compress`, `--routines`, `--add-drop-table`, `--lock-tables=false`. Or `--compress`, `--routines`.
- After the backup finishes, go back to the backup screen again. Now you will only see `--compress`, `--routines`, `--lock-tables=false` in options.
- Regardless of what options you left with, you always get the same three.

4. What would be the correct behavior?
The correct, user-friendly behavior would be to remember whatever options I have left the app with.

**Comment by huyphams** [comment]
I improved it, now TablePlus will remember the last used options. it will be included in the next release!
