### ISSUE TITLE
[Feature request] Safe mode enabled via connection settings

### ISSUE THREAD

**Issue by cjke** [TablePlus/TablePlus#1211]
Love TablePlus, and love the Safe mode feature recently added. 

Would it be possible to set it on the connection pane? Possibly under the "tag" dropdown?

My thought process:

- Everything else about a connection is stored here (tags, status, production flags), so makes sense to have here. The first few times I used safe mode, I didn't realise it persisted from session to session. From a confidence point of view, I'd like to set it as part of the connection settings and know I am entering the database with it on. 
- For some client production databases, I don't want to ever open it without safe mode on, I want to set it before even opening a connection 

Cheers!

![image](https://user-images.githubusercontent.com/884065/58450184-26838b80-8151-11e9-8532-5900406b6ae0.png)

**Comment by LauLaman** [comment]
+1 
 just renewed my licence in the hopes this feature was added (i was 48 updates behind)

**Comment by huyphams** [comment]
It had been added long time ago
<img width="612" alt="Screen Shot 2022-01-20 at 7 35 34 AM" src="https://user-images.githubusercontent.com/3654622/150240897-6c394c00-22cf-40b2-bca0-bceb516182a5.png">
