### ISSUE TITLE
[Feature Request] Open SQLite Database Directly From Finder

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1212]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.4 (229)

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

When opening an SQLite file directly from Finder, the database is only opened directly, when TablePlus is already running. If not, the "Open Connection" window is shown and has to be closed before working with the database file.

It would be great if TablePlus would present the database window always directly when opening the database from the Finder.

**Comment by huyphams** [comment]
I just tested on my setup and the `database window` always on the top, (the Welcome screen is still there) but I think I should hide it.

**Comment by huyphams** [comment]
Hi, you can try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
TablePlus now will close the Welcome Screen after handling an URL/file.

**Comment by huyphams** [comment]
Hey thanks @chrschmitz I updated the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I figured out that the root cause is the loading priority during the initialize.

**Comment by chrschmitz** [comment]
Unfortunately this does not solve the issue -- at least on my machine. Same problem as before.

**Comment by huyphams** [comment]
I uploaded the wrong build 😛 you can download again with the same link above. Thank you, please let me know the result!

**Comment by chrschmitz** [comment]
You made it! Thanks a lot!

Cheers,
Chris
