### ISSUE TITLE
PostgreSQL 11.3 tables are not displaying

### ISSUE THREAD

**Issue by lieroes** [TablePlus/TablePlus#1213]
PostgreSQL 11.3 / Build 228

Hi, I have two databases based on driver 11.2 and 11.3.
11.2 works well but in 11.3 I can't see any tables in left sidebar but select queries are works.

Thank you!

**Comment by huyphams** [comment]
Hey @lieroes thank for the feedback, TablePlus ran this query in order to get the table list, c could you please run it and let me know the result?

```
SELECT t.oid AS type_oid,t.typname AS type_name,e.enumlabel AS type_define FROM pg_type AS t JOIN pg_enum AS e ON e.enumtypid=t.oid;
(SELECT table_name, table_schema, table_type FROM information_schema.tables) UNION (SELECT c.relname AS table_name, n.nspname AS table_schema, 'MATERIALIZED VIEW' FROM pg_catalog.pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = 'm');
```

**Comment by lieroes** [comment]
Running this query I receive all tables from 4 different schemes. In my sidebar displayed only from scheme "public", how could I change required schema?

**Comment by huyphams** [comment]
it's on the bottom left @lieroes

**Comment by lieroes** [comment]
Thank you - it's helps :)
TablePlus is awesome! Definitely change all my MySQL databases from SequelPro :)
Have a nice day!
