### ISSUE TITLE
beautify bug with comments

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1214]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

228

3. The steps to reproduce this issue:

```
order by
  i.id desc
# limit 100
```
became
```
order by
  i.id desc #
limit 100
```
obviously, it is wrong.

**Comment by huyphams** [comment]
Sorry for being late.
Hi, the bug has been addressed in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue.
