### ISSUE TITLE
Truncate in Postgres shouldn't show dialog if no identity fields or cascading tables

### ISSUE THREAD

**Issue by kralcifer** [TablePlus/TablePlus#1216]

**Comment by kralcifer** [comment]
I guess it's fine.  mostly I just wanted to not have to do an additional mouse click, but the default enter with keyboard does what I want so it's fine.

**Comment by huyphams** [comment]
I think I can improve it by adding a shortcut key (just like the delete and shift-delete to delete tables.)

**Comment by huyphams** [comment]
I just added the shortcut for truncating: Option + Delete. The shortcut for delete item is Command + Delete or simply delete. Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="322" alt="delete" src="https://user-images.githubusercontent.com/3654622/58651336-3e1e6800-833b-11e9-8549-2b84954076b9.png">
