### ISSUE TITLE
Emoji are changed to ????

### ISSUE THREAD

**Issue by doubleforte** [TablePlus/TablePlus#1219]
I'm using Maria DB (10.1.40-MariaDB) as my driver.
TablePlus 2.4 (228). Trial version.
macOS 10.14.5.

My TEXT column has character_set as utf8mb4 and collation as utf8mb4_unicode_ci.

If I use an emoji and commit, it changes the emoji to "????". If I do the same process in other editors (SequelPro, Querious, or even via php) it works as expected and my emoji doesn't get mangled. Until I edit it in TablePlus, then it is displayed as "?" and destroyed upon save.

Help? I dig the app, but can't use it if it will break all my emoji.

**Comment by huyphams** [comment]
Hi, please choose the correct view encoding.
<img width="612" alt="Screen Shot 2019-06-01 at 7 52 40 AM" src="https://user-images.githubusercontent.com/3654622/58741375-3eedf180-8442-11e9-8ad4-9b037ba832ac.png">

**Comment by Gompje** [comment]
Hi @huyphams, run into this issue as well. Had to move a database to another server and the emoij were gone. I managed to work around the issue with these steps
1. open connection window like you said, make sure the utf8mb4 is set
1. check if the emoij are displayed correctly
1. select all tables
1. hit export
1. select sql, select all except gzip
1. go to other database + server
1. make sure the connection is set to the right encoding like above
1. restore
1. from sql dump
1. select the generated .sql file
1. this confused me a bit, but you have to select utf8 as encoding (the other one is just missing)
1. now you should have emoij

this was the only way I could get the emoij to export/import. using backup didn't work - and I struggled for a while until I realized I didn't even see the emoij in the datacolumn. 

I use sequel pro before tableplus. Never had this issue, I think they must set the correct encoding based on what is defined as collation for the database. Not perfect either, but maybe this can be a default? aka keep it that you can change it, but set it to default of the db setting?

I'm not sure why the sql dump didn't work though.

Or why I could not select the utf8mb4 setting on import.

**Comment by huyphams** [comment]
Hi @Gompje thank you for the details, TablePlus does append the encoding in the dump file. Have you tried to use the backup/restore feature instead of export/import dump? I will look into the export/import feature tomorrow (it's late now) to figure it the issue.
<img width="365" alt="Screen Shot 2019-06-05 at 12 06 10 AM" src="https://user-images.githubusercontent.com/3654622/58898866-bdd67900-8725-11e9-8535-2a4919e45f22.png">

**Comment by Gompje** [comment]
Yes I did, but then I had either ??, white spaces or raw codes (not sure when each happend, tried many combos) but never got emoij -- or it must have been something I didn't try ;) 

Thanks for looking into it. I managed to use my work around for now, but I still have to move a bunch of databases, it would be nice to reduce the steps/hassle/confusion.

**Comment by huyphams** [comment]
I just released that I didn't add the MySQL 8.0 for backup and restore (MySQL 8 supports utf8mb4). Now, I added it on this build:  https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
You can backup/restore with full support emoji.

**Comment by Gompje** [comment]
I was exporting from mysql 5.7 to mariadb 10.x. Normally they both support utf8mb4, no?

**Comment by huyphams** [comment]
I'm not sure, I have a MySQL 5.7 but I can't use the emoji. Btw, I will take a look into the import/export tmr

**Comment by Gompje** [comment]
Well I've tested this new build with a quick export of the now new mariadb, to a local docker (also mariadb) with the dump feature. When I choose mysql 8, it doesn't work at all (kinda obvious since its mariadb but welll testing is testing ;) ) And when choosing mysql 5.7 I'm getting the same results as before, when I used the backup option.

I have no mysql 8 instances running, the other ones are each 5.7 but this machine doesn't have the connections set yet (hint: a iCloud sync of those would be HEAVEN!)  

Let me know if I can test something else to help you out. :)

Thanks for making this app! it was looooong overdue and I've literally been waiting ages for a good database management app on mac.

**Comment by Gompje** [comment]
I think it was introduced in 5.4? Or was it 5.6? Definably somewhere around 2015; I remember that clearly. Was kinda 🥳 I could add emoji support to my app. Emoji was a  huge must back then, now it’s just expected.

**Comment by huyphams** [comment]
I'm back, I read the sequel pro code, nothing special except this.
<img width="914" alt="export" src="https://user-images.githubusercontent.com/3654622/59090883-3ad93c80-8938-11e9-9e78-d2880b704132.png">
But TablePlus does the same thing, it will write the view encoding (which is selected by the menu above) into the export file.

`this confused me a bit, but you have to select utf8 as encoding (the other one is just missing)` => This is the `file encoding`, the utf8mb4 is the database encoding. I should have renamed it to `file encoding`.

**Comment by huyphams** [comment]
Please let me know if anyone still seeing this issue.

**Comment by greatestview** [comment]
I am still seeing this issue. For reproduction:

## Versions and Settings
- TablePlus Version 3.1.2
- MariaDB 10.3.19, so working in MySQL 5.7 mode
- `Connection` -> `View Using Encoding` set to `utf8mb4`
- I’ve created a test sql file: [emoji test table.sql.gz](https://github.com/TablePlus/TablePlus/files/4371280/emoji.test.table.sql.gz)

## Steps
1. Import the sample SQL file attached here into a new database via `File` -> `Import` -> `From SQL Dump...`
2. Select encoding `utf8` in Import SQL Wizard, click `Import`. The table `my_table` should contain one row with three different emojis.
3. Select `File` -> `Export...`  -> `SQL`, check all checkboxes and click `Export...` and choose a filename.
4. Import the exported SQL file from step 3 via `File` -> `Import` -> `From SQL Dump...` as in step 1. and 2. There should be no visible change, the table `my_table` should still contain one row with three different emojis.
5. Import the exported SQL file from step 3 via `File` -> `Restore...`, there should still be no visible change, emojis are visible. So far so good.
6. Now export the database via `File` -> `Backup...`, make sure you are running on MySQL 5.7, click `Start backup...`.
7. Repeat step 4 with your just created backup sql file from step 6, emojis are destroyed!
8. Repeat step 5 with your just created backup sql file from step 6, emojis are deytroyed!

## Conclusion
When you open the sql file created in step 3 in a text editor supporting utf8, you can see all emojis. When you open the file created in step 6, you can see that the emojis are destroyed. So there should be something wrong with the `Backup` function. Export, Import and Restore seem to work.

@huyphams, could you have another look into this? Thank you so much!

**Comment by huyphams** [comment]
The Backup uses the official MySQL binaries, we could not manipulate the data. However, we can read the document and follow its instructions.
If you want to backup data with emoji, you can specify the encoding flag:  --default-character-set=utf8mb4
Maybe you should try to backup with that flag?

**Comment by greatestview** [comment]
Thank you, that did work.

Maybe it can be considered to add this flag to the backup default options? It also does not appear in the `Add option...` drop down menu. Maybe that could prevent some confusion.
