### ISSUE TITLE
Support for autocomplete in "Where section" of Data view

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#122]
I'm about selected section on the screenshot with placeholder "id = 10":
![Where section](https://i.imgur.com/9VDit0k.png)

What I use now to not type all field name is:
- press Column button
- start typing field name
- select suggested field and cut it
- close Column form
- paste field into "where section"

Hope, you are agree that native field name autocomplete will improve UI usability here.
Thanks a lot.

**Comment by huyphams** [comment]
Hi @PVGrad 

First of all, I agree with you that the current filter is not good enough. I have tried the Sequel Pro filters and some other clients. Personally, I think choose columns in a dropdown and select the conditions is boring. I'm working on some sketch design to improve this filter and will release it soon.

- Huy.

**Comment by huyphams** [comment]
Hi @PVGrad 

I added this autocomplete popup as a temporary solution.

<img width="1440" alt="completion" src="https://user-images.githubusercontent.com/3654622/33522153-0fc18f34-d818-11e7-979d-399a3610a15c.png">

- Huy.

**Comment by huyphams** [comment]
Hi @PVGrad I can't find your email on your public profile. In case you want to use TablePlus, please ping me at duchuykun@gmail.com we have a small gift your you.
