### ISSUE TITLE
Stored Procedures in MSSQL.

### ISSUE THREAD

**Issue by techon** [TablePlus/TablePlus#1222]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 74

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Mac v2.4 (228)

3. The steps to reproduce this issue:
Open connection. Tables and views show up in list, but where are the Stored Procedures?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by cesarmtz93** [comment]
@huyphams any update on this?

**Comment by fgcui1204** [comment]
@huyphams any update about this?

**Comment by huyphams** [comment]
Hey @fgcui1204 did you enable the function section?
<img width="607" alt="Screen Shot 2019-11-19 at 8 52 51 AM" src="https://user-images.githubusercontent.com/3654622/69148131-f981b700-0aa9-11ea-8c08-2775a001bba4.png">

**Comment by elios264** [comment]
that's horrible, that thing should not be so hidden, you made me install DBeaver and I was about to use it which is horribler, it not for my friend that found this bug.

**Comment by huyphams** [comment]
@elios264 We have enabled it by default recently, thank you!
