### ISSUE TITLE
Add a way to disable "Run All" hotkey

### ISSUE THREAD

**Issue by idris** [TablePlus/TablePlus#1223]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 228

3. The steps to reproduce this issue:
I generally have a loooong sheet of queries, basically queries that I just keep around and use often, or ones I have used in the past and didn't delete.  Sometimes when running a query with CMD+Enter, my finger slips and I do CMD+SHIFT+Enter, which runs ALL of my queries!

I'm requesting a way to disable the "Run All" hotkey.  Or at least add it to the hotkey preferences so I can set it to something that's more difficult to accidentally press.

**Comment by Fishy49** [comment]
It would be nice to be able to re-map _any_ hotkeys in the application I think.

**Comment by vishaluae** [comment]
This has happened to me multiple times when my finger slips and it just runs all my queries. Having a way to either disable it or re-map them would be a lifesaver.

**Comment by huyphams** [comment]
Hi all, I just added an ability to custom the shortcut keys: 
https://www.dropbox.com/s/bskp6rf1julta52/tableplus.dmg?dl=0
You can just change it to some impossible hotkey such as: `command + shift + option + return`
Please let me know if you have any issue with it.

**Comment by vishaluae** [comment]
@huyphams Would this be released as an official release?
I have a paid licence version of TablePlus which I am currently using. Would this build cause any issues with that? And if by installing this build, would I still receive updates?

**Comment by huyphams** [comment]
It will be released in the next update and yes, you can still update with this build. `Would this build cause any issues with that` => it only contains this new feature so I don't think it will have any critical issues 😛

**Comment by vishaluae** [comment]
@huyphams Thank you so much! I will no longer have to pull out my hair in anger!

**Comment by huyphams** [comment]
If you find that build crash, please download this patch: https://www.dropbox.com/s/bskp6rf1julta52/TablePlus.dmg?dl=0
if it does not crash then it fine (I forgot to put the default value for the shortcut).
