### ISSUE TITLE
Double clicking table tab should sticky it

### ISSUE THREAD

**Issue by jdeb9** [TablePlus/TablePlus#1225]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgresSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 228

3. The steps to reproduce this issue:
    1. 'Open Anything' (Ctrl/Cmd + P)
    2. Type table name
    3. Press Enter
    4. Now viewing table, name remains italicised in tab (unstickied)

The problem: using the 'open anything' functionality opens non-stickied table tabs. While this is good for quickly switching between tables, this is annoying because:
- you have to double click the tablename in the sidebar to sticky the table tab
- using the 'open anything' feature does not update the table list (in the sidebar) to the schema of the table being viewed.
- to sticky a table you are viewing after navigating to it via the 'open anything' feature, you must
    - ensure sidebar is viewing correct schema -or- use 'open anything' to open schema first
    - scroll and double click tablename (annoying when the list is very long)

Suggestion:
Double clicking the tab of an unstickied table should sticky it. This is similar behaviour to other programs, such as Visual Studio Code.

**Comment by huyphams** [comment]
Thanks @jdeb9 for the feedback, you can workaround with these steps:

1. Type a table name and open it.
2. If you want to change the table list, please type the schema name.
3. If you want to open a table in a new tab, please press command + T before doing the open anything.

I will find a way to add a feature that you can pin a table in open anything right after opening it.

**Comment by jdeb9** [comment]
Thanks for the response @huyphams, looking forward to it!

**Comment by huyphams** [comment]
The Open Anything now opens a table in a new tab if you hold command.
Download the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by Konstantin-Strakhov** [comment]
Will it goes to stable release someday? Without that using "open anything" is almost useless because tabs disappears when you goes to another "anything". It will be great to have configuration **Turn off "non-sticky tab" feature**

**Comment by huyphams** [comment]
Double-click now will stick the tab, please download the hot-patch here: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
