### ISSUE TITLE
Oracle 12c cancel running query no longer works

### ISSUE THREAD

**Issue by raymccarthy** [TablePlus/TablePlus#1227]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 12c

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.4(231)

3. The steps to reproduce this issue:
Previously cmd+. killed the currently running query.  Now pressing this option brings up a process list, but the list does not get populated in Oracle12 c, so it is no longer possible to cancel running queries in Oracle

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey, @raymccarthy thank you for the feedback. As a temporary solution, you can rollback to the previous build here: https://s3.amazonaws.com/tableplus-osx-builds/230/TablePlus.dmg
I'm sorry for the inconvenience
