### ISSUE TITLE
Bug after create new database (maria db)

### ISSUE THREAD

**Issue by phaizt** [TablePlus/TablePlus#1228]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Maria DB 10.3.14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.4(228)

3. The steps to reproduce this issue:

- on current connection press cmd+K then click new database (+ button)
- import from sql dump
- insert/update your data from your app (i use PHP)
- refresh, and your new data is not displayed (need to close tableplus first) 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Have you tried to press command + R @phaizt?

**Comment by phaizt** [comment]
Yes, i have tried press command + R and also hit refresh button.

**Comment by huyphams** [comment]
I think the connection was disconnected, in this case, you can press command + shift + R to reconnect, no need to close the app. Btw, I can't reproduce the issue, but will keep an eye on it.
