### ISSUE TITLE
Welcome screen opens at the incorrect size

### ISSUE THREAD

**Issue by devtimi** [TablePlus/TablePlus#1229]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 228

3. The steps to reproduce this issue:
Open any database, resize / reposition it.
Quit TablePlus
The welcome screen will open the size/position of the database view.

This is not how the welcome screen operates if you close all windows first. The database list doesn't need to be as big as a database view, so maintaining the size/position separately would be preferred. Doing so would make the welcome screen open the size and position I expect it every time, regardless of how I closed TablePlus.

**Comment by huyphams** [comment]
Actually, this is a bug, I've debugged it several times. The welcome screen will have an incorrect size when:
1. The app crashed.
2. The app was killed.
3. Run multiple versions of TablePlus (a beta and an official).
I can work around but it's not smooth.

**Comment by huyphams** [comment]
It's fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!

**Comment by devtimi** [comment]
Thank you, Huy!
