### ISSUE TITLE
Security: TablePlus does not validate SSH host key

### ISSUE THREAD

**Issue by raiskila** [TablePlus/TablePlus#1230]
### Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81)?
Build 228

### Which driver are you using and version of it (Ex: PostgreSQL 10.0)?
Not relevant, SSH issue

### Steps to reproduce this issue

1. Configure a DB connection using the "Over SSH" setting. Set passwords to "Ask every time".
2. Connect successfully.
3. Replace the SSH server instance in the cloud with another server, causing the server SSH keys to change.
4. Attempt to reconnect with TablePlus.

### Expected behavior

I expect to see a warning similar to what the `ssh` command line utility produces:

```$ ssh my-server
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:xxxxxx.
Please contact your system administrator.
Add correct host key in /Users/janne/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/janne/.ssh/known_hosts:xx
ECDSA host key for my-server has changed and you have requested strict checking.
Host key verification failed.
```

### Actual behavior

TablePlus silently ignores the changed host key and connects via SSH.

⚠️ **This is really bad!** ⚠️

This means someone could perform a man-in-the-middle attack on your network and TablePlus wouldn't stop you from connecting to your production database while this is happening. This would give the attacker access to your production database.

You should:
* Give the user the opportunity to see the SSH server's public key fingerprint before connecting for the first time
* Store it in the keychain, and
* Alert the user if the server's key changes, allowing them to verify that the new key is authentic.

**Comment by huyphams** [comment]
HI @raiskila we already supported it on the beta release: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
it will be released in the next update.

**Comment by raiskila** [comment]
Hi,

When I try to connect to an SSH server using the beta version you linked, I get this error on first connection after starting the app:

<img width="531" alt="Screen Shot 2019-06-12 at 11 11 19 PM" src="https://user-images.githubusercontent.com/351598/59382939-9572fe00-8d67-11e9-9636-d68c2f09723f.png">

After clicking "Edit connection" and clicking "Connect", it connects. I can't really verify whether the security bug is fixed because connecting isn't working properly.

**Comment by huyphams** [comment]
Hi @raiskila maybe the server has been rewritten. To make sure it will invalid, please rename the knows_hosts file: ~/.ssh/known_hosts to a temporary file and try again

**Comment by huyphams** [comment]
Hey @raiskila please let me know if you're still seeing it. I just released the official build 233, which supports this feature.

**Comment by raiskila** [comment]
Hi @huyphams 

TablePlus 2.5 (233) seems to be validating the SSH host key using the known_hosts file, thanks. I'm still having the separate postgres connection issue, but I can file a separate issue for that.

**Comment by huyphams** [comment]
Thanks @raiskila for letting me know.
