### ISSUE TITLE
Can't change column charset. Always reverted to default 

### ISSUE THREAD

**Issue by coud** [TablePlus/TablePlus#1231]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.20

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.4 (228)

3. The steps to reproduce this issue:

My database default charset is utf8 - utf8_unicode_ci. My connection is utf8mb4
Column is added through the interface without setting the charset. It is automatically set to database default charset.
I tried changing the charset to utf8mb4 - utf8mb4_unicode_520_ci in the interface but it is reverting back to default. Looking at the queries executed at the bottom when saving the changes, the alter command does not include the charset changes.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
We just added it recently and TablePlus only allow users to view charset. We will support changing charset in future releases.

**Comment by coud** [comment]
I think the alter command right now is a bug because it uses CHANGE always even though I did not rename the column so what happens is when I made a charset change through sql and try to change for example the NOT NULL OR NULL of a column then my manual change of charset is lost. You should consider using MODIFY when the column name does not change.
