### ISSUE TITLE
Support SSH ProxyCommand

### ISSUE THREAD

**Issue by takmongwai** [TablePlus/TablePlus#1232]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 228

3. The steps to reproduce this issue:

* Create a new connection....
* Over SSH: 
  * server: xxxx ,port: 20022

**Comment by huyphams** [comment]
Do you have any config file at /etc/ssh/ssh_config and ~/.ssh/config which override the host?

**Comment by weidewang** [comment]
> Do you have any config file at /etc/ssh/ssh_config and ~/.ssh/config which override the host?
hi,

Yes, I hava ~/.ssh/config ,and the ssh host connect via other ssh tunnel
-----------------------------------------------------
Host tunnel
    HostName <tunnel...ip>
    Port 6000
    User tunnel-user
   IdentityFile ~/.ssh/tunnel-priv-key.pem

Host xxx
  HostName <xxx.ip>
  Port 20022
  User ssh-user
  IdentityFile ~/.ssh/xxxxxxx.pem
  ProxyCommand  ssh tunnel -W %h:%p
-----------------------------------------------------

than,TablePlus connection config Over SSH 
server: xxx,port: 20022
-------------------------------------------------

**Comment by huyphams** [comment]
Currently, TablePlus doesn't support ProxyCommand so I think that why you can't connect to the server.

**Comment by weidewang** [comment]
Ok, understand.
This feature is worth looking forward to.
thank you very much

**Comment by pdeveltere** [comment]
@huyphams this is still not working for me. Has this been implemented?
