### ISSUE TITLE
the column order of view is not kept after exported into csv

### ISSUE THREAD

**Issue by zongzhiliu** [TablePlus/TablePlus#1233]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
redshift
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 228
3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I've fixed it, you can download the hotfix build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it.
