### ISSUE TITLE
Oracle not loading European/Special Characters

### ISSUE THREAD

**Issue by benvwin** [TablePlus/TablePlus#1234]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 12.1.0.2.0
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.4(231)

3. The steps to reproduce this issue:
When using oracle database to select a column with European or special characters they don't show up at all. Please see the first image for TablePlus vs the SQLDeveloper which displays these special characters.

![image](https://user-images.githubusercontent.com/32555009/59370844-493ca500-8cf8-11e9-89ec-a2f8a0b1ed0d.png)

![image](https://user-images.githubusercontent.com/32555009/59370863-55c0fd80-8cf8-11e9-9bbb-05ede349f7db.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by benvwin** [comment]
the ä isn't displaying in this example. There are a few others as well. Please let me know if you need more examples. Thank you!

**Comment by huyphams** [comment]
Hey guys, please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="1189" alt="utf8" src="https://user-images.githubusercontent.com/3654622/63312331-98461e00-c2d7-11e9-82e2-7b6276658765.png">
Let me know if you're still seeing the issue then I will reopen the issue.
