### ISSUE TITLE
[Feature Request] - Dynamo DB Support

### ISSUE THREAD

**Issue by kouponmedia** [TablePlus/TablePlus#1235]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
AWS Dynamo DB any version

Similar to the Mongo DB support, but for Dynamo. 

**Basic Abilities to do the following:**

- List tables for account by region.
- View table details
- Query, Scan, Put, Delete items.

**Comment by huyphams** [comment]
Close because it's duplicated. Please follow this issue: https://github.com/TablePlus/TablePlus/issues/666
