### ISSUE TITLE
Switching Workspaces on MacOS 10.14.5 not highlighting the active workspace

### ISSUE THREAD

**Issue by heihachi88** [TablePlus/TablePlus#1239]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 228

3. The steps to reproduce this issue:
Open 2 workspaces, and try to switch between them using a hotkey `Shift+⌘+]` or `Shift+⌘+[`

Here's the video demonstrating the behavior:

![ScreenRecording20190614at1](https://user-images.githubusercontent.com/5739191/59484625-5e4e3b00-8e94-11e9-801d-13843cbee8b4.gif)

Active workspace tab getting highlighted if i press on it with cursor, but with hotkeys it doesn't work.

**Comment by heihachi88** [comment]
Hello?

**Comment by huyphams** [comment]
Does it still happening on the build 233 @heihachi88

**Comment by heihachi88** [comment]
Yes, on previous build and on this one.

**Comment by huyphams** [comment]
Hey @heihachi88, could you please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 and let me know the result? Thank you!

**Comment by heihachi88** [comment]
Now it works, but there's some lag, when i switch the tabs very quickly, also:

![image](https://user-images.githubusercontent.com/5739191/59972342-1f646780-95af-11e9-9faf-feb74dd94ad9.png)

Why register button is appeared again? I already have a license.

**Comment by huyphams** [comment]
yep, it will show the license. We placed it here because some users want to unregister the license and move it to a new device.

**Comment by heihachi88** [comment]
Maybe a condition then? If you registered, then make "Unregister" or so.

**Comment by huyphams** [comment]
Hi @heihachi88 you can download this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I will close this issue, the fix will be released on the next update.
