### ISSUE TITLE
Unable to view local postgres data after latest update

### ISSUE THREAD

**Issue by THAlpha** [TablePlus/TablePlus#124]
Having to revert to an older version, no data shows up on a local postgres db - tried removing and adding the credentials again but nothing. Schemas not showing either apart from `public`.

**Comment by huyphams** [comment]
Hi @THAlpha 
I think I know how to reproduce this bug. Thanks for the feedback.

**Comment by huyphams** [comment]
Hi @THAlpha 
Could you please test this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0 
I just make a quick fix for this rare case.

- Huy.

**Comment by rosaalvarez** [comment]
Same issue

**Comment by rosaalvarez** [comment]
Well, I took the file on the link that you shared, and it works.

**Comment by huyphams** [comment]
Hi guys,

The build on the link is production build + hot patch this issue. You guy can use that build until the next update.

Huy.

**Comment by THAlpha** [comment]
Thanks @huyphams - that works for me.
