### ISSUE TITLE
Add option to disable auto-count query

### ISSUE THREAD

**Issue by donbeave** [TablePlus/TablePlus#1241]
Hello!

Will be happy to see any way to disable automatic `SELECT COUNT(*) as count FROM "public".my_table_name_here;` queries when working with huge tables. For huge tables with 1-2 TB data, this query is crazy slow. That's why I'm thinking to have a feature which allows the disabling count query for some particular tables.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.4 (228)

3. The steps to reproduce this issue:

Open any huge table in the UI ("Data" tab). In "data queries" panel will see something like:

```sql
-- 2019-06-16 23:05:34.0810
SELECT * FROM "public"."huge_table" ORDER BY "id" LIMIT 300 OFFSET 0;

-- 2019-06-16 23:05:35.0540
SELECT COUNT(*) as count FROM "public"."huge_table";
```

The second query will take a very long time.

**Comment by huyphams** [comment]
hey @donbeave thanks for the feedback, actually, TablePlus always estimate table before counting, so it will not affect the performance. I've updated the report here, so it will show the estimated count query in the console: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by donbeave** [comment]
Yeah, it's better now!

**Comment by donbeave** [comment]
Sorry, still have this issue for some huge partitioned tables, because of the query:

```sql
select reltuples::int8 as count from pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace where nspname='public' AND relname='huge_partitioned_table';

-- will return 0
```

**Comment by donbeave** [comment]
You can use this query to find all child tables:

```
SELECT
    nmsp_parent.nspname AS parent_schema,
    parent.relname      AS parent,
    nmsp_child.nspname  AS child_schema,
    child.relname       AS child
FROM pg_inherits
    JOIN pg_class parent            ON pg_inherits.inhparent = parent.oid
    JOIN pg_class child             ON pg_inherits.inhrelid   = child.oid
    JOIN pg_namespace nmsp_parent   ON nmsp_parent.oid  = parent.relnamespace
    JOIN pg_namespace nmsp_child    ON nmsp_child.oid   = child.relnamespace
WHERE parent.relname='huge_partitioned_table';
```

**Comment by huyphams** [comment]
hmmm, made sense. I think TablePlus should check one more condition before counting. If the estimate is 0 but there are returned rows. TablePlus will not perform the select count(*).

**Comment by huyphams** [comment]
I addressed the issue, please download this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by donbeave** [comment]
It works now, but without an estimated count: `1-300 of >300 rows`, and only one query in the logs window:

```

-- 2019-08-19 15:44:26.8080
SELECT "ctid",* FROM "public"."huge_partitioned_table" LIMIT 300 OFFSET 0;
```
