### ISSUE TITLE
Foreign key constraints not shown if there are duplicates between schemas

### ISSUE THREAD

**Issue by ryb73** [TablePlus/TablePlus#1243]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

228

3. The steps to reproduce this issue:

If I have two schemas with the same tables and foreign key constraints, TablePlus won't show the foreign key constraint when looking at a table in the second schema:

![image](https://user-images.githubusercontent.com/943476/59570577-6fe83c00-9068-11e9-9bbc-7069d9ea2444.png)
(in this example you can see that the `foreign_key` column says EMPTY, but there **is** a foreign key on this column)

If I change the name of the foreign key constraint in one of the schemas, then TablePlus will show the constraint.

**Comment by huyphams** [comment]
it's fixed in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you @ryb73

**Comment by ryb73** [comment]
Thanks for the quick turnaround!
