### ISSUE TITLE
Authentication plugin 'dialog' cannot be loaded

### ISSUE THREAD

**Issue by cykirsch** [TablePlus/TablePlus#1248]
1. Which driver are you using and version of it:
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 228 w/ registered license

3. The steps to reproduce this issue:
Add dialog.so file to `/usr/local/mysql/lib/plugin` dir. Attempt connection.
This file does work for Sequel Pro, although that app wanted the file in `/usr/local/lib/plugin` dir

![image](https://user-images.githubusercontent.com/8845299/59806543-55a59c80-92ba-11e9-8d4e-e884e256273e.png)

**Comment by huyphams** [comment]
Hi @cykirsch have you tried with the MySQL 8 driver? (it's compatible with MySQL 5 as well).

**Comment by cykirsch** [comment]
Yes, and MariaDB. MySQL8 was what I tried first though, and I've tweaked
some things since then so it's worth another go.

**Comment by huyphams** [comment]
TablePlus is a notarized app, which is Approved by Apple (Sequel Pro doesn't) so it will not allow any plugin which is not signed by the Apple certification, that's the reason you can't add the dialog.so manually. I will take a look at it.

**Comment by cykirsch** [comment]
Makes sense. Do you think it's something we'll be able to resolve? I won't be able to use it at work without it so I would have to let my manager know to request a refund. I definitely want to use it though :)

**Comment by huyphams** [comment]
So I think you can request a refund if needed because I need to rebuild the library to support daialog.so and it takes time.

**Comment by cykirsch** [comment]
Thank you. I'll keep an eye on this issue so I can give it another try in the future.

**Comment by huyphams** [comment]
Btw have you tried the newest beta build 234 @cykirsch? (and please also try with MariaDB driver) I rebuilt those libs on this build and as I remember, I've enabled Clear text password plugin in the driver.

**Comment by cykirsch** [comment]
Nice, it works! I'm in via MariaDB driver on build 234. There's a little weirdness, and if I determine some clear patterns I'll let you know. One _may_ be that if the password is wrong it just hangs on "Connecting to database..." instead of failing. Right now I'm good to go though. I appreciate the help!

**Comment by huyphams** [comment]
Thanks for the confirmation. I've added a warning popup which tells the user to use the MariaDB with dialog.so so I think we can close this issue for now.

**Comment by mpash** [comment]
This broke existing builds that already worked with a non-signed version of `dialog.so` Please revert this change. @huyphams

**Comment by mpash** [comment]
@huyphams This is still a major problem for SetApp users. The first time you connect `dialog.so` is not loaded, you need to disconnect, and retry entering your password every single time you connect. Which is hair-pulling.
