### ISSUE TITLE
Import/export window is gone after locking the Mac

### ISSUE THREAD

**Issue by CrixuAMG** [TablePlus/TablePlus#1249]
I was importing a 1.2GB sql export file (generated by TablePlus), and after some time talking with my colleagues, I noticed my Mac was locked and unlocked it. The import window was gone, and cannot find it anywhere, so I cannot check the progress.
Is there some way of showing this again?

Running the latest version (2.4, build 228) via Setapp.

**Comment by huyphams** [comment]
Thanks, let me check it!

**Comment by CrixuAMG** [comment]
@huyphams would it be possible to have a select "Shutdown after importing/exporting" option? Having this would be really nice!
