### ISSUE TITLE
Under the "create new connection"  MariaDB option is not coming 

### ISSUE THREAD

**Issue by mohapma** [TablePlus/TablePlus#1250]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by mohapma** [comment]
Build 70 i am using

**Comment by huyphams** [comment]
Hi @mohapma you can use the MySQL driver, it's compatible MariaDB. Windows repo is here: https://github.com/TablePlus/TablePlus-Windows/issues so I will close this issue.
