### ISSUE TITLE
MySQL backup gives access denied for user

### ISSUE THREAD

**Issue by lucasRolff** [TablePlus/TablePlus#1253]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.4 (228)

3. The steps to reproduce this issue:
- configure MySQL over SSH
- Have a password set for user that contains following characters `[ = ' ! ? # ( > ~` (and some letters and numbers)
- Try do a backup

```
Create tunneling...
Dumping...
mysqldump: [Warning] Using a password on the command line interface can be insecure.

mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect

Backup database completed
```

The user has full access to the mysql server, and doing a mysqldump from command line (with a `.my.cnf` in place) works fine - I guess it has to do with the password being escaped incorrectly.

**Comment by huyphams** [comment]
I think so @lucasRolff let me check it.

**Comment by huyphams** [comment]
Hey @lucasRolff I've fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it!

**Comment by lucasRolff** [comment]
Can confirm it works!

**Comment by charlie-s** [comment]
Has this not made it into latest builds?

**Comment by Vmadmax** [comment]
I have the same issue in the newest build (and before).

**Comment by reua** [comment]
Same thing here. Backup for MariaDB 10.1.43 fails with 1045 connected over ssh. Used user has full permission.

**Comment by shennyg** [comment]
FYI. This is still a problem in Build 290. My password contained `)$`. Changing the password allows me to import and dump.

**Comment by huyphams** [comment]
I can backup/restore with the username/password that contains `)$` maybe there are more special characters in your setup @shennyg ?

**Comment by shennyg** [comment]
No, my password was `rt3QAbWyuy)$FtebFv7hUgdMqtfWNCuCBAP`, I was connecting to an AWS RDS MySQL Aurora cluster.

**Comment by huyphams** [comment]
That's wierd, it only happens when with the long password. However, I can reproduce and fix it in this patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 if you have a chance, please give it a try @shennyg thank you!
