### ISSUE TITLE
SQL query editor saves on close

### ISSUE THREAD

**Issue by aramando** [TablePlus/TablePlus#1254]
This was touched upon by #592, but the scope of the issue is actually broader (and has not been resolved).

When it is closed the SQL query editor automatically and silently saves any query that was opened in it from either a saved favourite or an external SQL file on disk. This is obviously very bad as it makes it inevitable that work will be lost sooner or later.

Interestingly, it does not do this for queries that were entered into an empty SQL editor, saved to disk and then modified, but this is an issue in its own right, because once an editor's contents are saved to a file convention dictates that the editor should then be associated with that file and further edits should be able to be saved using Cmd+S, but this does not do anything (you have to "Save As..." and overwrite the file to update it).

1. Which driver are you using and version of it: Postgres 10.6
2. Which TablePlus build number are you using: 234
3. The steps to reproduce this issue:
   - Create a favourite query
   - Double-click the favourite to open in a SQL Editor, or right-click it and select "open in new tab"
   - Make a change in the SQL editor 
   - Close the SQL editor tab
   - Either edit the favourite or open it again to see the change persisted

**Comment by huyphams** [comment]
Have you disabled auto-save in the preferences @aramando?
<img width="612" alt="autosave" src="https://user-images.githubusercontent.com/3654622/59849981-48101580-9393-11e9-88c9-8601b489445e.png">

**Comment by aramando** [comment]
Oh... 🤦‍♂️ 

That's fixed it, thank you :-)

However, I do feel quite strongly that the auto-save option should be disabled by default (I don't _think_ I enabled it myself) because of the possibility of unexpectedly losing favourites and the contents of files. 

Furthermore, if this option is also going to continue to apply to files opened from disk as well as favourites this should be made clear in the wording of the option.

Thank you for a great Postgres client, by the way; I'm going to try to persuade my boss to buy me a licence as it's much nicer to use for day-to-day tasks than pgAdmin 👍

**Comment by huyphams** [comment]
Thank you! I will probably add a warning popup to tell the user this behavior for the first time they use Favorite and also update the text in preference to make it clear.

**Comment by CyrilMazur** [comment]
I got burned by this too 🤦‍♂️ +1 for warning users of this behaviour.

**Comment by huyphams** [comment]
I've added it in the official release 233. So I think we can close this issue.
