### ISSUE TITLE
Multi record insert statement not working for SQL Server 2017

### ISSUE THREAD

**Issue by DHFW** [TablePlus/TablePlus#1255]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
`Microsoft SQL Server 2017 (RTM-CU9) (KB4341265) - 14.0.3030.27 (X64) 
Jun 29 2018 18:02:47 
Copyright (C) 2017 Microsoft Corporation
Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): `Version 2.4 (228)`

3. The steps to reproduce this issue: Run an insert query like this, it reports an error (Statement terminated):
```sql
INSERT INTO [dbo].[user] 
  ([id],[name])
VALUES
  (1,'Name 1'),
  (2,'Name 2')
```

While this works:

```sql
INSERT INTO [dbo].[user] 
  ([id],[name])
VALUES
  (1,'Name 1')
```

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @DHFW TablePlus doesn't modify the query before sending it to the server. I don't know the root of the problem but mostly it's related to the SQL Server.

**Comment by DHFW** [comment]
Does't seem to be an issue anymore.
