### ISSUE TITLE
Extra Schema Reported on a Refresh

### ISSUE THREAD

**Issue by jon-djon** [TablePlus/TablePlus#1256]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.5): PostgreSQL 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 233

3. The steps to reproduce this issue: 

- To reproduce the issue I select a schema from the bottom left dropdown (e.g `foo.com`) 
- Then Refresh everything via the refresh button
- After the refresh there is an extra schema in there called `com`

I believe this bug happens when there is a `.` in the name of the schema.

**Comment by huyphams** [comment]
Hey @jon-djon, I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for letting me know.
