### ISSUE TITLE
[Feature Request] Save/Restore Workspace/Session

### ISSUE THREAD

**Issue by vesper8** [TablePlus/TablePlus#1260]
This feature is direly missing.. especially with the frequent updates that upon installing force you to close all your opened connections/databases/tables

The ability to save/restore (multiple) workspaces.

Simple as that. It's been requested multiple times and for someone who is constantly working with multi-db projects.. it would really be a huge help to have this feature.

Everything should be saveable/restorable when saving a "workspace or session". Including opened connections, opened databases and opened tables"

Upon loading a workspace/session, it should reopen the windows/tabs and reconnect.

Really hoping this can be added soon!

Thanks!

**Comment by Cottser** [comment]
I really like this suggestion. For some newer users such as myself, this might actually be a strong motivation to purchase a license :) So far in my use, the limit of two workspaces, tabs, etc. hasn't been a big issue for me because all is lost on quit anyway. If TablePlus remembered, on the other hand, I would see more value in being able to keep a bunch of things open and get back to where I was.

Maybe the initial version can be a "hot exit" similar to Sublime Text (or Chrome for that matter), which can be turned off in preferences if unwanted. In theory that's simpler than building the UI and such for managing workspaces/sessions and IMO easier for users to understand. @vesper8 would an implementation like that meet your needs?

**Comment by huyphams** [comment]
Actually, I planned to release this feature in the next release.

**Comment by vesper8** [comment]
@Cottser a "hot exit" would be great and I hope this makes it in, but as someone who has to work on many different projects, I also hope that the full-featured workspace saving/loading is also supported

@huyphams that's great! does that mean it should be available within 1 week? really looking forward to this one!

**Comment by huyphams** [comment]
of course @vesper8 
![2019-06-26 10 34 22](https://user-images.githubusercontent.com/3654622/60149164-fdacef80-97fd-11e9-807c-ad91d74bf448.gif)

**Comment by huyphams** [comment]
it's released in the build 235.

**Comment by vesper8** [comment]
@huyphams it's very nice that you added the "hot exit" feature.. but my feature request was a bit more in-depth.. with the ability to manually save and load multiple workspaces... I imagine now that you're able to do this for 1 workspace, then it wouldn't be too much work to be able to do it for multiple.. do you plan on releasing the full feature pretty please?

**Comment by vesper8** [comment]
@huyphams Pinging you again about this, it's nice you added the hot exit but what I would really like to see added is the ability to save and restore multiple worksets, not just a single one at a time

Since you've added the hot exit I think it shouldn't be too much work to add a save/restore feature that lets you save multiple workspaces under different names

Could you please at least confirm that this is on your todo list?

Many thanks!

**Comment by huyphams** [comment]
Thanks @vesper8 let me consider it.

**Comment by gennaios** [comment]
I'm not sure how this feature works. I have the setting enabled, yet if I quit with cmd-Q, upon reopening, I get the welcome dialog with list of connections. I had thought that it would re-open any workspaces including connections and skip that dialog.

**Comment by junxy** [comment]
This function is still not supported in Windows. Every time I restart the program, it is a bit annoying…

**Comment by malle-pietje** [comment]
Amazed this is still not implemented in the Windows version...
