### ISSUE TITLE
TablePlus froze durign import CSV

### ISSUE THREAD

**Issue by jakubhavle** [TablePlus/TablePlus#1264]
Hello, first thank you for great application. But i have very often problem with import data from CSV. Usually if file has more then 100MB the import froze during first seconds. If iam patient enough the import will finish. but mostly i got (application not responding).

Not sure, maybe problem is on my side. 

My setup: OSX
Table plus version: 2.5 (233)
Drive: PostgesSQL (9.3.18)

and that DB is in virtual vagrant machine.

not sure, maybe this is somethign related becuase DB is in virtual machine. File what iam trying to import is over about 127MB...i can send you via email? cant attach it here

**Comment by huyphams** [comment]
Hi it would be great if you can send me an example via email nick@tableplus.com thank you so much!

**Comment by jakubhavle** [comment]
I also enabled crash report, so will try it again and maybe i will get report also.

**Comment by huyphams** [comment]
Quick answer, TablePlus froze because it tried to log all the import queries. You can toggle the console (click the toggle icon or press command + shift + C). the issue will be gone

**Comment by jakubhavle** [comment]
Thanks for quick turn around of this problem ... I was suspicious about it, but thanks you a lot. Closing this issue

**Comment by huyphams** [comment]
The console log can be enabled during the import (by mistake). I improved it on the new update. Now, TablePlus only updates the console after importing.
