### ISSUE TITLE
Unable to login to MariaDB 10.3

### ISSUE THREAD

**Issue by mpash** [TablePlus/TablePlus#1265]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
233

3. The steps to reproduce this issue:
- Login with a PAM Authenticated server (Using the `dialog.so` plugin)
- Type in password
- See that TablePlus hangs without making the request

PS. You can overcome this by doing this
- Click on connection
- See password propmt
- Press escape
- Click connection AGAIN
- Login with passsword
- ...
- It works...

**Comment by huyphams** [comment]
Could you please make a gif @mpash the dialog.so is loaded by default so I don't think it was the root cause.

**Comment by mpash** [comment]
@huyphams I will need to PM you the gif to prevent abuse to our systems.

**Comment by huyphams** [comment]
Thanks, my email is nick@tableplus.com

**Comment by huyphams** [comment]
Hi @mpash I fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 Let me know if it works for you!

**Comment by mpash** [comment]
@huyphams That is not a SetApp build; please link the proper build

**Comment by mpash** [comment]
@huyphams Please respond.

**Comment by huyphams** [comment]
The Setapp team just approved out update. It will be available shortly

**Comment by mpash** [comment]
@huyphams tyvm
