### ISSUE TITLE
[Feature Request] Edit default flags used in the "backup" dialog

### ISSUE THREAD

**Issue by NickThompson1993** [TablePlus/TablePlus#1266]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySql5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 233

3. The steps to reproduce this issue:
It would be really great if there was a setting for adding/removing default flags (e.g one that I have to use frequently is `--set-gtid-purged=off`) for/in the database backup window. Currently these have to be manually entered each time

**Comment by huyphams** [comment]
Hi, TablePlus from the build 233 will remember the flag you've used for each connection. So I think adding hundred of flags isn't necessary.
