### ISSUE TITLE
[Feature Request] Sort list of connections

### ISSUE THREAD

**Issue by RadekBednar** [TablePlus/TablePlus#1267]
Hi,
is possible to add sort connections by name? I cant find this function. I have lots of connections and in sorted list is better orientations.

Thanks.

**Comment by hieuhlc** [comment]
At the moment TablePlus doesn't have this feature. I did workaround by drag&drop connection like so

![ezgif-1-e075b3da8ee7](https://user-images.githubusercontent.com/4828178/60248952-e9482000-98ed-11e9-9f9d-308b783f833b.gif)

**Comment by zoispag** [comment]
I just visited github to add this exact request.
I have far too many connections to do that by hand. It would be great to be able to click a button and sort them alphabetically :D

👍 from me!

**Comment by huyphams** [comment]
it's implemented in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you have any feedbacks.

**Comment by KenKolano** [comment]
Build with this feature seems to have been deleted and it's not present in current builds.
