### ISSUE TITLE
BEGIN-END should not be required to group statements during run all/run selected

### ISSUE THREAD

**Issue by mikestopcontinues** [TablePlus/TablePlus#1268]
1. Which driver are you using and version of it: SQL Server 2017
2. Which TablePlus build number are you using: 2.5
3. The steps to reproduce this issue:

Currently, there's no way to get this to work:

```sql
declare @x int = 0;
select top(1) * from contact where contact_id = @x;
```

...without wrapping it:

```sql
begin
  declare @x int = 0;
  select top(1) * from contact where contact_id = @x;
end;
```

Yet such a query would run fine if run directly against the db.

The expected behavior is that when you "run all" or when you select multiple statements and "run current", dependent statements like the above should work. I think developing or testing queries should be as easy as copy-and-paste.

**Comment by huyphams** [comment]
I think you're just seeing normal SQL behavior, TablePlus doesn't do anything special here. It just submits all the queries one by one and returns the result.
I'm not sure about submitting all the text at once (TablePlus will not split the text into queries) but I think it will break some behaviors. But let me try.

**Comment by alnitaka** [comment]
Tried it with Toad on Windows and it just works as is... In my opinion TablePlus shouldn’t require the user to add those BEGIN / END statements by hand.

**Comment by huyphams** [comment]
Sorry for being late, this build should eliminate the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
TablePlus now uses one transaction for multiple queries in SQL Server. Let me know if you're still seeing it.

**Comment by alnitaka** [comment]
Great, it works. Thank you Henry.

**Comment by alnitaka** [comment]
> Sorry for being late, this build should eliminate the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
> TablePlus now uses one transaction for multiple queries in SQL Server. Let me know if you're still seeing it.

There seems to be a side effect of this: when there are `BEGIN TRANSACTION;` / `COMMIT TRANSACTION;` statements into selection, they are ignored and all text is considered as a unique transaction. Multiple transactions are thus no more supported...
