### ISSUE TITLE
Ability to name and save SQL query tabs

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#127]
An option to rename tabs (on right click and/or from the menu options) would be nice to have. The ability to save tabs as files would be even better.

**Comment by huyphams** [comment]
I'm thinking about that. But may I ask you a question.

Why you want to rename the tab? because the tab name is table name. If we allow to rename the tab, it maybe confused.

 Btw: restore workspace/tabs after close app would be a nice feature, just like Xcode, Sublime Text, I agree with this.

**Comment by bhrd** [comment]
Well, I should've been clearer I guess. I'm specifically talking about the SQL Query tab. Let me edit the issue title as well.
![image](https://user-images.githubusercontent.com/221584/33923222-a5603dce-df84-11e7-9cef-8fdee3e14260.png)

**Comment by huyphams** [comment]
I understood, rename for only SQL Query tab. I agree with it 👍

**Comment by huyphams** [comment]
Save SQL function will be included in build78
