### ISSUE TITLE
[Bug] Backup not setting the date in the filename

### ISSUE THREAD

**Issue by david-mdmsystems** [TablePlus/TablePlus#1273]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
241
3. The steps to reproduce this issue:
Make a backup of any database, the proposed file name doesn't contain the fragment with the date like it was doing before.

**Comment by huyphams** [comment]
Hi, please click the title and change the naming pattern. And you can change it to whatever you want.
<img width="772" alt="naming" src="https://user-images.githubusercontent.com/3654622/60709667-5f98e380-9ee7-11e9-888b-305d2411680c.png">

**Comment by huyphams** [comment]
Hey @david-mdmsystems please let me know the result. If you're not satisfied with the solution, I will reopen this issue.
