### ISSUE TITLE
Feature request: Show running queries

### ISSUE THREAD

**Issue by joshbrw** [TablePlus/TablePlus#1274]
The recent version of TablePlus came with a great update that allows you to kill a long-running queries using the `SHOW PROCESSLIST;` MySQL query. I was wondering if we could have this pop-up available permanently to inspect the running queries on the server? Instead of it only being available when you've got a query currently running.

**Comment by huyphams** [comment]
Hi, it’s always available via hot key command + . Or using the main menu.

**Comment by joshbrw** [comment]
Thanks @huyphams, it doesn't actually do anything on my version of TablePlus though.

Version 2.6 (240)
OSX Mojave

**Comment by huyphams** [comment]
I've fixed it on the build 242.
Thank you!

**Comment by joshbrw** [comment]
Works perfectly, thanks @huyphams!

Is there any way we could have a `refresh` keyboard shortcut (such as `Cmd+r`) to refresh that dialog's content (re-run the `show processlist;` query).

**Comment by huyphams** [comment]
I will add a refresh button on the list! thanks for the suggestion.

**Comment by justim** [comment]
Another thing that would make it even better, is to make the queries selectable/copyable. There is no way to see the complete query right now (except for running `show processlist` yourself)

**Comment by huyphams** [comment]
It's been requested here: https://github.com/TablePlus/TablePlus/issues/1380
And yes, we will support it in the next release (and also in the next beta release).
