### ISSUE TITLE
Updating "point" spatial data through UI generates invalid query

### ISSUE THREAD

**Issue by pdayzed** [TablePlus/TablePlus#1276]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
_MySQL 8.0.12_

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
_Version 2.6 (240) for Mac_

3. The steps to reproduce this issue:
- Open a table with a `point` spatial datatype.
- Change the value of one or both coordinates.
- Commit the change.

The query that is generated is:
UPDATE `table_name`.`point_col_name` SET `geom` = ST_GeomFromText('POINT(-76.065345 39.047206)**,4326'**) WHERE `id` = XXXX;

The correct query should be:
UPDATE `table_name`.`point_col_name` SET `geom` = ST_GeomFromText('POINT(-76.065345 39.047206)**',4326**) WHERE `id` = XXXX;

MySQL stores the SRID with the data. The generated update query does not take this into account and places the point data plus SRID in the ST_GeomFromText function first parameter and leaves the second parameter blank.

**Comment by huyphams** [comment]
Thanks, let me check and fix it.
