### ISSUE TITLE
Clear All Button Does Nothing

### ISSUE THREAD

**Issue by dldereklee** [TablePlus/TablePlus#1278]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.19

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 240

3. The steps to reproduce this issue:

What does this Clear All button do? I thought it was suppose to clear all the current SQL filtering criteria (like what the - button on the right does), but it doesn't seem to work... (or maybe it does something else?)

![image](https://user-images.githubusercontent.com/20377366/60537320-1feeb380-9cbd-11e9-97e1-6d70e5f4fdd9.png)

**Comment by huyphams** [comment]
Hi, the Clear All button is used "unset filter". Maybe we should update the button title.
