### ISSUE TITLE
Simultaneous queries triggered from multiple tabs don't report accurate status

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#128]
I had one SQL query tab open and executed a long running redshift query.
The progress bar reported accurate state.
I opened a new tab and tried executing another query. 
Both queries were submitted to the server (I verified).
I expected to see the state of 2 queries on the progress bar on TablePlus, but couldn't see such a state.
The query on the second tab completed, but the app still doesn't allow editing queries on that tab.

**Comment by huyphams** [comment]
Hi,
I got it, thanks for your feedback. This bug will be fixed on build 77 👍
