### ISSUE TITLE
[Usability] Favorites Are Overridden on Change

### ISSUE THREAD

**Issue by glen-cooney-vacasa** [TablePlus/TablePlus#1282]
I am liking TablePlus a lot, but when I try to use the `Favorites` tab to store SQL queries I use frequently, I've found any change I make to them ends up getting saved to that favorite. Sometimes I pull up a favorite to use as a template for a different query I need, or I need to tweak some small part of the query for a specific need.

Would be better if it worked more intuitively, where the favorite would remain unchanged unless you manually save it.

**Comment by huyphams** [comment]
Hi @glen-cooney-vacasa you can turn off auto save in the preferences > behaviors

**Comment by huyphams** [comment]
Hi @glen-cooney-vacasa let me know if the option works for you. If it's not, I will re-open the issue.
