### ISSUE TITLE
All favourites deleted on startup

### ISSUE THREAD

**Issue by hugo-ricateau** [TablePlus/TablePlus#1283]
From time to time, all queries saved in the favourites panel are deleted at startup. It doesn't seem to be any specific pattern for this to happen: it's not following a crash and the issue happened several times in the past with many different builds.
I don't think it may help for debugging but still: connection is a local SQLite 3.27.2

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.2;
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): problem occurred in many versions;
3. The steps to reproduce this issue: unknown except launching tablePlus and opening an existing connection.

**Comment by huyphams** [comment]
TablePlus saves all favorite as files and if you delete a favorite, it will move it into the trash.
 It's weird when you said that all the queries were gone.
So how you add a favorite? You create it directly in TablePlus or add a folder?

**Comment by hugo-ricateau-tiime** [comment]
There was nothing in the trash. All favourites were added one by one using the GUI. What is the favourites storage path? So I can manually check whether they are still there or not and for potential permissions issue.

**Comment by huyphams** [comment]
You can find it here:  `cd ~/Library/Application\ Support/com.tinyapp.TablePlus/Cache/Favorite`

**Comment by hugo-ricateau** [comment]
There was nothing in the trash. All favourites were added one by one using the GUI. What is the favourites storage path? So I can manually check whether they are still there or not and for potential permissions issue.
(comment previously poster with the wrong account)

**Comment by hugo-ricateau** [comment]
Right now the folder is empty (and I'm sure there was nothing in the trash); looks like it has been purged. As a workaround I'll try to recover these files from a backup, but still, that's wired.

**Comment by huyphams** [comment]
Maybe it's related to this issue: https://github.com/TablePlus/TablePlus/issues/2070 the TablePlus data file was deleted by maintaining tools (clean my mac and similar tools...)

**Comment by hugo-ricateau** [comment]
In my memory, the incident occurred after updating TablePlus, but I'm not 100% sure and I'm also an Onyx user; so Onyx could be the responsible (unfortunately, I don't remember whether I ran it or not before noticing that these files have been deleted). As this never happened again and as I don't have much more concrete elements to provide, I think I should close this issue.
