### ISSUE TITLE
Beautified SQL Query missing space after 'in' condition

### ISSUE THREAD

**Issue by briggsyj** [TablePlus/TablePlus#1284]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgresSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.5, Build 223

3. The steps to reproduce this issue:
Beautify any query using an 'in' condition.

Example Query:
`SELECT count(*)::real AS "Count all" FROM "myTable" WHERE "myTable"."countries" in ('china', 'india') LIMIT 10;`

When beautified:
```
SELECT
	count(*)::real AS "Count all"
FROM
	"myTable"
WHERE
	"myTable"."countries" in('china', 'india')
LIMIT 10;
```

The current beautified 'Where' clause:
```
WHERE
	"myTable"."countries" in('china', 'india')
```
what it should be:
```
WHERE
	"myTable"."countries" in ('china', 'india')
```

**Comment by huyphams** [comment]
Thanks @jdeb9 let me see if I can improve it.

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
