### ISSUE TITLE
Connection database setting as filter

### ISSUE THREAD

**Issue by bertoost** [TablePlus/TablePlus#1286]
It's great being able to set a color for a connection. So, develop can be green, and production can be red. Therefor I have one connection which is for multiple environments. In such cases it would be great if you can provide a filter (like the search feature) for the connection. This way you still can make multiple connections for each environment (event if it's the same connection).

Thanks in advance.

**Comment by huyphams** [comment]
If I understand you correctly, you want a search field on the connection window so we can filter the connection quickly? 
And all the connections have the same name but a different environment?

**Comment by bertoost** [comment]
Let me try to make it clearer...
I have a database connection with several (a lot) of databases. All databases are suffixed with `_dev` or `_prod` etc.
I would like to define multiple connections (same server, same credentials) but with a filter to only see "dev" databases. The current "database" field must be a specific name, and would be nice if you can use it like the search-filter.

Nevertheless; I agree that there should be multiple users for the different environment/databases.

**Comment by huyphams** [comment]
Actually, you can filter the database using regex ^prefix or suffix$ I think it could help, at least at the moment.

**Comment by bertoost** [comment]
Yes. Thats while you are connected. But I want to make sure I am not accidentally working in a `_prod` database. It would be nice to set this filter in the connection instead.

**Comment by huyphams** [comment]
How about using the safe mode on the production? it would avoid any commit mistakes.
<img width="762" alt="Screen Shot 2019-07-05 at 6 25 17 AM" src="https://user-images.githubusercontent.com/3654622/60712569-b0abd600-9eed-11e9-9f66-bf5106193a12.png">

**Comment by bertoost** [comment]
Yes. But the problem is that all databases are on the same connection, so I see a lot of databases on the single connection I have and they are mixed dev/test/prod databases.
I think creating separated users for it, is the best solution for this ;-)

**Comment by huyphams** [comment]
I think it's a very specific feature and you can still select a wrong filter which ends up on production database (the solution will not work 100%).
Creating a separated user is the best solution.
I will close this issue for now because we're not going to implement it. Let me know if you have any other idea.

**Comment by bertoost** [comment]
Thanks for the discussion. It's indeed better to separate in multiple users
