### ISSUE TITLE
Unable to delete collection in MonogoDB

### ISSUE THREAD

**Issue by ziishaned** [TablePlus/TablePlus#1287]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

```bash
MongoDB shell version v4.0.5
git version: 3739429dd92b92d1b0ab120911a23d50bf03c412
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

![image](https://user-images.githubusercontent.com/16267321/60769654-87549b00-a0e3-11e9-82a5-8df70f5c0de0.png)

3. The steps to reproduce this issue:

* Open a MongoDB connection
* Select a database
* Select a collection
* Use the shortcut `⌘⌫` to remove the collection

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ziishaned** [comment]
@huyphams would you mind explaining why you closed this issue as it is still happening for me

**Comment by huyphams** [comment]
The newest release supports drop collection @ziishaned 
<img width="1750" alt="Screen Shot 2021-08-30 at 12 32 54 PM" src="https://user-images.githubusercontent.com/3654622/131289969-c4f7d020-8ab5-417e-a357-e94de22ddde9.png">

**Comment by huyphams** [comment]
Could you show me your issue @ziishaned I could not reproduce it

**Comment by ziishaned** [comment]
@huyphams Thanks for the quick response. I will give it a go with the latest release.
