### ISSUE TITLE
Allow editing of query tab content when a query is running

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#129]
Most times, I have the need to write more (or edit existing) queries, as a query is executing, and other apps do allow such interactions.

**Comment by huyphams** [comment]
Currently, I block the UI when execute. There are two step:
1. Process queries: spit string into queries, encode, save history <- this step won't take time (ms).
2. Submit query: send queries to server and waiting for the result <- this step take time and depend on your connection, database, and how big the query is.

I will improve this process and the UI should be block only on the first step.

Thanks.

**Comment by huyphams** [comment]
TablePlus doesn't allow edit while executing because TablePlus want to report the error position. I'm going to close this issue.
<img width="1216" alt="screen shot 2018-06-22 at 1 42 23 pm" src="https://user-images.githubusercontent.com/3654622/41761599-1c2ae8f8-7622-11e8-96b5-76598dcbf1cd.png">

**Comment by huyphams** [comment]
Hi @bhrd, I re-enable it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the feedback!
