### ISSUE TITLE
[Enhancement] Searching for a table and pressing enter should highlight the first table

### ISSUE THREAD

**Issue by scheMeZa** [TablePlus/TablePlus#1293]
Hi,

Thanks for your amazing work!

I don't know whether you accept enhancement ideas, but here's mine :)

When searching for a table it would be nice to select the first table from the results.

This way we can use the arrow keys to navigate the results.

Thanks in advance!

**Comment by hieuhlc** [comment]
@scheMeZa if you use Search Anything feature, the first item on result list will be automatically selected, then you can use arrows to navigate

**Comment by hieuhlc** [comment]
I think this feature helps us search faster and encourage us to perform most of navigations in the app

**Comment by huyphams** [comment]
As @hieuhlc suggestion, you can use Open Anything search (Command + P), the first item will be automatically selected. 
If you search and select an item on the left sidebar it will open it, which leads to bad UI experience.

**Comment by scheMeZa** [comment]
Thanks guys, that was exactly what I was looking for! :)
