### ISSUE TITLE
Update/add backup file name patterns to allow for sorting files by date

### ISSUE THREAD

**Issue by Cottser** [TablePlus/TablePlus#1294]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): n/a

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 244

3. The steps to reproduce this issue:

- File > Backup
- Click on field beside "File name:" to customize file name pattern.

This is a great feature to have. I think this is a more recent addition, but I find it missing zero-padded options (or just default to zero-padded, it's probably what most people want anyway if I had to guess). That, or provide preset "date" and "time" patterns that are formatted in a sortable way.

I would zero-pad the following patterns to 2 digits:

- month
- day
- hour
- minute
- second

So if the month is `7`, the pattern output should be `07` to allow for consistent sorting.

What I would like is a pattern like:

```
connection name,-,database name,-,year,-,month,-,day,-,hour,-,minute,-,second,
```

To output:

```
unknown_connection-unknown_database-2019-07-09--02-02-02
```

On July 9 2019 at 02:02:02.

Currently, it would output something like the following (haven't tested in the morning so not 100% sure about the hour output):

```
unknown_connection-unknown_database-2019-7-9--2-2-2
```

**Comment by huyphams** [comment]
I've fixed it, you can download the build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the feedback!
