### ISSUE TITLE
External schema/table(s) are not visible on RedShift

### ISSUE THREAD

**Issue by ehkygit** [TablePlus/TablePlus#1297]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 11.4 on machine but TablePlus uses 8.0.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.6(242)

3. The steps to reproduce this issue: connect to redshift via Postgres Connector and tables 
 under any External schemas are not displaying on the left

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @ehkygit I've added spectrum table on this build https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 please give it a try and let me know the result.
Ideally, I would like to split the PostgreSQL and Redshift into 2 drivers. They have a lot of different features now.

**Comment by ehkygit** [comment]
Hi @huyphams I tried recently and unfortunately issue still remains. I cannot see/fetch tables under an External Schema.

**Comment by ehkygit** [comment]
hello @huyphams any update regarding this bug ?

**Comment by huyphams** [comment]
Hey @ehkygit could you please run this query (on redshift) and let me know the result:
`SELECT schemaname as table_schema, tablename as table_name, 'TABLE' FROM svv_external_tables;`

**Comment by ehkygit** [comment]
@huyphams , I ran the query and returned with schemas has tables including externals.

**Comment by huyphams** [comment]
I've added Redshift Driver on this build, please download and give it a try: https://www.dropbox.com/s/4033rlop6eov1ur/TablePlus.dmg?dl=0
Thank you @ehkygit

**Comment by ehkygit** [comment]
@huyphams , I have just tried now. I am able to see RedShift driver but issue still remains. External tables are not visible. I tried many times and created new connection. Also, it still uses postgres driver. I don't know if this can be related with.

**Comment by huyphams** [comment]
Could you show me the screenshot of the connection status? This one?
<img width="359" alt="Screen Shot 2019-07-23 at 12 40 11 PM" src="https://user-images.githubusercontent.com/3654622/61725891-0504e180-ad47-11e9-98b8-054725431604.png">

**Comment by ehkygit** [comment]
it looks same with mine.

![image](https://user-images.githubusercontent.com/794267/61726187-86716980-ad71-11e9-9200-0f63556b2578.png)

**Comment by huyphams** [comment]
And have you changed the schema on the bottom left? 
<img width="306" alt="Screen Shot 2019-07-23 at 12 44 46 PM" src="https://user-images.githubusercontent.com/3654622/61726241-b60b7c00-ad47-11e9-8272-d4913538366e.png">

**Comment by ehkygit** [comment]
yes, I switch between external and internal ones. External schemas' tables are not visible as from the beginning. Internals have no issue, I can see all objects and types.

**Comment by huyphams** [comment]
Weird, here is the full query TablePlus uses to fetch all tables:
`(SELECT table_name, table_schema, table_type FROM information_schema.tables) UNION (SELECT c.relname AS table_name, n.nspname AS table_schema, 'MATERIALIZED VIEW' FROM pg_catalog.pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = 'm') UNION (SELECT schemaname as table_schema, tablename as table_name, 'TABLE' FROM svv_external_tables);` 
and I've UNION the result from external schema. Could you run it and check if there are external tables on result?

**Comment by ehkygit** [comment]
I ran the query. I couldn't return any external ones.

I found a problem in your query I guess. Table_name doesn't return table_names. It returns schemas. and also, table_Schema is not schemas, it is table itself.

I added a where condition to check my external schemas and it is there whit table_name column. that might be the reason. Could you please check once again ?

**Comment by huyphams** [comment]
Hmm, I don't quite understand this
`I found a problem in your query I guess. Table_name doesn't return table_names. It returns schemas. and also, table_Schema is not schemas, it is table itself.`
Could you explain it or show me a screenshot example?

**Comment by huyphams** [comment]
oh sh*t, I got it.

**Comment by ehkygit** [comment]
I was about to rephrase my comment. Select statement has a minor problem. glad to hear that you got it.

**Comment by huyphams** [comment]
I've fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you @ehkygit

**Comment by ehkygit** [comment]
great, it is working fine now as expected.
thanks @huyphams

**Comment by ehkygit** [comment]
@huyphams  can I request the new beta for our windows users as well ?

**Comment by huyphams** [comment]
Sure, we’re going to support redshift on the next Windows release this week

**Comment by ehkygit** [comment]
awesome, thanks @huyphams . It could be great if you can make it available for time being till the new release. also, I have other suggestions, can we discuss later on ? some minor bugs found and suggestions are there - nice to have.

**Comment by huyphams** [comment]
Sure, you can create an issue on Windows repo or email me at nick@tableplus.com
