### ISSUE TITLE
[Feature Request] Defer blobs and texts 

### ISSUE THREAD

**Issue by zineer** [TablePlus/TablePlus#1299]
Recent convert from SequelPro and the one thing I miss is the options for "Defer blobs and texts". With this option enabled, any blob or text field would get shown as "(not loaded)" initially, then you could double click to edit the field and it would load the data. 

I have a couple tables with large amounts of data in text fields, and don't need to see most of the info when I browse, so not loading the text fields would speed up browsing that table.

Using TablePlus build 242 and MySQL/MariaDB databases.

**Comment by erikdonohoo** [comment]
Would also love this. We have a table that stores exception traces of failures in our background processing jobs and the large blob columns make TablePlus choke. Absolutely love the product though.

**Comment by pieterclaerhout** [comment]
+1

Pretty much the only thing I'm missing after switching from Sequel Pro…

**Comment by yulinfeng000** [comment]
+1

**Comment by marijnbent** [comment]
+1

**Comment by marijnbent** [comment]
Duplicated issue: https://github.com/TablePlus/TablePlus/issues/1261
