### ISSUE TITLE
Support JSON pretty format

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#13]
Quick look: Right click on field > quick look.
Current TablePlus didn't support pretty format for data (Ex: JSON).

**Comment by Chinese1904** [comment]
@huyphams it seems it does not pretty format on my end using build 82 MariaDB. Is this known?

**Comment by maverickscrew** [comment]
@Chinese1904 yes, this is pending feature. I will come back to it asap. I'm working on dump functions.

**Comment by huyphams** [comment]
@Chinese1904 yes, this is pending feature. I will come back to it asap. I'm working on dump functions.

**Comment by sebslomski** [comment]
@Chinese1904 @huyphams I would love to have this feature as well. Can I somehow help implementing it?

**Comment by huyphams** [comment]
We will improve this to support JSON and XML in future, stay stunned 😄

**Comment by Chris1904** [comment]
@huyphams any updates on this? Pretty excited about this, because I am dealing with quite a few JSON columns haha

**Comment by huyphams** [comment]
Hi @Chris1904 I'm making a roadmap, so you guys can check it 👍

**Comment by 120dev** [comment]
Can you let us know where you are with adding this feature? Thanks a lot

![image](https://user-images.githubusercontent.com/4286701/206910015-1f048fb6-80db-4e02-9cad-e4c4f05b487e.png)

**Comment by adriel** [comment]
I believed its been added? Or are we talking about something else?
<img width="119" alt="image" src="https://github.com/TablePlus/TablePlus/assets/154217/01dae45f-0551-434a-9c63-92c1ba8ac5c4">
