### ISSUE TITLE
Query completion notifications

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#130]
Query completion notifications, would be nice!

**Comment by huyphams** [comment]
Sure 😸  💯

**Comment by bhrd** [comment]
Example: “query completed in 25 seconds” or “ERROR”🙂

**Comment by huyphams** [comment]
Hi @bhrd 
I have something new for you 😄 
<img width="1290" alt="nice" src="https://user-images.githubusercontent.com/3654622/34067376-12e0b0a2-e257-11e7-842a-b1aa16523cd4.png">

**Comment by huyphams** [comment]
If you minimized application or move to another application, TablePlus will show this.
<img width="631" alt="screen shot 2017-12-16 at 11 48 02 am" src="https://user-images.githubusercontent.com/3654622/34067386-44d4ad7a-e257-11e7-964d-7d54d107da68.png">

**Comment by huyphams** [comment]
And there are the whole new workspace managerment to help you work with mulple databases.
<img width="1262" alt="screen shot 2017-12-16 at 11 51 58 am" src="https://user-images.githubusercontent.com/3654622/34067396-899e6fa4-e257-11e7-90d8-8130fa4a35ee.png">

**Comment by bhrd** [comment]
Omg this is amazing turnaround time!
👏🏼👏🏼👏🏼🎉🎉. Can’t wait for this build! Kudos to you and your team!

**Comment by huyphams** [comment]
Update:
<img width="1290" alt="customizename" src="https://user-images.githubusercontent.com/3654622/34073226-80a73974-e2c7-11e7-9be6-b1002e50ee87.png">

**Comment by huyphams** [comment]
Hi @bhrd, are you there? please ping me via duchuykun@gmail.com we have a gift for you.
