### ISSUE TITLE
Foreign Key links not sanitised

### ISSUE THREAD

**Issue by dctsystems** [TablePlus/TablePlus#1301]
Postgres & MysqL

Build 242

Create a table with a text column as primary key field.
Add an entry with an apostrophe into that field.

Create new table with a foreign key which references the first table
Add an entry which has an apostrophe in its foreign key field,
Click on the array to generate an SQL error.

**Comment by huyphams** [comment]
Thanks @dctsystems I've fixed it, it will be released in the next update!
