### ISSUE TITLE
copy paste booleans between database types

### ISSUE THREAD

**Issue by dctsystems** [TablePlus/TablePlus#1302]
Postgres and Mysql

build 242

Create a table with a boolean column in Postgres
Enter data - it appears as TRUE or FALSE.

Create a table with a boolean column in Mysql
Enter data - it appears as 0 or 1.

Copy a row from the Postgress table, and paste it into the MySQL table.
Tableplus tries to enter "T" and "F", which when pushed and retrieved form mysql both get interpreted as 0, so the MSQL table always contains false.

**Comment by huyphams** [comment]
I've improved it, it will be available on the next build.
