### ISSUE TITLE
Whenever I export as SQL inserts (row or table), uuid fields get hashed and prepended by 'X'

### ISSUE THREAD

**Issue by diogodpc** [TablePlus/TablePlus#1303]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 2.6 (242)

3. The steps to reproduce this issue:

3.1 Access a row Table
3.2 Right Click
3.3 Copy Rows As->SQL Insert Statement
3.4 Paste into editor

Example of exported Data:
INSERT INTO `acl_roles` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `name`, `description`, `deleted`) VALUES (X'36396138333734612d613332342d313165392d383935382d303035303536383436663736', '2019-07-10 15:07:19', '2019-07-10 15:07:19', X'64356435373038652d373164612d313165392d623036352d303035303536383436663736', X'64356435373038652d373164612d313165392d623036352d303035303536383436663736', 'Users (Pull)', 'General System Users teams.', '0');

What it should be:
INSERT INTO `acl_roles` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `name`, `description`, `deleted`) VALUES ('69a8374a-a324-11e9-8958-005056846f76', '2019-07-10 15:07:19', '2019-07-10 15:07:19', 'd5d5708e-71da-11e9-b065-005056846f76', 'd5d5708e-71da-11e9-b065-005056846f76', 'Users (Pull)', 'General System Users teams.', '0');

Or am I missing an option to control this behavior?

Thanks,
dc

**Comment by huyphams** [comment]
Hi @diogodpc thank you for the feedback, it's duplicated with this issue: https://github.com/TablePlus/TablePlus/issues/918
I've explained it, please check out it!
