### ISSUE TITLE
Exporting data with line breaks to CSV

### ISSUE THREAD

**Issue by jjernberg** [TablePlus/TablePlus#1304]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 11.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

242

3. The steps to reproduce this issue:

Select data which has line breaks
Right click data and select "Export result..."
Export results as CSV with or without convert line break to space selected

Line breaks are included either way in the CSV.   No combination of CSV export options has been found to avoid this.

Example data:
```
How would you rate your experience today? Please reply with a number:
4-Above average
3-Average
2-Neutral
1-Below average
```

Workaround is selecting all data and copying using `Copy Rows As > CSV including field names` which works as expected.

**Comment by huyphams** [comment]
Oops, my bad, I've fixed it here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please let me know if you're still seeing it.
