### ISSUE TITLE
Dump fails

### ISSUE THREAD

**Issue by AaronHolbrook** [TablePlus/TablePlus#1307]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.6 (242)

3. The steps to reproduce this issue:
Perform a database backup.

Noted: If the bug is related to data, please attach an example SQL data.
```
Create tunneling...
Dumping...
mysqldump: [Warning] Using a password on the command line interface can be insecure.

mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'database_name' AND TABLE_NAME = 'wp_commentmeta';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)

Compressing....
Backup database completed
```

This happens any time I try to perform a database backup using TablePlus now.

**Comment by huyphams** [comment]
Hey @AaronHolbrook the issue is related to MySQL binary itself [MySQL issue](https://bugs.mysql.com/bug.php?id=91640) (TablePlus introduces the MySQL 8 binary and set it as default on the build 242).
Please try to change to MySQL 5.7 and let me know the result.

**Comment by AaronHolbrook** [comment]
Hey @huyphams, the database I'm connecting to is running 5.7.26, and I have no control over the version of mysql that the webhost is running.

How do I change TablePlus to Mysql 5.7?

**Comment by AaronHolbrook** [comment]
![Screen Shot 2019-07-15 at 6 45 21 AM](https://user-images.githubusercontent.com/953022/61213929-1f4a1a00-a6cc-11e9-80d0-23ff5d0818f4.png)

**Comment by huyphams** [comment]
<img width="772" alt="backup" src="https://user-images.githubusercontent.com/3654622/61213981-05fd9980-a6dd-11e9-9919-a4cc17c94cc5.png">

**Comment by AaronHolbrook** [comment]
That worked, thanks so much!

**Comment by huyphams** [comment]
Thank you for the confirmation, I will try to optimize it. TablePlus should choose the driver default based on the connection version.

**Comment by AaronHolbrook** [comment]
That would be very helpful, thanks for the quick support @huyphams !

**Comment by babul** [comment]
Would it be possible to add a backup option for MySQL 8.0 to be `--column-statistics=0` to be added to the mysqldump?

**Comment by huyphams** [comment]
I just added this, thanks @babul

**Comment by kokroo** [comment]
> Thank you for the confirmation, I will try to optimize it. TablePlus should choose the driver default based on the connection version.

I believe this is still not a thing?
