### ISSUE TITLE
[Design suggestion] Darker backgrounds in light theme

### ISSUE THREAD

**Issue by mikl** [TablePlus/TablePlus#1308]
Hi there,

Sorry if this is a bit of a bikeshed-issue, but I wanted to try out TablePlus, but found it somewhat uncanny and un-macOS-like, and that was a bit of a turn-off.

Here's the sidebar, TablePlus (left) compared to Postico (right):

<img width="524" alt="Screenshot 2019-07-15 at 14 43 59" src="https://user-images.githubusercontent.com/10263/61217300-e70fff00-a6fe-11e9-82ec-7d071ecaa553.png">

They are functionally equivalent, but TablePlus has a white background for the pane and grey background for the text fields, where Postico has the opposite.

I find that colour choice strange. Input fields on macOS (dark mode aside) almost always have a white background, and almost any kind of form has a light grey background to make them stand out. A form field with a grey background is usually a *disabled* field.

The settings dialog has the same problem, here is TablePlus:

<img width="500" alt="Screenshot 2019-07-15 at 14 53 43" src="https://user-images.githubusercontent.com/10263/61217619-9a78f380-a6ff-11e9-839c-e5e344dc8f46.png">

Compared to MailMate:

<img width="520" alt="Screenshot 2019-07-15 at 14 46 36" src="https://user-images.githubusercontent.com/10263/61217631-a2d12e80-a6ff-11e9-9cbc-0a6dd0eadd9b.png">

I've looked through all well-designed macOS apps I could think of, and they all use the same grey background and white text fields, and that makes TablePlus look strange in comparison.

This is a small detail, but I think it could go a long way towards making TablePlus look more at home on macOS.

**Comment by huyphams** [comment]
Thank you @mikl for the feedbacks. It's strange, I didn't change the background of the text fields. (because I need to follow the theming guideline). Maybe there is a visualize effect which overrides the background color. Let me check and improve it.

**Comment by huyphams** [comment]
I've updated the schema color on Catalina, not sure on the older macOS.
<img width="1360" alt="Screen Shot 2019-11-08 at 10 28 15 AM" src="https://user-images.githubusercontent.com/3654622/68483916-bce4ce80-0212-11ea-9c81-e627fe8b46f7.png">

**Comment by jamesratcliffe** [comment]
It's very dark on my system.
![image](https://user-images.githubusercontent.com/20323342/68597443-f44db800-046a-11ea-9245-a2822a5d12d8.png)
macOS 10.14.6, TablePlus 2.11 (276)

**Comment by huyphams** [comment]
Thanks @jamesratcliffe I can reproduce and fix the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It's pretty weird that Apple uses the light effect on macOS 10.11, 10.12, 10.13 and 10.15 BUT NOT on 10.14, on 10.14 it becomes darker than the others.

**Comment by jamesratcliffe** [comment]
That is weird.

Looks good now. Thanks!

**Comment by huyphams** [comment]
There are remaining Windows (preferences, backup, restore etc...) I will update it in the future releases!
