### ISSUE TITLE
Show an indication of elapsed time since query submission, within the status bar

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#131]
An indication of the **elapsed time** since the query is submitted to the server, within the status bar, would be a neat addition.

**Comment by huyphams** [comment]
Nice idea.
Currently, this section is empty. We can put the `elapsed time` here 😸 
<img width="853" alt="screen shot 2017-12-14 at 10 30 59 am" src="https://user-images.githubusercontent.com/3654622/33974251-fed8d9b6-e0b9-11e7-9e55-5db359b3c09d.png">

Huy.

**Comment by dougreid72** [comment]
Could this be expanded to show query time, fetch time and transfer time?

**Comment by cotfas** [comment]
+1 Some of the times the queries takes longer than 2min or more, will be nice to know when will finish
