### ISSUE TITLE
double-clicking the SQL button opens two windows instead of one "sticky" window

### ISSUE THREAD

**Issue by alvint** [TablePlus/TablePlus#1312]
This is related to issue #579, which enabled double-clicking the SQL button to create the SQL tab sticky, similar to tables. However, the fix for issue #782 seems to have broken this behavior. Is it possible for TP to wait to see if a click on the SQL button is actually a double click before opening a new window? That should allow the two features to coexist.

**Comment by alvint** [comment]
Why closed? This is still an issue...

**Comment by alvint** [comment]
Honestly, all new SQL tabs should probably be sticky anyway.

**Comment by huyphams** [comment]
Hi @alvint we've changed the behavior, all SQL tabs now are sticky.
