### ISSUE TITLE
Support autocomplete with table aliases where the table names are reserved keywords.

### ISSUE THREAD

**Issue by MaximilianTyrtania** [TablePlus/TablePlus#1314]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 11
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.7(246)
3. The steps to reproduce this issue:
Autocompleting field names works if I say

Select client.field1 from client where client.

But If I say

Select c.field1 from client c where c.

it does not. DBeaver "understands" this better and offers autocomplete in that scenario.

Thanks for a great piece of software and best wishes from Berlin,

Max

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
TablePlus does support alias, the reason it fails in the `Select c.field1 from client c where c.` because the table name is the reserved keywords (client).
I will improve it, thank you @MaximilianTyrtania

**Comment by MaximilianTyrtania** [comment]
Ah, I see! Thanks for the explanation and keep up your good work! Cheers, Max

**Comment by huyphams** [comment]
Hey @MaximilianTyrtania I've improved it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you have any issues left.
