### ISSUE TITLE
Beautify bug with unhex

### ISSUE THREAD

**Issue by hirish** [TablePlus/TablePlus#1317]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
244

3. The steps to reproduce this issue:

If you beautify the following statement (a la https://database.guide/3-ways-to-unhex-a-string-in-mysql/):

```
SELECT
	*
FROM
	table
WHERE
	id = x'00000000000000000000000000000000';
```
It will incorrectly add a space between the `x` and the `id`.

**Comment by huyphams** [comment]
Hi, the bug has been addressed in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue.

**Comment by hirish** [comment]
Yes, the build linked fixes the issue -- thanks!
