### ISSUE TITLE
Field '$readPreference' is currently not supported

### ISSUE THREAD

**Issue by ryan-idea42** [TablePlus/TablePlus#1318]
When connected to AWS DocumentDB, I get this error when I try to save changes to a document. 

`Field '$readPreference' is currently not supported`

Since AWS DocumentDB is based on MongoDB v3.6, and I'm not having any issues with this using regular MongoDB v3.6 OR using another MongoDB tool against DocumentDB, I wanted to report this to you to fix. 

Please let me know if there's an option or way to disable whatever is causing this error. 

I'm currently using TablePlus 2.7 build 247

**Comment by huyphams** [comment]
Currently, TablePlus uses the official [mongo-c-driver](https://github.com/mongodb/mongo-c-driver) for Mongo connection and the `$readPreference ` was implemented in the driver. I'm not sure that there will be an option to disable it. Let me check it.

**Comment by ryan-idea42** [comment]
@huyphams Not sure if y'all changed anything with the latest beta build, but it's working now. 

Either y'all changed something for AWS DocumentDB was updated to handle that field. 

I can now use AWS DocumentDB with TablePlus!

**Comment by huyphams** [comment]
I believe it was changed on the Amazon Server. I will close this issue for now. Please Let me know if you're still seeing it.
