### ISSUE TITLE
Stalled "Collecting database information" on Oracle

### ISSUE THREAD

**Issue by pbreit** [TablePlus/TablePlus#1319]
I am experiencing this. It seems to stall on "Collecting database information...".

It's an Oracle database which I have no trouble connecting to with Navicat or DBeaver.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 2.7 (247)
MacOS 10.14.5

3. The steps to reproduce this issue:
Select connection in welcome screen
Right-click "Connect"

Test Connection works ok. It flashes "Connecting to database" and then moves on which would indicate to me the connection was successful.

Is there any way to skip the Collecting database information or is that necessary to make queries?

Is there any log?

**Comment by veics** [comment]
I also have this issue. It takes several minutes to connect.

**Comment by huyphams** [comment]
This would be fixed in the build https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
Let me know if you're still seeing the bug.
