### ISSUE TITLE
Reloading workspace does not reconnect, and is stuck at "Refreshing"

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#132]
Reloading the workspace does not trigger a reconnect, and is stuck at "Refreshing" until I close the window and reopen the connection again.
![image](https://user-images.githubusercontent.com/221584/33958837-8726896e-dffa-11e7-8f17-28fb4a2c6fdf.png)
I'm facing this with Redshift, when trying to reconnect after logging out and logging back into my computer. My connection is good, as I have other redshift clients that reconnect without trouble.

**Comment by huyphams** [comment]
Hi @bhrd, thank you. I will investigate on this issue and fix it soon, will keep you posted.
Huy.

**Comment by huyphams** [comment]
I added a code check `connection is alive` before refreshing the workspace. Not sure if this fix, I'm still testing on it.

**Comment by bhrd** [comment]
I can also test if you have an early build, let me know.

**Comment by huyphams** [comment]
Sure, https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
But remember that the UI/UX are uncompleted (horizontally workspace tab, clickable notification etc...).

**Comment by huyphams** [comment]
I have added force reconnect command + shift + R and the timer checks the server if it's not responding. So this issue should be fixed.
