### ISSUE TITLE
Unable to Commit Changes (Windows)

### ISSUE THREAD

**Issue by bshea5** [TablePlus/TablePlus#1321]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mssql/server:2017-latest
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.1(71)
3. The steps to reproduce this issue:
Go to structure view for a table. Edit a column property and attempt to save. No changes are commit, and it seems like no action is taken at all, as changes remain highlighted orange/yellow.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @bshea5 , have you press Control + S or Edit > Commit?
Btw, please report the Windows issue here: https://github.com/TablePlus/TablePlus-Windows/issues

**Comment by bshea5** [comment]
Yes, I've tried both methods.

**Comment by bshea5** [comment]
The problem started with the most recent update. I've never ran into this problem before.

**Comment by huyphams** [comment]
Thank you @bshea5 i will double check it
