### ISSUE TITLE
Incorrect date shown in grid.

### ISSUE THREAD

**Issue by felixk** [TablePlus/TablePlus#1322]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 4.0.0.672
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.7(246)
3. The steps to reproduce this issue:

- Create a table with a date field.
- Insert a date as follows: set somedate = '2019-06-25'
- Upon viewing table contents the grid will show the date as 2019-06-24.

![image](https://user-images.githubusercontent.com/89974/61728994-4f389380-ad44-11e9-827b-fb9b750a00a8.png)

If using cqlsh, the date is correct:

![image](https://user-images.githubusercontent.com/89974/61729070-78592400-ad44-11e9-9f12-3058442e58d0.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @felixk thank you for letting me know. I've fixed it. The issue was related to the auto-config timezone. I'm sorry about that, this is a critical bug, you can download the hotfix here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by felixk** [comment]
Awesome! thanks so much!

**Comment by felixk** [comment]
Just tried it, works perfectly now, thanks again!
