### ISSUE TITLE
Minor UI Issue when Updating Multiple Records

### ISSUE THREAD

**Issue by Raistlfiren** [TablePlus/TablePlus#1326]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MYSQL 5.6.26

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.5 (233)
3. The steps to reproduce this issue:
Run a SELECT query over multiple records. 
In query view update multiple records with a new ID.

When updating multiple records at the same time, the UI glitches and doesn't show the change for records. In this example, I edited the first three records already, but they still show NULL for the value.
<img width="159" alt="Screen Shot 2019-07-24 at 10 57 45 AM" src="https://user-images.githubusercontent.com/234712/61809197-73f34080-ae02-11e9-8d61-2e6fa925a4f0.png">

If I click on the record, then it does show the updated value.
<img width="172" alt="Screen Shot 2019-07-24 at 10 57 54 AM" src="https://user-images.githubusercontent.com/234712/61809290-9c7b3a80-ae02-11e9-8680-03ed49820059.png">

Thanks!

**Comment by huyphams** [comment]
Hi, i believe it was fixed on the latest release 246.

**Comment by Raistlfiren** [comment]
@huyphams  - Sorry for posting this! I just updated, and does seem to be working properly. Thanks!
