### ISSUE TITLE
Generate multiple insert blocks when exporting tables

### ISSUE THREAD

**Issue by erikdonohoo** [TablePlus/TablePlus#1330]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySql 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 246

3. The steps to reproduce this issue:

If a do an export of a table, it generates one insert statement. When you have 400k+ rows in a table, this won't ever work when you try and import it later. The export function needs to generate multiple insert statements, one for every X rows (maybe 1k) like Sequel Pro does. Otherwise the import fails every time because it's too much data for one statement for the driver to handle. Does that make sense? I'm happy to provide more details if necessary.

The Backup feature isn't what I'm looking for here. I only need data from a select few tables in my DB at any given time. My entire DB is like 7GB so Backup is extremely expensive. Especially when you are testing migrations against your data, you just need the tables the migrations will run against. Thank you!

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @erikdonohoo thank you for the feedback, it was duplicated with this issue: https://github.com/TablePlus/TablePlus/issues/1109

**Comment by erikdonohoo** [comment]
Oh dang. I didn't find that one. Sorry for opening a duplicate. Thank you!
