### ISSUE TITLE
Connections,database,SQL query icons overlapped.

### ISSUE THREAD

**Issue by radiatorius2048** [TablePlus/TablePlus#1331]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
driver-independent

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.7 (246)

3. The steps to reproduce this issue:
7...9 connections opened simultaneously

![image](https://user-images.githubusercontent.com/20090434/62049708-7b5a8580-b218-11e9-910b-d85a6d711a78.png)

**Comment by huyphams** [comment]
thanks, it's duplicated with https://github.com/TablePlus/TablePlus/issues/786
