### ISSUE TITLE
Cancel dialog doesn't show running queries

### ISSUE THREAD

**Issue by federicodonner** [TablePlus/TablePlus#1332]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL DBVERSION_70

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.4 (246)
(MacOS 10.14.6)

3. The steps to reproduce this issue:
- Run a query that takes a few seconds
- Press the cancel button (cmd+.)
- The running queries dialog opens, it says "getting process list" but nothing shows up

**Comment by huyphams** [comment]
Hi @federicodonner thank you for the feedback. I figured out this issue recently, there is a permission denied issue which could result in this behavior.
Could you please try this patch: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 and let me know the error. It does not fix anything, but it will report the error.

**Comment by federicodonner** [comment]
Hi huyphams
I installed the version you sent me and tried to cancel the query. I got this error prompt:

> Msg: 297, Line 1, State: 1, Level: 16
> The user does not have permission to perform this action.

Let me know if you need any more tests.

**Comment by huyphams** [comment]
So I think the answer: `The user does not have permission to perform this action.` TablePlus couldn't anything, you can use a user which has this permission/.

**Comment by federicodonner** [comment]
I couldn't understand your message. I have root permissions on my computer, I don't have root permissions on the database I'm querying. What configuration do you need me to change?

**Comment by huyphams** [comment]
The root permission on the computer has nothing to do with the permission on the database, also, TablePlus couldn't change the permission itself (How does it make sense when it can do a thing that it does not have permission?)
`I couldn't understand your message ` => TablePlus does not produce this message, TablePlus send the query to the server and receive it from server. It uses this query to fetch the executing query:

```
select * from information_schema.processlist
```
So you must you a user which has permission to read the processlist.

**Comment by federicodonner** [comment]
I understand, I thought that error message is what you needed. So, what are the next steps to help you with this issue? Should I get a db user that can read the processlist? I'm not the dba so I need to ask for any changes to my user.

**Comment by huyphams** [comment]
Yep, that's true. You need to ask your dba to grant your user the permission, which can run this query:

select * from information_schema.processlist

**Comment by huyphams** [comment]
So, I'm closing this issue, if you need anything else, feel free to pm nick@tableplus.com we are happy to help you sort it out.
