### ISSUE TITLE
[Feature Request] Open new tables in a new tab by default as a preference

### ISSUE THREAD

**Issue by vesper8** [TablePlus/TablePlus#1333]
Currently if you use the quick search to open a new table (CMD-P), the table will open in the current tab. So if you want to open a new table in a new tab, you first have to open a new blank tab (CMD-T) and then use CMD-P to open a table in this new tab.

VSCode does something similar and it has an option to set the default behaviour when opening new files.

Could you please add a similar option to TablePlus' preferences so that we can optionally set it so CMD-P always opens a new tab with the new table by default?

I would definitely use that and it would save having to do two commands instead of one

Thanks!

**Comment by huyphams** [comment]
Thanks, it has been requested in https://github.com/TablePlus/TablePlus/issues/1053

**Comment by huyphams** [comment]
it's supported, please checkout https://github.com/TablePlus/TablePlus/issues/1053
