### ISSUE TITLE
Oracle Wallet Support

### ISSUE THREAD

**Issue by nmendelson** [TablePlus/TablePlus#1334]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oracle

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 246

Please support Oracle Wallet (necessary to connect to Oracle Autonomous Database) https://docs.oracle.com/cd/B28359_01/network.111/b28530/asowalet.htm#i1009041

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by lor1x** [comment]
I would like this too, don't want to waste GB's of data on my machine by installing their apps when you have Autonomous DB available but I can't connect to it no matter what I do on TablePlus, same error always ORA-12537. I used the same data I got from the walled but having the possibility to use the wallet directly would probably fix this issue for me

**Comment by mjoyce91** [comment]
Our team recently switched to Oracle autonomous database. As paid license users, we'd love to see this.

**Comment by huyphams** [comment]
Added support PEM file.
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
