### ISSUE TITLE
PostgreSQL import doesn't include the least INSERT section.

### ISSUE THREAD

**Issue by JacekJMMJ** [TablePlus/TablePlus#1335]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.7 and 10.9 (and probably on others work the same)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 2.7 (248)

3. The steps to reproduce this issue:
- Select a PostgreSQL Table -> Export -> SQL
- Delete the Table.
- Import From SQL Dump... -> select the exported file -> Import

After this operation the last part of the import file will not be imported and in the Table will have less rows.
In my example I had 4349 after export & import I have 4000 rows. The last INSERT INTO "public"."... section from the import file was not executed.

Please help. This happens all the time when I import from SQL Dump.

![Screen Shot 2019-07-30 at 1 44 28 PM](https://user-images.githubusercontent.com/25058677/62126841-eb2c4700-b2d0-11e9-9b5c-cdc7c143bc3b.png)

**Comment by huyphams** [comment]
Thank you @JacekJMMJ it was a serious bug, I'm about to release a hotfix now. Please wait for me for a min.
Reason:
TablePlus introduced a new importer recently which can handle large dump files but it didn't handle the last chunk file correctly. I've fixed it.

**Comment by JacekJMMJ** [comment]
Will the hot fix be available in TablePlus -> 'Check for Updates...' ? Or somewhere else?

**Comment by huyphams** [comment]
yep, I'm uploading the new build, I will notify you as soon as it's released.

**Comment by huyphams** [comment]
It's released now!
