### ISSUE TITLE
SQL Export sets timezone to UTC even though server timezone is PST

### ISSUE THREAD

**Issue by bretvanhorn** [TablePlus/TablePlus#1336]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB 10.2.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.8 (250) and previous release

3. The steps to reproduce this issue:

Exporting data from MariaDB adds in the following lines to set the server timezone. It appears to default to UTC, even though my server is using the system time zone, which is PST. All of my dates are stored based on the PST timezone. When I import the data to another server, all of my dates are adjusted based on that and thus, 7 hours behind where they should be. 

The offending lines:

```
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
```

Removing those lines prior to import seems to keep the dates intact.

**Comment by huyphams** [comment]
I've updated the MariaDB and removed those lines, you can download it here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by bretvanhorn** [comment]
No problem! Thanks for the quick patch!

**Comment by JackEllis** [comment]
@huyphams Just wanted to report an issue I had in v 2.8.1 (252). I exported a mySQL table from the server, imported it locally and the times were off. Timezones may have differed so let me know if this is expected functionality :)

**Comment by huyphams** [comment]
Are you using the MariaDB driver @JackEllis ?

**Comment by joelhoward** [comment]
I'm experiencing the same issue with our MySQL database servers.  Version selected on the MySQL connection is "MySQL 5.x".  It does when exporting from both our MySQL 5.7 and 5.1 severs.

**Comment by dragg** [comment]
@huyphams 
I'm having this issue as well and I still use SequalPro for export/import purpose so we should remove those lines or at least give an option don't change timezones during export.

**Comment by huyphams** [comment]
I've removed those lines on the new updates. Thanks for reminding me.

**Comment by huyphams** [comment]
Please let me know if you're still seeing it in the newest release 282, then I will reopen the issue.

**Comment by dragg** [comment]
@huyphams Just curious can I download this release somewhere right now or should I wait for the new release in [the changelog page](https://tableplus.com/blog/2017/02/changelogs.html)?

**Comment by huyphams** [comment]
If you're on the beta channel, it should be the build 284, otherwise, it's the build 282. They're the same except the build 284 contains Oracle Lib for Oracle Driver.
TablePlus Main Menu > Check for updates...

**Comment by dragg** [comment]
@huyphams I've just updated to build 282 and if I use export functionality with selecting necessary tables then it's good and we don't have the discussed SQL rows. Thanks for that!

But if I use in the menu "File -> Backup" then the script still has
```
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
```at the beginning and the following script at the end of the dump file. I assume it should works in the same way, right?

**Comment by huyphams** [comment]
Hi @dragg TablePlus backup function uses the MySQL Official Binaries to produce the backup file (and that's the reason why TablePlus export function has the TIME_ZONE flag in the first place, I'd followed it). 
So there is nothing I can do to fix it but I believe that there will be a flag that can disable the TIME_ZONE:
https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html

**Comment by huyphams** [comment]
and this is that flag:
`
--tz-utc

This option enables TIMESTAMP columns to be dumped and reloaded between servers in different time zones. mysqldump sets its connection time zone to UTC and adds SET TIME_ZONE='+00:00' to the dump file. Without this option, TIMESTAMP columns are dumped and reloaded in the time zones local to the source and destination servers, which can cause the values to change if the servers are in different time zones. --tz-utc also protects against changes due to daylight saving time. --tz-utc is enabled by default. To disable it, use --skip-tz-utc.
`

**Comment by dragg** [comment]
@huyphams 
Ok, I got it. Thank you for the explanation and your hard work!

**Comment by joelhoward** [comment]
Fixed for me also on macOS with 284.  Thanks @huyphams! Keep up the excellent work.
