### ISSUE TITLE
PostgreSQL User Management

### ISSUE THREAD

**Issue by jacobhaug** [TablePlus/TablePlus#1338]
I love TablePlus, it is an excellent product. I've purchased a license for everyone on my team. I just wish that you had support for user management in PostgreSQL. I know it was mentioned that you were going to work on it next back in 2018.

https://github.com/TablePlus/TablePlus/issues/542

Do you have any update on this?

**Comment by huyphams** [comment]
Hey @jacobhaug thank you. You can check the progress here: https://github.com/TablePlus/TablePlus/projects/1
- Work in progress: the task which I'm working on it.
- Very soon: the task will be moved to Work in progress. (After the task in WIP is done).
- Roadmap: new ideas, upcoming features, etc...
