### ISSUE TITLE
cannot logon to happy plan

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#134]
Cannot logon to happy plan in app, even though pw is correct

**Comment by huyphams** [comment]
Hi @brian-crane 

I checked and everything is fine, there are a forgot password in case you can't remember password.
If you don't want to enter the password, you can continue with github, butbucket or gmail. I think it's easier.

Huy.

**Comment by mikebronner** [comment]
Just as a point of feedback, I was able to log in using Github today. (not sure if the OP was using Github or not)
