### ISSUE TITLE
export db data crashed

### ISSUE THREAD

**Issue by jjhesk** [TablePlus/TablePlus#1340]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 8
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
252
3. The steps to reproduce this issue:
export 2.1gb data form the mysql drive for 2 millions rows
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @jjhesk did you export the query result or right-click to a table and choose export?

**Comment by jjhesk** [comment]
right-click to a table

**Comment by huyphams** [comment]
Hi @jjhesk could you please try the new build 278, I've resolved a memory issue recently, hopefully, it can also resolve this issue.
