### ISSUE TITLE
failed from mysql import too big of query

### ISSUE THREAD

**Issue by jjhesk** [TablePlus/TablePlus#1341]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 8
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
252
3. The steps to reproduce this issue:
import 155mb of the table content and run insert
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @jjhesk thank you,
Did you use the Import CSV or Import SQL or you run it in Query Editor?

**Comment by jjhesk** [comment]
Import SQL

**Comment by huyphams** [comment]
I'm sorry because of the delay, I think this issue is related to the max_allowed_packet where did you get the dump file,  did you export it by TablePlus?
