### ISSUE TITLE
Re-order folders in Favorite list

### ISSUE THREAD

**Issue by Jailyard90Grad** [TablePlus/TablePlus#1344]
I group my queries in folders in the Favorites menu. I would like to be able to re-order these folders. Currently I can drag/drop them but only into a pre-existing folders where they become sub-folders. I would like to be able to re-order them at the parent folder level.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 253

3. The steps to reproduce this issue:
- Try to drag and drop a folder to a parent level position in the Favorites menu. It does not move.
- Try to drag it into another folder so that it becomes a sub-folder. That works and is the only way it can be moved.

**Comment by huyphams** [comment]
It's supported now.
