### ISSUE TITLE
Feature request: Option to show timing in milliseconds

### ISSUE THREAD

**Issue by philp** [TablePlus/TablePlus#1345]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 9.5.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

252

3. The steps to reproduce this issue:

When running any kind of query, the execution time is displayed in the footer. Once this goes beyond 1000ms it is displayed in seconds only. Although that's nice to have for long running queries, it would be great to have the option to display in milliseconds. For example, if I'm comparing queries which take ~1500ms, it's not easy to compare timings without using `EXPLAIN ANALYZE`.

**Comment by huyphams** [comment]
I've updated the time format. Now TablePlus show `1.234 s` instead of `1 s`. Thank you for the feedback!

**Comment by huyphams** [comment]
You can download the hotfix build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!
