### ISSUE TITLE
TablePlus saving saves non current item

### ISSUE THREAD

**Issue by MaximilianTyrtania** [TablePlus/TablePlus#1349]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PG 11.3
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.8.1 (252)
3. The steps to reproduce this issue:
I'm working)  a lot with PG functions and views. Sometimes (like in the attached screenshot) I'd open a view (or a function), change something, hit command-S (I'm on Mac OS X) and the displayed error message would refer to some other function (like in the screenshot). TablePlus appears to be confused.
BTW, you always say "DDL changes cannot be undone" which is not true for PG (which allows DDL statements in transactions to be rolled back
![Screenshot 2019-08-06 at 11 30 03](https://user-images.githubusercontent.com/35692645/62529234-8fb50880-b83e-11e9-862a-869e10b92022.png)
). 
Noted: If the bug is related to data, please attach an example SQL data.
Best wishes from berlin, Max

**Comment by MaximilianTyrtania** [comment]
What I forgot to mention - I usually just open a new SQL tab, paste the code there and all is well.

**Comment by MaximilianTyrtania** [comment]
Unfortunately this one is still around. I think you should be able to reproduce it on your end like this:
Open some function (plpgSQL). Edit the function body, and make some error (non closing bracket or something.) Hit command-S. Table Plus will report the error correctly. Close the tab without saving. Open some other function and edit its body, this time without an error. Now hit cmd-S again. Table Plus will report the previous error again.

**Comment by huyphams** [comment]
Hi @MaximilianTyrtania you have to discard the change before doing some other task, if you did not discard the change, TablePlus would try to commit all the pending task, which includes the previous change.
You can discard the change by clicking the button on the top left.

**Comment by MaximilianTyrtania** [comment]
Hi Henry,

ooohh, I see. Thanks for telling me! You can close the issue then.

Best wishes all the way from Berlin,

Max

> On 16. Oct 2019, at 15:45, Henry Pham <notifications@github.com> wrote:
> 
> Hi @MaximilianTyrtania you have to discard the change before doing some other task, if you did not discard the change, TablePlus would try to commit all the pending task, which includes the previous change.
> You can discard the change by clicking the button on the top left.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Maximilian Tyrtania 
Contact King Softwareentwicklung 
Tel.:    ++0152/29270736
http://www.contactking.de

**Comment by huyphams** [comment]
Thanks for confirming!
