### ISSUE TITLE
MySQL enum fields

### ISSUE THREAD

**Issue by mrmonat** [TablePlus/TablePlus#135]
I have a problem with mysql tables containing enum type fields. If I change values of them, TablePlus isn't generating a query for that (blank popover, when I click on "preview"), and if I click on "commit", the changes are not saved to the table.

**Comment by huyphams** [comment]
Hi @mrmonat 
I just tested on the lasted build 77 and the enum still working. But I think the UI/UX of table structure when creating enum is bad. I'm thinking about this and will improve it.

<img width="1363" alt="enum" src="https://user-images.githubusercontent.com/3654622/34079304-11143bf6-e35e-11e7-8ba7-18ac18cd271e.png">

**Comment by aphex** [comment]
To add to this, as someone is looking at enum, is it possible to update the data view of enum columns also. It would be really nice if they used a dropdown select box instead of being able to type whatever into the box.

thanks!

**Comment by clessg** [comment]
I agree with aphex, it would be a really helpful addition. To give an idea, here is how Querious handles an enum field: https://i.imgur.com/B4HVbQk.png

**Comment by huyphams** [comment]
We will support user define type (include enum) in the next update 😁

**Comment by huyphams** [comment]
It's supported in the newest build.

**Comment by ShamanNguyen** [comment]
I got the error: SyntaxError: Unexpected identifier 'TABLE'

**Comment by huyphams** [comment]
could you show me the screenshot of the table structure and the generated query @ShamanNguyen thanks!
