### ISSUE TITLE
Feature request: Data import and replace/update data

### ISSUE THREAD

**Issue by sgwebmaster** [TablePlus/TablePlus#1350]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
252

Sequel Pro has a feature where you can select between different import methods like insert, update, replace. This feature is really helpful for data management using imports

![image](https://user-images.githubusercontent.com/53335473/62593704-492ce000-b90a-11e9-8cd6-127bb555bfb7.png)

**Comment by jakedewitt87** [comment]
Yes I keep reaching for this feature, this would be very helpful to have some way of updating/modifying existing table records via an import from a CSV file.

**Comment by huyphams** [comment]
It's implemented here: https://github.com/TablePlus/TablePlus/issues/420
