### ISSUE TITLE
Feature Request: Don't allow favourites to be edited outside the popup

### ISSUE THREAD

**Issue by jacquipickup** [TablePlus/TablePlus#1351]
When you double click a favourite and it's added to the SQL tab, it is very easy making changes in the tab and accidentally save over the original statement saved as a favourite.

Could it be that you can only edit a favourite in the popup that opens from on right click > Edit/Rename?

**Comment by huyphams** [comment]
Hi @jacquipickup there is an option in the preferenses to turn off the autosave.
<img width="612" alt="autosave" src="https://user-images.githubusercontent.com/3654622/62628652-0ff07200-b902-11e9-8bcb-422a331d01c9.png">

**Comment by jacquipickup** [comment]
That's great, thanks for this and for the fast reply!
