### ISSUE TITLE
[Feature Request] Support pinning result tabs.

### ISSUE THREAD

**Issue by sheriferson** [TablePlus/TablePlus#1353]
This feature comes from SQLWorkbenchJ and I find it very useful:

**Current behavior**: If the current tab has two queries:

```sql
select *
from myschema.mytable
limit 100;

select *
from myschema.myothertable
limit 100;
```

And I run only the first query, when I run the second query, the results of the second query will replace the results of the first one. I only get result tabs for both queries if I run both queries at the same time.

**Desired behavior**:

Have a setting which, when switched on, would open a new results tab for the second query after running the first one, independently. Basically, have the results from previous queries persist in tabs.

For the sake of completeness, in SQLWorkbenchJ, this is the toolbar button for the setting:

![Screen Shot 2019-08-07 at 12 45 52 PM](https://user-images.githubusercontent.com/3160968/62652979-73ce6700-b911-11e9-8a1c-34903e99cdb0.png)

**Comment by huyphams** [comment]
Hi @sheriferson have you tried to press command + D? TablePlus does support split-screen and I think it's much easier for comparing results.
Btw, I will think about the pin result button but it may increase the complexity of TablePlys.

<img width="1392" alt="Screen Shot 2019-08-07 at 4 52 11 PM" src="https://user-images.githubusercontent.com/3654622/62653324-b86afa00-b933-11e9-86a5-0e833a014a32.png">

**Comment by sheriferson** [comment]
I have tried it, but unfortunately that only works for one, maybe two additional queries, after which each query's window becomes too narrow to be usable. With each additional split, the results from the previous queries become harder to inspect since they're also appearing in a narrower frame and will require a lot more horizontal scrolling.

Thanks a lot for considering it. I understand if it makes things too complex to be worth it, but I'll be hoping you could find a way : )

**Comment by huyphams** [comment]
Thanks for your insight, I will find a way to add that feature into TablePlus without increasing the UI/UX confusion.

**Comment by R0dri** [comment]
Yes please, I'm having the same issue. It would be perfect if you could display many results like on MSSQL Sever client. It really increases productivity.

**Comment by sheriferson** [comment]
I wanted to check in to see if there is any hope of this being implemented any time soon. I still miss this feature deeply every time I use TablePlus.

**Comment by huyphams** [comment]
I just implemented this feature, please wait for the next update!
<img width="1617" alt="pin" src="https://user-images.githubusercontent.com/3654622/90312658-5e324b00-df30-11ea-9849-d30127ff98ea.png">
