### ISSUE TITLE
MySQL query timeout

### ISSUE THREAD

**Issue by ekirkland** [TablePlus/TablePlus#1356]
When executing a long running query, the client is always timing out after 15 minutes.  Occasionally I need to run some longer running queries.

I have set the query timeout in the settings to be 3600 seconds.  However, the queries always timeout exactly on 900 seconds (15 minutes). 

I'm using MySQL, and if I use a different client I can run these same queries that take longer than 15 mins to run without issue.

**Comment by huyphams** [comment]
it seems the timeout was set in the server, and the other client ran a command to override it (if the user doesn't have the permission it will end up disconnected).
I will investigate it and see if we can safely override the timeout.

**Comment by ekirkland** [comment]
Thanks, that would be helpful.

**Comment by timfennis** [comment]
Just as a small note, I've had similar issues caused by VPNs and firewalls. It could help to ensure that TCP keepalive is enabled by both the client and the server. (Not sure how it works exactly in MySQL)

**Comment by huyphams** [comment]
We've fixed the issue recently, turned out it was the SSH time out. Please let me know if you're still seeing it.
