### ISSUE TITLE
Add a feature to show the previous view on launch

### ISSUE THREAD

**Issue by daveverwer** [TablePlus/TablePlus#1357]
My main workflow with TablePlus is writing and executing random SQL queries against either a local, or production database. I love that the two database connections are persisted in the sidebar on launch, and that I can switch between them with keyboard shortcuts. I love that my each tab's query document is persisted between sessions automatically. I love that everything connects when I launch.

There is a point of friction though... Every time I launch the app, the main area of the app is blank. I almost *always* want to click the SQL Query button to open up my previous query document. I know there's a keyboard shortcut ⌘↵, which does save some time, but ideally I'd just like whatever I was doing previously to remain open. In my case, always the SQL query editor.

If there's an option to do this, I've missed it, but I'd love to learn about it.

Thanks for your consideration!

**Comment by huyphams** [comment]
Thanks for your insight, @daveverwer I will support restore the SQL Query.

**Comment by huyphams** [comment]
If you have a chance, please download this hotpatch, it supports restore SQL Query/file now.
https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks

**Comment by daveverwer** [comment]
Thank you! 🎁
