### ISSUE TITLE
Multiple Databases Blank

### ISSUE THREAD

**Issue by entrinix** [TablePlus/TablePlus#1359]
Opening multiple databases produces the second database as blank.

Open a database (in this case, 1 Mongo, 1 MySQL).  The second database is blank.

![Screen Shot 2019-08-09 at 14 20 04](https://user-images.githubusercontent.com/6059108/62781871-d14cea00-bab0-11e9-96b7-b28c38694eb5.png)

**Comment by huyphams** [comment]
it's blank because you didn't select a database (please see the place holder).

**Comment by entrinix** [comment]
Shouldn't it then at least show the name of the server it's connected to?  If you open 2 connections without selecting a database, both are blank, and it makes it hard to know which one is which without choosing a database for each.

I would suggest showing the server name, with cmd + K (or Choose Database...) underneath in small print to let you know nothing has been selected.  Something to let you know you must make another action.  Right now, it seems like a bug.

**Comment by huyphams** [comment]
Thanks for the suggestion. It will if you turn it on, here is how to do it.

<img width="227" alt="Screen Shot 2019-08-09 at 10 26 11 AM" src="https://user-images.githubusercontent.com/3654622/62782212-23c9de80-ba90-11e9-8810-8204e416b0a2.png">

**Comment by entrinix** [comment]
Ah, I see it now.  Yes, this helps.  Thank you.

Perhaps this should be the default to avoid confusion.  I'm a new user who is used to Querious, so some of these issues are from inexperience.  Having said that, it would be much more helpful for new users to see this and advanced users to take it off than the other way around.

Since TablePlus is so new, I'd venture to guess you have a lot more new users than advanced ones.
