### ISSUE TITLE
Table structure issues

### ISSUE THREAD

**Issue by vasilis-exo** [TablePlus/TablePlus#136]
How I can find the auto-increment value and change it?
How I can change field collation and encoding?
Why varchar option not exists in the data_type dropdown?
Where I can find the table information (eg. engine, creation date etc)?

I think that the ui is great but you have to implement some important functionalities in order to become a complete database tool. 👍

**Comment by huyphams** [comment]
Hi @vasilis-exo 

based the feedback, I think you are using MySQL driver. TablePlus is a young project. I started this project 4 months ago and support only PostgreSQL. MySQl and other dirvers were added later. Yup, there are a lot of things todo, and we ship update every weeks to fix all the issues. Thanks for your feedback 👍 😸  

- Huy.

**Comment by huyphams** [comment]
Most of the features on this thread has been implemented in build 118. I will close this issue and create the new one for `Field collation and encoding`: https://github.com/TablePlus/TablePlus/issues/584

Thanks for the feedback.
