### ISSUE TITLE
Colors!

### ISSUE THREAD

**Issue by oojacoboo** [TablePlus/TablePlus#1362]
Overall TablePlus is pretty good.  The UI is okay, still trying to get used to some of the button locations, which I find to be odd, but maybe over time that'll fade.

However, one thing that I've noticed with regards to the UI is... it all blends together.  There is little contrast and colorized separation between actions, and attributes, etc.

This is such a simple UI feature request, but one that could make the overall UX and usability of the app much much better.

Firstly, I'd like to state that I'm not talking about turning the thing into a colorful disaster.  I'm talking about low saturation colors added in key areas that would allow the eye to develop more familiarity and more quickly move around the UI.  Here are a few suggestions:

- Arrows for FK values (Go to reference arrows).  These are not part of the data.  They're not even on the same level as a NULL value really.  I'd recommend making these a lighter grey, possibly with a circle around them or rounded square to draw a little more attention.  They shouldn't be distracting from the data you're trying to read.
- Meh, just going to go with overall suggestions here, but please adding some padding to the column width, not much, but just a little so the data isn't slammed next to the previous and next column.  Your eye can discern the data better.
- Instead of a light grey background for each alternating row, try a light light blue or something, maybe even a light yellow/brown.
- Table column headers: add more line-height, maybe increased font-size.  You could also give these a color, possibly instead of making them so bold.
- Selected tab: shade of blue, denoting "selected".
- Selected buttons ("Items", "Data", etc.): color it blue as selected.

That's a few suggestions.  Most time and thought should be put into this, the selected state colors, hover states and selectable states.  This might seem like such a silly thing to be concerned with, but the UX boost will be much greater than you'd probably realize.

**Comment by huyphams** [comment]
> Arrows for FK values (Go to reference arrows). These are not part of the data. They're not even on the same level as a NULL value really. I'd recommend making these a lighter grey, possibly with a circle around them or rounded square to draw a little more attention. They shouldn't be distracting from the data you're trying to read.

Agreed and I've changed the color for arrow and brackets.
<img width="64" alt="Screen Shot 2019-08-11 at 11 41 41 PM" src="https://user-images.githubusercontent.com/3654622/62843620-95bd4600-bc91-11e9-9c11-180b9397489d.png">

**Comment by huyphams** [comment]
Most of them are implemented (include line-height in the next update!) thanks!
