### ISSUE TITLE
Delimiters not supported

### ISSUE THREAD

**Issue by gzzo** [TablePlus/TablePlus#1363]
Similar to the last comment in #414, I'm trying to create a trigger so I need to set the delimiter. Sequel Pro had no issues with this, I'm only using TablePlus for MySQL 8 support.

**Comment by huyphams** [comment]
If you're using the latest build 252 it should work @gzzo. You didn't answer the template issue so I don't know which build you have and how to reproduce the issue.

<img width="1421" alt="Screen Shot 2019-08-16 at 10 57 27 AM" src="https://user-images.githubusercontent.com/3654622/63172702-afa1b480-c014-11e9-856f-0e9148c4658a.png">

**Comment by gzzo** [comment]
Thanks. I was on build 250. Confirmed it's working on 252.

**Comment by mdpotts22** [comment]
I'm seeing this is not working for me for on build 264 for MariaDB (also tested MySQL 8.x).

Did something change with this?  This was a primary reason for me using TablePlus
