### ISSUE TITLE
MS SQL - Offset not working

### ISSUE THREAD

**Issue by spekkie2002** [TablePlus/TablePlus#1365]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server DBVERSION_70

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
252 on Mac OS 10.14.6

3. The steps to reproduce this issue:
1) Open a table with let's say 5000 records, set limiter to 100, offset 0 (or empty).
2) Try to switch page by using the arrow button, or changing the offset value in the popup
3) Nothing happens :(

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @spekkie2002 please answer the question 1. the `DBVERSION_70` is not the driver version, it's a protocol.
The old Microsoft SQL Server doesn't support offset so there is no way to support it in TablePlus.

**Comment by spekkie2002** [comment]
Hi @huyphams, i wasn't aware of that, thanks for letting me know!
