### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by connie99d** [TablePlus/TablePlus#1366]
Just a quick typo report -- I'm assuming this should say "Can't connect to *server" :)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 252

3. The steps to reproduce this issue: 1) try to connect to something, 2) be unsuccessful

![image](https://user-images.githubusercontent.com/44302936/62969528-4aef1b80-bdc2-11e9-90ff-9fb76e68efa3.png)

**Comment by huyphams** [comment]
It's fixed, thank you!
