### ISSUE TITLE
iPad app?

### ISSUE THREAD

**Issue by natebrunette** [TablePlus/TablePlus#1367]
Any plans to port this to Catalyst and make it available on iPads as well?

**Comment by huyphams** [comment]
@natebrunette hey, what is Catalyst? Btw, TablePlus is already on iPad appstore

**Comment by natebrunette** [comment]
Oh! Is that recent? I feel like when I checked before it wasn’t there. Catalyst is just apple’s new thing that lets you build an iPad and macOS app using swift UI.

**Comment by huyphams** [comment]
We pushed the app 4 weeks ago and 14 updates have been released since then.

**Comment by natebrunette** [comment]
Ah, excellent. Is there an option for a lifetime license like the desktop version?

**Comment by huyphams** [comment]
We will maintain the app forever instead of releasing a new version (TablePlus 2, TablePlus 3) every year, so there is no life-time license at the moment.

**Comment by MarkOSullivan94** [comment]
Any plans for an iPad app to be released?

**Comment by huyphams** [comment]
It's released 2 years ago @MarkOSullivan94

**Comment by MarkOSullivan94** [comment]
Thank you @huyphams!
