### ISSUE TITLE
Editing connections broken

### ISSUE THREAD

**Issue by mpash** [TablePlus/TablePlus#1369]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
No driver (main menu bug)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 252 (SetApp)

3. The steps to reproduce this issue:
- Add connection in a named group.
- Edit connection
- Hit save
- Window does *not* close
- Edits are unpersisted until program is fully closed then reopened

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @mpash, could you make a gif with gifox.io I can't reproduce the issue.

**Comment by mpash** [comment]
@huyphams I wasn't able to reproduce it myself as soon as I reported it. I think it happened because I had a certificate in a connection that I duplicated (a folder which I removed after the fact) and the moment I removed the cert and changed the database field it saved as normal.
