### ISSUE TITLE
Content on additional Query tabs are not persisted between sessions

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#137]
Closing and reopening a database session maintains the queries present in the primary query tab, but contents on second tab aren't persisted, and the new tab opens with an empty query console.

**Comment by huyphams** [comment]
This is an expectation behaviours, but it is not fit with yours. I'm thinking about this and keep this issue open, comeback later. Thanks.

**Comment by bhrd** [comment]
The app only persists contents from the last open tab, and I just lost a whole bunch of queries on my primary query console, just because I navigated to the second tab before closing the app. This seems more like a bug to me, now :/

**Comment by huyphams** [comment]
Hi @bhrd thanks, it shouldn't be done that way. I will improve this UX a little bit in next update.

**Comment by huyphams** [comment]
Now TablePlus saves the latest query of all query tab.
