### ISSUE TITLE
Cant import a sql file since subscription ran out

### ISSUE THREAD

**Issue by asadakbar** [TablePlus/TablePlus#1370]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 242

3. The steps to reproduce this issue:
Its been a year since I purchased TablePlus and it seems my update subscription is over, which I'm fine with. But since then I have also not been able to import any sql files. I go through the same import process as before, "File -> Import -> From SQL Dump", get a green success notification, but no new table shows up. I am still able to import csv files though.

I have had to copy paste the sql into a sql editor tab and run the query that way, but the import sql functionality has stopped working. I have tried importing multiple sql files and they all fail.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @asadakbar I pretty sure it's related to this issue, which was fixed on the build 250 and above, could you please try the trial build to confirm it?
<img width="589" alt="Screen Shot 2019-08-14 at 5 16 27 PM" src="https://user-images.githubusercontent.com/3654622/63053085-49ebe600-beb7-11e9-9ace-48b0dff81740.png">

**Comment by asadakbar** [comment]
Ok, how do I download the trial build?

**Comment by huyphams** [comment]
Just go to our homepage and download it: https://tableplus.io You have to reactive the app 242 because the trial build will wipe out your license.

**Comment by asadakbar** [comment]
Not sure I understand the process.

1) Download the trial build on the homepage
2) Test to see if the bug is fixed.
3) If its fixed, do I go back to the old version with my license and the bug unfixed? Where would I be able to download the old version?

**Comment by huyphams** [comment]
the build 233 will not be affected by that bug: https://s3.amazonaws.com/tableplus-osx-builds/233/TablePlus.dmg because it uses the old import handler, you can also try it here.

**Comment by asadakbar** [comment]
But then I won't get access to the latest version available for my subscription if I stay on 233.

**Comment by asadakbar** [comment]
@huyphams Is there an update regarding this? Its marked as fixed but there is no solution. If you want me to go back to version 233 then I won't have the version that my subscription has paid for.

**Comment by huyphams** [comment]
Hi @asadakbar please reach out our support nick@tableplus.com and he will help you to sort out the issue. I will close this issue for now because it was fixed on the newest release.
