### ISSUE TITLE
Be able to easily filter a column via right click

### ISSUE THREAD

**Issue by jpike88** [TablePlus/TablePlus#1371]
Would be good if I could:

- Be able to right click a column, and then click a 'Filter on this column' button, that adds it to the filters up the top.

Right now I have to click the 'Raw SQL' dropdown and choose the column, it can be a little painful to do all the time.

Great product guys!

**Comment by huyphams** [comment]
TablePlus already support quick filter when right-clicking:

<img width="466" alt="Screen Shot 2019-08-15 at 9 07 29 AM" src="https://user-images.githubusercontent.com/3654622/63093556-20c16900-bf3c-11e9-832f-e67fd4808a84.png">

But I think you want to ask for the feature that just fills the column and empty value then you can fill the value and apply it yourself?

**Comment by johnbwoodruff** [comment]
I know for myself, I'd love to be able to right click on a column header and select "Filter Column" which would automatically open the filter bar and pre-fill the column to the one I selected. Use case is I have an ID from support I need to look up. Currently have to go to a table, open filters, change column to the one I want, paste the id in the field, and then apply. I'd be much quicker to right click on the column I want, it automatically opens that column so I can just paste my id and go.

Absolutely stellar app btw. Bravo. 🎉

**Comment by huyphams** [comment]
I added it.
<img width="386" alt="Screen Shot 2019-09-05 at 10 20 30 PM" src="https://user-images.githubusercontent.com/3654622/64394205-64832c00-d02b-11e9-9ee9-221b0cf4b3d2.png">

**Comment by johnbwoodruff** [comment]
😱 Beast Mode!! Now I can't wait for the next release! 😄🎉

**Comment by jpike88** [comment]
yesssssss

**Comment by huyphams** [comment]
I also added some bonus features for the advanced filters.
- Default operator.
- Default column (especially primary key).

<img width="942" alt="default" src="https://user-images.githubusercontent.com/3654622/64399348-81752a80-d03e-11e9-9f5f-20bbafd1131f.png">
