### ISSUE TITLE
Cant disable "automatic rows count" feature

### ISSUE THREAD

**Issue by up73k** [TablePlus/TablePlus#1372]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
254

3. The steps to reproduce this issue:
Cant disable "automatic rows count" feature.
When I set option "Estimate count" to 0 or -1 it turns back to default value 500k.

Rows count is very bad for my very big partitioned table.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thank you @up73k I've updated the build. TablePlus now will not count if the estimate is zero but there are rows.

Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please let me know if you're still seeing it.
