### ISSUE TITLE
Refresh only active table?

### ISSUE THREAD

**Issue by Fossil01** [TablePlus/TablePlus#1373]
When doing CMD + R it refreshes all the tabs I have open. Is it possible to refresh only the tab I am currently viewing?

**Comment by huyphams** [comment]
@Fossil01 please right click on the content table, there will be a `refresh` menu which only reloads the current table. Unfortunately, there is no shortcut key at the moment.
<img width="600" alt="Screen Shot 2019-08-17 at 9 44 29 AM" src="https://user-images.githubusercontent.com/3654622/63211879-9f9cda00-c0d3-11e9-9746-75c1579e54db.png">

**Comment by Fossil01** [comment]
Maybe put this one down as a feature request instead of closing it?

**Comment by huyphams** [comment]
I thought you got trouble to find the menu because it was there. We have nearly 450 issues so I have to close it as many as I can to stay focus. btw, we already put the refreshing current table shortcut key into the roadmap.

**Comment by Fossil01** [comment]
Awesome, thanks.
