### ISSUE TITLE
Build 255 update doesn't update

### ISSUE THREAD

**Issue by sjamesmccarthy** [TablePlus/TablePlus#1374]
The update for build 255 always prompts, always downloads and always installs and then relaunches and says there is a new update of the same build. 

Also tried downloading latest version from site (build 252) and update from that version and have same issue. Never updates to 255 even after downloading, installing through updater in app.

Current versions:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/29286818/63227470-da6a4500-c19b-11e9-9fc2-551b4914b07e.png">

**Comment by huyphams** [comment]
Hey @sjamesmccarthy I'm sorry, I uploaded the wrong build...
I just uploaded the correct one. Thank you for letting me know.

**Comment by sjamesmccarthy** [comment]
Yay! Everything is updated now :) Thank you for your fast response.
