### ISSUE TITLE
Layout error on merge all windows

### ISSUE THREAD

**Issue by xavi-dev** [TablePlus/TablePlus#1376]
In 2.8.2 version (I've not checked any old one) there is a layout error when merging all windows, not taking into coonsideration the "extra" tab bar.

![image](https://user-images.githubusercontent.com/3817677/63250428-e7566980-c26b-11e9-9871-13c111e46231.png)

![image](https://user-images.githubusercontent.com/3817677/63250473-07862880-c26c-11e9-96a9-4165e06f58f2.png)

**Comment by huyphams** [comment]
I've fixed it @xavi-dev https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please let me know if you're still seeing it.

**Comment by xavi-dev** [comment]
That was fast! Thank you so much :)
