### ISSUE TITLE
The Commit command also saves changes to favourite queries

### ISSUE THREAD

**Issue by aramando** [TablePlus/TablePlus#1377]
The Commit command will also save any changes to any favourite queries that are currently open.

This is less of an issue for me now that you can change the default action for double-clicking favourites (thank you for that!!) but is still likely to catch users out.

1. Which driver are you using and version of it: PostgreSQL 10.6
2. Which TablePlus build number are you using: 255
3. The steps to reproduce this issue:
  1. Open a query window by double-clicking a favourite
  2. Modify the query and execute to get a result set 
  3. Change the value in a cell of the result set
  4. Press Cmd+S or click menu Edit -> Commit to commit the changes
  5. Close the tab with the query - notice it does not ask if you want to save
  6. Reopen the favourite and note that it has retained the modification

**Comment by huyphams** [comment]
TablePlus now will commit the changes, it only saves the favorite if there is no change.
