### ISSUE TITLE
Database list doesn't show names for Vitess

### ISSUE THREAD

**Issue by andybergon** [TablePlus/TablePlus#1378]
We use [Vitess](https://vitess.io/) as a clustering system for MySQL, all the TablePlus features work fine except this one.

When I try to open the DB list it shows items without names.

![image](https://user-images.githubusercontent.com/5220825/63284639-e6ddc300-c2ab-11e9-8763-139ce295620f.png)

What is the format of namespaces TablePlus expects to show them?

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 252

3. The steps to reproduce this issue:
Connect to a Vitess cluster.
Open the DB list.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Can you run this query and let me know the result @andybergon 
`show databases;`
Thank you!

**Comment by andybergon** [comment]
+--------------------+
| Database           |
+--------------------+
| FooPascalCase		 |
| bar_snake_case	 |
| baznocase          |
+--------------------+

**Comment by huyphams** [comment]
it seems the column contains an extra character (probably a space) so TablePlus has failed to parse it. Could you please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 and let me know the result?

**Comment by andybergon** [comment]
It works!!! 🎉

I'm impressed about the quick fix  😮

Thanks a lot, feel free to close now or after you release the build.
