### ISSUE TITLE
Open Anything - Include Favorites

### ISSUE THREAD

**Issue by qsrdallas** [TablePlus/TablePlus#1384]
While using the Open Anything command, it would be nice to have it include items from favorites. A separate command to just look for favorites would also work.

--

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 256

3. The steps to reproduce this issue: Hit command + P

**Comment by chadsaun** [comment]
I would prefer to keep it inside the "Open Anything" command. One command to rule them all.

**Comment by jschuur** [comment]
Based on the name Open Anything, I expected this would open my favorites. Another vote for a single command to, well... open anything.

It should also support filtering by favorites (prefixing the tag with @ maybe?). I was confused by what 'TablePlus will add the favorite into the auto suggestion list by using these keywords' when editing a favorite. I guess 'auto suggestion list' wasn't Open Anything?

**Comment by huyphams** [comment]
Thank you for suggestion. it will be supported in the next update or you can download the hotpatch here: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
