### ISSUE TITLE
How to view mysql table information in tableplus？

### ISSUE THREAD

**Issue by war1644** [TablePlus/TablePlus#1386]
Any help, thank you

**Comment by war1644** [comment]
![image](https://user-images.githubusercontent.com/16129819/64071662-59d63900-ccb1-11e9-835a-8c4185e6230f.png)

similar to this

**Comment by huyphams** [comment]
You can click here, let me know if you need any further information then I can add it into this.
<img width="1379" alt="section" src="https://user-images.githubusercontent.com/3654622/64071682-7fcdf000-cc55-11e9-96f1-52e4d87d053e.png">

**Comment by war1644** [comment]
Thanks, this solved my problem. There are no more needs for the time being.
