### ISSUE TITLE
Allow for more delimiters in "right click copy as" in query results

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#139]
I typically copy query results and paste into excel, and other SQL clients I use, support choice of delimiters while copying, and have an option to set default delimiter in preferences.
SequelPro for example, has tab-separated as default.
Even if you cannot make tab as the default delimiter, an option to configure this in preferences would be useful.
I do know that I can hit the export button to export the results with tab as a choice, but not always do I need an intermediate file before loading data directly to excel.

**Comment by huyphams** [comment]
hi @bhrd sorry for the delay because different time zone. Sure, we will have config `delimiter` on the future update.
Huy.

**Comment by huyphams** [comment]
Updating

<img width="508" alt="config" src="https://user-images.githubusercontent.com/3654622/35096699-bd8192b4-fc7f-11e7-8391-3388f685a5cb.png">
