### ISSUE TITLE
Feature Request: Grid Aggregates

### ISSUE THREAD

**Issue by jim256** [TablePlus/TablePlus#1394]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 256

3. The steps to reproduce this issue:
Feature Request

It would be awesome to have the feature to automatically have aggregates calculated when highlighting cells in the query results window. If, for example, I highlight two cells with the value 1 and 5, it would show COUNT: 2, COUNT DISTINCT: 2, SUM: 6, AVERAGE: 3, etc.

**Comment by jim256** [comment]
Great! Closing then.

**Comment by huyphams** [comment]
Hey @jim256 I'm about to upgrade Snowflake lib and implement some more feature for this driver, but unfortunately, I don't have Snowflake credential, may I ask you to test our app regularly?
If you want to test the app, please email me at nick@tableplus.com (we also would like to offer you a free license.)

**Comment by jim256** [comment]
Hey Huy,

That sounds great. I’d absolutely love to. Count me in.


Thank you,
Jared
801.499.9423

**Comment by jim256** [comment]
Adding a screenshot of what I think is a good implementation of this from DBeaver:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/15026225/64632098-b1615c80-d3b5-11e9-8d47-a21c3955b29f.png">


Also, for what it's worth, I haven't received any test builds. Happy to test!

**Comment by huyphams** [comment]
Yep, we already have it in our backlog.
