### ISSUE TITLE
Copy paste cell value to another row

### ISSUE THREAD

**Issue by sburkett** [TablePlus/TablePlus#1398]
Shortcut request:

One of the things that was incredibly convenient in HeidiSQL was the ability to go to a column value in a row, copy the value (CTRL-C), and then arrow around to other rows and quickly paste the value in other rows.

**Comment by huyphams** [comment]
Hi, sounds like you're using the Windows version. Here is the Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues
We've already supported it on macOS version and we're working to port it to the Windows next update!
I'm closing it because it does not an issue on macOS version.

**Comment by huyphams** [comment]
Actually, it's supported in Windows, but no shortcut, you have to right-click => copy and paste it manually, we will add the shortcut in the next release.

**Comment by huyphams** [comment]
it's released on the build 82 in Windows.
