### ISSUE TITLE
Request: Using NOW() in the Data explorer for manipulating data cells

### ISSUE THREAD

**Issue by janhkmn** [TablePlus/TablePlus#1403]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.2.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.82

3. The steps to reproduce this issue:
Go to Data -> insert NOW() into any date column. In Sequel this works and speeds up my workflow greatly. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
The date column is supported. Have you tried the click the braces? You can also hold option and left-lick the field the show the quick menu.

<img width="253" alt="date" src="https://user-images.githubusercontent.com/3654622/64067101-42d41000-cbf9-11e9-8d7d-fcee4c5ee8fc.png">

**Comment by janhkmn** [comment]
props for the speedy answer, thank you :)
No I haven't, this solves it. Tried typing out "NOW()".

**Comment by huyphams** [comment]
Thanks, I just updated the date handler now TablePlus also supports NOW() if you enter in the box.
it will be included in the next release.

**Comment by janhkmn** [comment]
Awesome :)
