### ISSUE TITLE
Typed emoji are lost on SQL Server

### ISSUE THREAD

**Issue by mernen** [TablePlus/TablePlus#1404]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Azure (RTM)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.8.2 (256) – Setapp version

3. The steps to reproduce this issue:
    1. Open a SQL Server/Azure table
    2. Edit text in an `nvarchar` field
    3. Type in some emoji (or, presumably, any character not representable in an SQL Server `varchar`
    4. Save your changes
    5. Emoji appears as "??" instead

---

Looking at the produced SQL, I see:

```sql
UPDATE [dbo].[example] SET [name] = 'Hello 😉' WHERE [id] = 1;
```

If I manually change it to an nvarchar literal (`N'Hello 😉'`), everything works fine. So it's not some driver issue, just adapting to SQL Server's idiosyncrasies related to character types.

**Comment by necmettin** [comment]
Don't know about SQL Server, but MySQL has utf8 (which can't store emojis because they are invalid in 'plain' utf8) and utf8_mb4 (which CAN store emojis because they are valid characters in this case).

Is it possible this is a similar/related situation?

**Comment by mernen** [comment]
Not quite… in SQL Server you do have to use the `nvarchar` type to store the full Unicode set, but even if you do, character literals still cannot represent them. You must use an nvarchar literal, `N'like this'`.

**Comment by huyphams** [comment]
Hi @mernen please choose this option, it should works on the latest update:
<img width="477" alt="Screen Shot 2020-09-13 at 3 25 57 PM" src="https://user-images.githubusercontent.com/3654622/93013731-751e9880-f5d5-11ea-99f6-e8e4ee18a3d6.png">

**Comment by mernen** [comment]
Yup, seems good. Thanks!
