### ISSUE TITLE
Feature request : Sqlite, be able to easily view the list of indexes (and their structure)

### ISSUE THREAD

**Issue by olivierFr** [TablePlus/TablePlus#1406]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Sqlite 3.27

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 256

3. The steps to reproduce this issue:
Be able to easily view the list of indexes (and their structure) in a table 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @olivierFr have you tried this one?
<img width="1379" alt="index" src="https://user-images.githubusercontent.com/3654622/64089591-174a4600-cd1d-11e9-84d4-f02a2921f1d0.png">

**Comment by olivierFr** [comment]
Oh, great! Thank you.
