### ISSUE TITLE
[Bug] Cannot read full value of field that contains binary

### ISSUE THREAD

**Issue by hieuk09** [TablePlus/TablePlus#1407]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Redis 5.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 256

3. The steps to reproduce this issue:

- Open redis in tableplus
- Run this command in console view:

```
set abc "\x04\b{\bI\"\x10_csrf_token\x06:\ux06EFI\"Eabc\x06;\x00FI\"\u0018authentication_data\x06;\x00F{\n:\x0Etenant_idI\"\x13PremiumRewards\x06;\x00T:\x0FconnectionI\"\x12google_oauth2\x06;\x00T:\nstateI\"\b123\06;\x00T:\nscopeI\"\x12email,profile\x06;\x00T:\x11redirect_uriI\"6http://localhost:2300\x06;\x00TI\"\x16authorize_referer\x06;\x00F\"\ehttp://localhost:2300/";
```

- In table view, I can't read/copy full value of `abc`.

**Comment by huyphams** [comment]
I think there is a null terminated character which currently is not supported by TablePlus. I will take a look at it.
