### ISSUE TITLE
[UI] Wrong column worked on after column reordering

### ISSUE THREAD

**Issue by hwid25** [TablePlus/TablePlus#1408]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.3.0) 6.3.0, 64-bit

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 84, Windows 10

3. The steps to reproduce this issue:

    - have an open table

    | Column 1 | Column 2 |
    |----------|----------|
    | 1 | 2 |

   - change column order by drag'n'drop

    | Column 2 | Column 1 |
    |----------|----------|
    | 2 | 1 |

    - update value of first column (column 2) from 2 to 4
        - mark, edit, enter

    - expected

    | Column 2 | Column 1 |
    |----------|----------|
    | 4 | 1 |

    - actual

    | Column 2 | Column 1 |
    |----------|----------|
    | 2 | 4 |

Note
    - after reloading the view (closing table & reopening) behaviour is correct
    - repro 100%
    - following sql change is correct for **actual** behaviour

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @hwid25 I fixed it. the new update will be released this week. Please report the Windows issue here: https://github.com/TablePlus/TablePlus-Windows/issues
Thank you!

**Comment by huyphams** [comment]
It's released in build 85!
