### ISSUE TITLE
Allow view/export schema

### ISSUE THREAD

**Issue by thovt93** [TablePlus/TablePlus#141]
Hi,
How can I view or export schema?
I can't find that feature on this application.

**Comment by huyphams** [comment]
Hi @kensupermen 
Thanks for your feedback, there is a similar issue: https://github.com/TablePlus/TablePlus/issues/93
Please check it out.

**Comment by huyphams** [comment]
Check out this issue: https://github.com/TablePlus/TablePlus/issues/418
