### ISSUE TITLE
Use SSH key in connection-URL

### ISSUE THREAD

**Issue by mbosman** [TablePlus/TablePlus#1415]
Is it possible to flag the SSH key should be used in the `myslq+ssh://` connection url?
Maybe some documentation about this vastly underrated feature could raise it's usability.

**Comment by huyphams** [comment]
Hi, yes there are:
- usePrivateKey=true => Eable SSH Key.

And you may want to enable the safe mode:

- safeModeLevel=2 => the safe mode level.
- advancedSafeModeLevel=1 => ingore select/explain queries.

We're working on the documents. it will be updated on our site soon.

**Comment by mbosman** [comment]
Thanks!

**Comment by huyphams** [comment]
Tip: just create a new connection and setup all the mode, then press command + C to copy the URL, you will see all the supported flags.

**Comment by mbosman** [comment]
🤯
