### ISSUE TITLE
Feature Request: .pgpass Support

### ISSUE THREAD

**Issue by mzagaja** [TablePlus/TablePlus#1416]
It would be great if `.pgpass` was supported or available to import.

See https://www.postgresql.org/docs/11/libpq-pgpass.html for more information.

**Comment by huyphams** [comment]
Really nice, We will support this feature.

**Comment by kannan-zeotap** [comment]
Hi,

Any updates on this feature?

GCP has introduced IAM integration with their CloudSQL instances. So users can login using their own auth token, which is dynamic. So having a PGPASS support would be quite useful in tableplus.

**Comment by huyphams** [comment]
TablePlus now supports getting the password via Command Line IAM.

![CleanShot 2022-09-23 at 15 09 27@2x](https://user-images.githubusercontent.com/3654622/191918020-20582fcf-2e9b-48a6-a17b-096d741f52c4.png)

if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're seeing any issue.
