### ISSUE TITLE
Return to default screen after clicking on TablePlus icon

### ISSUE THREAD

**Issue by lmquang** [TablePlus/TablePlus#142]
Hi, I have a problem when click on TablePlus icon which will redirect me to screen with message `No  database selected, press cmd + shift + D to select`.

Steps to Reproduce:
1. Open app
2. Choose host
3. cmd + shift + D to choose DB
4. Click on TablePlus icon (on Dock)

Environment:
TablePlus version 1.0 (77)

**Comment by huyphams** [comment]
It's a bug, TablePlus created a new workspace when you click on the Dock icon. (cmd + shift + \) you will see your workspace here.
Let me fix it.

**Comment by huyphams** [comment]
Hi @lmquang 

This is hotfix build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

Thanks for your feedback.

**Comment by lmquang** [comment]
Thanks, it's ok now
