### ISSUE TITLE
Updating Multiple Rows

### ISSUE THREAD

**Issue by volkanozyildirim** [TablePlus/TablePlus#1420]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
Mysql 5.7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
258

3. The steps to reproduce this issue:
Editing multiple rows update is great but there is a little bug after this improvement(https://github.com/TablePlus/TablePlus/issues/196). Only first row is updated. Here is video capture

https://gofile.io/?c=9iLpvb

**Comment by volkanozyildirim** [comment]
PS: I tried problem with multiple row editing, it behaves same and updates only first row

**Comment by huyphams** [comment]
Hey, @volkanozyildirim have you tried to run that 3 queries in the query editor? I think there is something wrong with the database.

**Comment by volkanozyildirim** [comment]
Editing multiple columns manually and saving was working before #196. There is no problem with queries or database, it works.

**Comment by huyphams** [comment]
Thank @volkanozyildirim for the confirmation, however, I couldn't reproduce the issue.
Could you please check if the history and see if there ware multiple update queries?
<img width="709" alt="Screen Shot 2019-09-10 at 8 28 04 AM" src="https://user-images.githubusercontent.com/3654622/64610197-1e202b00-d3a5-11e9-8eb8-8428239e9522.png">

**Comment by volkanozyildirim** [comment]
@huyphams I checked history, i see all queries that should be executed but rows are not updated. I'm using MariaDB 10.4.6 on my local and i realized its only happening on local.

**Comment by huyphams** [comment]
I think this bug is not related to TablePlus but the database server.
