### ISSUE TITLE
Support for Identity Column in Postgres

### ISSUE THREAD

**Issue by louis77** [TablePlus/TablePlus#1422]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PG 10+11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

258

We recently moved from Serial/Sequences to Identity Columns, which were introduced in PG 10. However in TablePlus there is no indication that a column is an Identity Column. Is it possible to support these column types (which are SQL standard) in TablePlus?

![Bildschirmfoto 2019-09-10 um 08 55 51](https://user-images.githubusercontent.com/1240462/64590888-dac7bb80-d3a8-11e9-96f2-0f3f8b049886.png)

**Comment by cettoana** [comment]
Any update on this issue?

**Comment by maxpain** [comment]
Any updates?

**Comment by s0xDk** [comment]
any updates?
