### ISSUE TITLE
All tables disappeared but request are working.

### ISSUE THREAD

**Issue by DMBPWR** [TablePlus/TablePlus#1424]
I'v been using TablePlus for 2 weeks and today I start editing some columns and I press `command + s` or `command + r` and all tables are disappeared. They are not displaying anymore. I'v made a request such as `SELECT * FROM my_table` and it works fine but its annoying because of disappeared tables.

Help, please!

**Comment by huyphams** [comment]
Could you show me a screenshot of the application workspace?

**Comment by DMBPOWER** [comment]
`Yes,` of course! :)

<img width="1112" alt="Screen Shot 2019-09-10 at 7 47 06 PM" src="https://user-images.githubusercontent.com/29796308/64633516-fc09c580-d403-11e9-9fb1-ba663a4702ca.png">

**Comment by huyphams** [comment]
Could you please run this query `SELECT table_name as table_name,table_schema as table_schema,table_type as table_type FROM information_schema.tables WHERE table_schema = 'brain-race';` and let me know if there are any result?

**Comment by DMBPOWER** [comment]
<img width="1112" alt="Screen Shot 2019-09-10 at 8 01 40 PM" src="https://user-images.githubusercontent.com/29796308/64634433-dd0c3300-d405-11e9-9a0e-6bc705282cf4.png">

**Comment by huyphams** [comment]
I'm not sure why it returned zero tables, how many databases do you have? Could you run this query and let me know the result
`
SELECT table_name as table_name,table_schema as table_schema,table_type as table_type FROM information_schema.tables WHERE table_schema <> 'information_schema' AND table_schema <> 'sys' AND table_schema <> 'performance_schema' AND table_schema <> 'mysql';
`
This query will list all the database in your MySQL. I would like to see what are the results.

**Comment by DMBPOWER** [comment]
<img width="1112" alt="Screen Shot 2019-09-11 at 12 11 06 AM" src="https://user-images.githubusercontent.com/29796308/64650802-b1e70b00-d428-11e9-87bc-ff1cf544e129.png">

**Comment by DMBPOWER** [comment]
I can `SELECT * FROM users` and get all values but I cant see tables in "tables". Weird.

**Comment by DMBPOWER** [comment]
Something like this
<img width="1090" alt="Screen Shot 2019-09-11 at 11 08 05 AM" src="https://user-images.githubusercontent.com/29796308/64679561-a6293200-d484-11e9-948e-1e2a3c6d3006.png">

**Comment by huyphams** [comment]
It must be something wrong with the database, are you using the root account? Have you configured the user manager and revoked some permissions?

**Comment by joshdavenport** [comment]
Seems unlikely it would shed much light but just in case it does, I see a similar sympton with a connection via an SSH tunnel where the IP for the MySQL host from within the server is the public IP (first screenshot)

![Screen Shot 2019-10-10 at 22 26 13](https://user-images.githubusercontent.com/757828/66608031-694c7a00-ebad-11e9-95e6-7505bb7889fa.jpg)

That connects but there are no tables and no results from `SHOW TABLES` etc 

That is obviously an invalid connection, debatably it shouldn't connect and that would be an entirely new bug, but anyway, fixing the connection by using 127.0.0.1 cleans everything up:

![Screen Shot 2019-10-10 at 22 26 21](https://user-images.githubusercontent.com/757828/66608030-694c7a00-ebad-11e9-881d-ae8e11af944b.jpg)

**Comment by huyphams** [comment]
I think you have two roles on the database and it's based on domain, the one with the public has no privilege to fetch the database content and the one with locahost/127.0.01

TablePlus can connect because it can read the server version 5.5.60 it the first image.

**Comment by joshdavenport** [comment]
That would totally make sense and it seems feasible that is what happened with @DMBPOWER too.

Looking at `SHOW GRANTS` output in the two contexts, they are different.

`GRANT RELOAD, SHUTDOWN, PROCESS, FILE, SHOW DATABASES, SUPER, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, EVENT, CREATE TABLESPACE ON *.* TO 'username'@'%' IDENTIFIED BY PASSWORD '___'`

for the first, and 

`GRANT RELOAD, SHUTDOWN, PROCESS, FILE, SHOW DATABASES, SUPER, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER, EVENT, CREATE TABLESPACE ON *.* TO 'username'@'localhost' IDENTIFIED BY PASSWORD '___'`
`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, TRIGGER ON ``databasename``.* TO 'username'@'localhost' WITH GRANT OPTION`

for the second.

Given the first had permissions to `SHOW DATABASES` but then no priveleges, I guess it would be possible to parse the privileges and feed back that we don't have permission to view tables?

Does seem like it wouldn't really be worth the effort of implementation though really, the user (me an hour ago) just needs to set up the connection properly.
