### ISSUE TITLE
[Enhancement] New tabs should have a SQL query editor by default

### ISSUE THREAD

**Issue by aramando** [TablePlus/TablePlus#1427]
I can't see any reason why a new tab shouldn't have a SQL editor created in it when it is opened; there doesn't seem to be anything you can do with a new tab until you have separately opened a SQL editor in it, either directly with Cmd+Enter or by inserting a favourite into a SQL editor. I start new queries a lot, so having to press 2 separate key combinations feels clunky and this would be a nice optimisation.

BTW I have recently discovered the Cmd+P "open anything" command and it has changed my life! Super-useful.

**Comment by opensourceame** [comment]
Totally agree, and the SQL editor should be **blank**.

**Comment by huyphams** [comment]
Blank query edit is another feature @opensourceame you can disable restore old query and the will be blank by default.
<img width="416" alt="Screen Shot 2020-12-09 at 10 06 24 PM" src="https://user-images.githubusercontent.com/3654622/101646980-c9b5a080-3a6a-11eb-8d55-44930cf9edca.png">

**Comment by opensourceame** [comment]
> Blank query edit is another feature @opensourceame you can disable restore old query and the will be blank by default.

Where is that option, I don't see it. I'm using 3.1.2

**Comment by huyphams** [comment]
TablePlus will open SQL Query with Command + T in the next update!
