### ISSUE TITLE
JSON Formatting

### ISSUE THREAD

**Issue by Chinese1904** [TablePlus/TablePlus#143]
Hi, 

I would love to see JSON formatted in JSON rows. It's rather complicated to navigate through the text if it isn't formatted. 

Thanks so much for this awesome tool!

**Comment by huyphams** [comment]
Hi @Chinese1904 
Thanks for the feedback, we already have this issue and have a plan to implement it.

**Comment by Chinese1904** [comment]
Looking forward to all the new versions! Thanks!
