### ISSUE TITLE
Snowflake critical driver upgrade

### ISSUE THREAD

**Issue by johnmastro** [TablePlus/TablePlus#1431]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Snowflake 3.41.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 256

3. The steps to reproduce this issue: [Snowflake has released a critical driver update](https://www.snowflake.com/blog/changes-to-how-snowflake-handles-ocsp/?mkt_tok=eyJpIjoiWlRZMVkyVmxOREE0TURJeSIsInQiOiI1R3d4dUVoams2QXJiYVB5SVREWGxmQzBOVTNjTXpnalZJbHJIUHhyZFRQOThVYnVvT1JUOHpjUzZHSFAzSnhycGVpSUNUb2h3UmJxcjFJeDlkYkloTXFkSnFcL2Q5dVNCRjI0MkhIOXpubVRsOWkyYytsNG41Z3hxSFNya2VVblIifQ%3D%3D) for their Python, JDBC, ODBC, Spark, and NodeJS drivers (not sure which you use)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @johnmastro I've updated the Snowflake lib to the latest release in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you run into any issues.

**Comment by huyphams** [comment]
Thanks, I'm investigating it now.

**Comment by huyphams** [comment]
It's fixed now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
And I also fixed some query issue. Thank you!

**Comment by johnmastro** [comment]
@huyphams thanks, I can confirm I'm able to connect now :)
