### ISSUE TITLE
x of y rows selected

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1432]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.72.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.8.2 (256)

3. The steps to reproduce this issue: Open table and mark a any number of lines.

Noted: If the bug is related to data, please attach an example SQL data.

TablePlus shows "n out of > 86 rows selected", when rows are highlighted (Screenshot1). When no row is highlighted "1-86 rows" is shown correctly (Screenshot2).

Correct would be "1 out of 86 rows selected".

Best,
Chris

![Screenshot1](https://user-images.githubusercontent.com/13820940/64905925-32369600-d6df-11e9-9311-cc7db1215f64.jpg)

![Screenshot2](https://user-images.githubusercontent.com/13820940/64905947-9b1e0e00-d6df-11e9-87a4-9425ab5314ff.jpg)

**Comment by huyphams** [comment]
I've fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!
