### ISSUE TITLE
Some of the databases are deleted automatically

### ISSUE THREAD

**Issue by keepschanging** [TablePlus/TablePlus#1434]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 226

3. The steps to reproduce this issue:
No defined steps available. My databases are completely deleted and this happens randomly. It runs well for a few weeks and suddenly one day can't access the database. I like the features of the software but it becomes really hard to use when you have to setup the db again and again.

<img width="1275" alt="Screenshot 2019-09-17 at 10 59 15 AM" src="https://user-images.githubusercontent.com/9402946/65013827-43c7aa00-d93a-11e9-8e11-62dd4baea66e.png">
<img width="1280" alt="Screenshot 2019-09-17 at 10 59 24 AM" src="https://user-images.githubusercontent.com/9402946/65013828-43c7aa00-d93a-11e9-8045-f4e64ad25903.png">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey, @keepschanging please double check your website/service or your machine. TablePlus `will not delete` your database randomly.

**Comment by huyphams** [comment]
I'm closing it because I think it's not related to TablePlus, Please let me know if you need any assistance. Thanks!
