### ISSUE TITLE
Feature Request: Add Spatial and Geometry viewer

### ISSUE THREAD

**Issue by jaumesala** [TablePlus/TablePlus#1436]
## Introduction
Nowadays it is quite common to deal with spatial data in a project. To give some basic examples:
- Images with location metadata.
- GPS tracking or path history of a device.
- GeoJson data geometries.

## Definition
It would be great if TablePlus could have at least a viewer for database fields such as: 
- Point
- Linestring
- Polygon
- GeometryCollection
- MultiPoint
- MultiLineString
- MultiPolygon

Of course, it would be great to be able to edit the data using TablePlus, for instance, draging a point of a geometry to change its shape.

## Examples
Some other database tools have embeded tools to view or even edit this type of fields. Here are some of them:

**MySQL Workbenck**
![Spatial Viewer](https://user-images.githubusercontent.com/385551/65123741-340c9c00-d9f4-11e9-921e-6b397f95507d.png)
![Geometry Viewer](https://user-images.githubusercontent.com/385551/65123755-3d960400-d9f4-11e9-90c6-7515fe7a091c.png)
![Geometry Viewer/Editor](https://user-images.githubusercontent.com/385551/65123761-41298b00-d9f4-11e9-9d7f-4abdac11a675.png)
[More info.](https://mysqlworkbench.org/2014/09/mysql-workbench-6-2-spatial-data/)

**pgAdmin**
![Geometry Viewer/Editor](https://user-images.githubusercontent.com/385551/65123691-16d7cd80-d9f4-11e9-89d9-95381faee573.png)
[More info.](https://www.bostongis.com/blog/index.php?/archives/272-pgAdmin4-now-offers-PostGIS-geometry-viewer.html)

**Sequel Pro**
![Geometry Viewer](https://user-images.githubusercontent.com/385551/65123717-235c2600-d9f4-11e9-9a1f-7847c42a3cf0.jpg)
[More info.](http://www.sequelpro.com/appcast/release_0.9.9.html)

**Comment by oliver-was-here** [comment]
@huyphams have there been any discussions regarding the addition of this feature?

**Comment by huyphams** [comment]
Hi @oliver-was-here we've put it on our road map already.

**Comment by huyphams** [comment]
Hi, please download this patch: https://www.dropbox.com/s/lgh81iqa7x6i3hu/TablePlus.dmg?dl=0 and you will be able to preview the geometry data along with image blob/bytea in other database drivers (PostgreSQL, MySQL).

Here is an example `GEOMETRYCOLLECTION`
<img width="1028" alt="Screen Shot 2020-01-17 at 9 51 26 AM" src="https://user-images.githubusercontent.com/3654622/72617981-87461b00-3910-11ea-85de-c224945eb554.png">

**Comment by oliver-was-here** [comment]
@huyphams hm, no dice 

 is this Version 3.0.0 (286)? 

i assume from your screenshot that you have the "Items" tab opened in the left-hand panel and the displayed items are different geometry rows for a table. let me know if i'm mistaken.

my entries appear to be encoded differently than your own. it's unclear to me how to visualize the stored data. inspecting a given row in the right-hand pane shows an `unsupported` type. x

![Screen Shot 2020-01-21 at 11 25 23 AM](https://user-images.githubusercontent.com/10605247/72822990-00ab7980-3c41-11ea-8cf8-4aba840ca8d5.png)

this same data is viewable in PGAdmin. 

![Screen Shot 2020-01-21 at 11 29 18 AM](https://user-images.githubusercontent.com/10605247/72823314-829ba280-3c41-11ea-8e70-038d2dcae631.png)

**Comment by huyphams** [comment]
Hi, the newest release is 290 now and it supports geometry, however I forgot to add the geography in that build, you can use this patch https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 
It supports both Geometry and geography data type. If you use a different data type, please let me know @oliver-was-here

**Comment by oliver-was-here** [comment]
@huyphams hm, it looks like the data is now being correctly parsed (no longer showing the `unsupported` message for the geometry data type). however, it's unclear to me what in the GUI i press in order to preview the data. am i missing something?

**Comment by huyphams** [comment]
You can view by hovering the mouse on it and wait for a while, however, it just an experiment test. We're working to add it to Quicklook along with some features (ex: with background map).

**Comment by oliver-was-here** [comment]
fantastic! thanks so much

and glad to hear about the background map - that would be immensely valuable for Geospatial work

**Comment by cesarmtz93-wit** [comment]
Does it work for sql server? because i can't get it to show me the Spatial result

![Screen Shot 2020-05-13 at 13 16 25](https://user-images.githubusercontent.com/57166683/81849308-f8db5200-951b-11ea-92c5-e8edb5535783.png)

**Comment by jaumesala** [comment]
Right click > Quick Look Editor > Show Map

**Comment by cesarmtz93-wit** [comment]
Yeah nothing happens

![Screen Shot 2020-05-13 at 13 37 13](https://user-images.githubusercontent.com/57166683/81851374-f3333b80-951e-11ea-8da9-d8fa18d24a28.png)
![Screen Shot 2020-05-13 at 13 37 03](https://user-images.githubusercontent.com/57166683/81851371-f2020e80-951e-11ea-82c4-429ceebb29e1.png)

**Comment by huyphams** [comment]
Hi @cesarmtz93-wit what was the data type of that field? is it text field or blob or binary? Could you click on the row and then show me the data type on the right sidebar?

**Comment by cesarmtz93-wit** [comment]
Hi @huyphams of course, here are the screenshots of the table definition as well as the query result 

![Screen Shot 2020-05-13 at 20 31 22](https://user-images.githubusercontent.com/57166683/81882743-17137300-9559-11ea-9dba-bb9bb8efca51.png)
![Screen Shot 2020-05-13 at 20 33 46](https://user-images.githubusercontent.com/57166683/81882745-1844a000-9559-11ea-8f98-5e65ae164f69.png)

**Comment by cesarmtz93-wit** [comment]
@huyphams any news?

**Comment by SebKp** [comment]
Maybe late to the party, if I have two columns `lat` and `lon` do I have a way to visualise these coordinates on a map, without having to encode them in a shapely Point?
Also how to do it for a subset of rows?

Thank you
