### ISSUE TITLE
Suggestion: CMD+S should save the current query when in query editor

### ISSUE THREAD

**Issue by bentaber** [TablePlus/TablePlus#1438]
When opening queries from .sql files, and editing and then hitting CMD+S within the query editor, changes are not persisted to the file on disk.  I realize this is due to the CMD+S keybinding being used to commit changes to the DB, but it goes against how all other text editors work.  Consistently having to Save As (CMD+SHIFT+S) and overwrite existing file is non-intuitive and prone to overwriting the wrong existing file.

Just a thought, thank you for such an awesome piece of software.

**Comment by huyphams** [comment]
Hey @bentaber did you turn off the auto-save feature? if you turn it off. The command + S will save the current query if there is no pending changes.

**Comment by bentaber** [comment]
Hi @huyphams - was not aware of this config option, thank you! This works perfectly for my use case.
