### ISSUE TITLE
Feature Request: Add ability to filter binary column with hex string

### ISSUE THREAD

**Issue by peritpatrio** [TablePlus/TablePlus#1439]
This is somewhat related to #710 but I think it’s best to open a separate issue for this.

---

It would be nice if I could filter the table with a hex string if the column is `VARBINARY(16)` so that this filter:

![image](https://user-images.githubusercontent.com/729565/65216675-6ed90780-daba-11e9-958b-108fc81091d8.png)

would run:

```sql
SELECT * FROM x WHERE uuid = 0x13F1EC8AAE303B9BDD050760CED65208;
```

**Comment by huyphams** [comment]
Interesting @peritpatrio thanks for the suggestion, currently you can work around 
 with the Raw SQL filter.
<img width="1010" alt="Screen Shot 2019-09-19 at 9 13 04 AM" src="https://user-images.githubusercontent.com/3654622/65242955-b4e39a80-dabd-11e9-8bdd-3bfba5a3086e.png">

**Comment by peritpatrio** [comment]
Thanks for the tip! This is quite convenient as well 👍

**Comment by bnussbau** [comment]
Sure you can work around with raw sql, but that removes the nice user experience where you can select the field directly from the dropdown. A feature like in sequel ace, where you can select "= (Hex String)" from the dropdown would be highly appreciated. I have to work with HEX comparisons everyday and it would improve my workflow so much. Will you think about it? 
![image](https://user-images.githubusercontent.com/8931007/105632927-17893b00-5e56-11eb-8d2b-c1177a1e34f9.png)

**Comment by huyphams** [comment]
Hi @bnussbau TablePlus does support it. It can detect the field was binary and auto-cast to binary. You can use two syntax below:

<img width="826" alt="Screen Shot 2021-01-24 at 9 22 48 PM" src="https://user-images.githubusercontent.com/3654622/105633323-7b2d5b80-5e8a-11eb-80d0-4181924b3fd7.png">

<img width="634" alt="Screen Shot 2021-01-24 at 9 22 35 PM" src="https://user-images.githubusercontent.com/3654622/105633330-7f597900-5e8a-11eb-9f08-2747c37e0f11.png">

**Comment by bnussbau** [comment]
wow thank you. I could swear I've tried it several times and it didn't work. But yes it sure does work! 🚀
