### ISSUE TITLE
Ability to sort results without modifying the query

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#144]
Often times using Postico I run a query and then click the title of one of the columns to quick sort it in-memory. I would love to have that option in TablePlus.

**Comment by huyphams** [comment]
You're right, it should be improved. I will do it in next release.

**Comment by huyphams** [comment]
Please check out new update 78.

**Comment by nathanpalmer** [comment]
Thank you @huyphams!
