### ISSUE TITLE
Latest build broke a working saved connection to PostgreSQL

### ISSUE THREAD

**Issue by moxplod** [TablePlus/TablePlus#1444]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL Azure Managed DB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows Build 88

3. The steps to reproduce this issue:
Try connecting an Azure managed postgres.

The latest update broke something - the saved connection stopped working. Where as I have not changed anything on that connection. The same connection works well with older builds of TablePlus.

![image](https://user-images.githubusercontent.com/4554395/65360145-a2e42380-dbb3-11e9-81a6-9ff05f2986c4.png)

**Comment by huyphams** [comment]
Hey @moxplod which version that works for you?

**Comment by moxplod** [comment]
I tried 72 and it still works there.
But as far as I remember 80 and 84 it also worked.

**Comment by huyphams** [comment]
I think the main difference is the build 86 and above use the installer, which requires admin (to install to the program files folder). Let me investigate further.

**Comment by moxplod** [comment]
Just installed build 89 and still the same issue persists.

**Comment by huyphams** [comment]
Could you try to enter the database IP instead of the hostname @moxplod? I want to confirm it was a DNS error.

**Comment by moxplod** [comment]
I just tried to use build 84 - that works as well.

**Comment by moxplod** [comment]
> Could you try to enter the database IP instead of the hostname @moxplod? I want to confirm if it was a DNS error.

Tried that with build 84 and 89. Works on 84 and fails on 89. Same error as my previous screenshot.

**Comment by huyphams** [comment]
Could you send me a screenshot of the connection form to email nick@tableplus.com Thank you!

**Comment by huyphams** [comment]
Sorted via email, if anyone ran into this bug, please download this hotpatch:
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
