### ISSUE TITLE
Export only produces the first 1000 rows.

### ISSUE THREAD

**Issue by djfrailey** [TablePlus/TablePlus#145]
**Operating System:** OS X 10.13.2
**Table Plus Version:** 1.0 (Build No. 76) - Free License

**Summary:**

When exporting a table that has more than 1,000 rows in it, regardless if it is a CSV, JSON, or SQL file the first 1000 rows is all it exports. This may be an unmentioned limitation of the Free Edition.

**Steps to reproduce:**

1. Generate a table with any number of columns and fill it with more than 1,000 rows.
2. Right click the table name and choose export.
3. Leave both "Select field to export" and "Export where" fields blank.
4. Choose any of the three file format options.
5. Click Export
6. Open the exported file in any editor
7. Observe that there are only 1,000 rows in the file.

**Expected Result:**

All rows in the database table would be exported.

**Comment by huyphams** [comment]
Hi @djfrailey 
The free version didn't limit the export function so it would be a bug. I just checked the lasted build (free version) and it still works. Which driver are you on (MySQL/PostgreSQL ...)?
Thanks

**Comment by djfrailey** [comment]
@huyphams I apologize, I thought I included that. I am on MySQL.

**Comment by huyphams** [comment]
Hi @djfrailey, I will investigate this bug, we will release the new version to fix this issue shortly.

**Comment by huyphams** [comment]
Hi @djfrailey 
Could you please confirm if this build work for you?
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Thanks

**Comment by djfrailey** [comment]
@huyphams 

This issue seems to be fixed. A little over 600K+ flushed to a CSV with no data loss in just under 10 minutes.

Thank you for your quick response time.
