### ISSUE TITLE
Only 1st table from selected is pinned

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1451]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

263

3. The steps to reproduce this issue:

1. select several (cherry pick or sequential) tables from `Recently` (maybe even from `Tables` section)
2. from context menu choose `Pin to top`

I'd expect all selected table to be pinned, but only 1st selected table is pinned.

**Comment by huyphams** [comment]
I've fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you @aik099
