### ISSUE TITLE
Unable to Install Plugins

### ISSUE THREAD

**Issue by tleish** [TablePlus/TablePlus#1452]
I am unable to install plugins from the TablePlus UI.  When I open "Manage Plugins" I see 3 plugins listed under "Available Plugins: (should I see more?).  When clicking on the down arrow next to any of the 3 plugins and select "Install", nothing happens.  If I click on "Website" I am taken to the plugin website.

I've restarted the application and restarted my machine, neither of which made any difference.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Not applicable

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.9.1 (264)

3. The steps to reproduce this issue:
Plugins > Manage Plugins > Install Plugin

**Comment by huyphams** [comment]
Hi, @tleish the plugin system currently is under development, there are 3 plugins at the moment, you can click Website to see what it is.
For example, plugin Dump Table will add a Copy Script As menu in the right-mouse-click menu context for left sidebar.
<img width="445" alt="Screen Shot 2019-09-26 at 11 49 24 AM" src="https://user-images.githubusercontent.com/3654622/65698950-b5e37180-e053-11e9-88b7-7b36f7cacb4b.png">

**Comment by tleish** [comment]
How do I install the plugins to begin with?  It's not working from the plugins manager.

**Comment by huyphams** [comment]
You can press command + L and click the dropdown, click install and **wait**, TablePlus will download and install it. After installing, you will see it in the Installed section:
<img width="820" alt="Screen Shot 2019-09-26 at 12 24 25 PM" src="https://user-images.githubusercontent.com/3654622/65701955-9864d680-e058-11e9-9cb9-40671660ec43.png">

**Comment by tleish** [comment]
The "Install" in the dropdown is not working for me. (Please read through my original comment.)

**Comment by huyphams** [comment]
I think it was blocked by the client (I can't reproduce it) but I will check it. You can also install it via the git repository.
Example: https://github.com/TablePlus/tabledump

**Comment by jerryklimcik** [comment]
Hi, I can confirm that this does **not working** in dropdown but also via the git repository:
<img width="1077" alt="Screen Shot 2019-12-10 at 12 36 13 PM" src="https://user-images.githubusercontent.com/23038104/70526499-03975280-1b4a-11ea-9fa0-f16a896bf571.png">
![Screen Shot 2019-12-10 at 12 36 29 PM](https://user-images.githubusercontent.com/23038104/70526510-0b56f700-1b4a-11ea-9dfc-d71281171956.png)
![Screen Shot 2019-12-10 at 12 36 40 PM](https://user-images.githubusercontent.com/23038104/70526518-0eea7e00-1b4a-11ea-8bc6-69a4899b29f3.png)
![Screen Shot 2019-12-10 at 12 37 05 PM](https://user-images.githubusercontent.com/23038104/70526524-114cd800-1b4a-11ea-90ad-7ee1e12e92aa.png)

**Comment by georgebohnisch** [comment]
Confirmed this issue as well. I've verified that the plugins exist in the Plugins directory within AppSupport, however, they are not being detected as activated in TP.

**Comment by huyphams** [comment]
I've resolved an issue where TablePlus couldn't read the plugins which were linked via symlink, please install this patch and see how it goes: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
Thanks all.
