### ISSUE TITLE
Oracle: data trimmed in some cells

### ISSUE THREAD

**Issue by pasku** [TablePlus/TablePlus#1454]
Hi,

I've been experiencing a problem with Oracle for a few versions now. It did not happen in 2.8.2 and it still happens in the latest release, 2.9.1.

The issue is that some cells come up trimmed. This is the case in the "conditions" column in the screenshots. I initially thought that it was just a UI bug but I have confirmed that it is not: when I copied the row or exported the SQL, it still was trimmed. Of course, the data shows up properly when I consume the database using other clients.

I'm not sure if these version numbers are enough to identify the Oracle version of TablePlus (I remember having to download a separate binary for Oracle support). Please let me know if there's any more info I can provide.

### **2.9.1**
![image](https://user-images.githubusercontent.com/449748/65701772-2acda000-e082-11e9-91f9-2f349472d045.png)
![image](https://user-images.githubusercontent.com/449748/65701780-2ef9bd80-e082-11e9-9676-89802f7c6be2.png)
----

### **2.8.2**
![image](https://user-images.githubusercontent.com/449748/65701824-43d65100-e082-11e9-9e92-b20e3b110833.png)
![image](https://user-images.githubusercontent.com/449748/65701836-4a64c880-e082-11e9-90a5-ac62fc147978.png)

**Comment by huyphams** [comment]
Thank you @pasku I will double-check and fix it.

**Comment by huyphams** [comment]
Hey @pasku could you please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 I've added a fallback for the ascii encoding, hope it works.

**Comment by pasku** [comment]
It is still not working. Thank you for your help.

![image](https://user-images.githubusercontent.com/449748/65872519-0410b180-e381-11e9-9994-4366f176a2ca.png)

**Comment by huyphams** [comment]
Thank you @pasku I think the bug is related to null-terminated character, which was trimmed due to utf8 decode.
I'm not sure why the build above didn't work. I've tried to fix the fallback function again in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 Could you please try it and let me know the result?

**Comment by pasku** [comment]
It seems to work fine. Thank you.
