### ISSUE TITLE
Feature request: show text type column content in popup

### ISSUE THREAD

**Issue by subdesign** [TablePlus/TablePlus#1457]
When I click on a _text_ type column containing long text, it would be nice to pop up a window to edit it easily, and not in a small "input field" like row. As HeidiSql does in the same situation.
Thanks

Example image: https://postimg.cc/BXd77KL8

**Comment by huyphams** [comment]
You can do it by right click > Quick Look or using middle mouse @subdesign You can also edit the text inside it.
<img width="866" alt="Screen Shot 2019-09-28 at 9 33 46 AM" src="https://user-images.githubusercontent.com/3654622/65816520-151bc000-e1d3-11e9-82ae-533a6ce58b7c.png">

**Comment by subdesign** [comment]
Thanks, I missed the point of Quick Look (thought view only), that's it what is want.

**Comment by suygarg** [comment]
> Thanks, I missed the point of Quick Look (thought view only, no save button in the popup..), that's it what is want.

You can edit directly in pop up and it will be saved. You can then commit the changes.
