### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by phaizt** [TablePlus/TablePlus#1459]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3.14
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
264
3. The steps to reproduce this issue:
Delete Table via keyboard shortcut (CMD+delete)

why i dont get this pop up options when i try to delete via keyboard shorcut??
please show this pop up options even i delete table from keyboard shortcut
https://prnt.sc/pct2qh

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @phaizt deleting via keyboard shortcut is most used feature, so we want to make it simple.
TablePlus has some hidden behavior:
Hold option + Delete => Truncate.
Hold shift + Delete => Delete cascade.

Now, I just added:
Hold Command + Delete => Ignore foreign key check.
It will available in the next update.

**Comment by phaizt** [comment]
Nice, Thank you.
