### ISSUE TITLE
Tables no longer listed

### ISSUE THREAD

**Issue by sebastiankruk** [TablePlus/TablePlus#1460]
We connect to the Redshift. For the last couple of weeks everything worked correctly until this morning.
Now we only see 4 tables listed out of dozens in one schema, and none listed in other schemas.

I used the most recent version (build 2.9.1 264) as well the recent beta update ( build 2.10 266) both have the same issue. The driver shows as PostgreSQL 8.2.0. We see the same issue on both Mac and Windows. 

Where can I check the queries that are executed or logs to see what has changed that stopped working?

**Comment by huyphams** [comment]
Hi @sebastiankruk thanks you for letting me know (I've received your email), I will check it now.

**Comment by sebastiankruk** [comment]
From what I see, there might be something wrong with our Redshift as there are only those 4 tables listed in the information_schema.tables. I guess you look at this to get the list of tables. Somehow other tools use different approach.

**Comment by huyphams** [comment]
Thanks @sebastiankruk for the insight, let me investigate it.

**Comment by huyphams** [comment]
This issue is sorted out via email, if anyone ran into this problem, please download the hot patch here:
macOS: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Windows: https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
