### ISSUE TITLE
Auto column-sizing too large on JSON fields

### ISSUE THREAD

**Issue by kayrunm** [TablePlus/TablePlus#1461]
Double-clicking a column header to resize is a really handy feature and I use it a fair bit, but today I've accidentally clicked on it on a JSON field which contains a fair chunk of data—resulting in the column width to the thousands of pixels wide. There doesn't seem to be an easy to resize this back to a useable width.

MySQL 5.7 (Presume this doesn't matter as it's UI..?)
Version 2.9.1 (Build 264)

Double-click a column header with a large amount of text (in this case, a JSON column with a large chunk of valid JSON)

**Comment by huyphams** [comment]
Hi, you could eliminate the cache by changing the font size.
1. Close all the tables.
2. Update the font size in the TablePlus preferences.

It also could be a great idea if TablePlus can reduce the size automatically if it was too wide.

**Comment by kayrunm** [comment]
Thank you! I got it sorted in the end just by taking a bit of time resizing it back down. I'll keep that in mind for if it happens again. 

Would be handy being able to double-click again and it reduces back to a normal size or something?

**Comment by huyphams** [comment]
@dvdnhm TablePlus has already supported it: right click > Quick Look Editor (or using middle mouse).

**Comment by dvdnhm** [comment]
Great, thank you.
I didn't notice it to be honest. Still a pencil icon would be cool for json
& text fields.

**Comment by huyphams** [comment]
We added a menu to reset the column positions and widths in the new release. so we can reset the column size without dragging it manually.
<img width="469" alt="Screen Shot 2020-02-10 at 10 36 44 AM" src="https://user-images.githubusercontent.com/3654622/74119251-41b7fd80-4bf1-11ea-870a-31b8a4aa11bb.png">
