### ISSUE TITLE
Oracle: upcoming password expiration warning being treated as hard error

### ISSUE THREAD

**Issue by pbreit** [TablePlus/TablePlus#1462]
When logging in to Oracle database, apparently the DB is returning a warning/error message that my password is due to expire within 7 days (in the future). TablePlus appears to be handling this as a hard error such that it cannot continue making the connection.

Error: ORA-28002: the password will expire within 7 days

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oracle

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.10 (266)

3. The steps to reproduce this issue: attempt to log in to Oracle with upcoming password expiration

![Screenshot 2019-10-02 11 55 12](https://user-images.githubusercontent.com/291985/66073347-bf655180-e50b-11e9-8e61-f23b1752d0da.png)

**Comment by huyphams** [comment]
Thanks @pbreit if you have a chance, please try this build and let me know the result: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by pbreit** [comment]
That appears to have fixed it, thank you.

(I say, "appears" because I am still stalling on the "Collecting database info". But when I test the connection I get the green fields.)

**Comment by huyphams** [comment]
Thanks, does it work now or still stuck at `Collecting database information...` @pbreit

**Comment by pbreit** [comment]
I'm pretty sure it is now connecting successfully (bypassing the password expiration notice) but then it is running into I believe this issue: https://github.com/TablePlus/TablePlus/issues/1319

**Comment by huyphams** [comment]
Thanks, I've made a build without collecting database information here: https://www.dropbox.com/s/6z06w7xenuwhymz/TablePlus.dmg?dl=0
basically, TablePlus will run these queries to collect some information it needs:
1. Get table list:
`SELECT table_name AS"table_name",OWNER AS"table_schema",'TABLE'AS"table_type"FROM all_tables WHERE(OWNER,table_name)NOT IN(SELECT OWNER,mview_name FROM all_mviews)`
2. Get view list:
`SELECT view_name AS"table_name",OWNER AS"table_schema",'VIEW'AS"table_type"FROM all_views`
3. Get materialized views:
`SELECT mview_name AS"table_name",OWNER AS"table_schema",'MATERIALIZED VIEW'AS"table_type"FROM all_mviews`
4. Get functions:
`SELECT OBJECT_ID as "oid",OWNER as "function_schema",OBJECT_NAME as "function_name" FROM ALL_OBJECTS where OBJECT_ID IN(SELECT OBJECT_ID FROM USER_PROCEDURES)`

Could you run the queries above and let me know the estimated time? it helps me investigate the issue.

**Comment by huyphams** [comment]
I'm closing this issue. We will follow the https://github.com/TablePlus/TablePlus/issues/1319 instead. please update the result on that thread. Thank you!
