### ISSUE TITLE
mysql - export aes_encrypted data in varbinary - corruption

### ISSUE THREAD

**Issue by joooow** [TablePlus/TablePlus#1466]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql 5.x
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 264
3. The steps to reproduce this issue: I use the mysql function AES_ENCRYPT on some columns in the database. If I export the DB, encrypted data can no longer be decrypted with the AES_DECRYPT function. I need to use Navicat to export my data correctly.

Noted: If the bug is related to data, please attach an example SQL data.
data are inserted with : 
insert into testdata (zip, info) values (75693,aes_encrypt('password','secretkey'));
to read the data : 
SELECT zip, AES_DECRYPT(info,'secretkey') FROM testdata;

when I decrypt encrypted data exported by Tableplus I have a null value.

[tableplus_testdata.txt](https://github.com/TablePlus/TablePlus/files/3690889/tableplus_testdata.txt)
[navicat_testdata.txt](https://github.com/TablePlus/TablePlus/files/3690890/navicat_testdata.txt)

**Comment by huyphams** [comment]
Thanks @joooow I'm fixing it, along with https://github.com/TablePlus/TablePlus/issues/918

**Comment by huyphams** [comment]
his build should fix the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it.
Thanks
