### ISSUE TITLE
Query Delimiter not working

### ISSUE THREAD

**Issue by mdpotts22** [TablePlus/TablePlus#1468]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 264

3. The steps to reproduce this issue:
I'm using DELIMITER // to start a sproc definition and ending with DELIMITER ; at the end of my sproc definition.  I believe this was working at some point (new user to TablePlus, but this was a feature I required) since Issue #1363 is describing the same issue I am having.

I get this error even just running `DELIMITER //`:

`Query 1 ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER //' at line 1`

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
the `DELIMITER //` is not a valid query.

The full valid query should be:
```
DELIMITER //
CREATE FUNCTION no_of_years(date1 date) RETURNS int DETERMINISTIC
BEGIN
 DECLARE date2 DATE;
  Select current_date()into date2;
  RETURN year(date2)-year(date1);
END 
//
```
MySQL Cli uses `DELIMITER //` because it's a console application, so in order to avoid to execute multiple lines query, it uses DELIMITER to begin a function. As soon as you enter the end of the delimiter `//` it will send the content of the function (without the delimiter) to the server.
The client Sequel Pro and TablePlus simply truncate the delimiter from the input.

From example, if you enter the function above, TablePlus and sequel pro will truncate the query and the actual query is:
```
CREATE FUNCTION no_of_years(date1 date) RETURNS int DETERMINISTIC
BEGIN
 DECLARE date2 DATE;
  Select current_date()into date2;
  RETURN year(date2)-year(date1);
END
```

**Comment by mdpotts22** [comment]
Thanks for the quick reply.  My actual example here is a sql file that has about 5k lines of sproc definitions.  The file runs fine on mysql workbench.  I'll try and get a better example of what the issue.

**Comment by mdpotts22** [comment]
Okay, I was a little quick in my thinking it was the delimiter because that was the error.  It actually appears that having a comment directly preceding the DELIMITER statement is the issue.  I get an error with the following:
```
-- Test 
DELIMITER //
CREATE FUNCTION no_of_years(date1 date) RETURNS int DETERMINISTIC
BEGIN
 DECLARE date2 DATE;
  Select current_date()into date2;
  RETURN year(date2)-year(date1);
END 
//
```
Even this throws an error if you select all and run:
```
-- TIMESTAMP
DELIMITER //
SELECT CURDATE()
//
```

Both of those will run in MySQL Workbench.

I can probably work around this, but there are many comments throughout the sproc definitions file (especially a pretty verbose comment at the start of every definition which is right where the delimiter statement starts.)

**Comment by huyphams** [comment]
Thanks, I can reproduce the issue and fix it in this build, if you have a chance, please try it:
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by mdpotts22** [comment]
It looks like it is working when using the delimiter now, however I'm seeing issues if I try to run 2 queries with no delimiter.  ie running these 2 selects in a run all is giving errors:
```
SELECT CURDATE();
SELECT NOW();
```

It runs the first query fine, then has 2 failed queries: 
```
Query 2 ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CURDATE()' at line 1
```
 and 
```
Query 3 ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'URDATE();
SELECT NOW()' at line 1
```

If I run those same commands inside any delimiter statement they work.

**Comment by huyphams** [comment]
Ah thanks, my bad.... I'm fixing it.

**Comment by huyphams** [comment]
Please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks @mdpotts22

**Comment by mdpotts22** [comment]
Everything looks to be good!  Thanks alot!
