### ISSUE TITLE
No Run-ALL button

### ISSUE THREAD

**Issue by AdarshRise** [TablePlus/TablePlus#1469]
1. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Ans: 90, on windows.

Couldn't find a Run all button 

![image](https://user-images.githubusercontent.com/31347367/66269335-d508ad00-e864-11e9-83f8-d7c85c8766fa.png)

**Comment by huyphams** [comment]
Hi @AdarshRise please use the Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues
I'm closing it because it's not related to macOS.  We will add the run all later, meanwhile you can work around by pressing Control + A and then run it.
