### ISSUE TITLE
Cannot edit cell

### ISSUE THREAD

**Issue by bdebever** [TablePlus/TablePlus#147]
Operating System: OS X 10.13.2
Table Plus Version: 1.0 (Build No. 77) - Happy Plan

Summary:

When trying to edit a cell value from the table view, the value is reverted back once the table is refreshed. 
Same when I try to delete values. 

See: http://d.pr/i/jDqQsV

**Comment by huyphams** [comment]
Hi @bdebever, 
Thanks for the bug report. There is `Preview` button, can you make a simple modify and click on it. With that info, I can easily reproduce the bug. 
<img width="458" alt="screen shot 2017-12-20 at 1 34 53 am" src="https://user-images.githubusercontent.com/3654622/34172858-03106a4c-e526-11e7-914a-fb594ab0f77b.png">

**Comment by bdebever** [comment]
Hi there, 

It stays empty! 

Thanks;

**Comment by huyphams** [comment]
Hi @bdebever 
Can you confirm me that you are using PostgreSQL version < 9  (Redshift)? And this table didn't have a primary key?

**Comment by Chinese1904** [comment]
It is happening with me as well that when I try to commit the changes it just erases them out of memory. MySQL 10.2.10-MariaDB.

**Comment by huyphams** [comment]
Hi @Chinese1904 @bdebever 
I have made some changes, could you please test this build?
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Thanks.

**Comment by Chinese1904** [comment]
Awesome, that does seem to have it fixed for me!

**Comment by bdebever** [comment]
Hey, I was actually on MySql, but I tried and it did fix the issue aswell! 

Thans @huyphams , nice one! :) Love your app btw!
