### ISSUE TITLE
Cassandra only show 1 table

### ISSUE THREAD

**Issue by niko44** [TablePlus/TablePlus#1471]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 2.2.8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
This bug appear since the build 88

3. The steps to reproduce this issue:
Only open a connection to a Cassandra database and you will see aonly one table (the first one).

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by niko44** [comment]
![TablePlus_Cassandra_build86_OK](https://user-images.githubusercontent.com/13762589/66382413-730e8b80-e9bb-11e9-9572-cea07d305428.JPG)
![TablePlus_Cassandra_build88_KO](https://user-images.githubusercontent.com/13762589/66382414-730e8b80-e9bb-11e9-9376-eda32e2a0a3a.JPG)

**Comment by huyphams** [comment]
Hi @niko44 please use the Windows repo for reporting issue: https://github.com/TablePlus/TablePlus-Windows/issues
I will close this for now because it does not related to the macOS. Have you tried the build 90, which is the newest build of TablePLus Windows?

**Comment by niko44** [comment]
Sorry I did not know there was a link only for Windows.
With the build 90, it's the same
