### ISSUE TITLE
Azure Postgres Backup Failure

### ISSUE THREAD

**Issue by patrikdevlin** [TablePlus/TablePlus#1473]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

- PostgreSQL 10.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

- Build 264

3. The steps to reproduce this issue:

- Attempting to backup an azure postgres database
- Issue occurs during connection proccess
- Tableplus attempts to add the `{{instance_name}}@` to the host/socket name, which causes the connection to fail.
- No problem connecting to the DB otherwise. 
- Host name should just be `{{instance_name}}.postgres.database.azure.com`

`"{{db_name}}" failed: could not translate host name "{{instance_name}}@{{instance_name}}.postgres.database.azure.com" to address: nodename nor servname provided, or not known`

**Comment by huyphams** [comment]
Hi @patrikdevlin if you have a chance, please try this build and let me know the result https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!

**Comment by huyphams** [comment]
Hi @patrikdevlin any chance that you could try the build? we're about the release a new update this week, thank you!
