### ISSUE TITLE
Add new option for delimiter when exporting to CSV

### ISSUE THREAD

**Issue by mariusghitoiu** [TablePlus/TablePlus#1475]
Hi, 
When importing some cvs files exported from table plus in google sheets everything gets messed up. The problem is the delimiter. All current options **, ; TAB** are problematic.

It will be very helpful when exporting to CSV to add **|** as an option for Delimiter, or if possible to allow the user to set a custom delimiter.

**Comment by huyphams** [comment]
I've fixed that bug on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
You can now use the default option and it should work (the previous build has an escape bug)
<img width="437" alt="Screen Shot 2019-10-18 at 12 10 32 PM" src="https://user-images.githubusercontent.com/3654622/67106053-4b2fdc80-f1a0-11e9-81a9-cdfcc5734a1c.png">
