### ISSUE TITLE
Invalid character for encoding truncates table results

### ISSUE THREAD

**Issue by bfinlay** [TablePlus/TablePlus#1476]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 11.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 264: "Version 2.9.1 (264)"

3. The steps to reproduce this issue:

1. Create table with text column:
![2019-10-09_11-31-12](https://user-images.githubusercontent.com/1757856/66501403-f9dd6a00-ea88-11e9-8e4d-9357eeac59cd.png)

2. Enter rows.   Enter special character in one of those rows
![2019-10-09_11-31-32](https://user-images.githubusercontent.com/1757856/66501446-0e216700-ea89-11e9-8ffa-da09a2913678.png)

3. Change view encoding
![2019-10-09_11-32-34](https://user-images.githubusercontent.com/1757856/66501492-21cccd80-ea89-11e9-8688-3214f4ddc610.png)

4. refresh table
![2019-10-09_11-34-51](https://user-images.githubusercontent.com/1757856/66501522-2abd9f00-ea89-11e9-93a2-74afa9d52408.png)

table results are truncated at the row with the special character.   Return to default encoding and all rows are shown again.

**Comment by huyphams** [comment]
Thanks, TablePlus should show a warning popup instead of quietly truncating the result. We will fix it in the next update.

**Comment by huyphams** [comment]
Hey @bfinlay I added this issue on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 if you have a chance, please give it a try.
