### ISSUE TITLE
Only the last modification goes to the transaction

### ISSUE THREAD

**Issue by zdzana** [TablePlus/TablePlus#1477]
1. Which driver are you using: MySQL 5, MySQL 8
2. Which TablePlus build number are you using: Build 267
3. The steps to reproduce this issue:

I change values in several records in the table data view. There is only one query changing data in the transaction view. When saving a transaction, only this query is called, and the discard cancels only this one modification.

![screenshot](https://user-images.githubusercontent.com/3853340/66568660-3339d680-eb6a-11e9-8430-5f8d24890cc6.png)

**Comment by huyphams** [comment]
Hi @zdzana we're fixing this issue, thanks.

**Comment by huyphams** [comment]
I've pushed a new beta that fixes this issue. Thanks @zdzana please let me know if you're still seeing it.
You can update the new release candidate by TablePlus > Check for updates...

**Comment by zdzana** [comment]
Confirm, the problem has been fixed. Thank you.
