### ISSUE TITLE
Results list not rendering final row

### ISSUE THREAD

**Issue by Jailyard90Grad** [TablePlus/TablePlus#1479]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
PostgreSQL 9.6 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
268

3. The steps to reproduce this issue: 
Run an SQL query. In the results pane, the last row will be cutoff even after scrolling. The only way to get it to render is to resize the pane or app window.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @Jailyard90Grad are you using Catalina and with this setting off?
<img width="921" alt="abc" src="https://user-images.githubusercontent.com/3654622/66678817-1fae6e80-ec43-11e9-99ec-9dd3af822e95.png">

**Comment by huyphams** [comment]
You can turn on the auto-hide table scrollers as a workaround solution @Jailyard90Grad , it looks like a Catalina issue.

**Comment by Jailyard90Grad** [comment]
Thanks for the reply, but I already have the auto-hide scrollers on and I’m not on Catalina.

Cheers,

Mark
www.markdoerr.com

Sent from my iPhone
My apologizes for typos and lunacy

**Comment by Jailyard90Grad** [comment]
Henry...ignore that last comment. I did NOT have auto-hide scrollers on as I thought I did. Turning that on solved it for me. Sorry about that.

**Comment by huyphams** [comment]
I've fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 
If you have a chance, please download it and let me know the result, Thank you!

**Comment by Jailyard90Grad** [comment]
Yes, that fixed it. Thank you!

Mark
