### ISSUE TITLE
[Mac Bug?] Workspace Resets When Clicking on Dock Icon

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#148]
Since the last update, the workplace window resets and clears if I go to another app then back to TablePlus by clicking on the Dock icon. This is hugely inconvenient, as you can imagine.

**Comment by huyphams** [comment]
Hi @mikebronner , this bug was fixed but not officially released. You can try the new build here:
﻿https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by mikebronner** [comment]
Duplicate of #142
