### ISSUE TITLE
TablePlus does not auto switch between Dark and Light mode

### ISSUE THREAD

**Issue by Fossil01** [TablePlus/TablePlus#1480]
I'm using 2.9.1 and when MacOS auto switches to dark mode at night TablePlus stays in Light mode. If I then go to MacOS settings and force dark mode instead of Auto then TablePlus switches.

Also works the other way around, it doesn't auto switch back to Light mode.

**Comment by huyphams** [comment]
Thanks @Fossil01 I just fixed it now. 👍

**Comment by huyphams** [comment]
just in case, here is the hot patch: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!

**Comment by joshlewis** [comment]
Just ran into this. I hope this fix ships publicly soon! Thank you for making it!
