### ISSUE TITLE
Export CSV data with "Quote if needed," quote and newline will be escaped wrong.

### ISSUE THREAD

**Issue by taichunmin** [TablePlus/TablePlus#1482]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 2.9.1 (264)

3. The steps to reproduce this issue:
    - run query `select '"' as quote1, '{"a":"b"}' as quote2, '1\n2' as newline from dual`
    - click export button
        ![](https://i.imgur.com/UYZ0en1.png)
    - Then the csv file will have wrong quote
      ```csv
      quote1,quote2,newline
      ",{"a":"b"},1
      2
      ```

4. Expected
    ```csv
    quote1,quote2,newline
    """","{""a"":""b""}","1
    2"
    ```

**Comment by huyphams** [comment]
Hi, this is expected behavior, the default behavior is `Quote If needed` and it only adds a quote if the content contains the delimiter character.
You can change the behavior by changing the Swap to `"` TablePlus will add a double quote regardless of the content.

**Comment by taichunmin** [comment]
In csv format, field should be quote when it contains quote, delimiter or newline. And quote should be escape.

**Comment by huyphams** [comment]
This hot patch should fix the issue @taichunmin thank you for letting me know:
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
