### ISSUE TITLE
[Bug] Decimal delimiter for CSV export is ignored

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1483]
This issue has been reported before (message #01032), it was fixed, but it seems to be back again.

Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.2

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 200 (macOS)

The steps to reproduce this issue:

Create an SQLite table with a few columns formatted as double.
Export table. Chose as decimal delimiter ','.

The resulting export file has numbers with "." as a delimiter.
The same happens when using right click > Copy Rows As > CSV / CSV With Header.

I have never been able to export a table with "," as decimal delimiter. The settings in the preferences also do not help.

Best,
Chris

**Comment by huyphams** [comment]
I can't reproduce the issue. Could you copy the table creation for me, I think TablePlus has failed to detect the numeric data so it didn't replace the . to ,

**Comment by chrschmitz** [comment]
Export the attached table with comma as delimiter.

[Test.sqlite3.zip](https://github.com/TablePlus/TablePlus/files/3724447/Test.sqlite3.zip)

**Comment by huyphams** [comment]
I see that the data type is TEXT(255) text is not a numeric data type so that why TablePlus won't replace it (and it should not be replaced because it's a string).

**Comment by chrschmitz** [comment]
Sorry, I was too fast creating the test file. Same issue, if the field is REAL.

[Test.sqlite3.zip](https://github.com/TablePlus/TablePlus/files/3724462/Test.sqlite3.zip)

**Comment by huyphams** [comment]
it's very hard to detect all the possible types in SQLite because it's a free database. The user can enter whatever they want as a type.  I've added a handler for `real` type but I'm not sure if it could be back again if the user uses another numeric type. Currently, TablePlus handles: number, integer, double, serial, bigint, real (just added).
. Thank you for letting me know!

**Comment by huyphams** [comment]
You can download this hot patch @chrschmitz thank you!
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
