### ISSUE TITLE
Table next page button always active even if no more results

### ISSUE THREAD

**Issue by etorel** [TablePlus/TablePlus#1484]
1. Which driver are you using and version of it: PostgreSQL 10.6

2. Which TablePlus build number are you using: 264

3. The steps to reproduce this issue:
- Open a table containing some data
- Click on the next page button which is always active

You should obtain something like this in bottom bar:
![image](https://user-images.githubusercontent.com/8760377/66760106-b4160c80-eea1-11e9-9661-c7c4841ff5d1.png)

There is an issue in the row number and the page is displayed empty.

**Comment by huyphams** [comment]
Hi, this is intentional behavior. Some times, the user adds data from other services and they would like to click next to check the next page, it also helps when the rows count is estimated value.

**Comment by etorel** [comment]
Impressive response time 👍 

Thanks for your explanation.
