### ISSUE TITLE
Query Editor Accidentally Ran All Queries

### ISSUE THREAD

**Issue by Akkadius** [TablePlus/TablePlus#1485]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

`MySQL 5.6+`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

`2.9.1`

3. The steps to reproduce this issue:

There is not so much of a reproduce as a safety validation. I have had 40+ queries (hundred s of lines) that I had stacked up in an editor window over a period of months because I will often re-use queries from previous sessions. And when I had went up to a query to do a Command + Enter, somehow it thought that I had selected every query in my damn window and ran it all and ran a deletion query that I had ran weeks ago. So right now I'm dealing with data loss on production and its kind of a pain in the ass.

I absolute love this editor, I use it with Alfred to navigate many databases quickly, you guys have done great work, but there need to be a validation window to popup before deciding to run more than a few queries at a time even if it was by freak accident. This should be easy to implement and save some huge headaches and if people hate it they can shut it off

**Comment by huyphams** [comment]
Hi @Akkadius did you try the second warning mode? if turn the warning mode on, TablePlus will warn you if you send a NONE SELECT query to the server.
<img width="1006" alt="Screen Shot 2019-10-15 at 9 53 21 AM" src="https://user-images.githubusercontent.com/3654622/66833137-a1e3af00-ef31-11e9-804b-08c5a0d04d3e.png">

**Comment by Akkadius** [comment]
Makes sense, I suppose I would expect to have **Alert Mode 2** on by default and then make it configurable to disable later on. I had no idea that these options even existed and I can probably guess most other people have no idea they exist either

<3

**Comment by huyphams** [comment]
TablePlus now allows us to custom shortcut key so I think this issue is resolved now.
