### ISSUE TITLE
privilege CREATE TEMPORARY TABLES not listed on available privileges

### ISSUE THREAD

**Issue by MLanW** [TablePlus/TablePlus#1486]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`MariaDB 5.5.64`
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`2.9.1 (build 264)`
3. The steps to reproduce this issue:
```
- Connection > User Management
- Select a user and host (i.e. root > localhost)
- Select `Database privileges` tab
```

On the right column named "Available Privileges" isn't listed the  CREATE TEMPORARY TABLES privilege. 

If i edit a user created from another system (i.e. PhpMyAdmin) with this privilege, in granted privileges column is listed and, if i remove it, i can't reassign it.

**Comment by huyphams** [comment]
Hi @MLanW please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I've added the `CREATE TEMPORARY TABLES` let me know if you're still seeing the issue.

**Comment by MLanW** [comment]
Hi @huyphams 
now I can give the privilege but I can't remove it because, if I open the User Management again, I always see it among those available.

Thanks in advance

**Comment by huyphams** [comment]
Ops sorry, I have got a typo, now it should be fixed: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by MLanW** [comment]
ok, now it work fine.

Thank you!
