### ISSUE TITLE
Beautify ⌘I adds extra spaces inside [] that breaks the query

### ISSUE THREAD

**Issue by vkosmirak** [TablePlus/TablePlus#1487]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Local Sqlite file

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.9.1 (264)

3. The steps to reproduce this issue:
----
1) Paste query:
```
select [301bbd2b-702b-4ba5-8355-fe8669106d1b].name as [oce__workplace__c.name] from oce__accountaddress__c  left join account as '301BBD2B-702B-4BA5-8355-FE8669106D1B' on [301BBD2B-702B-4BA5-8355-FE8669106D1B].uid == oce__accountaddress__c.oce__workplace__c where oce__accountaddress__c.uid = 'a1G6D000000BGbXUAW'
```
2) Hit Beatify ⌘I. Result:
```
SELECT
[301bbd2b - 702b - 4ba5 - 8355 - fe8669106d1b].name AS[oce__workplace__c.name]
FROM
	oce__accountaddress__c
	LEFT JOIN account AS '301BBD2B-702B-4BA5-8355-FE8669106D1B' ON[301BBD2B - 702B - 4BA5 - 8355 - FE8669106D1B].uid == oce__accountaddress__c.oce__workplace__c
WHERE
	oce__accountaddress__c.uid = 'a1G6D000000BGbXUAW'
```
3) `[301bbd2b-702b-4ba5-8355-fe8669106d1b]` becomes `[301bbd2b - 702b - 4ba5 - 8355 - fe8669106d1b]`. New spaces were added. Query is not valid anymore
4) After hit Uglify  ⇧⌘I, spaces still exist

**Comment by huyphams** [comment]
Hi, the bug has been addressed in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue.
