### ISSUE TITLE
Problem with SQL server semi-colon ending DECLARE statement

### ISSUE THREAD

**Issue by alnitaka** [TablePlus/TablePlus#1488]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL 2017 (DBVERSION_74)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 2.9 (260)

3. The steps to reproduce this issue:

Connect to any MSSQL db, then open SQL query and execute the following two statements either by using "Run all" or by selecting all rows and then using "Run current":
```
DECLARE @date date= '10-16-2019';
SELECT @date AS 'My date'; 

```

You get the following error message:
```
Query 2 ERROR: Msg: 137, Line 2, State: 2, Level: 15
Must declare the scalar variable "@date".

```

Just remove first semi-colon:
```
DECLARE @date date= '10-16-2019'
SELECT @date AS 'My date'; 

```

Then it works as it should:
```
My date
2019-10-16
```

According to Microsoft, semi-colon is an optional statement terminator and thus should not be interpreted as a query terminator by TablePlus. In addition, semi-colons are ANSI SQL-92 and may be mandatory in a future release. See [Deprecated Database Engine Features in SQL Server 2016](https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2016?redirectedfrom=MSDN&view=sql-server-ver15.

**Comment by huyphams** [comment]
Have you tried to swap it into one transaction @alnitaka 
<img width="763" alt="Screen Shot 2019-10-16 at 4 48 51 PM" src="https://user-images.githubusercontent.com/3654622/66953423-ddb36d00-f034-11e9-86b7-5ee89a66ead1.png">

**Comment by huyphams** [comment]
I'm closing it because it's duplicated with https://github.com/TablePlus/TablePlus/issues/1268
