### ISSUE TITLE
Editing Postgres functions

### ISSUE THREAD

**Issue by jmtov** [TablePlus/TablePlus#149]
I just wanted to know if it's possible to edit postgres functions.

Thanks in advance.

**Comment by huyphams** [comment]
Currently, TablePlus didn't support edit stored procedures /functions but we have a plan to support it in future.

**Comment by jmtov** [comment]
Awesome!

**Comment by huyphams** [comment]
Hey @jmtov the beta build has function feature. Can you give a try?
﻿﻿https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by jmtov** [comment]
I'll surely do! Thanks! 😺

**Comment by cloudkite** [comment]
Firstly thanks for the awesome app! Is the ability to edit procedures / functions coming for SQL Server as well?

**Comment by huyphams** [comment]
@cloudkite hey thanks, let me see how to get MS SQL Server functions 😄

**Comment by cloudkite** [comment]
@huyphams any news on this? This is the only thing holding me back from purchasing at the moment 👍

**Comment by huyphams** [comment]
Hi @cloudkite it works in progress, I'm fixing some SQL Server Syntax to support multiple schemas, create a function...
You can check out the newest build here: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
This build can show you the functions.
