### ISSUE TITLE
Better editing of TEXT columns

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [TablePlus/TablePlus#1490]
Version 2.9.1:

Editing TEXT columns is a HUGE pain :( (Unless I'm missing something.) It's near impossible in fact. Can something be done?

**Comment by huyphams** [comment]
Hi @JohnnyWalkerDesign what are the TEXT columns?

**Comment by huyphams** [comment]
I don't know if you mentioned the edit text in the table grid or something else.
You can edit the long text by using the right sidebar or the middle mouse click, if you do not have a mouse with a middle button, you can right-click => Quick Look.

**Comment by JohnnyWalkerDesign** [comment]
Columns of type TEXT

<img width="475" alt="Screenshot 2019-10-18 at 14 42 06" src="https://user-images.githubusercontent.com/6763222/67099341-ae783980-f1b5-11e9-9c38-454cc980fcbd.png">

**Comment by JohnnyWalkerDesign** [comment]
Ah, I see. I hide the right sidebar because it's usually just hogging screen space with no benefit. Thanks.

**Comment by huyphams** [comment]
Have you tried my suggestion @JohnnyWalkerDesign
![2019-10-18 10 45 23](https://user-images.githubusercontent.com/3654622/67099484-6f85bc00-f194-11e9-97be-235a10bc8a45.gif)
. The quick look is the full editor which can easily handle long tex.

**Comment by JohnnyWalkerDesign** [comment]
Wow. So "Quick Look" actually means "Edit". Interesting. Thanks.
