### ISSUE TITLE
Pasting into to fields, suddenly tried to create row

### ISSUE THREAD

**Issue by jannejava** [TablePlus/TablePlus#1491]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
264

3. The steps to reproduce this issue:
Pasting same value to fields makes the editor to jump to the end suddenly and tries to create a new row. This happens everytime after awhile. See attached screen recording.

https://www.dropbox.com/s/1ykfxm47taak3y3/tableplus.mp4?dl=0

Noted: If the bug is related to data, please attach an example SQL data.

Regards, Jan

**Comment by huyphams** [comment]
Hi @jannejava I think there was an accident when the field was not on editing mode and you pressed command + V => it created a new row with the value in the clipboard.
There is a faster way to edit multiple lines with the same value: Select all rows, toggle the right sidebar (by pressing space or click the top right button) and edit the field on right sidebar, it will update all the rows.

**Comment by jannejava** [comment]
Hi thanks for your reply! 

Great tip with the multi-edit mode too, I was not aware of this.

You are indeed right, been testing more now: seems I was too fast and some times the editing mode did not enable. But I was not aware this behaviour that cmd-V (=pasting) to a table would enable the "create mode" on a row. Good to know!

I am closing this issue now. :-)

![](http://giphygifs.s3.amazonaws.com/media/4pMX5rJ4PYAEM/giphy.gif)
