### ISSUE TITLE
Exporting table with SQL eats up all memory until machine freezes

### ISSUE THREAD

**Issue by louis77** [TablePlus/TablePlus#1492]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PG 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

271

3. The steps to reproduce this issue:

Export a big table in SQL format with Zip compression turned on.

Noted: If the bug is related to data, please attach an example SQL data.

![IMG_1701](https://user-images.githubusercontent.com/1240462/67196770-c214e180-f3fb-11e9-9beb-be2b91a099fc.jpg)

**Comment by huyphams** [comment]
Hi, I've fixed this issue on the newest release 276. Please let me know if you'res still seeing it.

**Comment by louis77** [comment]
I can confirm that memory and CPU now stay low for big table exports w/ compression. Thanks!

**Comment by phil93883** [comment]
I'm using the latest version (3.10 290) and this still happens.  On a new MacBook Pro with 16GB RAM, I'm trying to export a table with around 110 million rows.  I get the same out of memory error as above at around the 52m mark.  This is exporting from MariaDB.
