### ISSUE TITLE
PEM files for Oracle Connector

### ISSUE THREAD

**Issue by am17torres** [TablePlus/TablePlus#1493]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oracle

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 271

3. The steps to reproduce this issue: N/A

I am currently using DBeaver and looking to migrate to TablePlus. One of my existing, and working, DBeaver connections is to an externally managed Oracle Database. In the DBeaver connection instructions from the vendor they say that I **must** install their certificate in `/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/security/cacerts`  and update DBeaver's `javax.net.ssl.keyStore` property to point to the `cacerts` file containing the custom  cert.

I'm curious if/how it's possible to accomplish the same with TablePlus. If I have a `.pem` file, is it possible to use that to connect to a third party database? I assume this is different from connecting over SSH because I don't have a server proxying traffic. 

Thanks for the help!

**Comment by royOST** [comment]
This is also blocking me from migrating over. Need to use SSL for an oracle connection but it isn't supported like it is for MySQL.

**Comment by huyphams** [comment]
Working on new Oracle driver which support custom SSL, next beta update will include this!

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this patch: https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
