### ISSUE TITLE
UX: Selected table on the left may not be what is viewed (selected tab) 

### ISSUE THREAD

**Issue by msawired** [TablePlus/TablePlus#1494]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.5
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.9.1
3. The steps to reproduce this issue:
open a few tables by clicking on tables on left panel, then switch to another table using tabs on top.

When user switches to a different table, previous table selected on the left panel stays selected. This is basically a major UX issue, having two different indicators of selected table (left panel vs tab). This caused a few major issues for me, as I deleted a few rows from the wrong table multiple times. 

Recommendation: All indicators of selected table should indicate the selected table. E.g. When I switch tables using tabs, left panel should also show that table selected (or unselect, if selected Tab is a SQL tab, etc.) and they should be in sync. Another option would be to unselect the selected table on the left view when user changes the tab. This would force user to check the tab title to make sure they are on the same table.

![Screenshot 2019-10-21 18 30 24](https://user-images.githubusercontent.com/579033/67247981-e808a900-f430-11e9-802f-0da8a2e6ed3b.png)

**Comment by huyphams** [comment]
It will be added in the next update!

**Comment by msawired** [comment]
Thanks!
