### ISSUE TITLE
Error when connecting to a TLS-enabled db backend: "Error - Access without SSL Denied"

### ISSUE THREAD

**Issue by HannesBBR** [TablePlus/TablePlus#1495]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.5.5-10.3.15-MariaDB (with MariaDB Maxscale in front of it)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 264

3. The steps to reproduce this issue:

In Tableplus:
- Enter a hostname and port of a TLS-enabled Mysql server (in our case Maxscale, but that shouldn't make a difference afaik)
- Choose SSL Mode: `PREFERRED` or `REQUIRED` (but don't specify any certs or key)
- Click `Connect` or `Test`

Result:
- **Build 264**: Error - Access without SSL denied 
- **Build 228**: connection successful
- **Sequel pro** (same config, no certs or key): connection successful
- **mysql cli** (SSL Mode preferred or required): connection successful 

I would expect that the SSL Mode option in TablePlus just mirrors how the mysql cli works. It seems that at the moment these ssl modes are not correctly behaving. The weird thing is that it works correctly in an older build (e.g. 228).

**Comment by huyphams** [comment]
Hi @HannesBBR thank you for letting me know. Does it work with the build 233?
(Download here: https://tableplus.com/blog/2017/02/changelogs.html) or the latest build that it works with SSL mode in your setup.

**Comment by HannesBBR** [comment]
Just tried, and in build 233 it also doesn't work (same error "Access without SSL denied"). So 228 seems to be the latest version where it is still working.

**Comment by huyphams** [comment]
Thanks, I'm checking the commit log between two builds: 228-233.

**Comment by huyphams** [comment]
Hi @HannesBBR thank you, could you please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 and let me know the result?
I found out that from the 233 and above, TablePlus uses the MariaDB native instead of reuse the MySQL lib so it uses a different flag to enable SSL.

**Comment by HannesBBR** [comment]
Hey @huyphams ,

Thanks for the quick follow-up! That indeed would explain the deviation of the normal mysql 
behaviour. I tested the new build. 

Result:
- SSL Mode PREFERRED: Same error - "Access without SSL denied"  
- SSL Mode REQUIRED: New error "Unable to get local issuer certificate" 
=> this error is normally related with TLS Client Authentication. But since we're not requiring client authentication, this shouldn't occur. 

Maybe you can compare the behaviour with how the normal mysql client works, e.g. `mysql -h <hostname> -u <user> -p <password> --ssl-mode REQUIRED`? This works in our case (also with `PREFERRED`), so I guess there still is a mismatch with the original mysql SSL-mode behaviour.

**Comment by huyphams** [comment]
Actually, TablePlus does not use the MySQL client lib for making MariaDB connection. And MariaDB does not have the mode `PREFERRED`
If you try again with the MySQL driver connection (in TablePlus), I think it should work out the issue. I've read the MariaDB documents but there is nothing except the `MYSQL_OPT_SSL_ENFORCE` but it takes no effect.

**Comment by huyphams** [comment]
Could you please try again with the MySQL Connection Driver instead of MariaDB Connection in TablePlus and let me know the result @HannesBBR 
I found out that currently, MariaDB does not support the SSL ENFORCE OPT: https://jira.mariadb.org/browse/ODBC-238

**Comment by HannesBBR** [comment]
Ok, I see the issue now! It didn't occur to me that the connection I was testing was actually a 'MariaDB' TablePlus connection instead of a 'Mysql' connection, and that the SSL behaviour compared to the MariaDB SSL mode would be different. 

Using a 'Mysql' connection indeed immediately works, so I'll close the issue.

Thanks for your help!
