### ISSUE TITLE
BLOBs displaying as ASCII in build 270

### ISSUE THREAD

**Issue by vitebsk66** [TablePlus/TablePlus#1498]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 5.5.60
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 270
3. The steps to reproduce this issue:
If I run a select where the resulting data set includes data from BLOB columns (e.g. MediumBLOB), that information is displayed as ASCII character codes instead of plain text. Data from other column types is unaffected and displays normally. Accessing the same data with build 264 of TablePlus or with another GUI does not exhibit this behavior.

**Comment by huyphams** [comment]
Hi @vitebsk66 from the build 270, TablePlus will display the data which has encoding `binary` as Hex (it's not ASCII but looks like ASCII).
You can right-click => quick look editor (or using middle mouse) to see the content, TablePlus will try to decode the hex back to normal content: image, pdf, text etc...

**Comment by vitebsk66** [comment]
That makes sense. The column in question should really have been a MEDIUMTEXT instead of MEDIUMBLOB (not my design). If the software could (in a future update) detect the contents as text and display them as such, it would be helpful. In the meantime, the quick look feature still allows me to view and edit the text, which is vital. Thank you for your prompt response.

**Comment by huyphams** [comment]
Hey @vitebsk66 please try this build, TablePlus now will try to convert the content back to the original if it's possible https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by vitebsk66** [comment]
@huyphams that new build seems to do the trick! Looking good. Many thanks for the quick update.
