### ISSUE TITLE
Feature: Add generation of UUID strings.

### ISSUE THREAD

**Issue by davidpv** [TablePlus/TablePlus#1499]
It would be very useful to add the generation of uuids.

**Comment by huyphams** [comment]
Hi @davidpv 
1. Please download this build (I've exposed some API for the plugin): https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
2. Install this plugin: https://github.com/TablePlus/uuid-generator

**Comment by davidpv** [comment]
One concern, the thing is that I can generate uuid for a row already in the database but, how do I generate a UUID for a new row??

**Comment by davidpv** [comment]
By the way, thanks and congratulations for your job in TablePlus, excellent app!!

**Comment by ruudk** [comment]
@huyphams Thanks for this. But this message freaked me out, I don't think I ever want to risk this:
<img width="473" alt="Screenshot 2019-10-28 at 08 33 36" src="https://user-images.githubusercontent.com/104180/67659868-ba09f400-f95d-11e9-8aab-d8e2f06b7acd.png">

**Comment by huyphams** [comment]
It's developed by me and also open source so I think it's safe... 😄

**Comment by janWITZANY** [comment]
@davidpv 
> One concern, the thing is that I can generate uuid for a row already in the database but, how do I generate a UUID for a new row??

I had the same problem. It worked for me when I initially set a value in the column (e.g., null); afterward, I was able to generate the UUID. I'm not sure if there's a better way to handle this.
