### ISSUE TITLE
The correct file have no extension

### ISSUE THREAD

**Issue by indapublic** [TablePlus/TablePlus#15]
![screen shot 2017-07-13 at 14 51 10](https://user-images.githubusercontent.com/856260/28150888-da8caae0-67da-11e7-981e-ab70d2982b55.png)

I'm not sure is correct. `.ppk` is valid file extension for private key file

**Comment by huyphams** [comment]
hi @indapublic 
It is the warning, you can ignore the warning for now. I will improve it in the next release.
Thank you.

**Comment by huyphams** [comment]
Fixed in build 54. Please go to TablePlus > Check for update...
