### ISSUE TITLE
[Feature Request - Mac] Tabs for Multiple Windows

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#150]
Sierra introduced the ability to combine multiple native app windows into tabs in a single window. Would love to see that functionality in TablePlus to allow for easy switching between different workspaces.

i see that the base functionality is already there in the Windows menu:

![screen shot 2017-12-19 at 1 15 55 pm](https://user-images.githubusercontent.com/1791050/34179183-c9e947dc-e4be-11e7-8604-3f7b1ae4dc8f.png)

However, it seems the app itself is suppressing the title bar and/or tab functionality. If this is built on Electron, I know there is a setting to allow for this (I just can't remember what it was), as this issue has been reported to other Electron apps in the past, and they were able to fix it using an existing configuration variable somehow. :) Sorry for the vagueness.

The view menu has an option to show the tab bar, but when I enable that, it goes into the workspace overview.

Thanks!

**Comment by huyphams** [comment]
Hi Mike,
There is an option to show all workspaces in TablePlus. By press `command + shit + \` (support on High Sierra a above).

I'm working on a new feature (workspace navigation tab), this feature allows you switch between workspaces easily.

**Comment by mikebronner** [comment]
I am asking specifically for the tabs feature, because that is standard in macOS now, and I use it for my workflows in all my apps on a daily basis. Perhaps that could be added as well as the workplaces view? Maybe a toggle to optionally show the tab bar?

**Comment by huyphams** [comment]
We have a toggle button.
<img width="1152" alt="tab" src="https://user-images.githubusercontent.com/3654622/34188929-7b0df92a-e56b-11e7-9479-544b11c3564e.png">

But I want to make a tab because 1 click always better than toggle + click (2 clicks). I'm working on it.

**Comment by huyphams** [comment]
Hey, @mikebronner can you give a try on this build?
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
<img width="1274" alt="screen shot 2018-01-22 at 10 40 24 pm" src="https://user-images.githubusercontent.com/3654622/35229148-3fdb2bba-ffc5-11e7-84cf-1caf4eaa3a91.png">

**Comment by mikebronner** [comment]
Thanks @huyphams  :) I will give it a shot next week, I'm currently out of town traveling. :)
