### ISSUE TITLE
Error when saving binary data modified in Quick Look Editor.

### ISSUE THREAD

**Issue by dbr031** [TablePlus/TablePlus#1500]
1. Driver: MySQL 5.7.26

1. TablePlus Build Number: 270

1. The steps to reproduce this issue:

    1. Navigate to a non-empty table that has a binary data column. (As of build 270, this data is now displayed in HEX notation.)
    1. _Middle-click_ on the binary data record (or _right-click > Quick Look Editor_) to edit the record. (In the Quick Look Editor the data is currently displayed as CHAR, just like it was displayed in the table view pre-270.)
    1. Edit the data in the Quick Look Editor (or leave unchanged), but ensure to _include as least one special character or a letter between g-z_, e.g. `foobar`.
    1. Confirm the new or unchanged value, e.g. by clicking outside the panel, hitting ESC, or hitting CMD+Return on macOS. (TablePlus will highlight the modified cell, but the change has not yet been committed. Note that the cell value is now displayed in CHAR notation.)
    1. Commit the update, e.g. by hitting CMD+S on macOS.
    1. The commit currently fails with the following dialog:
        > **Error**
        > You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'X'`{CHAR_VALUE}` at line 1
        > All changes were reverted (DDL statements can't be reverted).
    
        whereas `{CHAR_VALUE}` will contain new the binary data in CHAR notation, e.g.
        > [...] syntax to use near 'X'foobar at line 1 [...]

It appears as though the new data, upon closing the Quick Look Editor, is temporarily stored as CHAR instead of HEX, but the resulting query when committing the change expects HEX notation.

A potential quick solution could be to converted the data back into HEX notation when closing the Quick Look Editor, assuming it was displayed as CHAR at the start. (I am unsure if data is always displayed as CHAR, or only under certain conditions.) Another _solution_ could be to always display the data in HEX, though personally I find viewing & editing in CHAR notation very useful.

A longer-term solution might be offering different views in the Quick Look Editor (such as HEX, CHAR, or BASE64) to allow the user to edit in either notation, and then convert the data into HEX when needed upon closing the editor.

**Comment by huyphams** [comment]
Thank you for the details
`A longer-term solution might be offering different views in the Quick Look Editor (such as HEX, CHAR, or BASE64) to allow the user to edit in either notation, and then convert the data into HEX when needed upon closing the editor.`
Yes, that's our plan, we will put a tab view into the quick look editor, it's easier for the user to understand the UX and also the way TablePlus convert the input value.

**Comment by dbr031** [comment]
> Yes, that's our plan, we will put a tab view into the quick look editor, it's easier for the user to understand the UX and also the way TablePlus convert the input value.

That's great news!

In the meantime, are there any workarounds for this issue, besides manually converting the data from CHAR into HEX after modifying it in the Quick Look Editor?

**Comment by huyphams** [comment]
Unfortunately, I don't think that there is any way to force TablePlus to convert the text back to hex. You have to wait the new beta next week  (or I will update this thread as soon as possible).

**Comment by huyphams** [comment]
Please try this build if you have a chance @dbr031 https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
let me know if it works for you. Thanks

**Comment by dbr031** [comment]
> let me know if it works for you. Thanks

Looks great! From what I've briefly tested, I can confirm this version automatically encodes the data back into HEX notation after editing binary value in CHAR notation via the Quick Look Editor. The subsequent commit queries ran successfully too, persisting the correct update as expected. 👏

**Comment by huyphams** [comment]
TablePlus now also will decode the blob back to the original content if it's possible: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
thanks @dbr031
