### ISSUE TITLE
cannot manage last user in user management list

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#1501]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3.16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
270

3. The steps to reproduce this issue:
Open user manager

The last user cannot be managed because of icon location. See screenshot.

<img width="194" alt="Screenshot 2019-10-24 at 16 31 44" src="https://user-images.githubusercontent.com/3632883/67496088-28a83280-f67c-11e9-8111-af09557b54a1.png">

**Comment by huyphams** [comment]
Thanks @minusf I've fixed it, I will update a hot patch asap.

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by minusf** [comment]
the last user can be reached now. thank you.
