### ISSUE TITLE
Query Editor doesn't detect/bypass closing quotes/backquotes

### ISSUE THREAD

**Issue by bkoch84** [TablePlus/TablePlus#1502]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
270

3. The steps to reproduce this issue:
i. Open Query Editor
ii. Type a single quote, double quote, or backquote.  The editor will automatically generate a corresponding, closing quote of the same type.
iii. Typing another quote of the same type while the cursor is immediately to the left of the correct closing quote now inserts another pair of that quote rather than detecting the previously generated closing quote and overwriting it/moving the cursor to the right.  This can be repeated indefinitely.

This began happening with the update to build 270.  I, unfortunately, cannot recall if prior to this the editor simply didn't auto-complete the closing quotes, or if it did, but properly detected and bypassed them.  I think maybe it just didn't auto-complete quotes at all?  

As a simple example of how this effects query editing, previously, if you pressed the single-quote key twice to indicate a blank string, you'd end up with two single-quotes with your cursor to the right of both quotes.  Now, if you take the same action, it results in 4 single-quotes with your cursor in the middle.  This behavior makes query entry/editing noticeably less efficient, as the cursor must be manually moved outside the closing quotes via the arrow keys or clicking, or excess quotes would need to be cleaned up later.

Parentheses and all types of brackets all have similar auto-complete functionality, but properly detect the closing paren/bracket and bypass it. 

If this behavior is intended, perhaps an option to control the behavior could be added?

**Comment by huyphams** [comment]
Thanks, this one of the known issues. We're working on it.

**Comment by bkoch84** [comment]
Perfect, thanks!  Apologies if that was posted elsewhere already.  I didn't spot it when searching.

Cheers~

**Comment by huyphams** [comment]
Hi @bkoch84 please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I've added some improvements. Thank you!

**Comment by bkoch84** [comment]
Thanks for the update.  I gave it a try and It looks to be preventing the auto-insertion of additional closing quotes, but is still leaving the cursor inside the original pair of quotes.

My hope was that now that the quotes are auto-generating a closing quote, that they'd also detect closing quotes similar to how pairs of `()`, `[]`, and `{}` all do, at least I think most users would prefer that.  Basically, if the cursor is to the left of a quote and you type that same type of quote, it'd detect it and move the cursor one position to the right rather than typing another between them.  If your cursor is not to the left of a quote and one is typed, it'd create a pair of them and place your cursor between them.

To see this in action, if you currently open the query editor and type `(`, it'll automatically add the closing `)` to the right of the cursor.  I could then type my query inside and the closing `)` would remain on the right.  Then when I type `)` to close the pair of parentheses, instead of adding a second closing one, it just sees there's one already there and moves the cursor to the right one without adding another. Many editors and IDEs handle single-quotes, double-quotes, and backquotes in the same way if they auto-generate the closing quote when the first is typed.

Hope that helps clarify a bit, though it's a bit awkward to try and explain, so I apologize.  Thanks for looking into it!

**Comment by huyphams** [comment]
Thanks @bkoch84, I'm a fan of Vscode (I'm using it for Golang) and the Sublime Text, I understand your expectations. I want to improve it but it's very hard to achieve the level of those editors, but I will try my best!

**Comment by huyphams** [comment]
Hey @bkoch84 please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 TablePlus now will move the cursor instead of adding a new quote at the end.

**Comment by alexgw-afr** [comment]
I would like to suggest that, if this is not already planned, that the "automatically insert matching close paren/quote" option ought to eventually make its way to the Preferences dialog as an enable-able checkbox.

**Comment by huyphams** [comment]
Sure @alexgw-afr I've added it already (but it has not been released yet).

**Comment by bkoch84** [comment]
Was just able to try out the new update and it's working great, thanks!  Nice to have the toggle-able option in Preferences for the functionality in place now as well.
