### ISSUE TITLE
VARBINARY field not displaying as it did before.

### ISSUE THREAD

**Issue by leepercox** [TablePlus/TablePlus#1507]
1. Which driver are you using and version of it:
Mysql 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
270

3. The steps to reproduce this issue:

Create a field with type VARBINARY and then view it

Noted: If the bug is related to data, please attach an example SQL data.

Until the latest version, any VARBINARY field would show the data normally. But now, I just get a load of gobble. 

![image](https://user-images.githubusercontent.com/6492146/67635686-86798c00-f8c1-11e9-82da-42330fd0c2a0.png)

![image](https://user-images.githubusercontent.com/6492146/67635688-8d080380-f8c1-11e9-8f52-9b5efc08dc15.png)

Since changing versions, I have not modified or touched my code. But now I just cannot view the data. This had worked up until now. 

This field SHOULD be showing the URL e.g. https://github.com/

If I am doing something stupid, please let me know. But I do believe this is an issue in the latest build of TablePlus.

**Comment by huyphams** [comment]
Please try this build @leepercox https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 and it seems duplicate with https://github.com/TablePlus/TablePlus/issues/1498

**Comment by huyphams** [comment]
We just released the build 272 which addressed this issue, let us know if you're still seeing it.

**Comment by leepercox** [comment]
Works great now. 
Thank you.

Sorry for the duplication.
