### ISSUE TITLE
Feature request: Zoom through ⌘ +  and ⌘ - keys

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1509]
**_Feature request_** 

Would be nice if one could zoom the SQL windows (larger font) by using the ⌘+ and unzoom by ⌘-

regards,
Bart. 
 

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
not relevant

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
272

3. The steps to reproduce this issue:
not relevant

**Comment by huyphams** [comment]
Which keyboard layout do you have @BFJonk TablePlus has already supported the command + and command - (tested on the US keyboard).

**Comment by BFJonk** [comment]
Hi, it's getting stranger... 

I'm using a standard apple extended keyboard 
![image](https://user-images.githubusercontent.com/24241551/68198894-37b4ac00-ffbd-11e9-947f-6707b176e4cc.png)

with the 'Dutch' keyboard layout. 
![image](https://user-images.githubusercontent.com/24241551/68198945-561aa780-ffbd-11e9-90ab-91df64abed93.png)

I now noticed the following: 
1) In Tableplus  ⌘+ and by ⌘-  do work when using the + en - which are on the main keyboard next to the 0
2)  In Tableplus ⌘- does work, when using the '-' on the numerical keyboard
3)  In Tableplus ⌘+ does NOT work, when using the '+' on the numerical keyboard

4) in Google docs   ⌘+ and by ⌘- do work regardless on which + or - keys used.

**Comment by huyphams** [comment]
I know the reason. I was wrong. the shortcut is command - and the command = (not command +).
And you can change it the preference.

**Comment by BFJonk** [comment]
Indeed, this works. Maybe the default should change to ⌘+, in stead of ⌘=  ?

**Comment by alexandreamadocastro** [comment]
Another problem is that only works in the SQL window, not in the actual table view.
