### ISSUE TITLE
[Feature Request] Sortable Columns in Structure View

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#151]
I would love to be able to sort my columns in structure view to help navigate those huge tables. :) Simple click on the header of the column should toggle ascending, descending, unsorted.

**Comment by huyphams** [comment]
Yeah sure, when I have done in-memory sort on this issue: https://github.com/TablePlus/TablePlus/issues/144
It can also be applied to the table structure.

**Comment by huyphams** [comment]
TablePlus build 78 is released.
