### ISSUE TITLE
cannot execute schema creation statements from Tableplus

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1512]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgresSQL 11.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
272

3. The steps to reproduce this issue:
a) see SQL. 
b) tried to execute all statements. returns with error "Query 1 ERROR: ERROR:  schema "external" does not exist" 
c) also the Syntax coloring is not recognising the word AUTHORIZATION

--> Note: If the bug is related to data, please attach an example SQL data.
see attchment
[Postgress create schema.txt](https://github.com/TablePlus/TablePlus/files/3779387/Postgress.create.schema.txt)

The statements can be executed from pgAdmin

**Comment by huyphams** [comment]
Hi @BFJonk thank you for the feedback. How did you run the query script? You select all the text and press execute or select the run all query?
<img width="554" alt="Screen Shot 2019-10-28 at 12 31 27 PM" src="https://user-images.githubusercontent.com/3654622/67692417-de29fd00-f97e-11e9-8d4d-fcf8a024078d.png">

**Comment by BFJonk** [comment]
Thanks for looking into it.

You can close this one. I'm unable to reproduce it :-(

or you can keep it open to fix the remark on the AUTHORIZATION keyword.

**Comment by huyphams** [comment]
I will close it for now but if you encounter it in the future, please let me know then I will re-open it.
