### ISSUE TITLE
Truncated results PG12 when copying from varchar column in TablePlus (works correctly in pgAdmin 4)

### ISSUE THREAD

**Issue by ts1g** [TablePlus/TablePlus#1515]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PG 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 2.10.2 (272)

3. The steps to reproduce this issue: 
A. Create a varchar field
B. Create a new row
C. Paste content into field
D. Save record
E. Copy content from saved record's varchar column and paste into TextEdit.
F. Copy content from same record's varchar column via another PG 12 GUI (e.g., PG Admin 4) and paste into TextEdit
G. Compare character length of both TextEdit documents (see image examples, correct number should be 156902 characters, as shown in the first image, not the 31086 characters that TablePlus allows to be copied from the varchar field)

<img width="381" alt="2019-10-29 varchar output PGAdmin4 156902 characters" src="https://user-images.githubusercontent.com/55764215/67778165-2f96c280-fa39-11e9-859f-3882d171c4c1.png">

<img width="371" alt="2019-10-29 varchar output TablePlus 272 31086 characters of expected 156902 characters" src="https://user-images.githubusercontent.com/55764215/67778211-3e7d7500-fa39-11e9-87b1-9dad8dfe5180.png">

**Comment by huyphams** [comment]
Hi @ts1g anh chance that I could get an insert for this record?  You can send it via the email nick@tableplus.com thank you!

**Comment by ts1g** [comment]
Upon further research, it doesn't appear to be the text that I inserted. It's any texted beyond 32,000 characters. 

You can use https://www.blindtextgenerator.com/lorem-ipsum to generate dummy text up to 99,999 characters and past it into a varchar with the same results: TablePlus tops out at 32,000 characters exactly when I copy from the varchar field, while pgAdmin 4 copies the full 99,999 characters (see attached image).

<img width="739" alt="2019-10-29 varchar output TablePlus 32000 characters vs pgAdmin4 99999 characters" src="https://user-images.githubusercontent.com/55764215/67779942-c5cbe800-fa3b-11e9-9f7a-bf1d158cb3de.png">


The odd character count (31,086) on my original had more to do with TextEdit counting spaces oddly, so the 32,000 character hard limit from Table Plus using the dummy text generator noted above is a more accurate representation.

**Comment by huyphams** [comment]
Hmm, I think the issue is not that simple, I've tested and it can handle 99999 characters correctly with varchar field.
<img width="1598" alt="Screen Shot 2019-10-29 at 12 09 58 PM" src="https://user-images.githubusercontent.com/3654622/67780626-1f84e000-fa45-11e9-83cc-19661a8f6adc.png">

**Comment by huyphams** [comment]
oh, I figured out. You have to copy it in the quicklook!!! I don't know why Apple Cocoa limit 32,000 char in the field???

**Comment by ts1g** [comment]
Yes, it stores them all. That's not the issue. The issue is that copying from the field only brings out the first 32,000 characters

**Comment by ts1g** [comment]
> In the meantime, you can work around by using this feature:

Thanks, will use "Copy Cell Value" for the time being, but I suspect the average user will do what I did: double click the cell, choose command-C, and then command-V into an app. 

Do you mind sharing what apps you tested? I had tested in Numbers by pasting the same lorem ipsum into a field, then clicking out of the field, then selecting the field again (but not the text) and then did a command-C and command-V to paste it in to TextEdit. It carried all 99,999 characters without having to go through and "select all" the text.

**Comment by huyphams** [comment]
the Sequel Pro with LONGTEXT field.

**Comment by ts1g** [comment]
> I don't think that Apple uses their own cocoa text field for their app. it must be a private framework.

It's the Apple way ;-)

**Comment by huyphams** [comment]
I've addressed the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for letting me know.

**Comment by ts1g** [comment]
> Thank you for letting me know.

Works like a charm, thanks!
