### ISSUE TITLE
Feature Request: Beautify / Uglify just on selection

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1520]
Beautify works on the whole canvas. 

This is not handy. 

Please change beautify such that it only works on the selected text if there is text selected. 

Or make 'Beautify Current' an option

**Comment by huyphams** [comment]
I've improved it, you can download the patch here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!

**Comment by BFJonk** [comment]
Confirmed ! Thx.
