### ISSUE TITLE
CRASH on MAC at EDITOR

### ISSUE THREAD

**Issue by gfesj69** [TablePlus/TablePlus#1522]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    mysqld 5.6.45

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
     2.10.2 (272)

3. The steps to reproduce this issue:
    Just Editing, I attached a CRASH REPORT.
[Crash_TablePlus.log](https://github.com/TablePlus/TablePlus/files/3789249/Crash_TablePlus.log)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by SivolcC** [comment]
@huyphams I tried the build, bug is still present.
Sent you an email with the crash report.

**Comment by huyphams** [comment]
Hi @SivolcC , did you send the email? I don't see any email in my inbox. Thank you in advance.

**Comment by huyphams** [comment]
Hi guys, I've added an attempt to fix the issue (many thanks @SivolcC for the crash log and the step to reproduce the issue)
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by SivolcC** [comment]
Works for me now with this build.
Thumbs up for the quick response time.
