### ISSUE TITLE
feture request

### ISSUE THREAD

**Issue by PromiseNev** [TablePlus/TablePlus#1525]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
     mysql 5
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
      2.10.2(270)
3. The steps to reproduce this issue:

     could u add shortcuts when I often switch between table data   and   table structure views?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Please hover the mouse over the button you will see it @PromiseNev you can also change the shortcut in the preferences.

**Comment by huyphams** [comment]
<img width="322" alt="Screen Shot 2019-10-30 at 11 56 43 PM" src="https://user-images.githubusercontent.com/3654622/67915155-ee093300-fb70-11e9-9ba4-78423d63d160.png">

**Comment by PromiseNev** [comment]
i'm very thank u for my issues, but, how to change shortcut,  there no option  in the preferences ?

**Comment by huyphams** [comment]
Ah I'm sorry. I've added it, please wait for the next release.
<img width="899" alt="Screen Shot 2019-11-01 at 11 13 24 AM" src="https://user-images.githubusercontent.com/3654622/68030628-aaa9e400-fc98-11e9-94e1-beebc0f02da0.png">

**Comment by PromiseNev** [comment]
> Ah I'm sorry. I've added it, please wait for the next release.
> <img alt="Screen Shot 2019-11-01 at 11 13 24 AM" width="899" src="https://user-images.githubusercontent.com/3654622/68030628-aaa9e400-fc98-11e9-94e1-beebc0f02da0.png">

wow!!!  thanks!!!!
