### ISSUE TITLE
Connection window stays hidden on Mac Catalina

### ISSUE THREAD

**Issue by seslav** [TablePlus/TablePlus#1526]
Hi, 
Recently I updated to TablePlus 2.10.2 (272) and ever since I try to open a connection (tested with Cassandra & AWS Aurora) a new window is opened but it stays hidden. I can see it in Mission Control, but when I select it, it disappears again.
I'm on Mac OS Catalina 10.15.1 (19B88).
Thanks,

**Comment by huyphams** [comment]
Could you please check the keyboard if there was a jammed key or please try again after restarting the macOS. I couldn't reproduce the issue. Thank you!

**Comment by seslav** [comment]
Hi, 
There are no jammed keys. I did restart yesterrday, but no results.

**Comment by seslav** [comment]
I tried to reinstall, but still the same. Does anyone know how to reset all configs for TablePlus?

**Comment by huyphams** [comment]
Could you show me a gif @seslav you can post here or send me at nick@tableplus.com
(I'm using gifox, it's free and good).

**Comment by seslav** [comment]
![2019-10-31 16 48 40](https://user-images.githubusercontent.com/5594036/67957737-ba74ea00-fbfe-11e9-9b6d-39498a35e068.gif)
Thanks!! :) Here is the gif, let me know if you need more info
