### ISSUE TITLE
Feature request: Display PostGIS longitude/latitude coordinates

### ISSUE THREAD

**Issue by yagoferrer** [TablePlus/TablePlus#1527]
1. Use mdillon/postgis:11-alpine docker container
2. Create a table to store a LatLong field using the data_type geometry
3. Store a longitude / latitude coordinate 

Expected result: it should display current longitude / latitude stored.
Current result: it says field type: "unsupported" and shows an hexadecimal value

**Comment by huyphams** [comment]
Thanks @yagoferrer  I've added support Geometry data for PostgreSQL in this patch, if you have a chance, you can download it here: https://www.dropbox.com/s/lgh81iqa7x6i3hu/TablePlus.dmg?dl=0 if you hover the mouse on the cell value, TablePlus will draw it:
<img width="1251" alt="Screen Shot 2020-01-17 at 6 06 15 PM" src="https://user-images.githubusercontent.com/3654622/72649448-1c1e3800-3954-11ea-82dd-8a15544b2f57.png">

**Comment by yagoferrer** [comment]
Hi @huyphams,
thank you for working on this.  I have downloaded the build 286 and I still see an hexadecimal value. It would be nice if the field displays the latitude / longitude

**Comment by huyphams** [comment]
Could you show me the table creation @yagoferrer also please update the app to the latest release 290!

**Comment by yagoferrer** [comment]
Hi @huyphams, I downloaded the latest build 290 and I see the same behavior.
This is the table creation SQL
```sql
CREATE TABLE "customer_location" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(), 
    "latLong" geography(Point,4326) NOT NULL, 
   PRIMARY KEY ("id"))
```

**Comment by huyphams** [comment]
Thanks @yagoferrer I just added support geography. You can now view the data with this patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0

**Comment by yagoferrer** [comment]
Thank you @huyphams it looks great!
