### ISSUE TITLE
Remember last schema

### ISSUE THREAD

**Issue by bmichotte** [TablePlus/TablePlus#153]
When we open a postgresql database, `information_schema` is selected as default schema.
It would be awesome if TablePlus could remember the last selected schema and restore it when opening the database.

**Comment by huyphams** [comment]
TablePlus currently remembers the last schema. I just tested, which version are you on?

**Comment by bmichotte** [comment]
build 77

See 
![tp](https://user-images.githubusercontent.com/235510/34213548-c975269a-e59f-11e7-9437-fc2702004fd1.gif)

**Comment by huyphams** [comment]
Thanks, @bmichotte this helps me a lot to reproduce this bug.

**Comment by huyphams** [comment]
Hi @bmichotte 
I have changed a little bit hope this fix your problem.
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by bmichotte** [comment]
@huyphams yes, it does fix the _issue_. Thanks for your quick answer !

Strange thing, a schema `'` appears in the schema list and disappear the second time I open a database (and never appear again)
![tp](https://user-images.githubusercontent.com/235510/34226932-a5a4c42e-e5cb-11e7-9561-3c97cc0aae89.gif)

**Comment by huyphams** [comment]
Hi @bmichotte 
This is my typo, I fixed it after sent you the build 😄

**Comment by bmichotte** [comment]
awesome then, thanks again and keep up the good work :)
