### ISSUE TITLE
Beautify bug -- with comments & WITH statement

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1536]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
11.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
275

3. The steps to reproduce this issue:
when having a comment line ( -- comment) followed by a WITH line, the beautifyer will combine the lines 

thus : 

-- query xyz
WITH buckets as ()

Beautify results in : 

-- query xyz WITH buckets AS (
)

It should not. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by BFJonk** [comment]
ALTER TABLE has the same issue : 

--- comment 
ALTER TABLE table
Add column c text;

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
