### ISSUE TITLE
[Question] How to open MySQL Connection and Postgres Connection at same time?

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#154]
I can't seem to figure out how to have two different connections open at the same time? Anytime I try opening a new workspace, it automatically uses the connection i am already connected on. Sorry if this has already been asked and answered. Thanks for any help. :)

**Comment by huyphams** [comment]
You can press `command + N` to open main windows and then you can open another connection.

**Comment by mikebronner** [comment]
Thanks, that worked. :)
