### ISSUE TITLE
Copy rows as SQL insert statements does not conform postgress-SQL standard for quoted text

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1541]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgress 11.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
275

3. The steps to reproduce this issue:
1) select query in MySQL connection 
2) right mouse button,  -> Copy rows AS -> SQL insert statements (Mysql database)
3) switch to postgress connection 
4) paste

INSERT INTO `apprelation_partner` (`id`, `name`, `description`, `zipcode`, `housenumber`, `city`, `country`)
		VALUES('394829', 'a name', 'a descritpion', '2525WV', '412', '\'s-Gravenhage', 'Netherlands');

5) execute all - fail 

Postgress expects single quotes to be escaped with '  not with \

thus the following does work : 

INSERT INTO `apprelation_partner` (`id`, `name`, `description`, `zipcode`, `housenumber`, `city`, `country`)
		VALUES('394829', 'a name', 'a descritpion', '2525WV', '412', '''s-Gravenhage', 'Netherlands');
 
workaround is a global replace of \' with '' 

 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, @BFJonk I'm not sure that I understand it correctly. Are you trying to copy the insert statement from MySQL to PostgreSQL?

**Comment by BFJonk** [comment]
Hi Henry, yes I tried to copy the _data_ from MySQL to postgreSQL. I will try the  Command + C and the Command + V

**Comment by huyphams** [comment]
Yep thanks, because Copy As Insert statement does not work that way! So I'm closing this issue.
