### ISSUE TITLE
Feature request: "Lazy-load" large binary column data

### ISSUE THREAD

**Issue by ohens** [TablePlus/TablePlus#1542]
Hi,
I switched from SequelPro to TablePlus especially for stability reasons and love it. One feature I'm really missing and which makes me use both applications for now is display of large binary columns.

If you have a column (or multiple columns) with a BLOB datatype and large data in it, TablePlus tries to load all contents on selecting the corresponding table. Afterwards, it's possible to filter columns and not display those columns, but that's too late then, because TablePlus already tried to load e.g. 1000 rows with BLOBs of 1MB each... and canceling the request doesn't work most of the time for me.

So it would be great, if on large binary columns, those columns could optionally be filtered before loading the table or not loaded and presented with some placeholder like "<not loaded>" until one clicks on the row/cell/specific value. Of course only makes sense, if it's larger BLOBS and not just UUIDs or something else which fits in a single line...

I really like the last improvements on binary data (showing hex/actual content), by the way. Thanks.

**Comment by huyphams** [comment]
Thanks @ohens , it's duplicate with https://github.com/TablePlus/TablePlus/issues/1299 we will support this feature in the future updates.
