### ISSUE TITLE
Feature request: Execute statement

### ISSUE THREAD

**Issue by mlevtov** [TablePlus/TablePlus#1544]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):PostgreSQL 9.6.6
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 272
3. The steps to reproduce this issue: Execute a statement in within a larger script

It would be great if there was a hotkey to execute the statement the cursor is on, as opposed to the entire script or having to highlight the statement within the script. My default use case is to execute one statement at a time, but I don't have a separate script for each statement, so removing the need to highlight would be a huge time saver.

For reference, DBeaver has a good implementation of this feature.

**Comment by huyphams** [comment]
You can separate the statement by the `;` and TablePlus will only execute the current statement. The shortcut is command + Return or Command + E.

**Comment by gintechsystems** [comment]
@huyphams It would be great if we can get a list of all the shortcuts in TablePlus somewhere, maybe under preferences. The only place I could find them all was on an old blog post on TablePlus website.

It would also be great to change any shortcut. For example, I am coming from SequelPro so doing command + r makes the most sense to me. If this feature isn't on the list
