### ISSUE TITLE
Default Structure View"

### ISSUE THREAD

**Issue by jsonau** [TablePlus/TablePlus#1546]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**N/A**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**272**

3. The steps to reproduce this issue:
    1. Connect to a database with tables
    2. Select a table in the sidebar
    3. It will always show the "Data View" of the table

**Comment by huyphams** [comment]
Duplicate https://github.com/TablePlus/TablePlus/issues/1547
