### ISSUE TITLE
bug feedback:::::

### ISSUE THREAD

**Issue by PromiseNev** [TablePlus/TablePlus#1548]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql5
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.10.2(272)
3. The steps to reproduce this issue:
![2DC84A2C-7DF0-4D7A-A807-F5026BEA7AC6](https://user-images.githubusercontent.com/16667188/68442755-f286b900-020c-11ea-8848-61e42afd7ccd.png)

**Unable to display database connection information**

**Comment by huyphams** [comment]
Thanks @PromiseNev I've fixed it on this patch: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
it will be included in the next release.

**Comment by PromiseNev** [comment]
Great, it has been fixed  .thanks!!!!

**Comment by PromiseNev** [comment]
@huyphams   i install new dmg,  but my database's     Chinese characters were garbled

**Comment by huyphams** [comment]
Please change the encoding and it should work @PromiseNev 
<img width="850" alt="Screen Shot 2019-11-08 at 8 59 38 AM" src="https://user-images.githubusercontent.com/3654622/68478387-1b578000-0206-11ea-8248-1835f5118779.png">
