### ISSUE TITLE
Header blocks actions when opening too many databases

### ISSUE THREAD

**Issue by jelleroorda** [TablePlus/TablePlus#1549]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Irrelevant.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 272

3. The steps to reproduce this issue:
Open at least 13 databases, this will cause the header to suddenly overlap features like the button for opening connections, databases or new SQL tabs. It also partly overlaps the search input. See the screenshot below for a closer look of the broken interface. The issue doesn't get fixed by closing databases again, so there is no workaround as far as I can see.

![image](https://user-images.githubusercontent.com/9193686/68471084-bb6cd380-021d-11ea-9df8-7de6a392ac3a.png)

**Comment by huyphams** [comment]
Hi @jelleroorda I've fixed this issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you!
