### ISSUE TITLE
[Postgres BUG] Dropping Table With Referential Constraints Fails

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#155]
<img width="407" alt="screen shot 2017-12-21 at 8 55 21 am" src="https://user-images.githubusercontent.com/1791050/34266041-bbe5ac92-e62c-11e7-8609-2bfb4649a511.png">

It might be good to have an option to force drop by disabling referential integrity (Sequel Plus does this in MySQL, Postico also does this in Postgres). By default the DROP statement should probably include the CASCADE command. (I have established the foreign key constraints to CASCADE ON DELETE.)

**Comment by huyphams** [comment]
Hi @mikebronner, I have received some feedback about this. I think we can put a config in preference that you can stick allow TablePlus to add cascade when dropping a table.

**Comment by mikebronner** [comment]
Out of curiosity, does it break things if always included in the drop statement?

**Comment by huyphams** [comment]
It not about break things. It's about how people think TablePlus should work. For example, when you delete a table and TablePlus also delete some references rows (by adding Cascade). It's not an expectation (for some people). TablePlus does something people didn't aware, it's dangerous.

**Comment by mikebronner** [comment]
Sounds good. Looking forward to the next update. :)

**Comment by huyphams** [comment]
Sure, I'm thinking about the UX. It would be nice if we have a shortcut key. Add a new menu when right click and shift + delete as a shortcut.

**Comment by huyphams** [comment]
Hi @mikebronner 
Here is solution. You can also delete cascade by hold shift + delete button on keyboard:
<img width="477" alt="screen shot 2017-12-22 at 11 57 39 pm" src="https://user-images.githubusercontent.com/3654622/34306072-ee5961c6-e773-11e7-8d2d-31fcdf1dba94.png">
