### ISSUE TITLE
Windows Free Trial should allow two filters

### ISSUE THREAD

**Issue by johnbwoodruff** [TablePlus/TablePlus#1550]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.11.1 (96) - x64

3. The steps to reproduce this issue:
* Download the windows build of TablePlus & install
* Connect to a datasource and pull up a table
* Attempt to use a filter (for example, paste an ID to filter by)
* Notice the following error message:

"You cannot use the advanced filter on the Free Trial. Do you want to buy a license to unlock it?"

According to your website, you can do up to two advanced filters on free trial. This currently works fine on the Mac version. (which I also tested on the same db in the same conditions) If this is intended, it should at least state on the website that this is only available on the Mac version, although I believe it should be supported on both.

![image](https://user-images.githubusercontent.com/5883616/68516643-d2252180-0241-11ea-82e4-1388be45e9de.png)

**Comment by huyphams** [comment]
Thanks @johnbwoodruff the Windows version was born after the macOS and also the Website, we didn't update the website since then.
We will update it in the upcoming version of the website.

TablePlus Windows/macOS/iOS have different limitations and we also change it a couple of times (when introduce new premium features or update the limitation numbers...).

**Comment by johnbwoodruff** [comment]
So if I understand correctly the windows version intentionally doesn’t allow filters without the premium version?

**Comment by huyphams** [comment]
Yep, that's true but it allows 3 tabs (macOS only 2 tabs).

**Comment by johnbwoodruff** [comment]
Sounds good, thanks for the clarification! 👍
