### ISSUE TITLE
Import/Export Error on Line 1 Error and Solution

### ISSUE THREAD

**Issue by sjamesmccarthy** [TablePlus/TablePlus#1551]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 277

3. The steps to reproduce this issue:
Select a table and right-click "export"
Choose SQL
Check all BUT gzip

open connection to other mysql server of same version 5.x
click FILE > Import > SQL dump file
at preview screen of SQL, click "Continue"
errors out at "Line 1"

Fix:
open .sql file in vs code or editor and remove all commented lines.
save the file
and import again - success.

Mac OS Catalina 10.15.2b1

Noted: If the bug is related to data, please attach an example SQL data.

-- -------------------------------------------------------------
-- TablePlus 2.11(277)
--
-- https://tableplus.com/
--
-- Database: mydatabasename
-- Generation Time: 2019-11-10 10:52:19.6480
-- -------------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES  */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

**Comment by sjamesmccarthy** [comment]
I rolled back to build 276 and didn't have any issues.

**Comment by huyphams** [comment]
Thanks @sjamesmccarthy I couldn't reproduce it on the newest beta (https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0) it would be great if you can also give it a try

**Comment by sjamesmccarthy** [comment]
It still said Build 277 but the file I downloaded from Dropbox appeared to fix the issue. Thanks!

Cheers, James




jM Galleries
7582 Las Vegas Blvd. S
Las Vegas, NV 89123

951-708-1831
Social Channels @jmgalleriesusa
