### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by SunyWait** [TablePlus/TablePlus#1554]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
oracle11g
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.11（276）
3. The steps to reproduce this issue:
查询结果中文乱码
Noted: If the bug is related to data, please attach
![IMG_3808](https://user-images.githubusercontent.com/24806537/68592228-7d95d680-04cd-11ea-8961-e8d7cd661d23.JPG)
 an example SQL data.
select* from [sys_menu[]

**Comment by huyphams** [comment]
Hi @SunyWait please change the encoding
<img width="850" alt="Screen Shot 2019-11-11 at 9 52 59 AM" src="https://user-images.githubusercontent.com/3654622/68592298-16463b00-0469-11ea-9ac7-f653e2b6ce85.png">

Or download this build:  https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by marocchino** [comment]
I have a similar problem with this.
I tried changing the encoding, but I only see Russian and English on the list. Is there a way to add Japanese here?

<img width="433" alt="Screen Shot 2019-11-12 at 8 21 57" src="https://user-images.githubusercontent.com/128431/68628981-86b29200-0525-11ea-9f72-ff3910b6a48e.png">

**Comment by huyphams** [comment]
You can use the American @marocchino it should work the same as Japanese.

**Comment by marocchino** [comment]
Oh, my problem seems to be solved. Thank you for answer.

**Comment by SunyWait** [comment]
谢谢
