### ISSUE TITLE
setapp下载的tableplus 无法连接oracle 

### ISSUE THREAD

**Issue by SunyWait** [TablePlus/TablePlus#1556]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
oracle11g
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
276
3. The steps to reproduce this issue:
![7D2BA40D41563E794C4D8D1E6161D93A](https://user-images.githubusercontent.com/24806537/68633302-5c180780-052c-11ea-99cb-cf6e0cf9cdad.jpg)
![4CC60687-0EB0-4949-8E1D-DD1A7C1D4CAA](https://user-images.githubusercontent.com/24806537/68633304-5cb09e00-052c-11ea-9ee2-29aa1fc63ad0.png)

无法连接oracle
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @SunyWait I think I uploaded the wrong set app build, Let me submit again.

**Comment by huyphams** [comment]
I've updated the build, it will be available within 24h.
