### ISSUE TITLE
Can't create table in MySQL Workspace

### ISSUE THREAD

**Issue by davidshimjs** [TablePlus/TablePlus#1557]
1. Which driver are you using and version of it
MySQL 8

2. Which TablePlus build number are you using
Mac OS X Catalina 10.15.1 - TablePlus 2.11 (276)

3. The steps to reproduce this issue:
New Table -> Suddenly closed a window when I have edited something. It occurs frequently. You can check out it below link. (mov)
https://drive.google.com/file/d/1JOdhVycRGXfyMWTKbAXg2aXmzF4MCP25/view?usp=sharing

**Comment by huyphams** [comment]
Hi @davidshimjs could you please try again with the build 278, thanks!

**Comment by davidshimjs** [comment]
@huyphams No changes on 278 build.

**Comment by davidshimjs** [comment]
@huyphams You can reproduce this situation with `wait_timeout = 10` setting. It'll be closed very quickly.

**Comment by davidshimjs** [comment]
@huyphams You can workaround this with uncheck Keep connection alive. but you'll see many alert dialog "MySQL Server has gone"

**Comment by davidshimjs** [comment]
It's a very critial issue. This issue occurs not only when I create table but also adding/editing rows.

**Comment by huyphams** [comment]
Hi @davidshimjs I'm sorry about the issue. The root cause of this issue it the connection was disconnected repeatedly.
Are you using MySQL 8 or MySQL 5 driver?
<img width="539" alt="Screen Shot 2019-11-13 at 5 58 50 PM" src="https://user-images.githubusercontent.com/3654622/68807992-421b1980-063f-11ea-884d-9fe4c6fe2bba.png">

**Comment by davidshimjs** [comment]
As I mentioned, MySQL 8 driver

**Comment by huyphams** [comment]
Hi @davidshimjs I'm sorry because of the delay (due to different timezone). I've sent you an email with a hotfix build. Thanks!
