### ISSUE TITLE
Bug: predictive table name does not work correct

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1559]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgress 11.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 279

3. The steps to reproduce this issue:
1) first type a schema-name and a dot, then the first characters of the table-name (see figure): 
<img width="479" alt="afbeelding" src="https://user-images.githubusercontent.com/24241551/68802565-6f2af480-065e-11ea-9509-55324127049c.png">
2) select the tablename. tableplus will now put the schema-name in twice : 
<img width="361" alt="afbeelding" src="https://user-images.githubusercontent.com/24241551/68802627-8f5ab380-065e-11ea-94cb-69defd9bf2d2.png">

**Comment by huyphams** [comment]
Did you enable the prefix schema @BFJonk?
If yes, it's a bug, I'm fixing it now.
<img width="648" alt="Screen Shot 2019-11-13 at 4 45 01 PM" src="https://user-images.githubusercontent.com/3654622/68802785-f3688200-0634-11ea-8a8c-e24295bfd555.png">

**Comment by BFJonk** [comment]
Hi Henry, yes I did:
<img width="797" alt="afbeelding" src="https://user-images.githubusercontent.com/24241551/68807635-78b95a00-0668-11ea-9892-a8d208e23d26.png">

**Comment by huyphams** [comment]
I fixed this issue, you can download the hot patch here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks @BFJonk
