### ISSUE TITLE
ALTER TABLE beautify is strange

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1560]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
11.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
279

3. The steps to reproduce this issue:
1) sample SQL 

```
ALTER TABLE table
Add column c text
add column d text;
```

2) Beautify 
3) Result

```
ALTER TABLE TABLE
	ADD COLUMN c text
		ADD COLUMN d text;
```

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
