### ISSUE TITLE
Feature Request: Filter out functions

### ISSUE THREAD

**Issue by CannopyJeffWei** [TablePlus/TablePlus#1566]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6 and  mdillon/postgis:9.6 docker container
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 270

Using Postgis populates an additional functions folder in the left submenu and also adds all functions to the search function (CMD+p). These are not things I'd ever use through my DB browser and just adds clutters both the search and the sidebar. Can we filter them out somehow? Or at the very least order the function folder and search results to be last?

**Comment by huyphams** [comment]
Currently, you can turn off the function section, it also filters out the functions from open anything (command + P). It requires closing and reopening the workspace, the downside is you also filter out your defined function as well.
<img width="669" alt="Screen Shot 2019-11-18 at 12 41 09 PM" src="https://user-images.githubusercontent.com/3654622/69071695-b7e90180-0a00-11ea-9cc0-a87dd1284953.png">

**Comment by CannopyJeffWei** [comment]
Thanks! Thats exactly what I'm looking for!
