### ISSUE TITLE
Feature Request: Better Importing

### ISSUE THREAD

**Issue by billriess** [TablePlus/TablePlus#1569]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
278

---

It would be nice to have a more rich import experience, similar to Sequel Pro. Currently, there is no way to do an import and update records. Also, there is no option to set additional fields not included in the csv. When adding additional fields it should allow things like "NOW()" and "NULL" for setting columns to the proper values.

**Comment by huyphams** [comment]
Hi @billriess it was planned in the November update: https://twitter.com/TablePlus/status/1194265748899868672
It's also duplicated with: https://github.com/TablePlus/TablePlus/issues/1553
and https://github.com/TablePlus/TablePlus/issues/1088

**Comment by billriess** [comment]
Sorry for the duplicate, I'll remove it.

Also, why is it every time I put a feature request in you guys already have the feature complete and near release? I'll have to follow the project on Twitter. Thanks!

**Comment by huyphams** [comment]
I could not make it in the next update 282, because it's complicated than I expected so this feature will be delayed to December (this year) or January release (next year.)
