### ISSUE TITLE
[Build 78] Bug reports

### ISSUE THREAD

**Issue by horo42** [TablePlus/TablePlus#157]
When I open a table and Alt + Click into a field and select "Manual Input..." the right side "Row detail" (which opens with the space key) opens, but the icon for it stays inactive. Minor visual bug.

When adding an index to a table, the "index_name", "index_algorithm" and "is_unique" values have a "DEFAULT" placeholder, but I need to fill out every single field for it to appear in the "Preview", and likewise if I try commiting, the index doesn't get created.

Creating a new workspace is wonky, the animations are off and sometimes it resizes the main window.

Right clicking on a table and selecting "Export..." and exporting to SQL works alright, but the export doesn't include a CREATE TABLE statement, and the INSERT INTO statement includes the database name as well, which should at least be a toggleable option, because most of the time the database I'm importing into has a different name.

Thanks for this fantastic app, I love it and use it every day, and hope to see it succeed 👍

**Comment by huyphams** [comment]
Hi @horo42, I'm glad that you like my app. Thanks for your all feedbacks. I'm working on build 79 and definitely will include your bug fixes. 😸 
"INSERT INTO statement includes the database name as well, which should at least be a toggleable option" => Nice idea 👍
