### ISSUE TITLE
Copy Rows as CSV include field names

### ISSUE THREAD

**Issue by kralcifer** [TablePlus/TablePlus#1570]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 

I'm on MacOS, using Postgres 11.5, not sure where to see what driver.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

278 but the change has been for a few builds.

3. The steps to reproduce this issue:

Copying results used to look much better, to me at least.  I see you are using 0x09 tab between columns and 0x0A for end of line.

My complaint is that it is putting end of line WAAAY too short, i.e. column 37.  This must be a bug.

Noted: If the bug is related to data, please attach an example SQL data.

name	description	success	created_at
update advertiser		t	2019-11-20 22:56:39.559397
new billing period	[2019-10-25 15:00:00,2019-11-25 15:00:00)	t	2019-11-20 23:02:04.326945

![image](https://user-images.githubusercontent.com/24683739/69362131-c6266000-0c42-11ea-84b4-61d20f16557d.png)

**Comment by huyphams** [comment]
Hey @kralcifer there is CSV default option in the preferences, you please take a look and see how's it going?
<img width="921" alt="abc" src="https://user-images.githubusercontent.com/3654622/69364095-0b10bd80-0c68-11ea-83b7-9e8f1da4eab8.png">

**Comment by kralcifer** [comment]
much better.  thanks!

**Comment by kralcifer** [comment]
not really CSV as in "**COMMA** separated value" if TAB is the default though

**Comment by huyphams** [comment]
Yeah, actually it was TSV.
