### ISSUE TITLE
 a way to quickly edit in  a large screen the jsonB?

### ISSUE THREAD

**Issue by simkimsia** [TablePlus/TablePlus#1573]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
278

3. The steps to reproduce this issue:
not a bug but a question

related to #1558

Is there a way to quickly edit in  a large screen the jsonB?

there's something similar in SEQUEL pro for TEXT field

**Comment by huyphams** [comment]
You can edit it quickly with the right sidebar (it will show raw value and you can also pretty the json with it)

**Comment by simkimsia** [comment]
Copy that thanks for the swift reply! 👍
