### ISSUE TITLE
how to toggle to backup view when inside the editor view for the database?

### ISSUE THREAD

**Issue by simkimsia** [TablePlus/TablePlus#1574]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgres 10.3
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.11.2 build278

3. The steps to reproduce this issue:
question not bug

how to toggle to backup view when inside the editor view for the database?

i always end up quitting all the window view when I have to run backup. Which I hate to do so because i can have work done halfway in my window but the backup was urgent

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's right on the menu 
<img width="501" alt="Screen Shot 2019-11-26 at 12 24 57 AM" src="https://user-images.githubusercontent.com/3654622/69599391-3803fe00-0fe3-11ea-82b5-87f95ad4eb05.png">
Small tip:
You can search for the menu on all macOS app:
<img width="657" alt="Screen Shot 2019-11-26 at 12 25 04 AM" src="https://user-images.githubusercontent.com/3654622/69599403-418d6600-0fe3-11ea-9731-01be54a6c166.png">

If you have any question, feel free to email us at nick@tableplus.com or search on the documents: https://docs.tableplus.com/
Thanks!

**Comment by simkimsia** [comment]
Thanks! I feel silly for asking in the first place :(
