### ISSUE TITLE
[Bug] App crashes when scrolling through long table list on Windows version

### ISSUE THREAD

**Issue by TheMisir** [TablePlus/TablePlus#1575]
When I scroll down on the table list the app crashes.

**Comment by huyphams** [comment]
Thanks @TheMisir, Can you try this patch and see how's it going? https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0

The issue tracker of Windows version is here, so I'm closing this one: https://github.com/TablePlus/TablePlus-Windows/issues
