### ISSUE TITLE
Feature request: Use OR to join columns when filtering instead of AND

### ISSUE THREAD

**Issue by joseramonc** [TablePlus/TablePlus#1577]
Hey! First of all, this app is superb. Great work!

It would be nice if when filtering, be able to set a setting for the filter, to use OR operator when joining columns instead of AND operator.

It currently generates this:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1993929/69668310-3d019580-1055-11ea-915b-17b422a4413c.png">
```
SELECT * FROM `msbcorpo_website`.`procedures` WHERE (`completed_at` IS NOT NULL) AND (`email_sent_to` IS NOT NULL) AND (`sms_sent_to` IS NOT NULL) ORDER BY `id` LIMIT 300 OFFSET 0;
```

And I'd like to use OR instead of AND, and generate this:
```
SELECT * FROM `msbcorpo_website`.`procedures` WHERE (`completed_at` IS NOT NULL) OR (`email_sent_to` IS NOT NULL) OR (`sms_sent_to` IS NOT NULL) ORDER BY `id` LIMIT 300 OFFSET 0;
```

Not sure if it would be a cool addition for the app. But would love to use this.

Thanks!

**Comment by huyphams** [comment]
It's possible now.
<img width="561" alt="Screen Shot 2020-09-27 at 5 10 34 PM" src="https://user-images.githubusercontent.com/3654622/94362266-5e536800-00e4-11eb-9116-c14d9b506f0a.png">
