### ISSUE TITLE
Feature Request: Spotlight search keyboard shortcut

### ISSUE THREAD

**Issue by jordharris** [TablePlus/TablePlus#1578]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.5.33
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.11.2 (278)
3. The steps to reproduce this issue:
N/A
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by jonopeo** [comment]
Yeah this would be great to see in the current or upcoming rework 👍 !

**Comment by huyphams** [comment]
Hi @jordharris I'm not sure that I understand this request correctly, could you explain it? Thanks

**Comment by jordharris** [comment]
Found it cheers
