### ISSUE TITLE
Process List window frozen bug

### ISSUE THREAD

**Issue by georgexsh** [TablePlus/TablePlus#1579]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
278

3. The steps to reproduce this issue:

press <kbd>cmd+.</kbd> to call out process list window, repeat sometimes, randomly, the whole window became frozen, no-place is clickable.

![image](https://user-images.githubusercontent.com/32751/69716299-b88e4000-1144-11ea-89f9-9a1524031851.png)

aside from this bug, I also have a feature request, able to view and kill processes is great, but I want to see the full SQL easier, I have to copy out SQL from `info` column, paste to a text editor to view the full content.

**Comment by huyphams** [comment]
I'm not sure what was the cause, I've added an attempt to fix it base on this issue: https://github.com/TablePlus/TablePlus/issues/1561
Let me know if you're still seeing the issue.
