### ISSUE TITLE
[Feature Request] - Export multiple tables with option to toggle Structure & Data

### ISSUE THREAD

**Issue by horo42** [TablePlus/TablePlus#158]
## Export feature request

It would be a nice feature to be able to export multiple tables like in PhpMyAdmin (or other DB management apps). 

<img width="494" alt="PhpMyAdmin multi table export" src="https://user-images.githubusercontent.com/5323731/34319961-0a8ad6d8-e7ef-11e7-9544-bf3e1db93a1c.png">

The first step would be selecting multiple tables with Shift/Cmd + Click, right clicking, then selecting "Export...".

<img width="329" alt="Exporting multiple tables in TablePlus" src="https://user-images.githubusercontent.com/5323731/34319998-7fd61a9c-e7ef-11e7-9b12-2ad64f3b6363.png">

The export modal would change when more than 1 table is being exported and the SQL option selected. In this case the "Select field to export" and "Export where" fields could be removed, the "TablePlus will export data as Insert command" grey section with the segment controls could expand, filling the whole space of the modal, and a scrollable table could appear in place of the "TablePlus will export data as Insert command" text, similar to what PhpMyAdmin has, with select boxes for Structure and Data options.

<img width="379" alt="TablePlus UI modification recommendation" src="https://user-images.githubusercontent.com/5323731/34320003-8fbfde7a-e7ef-11e7-9dbf-9337279ff663.png">

There are many possible implementations to this, but I definitely think this would be a more than welcome addition to the Export workflow.

In the top menubar under File there is an "Export data..." menu item, which is inactive when no database and table is opened. It could default to exporting the whole database in SQL format (since CSV and JSON don't make sense in this case), and all the tables would appear in the list.

## Toggle database name in INSERT INTO statements in SQL exports

Pulled from issue #157 

The INSERT INTO statements include the database name as well, which should at least be a toggleable option, because most of the time the database I'm importing into has a different name.

**Comment by joshbrw** [comment]
I really need this feature to be able to use TablePlus as my primary database management tool. In Sequel Pro you can export as SQL Dump, CSV and XLSX. In the SQL Dump you can include:

* Structure
    * Auto Increment value
    * DROP TABLE syntax
* Content
* Errors

If this could be emulated, that'd be fantastic!

**Comment by keithslater** [comment]
Looking forward to this feature being added

**Comment by rizkysyazuli** [comment]
i'm with @joshbrw +1

**Comment by onebrightlight** [comment]
I bought a license immediately from y'all because I love how this tool looks, knowing it would be feature-incomplete initially. I really enjoy using it to modify and work with dbs, but not being able to dump the entire db to backup or what have you is a huge issue at times and I find myself resorting to Sequel Pro. This feature would mean I could practically stay in TablePlus all the time!

**Comment by khoatrangeek** [comment]
This one missing feature is the only reason I still have to use Sequel Pro in these days. So much love if TablePlus can support this sooner.

**Comment by mikerogne** [comment]
Are there any plans to implement this? I was a little sad to realize this feature didn't exist when I needed it just now haha!

**Comment by huyphams** [comment]
We just put it on our roadmap, will be available in some next updates.

**Comment by onebrightlight** [comment]
Hey @huyphams I'm looking for this feature in the [roadmap](https://github.com/TablePlus/TablePlus/projects/1) and don't see it as any of the cards. Still waiting to get the feature and I know these things can take time. I'd just like to know where it sits, currently, before I end up buying a license to Navicat.

**Comment by huyphams** [comment]
The priority is:
1. Done encode and collation.
2. Full Import/export.
3. User management.

Currently, I'm working on that features.

Btw, all these features take time so please do take it as a deal breaker.

**Comment by onebrightlight** [comment]
Oh absolutely! I don't expect you to prioritize it, I just wanted to make sure it's not somewhere I didn't notice in the roadmap. I really like the tool, and l'm happy to wait and see what happens with it! Thanks for the quick response, regardless.

**Comment by huyphams** [comment]
Hey guys, please check out this issue: https://github.com/TablePlus/TablePlus/issues/418
