### ISSUE TITLE
Redis Driver

### ISSUE THREAD

**Issue by mobility2u** [TablePlus/TablePlus#1580]
This feature is not available for this driver.
Redis Version 3.2.12

TablePlus 2.11.2 (278)

<img width="1118" alt="Screen Shot 2562-11-28 at 10 41 52" src="https://user-images.githubusercontent.com/46254888/69775637-e8ccf180-11cb-11ea-8f67-e5b2d930d2ce.png">

**Comment by karbica** [comment]
I too am getting the same. This happens when I click the `+` button hoping to add a new DB to Redis. Here is the dump of the Redis server running in Docker.

```
127.0.0.1:6379> info
# Server
redis_version:5.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:5f6bfe2b13cc4617
redis_mode:standalone
os:Linux 4.19.76-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:c852cf6127ac3f067777f02792d347a9946b9f2f
tcp_port:6379
uptime_in_seconds:5897
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:4394376
executable:/data/redis-server
config_file:
```

**Comment by pauline-finnovate** [comment]
Did we figure out why? I am experiencing this as well.

**Comment by chensoul** [comment]
<img width="542" alt="image" src="https://github.com/TablePlus/TablePlus/assets/826932/a9a2f826-d511-44a3-aee7-a2a46c36a1c4">

Version 5.4.0 (505)

**Comment by vincentatherlabs** [comment]
Pump, anyone figured out?

**Comment by chensoul** [comment]
> <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/826932/265577829-a9a2f826-d511-44a3-aee7-a2a46c36a1c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjQ5NTMsIm5iZiI6MTcwMzY2NDY1MywicGF0aCI6Ii84MjY5MzIvMjY1NTc3ODI5LWE5YTJmODI2LWQ1MTEtNDRhMy1hZWU3LWEyYTQ2YzM2YTFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwODEwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzE4ZWI2ZWZkMTM0MWI1NjdlYjNmYmE1MWViM2M0NzE2OGEwNjU1ZDdiNjgwM2E5YmNiOTIwODc0MzU0ZDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p2BUNG7kwHG0-Y8gPfZLXL5RK1tN0DjwD89bDKaR25I">
> Version 5.4.0 (505)

Version 5.6.8 (524)，it still happens，how to solve it？

**Comment by huyphams** [comment]
I think we have a misunderstanding here, we do not need to create redis database. Just select it and then set value for a key.

**Comment by huyphams** [comment]
For more info.
If you want to create a new key in a database. Just run
set key_name key_value

if you want to create it on db_index, run
select index
set key_name key_value

They're all redis commands. you can find it in redis documents.
