### ISSUE TITLE
Cannot Split SQL Pane Horizontally

### ISSUE THREAD

**Issue by jjohnson1994** [TablePlus/TablePlus#1582]
1. PostgreSQL 12

2. 2.11.2

3.1 Connect to DB
3.2 Click 'Open SQL Query'
3.3 Right-click and select 'Split pane horizontally'

The pane doesn't split, instead any formatting is removed and the query is put onto one line. Using the keyboard short cut does still split the pane.

**Comment by huyphams** [comment]
Hi, @jjohnson1994 it's fixed in the beta channel.
If you're using the stable build, You can split the pane horizontally by pressing command + shift + D or using the main menu: Navigate > Split pane horizontally
