### ISSUE TITLE
[Build 78] Plugin API bug report

### ISSUE THREAD

**Issue by horo42** [TablePlus/TablePlus#159]
The context.execute() function returns empty objects as rows for every SELECT query with MySQL/MariaDB engine.

Tested code:
```
context.execute('SELECT arHandle FROM Areas', (result) => {
    context.alert(pluginName, JSON.stringify(result));
});
```

<img width="413" alt="The alert after the query finishes" src="https://user-images.githubusercontent.com/5323731/34340554-678679da-e986-11e7-8381-9f479f674d28.png">

**Comment by huyphams** [comment]
Hi @horo42 

Plugin feature is under development and not released yet, the API may be changed without any warnings. I'm still researching and considering infrastructure for the plugin system.

Thanks for your attention, I will keep you posted.

Huy.

**Comment by huyphams** [comment]
Btw, a row is an export object and didn't have a public attribute. so the JSON.stringify(row) will result {}. You can access to row data by export functions:
```
 // Get raw data
  func raw(_ name: String) -> String?

  // Get edited value
  func editedRaw(_ name: String) -> String?

  // Get last value
  func lastValue(_ name: String) -> String?

  // is field modified
  func isModified(_ name: String) -> Int

  // update field
  func update(_ name: String, _ value: String?)

  // set default for field
  func setConstant(_ name: String, _ constant: String)
```
