### ISSUE TITLE
sql beautifier not working when there's a comment starting with "--"

### ISSUE THREAD

**Issue by Liooo** [TablePlus/TablePlus#1592]
sql beautifier (`CMD+i` in OSX) doesn't work is in the situation.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version2.12 (280)

3. The steps to reproduce this issue:

```
# comment
select * from tables;
```
=> works

```
#-comment
select * from tables;
```
=> works

```
#--comment
select * from tables;
```
=> doesn't work

```
#---comment
select * from tables;
```
=> doesn't work

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
