### ISSUE TITLE
[Feature Request] Deep-link / custom URL scheme to open table/record

### ISSUE THREAD

**Issue by nullthoughts** [TablePlus/TablePlus#1593]
I think a handy feature for development environments would be the ability to create deep-links which open TablePlus to either a specific table, or specific row through a query.

For example, if you were building out an e-commerce website and wanted to be able to view the actual record in the database for a product: the developer could insert debug links in their development environment using the TablePlus custom URL scheme (for macOS): tableplus://connect/{connection_name}/{db}/{table}/?id={id}

Git Tower also provides this type of functionality: https://www.git-tower.com/help/mac/integration/url-scheme

I did search to see if anyone else had requested this, but came up empty handed.

**Comment by rtuin** [comment]
This would definitely be helpful and increase productivity! +1

**Comment by agu-z** [comment]
I'd love for this feature to exist!

**Comment by adriaanvanrossum** [comment]
This would be great. To explain our use case: we have an admin dashboard for our customers. We sometimes need to update something directly in the database. It would be amazing if we could trigger a certain query with the deep link. Something like this would be great:

```
tableplus://query?connection-name=Server%20Main&query=SELECT%20*%20FROM%20users%20WHERE%20uuid%20%3D%20'a4c838a0-ee2b-4efb-b60a-7fb0ee259d13'
```

Where the query is something like:

```sql
SELECT * FROM users WHERE uuid = 'a4c838a0-ee2b-4efb-b60a-7fb0ee259d13'
```

Maybe restrict to SELECT only to prevent data loss for funky apps that link to a `DELETE * FROM xxx;`

**Comment by DanielFatkic** [comment]
I have to bring this back to the top of the recent suggestions:)

+1 for this

**Comment by vesper8** [comment]
I am actually so sad to realize this feature doesn't exist yet... it would be so useful! Is there no workaround at all?

Will you please add it @huyphams ?

**Comment by jtomek** [comment]
This would be so useful. 

Only having the possibility to link to open would increase my productivity by 10 seconds, and I do these very often.

My current workflow:
Copy db name, open tableplus, find connect, enter, CMD+K, paste db name, enter, CMD+K, enter table name.

P.S. the shortcut to find a connection is different. Maybe you could align the search with the CMD+K experience.
P.S. 2 CMD+P doesnt always display the latest databases. I always need to restart the conenction. CMD+K is reliable.

**Comment by huyphams** [comment]
The next update will support this. The params will be:

- schema: the schema name, or database name (databases that don't have schema).
- name: the table name, view name
- column: the column name for filter
- operation: the operator, example <, >, =, <>, Contains...
- value: the value of the column

for example:

&schema=public&name=comments&column=content&operation=contains&value=test

**Comment by jtomek** [comment]
Amazing work, thank you! What format did you end up using? 

I am trying to piece it together, but cannot make it work. None of these work, it shows the "Invalid URL" error. 

tableplus://query?connection-name=My DB&schema=public&name=jobs&column=id&operation=contains&value=1
tableplus://query?connection-name=My DB&schema=public&name=jobs&raw=id%3D29%20OR%20id%20%3D%2028

Can you please help?

**Comment by huyphams** [comment]
Hi, please change the name to table/view

**Comment by jtomek** [comment]
**Connection name: abcdef**

<img width="202" alt="image" src="https://github.com/user-attachments/assets/a9071847-67a7-43a7-a350-1183b86b8ed0">

**Table: domains**

<img width="823" alt="image" src="https://github.com/user-attachments/assets/2327cacd-e845-4c62-bda7-15925cc482e7">

**URL:** 

tableplus://query?connection-name=abcdef&schema=public&table=domains&raw=id%3D29%20OR%20id%20%3D%2028

**Error:** 
<img width="258" alt="image" src="https://github.com/user-attachments/assets/6f6952fd-f8fa-4a11-b963-2cd6e8341eec">

**Comment by huyphams** [comment]
Hi @jtomek there is no such params `connection-name` If you choose the existing, you should use the connection id (but this is not documented). You can see the docs here https://docs.tableplus.com/gui-tools/manage-connections

**Comment by souterjk** [comment]
@huyphams Can you provide a fully working example here, or in the documentation somewhere? The product announcement for this feature on twitter just links to this github issue, but there still isn't a good example of how to use it. 

This comment (from above)https://github.com/TablePlus/TablePlus/issues/1593#issuecomment-2338179561 shows that there are query parameters, but what URL are you applying those query parameters to? A full URL example of using this would be super helpful.

**Comment by jtomek** [comment]
@vesper8 is your decision to re-subscribe depends on these features or why do you mention it?
The tool offers enormous value and it worth supporting. The developers have been very helpful over the years.

It feels unnecessary and somewhat blackmaily to me. 

Regarding your points, if you would have a look at the documentation (https://docs.tableplus.com/gui-tools/manage-connections#open-connection-from-terminal), you would know that it is possible to:

- open a remote DB, 
- open a table, 
- sort columns 
- fitler stuff.

The only limitation I see that it is not possible to open it in tabs but windows. But you can open 4 new windows and switch between them, as you would like with tabs.

I hope this help. Just read the docs, it's all described there in detail. ;)
