### ISSUE TITLE
Window jumps when openning a connection

### ISSUE THREAD

**Issue by filipac** [TablePlus/TablePlus#1594]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql, postgresql and sqlite
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
284
3. The steps to reproduce this issue:
Open a wimdow and center it to the screen for example. Then, double click a connection in order to connect. The loading screen appears BUT the window is moved randomly on the screen or another external monitor on the right/ I have to drag the window again back to where I had it first.

Sometimes it jumps to where it was before closing, sometimes it jumps very very random and I almost can't find it (in the lower left corner and i barely can drag it back for example).

I believe it gets messed up then an external monitor is unplugged and plugged again, that's when it jumps in crazy locations.

https://youtu.be/2voykw8C1Jg

**Comment by huyphams** [comment]
Hey, @filipac that was expected behavior. they're two different windows. We're working on the TablePlus 3.0 and we will merge those two Windows into one window (If you're using Linux, TablePlus Linux has the design of TablePlus 3.0).

**Comment by mchristie** [comment]
I'm currently running 3.1.2 on macOS 10.15.3 and I regular experience this random window position behaviour.
I've had the window open almost full screen, barely onscreen, just the top onscreen but hidden under the dock... places I'd definitely never drag the window to so it's not just remember the last-opened position.

**Comment by huyphams** [comment]
Hi @mchristie This build should fix the issue https://www.dropbox.com/s/wy9l92h844lcef6/TablePlus.dmg?dl=0

**Comment by filipac** [comment]
@huyphams it is fixed but build# is older than latest available, is this tight? (your dmg above is build 336, latest is 339(

**Comment by huyphams** [comment]
The 399 is beta build, the 336 is the official build.
