### ISSUE TITLE
please encoding shift-jis

### ISSUE THREAD

**Issue by eyemovic-goda** [TablePlus/TablePlus#1596]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
AWS RDS Oracle 11g

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
284

Thank you as always!

please encoding shift-jis

**Comment by huyphams** [comment]
Hey, @eyemovic-goda have you tried the encoding `American_America.UTF8` I think it would still work with other Unicode base encodings.

**Comment by eyemovic-goda** [comment]
Hey,@huyphams
thank you !
Worked in my environment!
