### ISSUE TITLE
Unknown column in query as table

### ISSUE THREAD

**Issue by Peckerd** [TablePlus/TablePlus#160]
Hi,

When running this query, I get an error 'unknown column email in 'field list'.
```SQL
SELECT cc.*
from contacts cc
left join (
              select email, count(*)
              from contacts
              where deleted = 0 and email <> ''
              group by email
              having count(*) > 1
            ) cc2
    on cc.email = cc2.email
  inner join companies c
    on c.id = cc.company_id
where cc.deleted = 0
ORDER BY
  cc.email;
```
This doesn't give an error in other applications, so my syntax should be correct.

**Comment by huyphams** [comment]
Hi just tested and it works
<img width="1269" alt="screen shot 2017-12-26 at 10 41 42 am" src="https://user-images.githubusercontent.com/3654622/34346363-69425d04-ea29-11e7-87dd-483556dbde6d.png">
I think this issue related with your database (probably you select a different database in PHPStorm).

You can try query: `select * from contacts` and see if there are email column or not.

**Comment by Peckerd** [comment]
Just checked and you are right. Sorry, my bad
