### ISSUE TITLE
Open Anything - Include opening a new (blank) SQL Query tab

### ISSUE THREAD

**Issue by chadsaun** [TablePlus/TablePlus#1603]
It would be great inside the "Open Anything" search box to be able to type something like `sql`  and have the option to open a new tab for an SQL Query.

**Comment by huyphams** [comment]
TablePlus will open SQL Query with Command + T in the next update! so I don't think we need this!

**Comment by chadsaun** [comment]
The whole point of having the "Open Anything" is so that you can use it to open anything. Yes, you could use a different keystroke combo, but that is just one more keyboard shortcut to memorize. That's what is so great about the "Open anything" feature. You only need to memorize one keyboard shortcut, and then you can type to open anything!

I hope you reconsider.

**Comment by rlabatt** [comment]
How about Shift + Commend + T opens a blank SQL Query tab. That would satisfy my needs.

**Comment by chadsaun** [comment]
The "Open anything search" is triggered from 1 keyboard shortcut. Then all you need to do is type some keyword like `sql` and have the first option to be "open sql tab".

Think [Alfred](https://www.alfredapp.com/) and [Jetbrains' "Searching Everywhere"](https://www.jetbrains.com/help/idea/searching-everywhere.html) feature. You can literally do just about anything with that one keyboard shortcut, and your hands don't have to leave the keyboard.

**Comment by rlabatt** [comment]
OK, not to be defensive, but can you tell me what to type after command+p?
I tried "sql" and Open Anything displayed a nice list of, well not what I
wanted - top open an empty SQL query window. I'm sure that Open Anything
works well for you, but it's not as intuitive as a simple key chord like
command+shift+n to open a new, empty sql query tab. I have no idea what the
current functionality of command+shift+o is, though the sql query window
that pops is nice.

All I'm saying is: fancy is sometimes the enemy of simple.

**Comment by chadsaun** [comment]
Sorry, my comment was referring to the request to have this added to table plus. It currently does not do that.

currently, you can use the shortcut command + T to open a new SQL query tab

**Comment by rlabatt** [comment]
Thanks Chad.
Command+T is helpful. What I'm suggesting is Shift+Command+T opens an empty
SQL tab. Today I need to open tabs until an empty SQL window opens. If
there is an easier way I'd love to learn about it. Thx.
The other suggestion I have, if you are open to them, is to bold the file
name in the file path at the top of the window. It will make it easier for
the user to hone in on the name of the file they are viewing.
Keep up the great work.

**Comment by JonathanGetahun** [comment]
I really like the shift+command+T approach, it would prevent us from having to navigate to preferences and then clicking SQL query just to open a new SQL query tab. I find myself constantly navigating back and forth, and it's very tedious
