### ISSUE TITLE
Option to restrict item filter to exact match

### ISSUE THREAD

**Issue by olibraga** [TablePlus/TablePlus#1608]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.5+7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
2.12 (282)
3. The steps to reproduce this issue:
Type in "Items" filter/search field, more functions/tables are shown than (I) expected.
E.g. If I type in "abc" both a "the_ABC_murders" and a "A_very_Big_Collection" tables are shown, I would like only the "the_ABC_murders" table to show.
I.e. option to interpret the typed "abc" as RE ".*abc.*" instead of ".*a.*b.*c.*".

A halfway solution would be to show the matching characters in the table names as bold, then I could at least quickly see the continuous bold "abc"s

**Comment by huyphams** [comment]
I've added an option for contains-pattern.

For example, if we use the double quote, it will search for items which contains the keyword.

<img width="254" alt="Screen Shot 2019-12-14 at 10 41 56 AM" src="https://user-images.githubusercontent.com/3654622/70850230-5d578f80-1e5e-11ea-980c-45a287b8265f.png">
