### ISSUE TITLE
Column dropdown not containing columns for a long time (multiple minutes)

### ISSUE THREAD

**Issue by jpike88** [TablePlus/TablePlus#1616]
1. TablePlus Build: ???
2. Database driver: ???
3. Step to reproduce the issue:

- TablePlus does not show the column list in the advanced filter properly.

see video. macOS, latest version of table plus

maybe cause it was waiting for things to happen. maybe a progress spinner or something in the corner so I know to wait?

![Screen Recording 2019-12-18 at 12 54 07 pm](https://user-images.githubusercontent.com/9585787/71059759-484c6a80-2196-11ea-9b1e-5cace5e8568e.gif)

**Comment by huyphams** [comment]
Hey @jpike88 thank you for the feedback but it would be great if you answer the template issue. it helps me to investigate the issue faster. We have a lot of issues (>500), I have no idea about the context of the issue without it.

**Comment by huyphams** [comment]
Hi @jpike88, does it still happening at the latest release 290?

**Comment by huyphams** [comment]
Finally, I can reproduce and fix this issue.
