### ISSUE TITLE
Apply/Applied don't show correct status

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [TablePlus/TablePlus#1617]
V2.12 (282)

The buttons used to show whether a filter is active or not do not show which filters are active when "Apply All" is pressed.

Video: 
https://drive.google.com/file/d/1JceBdryZ4pp4zBUSujqwieS1_45rv8Ob/view?usp=sharing

**Comment by huyphams** [comment]
Thanks @JohnnyWalkerDesign , I just fixed this bug.

**Comment by JohnnyWalkerDesign** [comment]
Does this not prove what I'm saying? A feature you insist could not be changed because endless people would email in and complain, wasn't even working correctly. I'll leave it with you, but please reconsider.
