### ISSUE TITLE
Bug: Filter case sensitivity not respected

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [TablePlus/TablePlus#1618]
V2.12 (282)

It seems the case sensitivity of "Contains" is ignored?

Video: https://drive.google.com/file/d/12E1fpWFyuNfUg6FCuTEOGAWkm1-pvFPx/view?usp=sharing

**Comment by huyphams** [comment]
Thanks @JohnnyWalkerDesign 
It was a type, I've fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It should be: Case sensitive (not insensitive).
