### ISSUE TITLE
Feature request : Reopen SQL-query windows after restarting application and remeber tab-names 

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1623]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgress 11.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
284

When TablePlus is restarted, it will re-open open tables, but not open sql query windows. It also does not remember any _**renaming**_ of query windows. 

Request to autosave these workspace details, such that these can be used after a restart

**Comment by skplunkerin** [comment]
Is there any way to do this yet? I'm currently working in a database with over 125 tables in it, and scrolling through all the tables to manually re-open up the same table tabs I always use is really frustrating _(especially when most of the table names are similar to each other, trying to find the right one over and over is a frustratingly slow process)_.

I would love if it's possible for TablePlus to remember the last opened tabs so each time I connect to the database they will be ready for me again; I don't necessarily want the tabs to automatically load the data for each table _(I'm fine hitting `cmd+r` to do that)_, it would just be a huge help if the tabs were just already open for me in the same order I placed them in.

**Comment by huyphams** [comment]
Hi @BFJonk if you are using the latest release, please save the queries on the left sidebar, so that when you reopen the app, it will restore all the tabs with the tab name (also all SQL Query tabs).

Please let me know if you are still seeing the issue.

![CleanShot 2022-08-03 at 23 51 57@2x](https://user-images.githubusercontent.com/3654622/182665138-3ba2be54-63a0-4df0-b9f1-726ec9ccf9d3.png)

Hi @skplunkerin please enable this as a temporary workaround.

![CleanShot 2022-08-03 at 23 53 40@2x](https://user-images.githubusercontent.com/3654622/182665420-25409057-a83e-4dd3-9d1f-4d85542d1b05.png)

**Comment by skplunkerin** [comment]
> please enable this as a workaround solution.

Thank you for this suggestion; it looks like this `"Reopen closed workspaces at startup"` option only works if I completely quit TablePlus, where opening TablePlus will auto-connect to the database and remember the tabs.
This kind of helps, but isn't ideal; if I close the connection to the database and reconnect, or close the window for the database connection and re-connect _(which re-opens the window)_, the tabs aren't restored.
@huyphams is that to be expected? _(I'm guessing that's what you mean by this being a workaround)_

**Comment by huyphams** [comment]
Yep, I understand your issue that's why I said it was a workaround.
I will keep thinking about this issue (mostly about the ux/ui).

**Comment by skplunkerin** [comment]
Thank you @huyphams, I really appreciate your help!

Just a thought that could potentially build off of this current solution:
_(if there's a better place to continue this conversation, please let me know and I'll stop posting here on this closed issue 😄 )_

Would it make sense to separate "saved database connections" from "workspaces"? The initial window I see when opening TablePlus is my saved list of "database connections"; but after testing out this `"Reopen closed workspaces at startup"` option, it seems more like I don't have a list of database connections, but rather a "list of workspaces"?

If that's correct, I think separating "saved database connections" from "saved workspaces" would make more sense and allow a workspace to be similar to how we can currently name, save, and tag queries in the `Queries` section. If I was able to save workspaces like this, I wouldn't need to wait for the `"... at startup"` for re-openning my workspace; instead I could just double-click my saved workspace to open it _(along with it's opened tabs/settings)_.
