### ISSUE TITLE
Mysql stored functions are all empty

### ISSUE THREAD

**Issue by optikalefx** [TablePlus/TablePlus#1625]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql / MariaDB 10.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
282

3. The steps to reproduce this issue:
Click on any of the stored functions

Video https://share.getcloudapp.com/geurq6pk

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey, @optikalefx could you try this query on the empty function/proceduce:
SHOW CREATE PROCEDURE `<your function/procedure name>`;

If the result is empty then it was the permission issue.

**Comment by optikalefx** [comment]
Thanks for helping with this. It does have a result.

![image](https://user-images.githubusercontent.com/926885/71520299-4fa40000-2889-11ea-921f-4f59a055ea0a.png)

**Comment by huyphams** [comment]
It does have a result but it's empty/null. You can see the Create Function column, it's NULL. This issue only happens if the function/procedure was created by another user.

**Comment by optikalefx** [comment]
Ah ha. I was logged in as a root user in SequelPro which is why it was able to view/edit them. I'm going to delete all of them from user root and re-create with our main user so that I don't have this issue.

Thanks!
