### ISSUE TITLE
Unable to start TablePlus

### ISSUE THREAD

**Issue by andreaolivato** [TablePlus/TablePlus#1626]
After a crash while refreshing database information, I am unable to reopen TablePlus

1. **Using the Latest stable build (re-downloaded Today) for Mac. Using Mac OS Catalina 10.15.2**

2. **Steps to reproduce this issue:**
- Open Table Plus
- Crash

Here's the log if I launch from Terminal

> /Applications/TablePlus.app/Contents/MacOS/TablePlus
> 2019-12-22 13:23:35.371 TablePlus[2580:16917] -[NSURL init] called; this results in an NSURL instance with an empty URL string. Please use one of the documented NSURL initialization methods instead (initWithString:, initFileURLWithPath:, etc.). This message shown only once.
> 2019-12-22 13:23:35.372 TablePlus[2580:16917] -[__NSCFString count]: unrecognized selector sent to instance 0x7fec1e340bb0
> 2019-12-22 13:23:35.373 TablePlus[2580:16917] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x7fec1e340bb0'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff31cf78ab __exceptionPreprocess + 250
> 	1   libobjc.A.dylib                     0x00007fff67f68805 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff31d76b61 -[NSObject(NSObject) __retain_OA] + 0
> 	3   CoreFoundation                      0x00007fff31c5badf ___forwarding___ + 1427
> 	4   CoreFoundation                      0x00007fff31c5b4b8 _CF_forwarding_prep_0 + 120
> 	5   TablePlus                           0x0000000107206c85 TablePlus + 4799621
> 	6   TablePlus                           0x0000000107206b35 TablePlus + 4799285
> 	7   libdispatch.dylib                   0x00007fff6927d50e _dispatch_client_callout + 8
> 	8   libdispatch.dylib                   0x00007fff6927e686 _dispatch_once_callout + 20
> 	9   TablePlus                           0x0000000107206afe TablePlus + 4799230
> 	10  TablePlus                           0x0000000107208b23 TablePlus + 4807459
> 	11  TablePlus                           0x0000000107208e94 TablePlus + 4808340
> 	12  TablePlus                           0x0000000107207ed9 TablePlus + 4804313
> 	13  TablePlus                           0x0000000107025893 TablePlus + 2828435
> 	14  TablePlus                           0x00000001070256c9 TablePlus + 2827977
> 	15  TablePlus                           0x0000000106e98779 TablePlus + 1202041
> 	16  libdispatch.dylib                   0x00007fff6927c583 _dispatch_call_block_and_release + 12
> 	17  libdispatch.dylib                   0x00007fff6927d50e _dispatch_client_callout + 8
> 	18  libdispatch.dylib                   0x00007fff6928b933 _dispatch_root_queue_drain + 663
> 	19  libdispatch.dylib                   0x00007fff6928bf22 _dispatch_worker_thread2 + 92
> 	20  libsystem_pthread.dylib             0x00007fff694d76b6 _pthread_wqthread + 220
> 	21  libsystem_pthread.dylib             0x00007fff694d6827 start_wqthread + 15
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> zsh: abort      /Applications/TablePlus.app/Contents/MacOS/TablePlus

**Comment by huyphams** [comment]
Hi @andreaolivato it seems like that your TablePlus settings are damaged. Please  try to remove the App data and open it again:
rm ~/Library/Application\ Support/com.tinyapp.TablePlus/Data/

Please note that it will remove all the connections and you have to create it over again.

You might want to open Key Chain and delete all TablePlus saved passwords too. Search with the keyword TablePlus => select and delete all.

**Comment by andreaolivato** [comment]
> Hi @andreaolivato it seems like that your TablePlus settings are damaged. Please try to remove the App data and open it again:
> rm ~/Library/Application\ Support/com.tinyapp.TablePlus/Data/
> 
> Please note that it will remove all the connections and you have to create it over again.
> 
> You might want to open Key Chain and delete all TablePlus saved passwords too. Search with the keyword TablePlus => select and delete all.

I've deleted everything in ~/Library/Application\ Support/com.tinyapp.TablePlus/Data/ , all the passwords in KeyChain for Table Plus but the error remains the same. Also the application reminds that it crashed last time. Is there another location where tableplus saves its cache/config?

**Comment by huyphams** [comment]
Hmm, then please try to remove the user default settings: 
```
rm ~/Library/Preferences/com.tinyapp.TablePlus.plist
```

**Comment by andreaolivato** [comment]
That worked, thanks a lot @huyphams the com.tinyapp.TablePlus.plist was the issue.

I've also restored all the files under Application Support which didn't create any issue.
