### ISSUE TITLE
Default Open Tabs

### ISSUE THREAD

**Issue by xingtianyoulong** [TablePlus/TablePlus#1627]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
ALL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
282
(We write down the version for tracking).

3. The steps to reproduce this issue:

> Open many tabs to execute diff SQL for the diff business
> When I close the table plus and reopen it, all tabs didn't exist
> So please make sure tabs exist after we reopen the table plus

**Comment by huyphams** [comment]
Hi @xingtianyoulong it's duplicated with: https://github.com/TablePlus/TablePlus/issues/1623

**Comment by xingtianyoulong** [comment]
> Hi @xingtianyoulong it's duplicated with #1623

OK，Hoping fix these issues!

**Comment by pinpins** [comment]
Any update on that feature request? Very much missing, stopping for going full version

**Comment by huyphams** [comment]
If you have a chance, please download this hotpatch, it supports restore SQL Query/file now.
https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
