### ISSUE TITLE
tableplus truncate table not working

### ISSUE THREAD

**Issue by fhefh2015** [TablePlus/TablePlus#1628]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySql 5.7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 282
3. The steps to reproduce this issue:
tableplus truncate table not working
Noted: If the bug is related to data, please attach an example SQL data.
![](https://i.imgur.com/WRPZRFB.png)
![](https://i.imgur.com/6Mkt8ei.png)
![](https://i.imgur.com/TqFHLo4.png)

not working

**Comment by huyphams** [comment]
Hi @fhefh2015 you have to commit the changes (Command + S or click the commit button on the top left)
TablePlus will not save it until you commit.

**Comment by huyphams** [comment]
Please let me know if you have any further question via email nick@tableplus.com
Thank you!
