### ISSUE TITLE
[Feature Request] Nested groups in favorite

### ISSUE THREAD

**Issue by bmichotte** [TablePlus/TablePlus#163]
It would be awesome :)

![capture d ecran 2017-12-27 a 17 36 47](https://user-images.githubusercontent.com/235510/34387314-bbd91ec2-eb2d-11e7-8745-226701d083ec.png)

**Comment by huyphams** [comment]
Thanks for the idea. I think if we have nested groups the UX might be complicated (and need 2 keystrokes to open a connection). But I know your problem, you want to group datacenter and production database at the same time.

**Comment by weyert** [comment]
Hmm, doesn't look like you can make that group as shown in the screenshot. I have made a group named Client1 and inside I want to make a new group for DEV/UAT/PROD only this isn't possible

**Comment by huyphams** [comment]
I changed my mind, TablePlus will support nested group.

**Comment by StijnMaenhaut** [comment]
@huyphams Any idea when this feature would be released? The "done" label was just removed, a bit confused :)

**Comment by eleftrik** [comment]
> TablePlus will support nested group.

@huyphams Any news about the estimated release date?

Thank you

**Comment by huyphams** [comment]
Hi guys, I just added nested group experiment in this build (still have some bugs but it works now): https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
