### ISSUE TITLE
force close while reconnect

### ISSUE THREAD

**Issue by cqyjk2006** [TablePlus/TablePlus#1631]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL Community Server (GPL) 5.6.10
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 282
3. The steps to reproduce this issue:
This issue is high frequency and random，I use ssh tunnel to link the database, so often prompted disconnected, when I click manually reconnect, tabplus occasionally will force close.This is my error message.
[error message.txt](https://github.com/TablePlus/TablePlus/files/3999909/error.message.txt)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I see the crash is coming from the MySQL 5.x driver, and it seems like it was a MySQL driver issue. Could you try with the MySQL 8.x driver and see how's it going? 
The 8.x driver is still compatible with the old MySQL.
