### ISSUE TITLE
Import CSV

### ISSUE THREAD

**Issue by chipsflower** [TablePlus/TablePlus#1632]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 282

3. The steps to reproduce this issue:
Import CSV File
When importing a CSV file, all the records are not imported (2200 out of 53000). I did not have this problem with the previous build. In a mySQL database I don't have this problem either.

**Comment by huyphams** [comment]
Hi @chipsflower we didn't change anything related to CSV parser recently. I assume it was an encoding issue, and the CSV was truncated due to encoding error.
<img width="742" alt="bac" src="https://user-images.githubusercontent.com/3654622/71561014-3943a300-2a47-11ea-8100-9efaf3f49d36.png">

**Comment by chipsflower** [comment]
Hello,
The import worked well with the previous import. I redid tests with the same files and there it does not work any more. So there is a problem somewhere!

**Comment by huyphams** [comment]
Thanks, I will check it. If you have any CSV that can share with me, you can share it with me to my email nick@tableplus.com Thank you!

**Comment by chipsflower** [comment]
Thank you for your reply
I have a CSV file named TEST of 53518 lines, I reduced the file to 1000
lines because too big for sending
I am testing the following two methods:
1. Import into an existing table (same structure) -> only 90 rows are
imported
2. Import with creation of new table (all fields are TEXT) -> 88 rows
imported!
With the previous version there was no problem!
thank you and good evening

Le dim. 29 déc. 2019 à 20:08, Henry Pham <notifications@github.com> a
écrit :

**Comment by obrunsmann** [comment]
I am also affected by this bug. I already tried with different encodings and tried to remove different colums from my source CSV.

The amount of successfully imported rows is different when removing columns from the SQLite Table. In my current configuration TablePlus imports 1867 of ~55k Rows, when **adding** another column to the Table, the number strangely increases to ~5,5k..

**Comment by huyphams** [comment]
Hey @obrunsmann and @chipsflower I can reproduce the issue and fix it in this patch: https://www.dropbox.com/s/lgh81iqa7x6i3hu/TablePlus.dmg?dl=0
if you have a chance, please give it try and let me know the result! thank you!

**Comment by xinyuezhaodsco** [comment]
I am still having problem with the new build, I have a csv file with ~10k rows (1.1M) and it only imports 11 rows to redshift table, and the import window never shows complete, it is stuck at 0.0/1.1M.

**Comment by obrunsmann** [comment]
@huyphams The patch worked for me! All rows have been imported 🎉 

The only thing is that the import was very slow. It took nearly 10 Minutes for ~55k rows (8 mb). Yesterday I switched to another tool while I experienced the import issue. The import of the same file only took less than 30 seconds.

**Comment by huyphams** [comment]
Maybe I know the reason, I could improve the speed to less than 30 seconds but it needs to be refactored a little bit.

**Comment by chipsflower** [comment]
Thank you. I just tested the patch version and this time all the lines of the file are imported (3 tries with different files). By cons the import is very long, about 10 minutes for a file of 50,000 lines against about 30 seconds before!

**Comment by huyphams** [comment]
Hi guys, this is the optimized version, which improves the speed a lot: https://www.dropbox.com/s/lgh81iqa7x6i3hu/TablePlus.dmg?dl=0
Thank you for trying the patch.

**Comment by obrunsmann** [comment]
@huyphams wow - that was blazing fast :))

It worked now for me. All rows have been imported again (~55k/8M) in around 5 sec. That's awesome!

**Comment by chipsflower** [comment]
Here, I test this morning and all the lines are imported in a few seconds. Great!
Thank you so much

**Comment by huyphams** [comment]
Hi @xinyuezhaodsco you might want to check out this issue: https://github.com/TablePlus/TablePlus/issues/1666 We also have a hot patch in that thread.

**Comment by karna-guild** [comment]
I'm getting the same error. Could you please guide how can I get the patched version? Is that build officially released? What is the build version?

**Comment by hellodit** [comment]
Still get this error when try to import csv file
