### ISSUE TITLE
SQL Query tab adds non-printable unicode characters 

### ISSUE THREAD

**Issue by MarynaKraynichuk** [TablePlus/TablePlus#1634]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
Mysql 5.5.47

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
2.12 (282)

3. The steps to reproduce this issue: 
it is not happening always, but mostly it happens when I write a query with LIKE condition. For example I write this query [select * from user where username like "%maryna%"] and I don't get any result but using the filters of the table user, I get the expected result and it is doing exactly the same query. I researched a little and found this page  (https://www.soscisurvey.de/tools/view-chars.php) and I saw that when I write queries in TablePlus, some characters non-printable are added to my query, and it because of that I can't see any result with lots of my queries. I attach a screenshot of the character which was added to my query (following the webpage I said before). Could you do some fix to prevent this non-printable characters? Thank you.  

<img width="1055" alt="Screenshot 2019-12-31 at 14 04 40" src="https://user-images.githubusercontent.com/22315553/71622694-e2b99e80-2bd7-11ea-9b36-8d94af487121.png">

**Comment by huyphams** [comment]
Hi @MarynaKraynichuk thank you for the feedback and happy new year.
TablePlus will not add any hidden character automatically, did you copy any part of the query from vscode or write it all in TablePlus? Did you accidentally hold the option key and type the numbers (It happened near the % character which is located on a number, if we hold option + press a number, there will be a chance that inserts a random Unicode character).

**Comment by quinyx-tjeerd** [comment]
Hello, 
I encountered the same issue, and this is quite a scary one.
Query:
```
UPDATE payments SET payment_status = 'paid' WHERE reference_id = '﻿62886047';
```
Pasting my query from source into TablePlus results in this:
![image](https://user-images.githubusercontent.com/64777787/87568140-76127700-c6c5-11ea-87e4-e5e92db69478.png)
The same query in VSCode:
![image](https://user-images.githubusercontent.com/64777787/87568211-94787280-c6c5-11ea-890b-e77f0197da17.png)

Queries like this can affect a lot of records unintentionally.
Namely all records where `reference_id` is `0`, the impact depends on the column that's used in the where condition.

This basically means TablePlus can't be safely used to execute queries in my honest opinion.
Unless we can configure TablePlus in a way so it also shows these characters?

**Comment by huyphams** [comment]
Could you send me an example via email nick@tableplus.com @quinyx-tjeerd thank you!

**Comment by huyphams** [comment]
Thanks @quinyx-tjeerd I just tested it on 3 editors: TablePlus, Sublime Text, and VSCode. Let me see if we can support invisible characters.
<img width="672" alt="Screen Shot 2020-07-15 at 11 21 29 PM" src="https://user-images.githubusercontent.com/3654622/87569928-11214600-c6f2-11ea-98da-596bb0289aa1.png">

**Comment by quinyx-tjeerd** [comment]
@huyphams Yeah that'd be great, then we can continue advising the usage of TablePlus again 😅

**Comment by huyphams** [comment]
I'm testing it 😄 
<img width="1335" alt="testing" src="https://user-images.githubusercontent.com/3654622/87580339-8fd1af80-c701-11ea-9308-846a521e3a4a.png">

**Comment by huyphams** [comment]
Hi @MarynaKraynichuk @quinyx-tjeerd if you have a chance, you can try this hot patch: https://www.dropbox.com/s/g801eovguzkqvlr/TablePlus.dmg?dl=0
Along with invalid character question mark, I also added an option "Show invisible Characters" on this patch:
<img width="305" alt="Screen Shot 2020-07-16 at 2 24 27 AM" src="https://user-images.githubusercontent.com/3654622/87586896-877e7200-c70b-11ea-9810-7d2f90d76366.png">

**Comment by quinyx-tjeerd** [comment]
Works like a charm for my usecase, thanks a lot!
any indication when this enhancement will find it's way into the official version?

**Comment by huyphams** [comment]
Thank you for trying it out. It will be included in the next update! @quinyx-tjeerd
