### ISSUE TITLE
Data / Meta Queries filter doesn't seem to work

### ISSUE THREAD

**Issue by JackWH** [TablePlus/TablePlus#1637]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MariaDB 10.2.18

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

2.12 (282)

3. The steps to reproduce this issue:

- Show the Console Log
- Edit some data, load some tables, commit some changes to those tables
- Try and use the filter dropdown to show/hide queries — switching between "All queries", "Data queries", and "Meta queries" makes no difference to which queries are filtered in the console. They are all always shown.

**Comment by JackWH** [comment]
Update: after playing with it some more, I see that it actually is working — it's just the usability isn't very clear.

I presume what's actually happening is, the setting chosen from the dropdown menu controls which _future_ queries are logged to the console. Previous queries won't be filtered retrospectively. This would be really useful for a future feature though!

I was also a bit confused as queries to fetch row counts from `information_schema` were counted as Data queries, when I would've assumed they would go under Meta queries. I kind of see the logic here, but it was a bit unintuitive at first. Perhaps this could be made clearer.

**Comment by huyphams** [comment]
Hi @JackWH I've removed that option in the new release (beta), TablePlus will log all the queries now.
