### ISSUE TITLE
[Bug][Build 79] Composite index columns should be ordered correctly

### ISSUE THREAD

**Issue by horo42** [TablePlus/TablePlus#164]
### Since column order in composite indexes is crucial in optimising queries, I consider this a bug.

If I create a table with

```PRIMARY KEY (`cID`,`cvID`,`bID`,`arHandle`)```

The columns should be displayed in this order. Current behavior:

<img width="361" alt="Alphabetical order of composite index columns" src="https://user-images.githubusercontent.com/5323731/34397391-1845d504-eb76-11e7-9971-92403da3c1b8.png">

This is not even lexicographical order, since bID is after cID and cvID.

But creating a new index with the same columns behaves differently. It correctly orders the columns lexicographically, even though this shouldn't be the case either.

<img width="368" alt="New index" src="https://user-images.githubusercontent.com/5323731/34397508-f3d976b6-eb76-11e7-8b06-f0e965e9e270.png">

Then moving cID before bID, pressing the enter key, then committing the changes, cID moves back to it's original place, but only visually, the index order changes correctly.

**Comment by huyphams** [comment]
Hi @horo42 can you try this build, I just fixed it: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by horo42** [comment]
#### I tested your fix, the issues are resolved, thank you!

This build doesn't seem to have the autocomplete of columns when editing indexes in the Row detail pane, neither when editing the primary key.

And I found some other issues (sorry 😅 ).

### Primary key column order

Editing the order of columns in the primary key, then discarding the changes, the order stays the same until I hit CMD + r.

### No column name validation

I can add ANYTHING as a column to the primary key and to any index, even if there is no column with that name. Committing fails, of course.

<img width="1213" alt="Creating index with column that doesn't exist" src="https://user-images.githubusercontent.com/5323731/34411437-d5ccff20-ebd6-11e7-9f06-6febbce29085.png">

### Inconsistent behaviour when index columns have spaces

As you have seen from the image above, adding a column with spaces to an index works properly. Adding the same column to the primary key however behaves differently. I type in "no column with this name", press enter, then a tag appears with this string. Pressing enter again or changing focus to a different part of the UI (like pressing the Review button, or selecting a column, etc.) breaks up the column, splitting it by the spaces, creating 5 tags.

Column names CAN have spaces in them, even though it's rare and very unorthodox.


Thanks for your attention, can't wait until the next release. Many great improvements! 👍

**Comment by huyphams** [comment]
`This build doesn't seem to have the autocomplete of columns when editing indexes in the Row detail pane, neither when editing the primary key.` => I fixed this bug after send you the build 😄

**Comment by huyphams** [comment]
Hi @horo42 I want to say that all fixed: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
😸

**Comment by horo42** [comment]
There is no "No column name validation" in the build you sent.

Additional issues I discovered while confirming your fixes:

### Empty index column tag

Creating a new index, typing in anything to the "column_name" input, then deleting it all, the placeholder for the "column_name" input changes to EMPTY from NULL.

In this case, whenever the index's row gets focus (I click on it), an empty column tag gets created.

<img width="905" alt="screen shot 2017-12-28 at 14 43 11" src="https://user-images.githubusercontent.com/5323731/34412434-79b47ac2-ebdd-11e7-9718-44b9ff749d12.png">

<img width="909" alt="screen shot 2017-12-28 at 14 43 18" src="https://user-images.githubusercontent.com/5323731/34412437-7cb7e358-ebdd-11e7-8cf8-7ac22f2fcda2.png">

Shows up as empty string in the review.

```CREATE INDEX CollectionVersionBlocks__idx ON `szervita`.`CollectionVersionBlocks` (``) USING BTREE;```

### Column name autocomplete stops working

Autocomplete stops working after reverting changes with the Discard button.

### Reverting index creation

If I create a new index, then type anything into the "column_name" input, press enter (so a tag gets created), then press the Discard button without losing focus of the input, the index doesn't get discarded (but the autocomplete stops working). The "column_name" field gets updated in the bottom pane.

If I press the Discard button again (or if I lose focus of the input first, before pressing it), the index disappears, but the Row detail right side pane stays open with the data of the discarded index. If I update any of the fields here, then lose focus of the input (or press enter), the index reappears.

Suggestion: close the Row detail pane if the selected row gets discarded, like when deleting it.

### Row detail pane "column_name" field bug

Initial state

<img width="218" alt="screen shot 2017-12-28 at 15 01 48" src="https://user-images.githubusercontent.com/5323731/34412875-0e1f1c06-ebe0-11e7-9b78-3451d88633ab.png">

I type "sstring". Images of before and after pressing enter:

<img width="219" alt="screen shot 2017-12-28 at 15 02 55" src="https://user-images.githubusercontent.com/5323731/34412900-4929b446-ebe0-11e7-9754-8233b317e3f6.png">
<img width="220" alt="screen shot 2017-12-28 at 15 03 01" src="https://user-images.githubusercontent.com/5323731/34412903-4c799f4e-ebe0-11e7-9e07-0f8fa8e6a750.png">

Now I click on the "cID" tag, and move it before the "bID" tag, so it's the first column in the list.

<img width="216" alt="screen shot 2017-12-28 at 15 04 05" src="https://user-images.githubusercontent.com/5323731/34412926-6e40bd06-ebe0-11e7-9fdb-5b7ce268f2eb.png">

Now I hit CMD + z in hopes of bringing back the input field, and it disappears completely.

<img width="213" alt="screen shot 2017-12-28 at 15 04 48" src="https://user-images.githubusercontent.com/5323731/34412932-7e5b1984-ebe0-11e7-942f-85500e99bb23.png">
