### ISSUE TITLE
Feature request: variables able to be used in schema names and in quotes (e.g. :variable.table)

### ISSUE THREAD

**Issue by alexgw-afr** [TablePlus/TablePlus#1641]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL version unknown 9 or 10.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.0.0, build 288.

CURRENTLY, there are a few options for SQL variables, e.g. ${variable} or :variable.

Due to historical reasons, I am stuck with :variable in my particular codebase.

1. Variables do not work easily when referring to schemas:

Example that does not work:
      select * from :myschema.users;  -- note lack of space between :myschema and users
Workaround:
      select * from :myschema . users; -- (note the spaces!)

This could be fixed if there was an option to have the regexp be [\w]+ instead of [\w.]+.

2. Variables do not appear to work in quotes, so:

select * from TABX where the_date <= ':todays_date'; -- does not work
Whereas the literal works:
select * from TABX where the_date <= '2019-01-01'::date; -- does work

As far as I can tell, there is no workaround for the date situation.

**Comment by mittalyashu** [comment]
Any updates on this feature?

**Comment by mittalyashu** [comment]
It will be nice to have feature where we can have input variable for each SQL query.

**For example**

```sql
SELECT * FROM users WHERE emailAddress = ?;
```

While running this query it can show a pop-up asking for an input every time we run the query or save multiple variables and select one and use it inside the SQL query.

**NOTE:** I am not talking about SQL variable

**Comment by huyphams** [comment]
It's supported a year ago @mittalyashu please take a look at this
<img width="776" alt="Screen Shot 2020-11-20 at 6 43 42 PM" src="https://user-images.githubusercontent.com/3654622/99796608-5d790880-2b60-11eb-8151-f01913c080d8.png">

**Comment by DIntriglia** [comment]
Wanted to follow up on this regarding the following quote above:

> Variables do not appear to work in quotes, so:
select * from TABX where the_date <= ':todays_date'; -- does not work
Whereas the literal works:
select * from TABX where the_date <= '2019-01-01'::date; -- does work

I am testing it in the latest version, and still can not get quotes to be recognized and popup the message. Can anyone elaborate on how to do this, or which Regex schema to use that supports quotes?

**Comment by huyphams** [comment]
We are not going to support this because it would break the normal queries. For example:

`UPDATE "public"."users" SET "device_id" = 'A :B';`

@DIntriglia @alexgw-afr you can use the variable `without quote` and the enter the value `with quote` for example

<img width="934" alt="Screen Shot 2021-09-02 at 6 47 48 AM" src="https://user-images.githubusercontent.com/3654622/131759750-5b372f93-a861-4fac-8f53-9039906cbabd.png">
