### ISSUE TITLE
Request: make it easier / default to open new connection in a new window

### ISSUE THREAD

**Issue by amitai52** [TablePlus/TablePlus#1643]
My preference is to open new DB connections in a new window, not a new tab.
(I prefer more windows, as you can leverage MacOS expose and similar features)

For that I right-click in the connections window and select new-window (instead of double click to open in a new tab) - it's a little annoying to do that each time I open a new connection.

I suggest to either:
- add a preference that new connections open in new windows / tabs by default
- OR add some control in the new-connection window that can be clicked directly.

I personally prefer the preference solution
Thanks
Dan

**Comment by huyphams** [comment]
Hi @amitai52 thank you for the suggestion. Have you tried the Command + N to open a new connection? is it solve your issue?

**Comment by amitai52** [comment]
Hi

Yes, Cmd+N is a good workaround.
Although it was more intuitive for me to click the plug icon (top left) in the gui which does 'show connections' - this option is more accessible via the GUI.

Dan
