### ISSUE TITLE
Surprising DROP PRIMARY KEY when trying to update a row

### ISSUE THREAD

**Issue by Jiia** [TablePlus/TablePlus#1646]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.44

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
282

3. Rough steps what I did
Tried to import a CSV file to a table. Got duplicate key errors when importing it.

I  opened the table, clicked on `some_column`. Typed in a new value, pressed CMD+S and got a weird error message. I opened the SQL preview and to my surprise it contained:

```
UPDATE `db`.`table` SET `some_column` = '2' WHERE `id` = '1';
ALTER TABLE `db`.`table` DROP PRIMARY KEY;
```

I never even opened the table structure view. I would very much like to know how to avoid accidentally doing this. Is there a keyboard shortcut that drops a column or something like that?

**Comment by huyphams** [comment]
it's unexpected @Jiia the only way to change table primary is via the token field in the structure. Let me investigate it.

**Comment by huyphams** [comment]
I think the issue might be related to the situation where the token field got focusing unexpectedly and it might affect the text in it.
I just added one more validation when the primary key can only be modified when the structure is opened.
