### ISSUE TITLE
Crashes when using foreign key navigation arrow between databases

### ISSUE THREAD

**Issue by Samuel-Webster** [TablePlus/TablePlus#1648]
MySQL 5.7.24
Build 112
Windows 10
Local development environment

When trying to use the foreign key navigation arrow to the right of the value in the cell to another database the software hangs then crashes. Both databases and values can be accessed and opened by switching (CTRL + K) and the arrow works fine if the foreign key is in the same database.

**Comment by huyphams** [comment]
Hi @Samuel-Webster thank you for the feedback, could you try this hot patch and see how's thing going?
https://www.dropbox.com/s/qw87iunfkchtb85/TablePlusUpdate.exe?dl=0
I'm closing this issue for now because it belongs to Windows Repo: https://github.com/TablePlus/TablePlus-Windows

**Comment by Samuel-Webster** [comment]
Thanks @huyphams the hot fixed worked!
