### ISSUE TITLE
Feature Request: Beautify OVER (PARTITION BY ... ORDER BY...) 

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1649]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
11.5
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
288
3. The steps to reproduce this issue:

Can you also BEAUTIFY 
```
CASE WHEN mpc.experiment_number = '0'
		THEN ( select count(*) from modern_pricing_client) 
			- 
			(sum(count(mpc.id)) OVER (ORDER BY mpc.experiment_number, mpc.experiment_name, to_char(mpc.date_first_mp_subscription, 'yyyy-MM') ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
		)
		ELSE 
			sum(count(mpc.id)) OVER (PARTITION BY mpc.experiment_number ORDER BY mpc.experiment_number, mpc.experiment_name,
			to_char(mpc.date_first_mp_subscription, 'yyyy-MM') ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) 
		END AS cum_client_count,`
```
to :

```
ELSE 
			sum(count(mpc.id)) OVER 
				(PARTITION BY 
						mpc.experiment_number 
				ORDER BY 
						mpc.experiment_number, 
						mpc.experiment_name,
						to_char(mpc.date_first_mp_subscription, 'yyyy-MM') 
						ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
				) 
		END AS cum_client_count,
```

**Comment by huyphams** [comment]
Hey, @BFJonk you can use the SQL formatter plugin as a temporary solution. You can install it by press Command + L => install SQL Formatter. Then you will see it in the menu Plugin > Format SQL (control + I)
Or you can build it your self here: https://github.com/TablePlus/sql-formatter

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0

**Comment by BFJonk** [comment]
Hi Henry,

Great improvement. I tried formatting some of my longer queries with CTEs
and am very pleased that my CTE comments now stay in place (#1536
<https://github.com/TablePlus/TablePlus/issues/1536>). It will make me use
the beautify button again!

I can also confirm that the other bugs (#1649
<https://github.com/TablePlus/TablePlus/issues/1649>, #1560
<https://github.com/TablePlus/TablePlus/issues/1560>, #1191
<https://github.com/TablePlus/TablePlus/issues/1191>) are closed as well.

Small improvement request (I can make a separate quest for this if you
like):

There seems to be a difference between formatting `date_trunc` on the one
hand, and `extract` and `date_bin` on the other side. The former
(date_trinc) is formatted as expected, the latter are broken into
seperate lines, making queries harder to read:

```SQL
SELECT date_trunc('hour', '2001-02-16 20:38:40'::TIMESTAMP);
--> kept on one line, which is logical, especially with longer select lists
select
date_trunc('hour', '2001-02-16 20:38:40'::TIMESTAMP);


SELECT extract(WEEK FROM TIMESTAMP '2001-02-16 20:38:40');
--> broken into lines, making queries harder to read
select
extract(
WEEK
from
TIMESTAMP '2001-02-16 20:38:40'
);


SELECT date_bin('15 minutes', TIMESTAMP '2020-02-11 15:44:17', TIMESTAMP
'2001-01-01');
-->
select
date_bin(
'15 minutes',
TIMESTAMP '2020-02-11 15:44:17',
TIMESTAMP '2001-01-01'
);
```


Larger question: would you consider a comma-first option for arguments? It
always helps me commenting out during testing.

kind regards,
Bart.

**Comment by huyphams** [comment]
Hi @BFJonk this patch fix the new line issue for the expression length 
mv TablePlus.dmg /Users/Shared/Builds/TablePlus/Production/TablePlus.dmg

**Comment by BFJonk** [comment]
Can't click that link..... ?

**Comment by huyphams** [comment]
Sorry, here is the link https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=mvf7s5gi&dl=0

**Comment by BFJonk** [comment]
sorry, I'm not sure what is being fixed here. Still have the same issue with EXTRACT:

```SQL
SELECT date_trunc('hour', '2001-02-16 20:38:40'::TIMESTAMP);
--> kept on one line, which is logical, especially with longer select lists 
select
	date_trunc('hour', '2001-02-16 20:38:40'::TIMESTAMP);


SELECT extract(WEEK FROM TIMESTAMP '2001-02-16 20:38:40');
--> observed result : broken into lines, making queries harder to read
select
	extract(
		WEEK
		from
			TIMESTAMP '2001-02-16 20:38:40'
	);
--> Expected result: on line, like with date_trunc()
SELECT 
	extract(WEEK FROM TIMESTAMP '2001-02-16 20:38:40');

SELECT date_bin('15 minutes', TIMESTAMP '2020-02-11 15:44:17', TIMESTAMP '2001-01-01');
--> idem 
select
	date_bin(
		'15 minutes',
		TIMESTAMP '2020-02-11 15:44:17',
		TIMESTAMP '2001-01-01'
	);
```

**Comment by huyphams** [comment]
Ops sorry @BFJonk I uploaded wrong build. Will update the build tomorrow!

**Comment by BFJonk** [comment]
no problem, good night!

**Comment by BFJonk** [comment]
gentile reminder :-)

**Comment by huyphams** [comment]
Hi @BFJonk I find out that the 
`SELECT 
	extract(WEEK FROM TIMESTAMP '2001-02-16 20:38:40');`
	
has the query inside WEEK FROM TIMESTAMP '2001-02-16 20:38:40', so it is hard to keep it in one line (because it is not a normal parameter). Let me see if we can do anything to make an exception.

**Comment by BFJonk** [comment]
Ah! sounds logical. 

However, does not explain why `date_trunc()` is broken off as well. 

And is it different with `SELECT extract(WEEK FROM '2001-02-16 20:38:40'::timestamp);` ? 

NB the build I'm using now (Version 6.1.8 (575)) is messing this example query:

```SQL
select distinct
	client_id,
	extract(
		year
		from
			request_created
	) as year,
	extract(
		month
		from
			request_created
	) as month,
	coalesce(sum(total_number_ported) over w, 0) as total_succeed_inports_requested,
	sum(singular) over w as inported_singular,
	sum(block_10) over w as inported_block_10,
	sum(block_100) over w as inported_block_100,
	sum(block_1000) over w as inported_block_1000,
	max(request_created::date) over w as request_date
from
	star.fact_porting_request pr
where
	status in ('agreed', 'ported', 'requested')
	and porting_type = 'inport'
	and actual_porting_date is not null
window
	w as (
		partition by
			client_id,
			extract(
				year
				from
					request_created
			),
			extract(
				month
				from
					request_created
			)
	); 
```
Beautify:
```SQL
select distinct
	client_id,
	extract(year from request_created) as year,
	extract(month from request_created) as month,
	coalesce(sum(total_number_ported) over w, 0) as total_succeed_inports_requested,
	sum(singular) over w as inported_singular,
		sum(block_10) over w as inported_block_10,
			sum(block_100) over w as inported_block_100,
				sum(block_1000) over w as inported_block_1000,
					max(request_created::date) over w as request_date
					from
						star.fact_porting_request pr
					where
						status in('agreed', 'ported', 'requested')
						and porting_type = 'inport'
						and actual_porting_date is not null window w as (
							partition by client_id, extract(year from request_created), extract(month from request_created));
	
```

**Comment by huyphams** [comment]
You can try the beta 577 which has a new beautify function.

**Comment by BFJonk** [comment]
Hi Henry, Love to try it! A slight hint on where/how to download would be nice, though :-)

**Comment by huyphams** [comment]
I'm seeing that you are on the build 575 (which is the beta build and only when you enable receives beta build), so you just go ahead and "check for updates..." to update to the next beta.

**Comment by BFJonk** [comment]
Indeed that works! Now on Build 577

date_trunc() still works
date_bin() now works as intended

```SQL
SELECT date_trunc('hour', '2001-02-16 20:38:40'::TIMESTAMP);
--> kept on one line, which is logical, especially with longer select lists 
select
	date_trunc('hour', '2001-02-16 20:38:40'::TIMESTAMP);


SELECT date_bin('15 minutes', TIMESTAMP '2020-02-11 15:44:17', TIMESTAMP '2001-01-01');
--> 
select
	date_bin('15 minutes', TIMESTAMP '2020-02-11 15:44:17', TIMESTAMP '2001-01-01');

```
extract() is still broken into multiple lines

```SQL
SELECT extract(WEEK FROM TIMESTAMP '2001-02-16 20:38:40');
--> Still broken into multiple lines, making queries harder to read
select
	extract(
		WEEK
		from
			TIMESTAMP '2001-02-16 20:38:40'
	);

```
