### ISSUE TITLE
Does not display full / correct error when executing a failed query

### ISSUE THREAD

**Issue by avfigueredo** [TablePlus/TablePlus#1650]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64) 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

2.12 (282)

3. The steps to reproduce this issue:

Try to insert a row in a table without a field that cannot be null. The query return error, but don't show exactly what is the error, just a generic message.

The field "password" on my users table cannot be null.

My query:

`INSERT INTO users (username, email, created_by_user_id, updated_by_user_id, created_at, updated_at, uuid, [name], type_id, seller_id)
SELECT
	A. [name],
	A.email,
	1,
	1,
	A.created_at,
	A.updated_at,
	NEWID (),
	A. [name],
	2,
	A.id
FROM
	sellers A
WHERE
	NOT EXISTS (
		SELECT
			*
		FROM
			users B
		WHERE
			B.seller_id = A.id);`

<img width="1528" alt="Screen Shot 2020-01-10 at 16 26 09" src="https://user-images.githubusercontent.com/8737136/72180893-ef53a900-33c6-11ea-9d97-bd08d597b688.png">

The same query executed in HeidiSQL return the correct error.

![image](https://user-images.githubusercontent.com/8737136/72180982-29bd4600-33c7-11ea-8f55-800b87488819.png)

**Comment by huyphams** [comment]
Hi @avfigueredo thank you for the feedback. We've addressed this issue recently if you have a chance. Please try this hot-patch: https://www.dropbox.com/s/v9r7txauzqqawtp/TablePlus.dmg?dl=0 it should show all the error message. (You can keep using it as the official build.)

**Comment by huyphams** [comment]
Build 286 is released now!
