### ISSUE TITLE
Feature Request: Query Favorite/Snippet Placeholders

### ISSUE THREAD

**Issue by othyn** [TablePlus/TablePlus#1652]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`MySQL 8`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`Build 286`

3. The steps to reproduce this issue:

Favorites are great. There is one key feature missing though compared to Sequel Pro that I sorely miss, which is for the ability for favorites/snippets to have placeholders for dynamic data, ones that can be tabbed through easily to provide data for the query instance.

Take this ficticious query as an example:

```sql
SELECT
    u.id,
    u.name,
    g.name
FROM
    users u
LEFT JOIN
    groups g
    ON u.group_id = g.id
WHERE
    g.id = 5;
```

This query is great to save as a favorite/snippet and re-use, but its not easy to:

- See what needs changing in the query if I return to it after `x` period of time, especially if there are multiple fields to change.
- Change the data quickly to morph the query to what I newly require.
- Stop errors through submitting a query that may not be fully modified as intended to produce the correct dataset if multiple parameters need changing, this as placeholders are obviously not valid SQL syntax and will cause the query to error as a safe guard.
- Ensure the query is inherently dynamic.

Whereas something like this, with whatever visual/placeholder syntax you wish, is much easier to read and understand, solving the above points with tab auto-completion to navigate and replace query placeholders:

```sql
SELECT
    u.id,
    u.name,
    g.name
FROM
    users u
LEFT JOIN
    groups g
    ON u.group_id = g.id
WHERE
    u.id = [user_id];
```

**Comment by huyphams** [comment]
Hi @othyn thank you for the suggestion. TablePlus has a similar feature, I'm not sure if you aware of it. Please try it and let me know your thoughts.
1. Create a TablePlus snippet with key binding.
<img width="915" alt="abc" src="https://user-images.githubusercontent.com/3654622/72267061-ccf3a280-35f5-11ea-8c23-c25c996b2973.png">
After that, you can use the key binding to insert the snippet::
![keyword-binding](https://user-images.githubusercontent.com/3654622/72267086-d977fb00-35f5-11ea-94b6-ca7b8c87ea0d.gif)
2. Create query parameters for the snippet.
- Enable query parameter.

<img width="635" alt="Screen Shot 2020-01-13 at 11 16 39 AM" src="https://user-images.githubusercontent.com/3654622/72267284-2f4ca300-35f6-11ea-955f-cd61f106f3bd.png">
- Update the query with variables


![2019-06-18 09 54 30](https://user-images.githubusercontent.com/3654622/59650147-281ffc80-91af-11e9-826b-8d96468521d3.gif)

**Comment by othyn** [comment]
Ah, thats perfect thank you!
