### ISSUE TITLE
High CPU usage from nothing

### ISSUE THREAD

**Issue by RomkaLTU** [TablePlus/TablePlus#1657]
1. Database driver: MySQL
2. TablePlus: Build 286.  OSX Catalina
3. Step to reproduce the issue:
 
- just opened TablePlus and got this:
CPU on max, fans spinning, I just opened and closed Mysql table thats all. This issue repeating randomly.

<img width="1351" alt="Activity Monitor (My Processes) 2020-01-14 15-18-39" src="https://user-images.githubusercontent.com/10167743/72347723-6e0b5780-36e1-11ea-8800-a126401d1fcf.png">

**Comment by huyphams** [comment]
Hi @RomkaLTU thank you for the feedback. In order to narrow down the issue, could you tell me more about your database setup? how big is the table?

**Comment by RomkaLTU** [comment]
I have about 10 million rows (~1Gb) in that database and some table have ~3 million rows.

**Comment by huyphams** [comment]
The number of rows won't affect the performance, TablePlus can handle a table with billion rows easily. I also test with a table that contains more than 1500 columns. Does your table have any big blob/binary/text column? does it happen with a certain table or any table?

**Comment by nickbasham-grayloon** [comment]
I'm getting really high CPU usage, too. I just have a very small database open, containing 9 tables and less than 1,000 total rows.

Running MacOS 10.15.2 on a 2019 16" MBP, TablePlus version 3.0.0 (286) through Setapp.

**Comment by nickbasham** [comment]
I'm getting really high CPU usage, too. I just have a very small database open, containing 9 tables and less than 1,000 total rows.

Running MacOS 10.15.2 on a 2019 16" MBP, TablePlus version 3.0.0 (286) through Setapp.

**Comment by huyphams** [comment]
Hi @nickbasham  any chance of getting an example? it could help me a lot, if you can, please send me a dump via email nick@tableplus.com

**Comment by lloydowen** [comment]
I also see this CPU usage, even with no particular database open, just migrating. So backup from one, and restoring to another. Small databases ~25mb.
2019 16" MBP - TablePlus version 3.0.0 (286)

**Comment by nickbasham** [comment]
> Hi @nickbasham any chance of getting an example? it could help me a lot, if you can, please send me a dump via email [nick@tableplus.com](mailto:nick@tableplus.com)

Sent!

**Comment by huyphams** [comment]
I just released the official build 290 which addressed this issue along with some new features, thank all!
