### ISSUE TITLE
Can't backup MySQL DB connected over SSH

### ISSUE THREAD

**Issue by blumtech** [TablePlus/TablePlus#1658]
1. Which driver are you using and version of it:
MySQL 5.7 and 8.0
2. Which TablePlus build number are you using:
3.0.0 (286)

3. The steps to reproduce this issue:
After connecting to the database -> File -> Backup... -> Select DB -> Start Backup
Backup database 'dbName'
Creating tunnel...
Create tunneling failed

I'm able to query the DB, export, import. The only time it fails is on the backup

**Comment by huyphams** [comment]
Hi @blumtech there is a menu in Help > Enable SSH Debug log, could you try to enable it and send me the log (nick@tableplus.com), thank you
<img width="443" alt="Screen Shot 2020-01-16 at 9 49 14 AM" src="https://user-images.githubusercontent.com/3654622/72530331-84322880-3845-11ea-878e-d1ebbbf2aa72.png">

**Comment by mirazasx** [comment]
I think I'm also having trouble taking a backup of MySql database. Get only this message and no files created.
```
Create tunneling...
Dumping...
/bin/sh: -c: line 0: unexpected EOF while looking for matching ``'
/bin/sh: -c: line 1: syntax error: unexpected end of file

Compressing....
Backup database completed
```

**Comment by huyphams** [comment]
I think you're using the old build @mirazasx no more `Compressing....` in the recent releases.

**Comment by mirazasx** [comment]
@huyphams I just updated to the newest version still the same error :(
```
TablePlus 3.1.0 is currently the newest version available.
```

**Comment by huyphams** [comment]
I've fixed an escape character bug in this patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 Please give it a try @mirazasx  @blumtech thank you!

**Comment by mirazasx** [comment]
It works :) I got a backup made for me :) Thanks 🍾🎉

**Comment by desaias** [comment]
@huyphams this patch version also fixes an issue we were having with making backing up for postgres through a ssh tunnel: `invalid port number: "\"`
