### ISSUE TITLE
[Feature Request] "over ssh" is not respecting ssh config

### ISSUE THREAD

**Issue by peh** [TablePlus/TablePlus#166]
As a user i would like my ~/.ssh/config File to be respected when using the "over ssh" option.

Having a more sophisticated SSH configuration with e.g. a bastion host that is used to proxy  connections is more or less best practice in todays cloud setups.
It would be great if TablePlus would support such things.
I understand that due to Apples Sandbox we would have to select the config file manually which is perfectly fine in my eyes!

**It's basically the last feature missing for me to buy a License!**

**Comment by huyphams** [comment]
Hey @peh, thanks for your feedback. I'm an ssh-config user. I use it every day with more than 20 servers and it saves a lot of time for me. Lets me see if I can do it.

**Comment by peh** [comment]
any progress? for now i am stuck with an ssh tunnel but it would be great to have the app doing everything for.

PS: i still bought the app it's to awesome to not pay for it!

**Comment by huyphams** [comment]
Some users have requested this feature too, so I moved it to work in progress. You will see it soon 😄

**Comment by mkarnicki** [comment]
Lovely, great that it's work-in-progress now. I would definitely like to use a host name from my ssh-config instead of providing server IP (which is not very human friendly).

Does the "Import private key" actually import/copy the key file somewhere or just saves the key file path? The "import" is a bit confusing. I think the following would be clearer:
"[Choose | Select] private key file [path]"

Actually, if the "Over SSH -> Server" is not an IP (but a host from ssh-config), it would be *sweeet* if TablePlus took the IdentityFile path from the SSH config file, based on the host name. But that's an extra feature ;). PSequel allows for host name (instead of IP), but you still have to provide identity file path manually.

Hope this helps. Just purchased TablePlus, looking forward to making great use of it :).

**Comment by huyphams** [comment]
Hi it respects ssh/config now:
Download (this is a build with production mode): https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

<img width="612" alt="respect config" src="https://user-images.githubusercontent.com/3654622/35821610-2d7d4648-0adc-11e8-914e-de9cf73025c7.png">

**Comment by mkarnicki** [comment]
@huyphams I'm stoked you started working on this!

I have a host configured in ~/.ssh/config. When I type in terminal:
`$ ssh host-name`
it properly connects to the host using a username and private key defined in ~/.ssh/config

However, I see this message when I followed your screenshot instructions (after downloading TablePlus from dropbox):

<img width="506" alt="screen shot 2018-02-05 at 23 38 53" src="https://user-images.githubusercontent.com/2966794/35832603-2e22c95a-0ace-11e8-9d2e-e5f46498a6b5.png">

This is part of my config:

```
Host host-name-here
  User user-name-here
  HostName ip-here
  IdentityFile ~/.ssh/key-name-here
```

Any ideas or how I could debug further? The private key doesn't have a passphrase defined (it is passphrase-less).

**Comment by mkarnicki** [comment]
@huyphams (I removed my previous comment, chose the wrong host).

I confirm this works GREAT! Thank you, I'm excited about TablePlus :)!

**Comment by huyphams** [comment]
Yup, I need to make this form more clear because you don't need to specify the username, password or the server port.
P/s: There is an annoying bug in 10.11, the white background in textfield, it gave me cancer 😄:
<img width="476" alt="screen shot 2018-02-06 at 11 54 26 am" src="https://user-images.githubusercontent.com/3654622/35842412-831b9714-0b34-11e8-93d1-9d17cf920911.png">

**Comment by davidolrik** [comment]
I think I have found one minor bug, when disconnecting and reconnecting the ssh connection the database connection is not reconnected.

**Comment by huyphams** [comment]
Thanks @davidolrik, but is it hang or something?

**Comment by mkarnicki** [comment]
I can't confirm that, seems all is working well. @davidolrik please try to be as detailed as you can in your follow up comment, thanks.

**Comment by davidolrik** [comment]
Yes it hangs, the timer in the bottom left just keeps counting away.

It also happens if I leave the window open, and don't use it for extended periods of time.

**Comment by huyphams** [comment]
hey, thanks for your helpful information.
We have two options:
1. Auto-reconnect: stick on => TablePlus will try to reconnect if the connection failed in the background.
2. Keeps connection alive: TablePlus sends a ping to sever to keep the connection alive.

If the connection failed while you sending a query, TablePlus also tries to reconnect first.

Seems TablePlus got trouble with ssh, everything is hanging because it waiting too long for ssh-timeout.

<img width="612" alt="options" src="https://user-images.githubusercontent.com/3654622/35980062-6248b3e8-0d1c-11e8-85e2-a303f6504d6d.png">

**Comment by davidolrik** [comment]
I think I know what the problem is.

The MySQL I'm connecting to is configured to aggressively close connections if they aren't used.
I think the cut-of-is set at around 10 seconds.

So the bug must be in the statement executer, that fails to notice that the connection has gone bad.

**Comment by davidolrik** [comment]
I have both of those options turned on.

**Comment by huyphams** [comment]
That's too bad, I set the ping is 30 second 🤣probably I will put a config here, then the user can set their period.

**Comment by davidolrik** [comment]
I don't have this problem in Sequel Pro, maybe they are pinging the connection before executing the query.

**Comment by huyphams** [comment]
Sequel Pro uses sshd for tunneling see [here](https://medium.com/@huyphams/how-using-ssh-tunneling-in-database-tools-might-leak-your-connection-forever-c6d48ff18746),  it's handled automatically by OS, and probably they sent ping more frequency.
Btw, I got the bug, will fix it in next update.

Thank you so much.

**Comment by davidolrik** [comment]
I found a different solution.

Immediately upon connecting, I execute `set session wait_timeout=3600;` which will let the ping work as intended. (This is specifically for MySQL)

**Comment by theflow** [comment]
It's not respecting the ssh/config for me. Is there any way to see some debug output of the connection attempt?

**Comment by huyphams** [comment]
Hey can you share me the screenshot of your connection config? this is mine with ssh/config.

<img width="612" alt="screen shot 2018-02-21 at 7 59 26 pm" src="https://user-images.githubusercontent.com/3654622/36481249-d33f9bb4-1741-11e8-8f38-bee3d34fd56e.png">

**Comment by theflow** [comment]
yeah, I saw the comments earlier, mine looks the same. Are you actually parsing the ssh/config or relying on a library that uses it? Anything that could be wrong in the .ssh/config format? (it works with ssh)

![connection___](https://user-images.githubusercontent.com/1552/36481877-8aa6ad96-1711-11e8-8113-a4f7e57471b0.png)

**Comment by huyphams** [comment]
I used the official API from libssh to handle the config. This is my ssh config.

```
Host tinydev
HostName <the host ip>
User root
```

The location of the config is ~/.ssh/config.

**Comment by nifoc** [comment]
I think I'm running into the same problem.

**.ssh/config**

```
Host mysite.io
  HostName IP_HERE
  User daniel
  Port 20022
  ForwardAgent yes
  PreferredAuthentications publickey
  IdentitiesOnly yes
  IdentityFile ~/.ssh/mysite
```

**TablePlus** (no manual `IdentityFile`)

![bildschirmfoto 2018-03-21 um 22 21 55-optimized](https://user-images.githubusercontent.com/222412/37738180-72dc7a14-2d56-11e8-9583-9cf4a821d4bf.png)

Clicking "Connect" does "nothing". It doesn't connect and simply runs into a timeout (I think).
Is there any way to debug the TablePlus SSH connection?
Running `ssh mysite.io` in a terminal works without any issues,

**Comment by itsdeezy** [comment]
@huyphams is there any work arounds? I tried explicitly importing an identity, still no dice.

**Comment by huyphams** [comment]
I'm trying with the identity, I will report you asap.

**Comment by 2b** [comment]
Hello.

I have same problem. Build 100 from Setapp.

![screen capture on 2018-04-15 at 20-29-57](https://user-images.githubusercontent.com/829041/38781378-4a6a19fc-40ec-11e8-9437-7add8432e743.gif)

**Comment by 2b** [comment]
I've completely emptied ~/.ssh/config, to make sure that problem isn't in additional ssh-parametres or spaces-markup, so I just added next 3 rows to ~/.ssh/config:

Host localhost
HostName 127.0.0.1
User root

And result was the same.

**Comment by itsdeezy** [comment]
@huyphams I believe my issue is actually related to #344

**Comment by huyphams** [comment]
Hey, @itsdeezy thanks for pointing it out. We have a release tomorrow, because of time constraints so I can't ship this bugfix in that build. 
We can expect that it will be fixed in build 102 (next week).

**Comment by huyphams** [comment]
Hi @itsdeezy I have implemented keyboard interactive support in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Can you give it a try?

**Comment by itsdeezy** [comment]
hey @huyphams,
tried out build 103, seems like 2fa is getting to where it asks for my login on my phone. However, it's stuck at the `Connecting to database...` stage.
![screen shot 2018-04-30 at 12 28 00 pm](https://user-images.githubusercontent.com/3641047/39438379-f7ccc3de-4c71-11e8-8b90-3eae57eed334.png)

Any way I can run this in verbose? maybe a console mode so I can give you some logs?

**Comment by huyphams** [comment]
Unfortunately, I turned off logging on production. There is no `two-factor authentication` in SSH. It's keyboard-interactive. The `two-factor authentication` is a method that server sends a question to the client and verify the connection after connected.
I have tested with my setup and it works, probably there are some edge cases that I missed.
Thanks for the report, I will try to reproduce it.

**Comment by sfdye** [comment]
Does Tableplus supports these two ssh config options?
```
   AddKeysToAgent yes
   UseKeychain yes   
```

I can't get it to work on `2.8.2 (256)` 😞

**Comment by christoph-kluge** [comment]
Since I stumbled across this ticket first and I've still tried to figure out why it's not working. I thought it might be useful to add some references to the other tickets here.  

If you use `Include`-statements then this could be a potential reason. This seems to be not implemented yet. Here are the referencing tickets #608 and #775

**Comment by mpyw** [comment]
This comment helped me:
https://github.com/TablePlus/TablePlus/issues/2531#issuecomment-1071949787
