### ISSUE TITLE
[Feature Request] Hide Columns from Column Menu

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1661]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): all

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.0 (Build 286)

It would be great if columns could be hidden from the column right-click menu. This could be reset using the current "Columns" button in the lower right corner.

**Comment by huyphams** [comment]
I've implemented this feature, it will be released in the next update, thanks @chrschmitz for the suggestion. I'm closing this issue for now to reduce the number of issues 👍

**Comment by bartoszhernas** [comment]
Not sure if I am missing something, but I kind of expected that hiding column would not try to fetch it. My use case is that I have a column that sometimes contains up to 20MB html data, and browsing the table in TablePlus with this column takes a while (and makes unnecessary load on DB). Is there a way to have TablePlus not ask for specific column from DB?
