### ISSUE TITLE
Can't connect to a Heroku Postgres instance

### ISSUE THREAD

**Issue by 2mol** [TablePlus/TablePlus#1664]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

252

3. The steps to reproduce this issue:

Enter the connection details from Heroku

I get

```
could not connect to server: Unknown error
	Is the server running on host "ec2-54-246-89-234.eu-west-1.compute.amazonaws.com" (54.246.89.234) and accepting
	TCP/IP connections on port 5432?
```

The connection works with any other tool.

**Comment by huyphams** [comment]
Hi @2mol could you double-check the URL and also update the TablePlus client to the build 286?

**Comment by 2mol** [comment]
Done, still the same error though. I'm guessing the Heroku certificate is weird? I know they don't provide certs that are valid for the current domain because they rotate the addresses pretty often. Postico first asks me if I want to trust the cert.

**Comment by huyphams** [comment]
it's weird because I have the same Heroku connection, you can take a look at this form.
<img width="612" alt="Screen Shot 2020-01-17 at 11 13 28 AM" src="https://user-images.githubusercontent.com/3654622/72622881-7e5a4700-391a-11ea-96e5-2fb314c13670.png">

**Comment by 2mol** [comment]
Hi! I had something blocking the network connection, so it looks like the fault was all on my side! It works now, I apologise for using up your time. Thanks for your help!
