### ISSUE TITLE
Insert CSV fails & hangs

### ISSUE THREAD

**Issue by edcorcoran** [TablePlus/TablePlus#1666]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 8.0.2 (Redshift)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 286

3. The steps to reproduce this issue:
Connect to Redshift 
File > Import > From CSV
Select the attached file
Choose Create New Table (or select table created in advance)
Click Import

The Import process starts but hangs at 4.0 bytes and I have to Force Quit TablePlus. The appropriate table is created and the first twelve rows are inserted, but nothing after that. If I change the order of the rows in the CSV file, the first twelve rows are still the only ones inserted.

[insert_test_file.csv.zip](https://github.com/TablePlus/TablePlus/files/4079227/insert_test_file.csv.zip)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @edcorcoran this patch should fix the issue: https://www.dropbox.com/s/lgh81iqa7x6i3hu/TablePlus.dmg?dl=0
Thank you for letting me know!
