### ISSUE TITLE
[Feature Request] Visualize PostGIS data easily

### ISSUE THREAD

**Issue by achedeuzot** [TablePlus/TablePlus#1667]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 286

I'm a happy user of TablePlus. I'm working with a lot of Geo systems and PostGIS. I often have postgis columns (line, points, geometries) and it would be very helpful if there was an easy way of seeing the items on a map. Let's say I have imported GPS points or polygons, having them draws on a map would be a tremendous help. PgAdmin (https://www.pgadmin.org/) have this feature and it's a killer one for me which makes me go back to using PgAdmin when I need to debug some GPS related issues. 

I'd prefer to keep working in TablePlus but not having this feature is really a bummer. It would be awesome if you could add it some time in the future.

Keep up the good work,

**Comment by huyphams** [comment]
Hi @achedeuzot thank you for the suggestion, I think this issue is duplicated with https://github.com/TablePlus/TablePlus/issues/1527 and maybe https://github.com/TablePlus/TablePlus/issues/1436 which has been implemented on the beta build and hot-patch (link in that issue thread). Please try it and let me know your thoughts

**Comment by achedeuzot** [comment]
Hi ! Sorry I didn't find the existing thread :)

Awesome, I just tried it out, it's a lot better than the binary view that existed before. I seem to have a glitch with it though. When the overview of the area is displayed, it's under a tooltip that displays the full text of the cell so I can't really see the geometry overview: 

<img width="637" alt="Screenshot 2020-01-18 at 15 39 50" src="https://user-images.githubusercontent.com/460597/72665512-22222080-3a09-11ea-8b29-5dfb202bc0c9.png">

As a sub-request, are there any plans for adding a map background underneath geometries that seem like GPS coordinates ? It really helps me debug if a given geopoint is inside or outside a given area.

**Comment by huyphams** [comment]
Thanks @achedeuzot  I'm working on the glitch issue, also we have a plan to add map background in the future releases, no worries.

**Comment by huyphams** [comment]
Hi @achedeuzot please check this build https://www.dropbox.com/s/hijhy8j8b6ilpdr/TablePlus.dmg?dl=0 , TablePlus now supports map background:
<img width="1578" alt="map" src="https://user-images.githubusercontent.com/3654622/80909575-86b48180-8d53-11ea-88b8-39783d03d19e.png">
