### ISSUE TITLE
Feature request: Read only mode

### ISSUE THREAD

**Issue by marvelph** [TablePlus/TablePlus#1671]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    290

3. The steps to reproduce this issue:

Please add read-only mode as connection setting.
Regardless of the privileges of the database user, I want a function that guarantees work that does not destroy data.

**Comment by huyphams** [comment]
Hi @marvelph  TablePlus has a similar feature, you can turn on the safe mode at the highest level.
<img width="1101" alt="Screen Shot 2020-01-20 at 9 05 44 PM" src="https://user-images.githubusercontent.com/3654622/72766986-ad95e000-3bc8-11ea-859c-baf0d20da6fd.png">

More information: https://docs.tableplus.com/gui-tools/code-review-and-safemode/safe-mode

**Comment by marvelph** [comment]
Thank you @huyphams .
Is it possible to set the mode default in the connection settings?

**Comment by huyphams** [comment]
Hi @marvelph, unfortunately, no, it would cause a lot of trouble for the newcomer if we set it to default, you can clone the connection, TablePlus will also clone that setting.

**Comment by marvelph** [comment]
I understand.
It is inevitable.

**Comment by huyphams** [comment]
So I think it was the best solution we have at the moment, feel free to contact me via nick@tableplus.com if you run into any issue or have any suggestion regarding the safe mode feature!
