### ISSUE TITLE
Add title bar to New Workspace window

### ISSUE THREAD

**Issue by vmitchell85** [TablePlus/TablePlus#1672]
First off, thanks for some great software! It's been well worth the money paid!

The new workspace window doesn't have a title bar which looks nice but functionally makes me drag my top connection group off the window at least once a week.

I would prefer a title bar be put on the window so dragging it around is consistent with other MacOS applications.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 290

3. The steps to reproduce this issue: N/A

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @vmitchell85 Thank you for the suggestion, you can drag the Welcome Screen around by clicking anywhere on the left of the Window. I just wanna make sure if you're aware of it.

**Comment by vmitchell85** [comment]
@huyphams Thanks for the quick response. Yes, I am aware but it's counter-intuitive since every other application is dragged by the title bar.

**Comment by huyphams** [comment]
As a part of the redesign of the Welcome Screen, one of the options is that we will unify it with the Workspace. Here is the design in Linux version:
![image](https://user-images.githubusercontent.com/3654622/72811821-ca68fc80-3c36-11ea-9eb3-34dc0d5efb25.png)

**Comment by vmitchell85** [comment]
That would probably work for me. I'd be more than willing to help test it on MacOS if you'd like.

Thanks,
- Vince

**Comment by natebrunette** [comment]
I've also had this problem since I started using TablePlus and got just annoyed enough with it to come here and make this issue. Otherwise, great work, keep it up!

**Comment by huyphams** [comment]
Hi guys, please download this patch https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 it has an extra header space, where you can click and drag the window.

**Comment by vmitchell85** [comment]
@huyphams That works great, just enough for me to grab!

Thanks for taking the time to add that space.

As far as I'm concerned this resolves the issue for me, not sure about @natebrunette ...

**Comment by natebrunette** [comment]
This is perfect

**Comment by huyphams** [comment]
Thanks, guys, I will close the issue for now. The change will be released in the next update!
