### ISSUE TITLE
Feature Request: Auto select first database on shortcut

### ISSUE THREAD

**Issue by markwalet** [TablePlus/TablePlus#1675]
One of my favorite shortcuts is Command+K. It opens a list with databases in the current connections and lets you directly search the databases by name. It works a lot like the shortcut in Slack.

Right now, when you have found the correct database, you first have to press down before it selects the first database. When you press enter it opens that database.

What I'd like to see improved here is an autoselection of the first database. When enter is pressed while the focus is on the input field, the databases popup just get's closed, without changing databases. It should instead, open the database at the top of the list.

Most of the time in local development, I know the database names by heart. And because I switch **a lot** between databases, this could really be a timesaver for me.

**Comment by huyphams** [comment]
It sounds like a Command + P, which already auto-select the first objects, includes the Database. But sure, we should allow it in Command + K too.

**Comment by markwalet** [comment]
Oh really? I didn't know about that shortcut.

Unrelated to this:
I quickly saw in the preferences pane that you could change your shortcuts but I didn't see Command+K there. Did I miss them or is there a special reason these aren't included. If not. I'll create a separate issue for that.

**Comment by huyphams** [comment]
There are so many shortcuts that currently are not listed in the preferences. It's because many reasons. (It does not allow to change, It's hardcoded by macOS and couldn't be changed)

**Comment by huyphams** [comment]
It has been implemented in this patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 thank you!
