### ISSUE TITLE
[Bug] Postgis geom data always returned as EWKT

### ISSUE THREAD

**Issue by kbarton-catalyze** [TablePlus/TablePlus#1676]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.1.0 (290)

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

When selecting geometry data it should be displayed in native format unless the query specifies a different format. EWKT format is returned when doing a simple `select geom`, as well as running `select st_geomfromewkt(geom) from table`. This is invalid. If a user wants their data displayed in EWKT, there is a simple function for that.

**Comment by kbarton-catalyze** [comment]
This issue is making TablePlus unusable for me. I'll have to switch to PGAdmin until this is fixed.

**Comment by huyphams** [comment]
Thanks, @kbarton-catalyze for the insight, we might put the config in the setting and let the user choose their default Geometry decoder.
You can workaround by cast the geometry to text, TablePlus will not convert it to WKT.

SELECT geom::text FROM generic_geo;

Just out of curiosity why do you prefer the hex format over the WKT format?

**Comment by kbarton-catalyze** [comment]
Thank you, a config setting would definitely be useful. We use it for testing various spatial data management scripts.

**Comment by spolloni** [comment]
+1 on this

**Comment by huyphams** [comment]
Hi guys, there is a new config in the preferences. If you disable it, TablePlus will not convert the spatial data to WKT.
Download the patch here: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
<img width="921" alt="abc" src="https://user-images.githubusercontent.com/3654622/74088472-8779a680-4ac9-11ea-9d48-3b589099bd6a.png">
