### ISSUE TITLE
Out of memory error while exporting large table

### ISSUE THREAD

**Issue by phil93883** [TablePlus/TablePlus#1677]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):  MariaDB 10.1.26

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  3.1.0 (290)

3. The steps to reproduce this issue: Export a large table (100 million records +) on a machine with 16GB RAM

Noted: If the bug is related to data, please attach an example SQL data.

I'm using the latest version (3.1.0 290) and this still happens. On a new MacBook Pro with 16GB RAM, I'm trying to export a table with around 110 million rows. I get the same out of memory error as above at around the 52m mark. This is exporting from MariaDB.

This is the same issue as #1492, which was closed.  It still happens.

**Comment by huyphams** [comment]
Thanks @phil93883 let me check it.

**Comment by phil93883** [comment]
Just to add, this occurs WITHOUT using gzip compression.

**Comment by phil93883** [comment]
Hello, have you taken a look at this?

**Comment by huyphams** [comment]
Hopefully, I can release a hot patch next week @phil93883

**Comment by phil93883** [comment]
Henry,

I'm trying the new version and it is worse than before.  It maxes out my RAM, my swap, and is basically unusable for large exports.

<img width="929" alt="tplus" src="https://user-images.githubusercontent.com/59853419/74789638-49c40d00-5283-11ea-95d8-1c4dd1d8b41b.png">

**Comment by huyphams** [comment]
I think I found the issue. Let me try to fix it.

**Comment by huyphams** [comment]
Hi @phil93883 please try this patch and see how it goes: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
