### ISSUE TITLE
[Build 80] Minor bug - Row detail pane "column_name" field disappears

### ISSUE THREAD

**Issue by horo42** [TablePlus/TablePlus#168]
From a comment in closed issue #164 

Initial state

<img width="218" alt="screen shot 2017-12-28 at 15 01 48" src="https://user-images.githubusercontent.com/5323731/34412875-0e1f1c06-ebe0-11e7-9b78-3451d88633ab.png">

I type "sstring" (or anything that is enough for TablePlus to break the resulting tag into the next line). Images of before and after pressing enter:

<img width="219" alt="screen shot 2017-12-28 at 15 02 55" src="https://user-images.githubusercontent.com/5323731/34412900-4929b446-ebe0-11e7-9754-8233b317e3f6.png">
<img width="220" alt="screen shot 2017-12-28 at 15 03 01" src="https://user-images.githubusercontent.com/5323731/34412903-4c799f4e-ebe0-11e7-9e07-0f8fa8e6a750.png">

Now I click on the "cID" tag, and move it before the "bID" tag, so it's the first column in the list.

<img width="216" alt="screen shot 2017-12-28 at 15 04 05" src="https://user-images.githubusercontent.com/5323731/34412926-6e40bd06-ebe0-11e7-9fdb-5b7ce268f2eb.png">

Now I hit CMD + z in hopes of bringing back the input field, and it disappears completely.

<img width="213" alt="screen shot 2017-12-28 at 15 04 48" src="https://user-images.githubusercontent.com/5323731/34412932-7e5b1984-ebe0-11e7-942f-85500e99bb23.png">

**Comment by huyphams** [comment]
Thanks for separate the issues (we can easily update/close after resolve). This issue related to Apple UI. It looks like Cocoa bug. I will investigate this issue in build 81.

**Comment by huyphams** [comment]
This build should fix this issue: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

Working with Apple UI likes an adventure

**Comment by horo42** [comment]
Confirmed, thank you :)
