### ISSUE TITLE
Result row limit ignored when last line is a comment

### ISSUE THREAD

**Issue by Alanaktion** [TablePlus/TablePlus#1683]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
291

3. The steps to reproduce this issue:
- Open a new SQL query
- Set a row limit (e.g. 1000 rows)
- Run a query ending with a comment that has more than the limited results

For example:

```sql
select *
from users
-- where
```

![image](https://user-images.githubusercontent.com/236490/73213937-651d7b80-410e-11ea-8131-2762fb3415d5.png)

The result should be limited correctly to the amount specified, but the `LIMIT` is added to the same line as the comment so it's ignored. The query actually executed (visible in the console log) is:

```sql
select *
from users
-- where LIMIT 1000;
```

I've noticed a few similar issues to this, where single-line comments interfere with other parts of the query execution in odd ways, but this is one that seems particularly risky.

This could be fixable somewhat naively by just adding a newline before appending the `LIMIT`, but it could be helpful for the editor to actually parse the query to remove comments (though that introduces a lot more complexity and potentially bugs).

**Comment by huyphams** [comment]
Thanks, @Alanaktion I can reproduce and fix it in this hot-patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
When using this build, it will prompt you to update (because I see you're using the beta build). Please do not update, because you will lose the patch.

**Comment by Alanaktion** [comment]
Looks good to me, seems to fix the issue. I can trigger similar behavior with an unclosed multi-line comment, but that's not an issue with TablePlus, that's just a syntax error. Thanks for the fast response!

**Comment by huyphams** [comment]
Thanks for confirming, however, the that build still not workings with this case (more than one single line comment):
```
SELECT
  *
FROM
  "comments"
-- LIMIT 1000;
-- LIMIT 1000;
```
This patch should fix it: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
