### ISSUE TITLE
Oracle 19 Connectivity

### ISSUE THREAD

**Issue by advaitk** [TablePlus/TablePlus#1684]
1. Which driver are you using and version of it 

>Not quite sure, do I have to install the drivers separately? I've not installed any (instantclient) on my workstation (OSX Catalina 10.15.2)

>I'm trying to connect to an Oracle 19.0.0.0.0 server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

>Version 3.1.0 (291)

3. The steps to reproduce this issue:

>Connection is resulting in error:

> Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

**Comment by huyphams** [comment]
Hi @advaitk TablePlus currently is using the Oracle 19 driver. so it would not be a problem. Maybe you're using the wrong port?

**Comment by advaitk** [comment]
@huyphams Not quite sure what resolved it, but i had to reboot my mac for an update, and post reboot connectivity started working. No changes were made to the saved connection configs.
I'll debug some more if I can reproduce it again, otherwise we can close this issue.
thanks for the quick response though.

**Comment by huyphams** [comment]
Thanks, please let me know if you see it again then I will reopen the issue.
