### ISSUE TITLE
auto-align width of the columns in data view

### ISSUE THREAD

**Issue by JyrkiLindblum** [TablePlus/TablePlus#1685]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @JyrkiLindblum TablePlus does auto-expand the width of the column in the data view, however, it only affects the first time you open the table or run a query (or continue running the same query) and then TablePlus will cache the column size. It also will remember if you resize the column. Please let me know if you need anything else or found a bug, thank you!
