### ISSUE TITLE
case-insensitive search by field in data view

### ISSUE THREAD

**Issue by JyrkiLindblum** [TablePlus/TablePlus#1686]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @JyrkiLindblum thanks for the feedback, however it's impossible for me to investigate the issue because I didn't answer the issue questions. TablePlus does support case insensitive for both MySQL and PostgreSQL.
I'm closing this issue for now, feel free to re-open it if you need anything else.
