### ISSUE TITLE
Enhancement: Nested Connection Groups

### ISSUE THREAD

**Issue by slastrina** [TablePlus/TablePlus#1688]
Hi, id like to request increased nesting for connection groups.

I typically work with multiple customers with multiple environments, it would be ideal to be able to group my connections for instance by:

->Customer1 (GROUP)
---->Environment1 (GROUP)
------->Database1 (CONNECTION)
------->Database2 (CONNECTION)

Im currently prefixing groups to sort of work around this but it would be nice to support more levels of nesting

Thanks In Advance For Viewing
Sam

**Comment by huyphams** [comment]
Hi, we are working on this issue, hopefully, we can make it in the next release.

**Comment by slastrina** [comment]
> Hi, we are working on this issue, hopefully, we can make it in the next release.

Fantastic news, looking forward to the release. Thanks

**Comment by huyphams** [comment]
I've updated the patch which supports nested group in this issue: https://github.com/TablePlus/TablePlus/issues/163
I'm closing this issue for now because it duplicates with #163.
