### ISSUE TITLE
Enhancement: View password for a given connection

### ISSUE THREAD

**Issue by slastrina** [TablePlus/TablePlus#1689]
Hi, I notice TablePlus on mac can use keychain to store the password, i was hoping to request a capability to show the password within Tableplus or at least have tableplus open the keychain at the appropriate key for the connection in order to authenticate and view the password. 

Unfortunately the keychain entries dont have anything identifiable on them other than the uuid in the account field, its difficult to relate back to the actual connection

**Comment by huyphams** [comment]
Hi @slastrina it was not designed for that. There is   an easier way to see the connection password. Just select the connection and press command + c or right click > copy as URL and paste it somewhere, then you will see the password.

**Comment by slastrina** [comment]
Hi @huyphams, thats good to know, didnt realise i could copy it out that easily, thanks

**Comment by huyphams** [comment]
Can we close this issue @slastrina ?

**Comment by slastrina** [comment]
Yep we can, thanks

**Comment by xyoun** [comment]
actually this is not very convenient, especially there are some especial characters in the password. for example password `!@#$%^&*()` will be showed as `!%40%23$%25%5E&*()`, we need to url decode it before use it.

**Comment by edbrannin** [comment]
@huyphams Is it really not feasible to have an [open/closed eye or something in the password input box](https://www.csestack.org/hide-show-password-eye-icon-html-javascript/), to toggle visibility?
