### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Sparclex** [TablePlus/TablePlus#169]
Hi 

I'm unable to update my tableplus application. I always get the error (screenshot) even tho I moved it to the applications folder. 

![image](https://user-images.githubusercontent.com/2805213/34467187-5b502d46-eeea-11e7-88eb-8d24a168b095.png)

Thanks for your help.

**Comment by huyphams** [comment]
The popup message says it all. Have you try to move TablePlua to Application folder?

**Comment by Sparclex** [comment]
Well yes. It is already in the applications folder: 
![image](https://user-images.githubusercontent.com/2805213/34467234-9bb6adfa-eeeb-11e7-9a29-55726afa675c.png)

**Comment by huyphams** [comment]
Well, TablePlus got trouble to replace itself, probably beacause of read-only permission. Which version of TablePlus and OSX are you on?

**Comment by Sparclex** [comment]
![image](https://user-images.githubusercontent.com/2805213/34467395-d0e82af8-eef0-11e7-9067-31c50c02dab8.png)
![image](https://user-images.githubusercontent.com/2805213/34467400-dc0e64b0-eef0-11e7-935b-9dd98a72c5fa.png)

**Comment by huyphams** [comment]
Hi @Sparclex, You are on MacOS High Sierra and it's unstable. I'm on High Sierra and it works fine, can you upgrade to the official release of High Sierra?

Btw, TablePlus 76 is out date a bit. We are on build 80 now, there are 50 changes since build 76.

**Comment by Sparclex** [comment]
Ok since its most likely a problem with the mac os beta I will close this issue and open it again, if I still have issues after changing to the stable version. Thanks for your help.
