### ISSUE TITLE
[Bug] Wrap selected text in quotes

### ISSUE THREAD

**Issue by robertobardi** [TablePlus/TablePlus#1690]
1. MySQL 5.6.42

2. build 290

When I try to use this function repeatedly, for example to use the ' before and after the desired text, I often do not get the desired result, but simply the ' character

let's imagine we have this situation on the SQL query panel:
003302729
003302729
003302729
003302729
003302729
003302729
003302729
003302729
003302729
003302729
003302729
003302729
003302729

If I double click on the single number for add ' character, i obtain:
'003302729'
'003302729'
'
'
'003302729'
'003302729'
'003302729'
'003302729'
'003302729'
'003302729'
'
'
'003302729'

Thanks and regards
Roberto

**Comment by robertobardi** [comment]
Hi huyphams, seems that with the last sw version (Build 296) the problem is solved!

**Comment by huyphams** [comment]
Thanks @robertobardi I will close this issue for now, please let me know if you run into this issue in the future.

**Comment by ErichDs** [comment]
Hey, I don't know if this is the right place to comment, but I'm facing a similar issue.

1. Postgresql 8.0.2 (redshift)
2. build 370
3. whe I select a text and add a single/double quote or brackets, it does not wrap the text, just leave a single char like:
 '
"
or
(

instead of 'example' / "example"/ (example)

is it a bug? I'm using a macbook.

**Comment by huyphams** [comment]
I don't understand your issue @ErichDs, could you show me the step to reproduce the issue?

**Comment by ErichDs** [comment]
Check below:
expected result is: 'example''
![example](https://user-images.githubusercontent.com/47831626/122423327-3652b000-cf64-11eb-8b40-a5627474c49b.gif)

**Comment by huyphams** [comment]
I think you're using the international keyboard. It's not possible to change this behavior on that keyboard.

**Comment by ErichDs** [comment]
got it! thanks!
