### ISSUE TITLE
Foreign key navigation not working with mysql8

### ISSUE THREAD

**Issue by matism** [TablePlus/TablePlus#1691]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

290

3. The steps to reproduce this issue:

Create an empty database with two tables with the fields id and name. Add a foreign key to one of the two tables and reference it to the id of the other table. The arrow in the referenced row does not show up:

![Screenshot 2020-01-30 at 16 08 35](https://user-images.githubusercontent.com/7680357/73461680-dc574780-437a-11ea-8876-3b27c286cc38.png)
![Screenshot 2020-01-30 at 16 08 43](https://user-images.githubusercontent.com/7680357/73461678-dc574780-437a-11ea-844e-51ef3ec8556f.png)
![Screenshot 2020-01-30 at 16 08 50](https://user-images.githubusercontent.com/7680357/73461676-dc574780-437a-11ea-9cdd-00fba4633a6f.png)

**Comment by matism** [comment]
It's working with the same procedure on MySQL 5.x.

**Comment by huyphams** [comment]
Hi, @matism could you please try adding the foreign key again on the MySQL 8 driver? I've tried multiple times and it works on my side.

**Comment by matism** [comment]
Hi Huy, just tried to alter the table again but after commiting my changes the foreign key field is EMPTY again. If it helps it's MySQL 8.0.17.

**Comment by huyphams** [comment]
Could you show me the result of
``` 
SHOW CREATE TABLE `test`;
```
And 
``` 
SHOW CREATE TABLE `test2`;
```
@matism thank you!

**Comment by matism** [comment]
Sure, here you go:

`CREATE TABLE "test" (
  "id" bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  "name" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE KEY "id" ("id")
)`

`CREATE TABLE "test2" (
  "id" bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  "test_id" bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE KEY "id" ("id"),
  KEY "test_id" ("test_id"),
  CONSTRAINT "test2_ibfk_1" FOREIGN KEY ("test_id") REFERENCES "test" ("id")
)`

**Comment by huyphams** [comment]
Could you show me the result when you run with MySQL 8 above? I see the test2 table has 3 columns but your result only shows 2 columns.
I created it with those commands above and it works.
<img width="1254" alt="Screen Shot 2020-01-31 at 4 32 33 AM" src="https://user-images.githubusercontent.com/3654622/73492153-b5ccf700-43e2-11ea-9083-b6f321ff239f.png">

**Comment by matism** [comment]
![Screenshot 2020-01-30 at 22 36 30](https://user-images.githubusercontent.com/7680357/73492501-14797d00-43b1-11ea-83e2-6c0522a76d76.png)
![Screenshot 2020-01-30 at 22 36 36](https://user-images.githubusercontent.com/7680357/73492496-14797d00-43b1-11ea-9de9-3a125727de45.png)
![Screenshot 2020-01-30 at 22 36 51](https://user-images.githubusercontent.com/7680357/73492494-14797d00-43b1-11ea-9d25-78525e21d3bd.png)
![Screenshot 2020-01-30 at 22 37 01](https://user-images.githubusercontent.com/7680357/73492492-13e0e680-43b1-11ea-8d3a-7d2059b70ddc.png)

**Comment by huyphams** [comment]
I mean from this screenshot where the issue happens, it has 3 columns. The one you send me only has 2 columns and it does not reproduce the issue on my side so I think it might be related to the data.
<img width="751" alt="abc" src="https://user-images.githubusercontent.com/3654622/73492669-bdd96680-43e3-11ea-8c24-deb74481f8a6.png">

**Comment by matism** [comment]
The third column doesn't matter. I just created the tables with the create statements I posted earlier and still getting the same problem -> foreign key stays EMPTY and foreign key navigation therefore not possible.

**Comment by matism** [comment]
Ah… that's interesting: I just toggled on the console log and copied the query that gets executed when showing the structure of my "test2" table. I manually ran it in the query editor and it shows the foreign key "test_id" although the structure view does not show it:

![Screenshot 2020-01-30 at 22 48 57](https://user-images.githubusercontent.com/7680357/73493328-d54c2b80-43b2-11ea-8768-af45703fa255.png)
![Screenshot 2020-01-30 at 22 49 13](https://user-images.githubusercontent.com/7680357/73493334-d7ae8580-43b2-11ea-9118-4449900c4174.png)

And here's the query:

```SQL
SELECT ordinal_position as ordinal_position,column_name as column_name,column_type AS data_type,character_set_name as character_set,collation_name as collation,is_nullable as is_nullable,column_default as column_default,extra as extra,column_name AS foreign_key,column_comment AS comment FROM information_schema.columns WHERE table_schema='test'AND table_name='test2';
```

**Comment by huyphams** [comment]
It was designed that way @matism it hard to explain but the result will be the same if you run it on MySQL 5. I think the real issue is the quote, I don't know why your creation statement uses double quotes but in my setup, it uses backtick. I'm finding a way to change it and see what's going on.
<img width="1655" alt="Screen Shot 2020-01-31 at 4 56 25 AM" src="https://user-images.githubusercontent.com/3654622/73493808-0abe3c80-43e6-11ea-9bca-ed96f496853a.png">

**Comment by huyphams** [comment]
Thanks @matism I updated this build, which can handle the double quote, please give it a try and see how's it going:
https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0

**Comment by matism** [comment]
I don't understand why it's working, but it is. Thanks a lot!

![Screenshot 2020-01-31 at 06 34 13](https://user-images.githubusercontent.com/7680357/73514978-f2edb500-43f3-11ea-9643-ba4e4109f883.png)
![Screenshot 2020-01-31 at 06 35 05](https://user-images.githubusercontent.com/7680357/73514982-f5e8a580-43f3-11ea-89ed-fd664ef3f459.png)

Maybe I am getting the double quotes because my os language is english although my keyboard and regional settings are german (austrian).

**Comment by huyphams** [comment]
Thank you for confirming. This fix will be released in the next release. I'm closing the issue for now to reduce the number of issues!
