### ISSUE TITLE
[Feature Request] Search for Information in Database or Schema

### ISSUE THREAD

**Issue by vpoguru** [TablePlus/TablePlus#1694]
It would be great if TablePlus could search for information in ALL tables of a database or schema. The search field above the items searches currently only for table names.

This idea is taken from [here](https://www.youtube.com/watch?v=R3g35QbS7mI).

**Comment by huyphams** [comment]
If you have a chance, please try this patch: https://www.dropbox.com/s/q18htnq1r0n6ysl/TablePlus.dmg?dl=0
Here is how to use it: https://twitter.com/TablePlus/status/1621376288509542401

Please let us know if you have any feedback!
