### ISSUE TITLE
Show comments on objects

### ISSUE THREAD

**Issue by doerwalter** [TablePlus/TablePlus#1695]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 12.1 (with Postgres.app)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 290

3. The steps to reproduce this issue:

I've created a procedure:
```sql
create schema errmsg;

CREATE OR REPLACE PROCEDURE errmsg.add(INOUT p_error text, p_message text)
 LANGUAGE plpgsql
AS $procedure$
begin
	if p_error is null or len(p_error) = 1 then
		p_error := E'\x01';
	end if;

	p_error := p_error || E'\x01\x01' || p_message || E'\x01';
end;
$procedure$
```

and a comment on this procedure

```sql
comment on procedure errmsg.add(p_error in out text, p_message in text) is 'Adds the global message `p_message` to the error messages in `p_error`.'
```

I would like to see and (and idealy be able to edit) this comment somewhere in the TablePlus UI for the procedure definition. Also it would be great if that comment gets displayed in the list of functions/procedures.

And of course many more object types in Postgres can be commented, so for those it would be also great if I could see the comments.

For info can be found here: https://www.postgresql.org/docs/current/sql-comment.html

**Comment by huyphams** [comment]
I've fixed a bug load function comment in this patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
maybe in the future, we will redesign the item viewer to support view/edit comment.

**Comment by huyphams** [comment]
Click the section, you will be able to see the comment.
<img width="1619" alt="Screen Shot 2020-02-06 at 12 52 12 PM" src="https://user-images.githubusercontent.com/3654622/73909617-b2a0a200-48df-11ea-8090-8d1e1d5807ea.png">

**Comment by doerwalter** [comment]
With this new version I can indeed see the comments for procedures and tables in the list, however it doesn't seem to work for views. I haven't checked anything else.

And of course this method won't work for displaying the comment on a schema, as there's no schema list. And displaying a schema comment in a table column only wouldn't make much sense anyway, as IMHO schema comments tend to be longer as they're the documentation for the whole schema. (We have schema comments that are several K long).

**Comment by huyphams** [comment]
We've added a way to add comment, if you're interested in it, you can download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
<img width="1665" alt="abc" src="https://user-images.githubusercontent.com/3654622/111115656-84d46500-8597-11eb-9cd8-a1f5637bb2c3.png">

**Comment by doerwalter** [comment]
With this change I can indeed edit the comments. However viewing multi line comments is cumbersome, and editing them nearly impossible (the only working approach is to copy line feeds from somewhere else and paste them into the comment editor).

There is still no way to edit or see the comments on views or schemas.

So IMHO this issue should be kept open until this is implemented.

**Comment by huyphams** [comment]
You can view the comment:
1. On the right sidebar,
2. Using middle mouse
3. Right click > quick look editor
4. Navigtate the red selection and hit command + return.

We will enable edit comment via quicklook and right sidebar on the official release.
