### ISSUE TITLE
Beautify @@session 

### ISSUE THREAD

**Issue by CrixuAMG** [TablePlus/TablePlus#1696]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.5.55

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.1.0 build 290

3. The steps to reproduce this issue:
Create any query using @@sesssion in a CONVERT_TZ() call, then use beautify, the @@ will be separated from session, causing the query to fail next time it is run.

**Comment by iforwms** [comment]
Can confirm, same issue with `@@global`.
