### ISSUE TITLE
Links in Query Results on columns with foreign key relationships don't always appear

### ISSUE THREAD

**Issue by shawnhooper** [TablePlus/TablePlus#1698]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.x 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build # 290

3. The steps to reproduce this issue:

For example, if I run 

SELECT * FROM memberships 

My **user_id** column should have a link to that record in the Users table. (The arrow showing up next to the value in that cell) 

Sometimes it doesn't appear.  Running the query again (sometimes more than once required) fixes it.

**Comment by huyphams** [comment]
Thanks @shawnhooper this patch should fix the issue: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
Let me know if you're still seeing the issue.

**Comment by shawnhooper** [comment]
Thanks Henry!  That did the trick!



*SHAWN M. HOOPER, Partner*Fivesense Technologies Inc.
+1-613-799-7860
shawn@fivesense.ca
fivesense.ca
