### ISSUE TITLE
Add Window Draggable Area to Connection Selection Panel

### ISSUE THREAD

**Issue by parhampb** [TablePlus/TablePlus#1699]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
290

3. The steps to reproduce this issue:
Mac specific. Sometimes when the screen is connected to external displays then disconnected/reconnected, some of the windows move around. Now some windows go to the edge of the screen. If the draggable part of the windows moves over the edge, there's no way of moving the window back. It would be good to have a small draggable area at the top of the connection selection panel too for these scenarios. Right now, I've just used Magnet to snap the window to a side, then drag it to where it should be

**Comment by huyphams** [comment]
Hi @parhampb thank you, please try this patch and see how's it going: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 there is a small space on the top of the welcome screen.

**Comment by parhampb** [comment]
Thanks for that @huyphams, works perfectly 👍
