### ISSUE TITLE
Backup error: syntax error near unexpected token

### ISSUE THREAD

**Issue by wuestkamp** [TablePlus/TablePlus#1703]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.1.0 (290)

3. The steps to reproduce this issue:
Backup a database

This results in no export file created and this error:

```
Backup database 'db'
Dumping...
/bin/sh: -c: line 0: syntax error near unexpected token `)'
/bin/sh: -c: line 0: `./dump_pg_10.5 --file="/Users/user/db.dump" --format=custom --blobs postgres://db:XXXX@127.0.0.1:5432/db'

Backup database completed
```

**Comment by huyphams** [comment]
Hi @wuestkamp thank you for the feedback, the bug has been fixed recently on this hotpatch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
Please let me know if you're still seeing the bug.

**Comment by wuestkamp** [comment]
Thanks. Will this fix be included in an official release soon?

**Comment by huyphams** [comment]
Yep, this month, if you see a feature/bugfix that is included in the hot patch, it will be released within a month./
