### ISSUE TITLE
Duplicating record with identity (SQL Server)

### ISSUE THREAD

**Issue by greg99999** [TablePlus/TablePlus#1705]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server DBVERSION_74

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 292

3. The steps to reproduce this issue:
Open table with identity column. Highlight row. Right click and choose "Duplicate".  

Bug 1: Highlight the duplicated row before a commit: The duplicated row in the grid shows the identity column as "DEFAULT". Row Detail on the right shows the source row's identity.  

Bug 2: Unable to commit record. (Msg: 339, Line 1, State: 1, Level: 16
DEFAULT or NULL are not allowed as explicit identity values.
All changes were reverted (DDL statements can't be reverted).)

Sample SQL (edited for brevity: Column HEIdentity is the identity column:

INSERT INTO [dbo].[HSELEM] ([HEIdentity], [helName]) VALUES (DEFAULT, N'Camden Contemporary');

**Comment by huyphams** [comment]
Thanks, I've fixed it in the beta release.
