### ISSUE TITLE
Can't download TablePlus version with Oracle 

### ISSUE THREAD

**Issue by henrycodebreaker** [TablePlus/TablePlus#1707]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oracle

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v 3.1.0 (Build 290) Mac Os 10.15.3

3. The steps to reproduce this issue:
Create a new connection to Oracle DB. Press "connect". Pop-up appears "Do you want to download the build which support Oracle". Press "Download
<img width="456" alt="Screen Shot 2020-02-07 at 8 22 57 PM" src="https://user-images.githubusercontent.com/40254517/74032932-b28bc980-49e7-11ea-8c76-5ce0d7a96b4c.png">
<img width="1186" alt="Screen Shot 2020-02-07 at 8 23 08 PM" src="https://user-images.githubusercontent.com/40254517/74032940-b6b7e700-49e7-11ea-95d3-85d33c9a9cfb.png">

". Nothing happens and stuck on loading screen.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @henrycodebreaker please restart the app try again or goto TablePlus > Preferences... and select Enable Receive Beta Updates... after that, you can check for update and download that build.

**Comment by henrycodebreaker** [comment]
Thank you that worked
