### ISSUE TITLE
query history does not include auto limit LIMIT

### ISSUE THREAD

**Issue by chdsbd** [TablePlus/TablePlus#1712]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.1.0 (290)

3. The steps to reproduce this issue:

If I run a query with auto limiting enabled, the limit imposed by the auto limiting does not appear in the query history.

I would expect that the query sent to the database would be the query shown in the query history view.

![image](https://user-images.githubusercontent.com/1929960/74166722-10413100-4bf5-11ea-9cdc-77d309981b2a.png)

**Comment by huyphams** [comment]
Thank you, this issue is fixed in the beta release!
