### ISSUE TITLE
Query Editor Suggestion: Autocomplete field names on SELECT

### ISSUE THREAD

**Issue by shawnhooper** [TablePlus/TablePlus#1713]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

290

3. Suggestion: 

I would love there to be a shortcut that would autocomplete field names on select.  For example, in the query editor if I typed

`SELECT users.*<TAB>`

the editor would update the query with:

`SELECT users.id, users.first_name, users.last_name (etc. etc.) `

**Comment by huyphams** [comment]
Hi @shawnhooper, TablePlus already has that feature. have you tried to select the * in auto-completion?
<img width="770" alt="Screen Shot 2020-02-12 at 12 08 45 AM" src="https://user-images.githubusercontent.com/3654622/74260311-e2123d00-4d2b-11ea-8814-16e05c7e89ca.png">

**Comment by shawnhooper** [comment]
@huyphams Great!   I hadn't tried it with the table name.  I was just trying to do SELECT * and nothing was coming up :)    Thanks!
