### ISSUE TITLE
MySQL Stored Procedures displaying incorrectly   

### ISSUE THREAD

**Issue by michaelbarley** [TablePlus/TablePlus#1717]
All my stored procedures in my database are just showing up as 

`CREATE PROCEDURE`

Very strangely, they all are working correctly. This issue only appears when I am at home using my home wifi; when I am at work I can see them fine. We have been looking into it at work and can't seem to find anything that would hide them for me. my IP has been whitelisted  

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 290

3. The steps to reproduce this issue:
When I click on any stored procedure when I am working remotely, I'm using Virgin Media Wifi.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @michaelbarley it seems your issue is related to this https://github.com/TablePlus/TablePlus/issues/1625 Please confirm it's your issue.

**Comment by michaelbarley** [comment]
Hello @huyphams yes seems to be.
