### ISSUE TITLE
Performance issue when importing large data sets

### ISSUE THREAD

**Issue by pckuijper** [TablePlus/TablePlus#1719]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**MySQL 5.7.22**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Build 290**

3. The steps to reproduce this issue:
Export large (10+ MB) of data from a database
Import data into another database

After looking at the file SQL file being generated compared to another tool (sequal pro in this case)
it looks like you are creating an insert statement for every row in the database.
This can quickly add up to 10000+ inserts which seems to be slowing the whole thing down.

Sequal pro solved this issue by splitting the insert statements by a certain amount of KiB of rows of data.
This would also decrease file size as the export i'm currently testing with is 14mb in size from TablePlus vs 5mb from Sequal Pro.

Another performance upgrade could be to allow autocommit to be set to 0.
This has already been requested here: https://github.com/TablePlus/TablePlus/issues/1597

**Comment by huyphams** [comment]
Hi @pckuijper we've supported it in the beta release, you can try that patch here: https://www.dropbox.com/s/gp730wwbd2kbkn6/TablePlus.dmg?dl=0

**Comment by pckuijper** [comment]
hey @huyphams thanks for this! Quickly tested it and it is **much** faster than the previous solution!
I've forwarded the link to my colleagues straight away!

Is there a changelog available per chance of the new updates from 290 to 295?

**Comment by huyphams** [comment]
It's here:
<img width="812" alt="Screen Shot 2020-02-12 at 9 37 19 PM" src="https://user-images.githubusercontent.com/3654622/74344916-dbdd9880-4ddf-11ea-8489-2c476509a4bb.png">

**Comment by joelhoward** [comment]
Awesome.  I can confirm my imports from TablePlus are running much faster now also.  I'll go ahead and close my #1597 issue as the update seems to resolve my performance issues.
