### ISSUE TITLE
Add option to hide Functions

### ISSUE THREAD

**Issue by eXorus** [TablePlus/TablePlus#172]
Helo,

Thanks for your software, it's very nice and clean.

But with the new version I have "Functions" that display auto, when I search a table I can't see my result because there are too much functions.

So I need to close Functions each time.

**Comment by huyphams** [comment]
Hey @eXorus thanks, I just tested with my database (has hstore extension). There are a lot of functions. TablePlus should remember the section state (open/close). Will come back in about 30 mins for the hotfix.

**Comment by huyphams** [comment]
@eXorus Can you try this build and let me know if it fixes your issue: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by eXorus** [comment]
Yes it's better now the state is remembered.
