### ISSUE TITLE
Import .sql file broken since build 294

### ISSUE THREAD

**Issue by milhouse1337** [TablePlus/TablePlus#1720]
Hi,

The import feature seems to be broken since the last update (294). It just crashes the app completely.

Driver: MariaDB
Version: 3.1.2 (build 294)

Import file (just an empty test):
https://gist.github.com/milhouse1337/e6a996ecc20941a44218c0ef02b9f493
Crash report:
https://gist.github.com/milhouse1337/bd52ab85d79fe3b997fa1353ed8c8500

Thank you!

**Comment by huyphams** [comment]
Hi @milhouse1337 please wait for us a min, the fixed build is on its way.

**Comment by huyphams** [comment]
Hi @milhouse1337 please check out the build 296, I apologize for the issue.

**Comment by milhouse1337** [comment]
I do confirm it works. 🚀

Awesome work btw! The fix for the 250KB chunks for the exports is also fixed, you just made my day. 🤓

Thank you!
