### ISSUE TITLE
Saved connections gets deleted then moving in sort order

### ISSUE THREAD

**Issue by emilgrip** [TablePlus/TablePlus#1722]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.1.2 (296)

3. The steps to reproduce this issue:
In main view when moving saved connections up/down in sort order, they will be deleted when trying to move them.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @emilgrip I could not reproduce it, are you sure that it was deleted or moved into some group?

**Comment by emilgrip** [comment]
Hi, it seems to happen somewhat sporadically @huyphams 

Screen record: https://drive.google.com/file/d/1USjSzEQxk6UjqCAOsz5IAqThO_NLAxEr/view?usp=sharing

**Comment by huyphams** [comment]
Hi @emilgrip thank you for reporting, I've fixed it in this patch: https://www.dropbox.com/s/fwfwodi5z9f81ec/tableplus.dmg?dl=0
👍

**Comment by emilgrip** [comment]
Nice, works fine now 👌 @huyphams
