### ISSUE TITLE
[Feature Request] Reset Auto Increment Button

### ISSUE THREAD

**Issue by cesarmtz93-wit** [TablePlus/TablePlus#1725]
@huyphams Add an option to reset the auto increment in the tables like the sample below (sequelpro)

![Screen Shot 2020-02-14 at 9 59 53](https://user-images.githubusercontent.com/57166683/74547650-0cbdea80-4f12-11ea-969f-703a40ef7581.png)

**Comment by cesarmtz93-wit** [comment]
any update?

**Comment by webdevnerdstuff** [comment]
In addition to this, please add a way to view the auto increment. I haven't been able to find it anywhere. Currently the only way I know how to even see what it is via a query, which isn't very convenient. If there is a way to view it, please do tell as I've been looking everywhere for it.

**Comment by huyphams** [comment]
I've added this feature to the next update.
<img width="847" alt="Screen Shot 2020-04-24 at 7 18 24 PM" src="https://user-images.githubusercontent.com/3654622/80211796-8ab01780-8660-11ea-900e-b42f8790f18b.png">

**Comment by webdevnerdstuff** [comment]
@huyphams Thank you! :)

**Comment by cesarmtz93-wit** [comment]
@huyphams Thanks!! :D
