### ISSUE TITLE
[BUG][build 81] Can't test a new credential if connexion failed

### ISSUE THREAD

**Issue by menthol** [TablePlus/TablePlus#173]
![capture d ecran 2018-01-08 a 15 57 39](https://user-images.githubusercontent.com/1001497/34676454-24241e88-f48d-11e7-8a05-16f954ad19be.png)

The Test button stay locked after credential validation failed

**Comment by huyphams** [comment]
Thanks, @menthol, I checked, the function still works fine. but it takes a long time to respond. I have been waiting for 3-5 minutes (it won't enable because TablePlus is trying to connect to the database). I'm investigating it.
