### ISSUE TITLE
[Feature Request]  Add possibility to customize and choose several tags 

### ISSUE THREAD

**Issue by dnim** [TablePlus/TablePlus#1732]
<img width="254" alt="Screen Shot 2020-02-22 at 7 10 38 AM" src="https://user-images.githubusercontent.com/1839962/75087080-ae61bf00-5544-11ea-9711-02e3ca3c721e.png">

Hi! Just wondering - do you plan to add this ability in the future?

**Comment by jbergstroem** [comment]
In addition to making the tag name and color customizable, I would also like to remove the abbrevation of the title. The connection screen has tons of retail space; no need to make it harder to read / understand (and if we can customize the labels; they can also be shortened by the user).

**Comment by huyphams** [comment]
Please wait for the next update!
<img width="606" alt="Screenshot 2023-03-07 at 9 23 20 PM" src="https://user-images.githubusercontent.com/3654622/223450162-c30b0d46-1939-47ac-bcdb-575e5bea705e.png">
