### ISSUE TITLE
Update Error - An error occurred while extracting the archive. Please try again later.

### ISSUE THREAD

**Issue by jaspersone** [TablePlus/TablePlus#1735]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
10.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
286

3. The steps to reproduce this issue:
Press "Check for update"
Press "Install Update"
Download begins
Install begins then error: "Update Error - An error occurred while extracting the archive. Please try again later."

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @jaspersone, could you please try it again?

**Comment by jaspersone** [comment]
Thanks it seemed to work!
Cheers,
*Jasper Sone* | Product at GoodTime

[image: goodtime.io] <http://goodtime.io/>
LinkedIn
<https://etchmobileincdbagoodtime.emailcontent2.com/api/mailings/39420/click?org=d137cadf-8e40-4a0e-a0e5-4ff5c49f0d67&sig=0TMu6DsjzqtTQujaXToEo7K5Z3plgw7ts-IGNwaTLO4%3D&url=https%3A%2F%2Ft.yesware.com%2Ftt%2F456b3d9bfeff4cfc679139293d1bf8254578bccd%2F2f24e2b05b4fa2af897f1cdfe623bf22%2F1292ee988c4e930ff60144fdca6c01bb%2Fwww.linkedin.com%2Fcompany%2Fgoodtime.io%2F>
 | Blog
<https://etchmobileincdbagoodtime.emailcontent2.com/api/mailings/39420/click?org=d137cadf-8e40-4a0e-a0e5-4ff5c49f0d67&sig=0TMu6DsjzqtTQujaXToEo7K5Z3plgw7ts-IGNwaTLO4%3D&url=https%3A%2F%2Ft.yesware.com%2Ftt%2F456b3d9bfeff4cfc679139293d1bf8254578bccd%2F2f24e2b05b4fa2af897f1cdfe623bf22%2F37b84decfb4af7a33f8275c7808b0576%2Fblog.goodtime.io%2F>
|
Careers
<https://etchmobileincdbagoodtime.emailcontent2.com/api/mailings/39420/click?org=d137cadf-8e40-4a0e-a0e5-4ff5c49f0d67&sig=0TMu6DsjzqtTQujaXToEo7K5Z3plgw7ts-IGNwaTLO4%3D&url=https%3A%2F%2Ft.yesware.com%2Ftt%2F456b3d9bfeff4cfc679139293d1bf8254578bccd%2F2f24e2b05b4fa2af897f1cdfe623bf22%2F6c3b1ebb232265b973f1d5f1336c5c89%2Fangel.co%2Fgoodtimeio%2Fjobs>
