### ISSUE TITLE
[ bug ] Copy pasting JSON from row to vs code appending an extra `}`

### ISSUE THREAD

**Issue by AlbertoMontalesi** [TablePlus/TablePlus#1737]
TablePlus build 296, mysql 8.

When I copy the content of a row that contains a stringified JSON to vs code, it always appends an extra `}` at the end of it.

To copy i simply click on the cell, and copy that content with command + c, i don't use the right sidenav

**Comment by huyphams** [comment]
I couldn't reproduce the issue, could you make a gif or send me an example? Thank you.

**Comment by AlbertoMontalesi** [comment]
@huyphams It turned out to be an issue with the JSON formatted for VScode rather than an issue with TablePlus, i'll close this.
