### ISSUE TITLE
[bug] Crash importing large csv files

### ISSUE THREAD

**Issue by bz13** [TablePlus/TablePlus#1738]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.8 and 11.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
296

3. The steps to reproduce this issue:
Import any large csv file into a new table.  I don't know exactly what large means, but at least, 38 MB.  I can not post example data.  TablePlus will eventually hang and then crash.  I've submitted a couple crash reports today.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I've tested with many CSVs (up to 1GB) and it works without any issue. I think this issue related to special data. 38MB is quite small.
Please send me the crash to huy@tableplus.com or post it here, TablePlus was not distributed via AppStore so the send crash button does nothing.

**Comment by huyphams** [comment]
Hi @bz13 if you have a chance, please try our latest release!
