### ISSUE TITLE
[Feature Request] Sub-grouping connections 

### ISSUE THREAD

**Issue by menthol** [TablePlus/TablePlus#174]
In Querious, we can subgrouping connection.

This is a needed feature when you have to deal with many connections.

Querious can sub-grouping.

![capture d ecran 2018-01-08 a 16 19 21](https://user-images.githubusercontent.com/1001497/34677611-fc329162-f490-11e7-88c3-a32fb3e45a79.png)

It's harder to read in TablePlus

<img width="555" alt="capture d ecran 2018-01-08 a 16 19 25" src="https://user-images.githubusercontent.com/1001497/34677629-0c8b34e2-f491-11e7-8c30-bab6e08e9a5c.png">

**Comment by huyphams** [comment]
it's duplicated with this issue: https://github.com/TablePlus/TablePlus/issues/163 So I will close this issue. Sub-group is nice. I will try to implement a beta version. Probably in build 82.
