### ISSUE TITLE
saving overloaded plpgsql-methods displays wrong method

### ISSUE THREAD

**Issue by MaximilianTyrtania** [TablePlus/TablePlus#1741]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL11.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.1.0(290)
3. The steps to reproduce this issue:
I have many overloaded plpgSQL methods (same method name wit different parameters).
If I edit one and hit "command S" (on Mac OS) Table Plus suddenly loads another method into the code editor. I need to find and reload the right method to see my changes. Always gives me a scary feeling to see my code gone.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @MaximilianTyrtania I've fixed it, it commit correct changelog but showing wrong item after reloading. I fixed it.

**Comment by MaximilianTyrtania** [comment]
Thanks for fixing it and for a great product!

Best wishes all the way from Berlin,

Max

Maximilian Tyrtania 
Contact King Softwareentwicklung 
Tel.:    ++0152/29270736
http://www.contactking.de
