### ISSUE TITLE
No dropdown helper on column?

### ISSUE THREAD

**Issue by bantilan** [TablePlus/TablePlus#1742]
Hi TablePlus Team,

Just notice in windows 10, there is no drop down helper for columns, like in data_type, extra, etc.. 

I am using MySQL 8.0.19

Any solution on this?
![Captu44re](https://user-images.githubusercontent.com/1697297/75485533-ce323080-59e5-11ea-8b4e-801112bb0c8d.PNG)

Best

**Comment by huyphams** [comment]
I moved it to the Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/195
