### ISSUE TITLE
DisConnect/Reconnect  loop

### ISSUE THREAD

**Issue by clarkbremer** [TablePlus/TablePlus#1743]
1. Which driver are you using and version of it 
MYSQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.1.2 (296)

3. The steps to reproduce this issue:
Connect to database, and click on first table.  

--

I recently licensed your excellent product!  But I'm having a frequent problem where Tables Plus goes into a loop disconnecting and reconnecting to the database.  I have to force-quit to get out of it.  Does not happen every time, but enough to be annoying.

This database is on GCP (Cloud SQL), and accessed via an Internal Load balancer into the cluster.  Not sure if that's relevant.

**Comment by huyphams** [comment]
It's fixed recently, please let us know if you're still seeing the bug. Thanks!
