### ISSUE TITLE
Can't alter collation

### ISSUE THREAD

**Issue by andrews05** [TablePlus/TablePlus#1744]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
296

3. The steps to reproduce this issue:
View table structure, change collation for a column, save.
A syntax error is thrown near 'COLLATION ...'
The correct syntax to use is "COLLATE", not "COLLATION"

**Comment by huyphams** [comment]
Thank you for letting me know, I fixed it! it will be released in the next update 🙌

**Comment by andrews05** [comment]
Thank you! :)
