### ISSUE TITLE
Behaviours preferences?

### ISSUE THREAD

**Issue by andrews05** [TablePlus/TablePlus#1745]
The first time I run a query in TablePlus, a small dialog pops up informing me that it will save queries and that I can change this in the "Behaviours" tab of the preferences. But no such tab exists and I can't find anything in the prefs about saving queries.

**Comment by huyphams** [comment]
There are two options in the preferences.
1. Turn off autosave.
2. Change the saved query location.
What were the options that you're looking for?
<img width="921" alt="Screen Shot 2020-02-28 at 12 59 35 PM" src="https://user-images.githubusercontent.com/3654622/75514535-3c98e200-5a2a-11ea-9453-fddb9e1f56a7.png">

**Comment by andrews05** [comment]
Ah, my apologies, wasn't looking closely enough.
You may want to change the message to correctly indicate where to find it :)
