### ISSUE TITLE
Won't connect to MariaDB as MariaDB

### ISSUE THREAD

**Issue by designermonkey** [TablePlus/TablePlus#1746]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

We host MariaDB 10.2 databases with required SSL.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.1.2 (296)

3. The steps to reproduce this issue:

Try to create a connection using MariaDB, with SSL REQUIRED and it rejects the connection. Try the same as MySQL 5 with SSL REQUIRED and it accepts the connection.

I can provide more info if required.

**Comment by huyphams** [comment]
Hi @designermonkey  If you have a chance, plese try this patch it should fix the issue:
https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
