### ISSUE TITLE
[Feature Request] Group or connection icon 

### ISSUE THREAD

**Issue by menthol** [TablePlus/TablePlus#175]
Having icon on group or connection can make finding one specific connection a lot easier.

Querious have icon on connection : 
![capture d ecran 2018-01-08 a 16 19 21](https://user-images.githubusercontent.com/1001497/34677760-6165c5a4-f491-11e7-9085-95f14a37a02c.png)

It's harder to  find specific connection on TablePlus :

<img width="555" alt="capture d ecran 2018-01-08 a 16 19 25" src="https://user-images.githubusercontent.com/1001497/34677782-7854f7da-f491-11e7-860b-03ef36885377.png">

Best regards

**Comment by huyphams** [comment]
Wow, I did know that, but anyway it's fun to implement this kind of feature 😄

**Comment by huyphams** [comment]
Hey @menthol  I just wanna tell you that I'm working on it 😄 
<img width="712" alt="screen shot 2018-01-16 at 1 07 28 pm" src="https://user-images.githubusercontent.com/3654622/34974180-49d669c4-fabe-11e7-8a05-bdd775902c4a.png">

**Comment by huyphams** [comment]
Hey @menthol 
You can try out the build here https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
<img width="712" alt="icon" src="https://user-images.githubusercontent.com/3654622/34985869-1e2547f8-fae8-11e7-8696-486829cb25e8.png">
Let me know if you have any feedback on it
