### ISSUE TITLE
I cannot call my own queries in the SQL tab.

### ISSUE THREAD

**Issue by zdzana** [TablePlus/TablePlus#1752]
1. MySQL 8.x
2. Build 299
3. In SQL tab enter any simple query i.e. SELECT * FROM table LIMIT 10; Click "Run Current"

Nothing happens. There is no query called in the open console at the bottom. Only the "Run Current" button changes to "Cancel", status bar at the top shows "Executed Statements Count 0/1"

Clicking "Cancel" opens the process list, which is empty.

![Zrzut ekranu 2020-03-2 o 12 52 32](https://user-images.githubusercontent.com/3853340/75674178-db207f80-5c84-11ea-93ba-ad04c6d3f654.png)

**Comment by zdzana** [comment]
Downgrade to 296, SQL tab works fine.

**Comment by huyphams** [comment]
Hi @zdzana I'm not sure about the issue, I could not reproduce it. Did you open the console after or before running the query (on build 299)?
Thank you

**Comment by zdzana** [comment]
Before, i have console open all the time.

**Comment by zdzana** [comment]
The console is just one of the symptoms, the most important thing is that the query is not performed at all. Even if I type the wrong one, one reaction is that the button from Run Current or Run All changes to Cancel. There is no request to the server, no error information, and no result.

**Comment by huyphams** [comment]
I think it got stuck before you click the `Run Current`. The database connection can only handle 1 query at time. If it got stuck, it would hold all the later queries until the first returned. is it happen right after making a connection or wake up in the background?

**Comment by zdzana** [comment]
I checked without doing any queries before. I open TablePlus, select the connection, go to the SQL tab, enter the query, each time the same problem.

**Comment by huyphams** [comment]
Thank you so much for confirming, I will take a look at it, will update this thread asap!

**Comment by huyphams** [comment]
Hi @zdzana I've fixed the issue on this build: https://www.dropbox.com/s/ndn8m23p7fbvwcq/tableplus.dmg?dl=0
We have to disable split results into tabs to reproduce the issue.

**Comment by zdzana** [comment]
I confirm. It's working fine now. Thank you.
