### ISSUE TITLE
Add search keyboard shortcut

### ISSUE THREAD

**Issue by qkdreyer** [TablePlus/TablePlus#1760]
1. Driver: all drivers.
2. TablePlus build: 296
3. Step to reproduce the issue:
- Unknown.

**Comment by huyphams** [comment]
Hi @qkdreyer I don't understand your request, also TablePlus platform (mac/windows/Linux or iOS) so I couldn't help.

**Comment by qkdreyer** [comment]
Sorry, I’m asking this for the macOS version, latest build (296), to be able to focus the search input using a keyboard shortcut

**Comment by huyphams** [comment]
There are a lot of search inputs inside the workspace if you press Command + F.

1. In Table/View content => it will open the filter and focus on the input field.
2. If you open Query Editor => it will open the search field and focus on the input field.

I'm not sure how to reproduce the issue, maybe there is a bug?

**Comment by qkdreyer** [comment]
I wasn’t aware of these two. It would be great if we could also filter the table list by pressing Cmd + F upon database opening

**Comment by huyphams** [comment]
You can hold the Command + shift + F, it will focus on the item search field. We could not use command + F because it will conflict with those two options above.

**Comment by qkdreyer** [comment]
Thanks 🙏
