### ISSUE TITLE
Can I change the maximum width of the trigger view?

### ISSUE THREAD

**Issue by CatsMiaow** [TablePlus/TablePlus#1761]
TablePlus v3.1.2

<img width="161" src="https://user-images.githubusercontent.com/1300172/75964492-a7ef2200-5f0a-11ea-88fa-c29c33c2a018.png">

It is difficult to expand the name, event, source, etc. at once without adjusting the overall width.

**Comment by huyphams** [comment]
It's duplicate to https://github.com/TablePlus/TablePlus/issues/519
