### ISSUE TITLE
Can't connect to MariaDB 10.4.12

### ISSUE THREAD

**Issue by ckissi** [TablePlus/TablePlus#1763]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Version: '10.4.12-MariaDB-1:10.4.12+maria~bionic-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.2.0 (299)

3. The steps to reproduce this issue:

I'm trying to connect to MariaDB 10.4.12 over SSH. Selected MariaDB from the connection menu.

![image](https://user-images.githubusercontent.com/5107590/76078296-a6713880-5fa2-11ea-85e6-56a27ea96d01.png)

Notice what I got when clicked test 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi guys, If you have a chance, plese try this patch it should fix the issue:
https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
