### ISSUE TITLE
[Feature Request] Table Definition for Snowflake is not working yet like in RedShift

### ISSUE THREAD

**Issue by ehkygit** [TablePlus/TablePlus#1769]
Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake : 4.7.1

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.2.0 (299)

The steps to reproduce this issue:
New Feature request not an issue

Noted: If the bug is related to data, please attach an example SQL data.

Please provide SQL definition of tables under structure- Snowflake..

**Comment by JohnRomanski** [comment]
I can't connect to Snowflake right now (https://github.com/TablePlus/TablePlus/issues/1150) but snowflake does have a great tool for this, the `get_ddl('table',....)` command does return what you are looking for. https://docs.snowflake.com/en/sql-reference/functions/get_ddl.html

**Comment by huyphams** [comment]
I've supported this feature on the hotpatch: https://www.dropbox.com/s/37zkls7jquz8g6o/TablePlus.dmg?dl=0
Thanks!
