### ISSUE TITLE
[PostgreSQL BUG, BUILD 81] Cannot delete value in a UUID column

### ISSUE THREAD

**Issue by nadapeter** [TablePlus/TablePlus#177]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.5.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
81

3. The steps to reproduce this issue:

    1. Have a row with a UUID column filled in.
    2. Double click on the UUID column of the row and delete the value. Notice the cell turns in to "EMPTY" instead of "NULL"
    3. Cmd + S, gives you an error
    ![image](https://user-images.githubusercontent.com/1158571/34802725-036f9a76-f624-11e7-85c9-d5391e55b471.png)

**Comment by huyphams** [comment]
Hey @nadapeter can you try hold option + click on the cell and set null for UUID? because empty is not NULL value.

**Comment by nadapeter** [comment]
Ahh that worked. Thanks!
When you delete the value in a UUID cell, I think it should set to NULL by default since EMPTY is not a valid value.

**Comment by huyphams** [comment]
We can't change empty to null automatically because empty is not null. But we can have an option to allow TablePlus to convert it to null in some case (Ex: uuid, number data type). I'm working on it.

**Comment by huyphams** [comment]
https://github.com/TablePlus/TablePlus/issues/139#issuecomment-358623078
