### ISSUE TITLE
[Feature Request] Saving Mode Setting Based on Tag

### ISSUE THREAD

**Issue by alexclst** [TablePlus/TablePlus#1770]
We can tag saved connections as “local”, “production”, etc. I’d like the ability to set which saving mode (silent, safe, etc.) based on these tags, so that all favorites marked “production” for example could automatically be set with my desired Saving Mode (Safe Mode 2), without needing to set it on each new favorite. There may be other settings in a connection window that’d be sensible to include in a “Defaults by Tag” sort of feature, but Saving Mode is the one I most want to see implemented.

**Comment by huyphams** [comment]
It's a nice idea but It will be a hidden setting and cause confusion for new users. So I don't think we should implement it.
