### ISSUE TITLE
Support for DynamoDB

### ISSUE THREAD

**Issue by andrewrothman** [TablePlus/TablePlus#1771]
Hi there,

TablePlus is a really amazing tool. I love using it every day.

I deal with Postgres quite a bit, but I also have to interact with Dynamo tables on a daily basis. The AWS web interface is far inferior. I've used TablePlus' integration with Redis, and other team members I've spoken to have used the Redshift integration.

I understand this might be a difficult ask. If at all possible, basic viewing and editing would go a long way for me and my team.

Thanks!

**Comment by huyphams** [comment]
Thanks, this request is duplicated to https://github.com/TablePlus/TablePlus/issues/666
