### ISSUE TITLE
BUG - Refresh, Reload, or Reconnect opens Filter criteria

### ISSUE THREAD

**Issue by bcorcoran** [TablePlus/TablePlus#1772]
Version 3.1.2 (296), MacOS Catalina

Reload Workspace, Reload Current Tab, and Reconnect all open the table Filter (above the column headings). This is odd behavior and is probably a bug. Personally I don't want the filter open if I don't need it because of the visual noise (not to mention the extra vertical space it takes up on smaller screens).

Nothing happens if you do not have a table open because there is no filter criteria to show.

**Comment by huyphams** [comment]
Hi @bcorcoran I'm not sure that I understand it correctly. Could you explain it step by step to reproduce the issue?

**Comment by bcorcoran** [comment]
1. Connect to a server and open a table
2. Make sure the filter criteria (pictured) is hidden:
![Screen Shot 2020-03-17 at 12 40 37](https://user-images.githubusercontent.com/313697/76879362-85cf9b00-684c-11ea-9c21-5b5cad2cbbd7.png)
3. `CMD+R`, `CMD+Shift+R`, or `CMD+Option+R` to refresh (depending on the kind of refresh you need)
4. Notice that the filter criteria comes back.

**Comment by huyphams** [comment]
Hi @bcorcoran could you check if the always show is enabled? I could not reproduce the issue.

<img width="544" alt="Screen Shot 2020-03-18 at 10 18 05 AM" src="https://user-images.githubusercontent.com/3654622/76921931-d35a0f80-6901-11ea-839b-82da6e6b89b7.png">

**Comment by bcorcoran** [comment]
Ah, I had no idea that was even an option. Setting to Remember the last state fixes it. It was set to "Always show", but I don't recall ever setting that... especially since I didn't even know that gear was a menu.

That being said, there does actually appear to be a visual bug with the filter panel. When closed, there is a 1px border that does not go away. No big deal tho!
