### ISSUE TITLE
Count is off when there are no results for a filter

### ISSUE THREAD

**Issue by adamwinn** [TablePlus/TablePlus#1773]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
296

3. The steps to reproduce this issue:
Enter in a filter that will show no data.  Status bar at the bottom will say "1 of 0 rows".  It should say "0 of 0 rows"

![Screen Shot 2020-03-17 at 8 15 53 PM](https://user-images.githubusercontent.com/3028964/76918665-76704200-688c-11ea-8b1f-04635ea6e2e9.jpg)

**Comment by huyphams** [comment]
Thanks, I just fixed it in the up coming beta release!
