### ISSUE TITLE
Export larger DB uses a lot of RAM

### ISSUE THREAD

**Issue by z-ax** [TablePlus/TablePlus#1777]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
296

3. The steps to reproduce this issue:
Open DB with about 1.4 GB of data, select all tables, Export to SQL with all checkboxes checked (including gzip).

It was the smallest DB of the online game, didn't try on the biggest. CPU load uses almost the full core all the time. But more interesting thing is RAM: it jumps from smaller usage to **something like 14-16 GB peak**. Good thing it's going back and forth like this without crashing, but that's not normal behaviour at all. Probably good thing I didn't try JSON export :) 

Dump size (.sql.gz) is bigger than I did with Sequel Pro, but probably because I set statements each 1MB instead of default 250KB (no prefs in TablePlus on this) — 165MB vs 147 MB. Comparing just because I have it to check quickly :)

**Comment by huyphams** [comment]
Hi @z-ax could you try out our beta release: https://www.dropbox.com/s/ndn8m23p7fbvwcq/TablePlus.dmg?dl=0 and see if the RAM issue is resolved? Thanks

**Comment by huyphams** [comment]
We fixed a similar issue recently, so I think the usage RAM is resolved in the beta build.
<img width="812" alt="abc" src="https://user-images.githubusercontent.com/3654622/77029734-1d5cf700-69cf-11ea-889f-e7c5ed036c18.png">

**Comment by z-ax** [comment]
Well, I shut down bigger DB after backups. But with smaller I see this: after connection it uses 45/90 MB (MySQL/Postgres), while exporting it goes up to about 250-300 MB. And then memory is not fully freed (MySQL connection uses about 190 MB).

Not that big of a deal, but maybe it helps.

**Comment by huyphams** [comment]
> Well, I shut down bigger DB after backups. But with smaller I see this: after connection it uses 45/90 MB (MySQL/Postgres), while exporting it goes up to about 250-300 MB. And then memory is not fully freed (MySQL connection uses about 190 MB).
> 
> Not that big of a deal, but maybe it helps.

It's complicated, macOS has a cached feature, it only releases memory when needed. I think we can close this feature for now. Please let me know if you have any questions.
