### ISSUE TITLE
Postgres Foreign key not displayed on table if key name is same as on another table

### ISSUE THREAD

**Issue by kjg** [TablePlus/TablePlus#1778]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 296

3. The steps to reproduce this issue:

run the following SQL to create the tables:

```sql
CREATE TABLE cinemas (
        id serial,
        name text,
        location text
);

AlTER TABLE cinemas ADD PRIMARY KEY (id);

CREATE TABLE movies (
        id serial,
        name text,
        cinema_id int
);
AlTER TABLE movies ADD PRIMARY KEY (id);

ALTER TABLE movies ADD CONSTRAINT fk_cinemas FOREIGN KEY (cinema_id) REFERENCES cinemas (id);

CREATE TABLE films (
        id serial,
        name text,
        cinema_id int
);
AlTER TABLE films ADD PRIMARY KEY (id);

ALTER TABLE films ADD CONSTRAINT fk_cinemas FOREIGN KEY (cinema_id) REFERENCES cinemas (id);
```

When viewing the structure of movies, the FK is shown: 
![image](https://user-images.githubusercontent.com/2205/77086828-49c54300-69d0-11ea-8c65-40fa54a79b35.png)

However when viewing the structure of films, the FK is NOT shown:

![image](https://user-images.githubusercontent.com/2205/77086880-5e094000-69d0-11ea-8fd2-b97f1a35457e.png)

**Comment by huyphams** [comment]
Thanks @kjg let me check it.

**Comment by kjg** [comment]
I can confirm this is working as expected in build 302. Thanks!

**Comment by huyphams** [comment]
Thanks!
