### ISSUE TITLE
need an undelete option

### ISSUE THREAD

**Issue by ajoslin103** [TablePlus/TablePlus#1779]
just bought TablePlus license -- awesome product

needs an undelete option

to reproduce

1. insert row (A) with a FK to an existing row in another table
2. insert row (B) with no FK
3. attempt delete of row (A) -- error is shown, as should be
4. try to now delete row (B) -- can't do it because row (A) can't be de-selected

**Comment by huyphams** [comment]
Have you tried command + Z @ajoslin103 ?

**Comment by ajoslin103** [comment]
HAHAHAHAHA!! 

That's just waaaaaaay too Mac-Like !!

this issue is CLOSED !!

🥇
