### ISSUE TITLE
Since I started user table plus with mongo the client is closed when i don't use it a while, I use also postgres and ms drivers and all of them is closed

### ISSUE THREAD

**Issue by chaimvaid** [TablePlus/TablePlus#1781]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @chaimvaid if you have a chance, please download this hotpatch: https://www.dropbox.com/s/wy9l92h844lcef6/TablePlus.dmg?dl=0 it should fix the issue, thanks!
