### ISSUE TITLE
File naming in backup database doesn't work

### ISSUE THREAD

**Issue by cmerijn** [TablePlus/TablePlus#1783]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.1.44

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 120 on Windows 10

3. The steps to reproduce this issue:
When exporting a database with Menu > File > Backup, I can't set the file name and i cant use the patterns. It just says untitled after I click OK.

**Comment by huyphams** [comment]
The pattern and also the title will change after selecting the connection > database in the list. Have you selected it? @cmerijn 
I will close this issue because it was the windows issue (this is the macOS repo), it should be posted here: https://github.com/TablePlus/TablePlus-Windows/issues
