### ISSUE TITLE
CSV is hanging now

### ISSUE THREAD

**Issue by jasonbronson** [TablePlus/TablePlus#1786]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.1.2 296

3. The steps to reproduce this issue:
import any csv hangs trying to either import files or just selecting table itself.
File is only 2 megs large

Noted: If the bug is related to data, please attach an example SQL data.
unknown what causes it

**Comment by huyphams** [comment]
Hi @jasonbronson is there any chance of getting a test CSV my email is nick@tableplus.com I couldn't reproduce the issue

**Comment by jasonbronson** [comment]
I figured it out. It looks like it crashes when there are too many columns in the file. Rather than error out. 

Example take a csv file and create it with thousands of columns and it crashes.
My csv was the issue and it's been fixed now it works
