### ISSUE TITLE
Sidebar headers are unreadable with dark theme 

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#179]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
81
3. The steps to reproduce this issue:
The headers are unreadable on both mouse-over (Favorite) and when active header (Item)
![image](https://user-images.githubusercontent.com/221584/34852640-8afacbda-f6e4-11e7-9a04-c5472c915202.png)

Also, I think the headers should read **Items** and **Favorites**

**Comment by huyphams** [comment]
Thanks, @bhrd the UI bug is one of know issue. It's only happened in Sierra.

**Comment by huyphams** [comment]
It's a legacy issue on the old OSX, and not easy to fix, so I will close it.
