### ISSUE TITLE
Typo when there are 0 rows affected

### ISSUE THREAD

**Issue by dguo** [TablePlus/TablePlus#1790]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

296 (version 3.1.2)

3. The steps to reproduce this issue:

Hello. There is a minor typo when 0 rows are updated. The message says "0 row affected" when it should be "0 rows affected". It shows up in both the query result and in the bar at the very bottom. Screenshot attached:

<img width="892" alt="Screen Shot 2020-03-27 at 8 26 45 AM" src="https://user-images.githubusercontent.com/2763135/77756144-03da3180-7005-11ea-9ca0-3d5484f77a0a.png">

**Comment by huyphams** [comment]
Thank you, we just fixed it 👍
