### ISSUE TITLE
Keychain duplicate entries

### ISSUE THREAD

**Issue by crewshin** [TablePlus/TablePlus#1794]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Doesn't matter.**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Build 300**

3. The steps to reproduce this issue:
Use TablePlus and look at the Keychain Access app.

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/273809/78084271-ba337300-7385-11ea-9bea-87015cb315d7.png">

I'm assuming this is a bug with storing the key.

**Comment by huyphams** [comment]
Hi @crewshin that is intentional behavior. TablePlus stores the password of connection separately (around 0~4 per connection). If you remove a connection, the number or record will be reduced.
