### ISSUE TITLE
Empty created view commit even after closing the tab

### ISSUE THREAD

**Issue by simonberger** [TablePlus/TablePlus#1796]
1. driver MySQL 5.7.29:

2. TablePlus:3.3.0 Build 300

3. Steps:

    1. I unintentionally created a new view - did nothing else in this new tab
    2. Closed the tab
    3. Added some rows to another table
    4. Commit those changes and got an error. The resulting mydsql statements started like this
```
CREATE VIEW `database`.`untitled_view_76` AS 
INSERT INTO `database`.`table1`( ...
```

Expectations:
My expectations are that closing a tab discards any done changes or newly created objects. 

Observations: 
- shouldn't just changes of the active tab be commited? Not sure how this functionality is intended.
- The view is incomplete and results in a wrong statement. It should not be commitable in that state.

**Comment by huyphams** [comment]
TablePlus will add all the pending changes into queue even after closing the tab, actually you can still open it by clicking the new view item on the left sidebar. You can discard the change by pressing command Z (undo) or clicking the top left button discard all.
We will not change this behavior because it is one of the core value of TablePlus.

**Comment by simonberger** [comment]
Thanks for the fast reply. Ok I now understand how it works. 
It is a great functionality but also dangerous and not intuitive as this view in my case was completely out of view. I had to scroll to see it in the list of tables.
I understand that you do not want to change something here and beside the fact of the faulty view statement there is no need of a fast change.
On the long term it might be helpful to have a clearer tracking of the active and commitable items in some way. I now use tableplus since some time but mainly just for viewing or editing some rows and I was completely lost here.

**Comment by huyphams** [comment]
The current design will cover those cases.
1. The user edit multiple tables and then commit it in one transaction.
2. The user edit a table and the commit it immediately.

If we change the design to only commit the current table. We could not do case 1. If we auto discards the invalid view => It's not clear when we should discard, it depends on the definition "invalid", and TablePlus will not know the statement is "invalid" until it sends and receives the result from the server, and we don't want to do something "auto discard", it's unintentional behavior.

**Comment by simonberger** [comment]
I get your UX dilemma. It is not easy. I think your current concept is fine of you consistently use it.

Regarding the invalid View state.
You could simply ignore this on the commit and probably inform about. It will at the end throw a save/discard message on program/connection close, right?

Here are some of the ideas coming in my mind when I wrote the phrase of clearer tracking of active objects. I am no UX guy but maybe you still get some ideas:
The commit icon and popup could be more interactive and verbose. For example a small number in the icon could show the number of different objects (tables, views) being part. Maybe even a bumping animation showing an increased object counter.
The commit layer should separate the statements (visually) by object and I would recommend to always show the commit screen for more than one object.

**Comment by huyphams** [comment]
I got your idea, thank you. When designing a feature, I always think about what is the main focus. The commit button isn't the main focus, the data is. So after the first time trying the commit, you will know where it is, and how it works, you will not want it constantly prompt/animation you every time you make a change. However, if you want to do so, you can set the safe mode to the warning mode, and it will show you the generated queries every time you try to commit. Otherwise, the indicator on the left sidebar and the modified color are enough for visualizing the changes.

<img width="1491" alt="Screen Shot 2020-04-01 at 9 40 07 PM" src="https://user-images.githubusercontent.com/3654622/78150340-5e3e1c80-7461-11ea-8b5c-fe17f8edd5a1.png">

**Comment by simonberger** [comment]
I am not in your opinion. An animation after changing data does not distract your view from anything important at that time. There indeed is no need of a flashy constant effect.
It could be a personal problem but I almost always need some moments to search for the commit button as it seems to be not where I expect it. Some highlighting obviously would help (currently it isn't even yellow if "active")

You can assess your users much better than I can but I would expect much less power users that create big amount of new table in the tool. These days a framework should do this job.

In your screen you have a very small developer example. In my case I have a multiple of this amount of tables. I do not have the new object in view.
A connected layer showing these added or changed objects would always have them in the view of the user. It could be there by default if more than one object is in processing but it could also be disabled. Surely they could also be showed on the top of the item lists or appear in a new tab "Edited" on top of functions, tables

I have the safe mode enabled. It is a very nice feature. In this case I just skipped over the small line of the view creation which I also didn't expect. Additionally I was lost how to remove the view from the commit result anyway. My solution would have been to copy the inserts and process them manually.

I surely accept other opinions. This was just a bunch of improvement ideas. There is no need for further discussion from my side. If you take something out of these to improve the software I would be happy.

**Comment by huyphams** [comment]
Thank you @simonberger actually some of your ideas are really cool, and I would love to implement it.
