### ISSUE TITLE
Licence problem

### ISSUE THREAD

**Issue by zdzana** [TablePlus/TablePlus#1798]
I just updated the application to version 3.3 (302) by homebrew cask upgrade. After rebooting, I received a message that my license has expired and I have no possibility of further updates. I was in trial mode. The dialog had a possibility to download older version, which I did.

After 3.1.2 (296) launch, I still can't activate my license key because the workstation limit was used.

The key purchased in the corporation, I don't have access to the license manager, and the current remote work situation is even more difficult. I only have the key.  How do I get back to the last running 3.2 with this key?

**Comment by zdzana** [comment]
Okay, I managed to find the person in charge of requesting the license and deactivated the previous installation. Now I have a working license but older than the previous version of the application 3.1.2 How to upgrade to the last available license before the expiration date?

**Comment by huyphams** [comment]
Hi @zdzana you must update the app using check for updates. It will update the app with the lasted release (with your license). If you update the app via homebrew, it will not respect the license.

**Comment by huyphams** [comment]
<img width="307" alt="Screen Shot 2020-04-02 at 5 54 11 PM" src="https://user-images.githubusercontent.com/3654622/78241662-f6dca700-750a-11ea-894b-2c2ff43bc47c.png">

**Comment by zdzana** [comment]
It works. Thanks.
