### ISSUE TITLE
Mouseover previews of overflowing cell values, unreadable on dark theme

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#180]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 82
3. The steps to reproduce this issue:
Previewing overflowing cell values (by mouseover) renders the text unreadable on dark theme

![image](https://user-images.githubusercontent.com/221584/35013863-93ae5f8e-fac3-11e7-9cf5-23e8932311b6.png)

**Comment by huyphams** [comment]
this issue is related to the old macOS, which is fixed by Apple recently.
