### ISSUE TITLE
SQL Query shows unpected beheviour when queries are commented out with "cmd + /"

### ISSUE THREAD

**Issue by umutuzgur** [TablePlus/TablePlus#1800]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
 PostgreSQL 10.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 300

3. The steps to reproduce this issue:
* Open the SQL Query screen
* Enter multiple sql queries
* Comment out whichever you want using the shortcut `cmd + /`
* Execute the query and you will see that the actually executed query will be different than what you commented out
* This doesn't happen if you add '--' without the shortcut

**Comment by huyphams** [comment]
Hi @umutuzgur could you give me an example queries here or via my email nick@tableplus.com thanks!

**Comment by umutuzgur** [comment]
@huyphams it happens with any query. It is related to input detection I think but you can use these queries. Just comment out whichever you want a couple of times with cmd + / and you can see that the executed query doesn't match what is in the screen

SELECT * FROM information_schema.table_constraints;
SELECT * FROM information_schema.tables;

**Comment by huyphams** [comment]
I'm not sure how to reproduce the issue @umutuzgur could you point it out? thanks
<img width="1639" alt="Screen Shot 2020-04-03 at 3 51 04 PM" src="https://user-images.githubusercontent.com/3654622/78342078-edaf1100-75c2-11ea-8e10-f93bfc571275.png">
<img width="1639" alt="Screen Shot 2020-04-03 at 3 50 46 PM" src="https://user-images.githubusercontent.com/3654622/78342481-8fcef900-75c3-11ea-95af-bbeddfab694d.png">

**Comment by umutuzgur** [comment]
@huyphams I will record a video of it today. It is a weird issue, I understand it is hard to debug it without seeing what happens
