### ISSUE TITLE
oarcle11g中文问题

### ISSUE THREAD

**Issue by SunyWait** [TablePlus/TablePlus#1802]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
oracle11g
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.3.0 300 setapp
3. The steps to reproduce this issue:
oracle 连接中文乱码
![image](https://user-images.githubusercontent.com/24806537/78501788-ed17a580-778f-11ea-8a3c-1f7ec05f1640.png)
没有之前utf8的选项了
![Uploading image.png…]()

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
English please @SunyWait

**Comment by SunyWait** [comment]
connect  oracle11g garbled Chinese character，

**Comment by huyphams** [comment]
You can select `American_America.UTF8` and it should work.

**Comment by SunyWait** [comment]
ok thank restart  solved this problem，

**Comment by Gowa2017** [comment]
What's about alt32utf8?
