### ISSUE TITLE
Feature Request: Relational Database Diagram

### ISSUE THREAD

**Issue by alexandreamadocastro** [TablePlus/TablePlus#1805]
I honestly don't know how difficult it is to do that, however, it would be very handy:

![image](https://user-images.githubusercontent.com/5918765/78567051-79f54a00-77f6-11ea-81b9-b4cadf94313a.png)

**Comment by huyphams** [comment]
Hi @alexandreamadocastro it's duplicated with https://github.com/TablePlus/TablePlus/issues/44 please  follow the issue #44
