### ISSUE TITLE
MongoDb support on Windows

### ISSUE THREAD

**Issue by pydupont** [TablePlus/TablePlus#1807]
Hi,

I love your software. I use it for relational databases but I also work a lot with MongoDb and Reddis.

That would be awesome if the MongoDb support was available for the Windows version too. This was requested in the comments of the issue #234 but never answered.

Cheers,

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/208
