### ISSUE TITLE
Function List not displayed

### ISSUE THREAD

**Issue by heejoon523** [TablePlus/TablePlus#1808]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 1914

3. The steps to reproduce this issue:
Connect to a existing database using PostgreSQL
Navigate to a schema containing functions
No functions will be shown anymore
![20200408_095457](https://user-images.githubusercontent.com/55621225/78732956-06327900-797f-11ea-92f0-84e063d286cb.png)
![20200408_095605](https://user-images.githubusercontent.com/55621225/78733050-3f6ae900-797f-11ea-849e-ef93cbfcef5b.png)
![20200408_095634](https://user-images.githubusercontent.com/55621225/78733053-4265d980-797f-11ea-8881-471512aee20c.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/209
