### ISSUE TITLE
Data conversion resulted in overflow on opening a MSSQL Table

### ISSUE THREAD

**Issue by juice** [TablePlus/TablePlus#181]
MSSQL 2012

Build 82

I opened one of my tables and this error message shows up "Data conversion resulted in overflow". It worked in a preview build.

**Comment by huyphams** [comment]
Hi @juice can you try this build and let me know the result: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Hope this fixes your issue.

**Comment by juice** [comment]
It works. Thank you.
