### ISSUE TITLE
Missing vertical scroll bar on new connection list view

### ISSUE THREAD

**Issue by alan-german** [TablePlus/TablePlus#1812]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 302

3. The steps to reproduce this issue: File => New Workspace (Cmd-N)

I use a Kensington TrackBall and their driver. No scroll bar appears regardless of "Show scroll bar" settings in System Preferences => General. I can assign a scrolling action to a trackball left-right button chord, but I feel I should see a vertical scrollbar here. I have over 100 stored connections.

**Comment by huyphams** [comment]
Hi, thank you. I just enable the scrollbar on the welcome screen also in the command + K popup! it will be included in the next update!
