### ISSUE TITLE
Export table to laravel migration

### ISSUE THREAD

**Issue by daugaard47** [TablePlus/TablePlus#1814]
Feature Request:

Just as the title says, I would love a plugin or export option to allow users to export a database table to a Laravel Migration file.

This would be a huge time saver when dealing with existing databases or manually altered ones.

If this already exists, please let me know.

Currently running TablePlus on Windows.

**Comment by huyphams** [comment]
Thanks, move to Windows Repo issue: https://github.com/TablePlus/TablePlus-Windows/issues/205
