### ISSUE TITLE
Check constraints disappearing from Structure View

### ISSUE THREAD

**Issue by kspeeckaert** [TablePlus/TablePlus#1815]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 3.3.0 (300)  on Mac OS X 10.15.4

3. The steps to reproduce this issue:

I don't know what the current status of #1118 is, but when I look at the structure view of a table, there's a _Check_ column. When I enter a condition (e.g. `image_url ILIKE 'HTTP_://%'`), it is picked up as a change and upon "saving", the check constraint is created. However, the value for the _Check_ column turns to `NULL` again.

Repeating the same action results in another check constraint being added.

I checked for the existence of the check constraint with the following query:

```
SELECT con.*
       FROM pg_catalog.pg_constraint con
            INNER JOIN pg_catalog.pg_class rel
                       ON rel.oid = con.conrelid
            INNER JOIN pg_catalog.pg_namespace nsp
                       ON nsp.oid = connamespace
       WHERE nsp.nspname = '<schema name>'
             AND rel.relname = '<table name>';
```

**Comment by wheelsandcogs** [comment]
None of my check constraints seem to be visible in the structure view any more, it's been that way for a couple of versions.

**Comment by huyphams** [comment]
Hi, Are you using PostgreSQL 12.2 and the build 304 @wheelsandcogs do you have any example to reproduce the issue? thanks

**Comment by wheelsandcogs** [comment]
hi @huyphams, I'm using build 304 but it's definitely been an issue in the previous build, and I think the one before that as well.

Postgres version: `PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`

**Comment by kspeeckaert** [comment]
Constraints reported through SQL:
<img width="907" alt="Screenshot 2020-04-20 at 13 34 53" src="https://user-images.githubusercontent.com/6348619/79747403-e77f9b00-830b-11ea-8c7d-5a8490223191.png">

View of the table structure (constraint `item_image_url_check` is missing):
<img width="823" alt="Screenshot 2020-04-20 at 13 35 10" src="https://user-images.githubusercontent.com/6348619/79747411-e9e1f500-830b-11ea-9285-15b94ef51444.png">

Definition generated by TablePlus, constraint is also missing (not sure if it should be included or not):
<img width="598" alt="Screenshot 2020-04-20 at 13 35 35" src="https://user-images.githubusercontent.com/6348619/79747480-041bd300-830c-11ea-83bf-194746e55731.png">

**Comment by huyphams** [comment]
Hi guy, please download and try this build https://www.dropbox.com/s/hijhy8j8b6ilpdr/TablePlus.dmg?dl=0 I've fixed this issue on PostgreSQL 12

**Comment by wheelsandcogs** [comment]
@huyphams just had chance to test this and it fixes the issue for me, thanks!

Apologies for the delay.

**Comment by wheelsandcogs** [comment]
@huyphams FYI the build above does show the constraints in the structure view, but it also has a bug where if you try and refresh a tab, the tab closes. Just thought you should know in case you hadn't noticed it.

**Comment by huyphams** [comment]
Thanks @wheelsandcogs I've fixed it immediately after release the hot patch, you can download it again here: https://www.dropbox.com/s/hijhy8j8b6ilpdr/TablePlus.dmg?dl=0
Have a nice day!

**Comment by chrschmitz** [comment]
Is it possible to add the column "check constraint" to SQLite as well?

**Comment by huyphams** [comment]
We will add it later @chrschmitz (I'm finding the way to load the check contains in SQLite).

**Comment by chartpath** [comment]
It seems there was a patched build but the file is not available in Dropbox anymore. I'm running Version 3.10.0 (348) and have this issue.

**Comment by eqon133** [comment]
im running Version 3.12.8 (368) on Mac, postgres 12, having same issue

**Comment by rafaelbiten** [comment]
I was looking for this feature too. I'm running an older version 3.1.2 though. If I could get a confirmation that this feature is present and working on the latest build, I'd consider renewing the license for another year. Could someone confirm that we can see the constraints for fields in Table Plus? Thank you

**Comment by telcy** [comment]
Same issue here

**Comment by LP-React** [comment]
Same issue here
I'm using PostgreSQL 15.3 and tablePlus 5.8.0

![image](https://github.com/TablePlus/TablePlus/assets/109695735/46d5ac53-053e-431e-8a96-d22d807ea1b5)
![image](https://github.com/TablePlus/TablePlus/assets/109695735/e18d9780-977c-4835-962e-2e9d2817a839)

**Comment by stefanofusai** [comment]
Same issue here. My versions are:
- PostgreSQL 16.3
- TablePlus 6.0.8

**Comment by ViktorQvarfordt** [comment]
Same issue here. My versions are:

* Postgres 15.1.1.13
* TablePlus 6.0.8
