### ISSUE TITLE
Tirgger option is not available in windows version?

### ISSUE THREAD

**Issue by muratbaloglu** [TablePlus/TablePlus#1816]
1.Mysql 7 or MariaDB

2. TablePlus  3,4,0 122 

  I am using windows version. Tirgger option is not available in windows version
Mac IOS version available. 

When will this feature come to the windows version?
![trigger_not](https://user-images.githubusercontent.com/22749367/79070879-16c95300-7ce1-11ea-8b60-82be82dcbe99.jpg)

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/155

**Comment by muratbaloglu** [comment]
Tirgger option is not available in windows version?
