### ISSUE TITLE
Ability to expand or resize autocomplete tooltip / popup window for long table / field names

### ISSUE THREAD

**Issue by mpaniagua-foreflight** [TablePlus/TablePlus#1818]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.16
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
302
3. The steps to reproduce this issue:
Begin typing any query where autocomplete will suggest a long table or field name. Autocomplete will suggest partial name with "..." placeholder, and no option to resize the tooltip to view the full name. This is very cumbersome when working with many long-named tables with potentially similar names.
<img width="609" alt="Screen Shot 2020-04-13 at 1 30 46 PM" src="https://user-images.githubusercontent.com/63609053/79148524-3452f700-7d8b-11ea-8f0a-f540178b1476.png">

**Comment by davidemerritt** [comment]
+1 - many of the tables I work with are too long to fit in the autocomplete.

**Comment by huyphams** [comment]
Hi please download this patch, I think it could improve the situation a lot: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by mpaniagua-foreflight** [comment]
Thanks @huyphams, the build you posted seems to have fixed the "..." issue and now the full table name is showing on long names. Will this change be included with the normal update releases?

**Comment by huyphams** [comment]
Yes, it will.

**Comment by davidemerritt** [comment]
Thank you so much!
