### ISSUE TITLE
[Linux] It should open any file for SQLite

### ISSUE THREAD

**Issue by kbumsik** [TablePlus/TablePlus#1819]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Linux 0.1 (Build 50)

3. The steps to reproduce this issue:

I have an SQLite file with a `.db.bin` name, but TablePlus won't show the file because it only look for `.db` file.

There should be an option for "Any File" in the file dialog, not only for "Database File".

![image](https://user-images.githubusercontent.com/7823583/79182836-c968f500-7e4a-11ea-8ab9-301e21d819c2.png)

![image](https://user-images.githubusercontent.com/7823583/79182881-e8678700-7e4a-11ea-98dc-e5e0aa83ccfb.png)

**Comment by huyphams** [comment]
Moved to Linux repo: https://github.com/TablePlus/TablePlus-Linux/issues/51
