### ISSUE TITLE
Update for favorite feature

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#182]
The favorite section in left panel will have:

- Tags: we can add a tag for favorites (Ex: PostgreSQL, MySQL, red, blue, ....)
- Filter: we can filter favorite by name, tags.
- Sort: we can sort favorites.
- Group and nested group: we can create a group of favorite just like connection on welcome screen.
- Hide favorite content: currently, favorite shows first 200 chars. Sometimes it's useless. We can hide it.

**Comment by tianhao** [comment]
Great! When released these features?

**Comment by huyphams** [comment]
Next update - Build 93 @tianhao 
<img width="1217" alt="history_improved" src="https://user-images.githubusercontent.com/3654622/36947831-e85f7e7c-2003-11e8-83cb-59d4a00dd0e7.png">

**Comment by tianhao** [comment]
We can manually add favorite item? Not Only "Add to favorite" from history list because that way need two step.
1. Add right click menu item when selected some text
2. Add "+" button on the bottom of the favorite list

Just suggestions :)

**Comment by huyphams** [comment]
Hmm, I don't know why people didn't see that we have a drop-down `Run Current`:
<img width="455" alt="screen shot 2018-03-05 at 1 02 18 am" src="https://user-images.githubusercontent.com/3654622/36948662-de41ac5a-2010-11e8-92de-0852d13bc690.png">

Btw, I also added the right-click menu to allow add to favourite. Thanks for the suggestion.

**Comment by tianhao** [comment]
Append favorite to SQL Query

![qq20180305-035257](https://user-images.githubusercontent.com/365540/36949863-c58ecf72-2028-11e8-8970-d0f43ff66a21.png)

Append "\n"+favorite to SQL Query

**Comment by huyphams** [comment]
Ah yeah, it's here incase you want to try before it released:
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by tianhao** [comment]
@huyphams 
I tested "Insert to SQL Query". It need to add a newline before inserting the favorite

```
select * from one;select * from tow; select * from three;
```

**Comment by huyphams** [comment]
It inserts the snippet exactly the caret position. So if you want a new line, I think you should add it first. 

if I insert new line automatically I cannot save a value and insert it as a value (in this case the snippet is not really a statement).

Behaviours of TablePlus always predictable, and it should.

**Comment by tianhao** [comment]
I think favorite is not snippet, favorite is from the complete SQL

**Comment by huyphams** [comment]
But you can use it as a pinned board, right? I usually pin hash and everything here. Probably the use cases are different. An optimize can save time for 70% of users but 30% users must give up their favourite behaviours.

**Comment by MartinZubek** [comment]
Hi all, was the sorting of "Favories" (now called "Queries") been left-out?
No matter what I do, the queries are always sorted by last date of change to the query.
Although there is visual indication when I start dragging a query, it can't be reordered inside given folder, only moved between folders.
Or is it a bug? Personally I would prefer the ability to have queries sorted by name.
