### ISSUE TITLE
When Console has a lot of text, makes entire app slow - "Clear the console" fixes it

### ISSUE THREAD

**Issue by egold** [TablePlus/TablePlus#1821]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 11.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 300

3. The steps to reproduce this issue: 

- Fill up the Console with a lot of SQL logs. Any large queries that will result in a lot of text appends to the Console at the bottom of the TablePlus interface. In my case, I noticed it after a few iterations of selecting-all on ~1000 rows tables and deleting the data. Delete all the rows, don't just truncate the table. The idea is to fill up the Console with a lot of text, which Truncate won't do. (This will spam the Console with a large `DELETE FROM` query with 1000 `OR` clause conditions) 
- Do this a few times to build up a beefy Console full of colored text
- Now notice most operations are really slow and result in a macOS beachball. This includes clicking tables (even tables with no rows yet)
- Click the Trash can icon to clear the Console. Notice no more macOS beachball, and UI is back to being super responsive as is normal.

I think the renderer for the Console is just not able to perform well with thousands of lines. Perhaps keeping a scrollback limit or using a different renderer, or lazily rendering the text on scroll (like an iOS or Android table view), in case it's the fonts and syntax highlighting causing the performance degradation.

I can't say for certain without knowing the source code, but it "feels" like the root cause is related to rendering a gigantic DOM in the Console, with parsing for syntax highlighting and everything happening on the fly. Making it lazy, threaded, queue driven, worker-based, recycling rows/cells, debugging mallocs, etc., is usually what I'd look at for something like this.

**Comment by patrickheeney** [comment]
I have been experiencing this for months and luckily saw this bug report. In my case I am using MySQL and have had tableplus open for a few days running queries. It would get to the point where doing anything with tableplus would macOS beachball for a good 30 seconds. I would eventually restart the app (never thought to toggle or clear the console) and the problem would go away for a few hours. 

Now toggling or clearing the console makes the app responsive again and I'll have to go without this feature to make the application usable. I think you are on to something regarding the rendering of the console. My guess is maybe they continue to syntax highlight, re-render, or perform work on the entire console every time a new entry is added as the issue gets exponentially worse the longer the console.

**Comment by huyphams** [comment]
We just released the 304 update which includes an attempt to fix this issue (temporarily disable highlight syntax in the console).

**Comment by egold** [comment]
Thanks for the fast turnaround on this! Do you intend to bring back syntax highlighting in a performant way, or keep it out for performance?

**Comment by huyphams** [comment]
It's a temporary solution, we will comeback to
fix it later.

**Comment by huyphams** [comment]
Just in case, the build that fixed the syntax highlighting issue, it will be officially released in the next update:  https://www.dropbox.com/s/9ldedn9gnvecljd/tableplus.dmg?dl=0
