### ISSUE TITLE
mac/sqlite new row gets removed on commit

### ISSUE THREAD

**Issue by noahblumberg** [TablePlus/TablePlus#1822]
1. sqlite 3.27.2
2. TablePlus version 3.3.0
3. steps to repro:
- connect an existing sqlite db
- select a table
- click + row button
- enter data
- notice new row is highlighted green and table is highlighted yellow
- type command+s or click the commit button
- notice the new row is gone

sample of the resulting sql output

-- 2020-04-16 16:51:10.9590
INSERT INTO  "Cars" ("year") VALUES ('2020');

-- 2020-04-16 16:51:10.9950
SELECT "rowid" as rowid,* FROM  "Cars" ORDER BY 1 LIMIT 300 OFFSET 0;

-- 2020-04-16 16:51:10.9960
SELECT COUNT(*) as count FROM  "Cars";

**Comment by huyphams** [comment]
It seems that SQLite silents the error. Let me check it. Can I have the table creation @noahblumberg thank you!

**Comment by huyphams** [comment]
It's resolved, thank you!
https://github.com/TablePlus/TablePlus/issues/1405
