### ISSUE TITLE
How do you get this awesome native multi-platform application?

### ISSUE THREAD

**Issue by lucyferzyr** [TablePlus/TablePlus#1824]
How do you get this awesome native multi-platform application?
Hi guys, 

I'm sorry to use github to ask for this but, I wasn't able to find a better place. TablePlus is an awesome app, I just love people doing an effort to keep building applications that consumes low ram/cpu. I know why some companies prefer to build multi-platform apps using frameworks like electron, but, I just can't see reasons why I would change tableplus for another app. How fast the app is, at least for my, is the main reason why I use tableplus.

That being said, I wish more people work on native multi-platform apps, I know you had a Q&A with a general explanation on your site on how you maintained TablePlus, but, I want to ask you guys, if it's possible that you make any kind of contribution explaining, as detailed as possible, how do you achieved this.

I'm a web app developer, and I know some people using electron just because, the amount of post/forums/people talking about the bad alternatives to achieve multi-platform is overwhelming. I really believe that, if you write such post, a lot of people would be encouraged to follow your path and maybe, we would see more native apps :).

**Comment by huyphams** [comment]
Hi @lucyferzyr I'm sorry because of the late response. There is no black magic, we've to pay for it. TablePlus for macOS, Windows, Linux, and iOS are separated projects. We implement it from scratch.

**Comment by mcybz** [comment]
> Hi @lucyferzyr I'm sorry because of the late response. There is no magic, we've to pay for it. TablePlus for macOS, Windows, Linux, and iOS are separated projects. We implement it from scratch.

Wow. That's incredible. So glad it's not an electron app.
