### ISSUE TITLE
TablePlus 304, empty databases, I am able to connect successfuly to a redshift clus, but when the load is finsihed I got nothing showed

### ISSUE THREAD

**Issue by meryemeRh** [TablePlus/TablePlus#1828]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @meryemeRh did you toggle the item pane? You can re-enable it by clicking the button on the top right corner.

**Comment by huyphams** [comment]
Please let me know if you're still seeing this issue.
