### ISSUE TITLE
Insert values with quotes and commas

### ISSUE THREAD

**Issue by sobolevn** [TablePlus/TablePlus#1833]
Hi! Thanks a lot for building TablePlus, it looks promising compared to other tools I have used.

I have a popular workflow that I am not sure is or is not possible in you app.

I have lists of strings values that look like so:

```
ABC001
ABC002
ABC003
```

When I copy-paste them is there any way to paste them as

```
'ABC001',
'ABC002',
'ABC003'
```

Currently I have to use a custom python script, which is kind of slow and unpleasant. 
Thanks!

**Comment by huyphams** [comment]
I'm not sure what version of TablePlus or database... so I'm not sure, here is how to do it in TablePlus (macOS build 304) SQL editor.
![2020-04-23 17 09 38](https://user-images.githubusercontent.com/3654622/80087503-5ae01180-8585-11ea-9c20-91d927e59382.gif)

**Comment by sobolevn** [comment]
Awesome! Thank you!
