### ISSUE TITLE
[Feature Request] Copy column

### ISSUE THREAD

**Issue by fabswt** [TablePlus/TablePlus#1834]
I often need to copy a single column out of a many-columns table.

An option to right click the column header and choose copy would be welcome.

(TablePlus 3.4.0 (304) with Postgres 9.6.)

**Comment by huyphams** [comment]
HI @fabswt  have you tried this option?
<img width="397" alt="Screen Shot 2020-04-24 at 5 21 59 PM" src="https://user-images.githubusercontent.com/3654622/80202638-2422fd80-8650-11ea-9ac8-838786263cbc.png">

**Comment by fabswt** [comment]
You're da man :)
