### ISSUE TITLE
Locks up when previewing rows with large JSON

### ISSUE THREAD

**Issue by jpike88** [TablePlus/TablePlus#1835]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.4.0 304

3. The steps to reproduce this issue:
Put a json into row, preview in right hand preview panel. I have one that is about 400-500kb) big, it causes TablePlus to freeze, and I have to kill it and restart

**Comment by huyphams** [comment]
I've puhsed ah attempt to fix this issue, please try this path and see how it goes https://www.dropbox.com/s/hijhy8j8b6ilpdr/TablePlus.dmg?dl=0 thanks

**Comment by jpike88** [comment]
Works like a charm. Im assuming that the syntax coloring is now happening asynchronously?

**Comment by psychomelet** [comment]
> I've puhsed ah attempt to fix this issue, please try this path and see how it goes https://www.dropbox.com/s/hijhy8j8b6ilpdr/TablePlus.dmg?dl=0 thanks

When will this fix be released?

**Comment by huyphams** [comment]
You can that build until the official is released (around 18th~30th this month), that build can self-update. No worries.
