### ISSUE TITLE
Redis: unable to send command containing empty strings

### ISSUE THREAD

**Issue by tgascoigne** [TablePlus/TablePlus#1836]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redis 5.0.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
304

3. The steps to reproduce this issue:
Empty string arguments in Redis commands seem to be omitted before being sent to the server.

example:
```
SET some_key ""
```

results in: 
```
Query 1 ERROR: ERR wrong number of arguments for 'set' command, 1 row affected
```

But this is a perfectly valid redis command, as demonstrated on redis-cli:
```
$ redis-cli -h redis
redis:6379> SET some_key ""
OK
redis:6379> GET some_key
""
```

**Comment by huyphams** [comment]
Thanks @tgascoigne I fixed this issue.

**Comment by tgascoigne** [comment]
That's great, thank you!

**Comment by huyphams** [comment]
Please try our hot patch: https://www.dropbox.com/s/ndn8m23p7fbvwcq/TablePlus.dmg?dl=0
 please let me know if you're still seeing the issue.

**Comment by tgascoigne** [comment]
Yep, works perfectly. Thank you
