### ISSUE TITLE
Could you add support for NLS_LANG=DANISH_DENMARK.WE8ISO8859P1

### ISSUE THREAD

**Issue by fbengtsson** [TablePlus/TablePlus#1837]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
We added it. Thanks.

**Comment by fbengtsson** [comment]
Thank you for your quick responce...
It's not quite working, but I guess it's hard to test :)

PUNKT1 SÿTORVET should be PUNKT1 SØTORVET
EDC M∆GLERNE POUL ERIK BECH should be EDC MÆGLERNE POUL ERIK BECH

Danish characters is as follows æøåÆØÅ
(ae oe aa AE OE AA)

<img width="244" alt="image" src="https://user-images.githubusercontent.com/4245028/81069781-a62de480-8ee2-11ea-9864-3f8717dff42b.png">

**Comment by huyphams** [comment]
Thanks @fbengtsson for trying it out, did you restart the app after changing the encoding?

**Comment by fbengtsson** [comment]
Yes, twice and a restart

**Comment by fbengtsson** [comment]
In my own macOS apps I set the NLS_LANG=DANISH_DENMARK.WE8ISO8859P1 environment var.
I guess you should do the same?

**Comment by huyphams** [comment]
Yes, we did the same.

**Comment by huyphams** [comment]
But I guess I should change the params 0 to 1 because TablePlus will not override the current environment value.
<img width="327" alt="Screen Shot 2020-05-05 at 8 27 40 PM" src="https://user-images.githubusercontent.com/3654622/81071426-e440fd80-8f0e-11ea-9124-3362b79da311.png">

**Comment by fbengtsson** [comment]
Found the problem, it seems you are one off in your index.
If I choose Japanese I get the Danish encoding

**Comment by huyphams** [comment]
Actually, it would be the same with American_America.UTF8 the prefix `American_America` or `JAPANESE_JAPAN` is the language for the error message
