### ISSUE TITLE
should not use `count(*)`

### ISSUE THREAD

**Issue by iiinsomnia** [TablePlus/TablePlus#1839]
should not use `count(*)`，because of large data will be very slow.

![image](https://user-images.githubusercontent.com/6582246/80556114-23e68180-8a05-11ea-9910-46c6b84326ff.png)

**Comment by huyphams** [comment]
Are you using MySQL @iiinsomnia please do not remove the issue template question.

TablePlus will estimate the rows. If the rows count is small, it will count the actual rows. That's how it works

**Comment by iiinsomnia** [comment]
thanks.
