### ISSUE TITLE
Display column length in table structure view

### ISSUE THREAD

**Issue by gologi** [TablePlus/TablePlus#184]
When i use postgresql driver with tablePlus v1 (82), on the table structure view, the data_type column show the type eg: varchar, but the column length information is missing
is it possible to add a column with this info ?

**Comment by huyphams** [comment]
Let me take a look at metadata, I have done it in MySQL.

**Comment by lopezator** [comment]
This still happens for CockroachDB, it impossible to know the size of the column unless you go to column definition.

**Comment by huyphams** [comment]
Hi @lopezator please download this patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 you will see the data length.
