### ISSUE TITLE
Can not connect mysql via ssh when use another port instead of 3306 

### ISSUE THREAD

**Issue by fffx** [TablePlus/TablePlus#1842]
Tableplus: Windows build 122

My config:
![image](https://user-images.githubusercontent.com/11586335/80691839-60000c00-8b03-11ea-81df-2089676323e3.png)
 
Click test got this error:

![image](https://user-images.githubusercontent.com/11586335/80691466-e2d49700-8b02-11ea-9f35-02b705764228.png)

But if I change the Port from `3307` to `3306`  then it works. but I don't want to use `3306` which is occupied by my local MySQL instance

**Comment by huyphams** [comment]
I don't think that the port 3307 is using the same protocol as 3306. You can use 3306 without any problem, one port can service many clients.

**Comment by huyphams** [comment]
I think this issue is not related to TablePlus so I will close this issue, please let me know if you have any question via nick@tableplus.com
