### ISSUE TITLE
Support for IAM based Redshift connections

### ISSUE THREAD

**Issue by Limess** [TablePlus/TablePlus#1844]
# Feature suggestion

Allow IAM authentication to AWS Redshift using the [`GetClusterCredentials`](https://docs.aws.amazon.com/redshift/latest/APIReference/API_GetClusterCredentials.html) API.

## Description

Allow users to connect to redshift using IAM. 

This is essential if an organisation locks down Redshift to only allow IAM authentication using temporary credentials (this also applies to active directory/SSO authentication but that has many more configurations/parameters).

This would need to accept:

1. The IAM role to use
2. An AWS Profile/AWS key + secret key/session token
3. A `DbUser` to use
4. An `AutoCreate` parameter to toggle auto creation of users if they do not exist
5. `DbGroups`, a comma separted list of groups to join with the user

## References

* [connecting to redshift using IAM through a JDBC driver](https://docs.aws.amazon.com/redshift/latest/mgmt/generating-iam-credentials-configure-jdbc-odbc.html)
* [options for providing IAM credentials](https://docs.aws.amazon.com/redshift/latest/mgmt/options-for-providing-iam-credentials.html)
* [example non JDBC implementation in the DBT project (python)](https://github.com/fishtown-analytics/dbt/blob/aa0e58ef3bbc863c880b7f5b0a316433e65e87ac/plugins/redshift/dbt/adapters/redshift/connections.py#L110-L133)

## Build Info
* > Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81)

	`3.4.0 (304)`

**Comment by nicholasgcoles** [comment]
@Limess this is a great feature request! 

What is your current workaround out of interest?

**Comment by Limess** [comment]
Sadly we don't have a workaround, we're still using manually provisioned username and passwords for now. We recommend tableplus as a DB client so it's a bit of a blocker.

**Comment by huyphams** [comment]
Hi @nicholasgcoles you can improve this by adding -a flag to make sure it open with TablePlus

> os.system(f"open {url}")

to os.system(f"open -a TablePlus {url}")

<img width="1075" alt="Screen Shot 2021-09-20 at 10 15 03 PM" src="https://user-images.githubusercontent.com/3654622/134027390-29614c31-7232-4b23-88e3-f6ddbc0c8a6e.png">

**Comment by huyphams** [comment]
TablePlus now supports getting the password via Command Line IAM.

![CleanShot 2022-09-23 at 15 09 27@2x](https://user-images.githubusercontent.com/3654622/191918020-20582fcf-2e9b-48a6-a17b-096d741f52c4.png)

if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're seeing any issue.

**Comment by kd-nishanth** [comment]
@huyphams Is there any kind of documentation for this one? I'm trying to connect via IAM but unable to. 

`aws --profile profile_name redshift get-cluster-credentials --db-user user --db-name default_db --cluster-identifier warehouse-cluster --duration-seconds 3600  --region us-east-2` gives me credentials which work well when passed manually via the password option. 

The Command Line IAM option fails when i pass the above in the password field with the error message: `FATAL:  password authentication failed for user `

**Comment by huyphams** [comment]
Hi @kd-nishanth does the user also dynamic, or only password dynamic?

**Comment by kd-nishanth** [comment]
The user is not created dynamically and only the password is.

**Comment by kd-nishanth** [comment]
@huyphams The user is not created dynamically and only the password is.
