### ISSUE TITLE
[Feature Request] Copy Column Values As Column

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1845]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.4.0 (304)

It would be great if TablePlus could copy column values as a column. This would facilitate copying only partial data from TablePlus into a spreadsheet.

Example: Currently, when copying 4 rows (right mouse click > Copy all column values), the values are copied to the clipboard as:

36, 37, 38, 39

It would be great if the data could be also copied as:

36
37
38
39

Currently, I first have to copy the contents of the clipboard into a text editor and replace ", " with "\n" before I can copy and paste it from there into a spreadsheet.

**Comment by huyphams** [comment]
Hi @chrschmitz  You can do it with TablePlus multiple carets. I think the current format is usefull because people can use it for queries (copy and paste it to Where condition)

**Comment by chrschmitz** [comment]
Huy, thanks for the quick response, but I do not understand what you mean with "TablePlus multiple carets".

**Comment by huyphams** [comment]
Please check this blog @chrschmitz https://tableplus.com/blog/2019/09/multiple-cursors-selection.html

**Comment by chrschmitz** [comment]
This is another workaround using the TablePlus editor instead of a standalone editor to reformat the contents of the clipboard before pasting it into a spreadsheet.

**Comment by huyphams** [comment]
Yes, I know it, but the problem is how many users who copy columns and paste into a spreadsheet and how many users who copy columns and paste into queries? If I change it to the new line `\n`, it will mess up the other use case.

**Comment by chrschmitz** [comment]
What about two options?

Copy All Column Values > As Horizontal List
                                         > As Vertical List

**Comment by huyphams** [comment]
I have thought about it in the first place but adding an option sometimes makes the UI hard to use and confusing. It just a small detail but the current term `Copy All Column Values` is also a bad practice. many users email me and asked for that option (it's there, but they didn't know/didn't understand it), so I don't want to mess it up.
I will keep thinking about it.

**Comment by huyphams** [comment]
However, it's possible with the plugin, you could create something that similar to this easily. Basically, get all the column values and then join it with new line: https://github.com/TablePlus/openurl

**Comment by chrschmitz** [comment]
I will look into that!

**Comment by huyphams** [comment]
Here is the demo and the code that I cloned from the plugin:
![2020-05-02 21 35 47](https://user-images.githubusercontent.com/3654622/80867206-0cd1b900-8cbd-11ea-81b8-f9d7aba52ae3.gif)
[copy-column.zip](https://github.com/TablePlus/TablePlus/files/4567924/copy-column.zip)

**Comment by huyphams** [comment]
Super easy, unfortunately, I don't have time to write the documents 😭. Hopefully, I can do it this month.

**Comment by chrschmitz** [comment]
Amazing! Works with charm!
