### ISSUE TITLE
[Feature Request] Allow SQLite Extensions to be Installed

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1846]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.4.0 (304)

It would be of great advantage if TablePlus would support the loading of [SQLite run-time loadable extensions ](https://www.sqlite.org/loadext.html) (such as the [math extension](https://sqlite.org/contrib/download/download/extension-functions.c?get=25)) as it is possible in [DB Browser for SQLite](https://sqlitebrowser.org).

The following lines of code, which work in other database browsers, unfortunately do not work either:

    PRAGMA load_extension = 1;
    SELECT load_extension('./libsqlitefunctions.dylib');

    SELECT power(2, 6);

This is TablePlus' output:

    Query 1 OK: 
    Query 2 OK: 
    Query 3 ERROR: no such function: power

Attached is the compiled library.

[libsqlitefunctions.dylib.zip](https://github.com/TablePlus/TablePlus/files/4567823/libsqlitefunctions.dylib.zip)

**Comment by huyphams** [comment]
Thanks @chrschmitz but it seems it's duplicate to this issue: https://github.com/TablePlus/TablePlus/issues/1817 please check and follow this issue instead.
