### ISSUE TITLE
[Feature Request] Drag and drop structure fields for order change

### ISSUE THREAD

**Issue by HadrienX** [TablePlus/TablePlus#1847]
Changing structure fields order may be cumbersome in TablePlus because we have to change every columns id.
Instead it would be great to drag a field to another place to change its position. Sequel Pro provides this feature.

![Capture d’écran 2020-05-03 à 10 36 55](https://user-images.githubusercontent.com/5130572/80909661-50aed780-8d2a-11ea-8786-31e624f6b3d4.png)

**Comment by huyphams** [comment]
Thanks, it's duplicated to https://github.com/TablePlus/TablePlus/issues/607
