### ISSUE TITLE
Geom data is displayed in another part of the globe.

### ISSUE THREAD

**Issue by rgrabowski** [TablePlus/TablePlus#1849]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 9.6.11
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
306
3. The steps to reproduce this issue:
Displaying polygons of ex: Stockholm county on the map shows the polygon on the another part of the world. Probably lat is replaced with long. QGis App shows it properly.

<img width="803" alt="Screenshot 2020-05-04 13 17 22" src="https://user-images.githubusercontent.com/2242603/80961052-6398d900-8e0a-11ea-944f-1f52047c2d5c.png">
<img width="953" alt="Screenshot 2020-05-04 13 16 29" src="https://user-images.githubusercontent.com/2242603/80961058-672c6000-8e0a-11ea-96b9-41de2c83b2b6.png">

I am also attaching Stockholms County polygon data.

[stockholm_shape.zip](https://github.com/TablePlus/TablePlus/files/4574299/stockholm_shape.zip)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
thank you, I'm checking it.

**Comment by huyphams** [comment]
Hi @rgrabowski please check out this hot patch and see how it goes: https://www.dropbox.com/s/ndn8m23p7fbvwcq/TablePlus.dmg?dl=0
Thank you!

**Comment by rgrabowski** [comment]
@huyphams Now it looks ok ;)
Thanks
<img width="914" alt="Screenshot 2020-05-04 16 48 02" src="https://user-images.githubusercontent.com/2242603/80979056-28f16980-8e27-11ea-88e3-673ab9bad7c0.png">

**Comment by huyphams** [comment]
Maybe I should add an option to hide pins ?

**Comment by rgrabowski** [comment]
Yes, it would be nice to see the only shape.

**Comment by huyphams** [comment]
It's supported now.
![2020-05-04 22 02 34](https://user-images.githubusercontent.com/3654622/80980624-0ffead80-8e53-11ea-9796-3a39508bb3db.gif)

**Comment by rgrabowski** [comment]
Look very nice.

**Comment by rgrabowski** [comment]
Maybe just "Show ~polygon~ pins"?

**Comment by rgrabowski** [comment]
Will it be accessible in the beta channel soon?

**Comment by huyphams** [comment]
Yes, we will release it in the next beta release (and probably officially at the end of this month).
