### ISSUE TITLE
Select Foreign Keys via Drop Down Menu (Optional)

### ISSUE THREAD

**Issue by ujaeggi** [TablePlus/TablePlus#1850]
It would be great if there would be an option for foreign keys in the form of a drop down menu like [HeidiSQL](https://www.heidisql.com) does. For example a table themes for a quiz has a foreign key to a table with with languages. Inside the theme table I can click on the language table an a drop down menu is shown with the id and the field next to it (in this case the language column):

<img width="383" alt="foreign-key-drop-down" src="https://user-images.githubusercontent.com/35268293/81003839-c8285800-8e4b-11ea-9db7-99412778dd1d.png">

**Comment by huyphams** [comment]
I'm not sure that I understand the issue correctly, but it seems it was the TablePlus for Windows. So I will close this issue for now because this is macOS repo and move it to the Windows repo with more details: https://github.com/TablePlus/TablePlus-Windows/issues/220
