### ISSUE TITLE
Unable to connect to SQL Server on non-standard port over ssh

### ISSUE THREAD

**Issue by finity84** [TablePlus/TablePlus#1852]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

```
Microsoft SQL Azure (RTM) - 12.0.2000.8 
        Apr  9 2020 16:39:55 
        Copyright (C) 2019 Microsoft Corporation
```

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

304

3. The steps to reproduce this issue:

Connecting to a 3rd-party data provider's DB so unable to provide much details. However it used to work before until they migrated the instance, changing port from 1433 to 3342. ODBC and Sql Server Management is still able to connect. Unable to test without SSH as connection is only permissioned for our internal network. Any advice would be appreciated.

Tried with various DBVERSION_, they all failed, mostly with login failed like

```
Adaptive Server connection failed (127.0.0.1:65123)
Adaptive Server connection failed (127.0.0.1:65123) 
Message: Msg: 18456, Line 1, State: 1, Level: 14
Login failed for user 
```

**Comment by huyphams** [comment]
Hi @finity84 I think the issue isn't on the TablePlus side, could you please try again and let me know the result? Thanks!

**Comment by finity84** [comment]
@huyphams I just tried with latest version I still received a login failed after trying a few driver versions.
Any way to see the sql messages? SSH log didn't show anything relevant it seems.

```
Error: General SQL Server error: Check messages from the SQL Server
Adaptive Server connection failed (127.0.0.1:52299) 
Message: Msg: 18456, Line 1, State: 1, Level: 14
Login failed for user 
```

**Comment by finity84** [comment]
@huyphams I just had access to the prior instance briefly with the standard port, and was able to connect without issues. Still can't connect to the instance with the non-standard port over ssh.
