### ISSUE TITLE
Support padding adjust in sql editor

### ISSUE THREAD

**Issue by yiwenshengmei** [TablePlus/TablePlus#1856]
Support padding adjust in sql editor just like "data table settings"

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 304
3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
is this the feature that you're looking for?
<img width="921" alt="abc" src="https://user-images.githubusercontent.com/3654622/81145110-d2f40180-8f9f-11ea-9f37-e447733e607a.png">

**Comment by huyphams** [comment]
It's duplicate to this issue: https://github.com/TablePlus/TablePlus/issues/1146
