### ISSUE TITLE
Feature Request: More custom keymap options

### ISSUE THREAD

**Issue by repsher** [TablePlus/TablePlus#1858]
I didn't know what the level of effort would be to add more customizable keymap options to the SQL editor would be but it's something I'd greatly appreciate. Specifically I'd like to remap the "Run Current" query to be Command+R (which is in use by something else I believe). Would also love to be able to save the .sql file I'm working on by just hitting Command+S like I do in most other editors. Again this key combo is in use by something else that I personally don't use.

<img width="791" alt="Screen Shot 2020-05-07 at 9 28 16 AM" src="https://user-images.githubusercontent.com/2151463/81314573-831c4580-9046-11ea-8fe8-6846a16afba8.png">

I looked around but didn't see this request, sorry if I missed it and it's a dup.

**Comment by cotfas** [comment]
"Run Current" +1

**Comment by lsandovalr** [comment]
+1

**Comment by huyphams** [comment]
It's supported "run current" now.
