### ISSUE TITLE
Export -> import Connections not doing anything

### ISSUE THREAD

**Issue by talkl** [TablePlus/TablePlus#1865]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 304

3. The steps to reproduce this issue:

export all connections from build 304 on macOs Mojave, put password to the file and include passwords and keys
import by right clicking where it says "No connection, "right click" to create a new connection" 
 -> import connections -> enter the password that i've set -> nothing happens

**Comment by talkl** [comment]
it's from macOs Mojave build 304 (licensed) -> macOs Catalina build 304 (new table plus) not licensed yet

**Comment by huyphams** [comment]
hi @talkl please download this build on both machines: https://www.dropbox.com/s/vu4t07fdskj4c6w/TablePlus.dmg?dl=0
and try to export/import again, it would solve the issue.

The reason: the current version has failed to handle export/export connections which do not belong to any groups.
