### ISSUE TITLE
MongoDB collections not displaying

### ISSUE THREAD

**Issue by foraern** [TablePlus/TablePlus#1867]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mongo 3.6.14
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.0 (308)
3. The steps to reproduce this issue:
Run connection via SSH Tunnel with private key
Select database
No collections (tables) appear

![image](https://user-images.githubusercontent.com/1875944/81558855-4faf2300-9386-11ea-84ae-8c47129b2b77.png)

It is possible to select another database in the connection, but collections still don't appear.
Working fine in previous version, no changes to connection or db.
When closing connection (tab/window), Table Plus freezes and stops responding.

For background, opened up Table plus this morning, connected to server, was working on a collection with no issue. Popup came up to update Table Plus. After update, was able to connect to server, and select db, but no collections appear.

Mysql connections work fine. (closing tab/window on mysql connection also works fine).

Same MongoDb connection on Studio 3T works fine.

**Comment by qvdp** [comment]
Same here on mongo database on macOs app, move to [build 304](https://s3.amazonaws.com/tableplus-osx-builds/304/TablePlus.dmg) fix the issue for the moment.

**Comment by huyphams** [comment]
Thanks, guy, I fixed it and uploading the build, please wait.

**Comment by huyphams** [comment]
Hi, Please try this hotpatch: https://www.dropbox.com/s/am0f0toy4wjf9pl/tableplus.dmg?dl=0 thank you!

**Comment by foraern** [comment]
Worked perfectly, thank you!
