### ISSUE TITLE
`ERROR:  transparent decompression only supports tableoid system column` when attempting to view compressed Timescale hypertable

### ISSUE THREAD

**Issue by martinhale** [TablePlus/TablePlus#1869]
Hey - I've ran into a slight issue when trying to use TablePlus with [TimescaleDB](https://docs.timescale.com/latest/introduction) (a popular PostgreSQL extension for efficiently dealing with time-series data).

Specifically the problem occurs when attempting to view a table that contains data that has been [compressed](https://docs.timescale.com/latest/using-timescaledb/compression).

Steps to reproduce given below. Please let me know if there is any other information that I can provide.

Thanks!

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`PostgreSQL 12.2`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`build 308`

3. The steps to reproduce this issue:

    1. Spin up a new Timescale image: 
        ```
        docker run -d --name temp -p 5432:5432 -e POSTGRES_PASSWORD=postgres timescale/timescaledb:latest-pg12
        ```
    2. Connect using TablePlus:
        ```
        postgresql://postgres:postgres@127.0.0.1/postgres
        ```
    3. Create a new [`hypertable`](https://docs.timescale.com/latest/api#create_hypertable):
        ```
        CREATE TABLE temp(t TIMESTAMPTZ);
        SELECT create_hypertable('temp', 't');
        ```
    4. Insert some data:
        ```
        INSERT INTO temp (t) VALUES ('2020-05-12');
        ```
    5. Compress the chunk
        ```
        ALTER TABLE temp SET (timescaledb.compress);
        SELECT compress_chunk(i) from show_chunks('temp') i;
        ```
    6. Attempt to view the hypertable by clicking the name in the sidebar. You will see the following error message:
![Screenshot 2020-05-12 at 12 47 52](https://user-images.githubusercontent.com/7632443/81685542-00cdc000-9450-11ea-9d2b-c415345e90a9.png)
        ```
        ERROR:  transparent decompression only supports tableoid system column
        ```
    7. A view similar to the what the above should show can be achieved with the query:
        ```
        SELECT * FROM temp
        ORDER BY t DESC
        LIMIT 300;
        ```

**Comment by huyphams** [comment]
I did exactly the same thing but it works.

<img width="1616" alt="Screen Shot 2020-05-12 at 7 29 33 PM" src="https://user-images.githubusercontent.com/3654622/81691382-ecf18080-9486-11ea-9ca3-f6464a2a87d8.png">

**Comment by huyphams** [comment]
Sorry, it was my bad.

**Comment by huyphams** [comment]
Hi @martinhale could you please try this build and see how it goes: https://www.dropbox.com/s/am0f0toy4wjf9pl/TablePlus.dmg?dl=0
Thanks!

**Comment by martinhale** [comment]
@huyphams That seems to work perfectly! Thanks so much! 😄
