### ISSUE TITLE
Unable to edit/delete keyboard shortcuts

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#187]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
83
3. The steps to reproduce this issue:
**Clicking on "Delete shortcut" or "Click to record new shortcut" have no effect.** It should be noted that I'm still on Mac OS Sierra as my workplace has not okayed High Sierra yet.

**Comment by huyphams** [comment]
Hi @bhrd the keyboard shortcut can't be changed, I'm refactoring to apply it. Probably I should put some text that tells users it is incompleted.

**Comment by mkarnicki** [comment]
I'd say `planned` would be a better label than `it's-not-a-bug-it's-feature` :)
