### ISSUE TITLE
Can't see foreign keys when viewing a table's structure in the interface

### ISSUE THREAD

**Issue by ajdabrowski** [TablePlus/TablePlus#1870]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

TablePlus 3.5.0 (308)

3. The steps to reproduce this issue:

I'm working on migrating a legacy DB and currently need to keep table names as they are, but it appears that table names where case sensitivity matters cause an issue for seeing foreign keys in the "structure" view.  

Here's the comparitive test I ran for myself:

## Works
Create two tables with standard naming (lower case, "_") and add foreign key constraint:

**question_category table**
<img width="1144" alt="Screen Shot 2020-05-12 at 10 38 16" src="https://user-images.githubusercontent.com/46501789/81714569-d0305b00-943c-11ea-8b86-e33dfc5567a0.png">

**question_subcategory table**
<img width="1146" alt="Screen Shot 2020-05-12 at 10 38 34" src="https://user-images.githubusercontent.com/46501789/81714777-0bcb2500-943d-11ea-9856-a1ea7cb481d6.png">

The foreign key information shows up as "public.question_category(id)" in question_subcategory.category_id

## Doesn't work
Create two tables with non-standard naming (title case, no spaces) and add foreign key constraint:

**QuestionCategories table**
<img width="1146" alt="Screen Shot 2020-05-12 at 10 47 04" src="https://user-images.githubusercontent.com/46501789/81715713-2520a100-943e-11ea-98cb-de62af1ca016.png">

**QuestionSubCategories table**
<img width="1143" alt="Screen Shot 2020-05-12 at 10 47 15" src="https://user-images.githubusercontent.com/46501789/81715753-3073cc80-943e-11ea-95c6-6fe840fe3464.png">

The foreign key information does not appear in QuestionSubCategories.category_id  

:(

**Comment by huyphams** [comment]
Thanks, let me check it.

**Comment by tebuevd** [comment]
experiencing the same thing. TB 3.5.0. Postgres 10

**Comment by tebuevd** [comment]
Is there a way to downgrade while we wait for this to be resolved?

**Comment by huyphams** [comment]
Hi, this build should fix the issue: https://www.dropbox.com/s/i6vgt7ho36emsm6/TablePlus.dmg?dl=0
Sorry because of the late response.

**Comment by ajdabrowski** [comment]
> Hi, this build should fix the issue: https://www.dropbox.com/s/i6vgt7ho36emsm6/TablePlus.dmg?dl=0
> Sorry because of the late response.

Getting a 404 "That file isn't here anymore" from that Dropbox link.

**Comment by huyphams** [comment]
Sorry, please use this link: https://www.dropbox.com/s/rbhue8kr9k8sl8s/TablePlus.dmg?dl=0

**Comment by huyphams** [comment]
Please let us know if you're still seeing the issue. thanks.

**Comment by dmythro** [comment]
So, yes. Using version 4.5.2 and have an issue where foreign key is shown in a **fields** table, but is **not shown in index list** table. And weirdest thing is, same foreign key is shown well in **index list** table for another table. @huyphams
