### ISSUE TITLE
Reorder tabs on mac

### ISSUE THREAD

**Issue by cotfas** [TablePlus/TablePlus#1871]
Catalina 10.15.4
TablePlus build 308

Posibility to reorder tabs from the left pane, and when dragging out, to jump to a new window. It is more naturally on mac.

<img width="88" alt="image" src="https://user-images.githubusercontent.com/3340367/81718872-f2e66200-9484-11ea-86b6-df5793544cb4.png">

**Comment by huyphams** [comment]
Hi @cotfas thank you, it's a duplication of https://github.com/TablePlus/TablePlus/issues/1727 so I will close this issue to clean up the repo.
