### ISSUE TITLE
[BUG] Tabs flickering on mac when merged back to one window

### ISSUE THREAD

**Issue by cotfas** [TablePlus/TablePlus#1872]
Catalina 10.15.4
TablePlus build 308

Steps to reproduce:
1 Create 4 tabs connection to MariaDB to the same TablePlus window
2 Right click on a tab and "Move tab to new window"
3 Statusbar -> Window -> Merge all windows
4 When all tabs are back in the same window, when moving with the mouse between tabs, some of them (I think the one that was merged) get flickered.

See the attached video:
[tablePlusTabsBug.mov.zip](https://github.com/TablePlus/TablePlus/files/4616974/tablePlusTabsBug.mov.zip)

**Comment by huyphams** [comment]
Thanks @cotfas I just fixed this bug, if you have a chance, please try this hot patch: https://www.dropbox.com/s/am0f0toy4wjf9pl/TablePlus.dmg?dl=0

**Comment by cotfas** [comment]
Wow, you were fast, all good from my side, it works, thank you.
