### ISSUE TITLE
running queries not visible in process list sometimes

### ISSUE THREAD

**Issue by salmanasiddiqui** [TablePlus/TablePlus#1875]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
308

3. The steps to reproduce this issue:
Well there are no specific steps to reproduce this issue, it happens almost on every long running query. I guess running any query which takes more than 20 seconds to return.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by cpuell** [comment]
This also happen randomly with simple queries. Tablesplus seems to loose connection and any query currently running is not been able to kill.

It shows the connection attempt, but no query in dialog. It is not even detect the loss of server connection.

You can test by using connection to a Postgres via VPN, than disconnect the VPN session while having a query running.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/58947247/184486074-f59da362-b003-4639-b1b2-d8f6cb38159e.png">

**Comment by huyphams** [comment]
Hi @cpuell the "Running queries" is using a different connection, it has nothing to do with the current connection of the workspace, you can see in the bottom left the status is Initializing... (it's connecting to the server to fetch the list).

> You can test by using connection to a Postgres via VPN, than disconnect the VPN session while having a query running.

You disconnect from the server so the process list could not connect to the server which results in no queries in the list.
