### ISSUE TITLE
UI show slow when come back to tableplus

### ISSUE THREAD

**Issue by pfdtk** [TablePlus/TablePlus#1877]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Aws redshift and rds

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 308 on macOs Catalina 10.15.3, Macbook Pro 16-inch

3. The steps to reproduce this issue:
Open tableplus and open several table, then switch to other app to do something, when I come back to tableplus by click the icon on the dock, the tableplus ui show very slow, maybe 1 or 2 seconds. It looks bad.

ps:
Build 304 is ok.

**Comment by huyphams** [comment]
Hi @pfdtk thanks, could you please try this patch and see how it goes: https://www.dropbox.com/s/am0f0toy4wjf9pl/TablePlus.dmg?dl=0
