### ISSUE TITLE
Memory leak when idle

### ISSUE THREAD

**Issue by philipnewcomer** [TablePlus/TablePlus#1879]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3.22

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.0 (308), although this issue has been occurring for me for quite some time (~6 months, so it's not related to any recent update).
macOS 10.15.4

3. The steps to reproduce this issue:
Leave TablePlus connected to the database overnight. When resuming work the next morning, TablePlus is consuming several gigs of RAM and is not responding. Sometimes I am able to kill TablePlus without having to reboot, however, if I don't get to it in time the entire system becomes unresponsive and I have to force-reboot my machine. If I am not interacting with TablePlus for a long period of time during the day sometimes it will lock up my machine during my workday if I am not keeping an eye on it, and I have to force-reboot midday. But by far the most common time for lockups and force-reboots is when I return to my machine in the morning. Usually I have just enough time to open Activity Monitor and I see TablePlus consuming several gigs of RAM and unresponsive before my entire system locks up completely.

<img width="1390" alt="Screen Shot 2020-05-14 at 6 39 03 AM" src="https://user-images.githubusercontent.com/1446874/81925915-29b89700-95af-11ea-9a55-d45757f360e7.png">

**Comment by philipnewcomer** [comment]
I have some more information. The memory leak appears to be triggered by *switching to* TablePlus after a long idle period. This typically happens for me when I begin my day. At the start of my day, TablePlus will be consuming the normal amount of RAM in Activity Monitor in its own macOS Space, but as soon as I switch to it, I get the spinning beach ball and TablePlus' memory usage begins to climb by 100 MB or so per second. This will continue until the whole machine locks up, unless I force quit TablePlus in time. This happens consistently almost every morning.

**Comment by huyphams** [comment]
Thanks @philipnewcomer for the information!

**Comment by sc0ttie** [comment]
Same here!

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.6.1 (320), macOS 10.15.4
PS. I'm sure this problem also occurs in 3.6.0

3. The steps to reproduce this issue:
Leave TablePlus connected to the database overnight. By the way, my database is hosted on local and installed by Homebrew.

But the memory leak is not triggered by switching to TablePlus, my computer just gets slowing/stuck after login for about 20 minutes and the Force Quit window says TablePlus is not responding.

**Comment by philipnewcomer** [comment]
I have another piece of information that may be helpful in reproducing this. I always use TablePlus in full screen mode in its own macOS Space. I started leaving TablePlus in normal (non-full screen) mode overnight, and I have not had any memory leaks when doing that. @sc0ttie any chance you've been leaving TablePlus in full screen mode as well?

The leak on my system may not actually be triggered by switching to TablePlus. I typically do that when returning to my machine as the beginning of my day, but since @sc0ttie reported that for him it's not triggered by switching to the app, I did some more testing and found that like him, just starting to use my machine after being idle overnight triggers the memory leak, without switching to it.

**Comment by philipnewcomer** [comment]
@huyphams are there any logs that would be useful or anything more we can provide to help you in investigating this issue?

**Comment by timscott** [comment]
I'm seeing 5Gb memory consumption lately in the morning. I never use full screen mode.

**Comment by crberube** [comment]
I am seeing this issue as well. TablePlus 3.6.1 (320), Postgres 10.5, OS X 10.15.5. After sleeping my computer with TablePlus connected to a database in a normal background window, upon resume it was using 24.70 GB of memory, rendering my computer pretty much unusable.

**Comment by huyphams** [comment]
Hmm, I think this issue is related to the auto-reconnect feature. let me check it.

**Comment by huyphams** [comment]
Hi guy, please try this patch and see how it goes: https://www.dropbox.com/s/l897ixh2y40ql41/TablePlus.dmg?dl=0
Thanks all.

**Comment by crberube** [comment]
Will do! The auto-reconnect feature sounds like a plausible culprit. I have another situation as well where I'll have multiple databases open in workspaces that are only accessible over VPN. Often I will keep those open as I am working in them throughout the day. Whenever I am disconnected from the VPN it appears to continually try to connect to those databases.

**Comment by crberube** [comment]
So far the memory usage has been much better. This morning upon waking the computer TablePlus was not using any more memory than usual, however it did stop responding and start to spin CPU cycles such that I had to force quit the application.

**Comment by philipnewcomer** [comment]
@huyphams that version seems to have resolved the memory leak issues for me, thank you.

**Comment by crberube** [comment]
@huyphams Over the last week memory usage has been consistently good. Still having occasional issues with the application locking up on wake. I have a process sample and spindump available if that would be helpful in diagnosing.

**Comment by philipnewcomer** [comment]
@huyphams Just confirming that I have not had any further memory leaks in 2+ weeks after installing that patch.

**Comment by huyphams** [comment]
Thanks all!
