### ISSUE TITLE
"Copy All Column Values" should use single quotes for strings

### ISSUE THREAD

**Issue by tamasnet** [TablePlus/TablePlus#1880]
When using the "Copy All Column Values" feature, double quotes are used to wrap the values. This makes it impossible to simply paste the clipboard back into the SQL editor, for example as part of an `IN (...)` clause.

It would be useful to get the list with single quotes, either as the default behaviour or through a preference setting or modifier key.

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 309

3. The steps to reproduce this issue:

- Run any query that includes a string-type column
- Optionally select a range of multiple rows
- Right-click on any value in the string-type column
- Click on "Copy All Column Values"

The resulting text placed on the clipboard will include the value of that column from all selected rows, separated by commas and each value wrapped in double quotes.

**Comment by huyphams** [comment]
That made sense @tamasnet we should change it.

**Comment by huyphams** [comment]
Hi @tamasnet here is the hot patch build: https://www.dropbox.com/s/am0f0toy4wjf9pl/TablePlus.dmg?dl=0
Bonus, you can also custom it to any format, please check this issue: https://github.com/TablePlus/TablePlus/issues/1834

**Comment by huyphams** [comment]
Sorry I mean this issue: https://github.com/TablePlus/TablePlus/issues/1845

**Comment by tamasnet** [comment]
Awesome, thank you, this will definitely make my days better!
