### ISSUE TITLE
TablePlus firing 3 identical queries instead of 1

### ISSUE THREAD

**Issue by Dinoshauer** [TablePlus/TablePlus#1881]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`308`

3. The steps to reproduce this issue:
Run a long running query and then run a query so see what queries are currently running, e.g.:
```sql
SELECT pid, age(clock_timestamp(), query_start), usename, application_name, query
FROM pg_stat_activity
WHERE application_name like 'TablePlus'
ORDER BY query_start desc;
```

Noted: If the bug is related to data, please attach an example SQL data.

As you can see from the screenshot below, postgres is reporting that 3 identical queries are running, with different ages, but I only executed one in the editor using `cmd+enter`

![image](https://user-images.githubusercontent.com/2325817/81945662-ac1c7780-95fe-11ea-8dcb-05de4a442ae0.png)

This seems relatively serious, as if it is actually the case that 3 queries are running, you could potentially get duplicate data with inserts etc. and be wasting a lot of resources running heavy queries

**Comment by huyphams** [comment]
Hmm, technically, it's impossible. TablePlus only opens 1 connection, and 1 connection can only handle 1 query at a time (if we execute more than 1 query at a time, the Postgre lib will crash).

**Comment by Dinoshauer** [comment]
Is there a way I can downgrade to test a previous version? I haven't noticed this before 308

**Comment by huyphams** [comment]
Yes, you can: https://tableplus.com/osx/changelog

**Comment by huyphams** [comment]
Maybe you forgot to put the filter?

- PostgreSQL version < 9

```
select * from stv_recents where status='Running';
```

- PostgreSQL version >= 9    
``` 
select * from pg_stat_activity where state!='idle' and query not ilike'%pg_stat_activity%' order by query_start desc;
```

**Comment by Dinoshauer** [comment]
No, all 3 queries are reported as `active`

![image](https://user-images.githubusercontent.com/2325817/81950371-21d71200-9604-11ea-894b-06c66862a4ae.png)


Build 300 and 304 are the same as 308

**Comment by huyphams** [comment]
I think those queries are counting from a large table. Could you please kill those queries and try again? (You can kill by open the process list and kill it).

**Comment by Dinoshauer** [comment]
It's a relatively large table (~35 million rows) yes. If I kill one of the pids TablePlus will sometimes report the query as dead/cancelled, but sometimes not.

**Comment by huyphams** [comment]
I will investigate it, is your Postgres server run on cluster mode or single node? is the table has fragmented content?

**Comment by Dinoshauer** [comment]
It's a database spun up through ibm cloud, it has a replica, i don't have much access to other than that i'm afraid. 
Not sure what you mean by fragmented content?

**Comment by huyphams** [comment]
I'm not sure but I think the count query will be "split into 3 child process"  on the server because its content are on multiple nodes or if it was a fragmented table. I will take a look at its document now.

**Comment by huyphams** [comment]
Have you tried to run the query with other clients and check the running process @Dinoshauer thanks!

**Comment by Dinoshauer** [comment]
Hey @huyphams - sorry for the ridiculously long lead time :) I can confirm that there are also 3 queries when run through the postgres cli, so I think your previous theory is correct! Thanks for the time!
