### ISSUE TITLE
Directory naming anything suffix .csv cause issue [UI Problem]

### ISSUE THREAD

**Issue by elijahtsai** [TablePlus/TablePlus#1883]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.1
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
308
3. The steps to reproduce this issue:

Setup:
(1) Create a directory with any name and suffix with .csv at knowing path. 
(2) In TablePlus menu, File > Import.
(3) Go to the path of directory when created in (1).

Problem: 
If the directory naming anything suffix .csv and interacting with the Import file selector it cannot go into the directory, it seems like treat the directory as a file.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, I just fixed it!
