### ISSUE TITLE
[Feature] Sorting of saved queries

### ISSUE THREAD

**Issue by MartinZubek** [TablePlus/TablePlus#1886]
1. Which driver are you using: **PostgreSQL 12.1**
2. Which TablePlus build number are you using: **3.5.0 (308)**

Currently there is no possibility to change the order of saved queries inside a folder.
It almost appears that the drag-and-drop reordering is supported but actually nothing happens.

Or if not allow manual ordering please at least make it sorted by the name of query by default.

![tp](https://user-images.githubusercontent.com/4619133/82093593-be301000-96fb-11ea-854d-592d61b02a14.gif)

Thank you very much for considering this.

**Comment by hugorodgerbrown** [comment]
+1 for ordering by name.

**Comment by huyphams** [comment]
Thanks, I just added an ability to change the sort (in the next update).
<img width="598" alt="Screen Shot 2020-05-17 at 10 15 39 PM" src="https://user-images.githubusercontent.com/3654622/82152516-f8c8b280-988b-11ea-83fe-29032647c0a3.png">

**Comment by MartinZubek** [comment]
Thanks, you are the best 👍

**Comment by huyphams** [comment]
Please download this patch if you don't want to wait for the next update: https://www.dropbox.com/s/ikxmp2miipd5jql/TablePlus.dmg?dl=0
Thank all!

**Comment by chrschmitz** [comment]
When I install this patch, TablePlus directly asks me to update to v3.5.2 Build 311 from March 18, 2020. The patch identifies as v3.5.0 (Build 308).

Which is the latest version?

**Comment by huyphams** [comment]
The 308 is the latest stable release, the 311 is the beta release (you've turned receive beta builds on the settings).

**Comment by chrschmitz** [comment]
This was the question: is your link newer than the latest beta?

**Comment by hugorodgerbrown** [comment]
@chrschmitz I can confirm that both 3.5.0 (Build 308) and 3.5.2 (Build 311) have sorting.

@huyphams thank you for the prompt patch on this - really appreciate it, and love the product.

**Comment by huyphams** [comment]
I can confirm that you can use both build without any problem. They contain the same patch
