### ISSUE TITLE
[Feature] Make tab switching wrap around to beginning/end

### ISSUE THREAD

**Issue by johanrosenson** [TablePlus/TablePlus#1887]
I know the issues with TablePlus getting proper tab support, but would it be possible to at least make the tab support that exists today wrap around when toggling between next/previous?

I mentioned this in my previous issue (that was more generic about tabs), but i'm splitting this out into its own issue, since this is a much smaller issue than other improvements.

What i mean is that if you are on the last tab and try to navigate to "Select Next Tab" that it should switch to the first tab, current behaviour does nothing.

Of course the same is expected when trying to "Select Previous Tab" when you are on the first tab.

**Comment by huyphams** [comment]
I've implemented this feature, thanks!
