### ISSUE TITLE
Minor - Consider renaming "fields name" to "headers"

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#189]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
--
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
83
3. The steps to reproduce this issue:
In the right click copy menu, it would make more sense to rename **fields name** to **headers** or **column names**
![image](https://user-images.githubusercontent.com/221584/35308121-e9110b60-005a-11e8-8b42-467788183457.png)

**Comment by huyphams** [comment]
I totally agree 😄 thank you @bhrd

**Comment by bhrd** [comment]
I have a follow-up to that
![image](https://user-images.githubusercontent.com/221584/35309840-343c23d8-0063-11e8-817b-fc37359c61d6.png)
I don't see a difference between "Copy Rows" and "Copy Rows As CSV". They seem to perform the same function.
I would suggest something like the following 

**Copy Cell
Copy Rows
Copy Rows with headers/column names
Copy Rows As > JSON 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... (other types** for future)
This way, you can also avoid the use of the word CSV, since CSV will only make sense if the user configured the delimiter to be comma.

**Comment by huyphams** [comment]
I don't see a difference between "Copy Rows" and "Copy Rows As CSV" => if I removed `Copy Rows` user may not know that they can copy and paste rows, I use this feature a lot to copy data from production to local. 
If I removed `CSV` user may not know that they can copy as CSV.

This is a trade-off but temporary I think it much easy to introduce the feature.

**Comment by bhrd** [comment]
@huyphams - My suggestion was not to remove `Copy Rows`, but only have `Copy Rows` instead of `Copy Rows as CSV`. 
The reasoning is, why would someone goto one more menu to `Copy Rows as CSV` instead of just clicking `Copy Rows` on the parent menu.
As for your second concern, If a user will only understand if you have the word `CSV` in the option, why do you need a menu item that just says `Copy Rows`?
Also, the use of the word CSV is misleading if the user changed delimiter in the app preferences.
