### ISSUE TITLE
[UI] Revert Reload button to left side

### ISSUE THREAD

**Issue by tarasyyyk** [TablePlus/TablePlus#1890]
1. Which TablePlus build number are you using: 3.5.2 (311)

The "Reload" button was moved In new version **3.5.2**. Can you revert it back to left side?
There are two subjective reasons:
- I used to see "Reload" button in left size, because there are list of tables and less pointer movement :)
<img width="1552" alt="TablePlus_Reload_button" src="https://user-images.githubusercontent.com/20100011/82220645-932a0400-9927-11ea-826d-493714d06288.png">

- This reload button placed similar as in major browsers (Google Chrome, Firefox, but not in Safari)

This "Lock model" can be moved to right side and Reload button to the left. For my opition this "Lock" button using less times than "Reload".

Does it make sence for you? I khow moving button was thoughtful decision.
Feel free to close this PR, if you not agree with me.

P.S. I just bought licence for 2 computers because TP is awesome! Best DB management app for macOS.

**Comment by huyphams** [comment]
You can do it by right click > custom toolbar, also this is the beta release, it's not official release.
<img width="1414" alt="Screen Shot 2020-05-18 at 8 52 05 PM" src="https://user-images.githubusercontent.com/3654622/82220883-70a8e280-9949-11ea-9a44-b153728b2e7f.png">
