### ISSUE TITLE
Search for item doesn't filter correctly table

### ISSUE THREAD

**Issue by pierrejolly** [TablePlus/TablePlus#1891]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
Mysql 8.x

**2. Which TablePlus build number are you using:**
v3.5.0 build 308

**3. The steps to reproduce this issue:**
Search for the name of a table in the "search for item ..." field, you'll see the table you're looking for but not only, there are some others tables with a totaly different name 🤷‍♂️ I don't understand why, maybe I miss something ?

![Screenshot 2020-05-18 at 15 50 43](https://user-images.githubusercontent.com/47548830/82221634-8bb32c80-9920-11ea-96fc-2b015e86e1fc.jpg)

**Comment by huyphams** [comment]
We're using Fuzzy search so it's the correct result. You can force TablePlus to use "contains" by put the term inside the double quote.

For example: "error"

**Comment by pierrejolly** [comment]
Oops, ok good to know, I'll use "error", thank you for your quick reply
