### ISSUE TITLE
On MacOS, not able to change location of saved queries.

### ISSUE THREAD

**Issue by deepcoder** [TablePlus/TablePlus#1892]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgresSQL, however I do not know how to get the version of this driver. As you do in 2. below for build number, you should explain how to get this information.
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.0 (308) Community Edition
3. The steps to reproduce this issue:
On Mac OS 10.15 and on 10.14, I am not able to move the location of the saved queries.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @deepcoder thank you for the feedback. The driver version is here:
<img width="223" alt="Screen Shot 2020-05-19 at 10 37 00 AM" src="https://user-images.githubusercontent.com/3654622/82281904-b94db380-99bc-11ea-80b0-72258edb0669.png">
`move the location of the saved queries ` do you want to sort the saved queries?

You can download our hot patch, which supports sorting queries by name, date added and date modified, link: https://www.dropbox.com/s/am0f0toy4wjf9pl/TablePlus.dmg?dl=0
<img width="554" alt="Screen Shot 2020-05-19 at 10 39 01 AM" src="https://user-images.githubusercontent.com/3654622/82282021-0b8ed480-99bd-11ea-9300-917099df8fc6.png">
