### ISSUE TITLE
Missing saved passwords and blank white screen upon opening DB

### ISSUE THREAD

**Issue by RoMoAmy** [TablePlus/TablePlus#1895]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
V. 3.5, Build 308
3. The steps to reproduce this issue
At first I was on version 3.4 and all my saved passwords were missing from the DB edit connection screen. I updated to 3.5, and restarted TablePlus. The passwords returned, but all DBs open to a blank white screen. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @RoMoAmy thank you for the feedback, I just replied to your email. Could you please send us a screenshot of the blank white screen please?
