### ISSUE TITLE
can not add comment for table

### ISSUE THREAD

**Issue by iiinsomnia** [TablePlus/TablePlus#1896]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): `MySQL`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): `Version 3.5.0 (308)`

3. The steps to reproduce this issue:

![image](https://user-images.githubusercontent.com/6582246/81519604-72384080-9374-11ea-8340-6329dd09eaca.png)

![image](https://user-images.githubusercontent.com/6582246/82551747-61b57080-9b93-11ea-802b-c889bb64584b.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
We've added a way to add comment, if you're interested in it, you can download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
<img width="1665" alt="abc" src="https://user-images.githubusercontent.com/3654622/111115656-84d46500-8597-11eb-9cd8-a1f5637bb2c3.png">
