### ISSUE TITLE
[Bug] MongoDB databases are inaccessible after update

### ISSUE THREAD

**Issue by vadimmisko** [TablePlus/TablePlus#1897]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mongo 4.2.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 308

3. The steps to reproduce this issue: Open any mongodb connection

OS: MacOS 10.15.4

After connecting to mongodb, "items" menu on the left is blank. Even after I select database from ⌘K, menu on the left stays blank and collection can't be selected.

**Comment by huyphams** [comment]
Could you please try this patch: https://www.dropbox.com/s/ikxmp2miipd5jql/TablePlus.dmg?dl=0 and let me know the result @vadimmisko thanks!

**Comment by vadimmisko** [comment]
@huyphams Patch resolved the issue, thanks
