### ISSUE TITLE
Database is locked error sqlite3 file opened from WSL

### ISSUE THREAD

**Issue by justinasfour04** [TablePlus/TablePlus#1899]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Sqlite3
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 124
3. The steps to reproduce this issue:

1. Create sqlite3 db file in WSL home directory
2. Open db file to view content
3. Run Select * from table
4. Database is locked 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/225
