### ISSUE TITLE
Show time taken to execute the query in SQL Query Tab. 

### ISSUE THREAD

**Issue by hariesnurikhwan** [TablePlus/TablePlus#19]
Showing time taken to execute the query is a great thing to add because I can check if my query is good enough.

**Comment by huyphams** [comment]
Sure!

**Comment by huyphams** [comment]
It's here 🚀
![timeexecute](https://user-images.githubusercontent.com/3654622/28502916-9ed3900a-7026-11e7-8a9c-08884c7e141b.png)

**Comment by hariesnurikhwan** [comment]
Nice work @huyphams!
