### ISSUE TITLE
Rearranging groups and connections visual bug

### ISSUE THREAD

**Issue by Chris1904** [TablePlus/TablePlus#190]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
83

3. The steps to reproduce this issue:
Rearrange the groups and connections

![test](https://media.giphy.com/media/l49JIiDyJY4hTih8c/giphy.gif)

Not important, but figured might as well post to keep track of it. Thanks :-)

**Comment by huyphams** [comment]
Ungrouped includes all connections which are in any group, `Ungrouped` is not actually a group so we can't re-order it. I had considered removing ungrouped and put all the connection in the same level with the group, but I think if I put it in Ungrouped user may know that `Ah I can create group`.

**Comment by Chinese1904** [comment]
I actually meant this: look at when I drop 'test' in between 'Local' and 'Ordern'. 

That blue line that indicates where it gets dropped, obviously, but you should not be able to sort groups within groups. So when moving a group, the blue line should be on top the closest group or underneath the last connection.

Do you get what I mean?

**Comment by huyphams** [comment]
yeah, I got it 😄
