### ISSUE TITLE
[UX] Suggestion : Add Excel grid behavior

### ISSUE THREAD

**Issue by RomainLanz** [TablePlus/TablePlus#1901]
Hey there! 👋 

In the Windows build, you can move by cells using the keyboard.

![Example of movement](https://user-images.githubusercontent.com/2793951/82833486-64c79e00-9ebe-11ea-9c33-17bb3d223449.gif)

This is not available in the macOS build but I believe it's a really useful features.
It could be even better if you can select multiple cells to copy/paste them from/to any table.

**Comment by AnthonyWebDev** [comment]
Yep I totally agree with the suggestion. As I am switching really often between Windows & MacOS it's the feature I miss the most.

**Comment by huyphams** [comment]
I'm working on it.

<img width="1735" alt="Screen Shot 2020-05-26 at 12 42 51 PM" src="https://user-images.githubusercontent.com/3654622/82864299-7193d280-9f4e-11ea-9d1f-cd489e19d179.png">

**Comment by huyphams** [comment]
Hey, you can try it out here: https://www.dropbox.com/s/1m4ro31q15kcgnj/TablePlus.dmg?dl=0
I also added an option to open Quicklook quickly with command + enter.

**Comment by RomainLanz** [comment]
Thanks!
