### ISSUE TITLE
Record console even if the history panel is closed

### ISSUE THREAD

**Issue by gjuchault** [TablePlus/TablePlus#1903]
Hello,

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.0 (308)

3. The steps to reproduce this issue:
	1. Close the history panel
	2. Do some requests
	3. Open the history panel, history is empty
	4. Do some requests
	5. History is filling

For smaller screens or when you want to dig into results you might want to close the history panel but open it from times to times.

Could you add an options to record history even if the history pane is closed?

:pray:

**Comment by huyphams** [comment]
Hi, did you mention the console log below the workspace? @gjuchault

**Comment by gjuchault** [comment]
![image](https://user-images.githubusercontent.com/678848/82919360-36a59500-9f76-11ea-95d0-a6bdc49c58fe.png)

Yes, I guess (the lower part with timestamp here).

Closing it means going into this state
![image](https://user-images.githubusercontent.com/678848/82919424-4c1abf00-9f76-11ea-94f2-1cf0dea155b5.png)

**Comment by huyphams** [comment]
The history will record all the executed queries regardless the state.
<img width="1532" alt="abc" src="https://user-images.githubusercontent.com/3654622/82919677-8a2cd880-9fa0-11ea-868c-98c56ff31f03.png">

**Comment by gjuchault** [comment]
Thank you! That solve most of my issues
Yet it would still be interesting to have the console filling even if "hidden"

**Comment by huyphams** [comment]
It's implemented in this patch: https://www.dropbox.com/s/k9qhgpjmzsyigwy/TablePlus.dmg?dl=0
It will be released soon. Thanks.
