### ISSUE TITLE
TablePlus wedges if told to run a query with a comment at the end

### ISSUE THREAD

**Issue by wadetregaskis-linkedin** [TablePlus/TablePlus#1904]
Against MySQL 8.0.18, if I try to run any SQL query with a comment at the end (e.g. `SELECT * FROM whatever; -- Great query, best query!`, TablePlus gets wedged in some broken state where it believes a query is perpetually running, but it isn't, so you can't kill anything and unstick it.  You have to quit the app and reopen it.

It appears, from the highlighting, that TablePlus is treating the comment as a standalone statement, and trying to execute _just_ that.  If I move the cursor explicitly to within the statement body and run that, it works fine.

**Comment by huyphams** [comment]
Hi @wadetregaskis-linkedin I'm not sure how to reproduce the issue, please try our latest release on macOS 314
Thanks!
