### ISSUE TITLE
Handle plain string results (such as from EXPLAIN FORMAT=JSON …)

### ISSUE THREAD

**Issue by wadetregaskis-linkedin** [TablePlus/TablePlus#1905]
Since the first line of the resulting JSON, from an EXPLAIN FORMAT=JSON …, is always just an opening curly brace, all you see in the results in a table with a single cell with "{…" in it.

It'd be nice if it just filled the whole area - that's normally the results table - with a simple text view, showing the entire result.

Otherwise, today, I have to either copy-paste the cell to another app in order to view it, or make the right sidebar absurdly wide in order to read it there.

**Comment by huyphams** [comment]
Hi @wadetregaskis-linkedin we added support it recently https://twitter.com/tableplus/status/1262340241542676482?s=21

You can download this build https://www.dropbox.com/s/ikxmp2miipd5jql/TablePlus.dmg?dl=0
Or waiting for the next update

**Comment by huyphams** [comment]
Hi @wadetregaskis-linkedin please try out the latest release 310, and press command + enter, there will be a show raw button.
<img width="1485" alt="Screen Shot 2020-05-27 at 12 10 05 PM" src="https://user-images.githubusercontent.com/3654622/82980190-052ed700-a013-11ea-891b-bcd9e108c8fe.png">

**Comment by wadetregaskis-linkedin** [comment]
I eventually found it, but it took a long time - I had no idea this "Quick Look Editor" even existed, and probably never would have if I couldn't see it in your screenshot above.  It's super handy!

However, can make this Github issue about making it the default view for a single-cell result?  Having to right-click then mouse then left-click etc is a lot of work - even aside from the discoverability challenge - compared to it just showing that 'Quick Look Editor' as the results view in place of the table view.
