### ISSUE TITLE
Import from CSV broken

### ISSUE THREAD

**Issue by kipopov** [TablePlus/TablePlus#1907]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 314

3. The steps to reproduce this issue:
Trying to open the import from CSV does not bring up the import dialog. Nothing happens. Going back to build 304 recovers the import functionality

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @kipopov it could be a macOS issue (I've seen it since I upgraded to 10.15), please try again with the build 314. I will keep an eye on it.

**Comment by kipopov** [comment]
I re-installed Build 314 and it is not working again. I am on the latest MacOS, and have been since last fall. Build 304 did not have an issue, and actually the following one did not either. It is just the latest 314 that has the problem. I am not able to import data, which is one of the main reasons I purchased a license. Any help would be greatly appreciated. Thank you.

**Comment by huyphams** [comment]
It's weird, I didn't change anything except one small detail, TablePlus from build 314 accepts folder with format foldername.csv <- this is not a file but a folder. 
I've tried to import many times and it works.
If you have any chance, please try to restart macOS and see how it goes?
Thanks!

**Comment by kipopov** [comment]
I have tried to import both ways:
1. File > Import > From CSV... and From Dump...   nothing happens, nothing opens.
2. Right click on a table in DB > Import > From CSV... nothing.

It is not that I pick a file or a folder. The dialog box to even select what you are importing from does not come up at all. If I replace the application with an copy of the previous build, it works fine.

**Comment by huyphams** [comment]
I can confirm the behavior `. The dialog box to even select what you are importing from does not come up at all` was the macOS bug, and somehow it locks the build 314. 
Hi @kipopov if you have a chance, please restart the MacBook and try again, thank you!

**Comment by kipopov** [comment]
Rebooting MacBook worked... weird.

**Comment by gingerlime** [comment]
I'm having a problem importing a redis CSV that I exported from another redis DB. It seems like it's working, but no data is being imported.

![import redis csv](https://user-images.githubusercontent.com/524274/84120340-f9d9a380-aa35-11ea-8b75-35b393f9710d.gif)

**Comment by huyphams** [comment]
Hi @gingerlime currently it does not support. We're working on it.

**Comment by gingerlime** [comment]
Thanks @huyphams. Would be useful to put a note on the app or something... otherwise it feels like it should work and there's no indication that it's not supported.
