### ISSUE TITLE
Export to CSV sorting columns by alphabet

### ISSUE THREAD

**Issue by jaimetobar** [TablePlus/TablePlus#1908]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.19

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 308

3. The steps to reproduce this issue:
When exporting a table to CSV, Table Plus sort the columns in alphabetical asc order with no regard to the order I have defined on the table/view.

Noted: If the bug is related to data, please attach an example SQL data.
![Screen Shot 2020-05-27 at 10 47 14 AM](https://user-images.githubusercontent.com/7042895/83043220-348c1680-a008-11ea-8fad-237775d5487d.png)

**Comment by huyphams** [comment]
Hi @jaimetobar CSV is append-only so I don't think it's sorted by alphabet, could you please open the file with a plain text editor and check the CSV content file?

**Comment by jaimetobar** [comment]
Hi! Thanks for the quick reply - I did, in the beginning I blamed google sheets but the CSV is also sorted:

**a. Primary Focus,b. Secondary Focus,c. Other Focus,Email,Full name,Interest level (average),Interest level (self),Interest level (supervisor),Parent team 1,Parent team 2,Parent team 3,Parent team 4,Party ID,Person ID,Role name,Security Group,Skill category,Skill ID,Skill level (average),Skill level (self),Skill level (supervisor),Skill name,Skill set,Team name**
Automation,Cloud Management,,amaliver@redhat.com,Abnerson Malivert,1,1,,NA,NA - CONSULTING,,,3589496,929,Consultant,General staff,NA RHC Commonly Requested Skills,366,1,1,1,Front-End Web Development,team,NAPS - Consultants
Automation,Cloud Management,,amaliver@redhat.com,Abnerson Malivert,4,4,,NA,NA - CONSULTING,,,3589496,929,Consultant,General staff,Red Hat Management,379,4,4,4,RH Ansible Automation,team,NAPS - Consultants

**Comment by huyphams** [comment]
Oh interesting, how did you export the CSV, the screenshot above was a table structure.

**Comment by jaimetobar** [comment]
Hi @huyphams, oddly enough now is working as expected - this has happened twice and now is back to normal. Sorry for the inconvenience!

**Comment by jaimetobar** [comment]
Hi, sorry to bother but this is happening again. All the steps are shown here: https://youtu.be/knexLY2XCeI

From the log, you can see TablePlus is sorting the columns. Yesterday it worked normally, today it started to sort again.

-- 2020-06-03 13:08:40.8520
USE `r_a_t_prod`;

-- 2020-06-03 13:08:42.8700
SELECT VIEW_DEFINITION as create_statement FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA='r_a_t_prod'AND TABLE_NAME='proposed_not_completed_plus_status_4_reg_leads';

-- 2020-06-03 13:09:10.6540
SELECT * FROM `r_a_t_prod`.`proposed_not_completed_plus_status_4_reg_leads` LIMIT 999999 OFFSET 0;

-- 2020-06-03 13:09:10.7650
SELECT table_rows as count FROM information_schema.TABLES WHERE TABLE_SCHEMA='r_a_t_prod'AND TABLE_NAME='proposed_not_completed_plus_status_4_reg_leads';

-- 2020-06-03 13:09:10.7920
SELECT ordinal_position as ordinal_position,column_name as column_name,data_type AS data_type,is_nullable as is_nullable,column_type as column_type FROM information_schema.columns WHERE table_schema='r_a_t_prod'AND table_name='proposed_not_completed_plus_status_4_reg_leads';

-- 2020-06-03 13:09:10.7930
SELECT COUNT(*) as count FROM `r_a_t_prod`.`proposed_not_completed_plus_status_4_reg_leads`;

-- 2020-06-03 13:10:07.7340
SELECT `Course full name from catalog`,`Course level`,`Course URL`,`Email`,`Full name`,`Interest level (average)`,`Interest level (self)`,`Interest level (supervisor)`,`LMS Completion Status`,`LMS Date Enrolled`,`Parent team 1`,`Parent team 2`,`Parent team 3`,`Parent team 4`,`Role name`,`Skill category`,`Skill level (average)`,`Skill level (self)`,`Skill level (supervisor)`,`Skill name`,`Team name` FROM `r_a_t_prod`.`proposed_not_completed_plus_status_4_reg_leads`;

**Comment by huyphams** [comment]
Hi @jaimetobar thank you for the video, could you please try this patch and see how it goes?
https://www.dropbox.com/s/c24abtimy62544f/tableplus.dmg?dl=0
Thank you!

**Comment by jaimetobar** [comment]
Hi @huyphams, thanks for the prompt response. It keeps sorting the columns.
![Screen Shot 2020-06-03 at 2 17 57 PM](https://user-images.githubusercontent.com/7042895/83679536-2c524f00-a5a5-11ea-91e5-6e819e0c3e7d.png)
![Screen Shot 2020-06-03 at 2 15 36 PM](https://user-images.githubusercontent.com/7042895/83679546-31170300-a5a5-11ea-8499-124799495d5c.png)

**Comment by huyphams** [comment]
Hi @jaimetobar I'm sorry I uploaded the wrong build :( please try this patch: https://www.dropbox.com/s/c24abtimy62544f/TablePlus.dmg?dl=0
Thank you!

**Comment by jaimetobar** [comment]
Hi, sorry I miss your message - could you please upload the file again? I tried but got 404 error. Thanks!

**Comment by huyphams** [comment]
Hi @jaimetobar please update the app to the build 320, it should fix the issue! thank you!
