### ISSUE TITLE
SQL syntax error after using Beautify feature.

### ISSUE THREAD

**Issue by thinsoldier** [TablePlus/TablePlus#191]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
83

3. The steps to reproduce this issue:
Paste in sql, run it, it works. 
Click beautify, run it, it fails.

The follow original query works as a single line:
    
    SELECT *, HOUR(`when`) as hour FROM cinemix WHERE `when` > '2017-12-25' AND `when` < DATE_ADD('2017-12-25', INTERVAL 1 DAY) ORDER BY `when` ASC

After clicking Beautify it fails:
``` 
SELECT
    *,
    HOUR (`when`) AS hour
FROM
    cinemix
WHERE
    `when` > '2017-12-25'
    AND `when` < DATE_ADD ('2017-12-25', INTERVAL 1 DAY)
ORDER BY
    `when` ASC
```

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
ORDER BY
    `when` ASC' at line 8
```

The problem seems to be caused by the spaces added after HOUR and DATE_ADD.

**Comment by huyphams** [comment]
Thanks for the feedback. I'm fixing it 👍

**Comment by huyphams** [comment]
Hi @thinsoldier can you give a try on this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
and let me know it works for you, thank you.
