### ISSUE TITLE
"Variables" Dialog no longer has a default "return key" action

### ISSUE THREAD

**Issue by nazgul** [TablePlus/TablePlus#1910]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

    MySQL 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

    315

3. The steps to reproduce this issue:

    * Create a Query with a query param for replacement
    * Press Command-Return
    * The Variables dialog pops up with the first value selected.
    * Press return (or enter a value and press return) to select the first field
    * Press return again

    Nothing happens.

    In prior releases, pressing return selected Apply and submitted the query. Which was awesome, because I could fire off a query with the default values by pressing "Command-Return Return Return". Now I have to use the mouse.

**Comment by huyphams** [comment]
Hi @nazgul please download and try this patch: https://www.dropbox.com/s/nlj228p2qaul3v7/tableplus.dmg?dl=0
It should allow you to use command + return to apply the variable.

**Comment by nazgul** [comment]
Perfect. That's even better than it was before! Thank you!
