### ISSUE TITLE
Connection is trying to connect to the local ip not the specified location

### ISSUE THREAD

**Issue by PeterTomlins** [TablePlus/TablePlus#1911]
Build 314
Create a new connection to a postgresql database
fill in the details (I originally had a url there but changed it to the raw ip) 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/304645/83102546-14d41b80-a0f8-11ea-81a1-4ae9f5613434.png">

**Comment by huyphams** [comment]
Hi @PeterTomlins it was your hotpot endpoint, the message was reported by PostgreSQL. Normally PostgreSQL does not allow you to connect directly, please use Over SSH feature!

**Comment by PeterTomlins** [comment]
Worked it out, on the local machine; I'd set the IPv4 host order in the wrong order.
