### ISSUE TITLE
Scrolling horizontally snaps back to last selected cell - breaking scroll

### ISSUE THREAD

**Issue by benmcgarvey** [TablePlus/TablePlus#1912]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.48

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.5.2 (310)

3. The steps to reproduce this issue:
  - Open a table which has more columns than horizontal screen space
  - Click on a cell
  - Cell is outlined red & row is highlighted
  - Scroll horizontally until outlined cell is off screen
  - Stop scrolling
  - Viewport snaps back so that selected cell is visible again, losing scroll location

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @benmcgarvey I'm sorry about the issue, we fixed it and released the build 314, please update the app, thank you!
