### ISSUE TITLE
[Feature Request] Highlight SQL syntax in console log

### ISSUE THREAD

**Issue by maxgashkov** [TablePlus/TablePlus#1917]
This is a feature request:

Please add syntax highlighting for SQL in console log. You obviously have the means to do so as highlighting is available in SQL editor.

Without it it's really difficult to navigate the wall of text there.

**Comment by huyphams** [comment]
Hi @maxgashkov we re-enable the console log syntax highlighting in this patch:  https://www.dropbox.com/s/9ldedn9gnvecljd/tableplus.dmg?dl=0 or you can wait for the next update.
Thanks.
