### ISSUE TITLE
Saved workspace queries based on connection

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#192]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 9.6

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
83

**3. The steps to reproduce this issue:**
When I open a connection and open the query window I'm presented with all of my previous queries. I find this feature to be very valuable to pickup where I left off. 

However, it's bringing up the same queries on any connection I open up. Since each database has their own set of tables and wide differences between them those same queries will not work. If this saved set of queries was per-connection then they would always stay relevant to that specific database (as an aside this is how Postico does it and I find it hugely valuable.)

**Comment by huyphams** [comment]
Sure, I'm working on it (including `favorites` tab), because this is a big improvement, so it will take me a couple of weeks to implement.
