### ISSUE TITLE
Result table's header is truncated

### ISSUE THREAD

**Issue by resting** [TablePlus/TablePlus#1920]
Result table's header is truncated. Not able to read the column's names.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL Server
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
On mac. v3.5.3 (314)
3. The steps to reproduce this issue:
Run a query and see the result.

![image](https://user-images.githubusercontent.com/350530/83220163-e52f1d00-a1a4-11ea-9f07-046a05ea2f27.png)

**Comment by huyphams** [comment]
I was able to reproduce the issue. If the bottom pane is closed before executing the query, the header will be truncated.

**Comment by huyphams** [comment]
It's fixed: https://www.dropbox.com/s/nlj228p2qaul3v7/TablePlus.dmg?dl=0
Thank you, please let me know if you're still seeing the issue.
