### ISSUE TITLE
TablePlus colors a string as if it were a number

### ISSUE THREAD

**Issue by adamwinn** [TablePlus/TablePlus#1921]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
315

3. The steps to reproduce this issue:
I pasted in a query and TablePlus colored the first string the correct red color but the second string is not highlighted the same red color.  The second string is highlight the color used for numbers.

![Screen Shot 2020-05-29 at 1 29 49 AM](https://user-images.githubusercontent.com/3028964/83233646-42e34b00-a14c-11ea-837c-e710f089389b.jpg)

**Comment by huyphams** [comment]
Hi @adamwinn thank you for the feedback, I've fixed this issue: https://www.dropbox.com/s/nlj228p2qaul3v7/TablePlus.dmg?dl=0
Thanks!
