### ISSUE TITLE
Query log semicolon inconsistency with PostgreSQL

### ISSUE THREAD

**Issue by erdemkeren** [TablePlus/TablePlus#1922]
driver: PostgreSQL 11.7
build:  314

The following is the output of the query generated by TablePlus: Please see the semicolon:

ALTER TABLE "public"."purchases" ADD COLUMN "is_ok" bool DEFAULT 'false';
ALTER TABLE "public"."purchases" ADD COLUMN "is_not_ok" bool DEFAULT 'false';
ALTER TABLE "public"."purchases" ADD COLUMN "created_by" jsonb
ALTER TABLE "public"."purchases" ADD COLUMN "created_at" timestamptz

I guess it is about the DEFAULT 'false'; part

**Comment by huyphams** [comment]
Hi @erdemkeren thank you for the feedback, I've fixed this issue: https://www.dropbox.com/s/nlj228p2qaul3v7/TablePlus.dmg?dl=0
Thanks!
