### ISSUE TITLE
Can not scroll to add new column on table Structure tab

### ISSUE THREAD

**Issue by erdemkeren** [TablePlus/TablePlus#1923]
driver: PostgreSQL 11.7
build: 314

I want to add new columns to a table
When I open the table and Switch to "Structure" view
When there are no visible empty rows visible
I can not scroll to see some more empty space to add a new row

Instead,
 I had to shrink down the index part a little bit and see the empty row.

<img width="1490" alt="Screenshot 2020-05-29 at 11 36 49" src="https://user-images.githubusercontent.com/1636960/83245622-494fe200-a1a1-11ea-861e-b4daed601058.png">

**Comment by huyphams** [comment]
There are many ways to add a new row @erdemkeren 
1. Double on empty space (like you did).
2. Right click > new column.
3. Command + I
4. Command + C and then Command + V selected row.
5. Command + D after selecting a row.
6. Click the + Column at the bottom.

**Comment by erdemkeren** [comment]
Hello @huyphams . Thanks for the reply.

Sure there are. I don't think is this is a blocker either. I didn't open this ticket for that reason.

But from my perspective, it was not a good idea to right-click an existing row to create a new one.

- I tried to scroll down - no luck
- Double click to the last existing row, press "tab" - no luck
- Look for a new column button (something like [+]) - no luck
- Shrinked the next UI component to see one more empty row - worked
So I stopped looking for alternatives.

It could go better if you just
- let me scroll a little bit and double click on an empty row
- hit tab to go to next column definition row / new column definition row like excel etc.

So, what I mean is I ask for improvement.

**Comment by erdemkeren** [comment]
I mean maybe you can consider adding [+] button as Sequel pro had. Just next to the column definition data table. When you go to the end of the empty space, you already see the + button.

So you don't search for it.

<img width="141" alt="Screenshot 2020-05-29 at 12 31 00" src="https://user-images.githubusercontent.com/1636960/83250422-61772f80-a1a8-11ea-9ffe-4a5b539a5e78.png">
