### ISSUE TITLE
[Feature Request] Make it possible to use bind on queries

### ISSUE THREAD

**Issue by FCO** [TablePlus/TablePlus#1924]
It would be great if it could automatically open a dialog box asking for values when there is a binding markup on the query (?, :1, or anything like that), that would be extremely useful for reusing queries.

**Comment by huyphams** [comment]
This feature was turned off by default, you can turn it on here:
<img width="595" alt="Screen Shot 2020-05-29 at 9 44 28 PM" src="https://user-images.githubusercontent.com/3654622/83272630-95c50d00-a1f5-11ea-8f4b-3b1f5e878c2a.png">

Docs: https://docs.tableplus.com/query-editor/query-parameters

**Comment by huyphams** [comment]
Params + keyword binding would be a combo: https://tableplus.com/blog/2018/08/keyword-binding-favorite.html
Please let me know if you have any question @FCO 
Thanks

**Comment by FCO** [comment]
Great! thank you very much! Sorry for not knowing about that. Worked like a charm.

**Comment by FCO** [comment]
it seems to me that the parameter followed with a comma without space is not working:

```sql
select :param , :param;
```
works, but
```sql
select :param, :param;
```
doesn't work

**Comment by huyphams** [comment]
I just fixed this issue @FCO it will be released in the next update.
