### ISSUE TITLE
Syncing connections between computers

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#193]
When purchasing TablePlus this week I mistakenly assumed that connections (not including passwords or keys) would be synced between devices. I see there is a Backup and Restore function but are there any plans to add a sync. I have quite a few connections and keeping them in-sync between my desktop and laptop would same me time in trying to keep them up to date myself.

**Comment by huyphams** [comment]
Thank @nathanpalmer for the suggestion. I know sync connection is would be a nice feature but currently, I need to do export/import connection first.

If I build syncing function, I need to research encode/decode first, because connection information is very very important, I can't make any mistake when handling it. And of course, I will not include any password and key when syncing connection.

**Comment by nathanpalmer** [comment]
Ok, great. Glad it's on your mind though.

**Comment by JAStanton** [comment]
In general I see this as something that would be more of an enterprise feature. I'd love on day 1 for a new co-worker to sync connections w/ DropBox and have all everything setup including all preferences for things like "Alert Mode" / "Safe Mode" for production connections. That'd be pretty slick!

**Comment by huyphams** [comment]
I have seen this feature in 1Password. they named it to a vault. Basically, they encrypted it and put it in cloud service (like Dropbox, Google Drive).

**Comment by eberkund** [comment]
I sync my Filezilla credentials with Dropbox, I don't know if this would a suitable solution for TablePlus?

**Comment by huyphams** [comment]
I'm planning to use this solution, includes History and Favorite.

**Comment by rizkysyazuli** [comment]
@huyphams understood. thx.

Anyway, the [pull request is here](https://github.com/lra/mackup/pull/1164) if someone else's also using mackup.

**Comment by zhengyue** [comment]
I just moved the `Data` folder in `~/Library/Application\ Support/com.tinyapp.TablePlus/` to iCloud Drive, and created a link in the original place using `ln -s`. Now the connections are synced between all my Mac computers.

**Comment by huyphams** [comment]
if you want to sync Favorite and History you can add the folder `Cache` to iCloud @zhengyue

**Comment by matt-stuart** [comment]
Simply having a UI element to specify where to store the above data would be handy to move it to iCloud / Dropbox / what have you. Otherwise this works for me for now.

**Comment by kirillplatonov** [comment]
Agree. Being able to specify folder for settings would be great. For example, that's how Dash doing it:
<img width="531" alt="screenshot 2019-02-12 17 19 10" src="https://user-images.githubusercontent.com/839922/52641659-6a2bef80-2eea-11e9-94bd-95c6d3a41cbf.png">

@huyphams hopefully you will have resources to implement it anytime soon. I really like TablePlus and having sync would make usage on different machines much smoother. Thanks for your amazing work!

**Comment by huyphams** [comment]
I've it on backlog already, you guys will see it soon! I pushed some code related to it on the build 190 (if you've read the changelogs).

**Comment by ssx** [comment]
what's the status of this? if I symlink via Dropbox is the sync reliable? will it sync everything?

**Comment by bskiefer** [comment]
Checking in on this

**Comment by jannejava** [comment]
+1

**Comment by rjventrone** [comment]
+1

**Comment by rijkvanzanten** [comment]
@huyphams any updates? 🙂 You stated

> you guys will see it soon!

so I'm curious to see where this was left of as that comment is about to reach it's 1 year anniversary 😄

**Comment by shaynem** [comment]
was just looking for this, it's painful to enter in all the information again into the iPad / iPhone for 20+ connections

**Comment by HansOspina** [comment]
This is a must if you pay for the iPad version and the Computer version you really expect this to happen. Please get it out soon!!

**Comment by jpike88** [comment]
Any progress?

Would be nice if it just synced with my iCloud account

**Comment by MattRiddell** [comment]
Yeah I'm looking for this too - I have an office and laptop and hate to get home and realize I forgot to copy my settings - just being able to specify ~/Documents/ as the settings location would be sufficient

**Comment by huyphams** [comment]
Hi @MattRiddell it's supported, you can change the path in the settings.

<img width="710" alt="Screen Shot 2020-06-21 at 11 21 24 AM" src="https://user-images.githubusercontent.com/3654622/85216668-90508200-b3b1-11ea-8a66-e843eb4a7c9e.png">

**Comment by onlime** [comment]
HI @huyphams

> Hi @MattRiddell it's supported, you can change the path in the settings.

Thanks for the hint. This is very nice and works perfectly. But I still can't find this locations settings in TablePlus mobile app (iOS). So syncing to mobile via iCloud is not yet possible?

**Comment by MattRiddell** [comment]
Awesome, thanks!

**Comment by jordan-brough** [comment]
FYI there's currently a small bug with custom locations where you can't create saved queries, but there is a workaround.
See https://github.com/TablePlus/TablePlus/issues/2002.

**Comment by zieglar** [comment]
Create three folder in Dropbox and copy ~/Library/Application Support/com.tinyapp.TablePlus/{Cache,Data,Temp} three folder content, set tableplus locations to new folder, All settings are lost :(
change locations failed

**Comment by huyphams** [comment]
TablePlus will not move the old data to new folder @zieglar you have to do this by your self by export and import connections.

**Comment by acalvino4** [comment]
I can see that 'locations' tab in my table plus preferences, but it doesn't seem to have a page in the docs: https://docs.tableplus.com/preferences/general

**Comment by diegostamigni** [comment]
Why is this closed as completed?

**Comment by leearmstrong** [comment]
Any news on being able to "sync" to iOS?  Even an import!?

**Comment by rogerluan** [comment]
+1 for built-in support for syncing connections and other configs between devices. Syncing via iCloud shared folder might work but it doesn't solve conflicts very well and may result in conflicts and/or merge conflicts which result in corrupt data. Having a built-in support for syncing connections means embedding a merge and conflict resolution strategy in the app so it doesn't end up accidentally corrupting the data (or overwriting in a unexpected way) in case of simultaneous access.

**Comment by robertveloso** [comment]
+1 Hope this function get added
