### ISSUE TITLE
[Feature Request] allow different delimiter when exporting as CSV

### ISSUE THREAD

**Issue by stb** [TablePlus/TablePlus#1930]
Hi we are using the pipe symbol (|) as delimiter for most of our exports. Would it be possible to add the custom delimiter option to the export as well? On import there is already an option to set a custom delimiter.
<img width="222" alt="import-delimiter-options" src="https://user-images.githubusercontent.com/248309/83525887-e71b1800-a4e5-11ea-882d-f21bd3db1956.png">
<img width="260" alt="export-delimiter-options" src="https://user-images.githubusercontent.com/248309/83525882-e5e9eb00-a4e5-11ea-87ff-5d9bd8366178.png">

**Comment by huyphams** [comment]
It will be supported in the next update! thanks!
