### ISSUE TITLE
Compound Foreign Keys Not Displaying

### ISSUE THREAD

**Issue by unlostify** [TablePlus/TablePlus#1931]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 317

3. The steps to reproduce this issue:

- Create a new table, "tableName" in schema "schemaName"
- Add two columns, "firstColumn_FK" and "secondColumn_FK"
- Add a foreign key (here's the SQL generated by TablePlus):

ALTER TABLE "schemaName"."tableName" ADD FOREIGN KEY ("tableName_firstColumn_fkey","tableName_secondColumn_fkey") REFERENCES "schemaName"."anotherTable" ("firstColumn","secondColumn") ON UPDATE CASCADE ON DELETE CASCADE;

- The foreign key shows up as being empty in the TablePlus GUI (it does however correctly show up in Navicat)

**Comment by huyphams** [comment]
Hi @unlostify I just fixed this bug: https://www.dropbox.com/s/i6vgt7ho36emsm6/tableplus.dmg?dl=0
Thank you for letting me know.

**Comment by unlostify** [comment]
Thanks so much Henry!! We're loving TablePlus and it seems like you're just dumping on the extra awesome features these days ;) Keep up the great work!
