### ISSUE TITLE
Connection closes after 300 seconds for long running queries

### ISSUE THREAD

**Issue by datenbrille** [TablePlus/TablePlus#1932]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7 with AWS RDS via SSH Jump host

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 314

3. The steps to reproduce this issue:

Connection to MySQL DB run a query which takes longer then 300 seconds to produce any output.
TablePlus will answer with: `Query 1 ERROR: Lost connection to MySQL server during query`

MySQL `max_execution_time` is set to 0 which should mean unlimited time.

I tested the same query with DBeaver over the same Jump Host and the query worked.

**Comment by huyphams** [comment]
Hi @datenbrille if you have a chance, please try this patch: https://www.dropbox.com/s/rbhue8kr9k8sl8s/tableplus.dmg?dl=0
I've added SET max_execution_time=28800 for MySQL connection.

**Comment by datenbrille** [comment]
`Query 1 ERROR: Query execution was interrupted, maximum statement execution time exceeded` after 28.983 s

**Comment by huyphams** [comment]
Thanks, are you sure that you use the same user with DBeaver @datenbrille ? TablePlus will not kill any queries automatically.

**Comment by datenbrille** [comment]
Yes I used the same user, the same jump host.

**Comment by datenbrille** [comment]
BTW this worked in older releases of TP but I will check this with different settings too. Maybe a change in the driver added some default options? I mean 300s sounds just not random.

**Comment by datenbrille** [comment]
I can reproduce this on 4 different DB with two different jump hosts:

Easy to test on MySQL: `SELECT SLEEP(350);`

Interesting on my local DB TP asked me if I want to continue with the query.

**Comment by huyphams** [comment]
Let me check the SSH lib, maybe the issue is related to the SSH timeout.

**Comment by datenbrille** [comment]
Okay I tested it with additional tools (same DB and same SSH Configuration):

DataGrip: ✅ 
MySQL Client: ✅ 
SequelPro: ✅ 

MySQL locally via TCP over TablePlus: ✅ 

Here the output of the MySQL client:

`Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 81639
Server version: 5.7.26-log Source distribution

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT SLEEP(350);
+------------+
| SLEEP(350) |
+------------+
|          0 |
+------------+
1 row in set (5 min 50.09 sec)

mysql>`

**Comment by huyphams** [comment]
I found the root problem. Please wait for the patch.

**Comment by huyphams** [comment]
If you have a chance, please try this patch: https://www.dropbox.com/s/k10hmoy6e734bdk/tableplus.dmg?dl=0
Thanks @datenbrille

**Comment by datenbrille** [comment]
I tried the patch but it did not work: `Query 1 ERRORLost connection to MySQL server during query`

Build 317

**Comment by huyphams** [comment]
Hi @datenbrille please try to increase some variables? I'm not sure what was the root cause on your setup but it works on my setup after increasing the value of `max_execution_time` to 28800000

Please try to run this query before the SELECT SLEEP(350);
SET net_read_timeout=28800000;

**Comment by datenbrille** [comment]
I tried this too. Same result:

```
SET net_read_timeout=28800000;
SELECT SLEEP(350);
```

`Query 1 ERRORLost connection to MySQL server during query`

**Comment by huyphams** [comment]
Thanks @datenbrille Could you please run this query

show variables;

and search the result and see if there is any variable with 300 in value?

<img width="1639" alt="Screen Shot 2020-06-04 at 3 49 17 PM" src="https://user-images.githubusercontent.com/3654622/83735737-f54e6d00-a67a-11ea-9cab-8ef61e4453be.png">

**Comment by datenbrille** [comment]
```sql
show variables where VALUE like '300';
delayed_insert_timeout,300
innodb_purge_batch_size,300
key_cache_age_threshold,300
slave_checkpoint_period,300
```

**Comment by datenbrille** [comment]
@huyphams In order to work further with TP I create a custom ssh config with tunnels and will use this for now. I think the problem is very much related to my setup and not a general TP problem. I would be convenient to modify some connection parameters like:

* read timeout
* connection timeout
* keep alive signal

What do you think? TablePlus is such a great product and I love it so much. It is the best SQL Client so fare and I tried a lot of them over the years on Mac OS X.

**Comment by huyphams** [comment]
Hi @datenbrille I'm still investigating the issue. Yesterday, I created a custom MySQL and jump host with default config, it worked perfectly. 
So I think the issue is related to the server-side config (that can be adjusted by the client after the connection is established). I'm reading the workbench code and see what they do after connecting.

**Comment by datenbrille** [comment]
What bothers me here is that I connect to the same machine, same jump host. One with TP ssh settings and one with system ssh config:

System ssh config:

```
Host db.control.mysugr
    HostName 3.250.133.128
    User karl_spies
    IdentityFile /Users/karl/.ssh/mysugr
    ServerAliveInterval 5
    LocalForward 3307 ...3306

Host staging.control.mysugr
    HostName ...
    IdentityFile ~/.ssh/mysugr
    User karl_spies
    ServerAliveInterval 5
    ForwardAgent yes
```
![Screenshot 2020-06-05 at 10 40 44](https://user-images.githubusercontent.com/795463/83856562-08fce080-a71a-11ea-9378-0b97e37d577a.png)
☝️  this is db.control.mysugr
![Screenshot 2020-06-05 at 10 46 20](https://user-images.githubusercontent.com/795463/83856555-069a8680-a71a-11ea-8244-30464732ee2b.png)
☝️  this is staging.control.mysugr

I noticed after the error TP does a reconnect and that staging.control.mysugr shows in the status something like a counter for the keep alive signal which db.control.mysugr does not show.

Screenshots from the TP config:

![Screenshot 2020-06-05 at 10 52 00](https://user-images.githubusercontent.com/795463/83856980-a2c48d80-a71a-11ea-8683-8448c11cb9e9.png)
![Screenshot 2020-06-05 at 10 51 47](https://user-images.githubusercontent.com/795463/83856993-a526e780-a71a-11ea-9d16-1e66d4435b78.png)
![Screenshot 2020-06-05 at 10 50 42](https://user-images.githubusercontent.com/795463/83856995-a5bf7e00-a71a-11ea-8851-fb31b12d0760.png)

**Comment by huyphams** [comment]
After reading the MySQL Workbench code, I found that they are using the MYSQL_OPT_READ_TIMEOUT
I just update it to 0 (unlimited), if you have a chance, please try this patch: https://www.dropbox.com/s/446u1eo2uq8yvew/tableplus.dmg?dl=0
Thank you @datenbrille

**Comment by datenbrille** [comment]
I am so sorry to make all this troubles:

![Screenshot 2020-06-05 at 11 25 00](https://user-images.githubusercontent.com/795463/83860239-52036380-a71f-11ea-9540-fce2a8061353.png)

**Comment by huyphams** [comment]
I'm sorry because of so many test builds. I end up create a test instance RDS on Amazon but I could not reproduce the issue, weird.
<img width="1498" alt="Screen Shot 2020-06-05 at 8 51 39 PM" src="https://user-images.githubusercontent.com/3654622/83884655-640cf280-a76f-11ea-91f9-7692d7733ed0.png">

However, I made an update on ssh lib (I added SO_KEEPALIVE), hopefully it will work:
https://www.dropbox.com/s/0x2b7gbuv9kvx38/tableplus.dmg?dl=0

**Comment by datenbrille** [comment]
@huyphams The link is outdated I guess?

**Comment by huyphams** [comment]
I updated the link here: https://www.dropbox.com/s/9ldedn9gnvecljd/tableplus.dmg?dl=0 not sure why Dropbox keep changing the link :/

**Comment by datenbrille** [comment]
Tested the build and still the same issues. I think it something in our setup. I have found the workaround with the custom ssh connection and will use this now. I don't want to waste your time on something which is might a user issue. Many thanks for your time and all the effort. I will test this in later release and investigate further. I will try to setup a wireshark for this.

**Comment by huyphams** [comment]
I've tried to implement `ClientAliveInterval` if you have a chance, you can download this patch: https://www.dropbox.com/s/g801eovguzkqvlr/TablePlus.dmg?dl=0
Thank you @datenbrille

**Comment by datenbrille** [comment]
I can confirm. The build works and does not run into a timeout. Many thanks. Very much appreciated.
