### ISSUE TITLE
Update Error on MacOS

### ISSUE THREAD

**Issue by gijs** [TablePlus/TablePlus#1933]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

**N/a**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

**315**

![Screenshot 2020-06-03 at 14 37 46](https://user-images.githubusercontent.com/7193/83637391-d9c66200-a5a7-11ea-8353-9e0d5c6f67d5.png)

3. The steps to reproduce this issue:

(this is on MacOS Mojave)

* Click **Check for updates...**

* Wait until it says: **Build 317 - Release Candidate is available**

* Click **Install Update**

* Wait

* Click **Install and Relaunch**

* Result:
**Update Error! An error occurred while extracting the archive. Please try again later.**
![Screenshot 2020-06-03 at 14 37 35](https://user-images.githubusercontent.com/7193/83637444-f1054f80-a5a7-11ea-91d7-f8341883804e.png)

**Comment by huyphams** [comment]
Hi sorry, I just fixed the issue. Thanks!

**Comment by gijs** [comment]
No worries, thanks for fixing it so quickly.
Awesome product by the way!
