### ISSUE TITLE
[Bug-Report] Switch db doesn't work on FullScreen mode - MacOS

### ISSUE THREAD

**Issue by link08** [TablePlus/TablePlus#1935]
1. **It's failing with any driver**

2. **TablePlus Version 3.0.0 (286) - MacOS Catalina 10.15.5**

3. **The steps to reproduce this issue:**
- Open TablePlus in FullScreen Mode
- Press shortcut: cmd + shift + \
- Try to select another db

# FullScreen Mode - FAIL
![Screenshot 2020-06-04 at 10 23 14 AM](https://user-images.githubusercontent.com/4208371/83707930-c1a91e00-a64d-11ea-83a6-720f4c3a3a4f.png)

![Screenshot 2020-06-04 at 10 23 24 AM](https://user-images.githubusercontent.com/4208371/83708022-f026f900-a64d-11ea-8338-a6e3ac47484a.png)

![Screenshot 2020-06-04 at 10 23 34 AM](https://user-images.githubusercontent.com/4208371/83707957-cec60d00-a64d-11ea-95c5-f8007dc8db2f.png)

# Normal Mode - WORKS
![Screenshot 2020-06-04 at 10 24 22 AM](https://user-images.githubusercontent.com/4208371/83708098-02a13280-a64e-11ea-9148-ed0850e62507.png)

**Comment by huyphams** [comment]
Thanks @link08 it was a known issue: https://github.com/TablePlus/TablePlus/issues/1638
Please use command + P as the workaround solution.
