### ISSUE TITLE
Unable to view anymore after sorting by JSON

### ISSUE THREAD

**Issue by z11i** [TablePlus/TablePlus#1936]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
314

3. The steps to reproduce this issue:
    1. create a table containing a json type, say, `foo`
    2. open the table in TablePlus
    3. click on the column of `foo`
    4. Error: `ERROR:  could not identify an ordering operator for type json`
    5. table is not showing anymore; have to reopen the table

Noted: If the bug is related to data, please attach an example SQL data.

I understand that JSON is not sortable by default. But it would be better to restore to the previous state (not sorted by the json column).

**Comment by huyphams** [comment]
Hi @z11i thank you for the feedback.
You can right-click on the header > remove sort.
<img width="626" alt="Screen Shot 2020-06-05 at 12 46 41 PM" src="https://user-images.githubusercontent.com/3654622/83841212-9e07d580-a72a-11ea-9a59-9d3208ae0ebd.png">

**Comment by huyphams** [comment]
I've updated the behavior, TablePlus will keep the column on error: https://www.dropbox.com/s/0x2b7gbuv9kvx38/TablePlus.dmg?dl=0
Thank you!
