### ISSUE TITLE
Lat and long point values being swapped when imported from .sql file

### ISSUE THREAD

**Issue by nckrtl** [TablePlus/TablePlus#1938]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.20

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
314

3. The steps to reproduce this issue:
Export a database with point values ( i.e. POINT(5.5606422 51.7506329),4326) ). Then confirm that the lat/long order in de .sql file is correct. Then import the sql file in a fresh database, you'll see that the lat/long value is being swapped. In MariaDB 10.4 it works correctly so It might be a specific issue related to the combination of MySQL and TablePlus.

Noted: If the bug is related to data, please attach an example SQL data.
can't share the sql file due to sensitive data

**Comment by desaintflorent** [comment]
I have the same bug too. when I import an exported database with point values.
Also when I change a point value manually in tableplus the lat and long get reversed. (ex: `POINT(3.0610803 50.6405425),4326` inserted get saved as `POINT(50.6405425 3.0610803),4326` instead  )
When I look at the sql query generated I can see : 
``
UPDATE `db`.`table` SET `location` = ST_GeomFromText('POINT(2.9569 50.6076)',4326) WHERE `id` = '1';
``
But it should be in my case :
``
UPDATE `db`.`table` SET `location` = ST_GeomFromText('POINT(2.9569 50.6076)',4326,'axis-order=long-lat') WHERE `id` = '1'
``
How could I set 'axis-order=long-lat' by default on my database in tableplus ?
Here an article I read on this : https://mysqlserverteam.com/axis-order-in-spatial-reference-systems/

**Comment by desaintflorent** [comment]
After digging a bit, I can confirm that the lat/long order in the export is correct but the 'axis-order=long-lat' parameter is missing. So the Export is in fact incorrect. **We need a way to choose  'axis-order=long-lat' in TablePlus when we export a database.**

If somebody is coming here with the same problem, as a workaround, I do a regex search and replace in my db export :

Search :
``
ST_GeomFromText\('POINT\((.+?)\)',4326\)
``

Replace :
``
ST_GeomFromText('POINT($1)',4326,'axis-order=long-lat')
``

Then when we import, lat and long values are not swapped anymore.

**Comment by huyphams** [comment]
You save me @desaintflorent thank you so much 🙌

**Comment by huyphams** [comment]
Please try the hotpatch build here 
https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thank you!

**Comment by desaintflorent** [comment]
Working perfectly with my database ! Tried it on Point and Geometry and the export and import is working good.

**Comment by desaintflorent** [comment]
That was the fastest bugfix i ever saw ! 
I was still on the free version of TablePlus, but i'm gonna buy a licence to congratulate your work ;) 
Cheers
