### ISSUE TITLE
Error geometry type parsing

### ISSUE THREAD

**Issue by jorisatabix** [TablePlus/TablePlus#1939]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 12.2 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.17), 64-bit

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3.6.0 - 319

3. The steps to reproduce this issue:

When having the `geometry` data type, with a `MULTIPOLYGON`, I get this message: `Error geometry type parsing`. Is it unsupported?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @jorisatabix could you please copy the MULTIPOLYGON data that causes the error? thank you!

**Comment by jorisatabix** [comment]
Uploaded it into a file, because it was too long to paste here in github.

[text.txt](https://github.com/TablePlus/TablePlus/files/4750323/text.txt)

**Comment by huyphams** [comment]
Hi @jorisatabix do you still seeing the issue with the recently builds? Please let me know if you're still seeing it.
