### ISSUE TITLE
Streaming response before the entire result is returned

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#194]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 9.6

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
83

**3. The steps to reproduce this issue:**
If I query out of a large table or using an expensive query that takes a while to complete I don't seem to get results until it's finished. I'm finding this different than with Postico (or possibly SQLpro) which start to return results almost immediately so I can evaluate the content and possibly cancel, modify, and start again.

**Comment by huyphams** [comment]
I'm working on this issue 👍

**Comment by huyphams** [comment]
Next update 92 👍
