### ISSUE TITLE
Errors appearing multiple times in query result

### ISSUE THREAD

**Issue by shawnhooper** [TablePlus/TablePlus#1940]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

318

3. The steps to reproduce this issue:

1. Query:   SELECT * FROM module WHERE idx = 1 
2. Query 1 ERROR: Unknown column 'idcc' in 'where clause' appears twice. 

(Column should have been "id" without the x) 

<img width="963" alt="image" src="https://user-images.githubusercontent.com/2073284/84073258-71f48a80-a99e-11ea-9524-a5c865bf1e4c.png">

**Comment by fo2w** [comment]
![image](https://user-images.githubusercontent.com/1845057/84120925-0d523200-aa69-11ea-8f0f-79e6802cddea.png)

you may need to enable this option which stop the query while error occurs

**Comment by huyphams** [comment]
ah thanks @fo2w @shawnhooper now I can reproduce the issue.

**Comment by huyphams** [comment]
Thanks, please update the app to build 320. It should fix the issue. I'm sorry about that.

**Comment by shawnhooper** [comment]
Thank you @huyphams !
