### ISSUE TITLE
Executing to many queries

### ISSUE THREAD

**Issue by ReptoxX** [TablePlus/TablePlus#1943]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySql 5.6
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
318
3. The steps to reproduce this issue:
I've had 378 Queries in my sql editor and tried to ran it. It didnt respond immediately so i hit command + return again (in total three times).
After the program became responsive again, it started to execute the queries over and over again.

![image](https://user-images.githubusercontent.com/13363890/84148944-fc50f300-aa5f-11ea-991f-e3663a147695.png)

**Comment by ReptoxX** [comment]
It happend with 193 queries, without me smashing the execute command twice.

**Comment by huyphams** [comment]
We fixed this issue @ReptoxX sorry about that. It only happens when the query has an error.

**Comment by ReptoxX** [comment]
That is good news. Will there be an Hotfix-Patch or something. I can't use the program right now.

**Comment by huyphams** [comment]
You can turn on the return on error 
<img width="364" alt="Screen Shot 2020-06-09 at 7 56 03 PM" src="https://user-images.githubusercontent.com/3654622/84149826-43081280-aa8b-11ea-9937-4ab2663af298.png">
We're going to a new update within 1 hour (so many updates :( ). Thanks.

**Comment by ReptoxX** [comment]
Thank you for the good work and fast response. I will work around it with this option.

**Comment by huyphams** [comment]
Please download this hot patch @ReptoxX https://www.dropbox.com/s/1021o6htbn46ynq/tableplus.dmg?dl=0 Thank you. If the error is resolved. We will release this patch. Thank you for the feedback.

**Comment by ReptoxX** [comment]
Looking good, the queries get executed. And these with errors does not cause a return or loop.
So my issue seems fixed :)

**Comment by huyphams** [comment]
Thanks, I'm working on the update.
