### ISSUE TITLE
Connection settings won't saved, if test connection was failed

### ISSUE THREAD

**Issue by objque** [TablePlus/TablePlus#1949]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
The latest available build is 320

3. The steps to reproduce this issue:

- Open up broken settings
- Click *test connection* and you will see error: connection is broken
- Change port number to 12345
- Click save settings
- Open up connection settings, that was just edited
- ???
- Connection port is 5433, but we tried to save 12345

![Screen-Recording-2020-06-10-at-2](https://user-images.githubusercontent.com/7000585/84310869-027fc600-ab6b-11ea-9fbd-251f95849b53.gif)

**Comment by vadimmisko** [comment]
Not sure if related, but I cant save any of the mongo connections also. Test always fails

**Comment by huyphams** [comment]
Hi @objque @vadimmisko are you using custom data location (cloud dropbox, google, icloud)? Thanks

**Comment by objque** [comment]
Hey, nope. Just using tableplus with it own location

**Comment by huyphams** [comment]
ohhh, that's really bad, let me fix it.

**Comment by huyphams** [comment]
Hi, please try this patch: https://www.dropbox.com/s/1021o6htbn46ynq/TablePlus.dmg?dl=0 it should fix the issue. Thanks all.

**Comment by objque** [comment]
Yep, my case now works. I don't use mongodb and can't verify is @vadimmisko's problem solved

**Comment by vadimmisko** [comment]
@huyphams does not solves problem with mongo. I can create separate issue if needed

**Comment by huyphams** [comment]
TablePlus stores Mongo in the keychain, so I think the issue is related to the keychain bug.
