### ISSUE TITLE
Feature Request: Database URL import

### ISSUE THREAD

**Issue by dcolthorp** [TablePlus/TablePlus#195]
I work with a lot of 12-factor apps, where the database connection is encoded in a URL. It'd be great if there was a feature to create a new connection from parsing a `postgres://`, `mysql://`, etc. URLs. 

Does this feature exist and I just missed it? Currently I have to pick apart the URLs for every server. I think this would be the single most useful new feature TablePlus could get (for me).

Great app!

**Comment by huyphams** [comment]
I’m working on import and export connections. I will include this in the next update. Thanks 😁

**Comment by huyphams** [comment]
@dcolthorp it's released in hotfix release 85. Please check it out 😄

**Comment by dcolthorp** [comment]
@huyphams – I wasn't able to find the feature in the new build (85). Can you provide info on where the feature is located/how to use it? Thanks!

**Comment by huyphams** [comment]
Can you download on website agian. It’s hotpatch so it wasnt’t included if you update the app before hot path released.

**Comment by dcolthorp** [comment]
Ah, that did it. Unfortunately, I wasn't able to get it to work with the database URLs for postgres from Heroku. The url looks like `postgres://asdfasdfasdfaa:asFDSa5FdfSDkdslS5kK0-ksKJ@ec2-12-123-123-123.compute-1.amazonaws.com:5432/sdlkds93jsd92h`.

I get an "invalid URL" error.

**Comment by huyphams** [comment]
Thanks let me check

**Comment by huyphams** [comment]
Hi @dcolthorp Just fixed issue about, could you give a try this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

Thanks 😄

**Comment by dcolthorp** [comment]
Awesome, thank you! Looks like I’ve finally found my DB app!


On February 1, 2018 at 12:02:29 PM, Huy Pham (notifications@github.com)
wrote:

Hi @dcolthorp <https://github.com/dcolthorp> Just fixed issue about, could
you give a try this build:
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

Thanks 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TablePlus/TablePlus/issues/195#issuecomment-362332024>,
or mute the thread
