### ISSUE TITLE
[Feature Request] Need shortcut to make a column value NULL

### ISSUE THREAD

**Issue by Sampath7619** [TablePlus/TablePlus#1951]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 320

3. The steps to reproduce this issue:
At present, there is no shortcut to making a column value NULL, its a bit time consuming right now if I want to make a column values as null. 
A Shortcut will be much helpful. 
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, A shortcut is much better but I just wanna make sure that you are aware of:

1. hold option + click > set null.
2. Right-click > Set value > null.
3. Use the right sidebar.

If the data is number or structure type, just leave it empty TablePlus will convert it to null.

**Comment by Sampath7619** [comment]
Hi,

Yeah, I'm aware of it. But it's making a bit time consuming to make them. So I felt a shortcut would help.

**Comment by huyphams** [comment]
I've added a shortcut to do this: Option + return it will be released in the next update 360.

Ref: https://github.com/TablePlus/TablePlus/issues/2205
