### ISSUE TITLE
Opening saved query always opens new tab

### ISSUE THREAD

**Issue by just3ws** [TablePlus/TablePlus#1952]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
321

3. The steps to reproduce this issue:

- Save a query in the Queries widge
- Open the query in a tab
- Double click the saved query
- A new tab is opened (now there are two tabs)
- Make a change in the second tab
- Save and close the second tab
- Save and close the first tab
- See that the changes have been overwritten by the first tab

This happened a couple times before I noticed and wondered why old changes were being saved. I had several files open and didn't notice that there were several open tabs for the same file.

The expected behavior for me is some combination of:

- Reopening a file that is already opened in a tab just places focus on the open tab
- Changes in files are reflected across multiple tabs
- Trying to the content of a tab to a modified file should give a warning

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
TablePlus now will find and navigate to the right tab instead of opening new tab.
