### ISSUE TITLE
multiple-carets with ⌘ + D works not consistently

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1953]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgress 11
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 319

clicking with ⌘ + D does often not result in extra cursor. It seems you need to place it really carefully at a very specific place in the text. 

example sql:

can be sent to you if required.

**Comment by huyphams** [comment]
Hi @BFJonk the difference between TablePlus and other apps is that TablePlus only selects the word after the cursor position when you pressing command + D.
If you want to select all words, you have to press command + control + G

**Comment by BFJonk** [comment]
Hi @huyphams , apologies for the inconvenience, I now see that my title was misleading. 

I just learned to use the multi select with the command key (⌘) and find the feature really useful. 

Howver, I also found that clicking at the right place was a nuisance. Example, try to click `.week` between the `.` and `week` to make that `'.create_date_week'`

SELECT
	*
FROM
	total_new  
	LEFT JOIN won_total_new ON total_new.week = won_total_new.close_date_week
	LEFT JOIN za_total ON total_new.week = za_total.week
	LEFT JOIN za_won ON total_new.week = za_won.close_date_week
	LEFT JOIN one_total_new ON total_new.week = one_total_new.week
	LEFT JOIN one_won_new ON total_new.week = one_won_new.close_date_week
	LEFT JOIN eu_total_new ON total_new.week = eu_total_new.week
	LEFT JOIN eu_won_new ON total_new.week = eu_won_new.close_date_week
	LEFT JOIN be_total_new ON total_new.week = be_total_new.week
	LEFT JOIN be_won_new ON total_new.week = be_won_new.close_date_week
	LEFT JOIN de_total_new ON total_new.week = de_total_new.week
	LEFT JOIN de_won_new ON total_new.week = de_won_new.close_date_week
	LEFT JOIN egn_total ON total_new.week = egn_total.week
	LEFT JOIN egn_won ON total_new.week = egn_won.close_date_week;

**Comment by huyphams** [comment]
Hi, @BFJonk I've fixed this issue, now you can Hold Command + Click to add more caret easily.
