### ISSUE TITLE
Slow Import, can it be made faster?

### ISSUE THREAD

**Issue by ConnectGrid** [TablePlus/TablePlus#1954]
Used SequelPro for years and it works great, but TablePlus seems to have an edge on it by supporting multiple database types and seems to have more active development. I'd pay for this app if/when the time came, but there's one hangup that I have.... imports are *extremely* slow compared to SequelPro, even on localhost. Painfully slow. Can this be improved?

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.5.4 (317)

3. The steps to reproduce this issue:
Import a compressed SQL export.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @ConnectGrid please update the app to our latest release and try the restore database feature. Please let me know if you're still seeing the issue.

**Comment by ConnectGrid** [comment]
I didn't realize the app was outdated. When I relaunched it just now, it was suddenly at version 3.6.1. Update must have happened in the background.

Import speed seems to be better with this version. At least it seems to process more MB/s now.

Thank you!
