### ISSUE TITLE
New sqlite connection dialog is cropped on macOS

### ISSUE THREAD

**Issue by abreis** [TablePlus/TablePlus#1956]
With build 320 on macOS 10.15.5, the dialog to create a new SQLite connection is cropped at the bottom:

<img width="612" alt="sqlite_crop" src="https://user-images.githubusercontent.com/95046/84580965-40335780-add4-11ea-8093-a8268b678830.png">

**Comment by huyphams** [comment]
Thanks, @abreis I fixed this issue 👍
