### ISSUE TITLE
Problem opening more than two tabs with Pro Database

### ISSUE THREAD

**Issue by JLHPursuitTech** [TablePlus/TablePlus#1957]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySql 5.7.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 320

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

Not sure if I am delusional but I am new.

I am having an issue where I am trying to open multiple tabs in a database that is 'Pro'.

My app is still in the free trial but that should not have an affect on a database that is upgraded no?

Can anyone shed some light?

**Comment by huyphams** [comment]
Thanks @JLHPursuitTech but TablePlus free trial limit 2 tabs.
