### ISSUE TITLE
JSON export / copy as with "zero fill" values results in broken JSON

### ISSUE THREAD

**Issue by dominikkukacka** [TablePlus/TablePlus#1959]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.30
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.5.3 (314)
3. The steps to reproduce this issue:

```
CREATE TABLE `dbapilay_maindb`.`test` (`id` int(11) NOT NULL AUTO_INCREMENT, `test` smallint(3) unsigned zerofill, PRIMARY KEY (id));

INSERT INTO `dbapilay_maindb`.`test` (`test`) VALUES ('1'), ('99'), ('999');
```

data in table: 
![image](https://user-images.githubusercontent.com/243319/84797755-76eab700-affa-11ea-85b8-0994172b9494.png)

After choosing "Copy Rows as JSON" or export as JSON it will export the following:
```
[
  {
    "id": 1,
    "test": 001
  },
  {
    "id": 2,
    "test": 099
  },
  {
    "id": 3,
    "test": 999
  }
]
```

So `test` is represented as an octal number which is sadly invalid and makes the whole JSON export/"copy as" invalid.

![image](https://user-images.githubusercontent.com/243319/84798131-e52f7980-affa-11ea-89ce-293c236c7f80.png)

**Comment by huyphams** [comment]
Fixed will be available in the next update!

**Comment by dominikkukacka** [comment]
Thank you!!
