### ISSUE TITLE
Ability to mass update rows

### ISSUE THREAD

**Issue by philippe-tellier** [TablePlus/TablePlus#196]
It would be very helpful to have the ability to select multiple rows and update all of them when changing the values in the right side bar.

Currently, it's only updating the last selected row.

**Comment by huyphams** [comment]
Nice Idea 😄, I will come back with another build.

**Comment by huyphams** [comment]
@philippe-tellier ready for the next update 😸 
![multiple](https://user-images.githubusercontent.com/3654622/35732451-f812b96c-084b-11e8-99f7-fa495d4f63af.gif)

**Comment by philippe-tellier** [comment]
@huyphams You are amazing 😎

Thanks a lot!
