### ISSUE TITLE
Can't import large single query from a SQL Dump (63Mo)

### ISSUE THREAD

**Issue by Kalzem** [TablePlus/TablePlus#1960]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x (Mac Catalina)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

TablePlus 3.6.1

3. The steps to reproduce this issue:

I have a SQL file of 63Mo that inserts (in a single query) many rows. But at around 10Mo / 63Mo processed, I get this error:

> The current max allowed package is 4194304 bytes but the statement length is 64308244.0 bytes.

How can I configure TablePlus to handle 63Mo of query?

**Comment by huyphams** [comment]
Hi @Kalzem please increase the max_allow_package on your server and try again. It's a MySQL server variable.

**Comment by Kalzem** [comment]
Thank you for your reply.

I had some troubles locating my.cnf on Mac Catalina.
For those wondering, mine was found at: `/usr/local/etc/my.cnf` where I added the line `max_allowed_packet=250M` then rebooted Mysql with: `brew services restart --all`.

Now my initial error is gone, but a new one appeared: `Data too long for column "cell" at row 618` which doesn't make sense because that column is declared as "TEXT" and the value at that row is only 40 utf8 characters. Oh well... I guess big single query isn't appreciated.
