### ISSUE TITLE
Table view counter issue

### ISSUE THREAD

**Issue by cotfas** [TablePlus/TablePlus#1965]
Build 320
Catalina 10.15.5

Having a table view that has 100k entries, when looking into it from left pane:

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/3340367/85224201-3e1f5900-b3d1-11ea-8797-f93ca1c8ff4b.png">

When querying it from sql statement: select * from table_view:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/3340367/85224191-32cc2d80-b3d1-11ea-926a-9b923c5bc78d.png">

The counter does not show the right values.

**Comment by huyphams** [comment]
Hi @cotfas thanks for the feedback. TablePlus will estimate the value before counting the actual row number. You can force TablePlus always count the row by uncheck the estimate row in the settings (but be careful, it will result in hanging sometimes on the very big table).
