### ISSUE TITLE
Incorrect export for MySQL8 (double quotes issue)

### ISSUE THREAD

**Issue by RuSS-B** [TablePlus/TablePlus#1967]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**MySQL 8**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**3.6.1 (320)**

3. The steps to reproduce this issue:
**Export tables from MySQL 8 database (not Backup feature), then try to import them will be an error because of double quotes used for the column names**

**Comment by RuSS-B** [comment]
![image](https://user-images.githubusercontent.com/3403762/85285053-e0eeda80-b498-11ea-8abd-d4d2ef615a8d.png)

**Comment by RuSS-B** [comment]
![image](https://user-images.githubusercontent.com/3403762/85285147-0ed41f00-b499-11ea-980d-f1733980e55d.png)

**Comment by huyphams** [comment]
Hi @RuSS-B please check your quote config, the creation statements were not produced by TablePlus but the server-side, so it would be affected by your server-side quote config.

**Comment by huyphams** [comment]
it would be the `ANSI_QUOTES`
ref: https://stackoverflow.com/questions/10591231/how-can-i-see-the-specific-value-of-the-sql-mode

**Comment by RuSS-B** [comment]
Hey @huyphams, thanks for your hint. It really helped me to understand what's really going on.

Still have a small question regarding this line in the export file.
Is it made by Tableplus? 
```
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
```

The thing is when it set's SQL_MODE to only NO_AUTO_VALUE_ON_ZERO it removes my ANSI_QUOTES param and the import breaks. If I remove this line it works like a charm

**Comment by jnbn** [comment]
This problem usually might be because of your remote server may have ANSI_QUOTES in its configuration. So instead of removing those lines every time (importing) you might want to consider changing your MySQL servers configuration not to have ANSI_QUOTES

**Comment by tnorthcutt** [comment]
For anyone else in the future running into this, if you aren't able to change the config on the remote server for whatever reason, you might try adding this to the dump before you import it:

`SET SESSION sql_mode = 'ANSI_QUOTES';`

I did that and it worked, allowing me to import the dump which used double quotes for column names.
