### ISSUE TITLE
Oracle - ORA-01445 on views

### ISSUE THREAD

**Issue by ccakes** [TablePlus/TablePlus#1968]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle (server is 12.2.0.1.0)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.6.2 (build 323)

3. The steps to reproduce this issue:
Attempt to open any view in data mode. I'm not an administrator of this server and have no visibility of the underlying tables comprising the views, but this is now happening on all views. I update TablePlus regularly but unfortunately have been lazy is raising this issue - I _think_ this behaviour started 1 or 2 builds ago. Maybe 321?

<img width="395" alt="image" src="https://user-images.githubusercontent.com/103831/85286432-f19c5200-b492-11ea-8659-cc786f91f5f2.png">

**Comment by huyphams** [comment]
Hi @ccakes I'm sorry for the issue, please try this patch: https://www.dropbox.com/s/r98khiuvkf0fzf0/TablePlus.dmg?dl=0 it should resolve the issue (TablePlus will not use ROWID on views).

**Comment by ccakes** [comment]
Wow - quickest response ever!! Link is 404 atm but this isn't causing me significant pain, happy to wait until the next release drops if that is easier.

Thanks again for an awesome product ❤️

**Comment by huyphams** [comment]
Hi, I updated the link: https://www.dropbox.com/s/9gxco8jt6m6rt8a/tableplus.dmg?dl=0
I'm not sure why Dropbox keeps changing the link recently. it's annoying.

**Comment by ccakes** [comment]
Just installed and can confirm, that's resolved the issue. Thanks for the speedy reply!
