### ISSUE TITLE
Tables are not showing up in sidebar

### ISSUE THREAD

**Issue by katiannap** [TablePlus/TablePlus#1969]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 8.0.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 3.6.1 (820)

3. The steps to reproduce this issue:
I cant find the tables i am creating in my sidebar.

Noted: If the bug is related to data, please attach an example SQL data.
<img width="343" alt="Screen Shot 2020-06-22 at 2 36 27 PM" src="https://user-images.githubusercontent.com/57581959/85337687-c6673200-b495-11ea-8787-dd5b71bdac2c.png">

**Comment by huyphams** [comment]
Hi @katiannap please try to refresh TablePlus by pressing command + R.

**Comment by katiannap** [comment]
Thanks!

**Comment by jeturcotte** [comment]
old, but this came up in my searches... so maybe it'll come up in someone else's search, too... when I connect to a mysql instance, the 'tables' on the left will accordion with a single click... for postgres, it takes a double click to load them up before accordions will start.  I didn't anticipate that, so thought i'd misconfigured it when i hadn't.
