### ISSUE TITLE
New version 84 breaks TablePlus for any OSX < 10.12

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#197]
TablePlus is unusable for many new OSX users due to new tab feature.

![screen shot 2018-01-26 at 11 20 10 am](https://user-images.githubusercontent.com/7946786/35456608-f3434dc8-028a-11e8-8457-b311d3b62f55.png)

**Comment by brian-crane** [comment]
Can I get an older build version in mean time?

**Comment by huyphams** [comment]
https://s3.amazonaws.com/tableplus-osx-builds/83/TablePlus.zip
Sorry im on phone 😬

**Comment by brian-crane** [comment]
Thanks Huy! I found a local table plus build 80 I will use in mean time.  Thanks again for quick response!

**Comment by huyphams** [comment]
I will make a hotfix build for you tmr with disable update notification. It’s annoying.

**Comment by akilism** [comment]
You can get around this by editing the connection and then clicking connect in the meantime.

**Comment by mkarnicki** [comment]
@huyphams Yes please. I was considering purchasing, and then this happened. I'm on El Capitan and don't intend to update to yet-unstable Sierra. Thanks.

**Comment by huyphams** [comment]
Sure, I will put a config to preferences to turn it off 👌

**Comment by brian-crane** [comment]
@huyphams Thanks! You are the best!

@mkarnicki - it's a great DB tool

**Comment by huyphams** [comment]
Hey @brian-crane @mkarnicki please upgrade to build85, it is fixed.

**Comment by huyphams** [comment]
I will close this issue. The next update (build 86) will include ability to turn off check for update notification.

**Comment by huyphams** [comment]
Hi all, 
The build 86 is released with the ability to turn off update notification.
I also added a page for legacy TablePlus version here: [Download](https://tableplus.io/blog/2017/02/changelogs.html)

**Comment by astewart-twist** [comment]
Build 90 appears to once again break for El Capitan.

**Comment by huyphams** [comment]
Hi @astewart-twist could you give me more information about the bug? because I have tested on EL Capitan before released this build.

**Comment by huyphams** [comment]
<img width="1281" alt="screen shot 2018-02-28 at 9 20 46 am" src="https://user-images.githubusercontent.com/3654622/36766538-f44ed03c-1c68-11e8-951a-28e2df197d7e.png">
