### ISSUE TITLE
[UI Improvement] Make TablePlus easier to reposition by adding space somewhere on the toolbar.

### ISSUE THREAD

**Issue by mkrkelj1** [TablePlus/TablePlus#1974]
Driver: PostgreSQL 11
TablePlus Build: 3.61

When you resize TablePlus, the toolbar grows to accommodate 100% of the width (more specifically, the status bar), leaving you with very little room to tack onto if you want to reposition it on your monitor. I think adding some spacing on either side of the status bar would help. I’ve resorted to clicking on the space between the Action Controls and the title bar / window control buttons (close, minimize, maximize). TablePlus toolbar, regardless of width:

<img width="1241" alt="table-plus-toolbar" src="https://user-images.githubusercontent.com/43376568/85781628-e5fb9600-b6f3-11ea-887d-d3c28a31ba53.png">

Compare this to Apple’s Notes app, which at a certain width has a nice chunk of space to grab onto near the middle: 

<img width="1055" alt="notes-toolbar" src="https://user-images.githubusercontent.com/43376568/85781681-f1e75800-b6f3-11ea-9138-7a32aa507fb3.png">

When you reduce the width the search bar will collapse into that space, but still give you enough space on the right to grab onto:

<img width="801" alt="notes-toolbar-collapse" src="https://user-images.githubusercontent.com/43376568/85781765-07f51880-b6f4-11ea-92f6-7b270c4eca39.png">

Anyway, this is a minor issue for an otherwise excellent tool that's replaced DataGrip for me.

**Comment by huyphams** [comment]
You can always custom the toolbar, add more spaces as well as remove unused button with TablePlus and many other mac app @mkrkelj1 it was the macOS standard.


<img width="1476" alt="Screen Shot 2020-06-26 at 2 00 52 AM" src="https://user-images.githubusercontent.com/3654622/85782727-f8f08380-b750-11ea-9d87-55b2cab08ea7.png">

**Comment by huyphams** [comment]
Mine after removing some button and adding spaces (right-click on the toolbar > custom toolbar...)
<img width="1061" alt="Screen Shot 2020-06-26 at 2 02 25 AM" src="https://user-images.githubusercontent.com/3654622/85782973-2806f500-b751-11ea-8724-adaa86a55eb0.png">

**Comment by mkrkelj1** [comment]
> You can always custom the toolbar, add more spaces as well as remove unused buttons with TablePlus and many other mac apps @mkrkelj1 it's the macOS standard.
> 
> <img alt="Screen Shot 2020-06-26 at 2 00 52 AM" width="1476" src="https://user-images.githubusercontent.com/3654622/85782727-f8f08380-b750-11ea-9d87-55b2cab08ea7.png">

I saw that you could edit it, but totally missed the _Space_ and _Flexible Space_ options - excellent! This definitely resolves the issue.
