### ISSUE TITLE
Syntax error copy as markdown table when column value contains a pipe symbol

### ISSUE THREAD

**Issue by standaniels** [TablePlus/TablePlus#1975]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
![image](https://user-images.githubusercontent.com/1199737/85987121-84864080-b9ed-11ea-870a-04d052ef569c.png)

3. The steps to reproduce this issue:

- Run the following query
```sql
select "pipe | symbol" as foo
```
- Right click on row => copy as => markdown table.
- This is the result:

```markdown
| foo           |
|---------------|
| pipe | symbol |
```
| foo           |
|---------------|
| pipe | symbol |

- The pipe symbol should be escaped, like this:

```markdown
| foo            |
|----------------|
| pipe \| symbol |
```
| foo            |
|----------------|
| pipe \| symbol |

**Comment by huyphams** [comment]
Hi @standaniels, thank you so much. I just fixed this issue. it will be released in the next update!
Have a great day!
