### ISSUE TITLE
Dragging the status toolbar item causes a window offset

### ISSUE THREAD

**Issue by coocy** [TablePlus/TablePlus#1977]
1. Driver: MySQL 8.0.18

2. TablePlus version: 3.6.2 (325)

3. The steps to reproduce this issue:

Hold the _status_ toolbar item and drag to move the window, after release the mouse, the main window then moves up automatically for 1 pixel.
If do this when the window is deactivated, sometimes it moves more pixels.
Dragging the blank area of the titlebar wouldn't cause the issue.

This a small issue but it bothers me for a long time.

![screenshot](https://user-images.githubusercontent.com/2136111/86019644-6d7d3800-ba59-11ea-9de3-690987f0421d.gif)

**Comment by huyphams** [comment]
Hi, thank you. I just fixed this issue. It will be included in the next update!
