### ISSUE TITLE
Delete on table with binary primary key produces syntax error

### ISSUE THREAD

**Issue by lenada** [TablePlus/TablePlus#1983]
### 1. Which driver are you using and version of it
MariaDB 10.3.8
### 2. Which TablePlus build number are you using
MacOS Version 2.12 (282) as well as 3.6.1 (322)
### 3. The steps to reproduce this issue:
Delete row with/by binary key produces invalid SQL/DLL and therefore fails.
generated SQL:
```SQL
DELETE FROM `selectiveads`.`sample` WHERE `id` = X'11eabc6378863bb49c409600000c020f)';
```

Sample Data:
```SQL

CREATE TABLE `sample` (
  `id` binary(16) NOT NULL COMMENT '(uuid_binary_ordered_time)',
  `foo` smallint(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `sample` (`id`, `foo`) VALUES (X'11eabc6378863bb49c409600000c020f', '18');
```

**Comment by huyphams** [comment]
Ops, sorry for the issue. I just fixed it. You can use the MySQL driver for MariaDB as a temporary solution, thank you so much @lenada
