### ISSUE TITLE
Unable to connect to remote MySQL in docker

### ISSUE THREAD

**Issue by gclove** [TablePlus/TablePlus#1985]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

`Mysql 5.7.30`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3.6.2(322)

3. The steps to reproduce this issue:

```bash
$ docker run --name some-mysql -p 23309:3306 -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7.30
```

> If the local IP is `2.2.2.2`

> The remote IP is `3.3.3.3` port `23309`

----

Tableplus will show

```
Access denied for user 'root'@'2.2.2.2' (using password: YES)
```

Is tableplus not connecting to 3.3.3.3 and trying 2.2.2.2?

**Comment by huyphams** [comment]
Hi @gclove TablePlus will use the address that you enter in the input. The message `Access denied for user 'root'@'2.2.2.2' (using password: YES)` is the server message. the `2.2.2.2 ` could be your router IP.

**Comment by gclove** [comment]
Yes, my router IP is `2.2.2.2` .

But I can connect with MySQL cli .

Does tableplus not support **caching_sha2_password**  ?

**Comment by gclove** [comment]
![image](https://user-images.githubusercontent.com/3645410/86441726-3f407680-bd3f-11ea-86f2-370158cbf78c.png)

**Comment by huyphams** [comment]
I believe that the address should be 127.0.0.1 because you mapped it to the local. Both 5x and 8x driver are support caching_sha2_password if it's not, it will throw the unsupported message.

**Comment by gclove** [comment]
Thank you very much. It is possible that I copied an extra space when copying the password.  

I'm so sorry to bother you ~~ @huyphams
