### ISSUE TITLE
[Feature Request] Alert/Safe Mode for Restore

### ISSUE THREAD

**Issue by kielabokkie** [TablePlus/TablePlus#1987]
I use the restore functionality quite often to load a specific state for my application during development. I have safe mode enabled for my production database but this does not apply to the restore database functionality. It would be great if the alert/safe mode would also prevent accidentally dropping and overwriting a production database when using the restore functionality.

**Comment by huyphams** [comment]
Thanks, I've added it, please wait for the next update!

**Comment by kielabokkie** [comment]
Great, looking forward to the next update 😄 Thanks @huyphams!
