### ISSUE TITLE
Redis: impossible to view keys, view database, etc... 

### ISSUE THREAD

**Issue by tristanbes** [TablePlus/TablePlus#1991]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`redis_version:5.0.3`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`325`
(also tried the latest stable)

3. The steps to reproduce this issue:
Connect to the redis database using TablePlus
- Can't do nothing
- Can't view keys
- Can't interact with database
- Command executed in "SQL" only displays into a tinytinytiny windows

![Item-0_et_AppleClockExtra](https://user-images.githubusercontent.com/346010/86918336-d71ad780-c126-11ea-8891-811712919d88.png)

**Comment by huyphams** [comment]
Hi @tristanbes you can view key and everything on the left sidebar (I saw you hide the left sidebar) you can toggle it by click the button at the top right.

```
Command executed in "SQL" only displays into a tinytinytiny windows
```
It was designed for data row, if you want to view it you can use the middle mouse or select it and press command + enter or click it and view it on the right sidebar.

**Comment by huyphams** [comment]
Please check this screenshot.
<img width="1137" alt="Screen Shot 2020-07-08 at 7 36 28 PM" src="https://user-images.githubusercontent.com/3654622/86919376-54a80d00-c152-11ea-85d1-394f768d379f.png">

**Comment by tristanbes** [comment]
ok thanks for the quick answer; sorry for the noise mainly due to the left sidebar hidden

**Comment by tristanbes** [comment]
Btw @huyphams ;

Pagination shows only 5 pages, when we have over 2 millions keys; is there any sort of limitations ?

**Comment by huyphams** [comment]
Could you show me a screenshot @tristanbes thanks!

**Comment by tristanbes** [comment]
Sure.
I've reached the end of pagination after few clicks;

![Item-0_et_AppleClockExtra_et_AirPortExtra_et_BatteryExtra](https://user-images.githubusercontent.com/346010/86920434-14349900-c12a-11ea-8476-1d51cbcd8a3b.png)

**Comment by conspireagency** [comment]
@tristanbes @huyphams has anyone been able to get TablePlus working with Redis to show all the data in the store?  Running into the same thing where it only shows 35 rows and paginates 2 times before running out of data... when I know for a fact there's thousands of entries in there.

**Comment by mkll** [comment]
> Please check this screenshot. <img alt="Screen Shot 2020-07-08 at 7 36 28 PM" width="1137" src="https://user-images.githubusercontent.com/3654622/86919376-54a80d00-c152-11ea-85d1-394f768d379f.png">

Some time ago I used TablePlus to work with Redis. My screen looked the same as your screenshot and everything was fine.

At some point, TablePlus stopped displaying Redis data in the left column. There's simply nothing there. I am attaching a screenshot.

![Screenshot 2023-11-19 at 22 58 51](https://github.com/TablePlus/TablePlus/assets/1652009/c92400ae-494a-47df-bc26-035d4f5708b1)

Of course, the data exists, I can work with it through RedisInsight, as well as thru CLI, and my site uses Redis to store sessions. Everything is working fine. This problem is exclusively related to TablePlus.

*TablePLus Version 5.3.6 (496)*
* Redis 7*

**Comment by huyphams** [comment]
Hi @mkll I think it was disconnected because there is no Redis version on the status bar.

**Comment by mkll** [comment]
@huyphams Maybe. But why doesn't TablePlus report any errors?

**Comment by mkll** [comment]
![Screenshot 2023-11-19 at 23 24 40](https://github.com/TablePlus/TablePlus/assets/1652009/ecfe728a-2083-41e8-88e9-66010263f953)

Connection check is successful

**Comment by huyphams** [comment]
I think you are missed the user.

Redis can connect but can not auth

**Comment by mkll** [comment]
> I think you missed the user.
> 
> Redis can connect but can not auth

The problem turned out to be different, the password was wrong. I didn't understand what was happening, so I didn't know which direction to go. Thank you for suggesting the right way of thinking! Now everything is working.

P.S. It would be better if TablePlus were not so silent. :)

**Comment by huyphams** [comment]
Thanks, I fixed the issue for the newest redis: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

Reason: Redis change the message when auth fail, but TablePlus is following false positive strategy. If you have a chance, please download that patch.
