### ISSUE TITLE
Receiving "Discard all changes?" warning when closing any query

### ISSUE THREAD

**Issue by dom0do** [TablePlus/TablePlus#1992]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MS SQL DBVERSION_70

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
Build 322

**3. The steps to reproduce this issue:**

- Open a connection window, click the **Queries** sidebar section, and open any saved query. The query can even be a blank file. (I keep a blank one for quick access to a fresh editor tab)
- Open another saved query so you have tabs and Close✖️ buttons.
- Select one of the tabs, then click the ✖️ to close it. Observe a prompt warning about unsaved changes even though there have been none. (⛔️ false positive)
- If you cancel the Warning prompt and then close the whole window with the red Close button, you will _not_ receive any false warnings about changes. ( ✅ correct behavior)
- If you open a couple query tabs, modify them, and then close the whole window, you will still not receive any warning even though you _did_ have unsaved changes (⛔️ false negative)

**Comment by j-ro** [comment]
Same here, except it happens with just one tab, and you can't quit the app -- if you click "discard" it just pops up again. You need to use the red X to close the window, or force quit, super annoying.

**Comment by huyphams** [comment]
Hi, if you have a chance, please download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Please let me know if you are still seeing the issue.
Thanks
