### ISSUE TITLE
[Feature Request] Ability to group databases in Main Menu

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#1994]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgres 11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 327

You can sort databases in the main menu based on driver, name and tag(dev/test/production). It be nice if you could also group databases together.

**Comment by huyphams** [comment]
Hi @BFJonk thank you for the suggestion. Could you explain the idea? I'm not sure that I understand it correctly.
TablePlus already supported group: right-click new > group.

<img width="542" alt="Screen Shot 2020-07-10 at 9 10 23 PM" src="https://user-images.githubusercontent.com/3654622/87163591-c9657d80-c2f1-11ea-89f9-7067b154063e.png">

<img width="342" alt="Screen Shot 2020-07-10 at 9 09 46 PM" src="https://user-images.githubusercontent.com/3654622/87163548-ba7ecb00-c2f1-11ea-8242-f45fe043c281.png">

**Comment by BFJonk** [comment]
Hi Henry, 

Apologies for missing this out! This was exactly what I was looking for :-) 

Cheers,
Bart.
