### ISSUE TITLE
tab switching keyboard shortcuts do not work when in edit mode

### ISSUE THREAD

**Issue by necmettin** [TablePlus/TablePlus#1999]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

322

3. The steps to reproduce this issue:

- Close all tabs.
- Open two tabs to any two tables.
- Double click any cell in the first tab, getting into edit mode. Or create/edit any filter and click the text field of the filter.
- Press ⌘+1 or ⌘+2 (or any other digit for that matter).

Expected result:
- The app should switch to the pressed tab (first tab for ⌘+1 etc), but it doesn't.

**Comment by huyphams** [comment]
Hi, thank you. I just fixed it in this patch: If you have a chance, please give it a try: https://www.dropbox.com/s/g801eovguzkqvlr/TablePlus.dmg?dl=0
