### ISSUE TITLE
Please use default browser for button Update Now

### ISSUE THREAD

**Issue by und3fined** [TablePlus/TablePlus#2]
Hi developer,

I'm not use Safari is *default browser*.
Please use default browser for button Update Now  

Thanks.

**Comment by huyphams** [comment]
TablePlus is using Safari for login because Safari is more secure and compatible with Apple App Deeplink (TablePlus needs deeplink to pass login info after oauth2 success). TablePlus only open Safari for login/purchase purpose  so I think it's not annoying that much.
Thank for feedback.

**Comment by und3fined** [comment]
I think you should upload the app to the App store for automatic updates.

**Comment by huyphams** [comment]
@und3fined App Store require sandbox feature, with sandbox mode, we can't choose file outside the app and have a lot of disadvantaged

**Comment by huyphams** [comment]
Now TablePlus will update new version via default browser
