### ISSUE TITLE
Use default private key for connecting over SSH.

### ISSUE THREAD

**Issue by hariesnurikhwan** [TablePlus/TablePlus#20]
Like many other apps like Transmit, Sequel Pro they choose private key automatically unless we select other private key. It would be very convenient. 

It's not big improvement but it'd save some time for us 😁

**Comment by huyphams** [comment]
Nice idea, I will try in the next release 😁

**Comment by huyphams** [comment]
It's great idea and save time but I think TablePlus can't select file without permission of user.

TablePlus is following [Apple Sandbox](https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html) to protect users.

In Sandbox mode, TablePlus can only read/write file which was selected by user. That's mean we can not select ssh-key by default.

I think, it's not a big deal 😁

**Comment by hariesnurikhwan** [comment]
I see, yeah it's not really a big deal.

Anyway so apps like Sequel Pro is not following Apple Sandbox?

**Comment by huyphams** [comment]
yeah, they don't. I think because they are open source. They still using open-ssh and many old stuff. You can read more about it in my medium: 
https://medium.com/@huyphams/how-using-ssh-tunneling-in-database-tools-might-leak-your-connection-forever-c6d48ff18746
