### ISSUE TITLE
Column filter should still apply after reload and selecting another row

### ISSUE THREAD

**Issue by mneuhaus** [TablePlus/TablePlus#200]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
All Driver

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
85

3. The steps to reproduce this issue:

- apply a filter to the column view
- select another row or reload

expected output: the columns should still be filtered
actual output: all columns are displayed again.

![](http://g.recordit.co/FPJ2JOw526.gif)

**Comment by huyphams** [comment]
Thank you for letting me know, I'm fixing it 👍
