### ISSUE TITLE
No tables show for postgres on new macos update 10.15.6

### ISSUE THREAD

**Issue by d903xb** [TablePlus/TablePlus#2005]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgresSQL 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.6.2 (322)

3. The steps to reproduce this issue: Loading table plus, launching a postgressql connection and trying to list tables.No tables show. Although you can click sql and run sql fine with results displayed for manual sql queries with the same connection.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @d903xb did you hide the left sidebar?
<img width="1362" alt="abc" src="https://user-images.githubusercontent.com/3654622/87865524-c547f880-c9a0-11ea-9268-8b4f8b73c9e2.png">

**Comment by d903xb** [comment]
Hi there,

After the upgrade it inactivated the bar - so I thought something was wrong!

Activated it again and no issues.

Thanks for the fast reply!

Thanks
Steve

**Comment by huyphams** [comment]
Thanks for confirming!

**Comment by d903xb** [comment]
Ps loved the product !
