### ISSUE TITLE
Feature Request: IAM authentication to AWS RDS Aurora (PostgreSQL)

### ISSUE THREAD

**Issue by kinghuang** [TablePlus/TablePlus#2007]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL. Not sure how to find driver version.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.7.0 (329)

3. The steps to reproduce this issue:

I have AWS RDS Aurora (PostgreSQL) clusters with IAM authentication enabled. With an IAM user, I can connect to databases by generating tokens to use as the password. It would be nice if TablePlus could make the API calls on my behalf to generate password tokens when connecting to an RDS Aurora database.

This is similar to #1844.

Docs: [Connecting to Your DB Instance Using IAM Authentication](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html)

**Comment by mrnonz** [comment]
Yep, Its will be a nice feature. 

Can't wait!

**Comment by bondezbond** [comment]
This definitely is a feature I've been missing with TablePlus

**Comment by huyphams** [comment]
We're adding it, I will send a test build asap,
![CleanShot 2022-09-23 at 11 37 46@2x](https://user-images.githubusercontent.com/3654622/191893000-1ca44fe0-211a-4023-9b39-f0886199bdb4.png)

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're seeing any issue.

**Comment by codezninja** [comment]
> Hi, if you have a chance, please try this patch: [dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0](https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0) Please let me know if you're seeing any issue.

is this coming out in an official release?

**Comment by huyphams** [comment]
Yup, we're going to release a new update next month.

**Comment by umutuzgur** [comment]
Hey @huyphams, will it be possible to set an AWS profile? We have a different AWS account for each environment and DBs. This would be perfect for us and I think it is a quite common setup as well.

**Comment by huyphams** [comment]
I think you can set it up via the command line easily, isn't it?

**Comment by codezninja** [comment]
> Hey @huyphams, will it be possible to set an AWS profile? We have a different AWS account for each environment and DBs. This would be perfect for us and I think it is a quite common setup as well.

Since this basically a pass through to command line you can basically set the value to be `aws --profile {profileName} rds generate-db-auth-token --hostname {db or cluster endpoint} --port 3306 --username {db username} `

**Comment by AHaymond** [comment]
@huyphams The command line pass through is very useful for connecting via IAM on AWS RDS. 

However something that would really be the icing on the cake for this feature would be setting it up to pass through the user, database, and host so that some "intelligence" could be built in to a script when managing multiple environments each with their own database and unique RDS endpoint. 

This would keep an organization (aka company) limited to only needing users to set the password to the password generating script and the rest would be handled. Otherwise the command has to be unique for each connection, making it more laborious for the end user of the organization.

Could such a thing be possible to add? Do you see any downsides to doing something such as that? Even something as simple as a bash script on the password generating end could grab `$@` and pull apart those three variables in order to generate the requisite AWS command that would output the final connection token.

**Comment by alexw23** [comment]
Built a script for the ProxyCommand that handles most of the issues above, plus also:
- Integrates with AWS-vault
- Uses an idle function to work out if the user is present, if not will skip and return 1
- Finds the AZ of an instance (needed for `ec2-instance-connect`)
- Logs all events and new sessions

## Pre-requisites 

This script assumes you have [aws-vault](https://github.com/99designs/aws-vault) configured already and are [using SSO](https://github.com/99designs/aws-vault/blob/master/USAGE.md#single-sign-on-sso), but totp should also work fine if it's touch based.

Also assumes you've setup an EC2 instance, with firewall access to the RDS database. And have setup EC2 instance connect as required.

## Scripts

**~/.ssh/config**

```sh
Host i-*
    IdentityFile ~/.ssh/id_rsa
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
    ProxyCommand ~/utils/proxy-command --instance-id %h --remote-user %r --port %p --aws-vault-profile prod-admin
```

**~/utils/proxy-command**

```bash
#!/bin/bash

export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin:$PATH

# Default values
identity_file="~/.ssh/id_rsa"
aws_vault_profile=""
port_number=22
instance_id=""
remote_user=""
logfile="$HOME/.ssh/aws-bastion.log"
session_script="$(dirname "$0")/start-session"
idle_seconds=300
trim_log_lines=1000

# Function to display help message
usage() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --instance-id ID           The AWS instance ID."
    echo "  --remote-user USERNAME     The username for the remote instance."
    echo "  --port PORT                The port number for SSH connection (default: 22)."
    echo "  --aws-vault-profile NAME    The AWS Vault profile to use (default: 'production-admin')."
    echo "  --identity-file PATH        Path to the SSH identity file (default: '~/.ssh/id_rsa')."
    echo "  --logfile PATH              Path to the log file (default: 'bastion.log')."
    echo "  --idle-seconds SECONDS     The number of seconds to check for screen idle time (default: 300)."
    echo "  --trim-log LINES           The number of lines to keep in the log file (default: 1000). If set to 0, no trimming is done."
    echo "  --help                     Display this help and exit."
    echo ""
    echo "Example:"
    echo " ProxyCommand $0 --instance-id %h --remote-user %r --port %p --aws-vault-profile production"
}

# Parse long options
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --instance-id) instance_id="$2"; shift ;;
        --remote-user) remote_user="$2"; shift ;;
        --port) port_number="$2"; shift ;;
        --aws-vault-profile) aws_vault_profile="$2"; shift ;;
        --identity-file) identity_file="$2"; shift ;;
        --idle-seconds) idle_seconds="$2"; shift ;;
        --logfile) logfile="$2"; shift ;;
        --help) usage; exit 0 ;;
        --) shift; break ;;
        *) echo "Unknown parameter passed: $1"; usage; exit 1 ;;
    esac
    shift
done

# Initialize an empty string to collect missing parameters
missing_params=""

# Check each parameter and append to the missing_params string if empty
[ -z "$instance_id" ] && missing_params="--instance-id "
[ -z "$remote_user" ] && missing_params+="--remote-user "
[ -z "$aws_vault_profile" ] && missing_params+="--aws-vault-profile "

# Check if any parameters are missing
if [ ! -z "$missing_params" ]; then
    echo "Missing required parameters: $missing_params"
    usage
    exit 1
fi

# set -xe

export BASTION_LOG_FILE="$logfile"

touch "$logfile"

if [ $(wc -l < "$logfile") -gt 1000 ] && [ "$trim_log_lines" -gt 0 ]; then
    echo "Trimming log file to last 1000 lines" >> "$logfile"
    tail -n 1000 "$logfile" > "$logfile.tmp"
    mv "$logfile.tmp" "$logfile"
fi

# Check idle time to determine if the screen is locked
if [ -n "$idle_seconds" ] && [ "$idle_seconds" -gt 0 ]; then
    idle_time=$(ioreg -c IOHIDSystem | awk '/HIDIdleTime/ {print $NF/1000000000; exit}')
    echo "$(date): Proxy command invoked for instance $instance_id and port $port_number with idle time $idle_time seconds" >> "$logfile"

    # Proceed only if the system idle time is less than the specified idle_seconds
    if [ "$(echo "$idle_time > $idle_seconds" | bc)" -eq 1 ]; then
        echo "$(date): The system has been idle for longer than the specified $idle_seconds seconds. Exiting." >> "$logfile"
        exit 1
    fi
else
    echo "$(date): Idle time not set or set to 0, skipping idle time check and proceeding with the session." >> "$logfile"
fi

# Import default path

with-aws-vault() {
    aws-vault exec $aws_vault_profile -- aws "$@"
}

# # Fetch the availability zone of the instance
availability_zone=$(with-aws-vault ec2 describe-instances --instance-ids $instance_id --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' --output text)
echo "$(date): Availability Zone Fetched: $availability_zone" >> "$logfile"

# # Send SSH public key using EC2 Instance Connect
ssh_key_response=$(with-aws-vault ec2-instance-connect send-ssh-public-key --instance-id $instance_id --instance-os-user $remote_user --ssh-public-key "file://${identity_file}.pub" --availability-zone "$availability_zone" --output text)
echo "$(date): SSH Key Response: $ssh_key_response" >> "$logfile"

# # Start an SSH session using SSM
echo "$(date): Starting SSH session to instance $instance_id on port $port_number" >> "$logfile"
with-aws-vault ssm start-session --target $instance_id --document-name AWS-StartSSHSession --parameters "portNumber=$port_number"
```

## Configuration

Then you configure TablePlus as below:
**DB Host:** your RDS host name
**Port:** your RDS port (i.e 3306)

`Over SSH`
**SSH Host:** (your EC2 instance ID i.e i-33jbsb3h4k3)
**User:** ec2-user
**Port:** 22

Welcome any feedback or improvements.

## TODO:
- [ ] Connect to random EC2 instance based on a tag (i.e. bastion), great for load balancing etc.
- [ ] Boot up an EC2 spot instance at entry, and have this instance turn off automatically when no SSH connections are found.
