### ISSUE TITLE
System Error 60 When Trying to Connect to MySQL Over SSH

### ISSUE THREAD

**Issue by alexclst** [TablePlus/TablePlus#2008]
MySQL 5.7.23-23 on Bluehost
TablePlus 3.6.2 build 322 on macOS 10.15.6 build 19G73

When trying to connect to a specific MySQL server via SSH I consistently get the following error:

```
Lost connection to MySQL server at 'waiting for initial communication packet', system error: 60
```

All of my other connections which are also via SSH work just fine. When using the **Test** option it shows that I get through the SSH but fail to authenticate for the database. When connecting it fails at the *Connecting to database...* step. I have tried both `localhost` and `127.0.0.1` as the *Host* and neither works. 

This same server I can go to via SSH in Terminal and connect using the `mysql` cli and it works perfectly. That makes me feel like maybe this is an issue with TablePlus, since essentially the *Over SSH* option for MySQL connections seems to me like it should be doing basically what my Terminal test does.

This is reproducible across two different Macs with TablePlus to this same server. Any ideas what is going on or how to fix this?

**Comment by huyphams** [comment]
Hi @alexclst thank you for letting me know.
I searched the system error 60 and it seems like it was permisson error. Have you tried to use socket instead?

**Comment by alexclst** [comment]
Ok, yeah, I figured it out. Thanks...
