### ISSUE TITLE
[Enhancement | Linux] Filter Database Schemas

### ISSUE THREAD

**Issue by rlcurrall** [TablePlus/TablePlus#2009]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 9.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Linux 62

3. The steps to reproduce this issue:

    1. Connect to a PostgreSQL database
    2. Click Dropdown to select a schema

[Image of issue](https://i.ibb.co/3MntWS7/table-plus-pg-temp.png)

## Description
When connected to a PostgreSQL database, the pg_temp_* and pg_toast_temp_* schemas are shown by default. In databases that are not regularly cleaned up this can become cumbersome to sift through to find the schema you want.

## Enhancement Proposal
We should have a way to filter out schemas for a given database. DataGrip (Jetbrains) has a similar feature where you select the schemas you want to show.

**Comment by huyphams** [comment]
Hi @rlcurrall thank you for the feedback, I just wanna make sure that you are aware of the open anything can do the schema filter for you.
Command + P and type the schema name!

**Comment by rlcurrall** [comment]
Thanks @huyphams for the quick reply! I wasn't aware of it, and that's awesome. Though it seems that it is not implemented yet in the Linux (Alpha) version which is what I'm currently running.

With that being the case, is that feature on the Linux roadmap to be implemented any time soon?

**Comment by huyphams** [comment]
Ah sure @rlcurrall I will add the open anything Command + P in the next update!

**Comment by Akkadius** [comment]
@huyphams trying to not open another issue here. I've given feedback around TablePlus in the past and you've been very helpful

I am now trying to get desktop parity in Linux today after using TablePlus (paid several licenses) for years now and one thing that is already painfully missing is the hotkeys

Command + P / Command + K searching is huge in my workflows, I fly around TablePlus exclusively using hotkeys and this hurts

Is there anyway I can help accelerate or bump getting support for this on Linux ?

<3

**Comment by rlcurrall** [comment]
Not sure if this has been resolved as TablePlus is no longer my daily driver. I'm closing this, if anyone stumbles on this with the same issue they can open a new issue.

**Comment by huyphams** [comment]
We added it long time ago. Thanks.
