### ISSUE TITLE
Show engine innodb status returns empty result

### ISSUE THREAD

**Issue by davidemerritt** [TablePlus/TablePlus#2010]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 322, v 3.6.2

3. The steps to reproduce this issue:
SQL: `SHOW ENGINE INNODB STATUS;` 
returns `type,name,status;Innodb,"", ""` when running this command via commandline (same user) returns full innodb status.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @davidemerritt it's not empty, but the first line is a newline (and Apple Grid View does not show ..., maybe it was a bad UX). If you open it via Quick Look or right sidebar, you will see the status.

<img width="1518" alt="Screen Shot 2020-07-31 at 2 19 24 PM" src="https://user-images.githubusercontent.com/3654622/89010523-f200f600-d338-11ea-8cfc-98a949cf4251.png">

**Comment by davidemerritt** [comment]
Ah thank you, missed that. Closing this.

**Comment by roma2341** [comment]
Same Issue with DbForge ..
