### ISSUE TITLE
Generate diagram issue with MySQL 8

### ISSUE THREAD

**Issue by alejandrozepeda** [TablePlus/TablePlus#2012]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 330

3. The steps to reproduce this issue: Generate a diagram of any table

Noted: If the bug is related to data, please attach an example SQL data.

<img width="814" alt="Screen Shot 2020-07-31 at 15 58 10" src="https://user-images.githubusercontent.com/6829004/89077067-077d1c80-d347-11ea-8da4-192afb1f5418.png">

**Comment by huyphams** [comment]
Hi @alejandrozepeda could you please press Command + L and update the plugin? I've updated it and also added a new feature Create diagram selected items, thank you!

<img width="749" alt="Screen Shot 2020-08-03 at 11 20 53 PM" src="https://user-images.githubusercontent.com/3654622/89204511-6e693280-d5e0-11ea-9f8b-05fa0f1d36dc.png">

**Comment by alejandrozepeda** [comment]
Hi @huyphams I updated tableplus to build 332 version 3.7.1 and having the same issue 

<img width="443" alt="Screen Shot 2020-08-05 at 14 29 00" src="https://user-images.githubusercontent.com/6829004/89455585-2a814500-d728-11ea-8610-0c4c01be9235.png">

**Comment by huyphams** [comment]
Hi @alejandrozepeda, please update the plugin, not TablePlus, You can update the Plugin with Command + L and then click the icon update.

<img width="467" alt="Screen Shot 2020-08-06 at 8 30 19 AM" src="https://user-images.githubusercontent.com/3654622/89480259-14729380-d7bf-11ea-9912-eccac37bdaed.png">

**Comment by alejandrozepeda** [comment]
@huyphams Oh my bad! Now is working, thank you for this amazing feature!

**Comment by huyphams** [comment]
Thank you!
