### ISSUE TITLE
Do you really need to depend on dev libraries on Linux?

### ISSUE THREAD

**Issue by cebas** [TablePlus/TablePlus#2013]
I wanted to test TablePlus on Linux Mint 20 but stopped during install because I saw tableplus depends on the dev version of two libraries, which causes the installation of near 60 more libs. 
Is this dependancy necesary? Do you really need more than 60 packages installed?
Thanks

**Comment by huyphams** [comment]
Hi @cebas TablePlus only use 3 lib on Linux: libgtksourceview-3.0-dev, libgee-0.8-dev, gnome-keyring
and all of them are a standard library, 60 more libs. are probably the dependency of those libs and it depends on the distro.

Our Linux repo here: https://github.com/TablePlus/TablePlus-Linux
Thank you!
