### ISSUE TITLE
MacOS: If two screens are attached, TablePlus starts outside the view

### ISSUE THREAD

**Issue by chinito** [TablePlus/TablePlus#2015]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
multiple

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.7.0(330)

3. The steps to reproduce this issue:
close and quit TablePlus, attach a second screen to the mac, now open TablePlus. You look and won't see it until you realize a small strip on the leftest border of the main screen (the one with the Dock). You're now able to move the window in the middle. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ccakes** [comment]
Mac user here frequently moving between standalone and having a second screen - I've seen this occasionally but maybe 5% of the time I launch the app. Infrequently enough that it always takes a couple of minutes for me to work out what's happened

**Comment by huyphams** [comment]
We leave the window layout for Apple, but it does not work very well. Let me investigate this issue.

**Comment by chinito** [comment]
Just want to give some more info on this issue. Yesterday I started the App, appeared in the middle of the screen ✅ . Rebooted my mac and tried to reproduce. App appeared in the middle of the screen ✅ . Today started my mac with my iMac (2010) as second screen. TablePlus was open but connected to a remote MySQL DB. Connection was lost, closed the window. Opened new, to connect to a local PG DB, Window was far left out of the window ❌

**Comment by codepotato** [comment]
Happens for me too!

**Comment by huyphams** [comment]
Hi guys, if you have a chance, please try this hot patch: https://www.dropbox.com/s/htrc93sqnfs73yj/TablePlus.dmg?dl=0 please let me know if you're still seeing the issue! thanks!

**Comment by chinito** [comment]
Thanks, will do!

**Comment by codepotato** [comment]
@huyphams Just downloading this now and will report back 👍

**Comment by codepotato** [comment]
@huyphams Looks to have solved it for me. Thanks!

**Comment by chinito** [comment]
Looks good to me as well. But I will try it tomorrow again, when in my office and connected to my old iMac. There I experienced the issue yesterday mutliple times. I will feed you back @huyphams

**Comment by chinito** [comment]
Can confirm it works on my iMac as well, great work @huyphams!
