### ISSUE TITLE
Fields in row detail are being painted in red randomly

### ISSUE THREAD

**Issue by jaumesala** [TablePlus/TablePlus#2016]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.7.0 (330)

3. The steps to reproduce this issue:
Clicking in a row, shows values in the row detail sidebar in red. Same row sometimes shows some fields in red sometimes normal. It happens with field types: JSON, String, Integer, etc.

Same row of data:
![Screenshot 2020-08-03 at 09 38 22](https://user-images.githubusercontent.com/385551/89157937-a1261300-d56d-11ea-8082-e4f78da5b54a.png)

![Screenshot 2020-08-03 at 09 38 29](https://user-images.githubusercontent.com/385551/89157941-a3886d00-d56d-11ea-9f08-4d8569eaed6e.png)

**Comment by huyphams** [comment]
Hi @jaumesala thank you for reaching out. I've fixed this issue in this hotpatch, if you have a chance, please try this: https://www.dropbox.com/s/g801eovguzkqvlr/TablePlus.dmg?dl=0

**Comment by jaumesala** [comment]
ok, I'll take a look later on, and let you know!

**Comment by huyphams** [comment]
Hi @jaumesala the new update should resolve this issue, no need to try out the hot patch. Thank you so much!

**Comment by jaumesala** [comment]
Yup! I've just checked it. Problem solved! Great work!
