### ISSUE TITLE
Discarding a modified query works when closing a window, but not when quitting the app

### ISSUE THREAD

**Issue by nazgul** [TablePlus/TablePlus#2017]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.8.0 (333)
But it's been around for at least two or more releases.

3. The steps to reproduce this issue:

This works.

* Open a connect to a database.
* Make sure you don't have auto-save turned on for queries.
* Open a query.
* Modify it.
* Command-W
* Discard

This does not

* Open a connect to a database.
* Make sure you don't have auto-save turned on for queries.
* Open a query.
* Modify it.
* Command-Q
* Discard

You'll get another Discard/Cancel dialog immediately.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by Jailyard90Grad** [comment]
Postgres 9.5 on Mac
Build 367

Same issue:
- Open connection
- Open query
- Run query **with no changes**
- Hit Command-Q to quit program
- A slide down Warning asks if I want to "Discard All Changes" or Cancel.
- Hitting Discard causes that same window dialog to appear. 

The only way to close the query window is to hit Cancel, then Command-W, which brings up a modal window with the same "Discard All Changes?" dialog but proper function.

**Comment by huyphams** [comment]
Hi @nazgul @Jailyard90Grad if you have a chance, please download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 
Please let me know if you are still seeing the issue.
Thanks
