### ISSUE TITLE
Export crash on Mac 

### ISSUE THREAD

**Issue by l41lt0n** [TablePlus/TablePlus#202]
Hi,

I am exporting data from a small SQLITe file and the programm export ok the data but stay opened and freezed. I can not to close it.

![screen shot 2018-01-30 at 1 29 48 pm](https://user-images.githubusercontent.com/32529405/35574749-c7e3d6ea-05c1-11e8-8741-0f76d04074a7.png)

**Comment by huyphams** [comment]
Thanks for letting me now, I'm checking it.

**Comment by l41lt0n** [comment]
Note:
I was trying to edit the structure SQLite before to export the data. ( I am not sure if it can be the reason that it stop to response ). but maybe it can to help.

I am new with this app. I was using other programm to database manager but now I would like to migrate to this one. It looks fantastic!

Thanks.

**Comment by huyphams** [comment]
Hi @l41lt0n could you check this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
I just fixed this issue 😄

**Comment by l41lt0n** [comment]
Wow! so fast. let me try and I will let you know. Thanks

**Comment by l41lt0n** [comment]
@huyphams,
Solved, It works!

Thank you.
