### ISSUE TITLE
Missing feature on Windows: ask for password every time

### ISSUE THREAD

**Issue by tommiv** [TablePlus/TablePlus#2021]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 136 for WIndows

3. The steps to reproduce this issue:
Just try to create a connection

So basically the title says it. In MacOS version you can select "Ask every time" next to the password input. I suppose this will make TablePlus to not store the password anywhere on disk. At least it really asks for a password every time I connect to a DB. However, in Windows version there is no such dropdown. If I leave the password input blank, TablePlus doesn't ask me for a password on connect, it just fails with "fe_sendauth: no password supplied" (which is good because I potentially can configure PG to not ask for a password at all). I'm afraid this is a security concern and this is really a must-have feature in Windows version (I suppose you store passwords encrypted but still I would prefer to not store it at all).

**Comment by huyphams** [comment]
Thanks @tommiv I moved this issue to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/266
