### ISSUE TITLE
TablePlus can't recognize \r\n now?

### ISSUE THREAD

**Issue by kzhui125** [TablePlus/TablePlus#2022]
1. Which driver are you using and version of it 

Microsoft SQL Server 2019 on a Windows machine: use "\r\n" in procedures.

2. Which TablePlus build number are you using (the number on the welcome screen:

332

when I open procedures, there are lots of "?"

<img width="301" alt="截屏2020-08-06 下午10 55 53" src="https://user-images.githubusercontent.com/11925432/89547157-fdbc5300-d837-11ea-8569-0619ac03787e.png">

**Comment by huyphams** [comment]
Hi @kzhui125 it just a render character issue, we've fixed it now. Thank you!

**Comment by kzhui125** [comment]
Thanks
