### ISSUE TITLE
UX enhancements for filter

### ISSUE THREAD

**Issue by olimart** [TablePlus/TablePlus#2023]
- Would be nice to default filter to `id` (automatically) in the dropdown menu or make it configurable
  - Default operator should be set automatically to `=` to avoid extra click for the most common operation

This would prevent a few extra clicks for certainly the most common scenario

**Comment by huyphams** [comment]
Hi @olimart you could do it with the filter setting:
<img width="465" alt="Screen Shot 2020-08-06 at 10 42 18 PM" src="https://user-images.githubusercontent.com/3654622/89552269-22173000-d836-11ea-99ed-b8187e39d560.png">

**Comment by olimart** [comment]
Beauty @huyphams 
I was looking for in the settings. Thanks
