### ISSUE TITLE
Document Db connection problems with Certificate Authority 

### ISSUE THREAD

**Issue by dpclark4** [TablePlus/TablePlus#2024]
Hi,

Is there a way to connect to AWS's DocumentDb? I've been able to connect to mongo in the past, but I am unable to with DocumentDb. I believe this issue relates to the need for a use of a Certificate Authority. I don't see a way to configure this inside TablePlus. I was able to successfully connect using Robo 3T, since that has a particular settings page that allows you to point to the CA. I am using the latest version of TablePlus, build 332. It looks like there was a related issue that was closed earlier this month: https://github.com/TablePlus/TablePlus/issues/1091#issuecomment-502980289. Is there a work around or a solution to this problem?

DocumentDb's connection instructions:
![image](https://user-images.githubusercontent.com/3443935/89572586-4e5f8c00-d7f7-11ea-9495-59a7c207c103.png)
TablePlus error when using the proper connection string (`mongodb://username:insertYourPassword@server:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false`
![image](https://user-images.githubusercontent.com/3443935/89572655-6c2cf100-d7f7-11ea-9257-b98d95a1aa52.png)
T3's settings page that allows you to point to a given CA:
![image](https://user-images.githubusercontent.com/3443935/89572781-9d0d2600-d7f7-11ea-8c6e-ab86d9477a81.png)

**Comment by peterbb148** [comment]
Have same issue.

**Comment by slavouhrin** [comment]
The same here. Although MySQL connection form has this option to provide the SSL key, it is missing for MongoDB.

**Comment by Sledro** [comment]
same issue

**Comment by crqra** [comment]
For anyone still facing this issue, I got through it using the following options:

```
mongodb://<username>:<password>@<host>:<port>/?tsl=true&tlsCAFile=<full path to CA file>&tlsAllowInvalidCertificates=true
```

**Comment by slavouhrin** [comment]
Thanks, but did not help in my case, probably due to an older version of MongoDB which doesn't support the `tls` options

**Comment by huyphams** [comment]
Hi, if you have a chance, please download the hotpatch https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 
It supports custom pem now.
<img width="612" alt="Screen Shot 2022-06-14 at 6 41 25 PM" src="https://user-images.githubusercontent.com/3654622/173569041-eda43dbf-7cfd-4f38-8269-ba26fcb5969b.png">

**Comment by quinyx-tjeerd** [comment]
Using the hot patched version I get:
```
No suitable servers found (`serverSelectionTryOnce` set): [connection error calling hello on '*.eu-central-1.docdb.amazonaws.com:27017']
```
when trying to connect to a AWS documentdb and having selected the correct pem CA

**Comment by egor-xyz** [comment]
Any updates here? Not works for me too

**Comment by jdelaune** [comment]
Still getting the `serverSelectionTryOnce` error from above. Any updates on this issue?

**Comment by cminovici** [comment]
Still... Any updates ? why are we paying the license for ?

**Comment by MichaelCharles** [comment]
I'm also getting this issue when attempting to attempt to a MongoDB compatible AWS DocumentDB instance. 

I've confirmed that I can connect via MongoDB Compass, and so the issue does appear to be with Table Plus as opposed to something to do with the configuration.

**Comment by MichaelCharles** [comment]
> Using the hot patched version I get:
> 
> ```
> No suitable servers found (`serverSelectionTryOnce` set): [connection error calling hello on '*.eu-central-1.docdb.amazonaws.com:27017']
> ```
> 
> when trying to connect to a AWS documentdb and having selected the correct pem CA

And to clarify what I mean when I say, "I'm still getting this issue," I mean that I, too, am getting the "No suitable servers found" message when attempting to connect.

**Comment by mahirpiy** [comment]
getting the same issue here
```
No suitable servers found (`serverSelectionTryOnce` set): [connection error calling hello on
```

**Comment by mikebannan** [comment]
Same. (It's not an AWS documentdb, but this issue appears to cover my situation.) I'm trying to move away from 3T, which connects fine. I'm guessing that it's because we use both a Root CA Cert and a Client Cert for SSL, while TablePlus only provides for the CA Cert, not the Client Cert. I've tried adding the paths to the certs in the connection string, but no joy.

`No suitable servers found (`serverSelectionTryOnce` set): [connection error calling hello on `

**Comment by huyphams** [comment]
Hi @mikebannan I've updated the form and added the CA and Cert file, if you have a chance, please try it and let us know the result
https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
Thank you!

**Comment by mikebannan** [comment]
@huyphams That worked perfectly! Thank you!

**Comment by huyphams** [comment]
You should select the SSL file on the file @Nikohm

**Comment by Nikohm** [comment]
@huyphams still seem to run into the issue with the SSL file selected for certificate key and certificate authority (global-bundle.pem downloaded from AWS) -- confirmed that the connection works otherwise with ssh tunnel and using mongo shell with the same file.

**Comment by Startouf** [comment]
Hello, I'm stuck on this as well. To clarify things, is this what is supposed to work when configuring TablePlus (see screens) ? I'm connecting via SSH proxy and the SSH config is good (green highlighting)

<img width="507" alt="Image" src="https://github.com/user-attachments/assets/da6117ee-f1df-4857-86d8-6a10459d2d71" />

<img width="260" alt="Image" src="https://github.com/user-attachments/assets/439fec76-b3fa-4283-8451-4cf6cb4c14eb" />
