### ISSUE TITLE
Auto-generated `ALTER TABLE` SQL maybe wrong

### ISSUE THREAD

**Issue by pastgift** [TablePlus/TablePlus#2029]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 330

3. The steps to reproduce this issue:
In table structure tab, change column's comment. If the column is using a non-default charset of the table, charset will be changed to default charset.

```sql
-- `ascii` column in `utf8mb4` table
CREATE TABLE `test` (
  `id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Auto-generated SQL which is not expected
ALTER TABLE `text`.`test` CHANGE `id`
`id` varchar(64) NULL COMMENT 'new comment';

-- Correct SQL
ALTER TABLE `test`.`test` CHANGE `id`
`id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT 'new comment';
```

**Comment by huyphams** [comment]
Thanks @pastgift let me check it.

**Comment by huyphams** [comment]
It's fixed and will be released in the next update! thanks.
