### ISSUE TITLE
Back-up of Postgres depends on PostgreSQL version

### ISSUE THREAD

**Issue by mkarnicki** [TablePlus/TablePlus#203]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
TablePlus says: PostgreSQL 9.6

```
$ apt list --installed | grep postgres
postgresql/xenial-updates,xenial-security,now 9.5+173ubuntu0.1 all [installed]
postgresql-9.5/xenial-updates,xenial-security,now 9.5.10-0ubuntu0.16.04 amd64 [installed,automatic]

// in psql
...=# SELECT version();
version
---<snip>
 PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
```

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 85.

3. The steps to reproduce this issue:

 - Select Backup
 - Choose connection
 - Choose backup file name/path
 - The list (?) in the middle is empty.

When I press the 'Backup' button, I see a pop-up with:
```
TablePlus

Please select a databse
```
However, I have no way to do that. Is it because the driver says v9.6 and I'm using 9.5? I can connect to that database with TablePlus no problem. Just the backup part doesn't work. Thanks.

**Comment by huyphams** [comment]
Hi @mkarnicki thanks for your purchased and the feedback, I appreciate it.

TablePlus supports backup by embedded database binaries (backup, restore).

So we have some trouble with this:
- It's not always compatible with user's database (wrong version).
- It increases the binary size.
- It works the same way with PostgreSQL, MySQL when using pg_dump and pg_restore.

So, in the upcoming build. we are going to remove this function to reduce the binary size and provide an alternating function: copy dump and copy restore statement.

A user can copy and run it in the terminal. It always works because they always have the correct version of PostgreSQL (MySQL).

**Comment by mkarnicki** [comment]
Hi Huy, thank you for replying.

I found it very convenient to click Backup/Restore. (TBH the ease of backup, for those databases that I don't necessarily have a back-up schedule set-up, was one of the reasons I considered and eventually purchased the license.)

I have an idea. Let me know what you think about it :)

Since you already make use of SSH, would it be possible for you to simply run pg_dump (or mysqldump) via SSH on the database server and simply download the dump of the file to the client side (and then remove that dump from the server)? Sure, it'd be required to have pg_dump or mysqldump on the server, but that's no biggie if you ask me, you could add that as a requirement for this functionality. Then, you wouldn't have to worry whether the version matches the user's database AND it would still be very convenient to make use of the Backup (and perhaps Restore) buttons.

Just an idea, I'm sure you have a lot of work. TablePlus is shaping up nicely, I'm confident the purchase will be very much worth it. 👍

**Comment by huyphams** [comment]
@mkarnicki we have a plugin system `cmd + L`, probably I should make it as a plugin, so people can download it (with version).
But don't worry, I will not remove this feature until I have done an alternative function.

**Comment by huyphams** [comment]
I fixed the bug in new update 86 please check it out 😄

**Comment by mkarnicki** [comment]
Hi @huyphams , thank you for working on this bug.

I have downloaded the update (and then the version from Dropbox, which supports ~/.ssh/config).

When I press Backup, select host, the list shows up correctly now :).

However, I then select folder location and press backup, I get the following:

<img width="662" alt="screen shot 2018-02-05 at 23 58 19" src="https://user-images.githubusercontent.com/2966794/35833271-c1b940e8-0ad0-11e8-9fa3-e4a25ba32729.png">


Please note that if I double click the host from the main window, it connects properly. What might be the issue then? Is the backup screen using different connection method than the main app screen?

**Comment by huyphams** [comment]
Hi @mkarnicki thanks for the feedback, I will check this issue.
