### ISSUE TITLE
TablePlus occassionally runs all the queries in the SQL Editor when you hit Command Enter

### ISSUE THREAD

**Issue by ramraj07** [TablePlus/TablePlus#2030]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.7 & AWS Redshift

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.6.1 (320) but this bug has been there for a long time now.

3. The steps to reproduce this issue:
While having more than one query in the SQL Editor, and pressing Command + Enter to run the current query, it runs *all* the queries in the editor. We have not noticed any particular pattern that triggers it, though its possible the cursor position at the beginning/end of the query or something is possible. This has happened at least 10 times in the past 6 months, and finally we are deciding whether we should continue using the program or not given how problematic this bug can be at the worst time. Our team has multiple licenses. Appears like the issue was previously raised as well - https://github.com/TablePlus/TablePlus/issues/1485

**Comment by huyphams** [comment]
Hi @ramraj07 I believe it was not a bug and it's related to this issue: https://github.com/TablePlus/TablePlus/issues/1223

**Comment by huyphams** [comment]
Hi, I've added an ability to change the hotkey so it should not be a problem anymore, you can download the hotpatch here: https://www.dropbox.com/s/bskp6rf1julta52/tableplus.dmg?dl=0
You can change the shortcut to an impossible shortcut such as: command + shift + option + return
Please let me know if you're still seeing the issue then we can reopen this
