### ISSUE TITLE
application can't handle large queries

### ISSUE THREAD

**Issue by gallen1** [TablePlus/TablePlus#2032]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgerSQL 8.0.2
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
132
3. The steps to reproduce this issue:
simple table search where rows exceed 1,000,000
As the query begins to complete (currently pulls about 10,000 at a time) memory maxes out and the program is unresponsive. once the query is canceled, memory does not clear and stays maxed until program is re-booted
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by gallen1** [comment]
sorry, build 136

**Comment by huyphams** [comment]
Thanks, let me check it. I moved the issue to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/268
