### ISSUE TITLE
Error while generating diagram

### ISSUE THREAD

**Issue by R00118189** [TablePlus/TablePlus#2033]
error:

Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=SyntaxError: Unexpected identifier 'Initial'. Expected ')' to end an argument list., WKJavaScriptExceptionColumnNumber=0, WKJavaScriptExceptionSourceURL=file:///Users/XXXXX/Library/Application%20Support/com.tinyapp.TablePlus/Plugins/com.tableplus.TablePlus.diagram.tableplusplugin/diagram/index.html, NSLocalizedDescription=A JavaScript exception occurred}

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **MariaDB 10.4.11** 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**333**

3. The steps to reproduce this issue:**Right Click on the table > generate diagram**

Plugin update (2.1) did not solve the problem. Now, dialog window opens, blinks and goes blank/empty even the nav bar is gone

https://imgur.com/a/AGKq0XU

**Comment by R00118189** [comment]
Plugin update (2.1) did not solve the problem. Now new window opens, blinks and is empty even the nav bar is gone

**Comment by dvkndn** [comment]
Thanks for the report. Can you tell me your Mac and/or Safari's version?

**Comment by R00118189** [comment]
Pro (13-inch, 2016, Four Thunderbolt 3 Ports) on 10.13.6 HighSierra
Safari Version 13.1.1 (13609.2.9.1.3)

**Comment by dvkndn** [comment]
Thank you @R00118189 :D I think we found the issue. Let us fix and update with you

**Comment by huyphams** [comment]
Hi @R00118189 please update the plugin to version 2.7. Please let me know if you're still seeing the issue. Thanks!
