### ISSUE TITLE
Update SQLite driver

### ISSUE THREAD

**Issue by adamkiss** [TablePlus/TablePlus#2035]
SQLite driver is from january 2019, and SQLite have had quite a number of improvements since then. Are you planning to upgrade the SQLite and/or add support for the new features (generated columns, filters on aggregate functions, iif function and more)?

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQLite 3.27.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

332

**Comment by chrschmitz** [comment]
Isn't it possible to choose between the internal TablePlus engine and the internal macOS engine? This would allow using the macOS version, which then could be even updated manually. macOS 11 Big Sur is currently on v3.32.3.

**Comment by adamkiss** [comment]
@chrschmitz
1. Catalina is on 3.28.0
2. Not everyone will switch to Big Sur right away

External engine (i.e. managed by `brew`) would work probably better, but some of these new features would probably also need a bit of an UI refresh. I know that out of every sqlite app I've tried, even those with latest driver didn't show e.g. generated columns correctly (= not at all, only in `select *` queries), and it wasn't able to alter table with `add column generated as`.

For now, I'd be happy to be able to open sqlite database with generated columns

**Comment by huyphams** [comment]
Hi guys, I just updated the driver to the version 3.31.0 https://www.dropbox.com/s/jygvwz7epjfaw6h/TablePlus.dmg?dl=0
It supports generated columns now. Thanks!

**Comment by adamkiss** [comment]
@huyphams Out of the curiosity, did you also add any kind of support in UI, or is it just the driver?

**Comment by huyphams** [comment]
I'm still not sure how to get the generated column list in the table structure. The query pragma_table_info("table_name") does not return the generated columns. Do you have any idea?

**Comment by adamkiss** [comment]
@huyphams (note: I've no experience with SQLite internals, this is from putting together something from googling) and then trying it out.

Having a table:

``` SQL
CREATE TABLE "test_generated" (
  "id" INTEGER PRIMARY KEY ASC ON CONFLICT ABORT AUTOINCREMENT,
  "id_double" INTEGER GENERATED ALWAYS AS (id * 2) STORED
);
```

Running `PRAGMA table_info('test_generated')`:
![CleanShot 2020-08-27 at 12 40 02](https://user-images.githubusercontent.com/481362/91432729-73797480-e862-11ea-9c64-7ff3e86a50b6.png)

Running `PRAGMA table_xinfo('test_generated')`:
![CleanShot 2020-08-27 at 12 40 32](https://user-images.githubusercontent.com/481362/91432768-83915400-e862-11ea-8f7a-7f40b9dfa91f.png)

The best way to actually get what's the column generated as seems to be parsing out the table sql
``` sql
select sql from sqlite_master where tbl_name = 'test_generated';
```

```
CREATE TABLE "test_generated" (
"id" INTEGER PRIMARY KEY ASC ON CONFLICT ABORT AUTOINCREMENT,
"id_double" INTEGER GENERATED ALWAYS AS (id * 2) STORED
)
```

**Comment by huyphams** [comment]
Thanks @adamkiss I've used the `table_xinfo`, we will improve it with the `select sql from sqlite_master where tbl_name = 'test_generated';` in the future but it's a different issue.
