### ISSUE TITLE
Settings missing when used via Setapp

### ISSUE THREAD

**Issue by atymic** [TablePlus/TablePlus#2038]
It seems that all of my connections/settings are missing when I launch tableplus through setapp. How can I fix this?

**Comment by huyphams** [comment]
Hi @atymic they are there if you're using the latest release!

**Comment by atymic** [comment]
Yep, on both setapp and non setapp @huyphams 
![image](https://user-images.githubusercontent.com/50683531/90606569-5847ad00-e243-11ea-8b0f-e7dcf587bcef.png)

**Comment by huyphams** [comment]
TablePlus from our website and Setapp are different apps, they have their own bundle ID. So they will have their own data by default.
You can export and then import the connections by right click > export connections.

**Comment by huyphams** [comment]
I thought you mentioned this feature in the first place, but it wasn't.
<img width="710" alt="Screen Shot 2020-08-19 at 2 44 11 PM" src="https://user-images.githubusercontent.com/3654622/90607017-d8154d80-e22a-11ea-9a16-699bbf728f47.png">

The anwser is they're different apps and have their own data dirs.

**Comment by atymic** [comment]
Ahh, Is there any way to figure out where the old dir is? That way I can point setapp to the right dirs (clicking the folder doesn't open the current location).
Thanks

**Comment by huyphams** [comment]
You can di it easily by right click on any history or query and choose open in finder! but I would recommend you to export and then import it.
<img width="336" alt="Screen Shot 2020-08-19 at 2 50 16 PM" src="https://user-images.githubusercontent.com/3654622/90607366-4f4ae180-e22b-11ea-9f14-5616b7b4a044.png">
