### ISSUE TITLE
Search field in main window

### ISSUE THREAD

**Issue by zhitnyakov** [TablePlus/TablePlus#2039]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDb

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
332

3. The steps to reproduce this issue:

- Just launch the app
- Try to find some connection in list of 50 connections
- Decide that you need search field in the top of the connections list

**Comment by huyphams** [comment]
Thanks @zhitnyakov for the suggestion, it was requested before and we will add it in the future update. Just a quick note. TablePlus does support type search, so if you want to quick search on the welcome screen, just type the connection name on the keyboard, it will navigate to the matched result.

**Comment by zhitnyakov** [comment]
> Thanks @zhitnyakov for the suggestion, it was requested before and we will add it in the future update. Just a quick note. TablePlus does support type search, so if you want to quick search on the welcome screen, just type the connection name on the keyboard, it will navigate to the matched result.

Great! Thanks a lot! I will use the method you've mentioned. And I'm sure direct search text field will increase convinience too.

**Comment by bcalik** [comment]
> Thanks @zhitnyakov for the suggestion, it was requested before and we will add it in the future update. Just a quick note. TablePlus does support type search, so if you want to quick search on the welcome screen, just type the connection name on the keyboard, it will navigate to the matched result.

It only works when you don't have Groups. It won't navigate to the matched result if its within a group.

**Comment by huyphams** [comment]
This feature will be included in the next update (Toggle with command + F).
<img width="757" alt="Screen Shot 2020-09-22 at 11 40 06 PM" src="https://user-images.githubusercontent.com/3654622/93911721-f5a76c80-fd2c-11ea-9c39-f4a2ce4ea733.png">
