### ISSUE TITLE
[Feature Request] Prompt for database password when none provided

### ISSUE THREAD

**Issue by mkarnicki** [TablePlus/TablePlus#204]
I store my passwords in [KeeWeb](https://keeweb.info/) password manager. I would prefer not to store my passwords in TablePlus.

When the password field is empty and "No password" is not checked, TablePlus fails with:
`fe_sendauth: no password supplied` (assuming the server required a password).

What I would like to see is a pop-up window with a title such as:
`<connection name here> - Table Plus`
and a prompt for the password (single text field), probably with an OK button for those who like to use a mouse (I don't :) ).

KeeWeb can tell by a window title which account/password it should use. By setting it's auto-type feature to <PASSWORD><ENTER> only, I could do the following:

1. Open TablePlus
2. Double click on a connection (no password provided, "No password" not checked)
3. Press my auto-type shortcut
4. KeeWeb auto-fills the password field and confirms with the Enter key.
5. I'm connected and the password is not stored in TablePlus once I close it.

I love KeeWeb. I don't know most of my passwords, because I don't have to 🎉 . And I like to store them in one, safe place only. I imagine this is low priority, but it shouldn't be hard to implement either.

However note the window title containing a unique connection name and the app title is crucial as otherwise KeeWeb (or other password managers that have similar capability) won't have a way to tell which password it should auto-fill (it's based on regex match). How exactly you format them doesn't matter:

```
foobar production - TablePlus
TablePlus - foobar.com
Password required for foobar staging - TablePlus
```
should all work.

Thank you ❤️

**Comment by nikmolnar** [comment]
+1 For sensitive connections, I would much rather pull the password from a manager rather than store with the connection.

**Comment by huyphams** [comment]
Hi all, I already added this feature in next update. Please try it out here: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by nikmolnar** [comment]
@huyphams Awesome, thanks!

**Comment by huyphams** [comment]
Btw @nikmolnar TablePlus stored all sensitive data in the keychain, it safe if you are the owner of your devices. The feature Prompt for the password is just for people who want to centralize password in one place like OP.
