### ISSUE TITLE
Feature Request: Quick filter on top of table view

### ISSUE THREAD

**Issue by hieuvo** [TablePlus/TablePlus#2040]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.7.1

3. The steps to reproduce this issue:
I've recently switched to TablePlus from Jetbrains DataGrip. TablePluts is much better in term of speed and usability, but 1 feature I miss from DataGrip is: quick filter on top of table view

![DataGrip-Filter](https://blog.jetbrains.com/wp-content/uploads/2020/05/datagrip-Filter.png)

**Comment by huyphams** [comment]
Hi @hieuvo you can press command + F to trigger the filter. Please let me know if you have any questions. Thanks.
<img width="1519" alt="Screen Shot 2020-08-20 at 7 57 26 AM" src="https://user-images.githubusercontent.com/3654622/90704496-d72bfc80-e2ba-11ea-8646-e6b296b49b31.png">

**Comment by hieuvo** [comment]
thanks for quick response @huyphams , 
I checked, but it isn't as quick as I expect. In DataGrip, the search string is treated as if it's where condition and column names autocomplete helps me to type very quickly
