### ISSUE TITLE
"Uglify" removes the last character with every press

### ISSUE THREAD

**Issue by JASGames** [TablePlus/TablePlus#2044]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
Tested on PostgreSQL 10 and SQLite on Windows 10

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
138

**3. The steps to reproduce this issue:**
Write a simple SQL query and then repeatedly click the "Uglify" button or press Control+Shift+I on Windows.
Watch as the last character of you SQL query is repeatedly removed with each press.

**Comment by huyphams** [comment]
Thanks @JASGames , it's fixed now, if you have a chance, please install this hot-patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
