### ISSUE TITLE
Full Screen (Big Sur)

### ISSUE THREAD

**Issue by AbbyJanke** [TablePlus/TablePlus#2046]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v 3.7.1

3. The steps to reproduce this issue:
Install Big Sur

![Screen Shot 2020-08-22 at 9 58 50 PM](https://user-images.githubusercontent.com/487798/90971255-dfef1f00-e4c2-11ea-9d4a-1090fcc468ba.png)

![Screen Shot 2020-08-22 at 10 02 40 PM](https://user-images.githubusercontent.com/487798/90971267-3cead500-e4c3-11ea-95d0-214d5dcc9b23.png)

When using full screen mode and and you go to use the menu bar icons move, but the bar does not.

**Comment by huyphams** [comment]
Hi @AbbyJanke thank you for letting me know. I just fixed this issue, you can download the beta build or this hotpatch: https://www.dropbox.com/s/jygvwz7epjfaw6h/tableplus.dmg?dl=0
Please let us know if you're still seeing the bug.
