### ISSUE TITLE
Small UI issue with top part of the view hidden

### ISSUE THREAD

**Issue by andweeb** [TablePlus/TablePlus#2049]
1. Which driver are you using and version of it: N/A (any)
2. Which TablePlus build number are you using: Build 337
3. The steps to reproduce this issue: Open any tab (editor, table view, etc.)

Looks like the latest build updated some layout offset, causing parts of the view to be hidden behind the top header. You can see in the screenshots below:

<img width="778" alt="Screen Shot 2020-08-24 at 11 45 14 AM" src="https://user-images.githubusercontent.com/10726590/91083518-4711ee00-e5ff-11ea-9ab8-88a3a4921683.png">
<img width="727" alt="Screen Shot 2020-08-24 at 11 46 22 AM" src="https://user-images.githubusercontent.com/10726590/91083616-70cb1500-e5ff-11ea-8199-efaed7656233.png">

**Comment by huyphams** [comment]
Hi @andweeb thank you for letting me know, could you please try this patch and see how it goes: https://www.dropbox.com/s/jygvwz7epjfaw6h/TablePlus.dmg?dl=0

**Comment by andweeb** [comment]
Nice! Yes it looks like that patch has fixed it. Thank you!

**Comment by huyphams** [comment]
Thank you! I've refactored the code and it caused this bug in some situations, sorry about that.
