### ISSUE TITLE
Feature Request: Allow a forceful deletion of Tables ignoring Foreign Key Checks

### ISSUE THREAD

**Issue by mneuhaus** [TablePlus/TablePlus#205]
It would be awesome, if there was an additional Option "Delete ignoring Foreign Key Checks" or "Force Deletion" that would add/set ```SET foreign_key_checks = 0;``` before the delete statements and ```SET foreign_key_checks = 1;``` at the end. This should probably be safeguarded by an additional confirmation popup i guess.

![](https://www.dropbox.com/s/5eo4qtb8nj2holz/Screenshot%202018-02-01%2002.00.25.png?dl=1)

**Comment by huyphams** [comment]
Yup, it should have a dialog with tick option.

**Comment by mneuhaus** [comment]
i just got an alternative way to handle this UX/UI wise. In the Popup that shows the error about the foreign key constraint there could be a red button or checkbox, that could disable the foreign key checks and retry the same query. That way this "forceful" execution could be applied to Deletion of Tables, Rows, Truncating, etc.

https://www.dropbox.com/s/9jsemeqcib5dl3f/Screenshot%202018-02-01%2010.16.50.png?dl=1

**Comment by mneuhaus** [comment]
Since this can be quite dangerous the confirmation could even be something similar to this:

https://www.dropbox.com/s/1pdo4m8ipypjl0c/Screenshot%202018-02-01%2010.28.46.png?dl=0

A textbox where you have to type in "ignore foreign key checks" or "force deletion ignoring foreign key checks"

**Comment by huyphams** [comment]
Thanks for your suggestion 🙌🏻

**Comment by mneuhaus** [comment]
Thank you for being so open to suggestions :)
