### ISSUE TITLE
`Z` coordinates are stripped when displaying PostGIS geometries as text

### ISSUE THREAD

**Issue by brncsk** [TablePlus/TablePlus#2050]
When the "Automatically convert PostGIS data to WKT" option is set, only the X and Y coordinates of PostGIS geometries are shown, even when working with 3D geometries.

**Comment by huyphams** [comment]
Thanks @brncsk I'm working on it.

**Comment by huyphams** [comment]
Hi @brncsk if you have a chance, please try this patch: https://www.dropbox.com/s/95puveiz8teinsh/tableplus.dmg?dl=0
TablePlus now supports multi-dimensional geometry

**Comment by brncsk** [comment]
Hey, @huyphams thanks for the quick fix – I confirm that the patch from Dropbox does solve my problem, 3D geometries are now represented as EWKT in the results view, that includes Z/M coordinates as well.
