### ISSUE TITLE
The window's right side is cutoff when open multiple databases

### ISSUE THREAD

**Issue by coocy** [TablePlus/TablePlus#2052]
1. Which driver are you using and version of it: Mysql 8.0.18
2. Which TablePlus build number are you using: Build 337 under macOS 10.15.6
3. The steps to reproduce this issue:

Open more than one databases in one window, after the left database navigation bar is shown, the window's right side is cutoff.

Before:
<img width="1088" alt="截屏2020-08-25 18 55 58" src="https://user-images.githubusercontent.com/2136111/91166986-c4278b00-e705-11ea-84e6-db4eb6ce5b3c.png">

After:
<img width="1088" alt="截屏2020-08-25 18 56 27" src="https://user-images.githubusercontent.com/2136111/91166997-c984d580-e705-11ea-8023-f5d60cadfa46.png">

**Comment by huyphams** [comment]
Hi @coocy if you have a chance, please download this hot patch and see how it goes: https://www.dropbox.com/s/jygvwz7epjfaw6h/TablePlus.dmg?dl=0
Thank you!

**Comment by coocy** [comment]
> Hi @coocy if you have a chance, please download this hot patch and see how it goes: https://www.dropbox.com/s/jygvwz7epjfaw6h/TablePlus.dmg?dl=0
> Thank you!

It's OK now. Thank you!
