### ISSUE TITLE
PostgreSQL - Changing is_unique Errors

### ISSUE THREAD

**Issue by unlostify** [TablePlus/TablePlus#2054]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 332

3. The steps to reproduce this issue:
- Create new Table with 2 columns (my_column & my_column2)
- Add a default index on the two columns (my_column,my_column2)
- Try to change the is_unique value
- Error shows: column ""my_column"" does not exist
- An extra set of quotations is being added around my_column and my_column2 before running the statement

DROP INDEX "table"."new_idx";

CREATE UNIQUE INDEX "new_idx" ON "schema"."table" USING BTREE ("""my_column""","""my_column2""");

**Comment by huyphams** [comment]
Thanks @unlostify we fixed this issue, it will be included in the next update!
