### ISSUE TITLE
MongoDB: Server at XXX reports wire version 2, but this version of libmongoc requires at least 3 (MongoDB 3.0

### ISSUE THREAD

**Issue by brianpham93** [TablePlus/TablePlus#2055]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Azure MongoDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.7.1(322)
3. The steps to reproduce this issue:
Create new connection to Azure MongoDB
Click on Test
Got error message

```
Server at XXX reports wire version 2, but this version of libmongoc requires at least 3 (MongoDB 3.0)
```
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @brianpham93 TablePlus use libmongc and it seems like it does not support MongoDB 2. We don't have any plan for old mongo at the moment. I'm sorry.
