### ISSUE TITLE
Typo(?) in the update screen

### ISSUE THREAD

**Issue by smile4steve** [TablePlus/TablePlus#2059]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.3.25

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.7.1 (332) 

3. The steps to reproduce this issue:
The Software Update window says: TablePlus 3.0.0 is now available. 
The Release Notes show new build with "Build 336" bu the text is wrong. 
![Screen Shot 2020-08-27 at 5 14 54 PM](https://user-images.githubusercontent.com/8741607/91496212-b995fe80-e889-11ea-96d8-ae0ab201cd5d.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, I've fixed it a few days ago.
