### ISSUE TITLE
Can't set NULL value back with integer or decimal field

### ISSUE THREAD

**Issue by thminhVN** [TablePlus/TablePlus#206]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- PostgreSQL 10.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- Version 1.0 (81)

3. The steps to reproduce this issue:
   1. Create some integer or decimal field
   2. Set random value
   3. Set `null` back to this field

**Comment by huyphams** [comment]
Hi @thminhVN please upgrade to build 85, there is an option in preferences allow TablePlus auto convert empty to null for numeric.

You can also set null by hold option + click on the cell.
