### ISSUE TITLE
[Unexpected Behaviour] Adding a New Column with data_type or column_name set to DEFAULT

### ISSUE THREAD

**Issue by unlostify** [TablePlus/TablePlus#2060]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 12.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 336

3. The steps to reproduce this issue:

- Go to the 'Structure' tab for any table
- Click '+ Column'
- Set a column_name but NOT a data_type (or a data_type but not a column_name)
- Commit your change
- Anything you entered is wiped away from the GUI, but not entered into the database

We understand why you cannot commit this (since both data_type and column_name are critical pieces of information), but it's very annoying to have them destroyed from the GUI as a result.

We expect the commit to fail, but we want to be able to then go back and add our missing data_type or column_name in the GUI, rather than lose everything we had typed and have to retype it from memory.

Notably, the GUI suggests that this should not be a problem since it shows 'DEFAULT' in the data_type cell

**Comment by huyphams** [comment]
Hi @unlostify if you have a chance, please try this patch https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
It should show an error instead of destroying all the invalid data type column
