### ISSUE TITLE
TablePlus freeze when closing mongodb over SSH

### ISSUE THREAD

**Issue by sanarena** [TablePlus/TablePlus#2061]
It freezes entire TablePlus windows for few minutes. Either have to wait really long time (which do not make sense) or force close and open TablePlus again.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mongo 4.0.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.8.0 (336)

3. The steps to reproduce this issue:
Connect to mongodb over SSH
Close the window/tab

**Comment by huyphams** [comment]
Hi @sanarena thanks for the feedback, I just fixed this issue, if you have a chance, please try this hotpatch: https://www.dropbox.com/s/wy9l92h844lcef6/tableplus.dmg?dl=0

**Comment by sanarena** [comment]
that was fast, and it is working as expected now!
