### ISSUE TITLE
Feature request: Separate list for sequences

### ISSUE THREAD

**Issue by Haarolean** [TablePlus/TablePlus#2066]
Currently, there are 3 lists available: recently, functions and tables. Would be nice to have a separate one for sequences.

**Comment by huyphams** [comment]
Please follow https://github.com/TablePlus/TablePlus/issues/1022
We're working on it!

**Comment by Haarolean** [comment]
It's been like 3 years since this has been requested. I'm not willing to renew my license just for that anyway, but thanks :-)

**Comment by huyphams** [comment]
It is supported, however you need to enable it by click the settings button at the bottom left > show sequences
