### ISSUE TITLE
UI Bug - certain UI elements being inaccessible until application restart

### ISSUE THREAD

**Issue by itskemo** [TablePlus/TablePlus#2067]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): POstgreSQL 11 (although this issue is driver irrelevant)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 337 (macOS Catalina .6 update)

3. The steps to reproduce this issue:
- Open TablePlus, connect to any DB defined connection (Lets call it C1)
- selecting any table to see its data results in everything being okay - UI has no problems.
- click "Open Connection" and connect to any other database (Lets call it C2)
- while being in C2 select any table to show its data
- UI becomes cut from the right side.
- switch back to C1 - UI is being cut from the right side again.

<img width="461" alt="Screenshot 2020-09-01 at 11 00 49" src="https://user-images.githubusercontent.com/587959/91830419-0d666600-ec43-11ea-81cb-2b373a27c4b2.png">
<img width="280" alt="Screenshot 2020-09-01 at 11 00 30" src="https://user-images.githubusercontent.com/587959/91830437-11928380-ec43-11ea-9933-6f8945516319.png">
<img width="406" alt="Screenshot 2020-09-01 at 10 59 09" src="https://user-images.githubusercontent.com/587959/91830439-122b1a00-ec43-11ea-9721-f0c72d1aa4d8.png">

**Comment by itskemo** [comment]
Please note that I'm using a purchased license - it allows me to effectively only use ONE connection (as in free version) instead of using multiple connections.

**Comment by huyphams** [comment]
Hi @itskemo please download our official release https://tableplus.com/release/osx/tableplus_latest or update to the latest beta here: https://www.dropbox.com/s/htrc93sqnfs73yj/tableplus.dmg?dl=0 , it would resolve the issue, thank you!

**Comment by itskemo** [comment]
Yep, this worked, thanks @huyphams
