### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by lcsqlpete** [TablePlus/TablePlus#2074]
I just started my free trial of TablePlus and like what I see so far.  Wondering if you have any future plans to:
 
- Allow editing of views without editing the base mySQL code.
- Provide a schema compare feature, preferably with a generated script to make any changes found.

Thanks,

Pete

**Comment by huyphams** [comment]
Hi @lcsqlpete this is our issue tracker so I will close this as it's not an issue.
1. I'm not sure that I understand you correctly, you want to edit the view data or view structure?
2. TablePlus does not support compare SQL code.
Please reply to nick@tableplus.com if you have any further questions. Thank you.
