### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by damiantoczek** [TablePlus/TablePlus#2075]
I'm using ArchLinux and not Debian, is there a plan to maybe use snap or flatpak for TablePlus?
Even if it was paid for Linux, I would buy it. It's a great peace of software.

**Comment by dvkndn** [comment]
Hi @damiantoczek thank you for interesting in the Linux app :D We have an issue tracker for it here: https://github.com/TablePlus/TablePlus-Linux

> I'm using ArchLinux and not Debian, is there a plan to maybe use snap or flatpak for TablePlus?

There are actually many related issues already. You may want to look into them depend on which distro you want:

https://github.com/TablePlus/TablePlus-Linux/issues/1
https://github.com/TablePlus/TablePlus-Linux/issues/3
https://github.com/TablePlus/TablePlus-Linux/issues/7
https://github.com/TablePlus/TablePlus-Linux/issues/17
https://github.com/TablePlus/TablePlus-Linux/issues/21

Afaik there is already a package on AUR that is co-maintained by both TablePlus and the community.

Anyway, I think we should close this issue and continue the discussion (or just subscribe) to one of the corresponding issues above :D
