### ISSUE TITLE
"utf8mb4" is not supported

### ISSUE THREAD

**Issue by marvelph** [TablePlus/TablePlus#2076]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
336

3. The steps to reproduce this issue:

Set the character set of the table or column to “utf8mb4”.

The table "🍣" is displayed as “?" in the table.

Entering the "🍣" character will cause the commit to fail.

**Comment by huyphams** [comment]
Hi @marvelph you can change the view encoding in the menu:
<img width="769" alt="Screen Shot 2020-09-08 at 9 00 48 AM" src="https://user-images.githubusercontent.com/3654622/92425563-cd0e6700-f1b1-11ea-9f33-a9afa04f82f9.png">

**Comment by marvelph** [comment]
Thanks @huyphams !

Please forgive the lack of research in the report.

**Comment by huyphams** [comment]
THanks @marvelph for confirming. Please let me know if you see any issues.
