### ISSUE TITLE
Oracle (19.0.0.0.0) cannot be operated with the current version of TablePlus.

### ISSUE THREAD

**Issue by S-Mocking** [TablePlus/TablePlus#2079]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 19.0.0.0.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 339

3. The steps to reproduce this issue:
Oracle (19.0.0.0.0) cannot be operated with the current version of TablePlus.

Noted: If the bug is related to data, please attach an example SQL data.
![image](https://user-images.githubusercontent.com/37429881/92676042-5ad58800-f353-11ea-8e84-c213b5c82b31.png)

**Comment by S-Mocking** [comment]
Is there any progress?

**Comment by samwise-nl** [comment]
I am able to connect to our Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 server with TablePlus Version 3.10.0 (347)

**Comment by S-Mocking** [comment]
After unremitting efforts, it is found that if the OCI of 19.8 is used, this problem will not exist if the OCI of 18.2 is used, so we can consider changing the OCI version to 18.2.

<img width="699" alt="QQ20201111-210910@2x" src="https://user-images.githubusercontent.com/37429881/98815562-481a2500-2462-11eb-9578-e4ae9e50798e.png">
<img width="728" alt="QQ20201111-210807@2x" src="https://user-images.githubusercontent.com/37429881/98815571-4b151580-2462-11eb-9c7e-8b2a461360e5.png">

**Comment by huyphams** [comment]
fixed with this patch:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
