### ISSUE TITLE
Feature Request: better ellipsis handling for long table names

### ISSUE THREAD

**Issue by mneuhaus** [TablePlus/TablePlus#208]
It would be awesome, if the ellipsis in long table names could be put into the "middle" or 2/3 position instead of the end. Sometimes there are long tablenames that mostly have a different ending, which are currently not easily readable without enlargening the sidebar: 

https://www.dropbox.com/s/31ilb85eia9w921/Screenshot%202018-02-01%2014.21.26.png?dl=0

**Comment by mneuhaus** [comment]
Basically like this: http://i40.tinypic.com/29yqslf.jpg

**Comment by huyphams** [comment]
Hey thanks, it’s called truncate middle
