### ISSUE TITLE
[Suggestion & Request] Remove this limit

### ISSUE THREAD

**Issue by techinfocomp** [TablePlus/TablePlus#2080]
You have applied 2 tab limitation on the free version. 
Can you please increase it to 5 tabs for tables? 

2 tab for the Database is just fine, please increase the number of Tab for tables, it helps us to develop with the help of TablePlus and it help lot's of people to choose TablePlus for there DB related work.

There are some software's in the market which is built fo that same purpose as TablePlus is providing unlimited Tabs for Table. and even for DB also.

**Comment by huyphams** [comment]
Hi @techinfocomp this is our issue tracker, if you have any question, please email the team at nick@tableplus.com Thanks!
