### ISSUE TITLE
[Feature Request] SUPER ANNOYING change you have made

### ISSUE THREAD

**Issue by webdevhayes** [TablePlus/TablePlus#2081]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MYSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.8.0

I love using Tableplus but you not so long ago changed the way the tabs work in the free version. Previously when you clicked on a tab, did would you needed to do, and then the tab would close. Now you have changed it that the tabs always stay open which means when I am constantly making changes to tables I now have to close them everything single time.. 

Either put it back to the way it was where it would be a tab that stays open when only clicked once or have it that if there are no unsaved changes to close the tab once you navigate away from the tab. 

Please try to get this resolved/implemented again. It's just getting to the point where I don't have money to pay for premium and I will possibly look for another free DB manager.

**Comment by huyphams** [comment]
Hi @webdevhayes I didn't change the tab behavior for years (probably from the beginning). If you use the app that much, the best way is to purchase a license and support the team, if you could not afford $60 please kindly email nick@tableplus.com he will help you out with a discount. If you have any questions, please also email the team at nick@tableplus.com
Have a great weekend.

**Comment by webdevhayes** [comment]
> Hi @webdevhayes I haven't changed the tab behavior for years (probably from the beginning). If you use the app that much, the best way is purchasing a license and support the team, if you could not afford $60 please kindly email [nick@tableplus.com](mailto:nick@tableplus.com) he will help you out with a discount. If you have any questions, please also email the team at [nick@tableplus.com](mailto:nick@tableplus.com)
> Have a great weekend.

Hey,

Thanks for the quick reply! 

Interesting I just tried the latest version and it doesn't appear to be having the issue I had. Sorry for wasting your time :(

**Comment by huyphams** [comment]
No worries @webdevhayes and thanks for confirming. If you decided to purchase, please email nick first, we're happy to help.

**Comment by webdevhayes** [comment]
> No worries @webdevhayes and thanks for confirming. If you decided to purchase, please email nick first, we're happy to help.

Hey,

I have figured out that the thing I mentioned above happens only once I have made a data change. Please see the videos attached. The first one shows the default behavior and the second video shows how the behavior changes once I have made a change and saved it. The second video the windows stop closing just because I had made a change. 

FIRST VIDEO
<div style="width:100%;height:0px;position:relative;padding-bottom:60.251%;"><iframe src="https://streamable.com/e/hd3ogt" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

SECOND VIDEO
<div style="width:100%;height:0px;position:relative;padding-bottom:60.251%;"><iframe src="https://streamable.com/e/cnj2nq" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>


Please can you make it so that after a change has been made and saved that the default behavior kicks in again and closes the tab if there are no unsaved changes?

**Comment by huyphams** [comment]
Hi @webdevhayes it's intentional behavior, just like Sublime Text or VScode, TablePlus will pin the tab as soon as you make a change, use filters and it will keep pining until you close it.

**Comment by webdevhayes** [comment]
> Hi @webdevhayes it's intentional behavior, just like Sublime Text or VScode, TablePlus will pin the tab as soon as you make a change, use filters and it will keep pining until you close it.

Hey @huyphams ,

Thanks for getting back to me so promptly. It's great that's intended( not a bug that's a feature ;) ). I appreciate that's intended functionality. Can I make a feature request then? that you add an option to turn that behavior? 

Or make it possible to do it the way phpstorm does it? Personally table plus suits me with two tabs because I don't like a lot of tabs open because things just get cluttered and messy. In php storm I limit the amount open and then they have an option that allows you to decide how the tabs behave. which is that once you set the limit you can select tabs to be closed/overridden based on the options you select in preferences. I have attached an image for your reference.

![Screenshot 2020-09-11 at 12 08 00](https://user-images.githubusercontent.com/101506/92918701-92adff80-f427-11ea-9739-5e88c2e2abc8.png)

As you can see from the screenshot it allows you to decide what to do once a limit has been reached which in this case I have set to 8 tabs and then closed when unchanged and it will select the most recently open tab to be removed.

It would be great if you could do this! please :)

Thanks for your time :)
