### ISSUE TITLE
[Feature Request] BigQuery Support

### ISSUE THREAD

**Issue by shinzui** [TablePlus/TablePlus#2083]
Hi,

Is there a public roadmap for TablePlus? I'm wondering if you're planning to support BigQuery. 

Thank you.

**Comment by ralaruri** [comment]
I would really enjoy BigQuery support eventually! I am used TablePlus for Redshift & MySQL

**Comment by adamf321** [comment]
+1

**Comment by tleung999** [comment]
+1

**Comment by Gui11aum3** [comment]
+1  🙏  I would love to have the simplicity of TablePlus for Big Query

**Comment by linyaru** [comment]
+1

**Comment by leecheeaun** [comment]
+1

**Comment by mcybz** [comment]
Would love to see BigQuery support

**Comment by Endiruslan** [comment]
Really need it!

**Comment by huyphams** [comment]
I'm investigating it!

**Comment by athen66** [comment]
+1 for this!

**Comment by ezraseychelle** [comment]
+1

**Comment by pacificsky** [comment]
+1. Would love Bigquery support. I think this would be a huge driver for TablePlus adoption.

**Comment by jakubsebekbt** [comment]
+1. BigQuery support is the only reason we have to use DBeaver now.

**Comment by S-UP** [comment]
+1

**Comment by var-bolt** [comment]
+1

**Comment by johnpena** [comment]
Any movement on this? What work would be required to get a BigQuery integration working?

**Comment by yassinebelmamoun** [comment]
+1

**Comment by gotwalt** [comment]
👍🏻

**Comment by W0lfEagle** [comment]
+1 Yes please!

**Comment by jayasimhan** [comment]
+1. Pretty please.

**Comment by tim-donandt** [comment]
+1

**Comment by t-chague** [comment]
Big +1 !

**Comment by stanasiukcom** [comment]
+1 x10!

**Comment by fmfiterate** [comment]
Big +1

**Comment by ka6u7ack** [comment]
+1 please!

**Comment by huyphams** [comment]
We're testing BigQuery, it will be included in the next update.

<img width="1407" alt="Screen Shot 2022-06-03 at 10 52 22 AM" src="https://user-images.githubusercontent.com/3654622/171782667-7a8c4261-105d-4609-ab45-9eb40d7a1a88.png">

**Comment by athen66** [comment]
hell ya!

**Comment by ralaruri** [comment]
This is great news! I am so excited!

**Comment by huyphams** [comment]
Anybody want to try it out, the hotpatch is here: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Welcome all feedback!

**Comment by christippett** [comment]
@huyphams, awesome!

Quick bit of feedback for you, TablePlus doesn't seem to like BigQuery's `STRUCT` data type... especially when nested! I'm not sure how you'd go about best displaying this in the app, but I've included a screenshot of how Google do it for what it's worth.

I also noticed BigQuery as a connection option in the iOS app, but it wouldn't accept the JSON key file I provided. I suspect you're still working on it given the title still shows MySQL 😉

<img src="https://user-images.githubusercontent.com/7218120/177216311-09baf636-36e8-4dd5-b55b-36e9d2b9280b.png" width="60%">
<img src="https://user-images.githubusercontent.com/7218120/177216307-d64d1bc3-501f-4c67-99a0-67ff7758a5b1.png" width="60%">
<img src="https://user-images.githubusercontent.com/7218120/177216310-717b9551-3e88-4287-b190-0e27fcd34c2c.png" width="60%">
<img src="https://user-images.githubusercontent.com/7218120/177216312-ddd9a2b3-9281-4cc1-b688-a8cc1583bcb0.jpeg" width="60%">

**Comment by huyphams** [comment]
Hi @christippett if you have a chance, please try this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

Also please try to update TablePlus iOS to the latest release and `re-import the BigQuery JSON` and try again, please let me know if you're still seeing the issue.

**Comment by christippett** [comment]
Haven't had a chance to try the new desktop build, but the latest iOS version connects successfully.

Had this error pop up though. I'm using BigQuery in `europe-west2`, but looks like the US region may be hardcoded in the app?

![image](https://user-images.githubusercontent.com/7218120/177852145-89529266-c173-4212-abdb-e9ff90376eba.jpeg)

**Comment by huyphams** [comment]
I've checked and it is not hardcoded anywhere, could you please double-check the Json Key File?

**Comment by christippett** [comment]
Key file doesn’t specify region. Why’s TablePlus looking for a table called `TablePlus` in my dataset? The region may default to US if it’s not explicitly set, but regardless there’s no table with that name in my dataset.

**Comment by huyphams** [comment]
I found the issue. It's the index query, it is not used on macOS but it is enabled on iOS. We've fixed it. Thank you!

**Comment by christippett** [comment]
Happy to help. Feel free to ping me when you release new builds and want feedback on something BigQuery related.

**Comment by huyphams** [comment]
Did you download the wrong platform @hmoore3 ? 
https://tableplus.com/download

<img width="1231" alt="win" src="https://user-images.githubusercontent.com/3654622/180111216-235c0d5b-b7ef-46dc-9fce-d668f502d565.png">

**Comment by hmoore3** [comment]
I meant for the Bigquery resource, looks like it's there in beta. Thanks!

**Comment by huyphams** [comment]
I don't understand, what is the resource? TablePLus does not need any dependency. Just download and run the app, the BigQuery is beta because we want to keep it in "warning mode" for a while as it is a new driver.

**Comment by desbo** [comment]
Hi, this is a great feature, thank you for your work on it @huyphams!

I'm wondering if it would be possible to use the ["application default credentials"] 
(https://cloud.google.com/docs/authentication/production) or authentication? It seems like this could be a way to avoid the need for users to provide a service account JSON key and instead use their local credentials for access.

**Comment by cwdjankoski** [comment]
Hello - thank you for making this great application, it looks really nice with all the functionality you need and i hope to finally have found a nice and complete bigquery client ⭐

one question though - it seems like auto-completion does not work for bigquery. i can query our tables ok but the query editor window does not react to neither table auto-complete nudges (by entering the starting letters from the table name and pressing <tab>) nor to column names auto-complete nudges (same as for tables). 
is this expected or is it perhaps planned as improvement in the future ?

thanks again and please let me know if i should provide some more information.
