### ISSUE TITLE
Free Trial limited 2 filters

### ISSUE THREAD

**Issue by andyseavers** [TablePlus/TablePlus#2085]
1. Postgres
2. Up to date
3. Using TablePlus with an activated license on computer number 1. Computer is in for repair so I grabbed another computer and pulled a backup from time machine. When pulling up table plus, I open a table that previously has multiple filters and immediately get the "Free Trial limited 2 filters" message. When I click out of that dialog, it immediately pops up again. I can't do anything in the application unless I force close TablePlus. I had to unregister my last computer, reregister this one, and then will have to do the same when I get my other computer back.

**Comment by huyphams** [comment]
Thanks, I just fixed it, @andyseavers TablePlus now will not show multiple alerts.
