### ISSUE TITLE
Cannot connect to MS SQL Server

### ISSUE THREAD

**Issue by zoispag** [TablePlus/TablePlus#209]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`Microsoft SQL Server 2008`
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`Build 85`
3. The steps to reproduce this issue:
`Create a connection and try to connect.`

I get a message: 
Error: NULL DBPROCESS pointer passed to DB-Library 
Message: 

![screen shot 2018-02-02 at 13 46 26](https://user-images.githubusercontent.com/21138205/35733912-7d03e06a-081f-11e8-9f6f-6a846f2c7543.png)

**Comment by huyphams** [comment]
Thanks, @zoispag let me check, seems SQL Server 2008 is not supported.

**Comment by zedentox** [comment]
Same issue here with Microsoft SQL Server 2005 😢 

Is it a bug ? Which versions are supported ?

**Comment by huyphams** [comment]
I'm installing a docker of old SQL Server. I will come back to you guys later.

**Comment by mcdemarco** [comment]
Build 87 failed against Microsoft SQL Server 2008 R2 with this error.  Let me know if you need any testing in the wild.

**Comment by huyphams** [comment]
I'm working on this issue and 
https://github.com/TablePlus/TablePlus/issues/225

**Comment by tomaffirmedit** [comment]
Also cannot connect to an MS SQL server, but have a different error. 

![image](https://user-images.githubusercontent.com/9863203/36250928-47425a70-1237-11e8-940c-9af0ed248cf9.png)

Claims it is a login error but datagrip handles it fine.

**Comment by huyphams** [comment]
Hi @tomaffirmedit , this error mean you should include domain in user field. for example

huy@domain name.

I'm not sure how DataGrip handle this case (probably they add it automatically). but TablePlus respects user input.

**Comment by huyphams** [comment]
Hey @zoispag and @zedentox could you try this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
And let me know the error message, thank you so much. (you can resize the error popup to see the message).

**Comment by zoispag** [comment]
Hey @huyphams 
It looks the same to me:

<img width="475" alt="screen shot 2018-02-17 at 13 11 21" src="https://user-images.githubusercontent.com/21138205/36340809-33538a1c-13e4-11e8-883b-1b9aa88d3e09.png">

Build 88

**Comment by zedentox** [comment]
Same message here.

I dont know if it can help but currently I use my database like this : (ASP code)
```ASP
Set Conn = Server.CreateObject("ADODB.Connection")
Conn.Open "Provider=SQLOLEDB;Data Source=my.ip.address.here;Initial Catalog=mycatalog;Trusted_Connection=No;User ID=myuser;Password=mypassword;LANGUAGE=french;Network=mynetwork"
```

Also I use DBeaver on MacOS with this JDBC url : ```jdbc:sqlserver://my.ip.address.here:1433;databaseName=mycatalog```

In driver settings I have :

| | |
| ---- | ---- |
| Driver name | Microsoft Driver |
| Driver type   | Generic              |
| Class name | com.microsoft.sqlserver.jdbc.SQLServerDriver |
| Category | MS SQL Server |
| Description | Microsoft JDBC Driver for SQL Server |

Maybe it's a problem with untrusted connections ?

**Comment by tomaffirmedit** [comment]
@huyphams Thanks this resolved my issue. Maybe a nice thing to add would be a user prompt and ask if they want the domain name added for them, or a more descriptive message. Regardless thanks for making this app it is outstanding.

**Comment by zoispag** [comment]
Hi @huyphams , any news in this maybe?

**Comment by huyphams** [comment]
Hi, @zoispag thanks for reminding me. Recently I tested, all the connection work fine. Maybe it's a problem with untrusted connections as zendentox mentioned above.
 It's very late in my country. So I will need some help from you tomorrow to figure out this bug.

**Comment by zoispag** [comment]
Sure @huyphams ! I will be in the office tomorrow, so it's also a great time to test the actual server I am interested in. Let me know what can I do to help you!
Thank you for your time!

**Comment by zedentox** [comment]
@huyphams Fell free to ask your questions. And good night. 😀

**Comment by huyphams** [comment]
Hey, I'm here, it would be great if you can try this build and let me know if it works: @zedentox @zoispag 
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

I have enabled NTLMv2 in this build.

**Comment by zoispag** [comment]
Ηι @huyphams. No luck with this build either. :(

**Comment by zedentox** [comment]
@huyphams You win !  🤩

Thanks you very much ! Now let's try this new tool 🧐

**Comment by huyphams** [comment]
But it still not working with zoispag, I still have no idea. Hey, @zoispag can you send me the screenshot of connection form (blur the sensitive information, please).

**Comment by zoispag** [comment]
If it worked for @zedentox there is a good possibility I am doing something wrong.
Here 's my connection form

![screen_shot_2018-03-06_at_09_23_57](https://user-images.githubusercontent.com/21138205/37021600-656ce2a2-2120-11e8-95b7-16db757eaf3a.png)

I am using the same host:port:user:pass that I was using on Windows with HeidiSQL if this helps somehow.

Thanks @huyphams

**Comment by huyphams** [comment]
Looks like TablePlus can't reach the server. Probably HeidiSQL uses DNS to resolve the hostname first. Have you tried to enter actually server address?

I believe this bug happened because TablePlus can't understand the `Host`.

**Comment by huyphams** [comment]
Have you tried to remove the SQLEXPRESS, just pure IP?

**Comment by zoispag** [comment]
Just tried (out of curiosity) and Valentina DB works with hostname\SQLEXPRESS
I would really love though if I could use TablePlus for all my db connections 🤓

**Comment by huyphams** [comment]
Update: I have tried with your information and have logged error:

```
Error: Attempt to set unknown LOGINREC field
Error: Server name not found in configuration files
Error: Unknown host machine name (192.168.99.100\HostName:32768)
Error: Unable to connect: Adaptive Server is unavailable or does not exist (192.168.99.100\HostName:32768)
Error: NULL DBPROCESS pointer passed to DB-Library
[INFO] deinit:11: Window TablePlus.PopupWindow Released
Error: NULL DBPROCESS pointer passed to DB-Library
Init TDS
Error: Attempt to set unknown LOGINREC field
Error: Adaptive Server connection failed (192.168.99.100:32768)
Error: NULL DBPROCESS pointer passed to DB-Library
[INFO] deinit:11: Window TablePlus.PopupWindow Released
```

I'm investigating on it.

**Comment by zoispag** [comment]
That's really great! Thanks

**Comment by huyphams** [comment]
I just made a little change in this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
<img width="612" alt="screen shot 2018-03-06 at 6 36 57 pm" src="https://user-images.githubusercontent.com/3654622/37030430-7fcd9d4c-216d-11e8-8e92-a0a696725451.png">

Can you try it? Not sure if it works or not but let's try.

**Comment by zoispag** [comment]
No luck! :(

![screen_shot_2018-03-06_at_13_18_32](https://user-images.githubusercontent.com/21138205/37031968-21bf5866-2141-11e8-8554-bfb931625a8c.png)

**Comment by zoispag** [comment]
We can assume that this is fixed and can be closed now, right? 🤓 🎉 🎉

**Comment by huyphams** [comment]
Yes, please. And full changelogs here: https://github.com/TablePlus/TablePlus/issues/308

**Comment by jornetsimon** [comment]
Hi,
I'm having the same error '_Adaptive Server connection failed_' on **build 104**.
The instance **is** specific.
_Microsoft SQL Server 2008 R2 (SP3) - 10.50.6220.0 (Intel X86)_ 

<img width="584" alt="connection" src="https://user-images.githubusercontent.com/936101/39719460-8a5ad606-5239-11e8-9231-9ad09a797732.png">
<img width="612" alt="error" src="https://user-images.githubusercontent.com/936101/39719466-8cedccb6-5239-11e8-9247-4c334114f59a.png">

Doesn't work neither with instance name nor without (obviously).

**Comment by huyphams** [comment]
Thank @jornetsimon, let me check it.

**Comment by jornetsimon** [comment]
Seems fixed in build 105.
