### ISSUE TITLE
Cmd+Enter when a cell is selected re-runs the query instead of opening the Quick Look Editor

### ISSUE THREAD

**Issue by emilio-notable** [TablePlus/TablePlus#2091]
Driver: PostgreSQL 10.13
TablePlus version: build 340
Steps to reproduce this issue:

1. Go to the SQL view
1. Run a query that returns 1 or more results
1. click any of the returned cells
1. Press cmd+enter to open the Quick Look Editor

Expected: it opens the quick look editor
Actual: it re-runs the query (as if the cursor and focus was on the query editor, instead of on the cell)

Note: this doesn't seem to be a problem with build 320
Note 2: this is not a problem either if I open a table directly (because there is no SQL editor and query to run)

**Comment by huyphams** [comment]
Oh, that's bad. I just checked and it seems it was started at version 336. I fixed it, the next update 342 on it way.
Thank you!

**Comment by huyphams** [comment]
The update 342 should resolve the issue, thanks!

**Comment by emilio-notable** [comment]
thanks @huyphams !!
just downloaded the new version and it works perfectly!
