### ISSUE TITLE
Run All/Run Selected Combo Box choices not enabled.

### ISSUE THREAD

**Issue by matkatmusic** [TablePlus/TablePlus#2092]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
V3.9.1 (342)

3. The steps to reproduce this issue:

The Run All combobox on the SQL view doesn't have 'Run All' and 'Run Selected Queries' enabled, even though the equivalent menu choices under the 'Connection' menu are enabled.
The key commands to run all/run selected still work as expected.

![Screen Shot 2020-09-16 at 6 54 08 PM](https://user-images.githubusercontent.com/2929847/93410564-0b5cf380-f84e-11ea-9d3e-2a2887f261f8.png)

**Comment by huyphams** [comment]
Hi @matkatmusic I'm sorry for the issue, this hot patch will fix it: https://www.dropbox.com/s/np3k19ue9cfvsay/tableplus.dmg?dl=0
Thanks!
