### ISSUE TITLE
[Feature Request] Shortcut to switch between "Data" and "Structure" in table inspect mode

### ISSUE THREAD

**Issue by constantinPilsl** [TablePlus/TablePlus#2095]
**Context:** 
- I often work with two tabs, one for the query editor itself and one (or more) with the respective table(s).
- To switch between the query editor tab and the table inspect use "cmd + [" or "cmd + ]".

**What is needed:**
- Helpful would be a shortcut to switch between the "Data" and the "Structure" field of the table inspect mode.

**Comment by huyphams** [comment]
Hi @constantinPilsl  the shortcut is control + command + [ and ]
