### ISSUE TITLE
Show current status while testing connection & specific error message if it fails.

### ISSUE THREAD

**Issue by hariesnurikhwan** [TablePlus/TablePlus#21]
While testing connection it'd be better if there's some status, same status while you're trying to connect to the server.

![image](https://user-images.githubusercontent.com/10152692/28506702-bb0f7002-705f-11e7-951c-23e39de1158c.png)

Currently I wasn't able to connect to my RDS over SSH using TablePlus.
And while testing the connection, I only get red coloured form. I dont know the exact error, which is not very helpful for users

![image](https://user-images.githubusercontent.com/10152692/28506769-29f30cae-7060-11e7-90ee-dbb10f8601eb.png)

Im hoping for something like this is or better (Hopefully better)

![image](https://user-images.githubusercontent.com/10152692/28506793-6c271642-7060-11e7-8f64-2803581516a4.png)

**Comment by huyphams** [comment]
It should be a bug, because when user input wrong username/password, there are two fields should be marked as red color. (not all the fields).
Plain text error is nice. I will add a error label if there are no way better.

**Comment by hariesnurikhwan** [comment]
What about the testing connection status?

Anyway do you need any information to fix the issue?

I'm starting to fall in love with TablePlus 😍

**Comment by huyphams** [comment]
Yeah sure, I will ` the testing connection status` too, don't worry.
Thank you for using TablePlus and love it.
FYI: The next big thing in TablePlus is plugis: it allows user to write plugin in javascript and interact with datababse directly.
Example:
![screen shot 2017-07-24 at 10 30 12 am](https://user-images.githubusercontent.com/3654622/28507189-1b8715e8-705b-11e7-943a-985e2530721c.png)
😁

**Comment by huyphams** [comment]
Hi @hariesnurikhwan I just added new build:
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

in this build, you can see error log popup when connection failed

**Comment by hariesnurikhwan** [comment]
Hi, I just tried the latest build, getting this error.
Im connecting to Amazon RDS over SSH

![image](https://user-images.githubusercontent.com/10152692/29263683-7d440b3a-810c-11e7-8bb0-a02acd8e9376.png)

**Comment by huyphams** [comment]
I will look into to this error, thank you

**Comment by huyphams** [comment]
I just made some change. Can you try this build https://www.dropbox.com/s/m29bcnkerdpxgx1/TablePlus.zip?dl=0

**Comment by hariesnurikhwan** [comment]
Nice huyphams!
The latest build fix the issue!
