### ISSUE TITLE
Unable to login with Windows Domain Account to SQL Server.

### ISSUE THREAD

**Issue by davidhooey** [TablePlus/TablePlus#210]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 85

3. The steps to reproduce this issue: Enter Domain account and password during connection.

For example the domain name can be passed in during a JDBC connection.

```
jdbc:jtds:sqlserver://[servername]:[port];domain=[domainname];databaseName=[databasename]
```

**Comment by huyphams** [comment]
Hey, @davidhooey thanks, I have read the documents of MSSQL again and understood, I will fix it in next update.

**Comment by huyphams** [comment]
Could you try again with this syntax: domain/user
TablePlus automatically uses a domain login if username contains`/`

**Comment by davidhooey** [comment]
I updated to build 86 and tested and DOMAIN\user works nicely! Thanks!

On Feb 3, 2018, at 1:59 AM, Huy Pham <notifications@github.com> wrote:

Could you try again with this syntax: domain/user
TablePlus automatically uses a domain login if username contains/

**Comment by gkibilov** [comment]
Using version 100 I get below error, I don't see ver 86 in my TablePlus.
Error: Unable to connect: Adaptive Server is unavailable or does not exist (CA02BI-DEVDB01\Dev) 
Message:
