### ISSUE TITLE
Preference to Disable Advance Table Caching

### ISSUE THREAD

**Issue by barnabyritchley** [TablePlus/TablePlus#2102]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
342

3. The steps to reproduce this issue:
Open new connection to Database. We have many databases with a high table count - it takes a long time for table plus to query and cache all the tables from within each DB.  Would be great to have an option in preferences to disable look ahead type table caching so only the DB's are retrieved, and then the table names are retrieved once a DB is selected.

**Comment by huyphams** [comment]
Hi @barnabyritchley here is the full list queries that TablePlus run during collecting database information:

1. SELECT version();
2.  SHOW VARIABLES
3. SELECT table_name as table_name,column_name as column_name,column_type as column_type FROM information_schema.columns WHERE table_schema='katonice'AND data_type='enum';
4. show full tables from `database_name`;
5. SELECT ROUTINE_SCHEMA as function_schema,ROUTINE_NAME as function_name,ROUTINE_DEFINITION as create_statement,ROUTINE_TYPE as function_type FROM information_schema.routines where ROUTINE_SCHEMA='database_name';

I'm not sure which was the problem on the large database set (like your). Could you help me to run those queries and see what is the issue? Or could you tell me more when TablePlus takes a long time to load?

**Comment by barnabyritchley** [comment]
Hi @huyphams this looks to be caused by something else.  It seemed a TP issue, but actually it looks as though the schema results were being cached after the initial TP queries when we were accessing the schema directly. Thanks for your fast reply!
