### ISSUE TITLE
SSH invalid privatekey windows

### ISSUE THREAD

**Issue by marijnhurkens** [TablePlus/TablePlus#2104]
I'm having trouble with connecting to a MySQL database over SSH using TablePlus on Windows. I manually selected the private key and entered the ip address and user to connect with. After trying to connect or testing I get the "invalid private key" message.

- I've verified that the key is correct by manually connecting using Powershell
- The permissions are read-only (don't know if that matters)
- I've tried running TablePlus as administrator
- I've also tried to rename the key to something with an extension (id_rsa -> id_rsa.priv) to ensure this isn't some weird Windows issue.
- I read there should be an option to enable ssh logging, but I can't seem to find this option on the Windows version.

Build: 140
Windows build: 2004

Can someone help me with this issue?

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/302
