### ISSUE TITLE
Lỗi trong Queries khi save 

### ISSUE THREAD

**Issue by demoqb1** [TablePlus/TablePlus#2111]
Khi tiến hành lưu lại những thay đổi trong Queries/Forder/files thỉnh thoảng bị duplicate file !!

**Comment by demoqb1** [comment]
https://prnt.sc/unl4jd

**Comment by huyphams** [comment]
Bạn dùng macOS hay Windows hay iOS?

**Comment by demoqb1** [comment]
mình dùng Windows 10 , trường hợp này chỉ xảy ra khi mình đặt tên file có ký tự "_" thì file sẻ duplicate , khi không đặt thì save bình thường ,Cảm ơn bạn mình rất khóa TablePlus ^^!

**Comment by demoqb1** [comment]
mình dùng Windows 10 , trường hợp này chỉ xảy ra khi mình đặt tên file có ký tự "_" thì file sẻ duplicate , khi không đặt thì save bình thường ,Cảm ơn bạn mình rất khoái TablePlus ^^!

**Comment by son11592** [comment]
Hi @demoqb1, mình đã phát hiện ra lỗi rồi, bản update sẽ được gửi sớm tới bạn. Cám ơn vì đóng góp của bạn :D

**Comment by huyphams** [comment]
Bạn cài bản patch này vào sẽ hết bị nhé: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Btw, github issue tracker cho bản windows ở đây: https://github.com/TablePlus/TablePlus-Windows/issues nhớ trả lời mấy câu hỏi template khi tạo issue nhé, cám ơn bạn.

**Comment by demoqb1** [comment]
@huyphams giúp mình vấn đề này được không, mình muốn copy dữ liệu trong khoảng 3 4 cột có trong 1 bảng nhưng hình như TablePlus không cho phép điều này vì nó mặc định là chọn luôn 1 row hoặc tất cả các row chứ không cho phép chọn theo cột

**Comment by huyphams** [comment]
Ở góc trái bên dưới có nút columns, bạn chọn columns rồi sau đó copy như bình thường

**Comment by demoqb1** [comment]
> Ở góc phải bên dưới có nút columns, bạn chọn columns rồi sau đó copy như bình thường
Nếu mở 1 bảng ra sẻ cho phép chọn columns như vậy ,Nhưng Mình select 1 bảng ra với điều kiện kèm theo thì không có  nút columns 
https://prnt.sc/uv6axa

**Comment by huyphams** [comment]
À vậy thì bạn chịu khó bỏ cái list column lên select, cái kia mình sẽ cân nhắc thêm vào sau

**Comment by demoqb1** [comment]
OK.Cảm ơn bạn

**Comment by demoqb1** [comment]
@huyphams  mình có 1 số vấn đề nữa muốn gửi đến bạn

**Comment by demoqb1** [comment]
@huyphams  mình có một số vấn đề nhỏ nữa muốn gửi đến bạn
-Khi tiến hành save những thay đổi mới ở file thì tất cả Cây thư mục Queries đều mở ra , mình thấy điều này hơi khó chịu cho những bạn tạo nhiều cây thư mục
-Chức năng ctrl + F không hoạt động khi mình nhấn Enter ,phải click chuột vào find next thì mới hoạt động

**Comment by huyphams** [comment]
@son11592 xem nhé cái này bản windows

**Comment by quyhoangs** [comment]
![image](https://user-images.githubusercontent.com/61405350/97255484-530a6e00-1843-11eb-9e26-878b65df3f74.png)
version 146

**Comment by son11592** [comment]
Hi @quyhoangs, 

> Trong version này thì 2 tính năng mở theo tab và Mở trong 1 tab không chạy được!!
Phần mode hiển thị này sẽ được áp dụng trong lần execute query tiếp theo. Hiện mình vừa kiểm tra trên bản 3.10.11 (146) thì vẫn hoạt động bình thường. Nếu như bạn vẫn gặp tình trạng này thì vui lòng cho mình xin vài hình ảnh để giúp mình debug dễ dàng hơn. 

> 1 số lỗi vặt : cửa sổ replace sẻ chui ra ngoài desktop nếu mình mở nó mà không nhấn vào hộp thoại
Phần này bên mình sẽ tối ưu hơn về hộp thoại này trong bản update tiếp theo để hạn chế việc mất focus.

> Mình muốn điều chỉnh để khi chạy truy vấn bấm ctrl + E như SSMS(sql server) thay vì mặc định là ctrl + Enter và Ctrl +Shift+ Enter được không nhỉ
Phiên bản Windows chưa hổ trợ thay đổi Shortcuts. 

Và đây là repo của phiên bản TablePlus macOS, nếu có những issues liên quan đến phiên bản Windows của TablePlus, vui lòng bạn tạo ticket trên repo này `https://github.com/TablePlus/TablePlus-Windows/`. Xin cám ơn

**Comment by quyhoangs** [comment]
![image](https://user-images.githubusercontent.com/61405350/97264129-eb5e1e00-1856-11eb-8343-aee929ec7e71.png)
ví dụ như mình muốn xem 2 bảng này nhưng khi execute  thì nó chỉ show bảng đầu tiên (Mình Ctrl + A -> Run Curent)

**Comment by huyphams** [comment]
Có vẻ như là với SQL Server, thì bọn mình đã gộp lại chung thành 1 transaction (thay vì split into queries như các driver khác). Lý do gộp thành 1 transaction là bởi vì SQL Server hỗ trợ variables, nếu cắt các câu queries thì các biến sẽ bị undefined.
Bạn có thể run từng query và sau đó pin lại để so sánh kết quả.

**Comment by quyhoangs** [comment]
OK,mình cũng đang làm như vậy. Cảm ơn bạn !

**Comment by quyhoangs** [comment]
![image](https://user-images.githubusercontent.com/61405350/97411501-eec6d780-1932-11eb-9dee-010b1aa3008e.png)
Mình vừa thử tính năng restore nhưng không restore được,đồng thời cũng không xổ xuống được mục add option.

**Comment by son11592** [comment]
Hi @quyhoangs, cho mình hỏi bạn đang sử dụng loại database nào vậy? Màn hình Restore che khuất nên mình không thấy được

**Comment by quyhoangs** [comment]
> Hi @quyhoangs, cho mình hỏi bạn đang sử dụng loại database nào vậy? Màn hình Restore che khuất nên mình không thấy được

mình dùng SQL Sever  định dạng .bak

**Comment by son11592** [comment]
Hi @quyhoangs, xin lỗi về sự bất tiện này. Hiện tại, tính năng restore và backup database chưa được hổ trợ đối với SQL Server, mong bạn thông cảm.

**Comment by quyhoangs** [comment]
>hi @son11592 
Trong Version 3.11.1 (148)  -x64 -- mình không còn dùng được trình plugin nữa, không biết bạn đã test chưa

**Comment by son11592** [comment]
Hi @quyhoangs, cho mình hỏi vấn đề của bạn gặp phải là gì? Bạn có thể chia sẻ một số hình ảnh để mình xem được chứ?

**Comment by huyphams** [comment]
Nếu lỗi không liên quan đến issue thì hãy tạo issue mới, đừng comment vào issue cũ.

**Comment by quyhoangs** [comment]
![image](https://user-images.githubusercontent.com/61405350/100691559-8fd60180-33bb-11eb-9020-0c0ce1e95257.png)
sr các bạn nhưng hình như mình đang gặp vấn đề về submid new issue

**Comment by huyphams** [comment]
Bạn phải điền cái title issue vào nó mới cho submit @quyhoangs

**Comment by quyhoangs** [comment]
> Bạn phải điền cái title issue vào nó mới cho submit @quyhoangs
> 
> Bạn submit đúng ở bên Windows repo nhé: https://github.com/TablePlus/TablePlus-Windows/issues

OK, thank bro
