### ISSUE TITLE
MongoDB authentication fails

### ISSUE THREAD

**Issue by stevenrombauts** [TablePlus/TablePlus#2113]
Using only the connection string I am unable to have TablePlus authenticate properly. I keep getting the error "Authentication failed". 

The same connection strings work fine when used to connect from inside our app or via the command line. 

1. Driver: *mongodb*
1. TablePlus build number: *345*
1. The steps to reproduce this issue:

    Try to connect to a MongoDB instance that requires authentication by adding username and password in the connection string: `mongodb://admin:password@127.0.0.1:27017/logs` 

Any idea how to fix this? Thanks!

**Comment by huyphams** [comment]
Hi @stevenrombauts it seems like it was a configuration issue and not a TablePlus issue, please follow the Mongo instruction and see how it goes?
https://docs.mongodb.com/manual/reference/connection-string/

**Comment by stevenrombauts** [comment]
HI @huyphams, thanks for getting back to me. It was a configuration issue indeed, I was authenticating against the wrong auth db!
