### ISSUE TITLE
Selecting an sql_variant column type results in ERROR: Failed to bind column type: 98

### ISSUE THREAD

**Issue by morecommerce** [TablePlus/TablePlus#2117]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Microsoft SQL Server Connection**
`DBVERSION_74`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Version 3.9.1 (342)**

3. The steps to reproduce this issue:

* Issue a select statement for a table that has a column of type `sql_variant`
* Receive the following error
```
Query 1 ERROR: Failed to bind column type: 98
```
Additionally, TablePlus will repeatedly attempt disconnect and reconnect until the query is closed.

<img width="653" alt="Screen Shot 2020-10-02 at 1 03 53 PM" src="https://user-images.githubusercontent.com/50182041/94965326-1e0f3380-04b0-11eb-8989-04651ecb1ce2.png">

![image](https://user-images.githubusercontent.com/50182041/94965368-34b58a80-04b0-11eb-9d2a-7d611d6be4ed.png)

<img width="522" alt="Screen Shot 2020-10-02 at 1 07 49 PM" src="https://user-images.githubusercontent.com/50182041/94965458-629acf00-04b0-11eb-98cb-14a9ee179ca5.png">

**Comment by huyphams** [comment]
Hi @morecommerce let me check this issue, in the meantime, you can use the protocol 70, it should work with the sql_variant

**Comment by huyphams** [comment]
This build also fixes the issue on the protocol 74: https://www.dropbox.com/s/37zkls7jquz8g6o/tableplus.dmg?dl=0
Please let me know if you're still seeing the issue. Thanks.

**Comment by morecommerce** [comment]
I can confirm using protocol 70 on my exiting build works. 👍

I also tried the build you provided, but it does not work using protocol 74. The select statement just results in a generic error message:

```
Query 1 ERROR
```
