### ISSUE TITLE
Application Version Number and DB Version Number

### ISSUE THREAD

**Issue by wayneforrest** [TablePlus/TablePlus#2120]
1. Not applicable

2. 3.9.1 (Build 342) 

3. Make the Application version number and Build number together with the DB Version copyable.

This will save efforts when creating issues/tickets and eliminate typing errors.

**Comment by huyphams** [comment]
I just made the about dialog copyable, thanks for the suggestion.

**Comment by wayneforrest** [comment]
Awesome thanks :-)
