### ISSUE TITLE
Row Estimation for tables, views, etc

### ISSUE THREAD

**Issue by rishabhjha708** [TablePlus/TablePlus#2122]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 9.6.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): v3.3.3 build 120

3. The steps to reproduce this issue:
I wanted to ask how row estimation is done for Postgres as I am getting an estimate of nearly 10^7 in very short time, 
Also for views, does tableplus is actually counting rows by count(*) or again some estimation

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @rishabhjha708 please enable the console (cmd + shift + C), you will see how TablePlus estimate row!

**Comment by rishabhjha708** [comment]
For WIndows user, it would be Ctrl + Shift + C
