### ISSUE TITLE
[Feature request] Ability to set default query row limit

### ISSUE THREAD

**Issue by hugorodgerbrown** [TablePlus/TablePlus#2125]
**Using 3.91 (342) on macOS, querying Postgres, Redshift, SQLite]**

---

By default (on opening a new SQL window), the query row limit is set to "No limit". This catches me out every time, as when I'm using the SQL window I spend 90% of my time trying to understand the shape of the data, for which I only really need a sample of rows. I often start off with a straight `SELECT * FROM ...`, and end up querying a million row table by accident. 

I appreciate this may be just the way I use TablePlus, however it would be great to be able to set a default query row limit in the preferences (with the same options as the row limit in the query pane).

![Screenshot 2020-10-06 at 10 53 13](https://user-images.githubusercontent.com/200944/95186686-26be7d00-07c2-11eb-964f-7a33cebd9db4.png)

**Comment by JohnRomanski** [comment]
Hi @hugorodgerbrown! For me, on 3.10.0 (347) once I set that dropdown once for a connection, the app persists that as a default even after I disconnect from the connection, or quit and restart the app. Are you looking for a default set at a higher level than that, at the app level?

This could be added under the preferences in the `Table Data` block, but if you use connections, it should only affect you once per connection at least.

**Comment by hugorodgerbrown** [comment]
Thanks @JohnRomanski - I don't know why that hadn't occurred to me. I switch between connections quite a bit, so maybe that's why. Thank you.
