### ISSUE TITLE
Feature request: Remember backup options

### ISSUE THREAD

**Issue by satanTime** [TablePlus/TablePlus#2126]
Hi, for mysql I need `--hex-blob` and would like this option to be present in the list of flags or at least being remembered if I add it manually.

**Comment by huyphams** [comment]
Hi @satanTime if you're macOS and on the latest release, it will remember if you add the flag manually. If it didn't work, please let us know the step to reproduce the issues (I just tried and it works).

**Comment by satanTime** [comment]
Hi @huyphams,

thank for the reply.

I'm on 3.9.1 342, let me double check. Perhaps I used several different connections, but all of them are mysql related. I'll be back later today.

**Comment by satanTime** [comment]
yeah - you are right, it's stored per connection. Also works for me.

Sorry for a false call.

**Comment by huyphams** [comment]
FYI: The flags will be tied for each connection! and it won't be shared.

**Comment by satanTime** [comment]
Aha, thanks.

My case was, if you need it.

I made a backup with triggers, and there is a table with POINT field type in the database.
because the backup contains DEFINER I used sublime editor to replace it with an empty line and the editor corrupted binary data of the POINT field.
When I tried to restore a local database with this backup I, expectedly, got an error about unexpected `\0`.

That reminded me about `--hex-blob` flag and I found it's not present in the options list and I had to google its correct value. Would be nice to have it in the list, but still not a must.
