### ISSUE TITLE
Unable to create connection to local SQLite DB in IPad OS v14

### ISSUE THREAD

**Issue by BrainTonic** [TablePlus/TablePlus#2127]
- Before updating to latest IPad OS, I was able to access a SQLite DB that was located on local file system.
- After updating to latest IPad OS, I am not able to connect to mentioned SQLite DB nor create a new connection to any local SQLite DB.

Initial Thoughts:
- Permission issue
 - After opening app for the first time, I'm not seeing any request for access to local file system or any other permission requests.

**Comment by huyphams** [comment]
Move to iOS repo: https://github.com/TablePlus/TablePlus-iOS/issues/5

**Comment by huyphams** [comment]
It's fixed on 3.10.1 thanks @BrainTonic
