### ISSUE TITLE
drop index produces 2 queries instead of 1

### ISSUE THREAD

**Issue by plakhin** [TablePlus/TablePlus#2131]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.10.8 Build 142

3. The steps to reproduce this issue:
create any index, drop index

When dropping and index TablePlus produces 2 queries:
```
-- 2020-10-15 11:39:47.5368
DROP INDEX "public"."campaign_logs_message_campaign_id_index";

-- 2020-10-15 11:39:47.5378
COMMENT ON INDEX "public"."campaign_logs_message_campaign_id_index" IS NULL;
```

Second query raises an error as index is already dropped and transaction is rolled back.

**Comment by huyphams** [comment]
Thank you for letting me know. We fixed it on this patch: https://github.com/TablePlus/TablePlus-Windows/issues
Out of curiosity, where did you find the issue tracker? We link the Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues everywhere (on the app, on supporting page) but people keep posting on this repo, but this repo is only for TablePlus macOS app.

**Comment by plakhin** [comment]
Thanks for response and sorry for posting in wrong repo.
This repo is the 3rd link in google by "tableplus" query, I guess this is the reason. May be you can add the link to windows repo into the issue template, so people will see it while creating an issue.

**Comment by Dragory** [comment]
@huyphams This repository is also linked in the footer of the TablePlus website, under "Community". I wasn't even aware of a separate repository for the Windows app. The repository name here - `TablePlus/TablePlus` - also doesn't indicate that it's platform specific, and neither does the README (but I imagine this is more of a legacy thing, as the app was originally only on macOS). I see now it mentions "macOS" under About on the repository sidebar however.
