### ISSUE TITLE
Very Ugly Crash on Oracle 12c

### ISSUE THREAD

**Issue by rafaelkarstadidas** [TablePlus/TablePlus#2132]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**347**

3. The steps to reproduce this issue:
**Just connects and try to run a query on a view, it crashes immediately.**

Noted: If the bug is related to data, please attach an example SQL data.

[tableplus-crash.log](https://github.com/TablePlus/TablePlus/files/5385807/tableplus-crash.log)

<img width="1920" alt="tableplus-crash" src="https://user-images.githubusercontent.com/44427427/96148526-a0fca900-0f08-11eb-94b1-d22c9cd24160.png">

**Comment by huyphams** [comment]
Hi, TablePlus now support Oracle natively without the need of rosetta 2, which is much better!
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
