### ISSUE TITLE
Don't select groups in Switch Connection

### ISSUE THREAD

**Issue by jamesratcliffe** [TablePlus/TablePlus#2134]
This is a feature/enhancement request:
I like the Switch Connection feature (cmd+shift+K) and how you can type to filter the connections. However, I have my connections in groups, and it always selects the group, not the connection I want to open. Then I have to press down to get the connection I want to open. It would be better if it skipped groups and selected the first matching connection.
Thanks!

**Comment by huyphams** [comment]
We implemented it, please wait for the next update!

**Comment by jamesratcliffe** [comment]
Nice, thanks!
