### ISSUE TITLE
Red dot in some places

### ISSUE THREAD

**Issue by codificandoCodigo** [TablePlus/TablePlus#2135]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
342
3. The steps to reproduce this issue:
Not sure, in some places a red dot appears, this also happen with firefox dark theme so i guest y something related beetween the type of dark and macos.
![imagen](https://user-images.githubusercontent.com/29681415/96296921-740ecb80-0fc6-11eb-80d6-0b5980926907.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's fixed in this hotpatch: https://www.dropbox.com/s/lrayilk3zdximmn/TablePlus.dmg?dl=0 thank you!
