### ISSUE TITLE
Ability to Modify / Remove Keyboard shortcuts

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#214]
Would like to be able to remabe cmd+E to something else if needed Thanks!

**Comment by huyphams** [comment]
Currently, TablePlus support: Command + E or Command + Return (and command + shift + E and command + Shift + Return).
There are preferences allows user change all the shortcut keys but still under development.
<img width="512" alt="screen shot 2018-02-06 at 11 42 12 am" src="https://user-images.githubusercontent.com/3654622/35842115-c8adc952-0b32-11e8-94c1-3629ebf93f18.png">
This preferences, you will be able to change the keys in some next updates.

**Comment by brian-crane** [comment]
@huyphams  I havent visited the Preferences window in a long time... Now that I open it I can see all the new changes you and your team added! Very nice! I love having preferences I can set for my own personal user experience.  

Keep it up Huy!!!!!!

**Comment by huyphams** [comment]
This preference is still under development, the shortcut can be changed this time. I will enable this to allow user customize shortcut keys soon (My plan is in build 88).
