### ISSUE TITLE
Update query files on focus on app or tab

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2140]
I have an sql queries folder and added it inside the app.

<img width="308" alt="CleanShot 2020-10-20 at 14 41 41@2x" src="https://user-images.githubusercontent.com/29014463/96565738-61f09e00-12e2-11eb-82b2-14eeb3917802.png">

When I make edits to sql files from another text editor, save the changes and focus back on TablePlus app, the sql query doesn't get updated.

We need to close the tab and re-open that queries file.

**Comment by samuel-prjphx** [comment]
this feature would be really helpful! especially since tableplus does not allow connection switching within tabs

**Comment by huyphams** [comment]
It's resolved on TablePlus 454. Thanks!
