### ISSUE TITLE
tableplus 3.10.0 stuck in update loop on macOS

### ISSUE THREAD

**Issue by core-code** [TablePlus/TablePlus#2141]
1. update via built-in update check to latest verson

2. use update check: it still offers an update. 

even if you click update 10 times it will offer another update

the issue is that your sparkle appcast claims that build '348' is available while the actual download only contains build '346'

**Comment by robertmryan** [comment]
It's confused about the build number, thinking that I'm using 346 when you can clearly see I'm already using 348:

<img width="992" alt="Screen Shot 2020-10-20 at 4 50 14 PM" src="https://user-images.githubusercontent.com/1530768/96656285-58703180-12f4-11eb-886e-01392bb57ea0.png">

**Comment by huyphams** [comment]
Hi, I'm sorry, we just fixed it, it's the server-side issue.
