### ISSUE TITLE
[bug] Auto switch b/w light and dark mode

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2143]
Which TablePlus build number are you using: 342

![CleanShot 2020-10-21 at 10 29 09@2x](https://user-images.githubusercontent.com/29014463/96675505-a2a2f280-1388-11eb-9b3f-47ed6695c1af.png)

As you can see the time in the image, its morning and the app is still in dark mode even with theme set as auto.

**Comment by BramVanBerkel** [comment]
see: https://github.com/TablePlus/TablePlus/issues/1782
