### ISSUE TITLE
[feature request] Show warning for delete all entries in table

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2148]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 342

3. The steps to reproduce this issue:

Show warning when executing queries like `DELETE FROM users;`

**Use cases**
* Help avoid running this query _(by mistake)_ in production database

**Comment by huyphams** [comment]
Hi @mittalyashu you can enable it by clicking the lock icon on title bar. Thanks!
