### ISSUE TITLE
SQL History now shared between all databses making it harder to find, also search function for query history is not working

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#215]
It used to be if I ran query1, query2 on DB1, and query3, query4 on DB2, the SQL History for DB1 would only show query1, query2.  Now it shows all queries from all databses.  I thought before you segregated query history to their relevant database

**Comment by huyphams** [comment]
Hi @brian-crane thanks, I'm working on this in another issue and you're right, I'm going to split history based on connection.
