### ISSUE TITLE
Cannot Access MariaDB on WSL from Windows Host

### ISSUE THREAD

**Issue by splashsky** [TablePlus/TablePlus#2150]
I'm running WSL (Ubuntu 20.04) on Windows 10, attempting to access my MariaDB 10.3.22 server on WSL from my host OS, however I'm not able to. `localhost` and `127.0.0.1` do not work, regardless of credentials. I get `Can't connect to server on localhost (10061)`, no other errors.

I don't believe I know how to connect to WSL properly. Can anyone point me in the right direction?

**Comment by huyphams** [comment]
Hi @splashsky thank you for reaching out. Yep, it's not the TablePlus issue, please email nick@tableplus.com if you run into any trouble.

Regarding the issue, you could not connect directly to MySQL. MySQL prohibits all connect from out side by default. You must enable the Over SSH (the host and the port is the Ubuntu IP address).
