### ISSUE TITLE
Please add "Save and Connect" button. 

### ISSUE THREAD

**Issue by clarkbremer** [TablePlus/TablePlus#2153]
When I edit a connection, I press "test", and get green - all good!  Of course I want to connect at this point, but if I forget to save first... I lost my edit.  And if I press "save", then I go back to the list of hosts, and have to click it again.  If you had a "Save and connect" button, that would be better.  I have a LOT of connections, so I have to scroll to find the one I just saved.  Thanks!  CB.

**Comment by huyphams** [comment]
Hi @clarkbremer the current connection button is actually Save & Connect
Please let me know if you run into any issue.
