### ISSUE TITLE
[Bug Report] TablePlus automatically sorts tables (SQLite)

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#2157]
1. Which driver are you using and version of it: 3.31.0
2. Which TablePlus build number are you using: 3.10.0 (348)
3. The steps to reproduce this issue:

TablePlus sorts tables even if no sort order is activated. I have an application where the order of the rows is important. Unfortunately, I am not able to check these tables with TablePlus, because these tables are automatically sorted.

I assume that this happens if the first column is an integer. Please disable this feature! Currently, I have to move to other tools.

BTW: It would be great if the sort order (when activated for a table) would be stored between sessions.

**Comment by huyphams** [comment]
I can confirm it was a bug, TablePlus should only sort a table if the table contains the primary key.

**Comment by chrschmitz** [comment]
Maybe you can add the rowid as the very first column (not editable). Would this also help to solve issue #2159 ?

**Comment by chrschmitz** [comment]
This issue seems to be solved. Thank you!
