### ISSUE TITLE
Unable to connect when using self signed certs

### ISSUE THREAD

**Issue by davidolrik** [TablePlus/TablePlus#216]
Trying and failing to connect to MySQL 5.7.19-17 using the cert generated by the package installer.

```
SSL Certificate:
Signature Algorithm: sha256WithRSAEncryption
RSA Key Strength:    2048

Subject:  MySQL_Server_5.7.19-17_Auto_Generated_Server_Certificate
Issuer:   MySQL_Server_5.7.19-17_Auto_Generated_CA_Certificate

Not valid before: Nov  3 00:44:09 2017 GMT
Not valid after:  Nov  1 00:44:09 2027 GMT
```

A `--insecure` option per connection would be nice.

**Comment by davidolrik** [comment]
Adding this would probably also fix #55

**Comment by huyphams** [comment]
Hey thanks, dealing with SSL is always very hard because security is very important. I will go through again try to reproduce the bug. It takes a little bit time but definitely, I can add an option allow self-certification.

**Comment by huyphams** [comment]
@davidolrik have you try to disabled ssl mode?
<img width="495" alt="ssl" src="https://user-images.githubusercontent.com/3654622/35907848-a6c4c8e6-0c21-11e8-944e-023a524026e6.png">

**Comment by davidolrik** [comment]
I have, and it works - but I would prefer not having my database password travling over the net in plaintext.

**Comment by huyphams** [comment]
I have tuned this behavior on this build, not sure if it fixes this issue or not, it would be great if you can test and let me know the result: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Changes:
- Changed connection timeout to 60 seconds.
- Fixed an SSL bug in MySQL.
- Fixed some minor bugs and typo.
