### ISSUE TITLE
[Feature Request] Windows - Add a Shortcut key to create a new database quickly

### ISSUE THREAD

**Issue by Mutahhar** [TablePlus/TablePlus#2161]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`MySQL 5.7.24`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Tableplus `3.10.11 (146)` for **Windows**

### It is a feature request to add a shortcut key to create a new database quickly.

**Comment by amatzen** [comment]
Your Issue is placed in the macOS issue tracker, you should submit the feature request for Windows GUI here: https://github.com/TablePlus/TablePlus-Windows/issues
