### ISSUE TITLE
[Feature Request] Keyboard Shortcut

### ISSUE THREAD

**Issue by Kish-Siva-1** [TablePlus/TablePlus#2164]
Hello,

I would like to request a keyboard shortcut that will put the cursor into the window pane on the right hand side. 

![image](https://user-images.githubusercontent.com/48958855/97622835-1c8c4900-1a25-11eb-87d8-5d48a98b4cfb.png)

That is the section with all of the field names. Also it would be easy if the fields in the pane on the right hand side populated with the field names without the user having to click on a row in the database.

Regards,
Kish

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/175
