### ISSUE TITLE
[feature request] Show Connection Name in Sidebar when no DB selected

### ISSUE THREAD

**Issue by leancode** [TablePlus/TablePlus#2167]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL, Postgres, Redis

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.10.0 (348)

3. The steps to reproduce this issue:
Create a new connection but don't select a database. When you open the connection in the left sidebar you see the DB symbol but no text below. If you select a DB in the connection you get the name of the DB. In case of redis you get "Keyspace" written below it. i suggest to use the name of the Connection instead of leaving it empty or writing "Keyspace".

Why is it better?
If you have multiple connections open they all look the same on the left, either blank or "Keyspace". To find out which one I am in I have to hover for 2-3 seconds over the connection get the popup. This is slow. I would like to be able to visually see immediately where I am at.
![Screenshot 2020-10-30 at 15 52 46](https://user-images.githubusercontent.com/611460/97720462-97f30680-1ac8-11eb-8858-9de96bdd0449.jpg)

**Comment by huyphams** [comment]
You can enable this option!
<img width="404" alt="Screen Shot 2021-08-28 at 11 35 07" src="https://user-images.githubusercontent.com/3654622/131206245-8579b1ad-365e-427d-a524-c2eab2380d03.png">
