### ISSUE TITLE
SQLQuery error

### ISSUE THREAD

**Issue by l41lt0n** [TablePlus/TablePlus#217]
Hi,

I found a small 'bug' when I use the feature to display query "Beautify" it works fine.
but when I do the invert "Uglify" dont respect the SPACE wabout ORDER, BETWEEN, AND

for example

Normal Query:
SELECT * FROM aluno WHERE escola="53012801" ORDER BY turma LIMIT 10

Beautify Query:
SELECT
    *
FROM
    aluno
WHERE
    escola = "53012801"
ORDER BY
    turma
LIMIT 10

Uglify Query
SELECT*FROM aluno WHERE escola="53012801"ORDER BY turma LIMIT 10

Low priority but necessary. ( I am using build 86 )

Thanks.

**Comment by huyphams** [comment]
Hi, @l41lt0n that's an expectation behavior, those spaces are not necessary. When TablePlus uglify SQL Statements, it tries to remove as many as characters possible 😄

**Comment by l41lt0n** [comment]
Hi @huyphams,

I got it!
sorry for false alarm.

Thanks.
