### ISSUE TITLE
[Bug] character_set is reset when changing data_type, column_name or any other structure related field.

### ISSUE THREAD

**Issue by SimonBackx** [TablePlus/TablePlus#2171]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 348

3. The steps to reproduce this issue:

Create a new column. Set data_type to varchar(36), and character_set to "ascii". 
Push the changes. Now the character_set is suddenly reset to the default one, because it wasn't set in the generated query:
```sql
ALTER TABLE `DATABASE`.`TABLE` ADD COLUMN `test` varchar(36) NULL COMMENT '';
```

Correct the mistake by setting it again to character_set = ascii. Now push, it works.

Now, change the data_type, or any other field of this column to something else. E.g. change the name from 'test' to 'test2'. 
Now the data_type is reset back to the default one... Also because the generated query is wrong:
```sql
ALTER TABLE `DATABASE `.`TABLE ` CHANGE `test` `test2` varchar(36) NULL COMMENT '';
```

**Comment by huyphams** [comment]
The newest release should fix this issue. Thanks!
