### ISSUE TITLE
Can't connect with Table Plus to external database (works via Sequel Pro)

### ISSUE THREAD

**Issue by filipvanreeth** [TablePlus/TablePlus#2172]
Hi,

I can connect to an external database with Sequel Pro but the connection fails with Table Plus.

I'm getting this error: "Access denied for user 'ID100619_staging'@'94.227.83.57' (using password: YES)". It seems that Table Plus is using my current IP address instead of using the host url: https://cln.sh/08dhbU.

This is the only connection issue that I have with connecting to any database with Table Plus, or maybe I'm doing something terribly wrong? ;-)

**Comment by huyphams** [comment]
Hi @filipvanreeth are you sure that you can connect directly to that hot with Sequel Pro? MySQL prohibits connection from the outside by default. Furthermore, that IP is your router IP address, and the message was sent from the server, so if TablePlus use the wrong IP it could not connect to the host in the first place.

Please double-check it if you're using SSH tunneling. I can confirm this issue isn't a TablePlus issue.

**Comment by huyphams** [comment]
Hi @filipvanreeth please let me know if you're still seeing the issue via email nick@tableplus.com Thank you!

**Comment by filipvanreeth** [comment]
@huyphams I'm still getting the error. I'm definitely connected via Sequel Pro as you can see: https://cln.sh/vKPc7O. No idea what could be wrong.

**Comment by huyphams** [comment]
Could you show me a screenshot of the Sequel Pro connection form please

**Comment by filipvanreeth** [comment]
Here you are: https://cln.sh/if1ws5 ;-)

**Comment by huyphams** [comment]
Are there any reason why Sequel Pro has 18 Password character but TablePlus only 16?

**Comment by filipvanreeth** [comment]
OMG, indeed. Now it works! ;-)
