### ISSUE TITLE
License limitation per 1 device

### ISSUE THREAD

**Issue by Borkache** [TablePlus/TablePlus#2173]
Hello, I really like this app, I bought it near a year ago. But I have near 2 laptops, a desktop on linux and iMac, so why should I buy the same license 3+ times just to use it everywhere? 
Why the limit is just for 1 device and I have to sign in/ sign out each time, is there a real reason? 
Is it possible to limit per account and number of devices, for ex 3?
I have a JetBrains license for DataGrip and Phpstrom and have not faced any limits like these.
Best wishes

**Comment by huyphams** [comment]
Hi @Borkache this is our issue tracker (for bugs and features), if you have any question regarding the pricing, please contact our support.

Thank you!

**Comment by PVGrad** [comment]
I agreed with @Borkache - it is issue, because this is an obstacle to work from two of your workstations (pc, laptop)

**Comment by jaydorsey** [comment]
I'd also like to see a per-user pricing model (compared to current per-computer)

**Comment by vol0da** [comment]
This was indeed an unpleasant surprise after I tried to activate the license on my laptop (2nd device).
I'm regularly jumping between two devices solely used by me and while I really like TablePlus, the pricing model is making it too expensive.
