### ISSUE TITLE
[Feature Request] Apple Silicon Compatibility (ARM)

### ISSUE THREAD

**Issue by lloydowen** [TablePlus/TablePlus#2180]
With the recent release of Apple Silicon it would be great to have a native version of TablePlus to run on the latest Mac's.

**Comment by huyphams** [comment]
We're working on it and have a private beta already: https://twitter.com/TablePlus/status/1326207746341957633
Please follow our fan page to get update thanks.

**Comment by huyphams** [comment]
Please check it out here: https://twitter.com/TablePlus/status/1327650704295489536 it's released!

**Comment by alexclst** [comment]
While this is released on the website, there is not yet a consistent Universal version via Setapp. I suggest reopening this issue until that is taken care of.

**Comment by ssimek** [comment]
Actually, there was an Apple Silicon version on SetApp a while ago (I think it was build 354, same as what's on the web). Then there were two builds of 3.12.0, the second of which was Intel only (had it in the description as well). There is a new version 3.12.1 (build 357) that is only on SetApp (there is still build 354 on the web as of now), and still Intel only.

Maybe some CI issue?

Also, is there a way to use the version downloaded from the web with SetApp or download a specific build via SetApp? Couldn't find either...

**Comment by huyphams** [comment]
We've reverted the support because many Oracle users requested us to do so, Oracle doesn't support ARM so there is no way to build M1 for Setapp.

On the Website, we have two separate builds for none-Oracle (M1) and Oracle user (intel only), however, we can't do it with the Setapp release.

**Comment by ssimek** [comment]
Sounds like SetApp should implement support for multiple build variants :) I understand and feel with the many poor souls out there sentenced to work with Oracle, but it is also quite likely that a lot of M1 Mac owners would prefer a native build without Oracle support.

**Comment by alexclst** [comment]
Any update on Oracle supporting Apple Silicon such that the Setapp version can be Universal? Alternatively, if that seems to take a while, can you give us Setapp users who don't care about Oracle a way to use the full version from the website without "free" restrictions, like by generating longterm license keys by verifying Setapp subscription or having the app itself check for an active Seetapp subscription on the Mac?

**Comment by majksner** [comment]
I've installed the version from the website for M1 but as soon as first updated came it was back to x86 architecture.

**Comment by huyphams** [comment]
Hi @majksner please disable beta update in the preferences

**Comment by ssimek** [comment]
@huyphams The web download now seems to be an universal app that supports Oracle as well. Is there anything preventing us from having an Universal app on SetApp as well? As time passes, TablePlus (which was one of the first apps to support M1, just for a brief moment for us SetApp users) is actually one of the last apps that still keeps running under Rosetta.

**Comment by alexclst** [comment]
@ssimek that web version is also one build number behind the Setapp version. Which only exacerbates the question to @huyphams: When will us Setapp (and Apple Silicon Mac) users get the Universal build? While Rosetta 2 works fine on my Mac mini, TablePlus is one of just a few apps I use regularly that is not Universal. Please keep us updated on when to expect the Universal build that clearly already exists with Oracle support from Setapp.

**Comment by huyphams** [comment]
@ssimek no the Universal app does not support Oracle. Oracle doesn't have binares for ARM.

**Comment by alexclst** [comment]
@huyphams in that case, can you give us Setapp users who do not need Oracle a way to unlock the website version so it isn't restricted in the free mode?

**Comment by ssimek** [comment]
@huyphams Now I'm completely confused. There is only one Mac download of Table Plus (the Universal app). There is one version on SetApp. Why can't they just be the same? If it's OK for the Web download to say "This build does not support oracle, please download another one", shouldn't the SetApp version do the same?

Btw., have you considered moving the Oracle connector to a separate process? That way, you could run it as Intel even on ASi, with the rest of the app running natively.

**Comment by alexclst** [comment]
@huyphams, I don't use Oracle so truly don't care (that is also why I'd love you to give us a way to have the web version without the free restrictions with our Setapp subscription), but if the Universal build on the website doesn't have it, why does it still list Oracle in the create a new connections window? If this means it does have Oracle, why isn't the Setapp build Universal? Has Oracle given you any idea of when support will come? Have you considered @ssimek's idea, to create a sub-process that allows all main builds to be Universal?

**Comment by ssimek** [comment]
@alexclst that's precisely why I thought the Universal build supports Oracle. You can create and save a connection, but it says something like "you need to download another build" when trying to connect.

**Comment by alexclst** [comment]
@ssimek ah, ok. That is a bit confusing. But I don't use Oracle, so that won't affect me. I do hope that a fully-functional Universal build (that also comes to Setapp) is possible in the (near) future. Until then I'll probably use the "free trial" web version, since it fits 99% of my uses and is noticeably faster on my M1 Mac (which is odd, since most Rosetta 2 apps I don't notice a perceived slowdown at all). If I ever need the other features I can always download the Setapp version, as I've stored my connections in a shared place and authorized both copies on the keychain items.

**Comment by HilbertGilbertson** [comment]
I've also been disappointed to find the Setapp version does not have native M1 support, although I can understand the reasons why, given that Setapp does not appear to support the option of multiple builds at present. For now I shall probably just stick with an older web version that still has native M1 support (I used to run Tableplus retail with a license but let it lapse when I migrated to the Setapp build), and cease using the Setapp version. I still hope some path can be found to enable Setapp subscribers to use the latest M1 build.

**Comment by filmgirl** [comment]
Add me to the list of people who would love an M1 version/option for SetApp. If the issue is that Setapp doesn't allow multiple builds, I'm happy to reach out to some of the folks there that I know if that would be helpful. Thanks for all that you do -- I love the app, I would just love to be able to run it natively (like others, I don't care at all about Oracle support).

**Comment by kobaltz** [comment]
I'm dealing with a large postgresql database. The Apple Silicon version is much faster than running it under Rosetta 2. As a Setapp subscriber, I would love to see a Universal build of TablePlus as well.

**Comment by rddvries** [comment]
I'm on the same boat as @kobaltz, +1 for having no problem with manually downloading the Silicon version as Setapp subscriber.

**Comment by hroland** [comment]
Yess, please ship it on Setapp too :)

**Comment by huyphams** [comment]
Hi guys, we're going to leave Setapp (we're discussing with them) this year. Please use our official release on the website for ARM support.
We're sorry for the inconvenience.
