### ISSUE TITLE
[Feature request] Make it easier to see which changes have been made

### ISSUE THREAD

**Issue by nachocab** [TablePlus/TablePlus#2181]
The current approach to show changes in tables or rows by changing color works well when there are a few elements or you haven't scrolled much, but if you have hundreds of tables or thousands of rows, or if you scrolled away for some reason, it's really hard to see what will be committed when you hit save.

Alternative approaches worth exploring:
- Command to show a text description of changes to be committed (which would include table/row info)
- Commands to navigate the next/previous change to be committed

**Comment by huyphams** [comment]
Hi @nachocab thank for the suggestion, have you tried to press command shift P to see the changelogs?

**Comment by nachocab** [comment]
Ah, so that's what `Preview` does. 😅

That works for now, thank you. I'll close this issue 👍
