### ISSUE TITLE
UI freezing while trying to colorize 40kb json payload in row detail sidebar.

### ISSUE THREAD

**Issue by wix-andriusb** [TablePlus/TablePlus#2183]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
300

3. The steps to reproduce this issue:
query a table which has a text column containing json.
Select a row where the text field containing json has a 41kb payload.

The row appears in the "row detail sidebar", with the text field containing the json data uncolorized.
Then the UI freezes for 2 seconds.
UI unfreezes with the json data colorized.

The colorization could be done in an asynchronous manner.

**Comment by huyphams** [comment]
Hi @wix-andriusb we fixed this issue in the latest release 348
