### ISSUE TITLE
Crash bug on Big Sur

### ISSUE THREAD

**Issue by zotopteam** [TablePlus/TablePlus#2185]
The last time you opened TablePlus, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?

Process:               TablePlus [1182]
Path:                  /Applications/TablePlus.app/Contents/MacOS/TablePlus
Identifier:            com.tinyapp.TablePlus
Version:               3.10.0 (348)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TablePlus [1182]
User ID:               501

Date/Time:             2020-11-15 12:16:23.940 +0800
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12

**Comment by zotopteam** [comment]
When I upgrade to the big sur, to open the tableplus, the tableplus prompts the error when the interface is displayed
Thanks
Please help me, thank you

**Comment by huyphams** [comment]
It has been fixed on the hotpatch build https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Please give it a try, thanks

**Comment by zotopteam** [comment]
Thanks, it's settled
