### ISSUE TITLE
Copying a VIEW CREATE statement results in nothing on the pasteboard

### ISSUE THREAD

**Issue by daytonlowell** [TablePlus/TablePlus#2187]
>1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7

> 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

348

> 3. The steps to reproduce this issue:

Right click on a MySQL view in the "Items" tab on the sidebar and choose `Copy Script As > CREATION`.
The statement won't be on your pasteboard. In fact, nothing will be on your pasteboard. Whatever was on there before will be gone but the view `CREATE` statement won't be there.

I've been able to reproduce this issue on multiple views. They're all MERGE views, so nothing fancy. Copying `DROP` and `TRUNCATE` scripts works as expected.

**Comment by huyphams** [comment]
It's fixed now for MySQL.
