### ISSUE TITLE
Add additional option in Backup database option dropdown

### ISSUE THREAD

**Issue by johnfmorton** [TablePlus/TablePlus#2188]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
Version 3.10.0 (348)

3. The steps to reproduce this issue:
* Choose "Backup..." 
* Select a database to backup
* Click the "Add option..." dropdown menu item.

Under this drop-down list, I would like to have an additional option added for `--no-tablespaces`. Currently, I need to add this manually every time I use this backup command for a set of database servers that I use. Having the option in the drop-down list would be beneficial.

**Comment by huyphams** [comment]
Thanks, we will add it in the next update.
