### ISSUE TITLE
Feature Request: Overview of all Tables in a Database with Rows, Size, etc.

### ISSUE THREAD

**Issue by mneuhaus** [TablePlus/TablePlus#219]
It would be awesome, if you could integrate an "Overview" of all Tables in a Database with the Number of Rows, Size, encoding, etc. Sometimes i need to find big "evil" Tables that clog up and with a View likes that it used to be (in Navicat) quite easy to identify them.

![screenshot 2018-02-07 17 22 58_preview](https://user-images.githubusercontent.com/316605/35927843-fea6c79e-0c2b-11e8-8fda-b164a6f035b4.png)

**Comment by huyphams** [comment]
This is the idea pop up immediately in my mind, but I need to rethink the UI a little bit.

<img width="1196" alt="demo" src="https://user-images.githubusercontent.com/3654622/35928082-de34c9d8-0c5e-11e8-9907-7455fe77c84b.png">

**Comment by mneuhaus** [comment]
take your time with the UI, the Screenshot was just for reference :)

**Comment by mneuhaus** [comment]
![](https://media.giphy.com/media/3o7abA4a0QCXtSxGN2/giphy.gif)

**Comment by mneuhaus** [comment]
No I think that should suffice 🙂
