### ISSUE TITLE
Auto theme does not switch theme automatically.

### ISSUE THREAD

**Issue by xpol** [TablePlus/TablePlus#2193]
Version 3.11.0 (352)
OS: macOS 11.0.1 / macOS 10.15.7

Issue 1: Choose auto theme does not update the theme according to daytime/night.

The steps to reproduce this issue:

1. In daytime select auto color theme in Preference -> Fonts & Colors, the table plus UI become dark, but Light UI is expected.

Issue 2: Auto theme does not shift color theme automatically when it turns into night. 
The steps to reproduce this issue:
1. In night choose auto color theme in Preference -> Fonts & Colors.
2. Wait other applications like Finder/Xcode turn into Light theme, the table Plus UI elements still dark.

**Comment by xpol** [comment]
And when change theme it will trigger tableplus menu.

https://youtu.be/sS6TLzi8-2o

**Comment by huyphams** [comment]
It's duplicated of https://github.com/TablePlus/TablePlus/issues/1782 however, there is a new bug on this issue, it's the AppKit UI bug and I think it's a macOS bug.
