### ISSUE TITLE
Japanese characters are garbled in MS SQL.

### ISSUE THREAD

**Issue by hokita** [TablePlus/TablePlus#2194]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server DBVERSION_74

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.11.0 (352)

3. The steps to reproduce this issue:
After updating to Version 3.11.0 (352), Japanese characters are garbled. It happens only in MSSQL.
![Screen_Shot_2020-11-19_at_9_46_24](https://user-images.githubusercontent.com/19848415/99623395-5cb47980-2a6f-11eb-9010-ce227172c97b.png)

**Comment by huyphams** [comment]
Hi @hokita there is a view encoding at the main menu: Connection > View encoding please try to change it to Unicode and see how it goes

**Comment by hokita** [comment]
I changed the encoding, but it didn't change. If I downgrade to `Version 3.10.0 (348)`, it will be fixed.

![Screen Shot 2020-11-19 at 16 19 20](https://user-images.githubusercontent.com/19848415/99634550-0b62b500-2a84-11eb-8569-65ff58ffeacd.png)

**Comment by huyphams** [comment]
Thanks @hokita I will take a look at it.

**Comment by huyphams** [comment]
Hi @hokita  please try this hot patch and see how it goes: https://tableplus.com/release/osx/tableplus_latest

**Comment by hokita** [comment]
@huyphams It seems have been fixed. Thanks!!

**Comment by huyphams** [comment]
Thank you!
