### ISSUE TITLE
[bug] windows - does not save password of the database connection.

### ISSUE THREAD

**Issue by bientran** [TablePlus/TablePlus#2197]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Ignore
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 148
3. The steps to reproduce this issue:
a. Create a new connection with credential
b. Close app then reopen
c. Right-click to the connection choose "Connect" from the context menu --> Driver Error - fe_sendauth: no password supplied
d. Right-click to the connection choose "Edit" from the context menu --> The password field empty
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Moved to https://github.com/TablePlus/TablePlus-Windows/issues/323
