### ISSUE TITLE
Cannot import Digital Ocean managed database MySQL 8

### ISSUE THREAD

**Issue by jannejava** [TablePlus/TablePlus#2199]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
348

3. The steps to reproduce this issue:

I am using Digital Ocean managed database and MySQL8
https://www.digitalocean.com/docs/databases/mysql/

- Export one database

- Import exported database to another database on the managed database.

This error occurs:

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"announcements" (
  "id" varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  "us' at line 1`

The funny thing is that I am exporting/importing on the same database instance and not between MySQL-versions. I also have MySQL8 installed on my local computer and I cannot import the sql-dump there either.

What can cause this, is there an setting I can change?

Let me now if you want more details!

**Comment by huyphams** [comment]
It could be your digital ocean use double quote instead of the back-tick? maybe we could change the ANSI quote back to backtick and try again.

**Comment by jannejava** [comment]
Thanks for your quick reply!

When you mention it, it seems true. Kind of an mix in the exports.

```sql
DROP TABLE IF EXISTS `announcements`;
CREATE TABLE "announcements" (
  "id" varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  "user_id" bigint unsigned NOT NULL,
  "body" text COLLATE utf8mb4_unicode_ci NOT NULL,
  "action_text" varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  "action_url" text COLLATE utf8mb4_unicode_ci,
  "created_at" timestamp NULL DEFAULT NULL,
  "updated_at" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
```

**Comment by huyphams** [comment]
Yes, but the problem is that those queries were returned by the server and TablePlus didn't reproduce it. Maybe there is some config but currently, TablePlus use all default settings so maybe we should change it on the server-side. it's the ANSI quote.

**Comment by jannejava** [comment]
It must be this setting right? https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes

Why would DO have this setting? Is there an obvious reason?

**Comment by huyphams** [comment]
I'm not sure why DO do this because it's not the MySQL default setup. I rarely see a user change it to double-quote except there is a clear reason. We should ping and ask them.

**Comment by jannejava** [comment]
I'll do that! Thanks for your support. I appreciate it!

**Comment by KarimGeiger** [comment]
Hi @jannejava, I just ran into this same issue with a DO managed database created just a few months ago, so I'm assuming DO is sticking with double quotes for some reason. Did you have a chance to ask them? What was their response, or alternatively, how did you resolve this? I'm a bit scared to change that setting as I don't know the side-effects this may have.

**Comment by huyphams** [comment]
I believe that they want it to compatible with PostgreSQL syntax @KarimGeiger

**Comment by huyphams** [comment]
It like you can write select query which can run on both PostgreSQL and MySQL (I'm talking about the dump, because it is much complex than the daily queries).

By enabling it, the users can write the query with more data source (PostgreSQL, MySQL) with the same syntax.

**Comment by jannejava** [comment]
Most likely, I contacted DO support to ask if there were any downsides. They assured me there weren't. Since I enabled the feature, I haven't noticed any problems.

**Comment by KarimGeiger** [comment]
Thanks! I appreciate the response on an old issue like this!
