### ISSUE TITLE
Postgresql Add new Row: Error statement All changes where reverted

### ISSUE THREAD

**Issue by davidep87** [TablePlus/TablePlus#22]
Adding a new row in a table from TablePlus with manual input show me an alert message with the text:

Error statement 
All changes where reverted

Software is updated and at the latest version

**Comment by huyphams** [comment]
@davidep87 , the statement was failed but the server return empty error message.
It would be great if you can copy me generated SQL Statement in previewer. (Don't forget to rename column if it was private)

**Comment by davidep87** [comment]
INSERT INTO "public"."contestInfos" ("updatedAt", "contestId", "id", "lang", "type", "createdAt")
    VALUES (DEFAULT, DEFAULT, '11', 'de', 'fdsafd', DEFAULT);

i think is a problem related to the camelCase

**Comment by huyphams** [comment]
The bug related `camelCase` was fixed before. If the statement was failed, PostgreSQL should say something but empty.
I saw in the screenshot (on Facebook). You have `contestId` the same with existed row. There are any unique index on this field?

**Comment by davidep87** [comment]
I don't know if this information can be helpfull but all the database structure is created by Sequelize ORM.. as you can see from this screenshot the problem is not related just to one table but to all..
[http://imgur.com/a/F3JFE](image)
If you want i can give you an export of the db structure

**Comment by huyphams** [comment]
I got the bug,
<img width="346" alt="screen_shot_2017-07-29_at_1_18_35_pm" src="https://user-images.githubusercontent.com/3654622/28742683-ca9e9f02-7460-11e7-9864-f8840199ff27.png">

**Comment by huyphams** [comment]
Fixed in new build @davidep87

**Comment by davidep87** [comment]
If the update is in the build 56 i think the bug still persist..
Please check the new screenshots:
[NewScreen](http://imgur.com/a/FhI1x)

**Comment by huyphams** [comment]
Hi @davidep87 
PostgreSQL said that you should not leave `createdAt` is null. If you want to use default, you need to set default value of column first.

**Comment by davidep87** [comment]
As you can see from the screenshot i wrote all the fields but i get always the same error

**Comment by huyphams** [comment]
Thanks @davidep87 I got the bug

**Comment by huyphams** [comment]
Hi @davidep87 
Can you check this build https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
and tell me the result.

**Comment by davidep87** [comment]
BUG IS FIXED !
