### ISSUE TITLE
Feature Request: Add option for default charset und collation in new db wizard

### ISSUE THREAD

**Issue by psycodepath** [TablePlus/TablePlus#220]
It would be awesome to be able to set the charset and collation in the create new db wizard. 
Furthermore a setting to choose your preferred charset + collation would help as well (eg. for MySQL utf8mb4 & utf8mb4_unicode_ci)

**Comment by huyphams** [comment]
This related to https://github.com/TablePlus/TablePlus/issues/218
I'm starting to implement this because it's the most important feature (for MySQL users).

**Comment by neamtua** [comment]
Hello,

Any traction on this? It's quite an important one.

**Comment by huyphams** [comment]
It's added for MySQL, the Oracle should be the other issue! thanks all.

**Comment by muhammadnasr** [comment]
@huyphams can you point me to Oracle issue, I can't find it.

Thanks.

**Comment by hieuhlc** [comment]
@muhammadnasr i think it's this one #713
