### ISSUE TITLE
[Feature Request] Modify table auto increment

### ISSUE THREAD

**Issue by AveZomer** [TablePlus/TablePlus#2200]
Hello, Best TablePlus team.
I need a possibility to modify auto increment for a table in GUI.

**Comment by huyphams** [comment]
Hi @AveZomer please click here to change the auto increment
<img width="1298" alt="Screen Shot 2020-11-25 at 6 51 35 AM" src="https://user-images.githubusercontent.com/3654622/100164565-b17e4700-2eea-11eb-9210-3c01e64d386c.png">

**Comment by mittalyashu** [comment]
@huyphams What is the meaning of "Reset auto increment" button?

If we remove all the rows from a table and reset the count, will it start from the ID as `1`?

**Comment by reanim8ed** [comment]
@huyphams there is no such button on Windows version

![](https://i.imgur.com/zqCGbQ4.png)
