### ISSUE TITLE
[Bug] Japanese character will be disappeared when Beautify

### ISSUE THREAD

**Issue by c0ridrew** [TablePlus/TablePlus#2204]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Mysql 5.7.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.11.0 (352)

3. The steps to reproduce this issue:

example query

```
SELECT
	id AS ユーザーID,
	created_at AS 作成日
FROM
	users
WHERE
	user_id = 1
ORDER BY
	order_date DESC
LIMIT 1;
```

After Beautify

```
SELECT
	id AS ID,
	created_at AS
FROM
	users
WHERE
	user_id = 1
ORDER BY
	order_date DESC
LIMIT 1;
```

All Japanese letters are gone.

I (As a representative of a Japanese citizen) 'd appreciate it if you fix this! thx

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
