### ISSUE TITLE
[wanted shortcut] set to Null

### ISSUE THREAD

**Issue by qqgg231** [TablePlus/TablePlus#2205]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
142

Please allow to set Null value faster than by making a few clicks.

**Comment by DanielHudson** [comment]
I only just figured you can option-click, which is slightly quicker than the right click route. A keyboard shortcut would be 👌

**Comment by qqgg231** [comment]
> I only just figured you can option-click, which is slightly quicker than the right click route. A keyboard shortcut would be 👌

I don't understand. How to do this?

**Comment by DanielHudson** [comment]
I'm not sure on windows, but on Mac you can hold down the 'option' key whilst clicking in the cell. It's a step shorted than just plain right clicking.

**Comment by qqgg231** [comment]
Ok, I can't get it working on Windows.

**Comment by huyphams** [comment]
I've added a shortcut to do this: Option + return it will be released in the next update 360.
