### ISSUE TITLE
Typo in advanced filter settings

### ISSUE THREAD

**Issue by NateJones96** [TablePlus/TablePlus#2206]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.49-cli-lve

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.11.1 (148) - x64

3. The steps to reproduce this issue:
When clicking on the gear icon settings in the Advanced Filter panel, the first option reads "Default fitler column". Notice "fitler" instead of "filter". Just wanted to let you know!

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/326
