### ISSUE TITLE
Feature request: Advanced filter default column 'Any Column'

### ISSUE THREAD

**Issue by NateJones96** [TablePlus/TablePlus#2207]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MySQL 5.6.49-cli-ive

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
Version 3.11.1 (148) - x64

**3. Feature request:**
Right now you can select either Raw SQL or Primary ID as the default column in the Advanced Filter settings, but I'd like to also be able to set the default filter to 'Any Column' so I can quickly search through a whole table without having to select a specific column (since I'm not always just searching by Primary ID).

Thanks, and I appreciate the awesome product! Keep up the great work.

**Comment by huyphams** [comment]
Moved to Windows repo https://github.com/TablePlus/TablePlus-Windows/issues/325 because the macOS has supported this
<img width="506" alt="Screen Shot 2020-11-28 at 7 19 53 AM" src="https://user-images.githubusercontent.com/3654622/100489983-724e3100-314a-11eb-984d-4ac2ca45695c.png">
