### ISSUE TITLE
Feature Request: Option to select columns in order when Importing CSV

### ISSUE THREAD

**Issue by NateJones96** [TablePlus/TablePlus#2208]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MySQL 5.6.49-cli-ive

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
Version 3.11.1 (148) - x64

**3. Feature request:**
When importing data using the Import from CSV feature, often times the header column names in the CSV aren't the same as the ones in the database, so it doesn't automatically detect that and by default sets that column as "Do Not Import". However, it would be nice if there was an option to automatically assign the columns by the order they're in, so for example:

I have 3 columns in my database: **col1**, **col2**, and **col3**.

In my CSV, they might be called: **col1**, **Column Two**, **Column Three**.

So of instead of the import by default mapping only the first col1 because the names match and leaving the others as Do Not Import, it would be nice if it would just match them because they are in the same order and amount of columns. This would be extremely convenient, because right now I have to switch over to Sequel Pro to be able to import data like this (unless I'm missing something and this option already exists in TablePlus). Anyway, thanks for reading!

**Comment by huyphams** [comment]
Thank you for the suggestion. Please use our Windows repo for Windows App: https://github.com/TablePlus/TablePlus-Windows/issues
We've had this feature on macOS already. It's called mapping strategy.
<img width="405" alt="Screen Shot 2020-11-28 at 7 17 34 AM" src="https://user-images.githubusercontent.com/3654622/100489883-cc9ac200-3149-11eb-8255-2582e584dc91.png">

We've ported this to Windows recently, If you want to use the pre-build Windows, you can download it here: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by NateJones96** [comment]
Brilliant! I downloaded the new build and that allows me to import correctly. Thanks for the quick reply, and I'll be sure to use the windows repo to report any other issues or features. Thanks @huyphams !
