### ISSUE TITLE
unreadable white on olive green text

### ISSUE THREAD

**Issue by skibz** [TablePlus/TablePlus#221]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.7.14
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 86
3. The steps to reproduce this issue:
* switch to the dark colour theme
* the text in the header bar will be unreadable
![screen shot 2018-02-09 at 14 23 36](https://user-images.githubusercontent.com/2462211/36027713-0773a8e0-0da5-11e8-8fb3-eddee92616c3.png)

**Comment by huyphams** [comment]
Hi @skibz currently, we can't optimize the color automatically. So you need to click on the title and change the color by hand.

**Comment by skibz** [comment]
thanks!

**Comment by huyphams** [comment]
Let it open @skibz I have an idea to improve it automatically 😄

**Comment by skibz** [comment]
sorry about that, reopening! and thanks again for helping out!

**Comment by huyphams** [comment]
It is improved in the latest beta build 135, so I will close this issue.
