### ISSUE TITLE
Plugin does not working

### ISSUE THREAD

**Issue by quyhoangs** [TablePlus/TablePlus#2211]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Sever 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
 Version 3.11.1 (148) -x64
3. The steps to reproduce this issue:
Menu->Plugins->Plugin Manager 
Ở đây thì mình không còn chọn được các plugin nữa
![image](https://user-images.githubusercontent.com/61405350/100692319-2ce56a00-33bd-11eb-9bb3-1a72d2d46a12.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Please use the Windows repo:
https://github.com/TablePlus/TablePlus-Windows/issues
