### ISSUE TITLE
[bug] comment and sql query getting mixed up on beautify the query

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2217]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 354

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

I am using shortcut key to beautify the query.

![CleanShot 2020-12-02 at 07 43 37](https://user-images.githubusercontent.com/29014463/100819449-367cd980-3472-11eb-9cd0-01da151635a7.gif)

**Comment by mittalyashu** [comment]
Another bug related to beautifying the code

![CleanShot 2020-12-02 at 09 51 51](https://user-images.githubusercontent.com/29014463/100828014-16eeac80-3484-11eb-8f11-cb7afb206f19.gif)

**Comment by deepcoder** [comment]
I  experience similar problem with TablePlus on MacOS Version 3.12.4 (360),  Postgresql 12.3:

If I use the '--' comment format, beautifying messes up the query, however if I use '/* */' comment format, beautify works correctly:

```
-- get one reading per (second, minute, or hour)
SELECT DISTINCT ON (date_trunc('second', last_updated))
    date_trunc('second', last_updated) AS last_updated,
    state
FROM
    states_archive
WHERE
    last_updated > now() - interval '2 day'
    AND state != 'unavailable'
    AND entity_id = 'sensor.refrigerator_govee_temperature'
ORDER BY
    date_trunc('second', last_updated);
```

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
