### ISSUE TITLE
Doesn't show the selected font size in query editor settings

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2218]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 354

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

<img width="277" alt="CleanShot 2020-12-02 at 07 50 15@2x" src="https://user-images.githubusercontent.com/29014463/100819954-2d403c80-3473-11eb-8313-6a08ed902c5e.png">

_I know we can see and change the font settings from preferences_

**Comment by huyphams** [comment]
I just added it, thanks.
<img width="346" alt="Screen Shot 2020-12-22 at 11 35 55 PM" src="https://user-images.githubusercontent.com/3654622/102911329-73a31d00-44ae-11eb-8040-609405ffc1da.png">
