### ISSUE TITLE
Support of Unix Domain socket connection

### ISSUE THREAD

**Issue by stephane** [TablePlus/TablePlus#222]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
86

3. The steps to reproduce this issue:
The new connection dialog don't allow me to connect on local DB via Unix Domain socket

**Comment by huyphams** [comment]
Hi @stephane Can you check the build 107? TablePlus supports socket now. You can use the field host for socket.
<img width="612" alt="screen shot 2018-05-31 at 3 55 30 pm" src="https://user-images.githubusercontent.com/3654622/40772754-0e198ba4-64eb-11e8-85c8-6ef51eebb3cd.png">

**Comment by jamesratcliffe** [comment]
It works for me on build 107; I can connect. Thanks a lot!!

However, the connection window doesn't match your screenshot. The field is still labelled "Host", not "Host/Sock":
<img width="500" alt="screen shot 2018-05-31 at 8 35 18 am" src="https://user-images.githubusercontent.com/20323342/40782506-916ea338-64ad-11e8-9163-aa0200e530e9.png">

**Comment by huyphams** [comment]
Yes because I have changed the title in the next build 108.

**Comment by stephane** [comment]
@huyphams It works! Thank you.
