### ISSUE TITLE
Launch TablePlus on Windows with a connection string

### ISSUE THREAD

**Issue by rfay** [TablePlus/TablePlus#2224]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 160

3. The steps to reproduce this issue: Try to launch TablePlus on Windows with a connection string

I'd like to launch TablePlus with a connection string, as is done easily on macOS as explained in https://github.com/TablePlus/TablePlus/issues/227#issuecomment-364486169

On macOS, you'd do this per #227
```
query="mysql://root:root@127.0.0.1:${DDEV_HOST_DB_PORT}/db" 
open "$query" -a "/Applications/TablePlus.app/Contents/MacOS/TablePlus" 
```

but how do you do it on Windows? 

The context: [ddev](https://github.com/drud/ddev) is a docker-based local development tool that happily launches tableplus on macOS using the technique above (and can heidisql on Windows because it has the technique) . We'd like to be able to support TablePlus on Windows and WSL2 as well.

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/342
