### ISSUE TITLE
Search for binary IDs

### ISSUE THREAD

**Issue by AlexBa** [TablePlus/TablePlus#2227]
1. Database: MySQL
2. TablePlus Version: 354 version 3.12.0
3. Step to reproduce the issue:

- Could not filter a binary column.

Hey,
currently, it's not possible to search for binary IDs in the database (MySQL) via filters like "equal" or "contain". However reading a value is working great.

<img width="995" alt="Bildschirmfoto 2020-12-09 um 13 27 49" src="https://user-images.githubusercontent.com/7062807/101629982-79b2eb80-3a22-11eb-8dea-8feebf9b4154.png">
<img width="972" alt="Bildschirmfoto 2020-12-09 um 13 28 02" src="https://user-images.githubusercontent.com/7062807/101629986-7ae41880-3a22-11eb-92b6-46296339f782.png">

**Comment by huyphams** [comment]
Hey @AlexBa thank you for letting us know. I confirm it was a bug.

P.s Please do not remove the issue template question, we use those questions to track the issue progress (fixed or pending or not fixed).

**Comment by huyphams** [comment]
You can download the hotpatch build here @AlexBa  https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thank you!
