### ISSUE TITLE
query result text not vertically aligned

### ISSUE THREAD

**Issue by alvint** [TablePlus/TablePlus#2228]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgres 12.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
354

3. The steps to reproduce this issue:
- set Result view mode to "Append all results in one tab"
- execute multiple queries at once using Run All Queries

The query result text is not vertically aligned, and is cut off (see picture). The text area appears to be scrollable, and you can scroll it to reposition the text. I'm guessing a newline is not being stripped from the result text, which is making it two lines instead of the anticipated one.

<img width="677" alt="Screen Shot 2020-12-09 at 10 13 45 AM" src="https://user-images.githubusercontent.com/622202/101649585-0fda1800-3a09-11eb-853f-546c8f14c333.png">

**Comment by huyphams** [comment]
Thanks @alvint let me fix it.

**Comment by alvint** [comment]
Wow, that was fast!

**Comment by huyphams** [comment]
I've fixed this issue, thanks @alvint it will be included in the next update!
