### ISSUE TITLE
Feature request: connects to analytics databases

### ISSUE THREAD

**Issue by MatthieuBizien** [TablePlus/TablePlus#223]
I work with multiple "big data" databases, like BigQuery, Athena(Aws), Hive, Spark, Presto, etc. They can all be queried with SQL. Is it in your roadmap to integrate with more SQL engines, or to provide a way to integrate it yourself?  They are usually compatible with JDBC.

**Comment by huyphams** [comment]
We are a native application so it's very hard to dynamic support (like a java application). We are planning to support all over the relational database (as many as we can).

**Comment by uber-mahyar2** [comment]
Hive & Presto support over ssh would be pretty nice.

**Comment by martenlindblad** [comment]
Presto would be awesome.

**Comment by alexanderkoehlerkun** [comment]
BigQuery please :)

**Comment by ericgrosz** [comment]
+1 for Presto and Hive. Are there any updates on adding support for those?

**Comment by MarioCatuogno** [comment]
+1 for Hive. Is it possible to support it via JDBC?

**Comment by sourcec0de** [comment]
Google Spanner 😎

**Comment by pouledodue** [comment]
Presto support would enable [Pulsar SQL](https://pulsar.apache.org/docs/en/sql-overview/) support 😍

**Comment by ryanmargheriti** [comment]
BigQuery would really be fantastic and round out an already great offering

**Comment by pouledodue** [comment]
and [HerdDB](https://github.com/diennea/herddb) 😍

**Comment by pwacher** [comment]
I would offer up my firstborn for Presto support.

**Comment by andrewcstewart** [comment]
Athena would be an interesting one.  Looks like there's an ODBC driver: https://docs.aws.amazon.com/athena/latest/ug/connect-with-odbc.html

**Comment by acrodrig** [comment]
Plus one for Athena!

**Comment by tomberthon** [comment]
Another plus 1 for Athena

**Comment by wtfzambo** [comment]
Another plus 1 for Athena

**Comment by s2t2** [comment]
If you point me in the direction, I could help work on a BigQuery connection maybe?

**Comment by andrewcstewart** [comment]
I wonder if it would make more sense to just create a general ODBC based connection type in TablePlus.  Maybe allow users to point to their own ODBC drivers.

**Comment by acrodrig** [comment]
I really really need this to make TablePlus the one client to rule them all! Please add Athena as a DB.

**Comment by AlexDHoffer** [comment]
Create a generic JDBC while we're at it. I would LOVE to be able to gather data from Spark SQL using TablePlus.

**Comment by marcosbrasil** [comment]
+1 Bigquery

**Comment by shashank-iitj** [comment]
+1 for Athena support.

**Comment by joeflateau** [comment]
Another +1 for Athena

**Comment by lucasasalmins** [comment]
+1 Athena & Bigquery

**Comment by linroex** [comment]
BigQuery +1, I like it.

**Comment by rav-bzz** [comment]
+1 for Athena

**Comment by random-ua** [comment]
+1 for Athena via ODBC #1269

**Comment by theMogget** [comment]
+1 for Presto

**Comment by d2207197** [comment]
+1 for Presto and Athena!

**Comment by FredLeudon** [comment]
Hi, I think I would buy TablePlus if I could use ODBC connexions.

**Comment by huyphams** [comment]
We're testing BigQuery, it will be included in the next update.

<img width="1407" alt="Screen Shot 2022-06-03 at 10 52 22 AM" src="https://user-images.githubusercontent.com/3654622/171782667-7a8c4261-105d-4609-ab45-9eb40d7a1a88.png">

Please create a separate issue for other drivers.

**Comment by cesar-loadsmart** [comment]
+1 for Trino. DBeaver already supports it

**Comment by RemyNtshaykolo** [comment]
+1 for athena

**Comment by dunamu-thor** [comment]
+ 1 for Trino.

**Comment by satheler** [comment]
+1 for Trino

**Comment by dboone31** [comment]
+1 for Trino

**Comment by vitorleal** [comment]
+1 for Trino
