### ISSUE TITLE
TablePlus should show error or remind the user when they forget to enter column data type

### ISSUE THREAD

**Issue by davewthompson** [TablePlus/TablePlus#2231]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.0 (354)

3. The steps to reproduce this issue:
Create a new table.
Add a new row and leave the data type empty
Save new row.
Row is not saved and is deleted.

Expectation:

- Show an error popup

See [video on YouTube.](https://youtu.be/BjsW2199SD8)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @davewthompson i think you made an mistake on the form, the column name should be the name and don't leave the data type empty

**Comment by davewthompson** [comment]
Oh, I see, you have this stray column number column at the start. Odd. Don't you think you should perhaps show an error message if the values can't be saved, rather than destroying the work that the user has done?

**Comment by huyphams** [comment]
This build will show you an error when you forgot to enter the data type: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
