### ISSUE TITLE
[Feature Request] Copy columns from a table to other

### ISSUE THREAD

**Issue by AveZomer** [TablePlus/TablePlus#2234]
1. Which driver are you using and version of it MySQL 8
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 354 v. 3.12.0

3. The steps to reproduce this issue:
Need a function to copy some columns from a table to other.

**Comment by huyphams** [comment]
I'm not sure that I understand you correctly. You can do it within TablePlus by pressing Command + C then Command + V to paste it.

**Comment by huyphams** [comment]
![2020-12-22 23 42 29](https://user-images.githubusercontent.com/3654622/102912014-7d795000-44af-11eb-86c3-29bb54c85fc6.gif)
