### ISSUE TITLE
Add to Queries doesn't work

### ISSUE THREAD

**Issue by avfigueredo** [TablePlus/TablePlus#2236]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.12.0 (354)

3. The steps to reproduce this issue:

 Execute any query and try to "Add to Queries", nothing happens. No errors, no alerts and the query doesn't appear in queries tab.

**Comment by huyphams** [comment]
Hmm I could not reproduce the issue, I think there was something wrong with the macOS view presentation. Have you tried to restart the app @avfigueredo  ?

**Comment by avfigueredo** [comment]
I found the issue, I save my connections and queries in a folder on microsoft one drive for backup. After restore for default options, works!
