### ISSUE TITLE
[Feature Request] Show filter history

### ISSUE THREAD

**Issue by tijsverwest** [TablePlus/TablePlus#2238]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.12.0 (354)

It would be nice to have filtering history for a table. For example, I did filter some table by id = 1 and then by id = 2. Now I want go back to my first filter, which is id = 1, but I don't see how I can do that except typing it manually again and again. It will be extremely useful especially for complex filters.

**Comment by huyphams** [comment]
TablePlus does support filter history. You can navigate between filters with the command + arrow. You can open a new filter by clicking the + on the right or press command + I (all the shortcuts below the filter).

![2020-12-17 06 58 54](https://user-images.githubusercontent.com/3654622/102420743-61039080-4035-11eb-9033-f213013f4c4c.gif)

**Comment by tijsverwest** [comment]
Ah, I see. Thanks, I didn't think about that from that standpoint
