### ISSUE TITLE
Feature request: import data from flat files

### ISSUE THREAD

**Issue by jreljac** [TablePlus/TablePlus#224]
One of the features I use often in Sequel Pro but don't see in TablePlus so far is the ability to import from a file into either an existing table or new table.

Not sure how important importing into a new table is, but importing data into an existing table would be super helpful.  Sequel Pro allows for CSV and SQL imports and, for CSV imports it allows you to map csv columns to table fields including the ability to set default values (see image)

![sequel pro](https://user-images.githubusercontent.com/2060831/36036014-b0cbf506-0d86-11e8-8f6c-835bd091e627.jpeg)

**Comment by huyphams** [comment]
Currently, you can copy CSV and paste directly to TablePlus, or right click on TablePlus content and choose import.

The limitation is you can't map table-field with CSV-field.

We need to improve this feature in some next update to make it better.

**Comment by jreljac** [comment]
So I just missed the import option.  The main reason I use the mapping is to define a field as NULL for import (to over ride what's currently in the field) . I just tried your import and it works as expected, finding it was just a bit difficult but then again, I only played around for < 15 minutes.

Thanks for pointing that out.

**Comment by DeanWard** [comment]
+1 for being able to map imports!

**Comment by 413x** [comment]
+1 for import mapping

**Comment by huyphams** [comment]
It's on #Build95 which will be released at the end of this week. 👍 
![screen shot 2018-03-20 at 6 17 39 pm](https://user-images.githubusercontent.com/3654622/37651538-06bd8760-2c6b-11e8-940c-1d995b15ea70.png)

**Comment by jreljac** [comment]
Excellent, looking forward to giving it a try.  Thanks for incorporating so quickly.

**Comment by jeffreybox** [comment]
Is this feature only available in the licensed version?

**Comment by huyphams** [comment]
it's available for free version @jeffreybox

**Comment by jeffreybox** [comment]
@huyphams when I choose import, there is no option to create a table - looks like the table must be created first. Can you link me to an explanation or tutorial? I don’t want to clog this thread. Thanks!

**Comment by huyphams** [comment]
Currently, TablePlus doesn't support creating a table from a flat file. But it will support. That option will be put right after `Select a table...` as a checkbox.

**Comment by jeffreybox** [comment]
@huyphams Oh I must have misunderstood. I thought your post above show that functionality added in #build95. Any idea on when this feature will be available?

**Comment by huyphams** [comment]
It will be released in the next update build 119. We were testing it for a while.
