### ISSUE TITLE
Result View Mode: horizontal in 1 tab view is unreadable if row is too long

### ISSUE THREAD

**Issue by dougreid72** [TablePlus/TablePlus#2240]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.12.0 (354)

3. The steps to reproduce this issue:Selecting "Append All Results in one Tab"

Noted: If the bug is related to data, please attach an example SQL data.
<img width="850" alt="Screen Shot 2020-12-16 at 1 44 44 PM" src="https://user-images.githubusercontent.com/48137265/102398565-0fabc080-3fa5-11eb-84a2-07671efe5588.png">

**Comment by huyphams** [comment]
Thank you. I've fixed this issue, it will be included in the next release!
