### ISSUE TITLE
Window resize broken

### ISSUE THREAD

**Issue by licanulla** [TablePlus/TablePlus#2242]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 354
3. OS version: MacOS Catalina (10.15.7)

Unable to reduce width size of the window. Only encrease from some locked width.

**Comment by huyphams** [comment]
Sometimes it's is an MacOS bug. Have you tried to restart the app @licanulla thank you

**Comment by licanulla** [comment]
That helps, thanks!

**Comment by danilokleber** [comment]
I can't get the window to preserve its maximized size (fill all the screen, not macOS's full screen). If I set the size smaller than a certain point it is kept. What should I do?

Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 11.10
Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 367
OS version: macOS Big Sur (11.3)
