### ISSUE TITLE
[Feature Request] Menu/Preferences/Designs access on Welcome/Connections screen.

### ISSUE THREAD

**Issue by iyashpal** [TablePlus/TablePlus#2246]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Not Applicable**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**build 150**
3. The steps to reproduce this issue:
**Not Applicable**

**Problem:**
I switch table plus theme twice a day in the day I use light theme and in nights I use dark theme. Currently it's very long process to change the table plus settings. Each time I have to  connect a connection and to to menu and change the theme then restart Table Plus. Fine no issue but the process is very long and some time we have to do the things quickly but due to long process to reach out to settings its very frustrating. The issue is not related to themes only the thing is if I need to load the connections from different directory quickly then I have to follow the same process again and again which makes me very slow sometimes. And same for **Empty Diagrams**. Right now the major issue is when we first setup the software we need to create a connection and connect to it and then do the settings. I always keep my connections to google drive so I can access all connections anywhere. Rest you know better.

**Solution:**
Pull the Menu to Welcome Screen Like below
![image](https://user-images.githubusercontent.com/19922707/102579256-2592c000-4122-11eb-9f20-667ebd43c1a5.png)

By doing this we don't need to connect to the connection every time to change the settings/themes.  And for **Empty Diagrams**  you can add an item to context menu on home screen like this:
![image](https://user-images.githubusercontent.com/19922707/102579608-cda88900-4122-11eb-9b11-6afb69123beb.png)

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/350

**Comment by huyphams** [comment]
There will be an auto theme on the next update so you don't have to switch it over and over again. You can choose it in the TablePlus settings.

**Comment by iyashpal** [comment]
What about Preferences? will it be accessible on welcome screen?

**Comment by huyphams** [comment]
You can press control + , to open preferences anytimes, anywhere

**Comment by iyashpal** [comment]
And diagrams?

**Comment by huyphams** [comment]
it has been added on the latest release 154 on the Windows.

**Comment by iyashpal** [comment]
I got the update and feature thank you so much for quick action on my feature request.
