### ISSUE TITLE
Running .sql file crashes TablePlus

### ISSUE THREAD

**Issue by formido** [TablePlus/TablePlus#2248]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

    12.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

    Build 354

3. The steps to reproduce this issue:

    a) Open [videoezy.txt](https://github.com/TablePlus/TablePlus/files/5720567/videoezy.txt) contents as .sql

    b) Chose 'Run All'

    c) My TablePlus crashes

**Comment by formido** [comment]
Never mind, seems to be something with my postgres install. Crashed in a different client also.

**Comment by formido** [comment]
Worked perfectly from `psql`, weird that both TablePlus and DBeaver crashed on it.

**Comment by huyphams** [comment]
It didn't not crash, however, it hang for while, I think TablePlus was waiting for the response from the server.

<img width="1392" alt="Screen Shot 2020-12-20 at 14 27 04" src="https://user-images.githubusercontent.com/3654622/102707657-74ca2380-42cf-11eb-8cd9-84fe88eae70a.png">

**Comment by formido** [comment]
It hung when you tried it or hung according to my crash logs? I can believe it hung, but just weird coincidence TP and DB both hung for 10 min but import only took a minute or two at the command line. TablePlus is of course working fine on the imported data now. 💯
