### ISSUE TITLE
[Feature Request] Add a client name to the redis connection

### ISSUE THREAD

**Issue by marcbachmann** [TablePlus/TablePlus#2249]
1. Which driver are you using and version of it: Redis 6
2. TablePlus Version: 3.12.0 (354)

3. The steps to reproduce this issue:
- Connect to redis
- Execute `CLIENT LIST`
- The output shows
  ```
   id=334 addr=172.17.0.1:39246 fd=13 name= age=75 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=32742 obl=0 oll=0 omem=0 events=r cmd=client user=default
  ```
    
- Suggested output:
  ```
   id=334 addr=172.17.0.1:39246 fd=13 name=TablePlus-v3.10.0-b348 age=75 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=32742 obl=0 oll=0 omem=0 events=r cmd=client user=default
  ```
  
Redis supports setting the client name using the command [`CLIENT SETNAME`](https://redis.io/commands/client-setname).
It would be good to use that to show which connection is coming from TablePlus.

**Comment by huyphams** [comment]
Thanks, it will be included in the next update!
