### ISSUE TITLE
Support MS SQL 2008 syntax.

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#225]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Microsoft SQL Server 2008

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 87

3. The steps to reproduce this issue:

Wrong select syntax.

**Comment by sntran** [comment]
Hi @huyphams,

Is there an update to it? We have a lot of SQL Server databases so fixing this would helps a lot.

**Comment by huyphams** [comment]
We are working on it, it will be released in build 89 👍

**Comment by huyphams** [comment]
Hey @sntran it's fixed: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0 
please let me know if it works for you. Thanks!

**Comment by sntran** [comment]
@huyphams , I have tested build 89 and it is indeed fixed. Thanks!
