### ISSUE TITLE
Error: Incorrect syntax near the keyword 'IF' - SQL Server 2014

### ISSUE THREAD

**Issue by MT128** [TablePlus/TablePlus#2252]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 150

3. The steps to reproduce this issue:
- open storage procedure editor, change sth and then click ctrl+s
- SQL preview will be: DROP PROCEDURE IF EXISTS [dbo].[xxxxxx]; which "IF EXISTS" is not supported in SQL Server 2014
- error occurs:
 
![image](https://user-images.githubusercontent.com/34278995/102883209-ef21b180-444f-11eb-8945-c621b00e4f77.png)

> IF EXISTS
> Applies to: SQL Server ( SQL Server 2016 (13.x) through current version).
https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-procedure-transact-sql?view=sql-server-ver15

**Comment by huyphams** [comment]
Move to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/358
