### ISSUE TITLE
next page button is disabled but cmd+right arrow works and displays an empty page

### ISSUE THREAD

**Issue by gabimor** [TablePlus/TablePlus#2253]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgresSQL 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.0 (354)

3. The steps to reproduce this issue
open a table (double click any table name0
focus on the table area
cmd+right click until you reach the last page
the bug: you can go one page beyond the last page, even though the next page button is disabled

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
This build should fix the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
