### ISSUE TITLE
[enhancement] Install database drivers (reduce app size)

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2258]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 355

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

_I think_ the app ship with all database driver packed into a single app which makes the size of the app so big

![CleanShot 2020-12-25 at 17 18 17@2x](https://user-images.githubusercontent.com/29014463/103134184-73389b00-46d5-11eb-806e-c07ef6d46333.png)

It might decrease the app size if we can download the database driver on-demand.

**Comment by huyphams** [comment]
Hi @mittalyashu please use the version on our web site. It's 50MB

TablePlu is a native app so there is no way to hook dll on runtime.

**Comment by mittalyashu** [comment]
@huyphams I am using Tableplus app from Setapp subscription.
