### ISSUE TITLE
after adding new column and put new custom position in "ordinal_position" it always move to 1st position

### ISSUE THREAD

**Issue by iammohsinar** [TablePlus/TablePlus#2260]
version: Mysql
build number: 352

when i edit table to add new_column at position 2 by using "ordinal_position" UI, after saving table column always positioned at 1 not at 2.

**Comment by huyphams** [comment]
Thank you @iammohsinar if you have a chance, please try this patch https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
