### ISSUE TITLE
Feature Request: Add support for DuckDB

### ISSUE THREAD

**Issue by fintron** [TablePlus/TablePlus#2262]
DuckDB is a new OLAP flat file database that is very similar to SQLite. Can you add support for it?

**Comment by psimm** [comment]
DuckDB has become much better since this issue was opened (more supported SQL commands and better integration with reading Parquet files and other formats). It also became more popular: https://db-engines.com/en/ranking_trend/system/DuckDB

Support for DuckDB in TablePlus would be awesome

**Comment by alecgorge** [comment]
Bumping this again. The only GUIs for DuckDB right now are DBeaver and DataGrip and DBeaver crashes all the time

**Comment by mindreframer** [comment]
They provide stable Node.js drivers, this should be quite usable

**Comment by massung** [comment]
Yes, very much please.

**Comment by didierfranc** [comment]
Will be great to have it!

**Comment by toanphan19** [comment]
Would absolutely love to have DuckDB in my favourite IDE! I'm trying to work with DBeaver right now but it's not pleasant at all.

**Comment by azngeek** [comment]
+1 Here :)

**Comment by jamielxcarter** [comment]
Love TablePlus and DuckDB. I can't wait to be able to use them both together!

**Comment by scholarazwa** [comment]
Bumping this up. Please add support for DuckDB in TablePlus. 🙏

**Comment by daveycope** [comment]
+1 Please add support for DuckDB. Very little out there to match TablePlus if this was added. Thank you!

**Comment by psimm** [comment]
@huyphams Could you please comment on this issue? So much demand for DuckDB support 🙏

**Comment by massung** [comment]
One note I'll make (I very much want this, too):

DuckDB is not yet 1.0. I use it all the time in my work and it's great, but - until 1.0 - the DuckDB team has made it clear that their `.db` file format (and the API) will not be stable nor backwards compatible. 

If I were @huyphams, I'd probably be waiting for 1.0. Or at the very least an announcement that the API is now stable and the file format will be backwards compatible.

**Comment by johnoscott** [comment]
DuckDB is at 0.10.0 as of Feb 2024 which is the first release to support backward compatibility. https://duckdb.org/2024/02/13/announcing-duckdb-0100.html

I don't see a reason to wait to add support to this fine project ?

**Comment by huyphams** [comment]
Trying with the version 0.10.3, so far no issue.
<img width="316" alt="Screenshot 2024-06-01 at 10 36 02 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/60d87d5b-8cee-4565-92b8-671b1884b81b">

**Comment by huyphams** [comment]
<img width="1081" alt="Screenshot 2024-06-01 at 2 59 50 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/00cae022-8f8a-48b4-87ce-cdf90a0ce14f">

**Comment by huyphams** [comment]
Added in release 562, please update!

**Comment by spren9er** [comment]
Great! Thanks for adding DuckDB support!

However, FLOAT, DATE and INTERVAL columns are not working for me!

For FLOAT and DATE columns, there are only `NULL` values showing up, even though none of the values are `NULL` in table.
INTERVAL data shows incorrect number (most of the time it's `0`).

### Table in TablePlus

<img width="256" alt="Bildschirmfoto 2024-06-15 um 09 12 02" src="https://github.com/TablePlus/TablePlus/assets/5602551/2683dbc7-a760-4e16-8095-b2d728f82a46">

### Table in DuckDB

<img width="484" alt="Bildschirmfoto 2024-06-15 um 09 13 44" src="https://github.com/TablePlus/TablePlus/assets/5602551/4d692e99-e8e3-4eed-bc88-4f18bcd41f35">

Can be easily reproduced by running following SQL queries in TablePlus:

```
SELECT 1::FLOAT;
```

```
SELECT current_date;
```

```
SELECT INTERVAL '1 day';
```

Other types like DOUBLE, TIME and TIMESTAMP seem to work fine:

```
SELECT 1::DOUBLE;
```

```
SELECT current_time;
```

```
SELECT current_timestamp;
```

### Specs

DuckDB Version: v1.0.0 (1f98600c2c)
TablePlus Version: 562
macOS: Sonoma 14.5
