### ISSUE TITLE
Feature: paid feature where I can disable tabs?

### ISSUE THREAD

**Issue by denodster** [TablePlus/TablePlus#2264]
I hate how table plus makes tabs, they disrupt my workflow.

I came over from using Sequel Pro, which as become buggy and unusable over the last few years, not because it isn't well thought out but because it crashes and acts oddly quite frequently these days. Also, I've taken to using windows and Sequel Pro will never be anything other than a Mac program. 

Sequel Pro has a similar interface to table plus, but does not automatically open tabs, but I've never felt the need to open a tab while using it. Now that I'm using Table plus, I find the automatic tabs annoying and disruptive. I've also noticed that you've hinged your whole paid model on tabs.

My issue with tabs: normally when I use an app that has tabs, I have to click a plus or do something explicit to create one. Therefore I make a conscious decision to make a tab and I've already created the brain space for that tab. Table plus opens tabs on it's own implicitly at times that don't make sense to me. If I purchased table plus I imagine opening 100 tabs over the course of the my day while ignoring all of them and then periodically closing all but the current one. The current warning at 3 tabs is nice because it prevents me from doing this. This creates a disincentive for me to buy table plus because buying it will make my experience worse. As a software developer I appreciate the software you've created and I don't want to remain in the free tier, 

What to do instead? just have one workspace. and any act that currently opens a new tab should just change the current workspace. The only exception to this would be the the SQL Editor, which in my mind doesn't feel like it should open a tab regardless, cause it's completely different from everything else and tabs generally imply the idea of threading a common task. There should be one SQL editor, and so long as it retains whatever I last typed into it when I click on it I'm good.

I know that I'm probably not jiving with the design philosophy that you all are aiming at, and that you probably think I'm wrong, but I can't be the only person who uses table plus this way. I appreciate good software and this is good software, that I would like to pay for, but I'm currently in a situation where if I pay for it, my experience with it will get worse. maybe you should switch to some other mechanic like a query limit or something else to trigger the trial limit, forcing the user to restart the program when they bump up against it, I don't know just a thought. I really think the current user experience surrounding tabs makes no sense though.

**Comment by denodster** [comment]
One more thought: I use VS code on a regular basis, and while that is not really an SQL program, It's tabbed behavior is to change the current tab when selecting a file in the left hand bar with a single click, and open a new tab when a file is double clicked on. I would be game for this with Table plus, as it would help curb the implicit tab multiplying.

**Comment by huyphams** [comment]
Hi, I will move this issue to Windows because this is the TablePlus macOS issue tracker. TablePlus on macOS will not open a new tab until the current tab has been modified. Like an editor VScode or Sublime Text.

**Comment by huyphams** [comment]
https://github.com/TablePlus/TablePlus-Windows/issues/353
