### ISSUE TITLE
issue with record number

### ISSUE THREAD

**Issue by irshadelevision** [TablePlus/TablePlus#2266]
1. Mariadb
2. build 352
3. when you create a view the total number of record showing on the bottom is wrong. for  example it is showing 1-300 of ~ 300 rows. The correct is 1-300 of ~317. in other tables it is showing correct.

**Comment by huyphams** [comment]
Hi @irshadelevision it was an intentional behavior. It is an estimated value. You can turn off estimated count in TablePlus preferences.
