### ISSUE TITLE
Title bar behaviour is inconsistent

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [TablePlus/TablePlus#2268]
Version 3.12.0 (354)

Unable to click and drag the window in certain areas. Seems inconsistent.

https://user-images.githubusercontent.com/6763222/103784357-c2fe5700-5031-11eb-80b9-63818d8ac233.mov

**Comment by mrardon** [comment]
I have this issue as well on MacOS Big Sur 11.2 (M1). Drives me insane sometimes when trying to find the spot to drag the window. 

Have found any consistent spot to drag the window?

**Comment by JohnnyWalkerDesign** [comment]
The left side seems to be your best bet. I'm on Big Sur, too.

**Comment by huyphams** [comment]
Hi guys, we've brought back the moveable title bar on the build 360. Please check it out!

**Comment by JohnnyWalkerDesign** [comment]
Hallelujah.
