### ISSUE TITLE
Feature Request: Open TablePlus and connect to database from command line

### ISSUE THREAD

**Issue by kevinkaske** [TablePlus/TablePlus#227]
I use Freeter (https://freeter.io/) to organize my development env. It would be nice to be able to open TablePlus from the command line and pass in the databases I want to connect to. I could then assign that to a button in Freeter for each project.

**Comment by huyphams** [comment]
Hmm, have you try to type: `open postgresql://user@127.0.0.1/<database_name>`

TablePlus supports open a connection via command line with an URL.

**Comment by kevinkaske** [comment]
I'm talking about being able to open terminal in MacOS and launch the application as well as connect to a database from command line. It's probably a very niche request.

**Comment by kevinkaske** [comment]
Works perfectly! Thank you!

**Comment by emadel80** [comment]
@huyphams Thank you for the hint.  In my case working temporary with sqlite.  Just had to type in the terminal:

open database/database.sqlite

**Comment by Graloth** [comment]
How would you do this on windows? I can't really find a list of flags to pass to the .exe when launching it if that is how it's done, and the "open" command doesn't exist on windows.

**Comment by rfay** [comment]
@Graloth I asked your question about launching with connection string on Windows again as a new issue in https://github.com/TablePlus/TablePlus/issues/2224

**Comment by HelgeSverre** [comment]
For future searchers.

If you right click on an existing connection
![CleanShot 2023-10-09 at 10 37 28](https://github.com/TablePlus/TablePlus/assets/1089652/a1d6b54e-9560-40f8-b6a8-f1ba5731f4ed)

You will get something like this:

```shell 
mysql://@127.0.0.1?statusColor=005392&env=local&name=Laravel%20Herd&tLSMode=0&usePrivateKey=false&safeModeLevel=0&advancedSafeModeLevel=0&driverVersion=0
```

You can truncate it down to only the name of the connection:

```shell
mysql://@127.0.0.1?name=Laravel%20Herd
```

Then throw that into an alias like so:

```shell
alias db="open mysql://@127.0.0.1?name=Laravel%20Herd"
```

Note if you use zsh, you need to quote the url:

```shell
alias db="open 'mysql://@127.0.0.1?name=Laravel%20Herd'"
```
