### ISSUE TITLE
Mac-ish design for welcome screen

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2273]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 357

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

| References |
| --- |
| ![CleanShot 2021-01-08 at 17 12 39@2x](https://user-images.githubusercontent.com/29014463/104011994-0f35cc80-51d5-11eb-9889-09dc9681fea9.png) |
| ![CleanShot 2021-01-08 at 17 11 43@2x](https://user-images.githubusercontent.com/29014463/104012004-152bad80-51d5-11eb-9018-9c9afed2a0db.png) |

Comparing to current design

![CleanShot 2021-01-08 at 17 13 12@2x](https://user-images.githubusercontent.com/29014463/104012053-27a5e700-51d5-11eb-89a2-51f88acdb95f.png)

**Comment by huyphams** [comment]
We used to be like this, however we changed the design because the left space are petty much useless.
Some users also said that the want to remove the left space completely.

we are working on the new version 4.0 so I will close this issue for now
