### ISSUE TITLE
different fill's for different themes

### ISSUE THREAD

**Issue by mittalyashu** [TablePlus/TablePlus#2274]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 357

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

Not sure if its intentional or an issue.

![CleanShot 2021-01-08 at 17 41 22](https://user-images.githubusercontent.com/29014463/104014372-eadbef00-51d8-11eb-9ad8-0b136e2eaaf9.gif)

**Comment by huyphams** [comment]
It is. Thanks
