### ISSUE TITLE
"search within" not working

### ISSUE THREAD

**Issue by nachocab** [TablePlus/TablePlus#2275]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 13

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.12.2 (359)

3. The steps to reproduce this issue: I enter the post_id of the first row (3075) but no row is returned. The only valid options are Contains, Has prefix and Has suffix. What am I missing?

![CleanShot 2021-01-11 at 16 07 01](https://user-images.githubusercontent.com/27538/104199328-95495180-5427-11eb-9d29-4935c2ed9f40.gif)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I could not reproduce it on the latest release, please let me know if you are still seeing it.
Thanks
