### ISSUE TITLE
Beautify doesn't handle CTEs

### ISSUE THREAD

**Issue by nachocab** [TablePlus/TablePlus#2276]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 13

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.12.2 (359)

3. The steps to reproduce this issue:

Given this query:

```
-- comment
with t1 as (
select * from t)
select * from t1
```

Beautifying with `command + i` should give this:

```
-- comment 
WITH t1 AS (
	SELECT
		*
	FROM
		t
)
SELECT
	*
FROM
	t1
```

But the current behavior is this, which breaks the query:

```
-- comment WITH t1 AS (
	SELECT
		*
	FROM
		t
)
SELECT
	*
FROM
	t1
```

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
