### ISSUE TITLE
"Buy a license" is truncated

### ISSUE THREAD

**Issue by jaydorsey** [TablePlus/TablePlus#2280]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 358

3. The steps to reproduce this issue:

- Open the License Registration screen
- Observe the `e` at the end of the `Buy a license` button appears truncated

![image](https://user-images.githubusercontent.com/191564/104525650-92d52c00-55ce-11eb-8ac8-8f73c439e944.png)

I'm on macos catalina

**Comment by huyphams** [comment]
Thank you so much, I just fixed it! 🙌
