### ISSUE TITLE
MySql 5.7 with TLS 1.2

### ISSUE THREAD

**Issue by esemlabel** [TablePlus/TablePlus#2283]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySql 5.7.32

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.12.2 (358)

3. The steps to reproduce this issue:

When using MySql 5.7 with TLS 1.2 you won't able connect to database, when MySql 5.x is selected.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/17903845/105023640-e1ae1600-5a53-11eb-88d4-8c1672c3ff58.png">
![image](https://user-images.githubusercontent.com/17903845/105023683-f094c880-5a53-11eb-9702-cebb8a453996.png)

But it works once you change setting to 8.x
<img width="320" alt="image" src="https://user-images.githubusercontent.com/17903845/105023743-02766b80-5a54-11eb-90c3-aa6201e0e914.png">

**Comment by huyphams** [comment]
The 5x driver is used for very old MySQL, now we rename it to default and old driver to make it clear.
