### ISSUE TITLE
Retain windows and connections between launches

### ISSUE THREAD

**Issue by mikeerickson** [TablePlus/TablePlus#2284]
This is not a bug, but rather a request.  

It would sure be nice to retain window position and connections between launches.  I need to constantly work with 3 different database connections (one local, two ssh) and each time I quit (and sometimes on accident) when I relaunch the app, it only retains my local connection window, thus I have to manually reconnect to the other ssh connections, which is a laborious process.

Further, can you please add a feature to confirm I meant to quit (I accidentally quit way too often when I am working at warp speed)

Thanks :-)

**Comment by huyphams** [comment]
Hi, please enable this option (please do not remove the issue template questions) however the Windows version does not support this.

<img width="921" alt="open" src="https://user-images.githubusercontent.com/3654622/105119338-b3d3da80-5b02-11eb-9b12-a1d14d286259.png">

**Comment by mikeerickson** [comment]
This option is already selected

![image](https://user-images.githubusercontent.com/183153/105204299-e11b8b00-5af8-11eb-937c-c959501768b7.png)

When I restart, it opens 1 of 4 windows, which as mentioned in OP is the local MySQL connection but it does not open the 3 other windows, which are connected to remote DBs via SSH.

**Comment by mikeerickson** [comment]
@huyphams please see above
