### ISSUE TITLE
[Feature] Nickname Databases

### ISSUE THREAD

**Issue by MattWilliamsonFundmetric** [TablePlus/TablePlus#2286]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL, Ver 14.14 Distrib 5.6.33 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.12.2 (359)

3. The steps to reproduce this issue: N/A

Having a way to add a nickname to a database would be amazing, as I often work with databases (in the same MySQL connection) that are 8-10 alphanumeric character hashes. we are not able to rename the databases, so it becomes a pain in the rear end when trying to find one of the 20 databases for data fixing/reporting by using the "open database" button on the top.
![Screen Shot 2021-01-20 at 6 00 14 PM](https://user-images.githubusercontent.com/52211366/105246709-05538800-5b4a-11eb-82f0-039013bb220c.png)
 menu bar.

**Comment by huyphams** [comment]
I don't think that we should add any addition info to the database name, we should setup connection for separated databases to avoid this issue.
We can search and open connection by name with command shift K
