### ISSUE TITLE
[GUI Change Request] Make the > Menu Less Annoying (The one the appears when too many tabs are open)

### ISSUE THREAD

**Issue by unlostify** [TablePlus/TablePlus#2287]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 358

3. The steps to reproduce this issue:

We find that we frequently end up having enough tabs open that we end up having to use the > menu that appears at the right side of the list of tabs.

While it makes sense that you can only show a limited number of tabs at one time, its particularly frustrating to:
- Have enough tabs open that the > menu has appeared, and then
- Be in the middle of constructing a new SQL query, and then
- Realize that you need to open a table/view (e.g. to look at the column names in it,) and then
- Try to return to the SQL Query tab that you were working on

At this point, in order to find the SQL Query you were creating, you'll have to click on the > menu. When you do that you'll notice that all open SQL Query tabs are named identically (so its hard to tell them apart by name). So, essentially, you need to try clicking on the various SQL Query items in the list until you find the right one.

(Side Note: The fact that all of the SQL Editor tabs are named 'SQL Query' is less of an issue when the tab isn't hidden under the > menu, since you can commit which tab is highlighted to your memory before switching to another tab)

Consequently, I often try to close open tabs that I'm done with frequently. This however can be frustrating since there is no harm in closing some types of tabs (e.g. a Table/View/Function tab), while its important to be more careful with others (e.g. an SQL Query tab, or one of the files saved in Tableplus's Queries tab) since:
- These two types of tabs may contain unsaved edits that I may want to later perform redo or undo operations on (something thats no longer possible once a tab has been closed), and
- If, specifically, the tab you close was a file from Tableplus's Query tab _with unsaved changes_, those changes will be automatically saved regardless of whether thats what you intended to do or not.

As a result, I find that while I should be more careful when closing tabs, its a task I have to do so frequently enough that I do make mistakes and accidentally close tabs I didn't intend to close.

I'm sure it'd be a non-trivial amount of work to seperate Table/View/Function tabs from SQL Editor/Query Files tabs, but I wonder if the right approach might be to seperate out the two types of tabs in the GUI - both because:
- It'd seperate the tabs that can be closed with _no side effects_ from the ones that which do _have side effects_ (making it easier to minimize mistakes)
- Depending on how this idea is implemented GUI-wise, it could make it a lot more efficient to flip from an SQL Editor window to a table/view and back to that same SQL Editor (something that I find myself doing regularly)

**Comment by huyphams** [comment]
Hi @unlostify thanks for the feedback. We will improve it. In the meantime, you can use the workaround solutions below.

1. Name your queries tab: 
<img width="789" alt="Screen Shot 2021-01-21 at 2 18 25 PM" src="https://user-images.githubusercontent.com/3654622/105316563-a2b6c680-5bf3-11eb-8de4-b01642b03076.png">

2. Turn off autosave.
<img width="921" alt="save" src="https://user-images.githubusercontent.com/3654622/105316737-e0b3ea80-5bf3-11eb-9d4a-ea4046315dfb.png">

**Comment by unlostify** [comment]
1. I didn't realize you can re-name tabs. Thanks, thats a great workaround for the time being =)

2. Ah, that makes sense. I knew that preference was there, but hadn't realized it applied to _both_ the SQL Editor tabs and TablePlus's 'Query' Files. Ideally though, I'd really like it _enabled_ for SQL Editor tabs, but _disabled_ for files in Tableplus's Query tab.

That's because:
- With SQL Editor tabs I don't want to completely lose queries I've drafted if I accidentally close a tab, but
- With TablePlus's Query files I don't want to accidentally make destructive changes to files I've created, tested and improved over time that are already permanently saved as .sql files in Finder (so, given the choice, I'd rather lose changes I've drafted that might screw up my saved query vs. auto-saving the file without asking me for confirmation first).

Thanks for your hard work on TablePlus, Henry =)
