### ISSUE TITLE
[improvement] space right after aucomplete selection

### ISSUE THREAD

**Issue by khngtamara** [TablePlus/TablePlus#2288]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): mysql 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.12.2 (358)

3. The steps to reproduce this issue: Start writing any keyword and select a suggested aucomplete. After that I have to type in a space which could be done by the software.

**Comment by huyphams** [comment]
We will add an option for this in the next update.
Ref: https://github.com/TablePlus/TablePlus/issues/480
