### ISSUE TITLE
Show Database name in sidebar as shown in preview screenshots

### ISSUE THREAD

**Issue by joshstrange** [TablePlus/TablePlus#229]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL I don't see a version in the UI

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 87

3. The steps to reproduce this issue:

- Open Workspace

- Open more than 1 connection

- No Name under icon

[Example](https://www.dropbox.com/s/tr3xdnu57r9l61k/Screenshot%202018-02-09%2012.46.15.png?dl=0)

**Comment by joshstrange** [comment]
Well I just noticed it shows the DB name. I'd really like to be able to see the connection name (So I can see QA/Dev/Staging/etc)

**Comment by huyphams** [comment]
Have you selected a database @joshstrange. The icon name is the database name. btw, if user didn't select a database, it will be empty. I'm thinking about it

**Comment by joshstrange** [comment]
@huyphams Yeah, I hadn't selected a DB yet. I'm conflicted on what I think should go there. I really want to be able to see which server I'm connected to (which I can kind of get by changing their colors but that is only on hover). If I could set icon's for each server that would be great.

**Comment by huyphams** [comment]
Yup, that's the point we can improve, the icon color or default is connection name if the user hasn't selected a database. Great suggestion!
Btw, it also depends on the driver because PostgreSQL user must specify a database if they can connect to the database.

**Comment by wdepril** [comment]
it would be great to show the connection name on the sidebar, that way it becomes configurable.  Database on a second line would be useful.    All our databases (mysql) are named the same in different environments and having to hover over to check which db to select is just not convenient but more importantly error prone.

**Comment by huyphams** [comment]
Sure! I'm working on it.

**Comment by huyphams** [comment]
it will be included in the new update as a temporary solution.
<img width="434" alt="name" src="https://user-images.githubusercontent.com/3654622/57346260-1262f480-7178-11e9-80b7-12d48dd69d99.png">

**Comment by axsuul** [comment]
@huyphams Is there a way to show the tag in the left pane (e.g. production)?
