### ISSUE TITLE
Database Restore Error

### ISSUE THREAD

**Issue by mikeerickson** [TablePlus/TablePlus#2290]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 359

3. The steps to reproduce this issue:

- Select File > Restore
- Select Connection 
- Select Database (test8)
- Select File (Backup from MySQL 5.7)

I receive the following error

Restore database 'test8'
Restoring...
restore_ms_5.7: [Warning] Using a password on the command line interface can be insecure.

ERROR 2026 (HY000): SSL connection error: unknown error number

Restore database completed

I was able to get the data into the new MySQL8 database by "exporting" (as opposed to Backup) all the tables, then importing that file.  

Perhaps the Backup/Restore operations to only be done from/to same version of MySQL?

**Comment by Pat-Gekoski** [comment]
Same problem here. 
Running on Mac
mysql 8.0.29
TablePlus build 437

**Comment by sebastiandedeyne** [comment]
Happens to me too, especially with large dumps (1GB+ gzipped). After retrying a few times it does come through though.

Currently on Version 5.2.2 (478).

**Comment by nicoabie** [comment]
Happens to me too in m1 mac Version 5.3.4 (493)
this worked before

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2797992/223480287-d11ca8d5-4485-44b8-9cc9-58dfe6056c6e.png">

**Comment by 22289d** [comment]
Same problem but as above, if I open the gzip and then import the dump, it works.

**Comment by ryanmortier** [comment]
Same problem here, 3 years later.

**Comment by nocodelab** [comment]
Same problem here.

**Comment by erikgyepes** [comment]
Looks like the issue is that you have to select the MySQL version, then it works.
