### ISSUE TITLE
Format SQL crashes for very, very large input queries.  Also a scroll bar for the sql window is needed.

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#23]
[errorQuery.txt](https://github.com/TablePlus/TablePlus/files/1183879/errorQuery.txt)

After inserting this large SQL into the text window and hitting the Format (Cmd + I) button, TablePlus  crashes right away.

Also I think a scroll bar for the sql window is necessary to help view such large queries.

**Comment by huyphams** [comment]
Hi @MrGundBear , 
The bug has been fixed. Thank you for your attachment.
I also added a config to set SQL Query has a scroll bar, you can toggle.

**Comment by MrGundBear** [comment]
fantastic! Great turn-around Huy
