### ISSUE TITLE
font color option for "invisible" characters

### ISSUE THREAD

**Issue by qwesda** [TablePlus/TablePlus#2300]
I use the option to show invisible characters. The syntax highlighter groups them together under `other` and thus they have the same color and _heaviness_ like most of the query. 

 - they should have a less prominent color than normal text 
 - there should be a color option for them

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/384993/106933961-d4fb1480-6719-11eb-8d22-3cbfbdbb7207.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/384993/106934492-797d5680-671a-11eb-995c-65f0e02bbe45.png">

Version 3.12.2 (358)

**Comment by huyphams** [comment]
Hi @qwesda thank you for the feedback, I'm working on it. It should be available in the next update (within this week).

**Comment by huyphams** [comment]
<img width="1292" alt="Screen Shot 2021-02-10 at 12 32 40" src="https://user-images.githubusercontent.com/3654622/107469301-149f8180-6b9c-11eb-98c3-614bddb7c30d.png">

**Comment by huyphams** [comment]
It's released in the build 360
