### ISSUE TITLE
Crash after deleting empty folder in queries

### ISSUE THREAD

**Issue by Uratownik** [TablePlus/TablePlus#2305]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL 2019

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.2 (358) for MacOS ARM64

3. The steps to reproduce this issue:
1. Create new folder in Queries
2. Open that empty folder (arrow points down)
3. Delete that folder

**Comment by huyphams** [comment]
It's fixed, thanks!
