### ISSUE TITLE
[Bug] PostgreSQL Check Constraint appearing on wrong columns

### ISSUE THREAD

**Issue by ato-kreatize** [TablePlus/TablePlus#2306]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 13.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 359

3. The steps to reproduce this issue:
Create a table with the following query:
```
CREATE TABLE "test_table" (
    "id" serial PRIMARY KEY,
    "some_id" int4 NOT NULL,
    "another_id" int4 NOT NULL,
    "ordered_id" int4 NOT NULL,
    "some_property" bool NOT NULL DEFAULT false,
    "size" int4 NOT NULL,    
    CONSTRAINT batch_size_check CHECK (size > 0)
);
```

Expectation: Only the column `size` shows a check of `size > 0`.
What I see instead: 
<img width="918" alt="Screen Shot 2021-02-08 at 6 33 43 PM" src="https://user-images.githubusercontent.com/54443966/107258592-47326880-6a3c-11eb-85ae-02420b71187a.png">

**Comment by skollro** [comment]
Can confirm this bug.

**Comment by huyphams** [comment]
I believe it was fixed on the newest release.

**Comment by huyphams** [comment]
<img width="1487" alt="Screenshot 2023-03-02 at 11 40 18 AM" src="https://user-images.githubusercontent.com/3654622/222332757-e493c08e-8570-4938-900d-e75ec4b19e1c.png">
