### ISSUE TITLE
Feature request: Snowflake support

### ISSUE THREAD

**Issue by astewart-twist** [TablePlus/TablePlus#231]
Just throwing it out there.

**Comment by huyphams** [comment]
Is it a relational database? I just googled and found this: https://www.snowflake.net/ not sure if it is the one you mentioned

**Comment by rhlahuja** [comment]
Snowflake is indeed a relational "data warehouse" (similar to Redshift) and they provide their own JDBC driver: https://docs.snowflake.net/manuals/user-guide/jdbc-download.html. I would be interested in seeing this added as well. Does TablePlus provide the option of specifying a custom database driver for new connections? Thanks for a great app, by the way!

**Comment by huyphams** [comment]
They have C/++ Driver: https://github.com/snowflakedb/libsnowflakeclient
Looks like it's possible to add to TablePlus.

**Comment by brupm** [comment]
👍

**Comment by estetoro** [comment]
👍

**Comment by jdiggans-twist** [comment]
👍

**Comment by bfarley-tb** [comment]
👍

**Comment by brupm** [comment]
Any news on this @huyphams?

**Comment by huyphams** [comment]
I can compile the driver but look like I need to register an account on Snowflake for testing? Is there any way to create a testing database, without register an account with a credit card?

**Comment by astewart-twist** [comment]
@huyphams - I'm not sure, but I'm happy to help test.

**Comment by huyphams** [comment]
Thanks @astewart-twist but let me create a trial account first, I think, the next TablePlus beta will support snowflake.

**Comment by huyphams** [comment]
Hey guys, I just signed as a partner of Snowflake and started working on this driver. Hopefully, we will have a beta version at the end of this week or the next week.

**Comment by astewart-twist** [comment]
Looking forward to it @huyphams !

**Comment by Chris1904** [comment]
Oh man, I was just about to throw this out here. Can't wait! If you need help to test anything, let me know!

**Comment by andyoneal** [comment]
looking forward to this. we've just started a trial with snowflake.

**Comment by daturkel** [comment]
Thank you! So excited to see this. Keep up the good work.

**Comment by huyphams** [comment]
There are some issues remaining before I can release this driver:
1. The session is not killed properly: https://github.com/snowflakedb/libsnowflakeclient/issues/106
it happens in all clients I know, not only in TablePlus, the only way to kill the session is closing the workspace before exit TablePlus app.
2. Some basic features are still missing.

**Comment by daturkel** [comment]
Some quality-of-life features might be: 
- ability to specify warehouse in the connection profile (otherwise you have to run `USE WAREHOUSE warehouse_name` before running a query
- table completion ignoring case for all-caps names. My understanding is that Snowflake is case-insensitive by default (rendering column/table names in all-caps), but case-sensitive if you put something in double-quotes. Currently autocomplete is suggesting `schema."TABLE"`, but I think `schema.table` is sufficient for 99% of cases.

**Comment by huyphams** [comment]
Just publish the beta build 147 that includes Snowflake @daturkel 
1. I have added Warehouse as your suggestion.
2. Disable auto add a double quote in case sensitive.

**Comment by daturkel** [comment]
Amazing! Thanks for fast response!

**Comment by astewart-twist** [comment]
woo!  Testing right now.  Session crashes as soon as I click 'connect'.  Happy to provide info for debugging.

**Comment by natesilva** [comment]
Wow, this is great! Thank you for adding it.

I have a suggestion: when setting up a connection, in the “Account” field, allow the user to type the full account name, such as `mycompany.snowflakecomputing.com` or  `mycompany.us-east-1.snowflakecomputing.com`. Currently it fails if you do that -- you have to type just the first part (`mycompany` or `mycompany.us-east-1`). You should be able to do it either way.

**Comment by huyphams** [comment]
Yeah, It's confusing me too. I don't know why Snowflake has decided to do that, the account is the first part of the host. It took me a while to figure out which is account and which is `user name`.
Let's me see if I can improve it.

**Comment by huyphams** [comment]
@astewart-twist the setup should look like this:
<img width="612" alt="abc" src="https://user-images.githubusercontent.com/3654622/47539688-bd5a4200-d8fb-11e8-813e-e70fd1fe50bf.png">

**Comment by astewart-twist** [comment]
@huyphams ah, ok - adding the `.us-east-` to the account looks like it's working.

**Comment by huyphams** [comment]
I don't know @astewart-twist this field is required by SnowflakeDB driver, I will submit a question ask them about it.

**Comment by huyphams** [comment]
Hi all, I have updated a snowflake driver and fix some critical bugs include the hanging bug.
https://github.com/TablePlus/TablePlus/issues/788
Please update to build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks.

**Comment by astewart-twist** [comment]
@huyphams - I think I've figured out the problem.  The format of the account name is going to vary based on the aws zone that the account is hosted in.  There's a full explanation of the different account naming conventions by region at https://docs.snowflake.net/manuals/user-guide/connecting.html#your-snowflake-account-name-and-url

> The format of the URL domain is different depending on the Snowflake Region where your account is located:
> 
> - US West: `account_name.snowflakecomputing.com`
> - Other regions:`account_name.region_id.snowflakecomputing.com`
> 
> Where `account_name` is the name of your account (provided by Snowflake) and `region_id` is:
> 
> 
> Cloud Platform | Region ID | Snowflake Region
> -- | -- | --
> AWS | us-east-1 | US East
> AWS | eu-west-1 | EU (Dublin)
> AWS | eu-central-1 | EU (Frankfurt)
> AWS | ap-southeast-2 | AP (Sydney)
> Microsoft Azure | east-us-2.azure | East US 2
> 
>
> For example, if your account name is xy12345:
> 
> - In US West, the URL would be xy12345.snowflakecomputing.com.
> - In US East, the URL would be xy12345.us-east-1.snowflakecomputing.com.
> - In EU (Frankfurt), the URL would be xy12345.eu-central-1.snowflakecomputing.com.
> - In East US 2, the URL would be xy12345.east-us-2.azure.snowflakecomputing.com.
> 


So it looks like the Snowflake connection in TablePlus is only taking into account the formatting for `us-east-1`, or at least all regions that aren't US West.

**Comment by astewart-twist** [comment]
@huyphams - I'll create a new issue for this since this one is closed out.
