### ISSUE TITLE
Beautify: Special characters like German Umlauts äüöß are not handled well

### ISSUE THREAD

**Issue by VanDerLars** [TablePlus/TablePlus#2311]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.2 (359)

3. The steps to reproduce this issue:

This is my Query:
```SQL
select t.*, (select name from touren_personen_kfz where tour_id = t.id and type = 2 and gültig_ab <= '2021-01-01' and gültig_bis >= '2021-01-01' LIMIT 1) as kfz from touren t;
```

I reformat it using "CMD + I" or "CTRL + I"

This is the output with CMD + I:
```SQL
SELECT
	t.*,
	(
		SELECT
			name
		FROM
			touren_personen_kfz
		WHERE
			tour_id = t.id
			AND TYPE = 2
			AND g ltig_ab <= '2021-01-01'
			AND g ltig_bis >= '2021-01-01'
		LIMIT 1) AS kfz
FROM
	touren t;
```
look at `g ltig_ab` -> the "ü" is vanished

This is the output with CMD + I:
```SQL
select
  t.*,
  (
    select
      name
    from
      touren_personen_kfz
    where
      tour_id = t.id
      and type = 2
      and g ü ltig_ab <= '2021-01-01'
      and g ü ltig_bis >= '2021-01-01'
    LIMIT
      1
  ) as kfz
from
  touren t;
look at `g ü ltig_ab` -> the "ü" has now spaces around.

Happens to most special, but utf-8 compliant characters.

Cheers :)

**Comment by jorygun** [comment]
Not sure if this is related, but i would like to be able to search for utf chars in a field.  If I search for ü I get every entry with a u in it.

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
