### ISSUE TITLE
Tables and triggers missing on open database

### ISSUE THREAD

**Issue by munntjlx** [TablePlus/TablePlus#2319]
1. Which driver are you using and version of it MariaDb

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.12.4

3. The steps to reproduce this issue:

Open any database

I used to get a list of tables and triggers, now all I see is:

![image](https://user-images.githubusercontent.com/48925191/108440471-35617a00-7221-11eb-9fb0-e0d780123bee.png)

I can do full sql queries, but not see tables inside my database.

**Comment by huyphams** [comment]
Hi @munntjlx have you collapsed the left sidebar? Please click the button on the top right corner.

**Comment by munntjlx** [comment]
Thanks that fixed it! I bought a license. great product!
