### ISSUE TITLE
Functions in non-public schemas do not show up at all

### ISSUE THREAD

**Issue by remotezygote** [TablePlus/TablePlus#232]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
87

3. The steps to reproduce this issue:
Create a function within a non-public schema. It does not show up in the "Functions" list in that schema.

**Comment by remotezygote** [comment]
It's also worth noting that functions inside non-public schemas also do not show up in the public schema. They show up nowhere, seemingly.

**Comment by huyphams** [comment]
Yup, I confirmed this bug. I'm investigating it.

**Comment by huyphams** [comment]
Hey can you check this build and let me know if it works 😄: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by remotezygote** [comment]
Works great!
