### ISSUE TITLE
Whenever sorting a column, it emits a system beep?

### ISSUE THREAD

**Issue by mikeerickson** [TablePlus/TablePlus#2321]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.12.2 (359)

3. The steps to reproduce this issue:

When displaying column of data, click on any column header (doesn't matter which column) you should hear the beep.  I have tried many different connections (I have 4 connections open at a time) nor does it matter which table/column is used.

**Comment by huyphams** [comment]
Hi @mikeerickson it could be another issue. I'm sure that if you restart the app, the issue will be gone. Could you please let me know before that, have you opened any windows popup in the app (like database popup, safe mode popup etc...)?

**Comment by mikeerickson** [comment]
@huyphams This instance of TablePlus has been running for quite some time so hard to say for sure.  I will go ahead and restart the app (which will lead to my [other issue](https://github.com/TablePlus/TablePlus/issues/2284) about preserving windows after restart as I will have to manually reopen the other 3 windows which are ssh connections).

**Comment by huyphams** [comment]
Finally, I can reproduce the issue now.
1. Open any popup (for example Open database popup by clicking the database button on the toolbar)
2. Press Command + W to close the popup.

I just fixed it and will release a new update tonight.
