### ISSUE TITLE
Trigger management section missing from windows version. 

### ISSUE THREAD

**Issue by JimmySalis** [TablePlus/TablePlus#2324]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 156

3. The steps to reproduce this issue:

The trigger management section on the table structure window is missing from Windows version of app. This is not explained in docs. After talking to helpline I'm told there is no release date for this. I'm putting this here to alert potential customers. The bug I'm reporting is a lack of information about this in docs or on website.

**Comment by huyphams** [comment]
Moved to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues/380

**Comment by JimmySalis** [comment]
Have the docs been updated now? I see the issue is closed?

**Comment by huyphams** [comment]
No, we move it to the Windows repo. This is the macOS issue tracker.

**Comment by huyphams** [comment]
the newest TablePlus windows suports triggers now.
