### ISSUE TITLE
Does not disconnect from SQLite database cleanly when quitting

### ISSUE THREAD

**Issue by davidbailey00** [TablePlus/TablePlus#2325]
**Which driver are you using and version of it (Ex: PostgreSQL 10.0):** SQLite 3.31.0

**Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):** 360

**The steps to reproduce this issue:**

1. Open a SQLite database with TablePlus
2. Quit TablePlus, e.g. using <kbd>Cmd+Q</kbd>

**Expected result:**

TablePlus disconnects from the database when quitting, as if I had used Connection → Disconnect

**Actual result:**

TablePlus does not disconnect before quitting.

When WAL is used, this can result in temporary files remaining alongside the database, such as `my.db-shm` and `my.db-wal` for a database named `my.db`

**Comment by huyphams** [comment]
Hi @davidbailey00 if you have a chance, please download this hot patch, if you still seeing the issue, please let me know:

https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by davidbailey00** [comment]
Thank you! I can confirm the hot patch fixes the issue.
