### ISSUE TITLE
Copy Insert Query from view data, issues with decimal type

### ISSUE THREAD

**Issue by Wit3** [TablePlus/TablePlus#2326]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Microsoft SQL Server ( Azure )

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 156

If i try to copy from data view of table a row, with the right click on the row and select -> Copy AS -> Insert Statement.

The query generated has one value more than the nr of fields declared, because one field is decimal (18,6) and the query split the value when occurence the "," in value field.

**Comment by huyphams** [comment]
HI @Wit3 thank you. We've fixed please wait for the next update.
Btw, this is our macOS issue tracker so I'm closing this issue.
