### ISSUE TITLE
When set Line Height > 1.0, text is not center of the line

### ISSUE THREAD

**Issue by dinhquochan** [TablePlus/TablePlus#2327]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): *

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 360

3. The steps to reproduce this issue:
- Set `Line height` > 1.0 (e.g: 2.0)
- Write something in the SQL panel

<img width="712" alt="Screen Shot 2021-02-27 at 12 29 24 AM" src="https://user-images.githubusercontent.com/9979458/109334887-e2786a00-7893-11eb-9e2e-66fa140c33b3.png">
<img width="1054" alt="Screen Shot 2021-02-27 at 12 30 58 AM" src="https://user-images.githubusercontent.com/9979458/109334892-e3a99700-7893-11eb-8e0e-d68f96ae1ddf.png">

**Comment by huyphams** [comment]
thank you for reporting the issue, if you have a chance, please try this hot patch and see how it goes: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0
