### ISSUE TITLE
Mono fonts in another panel is not same font settings

### ISSUE THREAD

**Issue by dinhquochan** [TablePlus/TablePlus#2328]
Dear,

Is it a bug? All mono-fonts in app should be once in settings!

<img width="1054" alt="Screen Shot 2021-02-27 at 12 38 47 AM" src="https://user-images.githubusercontent.com/9979458/109335296-6c283780-7894-11eb-90a4-4c7599e72381.png">

**Comment by huyphams** [comment]
Hi @dinhquochan it's intentional
