### ISSUE TITLE
Suggestion Drop Down makes typing SQL very slow

### ISSUE THREAD

**Issue by nd1012** [TablePlus/TablePlus#2329]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB - but doesn't matter at all, because it's not a problem with the driver for the DBMS

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.4 (360)

3. The steps to reproduce this issue:
Connect to any database which hosts multiple thousands of tables and enter a manual SQL command. The keyword suggestion drop down contains the table names and will be rebuild with every typed character, which slows down the whole thing and is very CPU and memory intensive, which is a huge performance issue.

I'm working with databases that host multiple thousands of tables (16K tables in one database f.e.). For me it'd be nice to have an option to switch off the keyword suggestion drop down, or to limit it to the SQL keywords only.

Also displaying the table list, which I don't want to use with such a huge number of tables (scrolling forever), does slowdown when connecting to a database - but I can live with that, since this is being done only one time when connecting.

Anyway, I think this is kind of very special and applies only for a small number of users. The keyword suggestion drop down is a nice feature, but in my case it makes the app unusable, because I need to work a lot with manual typed SQL statements.

**Comment by huyphams** [comment]
Hi @nd1012 have you tried to disable the auto suggestion?
<img width="663" alt="Screen Shot 2021-03-01 at 12 57 11 PM" src="https://user-images.githubusercontent.com/3654622/109458518-8b3ee900-7a8f-11eb-9332-fc69f1abe6b0.png">

**Comment by nd1012** [comment]
No, I didn't see that, but that's exactly what I need - thank you so much!
