### ISSUE TITLE
[Feature Request] master password

### ISSUE THREAD

**Issue by Link2Trials** [TablePlus/TablePlus#2330]
Instead of input a password by each change it is better to fill in a password when starting up the program..that saves a lot of time (for windows users)

**Comment by huyphams** [comment]
HI @Link2Trials this is the macOS repo, macOS has support fingerprint (and other method like Apple watch unlock etc...).

Regarding your issue, the safe mode is designed to prevent mistakes on production, not to secure the database, so the master password does not help.

if you have any issue with the app on Windows please report it here: https://github.com/TablePlus/TablePlus-Windows/issues, and don't forget to answer the issue template questions.
Thank you.
