### ISSUE TITLE
Cassandra - Invalid Integer Column Filter Escaping

### ISSUE THREAD

**Issue by qkdreyer** [TablePlus/TablePlus#2332]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): `Cassandra 3.11.3.5117`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): `Table Plus 3.12.4 (360)`

3. The steps to reproduce this issue:
- Execute the statement `CREATE TABLE "_test" ("id" INT, PRIMARY KEY (id));`
- Toggle Filter (⌘+F)
- Select the `id` column
- Filter with a valid integer value (i.e. `1`) and apply filter : `SELECT * FROM "_test" WHERE "id" = 1 LIMIT 300;`
- Filter with an invalid value (i.e. `a`) and apply filter : `SELECT * FROM "_test" WHERE "id" = a LIMIT 300;`
- Filter with the same previous valid integer value (i.e. `1`) and apply filter : `SELECT * FROM "_test" WHERE "id" = '1' LIMIT 300;` 
- Error : `Invalid STRING constant (1) for "id" of type int`
- The filter value is wrongly escaped

Note : Unsetting the table filters fixes the problem, until another invalid filter is applied

**Comment by qkdreyer** [comment]
http://g.recordit.co/sKYFmuidqt.gif

**Comment by huyphams** [comment]
I've fixed it, thanks @qkdreyer if you have a chance, please try this hotpatch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
it will be included in the next update.

**Comment by qkdreyer** [comment]
Thanks a lot for the fast support, it works 💯
