### ISSUE TITLE
Update datetime by NOW() on multiple records at once

### ISSUE THREAD

**Issue by inDeev** [TablePlus/TablePlus#2337]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB 10.5.9

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 360

3. The steps to reproduce this issue: Open any table with datetime values, select multiple rows and inside right panel (Row detail) enter value NOW() to the key of datetime format. Try to save, error alert appear:
**Incorrect datetime value: 'NOW()' for column `database`.`table`.`column` at row 1
All changes were reverted (DDL statements can't be reverted).**
If NOW() is manually entered to one or more datetime cells directly inside the table and saved, there is no issue. Value is converted to current datetime as expected.

**Comment by huyphams** [comment]
Hi @inDeev you can set NOW() by using the menu context, we will look into this issue and fix it in future releases.
<img width="545" alt="Screen Shot 2021-03-05 at 7 27 42 AM" src="https://user-images.githubusercontent.com/3654622/110049380-53cc8700-7d84-11eb-95c9-d94a1c9d6f3f.png">
