### ISSUE TITLE
Tables are not shown in cassandra : Missing "keyspace_name" column

### ISSUE THREAD

**Issue by vcanuel** [TablePlus/TablePlus#2338]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Cassandra 4.0.0.6811 (via DataStax on Demand Service)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 363

3. The steps to reproduce this issue:

I am connected to a cassandra instance on the new DataStax on demand service.

Unfortunately TablePlus cannot list tables. I got this error : `Schema queries require keyspace_name column"`

But I see this column via this query : 

SELECT *   FROM system_schema.keyspaces;
'keyspace_name' | 'durable_writes' | 'graph_engine' | 'replication' |  
-- | -- | -- | -- | --
'data_endpoint_auth' | t |   | '{"class":"org.apache.cassandra.locator.NetworkTopologyStrategy" | europe-west1:"3"}'
'datastax_sla' | t |   | '{"class":"org.apache.cassandra.locator.NetworkTopologyStrategy" | europe-west1:"3"}'
...

**Comment by huyphams** [comment]
Thanks @vcanuel let me take a look at it

**Comment by huyphams** [comment]
TablePlus uses this query to get the table list, I'm testing with Cassandra 4.0 and it works fine. Can you run this query at your end?

SELECT keyspace_name as table_schema, table_name as table_name FROM system_schema.tables where keyspace_name='<your_key_space_name>';

**Comment by vcanuel** [comment]
Indeed this query failed : 

`SELECT keyspace_name as table_schema, table_name as table_name FROM system_schema.tables where keyspace_name='data_endpoint_auth';`

`Query 1 ERROR: Schema queries require keyspace_name column`

Apparently keyspace_name is a valid column in this system.

`SELECT keyspace_name , table_name as table_name FROM system_schema.tables where keyspace_name='data_endpoint_auth';`

'keyspace_name' | 'table_name'
-- | --
'data_endpoint_auth' | 'token'

As DataStax Astra will be (I presumed) more and more used in the future, could you update this query in TablePlus ?

**Comment by huyphams** [comment]
I don't see anything wrong with the query:
```
SELECT keyspace_name as table_schema, table_name as table_name FROM system_schema.tables where keyspace_name='data_endpoint_auth';
```
You removed the alias `as table_schema` and it works?

**Comment by vcanuel** [comment]
Indeed it doesn't make sense...

I will contact DataStax to see what's wrong.

Thanks for your help.

**Comment by huyphams** [comment]
Btw, I removed the alias in the query in this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 if you have a chance, please give it a try

**Comment by vcanuel** [comment]
@huyphams It works as expected ! Thanks for this.

<img width="428" alt="Screenshot 2021-03-07 at 15 17 19" src="https://user-images.githubusercontent.com/167304/110242876-4962e680-7f58-11eb-8071-e9e7f81a6de4.png">

Now the question is : is this a bug from DataStax's implementation of Cassandra or a security feature (like to protect calls from sys tables..). ?

**Comment by huyphams** [comment]
Hmm I'm not sure but I just removed the alias, it made no sense to me because alias has nothing todo with the security.
