### ISSUE TITLE
Please add MongoDB support

### ISSUE THREAD

**Issue by lakamsani** [TablePlus/TablePlus#234]

**Comment by huyphams** [comment]
Hey thank for the suggestion, but Mongo Database is not a relational database. It's NoSQL document based and not easy to show it in the table grid.
If we support Mongo DB, we should build another application

**Comment by lakamsani** [comment]
Ok. Redis is not relational right? Values for redis keys can be arbitrary json documents.  Can the redis code be extended for MongoDB?

**Comment by huyphams** [comment]
We have a post about Redis, it's not a relational database but it's super simple key-value. We support Redis `very basic` (not full features) because user PostgreSQL/Rails are using it as a mem cache.

Mongo is not simple as that, and if we support it, people always want more feature (some of the features has a completely different design with the relational database. Ex: Query Style).

The mongo driver can lead us to become another DBeaver.

**Comment by spywhere** [comment]
Now Cassandra has been supported on TablePlus, would MongoDB possible?

**Comment by alnorris** [comment]
Personally, I'm 1+ on Mongo support. Most mongo guis out there use a table grid.

**Comment by ohld** [comment]
Any updates on this, guys? @huyphams

**Comment by jacurtis** [comment]
Just want to bump this.  I searched this on google to see if MongoDB was coming to TablePlus.

I understand it's not relational like postgres, mysql, etc but I see that we have Redis which is Key/Value store and similarish to MongoDB (its closer to MongoDB than it is to MySQL).  And now we have Cassandra which is usually compared very closely to MongoDB and is also a NoSQL database.  Most GUIs for MongoDB also use tableview with json tree to display database information, so its not too far off from what we already have.

With MongoDB support, this would be a perfect all-in-one database GUI. 

Robomongo (now Robo3T) is what most developers use for mongodb. Its open source, which might also assist your team (https://github.com/Studio3T/robomongo)

**Comment by vesper8** [comment]
awesome!!!

**Comment by Atomzwieback** [comment]
appreciate it aswell

**Comment by huyphams** [comment]
It's here: https://twitter.com/TablePlus/status/1088468373732638720

**Comment by emargareten** [comment]
Does the windows version support mongo as well?
