### ISSUE TITLE
Connecting with jdbc:as400://

### ISSUE THREAD

**Issue by pmindrup** [TablePlus/TablePlus#2344]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): JTOpen - jt400.jar 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.12.5 (363)

3. The steps to reproduce this issue:  

Trying to create a new connection using "Import from URL" - this results in the error message "Invalid URL."

**Comment by huyphams** [comment]
Hi, TablePlus is a native app so we could not use the JDBC URL.

**Comment by pmindrup** [comment]
OK – guess I was confused by this page on the Table Plus site:

 

https://tableplus.com/blog/2019/09/jdbc-url-formats.html

 

Thanks,

Paul
