### ISSUE TITLE
Feature request: Read credentials from environment variables

### ISSUE THREAD

**Issue by johnbillion** [TablePlus/TablePlus#2349]
It would be great if database connection credentials could be read from environment variables whose names are specified in the connection configuration. This would be especially useful for connections over SSH.

For example, I'd like to provide the SSH host name and SSH key for a connection, but then have the database host, port, user, password, and database name populated via some `RDS_*` environment variables that exist on the remote server. This would mean I don't first need to manually SSH into the server to fetch the database credentials and store them locally.

I imagined it could work by specifying something like `$RDS_HOST` in the database `Host` field which instructs TablePlus to read this value from the environment variable of that name after opening the SSH connection, but this doesn't work for all fields because that could also be a valid password or username, however unlikely.

**Comment by Ojasv-Singh-Zeotap** [comment]
I support it. Would be great to have a configuration file to read from or environment variable

**Comment by derekbunch** [comment]
i would also like to see this

**Comment by huyphams** [comment]
Hi @johnbillion this build should support it:
https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0

<img width="576" alt="CleanShot 2022-09-26 at 11 32 12@2x" src="https://user-images.githubusercontent.com/3654622/192194384-e63a41d1-8269-49aa-8cec-e6c621d31bf5.png">
