### ISSUE TITLE
Query is very slow

### ISSUE THREAD

**Issue by euii** [TablePlus/TablePlus#235]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- MySQL 5.7.19
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- Version 1.0 (87)
3. The steps to reproduce this issue:
   - connect to db by over ssh  
   - open query tab and input query sql and RUN ALL 
   - tablePlus notices "Executed Statements Count 0/1 " for long time, display speed xx b/s at top-right

![xnip2018-02-41_10-49-55](https://user-images.githubusercontent.com/701552/36057904-4ccd1bb4-0e50-11e8-9d78-89cdffe4991a.jpg)

**Comment by huyphams** [comment]
Did you feedback on TablePlus feedback popup 😄 I see a lot of feedback there but they didn't put their email so I can't reply to them.

Btw, this is weird, I will investigate this issue to figure out what happened.

**Comment by euii** [comment]
Yes I did it. I forgot leave mail address ;)

**Comment by euii** [comment]
sorry,  response for long time, today I upgrade table plus to newest version [1.0(103)], the same issue is still existing.
