### ISSUE TITLE
Table Search is Not Accurate

### ISSUE THREAD

**Issue by ddarbyson** [TablePlus/TablePlus#2351]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

- n/a

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.12.5 (364)

3. The steps to reproduce this issue:

When searching tables, the results should not assume other matching characters… Or maybe it’s an issue with underscores, not sure (see attached)

For example, In a WordPress multisite install you have hundreds of tables with ID suffix to table_prefix to allow sites to be created by the hundreds. I should be able to search for `wp3_11_` exclusively and only those tables matching that search prefix should appear.

Unfortunately I also see `wp3_118_, wp3_119_, wp3_110_` etc. and anything that has the characters wp3_11 in there.

<img width="334" alt="Screen Shot 2021-03-12 at 1 07 47 PM" src="https://user-images.githubusercontent.com/1116416/110980584-fad89200-8333-11eb-9d30-a3ac9a20e26c.png">
1endnh6cN26PXX2wN62i7b8Mr/view?usp=sharing

**Comment by huyphams** [comment]
TablePlus use fuzzy search by default. You can force it to search by:
1. Use double quote for contains: "value"
2. Use regex for previx: ^value
3. Use regex for suffix: value$
