### ISSUE TITLE
DROP KEY should be before DROP COLUMN

### ISSUE THREAD

**Issue by humancopy** [TablePlus/TablePlus#2352]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
`MySQL 8`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
`364`

3. The steps to reproduce this issue:
Try to delete both a column and a key. TablePlus always puts the `DROP COLUMN` before `DROP KEY` which doesn't work well for unique keys. MySQL complains of duplicates. 

TablePlus should put the `DROP KEY` & `DROP CONSTRAINT` queries before `DROP COLUMN`

**Comment by huyphams** [comment]
This build should fix the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
