### ISSUE TITLE
After switching from Redis db0 to db1, when returning to db0, only db1 entries are shown

### ISSUE THREAD

**Issue by JackWH** [TablePlus/TablePlus#2353]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Redis 6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.12.5 (364)

3. The steps to reproduce this issue:

* Open a Redis connection to a Redis server with `db0` and `db1` defined
* Click on `db0` in the sidebar to show the entries from `db0` database
* Click on `db1` in the sidebar to show the entries from the `db1` database
* Click back to `db0` in the sidebar. Whilst `db0` gets given an active state in the UI, only entries from `db1` appear
* Clicking back and forth between both DBs will now only ever show entries from `db1`

It appears you can "fix" this by manually issuing a `SELECT 0` command in the SQL editor. But that fix is only temporary until the next time you click between the DBs in the sidebar.

**Comment by markstephenburnham** [comment]
This is still an issue in Version 4.2.0 (388).

**Comment by huyphams** [comment]
Hi @markstephenburnham could you run this command and post the result here: INFO keyspace

Thank you

**Comment by huyphams** [comment]
If you have a chance, please try this hotpatch, if you are still seeing the issue please let me know: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks!

**Comment by markstephenburnham** [comment]
Beautiful!  Thank you - looks great!!
