### ISSUE TITLE
Feature Request: SQL files workspace/folder

### ISSUE THREAD

**Issue by ff6347** [TablePlus/TablePlus#2354]
Thank you for working on TablePlus. It is an awesome piece of software. I would love it even more if I could set a folder where all the sql tabs are saved/loaded from as a file. This would make my live so much easier.

**Comment by huyphams** [comment]
Hi @ff6347 you can do it within the Queries tab, thanks!
<img width="959" alt="Screen Shot 2021-03-17 at 2 28 55 PM" src="https://user-images.githubusercontent.com/3654622/111430592-27721c80-872d-11eb-86a7-6e35280b85d1.png">

**Comment by ff6347** [comment]
Oh. Cool. Makes TablePlus even more awesome! Thanks
