### ISSUE TITLE
Pin to top is not saved

### ISSUE THREAD

**Issue by lutek** [TablePlus/TablePlus#2357]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 8.0.22

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.5 (365)

3. The steps to reproduce this issue:
Pin to top is not saved. After restarting the app they disappear. 
I use the option to save settings in iCloud `/Users/lutek/Library/Mobile Documents/com~apple~CloudDocs/TablePlus`

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @lutek please do not remove issue template questions. It helps us to track the issue

**Comment by lutek** [comment]
Sorry, I've updated the issue
