### ISSUE TITLE
Redis Driver

### ISSUE THREAD

**Issue by ideaalloc** [TablePlus/TablePlus#236]
1. Redis 4.0.6

**Comment by goldalworming** [comment]
+1

**Comment by huyphams** [comment]
I just tested and it works on redis 4.0.6 and the latest version 4.0.8

<img width="1228" alt="screen shot 2018-02-11 at 6 56 51 pm" src="https://user-images.githubusercontent.com/3654622/36073078-56880430-0f5d-11e8-9b73-a0acb1f0fa06.png">

**Comment by coredumperror** [comment]
Does the "4.0.6" in the first comment on this thread mean that TablePlus only supports redis servers of that version? I ask because I have a redis 3.2.4 server running in a local docker network, and while TablePlus can show me the contents of the database, I can see only the keys. There does not seem to be any way to access the *values*.

**Comment by huyphams** [comment]
No, TablePlus works with Redis 3.2.4, you see only keys because this driver is still under development

**Comment by coredumperror** [comment]
Thanks. I thought that might be it, but I wanted to confirm.

**Comment by Ilyes512** [comment]
Is there somewhere where we can track the progress of the Redis driver (the backlog).

**Comment by huyphams** [comment]
We only have on public roadmap here: https://github.com/TablePlus/TablePlus/projects/1
if you want any feature, you can create an issue for tracking that feature 👍

**Comment by Ilyes512** [comment]
Well I can see the keys now, but I can see the value and other possible meta data like TTL. I would be nice if there an issue with all (minimal) features that are needed for a "complete" redis client.

**Comment by huyphams** [comment]
I just created new issues for this @Ilyes512 https://github.com/TablePlus/TablePlus/issues/275

**Comment by tomspeak** [comment]
+1 for redis client. Would love even the basic ability to view a redis store.

Selfishly, for my set up, once Redis is implemented, TablePlus is a complete solution for me!

**Comment by fedor-r** [comment]
+1 for redis client. Basic view /delete record will be nice to have

**Comment by abashev** [comment]
+1 for redis

**Comment by oujingwen** [comment]
+1 for redis

**Comment by huyphams** [comment]
Hey guys, good news. TablePlus next update will support Redis officially and here is the early build include that support. It would be great if you guys can give it a try and let me know your thought.

Download: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

This build can self-upgrade when the official is released, so don't worry.

**Comment by coredumperror** [comment]
From my quick perusal, this looks good!
