### ISSUE TITLE
Improve tab behavior

### ISSUE THREAD

**Issue by jonorozcoc** [TablePlus/TablePlus#2361]
I consider we'll have a better user experience if we make some changes to the way tabs are opened

For somebody that uses many tables temporally will open many tabs and we have to close those tabs to keep everything organized.

1. Overriding the current active tab if I press click on a table and the current tab is not an SQL query
2. Pressing double click into a table will open a new tab

**Comment by huyphams** [comment]
Are you using the Windows verison @jonorozcoc because the macOS has this behaviour

**Comment by jonorozcoc** [comment]
@huyphams I'm using Windows version

**Comment by huyphams** [comment]
Thanks, please submit to the [Windows repo](https://github.com/TablePlus/TablePlus-Windows/issues) next time and don't remove the issue template questions.

I found a similar issue: https://github.com/TablePlus/TablePlus-Windows/issues/353
