### ISSUE TITLE
How can I use --no-privileges when exporting a database?

### ISSUE THREAD

**Issue by CE-Creates** [TablePlus/TablePlus#2362]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 12.0.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.12.2 (358) on MacOSx

3. The steps to reproduce this issue: I can create a dump file with the backup feature. but I cant restore the same file. It shows. Role "XXX" not found.

**Comment by huyphams** [comment]
Hi you can add the flag directly into the box (copy and paste), because it is editable:
<img width="772" alt="Screen Shot 2021-03-23 at 3 04 50 PM" src="https://user-images.githubusercontent.com/3654622/112113438-61d63080-8be9-11eb-808f-cfd0313a1f7d.png">
