### ISSUE TITLE
MSSQL - Getting "Incorrect syntax near 'FIRST'" error when adding column

### ISSUE THREAD

**Issue by timsayshey** [TablePlus/TablePlus#2365]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2019 15.0.4073.23 (X64) 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.5 (364)

3. The steps to reproduce this issue:
Create a table. Save it. Then open it and try to add a column, then try saving. You will get the following error: 
`Incorrect syntax near 'FIRST'.`

I have no idea where FIRST is coming from. Removing it from the resulting query fixes the issue but TablePlus keeps adding it.

Screenshot:
![image](https://user-images.githubusercontent.com/1148940/112374048-a3311380-8caf-11eb-9b0f-0afa29d6eb6b.png)

**Comment by huyphams** [comment]
Hi @timsayshey please install this hot patch, it should fix the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thank you for letting us know.
