### ISSUE TITLE
Feature request: run query from file

### ISSUE THREAD

**Issue by moltar** [TablePlus/TablePlus#2366]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.12.5 (364)

---

Sometimes when I am working on queries for an application, I need to edit and re-run them many times. Then copy paste them back to the application, and if I need to fix them, I need to copy paste them back to the GUI.

I wish there was a way to maintain the query in a local `.sql` file, and then be able to run it thru TablePlus. Upon editing and saving of the file in an IDE, TablePlus would refresh the contents of the query window from that said file.

Bonus checkbox: auto-run queries on save.

**Comment by huyphams** [comment]
Hi @moltar please checkout this issue https://github.com/TablePlus/TablePlus/issues/2354
