### ISSUE TITLE
Redundant index created for primary keys in MariaDB

### ISSUE THREAD

**Issue by s0xDk** [TablePlus/TablePlus#2368]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **MariaDB**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **364**

3. The steps to reproduce this issue: create new table with primary key

When you create new table with primary key (default), TablePlus(?) creates two separate indexes: **PRIMARY** and **id UNIQUE**. It's redundant.

<img width="460" alt="Screenshot 2021-03-28 at 16 11 06" src="https://user-images.githubusercontent.com/44265/112753412-35068c80-8fe0-11eb-81d1-05fcdc3f13ce.png">

**Comment by huyphams** [comment]
It was created by MySQL/MariaDB not TablePlus, you can see the preview statement below:

<img width="1543" alt="Screen Shot 2021-08-30 at 6 00 28 PM" src="https://user-images.githubusercontent.com/3654622/131329535-6d12b1db-abde-45f6-ba82-77db49a84c39.png">
