### ISSUE TITLE
MS SQL 2019 Unable to edit table structure

### ISSUE THREAD

**Issue by grey280** [TablePlus/TablePlus#2370]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2019

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
364

3. The steps to reproduce this issue:
Any attempt to edit the schema of an existing table seems like it will work, but when I attempt to save, I receive the following error:

<img width="270" alt="Screen Shot 2021-03-29 at 13 52 55" src="https://user-images.githubusercontent.com/2984983/112898957-5f1a8600-9096-11eb-89e5-59c9e1f50864.png">

It's very possible that there's something wrong with the database, but if so, I'm unable to get enough diagnostic information out of TablePlus to figure out what's going on.

**Comment by huyphams** [comment]
Hi, please update the latest release 366 it should fix the issue.

**Comment by grey280** [comment]
That worked, thank you!
