### ISSUE TITLE
Small autocomplete dropdown

### ISSUE THREAD

**Issue by syabro** [TablePlus/TablePlus#2373]
TablePlus 3.12.5 (364)

<img width="451" alt="image" src="https://user-images.githubusercontent.com/29029/113107403-8dba6d00-920c-11eb-8965-30198603e808.png">

How can I make it wider? Its very hard to use now :(

**Comment by huyphams** [comment]
<img width="712" alt="Screen Shot 2021-03-31 at 7 29 52 PM" src="https://user-images.githubusercontent.com/3654622/113144473-78b6fb80-9257-11eb-889f-fee511294b3a.png">

**Comment by syabro** [comment]
Emm I way talking about symbols count in line, not font size. 
Having ... instead of real letter sucks

**Comment by syabro** [comment]
@huyphams ping?
