### ISSUE TITLE
Update the wrong database after SQL query

### ISSUE THREAD

**Issue by Lp-Francois** [TablePlus/TablePlus#2377]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
3.12.6 MYSQL 8, on Mac OS

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
(build366)

3. The steps to reproduce this issue:

- Open 1 connection to a remote database
- Connect to one database named AAA and run a SQL query on it such `SELECT * FROM `AAA`.`mytable` ORDER BY `something` LIMIT 300 OFFSET 0;`
- You should see a list of rows corresponding to the previous request
- Now, change the SQL request to use another database: `SELECT * FROM `BBB`.`mytable` ORDER BY `somethingelse` LIMIT 300 OFFSET 0;`
- You should see a list of rows corresponding to the previous request, with values from the BBB database.
- Now double click on one value and change it. Then save. The request sent is updating AAA with the select values of BBB. 
- example:  UPDATE `AAA`.`mytable` SET... = 2 WHERE `id` = 52;

Expected behavior: Modifying the results from a query on one database should Update the same database.

**Comment by Irutehe** [comment]
Hi,
I encountered another version of this issue.


    Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    3.12.6 MYSQL 8, on Mac OS

    Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    (build376)

    The steps to reproduce this issue:

1. Run a query with at least 2 joins: 
`select b.* from a_table as a 
join b_table b on a.id = b.a_table_id
where a.id = 1;`
2. Modify a value in the results set
3. Commit changes
4. The update will happen on **a** table, instead of **b** table.

Expected behavior: The update will be made on **b** table.

**Comment by Lp-Francois** [comment]
TablePlus Team seems to ignore this issue, so I close it
