### ISSUE TITLE
Activity monitory shows intel architecture with TablePlus build367

### ISSUE THREAD

**Issue by MapleLove2014** [TablePlus/TablePlus#2379]
TablePlus version:
![image](https://user-images.githubusercontent.com/34023519/113851338-fd60c700-97cd-11eb-976f-63a8ae5768de.png)

architecture:
![image](https://user-images.githubusercontent.com/34023519/113851526-2bdea200-97ce-11eb-9f44-6a7766c938b8.png)

**Comment by huyphams** [comment]
Hi @MapleLove2014 please use our latest release https://tableplus.com/release/osx/tableplus_latest the beta support Oracle so it's not possible to build for ARM.
Thanks
