### ISSUE TITLE
Invalid usage of the option NEXT in the FETCH statement

### ISSUE THREAD

**Issue by jbrooksuk** [TablePlus/TablePlus#238]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

    Microsoft SQL Server 2008

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

    Build 87

3. The steps to reproduce this issue:

    Try to view table data on a Microsoft SQL Server 2008 database.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/246103/36060300-ada00044-0e3e-11e8-8753-9c0474a0145c.png">

**Comment by huyphams** [comment]
It's duplicated with: https://github.com/TablePlus/TablePlus/issues/225

**Comment by huyphams** [comment]
Hi @jbrooksuk can you help me test this statement in SQL Query:
`SELECT * FROM <table> ORDER BY 1 BETWEEN 0 AND 5;`

I didn't have any MS SQL Server 2008 for testing.

**Comment by jbrooksuk** [comment]
> Incorrect syntax near the keyword 'BETWEEN'.

**Comment by huyphams** [comment]
Ok, I will install a Virtual machine and install MS SQL 2008 😄

**Comment by jbrooksuk** [comment]
Thanks @huyphams!

I'll be purchasing a license soon enough :)

**Comment by huyphams** [comment]
Hi @jbrooksuk it's fixed in this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Can you give it a try and let me know if it works for you 😄

**Comment by jbrooksuk** [comment]
@huyphams this is working perfectly. Thanks 🚀
