### ISSUE TITLE
Show table by typing name after clicking on table in left column.

### ISSUE THREAD

**Issue by kachelle** [TablePlus/TablePlus#2385]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.5 (364)

3. The steps to reproduce this issue:

- Click on a table
- Type the table name you want to select (in my case 'migrations' ).
- Normally the 'migrations' table should be shown, but it is always the one you have clicked on.
- (work around is arrow up & down).
Steps in video:
https://user-images.githubusercontent.com/33377566/114610523-4ddd9600-9ca0-11eb-958b-5ee1d8923174.mov

**Comment by huyphams** [comment]
Hi @kachelle you can download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
When you hit enter, it will open the table.
