### ISSUE TITLE
feature suggestion: Duplicate Table(Copy Table). (PS: Sequal Pro And Sequal Ace has it.)

### ISSUE THREAD

**Issue by cnzx219** [TablePlus/TablePlus#2388]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

mysql 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

366

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

Sequal Pro And Sequal Ace has a features: Duplicate Table (Copy Table). When i backup and test data, it's convenience.

**Comment by huyphams** [comment]
You can right click on a table and select clone... it will do the same thing as Sequel Pro.
