### ISSUE TITLE
Modify tinyint(1) value on a record by double clicking on it does not work

### ISSUE THREAD

**Issue by akoury** [TablePlus/TablePlus#239]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite 3.21.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 87

3. The steps to reproduce this issue:
I have a database with products, I have a 'published' column which is simply a tinyint(1) data type, I can modify all values of the records in the table (for example the name column) by clicking directly on the value, however when I double click the tinyint(1) value it does not let me modify it directly, I can however modify it by editing it in the right sidebar (row detail) that appears when I click on the record.

It is a minor bug, however I thought I should let you know because this is a great product and it seems like you pay attention to tiny details like these.

Thanks for all the hard work!

**Comment by huyphams** [comment]
Yes, I actually care all the tiny detail 😄

**Comment by huyphams** [comment]
It's fixed 😄 
You can download new build here: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
