### ISSUE TITLE
[Feature Request] Group tables in the database view

### ISSUE THREAD

**Issue by MasonSpeed** [TablePlus/TablePlus#2391]
In the same way that "Functions" and "Tables" are grouped in a kind of accordion, it'd be great if we could group our actual tables together

So for example, I have an app with 30+ tables, being able to group them by functionality (User tables, product tables, pivot tables etc etc) would make finding things a lot easier and manageable

**Comment by huyphams** [comment]
We're working on it, along with many other group rules. Please wait for the next update!

![2022-09-03 16 19 06](https://user-images.githubusercontent.com/3654622/188264458-8226ff96-d645-4986-bb68-da8d9df50aa7.gif)

**Comment by nawlbergs** [comment]
I have 2 Issues with the Group implementation
 - You can't re-order them.. (ones you create first are just stuck at the top)
 - You can't set a filter priority... (if two tables match the pattern for a group... which one should it go into?)

**Comment by ReessKennedy** [comment]
Table groups seem to only last for the sessions but go away when I close and reopen. Is this expected? Seems like would be way better to have the persist given time to set them up. Maybe I am missing something?
