### ISSUE TITLE
Apply All button resets all column filter fields 

### ISSUE THREAD

**Issue by L1nuxF4n** [TablePlus/TablePlus#2396]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.6 (Build 366)

3. The steps to reproduce this issue:
I'll have some field filters, some used  and some unchecked. Then I'll uncheck them all to just refresh the entire table i have open and then I'll click on Apply All so I don't have to refresh the whole connection. All of the individual fields reset to the top field name in the drop down. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @L1nuxF4n thank you for letting me know. I will fix this bug in the next update. In the meantime, you can click `Unset` it will reload the table without the filter.
<img width="399" alt="Screen Shot 2021-04-28 at 6 10 04 PM" src="https://user-images.githubusercontent.com/3654622/116394324-f832ed00-a84c-11eb-8272-c7fa420330ca.png">

**Comment by huyphams** [comment]
I could not reproduce it on the latest release, please let me know if you are still seeing the issue.
