### ISSUE TITLE
Exports with templates, or at least option to add current timestamp, connection name

### ISSUE THREAD

**Issue by dmythro** [TablePlus/TablePlus#2397]
Currently export name uses DB name only. Which is non-informative on consequent backups/exports.
I personally would be really glad if we could export with name using: connection name, DB name, current date/time.

I'd prefer ability to format exports like this:
1. Connection name, DB name, Date-time (`Connection Name "some_db_name" 2021-04-24 12-34.56`)
2. Connection name, DB name (`Connection Name "some_db_name"`)
3. DB name

Maybe with options to escape unsafe characters, lowercase/uri format. Maybe other date formats (But `YYYY-MM-DD HH-mm.ss` is probably the most common to use).

P.S. Thanks for the app, glad to support it with license, hope it'll only get better :)

**Comment by huyphams** [comment]
Hi, you can click to the button below the name to change its pattern, all of that are supported.

**Comment by dmythro** [comment]
Wow, I didn't know it's clickable, looks disabled. You definitely should update UI a bit :) 
How do I add space there?

**Comment by huyphams** [comment]
I think there is a "space" pattern in the option (the last option), if you want any characters/words that do not exist in the list, you can just enter it in the text box directly.
<img width="570" alt="Screen Shot 2021-04-25 at 1 02 52 PM" src="https://user-images.githubusercontent.com/3654622/115982592-aa0cb800-a5c6-11eb-9cdf-bb87a839beff.png">

**Comment by dmythro** [comment]
Yes, that wasn't obvious for a quick try but found that too. Usually fields like this behave a bit differently from what I tried (like path templates for Capture One Pro).

**Comment by dmythro** [comment]
Thanks for the quick reply anyways :)
