### ISSUE TITLE
Make Passwords distinguishable in Apple KeyChain

### ISSUE THREAD

**Issue by chinito** [TablePlus/TablePlus#2398]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
n/A
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.6 (366)

3. The steps to reproduce this issue:
- Go to Apple Key Chain, use the Search and type in "Table" or "Tableplus"
- See all saved Passwords, try to find the one you are looking for, all are named "TablePlus"

Solution: Add connection name to it
[screenshot.pdf](https://github.com/TablePlus/TablePlus/files/6385039/screenshot.pdf)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @chinito you can see the connection password by go to the welcome screen, right-click > Copy as URL.

If you don't want to expose the password, you can change the safe mode so it will authorized with touchID before letting you copy the URL.

**Comment by chinito** [comment]
Thanks @huyphams I was looking in the Apple Keychain, as it said it stores the PW there. And this feature is not very obvious though. Thanks anyway!

**Comment by huyphams** [comment]
Yeah I think so, but it is a little bit low level for the users to find out the connection's password, it also needs to be kept synching when we change the name so we have to update it more frequently.

**Comment by chinito** [comment]
Is it a big issue? The guys from Sequel Pro do it right. 
![image](https://user-images.githubusercontent.com/1230894/116395837-edfcf880-a824-11eb-85e4-705d4e8dcd84.png)
