### ISSUE TITLE
Feature Request: Make it so that filters default to "=" instead of "contains"

### ISSUE THREAD

**Issue by carkar7** [TablePlus/TablePlus#2399]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.0.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.6 (366)

We use this tool at our company and one of the major gripes is that filters are defaulting to contains, when "=" is the expected function. Accidentally triggering a filter with "contains" can substantially increase the time it takes to filter results.

**Comment by huyphams** [comment]
Hi, there is a setting button on the left of the filter where you can change the default to =
