### ISSUE TITLE
Option to order DBs by name, by size, and by most frequently used (and to remember your option choice for future viewing) - also add scroll bar to the DB selection window.

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#24]
![screen shot 2017-07-28 at 10 31 07 pm](https://user-images.githubusercontent.com/7946786/28742462-9826be86-73e5-11e7-9fba-30bfd87f6108.png)

Like picture and title say, these improvements could speed up access to my most used DBs.

I understand the 'most frequently accessed db' may be a little tricker to implement, but possibly you could just have a local count for each db and environment.

**Comment by huyphams** [comment]
Excellent @MrGundBear , order in DBs popup is nice but I think `most frequently used` can be done by clone an other connection. I'm trying to use `Open anything...` - `command + P` to switch between databases.

**Comment by huyphams** [comment]
Open anything remembers last matched and high priority
<img width="1103" alt="screen shot 2017-11-01 at 9 48 15 am" src="https://user-images.githubusercontent.com/3654622/32257825-e5a85058-bee9-11e7-8f3e-b19c96133b18.png">
