### ISSUE TITLE
AWS Aurora SSL Over SSH Not Working

### ISSUE THREAD

**Issue by richcorbs** [TablePlus/TablePlus#240]
Build 87. Trying to connect to a MySQL database.

To reproduce:

1. Configure an AWS Aurora instance to use SSL over SSH as in the screenshot.

<img width="506" alt="screen shot 2018-02-10 at 1 07 46 pm" src="https://user-images.githubusercontent.com/437167/36066277-4a732142-0e64-11e8-940b-95b3d2ea11f1.png">

2. Use "Test" or "Connect" buttons to try to connect.

Expected: Connect to AWS Aurora instance.

What happened: SSH connection was successful but SSL threw an error "Unable to get certificate". See screenshot below.

<img width="478" alt="screen shot 2018-02-10 at 1 08 03 pm" src="https://user-images.githubusercontent.com/437167/36066278-4a9bffcc-0e64-11e8-81c5-3ba046789d81.png">

Note: In SequelPro the SSL over SSH connection works. In SequelPro with SSL disabled the connection fails. Disabling SSL is not an option.

**Comment by huyphams** [comment]
Thanks @richcorbs, could you try this build and let me know if it works: https://www.dropbox.com/s/75zgayubxmtj85i/TablePlus.zip?dl=0

**Comment by richcorbs** [comment]
Hi Huy,

That build works with SSL over SSH for both of my Aurora clusters!

Awesome work!

Rich
