### ISSUE TITLE
Safe UPDATEs & DELETEs (SET SQL_SAFE_UPDATES=1)

### ISSUE THREAD

**Issue by jolipixel** [TablePlus/TablePlus#2400]
Love TablePlus, awesome job!

However, one feature I miss from MySQL Workbench is the Safe Updates option : 

![image](https://user-images.githubusercontent.com/1130836/116323569-93c94c80-a7be-11eb-874e-206c6af25a3e.png)

It blocks **UPDATE** and **DELETE** queries when they are executed **without a WHERE clause on a column that uses a KEY**.

Technically, it simply sends a `SET SQL_SAFE_UPDATES=1;` on all MySQL sessions.

Here is a demo with the error message on TablePlus : 

![image](https://user-images.githubusercontent.com/1130836/116323914-54e7c680-a7bf-11eb-85f0-61f3e9bf0f6b.png)

A _Safe Query toggle_, like the one for [Safe Mode](https://docs.tableplus.com/gui-tools/code-review-and-safemode/safe-mode) would be perfect.

As a work around solution, is it currently possible to set a default query to all newly created sessions?

**Comment by huyphams** [comment]
Hi @jolipixel you can add this command to the bootstrap query, like this:

<img width="1035" alt="Screen Shot 2021-04-28 at 5 58 39 PM" src="https://user-images.githubusercontent.com/3654622/116393059-6080cf00-a84b-11eb-9a52-a4d51925d259.png">
