### ISSUE TITLE
Please add a new shortcut for back to the last open SQL Editor;

### ISSUE THREAD

**Issue by oknixus** [TablePlus/TablePlus#2401]
Open a new SQL Editor using `cmd + E`, but if want to back the last open SQL Editor that only by clicking mouse;

So please add a shortcut for back to the last open SQL Editor.

Thanks🙂

**Comment by huyphams** [comment]
Hi @oknixus you can use command + number.

P/s Please do not remove the issue template questions.

**Comment by oknixus** [comment]
> Hi @oknixus you can use command + number.
`cmd + number` only switch to the target SQL Editor, that does not make the cursor into the editor. 
After switched, need to click mouse again. 

Sorry, I am a heavy Vimer.
