### ISSUE TITLE
can not show emoji

### ISSUE THREAD

**Issue by AsanZhang** [TablePlus/TablePlus#2402]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.6 (366)

3. The steps to reproduce this issue:
a column value is 冷门歌手👩‍🎤

Noted: If the bug is related to data, please attach an example SQL data.
冷门歌手👩‍🎤

**Comment by AsanZhang** [comment]
it shows like follow：
![image](https://user-images.githubusercontent.com/4980914/116541749-71e6db80-a91e-11eb-9efe-e2b102c2106b.png)

**Comment by huyphams** [comment]
Hi @AsanZhang have you tried to change the view encoding?
<img width="785" alt="Screen Shot 2021-04-29 at 6 10 29 PM" src="https://user-images.githubusercontent.com/3654622/116541877-321bf600-a916-11eb-9547-b82d774e10c9.png">

**Comment by AsanZhang** [comment]
> Hi @AsanZhang have you tried to change the view encoding?
> <img alt="Screen Shot 2021-04-29 at 6 10 29 PM" width="785" src="https://user-images.githubusercontent.com/3654622/116541877-321bf600-a916-11eb-9547-b82d774e10c9.png">

@huyphams ok. it works.therefore how could I make utf8mb4 as the default encoding view?

**Comment by huyphams** [comment]
Thanks, it's default settings. You only need to change it 1-time.
