### ISSUE TITLE
UI crash when instantly deleting new folder (before naming it)

### ISSUE THREAD

**Issue by erikforss** [TablePlus/TablePlus#2404]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
It is an UI related bug, doesn't depend on the driver.
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.6 (366) on macOS Catalina v10.15.5 (19F101)
3. The steps to reproduce this issue:
   1. Open Table Plus
   2. Switch Tabs to `Queries` 
   3. Create a new Folder (or sub folder)
   4. Delete it, before naming it (so before it is actually created)
To reproduce, see gif attached
![TablePlusUiBug](https://user-images.githubusercontent.com/40789770/116652884-63cca580-a986-11eb-8ac5-4d009c996b37.gif)

**Comment by huyphams** [comment]
Hi, I just fixed it, thank you for letting me know. You can download the hot patch here: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by erikforss** [comment]
Wow, that was quick!
TablePlus is really a great tool, thanks for your work guys!
