### ISSUE TITLE
suggestion - option to prompt before closing unsaved tab

### ISSUE THREAD

**Issue by AlexHello** [TablePlus/TablePlus#2405]
Version 3.12.6 (366) / Postgres - OS X 11.3

Please can we have the option to prompt before closing unsaved Tabs. I often have many tabs open reducing the size of them, which leads quite often to me accidently closing a tab that was not saved. That is clicking the little x by mistake.

It would be good to have the option to prompt before closing a tab that has unsaved data in it.

<img width="1301" alt="Screenshot 2021-04-30 at 13 11 57" src="https://user-images.githubusercontent.com/1131580/116693356-b6718600-a9b5-11eb-946f-9eeb07fe5428.png">

**Comment by huyphams** [comment]
You can turn off the auto save in the TablePlus settings.

Thanks!
