### ISSUE TITLE
PostgreSQL allows connection without opening database only if database is named the same as user

### ISSUE THREAD

**Issue by rdebled** [TablePlus/TablePlus#2408]
Postgres 10.5

TablePlus 3.12.6

When configuring a new connection the database name is optional. Without a supplied database name the connection gets made to a database matching the name of the user. In that case no database is opened by default, but if any database name _is_ supplied then that database _does_ get opened. There should be a way to prevent this.

To reproduce:

Create databases named 'bob' and 'susan' and a user named 'bob' with access to both.  Configure the connection with the database field left blank.  TablePlus connects to the server without opening 'bob'.

Remove the 'bob' database.  TablePlus can't connect without entering a database name.  Configure 'susan' as the default.  TablePlus can now connect but 'susan' will be opened on connection.

Ideally I would prefer to be able to connect to any database server without automatically opening a database on connection.

**Comment by huyphams** [comment]
Hi @rdebled I don't think it is TablePlus issue, from the old PostgreSQL it does not allow you to connect without database but in the modern version (PG 12), you can do it. Here is mine (tested all green).
<img width="612" alt="Screen Shot 2021-05-05 at 22 34 36" src="https://user-images.githubusercontent.com/3654622/117168126-14f19680-adf2-11eb-9d43-b5922aa02389.png">
