### ISSUE TITLE
MySQL error around DEFAULT_GENERATED COMMENT when editing the name of a column

### ISSUE THREAD

**Issue by hartbit** [TablePlus/TablePlus#2410]
1. Which driver are you using and version of it: MySQL 8
2. Which TablePlus build number are you using: 366
3. The steps to reproduce this issue:

Create a table as such:

```sql
CREATE TABLE `article` (
  `id` int NOT NULL AUTO_INCREMENT,
  `faoId` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `sourceUpdatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_d785b1c105d756f3d3aff59a0a5` (`faoId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

then edit the name of the `sourceUpdatedAt` column. It generates the following error:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT_GENERATED COMMENT ''' at line 1
All changes were reverted (DDL statements can't be reverted).
```

when running the following generated query:

```sql
ALTER TABLE `db`.`article` CHANGE `sourceUpdatedAt` `sourceUpdatedAt2` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) DEFAULT_GENERATED COMMENT '';
```

**Comment by huyphams** [comment]
I'm using your script but I could not reproduce the issue, please check the gif.
![2021-05-06 18 17 05](https://user-images.githubusercontent.com/3654622/117289910-60aa4b80-ae97-11eb-8859-fb736f1a5762.gif)

**Comment by hartbit** [comment]
Here's a GIF showing the same operation going wrong on my end:

![](http://g.recordit.co/RInQDCko0s.gif)

**Comment by huyphams** [comment]
Hi @hartbit could you take a screenshot of the full table structure so I can see all the data? Like this one, Thank you
<img width="1385" alt="Screen Shot 2021-05-06 at 6 48 19 PM" src="https://user-images.githubusercontent.com/3654622/117293530-b08b1180-ae9b-11eb-93cd-1dd369a5465a.png">

**Comment by hartbit** [comment]
Hi @huyphams . Its the same structure as you as I use the above query to create the table each time:

<img width="1850" alt="Screen Shot 2021-05-06 at 14 36 01" src="https://user-images.githubusercontent.com/325519/117299068-647aa580-ae78-11eb-8b55-d5c91a673d01.png">

**Comment by huyphams** [comment]
No, I think MySQL 8.0.24 has a different implementation in their core and it has extra value DEFAULT GENERATED that causes the issue.

**Comment by hartbit** [comment]
Oh yes, indeed! I hadn't spotted that. Weird.

**Comment by hartbit** [comment]
Thanks for your exceptional support!

**Comment by huyphams** [comment]
Hi @hartbit please download this hot patch, it should fix your issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
