### ISSUE TITLE
Bug: "Contains - Case insensitive" filter not working for CockroachDB

### ISSUE THREAD

**Issue by angel-urena** [TablePlus/TablePlus#2413]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

CockroachDB CCL v20.2.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

368

3. The steps to reproduce this issue:

Applying the `Contains - Case insensitive` filter on a column performs a case sensitive query. This can be confirmed in the generated query being `... LIKE '%text%' ...` rather than `... ILIKE '%text%' ...`.

**Comment by huyphams** [comment]
Hi @angel-urena please download this hotpatch, it should fix the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks!

**Comment by angel-urena** [comment]
> Hi @angel-urena please download this hotpatch, it should fix the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
> Thanks!

Wow, didn't expect to get a solution so fast. Works great! Thanks!
