### ISSUE TITLE
Hstore is unsupported

### ISSUE THREAD

**Issue by espen** [TablePlus/TablePlus#2414]
While I am able to edit a hstore column the UI says it is an unsupported field type
<img width="211" alt="CleanShot 2021-05-14 at 15 19 16@2x" src="https://user-images.githubusercontent.com/32258/118276288-c4e89300-b4c7-11eb-8a52-5f0559573153.png">
.

**Comment by huyphams** [comment]
Hi @espen please do not remove the issue template question, TablePlus support more than 10 database type so I don't know which one is Hstore

**Comment by huyphams** [comment]
Looks like it is PostgreSQL. Thanks, we've fixed it!

**Comment by espen** [comment]
Sorry! Yes it is PostgreSQL.

Dude 💯💯💯🚀
