### ISSUE TITLE
Can't create a backup - SSL error

### ISSUE THREAD

**Issue by danielschweiger** [TablePlus/TablePlus#2415]
**Which driver are you using and version of it:**
Maria DB 10.5.8

**Which TablePlus build number are you using:**
3.12.8 (368)

**The steps to reproduce this issue:**
Backup Database -> Select Database -> Start Backup

**Error:**
mysqldump: Got error: 2026: SSL connection error: unknown error number when trying to connect

The backup.sql file then has 0 bytes.

I can connect and query this DB without any problems, just backup don't work.

**Comment by huyphams** [comment]
Thanks @danielschweiger TablePlus does not support SSL for backup/restore, we're going to support it now. Thanks for letting me know.

**Comment by lutek** [comment]
I have the same error with out ssl connection (the same app version):

![image](https://user-images.githubusercontent.com/846598/118965353-e71b5e80-b968-11eb-87f3-518b76a52dab.png)

**Comment by sekmun** [comment]
hey @huyphams would love to see this feature too thanks! keep up the good work.

**Comment by huyphams** [comment]
Hi guys, please try this patch and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by sekmun** [comment]
> Hi guys, please try this patch and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

@huyphams you're a champ!

**Comment by lutek** [comment]
> Hi guys, please try this patch and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

works for me.

**Comment by scheidtp** [comment]
Hi there!
When will this patch be merged to the release branch?

**Comment by huyphams** [comment]
it's been merged a year agon. Are you still seeing the issue @scheidtp ? Could you show me the message please?

**Comment by scheidtp** [comment]
Sure...

![SCR-20221012-ift](https://user-images.githubusercontent.com/10152346/195330077-c116f87f-cf78-47c2-9102-4c41295fda40.png)

![SCR-20221012-ij6](https://user-images.githubusercontent.com/10152346/195330164-dd9d5d93-35e8-4ca0-9d9e-4495a8769141.png)

**Comment by scheidtp** [comment]
Works like a charm. Thanks a lot.

**Comment by CobraClutch** [comment]
I've had this error popping up for me lately. I have the newest version of TablePlus (TablePlus 5.8.4 / Build 532). Are you able to re-upload the patch @huyphams? The Dropbox link above is expired.

**Comment by huyphams** [comment]
Hi @CobraClutch the patch was included in the latest release, you may choose the MySQL 8 for the TLS 1.3
