### ISSUE TITLE
[Feature Request] default LIMIT also in SQL Query window

### ISSUE THREAD

**Issue by keithwhyman** [TablePlus/TablePlus#2417]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
168
3. The steps to reproduce this issue:
Run a select, you must manually add a LIMIT else it will run forever
Noted: If the bug is related to data, please attach an example SQL data.

Just a basic request
When i browse a table, in MariaDB at least it seems to default to 300 rows, which i can change if i want (gearwheel at the bottom right).
In the SQL Query window it would be nice to have the same thing, so that it also defaults on 300, or what I choose, seems not to be there at the moment
Would be helpful

**Comment by huyphams** [comment]
Hi, please click the limit button in the Query editor? It on the left of the run current query and change it to 300!

**Comment by keithwhyman** [comment]
@huyphams 
Ha - yes obviously, see it now, it seems though to default to no limit, would it be possible to change the default of this?
I doubt that anyone wants a default No limit
