### ISSUE TITLE
how to hidden pg_temp_* schemas

### ISSUE THREAD

**Issue by defp** [TablePlus/TablePlus#2419]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

![image](https://user-images.githubusercontent.com/612381/118596213-fd48e380-b7dd-11eb-9ff2-7a82b08ab1a8.png)

3. The steps to reproduce this issue:
![image](https://user-images.githubusercontent.com/612381/118596388-08037880-b7de-11eb-9d50-36ea172be811.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, please install this patch, it should fix the issue.
https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by defp** [comment]
@huyphams wait  setapp version 😀
