### ISSUE TITLE
FR: bigger clickable area to drag the window around in title bar

### ISSUE THREAD

**Issue by matkatmusic** [TablePlus/TablePlus#2420]
The current title bar doesn't provide much **obvious** room to click on so we can drag the app window around because of all of the buttons.
It is also **not immediately apparent** that we can click on the text field that shows the `[SQL Version, TLS version, host name and Database being connected to]` to drag the window around. 

Xcode has a similar design but provides a nice area that **intuitively looks** like it can be used to drag the window around.
<img width="1148" alt="Screen Shot 2021-05-18 at 1 17 46 PM" src="https://user-images.githubusercontent.com/2929847/118717960-90cce500-b7db-11eb-8f5c-3b76d5873f75.png">

Compare with:
<img width="513" alt="Screen Shot 2021-05-18 at 1 18 58 PM" src="https://user-images.githubusercontent.com/2929847/118718014-9f1b0100-b7db-11eb-9bf7-76053a5b88df.png">

**Comment by huyphams** [comment]
Hi @matkatmusic you can right click and select custom toolbar to add more space. We will consider adding space by default. Thanks!
