### ISSUE TITLE
Auto limit not working when comments before "SELECT" keyword

### ISSUE THREAD

**Issue by ssiangge** [TablePlus/TablePlus#2422]
The auto limit will not append "LIMIT nnn" to the "SELECT" statement when there is a comment before the "SELECT" keyword and causing the query to load everything.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.32 , MariaDB 10.2.21

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 368 | Version 3.12.8 (368) | MacOS Big Sur

3. The steps to reproduce this issue:
Noted: If the bug is related to data, please attach an example SQL data.

Prepare:
- a table with more than 100 records (because the minimum auto limit is 100)
- set auto limit to 100 rows

.

Example 1: line comment
Note: there is 1 empty line before "SELECT"
```
--

SELECT * FROM tablename
```

Example 2: line comment
Note: there is a space before "SELECT"
```
--
 SELECT * FROM tablename
```

Example 3: block comment
Note: there is a space before "SELECT"
```
/**/ SELECT FROM tablename
```

Example 4: mixed
Note: **NO** space before "SELECT" but there is a space before "--"
```
/**/ --
select * from tablename
```

.

However, this work correctly:

Same like Example 1, but **NO** empty line before "SELECT", but there is space after "--"
```
-- 
SELECT * FROM tablename
```

Same like Example 2, but **NO** space before "SELECT"
```
--
SELECT * FROM tablename
```

Same like Example 3, but **NO** space before "SELECT"
```
/**/SELECT * FROM tablename
```

Same like Example 3, but **NO** space before "SELECT"
```
/* some comment message here */SELECT * FROM tablename
```

Same like Example 4, but **NO** space before "--"
```
/**/--
SELECT * FROM tablename
```

**Comment by huyphams** [comment]
Hi @ssiangge thank you for letting me know. Please download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 it should fix the issue!
