### ISSUE TITLE
Adding Identity to a Column Produces Error

### ISSUE THREAD

**Issue by allenweiss** [TablePlus/TablePlus#2423]
I'm using MSSQL

TablePlus Version 3.12.8 (368)

Every time I try to change a column to be the identity, I get an error.  Here is the sql

ALTER TABLE [dbo].[Survey] ADD DEFAULT IDENTITY(1,1) FOR [survey_id];

<img width="1115" alt="screenshot_863" src="https://user-images.githubusercontent.com/1487109/119274463-e121b980-bbc4-11eb-9653-e3924430cafa.png">

**Comment by huyphams** [comment]
Hi, it's not possible to alter an existing column with identity. 

```
You have 2 options,

1. Create a new table with identity & drop the existing table

2. Create a new column with identity & drop the existing column

```

Source: https://stackoverflow.com/questions/1049210/adding-an-identity-to-an-existing-column
