### ISSUE TITLE
2 Unique id indices when creating table.

### ISSUE THREAD

**Issue by blaaat** [TablePlus/TablePlus#2425]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MariaDB 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 3.12.8 (368)

3. The steps to reproduce this issue:

Create new table, keep default id serial, with id as primary key. 
2 indices are created; one PRIMARY unique (id), and one id unique (id) instead of one.

**Comment by huyphams** [comment]
This is the MariaDB behavior not TablePlus as it does not add any additional query, you can press command + shift + P to see the transcript.

**Comment by blaaat** [comment]
I don't think this is MariaDB specific, MySQL docs read the same: 

https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html

> SERIAL is an alias for BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE.

TablePlus creates this create syntax

> CREATE TABLE `xxx`.`test` (`id` serial, PRIMARY KEY (id));

adding another Primary key on (id), even though serial already implies an unique key

**Comment by huyphams** [comment]
A unique key is not a primary key, you can see that TablePlus sends `CREATE TABLE xxx.test (id serial, PRIMARY KEY (id));` without any additional query.
I agree that it could create two indices but it is more a MariaDB issue than a TablePlus issue as it has no control over it.

**Comment by huyphams** [comment]
However, it could be better if we just use the int and auto-increment instead of serial.
<img width="771" alt="Screen Shot 2021-10-04 at 2 57 11 PM" src="https://user-images.githubusercontent.com/3654622/135814346-841f22b2-fc33-4fe1-ba7d-4603fff40c1a.png">

**Comment by blaaat** [comment]
I think the syntax to solve this would be: 

> CREATE TABLE `dd` (`id` serial PRIMARY KEY);

**Comment by blaaat** [comment]
> However, it could be better if we just use the int and auto-increment instead of serial.
> <img alt="Screen Shot 2021-10-04 at 2 57 11 PM" width="771" src="https://user-images.githubusercontent.com/3654622/135814346-841f22b2-fc33-4fe1-ba7d-4603fff40c1a.png">

If you choose this way, can you still default to bigint unsigned NOT NULL?

**Comment by huyphams** [comment]
it's the default row, the user should modify it to fit their requirements. We do not know which is the better setting for the user as it base on their use-case. The only thing we can do is set a default the could fit a common use case.

**Comment by blaaat** [comment]
Well. the default is serial now, which is a bigint unsigned not null auto increment.
But changing syntax to CREATE TABLE dd (id serial PRIMARY KEY); would fix this and keep the serial default?

**Comment by huyphams** [comment]
> However, it could be better if we just use the int and auto-increment instead of serial. <img alt="Screen Shot 2021-10-04 at 2 57 11 PM" width="771" src="https://user-images.githubusercontent.com/3654622/135814346-841f22b2-fc33-4fe1-ba7d-4603fff40c1a.png">

I've changed it to this. The user can change the data type int or anything else to fit their requirements (small int, big int, unsigned etc...).
