### ISSUE TITLE
Views give inaccurate count in the UI

### ISSUE THREAD

**Issue by jklmnop** [TablePlus/TablePlus#2426]
I have some views that have more than 300 records, but the count in the UI seems capped at 300. The first page says "1-300 of ~300 rows" and subsequent pages say "301-300 of ~300 rows".

In one example, a `select count(*) from myview;` will yield the correct count, but the UI shows this:
Page 1
![image](https://user-images.githubusercontent.com/180323/119831062-e33c8e80-beca-11eb-8cbd-493f6d4b19ff.png)
Page 2+
![image](https://user-images.githubusercontent.com/180323/119831120-f3ed0480-beca-11eb-82ae-6947ab9eedcd.png)

This seems to be the case for every view with more than 300 records. Views with fewer records report correctly.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB 10.4.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.12.8 (368)

3. The steps to reproduce this issue: Have a view with more than 300 records.

**Comment by huyphams** [comment]
Hi it is estimated value (we should not count a table with many rows because it could crash the server, so TablePlus will eatimate rows before counting)
You can force TablePlus to count rows by uncheck the estimate row count in the TablePlus preferences.
Thanks!

**Comment by jklmnop** [comment]
Great to know! Had no idea there was a setting for this! Thank you for responding so quickly.

One issue about that setting though: the default for that setting is to estimate >500k rows. None of my views come even close to that. Usually they're somewhere between 10k and 50k and it still forces the estimate for any view with >300 rows. I would have expected the count to be exact and not estimated considering that I don't have any views with >500k rows.

Overall, it's not a big deal.

Turning off that setting works perfectly.

**Comment by huyphams** [comment]
The estimated  value is not updated realtime (this is the database design issue) so in your case, the eatimate value = 0. 0 < 500k however TablePlus will not try to count the real value if the estimated value = 0 or bigger than the threshold. Most of the time, estimated = 0 but it actually has billion rows.
