### ISSUE TITLE
Option for lower case hex value (id) display

### ISSUE THREAD

**Issue by rlincke** [TablePlus/TablePlus#2427]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.12.8 (368)

3. The steps to reproduce this issue:
 
Open a database using 16 byte id keys (e.g., 014EB370BE484DCFB9E3CCF222EFE8CA). They are represented in upper case.
If I copy them to test an API, e.g., with Postman, I need to convert the values to lower case (i.e., 014eb370be484dcfb9e3ccf222efe8ca).
Would be great if they would be displayed lower case directly in TablePlus (maybe an option in Preferences, if they should be upper or lower case). Would make debugging and developing with DB/API much faster.

Thank you!

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @rlincke you could reuse this plugin: https://github.com/TablePlus/openurl by changing this file: 

https://github.com/TablePlus/openurl/blob/master/OpenURL.tableplusplugin/main.js

to 

```
'use strict';

import { getURL } from './library/helper';

var onRun = function(context) {
    // Get table in opening tab
    var value = context.clickedRowValue();
    if (value == null) {
        context.alert('Error', 'Data is null');
        return;
    }
    SystemService.insertToClipboard(value.str.toLowerCase());
    SystemService.notify('Info', 'copied!');
};

global.onRun = onRun;
```

And then install it to TablePlus, you will see a new menu context when you right-click on the cell.

Please let me know if you have any questions.

**Comment by huyphams** [comment]
I made it for you, so you can just download it, unzip and then double click to install
[CopyLowercase.tableplusplugin.zip](https://github.com/TablePlus/TablePlus/files/6557616/CopyLowercase.tableplusplugin.zip)

**Comment by rlincke** [comment]
Hello Henry,

thank you very much for the fast answer and your effort in providing an adapted Plug-in version. Very appreciated.

Short question, did you test the plugin?

I have version 3.12.8 (368) and I get a message:
Error, Data is null. Any idea how to fix that?
(The Plug-in you changed (open url) works though).

Thank you!

Best regards,
Rüdiger
