### ISSUE TITLE
Selecting backwards wordwise + backspace deletes the wrong text

### ISSUE THREAD

**Issue by narrowtux** [TablePlus/TablePlus#2428]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 13.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 168 on windows 10

3. The steps to reproduce this issue:
  * go to an SQL editor
  * enter some words
  * doubleclick and drag backwards
  * press backspace
  * not the selected region is deleted, but the text before that. please see the attached video

https://user-images.githubusercontent.com/616791/119977458-bff00d00-bfb8-11eb-9791-1ced0857b415.mp4

**Comment by huyphams** [comment]
Hi, this is macOS repo, please use our Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues

Btw, which version are using? this could be fixed in the patch 4.0.4 https://github.com/TablePlus/TablePlus-Windows/issues

**Comment by huyphams** [comment]
I was wrong, it is not fixed, let me fix it.

**Comment by narrowtux** [comment]
so ... should I report this over at the windows repo?

**Comment by huyphams** [comment]
We're working on it right now so you don't have to open new issue. Thanks

**Comment by narrowtux** [comment]
Thank you

**Comment by huyphams** [comment]
Hi @narrowtux please install this hotpatch, it should fix the issue: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
