### ISSUE TITLE
ctrl-click does not show the context menu in OSX

### ISSUE THREAD

**Issue by heliodor** [TablePlus/TablePlus#2431]
This is for Mac OSX. `ctrl-click` and `two-finger click` aren't treated the same. They are both supposed to function as a "right-click" according to OSX usability standards.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
3.12.8 (368)

3. The steps to reproduce this issue:
Open a Cassandra connection.
Open any two of the keyspaces. They should now be shown as tabs in a vertical strip on the left edge of the window.
Press `ctrl-click` and nothing happens. Do a `two-finger click` and the context menu pops up.

**Comment by huyphams** [comment]
I think it should be option + click?

**Comment by heliodor** [comment]
It's supposed to be ctrl-click. It works for the rest of the GUI, just not in that particular tab strip. Option-click doesn't do anything either, but it's ctrl-click across the whole operating system. The CTRL key is probably being intercepted in the code for the tab strip.

**Comment by huyphams** [comment]
Ah thanks, let me add this behavior.

**Comment by huyphams** [comment]
Hi @heliodor please try this build and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks

**Comment by heliodor** [comment]
Yep, it works now!
