### ISSUE TITLE
Backing up a database fails on M1

### ISSUE THREAD

**Issue by vdbelt** [TablePlus/TablePlus#2435]
When making a backup of a database, the following error appears:
```
Backup database 'demo'
Creating tunnel...
Dumping...
/bin/sh: ./dump_ms_8.0: Bad CPU type in executable

Backup database completed
```

1. Which driver are you using and version of it:
MariaDB / MySQL

2. Which TablePlus build number are you using:
Version 3.12.8 (368)

3. The steps to reproduce this issue:
File -> Backup -> Select database -> Start backup

**Comment by huyphams** [comment]
Hi @vdbelt did you install rosetta? Please try to run any intel application and install rosetta it should resolve the issue.

**Comment by vdbelt** [comment]
Thanks.

I didn't install Rosetta just yet, as I am trying to set up a workflow without it. This was one of the only issues encountered, hence the opened issue.

If the dump binary has any dependencies that aren't working natively yet, I'll be happy to take a look if you can point to them.

**Comment by michaelyork** [comment]
Any chance we can get the Rosetta dependency removed? Would love to keep my workflow fully native as well.
