### ISSUE TITLE
Cannot use MAX() function in where clause

### ISSUE THREAD

**Issue by mclaugh33** [TablePlus/TablePlus#2437]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 8.0.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.8 (368)

3. The steps to reproduce this issue:
SELECT count(field)
FROM table
WHERE field = (select max(field) from table)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @mclaugh33 this issue is not related to TablePlus. The error you are seeing is the server message. It could be version 8.0.2 does not support max.
