### ISSUE TITLE
MSSQL login with domain and username not working

### ISSUE THREAD

**Issue by Sennahoi** [TablePlus/TablePlus#244]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2016 (SP1-CU1) 13.0.4411.0 (X64)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 87

3. The steps to reproduce this issue:
Create a mssql server connection that needs a login with domain and username, e.g.
Username: INTERN\Administrator
Set Host, Passwort and port and hit "test" and get the message:

"Error: NULL DBPROCESS pointer passed to DB-Library 
Message: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.". 

In SQLPro for MSSQL I use the Authentication Type "Windows Authentication" and the same username etc. and it connects.

**Comment by huyphams** [comment]
Hey thanks, @Sennahoi I will check this issue.
there is an issue similar with this https://github.com/TablePlus/TablePlus/issues/210

**Comment by delfuego** [comment]
I too see this exact same issue.

**Comment by dansherman** [comment]
I see the same issue. SQLPro works fine for the connection when using "SQL Server Authentication" instead of "Windows Authentication".

**Comment by huyphams** [comment]
I copied the solution from issue #210 

If the username has domain `DOMAIN\username`, TablePlus will automatically use it as domain login.

**Comment by dansherman** [comment]
Turns out SQL Server give the "untrusted domain" error message when the password is wrong too. Using the right password fixed it.

> I copied the solution from issue #210
> 
> If the username has domain `DOMAIN\username`, TablePlus will automatically use it as domain login.
