### ISSUE TITLE
Truncate has no effect on a Mongo collection

### ISSUE THREAD

**Issue by jorisw** [TablePlus/TablePlus#2440]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MongoDB 4.4.3 on MacOS 11.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

368

3. The steps to reproduce this issue:

- Open a connection to a MongoDB database
- Right click on a collection in the left pane
- Choose Truncate
- Confirm the dialog window that has two disabled checkbox options
- Notice the yellowed collection in the left pane
- Hit Command-S to execute the operation
- Refresh the collection content
- Notice all the records are still in there

**Comment by huyphams** [comment]
Thanks, if you have a chance, please try this patch, it supports truncate collection: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by jorisw** [comment]
Hi, thanks, however my Mac says `No mountable filesystems` on that dmg.

**Comment by huyphams** [comment]
It's released so no need to download the hotpatch @jorisw
