### ISSUE TITLE
Delete has no effect on a Mongo collection

### ISSUE THREAD

**Issue by jorisw** [TablePlus/TablePlus#2441]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MongoDB 4.4.3 on MacOS 11.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

368

3. The steps to reproduce this issue:

- Open a connection to a MongoDB database
- Right click on a collection in the left pane
- Choose Delete
- Confirm the dialog window that has two disabled checkbox options
- Notice the yellowed collection in the left pane
- Hit Command-S to execute the operation
- Refresh the window content (Cmd-R)
- Notice the collection is still there with all the records in there

**Comment by dapobelieve** [comment]
Just had this issue @jorisw did you find any way around this

**Comment by jorisw** [comment]
Nope, switched to MongoHub,

**Comment by huyphams** [comment]
Hi, please download this hotpatch, it supports drop collection now: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks!
