### ISSUE TITLE
Cannot connect to Oracle DBs using MacOS Big Sur

### ISSUE THREAD

**Issue by clemdaniel** [TablePlus/TablePlus#2442]
I have been using TablePlus as my DB client of choice for a while, but since upgrading to a new Macbook I can no longer connect to any Oracle SQL servers.  On a previous machine (Macbook Pro 2015 with MacOS Catalina) I was able to connect without issue with versions 367 and 368.  I really don't want to go back to Oracle SQL developer, which crashes constantly.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 12c, 19c

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
371
OS: Big Sur, 11.2.3
Device: Macbook Pro 2019

3. The steps to reproduce this issue:
Attempt to initialize a connection with any Oracle DB
Note: Tested with Oracle DB instances managed by AWS RDS

This following error message is shown when trying to test or open a connection:
Error: ORA-12571: TNS:packet writer failure
<img width="296" alt="image" src="https://user-images.githubusercontent.com/7397502/122277106-832a7e00-ceb3-11eb-884c-9eb5db1465eb.png">

**Comment by huyphams** [comment]
Hi @clemdaniel can you please try again with the build https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
Let me know if you're still seeing the issue.
