### ISSUE TITLE
Option in Preferences to set Open in New Tab be the primary [Feature Request]

### ISSUE THREAD

**Issue by Ben1nBlack** [TablePlus/TablePlus#2444]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.0.0

At Present the default click action on an item, opens the item in the current tab, I have to right click to have the item open  in new tab, I would like that there be and option in preferences to flip the default action, so that when you click it opens in new tab and right click opens in current tab

**Comment by huyphams** [comment]
Hi you can open new tab with double-click or middle mouse. We do not want to add the option to swap it at the moment.
