### ISSUE TITLE
Export feature doesn't include all the table rows

### ISSUE THREAD

**Issue by shanekovash** [TablePlus/TablePlus#2445]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):  11.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.0.0 (370)

3. The steps to reproduce this issue: Export a table with more than 15,000 rows

Noted: If the bug is related to data, please attach an example SQL data.

Seeing an issue with exporting a large table through an ssh tunnel connection. Only the first 11,325 rows seem to export. Tried sql and csv exports. Had to export the remaining rows from a filtered list.

**Comment by huyphams** [comment]
Hi @shanekovash, it's not possible to reproduce the issue without the step. I do believe that you misunderstanding the feature.

Export the current page <> export the result.
