### ISSUE TITLE
Feature request: retrieve temp password token by executing command

### ISSUE THREAD

**Issue by KingMob** [TablePlus/TablePlus#2446]
Our org recently switched to using ADFS IAM authentication for our Aurora Pg credentials. This means we don't have a static, saved password any more, but we have to get credentials on the fly via something like:

```shell
export RDSHOST="mypostgres-cluster.cluster-123456789012.us-west-2.rds.amazonaws.com"
export PGPASSWORD="$(aws rds generate-db-auth-token --hostname $RDSHOST --port 5432 --region us-west-2 --username jane_doe )"
```

It would be great if TablePlus could run a script to retrieve the password, so we don't have to do it manually every time.

(While less important, this would be useful for the hostname, too. AWS IAM ADFS doesn't support CNAMEs for clusters yet, so while rare, it's possible for the dynamic hostname to change as well.)

**Comment by fernandocarletti** [comment]
I believe it should also support dynamic usernames as well so it could be used with [Hashicorp Vault](https://www.vaultproject.io/docs/secrets/databases).

**Comment by huyphams** [comment]
TablePlus now supports getting the password via Command Line IAM.

![CleanShot 2022-09-23 at 15 09 27@2x](https://user-images.githubusercontent.com/3654622/191918020-20582fcf-2e9b-48a6-a17b-096d741f52c4.png)

if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're seeing any issue.

**Comment by zoispag** [comment]
@huyphams sorry to comment on a closed PR; is it possible to not hide the password input, when the type is Command Line?

**Comment by adrianomitre** [comment]
> TablePlus now supports getting the password via Command Line IAM.

Is this feature also available on Linux?
