### ISSUE TITLE
[Feature Request] Customize normal rows color

### ISSUE THREAD

**Issue by TwanLuttik** [TablePlus/TablePlus#2448]
I would like to customize existing rows to give them a different colors like the other colors  when you delete or modify rows

<img width="612" alt="Screen Shot 2021-06-29 at 12 19 00 PM" src="https://user-images.githubusercontent.com/19343894/123855061-4d828d80-d8d4-11eb-879d-84f4a8c1e1b6.png">

**Comment by Tom-Pearce** [comment]
I'd also like to extend on this request by asking for the possibility to customise the actual text colour of the data. I've historically used HeidiSQL on windows, and recently switched to Mac and using TablePlus, but find the all black/white text jarring to read. 

Maybe it's personal preference, maybe it's from being used to colour coded data types for years, but the ability to customise these colours would be useful. Or even just the ability to switch between presets of the current monochrome and a coloured version.

Here is HeidiSQLs data viewer, numeric types are blue, text types green, date/time types red/burgendy etc:
![](https://www.heidisql.com/images/screenshots/data.png)

**Comment by TwanLuttik** [comment]
Closed the issue since recently tableplus has released an update where by this is possible
