### ISSUE TITLE
[Feature request] Customize setting on is_nullable and column_default in SQL

### ISSUE THREAD

**Issue by ItalicJerrold** [TablePlus/TablePlus#2449]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.9
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 3.12.8 (368)
3.  Request default setting for creating table, such as default _is_nullable_ and _column_default_, or become able to customize policy for column_default, such as int to 0, varchar to empty and bool to false

**Comment by huyphams** [comment]
You can click the dropdown and select advance, it will allow you to enter expression (0 or false), or select EMPTY.
<img width="244" alt="Screen Shot 2021-07-01 at 11 18 29 AM" src="https://user-images.githubusercontent.com/3654622/124063958-1d66f600-da5e-11eb-9339-d35e4f2cb91d.png">
