### ISSUE TITLE
Add pagination for custom queries

### ISSUE THREAD

**Issue by timster** [TablePlus/TablePlus#245]
It would be nice if the paginator you get in table view:

<img width="255" alt="capture 2018-02-12 at 6 29 09 am" src="https://user-images.githubusercontent.com/173666/36094916-0b603232-0fbe-11e8-9dc3-ca7d6a7efb92.png">

Could be used when running custom queries here:

<img width="143" alt="capture 2018-02-12 at 6 29 00 am" src="https://user-images.githubusercontent.com/173666/36094925-1543635a-0fbe-11e8-8f55-4905f01bf8d4.png">

Maybe have a default page size then a button for "fetch all rows".

Yeah I know I can add a LIMIT to my query, but this is a helpful thing that many other database tools have.

**Comment by huyphams** [comment]
TablePlus supported streaming result now. We can cancel any time so I think we don't need this feature.
If you think the streaming is not your expectation please reopen this issue again.

**Comment by francisco4challenge** [comment]
+1

**Comment by mdc-git** [comment]
It would be nice to have either streaming results or pagination for custom queries in the Linux client as well, since it is no longer in beta. And the UI locks up at 100% CPU usage with large result sets.
