### ISSUE TITLE
Should handle opening of sqlite files faster and simpler, possibly owning .db and .sqlite extensions

### ISSUE THREAD

**Issue by rickmark** [TablePlus/TablePlus#2453]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 730

3. The steps to reproduce this issue: Create connection to SQLite Database - If you are examining a lot of these small files, creating a temp connection with the name of the path of the file if the opened file has the magic would make editing and viewing these fast

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It was supported long time ago. If there is other application override it, you can change it by right click to the sqlite file and make TablePlus as default.
![2021-07-12 15 44 28](https://user-images.githubusercontent.com/3654622/125257984-1e363c80-e328-11eb-88a6-d6f87e21ac8e.gif)
