### ISSUE TITLE
[Feature Request] Setting to keep quick-opened tabs opened

### ISSUE THREAD

**Issue by dominiquediotte** [TablePlus/TablePlus#2454]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQL Server 2017

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 370

3. The steps to reproduce this issue: When I quick-open an object with Command-P on Mac, the tab are not kept open like if I would double click on them on the left-side navigator. Could there be an option to keep quick-opened tabs open. Because if I quick open another tab, it will close the previous one.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
You can hold command when you open an item with command + P to keep the tab @dominiquediotte

**Comment by dominiquediotte** [comment]
@huyphams I don't know if I'm doing it wrong, but this doesn't work. When I hold Command and click on an item it does not open, first, and even if I double-click it, it keeps being temporary (in italics) in the top bar. Opening a new object will close the previous one.
