### ISSUE TITLE
Single table export in macOS 10.15 not working

### ISSUE THREAD

**Issue by mikejoseph** [TablePlus/TablePlus#2455]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL (Old, assuming 5.4.x)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
370

3. The steps to reproduce this issue:
- Connect to remote server
- Select database
- Select table
- Select File -> Export
- Select any export option
- Click "Export..." button

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @mikejoseph does it work on the newest release 374?
