### ISSUE TITLE
Data View Refresh very slow

### ISSUE THREAD

**Issue by dylanwenzlau** [TablePlus/TablePlus#2462]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.12 (running on AWS RDS Aurora)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.0.0 (370)

3. The steps to reproduce this issue:
Click on any normal table from the sidebar so it displays the default first page of data in data view. This initial loading of data view is fast and normal. Now, use CMD+R to refresh data view, and it takes several seconds, maybe 3-30 seconds, to refresh the data. This data refresh should generally always take less than 10 milliseconds because it's a simple order by on the primary key. I'm not sure what it's doing during the refresh command, but it's definitely very slow and unnecessary. If the refresh command needs to do more work than just refreshing the data view, then data view needs its own refresh button. Right now, it doesn't even make sense for me to use data view to view data because it's faster to go type the query manually in the query editor.

Noted: If the bug is related to data, please attach an example SQL data. (not related to specific data, happens with all tables, they are all the standard INT UNSIGNED AUTO_INCREMENT as PRIMARY key)

**Comment by huyphams** [comment]
The command + R will refresh the whole workspace and not only the current table. You can right click on the table data and select refresh.
<img width="809" alt="Screen Shot 2021-07-30 at 9 10 10 AM" src="https://user-images.githubusercontent.com/3654622/127589309-02349979-a96f-4349-a4cb-17ae72c14bea.png">

We're working to improve the workspace loading time in the next update. 376 (you're also behind 2 updates).

**Comment by dylanwenzlau** [comment]
Ah, got it. Thanks for the tip. I'll use the CMD+ALT+R shortcut from now on.

A table row isn't that intuitive a place to look for an action that applies to the entire page, so maybe it would help to add a callout elsewhere. I actually did right click on the table name itself in the sidebar list but didn't see a refresh option.
