### ISSUE TITLE
Painfully slow input lag

### ISSUE THREAD

**Issue by anentropic** [TablePlus/TablePlus#2464]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 11.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.0.2 (374)

3. The steps to reproduce this issue:

Start typing in an SQL query tab. Every key-press takes maybe half a second to register.

To me it seems like the lag is related to autocomplete, like each key-press has to filter the autocomplete suggestions list and that's taking way too long for some reason.

This started happening recently for me, like just this week. I've closed and reopened TablePlus but it persists.

**Comment by huyphams** [comment]
Hi @anentropic please click the settings button below the editor and turn off auto completion. Please let us know if you are still seeing the issue.

**Comment by anentropic** [comment]
thanks, turning off "Autocomplete options > Tables" fixed it

to be fair, one of the schemas in this db does have a huge number of tables...

**Comment by huyphams** [comment]
Hi @anentropic the newest release 382 should fix this issue, even "Autocomplete options > Tables" is turned on.
Please let me know if you are still seeing the issue.
