### ISSUE TITLE
[Question/Suggestion] Set default Match Column Option

### ISSUE THREAD

**Issue by CaptainStabs** [TablePlus/TablePlus#2465]
Is there any way to set the default `Match Columns by ...` when importing a file? 
![image](https://user-images.githubusercontent.com/40151222/127667700-779910b4-7656-4102-9386-d60f843d7404.png)

Also, an option to just have the simple SQL result printout, the same format that you get when you have 200+ queries, would be nice as well.  Example:
![image](https://user-images.githubusercontent.com/40151222/127668973-93115fb3-3f28-4ea1-bfa6-f5613b14b26a.png)

It might also be a good idea to lower the threshold for switching from tabs to plain text down from 200, as having 200 tabs is not the best, and single tab mode doesn't really cut it for the readability of the plain text :) 
![image](https://user-images.githubusercontent.com/40151222/127669079-ef6cdbd7-584e-4663-bb1f-d777715edf26.png)

Keep up the good work!

**Comment by huyphams** [comment]
Hi @CaptainStabs this repo is for issue only, if you have any questions please email nick@tableplus.com

If you want to change the result mode, you might want to check this out:

<img width="575" alt="Screen Shot 2021-07-30 at 21 39 58" src="https://user-images.githubusercontent.com/3654622/127669597-82c11214-24cb-4752-aba5-93e25d803516.png">

**Comment by CaptainStabs** [comment]
This should probably be changed then 📦 
![image](https://user-images.githubusercontent.com/40151222/127679260-ff1b65ec-96f3-413d-b174-c96064d39ba8.png)

**Comment by huyphams** [comment]
Thanks @CaptainStabs i am sorry because of the confusion. We have more than 800 open issues so I just want to reduce the number of issues. I should work harder to fix it 😅
