### ISSUE TITLE
Support for combining all schemas in left panel (postgres)

### ISSUE THREAD

**Issue by purge** [TablePlus/TablePlus#2468]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

postgresql 13

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

4.0.2 374

Feature request

i've come across some databases that are arbitrarily split into many schemas (for no good reason) and it makes it very hard to work with in tableplus. a good options would be to be able to check all schemas in a list to show in the left column rather than one at a time (and prefix the table / function name)

**Comment by huyphams** [comment]
Duplicate https://github.com/TablePlus/TablePlus/issues/2508
