### ISSUE TITLE
Beatify does not work if you have ' -- ' in query

### ISSUE THREAD

**Issue by maximbashevoy** [TablePlus/TablePlus#2469]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySql 5.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 4.0.2 (375) via SetApp

3. The steps to reproduce this issue:

Type SQL query:

```
select ' -- ' as del, 'a' as value from baskets;
```

Click Beautify: nothing happens.

Delete one '-':

```
select ' - ' as del, 'a' as value from baskets;
```

It works!

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
