### ISSUE TITLE
Idea: Add bootstrap/startup queries per connection

### ISSUE THREAD

**Issue by davidolrik** [TablePlus/TablePlus#247]
I would like to be able to execute a series of statements immediately after connecting to a given database.

For each connection I could provide a few queries that would alter the current session automatically each time the connection is established.

This will let me do stuff like this on MySQL:

`set session wait_timeout=3600;`

**Comment by huyphams** [comment]
if the build in https://github.com/TablePlus/TablePlus/issues/216#issuecomment-364933843 fixed this issue, I think don't need a bootstrap, because it can make the form more complicated, maybe confused with new users.

**Comment by huyphams** [comment]
Hi @davidolrik it's added now on the beta build, or you can download here: https://www.dropbox.com/s/ndn8m23p7fbvwcq/TablePlus.dmg?dl=0

<img width="1034" alt="Screen Shot 2020-05-01 at 8 35 30 PM" src="https://user-images.githubusercontent.com/3654622/80809201-64075900-8beb-11ea-9844-96c8148c4a29.png">
