### ISSUE TITLE
Allow the user to show all tables using a Microsoft SQL Server Connexion

### ISSUE THREAD

**Issue by yanckst** [TablePlus/TablePlus#2470]
## Question

It is a bug or a feature request. I don't really know. Here's why.

## Context
When opening a database, by default, it seems that the first selection of the filter dropdown is selected. That's a great feature to filter the tables, but I don't see the option to not select this filter. I want to see all tables once (without filters)

### On first load

![image](https://user-images.githubusercontent.com/30554401/128754268-7a1a4f79-bb43-4b9f-b59f-666f20e90a65.png)

###  When trying to remove the filter, it seems that I can't select the "none" option
![image](https://user-images.githubusercontent.com/30554401/128754318-14f08602-894c-4bd2-b1b3-8458f8bd1faf.png)

### Here's a look on the tables I have on localhost (using SSMS)
![image](https://user-images.githubusercontent.com/30554401/128754477-17a4ab54-56de-443b-8e09-80ef243ee54c.png)

### Conclusion
As you can see, it seems that TablePlus, by default, is taking the first item in the name separated by a dot to create the filter dropdown. But it seems that we can't select nothing.

----

## Steps to reproduce

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server Connexion

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 174

3. The steps to reproduce this issue:
- Connect to a local Microsoft SQL Server 
- Select a database

Any inputs on this 🙂

Thanks!

**Comment by huyphams** [comment]
It is our UI/UX decision. Currently TablePlus are being filtered by schema. You can switch between schema using command + P or click the dropdown at the bottom.
It's not a bug or issue, it's the app UI design. We might consider putting an option to view table in all schemas but not for now.
