### ISSUE TITLE
export unicode issue

### ISSUE THREAD

**Issue by b051** [TablePlus/TablePlus#2471]
1. MySQL 5.7

2. TablePlus 4.0.2 (374)

3. The steps to reproduce this issue:
```sql
CREATE TABLE `universal_radicals` (
  `radical` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`radical`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
and insert it with radical = "𠂇"

when exported, the sql looks like
```sql
...
INSERT INTO `universal_radicals` (`radical`) VALUES
('?')
...
```

it works fine in other tools like Sequel Pro

**Comment by huyphams** [comment]
Hi @b051 please enable this.

<img width="840" alt="Screen Shot 2021-08-12 at 2 27 24 PM" src="https://user-images.githubusercontent.com/3654622/129155702-2f79603e-313d-41df-9fca-a936fcb7a001.png">

**Comment by b051** [comment]
thanks! @huyphams that solves the problem
