### ISSUE TITLE
Wrong shortcut shown for table structure

### ISSUE THREAD

**Issue by mohammedyh** [TablePlus/TablePlus#2472]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql  Ver 8.0.25 for macos11.3 on x86_64 (Homebrew)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Bulld 374

3. The steps to reproduce this issue:
Hover over the "structure" tab

(On macOS - default keymaps)

**Comment by huyphams** [comment]
hi @mohammedyh could you point out what was wrong with it?

it is control + command + ] or [ and it's correct.

**Comment by mohammedyh** [comment]
Hi @huyphams,

When I am on the structure tab and hover over it, the shortcut shown is Command + Shift + ]

Attached a screenshot of the shortcut shown for me.

<img width="317" alt="Screenshot 2021-08-16 at 09 08 46" src="https://user-images.githubusercontent.com/32526267/129532024-8a0448a0-303a-4145-805d-9f7e0a6d5190.png">

**Comment by huyphams** [comment]
The shortcut is dedicated for a button, you can hover over the data button, it will be different.

**Comment by mohammedyh** [comment]
I see. No worries, thank you for pointing that out
