### ISSUE TITLE
Cannot filter in Postgress if table is in a schema other than "public"

### ISSUE THREAD

**Issue by jannejava** [TablePlus/TablePlus#2474]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgress 12.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
376

3. The steps to reproduce this issue:

Trying to filter rows in a table that is not in the schema "public" (if I switch to public it works). In my case it's in a schema called "measure_data".

None of the column names are picked up and filtering does not work. See screenshot.

![CleanShot 2021-08-19 at 10 38 58@2x](https://user-images.githubusercontent.com/543616/130038332-49b6c15a-1049-4b5c-8e0d-e96322641993.png)

Thanks in advance!

**Comment by huyphams** [comment]
Hi @jannejava I could not reproduce the issue, could you please refresh the app and try again? It could be a connection issue.

**Comment by jannejava** [comment]
Holy smoke, it works after restarting the app! 👍
