### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by beaudierman** [TablePlus/TablePlus#2475]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
376

3. The steps to reproduce this issue:
Choose any decent sized table, Right-Click > Export > SQL. (This step isn't required but I just wanted to establish that I am using an export that TablePlus made.)
On another DB, File > Import > From SQL Dump
After a minute or so of very little progress, an error appears:
<img width="669" alt="Screen Shot 2021-08-19 at 9 48 36 AM" src="https://user-images.githubusercontent.com/3011253/130082602-bf7495e6-913d-4051-9293-ea6e1de81028.png">

Notes:
1.  I'm running macOS Big Sur (v11.5.1) with 16GB of RAM and an Intel processor.  The activity monitor shows TablePlus never going above 800MB of memory used, and I still have 6-8GB free.
2.  This error seems to only appear when importing into a slower remote DB server.  When I try the same file on a local or prod DB server, there is no issue.
3.  Importing this SQL dump with another program (Sequel Ace or cli mysql import) there is no issue.

**Comment by huyphams** [comment]
The message was from the server side not the app so it has nothing todo with the device memory usage. TablePlus will pack the query into small chunks and send it to server.
I think that TablePlus had tried to pack a bigger chunk when compared with Sequel Ace or CLI.

In the meantime, you can use the restore feature as a workaround solution because it uses CLI to restore the backup. I will take a look at it.
Thanks

**Comment by beaudierman** [comment]
> The message was from the server side not the app so it has nothing todo with the device memory usage. TablePlus packed the queries into small chunks and send it to server. I think that TablePlus had tried to pack a bigger chunk when compared with Sequel Ace or CLI.
> 
> In the meantime, you can use the TablePlus Restore feature as a workaround solution because it uses CLI to restore the backup. I will take a look at it.
> Thanks

Thank you, this workaround does indeed work.
