### ISSUE TITLE
Proposal: Add shortcuts for "Set Value" Menu

### ISSUE THREAD

**Issue by evolkmann** [TablePlus/TablePlus#2476]
I often use the "Set Value" right-click menu (see attached video).
It would be great to have keyboard shortcuts for this.
I use TablePlus Build 374.

https://user-images.githubusercontent.com/24471188/130324374-7c8023a5-ee20-4c5c-8ff6-dc50b8015fc1.mov

**Comment by huyphams** [comment]
Hi @evolkmann it's Option + Return

**Comment by evolkmann** [comment]
Hi @huyphams thanks a lot for the quick response 🙂👍🏻

Anyway, the shortcut should be visible in the right click menu, just like Copy, Paste, etc.
