### ISSUE TITLE
CockroachDB numeric precision misinterpreted

### ISSUE THREAD

**Issue by willrnch** [TablePlus/TablePlus#2477]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

`CockroachDB CCL v21.1.7 (x86_64-apple-darwin19, built 2021/08/09 17:58:36, go1.15.14)`

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

`Build 381`

3. The steps to reproduce this issue:

Create a table with a numeric column with a precision other than 10:

```sql
create table test ("value" numeric(12));
```

TablePlus will generate the following query to retrieve the table details:

```sql
SELECT
	column_name,
	udt_name,
	numeric_precision_radix AS numeric_precision,
	numeric_scale AS numeric_scale,
	is_nullable,
	column_default,
	column_name AS foreign_key
FROM
	information_schema.columns
WHERE
	table_name = 'test'
	AND table_schema = 'public';
```

and will use the `numeric_precision_radix` as the `numeric_precision`. It should use the `numeric_precisions` instead:

```sql
SELECT
	column_name,
	udt_name,
	numeric_precision,
	numeric_scale AS numeric_scale,
	is_nullable,
	column_default,
	column_name AS foreign_key
FROM
	information_schema.columns
WHERE
	table_name = 'test'
	AND table_schema = 'public';
```

**Comment by huyphams** [comment]
Thanks @willrnch I've fixed it! please find the hotpatch here: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
