### ISSUE TITLE
Main window border color

### ISSUE THREAD

**Issue by kczx3** [TablePlus/TablePlus#2478]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 176

3. The steps to reproduce this issue: N/A

Just updated to build 176 and notice a new light gray border around the main window that I don't recall seeing before.  I use the Dark theme and the border is pretty distracting now.  It appears to get much darker when the window does not have focus and I prefer that color.  Might be nice to have a setting to toggle it or customize the color.

**Comment by huyphams** [comment]
Hi @kczx3 please click the title bar and choose the first color. it would fix the issue. It would be the same as Windows.

If you have any issue in the future, please report it to Windows repo: https://github.com/TablePlus/TablePlus-Windows/issues
<img width="835" alt="Screen Shot 2021-08-24 at 7 55 22 PM" src="https://user-images.githubusercontent.com/3654622/130620032-b49547ba-44c7-42f5-8d30-74d55528bb4e.png">

**Comment by kczx3** [comment]
Wow, that was easy.  Thanks!  Is that documented anywhere so that I wouldn't have had to bother you?

(Sorry, didn't realize there was a separate repo for Windows.)

**Comment by huyphams** [comment]
It's here: https://docs.tableplus.com/gui-tools/the-interface/toolbar#customize-toolbar
