### ISSUE TITLE
Cannot connect to MariaDB with self-signed ECSDA certificates

### ISSUE THREAD

**Issue by sicusa** [TablePlus/TablePlus#2483]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql  Ver 15.1 Distrib 10.6.4-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 376

3. The steps to reproduce this issue:
I use [smallstep/step-ca](https://hub.docker.com/r/smallstep/step-ca) to create my self-signed certificates. After installing root certificate to computer, I can connect to my MariaDB Server in the terminal:

```
> mysql -u conlang -h db.gilatod.art --ssl-ca='~/Documents/Certificates/root_ca.crt' --ssl-cert='~/Documents/Certificates/database/cert.pem' --ssl-key='~/Documents/Certificates/database/cert.key'
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 42
Server version: 10.6.4-MariaDB-1:10.6.4+maria~focal mariadb.org binary distribution
 
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
 
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
 
MariaDB [(none)]>
```

But when I try to connect with TablePlus, it shows the following error:
![Image1](https://user-images.githubusercontent.com/1961145/131012189-225a01d3-f57f-49d2-a55b-65cf2ffbaab8.png)
![Image2](https://user-images.githubusercontent.com/1961145/131012205-61476fb7-fc27-4484-abfc-65743164751f.png)

**Comment by huyphams** [comment]
Hi guys, If you have a chance, plese try this patch it should fix the issue:
https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
