### ISSUE TITLE
Basic chart capabilities

### ISSUE THREAD

**Issue by JivanRoquet** [TablePlus/TablePlus#2485]
It would be very handy to have some basic chart capabilities that allow the user to display results in chart form.

Especially handy when doing group by queries and time series. It would avoid having to export the results into a visualisation software.

**Comment by huyphams** [comment]
Hi @JivanRoquet if you are using the iOS version, TablePlus support basic chart feature. You can use the PC/MAC license for the iOS version!
Thanks

**Comment by JivanRoquet** [comment]
@huyphams Thanks for the tip!!! Any plans to add some of these to the desktop version?

**Comment by huyphams** [comment]
We're working on it. Please wait for the next update.

<img width="1569" alt="Screen Shot 2021-08-31 at 5 46 31 PM" src="https://user-images.githubusercontent.com/3654622/131489391-43d86740-287e-462d-9c26-00ca3e9b4269.png">

**Comment by JivanRoquet** [comment]
Just tried it out with the new release, this is amazing 🎉 

thanks @huyphams
