### ISSUE TITLE
UX / UI : Add a new primary column with auto_increment

### ISSUE THREAD

**Issue by jolipixel** [TablePlus/TablePlus#2486]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MariaDB 10.4.6

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
Version 4.1.0 (376)

**3. The steps to reproduce this issue:**
It is not possible to add a new column to an existing table with `AUTO_INCREMENT` and define it has `PRIMARY` with the current User Interface.

Following query do the job:
```
ALTER TABLE `db`.`table` 
ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT FIRST,
ADD PRIMARY KEY (`id`);
```

**Comment by huyphams** [comment]
Hi @jolipixel this build should fix this issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Please let me know if you have any problem with it.
Thanks
