### ISSUE TITLE
Msg: 207, Line 1, State: 1, Level: 16 Invalid column name 'Remarks'. All changes were reverted (DDL statements can't be reverted).

### ISSUE THREAD

**Issue by kzhui125** [TablePlus/TablePlus#2487]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64) 
	Nov  6 2020 16:50:01 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 381

3. The steps to reproduce this issue:

```sql
SELECT TOP 100
  B.Remarks, B.AppKey
FROM Table1 A INNER JOIN Table2 B
ON A.AppKey = B.AppKey
```

edit Remarks column, save, I get error "Msg: 207, Line 1, State: 1, Level: 16 Invalid column name 'Remarks'. All changes were reverted (DDL statements can't be reverted)."

**Comment by huyphams** [comment]
How did you edit it @kzhui125 ? I don't understand the issue.

**Comment by kzhui125** [comment]
```
SELECT TOP 100
  B.Remarks, B.AppKey
FROM Table2 B INNER JOIN Table1 A
ON A.AppKey = B.AppKey
```
works

AppKey is primary key

<img width="222" alt="1" src="https://user-images.githubusercontent.com/11925432/131221414-a5f228c8-9b57-4c81-8326-f67e82515b8c.png">
then command + s

**Comment by kzhui125** [comment]
double click remark cell, edit a different value(such as a123) ,save

**Comment by huyphams** [comment]
We should not edit a result from a JOIN query, it could yield unexpected result.

**Comment by kzhui125** [comment]
thanks, but it works when Remarks is the first table of JOIN query

**Comment by huyphams** [comment]
We will close this as TablePlus doesn't support edit rows from a join query. And we should not edit the value of the join query.
