### ISSUE TITLE
⌘-W closes tab in another window instead of the frontmost window

### ISSUE THREAD

**Issue by zydeco** [TablePlus/TablePlus#249]
When pressing ⌘-W to close a non-workspace window, it closes a tab in one of the workspace windows instead of closing the frontmost window.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
n/a

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 87

3. The steps to reproduce this issue:
 * Open a workspace
 * Choose "About TablePlus" from the application menu
 * Press ⌘-W to close the about window
 * Instead, a tab in the workspace will close, and the frontmost window will remain

In the new workspace window, ⌘-W is ignored completely instead of falling through to a background window, which is less destructive.

**Comment by huyphams** [comment]
Thank @zydeco I'm fixing it now.
