### ISSUE TITLE
Feature request: Support for TLS v1.2

### ISSUE THREAD

**Issue by patrickvuarnoz** [TablePlus/TablePlus#2496]
Our server admin notified me that TablePlus is connecting to the server with a (now) deprecated TLS v1.1 protocol. Would it be possible to upgrade the protocol to TLS v1.2?

**Comment by huyphams** [comment]
Hi @patrickvuarnoz please do not remove issue template question. I don't understand or can't reproduce your issue without it

**Comment by patrickvuarnoz** [comment]
Sorry, for that. Here we go:

### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.30

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 382

3. The steps to reproduce this issue: Connect to server, e.g. 10.0.0.1:3306. SSL mode is set to REQUIRED. I also do provide SSL keys for that connection should that matter.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Which driver are you using @patrickvuarnoz please do not use the old driver, we only use old driver for very old MySQL version.

<img width="525" alt="driver" src="https://user-images.githubusercontent.com/3654622/132209752-b59e1745-833d-4c02-a47e-87027852c19a.png">

**Comment by huyphams** [comment]
The default version should always use the TLSv1.2
<img width="474" alt="Screen Shot 2021-09-06 at 6 22 28 PM" src="https://user-images.githubusercontent.com/3654622/132209960-1d4a871f-f6c8-4a32-8151-60690afa1000.png">

**Comment by patrickvuarnoz** [comment]
Yes, these connections were set to Ver = OLD. But I don't recall having ever set such an option. 
But hey, with Ver = DEFAULT everything works and it indicates TLS v1.2 as you mentioned. 

Many thanks for your quick help!
