### ISSUE TITLE
Feature Request: Add text wrapping functionality to data view

### ISSUE THREAD

**Issue by ryangurn** [TablePlus/TablePlus#2497]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.5.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.1.2 (382)

3. The steps to reproduce this issue:
No Issue

I am requesting the addition of text wrapping for rows in the data view. This will allow for more easy viewing of data that is quite long, specifically in text, medium text, and long text columns. It is quite hard to view the information at a glance when you need to click on each row to view the full extent of the information in the sidebar. At least some sort of setting of option for this would be wonderful.

**Comment by huyphams** [comment]
Hi @ryangurn You can view the text by:
1. Middle mouse click.
2. Hit Command + Return.
3. Right click -> Quick Look Editor.

<img width="1727" alt="Screen Shot 2021-09-07 at 6 42 16 AM" src="https://user-images.githubusercontent.com/3654622/132266030-8dc26e5e-bb02-4d97-a35d-60e316d92a1c.png">

**Comment by ryangurn** [comment]
I understand that exists, however it is cumbersome to perform three steps to read large data (which is most data nowadays) when it could just be a toggle-able setting.

**Comment by huyphams** [comment]
@ryangurn it's three ways not three steps.

**Comment by ryangurn** [comment]
@huyphams ah, I did not get that

**Comment by ryangurn** [comment]
you still might want to consider a solution that could just be toggled a single time to make life easier

**Comment by huyphams** [comment]
Those step are single time and the last one are two step because of the right click > Select menu, how does it could be faster @ryangurn do you have any suggestion?

**Comment by ryangurn** [comment]
a setting of **wrap text** setting that is clicked once no matter how many records there are, so that you can view all the data on the data view without the need to use a separate view.

**Comment by huyphams** [comment]
So I think the right sidebar does it very well, we can also filter the columns and navigate with up/dow arrow

**Comment by ryangurn** [comment]
This is an example of the type of data that would be really nice to view without needing to expand the column to 10x its size. 
![Screen Shot 2021-09-06 at 7 53 16 PM](https://user-images.githubusercontent.com/1297082/132266388-4d3f59a2-bc9e-423c-8e1d-db051383b744.png)

**Comment by ryangurn** [comment]
yes the sidebar helps but it also reduces amount of space that is available to view the information in the first place

**Comment by huyphams** [comment]
Thanks @ryangurn so I think we can put an option in quicklook that could keep that window open.
