### ISSUE TITLE
Add support for $1, $2, parameters

### ISSUE THREAD

**Issue by sgronblo** [TablePlus/TablePlus#2498]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 11.10
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.1.2 (382)
3. The steps to reproduce this issue:
    1. Create a query like `SELECT * FROM client WHERE id = $1`
    2. Enable "Enable query params"
    3. Select `\$[\w.]+` from the variable regex dropdown
    4. Press "Run Current"
    5. You would expect a dialog for setting the $1 parameter to show up but instead the query is run and errors with "ERROR:  there is no parameter $1"

**Comment by sgronblo** [comment]
Actually the description for the character class `\w` is:

> Alphanumeric characters plus "_"

or

> [A-Za-z0-9_]

https://en.wikipedia.org/wiki/Regular_expression#Character_classes

So technically it should already work?

**Comment by huyphams** [comment]
Ah thank you @sgronblo my bad. I fixed it, if you have a chance, please try this hot patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
