### ISSUE TITLE
Add option to press middle mouse wheel click to close tabs

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#25]
![screen shot 2017-07-28 at 10 41 45 pm](https://user-images.githubusercontent.com/7946786/28742493-5f2e7b90-73e6-11e7-969a-d0ef296c4689.png)

**Comment by huyphams** [comment]
Sure, and switch tab by numpads too.

**Comment by huyphams** [comment]
Added in new release 👍🏻
