### ISSUE TITLE
Option: Automatically UPPERCASE keywords only works on return/tab

### ISSUE THREAD

**Issue by simongade** [TablePlus/TablePlus#2503]
I would except the option "Automatically UPPERCASE keywords" to ALWAYS uppercase keywords. But it only does so if you press return og tab after typing a keyword.

MySQL, TablePlus Version 4.1.2 (383)

**Comment by huyphams** [comment]
it's an intentional behavior. The keyword could match with table name so we only uppercase it when the user hit return or tab.
