### ISSUE TITLE
Database Treeview

### ISSUE THREAD

**Issue by lailton** [TablePlus/TablePlus#2508]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB last version

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 388

3. The steps to reproduce this issue:
It is not an issue, it is a suggestion.

I would like to suggest 2 features to tablePlus.

1 - When we have multiple databases with _ would be nice if it can be converted to treeview, example:

beta_CLI01
beta_CLI02
beta_CLI03
manager_CLI01
manager_CLI02

to something like:

- beta
  - CLI01
  - CLI02
  - CLI03
- manager
   - CLI_01
   - CLI_02

2 - Sometimes I am doing some IMPORT database via command line, and to be able to see new database, I need to close the dialog to select database ( if it was not ready yet ) and repent multiple times until I receive it.

Suggestion, add a button REFRESH to show new databases it can be together with buttons + - ( rectangle in blue )

![Screen Shot 2021-09-28 at 00 23 21](https://user-images.githubusercontent.com/59419433/135017985-ad22fa34-d05f-4452-b054-7fb0798a8306.png)

It is just a suggestion, I normally use the search bar to find client database. but if possible treeview will be cool :)

Thanks

**Comment by huyphams** [comment]
We will not implement this feature at the moment as it could increase the complexity of the sidebar, we will update this issue when we make an option to toggle this.
Thanks
