### ISSUE TITLE
Can no longer use multiple tabs

### ISSUE THREAD

**Issue by tcervo** [TablePlus/TablePlus#2510]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.0.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 388

3. The steps to reproduce this issue: Connect to a table, open a new tab, connect to a different table - it opens in the original tab, overwriting the first table.

I recently updated to MacOS 11.6 (Big Sur). Ever since, I can only use a single tab at a time. No matter how many new tabs I open (they all open to a SQL Query window), trying to load a new table will overwrite the existing table/tab. Previously, it would overwrite the new/currently selected tab. I checked for updates, and TablePlus says I'm up to date (4.2.0). This is a paid version, and I confirmed it's still registered.

**Comment by huyphams** [comment]
Hi @tcervo you can open multiple tabs in many ways:

1. Double click items.
2. Right-click open in new tab.
3. Hold command + enter in open anything (Command + P).
4. Modify the content of the table, the tab will be pinned and never be replaced.
5. Change back the command + T behavior to the empty tab.

<img width="1035" alt="abc" src="https://user-images.githubusercontent.com/3654622/135125172-6d4091db-8bf0-4d98-a373-6d194bba0d03.png">

**Comment by tcervo** [comment]
Thanks, @huyphams. Seems the behavior has changed a bit(?). I used to just command+T then click on a table from the Items list and it would open in the newly opened tab. I changed the New Tab behavior to Empty tab, and that works.
