### ISSUE TITLE
Missing 'dialog' plugin on Windows

### ISSUE THREAD

**Issue by quinyx-tjeerd** [TablePlus/TablePlus#2512]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows:  Version 4.5.0 (178) - x64

3. The steps to reproduce this issue:
Trying to connect gives a popup:
"Authentication plugin 'dialog' cannot be loaded: The specified module cannot be found."

**Comment by huyphams** [comment]
Thanks @quinyx-tjeerd this is the macOS repo. Moved to https://github.com/TablePlus/TablePlus-Windows/issues/450

**Comment by huyphams** [comment]
If you have a chance, please install this patch: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0 it should fix the issue.
Thanks
