### ISSUE TITLE
"New view" regression - syntax error CREATE VIEW

### ISSUE THREAD

**Issue by nachocab** [TablePlus/TablePlus#2514]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 13.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 391

3. The steps to reproduce this issue:

    1. Click on "New view" and rename it "tmp"
    2. Paste a test query "SELECT 1;" and press Save
    3. Expected output: CREATE VIEW tmp AS SELECT 1;
    4. Actual output: CREATE VIEW tmp AS ; (which leads to a syntax error) 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @nachocab thank for letting me know, if you have a chance, please download this hotpatch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
It should fix the issue.

**Comment by nachocab** [comment]
Thanks! How long does it usually take for the update to go through Setapp?

**Comment by huyphams** [comment]
Now, just a few minutes ago.
