### ISSUE TITLE
Confirm message when delete connection

### ISSUE THREAD

**Issue by erashdan** [TablePlus/TablePlus#2516]
1. Which driver are you using and what version of it? 
Not related to database connection

2. Which TablePlus build number are you using:
Version 4.2.0 (388)

3. The steps to reproduce this feature:
- Open window that shows all connections
- Right-click on any saved connection
- Click delete 
- No confirm message

**Comment by huyphams** [comment]
The connection is not critical data and the user can recreate it easily, put a confirmation popup on it is not a good pattern. TablePlus does confirm us if we try to delete a group (because recreate many connections is a bit annoyed if we delete it accidentally).
