### ISSUE TITLE
Importing / Open .diagram file

### ISSUE THREAD

**Issue by mmaestrini** [TablePlus/TablePlus#2517]
Hi everyone

Awesome thing to have the generation of ER diagrams. However I don't understand once i created it and saved it as .diagram file, how do i open/import it again?

**Comment by huyphams** [comment]
Yes, you can import diagram from file. If you have any issue with it, please submit the issue here: https://github.com/tableplus/diagram-plugin
Thanks!

**Comment by mmaestrini** [comment]
Yes but the questions was how to import it. Can’t see anywhere how to. Sorry for the stupid question

**Comment by huyphams** [comment]
Please see the image below:

<img width="1715" alt="import" src="https://user-images.githubusercontent.com/3654622/135829208-c1ccb78a-d453-4875-a51a-d7aee96f1d6a.png">

**Comment by mmaestrini** [comment]
thanks
