### ISSUE TITLE
Open database: last database entry is obscured by [+/-]

### ISSUE THREAD

**Issue by BarryCarlyon** [TablePlus/TablePlus#2518]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Windows 180

3. The steps to reproduce this issue:

- Open a Connection to a server
- Click the Database Button to get the DB list
- Observe final entry being obscured

![image](https://user-images.githubusercontent.com/20999/135882626-480c2470-1ad5-4bdc-974d-b62bdf6556b6.png)

**Comment by huyphams** [comment]
Hi @BarryCarlyon thank you for letting me know. We've fixed it. It will be released in the next update
<img width="667" alt="Screen Shot 2021-10-12 at 12 50 21 PM" src="https://user-images.githubusercontent.com/3654622/136898955-7ad93be9-2238-469e-a240-578109383a0d.png">
.
