### ISSUE TITLE
Unable to view tables' information once the pop-up to upgrade plans appears

### ISSUE THREAD

**Issue by ashishraste** [TablePlus/TablePlus#252]
1. Which driver are you using and version of it : MySQL/MariaDB, ver 15.1  Distrib 10.2.10-MariaDB

2. Which TablePlus build number are you using : Build 87

3. The steps to reproduce this issue: Observed this issue after a couple of hours of opening/using the app and starts when the app asks the user to upgrade with the following message:

````
You're on the Free version now. Please upgrade to open Unlimited Tabs 🚀
````

**Comment by huyphams** [comment]
The free version can only open two tab, please close the other tabs and then you can open that table

**Comment by ashishraste** [comment]
Ah I see. Closing this issue then. Thanks!
