### ISSUE TITLE
In "Run Current" query mode an update statement doesn't indicate how many rows have changed

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#253]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 9

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
87

**3. The steps to reproduce this issue:**
I don't know if it has to do with Run Current vs Run All. However, if I execute a single statement that has an update in it all I receive is 

```
Query OK
```

In Postico it comes back as

```
UPDATE 3
```

Similar situation if I try to begin, commit or rollback a transaction. I simply get 

```
Query OK
```

versus

```
BEGIN
```

**Comment by huyphams** [comment]
Hey can you check this build:
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
1. Support enter key as an alias of return in: Execute Query, open anything, autocomplete.
2. Show the number of row affected.

**Comment by nathanpalmer** [comment]
I wasn’t able to try that build, but the latest release that includes these work perfect. Thank you!
