### ISSUE TITLE
Tableplus, AWS ssm bastion, and IAM authentication

### ISSUE THREAD

**Issue by janmeier** [TablePlus/TablePlus#2531]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgresql 11, running on RDS aurora

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.5.0 (396)

3. The steps to reproduce this issue:

So this is is not an issue per se, but more a question about how to work best with tableplus in the context of AWS RDS. Let me know if I should post it somewhere else.

We have two problems that we need to solve - Connecting to a database via an ssh tunnel, and getting a temporary password each time a user needs to log in:

* Our database is in a private VPC - therefore we need to open an ssh tunnel to connect to it. However, instead of a regular ssh bastion host, we use what AWS calls a managed instance. Basically, what that means is that you use the AWS CLI to open the SSH session, and access are then handled via IAM, instead of via ssh keys. In practice we have the following in our `.ssh/config`. Notice that we are using `ProxyCommand` to call the AWS cli to start the session
```config
host lenus-prod-eu
    ProxyCommand sh -c "aws ssm start-session --target XXX --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
    User ec2-user
    IdentityFile ~/.ssh/rds-bastion.pem
    LocalForward 5433 clusterXXX.eu-west-1.rds.amazonaws.com:5432
```

However, tableplus does not accept `lenus-prod-eu` as a host. It seems that it's not using my ssh config 
![image](https://user-images.githubusercontent.com/1210224/139053925-cf731da6-a319-4a93-b9a1-aa1863b1f2da.png)

This issue is already mentioned in https://github.com/TablePlus/TablePlus/issues/2241 and https://github.com/TablePlus/TablePlus/issues/2003

* We are using RDS IAM auth - This means users use a short-lived token to log, instead of a password. This token is generated using the aws cli: `aws rds generate-db-auth-token --hostname XXX --port 5432 --region us-east-1 --username XXX`. Ideally we would like to automate this as well, instead of requiring users to generate the password via the terminal

This is already mentioned in https://github.com/TablePlus/TablePlus/issues/2446 and https://github.com/TablePlus/TablePlus/issues/2007

To work around these issues, I've had to create a custom script that opens the ssh tunnel, generates the token, and calls `open "postgres://user:passsword@host ..."` to open tableplus. However, this comes with a lot downsides for our users. They can no longer work with saved queries, or change any connection settings (such as enabling safe mode), since tableplus sees the connection as a new database each time.

Do you have any pointers on how we could improve this?

**Comment by soymsk** [comment]
@janmeier 
> However, tableplus does not accept lenus-prod-eu as a host. It seems that it's not using my ssh config

My past issue might relate to your issue. (sorry if I missed something)
https://github.com/TablePlus/TablePlus/issues/2491

Currently, tableplus can read my ssh config if I launch it by CLI `/Applications/TablePlus.app/Contents/MacOS/TablePlus` and I'm able to connect my rds via AWS SSM.

I'm very looking forward they can solve my above issue.

**Comment by huyphams** [comment]
<img width="1173" alt="Screen Shot 2021-11-23 at 7 38 50 PM" src="https://user-images.githubusercontent.com/3654622/143025505-20798375-a5a8-4158-ab8c-eca1696c86d9.png">

There is a debug log, could you enable it and see what is going on?
Thanks @soymsk

**Comment by soymsk** [comment]
![image](https://user-images.githubusercontent.com/1835770/144691892-6d2d9499-945b-485e-ad16-c40436069bc9.png)


To enable ssh debug log, I should launch TablePlus from Terminal. From terminal launch, I never met this issue.
So its log will not show any hints about my issue.

Is there any way to see log with launching from Application Icon?

**Comment by janmeier** [comment]
@huyphams Im experiencing the same behaviour. When I open table plus directly through /Contents/MacOS/TablePlus, the ssh tunnel works, but not when launching table plus normally

**Comment by huyphams** [comment]
I think the issue could be related to the permission. (Run directly on Terminal Vs Double click to run the app). Could you check if it has the same access permission?

**Comment by janmeier** [comment]
> I think the issue could be related to the permission. Run directly on Terminal Vs Double click to run the app, could you check if it has the same access permission?

How would I check that?

**Comment by fitex** [comment]
Also same situation here: it doesn't work when launching TablePlus from dock, but it work fine when launching from Terminal (/Applications/TablePlus.app/Contents/MacOS/TablePlus). 
Any update on a fix?

**Comment by janmeier** [comment]
So far what I have is a bash script that can be saved as `.command` file on the desktop, allowing users to double click on it. 

It handles MFA, opens the tunnel, puts the password into the clipboard, and opens table plus so the user just has to click on the right connection and paste the PW.

```bash
#!/bin/bash -e

USERNAME=jan
HOSTNAME=XXX.eu-west-1.rds.amazonaws.com
PORT=5433
REGION=eu-west-1

aws-mfa 
ssh -f lenus-prod -L $PORT:$HOSTNAME:5432 sleep 100

PGPASSWORD=$(aws rds generate-db-auth-token --hostname $HOSTNAME --port 5432 --region $REGION --username $USERNAME) 
echo "Opening tableplus. When prompted, simply press CMD+V to paste your password (its already in the clipboard)"
echo $PGPASSWORD | tr -d "\n" | pbcopy

/Applications/TablePlus.app/Contents/MacOS/TablePlus
```

This is working _okay_, but I would still love it all this could be handled by table plus directly

**Comment by huyphams** [comment]
Just an idea, I think we can add a tab for bash script here. So basically the bootstrap command will support two scripting types. But I'm not sure if the app can read those variables.

1. SQL
2. Bash script.

<img width="1034" alt="bash" src="https://user-images.githubusercontent.com/3654622/145566260-76d77dd6-773a-42eb-91ee-eb41eaa2a4c2.png">

**Comment by janmeier** [comment]
> Just an idea, I think we can add a tab for bash script here. So basically the bootstrap command will support two scripting types. But I'm not sure if the app can read those variables.
> 
> 1. SQL
> 2. Bash script.
> 
> <img alt="bash" width="1034" src="https://user-images.githubusercontent.com/3654622/145566260-76d77dd6-773a-42eb-91ee-eb41eaa2a4c2.png">

I think that makes a lot of sense!

For our usecase, the bash script would then set `PGPASSWORD`, and tableplus should read that and use it as the password. Do you think that would be doable? Or some other way to get the password from the script to tableplus

Our script would basically do three things
1. Check if the user has a valid mfa token, and prompt for a code if not
2. Open SSH tunnel
3. Get temporary password

Number 1. might be a bit more cumbersome, since it can potentially required interaction from the user (inputting mfa code if the token has expired)

**Comment by jason-nabooki** [comment]
@huyphams should we open a separate issue regarding the bug where we can't use an instance ID as the SSH hostname when opening from the dock?

Do you have any suggestions on how to compare permissions?

**Comment by fenichelar** [comment]
When launching from Finder/Dock/Spotlight, `PATH` is `/usr/bin:/bin:/usr/sbin:/sbin`. `aws` and `session-manager-plugin` are not likely to be installed/symlinked there. I installed `aws` and `session-manager-plugin` using Homebrew, so both were symlinked to `/usr/local/bin`.

The full path for `aws` could be used in `~/.ssh/config`, but I am not aware of a way to pass the path of `session-manager-plugin` to the `aws` command. Therefore I put the following in my `~/.ssh/config`:

```sh
Host i-* mi-*
  ProxyCommand sh -c "PATH=/usr/local/bin:$PATH && aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```

**Comment by jason-nabooki** [comment]
Thank you so much @fenichelar, that fixed the issue!

**Comment by mpyw** [comment]
@fenichelar it worked, thanks!

**Comment by huyphams** [comment]
TablePlus now supports getting the password via Command Line IAM.

![CleanShot 2022-09-23 at 15 09 27@2x](https://user-images.githubusercontent.com/3654622/191918020-20582fcf-2e9b-48a6-a17b-096d741f52c4.png)

if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're seeing any issue.

**Comment by erikdw** [comment]
AFAICT this issue is indeed exactly what @fenichelar said [above](https://github.com/TablePlus/TablePlus/issues/2531#issuecomment-1071949787):  the `PATH` of the TablePlus process when you launch TablePlus from Spotlight/Finder/etc. does not include the non-system paths where things like `session-manager-plugin` are installed by `brew`.

The workaround I'm using right now is to modify `launchctl` to add a `PATH` env that includes `/opt/homebrew/bin`.  i.e.,
* https://github.com/qutebrowser/qutebrowser/issues/4273#issuecomment-595892960

Perhaps TablePlus could provide something like one of these ideas as a solution that avoids modifying our `~/.ssh/config` files, or tweaking our entire system:
* an option to set the `PATH` for the TablePlus program
* an option to set the `PATH` used when launching the SSH tunnels (where the `PATH` is used to execute the `ProxyCommand` in `~/.ssh/config`)

**Comment by paulhansford** [comment]
> TablePlus now supports getting the password via Command Line IAM.
> 
> ![CleanShot 2022-09-23 at 15 09 27@2x](https://user-images.githubusercontent.com/3654622/191918020-20582fcf-2e9b-48a6-a17b-096d741f52c4.png)
> 
> if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0 Please let me know if you're seeing any issue.
Great to see IAM authentication being supported!
But, I see the dropbox link is for a `.dmg` file. 
Is there a supported Windows client with the same option to use commandline/IAM authentication token calls? I have checked for updates and updated today to `Version 4.1.9 (206) - x64`.

**Comment by huyphams** [comment]
Hi we're going to release the Windows update soon (within this week), which include this feature and metrics board.

**Comment by mm-y-aoki** [comment]
When using IAM authentication, what should the value in the password field be in the following format?

`aws rds generate-db-auth-token --hostname hoge.cluster-abcdefg.us-east-1.rds.amazonaws.com --port 5432 --region us-east-1 --username hogeroot`

If I type in the terminal command, a token is returned as a response, but even if I enter the password as shown in the password entry form, no connection is made!

If the value received in the response is copied directly to the password input form, the connection was established.

**Comment by huyphams** [comment]
> even if I enter the password as shown in the password entry form, no connection is made!
> If the value received in the response is copied directly to the password input form, the connection was established.

Seems like those statements are conflicting. So when you copy the password, it works or not?

**Comment by erikdw** [comment]
@mm-y-aoki : did you try the workarounds above?  https://github.com/TablePlus/TablePlus/issues/2531#issuecomment-1264274014

@huyphams : did you see my suggestion above to update Tableplus avoid needing to do those workarounds?

**Comment by huyphams** [comment]
Hi @erikdw on the release 
Build 468 - Ready for macOS Ventura
Release date: 25 October 2022.

We've support run AWS IAM with login (which loads .zprofile). If you have a chance, you could try it. Btw, let me check if there is any way to load those environments to TablePlus upon startup.

**Comment by mm-y-aoki** [comment]
@huyphams 
Sorry for the strange explanation.

- Cannot connect to password input form with "aws rds generate-db-auth-token ~~~~"
- Enter the command "aws rds generate-db-auth-token ~~~~" in the terminal, and a token will be returned as a response.
- If you put the token in the password input form, you can connect.

This is what I wanted to tell you.

@erikdw
Thank you for your comment.

I am running the app from the Finder as you said.
After running "launchctl setenv /opt/homebrew/bin" from the command line, I restarted the app to check the connection, but still no connection

**Comment by huyphams** [comment]
thanks @mm-y-aoki  Please make sure that the password which was returned from the statement is clean (pure password), does it is return with extra spaces or new lines?

**Comment by mm-y-aoki** [comment]
@huyphams 
The password returned from the statement was clean (pure password)

Just to be sure, is the value that should be put in the form here the aws command like in the attached image?

or is it the password returned by the statement itself?
"hogedb.cluster-abcdefg.us-east-1.rds.amazonaws.com:5432/?Action=connect&DBUser=hogeroot&X-Amz-Algorithm=AWS4-HMA~~~~"

![スクリーンショット 2022-11-29 16 09 19](https://user-images.githubusercontent.com/54300217/204463235-9284616c-b127-4461-b3f0-f3fd151c06fd.png)

**Comment by erikdw** [comment]
@huyphams 
> We've support run AWS IAM with login (which loads .zprofile)

Sorry, I'm not sure what this means **exactly**.

There are (at least) 2 separate issues being discussed in this issue:
* just getting the password from a command
     * this is working, thanks a lot for adding, I have a couple issues with the config not being shareable that I'll raise separately.
* *needing* to launch TablePlus from Terminal or hack your `~/.ssh/config` if you have non-default-PATH resident programs being invoked in your `ProxyCommand`.
      * This is mentioned in a couple comments in this issue:
           * https://github.com/TablePlus/TablePlus/issues/2531#issuecomment-1071949787
           * https://github.com/TablePlus/TablePlus/issues/2531#issuecomment-1264274014

I'm running build 468 & I **have** been successfully using a command to grab the password back and it works, *if* I follow one of the workarounds above.  The root cause of why I need those workarounds seems to be the `PATH` used by TablePlus's running of the `.ssh/config` file's `ProxyCommand`.  It's not including `/usr/local/bin` (or `/opt/homebrew/bin` or whatever) and thus not finding various required scripts.

> I'm very confident this is the root cause of "needing to launch from Terminal", because I can fix the "connection failing" error by *either*
> * modifying the `~/.ssh/config` targets' `ProxyCommand` lines to have `PATH` include `/opt/homebrew/bin` - OR -
> * modifying `/etc/launchd.conf` to define `PATH` as having `/opt/homebrew/bin` 

Happy to fork this off to another issue, but it *is* an issue.

**Comment by huyphams** [comment]
Thanks for the details @erikdw I will look at it.

**Comment by huyphams** [comment]
@mm-y-aoki 
You can put the command line which returns the password into that field.

**Comment by mm-y-aoki** [comment]
My mac OS is Monterey 12.4 so I used launchctl instead of modifying /etc/launchd.conf

https://stackoverflow.com/questions/51636338/what-does-launchctl-config-user-path-do
I rebooted my mac after executing the following command from this site, but I could not connect using [Command Line (IAM authentication)] on the 
`sudo launchctl config user path /opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin`

By the way, the aws command is indeed under /opt/homebrew/bin
```
$ ll /opt/homebrew/bin/aws
lrwxr-xr-x 1 hoge admin 30B 11 21 15:33 /opt/homebrew/bin/aws -> . /Cellar/awscli/2.9.0/bin/aws
```
So now I am running table plus from the terminal and connecting with IAM authentication.

**Comment by erikdw** [comment]
@mm-y-aoki 

You might wanna check if your changes to launchctl got picked up.  You might need to kill Finder, Dock, etc. Try launching again without doing it from the Terminal and then figure out the `PATH` env var in the TablePlus process.

This incantation might help:

```
% ps eww -o command $(ps aux | grep TablePlus | grep Applications | awk '{print $2}') | tr ' ' '\n' | grep PATH
PATH=/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by fenichelar** [comment]
I'm not sure the PATH issue is a TablePlus issue. TablePlus is using the PATH it was given. If you want to use the SSH config file with applications that don't use the user's shell, the SSH config file should be using absolute paths to make it not dependent on the PATH set in the user's shell.

Unfortunately, the AWS CLI doesn't allow the session manager plugin absolute path to be specified, which is an issue AWS should address: https://github.com/aws/aws-cli/issues/6800.

**Comment by mm-y-aoki** [comment]
@erikdw 
I restarted the app and restarted my mac and now I can connect, thank you!

**Comment by MaximeLaurenty** [comment]
I have an issue similar to the first one (ssh config for AWS SSM not properly handled by TablePlus) though it is present in both Dock & terminal launch.
I have a setup similar @fenichelar's comment above with just my AWS profile in addition (`main-ssh`):
```
Host i-* mi-*
 ProxyCommand sh -c "PATH=/usr/local/bin:$PATH && aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p' --profile main-ssh"
 
Host ssh_test
 HostName i-xxxx
```
This works fine to ssh from Terminal, but not within TablePlus.
Logs: `[2022/12/16 14:50:10.877615, 1] ssh_connect_host_nonblocking:  Failed to resolve hostname i-xxxx (nodename nor servname provided, or not known)`

I have a few workarounds, but they aren't very practical for the 10+ instances we manage and the 20+ people who need them: 
1. having the proxycommand within the host (but this requires as many copy-paste as instances).
```
Host ssh_test
 HostName i-xxxx
 ProxyCommand sh -c "PATH=/usr/local/bin:$PATH && aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p' --profile main-ssh"
```
2. indicating in TablePlus the instance id (i-xxxx) directly and not using the declared Host (but it works only for connecting without any SSH detail, + it is a bit of a mess to manage for the team when instances change)
3. using a Host whose name matches the pattern `i-*`(poor naming for end-users)
```
Host i-ssh_test
 HostName i-xxxx
``` 
4. Setting the ProxyCommand for all Host (it's unusable for anyone who connects to any ressource outside AWS SSM):
```
Host *
 ProxyCommand sh -c "PATH=/usr/local/bin:$PATH && aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p' --profile main-ssh"
```
--> It looks like in my case TablePlus doesn't consider the pattern matching on HostName like expected but on Host.
Any idea if I did something wrong and how to solve it?

**Comment by MaximeLaurenty** [comment]
For other with a similar issue: I found a solution by defining the default behaviour after the host specificities:
```
Host ssh_test
 HostName i-xxxx

Host i-* mi-*
 ProxyCommand sh -c "PATH=/usr/local/bin:$PATH && aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p' --profile main-ssh"
```

Given both initial and final orders work fine with standard ssh command, I guess that the issue is be coming from different priority resolution in TablePlus vs standard ssh.
NB: the place of 
```
Host *
 CanonicalizeHostname yes
```
within the file doesn't seem to have any effect here (I tried before, between and after the two Host blocks).

**Comment by alexw23** [comment]
Did anyone get this working?

I've configured it as above comments above, in Terminal running `ssh ec2-user@i-XXXXXXXXXX` works fine. However it doesn't seem to be working within TablePlus. Just seems to hang and doesn't actually connect.

```
 ✘ MacBook-Pro  ~  /Applications/TablePlus.app/Contents/MacOS/TablePlus
2023-02-04 14:16:36.925 TablePlus[29611:2739445] Warning: Window move completed without beginning
[2023/02/04 14:16:38.556568, 3] ssh_config_parse_file:  Reading configuration data from /Users/alex/.ssh/config
[2023/02/04 14:16:38.556619, 3] ssh_config_parse_file:  Reading configuration data from /etc/ssh/ssh_config
[2023/02/04 14:16:38.556657, 2] ssh_config_parse_line:  Unapplicable option: SendEnv, line: 55
[2023/02/04 14:16:38.556666, 2] ssh_connect:  libssh 0.9.5 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
[2023/02/04 14:16:38.556674, 2] ssh_socket_connect_proxycommand:  Executing proxycommand 'sh -c "PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin && aws-vault exec profile-name -- aws ssm start-session --target i-XXXXXXXXXX --document-name AWS-StartSSHSession --parameters 'portNumber=22'"'
[2023/02/04 14:16:38.560596, 2] ssh_socket_connect_proxycommand:  ProxyCommand connection pipe: [20,21]
[2023/02/04 14:16:38.560643, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2023/02/04 14:16:38.560661, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
[2023/02/04 14:16:38.560664, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
[2023/02/04 14:16:38.560666, 3] ssh_connect:  Actual timeout : 120000
[2023/02/04 14:16:38.560682, 4] ssh_socket_pollcallback:  Poll callback on socket 21 (POLLOUT ), out buffer 0
[2023/02/04 14:18:38.562958, 1] ssh_connect:  Timeout connecting to i-XXXXXXXXXXX
[2023/02/04 14:18:38.562996, 3] ssh_connect:  current state : 9
```

**Comment by alexw23** [comment]
The PATH solution fixed it for me.

How has everyone been getting around the password prompts after computer sleep when using `aws-vault`?

**Comment by djpowers** [comment]
The [previous suggestions to permanently resolve the PATH issues](https://github.com/TablePlus/TablePlus/issues/2531#issuecomment-1330197985) are probably better long-term solutions, but if you're hitting this error trying to use IAM authentication and want a quick one-time fix without modifying the PATH the following options worked for me:
- launch TablePlus from the terminal (mentioned above, but I find this specific command easiest):
    ```sh
    open -n /Applications/TablePlus.app/
    ```
- run the full `aws rds generate-db-auth-token` command in your terminal, copy the output; change TablePlus server settings to "Ask every time" and test the connection; paste in the copied password when prompted

Again, you'll probably be better served by one of the other provided workarounds if you'll be connecting to this server regularly, but sharing in case this helps.

**Comment by anentropic** [comment]
It'd be great if we could use env vars as 'dynamic' values in a connection config

That would cover a lot of use cases without adding further complexity on TablePlus side, beyond that one feature

or if `open -n /Applications/TablePlus.app/` can accept a connection url as argument

**Comment by huyphams** [comment]
We will support run any custom script in the up coming update or you can try it here:

https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0

So basically, you can load any script or source.

![Screenshot 2024-03-25 at 4 38 39 PM 2](https://github.com/TablePlus/TablePlus/assets/3654622/b7d3a667-a5e0-44ce-ad57-c5dbea11c5a3)

**Comment by jreidgreer** [comment]
hey @huyphams is there any documentation on how to use the `Bootstrap commands`?

**Comment by alexw23** [comment]
Hi everyone, ended up building a handy script for the ProxyCommand that fixes most of the issues above, plus also:
- Integrates with AWS-vault
- Uses an idle function to work out if the user is present, if not will skip and return 1
- Finds the AZ of an instance (needed for `ec2-instance-connect`)
- Logs all events and new sessions

## Pre-requisites 

This script assumes you have [aws-vault](https://github.com/99designs/aws-vault) configured already and are [using SSO](https://github.com/99designs/aws-vault/blob/master/USAGE.md#single-sign-on-sso), but totp should also work fine if it's touch based.

Also assumes you've setup an EC2 instance, with firewall access to the RDS database. And have setup EC2 instance connect as required.

## Scripts

**~/.ssh/config**

```sh
Host i-*
    IdentityFile ~/.ssh/id_rsa
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
    ProxyCommand ~/utils/proxy-command --instance-id %h --remote-user %r --port %p --aws-vault-profile prod-admin
```

**~/utils/proxy-command**

```bash
#!/bin/bash

set -x

export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin:$PATH

# Default values
identity_file="~/.ssh/id_rsa"
aws_vault_profile=""
port_number=22
instance_id=""
remote_user=""
logfile="$HOME/.ssh/aws-bastion.log"
idle_seconds=300
trim_log_lines=1000

# Function to display help message
usage() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --instance-id ID           The AWS instance ID."
    echo "  --remote-user USERNAME     The username for the remote instance."
    echo "  --port PORT                The port number for SSH connection (default: 22)."
    echo "  --aws-vault-profile NAME    The AWS Vault profile to use (default: 'production-admin')."
    echo "  --identity-file PATH        Path to the SSH identity file (default: '~/.ssh/id_rsa')."
    echo "  --logfile PATH              Path to the log file (default: '~/.ssh/aws-bastion.log')."
    echo "  --idle-seconds SECONDS     The number of seconds to check for screen idle time (default: 300)."
    echo "  --trim-log LINES           The number of lines to keep in the log file (default: 1000). If set to 0, no trimming is done."
    echo "  --help                     Display this help and exit."
    echo ""
    echo "Example:"
    echo " ProxyCommand $0 --instance-id %h --remote-user %r --port %p --aws-vault-profile production"
}

# Parse long options
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --instance-id) instance_id="$2"; shift ;;
        --remote-user) remote_user="$2"; shift ;;
        --port) port_number="$2"; shift ;;
        --aws-vault-profile) aws_vault_profile="$2"; shift ;;
        --identity-file) identity_file="$2"; shift ;;
        --idle-seconds) idle_seconds="$2"; shift ;;
        --logfile) logfile="$2"; shift ;;
        --help) usage; exit 0 ;;
        --) shift; break ;;
        *) echo "Unknown parameter passed: $1"; usage; exit 1 ;;
    esac
    shift
done

# Initialize an empty string to collect missing parameters
missing_params=""

# Check each parameter and append to the missing_params string if empty
[ -z "$instance_id" ] && missing_params="--instance-id "
[ -z "$remote_user" ] && missing_params+="--remote-user "
[ -z "$aws_vault_profile" ] && missing_params+="--aws-vault-profile "

# Check if any parameters are missing
if [ ! -z "$missing_params" ]; then
    echo "Missing required parameters: $missing_params"
    usage
    exit 1
fi

export BASTION_LOG_FILE="$logfile"

touch "$logfile"

if [ $(wc -l < "$logfile") -gt 1000 ] && [ "$trim_log_lines" -gt 0 ]; then
    echo "Trimming log file to last 1000 lines" >> "$logfile"
    tail -n 1000 "$logfile" > "$logfile.tmp"
    mv "$logfile.tmp" "$logfile"
fi

# Check idle time to determine if the screen is locked
if [ -n "$idle_seconds" ] && [ "$idle_seconds" -gt 0 ]; then
    idle_time=$(ioreg -c IOHIDSystem | awk '/HIDIdleTime/ {print $NF/1000000000; exit}')
    echo "$(date): Proxy command invoked for instance $instance_id and port $port_number with idle time $idle_time seconds" >> "$logfile"

    # Proceed only if the system idle time is less than the specified idle_seconds
    if [ "$(echo "$idle_time > $idle_seconds" | bc)" -eq 1 ]; then
        echo "$(date): The system has been idle for longer than the specified $idle_seconds seconds. Exiting." >> "$logfile"
        exit 1
    fi
else
    echo "$(date): Idle time not set or set to 0, skipping idle time check and proceeding with the session." >> "$logfile"
fi

# Import default path

with-aws-vault() {
    aws-vault exec $aws_vault_profile -- aws "$@"
}

# Fetch the availability zone of the instance
availability_zone=$(with-aws-vault ec2 describe-instances --instance-ids $instance_id --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' --output text)
echo "$(date): Availability Zone Fetched: $availability_zone" >> "$logfile"

# Send SSH public key using EC2 Instance Connect
ssh_key_response=$(with-aws-vault ec2-instance-connect send-ssh-public-key --instance-id $instance_id --instance-os-user $remote_user --ssh-public-key "file://${identity_file}.pub" --availability-zone "$availability_zone" --output text)
echo "$(date): SSH Key Response: $ssh_key_response" >> "$logfile"

# Start an SSH session using SSM
echo "$(date): Starting SSH session to instance $instance_id on port $port_number" >> "$logfile"
with-aws-vault ssm start-session --target $instance_id --document-name AWS-StartSSHSession --parameters "portNumber=$port_number"
```

## Configuration

Then you configure TablePlus as below:
**DB Host:** your RDS host name
**Port:** your RDS port (i.e 3306)

`Over SSH`
**SSH Host:** (your EC2 instance ID i.e i-33jbsb3h4k3)
**User:** ec2-user
**Port:** 22

Welcome any feedback or improvements.

## TODO:
- [ ] Connect to random EC2 instance based on a tag (i.e. bastion), great for load balancing etc.
- [ ] Boot up an EC2 spot instance at entry, and have this instance turn off automatically when no SSH connections are found.
