### ISSUE TITLE
Feature request: Keep quick look editor open if app not in foreground - MacOS 

### ISSUE THREAD

**Issue by danielcastrobalbi** [TablePlus/TablePlus#2535]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7.29

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 4.5.0 (396)

3. The steps to reproduce this issue:

e.g. open a json column in the quick look editor, switch from TablePlus to another app on your system, the editor closes. 

It would be great to keep the editor open as in some cases you want to compare values in TablePlus with some data in another app. As alternative the editor could be presented in an additional window.

**Comment by benjaminprojas** [comment]
My colleague and I have an argument whether this is the most annoying thing with TablePlus or not 😆

**Comment by benjaminprojas** [comment]
> I think we can use the right sidebar as a temporary solution, but having an option to keep it open is a good idea.

Temporary solution sounds good, better than how it is!

**Comment by arnaudbroes** [comment]
Any update on this yet?

**Comment by arnaudbroes** [comment]
Thank you so much for working on this!

**Comment by huyphams** [comment]
if you have a chance, you could try this build here
https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

**Comment by arnaudbroes** [comment]
@huyphams that seems to be working great - 
![image](https://github.com/TablePlus/TablePlus/assets/18156697/218c9011-351b-47bc-b0b0-7fcd9e1daf92)

You can't imagine how much of a game changer this will be for our team's productivity. I really appreciate it!
