### ISSUE TITLE
MSSQL Stored Procedure Won't Commit

### ISSUE THREAD

**Issue by allenweiss** [TablePlus/TablePlus#2538]
I'm connected to a 2019 MSSQL database on Everleap's servers.  I'm using TablePlus 4.5.0.  Everything works fine except:

1. I add a new Function/Procedure

2. I put in a simple stored procedure and hit commit.

3. Once I do this the function tab closes and nothing happens.  No stored procedure exists.  I have tried this with a number of different functions, etc and the same thing happens...nothing.

I'm not sure what is going on but from all I've read this should be working.

**Comment by andoniserra** [comment]
I have the same problem with Mysql 5.7.34
TablePlus 4.5.0 build 397

**Comment by allenweiss** [comment]
I wrote to their support email address but so far I’ve heard nothing about this issue.

**Comment by huyphams** [comment]
Hi @allenweiss @andoniserra if you have a chance, please download this hotpatch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Please let me know if you are still seeing the issue.

**Comment by allenweiss** [comment]
Thank you....that solved the problem for me.  Much appreciated.

**Comment by andoniserra** [comment]
Solved too :D
thanks!

**Comment by huyphams** [comment]
Thanks 👍
