### ISSUE TITLE
Remote server connection error "SSL connection error: error:00000001:lib(0):func(0):reason(1)"

### ISSUE THREAD

**Issue by nicolasbinet** [TablePlus/TablePlus#2539]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
397

3. The steps to reproduce this issue:
Since a few days the remote connection through password doesn't work any more, the app is returning the following crypic error : "SSL connection error: error:00000001:lib(0):func(0):reason(1)"
I've tried using the server name, IPv4 & IPv6. Nothing is working.

Also, I've enabled the SSL debug log, but no error is being reported.

Any idea what the error means ? and how I could solve it ?

Nicolas

**Comment by huyphams** [comment]
it's the SSL issue. Please try to change the driver version and see how it goes.

<img width="498" alt="Screen Shot 2021-11-03 at 15 32 47" src="https://user-images.githubusercontent.com/3654622/140029543-484eff97-5324-4304-bff4-efb27f5671d8.png">

**Comment by nicolasbinet** [comment]
Ok thanks for pointing me to a direction.
I changed the SSL mode to "Disabled" and it works.
It was previously set to "Preferred", do you know why this doesn't work anymore ?

**Comment by huyphams** [comment]
May I ask what version of MySQL are you using?

**Comment by nicolasbinet** [comment]
The server is running MySQL version 5.7.26

**Comment by huyphams** [comment]
Thanks, please try to change the ssl to old, it support tls v1.1
The default driver requires tls v1.2

**Comment by nicolasbinet** [comment]
Now I'm getting "SSL connection error: protocol version mismatch"

<img width="612" alt="CleanShot 2021-11-03 at 10 28 57@2x" src="https://user-images.githubusercontent.com/867710/140036615-259115df-8b95-4e2c-a2b8-4c552c8bf7c6.png">

**Comment by nicolasbinet** [comment]
@huyphams The problem was rooted on the hosting side. Infomaniak fixed the problem and now keeping the "Default" driver and "Preferred" SSL mode works fine.
