### ISSUE TITLE
Treat ENTER on Keypad the same as RETURN

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#254]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 9

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
87

**3. The steps to reproduce this issue:**
When using Cmd+Return to execute a query I often reach for and try to use Cmd+Enter (keypad Enter.) This works fine in Postico by using either. Can we treat them the same here? 

![maxresdefault](https://user-images.githubusercontent.com/125599/36172563-4a82bc0c-10d4-11e8-9dcf-51b3800ef891.jpg)

**Comment by huyphams** [comment]
Sure @nathanpalmer will be included in next update.

**Comment by nathanpalmer** [comment]
Works great! Thanks.
