### ISSUE TITLE
System Notifications on MacOS

### ISSUE THREAD

**Issue by dstarh** [TablePlus/TablePlus#2542]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.5.0(397)
3. The steps to reproduce this issue:
Run a long running query
Noted: If the bug is related to data, please attach an example SQL data.

When running a long running query, and there are multiple workspaces open, we get alerts between the workspaces.  Is it possible to have those be system alerts?  I would like to get the alert that the query is finished running if I've moved my focus away from Table Plus

**Comment by huyphams** [comment]
Hi @dstarh if the app lose focus TablePlus will send system notification. Please make sure you are not blocking it or in do not disturb mode.
Thanks

**Comment by dstarh** [comment]
Sorry my mistake, somehow they got turned off and I don't usually do that
