### ISSUE TITLE
Query editor history lost

### ISSUE THREAD

**Issue by JivanRoquet** [TablePlus/TablePlus#2543]
Avid TablePlus user here, but really not cool feedback this time.

I was having a PostgreSQL workspace open with a bunch of "SQL Query" tabs open (step 1). Next, I opened another workspace from the same connection, opened the same SQL Query tabs and made many edits to these (that's step 2).

Next I close the workspace in inverse order that I opened them. I then reopen a workspace from this connection, and guess what, all my "SQL Query" tabs went back to the state they were _before_ the many edits made in step 2. Which made me lose several hours of careful step-by-step thinking, and now I can't remember anything of the fine details that went into what was lost.

Yes I know, I can use the "save as" menu entry. Which I'm doing fairly frequently, but just not for this particular work session.

As much as I love TablePlus overall, I never understood why the tab and workspace management was so atrociously bad. The scenario above should be a non-existant issue for any serious piece of software in 2021.

**Comment by huyphams** [comment]
Hi @JivanRoquet please do not remove the issue question template, also the app has the Queries tab which is designed for saving queries. The TMP query could be overridden in many ways and it's not a reliable solution for saving queries.

<img width="1329" alt="queries" src="https://user-images.githubusercontent.com/3654622/140628199-d2a8b577-d205-4097-b699-f1bf76482764.png">

**Comment by JivanRoquet** [comment]
Apologies for removing the question template, was a bit in rant mode :)

Thanks for the prompt feedback.
