### ISSUE TITLE
No universal binary available for SetApp users

### ISSUE THREAD

**Issue by nlenkowski** [TablePlus/TablePlus#2544]
TablePlus is hands down the best MySQL client on macOS today, and a breath of fresh air coming from Sequel Pro 👍  That said, currently only an Intel binary is available to SetApp users and it runs noticeably slower than the universal binary on M1 Macs. In fact, it's so much slower that I’ve stopped using the SetApp version and dropped back to the free trial build, which is released as a universal binary. Much love from us SetApp users if this could be corrected!

**Comment by appcoders** [comment]
Will not happen : https://github.com/TablePlus/TablePlus/issues/2180#issuecomment-962531764

**Comment by alexclst** [comment]
I am really disappointed by this. Luckily for me I feel that I live within the free trial restrictions anyway, but if those ever get stricter it'll be a problem as Setapp has enough else I use I both won't want to drop it, but also not want to pay a separate subscription fee for TablePlus. If this is partially a technical limitation on Setapp not supporting multiple builds, they really need to fix that.

My plan is to use the free trial of TablePlus forever, until it is too restricted for me. Maybe TablePlus and Setapp can come to some other arrangement to grant us access to full features, but that seems very unlikely. I've tried other MySQL apps and none are as good as TablePlus, some don't even have socket support which is critical for my local development servers.

**Comment by nlenkowski** [comment]
[As per this comment](https://github.com/TablePlus/TablePlus/issues/2180#issuecomment-962531764) it looks like TablePlus is leaving SetApp in the near future, so this issue is moot. Call me disappointed as well.

**Comment by kobaltz** [comment]
I've reached out to SetApp to ask on their end to make this relationship work. TablePlus was one of the primary reasons why I even invested in SetApp.
