### ISSUE TITLE
CSV Import fails with an alphanumeric column that starts with numeric value

### ISSUE THREAD

**Issue by kiettran** [TablePlus/TablePlus#2547]
#### Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
MariaDB 10.1.41

#### Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
Version 4.5.0 (396)

#### The steps to reproduce this issue:
1. Create a CSV with two columns. One has an ID number such as `1` and the second column has a string value of `0-S`.
2. File > Import > From CSV...
3. Results the following query which causes an error.
```sql
Unknown column 'S' in 'field list'
INSERT INTO `table` (`id`, `column`) VALUES (1, 0-S);
```

Because the data starts with a `0`, the import tool sees it as a numeric value which is obviously not.

**Comment by huyphams** [comment]
Hi @kiettran your steps to reproduce the issue are not clear. Please show all the steps and other options, such as: creating a new table from a CSV or importing a CSV to a table, map strategy, etc...

**Comment by kiettran** [comment]
I can't reproduce it anymore, thus I will be closing this issue.
