### ISSUE TITLE
Default to "Run Current" instead of "Run All"

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#255]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 9

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
87

**3. The steps to reproduce this issue:**
I ran into a big issue a few days back where hitting Cmd+Return ran every query I had in the window at the time. This was unexpected and led to have to effectively start the process I was working on over again (several update statements cleared out my data.)

I was wondering if it might be more reasonable to default new installations to "Run Current." I later found and defaulted mine to this. 

Postico defaults this way and runs up to the next semicolon.
SQLpro executes everything on Shift-Command-E unless you highlight the current statement (but they also manage multiple results in the same window so it's more obvious.)

**Comment by huyphams** [comment]
Hi @nathanpalmer 

1. We default to run all because this option is added from the beginning. The run current was added later.

2. TablePlus can split result in multiple tabs
<img width="413" alt="screen shot 2018-02-14 at 9 20 14 am" src="https://user-images.githubusercontent.com/3654622/36184766-4b413c10-1168-11e8-9ec8-dfc0962854c1.png">
 see here:

3. I'm thinking about to switch the default as you said, but `run all query` makes more sense than run current. But run current is useful than run all.

**Comment by nathanpalmer** [comment]
2. So, I did see this option, and it's nice. It would be great if it wasn't needed as an option though. If you get multiple results, then multiple tabs automatically show up. Is there a reason I'm missing where we'd want to suppress the results of multiple queries and only show the first? (effectively having that option turned off.)

3. It may be that my usage is different than the norm, but running more than 1 query at a time is the exception. When I do that I highlight those together and then click Run (or Cmd+Enter.) Would love to hear other feedback on if they use it different.

**Comment by huyphams** [comment]
2. Because some users run a script with a thousand of statements (they import a SQL file) and they don't need to see all the result.
3. I'm thinking, but it's one-time config so it's not a big deal, it's just more convenient for new users.

**Comment by nathanpalmer** [comment]
I’d argue that it’s imports to see all the results even for large queries. Going back to my SQL Server days I’d run very large scripts with hundreds of statements in it. Seeing all the results, updated and deleted counts in the result window was very important to ensure accuracy. Especially because it was common to put a begin transaction at the top and a rollback at the bottom, verify all the counts before running it with a final commit.

**Comment by danomano7** [comment]
When I run two queries in one window and run all, I don't see the tabs for both result sets.  It only runs the last statement that was typed.  I have Split results option enabled.  What else am I missing in order to get multiple result set tabs?

**Comment by huyphams** [comment]
Hi @danomano7 do you follow this setting? if would be great if you can you give me the screenshot, thanks.
<img width="940" alt="nice" src="https://user-images.githubusercontent.com/3654622/37360567-46b6d01c-2723-11e8-889c-eeceda6ef274.png">

**Comment by danomano7** [comment]
I have 3 queries and I have split results enabled and run all on by default.  When I run all, I only get the results for the 3rd query on line 7.  No tabs ever show up.


[cid:image001.png@01D3BABC.02428C10]

**Comment by huyphams** [comment]
Can you share me your screenshot @danomano7, my email is huy@tableplusapp.com

**Comment by huyphams** [comment]
it's in build 100 👍
