### ISSUE TITLE
Diagram Generator Plugin couldn't display relationship after exporting into PNG or SVG

### ISSUE THREAD

**Issue by ranggakd** [TablePlus/TablePlus#2555]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2016

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 182

3. The steps to reproduce this issue:
- Install the Diagram Generator Plugin
- Select multiple tables
- Right-click and choose `Generate diagram` > `Generate Diagram selected Items`
- In Diagram Generator observe at least one relationship between tables like this below
![diagram generator](https://user-images.githubusercontent.com/36787606/142965553-7144c266-6515-4eb4-9381-e1d6798463ef.png)
- Choose `Save as PNG` or `Save as SVG` to export the diagrams into a certain file.
- Open the exported file. The relationship is missing.
![image](https://user-images.githubusercontent.com/36787606/142965939-51055367-1165-4db2-bb31-4fb935ceef23.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Wrong repo, it should be reported here: https://github.com/TablePlus/diagram/issues

**Comment by huyphams** [comment]
I could not reproduce the issue, are you using the latest release of the diagram plugin?

**Comment by ranggakd** [comment]
I'm using the fourth version I believe.
![image](https://user-images.githubusercontent.com/36787606/142975789-17a5196b-6771-416f-81d8-09b1df38a568.png)

I will continue to report this issue [here](https://github.com/TablePlus/diagram/issues)
