### ISSUE TITLE
Not full screen when connected to the DB

### ISSUE THREAD

**Issue by cc2937** [TablePlus/TablePlus#2558]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.0.27

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 397

3. The steps to reproduce this issue: after connected to the database

Noted: If the bug is related to data, please attach an example SQL data.

There is always a blank space below, even I full screended the window last time.

Here's the screen shot:

![image](https://user-images.githubusercontent.com/30150098/143518120-030cc156-bc86-4877-a1c0-0e8e6550e6f9.png)

**Comment by adamwinn** [comment]
I've had this same issue for months and months and it drives me nuts

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this hotpatch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 
Please let me know if you are still seeing the issue.

**Comment by newadventure079** [comment]
@huyphams It worked, thanks!  I had to manually enlarge the window to get ride of the space on the bottom and then after that it remembered the window size!

**Comment by cc2937** [comment]
> Hi, if you have a chance, please try this hotpatch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 Please let me know if you are still seeing the issue.

It works! Thanks very very much! 👍
