### ISSUE TITLE
quick look editor incorrect json rendering

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#2570]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 4.5.0 (396)

3. The steps to reproduce this issue:

this json renders incorrectly in the quick look popup:
```
{
    "comments" : "https:\/\/example.com\r\n\"><script src=https:\/\/example.com><\/script>"
}
```
renders as:

```
comment : "https://example.com
```

**Comment by huyphams** [comment]
I think it should look like this, the end quote " was missing because of the new line.


<img width="816" alt="Screen Shot 2021-12-09 at 9 21 59 PM" src="https://user-images.githubusercontent.com/3654622/145413805-409937b2-ec7b-40d8-a1be-bf0bee0bbeef.png">

**Comment by minusf** [comment]
yes, you are correct.  i am not sure why i thought the left side view was supposed to show the whole value, now i see that the right side view is for that.  i'll close the issue, thank you.
