### ISSUE TITLE
[BUG] Filtering queries doesn't reset properly

### ISSUE THREAD

**Issue by nachocab** [TablePlus/TablePlus#2573]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 4.5.1 (401)

3. The steps to reproduce this issue:
- Having a list of folders with queries inside them, type something in the "Search for query" input box (in my case, I search for 80)
![CleanShot 2021-12-15 at 19 10 52](https://user-images.githubusercontent.com/27538/146241898-ab90eb33-6b04-497b-8131-e4bc9425b49f.png)
- A subset of the query files should appear

![CleanShot 2021-12-15 at 19 12 02](https://user-images.githubusercontent.com/27538/146242052-51170529-c9f2-40bf-8afa-d8ea1f98beca.png)

- Clear the search query
- Expected result: all the query files are visible again
- Actual result: only the query files that passed the previous filter are visible. The other files are only visible if a new matching query is entered

**Comment by nachocab** [comment]
@huyphams 

Almost a year has passed and this issue is still unresolved. 

It seems like it would be an easy fix: for some reason, filtering respects top-level query files. However, if they're nested inside a folder, clearing the filter doesn't show all the files that were originally in the folder.

This means that whenever I have to "Search for query…", once I'm done I have to restart TablePlus.

Can anyone reproduce this issue?

**Comment by huyphams** [comment]
Hmm, I'm not sure how I missed this issue? It's an easy fix, let me kill it.

**Comment by huyphams** [comment]
I killed that bug, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Thank you for reminding me. It's weird that I didn't see it :/
