### ISSUE TITLE
TP stuck on 'collecting database information...'

### ISSUE THREAD

**Issue by agatho-daemon** [TablePlus/TablePlus#2574]
Using PostgreSQL 13.5

TablePlus Build 184

Can't figure out the cause to reproduce yet.

I am using two versions of TP, a Windows 10 at home and macOS at the office.

Every now and then the Windows version gets stuck loading a table am working on. Only after accessing the database through the macOS version the next morning in the office can I use the Windows version at home.

Running:

```sql
SELECT * FROM pg_stat_activity;
```
Would list entires where TP is running the following query:
```sql
wait_event_type | Client
wait_event      | ClientRead
state           | idle
query           | SELECT p.oid AS oid,p.relname AS table_name,n.nspname AS table_schema FROM pg_class AS p JOIN pg_namespace AS n ON p.relnamespace=n.oid WHERE p.relkind='r'
```

**Comment by huyphams** [comment]
Hi @agatho-daemon if you have a chance, please download this patch https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 and enable this option, please let me know if you are still seeing the issue.

<img width="762" alt="Screen Shot 2021-12-18 at 10 51 20 AM" src="https://user-images.githubusercontent.com/3654622/146627991-05ec7f6d-ec26-4bec-8e82-8df4020a6d3c.png">
