### ISSUE TITLE
Minimize workspace to dock on mac.

### ISSUE THREAD

**Issue by stsepelin** [TablePlus/TablePlus#258]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
87
3. The steps to reproduce this issue:
When i work only with one workspace and minimize window with it to the dock on mac (Command+M), I can't open it back by clicking on tablePlus icon in dock. Every time it opens new startup window instead of last workspace.

**Comment by huyphams** [comment]
Hi @stsepelin, this is an expected behavior but I think we should change it a little bit. I will come back with a build shortly.

**Comment by huyphams** [comment]
I improved minimized behavior in this build, can you test it and let me know you thought? 😄 
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by stsepelin** [comment]
Right now it's working like expected, but there is something weird in dock (some empty space).
Mac OS: 10.13.3 (17D47)
<img width="251" alt="screen shot 2018-02-14 at 17 59 53" src="https://user-images.githubusercontent.com/8102174/36214089-33a6fa2e-11b1-11e8-96b6-a5957ae09819.png">

**Comment by huyphams** [comment]
Thanks, looks like it's preferences window. Did you minimize TablePlus preferences?

**Comment by stsepelin** [comment]
You are right, that was a preferences window, but when I click on it in dock, nothing happens.

**Comment by huyphams** [comment]
This build should fix all the issues: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
(Include `I click on it in dock, nothing happens.`)
