### ISSUE TITLE
Cannot Establish Connection

### ISSUE THREAD

**Issue by DominiqueA-Kaizen** [TablePlus/TablePlus#2581]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **Version 4.5.2 **

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **402**

3. The steps to reproduce this issue: 

- Import URL
- Connecting to database displays

I am using MacBook Pro and successfully connected to the url in the past.  Now, no connection is established. We have verified the URL.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @DominiqueA-Kaizen I don't think this issue is a TablePlus issue, we also don't have enough info to help you, so I'm closing this issue. Please let me know if you have any questions.
