### ISSUE TITLE
Garbage values returned for RAW data type in Oracle db.

### ISSUE THREAD

**Issue by pavan22** [TablePlus/TablePlus#2586]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oracle Client Version 19.0.0.0.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  build 403

3. The steps to reproduce this issue:

The issue is with the data and the issue is that tableplus  is returning garbage values for RAW datatypes.

Attaching the screenshot of how the data is returned for RAW data type values.

Noted: If the bug is related to data, please attach an example SQL data.
<img width="196" alt="Screenshot 2022-01-04 at 9 42 26 AM" src="https://user-images.githubusercontent.com/16536813/148008668-01b74607-f71d-4d1b-9d2b-ee721d7f6646.png">

**Comment by huyphams** [comment]
Hi @pavan22 @mmvelasquez-mdsol could you please try to change the view encoding to one of these UTF8 and see how it goes?
<img width="566" alt="CleanShot 2022-11-25 at 17 57 52@2x" src="https://user-images.githubusercontent.com/3654622/203969183-2264aee4-8c83-42ab-9a02-360417a71e74.png">

**Comment by mmvelasquez-mdsol** [comment]
I tried them all (re-starting the app after selecting each), but didn't help. I still need to rely on RAWTOHEX.
![image](https://user-images.githubusercontent.com/22908579/203993597-bafdadc0-d300-46f6-b64d-618f43f17d65.png)

**Comment by huyphams** [comment]
Fixed in this build https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
TablePlus now shows raw as hex.
