### ISSUE TITLE
When first opening SQL query window, I have to manually drag down to view query

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#26]
This slows down SQL query viewing, see below video animation.  Perhaps add option so that this text area will auto-expand to 10-15 lines, to give me an idea of the query I am running.  Also will make query more visible for new users.

![2017-07-28 23_05_58](https://user-images.githubusercontent.com/7946786/28742613-699f7d74-73e9-11e7-9ed9-e9c6651f9d37.gif)

OSX info:
<img width="242" alt="screen shot 2017-07-28 at 11 01 53 pm" src="https://user-images.githubusercontent.com/7946786/28742590-caedd856-73e8-11e7-971c-cec69b7a01e1.png">

**Comment by huyphams** [comment]
This is strange behavior because SQL Query alway expanded by default, could you please give me some extra info about the OS X version?

**Comment by MrGundBear** [comment]
updated comment.

**Comment by huyphams** [comment]
Hi @brian-crane could you check if the release fixed this issue.

**Comment by brian-crane** [comment]
@huyphams It actually is still occurring in the same way as originally described, even in Build 56.  It is only a small convenience though.

**Comment by huyphams** [comment]
@brian-crane sure but I need to fix it. UX is very important. I will borrow some MacBook EL Capitan and try to reproduce this issue.

**Comment by brian-crane** [comment]
@huyphams I can confirm this issue is resolved in Release 57.

**Comment by huyphams** [comment]
Thank you @brian-crane, enjoy coding 😁
