### ISSUE TITLE
Using TAB & SHIFT+TAB in tables

### ISSUE THREAD

**Issue by stsepelin** [TablePlus/TablePlus#260]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
88
3. The steps to reproduce this issue:
While editing columns in row by double click on column I can switch between columns in this row using TAB & SHIFT + TAB.
![untitled-1](https://user-images.githubusercontent.com/8102174/36253260-acebfe40-124f-11e8-807a-dce0fd20e875.png)
But if I insert some data in column and press TAB it focusing on "search" input instead of second column.
![untitled-2](https://user-images.githubusercontent.com/8102174/36253271-b2026766-124f-11e8-8e25-3d04fc0a3a0d.png)

**Comment by huyphams** [comment]
I see, thanks for the feedback 😄

**Comment by huyphams** [comment]
I figured out this bug, it will be fixed in next update 👍
