### ISSUE TITLE
Weird menu background on MacOS

### ISSUE THREAD

**Issue by ginkcode** [TablePlus/TablePlus#2604]
My Mac is in Light mode but the menu and spotlight was set to Dark mode

When open TablePlus the menu background turns to something pretty weird.
Never seen this in any other applications:

<img width="729" alt="Screen Shot 2022-02-09 at 3 18 47 PM" src="https://user-images.githubusercontent.com/9301098/153154358-92546ade-ffb1-4482-905c-aa66e984396e.png">

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 402

**Comment by huyphams** [comment]
Thanks for letting me know, please check the duplicate issue below
 https://github.com/TablePlus/TablePlus/issues/2556
