### ISSUE TITLE
Random database used for update statements from a select

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [TablePlus/TablePlus#2605]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.0.22

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 4.2.0 (383)

3. The steps to reproduce this issue: Write a select that specifies the database.  Edit the rows. Submit the changes.  Watch TablePlus randomly select a database to write to.

Noted: If the bug is related to data, please attach an example SQL data.

![Screen Shot 2022-02-09 at 10 27 46 AM](https://user-images.githubusercontent.com/348801/153235209-2d9c6074-0a2f-4f4d-b042-9b0e216932a3.png)

* See the left pane, I have no database selected.
* The select has `nwy3m7y9` specified as the database.
* The update statements has `8z682964` specified as the database.

**Comment by huyphams** [comment]
Thanks @ChrisThompsonTLDR we must select the database (on the left sidebar) before doing any updates. I think TablePlus should not allow users to update any records if the user didn't select any databases.

**Comment by huyphams** [comment]
I'm sorry for the issue, I'm not asking you to look into the list database. I think that it would be better if we fix the TablePlus in the next update and disable the update inline feature when the user forgot the select a database.

However, I found a better solution where I can detect the table in query, if you have a chance, please download this hot patch and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
