### ISSUE TITLE
Improve table comment visibility

### ISSUE THREAD

**Issue by Jiia** [TablePlus/TablePlus#2607]
This is a minor nitpick, but the table comments are quite well hidden and their visibility could be improved upon.

To be able to view a table's comment you need to:
1. Open the table
2. Click the structure button
3. Click the info button
4. Scroll to the bottom of the info modal

I think it would improve the user experience quite a lot if the last two steps could be cut out by displaying the table comment on the structure view.

**Comment by huyphams** [comment]
I just wanna make sure that you are ware of this feature.
<img width="1651" alt="overview" src="https://user-images.githubusercontent.com/3654622/156182045-f89fd5b0-f7a4-4191-8118-8ca2acb46fa8.png">

**Comment by Jiia** [comment]
Actually, no. Thanks for the tip!
