### ISSUE TITLE
When renaming a table during creation, the new name isn't updating everywhere

### ISSUE THREAD

**Issue by leeola** [TablePlus/TablePlus#261]
- Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7.17

- Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 88

- The steps to reproduce this issue:

1. Create a table, but don't yet commit
2. Open the table view and rename the table by using the field to the left of the Primary key field. Type in a new name, hit enter.
3.  The new name is not visible in the tab. The new name is also not visible in any foreign keys you're trying to create.

This issue is mostly annoying when trying to create multiple tables before committing, and assigning foreign key relationships between each table. The foreign keys all say things like "untitled_table_33", so it's difficult to know what table it is even referring to.

**Comment by huyphams** [comment]
Hey @leeola thanks for the feedback. I will fix this issue on update 89.
