### ISSUE TITLE
Apply All filters not working

### ISSUE THREAD

**Issue by lcsqlpete** [TablePlus/TablePlus#2610]
MySQL 5.4

TablePlus Version 4.5.2 (402)

To reproduce:

1. Clicked view vSessionActivity to display the data.
2. Set a filter on SCRIPT_NAME Contains facility_curtains 
3. Set a filter on QUERY_STRING contains 256
4. Click Apply All

Actual result: All rows are displayed.
Expected result: Only rows that match the filter criteria are displayed.

See attached screenshot that illustrates the problem.

Note that applying each filter individually produces the correct data.

![Screen Shot 2022-02-16 at 12 22 59 PM](https://user-images.githubusercontent.com/8495380/154351624-c1daa0c6-368a-4ae9-90d8-9d65b4d48933.png)

**Comment by huyphams** [comment]
Hi @lcsqlpete you must stick the check box button on the left of the filter before clicking Apply All.

"Apply All" => Apply all the checked filter.

**Comment by lcsqlpete** [comment]
THanks for the reply.

I am now running into a different issue.  I have an existing filter on a
column in a view.  When I click the column name dropdown the only options
displayed are Any column, content, created at, and the name of the current
column.  If I click the dropdown that normally includes all the possible
comparison operators, it shows only ">", "<", and "contains", "contains is
the currently-se;ected option.Normally, the dropdown includes a list of all
columns so this prevents me from changing the filter to use a
different column.

IN an attempt to work around this, I clicked the "-" button for the one
existing filter to remove it.  The filter details were removed by if I then
click the Filters button, it is displayed again.

I have attached screenshots to illustrate this.

**Comment by lcsqlpete** [comment]
Any progress on this?

**Comment by huyphams** [comment]
Hi @lcsqlpete  please read my previous comment

**Comment by lcsqlpete** [comment]
On Mar 3, I reported a different problem which I have not had an answer to.

Pete
lcSQL Software
