### ISSUE TITLE
How do I open different tables without opening new tabs?

### ISSUE THREAD

**Issue by Robio** [TablePlus/TablePlus#2613]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):  Don't know

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.5.2 (402)

3. The steps to reproduce this issue: I can't figure out how TablePlus decides whether to open a table in a new tab or the current tab, and I can't seem to find a setting to have the app default to opening in the current tab, which is my preference. Can you provide some insight?

**Comment by huyphams** [comment]
TablePlus will keep the tab (will not replace it) if you:

1. Modified the tab content or filter.
2. Double click the item on the left sidebar.
