### ISSUE TITLE
Restoring a dump created with percona mysqldump on MariaDB fails

### ISSUE THREAD

**Issue by boutetnico** [TablePlus/TablePlus#2615]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.6.5
Percona server 5.7.36-39

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.6.0 (406)

3. The steps to reproduce this issue:

- Download and unzip the example [dump.sql.zip](https://github.com/TablePlus/TablePlus/files/8160791/dump.sql.zip)
- Click File > Import > From SQL dump
- Select attached `dump.sql`
- Click import
- Notice the following error
![tableplus-error](https://user-images.githubusercontent.com/973739/156151680-c0e2d7cc-2629-4a41-acef-82ba49a834a3.png)

The same import works in Sequel Ace or directly using mysql cli.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @boutetnico please try restoring the dump file with the restore feature (instead of import).
<img width="309" alt="Screen Shot 2022-03-01 at 7 59 28 PM" src="https://user-images.githubusercontent.com/3654622/156173245-06ef399f-a710-47af-a7c5-5f59f933ee67.png">

**Comment by boutetnico** [comment]
Thank you @huyphams it works!
imo both options should be merged into a single action, 2 of our team got confused by this.
