### ISSUE TITLE
TablePlus not respecting Capital Letters

### ISSUE THREAD

**Issue by S-UP** [TablePlus/TablePlus#2618]
Version 4.5.2 (402)

BUG: When running a query with an SQL statement like [...  snake_case AS PascalCase ] then TablePlus shows in the output table "pascalcase", i.e. all in lower case. This is highly annoying as it affects readability.

**Comment by huyphams** [comment]
Hi @S-UP I'm unable to reproduce the issue, also I'm not sure this bug is related to TablePlus or the default database behavior. Please update the step to reproduce the issue.
Thank you in advance.

**Comment by S-UP** [comment]
@huyphams Is it possible to provide a test dataset? I am connecting to our corporate database (postgres). Thus, I cannot share details here. But it is a standard SQL statement.

**Comment by huyphams** [comment]
Could you tell me the step to reproduce the issue, for example:

1. Connect to any PostgreSQL database. (and version pg 12.2 for example).
2. Run a query Select 1;
3. Expected: result should show 1
4. Actually: result show 2

etc... you don't have to put your real data here.

**Comment by S-UP** [comment]
Sure.

1. PostgresSQL 11.12: TLSv1.2: Amazon AWS
2. SELECT snake_case AS PascalCase FROM example_db
3. Click "Run Current"
4. Results window shows all variables, i.e. above PascalCase, in lower-case. That is, pascalcase

**Comment by huyphams** [comment]
Thanks for the details. However, I can confirm this is not a TablePlus issue. It is the PostgreSQL behavior.
If you want to keep the Camel case, you have to put a quote in it.

For example: 

```
SELECT 'a' as "Something"; 
```
it will keep the column Something but 

```
SELECT 'a' as Something;
```

Same behavior with psql client. Client has nothing todo with the result format, it was returned by the server.
<img width="263" alt="Screen Shot 2022-03-04 at 10 10 54 PM" src="https://user-images.githubusercontent.com/3654622/156788823-1b73e046-7540-4ad0-9049-be3ea1ef709c.png">

**Comment by S-UP** [comment]
Thanks a lot! This was the first time I worked with TablePlus AND Postgres, at the same time. My previous databases always respected the format as outlined above.
