### ISSUE TITLE
Varchar is not available in the data_type dropdown

### ISSUE THREAD

**Issue by leeola** [TablePlus/TablePlus#262]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 88

3. The steps to reproduce this issue:

- Create a new table
- Create a new column on the new table
- Click the dropdown list, VARCHAR is not available.

**Comment by huyphams** [comment]
Thanks, I just added Varchar in new build 89, because varchar is a data type with specific data length.

The current UI doesn't allow user sets data length. Because of this limit, I will change the UI in next update to support this case.
