### ISSUE TITLE
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread

### ISSUE THREAD

**Issue by yunshuaipeng** [TablePlus/TablePlus#2621]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Server version: 5.7.23 MySQL Community Server (GPL)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.6.0 (406)

macos: Big Sur 11.6.1

3. The steps to reproduce this issue:
when using then click "Close Tabs to the Right" (sometimes)

Noted: If the bug is related to data, please attach an example SQL data.

Process:               TablePlus [67758]
Path:                  /Applications/TablePlus.app/Contents/MacOS/TablePlus
Identifier:            com.tinyapp.TablePlus
Version:               4.6.0 (406)
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           TablePlus [67758]
User ID:               501

Date/Time:             2022-03-10 17:05:40.434 +0800
OS Version:            macOS 11.6.1 (20G224)
Report Version:        12
Anonymous UUID:        4162A093-69E0-55F7-E0D2-8EDEF9CD95AC

Sleep/Wake UUID:       E014901C-09F0-4077-9344-E06AEE46E015

Time Awake Since Boot: 420000 seconds
Time Since Wake:       280000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000071434fc2b6b0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [67758]

VM Regions Near 0x71434fc2b6b0:
--> MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  reserved VM address space (unallocated)
    

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib                 0x00000001a252b190 objc_retain + 16
1   com.tinyapp.TablePlus           0x0000000104376dc4 0x104330000 + 290244
2   com.tinyapp.TablePlus           0x0000000104374bcc 0x104330000 + 281548
3   com.apple.AppKit                0x00000001a50ea464 _NSViewDrawRect + 148
4   com.apple.AppKit                0x00000001a581c548 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1312
5   com.apple.AppKit                0x00000001a50e9be4 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 676
6   com.apple.QuartzCore            0x00000001a8a50ed8 CABackingStoreUpdate_ + 196
7   com.apple.QuartzCore            0x00000001a8aadd0c invocation function for block in CA::Layer::display_() + 64
8   com.apple.QuartzCore            0x00000001a8a5028c -[CALayer _display] + 1760
9   com.apple.AppKit                0x00000001a50e983c -[_NSBackingLayer display] + 372
10  com.apple.AppKit                0x00000001a505b1a8 -[_NSViewBackingLayer display] + 644
11  com.apple.QuartzCore            0x00000001a8a4f384 CA::Layer::display_if_needed(CA::Transaction*) + 780
12  com.apple.QuartzCore            0x00000001a8b7b3bc CA::Context::commit_transaction(CA::Transaction*, double, double*) + 512
13  com.apple.QuartzCore            0x00000001a8a31310 CA::Transaction::commit() + 684
14  com.apple.AppKit                0x00000001a50fe750 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 304
15  com.apple.AppKit                0x00000001a5853cd4 ___NSRunLoopObserverCreateWithHandler_block_invoke + 64
16  com.apple.CoreFoundation        0x00000001a2790888 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
17  com.apple.CoreFoundation        0x00000001a27906d4 __CFRunLoopDoObservers + 572
18  com.apple.CoreFoundation        0x00000001a278fc1c __CFRunLoopRun + 764
19  com.apple.CoreFoundation        0x00000001a278f1a8 CFRunLoopRunSpecific + 600
20  com.apple.HIToolbox             0x00000001aa6b5280 RunCurrentEventLoopInMode + 292
21  com.apple.HIToolbox             0x00000001aa6b4f0c ReceiveNextEventCommon + 320
22  com.apple.HIToolbox             0x00000001aa6b4db4 _BlockUntilNextEventMatchingListInModeWithFilter + 72
23  com.apple.AppKit                0x00000001a4f81660 _DPSNextEvent + 836
24  com.apple.AppKit                0x00000001a4f80000 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1292
25  com.apple.AppKit                0x00000001a4f71e4c -[NSApplication run] + 596
26  com.apple.AppKit                0x00000001a4f43878 NSApplicationMain + 1064
27  com.tinyapp.TablePlus           0x0000000104341308 0x104330000 + 70408
28  libdyld.dylib                   0x00000001a26b1430 start + 4

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib          0x00000001a2658dd4 mach_msg_trap + 8
1   libsystem_kernel.dylib          0x00000001a2659184 mach_msg + 76
2   com.apple.CoreFoundation        0x00000001a2791910 __CFRunLoopServiceMachPort + 372
3   com.apple.CoreFoundation        0x00000001a278fddc __CFRunLoopRun + 1212
4   com.apple.CoreFoundation        0x00000001a278f1a8 CFRunLoopRunSpecific + 600
5   com.apple.AppKit                0x00000001a5100334 _NSEventThread + 196
6   libsystem_pthread.dylib         0x00000001a2693878 _pthread_start + 320
7   libsystem_pthread.dylib         0x00000001a268e5e0 thread_start + 8

Thread 2:
0   libsystem_kernel.dylib          0x00000001a2658dd4 mach_msg_trap + 8
1   libsystem_kernel.dylib          0x00000001a2659184 mach_msg + 76
2   com.tinyapp.TablePlus           0x00000001048049dc 0x104330000 + 5065180
3   libsystem_pthread.dylib         0x00000001a2693878 _pthread_start + 320
4   libsystem_pthread.dylib         0x00000001a268e5e0 thread_start + 8

Thread 3:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x00000001a2658dd4 mach_msg_trap + 8
1   libsystem_kernel.dylib          0x00000001a2659184 mach_msg + 76
2   com.apple.CoreFoundation        0x00000001a2791910 __CFRunLoopServiceMachPort + 372
3   com.apple.CoreFoundation        0x00000001a278fddc __CFRunLoopRun + 1212
4   com.apple.CoreFoundation        0x00000001a278f1a8 CFRunLoopRunSpecific + 600
5   com.apple.CFNetwork             0x00000001a6c870f4 0x1a6a3c000 + 2404596
6   com.apple.Foundation            0x00000001a3532c80 __NSThread__start__ + 864
7   libsystem_pthread.dylib         0x00000001a2693878 _pthread_start + 320
8   libsystem_pthread.dylib         0x00000001a268e5e0 thread_start + 8

Thread 4:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib         0x00000001a268e5cc start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600001cab690   x1: 0x0000000136e68870   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000001   x6: 0x0005600000164c80   x7: 0x00000001a8bffd24
    x8: 0x0000f1434fc2b690   x9: 0x000071434fc2b690  x10: 0x0000000000000010  x11: 0x0000000136e68880
   x12: 0x0000000000000011  x13: 0x0000000125827fc0  x14: 0x0000000000000032  x15: 0x00000001049be7f0
   x16: 0x00000001a252b180  x17: 0x00000001a34f0ce0  x18: 0x000000010ce2340c  x19: 0x0000000000000000
   x20: 0x0000600001cab690  x21: 0x0000000161fe0960  x22: 0x00000001faf7ae5a  x23: 0x00000000000002b8
   x24: 0x000000021127ead8  x25: 0x0000000000000090  x26: 0x0000000000000000  x27: 0x00000001faee2c43
   x28: 0x0000000000000001   fp: 0x000000016bacc220   lr: 0x0000000104376dc4
    sp: 0x000000016bacc1b0   pc: 0x00000001a252b190 cpsr: 0x20000000
   far: 0x000071434fc2b6b0  esr: 0x92000005

Binary Images:
       0x104330000 -        0x104907fff +com.tinyapp.TablePlus (4.6.0 - 406) <DB7C14EE-5CF5-3F5F-B68A-3C4587B39FA2> /Applications/TablePlus.app/Contents/MacOS/TablePlus
       0x104af0000 -        0x104b37fff +org.sparkle-project.Sparkle (1.27.1 - 1.106) <E958640C-06CC-3689-BA1C-B3A664D2DF8D> /Applications/TablePlus.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       ... and more

**Comment by Salmankhan033** [comment]
> 1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
>    Server version: 5.7.23 MySQL Community Server (GPL)
> 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
>    Version 4.6.0 (406)
> 
> macos: Big Sur 11.6.1
> 
> 3. The steps to reproduce this issue:
>    when using then click "Close Tabs to the Right" (sometimes)
> 
> Noted: If the bug is related to data, please attach an example SQL data.
> 
> Process: TablePlus [67758] Path: /Applications/TablePlus.app/Contents/MacOS/TablePlus Identifier: com.tinyapp.TablePlus Version: 4.6.0 (406) Code Type: ARM-64 (Native) Parent Process: ??? [1] Responsible: TablePlus [67758] User ID: 501
> 
> Date/Time: 2022-03-10 17:05:40.434 +0800 OS Version: macOS 11.6.1 (20G224) Report Version: 12 Anonymous UUID: 4162A093-69E0-55F7-E0D2-8EDEF9CD95AC
> 
> Sleep/Wake UUID: E014901C-09F0-4077-9344-E06AEE46E015
> 
> Time Awake Since Boot: 420000 seconds Time Since Wake: 280000 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread: 0 Dispatch queue: com.apple.main-thread
> 
> Exception Type: EXC_BAD_ACCESS (SIGSEGV) Exception Codes: KERN_INVALID_ADDRESS at 0x000071434fc2b6b0 Exception Note: EXC_CORPSE_NOTIFY
> 
> Termination Signal: Segmentation fault: 11 Termination Reason: Namespace SIGNAL, Code 0xb Terminating Process: exc handler [67758]
> 
> VM Regions Near 0x71434fc2b6b0: --> MALLOC_NANO (reserved) 600018000000-600020000000 [128.0M] rw-/rwx SM=NUL reserved VM address space (unallocated)
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread 0 libobjc.A.dylib 0x00000001a252b190 objc_retain + 16 1 com.tinyapp.TablePlus 0x0000000104376dc4 0x104330000 + 290244 2 com.tinyapp.TablePlus 0x0000000104374bcc 0x104330000 + 281548 3 com.apple.AppKit 0x00000001a50ea464 _NSViewDrawRect + 148 4 com.apple.AppKit 0x00000001a581c548 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1312 5 com.apple.AppKit 0x00000001a50e9be4 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 676 6 com.apple.QuartzCore 0x00000001a8a50ed8 CABackingStoreUpdate_ + 196 7 com.apple.QuartzCore 0x00000001a8aadd0c invocation function for block in CA::Layer::display_() + 64 8 com.apple.QuartzCore 0x00000001a8a5028c -[CALayer _display] + 1760 9 com.apple.AppKit 0x00000001a50e983c -[_NSBackingLayer display] + 372 10 com.apple.AppKit 0x00000001a505b1a8 -[_NSViewBackingLayer display] + 644 11 com.apple.QuartzCore 0x00000001a8a4f384 CA::Layer::display_if_needed(CA::Transaction*) + 780 12 com.apple.QuartzCore 0x00000001a8b7b3bc CA::Context::commit_transaction(CA::Transaction*, double, double*) + 512 13 com.apple.QuartzCore 0x00000001a8a31310 CA::Transaction::commit() + 684 14 com.apple.AppKit 0x00000001a50fe750 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 304 15 com.apple.AppKit 0x00000001a5853cd4 ___NSRunLoopObserverCreateWithHandler_block_invoke + 64 16 com.apple.CoreFoundation 0x00000001a2790888 **CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 36 17 com.apple.CoreFoundation 0x00000001a27906d4 __CFRunLoopDoObservers + 572 18 com.apple.CoreFoundation 0x00000001a278fc1c __CFRunLoopRun + 764 19 com.apple.CoreFoundation 0x00000001a278f1a8 CFRunLoopRunSpecific + 600 20 com.apple.HIToolbox 0x00000001aa6b5280 RunCurrentEventLoopInMode + 292 21 com.apple.HIToolbox 0x00000001aa6b4f0c ReceiveNextEventCommon + 320 22 com.apple.HIToolbox 0x00000001aa6b4db4 _BlockUntilNextEventMatchingListInModeWithFilter + 72 23 com.apple.AppKit 0x00000001a4f81660 _DPSNextEvent + 836 24 com.apple.AppKit 0x00000001a4f80000 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1292 25 com.apple.AppKit 0x00000001a4f71e4c -[NSApplication run] + 596 26 com.apple.AppKit 0x00000001a4f43878 NSApplicationMain + 1064 27 com.tinyapp.TablePlus 0x0000000104341308 0x104330000 + 70408 28 libdyld.dylib 0x00000001a26b1430 start + 4
> 
> Thread 1:: com.apple.NSEventThread 0 libsystem_kernel.dylib 0x00000001a2658dd4 mach_msg_trap + 8 1 libsystem_kernel.dylib 0x00000001a2659184 mach_msg + 76 2 com.apple.CoreFoundation 0x00000001a2791910 __CFRunLoopServiceMachPort + 372 3 com.apple.CoreFoundation 0x00000001a278fddc __CFRunLoopRun + 1212 4 com.apple.CoreFoundation 0x00000001a278f1a8 CFRunLoopRunSpecific + 600 5 com.apple.AppKit 0x00000001a5100334 _NSEventThread + 196 6 libsystem_pthread.dylib 0x00000001a2693878 _pthread_start + 320 7 libsystem_pthread.dylib 0x00000001a268e5e0 thread_start + 8
> 
> Thread 2: 0 libsystem_kernel.dylib 0x00000001a2658dd4 mach_msg_trap + 8 1 libsystem_kernel.dylib 0x00000001a2659184 mach_msg + 76 2 com.tinyapp.TablePlus 0x00000001048049dc 0x104330000 + 5065180 3 libsystem_pthread.dylib 0x00000001a2693878 _pthread_start + 320 4 libsystem_pthread.dylib 0x00000001a268e5e0 thread_start + 8
> 
> Thread 3:: com.apple.NSURLConnectionLoader 0 libsystem_kernel.dylib 0x00000001a2658dd4 mach_msg_trap + 8 1 libsystem_kernel.dylib 0x00000001a2659184 mach_msg + 76 2 com.apple.CoreFoundation 0x00000001a2791910 __CFRunLoopServiceMachPort + 372 3 com.apple.CoreFoundation 0x00000001a278fddc __CFRunLoopRun + 1212 4 com.apple.CoreFoundation 0x00000001a278f1a8 CFRunLoopRunSpecific + 600 5 com.apple.CFNetwork 0x00000001a6c870f4 0x1a6a3c000 + 2404596 6 com.apple.Foundation 0x00000001a3532c80 **NSThread__start** + 864 7 libsystem_pthread.dylib 0x00000001a2693878 _pthread_start + 320 8 libsystem_pthread.dylib 0x00000001a268e5e0 thread_start + 8
> 
> Thread 4: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 5: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 6: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 7: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 8: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 9: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 10: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 11: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 12: 0 libsystem_pthread.dylib 0x00000001a268e5cc start_wqthread + 0
> 
> Thread 0 crashed with ARM Thread State (64-bit): x0: 0x0000600001cab690 x1: 0x0000000136e68870 x2: 0x0000000000000000 x3: 0x0000000000000000 x4: 0x0000000000000000 x5: 0x0000000000000001 x6: 0x0005600000164c80 x7: 0x00000001a8bffd24 x8: 0x0000f1434fc2b690 x9: 0x000071434fc2b690 x10: 0x0000000000000010 x11: 0x0000000136e68880 x12: 0x0000000000000011 x13: 0x0000000125827fc0 x14: 0x0000000000000032 x15: 0x00000001049be7f0 x16: 0x00000001a252b180 x17: 0x00000001a34f0ce0 x18: 0x000000010ce2340c x19: 0x0000000000000000 x20: 0x0000600001cab690 x21: 0x0000000161fe0960 x22: 0x00000001faf7ae5a x23: 0x00000000000002b8 x24: 0x000000021127ead8 x25: 0x0000000000000090 x26: 0x0000000000000000 x27: 0x00000001faee2c43 x28: 0x0000000000000001 fp: 0x000000016bacc220 lr: 0x0000000104376dc4 sp: 0x000000016bacc1b0 pc: 0x00000001a252b190 cpsr: 0x20000000 far: 0x000071434fc2b6b0 esr: 0x92000005
> 
> Binary Images: 0x104330000 - 0x104907fff +com.tinyapp.TablePlus (4.6.0 - 406) /Applications/TablePlus.app/Contents/MacOS/TablePlus 0x104af0000 - 0x104b37fff +org.sparkle-project.Sparkle (1.27.1 - 1.106) /Applications/TablePlus.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle ... and more

Have you fixed the problem?

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue. Thanks

**Comment by yunshuaipeng** [comment]
The new version works fine. I will colse this issue.
