### ISSUE TITLE
Redis AWS ElastiCache not working

### ISSUE THREAD

**Issue by ReckeDJ** [TablePlus/TablePlus#2622]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redis

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
406

3. The steps to reproduce this issue:
Connect to AWS ElastiCache via SSH tunnelling with SSL_VERIFY_NONE SSL setting.
Connection is successful but there are no databases listed.
Redis version is 6.2.5

<img width="1194" alt="tableplus-elasticache" src="https://user-images.githubusercontent.com/2484433/157683509-ece27408-cbac-46da-8def-11715db3aa9a.png">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ReckeDJ** [comment]
Hi @huyphams,

Yes that confirms my thoughts because there is no Redis version listed in the middle top-bar.
I just tried to execute the `INFO` command; see the attached screenshot. Is there something I can do about that?

<img width="1194" alt="tableplus-elasticache-noauth" src="https://user-images.githubusercontent.com/2484433/157700915-13976dd5-9f26-4eb1-9d6e-053653a9a827.png">

**Comment by huyphams** [comment]
I think you must add the authentication info (The password field), you can find it in the Amazon Redis Dasboard.

**Comment by ReckeDJ** [comment]
@huyphams Thanks! Guess I was using the wrong password there. All fixed now! 👍
