### ISSUE TITLE
Filter's "Table's columns" dropdown has incorrect items

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#2624]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): postgresql 14.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 4.6.0 (406)

3. The steps to reproduce this issue:

- add some filters to a table view
- after adding a new filter using the `+` on the previous line, the dropdown with "Table's columns" is incorrect.  I am attaching 2 screenshots.  filter no 2 dropdown and filter no 3 dropdown.

<img width="217" alt="Screenshot 2022-03-11 at 15 01 05" src="https://user-images.githubusercontent.com/3632883/157882222-b67e8147-1cda-4785-9caf-f54346c7ea14.png">

<img width="163" alt="Screenshot 2022-03-11 at 15 01 15" src="https://user-images.githubusercontent.com/3632883/157882253-ddc5a123-fac0-4487-be7a-04b7c8936baf.png">

**Comment by huyphams** [comment]
it could happen when the app is loading rows. It will refresh all the columns in the list. Could you make a screencast for me, please?

**Comment by huyphams** [comment]
Hi @minusf did you try to build above?

**Comment by minusf** [comment]
hello.  this issue has still not been fixed.  i still get incorrect columns in the dropdown. i need to close/reopen the filter pane for the dropdown to update correctly.

**Comment by minusf** [comment]
https://user-images.githubusercontent.com/3632883/190987606-9d661cf7-4eeb-4f70-a84c-a6845918a380.mov

**Comment by huyphams** [comment]
Hi, @minusf do you have the step to reproduce the issue? Does it finish loading or it is still fetching rows?

**Comment by minusf** [comment]
unfortunately i dont have specific steps... i just keep the app open and come and go between tables. the size of the table is not a factor here, all rows are fetched. opening and closing the filter pane also does not fix it all the time. a cmd-r does all the time.

**Comment by minusf** [comment]
also would it be possible to sort the dropdown alphabetically?  on tables with many columns the column order is not useful and it makes me look through every item in the list...
