### ISSUE TITLE
What does the query time benchmark represent?

### ISSUE THREAD

**Issue by JulienDemarque** [TablePlus/TablePlus#2627]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 13.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 406

4. The steps to reproduce this issue:

Any SQL query gives the time of the query in ms. My question is, does that include the network latency if my db is on the other side of the work? Is is possible to get a detailed benchmark?

**Comment by huyphams** [comment]
Hi @JulienDemarque it is not possible to get that info (queries time) because it is not a part of the result (from database server).
You can use the explain query for the details.

**Comment by JulienDemarque** [comment]
@huyphams Ok so just to be clear, the network latency is included in the time shown in tableplus, it is just not possible to know how much was the latency?

**Comment by huyphams** [comment]
Yes, the network latency is included
