### ISSUE TITLE
ENUM update issue (related to 553)

### ISSUE THREAD

**Issue by okomarov** [TablePlus/TablePlus#2630]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **PostgreSQL 12.9**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **411**

3. The steps to reproduce this issue:

When I apply my migrations with an ORM or I restore the database which happens to e.g. change some ENUMs, then TablePlus does not reflect the changes even if I hit the **refresh** icon at the top right. 

The ENUM field loses the ability to select options in the UI and behaves like a text field.

I need to quit and re-open TablePlus.

**Comment by dmythro** [comment]
+1 on this. Pretty annoying as for some time I thought my migrations didn't work :)

**Comment by huyphams** [comment]
Fixed: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
Command + R now will reload the enum as well (previously need command + shift + R)
