### ISSUE TITLE
Cant open redshift url from terminal (MacOs)

### ISSUE THREAD

**Issue by josselin-mahe-doctolib** [TablePlus/TablePlus#2631]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Do not know how to get this information and not sure this is relevant.

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
406

4. The steps to reproduce this issue:
open a bash terminal and run :
open redshift://<login>:<password>@<host>:<port>/<db>&...

Hello!

I am trying to open a link to a redshift database from a bash script (or a terminal) from a mac (Monterey v12.2.1).
I can get tableplus to open on link matching the pattern postgresql://... but I can't find the key for redshift. I always seem to get : 
`No application knows how to open URL`
I have not found any official documentation on the feature and I am mainly resorting to [this blog post](https://joshbutts.com/posts/tableplus-shortcuts/) as a reference.

For information, I have unsuccessfully tried the following keys: 

1. redshift
2. awsredshift
3. aws-redshift
4. aws_redshift
5. aws%20redshift
6. amazonredshift
7. amazon-redshift
8. amazon_redshift
9. amazon%20redshift
10. redshiftaws
11. redshift-aws
12. redshift%20aws
14. redshiftamazon
15. redshift-amazon
16. redshift_amazon
17. redshift%20amazon

I am at the end of the rope here.

What is the correct key to open a redshift connection please?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @josselin-mahe-doctolib TablePlus does not support redshift url schema at the moment, we just added it in this patch, if you have a chance, please download this build: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

Tip: if you right-click on the connection > Copy URL you will see the URL syntax, and then you can open it in the terminal.
For example:

open -a TablePlus "database_url"


`-a TablePlus`  will choose TablePlus as the handler (if there are more than one apps that registers the same URL).

**Comment by josselin-mahe-doctolib** [comment]
Thanks a lot for the answer. I will try but not sure it will be easy to ask all the team to install the plugin.
I also found in a last attempt that we could use the postgresql:// for redshift issue without much trouble. Don't know if this will have weird consequences later on.
=> Looking forward to the patch being integrated with the main product :)
