### ISSUE TITLE
The server is unkown

### ISSUE THREAD

**Issue by gempir** [TablePlus/TablePlus#2633]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
mysql default

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
410

**3. The steps to reproduce this issue:**
- setup connection via ssh
- connect once to the server and accept the "The Server is unknown" warning and continue
- completely close TablePlus
- connect to the same server again

--> the warning will appear again

TablePlus keeps prompting me that the server is unknown. Can I somehow give TablePlus my known_hosts file? Why doesn't it just read it from my home directory. 
Or are permissions wrong on some file and that's why it can't update it's internal known_hosts? It's getting annoying to accept the prompt each time.

![image](https://user-images.githubusercontent.com/9765622/159429437-80eefa66-3db2-49d1-85de-8612a7643321.png)

**Comment by huyphams** [comment]
Hi @gempir please remove the duplicate entry in the known_hosts, or if it is possible, you can delete that file to reset it. Please let me know if you are still seeing the issue.

**Comment by gempir** [comment]
That indeed fixed it! Thank you! 

A Bit confusing because ssh can handle that just fine and never gave me any prompt when doing `ssh server`

**Comment by brunoamaral** [comment]
I am still seeing this issue on Version 4.8.8 (450), already tried to reset the file and remove duplicates.

**Comment by slaFFik** [comment]
@huyphams 
Same issue on Version 6.3.0 (584)

**Comment by huyphams** [comment]
Possibly that TablePlus doesn't have permission to write to know_hosts.
