### ISSUE TITLE
update all duplicate rows when you want to update someone row；

### ISSUE THREAD

**Issue by minesunny** [TablePlus/TablePlus#2638]
I found a bug。there some duplicate rows on their all fileds；when you want to update some one filed in some row；the result is this filed updated in all rows。it shouldn't update all row。This is I knew in MySQL。I suggest that you can use `limit 1` in update SQL to solve this bug。I found this method by capturing Navicat app。

**Comment by huyphams** [comment]
Hi @minesunny please do not remove our template issue question, I could not reproduce the issue.
