### ISSUE TITLE
Foreign keys from postgres schema are not shown

### ISSUE THREAD

**Issue by tonyxiao** [TablePlus/TablePlus#264]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 9.6.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
88

3. The steps to reproduce this issue:

Table creation statements

![image](https://user-images.githubusercontent.com/696842/36274652-4aff8b5a-123d-11e8-9e86-8e0e3faa35ed.png)

How Postico shows it

![image](https://user-images.githubusercontent.com/696842/36274676-5dd54bb6-123d-11e8-9025-01c933b37523.png)

How TablePlus shows it (with issue highlighted)

<img width="973" alt="cloudapp annotation 2018-02-15 at 10 45 56 png" src="https://user-images.githubusercontent.com/696842/36274692-6bd4be04-123d-11e8-9ad2-908e9c1b6da0.png">

**Comment by huyphams** [comment]
Hi @tonyxiao can you try this buidl: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
I just fixed the issue above.

**Comment by tonyxiao** [comment]
Yep seems to be fixed by your custom build. I'm assuming this will be released as part 89?

**Comment by tonyxiao** [comment]
Also I should probably file a separate issue for it, however these `varchar` labels don't make any sense to me.

<img width="329" alt="cloudapp annotation 2018-02-16 at 18 17 21 png" src="https://user-images.githubusercontent.com/696842/36337190-a5e70d1e-1345-11e8-9acc-9a4795416607.png">
