### ISSUE TITLE
Binary arrays in Postgres

### ISSUE THREAD

**Issue by mark-b-ab** [TablePlus/TablePlus#2640]
1. Which driver are you using and what version of it (Ex: PostgreSQL 10.0): PostgreSQL 13.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 411

Please add the ability to view `bytea` as hex values

This can be achieved by querying `field::varchar`

**Comment by mark-b-ab** [comment]
This is edit, but I need view

**Comment by mark-b-ab** [comment]
That would be great! Thanks a lot

**Comment by mark-b-ab** [comment]
With current approach I have to click on each value to find the one I am looking for

**Comment by huyphams** [comment]
Just out of curiosity, did you scan the hex by looking at it? why don't you use the filter?

**Comment by mark-b-ab** [comment]
Sometimes I need a human eye to find the data, I don't know the specific value, or have a subset of values that might work. I can write the query or use filters but it will take a couple of minutes rather than a couple of seconds with a list view
