### ISSUE TITLE
Feature: Copy selected columns from data view into export tool

### ISSUE THREAD

**Issue by omnilord** [TablePlus/TablePlus#2642]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):  Any, UI issue (MySQL, Postgres, MariaDB, etc.)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 410

3. The steps to reproduce this issue:

- Open any table
- Click the "Columns" button
- Add columns, review data, add/remove columns until the desired columns are set
<img width="422" alt="Screen Shot 2022-03-07 at 7 12 09 PM" src="https://user-images.githubusercontent.com/2309469/160898141-bc9365cc-fe48-4698-b57f-7d880530cdcb.png">

- Right-click anywhere in the data
- Click "Export Current Page" from the context menu
<img width="278" alt="Screen Shot 2022-03-07 at 7 12 21 PM" src="https://user-images.githubusercontent.com/2309469/160898213-2fad1fea-eaa5-4106-90f0-76b861dac68f.png">

- No columns are populated in the export view; have to reselect an unknown set of columns and you cannot toggle back and forth to reference which columns were set; you have to memorize _all_ of them before attempting export.
<img width="335" alt="Screen Shot 2022-03-07 at 7 12 32 PM" src="https://user-images.githubusercontent.com/2309469/160898259-a3e11c04-d8de-4ed4-93a1-39f6f8a69ad2.png">

**Comment by huyphams** [comment]
Thanks, this feature will be included in the next update!
