### ISSUE TITLE
Invalid host private key using 1password

### ISSUE THREAD

**Issue by innocenzi** [TablePlus/TablePlus#2645]
I am trying to connect to a server using my `~/.ssh/config` file, and an `Ed25519` key managed by 1password. 

When trying to connect, I get an error dialog with the following message: `Invalid host private key`.

![image](https://user-images.githubusercontent.com/16060559/161101444-0ed585af-7975-4b10-92e2-5bc4e971602b.png)

When trying to debug the issue by enabling the SSH debug log in `Help` and launching TablePlus via `/Applications/TablePlus.app/Contents/MacOS/TablePlus`, I can connect normally to my database. 

I'm not sure what changes between the two modes, but the TL;DR is that normal TablePlus doesn't work, and table plus launched via command line works as expected. I think the issue might come from the fact that my key is managed by 1password's SSL agent.

![CleanShot 2022-03-31 at 18 14 38](https://user-images.githubusercontent.com/16060559/161101924-643c05e4-cb17-42bf-acc3-400173317031.png)

**Comment by datenbrille** [comment]
I have a similar issue with a setup of AWS+SSM via a bastion host. Starting TP from the cmd solves the issue. It there a way to get more details in the error message/dialog?

**Comment by innocenzi** [comment]
For anyone having my issue, a workaround is to download the private key and specify it in the TablePlus connection. 

![image](https://user-images.githubusercontent.com/16060559/162439630-616619d2-f7db-4da5-9a59-ab49437e31d5.png)

**Comment by tdimeco** [comment]
Hi,

I have the same issue with 1Password, with a slightly different error message.

Error message:
<img width="416" alt="TablePlus error" src="https://user-images.githubusercontent.com/3112087/174743119-bd60d35b-1868-4b9e-961c-e13c45501aef.png">
Config:
<img width="612" alt="TablePlus config" src="https://user-images.githubusercontent.com/3112087/174743213-3dc8f85e-beca-4536-9e5a-1f5cc9c92e5f.png">
SSH config:
<img width="715" alt="SSH config" src="https://user-images.githubusercontent.com/3112087/174743255-b29c1c44-6666-4437-86f8-5cf76a5a36cf.png">

Thank you!

**Comment by leecolarelli** [comment]
I have found the exact same issue as the author... I tried for ages to get TablePlus to work with 1password and it just would not. Then as soon as I enabled the `SSH Debug Log` and started via the command line, it requested access from 1Password and everything worked correctly.

**Comment by studnitz** [comment]
The [1Password SSH Agent documentation has a compability table](https://developer.1password.com/docs/ssh/agent/compatibility/#tableplus) for differnt Apps, including TablePlus.

By using [`SSH_AUTH_SOCK`](https://developer.1password.com/docs/ssh/agent/compatibility/#ssh-auth-sock) I was able to make TablePlus work with the 1Password SSH Agent.

**Comment by DIntriglia** [comment]
Thank you @studnitz - That worked like a champ. 

I set it up using the [Configure SSH_AUTH_SOCK globally for every client](https://developer.1password.com/docs/ssh/agent/compatibility/#configure-ssh_auth_sock-globally-for-every-client) option and it worked like a champ. 

Simply removed the manually added SSH key, tried again, and it then prompted to use 1Password instead. WooHoo!

**Comment by huyphams** [comment]
Hi, we added support `ed25519` in this patch, if you have a chance, please try it: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0

**Comment by tdimeco** [comment]
It works perfectly! Thank you! 😊

**Comment by DIntriglia** [comment]
@huyphams All of a sudden, it has stopped working for me. Was there a recent 1Password or TablePlus update that could have caused this?
