### ISSUE TITLE
Example of Incorrect generated alters for MySQL

### ISSUE THREAD

**Issue by VinaiRachakonda** [TablePlus/TablePlus#2646]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Mysql 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 4.6.2

3. The steps to reproduce this issue:

Consider the following schema

```
CREATE TABLE `alters` (
  `pk` int NOT NULL,
  `va1` int DEFAULT NULL,
  `val2` int DEFAULT NULL,
  `val3` int DEFAULT NULL,
  `val4` int DEFAULT NULL,
  PRIMARY KEY (`pk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

Tableplus generates the following query when dropping some columns and adding a column at the end of the table

```
ALTER TABLE `test`.`alters`
DROP COLUMN `val2`,
DROP COLUMN `val3`,
DROP COLUMN `val4`,
ADD COLUMN `val5` int NULL AFTER `val4`;
```

This errors with MySQL given that val4 gets dropped before. The after clause should not be there.

Noted: If the bug is related to data, please attach an example SQL data.

<img width="1239" alt="Screen Shot 2022-03-31 at 4 43 57 PM" src="https://user-images.githubusercontent.com/7027863/161167083-3813760d-497d-40c7-8083-469edee88d0f.png">

**Comment by huyphams** [comment]
Thank you for letting me know. Please wait for the next update!
