### ISSUE TITLE
Clickhouse not work

### ISSUE THREAD

**Issue by PromiseNev** [TablePlus/TablePlus#2647]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    ClickHouse 21.12.3.32
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
     Version 4.6.3 (413)
3. The steps to reproduce this issue:
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/16667188/161494131-6fdae402-f84b-43ce-9a57-01bffab165da.png">

**Always stuck and not moving, DBeaver work well**

**Comment by huyphams** [comment]
Could you show me your connection form, I think you are using the wrong port.

**Comment by PromiseNev** [comment]
> Could you show me your connection form, I think you are using the wrong port.

i use 9000 & 8123    neither work

**Comment by huyphams** [comment]
Could you show me your connection form @PromiseNev thank you

**Comment by PromiseNev** [comment]
<img width="612" alt="Xnip2022-04-06_19-19-25" src="https://user-images.githubusercontent.com/16667188/161963460-0d19e7de-a9af-469c-947b-ac2af709812b.png">

@huyphams     thank you ....

**Comment by huyphams** [comment]
Your setup is wrong...

**Comment by PromiseNev** [comment]
>  Host  is  AWS EC2's DNS name,  MYSQL same to it,  em.....what option is wrong ... - -!

**Comment by Etam1ne** [comment]
Sorry if I get this wrong, but I have the same issue and can't find a solution though the issue is closed
