### ISSUE TITLE
On Quit (Cmd + Q), have an option for a confirmation screen asking, "Are you sure you want to quit? Yes / No"

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#265]

**Comment by brian-crane** [comment]
btw I like the updated website - very slick!

I can also see you are first in Google results when entering 'TablePlus' - good!

**Comment by huyphams** [comment]
Thanks, Brian. If there are uncommit changes, TablePlus will show you a confirmation popup like this:

On Build 88 I fixed many issues related to this confirmation popup. Which Build are you on @brian-crane?

<img width="1075" alt="screen shot 2018-02-16 at 8 03 22 am" src="https://user-images.githubusercontent.com/3654622/36288975-0375264c-12f0-11e8-9755-5724e2849c67.png">
