### ISSUE TITLE
Clickhouse Connection is error

### ISSUE THREAD

**Issue by PromiseNev** [TablePlus/TablePlus#2652]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
 ClickHouse  21.12.3.32
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    Version 4.6.4 (415) 
3. The steps to reproduce this issue:
 
<img width="568" alt="Xnip2022-04-09_18-29-44" src="https://user-images.githubusercontent.com/16667188/162568175-fd787d2d-bf99-4c4a-aee6-9296796dab82.png">
<img width="570" alt="Xnip2022-04-09_18-32-14" src="https://user-images.githubusercontent.com/16667188/162568179-4c47397f-356a-4d69-88fb-fe39c3a14bf7.png">

IF I USE Port 9000, popup dialog this...

IF I USE Port 8123... then click  "Test"   emm......everything is not change..

**Comment by sathwik-aileneni** [comment]
Facing the same issue for clickhouse connection. Is there any specific port we need to use? 

I tried 8123, 9281, 9181, 9010, 9000
