### ISSUE TITLE
Only one schema selectable for Oracle DB

### ISSUE THREAD

**Issue by joymmart** [TablePlus/TablePlus#2656]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle Connection
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 415
3. The steps to reproduce this issue:
Open an Oracle Connection
Click the schema drop-down
Only the defaulted schema is in the drop down

I can explicitly query tables in other schemas, so I do not believe this is an access issue. Other driver type that include the schema drop-down (checked with PostgreSQL) do display all available schemas.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
This issue would be fixed in recent releases. Please let me know if you are still seeing it.

**Comment by kinghuang** [comment]
I'm also having the same problem with TablePlus 5.0.2 (459). I can write queries against other schemas. But, only my current schema appears in the schema select menu.

**Comment by hakwik** [comment]
Still very much an issue with version 5.2.2 (479).

**Comment by hakwik** [comment]
@huyphams please consider reopening.

**Comment by wshuman3** [comment]
Still seeing this issue with 5.2.5 (481)

**Comment by jomiva** [comment]
I'm having this issue too. I can query to other schemas "schema.tableName" but I can't see any schema from the dropdown. I'm using Oracle too.
