### ISSUE TITLE
Copying/exporting from a table with no primary key includes the ctid system column

### ISSUE THREAD

**Issue by zydeco** [TablePlus/TablePlus#266]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 88

3. The steps to reproduce this issue:
 * Select some rows from a table with no primary key
 * Copy it (⌘-C or context menu Copy Rows As > anything)
 * Paste it (either in a table with the same schema, or another database)
 * The first column pasted will be the ctid instead of the first column from the table it was copied

This happens also when you copy as CSV, JSON or as an insert statement.
The ctid field shouldn't be included, since it can't be used when inserting, it's not part of the data but an identifier related to the physical layout of the table (see [postgres docs](https://www.postgresql.org/docs/8.2/static/ddl-system-columns.html)).

**Comment by huyphams** [comment]
Thanks, I'm fixing it now.

**Comment by huyphams** [comment]
Hey @zydeco could you try this build and let me know if it works for you?
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by zydeco** [comment]
Yes, that works perfectly, thanks!
