### ISSUE TITLE
Display VARCHAR length in Redshift table structure view

### ISSUE THREAD

**Issue by kuchkovsky** [TablePlus/TablePlus#2660]
When I use Redshift driver 1.0.37176 with TablePlus v4.6.4 (414), the data_type column shows the type (character varying), but the column length information is missing.

Is it possible to add a length for the VARCHAR type?

**Comment by kuchkovsky** [comment]
I see this feature in DataGrip, but it's missing in TablePlus for some reason.

**Comment by huyphams** [comment]
Thanks, let me check it.

**Comment by huyphams** [comment]
Hi @kuchkovsky if you have a chance, please download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 It should show the character length.
Thank you.
