### ISSUE TITLE
Authentication failed when connecting to ClickHouse

### ISSUE THREAD

**Issue by maxpain** [TablePlus/TablePlus#2666]
1. Which driver are you using and version of it: ClickHouse
2. Which TablePlus build number are you using: 414

ClickHouse server version 22.2.2

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5875582/164300858-5f6bd6f7-2483-4fb4-98e7-3ff199875872.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5875582/164300677-0e89d658-b843-4423-89dc-6e9a844790b0.png">

**Comment by huyphams** [comment]
Hi @maxpain please try this hotpatch and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
