### ISSUE TITLE
Can't change table structure

### ISSUE THREAD

**Issue by minesunny** [TablePlus/TablePlus#2668]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
version 466
3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.
 

https://user-images.githubusercontent.com/98507458/165241193-920d3b38-be38-468e-9bcb-d96e2877da87.mov

**Comment by simube** [comment]
Did you hit Cmd&S after adding the column? It doesn't look like that...

Green background means that values are added, yellow means "change", red "delete" - but everything is applied only if you hit "Edit -> Commit" or Cmd&S

**Comment by joebnb** [comment]
in mac it's always happen，and it need quit app and restart when use it with sqlite
