### ISSUE TITLE
[Feature Request] - Safe mode at the connection level

### ISSUE THREAD

**Issue by smiley-uriux** [TablePlus/TablePlus#2669]
Love the extra protection safe mode provides, however I really only want it enabled on my production connections. I spend more time within non-production accounts though so I find myself disabling safe mode and having to remember to enable it when I switch to production - which sort of defeats the purpose. Being able to configure safe mode at the connection level, or perhaps applying safe mode to a configurable subset of connection tags would be a super useful addition.

Really great job with this software - its hands down my favorite MacOS db client and is getting better all the time!

**Comment by dougjohnston** [comment]
I just found this feature and I had the exact same question. While it would be nice to have the Safe Mode setting within the connection edit window, it does seem that if you change the setting once connected, the setting persists to future connections. So, I went into each of my production databases, set Safe Mode to my desired setting, and it now keeps the setting next time I connect. YMMV.

![Screen Shot 2022-04-29 at 12 49 41 PM](https://user-images.githubusercontent.com/12276/166060287-1c64bed8-720a-420c-898d-61e8370f2fd4.png)

I also agree that TablePlus is awesome!!!

**Comment by huyphams** [comment]
Hi @smiley-uriux we can now set the default safe mode for any new connections in the settings
<img width="612" alt="Screen Shot 2022-04-30 at 7 51 28 AM" src="https://user-images.githubusercontent.com/3654622/166084106-f754e67b-2395-41b0-9a68-6dce8d5b2580.png">

**Comment by smiley-uriux** [comment]
A very welcome addition, thanks @huyphams!

**Comment by kevinsmith** [comment]
I'm also very interested in the original feature request: the ability to set a given connection to enable "safe mode". I'd like to require password before doing it in prod, alert before doing it in staging, and disable safe mode for local development.

**Comment by huyphams** [comment]
Hi @kevinsmith it's connection level from the beginning, do you have any issue with it?

**Comment by huyphams** [comment]
Hi, @smiley-uriux I think I missed understood you from the beginning. TablePlus safe mode is per connection level already. Please let me know if you have any issue, if you found any issue please show us the steps to reproduce the issue.

**Comment by kevinsmith** [comment]
I'm confused. I would expect to set per-connection preferences in this part of the UI.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/397904/194208143-84229084-71f2-4dba-a856-d027c108bc43.png">
