### ISSUE TITLE
UI freezes for a few seconds when receiving large (8M) datasets and closing its tab

### ISSUE THREAD

**Issue by Andre-Depop** [TablePlus/TablePlus#267]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 8.0.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 

Build 88

3. The steps to reproduce this issue:

Make a query that returns a huge amount of data; when that returns the UI will freeze for 15 seconds, preventing work in other tabs. Once the initial freeze is over, _closing_ the tab also causes a freeze.

If that's of any relevance, I was connecting to Redshift over TLS which is itself over SSH.

**Comment by huyphams** [comment]
This issue should be fixed it I implement this: https://github.com/TablePlus/TablePlus/issues/194

**Comment by Andre-Depop** [comment]
Thanks for the quick reply 👍

**Comment by Andre-Depop** [comment]
> Btw, Can you give me more info about the data. Is it text only?

Yes, the data was text only; about 20 columns or so of integers & strings.

**Comment by huyphams** [comment]
It's fixed in issues: https://github.com/TablePlus/TablePlus/issues/194 
You can try the build in dropbox file before its official release next week.
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
