### ISSUE TITLE
Cannot click on the Autocomplete suggestions for table/relation 

### ISSUE THREAD

**Issue by PeggyFan** [TablePlus/TablePlus#2671]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redshift

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.6.4 (414)

3. The steps to reproduce this issue:
I'm working with a database with multiple schemas.
When I write the query, there is autocomplete suggestions of table (and the schema it's in).
But when I click on the table of choice, nothing happens. It doesn't update the table with the corresponding schema name.
It would be nice to be able to choose tables across schema this way.

![Untitled](https://user-images.githubusercontent.com/8127522/165856986-55223ebc-7542-4b80-bf05-3a38a07d27c0.png)

**Comment by huyphams** [comment]
Hi @PeggyFan please enable the auto prefix schema and try again. Thanks
<img width="603" alt="Screen Shot 2022-05-23 at 9 43 36 AM" src="https://user-images.githubusercontent.com/3654622/169733485-d58dd438-6cd7-485a-a393-1904ec6c74f3.png">

**Comment by huyphams** [comment]
Hi @PeggyFan please see the attachment below:
<img width="1511" alt="Screenshot 2023-02-16 at 9 17 50 AM" src="https://user-images.githubusercontent.com/3654622/219250894-d326f9ae-4fa9-4856-a18a-8bf5d64f21f1.png">

**Comment by PeggyFan** [comment]
thank you- found it and it works.
