### ISSUE TITLE
Enum values are re-ordered alphabetically when exporting to SQL file

### ISSUE THREAD

**Issue by sxg** [TablePlus/TablePlus#2672]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 14.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 421

3. The steps to reproduce this issue:
- Create an enum (`CREATE TYPE permission_level AS ENUM ('read', 'edit', 'delete';`)
- Export the database as a SQL file from TablePlus' File → Export
- Import the SQL file into a new database
- Check the value of the enum. The order of the enum values are re-arranged alphabetically and is now 'delete', 'edit', 'read' instead of preserving the original order.

It looks like the order of the enum values are re-arranged in the exported .sql file, so the issue is in the export process. Notably, `pg_dump` doesn't do this.

**Comment by huyphams** [comment]
Hi @sxg thank you for letting me know. We fixed the bug, it will be released in the next update 👍
