### ISSUE TITLE
Incorrect Float64 values for Clickhouse

### ISSUE THREAD

**Issue by dadebue** [TablePlus/TablePlus#2673]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Latest Clickhouse Beta

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Buil 414

3. The steps to reproduce this issue:
I have a table with Nullable(Float64) LZ4 compressed columns:
![Screen 2022-05-03 at 11-25-47](https://user-images.githubusercontent.com/81422785/166431123-16f478e7-907a-4b71-b547-6bfc1c7a0c5b.png)

When I query the data the values of those columns are shown incorrectly in TablePlus:
![Screen 2022-05-03 at 11-26-07](https://user-images.githubusercontent.com/81422785/166431155-d668d7ec-5d71-493f-9096-c374d2c3b28b.png)

Comparison to the official Clickhouse HTTP interface:
![Screen 2022-05-03 at 11-26-19](https://user-images.githubusercontent.com/81422785/166431219-87199e4a-8547-44e6-85a8-61bac93535b6.png)

Here is the data:
```
time_stamp	logger_id	measurement_id	ACC_X_2	ACC_Y_2	ACC_Z_2
0	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	0	0	0
20000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.3512499250937253	4.709999894723296	2.6462499408517033
40000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.4212499235291034	4.651249896036461	2.834999936632812
60000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.3362499254290015	4.8274998920969665	2.571249942528084
80000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.3749999245628715	4.737499894108623	2.463749944930896
100000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.0837499310728163	4.53249989869073	2.528749943478033
120000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.2474999274127185	4.708749894751236	2.463749944930896
140000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.322499925736338	4.657499895896763	2.539999943226576
160000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.361249924870208	4.641249896259978	2.6037499418016523
180000	7cebba11-1ee5-4780-93fa-10b322deee53	1159bb3f-1d00-4f46-bd4f-b5b49fabfa92	-3.40749992383644	4.7074998947791755	2.6437499409075826
```

**Comment by huyphams** [comment]
Hi @dadebue could you please try this build and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thank you

**Comment by dadebue** [comment]
All values are correct with this build! 👍🏼

**Comment by bewareilive** [comment]
Hello, what is the tool in the picture?
