### ISSUE TITLE
Regex for query parameters requires whitescapes

### ISSUE THREAD

**Issue by grzn** [TablePlus/TablePlus#2675]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PosgreSQL 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.6.4 (414)

See the attached screenshot. it worked when there are spaces before and after $2 and $3.

<img width="846" alt="CleanShot 2022-05-06 at 14 50 55@2x" src="https://user-images.githubusercontent.com/175126/167126112-4d12fe62-3305-4e1f-9424-36beacbfb7dd.png">

**Comment by huyphams** [comment]
Hi @grzn thank you for letting me know. I just fixed it. If you have a chance, please download the hotpatch here: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
