### ISSUE TITLE
[Feature Request] Better keyboard support for table filters

### ISSUE THREAD

**Issue by stephen-ullom** [TablePlus/TablePlus#2676]
**Specs**
MacOS 12.3.1
MySQL 5.7.12
TablePlus Build 414

**Steps to Reproduce**
Open Anything (⌘ + P) then choose a table (Return) **OR** click a table from the item list.
Show filters (⌘ + F).

**Issue**
I love that you can do so much with keyboard shortcuts. But there is no way to choose a *table column* or *query operator* without using a mouse. 

Originally I expected to be able to use `tab` or `⇧ + tab` to to cycle through the selection fields but it looks like tab does nothing. I thought maybe it cycles between search conditions if you have multiple but no. 

**Solution**
Add tab or arrow key support to cycle through search options at least for columns and query operators. If there is a reason why the focus must remain in the text field, maybe provide a keyboard shortcut to choose the column and operator options.

**Comment by huyphams** [comment]
Duplicate: https://github.com/TablePlus/TablePlus/issues/1041

Hi guys, if you have a chance, please download this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Cmd + Left Arrow/Right Arrow to open the Columns/Operator popup
