### ISSUE TITLE
[BUG] Triggers is not working

### ISSUE THREAD

**Issue by marcusnunes** [TablePlus/TablePlus#2678]
When I click on triggers it shows an empty list

TablePlus - Version 4.6.4 (414)
Mysql 8

**Comment by huyphams** [comment]
Hi @marcusnunes we're using this query to fetch triggers:

SELECT trigger_name as name,event_manipulation as event,action_timing as timing,action_statement as statement,created as created FROM information_schema.triggers WHERE event_object_schema='replace_database_name' AND 
 event_object_table='replace_with_table_name';
 
 
 Could you please run the query and see how it goes? I think it is the permission issue (your user do not have the permission to fetch the trigger list).
 
 - replace_database_name: your database name
 - replace_with_table_name: your table name
