### ISSUE TITLE
Previously connected to Redshift perfectly fine, but no longer can

### ISSUE THREAD

**Issue by tegansnyder** [TablePlus/TablePlus#2683]
I'm scratching my head trying to figure this one out. Just last week I was able to connect to Redshift using TablePlus. Nothing has changed on my connection settings. The same connection settings in VS Code allow me to connect, but TablePlus is not letting me anymore. It used to work.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Redshift

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 422 / v4.6.6

4. The steps to reproduce this issue: Try and connect to an existing Redshift connection that worked fine last week but fails now

Is Tableplus using the Amazon Redshift JDBC driver behind the scenes? I wonder if it needs to be updated? Also I tried downgrading to 4 of the previous builds of TablePlus down to build 402 and the same issue persists. It's strange that it works in VSCode with https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift but not in TablePlus.

**Comment by huyphams** [comment]
Hi @tegansnyder TablePlus does not use JDBC (it's not a Java application, it's a native application). Could you double-check the input?

**Comment by tegansnyder** [comment]
I double checked the input. It's actually really strange. I'm only able to connect with VSCode. I tried same settings with TablePlus and Datagrip and it won't connect. I also tried a PHP script I have that previously was able to connect to it and it is also failing.

Note: all these failures to connect are on my local machine. I have AWS batch jobs running in the same AWS account that are able to connect just fine to Redshift. So normally I would think it was related to a security group not allow ingress from my IP address, but the thing that makes that difficult is it actually works locally with VSCode. I'm putting in a AWS support ticket to see if they can help. It could also very well be some weird network controls on my corporate network, but again its weird that VSCode works.

**Comment by tegansnyder** [comment]
Does Tableplus use libpq C library behind the scenes to communicate to Redshift?

**Comment by huyphams** [comment]
I just tested and it works just fine.
<img width="1508" alt="Screen Shot 2022-05-14 at 6 26 35 AM" src="https://user-images.githubusercontent.com/3654622/168401039-79dc279a-ce13-488e-bfbf-7989e9ceb2f2.png">

**Comment by tegansnyder** [comment]
I think it is something to do with corporate security controls in place at my place of employment. What is interesting is I did a PCAP with wireshark on the VS Code connection and it appears the VS Code Redshift connection tool is non-encrypted HTTP vs the Tableplus connection. So I'm going to close this issue and work with our internal teams.
