### ISSUE TITLE
Backup and Restore UI truncates connections initially even when there is space

### ISSUE THREAD

**Issue by joshdavenport** [TablePlus/TablePlus#2686]
![2022-05-16 13 48 23](https://user-images.githubusercontent.com/757828/168596299-550cb101-cd44-40b1-9d2b-bb059a18ab7b.gif)

When opening either of these dialogs, the connections are truncated with ellipsis even when there is plenty of space to display the information. The same can also happen to the databases when clicking a connection:

![image](https://user-images.githubusercontent.com/757828/168606374-a9642bfc-1207-49a5-baee-0cd7c806280e.png)

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
421

3. The steps to reproduce this issue:
Open Backup or Restore, connections are truncated.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @joshdavenport if you have a chance, please download this patch and see how it goes:
https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
