### ISSUE TITLE
Oracle problem

### ISSUE THREAD

**Issue by xaopohi** [TablePlus/TablePlus#2688]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 11.2.0.2.0
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.6.6 (423)
3. The steps to reproduce this issue:

The current user has 530280 tables, and there are at least three users like this, and each user is at least 100g, so the tool will be very slow to connect to the database and stutter, and it will be very stuttered when writing 'sql', and the message prompted when the sql' executes an error is garbled that can't be understood.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @xaopohi there is a setting button at the bottom left of the pane, please turn on Lazy loading schema items and see how it goes

**Comment by xaopohi** [comment]
@huyphams The name of the 'SQL' prompt table will be very too laggy, and the 'SQL' writing is very slow

**Comment by huyphams** [comment]
Please try to turn of auto complete too ![9FFF7726-A777-479F-AA6D-8EF3ED511F50](https://user-images.githubusercontent.com/3654622/168943908-dc731e0c-1160-4e69-858e-79fc2b655d4d.jpeg)

**Comment by xaopohi** [comment]
This function is still needed to see if it can be optimized. When an error is reported during the execution of an 'SQL' statement, the error information is not visible
<img width="521" alt="WX20220518-104954@2x" src="https://user-images.githubusercontent.com/48237209/168947916-10f39570-fd40-478b-8555-253de8c1d0c3.png">

**Comment by huyphams** [comment]
Hi @xaopohi how does the original issue, are you still seeing them after turning on lazy load and turning off auto completion?

**Comment by xaopohi** [comment]
The original problem is no longer a problem
