### ISSUE TITLE
New > Connection From Url always creates Postgres connection

### ISSUE THREAD

**Issue by travisdahlke** [TablePlus/TablePlus#269]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
88

3. The steps to reproduce this issue:
New > Connection From Url
Paste `mysql://localhost/test`, click 'Import'
The Postgres connection settings window appears, while the Name field is populated with "MySQL Connection"
![connection 2018-02-16 13-36-07](https://user-images.githubusercontent.com/737008/36325729-5aa2d8c8-131e-11e8-9e6e-a3507cc8ceb7.png)
Expected outcome: the driver is selected appropriately from the url.

**Comment by huyphams** [comment]
It's fixed in this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Could you give it a try 😄
