### ISSUE TITLE
TablePlus not starting

### ISSUE THREAD

**Issue by tashi21** [TablePlus/TablePlus#2691]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- N/A

3. The steps to reproduce this issue:
- Try to start the app.
Noted: If the bug is related to data, please attach an example SQL data.

TablePlus is not starting on my system. I did a complete reinstall and it still results in the same error. The error message is:
The application was unable to start correctly (0xc0000135). Click OK to close the application. It was working fine until it stopped working on its own.

System:
Edition: Windows 11 Home Single Language
Version: 21H2
OS Build: 22000.675
Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
System Type: 64-bit operating system, x64-based processor

**Comment by huyphams** [comment]
It could be a .Net issue, please read this https://answers.microsoft.com/en-us/windows/forum/all/0xc0000135-error-when-opening-most-applications/7db10be2-66fb-4e5d-b553-8fa524bb2124 and try to install the .Net 4.8
Also the correct Windows repo is here: https://github.com/tableplus/tableplus-windows/issues
Thanks
