### ISSUE TITLE
[UI Improvement] Visual indicator that filter input is ignored

### ISSUE THREAD

**Issue by apfelbox** [TablePlus/TablePlus#2692]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- MariaDB

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- 4.6.6 (422)

5. The steps to reproduce this issue:
- Use filtering

Noted: If the bug is related to data, please attach an example SQL data.
When using filters, some of the dropdown values lead to the text input afterwards being ignored (which is correct):

![CleanShot 2022-05-26 at 11 31 47](https://user-images.githubusercontent.com/1032411/170460787-f8a14d8e-cba6-45dc-8194-ad62f9b2ebf4.png)

However, it would be great if the UI would reflect that by hiding / disabling / fading out the input field when it is ignored for filtering.

**Comment by huyphams** [comment]
If we ignore the field, you will not be able to hit the enter to apply the filter, also there will be no indicator that marks the filter is being applied

**Comment by apfelbox** [comment]
Ok, I understand that. However having a value there that doesn't apply is really confusing UI.

I actually got the exact question "hey, but aren't that all entries with `ok: false`"? And I needed to tell them "no.. see, for some of these entries (and you need to now which ones, because nobody tells you) the input field will be ignored." – which is less than ideal.

**Comment by huyphams** [comment]
it's a known issue (actually we used to disable it in the past). However, it caused more trouble than it's worth.
1. Not be able to hit enter.
2. Not be able to navigate use cmd + up/down/left/right arrow.

If we clear the input instead of disabling it, it still has a downside (cleaning old values is a downside), so we would prefer to keep it as it is.
