### ISSUE TITLE
Default filter operator setting not effective on Windows

### ISSUE THREAD

**Issue by davekaro** [TablePlus/TablePlus#2693]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Windows build 194

3. The steps to reproduce this issue:
  - Click on a table
  - Open the filters, change the default filter operator to `=`
  - Right click a column heading and chose "Filter with column"
  - The default filter operator is `Contains`, but it should be `=`

No matter how I do it, I always get `Contains` and not `=`.

![Screenshot 2022-05-26 105911](https://user-images.githubusercontent.com/21263/170515884-5e0bb5e7-b261-49a7-8885-7188586deda4.png)

My friend uses TablePlus on macOS and I had him try it. He changed the default operator to `=` and upon filtering a column, it defaulted to `=` - so this is likely a Windows only issue.

**Comment by huyphams** [comment]
Hi @davekaro thank you, let me fix it.

**Comment by huyphams** [comment]
The issue has been fixed, if you have a chance, you can download the hotpatch here: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0

**Comment by davekaro** [comment]
I tried the hotpatch - it works great. Thanks!
