### ISSUE TITLE
Latest versions don't open on 10.11 by clickhouse

### ISSUE THREAD

**Issue by MacTerrassa** [TablePlus/TablePlus#2694]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): none (do not open the app)

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 414 (and later)

4. The steps to reproduce this issue: Double click on the application. It does not open, it appears in the dock and immediately closes, generating an error message:

Process:               TablePlus [4156]
Path:                  /Applications/TablePlus.app/Contents/MacOS/TablePlus
Identifier:            com.tinyapp.TablePlus
Version:               4.6.4 (414)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TablePlus [4156]
User ID:               501

Date/Time:             2022-05-27 13:38:26.359 +0200
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        ****************

Time Awake Since Boot: 10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
/Applications/TablePlus.app/Contents/MacOS/../Frameworks/ClickHouse.framework/Versions/A/ClickHouse

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.tableplus.ClickHouse      	0x0000000105ca3ed3 std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, clickhouse::Type::Code, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, clickhouse::Type::Code> > >::unordered_map(std::initializer_list<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, clickhouse::Type::Code> >) + 1235
1   com.tableplus.ClickHouse      	0x0000000105ca650b _GLOBAL__sub_I_type_parser.cpp + 1211
2   dyld                          	0x00007fff66b7210b ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
3   dyld                          	0x00007fff66b72284 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
4   dyld                          	0x00007fff66b6e8bd ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 305
5   dyld                          	0x00007fff66b6e852 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 198
6   dyld                          	0x00007fff66b6e743 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 127
7   dyld                          	0x00007fff66b6e9b3 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 75
8   dyld                          	0x00007fff66b610f1 dyld::initializeMainExecutable() + 208
9   dyld                          	0x00007fff66b64d98 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 3596
10  dyld                          	0x00007fff66b60276 dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 512
11  dyld                          	0x00007fff66b60036 _dyld_start + 54

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x00007fc7b8d03a40  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00007fc7b8d03a40  rsi: 0x00007fff5d3ff910  rbp: 0x00007fff5d3ff900  rsp: 0x00007fff5d3ff8a0
   r8: 0x0000000000000002   r9: 0x00000000ffffffc0  r10: 0x000000010309d601  r11: 0x0000000103076250
  r12: 0x00007fff5d3ff910  r13: 0x7d1c121419118f83  r14: 0x00007fc7b8d03a30  r15: 0x0000000000000000
  rip: 0x0000000105ca3ed3  rfl: 0x0000000000010293  cr2: 0x0000000105e9beb2
  
Logical CPU:     1
Error Code:      0x00000000
Trap Number:     6
....

The latest version I can open is 410 (4.6.2). 
I have tried 414, 422 and 424. Both downloaded directly from their website, and accepting the proposed update when opening version 410, which installs the current 424. All of them cannot be opened and generate the same error message. What are the actual requirements of the app then? Is it the processor in my mac, an Intel Core 2 Duo (2007)?
Regards

P.S. Mechanically translated message since I do not speak English, I apologize if I have not expressed myself correctly.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I just tried to open TablePlus on macOS 10.11 and it works
<img width="753" alt="Screen Shot 2022-05-27 at 8 22 56 PM" src="https://user-images.githubusercontent.com/3654622/170707801-16558e28-4329-4459-940c-2cdab0406037.png">

**Comment by MacTerrassa** [comment]
Maybe it is then the issue of the processor? My mac is from 2007, an Intel Core 2 Duo, and on more occasions they have responded to me when faced with a problem, that the processor does not have a series of necessary orders depending on which program. Will it be the case of TablePlus? Your Mac is one of 2019, much more modern and it can be that.

**Comment by huyphams** [comment]
Hi @MacTerrassa if you have a chance, please try this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by huyphams** [comment]
Please let met know if you are still seeing the issue.

**Comment by MacTerrassa** [comment]
Hello, sorry for not responding sooner, I just got on my old mac and tried to open the dropbox version of the previous message and it opens perfectly, without any problem. The changes seem to be successful. Thanks. Now I will be able to review the program and see if in addition to working, it adapts and I can finally acquire a license or not. Regards.
