### ISSUE TITLE
Slow SQL Export / Import

### ISSUE THREAD

**Issue by mileshd** [TablePlus/TablePlus#2695]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **MySQL 8**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **4.6.6**

3. The steps to reproduce this issue: **Exported database as SQL, came to a 2.3 GB file.**

I have been using SequelPro for years, but recently switched to TablePlus. Loving Table plus, but am having an issue with slow imports. I exported my database (about 2.3 GB) and am attempting an import to a local database. This would take a few minutes with SequelPro, but I have been waiting over 20 min with TablePlus and it's only imported 0.7 / 2.3GB.

Is this the performance that should be expected, or could there be some configuration / other factor that is causing this speed, and are there steps I can take to improve it?

It's a brand new computer with everything fresh-installed as of a couple days ago.

Sequel Pro Version: 4.6.6
Database: MySQL 8
Computer: MacBook Pro: m1, 16GB Memory.

Thanks!

**Comment by mileshd** [comment]
Over an hour later, at 1.5 / 2.3 GB.

**Comment by huyphams** [comment]
Hi @mileshd could you please try the restore feature (not import) and see how it goes?

**Comment by mileshd** [comment]
Hi @huyphams, thank you for your reply.

My issue was actually chrome was taking up so much memory, that it was severely degrading the import performance. I known chrome hogs memory, but it had never impacted other application's performance in this way, nor did my chrome habits have this kind of impact when running comparison tests on my older Mac.

Needless to say, I was shocked that was the answer. But this is not an issue with TablePlus.

Thanks again!
