### ISSUE TITLE
Database names are truncated in the restore window

### ISSUE THREAD

**Issue by pieterclaerhout** [TablePlus/TablePlus#2696]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

TablePlus 4.6.6 (422) on macOS

3. The steps to reproduce this issue:

Create a database with a long name and then go to File > Restore. After selecting the connection, the list of database names is presented like this:

<img width="1015" alt="Screenshot 2022-05-30 at 13 18 42" src="https://user-images.githubusercontent.com/74731/170982296-d50ce3ae-6689-4d25-a60e-96698db969b2.png">

Resizing the panels doesn't help and the database names stay truncated (which makes it hard to know which one to select).

**Comment by huyphams** [comment]
HI @pieterclaerhout thank you for letting know. If you have a chance, please download this patch and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by pieterclaerhout** [comment]
The patch works fine! 🎉

<img width="1015" alt="Screenshot 2022-05-30 at 15 56 10" src="https://user-images.githubusercontent.com/74731/171007112-aa80b56f-18f3-4e56-a1b2-94b38b2d682a.png">
