### ISSUE TITLE
Autocomplete is interrupted if underscore character ( _ ) is part of table name

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#27]
as shown in below animation, autocomplete is interrupted if underscore character ( _ ) is part of table name.

![2017-07-28 23_20_59](https://user-images.githubusercontent.com/7946786/28742689-a319bb8a-73eb-11e7-8ac0-95fe18f11b2f.gif)

OSX info:
<img width="242" alt="screen shot 2017-07-28 at 11 01 53 pm" src="https://user-images.githubusercontent.com/7946786/28742692-aaaf650c-73eb-11e7-8b5c-4874e493e576.png">

**Comment by huyphams** [comment]
yup, we already know this issue and it's limitation of the current solution.
We have a plan to improve SQL Query Editor with suggestion based on current database context and improve the UI.
It's will not available in short time. It's need couple of month to implement. But sure, we will improve it.

**Comment by brian-crane** [comment]
Hi Huy - just a random side question - is there a place I can view the release notes for new releases? Such as new 56 release, where can I see where new features have been added?

**Comment by huyphams** [comment]
@brian-crane 
For temporary you can view it in github wiki
https://github.com/TablePlus/TablePlus/wiki/Changelogs

Or follow our fan page. Click the icons on welcome screen.
