### ISSUE TITLE
Minor - Allow arrow key navigation when switching databases

### ISSUE THREAD

**Issue by bhrd** [TablePlus/TablePlus#270]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
88
3. The steps to reproduce this issue:
Press `command+K` to switch databases.
Start typing database name
Down arrow does not choose from filtered list. (I notice that tab allows switching to the list and down arrow works after that, but why not down arrow directly?)
![image](https://user-images.githubusercontent.com/221584/36332660-f30897a2-1327-11e8-9978-409cd0ed8a18.png)

**Comment by huyphams** [comment]
Sure @bhrd 😄
