### ISSUE TITLE
Unable to parse type: DateTime('UTC') in ClickHouse

### ISSUE THREAD

**Issue by romap0** [TablePlus/TablePlus#2701]
Driver: ClickHouse
TablePlus build: 425

Table schema:
```sql
CREATE TABLE test_table (
  `id` String,
  `blocked` UInt8,
  `beginTime` DateTime ('UTC'),
  `endTime` DateTime ('UTC')
)
ENGINE = MergeTree ()
PARTITION BY toYYYYMM (beginTime)
ORDER BY (id, beginTime)
TTL beginTime + toIntervalMonth (3)
SETTINGS index_granularity = 8192;
```

When I select rows from this table instead of date I receive an error "Unable to parse type: DateTime('UTC')"

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1765996/171627019-455e25a1-91b8-4e07-92a0-a8bf3660aa14.png">

**Comment by huyphams** [comment]
Hi @romap0 I've fixed this issue, please try this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by gebrits** [comment]
@huyphams not OP but it works for me.

**Comment by romap0** [comment]
@huyphams Yes, now it works for me
