### ISSUE TITLE
Google Cloud Sql + TablePlus

### ISSUE THREAD

**Issue by hereiscasio** [TablePlus/TablePlus#2704]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
13.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
424

3. The steps to reproduce this issue:
I simply can't success to load my Google Cloud Sql for PostgreSQL in TablePlus,
So I wonder that... do u support this feature?

Or do u have any tutorial about that?

**Comment by huyphams** [comment]
Could you show me error? It seems like it is a usage issue instead of a TablePlus issue
