### ISSUE TITLE
Unable to parse type: FixedString(20) in ClickHouse

### ISSUE THREAD

**Issue by gebrits** [TablePlus/TablePlus#2707]
Driver: ClickHouse
TablePlus build: Version 4.6.8 (424)
Clickhouse: 22.1.3.7

```
CREATE TABLE test
  (
    id UInt32 Codec(DoubleDelta, ZSTD),
    address FixedString(20) 
  ) ENGINE = MergeTree()
    PRIMARY KEY block
    ORDER BY block;

insert into test(id, address) values (1, UNHEX('30856ac72435c4a741a307A07C3B700C04f2Dcc4'))

```

Querying results in `Unable to parse type: FixedString(20)`

**Comment by gebrits** [comment]
Since FixedString underneath is a bytearray, it would probably make most sense to display as a hex-string

**Comment by huyphams** [comment]
SELECT UNHEX('30856ac72435c4a741a307A07C3B700C04f2Dcc4') as a; return NULL. However I have added the FixedString to TablePlus.
