### ISSUE TITLE
list of table font size

### ISSUE THREAD

**Issue by acveer** [TablePlus/TablePlus#2711]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.0
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
47
3. The steps to reproduce this issue:

I love table plus, have purchased license to it since last 2 years. I wish there is a way to increase the font size of the list of tables in the left UX pane. The default is small to my old eyes. Please add this enhancement

**Comment by huyphams** [comment]
We do not have the build 47 @acveer
