### ISSUE TITLE
Unable to connect to a database via SSL - Unknown key OID type

### ISSUE THREAD

**Issue by BabyGroot** [TablePlus/TablePlus#2718]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
Aurora MySQL5.7

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
428

5. The steps to reproduce this issue: 
Attempt to connect to the database via SSL

I got the following error:
<img width="257" alt="Screenshot 2022-06-22 at 12 38 52" src="https://user-images.githubusercontent.com/9529619/175011058-4078dcd0-d180-4f69-888e-9b95660c5f62.png">

Note the same setup worked on MySQL workbench so it is not an issue with the certificates and key.

**Comment by huyphams** [comment]
Are you using the same MySQL driver with the MySQL workbench? Have you tried to use the old-driver?
<img width="475" alt="Screen Shot 2022-06-22 at 6 11 34 PM" src="https://user-images.githubusercontent.com/3654622/175015272-6fc86625-420a-4c3c-a0e3-861654680c15.png">
