### ISSUE TITLE
Beautify breaks query syntax

### ISSUE THREAD

**Issue by LukeZeller** [TablePlus/TablePlus#2725]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 14.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 414

3. The steps to reproduce this issue:

Can repro with the following data:
```
CREATE TABLE bugtest(jsoncol json);
INSERT INTO bugtest
		values('{"arr": ["a", "b"]}'), ('{"arr": ["c", "d"]}'), ('{"arr": ["e", "f"]}');
```

Then the following valid query (select every row where arr contains "a" or "f"):
```
SELECT * FROM bugtest WHERE (jsoncol ->> 'arr')::jsonb @> ANY (ARRAY ['["f"]'::jsonb, '["a"]'::jsonb]);
```
is Beautified to the following invalid query (note the unbalanced single quotes near the end):
```
SELECT
	*
FROM
	bugtest
WHERE (jsoncol ->> 'arr')::jsonb @> ANY (ARRAY ['["f"] '::jsonb, ' ["a"]::jsonb]);
```
There are also some strange spaces added inside the json literals but these alone don't appear to be problematic

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
