### ISSUE TITLE
功能需求：需要在查询数据显示，前面增加上行号

### ISSUE THREAD

**Issue by where-happens** [TablePlus/TablePlus#2726]
功能需求：需要在查询数据显示，前面增加上行号
![image](https://user-images.githubusercontent.com/84372583/177035853-93b58ccc-36f1-4cef-b918-cbf8973393db.png)

**Comment by huyphams** [comment]
Are you looking for this?

<img width="476" alt="line" src="https://user-images.githubusercontent.com/3654622/177046457-e3dfcc81-7b06-4ede-8238-e4a622e8d36e.png">

We're working on it.

**Comment by huyphams** [comment]
Duplicate of https://github.com/TablePlus/TablePlus/issues/2488

**Comment by where-happens** [comment]
> Duplicate of #2488

yes,i need setting for this.but i'm not find somewhere to set!

**Comment by where-happens** [comment]
> Hi @where-happens You could try the pre-release here https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

when i update to the new version(429),the line number invalid

**Comment by huyphams** [comment]
Are you using Oracle?

**Comment by where-happens** [comment]
> Are you using Oracle?

Oracle,MySQL,MSSQL is using

**Comment by huyphams** [comment]
We've released the new updates. Please try the latest release.

**Comment by where-happens** [comment]
> We've released the new updates. Please try the latest release.

This function is solved,thanks~
but another function i hope to solve.when i write code,i hope  code  could folding
![image](https://user-images.githubusercontent.com/84372583/178134150-ae5a5741-761f-4239-8cbf-0e88f147085d.png)

**Comment by huyphams** [comment]
Added it on latest release @where-happens
