### ISSUE TITLE
Table view row auto-fit width (on header double click) still has some values truncated ending with "..."

### ISSUE THREAD

**Issue by dmythro** [TablePlus/TablePlus#2728]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.7.1 (428)

3. The steps to reproduce this issue:
    - Query any data with dates, longer values etc
    - Double-click table header `|` (at the right side of the row header item)  where you do row width resize (you get resize cursor)
    - Check layout, it has "..." at the end, instead of values for the longest value's full value (see `createdAt` on a screenshot):
    ![image](https://user-images.githubusercontent.com/1391015/177173632-ab27def0-175d-4117-b0b1-fb2cc659b3be.png)

Same with long IDs etc, which is pretty annoying when you need to compare some data etc, still have to manually resize row height.

**Comment by huyphams** [comment]
Hi, thank you for letting me know. This is one of the known issues, the values were overlapped by the braces. I'm still trying to hack into the AppKit and see how we can override this behaviour.

**Comment by huyphams** [comment]
In the meantime, you can use this option, it will auto-expand the columns to the correct size.
<img width="458" alt="Screen Shot 2022-07-04 at 10 10 14 PM" src="https://user-images.githubusercontent.com/3654622/177181414-2f552ba3-4638-41c0-a8d1-119aae29b0a6.png">

**Comment by windware-ono** [comment]
> In the meantime, you can use this option, it will auto-expand the columns to the correct size. 

Does this happen to rely on which font is used?

I tried it with the font I use and a simple boolean column in PostgreSQL 14 didn't get the width right. TablePlus build is 432 on MacOS 12.4 ARM.

It didn't work on Courier font as well.

When I selected the 'Reset column...',
<img width="72" alt="reset" src="https://user-images.githubusercontent.com/4352236/178183102-f955514f-8f14-4151-b049-883d6b3ffead.png">

When I double clicked the vertical separator in the header, it narrowed it even further.
<img width="59" alt="double-click" src="https://user-images.githubusercontent.com/4352236/178183148-2396842c-5f92-4616-bc17-fe2ea65cf02b.png">

**Comment by huyphams** [comment]
I've tried to improve it in this patch, if you have a chance, please try it: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue.

**Comment by windware-ono** [comment]
@huyphams 

Tried the build but nothing changed.
A column set as a boolean in PgSQL 14 still gets TRUE/FALSE truncated on either of the methods.

It works with Courier by double clicking the vertical separator but still gets truncated on 'Reset column' action.

It seems to depend on what font I'm using. Not sure if it has anything to do with serif and sans-serif but Helvetica seems to get truncated on both methods too.

**Comment by dmythro** [comment]
> Hi @dmythro are you clicking the table data or the structure? Could you show me the screenshot please?

![image](https://user-images.githubusercontent.com/1391015/178286630-1f4bbeb0-c3a3-40fb-a54c-c9719effb9c4.jpeg)

**Comment by huyphams** [comment]
Hmm weird, could you please try build 3.8.1 https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 
and see how it goes?

**Comment by dmythro** [comment]
I tried **4.8.0** now (prev screenshot I did was 4.7.1 or something) and the thing is:
- Initially when I fetch data, column width is good and IDs with dates are not getting truncated. Which is already very nice.
- But when I resize column to like a half size then double-click like I shown on a photo to fit the width — it gets truncated with "..." like before. "Reset column ..." menu item gets back nice data view column sizes.
- **4.8.1** build fixes issue in both cases as far a s I checked different columns.

**Comment by dmythro** [comment]
> Hmm weird, could you please try build 3.8.1 https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
> and see how it goes?

Will you release this patch to the main channel? There's still 4.8.0 to download from website, not 4.8.1.

**Comment by huyphams** [comment]
We release a new update every month, please wait for it

**Comment by huyphams** [comment]
Hi @Jiia I believe that the table was empty at first then you import some data.
TablePlus will remember the old state so you have to reset it. Please right click on the header and select > reset widths and positions.
Thanks

**Comment by Jiia** [comment]
@huyphams Ah you're correct it only happens if I've previously queried some data. Thanks for helping out!

I'm curious, why doesn't TablePlus reset the column widths automatically every time a new query is executed?

**Comment by huyphams** [comment]
> @huyphams Ah you're correct it only happens if I've previously queried some data. Thanks for helping out!
> 
> I'm curious, why doesn't TablePlus reset the column widths automatically every time a new query is executed?

Many users want to keep the size because they want to check some columns and don't want to lose track when re-running the query.

**Comment by yefengyu** [comment]
> > [@huyphams](https://github.com/huyphams) Ah you're correct it only happens if I've previously queried some data. Thanks for helping out!
> > I'm curious, why doesn't TablePlus reset the column widths automatically every time a new query is executed?
> 
> Many users want to keep the size because they want to check some columns and don't want to lose track when re-running the query.

Would it be possible to add an optional setting to auto-resize columns after each query? The current behavior (keeping manual width adjustments) could remain as default, but I'd love to have the choice to enable automatic column width adjustment.
