### ISSUE TITLE
Support for filtering using Postgres JSON operators

### ISSUE THREAD

**Issue by bengotow** [TablePlus/TablePlus#2731]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 12.11

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
428

4. The steps to reproduce this issue:
Postgres provides a handful of special operators for checking JSON set membership and containment. (https://www.postgresql.org/docs/9.5/functions-json.html Table 9-41). These are different from "contains" because they leverage GIN indexes and can perform specific types of checks extremely fast.

- "Find me rows where this JSON array contains this value"
- "Find me rows where this JSON matches this sub-object"

It'd be really nice if the most popular / straightforward of these operators were included in this dropdown. Specifically `?` ("Does the string exist as a top-level key") and `@>` ("Does the left JSON value contain the right JSON"). Would save our team writing these queries by hand!

<img width="258" alt="image" src="https://user-images.githubusercontent.com/1037212/177583194-0d61bac9-0347-4937-ac18-65a83099aaae.png">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Great idea @bengotow thank you.

**Comment by huyphams** [comment]
Hi @bengotow if you have a chance, please try this patch: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0 
it should support jsonb contains operator.

**Comment by bengotow** [comment]
Ahh this is great, thanks @huyphams - the new build works great! It looks like it updates the behavior of both Contains and "Contains (case insensitive)" which is awesome! Thanks for the quick turnaround 🙌 

If it's not too hard, it might be nice to change the labels in the dropdown when the  `@>` behavior is enabled (to "JSON Contains (@>)" maybe?) Just worried that if someone didn't know this behavior was changed and expected "LIKE", they might be confused because it requires that you type a valid JSON subset instead of any random string.
