### ISSUE TITLE
Don't limit filename extensions

### ISSUE THREAD

**Issue by Robert-M-Muench** [TablePlus/TablePlus#2734]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/1826391/178141980-8f37a844-2f9a-49f7-a2bf-b9ea2ba9482c.png">

It just doesn't make a lot of sense to limit this. Let me open the files I want...

**Comment by huyphams** [comment]
Hi @Robert-M-Muench please do not remove our issue questions template...

**Comment by Robert-M-Muench** [comment]
Well, this is a super-simple general issue. Nothing very specific.

**Comment by huyphams** [comment]
There are many ways to open the file in the macOS app so I don't even know where/how you open the file. And the reason we want to keep the issue questions is that when a feature is implemented, we will come back and close the issue or tell the user to update to the version that has support those features (Some users with an old build may report the same issue).

**Comment by huyphams** [comment]
The limitation has been removed in the latest release. Thanks for reporting!
