### ISSUE TITLE
macOS dmg is broken

### ISSUE THREAD

**Issue by moaazsidat** [TablePlus/TablePlus#2741]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

On macOS Big Sur Version 11.5.2, trying to open the dmg file gives this error
<img width="258" alt="Screen Shot 2022-07-15 at 8 27 19 PM" src="https://user-images.githubusercontent.com/5963656/179287875-da72031a-cb5d-4a21-9639-3962966add62.png">

**Comment by huyphams** [comment]
Hi @moaazsidat could you please try to download it again, I think it is a network issue. If it was a dmg issue, it would be reported everywhere now.
