### ISSUE TITLE
TablePlus on ubuntu 18.04 did not show the database tables after connect

### ISSUE THREAD

**Issue by QuocThi** [TablePlus/TablePlus#2742]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 12.11
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 186
3. The steps to reproduce this issue:
I created a connection to the postgres12 container as bellow snapshot:
![image](https://user-images.githubusercontent.com/30611784/179416459-b0310926-a784-473f-bad9-dc69060c94ca.png)
After that I could connect to the database but there are table of my database showed, there are many tables showed but none of them are mine:
![image](https://user-images.githubusercontent.com/30611784/179416438-81e44adf-12b6-4a03-81e7-4c05f07dc115.png)
From the container, I can list the database table:
![image](https://user-images.githubusercontent.com/30611784/179416566-6df5dfdb-cc68-4f53-838b-a5d9fb2cadc5.png)

Please help me resolve this issue!
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
You can change the schema at the bottom left to see the tables.
Please report issues for Linux here: https://github.com/tableplus/tableplus-linux/issues
This repo is the macOS repo.
Thanks.
