### ISSUE TITLE
[FEATURE REQUEST] - give the login window an app title

### ISSUE THREAD

**Issue by robbykotulla** [TablePlus/TablePlus#2743]
### Explanation
On Windows I use Keepass to manage my passwords. Keepass offers the possibility to write the password via AutoType into a target window, but needs a reference for this. (eg. an app title)
https://keepass.info/help/base/autotype.html

### Feature Request
If the login window would offer an app title, I could reference it in Keepass and write my strong password via AutoType for authentication.

**Comment by huyphams** [comment]
Hi @robbykotulla please post the Windows issue/feature request here: https://github.com/tableplus/tableplus-windows/issues Please do not ignore issue template questions.
Thanks
