### ISSUE TITLE
Feature request: Add Search field to Backup/Restore database modal

### ISSUE THREAD

**Issue by jtomek** [TablePlus/TablePlus#2745]
We have a multi-tenant SaaS. Each tenant has a database. 

We find ourselves backing up / restoring databases quite often. 

In TablePlus, it's unfortunately not possible to find a database in the backup/restore lists by just pasting a tenant id. We need to scroll and search through the list to find what we are looking for. Would it be, please, possible to add an input field to filter database names?? It would save much of our mental overhead during this activity.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/3748234/179963643-29896b15-29db-4ec5-872e-ccffe09d3fba.png">

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL, REDIS, SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 4.8.0 (432)

3. The steps to reproduce this issue: Not an issue

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I see, we will add a search field there.
Thanks for the suggestion.

**Comment by huyphams** [comment]
Hi @jtomek if you have a chance, please download this build, it has a search field: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you have any issue with it.

**Comment by jtomek** [comment]
Hello @huyphams I see you pushed it to the main build as well. Thank you!

One small remark: the field is displayed in the middle of the screen on Mac M1. It's cosmetic but perhaps something for the backlog.

Thank you once again!!
<img width="955" alt="image" src="https://user-images.githubusercontent.com/3748234/180962006-12b4372b-99e6-46df-937d-c15a503084f7.png">

**Comment by huyphams** [comment]
Hi @jtomek thank you for letting me know. I just fixed this bug.
