### ISSUE TITLE
Global Privileges not being loaded on the UI

### ISSUE THREAD

**Issue by bzarzuela** [TablePlus/TablePlus#2746]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql 8.0

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 432

4. The steps to reproduce this issue: 

Create a user, assign it a global privilege for replication client. 
Restart TablePlus
View the created user, replication client privilege is unchecked.

Query log when clicking apply:
GRANT REPLICATION CLIENT ON *.* TO 'nagios'@'10.0.0.135';

FLUSH PRIVILEGES;

-- Shows the correct permission is in the user table
SELECT * FROM mysql.`user` WHERE User = 'nagios' AND Host = '10.0.0.135';

  {
    "Host": "10.0.0.135",
    "User": "nagios",
    "Select_priv": "N",
    "Insert_priv": "N",
    "Update_priv": "N",
    "Delete_priv": "N",
    "Create_priv": "N",
    "Drop_priv": "N",
    "Reload_priv": "N",
    "Shutdown_priv": "N",
    "Process_priv": "N",
    "File_priv": "N",
    "Grant_priv": "N",
    "References_priv": "N",
    "Index_priv": "N",
    "Alter_priv": "N",
    "Show_db_priv": "N",
    "Super_priv": "N",
    "Create_tmp_table_priv": "N",
    "Lock_tables_priv": "N",
    "Execute_priv": "N",
    "Repl_slave_priv": "N",
    "Repl_client_priv": "Y",
    "Create_view_priv": "N",
    "Show_view_priv": "N",
    "Create_routine_priv": "N",
    "Alter_routine_priv": "N",
    "Create_user_priv": "N",
    "Event_priv": "N",
    "Trigger_priv": "N",
    "Create_tablespace_priv": "N",
    "ssl_type": "",
    "ssl_cipher": "",
    "x509_issuer": "",
    "x509_subject": "",
    "max_questions": 0,
    "max_updates": 0,
    "max_connections": 0,
    "max_user_connections": 0,
    "plugin": "mysql_native_password",
    "authentication_string": "*C0D0A9F55B85EB0153D3CD5DBC52DC9C83B2BC51",
    "password_expired": "N",
    "password_last_changed": "2022-07-21 11:35:03",
    "password_lifetime": null,
    "account_locked": "N",
    "Create_role_priv": "N",
    "Drop_role_priv": "N",
    "Password_reuse_history": null,
    "Password_reuse_time": null,
    "Password_require_current": null,
    "User_attributes": null
  }

**Comment by huyphams** [comment]
Hi @bzarzuela if you have a chance, please try this patch it should fix the issue: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
