### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by salujaparam** [TablePlus/TablePlus#2748]
1. PostgreSQL 11.5

2. build 200

3. Write a query for any table. Sort it by any column. Click on any cell in the sorted column. It will not select correct data.

**Comment by onepom** [comment]
I'm seeing the same issue after updating to build 200. 

For example
| id | data |
| :-: | :-: |
| 1 | A |
| 2 | B |
| 3 | C |

If you sort by id (descending) and then select the cell in row 1 column 2 (C) the value that is shown is from the original query (A)
| id ▼ | data |
| :-: | :-: |
| 3 | :a: |
| 2 | B |
| 1 | A |

**Comment by huyphams** [comment]
If you have a chance, please download this path: https://www.dropbox.com/s/eqztxlh2bai0lyd/TablePlusUpdate.exe?dl=0
Please also report the issue for the windows here: https://github.com/tableplus/tableplus-windows/issues
Thank you
