### ISSUE TITLE
High CPU usage, when TablePlus is focused on the "SQL Query" tab

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#2750]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
432

3. The steps to reproduce this issue:

* connect to the MySQL database
* open 2 tabs: one has any SELECT SQL in it and another shows table data (any table)
* leave the "SQL Query" tab active
* open Activity Monitor
* notice, that TablePlus has a constant ~20% CPU load now
* switch to the TablePlus tab, which shows table content
* notice, that TablePlus CPU usage has dropped significantly

OS: macOS Mojave 10.14.6

**Comment by huyphams** [comment]
Hi @aik099 could you please check  again or tell me how big the SQL Query is? 
I could not reproduce the issue.

**Comment by aik099** [comment]
Any SQL should do. Last SQL I used, which caused 60% CPU usage was:

```
SELECT ProductId, SKU, `ProductQtySoldPast6Months`, `ProductSalesPast6Months`, `ProductQtySoldPast6Months`,
	`ProductCostsPast6Months`,
	`SupplierOrdersQtyPast6Months`,
	`ProductSalesOrderCountPast6Months`
	FROM Products
```

It's without trailing `;`. Maybe that matters.

Is where any way for me to collect more debugging info for you?

**Comment by huyphams** [comment]
I mean, how big is the text in SQL Query, how many characters in the SQL Query, not only the current SQL Query. Can you take a screenshot of the SQL Query?

**Comment by aik099** [comment]
What you how big. The above-shown SQL length is 220 bytes.

Here is the video with a very simple query below:
```sql
SELECT *
FROM `52x_Users`
```

Once I've executed it I've got 4 rows back. Here is the video (see https://www.screencast.com/t/jjhqpzyI3Cx) explaining the problem and demonstrating in the Activity Monitor, that once any query is executed and results are displayed I've got constant CPU load to just see these results. Once I've not looking at the `SQL Query` tab anymore it's all back to normal.

**Comment by mbaumbach** [comment]
Also seeing a constant CPU of around 30-40% with 4.8.0 (432). Just leaving a results window open keeps the CPU pegged. I'm on an M1 MacBook Pro with 32GB of memory running macOS 12.5. Downgrading to an older version of TablePlus and the issue goes away.

**Comment by huyphams** [comment]
Hi @mbaumbach @aik099 if you have a chance, please try this patch, it should fix the High CPU issue: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0

**Comment by huyphams** [comment]
The new build 436 has been released which includes this fix.
Thanks all.

**Comment by mbaumbach** [comment]
@huyphams Seems good to me in 436. Thanks for the quick fix!
