### ISSUE TITLE
Prettify JSON in PostgreSQL 

### ISSUE THREAD

**Issue by Ollie-Boyd** [TablePlus/TablePlus#2752]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgrSQL 13

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 186

4. The steps to reproduce this issue:

Not a bug but a feature request. When clicking on a row, the data in the row currently show on the right hand side of the screen. It would be amazing if there was an option there to prettify JSON data as I currently have to constantly copy it out to an online JSON prettifyer.

**Comment by huyphams** [comment]
Hi @Ollie-Boyd you can just hit command + return to show it in pretty mode. The right sidebar is designed to show the raw value (pretty JSON is not the raw value).
<img width="839" alt="Screen Shot 2022-07-22 at 3 21 55 PM" src="https://user-images.githubusercontent.com/3654622/180396620-f5ee1c25-d0dc-4682-a893-cf3483d61e47.png">
