### ISSUE TITLE
TablePlus displays only included columns when they are added to an index

### ISSUE THREAD

**Issue by szalaybalazs** [TablePlus/TablePlus#2754]
# TablePlus displays only included columns when they are added to an index

When creating indices containing included columns the macOS application displays only those ones under table / structure / index / column_name. Currently there is no way to inspect / edit regular columns in the index from the application if there are included columns used in the index.

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 14:0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 428

3. The steps to reproduce this issue: Create an index containing 'included' columns. CREATE INDEX tab_x_y ON tab(x) INCLUDE (y);

**Comment by huyphams** [comment]
Hi @szalaybalazs if you have a chance, please download this patch: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0 
It should show the correct index column now. However, I think TablePlus also should have a include column in the index section. We will add it later.
