### ISSUE TITLE
MSSQL collate causes connection crash

### ISSUE THREAD

**Issue by Tridie2000** [TablePlus/TablePlus#2755]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MSSQL 2019 (DBVERSION_70)

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
436

**3. The steps to reproduce this issue:**
- copy the attached SQL code
- execute the SQL code to create the sample table
- try to view the table data and watch TablePlus database connection crash

**Noted: If the bug is related to data, please attach an example SQL data.**
```
CREATE TABLE crash (
    id bigint IDENTITY (1,1) PRIMARY KEY NOT NULL,
    willCrash varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL,
);
```

**Comment by huyphams** [comment]
Hi @Tridie2000 please try to use the newer protocol, it will solve the issue.
<img width="625" alt="Screen Shot 2022-07-26 at 10 34 22 PM" src="https://user-images.githubusercontent.com/3654622/181048483-cfc409ff-8e84-45c5-bece-3a99e26de5c8.png">

**Comment by Tridie2000** [comment]
Using a newer protocol fixes the varchar issue.
