### ISSUE TITLE
Unclear where to click to reconnect when connection has been disconnected

### ISSUE THREAD

**Issue by sam-gronblom-rj** [TablePlus/TablePlus#2756]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres, but probably not relevant

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.8.0 (432)

3. The steps to reproduce this issue:

When your connection is disconnected the top "info bar" shows the following:

![image](https://user-images.githubusercontent.com/32093141/181146632-e30548e5-7219-4474-9cd9-3cfcaa595536.png)

However it's not clear exactly what to tap. Presumably you are supposed to tap on the message (or preferrably anywhere inside the "status display field"). However it seems the area that you can actually click to reconnect is almost random.

**Comment by huyphams** [comment]
Hi @sam-gronblom-rj  when the connection is disconnected, you can click the header to reconnect (in the middle), or press command + shift + R, or go to the menu Connection > Reconnect.
If the connection is disconnected in the background, the app will try to reconnect when it becomes active.

**Comment by sam-gronblom-rj** [comment]
So is there some invisible box inside of the red area you have to hit? Why doesn't a click anywhere in the red area trigger reconnect?
