### ISSUE TITLE
Feature request: Snippet/Template (preferable with hot keys)

### ISSUE THREAD

**Issue by FoxyBOA** [TablePlus/TablePlus#276]
I used to use snippets/templates with hot keys  in tools like Aqua Data Studio. It would be great to see them in TablePlus too.

E.g. 
1. Cmd+Shift+S -> "SELECT FROM | WHERE". Where | is a cursor location for quick table selection
2. Cmd+Shift+I -> "INSERT INTO | () VALUES()"

Anyway, snippets/templates (especially customizable) will be a big plus for many users of TablePlus (especially with hot keys binding :)

**Comment by huyphams** [comment]
Hey, @FoxyBOA  thanks, 
I think it's nice Idea. I will try it out and let's see how we can integrate it to TablePlus

**Comment by huyphams** [comment]
TablePlus supports key binding for favorites which could replace this feature, thanks.
