### ISSUE TITLE
Protocol mismatch on attempt to connect to MySQL 8

### ISSUE THREAD

**Issue by devjones** [TablePlus/TablePlus#2762]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.
Cannot connect to MySQL server.  I get the following error: "Protocol mismatch; server version = 11, client version = 10".

I thought this was because maybe my client TablePlus app was out of date with the latest MySQL, so I purchased a renewal and I'm still seeing the same error.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.30

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
436

3. The steps to reproduce this issue:
Attempt to connect to MySQL

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I think you have used the wrong port. It should be 3306 (not 33060).

**Comment by devjones** [comment]
You're correct. Thanks.
