### ISSUE TITLE
4.8.2 "Table Plus does not support restore feature in MySql" - this worked before the update?

### ISSUE THREAD

**Issue by janczawadzki** [TablePlus/TablePlus#2764]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7 and 8.0 - restoring to 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

4.8.2 build 436

3. The steps to reproduce this issue:

Backup database, try to restore.

Noted: If the bug is related to data, please attach an example SQL data.

Doesn't seem like it's data-related

**Comment by huyphams** [comment]
Hi, @janczawadzki please try to reselect the MySQL Version and it will work again. We've remove some old binaries.

**Comment by tobz-nz** [comment]
I'm getting this error as well - tried resetting the version to `default`, no luck.
System is the same: 436, mysql 5.7.39 & 8.0.30

**Comment by huyphams** [comment]
Hi @tobz-nz could you show me how you reset it?

**Comment by tobz-nz** [comment]
@huyphams Just with the dropdown in the connection settings.

![image](https://user-images.githubusercontent.com/443054/185292902-eb2bf148-770c-44c5-ab71-fda369a2f060.png)

**Comment by huyphams** [comment]
Hi @tobz-nz it's much simpler, please see the attachment.

<img width="764" alt="reset" src="https://user-images.githubusercontent.com/3654622/185293011-d07e532b-67e1-4d7a-a381-7aaa22ce4bb3.png">

**Comment by tobz-nz** [comment]
@huyphams Ah.. didn't even see that option. yes that worked 👍
