### ISSUE TITLE
import fail - can't log query because statement length too big

### ISSUE THREAD

**Issue by dvnschmchr** [TablePlus/TablePlus#2765]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): mysql 8.0.16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): version 4.8.2

3. The steps to reproduce this issue: import my SQL dump

The message i get:

<img width="372" alt="Screen Shot 2022-07-31 at 19 20 06" src="https://user-images.githubusercontent.com/45643901/182059999-0c7f88b5-07d5-4bc8-bdfa-4ce80430e2fe.png">

is there any way to have table plus split the import into sections?

Noted: If the bug is related to data, please attach an example SQL data.

^ i dont think i can attach my sql dump its over 200mb

**Comment by huyphams** [comment]
Hi @dvnschmchr i don't think it is a TablePlus issue because it is a single statement so it could not be splited into smaller statements.
Please try to increase the max allowed package limitation and try again.

**Comment by huyphams** [comment]
Please check if you are increasing session or global limitation

**Comment by huyphams** [comment]
Please do not spam the issue :(

**Comment by huyphams** [comment]
if you edit the config it, you must restart thr server. If you increase it via the sql you  don't have to restart the server (it will will reset when you restart because it is not saved to the file).
Please also check the variable again to make sure the limition has been changed (via SQL).
https://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size

**Comment by huyphams** [comment]
Did you check the max allowed package via sql (to make sure that the max allowed package has been increased correctly)? https://dev.mysql.com/doc/refman/8.0/en/show-variables.html

**Comment by huyphams** [comment]
You can set it via the sql as a temporary solution.
I'm closing it as it is not a TablePlus issue.
Please let me know if you still having any questions.

**Comment by huyphams** [comment]
TablePlus report that you need to increase it more than 19 millions bytes, which is 19 MB. So 1GB is more than enough.

**Comment by huyphams** [comment]
Hi @dvnschmchr could you please open TablePlus and then run this query: select @@global.max_allowed_packet as max_packages;
please post the result here, thank you!

**Comment by yogithesymbian** [comment]
> Hi @dvnschmchr could you please open TablePlus and then run this query: select @@global.max_allowed_packet as max_packages; and also: select @@max_allowed_packet as max_packages please post the result here, thank you!

```
-- 2023-01-24 12:07:23.4230 PM
show variables;

-- 2023-01-24 12:08:21.8670 PM
select @@global.max_allowed_packet as max_packages;

-- 2023-01-24 12:08:29.5730 PM
select @@max_allowed_packet as max_packages

-- 2023-01-24 12:08:49.1040 PM
-- -------------------------------------------------------------
-- TablePlus 5.2.2(479)
--
-- https://tableplus.com/
--
-- Database: db_2022
-- Generation Time: 2023-01-24 11:23:30.1680 AM
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;

-- 2023-01-24 12:08:49.3890 PM
-- Can't log this query because it's too big!
```

**Comment by yogithesymbian** [comment]
lol alr solved its just cause i collapse > table , the icon collapse are toooo little . haha
