### ISSUE TITLE
Add New Items button cut off on "Queries" tab

### ISSUE THREAD

**Issue by dmachiavello** [TablePlus/TablePlus#2768]
In any width, the "Queries" button is cut off, sometimes completely. "Items" is completely fine and never had issues.  The issue persists even after restarting the app. This started happening after the most recent update.

![Screen Shot 2022-08-01 at 3 18 44 PM](https://user-images.githubusercontent.com/1901051/182228975-1b64ef52-8b61-48c7-b1f2-626b21890d07.png)

OS: MacOS Monterey 12.4 (21F79)

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB 10.5.5 (this doesn't matter in this case, it appears UI related)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.8.2 (436)

3. The steps to reproduce this issue: Have queries in the saved queries tab

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @dmachiavello if you have a chance, please download this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0 it should fix the issue.
Thank you!

**Comment by dmachiavello** [comment]
Great! left aligning works well
