### ISSUE TITLE
Unable to parse type: Void for bool values

### ISSUE THREAD

**Issue by bojcheski** [TablePlus/TablePlus#2769]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Clickhouse 22.4.4.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.8.2 (436)

3. The steps to reproduce this issue:

When viewing a table, all bool columns have following display: 'Unable to parse type: Void'

**Comment by huyphams** [comment]
Hi @bojcheski if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
It will show Bool as an integer (as it is an integer in click house.)

**Comment by bojcheski** [comment]
Thank you @huyphams !

**Comment by StyxOfDynamite** [comment]
Is this due to be released into the latest build version?
