### ISSUE TITLE
Alphabetically ordering when clicking on a column in a sql query result

### ISSUE THREAD

**Issue by Sennahoi** [TablePlus/TablePlus#277]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
89

3. The steps to reproduce this issue:
Microsoft SQL Server 2016

- Connect to a mssql server
- Open the sql query window and execute a select that returns more that 10 entries.
- Click on an id column (long, primary key) and the sorting is 0,1,10,11,12,2,... instead of 0,1,2,...,10,12,12.

**Comment by huyphams** [comment]
It's fixed: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Thanks for the reporting 👍

**Comment by Sennahoi** [comment]
Awesome, it works. Thanks for the fast fix!
