### ISSUE TITLE
Line comment shortcut does not comment out a line that has a '--' after a valid line statement (previous comment at the end of the statement)

### ISSUE THREAD

**Issue by dmachiavello** [TablePlus/TablePlus#2775]
It's helpful to add comments to certain lines of SQL statements, especially with confusing WHERE clauses. Currently the toggle line comment command won't re-comment a line if there's already a `--`, but it will successfully uncomment the line.

---
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): None

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 4.8.2 (436)

3. The steps to reproduce this issue:

- Create a SQL line that has a terminating comment that starts with `--`. 
- Press the line Line Comment keyboard shortcut (CMD / for me)
- The line will not be commented.

---

To make things clearer, consider the following example:
```
SELECT
    *
FROM
    some_table t
WHERE
    t.status = 'Y'
    -- t.status IN ('S', 'D') -- transit states
    -- t.status IN ('X', 'E') -- terminating states
```

Using the keyboard shortcut, the line with `t.status = 'Y'` can be toggled correctly, but the next two lines can only be Untoggled.

I'm attaching a screencast of the issue. The only way to comment out the line is to manually type the `--` at the start of the line.

https://user-images.githubusercontent.com/1901051/182649286-d91f4339-fcdb-41ea-b5ce-c365a1e50446.mov

**Comment by sergeyphi** [comment]
+1 on this

commenting lines in and out is a part of my daily routine -- and not able to do that on lines with a trailing comment at the end is very annoying

**Comment by huyphams** [comment]
Hi guys, the bug has been fixed. If you have a chance, you can try this path: https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
this will be included in the next update. Please let me know if you're still seeing any issue.
