### ISSUE TITLE
Disable table listing option

### ISSUE THREAD

**Issue by semiherdogan** [TablePlus/TablePlus#2776]
Hi, 
I have ~4K tables on database and listing those tables takes a lot of time, 
is there any way to disable table listing?

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 402

3. The steps to reproduce this issue:
Open database that has more than 2000 tables.
You will see tableplus freezes for a while

**Comment by huyphams** [comment]
2000 tables are not much, could you try again with our latest release and see how it goes?
