### ISSUE TITLE
Error geometry type parsing for PolyhedralSurfaceZ

### ISSUE THREAD

**Issue by elyrank** [TablePlus/TablePlus#2779]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgreSQL 14.4 with postGIS extension

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.8.2 (436)

3. The steps to reproduce this issue:
when viewing the geom data of type `POLYHEDRALSURFACEZ` - I get in the value: 'Error geometry type parsing'

example sql: 
```
  SELECT ST_GeomFromEWKT('POLYHEDRALSURFACEZ(
((0 0 0, 0 0 1, 0 1 1, 0 1 0, 0 0 0)),
((0 0 0, 0 1 0, 1 1 0, 1 0 0, 0 0 0)),
((0 0 0, 1 0 0, 1 0 1, 0 0 1, 0 0 0)),
((1 1 0, 1 1 1, 1 0 1, 1 0 0, 1 1 0)),
((0 1 0, 0 1 1, 1 1 1, 1 1 0, 0 1 0)),
((0 0 1, 1 0 1, 1 1 1, 0 1 1, 0 0 1))
)'); 
```

**Comment by huyphams** [comment]
Hi @elyrank if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Let me know if you are still seeing the issue.

**Comment by elyrank** [comment]
Thanks for the quick response!
it is now displaying it correctly, although the preview is empty.
do you know if there is a plan to support a preview of 3D objects?
