### ISSUE TITLE
Paid user on multiple machines - User logged out and credentials not saved

### ISSUE THREAD

**Issue by RoLoTo** [TablePlus/TablePlus#278]
Driver: N/A
Build: v1.0 build 89
Steps to reproduce: Login on one machine, then login on another.  Close the connection.  Go back to the original machine, user is logged out, the login credentials are not even saved.

Consider saving the credentials and having a easy path to 're-login'.

**Comment by huyphams** [comment]
Hi @RoLoTo 
TablePlus license has the seat number, if you want to use it on multiple devices you must increase this number. (By click in account in welcome screen).

We wrote it in our FAQ and the license form:
<img width="359" alt="screen shot 2018-02-22 at 8 59 54 am" src="https://user-images.githubusercontent.com/3654622/36516032-c3ff3174-17ae-11e8-9f9d-dfa26c43854e.png">

https://tableplus.io/faq

**Comment by RoLoTo** [comment]
From the FAQ:

_You can log in to multiple computers, the number of seats of your license is the number of devices you can log in at a time. When you are out of seats, if you log in to a new device, your oldest device will be removed._

So I am logging into multiple computers, but only one at a time.  The problem is when I am logged out of one of the computers, the credentials are completely forgotten.  The system should remember them so that we can simply click 'login' instead of having to type everything in again.

**Comment by RoLoTo** [comment]
@huyphams

**Comment by huyphams** [comment]
Hi @RoLoTo I'm sorry but it's not possible. We can't make this features just because people want to use it on 2 computers but only pay for one computer.
The best solution is extending the number of seats. Currently, we discount it only $35
