### ISSUE TITLE
Not possible to filter jsonb fields with text any longer

### ISSUE THREAD

**Issue by tiago-taveira** [TablePlus/TablePlus#2781]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 13.4
3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
439

4. The steps to reproduce this issue:

Filter any jsonb field with "contains"
- Example of data in column: `{"de": "Gasaustritt aus Anlagen", "en": "Equipment gas leakage"}`
- Example of search text: `hello`

Error in screenshot 
```ERROR:  invalid input syntax for type json
LINE 1: ...LECT * FROM "public"."categories" WHERE "name" @> 'hello'::j...
^
DETAIL:  Token "hello" is invalid.
CONTEXT:  JSON data, line 1: hello
```
<img width="1080" alt="Screen Shot 2022-08-09 at 09 44 45" src="https://user-images.githubusercontent.com/72075145/183605821-4911a2cd-68bd-427c-bcf2-95bc80b96e02.png">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @tiago-taveira if you have a chance, please download this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
TablePlus now will search full text if the value is not a json.
