### ISSUE TITLE
Locations settings don't work for connections

### ISSUE THREAD

**Issue by johnpena** [TablePlus/TablePlus#2783]
**Which driver are you using and version of it (Ex: PostgreSQL 10.0):**

Multiple connections (Postgres, BigQuery)

**Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**

Version 4.8.2 (436)

**The steps to reproduce this issue:**

* Open settings, select the locations tab, and set a location for Connections. I chose an iCloud location:

![Screen Shot 2022-08-10 at 10 25 41 AM](https://user-images.githubusercontent.com/43687/183926957-51d25e3b-d8c7-470b-9912-8b027918dee1.png)

* Confirm that TablePlus saves the connection settings plist files to the chosen location:

![Screen Shot 2022-08-10 at 10 25 51 AM](https://user-images.githubusercontent.com/43687/183927159-c977e9fb-4703-4451-8808-aba3c2be027c.png)

* Restart TablePlus
* Connections no longer appear in the startup window:

![Screen Shot 2022-08-10 at 10 26 00 AM](https://user-images.githubusercontent.com/43687/183927362-cc21e6e4-2c77-4137-b8b9-4455b427c37d.png)

**Comment by johnpena** [comment]
Strangely, if i click the "Restore Default" button in the Locations settings tab, all of my locations are restore in the connections window.

**Comment by huyphams** [comment]
Hi @johnpena when you change the location, you have to import the connection again. You can right-click the connection on the desktop, and export.
Then change the location and import it again. TablePlus will not move the connection to the new location.

**Comment by johnpena** [comment]
> Then change the location and import it again. TablePlus will not move the connections to the new location.

This strikes me as a usability issue, I'd expect that if I change the location then TablePlus will move my existing connections to that location.

**Comment by huyphams** [comment]
I think it would be an option (TablePlus will show a popup and if the user checks the box, TablePlus will move it). This feature is designed for teams, so the connections should be there by default (shared by other team members), if TablePlus moves it again, it would override the existing data.

**Comment by johnpena** [comment]
Got it, didn't realize it's currently being used that way. I agree an option would be better. Should I file a feature request?

**Comment by huyphams** [comment]
Sure, we will add this option to the future releases.

**Comment by johnpena** [comment]
Great, just added the feature request. @huyphams thanks for the info and the support.
