### ISSUE TITLE
Infected with bitcoin miner?

### ISSUE THREAD

**Issue by sullerandras** [TablePlus/TablePlus#279]
Downloaded the zip file and scanned with Virustotal: https://www.virustotal.com/#/file/fe8ad23d9b7ecb2d1c2da02e6bd643e3d284342dbbe9cf892c54271c486a4cdc/detection
Two scanner detected the same trojan. False positives?

**Comment by huyphams** [comment]
Hey @sullerandras 
It's say `Contains one or more Mac OS X executables. Seems to be a Mac application placed in a compressed file.`

Yes, TablePlus contains more Mac OS X executables. because it includes pg_dump and pg_restore, mysql_dump, mysql_restore executeable. 

TablePlus support backup/restore.

**Comment by sullerandras** [comment]
Your comment seems unrelated. I'm talking about these alerts:
<img width="1107" alt="screen shot 2018-02-22 at 11 25 14 am" src="https://user-images.githubusercontent.com/394358/36518839-2017309c-17c3-11e8-812d-d55c6d60feff.png">

**Comment by huyphams** [comment]
Sorry, I thought to click on detail to show the error (but it's not). 

TablePlus didn't have any bitcoin miner (I don't see any reason why I should add a miner and public my profile as an author at the same time 😄).
 
As you see, it uses 0% CPU in idle. If there is some background task, it will increase CPU usage:

<img width="912" alt="screen shot 2018-02-22 at 10 28 44 am" src="https://user-images.githubusercontent.com/3654622/36518931-2e50d184-17bb-11e8-990f-16f577bc1a76.png">

**Comment by sullerandras** [comment]
It wasn't trying to imply that you deliberately added a bitcoin miner to your own product :)
Maybe an attacker managed to replace the zip files on s3? If you are sure that the zip files on s3 are not tampered with then it's probably a false alarm?

**Comment by huyphams** [comment]
The S3 is read-only mode and I have `dsa signature key` to make sure the zip was not modified.
Btw, I'm appreciated  that you report this to me 👍 
I always respect user policy, and the security is my first attention when making any new feature.

**Comment by huyphams** [comment]
Hey @sullerandras I found this: https://discussions.agilebits.com/discussion/86860/avg-quarantined-1password-libswiftdispatch-dylib
Hope it helps

**Comment by huyphams** [comment]
For people who come later, Avast is working to fix this false alarm 😄 
<img width="747" alt="screen shot 2018-02-22 at 6 56 02 pm" src="https://user-images.githubusercontent.com/3654622/36537272-3d10e83e-1802-11e8-96fd-db66955e6b85.png">

**Comment by sullerandras** [comment]
The build linked in #281 does not trigger any alerts on virustotal: https://www.virustotal.com/#/file/4567cf36158bf8c80de623d63c2c7f27eac945df2cde5aa51d550e19c772725b/detection
Not sure what does this prove though. Maybe the zip on s3 is really compromised?

**Comment by huyphams** [comment]
I don't think so because I'm the only one who maintains the Amazon account and all the builds were uploaded by me.
We should wait for Avast fix their error and rescan again 🤔

**Comment by huyphams** [comment]
Btw @sullerandras are you sure the system doesn't cache the result (based on SHA-256 key)? Because when I submit the old build it produces the result immediately instead of one by one?

**Comment by sullerandras** [comment]
Virustotal caches the results. You can even search for a sha256 hash to view the latest scan results without having to upload the file again.
Anyway this was clearly a false alarm, so i'm closing it.
