### ISSUE TITLE
Error connecting CockroachDB Serverless

### ISSUE THREAD

**Issue by vicary** [TablePlus/TablePlus#2790]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
CockroachDB Serverless

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
436

3. The steps to reproduce this issue:
    1. Create a serverless cluster via https://cockroachlabs.cloud/
    2. Copy the connection string
    3. Import into TablePlus
    4. Click *Test*
    5. Their connection string contains extra options `?sslmode=verify-full&options=--cluster%3D{your_cluster_id}`, but the PostgresSQL connection panel doesn't have that so it is ignored.

**Comment by jrschumacher** [comment]
See workaround https://github.com/TablePlus/TablePlus/issues/2546#issuecomment-1041251086

**Comment by vicary** [comment]
@jrschumacher Thanks, it works!

**Comment by vicary** [comment]
Closing for duplication of #2546
