### ISSUE TITLE
Feature request: Data type highlighting

### ISSUE THREAD

**Issue by quantumwebco** [TablePlus/TablePlus#2792]
It would be great to have the cells highlighted by data type e.g.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/12368817/185606453-c161f16e-93e0-4c56-8b3c-b0319ace3f58.png">

**Comment by huyphams** [comment]
Hi @quantumwebco we're working on this feature.

**Comment by huyphams** [comment]
We've added it, however I think you are using the Windows build, so please follow the Windows repo.
![CleanShot 2022-08-26 at 22 13 11@2x](https://user-images.githubusercontent.com/3654622/186937022-02f1477e-c07a-41c8-97fc-b167e0d8a912.png)

**Comment by quantumwebco** [comment]
@huyphams Amazing! I've been waiting for this!! Thanks so much
