### ISSUE TITLE
Item list empty using MSSQL

### ISSUE THREAD

**Issue by zainspresso** [TablePlus/TablePlus#2793]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Azure (RTM)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
436

3. The steps to reproduce this issue:

The "item" list is completely empty but there are tables available. I can see al my tables if I run: 
SELECT * FROM INFORMATION_SCHEMA.TABLES;

**Comment by huyphams** [comment]
Could you show me a screenshot of the workspace @zainspresso

**Comment by zainspresso** [comment]
Sorry for my late response, hereby @huyphams 
<img width="1337" alt="Screenshot 2022-08-23 at 22 43 49" src="https://user-images.githubusercontent.com/24475693/186261923-cae42749-d38a-47eb-a8d3-db9e3c54a961.png">

**Comment by zainspresso** [comment]
Never mind, I see now that there is a selector at the bottom to switch. Sorry ;)
