### ISSUE TITLE
Action Controls Toolbar Item isn't wide enough for High Contrast Mode

### ISSUE THREAD

**Issue by devtimi** [TablePlus/TablePlus#2797]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A this is a UI problem.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 436

3. The steps to reproduce this issue: Turn on high contrast mode, look at toolbar.

Noted: If the bug is related to data, please attach an example SQL data.

Screenshot attached. Action Controls group is too small for the border in high contrast mode. This applies to both the actual toolbar and the customize toolbar view.

<img width="146" alt="Screen Shot 2022-08-23 at 12 47 30" src="https://user-images.githubusercontent.com/2067469/186215994-ad328948-4cfe-4ba6-8d95-fa664f1f2fef.png">

**Comment by huyphams** [comment]
Hi @devtimi if you have a chance, please try this build: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0 
Please let me know if you're still seeing the issue.

**Comment by devtimi** [comment]
Thanks for the new build, the button set looks correct now :)

<img width="133" alt="Screen Shot 2022-08-25 at 11 36 30" src="https://user-images.githubusercontent.com/2067469/186708943-0908d081-1a30-4563-b043-5a572026b1df.png">

**Comment by huyphams** [comment]
Thank you for confirming, please let me know if you find any other UI issues.
