### ISSUE TITLE
When executing a large query, we need to be able to "Stop Query" if it's taking too long.

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#28]
See details in below image, would like a "Stop Query" button if possible.

![2017-07-31 14_25_18](https://user-images.githubusercontent.com/7946786/28799113-171ba8ce-75fc-11e7-96b7-e2f46889938e.gif)

**Comment by huyphams** [comment]
I'm working on Stop query feature and optimize query process.
