### ISSUE TITLE
UI freezes after a long query execution

### ISSUE THREAD

**Issue by Sennahoi** [TablePlus/TablePlus#280]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL Azure
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
89
3. The steps to reproduce this issue:
- Connect to an Azure MSSQL instance
- Execute some query like select * from someTableName
- Wait a minute or more and see the UI freezing even after the query returned

The table I used contains about 7000 rows and sp_spaceused 'data_file' returns 313544 KB of data.

**Comment by huyphams** [comment]
Sorry, build 96 didn't include the streaming for SQL Server.
You can try this build, it's return data immediately after executing the query:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by Sennahoi** [comment]
Yes, that works. Great.
