### ISSUE TITLE
Can't connect to SingleStore DB anymore (paid licence here)

### ISSUE THREAD

**Issue by pierre-b** [TablePlus/TablePlus#2804]
Hello, I recently bought a licence of TablePlus but a recent update of the SingleStore Cloud DB **removed support for TLS1.1** and TablePlus cannot connect to SingleStore anymore.

SingleStore uses the "old MySQL" protocol, which is using TLS1.1 in TablePlus.

Could you please upgrade the "Old MySQL" protocol to use TLS1.2 or let us choose which TLS version to use?

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Old MySQL

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
4.8.2 (436)

5. The steps to reproduce this issue:
- create a managed cluster in SingleStore Cloud
- configure TablePlus to connect to SingleStore using SSL
- error is : `Access denied for user 'user'@'xxx.xxx.xxx.xxx' (using password: YES). TLS version tlsv1.1 is not in the list of allowed versions tlsv1.2 specified by the tls_version system variable.`

Thanks for your help

**Comment by huyphams** [comment]
Hi @pierre-b please choose this option back to default.
<img width="474" alt="CleanShot 2022-09-06 at 22 27 54@2x" src="https://user-images.githubusercontent.com/3654622/188675081-0e82bbb4-fd16-446c-94e0-3e044517128c.png">

**Comment by pierre-b** [comment]
The SingleStore DB doesn't "talk" the new MySQL protocol unfortunately...

**Comment by huyphams** [comment]
Hi @pierre-b could you please try again with MariaDB driver (instead of MySQL Old Driver)? MariaDB driver should support  TLS 1.2

**Comment by huyphams** [comment]
Please choose the SSL mode ENFORCE or VERIFY
<img width="456" alt="CleanShot 2022-09-06 at 23 30 23@2x" src="https://user-images.githubusercontent.com/3654622/188688172-7cd58742-9de0-4f8b-a54b-44e286bcfac7.png">

**Comment by pierre-b** [comment]
Thank you @huyphams for the trick, it works!

**Comment by huyphams** [comment]
We also added the SingleStore in the MySQL connection form.

<img width="494" alt="CleanShot 2022-09-07 at 11 09 09@2x" src="https://user-images.githubusercontent.com/3654622/188786814-c10a87d4-b9f7-410f-86b2-1b347b8b3a63.png">

**Comment by pierre-b** [comment]
Awesome! Thanks for you fast answers
