### ISSUE TITLE
MySQL Mac Only executes last query over and over.

### ISSUE THREAD

**Issue by dRoss** [TablePlus/TablePlus#2808]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.26

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Mac build 448

4. The steps to reproduce this issue:
Paste multiple update queries in the SQL text editor view. Seems to only happen when there are hundreds of queries or more.
Press "Run All"
If there are 12,097 queries, it shows "Query 12097 OK: 0 rows affected" over and over.
(see attached screenshot)

<img width="483" alt="Screen Shot 2022-09-13 at 2 04 36 PM" src="https://user-images.githubusercontent.com/452127/189989672-f3d9e5fa-b14f-418f-b6ca-cb03d0084369.png">

**Comment by huyphams** [comment]
Hi @dRoss thank you for letting me know. If you have a chance please download this patch https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
it should fix the issue.
