### ISSUE TITLE
Attempting to delete a stored procedure on Postgres fails

### ISSUE THREAD

**Issue by RoLoTo** [TablePlus/TablePlus#281]
1. PostgreSQL 9.6.1

2. Build 89

3. Try to delete any stored procedure.

_"ERROR:  syntax error at or near ";"
LINE 1: DROP FUNCTION "public"."zzz";
                                         ^

All DML changes were reverted"_

**Comment by huyphams** [comment]
It's fixed in this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Thanks for the reporting 👍
