### ISSUE TITLE
Large insert or update script results in wrong data changes

### ISSUE THREAD

**Issue by eitalouarruda** [TablePlus/TablePlus#2810]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 10.5 and 14 | MySQL 5.7 and 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 449 (Setapp License) 

3. The steps to reproduce this issue: Execute a script for change data in batch or insert data in batch, with 50 lines or more (with semicolon separator), it will execute the just the first line of the script, but multiple times, to be more specific the same amount of times you have in lines count in the script.

(300 "insert into" with diferente data per line will just execute the first line 300 times)
I try it on Postgres and MySQL in multiples versions for each one.

Noted: If the bug is related to data, please attach an example SQL data. Sending a script to replicate a table that I have on mySQL and the exact script that a run last time. The result is on the attached image

[scripts.zip](https://github.com/TablePlus/TablePlus/files/9569205/scripts.zip)
![image](https://user-images.githubusercontent.com/8331926/190243592-cf7306f3-7a41-4bc8-997a-84220ea52966.png)

**Comment by huyphams** [comment]
Hi @eitalouarruda  thank you for letting me know. If you have a chance please download this patch https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
it should fix the issue.

**Comment by eitalouarruda** [comment]
Thank you so much, it definitely works and I see it's already on setApp too thank you. =D
