### ISSUE TITLE
Context-Menu "Generate UUID" action always generates the same UUID.

### ISSUE THREAD

**Issue by christoph-kluge** [TablePlus/TablePlus#2814]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL but I guess it's irrelevant here.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 4.8.8 (450)

3. The steps to reproduce this issue:

Add multple rows. Choose a random field. Click "Generate UUID" from context menu. Repeat. See that you have generated the same UUID.

<img width="617" alt="Screenshot 2022-09-19 at 15 19 08" src="https://user-images.githubusercontent.com/1446269/191026608-9e4aec9d-f645-466d-a512-ab6c1ec48385.png">

**Comment by huyphams** [comment]
thanks @christoph-kluge the bug is fixed. Please wait for the next update!
