### ISSUE TITLE
Feature request: Ability to disable functions display

### ISSUE THREAD

**Issue by mark-b-ab** [TablePlus/TablePlus#2815]
Hello, 
on our project we are using SingleStore database and one of its features is ability to use WASM binaries as procedures.
The problem that we are facing with that size of each binary is couple of Megabytes.

TablePlus executes the following query to get all function definitions.
```
SELECT
	ROUTINE_SCHEMA AS function_schema,
	ROUTINE_NAME AS function_name,
	ROUTINE_DEFINITION AS create_statement,
	ROUTINE_TYPE AS function_type
FROM
	information_schema.routines
WHERE
	ROUTINE_SCHEMA = 'table';
```
On our DB it takes around 20mins to execute this function, because DB goes to S3 to download all binaries.
This results in 20min delay to just connect to db and start using it, also in around ~200Mb of data (unusable on mobile data).

Is it possible to add some toggle not to load functions at all or at least its definition (this field contains binary)?

**Comment by huyphams** [comment]
Hi @mark-b-ab please check out this settings.
<img width="468" alt="CleanShot 2022-09-21 at 14 46 08@2x" src="https://user-images.githubusercontent.com/3654622/191445812-bb4ecd19-b700-40be-8c1d-d41b90e5e97e.png">

**Comment by mark-b-ab** [comment]
It helped! Thanks a lot!
