### ISSUE TITLE
MacOs - ui/ux bug

### ISSUE THREAD

**Issue by aqjw** [TablePlus/TablePlus#2819]
Build 450

<img width="668" alt="Screenshot 2022-09-26 at 23 58 18" src="https://user-images.githubusercontent.com/13101908/192379163-a7e3b9c3-a4dc-4ab3-8e93-4a9235e4df34.png">

<img width="542" alt="Screenshot 2022-09-26 at 23 58 24" src="https://user-images.githubusercontent.com/13101908/192379178-95f8ca55-fad3-4229-9297-02b749b8fda1.png">

**Comment by huyphams** [comment]
Duplicate:
https://github.com/TablePlus/TablePlus/issues/2813
https://github.com/TablePlus/TablePlus/issues/2545

Reason: 
- Currently, we don't find any good solution for it. If we make the constraint to prevent it happens, it would not let the user resize the right sidebar bigger, which we think is more important than a minor UI issue.
