### ISSUE TITLE
I cannot stand the new filter dropdowns

### ISSUE THREAD

**Issue by clakeb** [TablePlus/TablePlus#282]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.*
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 89, macOS
3. The steps to reproduce this issue:
update TablePlus

The new filter drop downs when viewing a table are painful for me because they slow me down. Instead of me just writing my `WHERE` statements quickly I have to choose something each step of the way. A simple `id = 687` takes longer to select now. I don't like them in Sequel Pro either. I did like them when I was a beginner because they helped me learn syntax. But now they are just slow. Could you make the new filter system optional? I do like that the filter was moved to the top. I think it should be on by default as well instead of turning it on at the bottom of the view.

**Comment by huyphams** [comment]
Hi @clakeb please upgrade to build 90 and it will solve your issue 😄
