### ISSUE TITLE
[Feature Request] Confirm Table Name(s) when Selecting Truncate.

### ISSUE THREAD

**Issue by gilmouad** [TablePlus/TablePlus#2821]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Maria DB 10.3.28

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 446

3. The steps to reproduce this issue: Click on a table, right click, select Truncate. The dialog that appears first of all has Truncate tables (plural) when I only selected one table. It also does not refer to the table or tables in question. I appreciate they will then be highlighted yellow for the changes to be committed, but getting the right information in advance would ease concerns.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, I just improved the Truncate/Delete table popup, now it will show the table name if you delete/truncate a single table!
Please wait for the next update.
