### ISSUE TITLE
Vert alignment issue of sidebar and SQL w/large font sizes/height

### ISSUE THREAD

**Issue by edrozenberg** [TablePlus/TablePlus#2827]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 14.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.8.8 (450)

3. The steps to reproduce this issue:
In app prefs, set sidebar font to a large value, set SQL line height to a larger value

Noted: If the bug is related to data, please attach an example SQL data.

In sidebar, the little blue DB icon and the text are not aligned. This becomes easily visible at larger font sizes:

<img width="473" alt="Sidebar alignment" src="https://user-images.githubusercontent.com/2648417/193506333-3824f5a6-580e-4fe5-b1a0-e0b414b3b506.png">

In SQL editor, the line numbers do not align with the contents when using larger >1 line height values, easily visible for larger line height values:

<img width="622" alt="Line Height Alignment" src="https://user-images.githubusercontent.com/2648417/193506421-33ae0133-fe28-4f52-8263-b83809edc10e.png">

**Comment by huyphams** [comment]
thank you for reporting the issue, if you have a chance, please try this hot patch and see how it goes: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0

**Comment by edrozenberg** [comment]
Tested with Version 5.3.8 (500) and problem appears fixed. Thank you very much.
