### ISSUE TITLE
Add other SingleStore options

### ISSUE THREAD

**Issue by heychazza** [TablePlus/TablePlus#2832]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SingleStore DB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 454

3. Information:
I see you recently added the SingleStore DB option, thanks for that! Is there any chance with this we can see auto completion options in the SQL panel?

E.g. [TIME_BUCKET](https://docs.singlestore.com/managed-service/en/reference/sql-reference/time-series-functions/time_bucket.html)

It would be an awesome addition and I'm sure would help many.

**Comment by JackEllis** [comment]
This would be awesome.

**Comment by huyphams** [comment]
Thank you, I just added it.
