### ISSUE TITLE
Table Plus keeps quitting randomly. 

### ISSUE THREAD

**Issue by SamGoldbergNYRB** [TablePlus/TablePlus#2835]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Are you using TablePlus old build @SamGoldbergNYRB I don't see any details in your issue report.

**Comment by SamGoldbergNYRB** [comment]
Which driver are you using and version of it (Ex: PostgreSQL 10.0):

/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

454

**Comment by huyphams** [comment]
Do you have the step to reproduce the issue @SamGoldbergNYRB I could not reproduce it.

**Comment by SamGoldbergNYRB** [comment]
There is no steps really. Table Plus is open and then it quits.

**Comment by huyphams** [comment]
Hi @SamGoldbergNYRB if you have a chance, please download this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue.
Thanks

**Comment by SamGoldbergNYRB** [comment]
Hi - the patch did not work.

**Comment by huyphams** [comment]
Hi @SamGoldbergNYRB could you please try this patch and see how it goes: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Thanks!

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue. Thanks
