### ISSUE TITLE
[Feature Request] - Add option for line wrapping in sql editor.

### ISSUE THREAD

**Issue by davidemerritt** [TablePlus/TablePlus#2836]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- mysql + snowflake

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- Version 5.0.0 (454)

5. The steps to reproduce this issue:
- For long insert or select statements, it would be nice to control line wrapping in the editor. Long statements, especially if there are several become very hard to read/look through. This would be a great QoL improvement. Thanks!

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's supported now. If you have a chance, you could try this build:

https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0

<img width="530" alt="CleanShot 2022-10-09 at 11 17 41@2x" src="https://user-images.githubusercontent.com/3654622/194737751-bdc28863-9e69-4dd5-a4af-f9069f057f3b.png">
