### ISSUE TITLE
The settings are not saved

### ISSUE THREAD

**Issue by cuonghuynh** [TablePlus/TablePlus#2840]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 454

4. The steps to reproduce this issue: The settings at the right bottom that is not saved, I have to config it every open application. Could we keep it for next using?

**Comment by huyphams** [comment]
I'm not sure that I understand you correctly. What are the settings at the right bottom? Do you mean the paging limitation?

**Comment by cuonghuynh** [comment]
I mean this one, there are some options to show recently section,... the changes are not saved
![image](https://user-images.githubusercontent.com/3349033/195491558-589d5955-2c8a-4116-9020-26af8b0c5839.png)

**Comment by huyphams** [comment]
It's per-connection settings. Could you show me the step to reproduce the issue please?

**Comment by cuonghuynh** [comment]
I misunderstood it. I expected that should be saved for all connections.
