### ISSUE TITLE
List items and table hidden in database 

### ISSUE THREAD

**Issue by WCU12345** [TablePlus/TablePlus#2842]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 206

3. The steps to reproduce this issue: I opened TablePlus and usually the item list pops up and I can open one of our databases but I opened it today and the screen was completely blank (picture attached). I can run a query (picture attached) and the table appears in the editor but I cannot open the database to run searches like I need to. When I click "show database list" I get a warning that says "this feature is not available for this driver" but this has ever been an issue before. Help please! 

![table plus query](https://user-images.githubusercontent.com/115717263/195613768-73592fc0-ea47-4b4c-a6d3-9bc68aa08e24.png)

![table plus blank](https://user-images.githubusercontent.com/115717263/195613757-63cbc398-ddf5-4809-9059-8a3f475bb63b.png)

**Comment by huyphams** [comment]
Hi @WCU12345 please click the top right buttons to toggle the panes.

**Comment by WCU12345** [comment]
I am a moron and I needed to toggle the panes...
