### ISSUE TITLE
row number corruption in sql query tab results 

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#2844]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 14.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 450

3. The steps to reproduce this issue:

- go to SQL Query panel
- make any query with results
- scroll with mouse wheel

i am attaching a video:

https://user-images.githubusercontent.com/3632883/195625619-71565974-446d-46f9-977b-bec2dd6aa483.mov

**Comment by huyphams** [comment]
Interesting, it only happens when we use the scroller on Mouse (works with trackpad).

**Comment by minusf** [comment]
true: the numbers are present more reliably, however having a number scroll up next to the column name is confusing for me

**Comment by huyphams** [comment]
If you have a chance, please download this patch: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0 
Please let me know if you still seeing the issue.

**Comment by minusf** [comment]
i can't reproduce the issue so easily anymore, but the scrolling is very flickery, and sometimes when the scrolling stops, the last 3-4 lines have empty line numbers.
