### ISSUE TITLE
Bug - Error running query with parameters when new lines contain carriage return

### ISSUE THREAD

**Issue by yanivps** [TablePlus/TablePlus#2850]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 14.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
5.0.2 (459)

3. The steps to reproduce this issue:
I have two queries which seems to look the same.

The first one executes without any problem :)

![image](https://user-images.githubusercontent.com/3877730/196042665-25e248eb-684c-43ab-89b4-d164369e291f.png)

The second one yields this error:
![image](https://user-images.githubusercontent.com/3877730/196042736-2b45856d-524e-4b2d-b196-f7b6e94a0a16.png)

Strange right?!

So I've investigated and found that the difference between the two queries is that the first one which works, has a single new line (`\n` char denoted by `0a` in the photo) after the word `posts` 

while the second one which does not work has a carriage return (`\r` char denoted by `0d` in the photo) followed by a new line (`\n` char denoted by `0a` in the photo) after the word `posts`

![image](https://user-images.githubusercontent.com/3877730/196043055-cffd4979-ec91-4516-bfac-1430484656a1.png)

This probably happens when I copy query from a different text editor which uses carriage return for new lines

Can this please be fixed that both `\r\n` and `\n` will work?

Thanks

**Comment by huyphams** [comment]
Hi @yanivps can you send me the txt file? I could not reproduce the issue.
Thank you!

**Comment by yanivps** [comment]
Hi @huyphams 
Here it is: https://file.io/YB2SkKKctteK
Please let me know if anything else is needed

**Comment by huyphams** [comment]
Hi @yanivps could you upload that file to this issue please
<img width="344" alt="CleanShot 2022-10-23 at 07 52 50@2x" src="https://user-images.githubusercontent.com/3654622/197367984-50430a9c-cd6c-400d-a840-7a6241cb1ea5.png">

**Comment by yanivps** [comment]
@huyphams  Yes sorry about that I didn't know I can upload files directly to issues 😅
Thanks
[params_error.sql.zip](https://github.com/TablePlus/TablePlus/files/9846474/params_error.sql.zip)

**Comment by huyphams** [comment]
Hi, thanks for the file. we've fixed the bug, you can download the hotpatch here: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Thanks!
