### ISSUE TITLE
Security flaw - Passcode lock doesn't prevent a malicious user from connecting to your Database

### ISSUE THREAD

**Issue by whambulance** [TablePlus/TablePlus#2851]
1. Which driver are you using and version of it:
Any

2. Which TablePlus build number are you using:
Build 432 - MacOS version

3. The steps to reproduce this issue:

- [ ] Setup the Passcode lock in the General prefences
- [ ] Wait for the application to lock itself, until it looks as such:

![image](https://user-images.githubusercontent.com/42666312/196143588-8bff0ade-45d9-4bcb-970e-2ed69d3b05ce.png)

- [ ] Right click somewhere around the center, and you're able to click through this visible "Enter Passcode" layer, to reach the UI behind it.

![image](https://user-images.githubusercontent.com/42666312/196143548-e9c3c586-dd06-4c91-9788-39a86bbedb02.png)

- [ ] Click on "Connect" to connect to a database

Because the passcode view doesn't prevent you from clicking on the layer underneath it, currently it isn't doing anything to prevent malicious users from accessing your saved database connections.

**Comment by huyphams** [comment]
We fixed it, thanks for letting me know.
