### ISSUE TITLE
Metrics X axis information unreadable

### ISSUE THREAD

**Issue by Bynsu** [TablePlus/TablePlus#2853]
MariaDB 10.5.9, Build 210, Windows 10 x64

1. If you use datetime type value (or any other visually long value) for X axis, the values at the bottom will become unreadable because they overwrite each other. Zooming doesn't help for really long charts (example, chart for 10 years with a step of 1 week) and actually I don't want to zoom every time to see the date. A good solution would be to implement a possibility for vertical orientation of X axis value at the bottom. A second good solution would be to show the X and Y axis values in the tooltip when I hover over the bar/dot (for bar and line charts respectively).

2. Please make it possible to duplicate charts and move them from one metrics entry to another.

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this patch, it support x-axis rotation now.
https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0
Duplicate/move should be a different issue.

**Comment by huyphams** [comment]
<img width="1246" alt="Screenshot 2023-02-22 at 10 36 58 PM" src="https://user-images.githubusercontent.com/3654622/220675259-88b14c71-7d3b-4e77-95ce-bed30e90243d.png">
