### ISSUE TITLE
Small: a typo in "Your license was expired" modal ("licenese" should be "license")

### ISSUE THREAD

**Issue by wzulfikar** [TablePlus/TablePlus#2854]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

**Small**: A typo in "Your license was expired" modal. Should be "license" instead of "licenese".

<img width=400 src=https://user-images.githubusercontent.com/7823011/197405068-24faedf3-39b0-4202-8bb2-df31509c867d.png />

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
  → (use any driver)
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
  → **Build 458** (if it's any difference, I installed TablePlus using `brew install tableplus`)
3. The steps to reproduce this issue:
    1. Click "Register license" in TablePlus menu
    2. Add a valid license
    3. Click "Activate"
    4. See the typo

Preview:

https://user-images.githubusercontent.com/7823011/197405181-05a057d1-3c89-4f44-8ce0-ff001e835de9.mp4

**Comment by huyphams** [comment]
Thank you for letting me know. I fixed it!
