### ISSUE TITLE
BigQuery: Tables does not show all tables

### ISSUE THREAD

**Issue by yoshiokatsuneo** [TablePlus/TablePlus#2865]
I have around 600 tables on BigTable dataset.
But, TablePlus only shows around 320 tables(on Items tab), and does not show other tables.

**Comment by yoshiokatsuneo** [comment]
@huyphams Yes, I'm using TablePlus Version 5.1.0 (468) on macOS Ventura.

**Comment by yesokay** [comment]
+1 on this: Tables only show 300 of tables for me out of 775 on both latest stable and build 475.

**Comment by loris** [comment]
It also shows a very low number of Datasets (~50), but we have hundreds actually

**Comment by huyphams** [comment]
Hi guys, if you have a chance, please try this patch https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0

**Comment by DaThresh** [comment]
Any movement on this issue? I'm running into the issue that @loris pointed out - when using BQ, the dataset list only shows 50 results.

Currently using TablePlus Version 5.6.8 (524) on macOS Monterey

**Comment by huyphams** [comment]
Hi @DaThresh it only show 50 tables or 50 databases?

**Comment by DaThresh** [comment]
@huyphams 50 datasets (databases)

**Comment by huyphams** [comment]
Hi @DaThresh you may want to try this patch: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0 

It should fix the issue, let me know if you're still seeing the bugs.
