### ISSUE TITLE
PostgreSQL quick filter 't' != true

### ISSUE THREAD

**Issue by hyperknot** [TablePlus/TablePlus#2868]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

This is a super long standing bug, very basic and I'm honestly surprised it's still present, knowing the generally very high quality of the software. In PostgreSQL the Quick filter turns boolean values into t/f, instead of true/false, which doesn't work. It should be written true / false instead.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 12

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
468

4. The steps to reproduce this issue:
Right click on any boolean value in the Data screen, and select: Quick filter / ... = 't'

This won't work, as it needs to be "true". Every time I do this I have to manually go to the filters at the top and change 't' into true. Then it'll work.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Actually, it will but it needs to be quoted correctly. The boolean PostgreSQLreturn is is f and t (not true and false). Let me update the syntax.

**Comment by huyphams** [comment]
If you have a chance, you can try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Thank you!

**Comment by hyperknot** [comment]
It works perfectly thank you!
