### ISSUE TITLE
mongoDB collections not displaying on iPad

### ISSUE THREAD

**Issue by Kerolo** [TablePlus/TablePlus#2869]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
**Mongo 4.2.23**
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  
**5.1.0(Build 392)**
3. The steps to reproduce this issue:
- **Run connection without SSH Tunnel**
- **Select database**
- **No collections appear (Actually it appeared once)**
![cf42d7b989cacc7fb963f5847b38ac9](https://user-images.githubusercontent.com/22723769/199753980-96072c63-c070-4060-b94d-8e3f5643449b.jpg)

Similar to this [issue#1867](https://github.com/TablePlus/TablePlus/issues/1867)

**Comment by huyphams** [comment]
Hi @Kerolo please click the "schemas" and select an object.

**Comment by Kerolo** [comment]
> 

yeah i have selected an a database and nothing appear in "items"

**Comment by Kerolo** [comment]
After i clicked the green bar and chose "Reconnect", then the collections displaying...
it works now, but it's perfect if this problem would be fixed. @huyphams
