### ISSUE TITLE
[Feature Request] MAC App Store Version

### ISSUE THREAD

**Issue by aescolastico** [TablePlus/TablePlus#2872]
Is there any interest in providing a M.A.S. distribution of tableplus?

**Comment by huyphams** [comment]
We don't have any plan for it.

**Comment by aescolastico** [comment]
Do you mind elaborating on why not?

**Comment by huyphams** [comment]
The appstore requires the app sandbox so many TablePlus features will not work. Apple also cuts 30% of revenue and the pricing model is not fit with our requirements....
