### ISSUE TITLE
[license issue] key is expired

### ISSUE THREAD

**Issue by yunshuaipeng** [TablePlus/TablePlus#2875]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
msyql 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
iso: build 394
3. The steps to reproduce this issue:
 - download app from App Store.
 - open app and click 'Unlock' then input my desktop key.

Hi, I bought the desktop license last year. I think it is expired. But I want to know how to download old ios version, then let me use my old key to unlock ios app.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/44765369/200498452-fcbc543d-3b94-44fb-9af8-3c782c798c68.png">

**Comment by tittitoo** [comment]
I purchased the license in June 2024 and now it has expired and I do not intend to renew. iOS app now is coming as license expired and when I try to activate it with desktop key, I have got key is expired message. What would be the way to resolve this? Although I am no longer subscribing to updates, the app is supposed to be free forever. I am OK if I can install the older app version.

**Comment by nelldnine** [comment]
I have the same issue. I thought it was free to use forever just without the updates.

iOS 26.3.1
