### ISSUE TITLE
[Redis Manager Bug] Don't run auth command when connected automatically

### ISSUE THREAD

**Issue by tiyee** [TablePlus/TablePlus#2879]
As title said, I set Redis username and password on Connection Settings, but the password is ineffective。

1. TablePlus Version 5.1.0 (468), MacOS 13.0.1 (22A400), redis-5.0 

![auth](https://user-images.githubusercontent.com/2190710/201275590-8d560391-7e7c-4bbe-ae42-87fa4fdccf1c.jpg)

**Comment by huyphams** [comment]
I think the op entered a wrong password

**Comment by overbit** [comment]
@huyphams I can confirm that at least in my case, the credentials are correct and working with redisinsight and other solution. 
Moreover, I would expect an error like `WRONG PASSWORD`.

**Comment by huyphams** [comment]
Hi @overbit if yu have a chance, pleaee ty this patch it will show error when entering wrong password https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
