### ISSUE TITLE
[BUG] TablePlus Crashes when mac wakes from sleep mode [macOS Monterey]

### ISSUE THREAD

**Issue by crydotsnake** [TablePlus/TablePlus#2883]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 468

2. The steps to reproduce this issue:
- Open a Database in TablePlus (One or two connections)
- Put your Mac in Sleep Mode
- Wait half an hour (or longer), and then turn on the mac again.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue. Thanks

**Comment by crydotsnake** [comment]
Issue is still not fixed in the stable version..

**Comment by crydotsnake** [comment]
Patch seems to work.

**Comment by crydotsnake** [comment]
It is still not fixed in the stable version 🙄
