### ISSUE TITLE
Why my table plus is intel ?

### ISSUE THREAD

**Issue by GSYin** [TablePlus/TablePlus#2885]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
pass
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
 My table plus is Version 5.1.0 (469)
3. The steps to reproduce this issue:
I find my table plus is intel ,but my macbook is M1.
<img width="462" alt="Xnip2022-11-19_00-11-24" src="https://user-images.githubusercontent.com/26523069/202751597-82da6960-aa1c-4a73-802f-8af05053b92b.png">
<img width="924" alt="Xnip2022-11-19_00-14-26" src="https://user-images.githubusercontent.com/26523069/202751640-457b8fda-a5be-4ac5-8242-d49e93a0cc67.png">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
HI @GSYin you're using our beta release. Which is intel only because Oracle don't have M1 version.
You could disable beta update in TablePlus preferences and then download the app from our website again (the official release)
