### ISSUE TITLE
Function SQL Server with returns as table not show up on functions section

### ISSUE THREAD

**Issue by deinmahendra** [TablePlus/TablePlus#2888]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **Microsoft Azure SQL Edge Developer (RTM) - 15.0.2000.1565 (ARM64)**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 468

3. The steps to reproduce this issue:

- Use database that available on SQL Server.
- Create a table with this script.
`CREATE TABLE TestReturnTable(
	Id INT NOT NULL IDENTITY(1,1),
	Temp1 VARCHAR(10) NULL,
	Temp2 VARCHAR(10) NULL
);
INSERT INTO TestReturnTable(Temp1, Temp2) VALUES('Test1', 'Test2');
INSERT INTO TestReturnTable(Temp1, Temp2) VALUES('Test1', 'Test2');`

- Create a function with return as table with this script.
`CREATE FUNCTION ShowTestReturnTable (@id AS INT)
RETURNS TABLE AS RETURN
SELECT Id, Temp1, Temp2 FROM TestReturnTable
WHERE Id = @id;`

- See the Functions section on the left. There is function show up on TablePlus. For your information, I tried using Navicat and the function show up.
TablePlus
![Result](https://user-images.githubusercontent.com/118809519/203283795-31f64e10-0be9-4414-83b4-c739e1a55dab.png)
Navicat
![Navicat](https://user-images.githubusercontent.com/118809519/203284453-25066108-2ff5-4329-9cb1-aebeabbcf9ea.png)

**Comment by huyphams** [comment]
Hi @deinmahendra have you tried to change the schema filter at the bottom of the left sidebar?

**Comment by deinmahendra** [comment]
Hi @huyphams Yes, I did. From my end, only 2 schema available (dbo and INFORMATION_SCHEMA). I switched both of schema none of them can show the function that I created.

**Comment by huyphams** [comment]
Thanks, did you refresh the workspace with cmd + R?

**Comment by deinmahendra** [comment]
Yes. I did it as well. Also re-lunch the TablePlus app and still get nothing on the functions section.

**Comment by deinmahendra** [comment]
Hi @huyphams just follow up this issue. Can you replicate this issue from your end?

**Comment by jwagon** [comment]
FWIW, I can also reproduce this issue. 

I'm using the SQL Server driver, version 5.4.2 (506) against a database with many 
1. procedures
2. scalar functions
3. table-valued functions

I can confirm that only #1 and #2 show up in the list of "Functions" in TablePlus. I also can verify I'm looking at the correct schema. These all show up fine in SQL Server Management Studio, and I can find them by SELECTing from INFORMATION_SCHEMA, and of course I can SELECT from these TVFs with no problem.

Any other information be helpful?

**Comment by coltonbrugger** [comment]
@huyphams Thanks for your great work on other issues recently.

I am now realizing that all the gremlin functions that never show in my function list in the TablePlus sidebar are all table-valued functions.

It seems that all my database objects (`sys.objects`) with `type_desc = 'SQL_TABLE_VALUED_FUNCTION'` do not show up in the sidebar while all those with `type_desc = 'SQL_SCALAR_FUNCTION'` do show up in the sidebar list.

This means I have to go manually query the `OBJECT_DEFINITION` for those table-valued functions and then run a `CREATE OR ALTER` in a new query tab to edit them every time. This is certainly frustrating for workflow, and I'd appreciate your attention to this issue if possible.

Cheers, sir!

**Comment by huyphams** [comment]
Let me fix it @coltonbrugger thank you for digging into the issue.

**Comment by huyphams** [comment]
Hi @coltonbrugger @jwagon @deinmahendra if you have a chance, please download this hotpatch: https://www.dropbox.com/scl/fi/xpij4xvzl28qeo8mbdyh2/TablePlus.dmg?rlkey=w0ew6gdw5nke995e30l2aipv3&dl=0
And see how it goes.

**Comment by coltonbrugger** [comment]
@huyphams This does not work for me still, in the hotpatch version from Dropbox [linked above](https://github.com/TablePlus/TablePlus/issues/2888#issuecomment-2076272902), nor in the latest release for me on Mac OS.
