### ISSUE TITLE
Postgres 15

### ISSUE THREAD

**Issue by BramVanBerkel** [TablePlus/TablePlus#2889]
Hi, thanks for this great tool,  I use it everyday!

In october postgres 15 was released, is an update for tableplus planned to include postgres 15?

Thanks in advance!

**Comment by huyphams** [comment]
Hi @BramVanBerkel TablePlus does not need an update to work with PostgreSQL 15. Do you have any issues with it?

**Comment by BramVanBerkel** [comment]
Hi @huyphams, when backupping a database that runs postgres 15 i get:
```
Backup database '{name of db}'
Creating tunnel...
Dumping...
dump_pg_14.0: error: server version: 15.1 (Ubuntu 15.1-1.pgdg22.04+1); dump_pg_14.0 version: 14.0
dump_pg_14.0: error: aborting because of server version mismatch

Backup database completed
```

**Comment by huyphams** [comment]
Thanks, we will bundle the PG15 binaries into TablePlus when we release the new version of DBngin.com

**Comment by BramVanBerkel** [comment]
Good to hear, thanks for the great work!

**Comment by huyphams** [comment]
If you have a chance please download this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0 It includes PostgreSQL 15 binaries.
Thanks.

**Comment by lauri865** [comment]
I'm on v5.1.1. and getting an error when using the backup feature on PG 15.1 db:
```
Backup database 'postgres'
Dumping...
dyld[51117]: missing symbol called

Backup database completed
```

**Comment by kisonay** [comment]
I get this error with the latest version

**Comment by huyphams** [comment]
Hi @kisonay did you choose the PostgreSQL 15 in the dropdown?

**Comment by kisonay** [comment]
> Hi @kisonay did you choose the PostgreSQL 15 in the dropdown?

I just took a another look and totally missed the 15.1 in the list since it wasn't at the top. Sorry about that!
