### ISSUE TITLE
Feature request: search and grouping the item of favorite like bookmark of Browser

### ISSUE THREAD

**Issue by tianhao** [TablePlus/TablePlus#289]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
90

3. The steps to reproduce this issue:
I have a lot of favorites, need search and grouping

**Comment by huyphams** [comment]
Thanks for the feedback, we have a plan to do it:
https://github.com/TablePlus/TablePlus/issues/182
