### ISSUE TITLE
[BUG] TablePlus Crashes when ClickHouse db has filled column with type Array [macOS Monterey]

### ISSUE THREAD

**Issue by AnastasiaKremenetskaya** [TablePlus/TablePlus#2896]
1. Clickhouse 22.8.6

2. Version 5.1.0 (468):

3. Steps:

    3.1 Add column with type Array(Nullable(UInt64)) (`ALTER TABLE xxx ADD COLUMN IF NOT EXISTS xxx Array(Nullable(UInt64));`)

    3.2 Fill column with any value

    3.3 Click to open table with added column

    3.4 CRUSH

**Comment by huyphams** [comment]
Hi, we just fixed this issue, will update hotpatch soon.

**Comment by huyphams** [comment]
Hey, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0 
Please let me know if you're still seeing the issue.T
Thanks

**Comment by nalandial** [comment]
> Hey, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0 Please let me know if you're still seeing the issue.T Thanks

Yup, the new version works. Thanks!

**Comment by nalandial** [comment]
@huyphams Any idea when that patch will be officially released?

**Comment by huyphams** [comment]
I submitted two other issues to ClickHouse. Hopefully, they can fix it within this month.
