### ISSUE TITLE
Keybinding to toggle the results view under SQL editor

### ISSUE THREAD

**Issue by SijanC147** [TablePlus/TablePlus#2898]
I don't think this is a bug, more of a feature request, or maybe it's already there but I can't find it as the app generally does a decent job of having keyboard shortcuts for most things.

I believe this would be incredibly useful, at the moment, when running a query the results view pops up and takes over most of the view, and there is no way of getting back to the sql editor without using the mouse to manually drag the results view back down. 

For some reason this view will also sometimes start pulled up and empty when opening a new SQL editor, maybe that is more of a bug type thing, but it wouldn't be annoying at all if the view was able to be toggled with a keybinding. 

I don't think there is an option for this in the menu bar either which could be mapped in OSX to a keyboard shortcut 😔.

Thanks and keep up the great work.

**Comment by SijanC147** [comment]
Dude, you're a legend! worked like a charm. Just renewed my license to help you keep this up! thanks again :) 

p.s. should i hold off on any other updates for now, would this patch be overwritten?

**Comment by huyphams** [comment]
This patch will be included in the next update, so no action needed.

**Comment by SlKelevro** [comment]
@huyphams cmd + ` is native mac hotkey to switch between open windows in the app (it's called "Move focus to the next window"), why would you use it for anything app-specific?

**Comment by huyphams** [comment]
Hi we changed it to control + ` in the newest release. We will add a preference for it in the future updates.

**Comment by SijanC147** [comment]
In the meantime, the keybinding can be re-mapped to anything from the keyboard app shortcut preferences.

**Comment by SlKelevro** [comment]
@huyphams great news, thanks!
