### ISSUE TITLE
Connections are saved on connecting, even if I don't press "Save"

### ISSUE THREAD

**Issue by ov** [TablePlus/TablePlus#2899]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 468

3. The steps to reproduce this issue:

- Make a new connection (I use MySQL, but it doesn't really matter), save it, close it;
- Select it in the connections list, right-click, edit;
- Change something, say its name, do not click "Save"
- Click "Connect"
- The connection is now saved with the name you changed, even if you didn't click "Save"

**Some background:** I have two accounts on production database. One is read-only for browsing the data in a safe manner. Another account has a write access, so if I need to change something, I open the connection parameters and **temporary** change the login details to the admin account and **temporary** login with these credentials.

**Why this is a problem:** once I do that temporary one-off change, TablePlus updates the saved connection with the new, admin details. This is not what I need, as I didn't press the "Save" button.

**Expected behaviour:** to save the connection only when the "Save" button is pressed. If something is changed without pressing the "Save" button - consider it as a temporary one-time change.

It is done this way in SequelPro and its successors and it is pretty convenient.

Thank you.

**Comment by huyphams** [comment]
Hi @ov I think you should create two separate connections and in one connection, you can enable the safe mode which requires you to re-enter the password every time you made a change. 
<img width="854" alt="CleanShot 2022-12-09 at 21 58 31@2x" src="https://user-images.githubusercontent.com/3654622/206730429-571476ef-72a3-4c73-8235-f2b37767b734.png">
