### ISSUE TITLE
Add ability to view 'Messages' in SQL Query results window

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#29]
Would be nice to have a plaintext console output of my SQL command. This is good for 2 reasons.

1. Be able to read full Error message upon any error
2. For specialty commands such as 'drop function' I need to see proper data response.

Note in below image nothing is displayed when I run the 'drop function' query.

![2017-07-31 17_11_40](https://user-images.githubusercontent.com/7946786/28803747-a93dc4a0-7613-11e7-9f6c-d93be2c775ce.gif)

This is how PgAdmin 4 handles this. 

success
![screen shot 2017-07-31 at 5 20 39 pm](https://user-images.githubusercontent.com/7946786/28803920-c1acbaa4-7614-11e7-8836-2bacd32c0615.png)

error
![screen shot 2017-07-31 at 5 14 55 pm](https://user-images.githubusercontent.com/7946786/28803921-c1c0df66-7614-11e7-8c43-02c9ce64c63d.png)

**Comment by huyphams** [comment]
@brian-crane sure, I will add ability to view query message

**Comment by huyphams** [comment]
It will be fixed in next release.

**Comment by huyphams** [comment]
@brian-crane done, please checkout new build 💃

**Comment by brian-crane** [comment]
@huyphams Awesome it's working great - even for multi-line queries the messages are showing properly!
