### ISSUE TITLE
Adding nullable timestamp columns does not work

### ISSUE THREAD

**Issue by leeola** [TablePlus/TablePlus#290]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

90

3. The steps to reproduce this issue:

- Create a table, commit it.
- Add a new column to the table, don't commit it
- Set the datatype to timestamp
- Set the `is_nullable` value to `YES`
- Attempt to commit the column

The column fails. Likewise, you can try changing the default value to `NULL`, which also fails. As far as I can tell, you cannot commit a nullable timestamp column during creation.

**Comment by huyphams** [comment]
I followed your steps but it works, I'm not sure how many columns on your new table maybe it's another bug.

![feb-28-2018 08-54-52](https://user-images.githubusercontent.com/3654622/36765698-14cfa858-1c65-11e8-85f4-7f6785b87d07.gif)

**Comment by huyphams** [comment]
Hi @leeola can you try with the lasted build 107?

**Comment by leeola** [comment]
Unfortunately I don't have a system I can test this on for a while; can't be of help to repro this, sorry. I'll try to test this when I do, but I'm not sure on the timeframe of that. Feel free to mark as resolved, I'll ask for reopen if I find any ongoing issue here. Thanks!

**Comment by SergeyMiracle** [comment]
Having the same issue with lates build.

**Comment by SergeyMiracle** [comment]
@huyphams i have MySQL 5.7.22
As i see one can not commit a nullable timestamp column at all

**Comment by huyphams** [comment]
I just tested with MySQL 5.7.21 but it works. I can't reproduce the bug myself. If I can reproduce the bug, it can be fixed quickly. Can you help me @SergeyMiracle, please 🙌 
![2018-07-04 14 45 21](https://user-images.githubusercontent.com/3654622/42263679-ea012146-7f98-11e8-9977-019d96422466.gif)

**Comment by SergeyMiracle** [comment]
@huyphams i see this https://cl.ly/4444181r0y1C

**Comment by huyphams** [comment]
Thanks @SergeyMiracle I just fixed the bug here: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by SergeyMiracle** [comment]
@huyphams yeah it works now 👍  Great job!
