### ISSUE TITLE
sql automatically generated during data import lacks double quotes

### ISSUE THREAD

**Issue by TanYu96** [TablePlus/TablePlus#2902]
driver: PostgreSQL 12.11

TablePlus build number: build 468

The steps to reproduce this issue:
right click after selecting the table -> import -> From CSV -> insert option : UPDATE ON DUPLICATE -> import

get this:
ERROR:  column "xxxxx" does not exist

The field name is capitalized, but in the generated sql, "ON CONFLICT (xxxx)" is not expanded with double quotes.

sql fragment:
  ', '        ', '0') ON CONFLICT (xxx, xxx) DO UPDATE SET "xxx" = excluded."xxxx","xxx" = xxxxxx

**Comment by huyphams** [comment]
We fixed it, please wait for the next update or you can download the hotpatch here: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Thank you for letting me know.
