### ISSUE TITLE
bq connection does not see the timeout parameter, request drops after 10s

### ISSUE THREAD

**Issue by skyveider** [TablePlus/TablePlus#2904]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
bigquery 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
Build 468

3. The steps to reproduce this issue:
set query timeout parameter for example 300 sec -> execute query which longer then 10 sec

**Comment by huyphams** [comment]
Thanks, let me check it.

**Comment by huyphams** [comment]
Hi @skyveider if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue.
