### ISSUE TITLE
[app crash] quick look editor explodes & passwords disappearing again after updates...

### ISSUE THREAD

**Issue by Beholdram** [TablePlus/TablePlus#2906]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **MySQL 8.0.18-google**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **212**

3. The steps to reproduce this issue: **update ends, open TP without rebooting, try to quick look anything regardless of the type, see the app lose a bit of opacity before the crash.**

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by Beholdram** [comment]
After reboot, TP is not saving the password, if it crashes, i have to connect manually everytime :(

**Comment by huyphams** [comment]
@Beholdram please update to the 214 and see how it goes, I'm sorry for your issue.

**Comment by Beholdram** [comment]
214, quick look editor working

ty ppl for all the great work ♥♥♥
