### ISSUE TITLE
Mac Client Just closes randomly after a while

### ISSUE THREAD

**Issue by Carmageddon** [TablePlus/TablePlus#2907]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 

MySQL, MS SQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 

468

5. The steps to reproduce this issue:

It seems to have started some time ago without any reason - I come back to the MacBook and TablePlus is just closed - there's no crash pop up or anything.
It just randomly disappearing as if I didn't run it.
Nothing else that is open exhibiting such a behaviour. It happens regardless on whether its plugged in or not.
I'd try to reinstall, but not sure how to backup my connections and saved passwords?

**Comment by huyphams** [comment]
Hi @Carmageddon based on the crash report. It happens in the native driver: MySQL driver and SQL server driver (freetds), we're trying to dive into it but it seems like the driver is designed to "let it crash and then respawn". We're still trying to find a way to prevent it.

**Comment by Carmageddon** [comment]
@huyphams thanks for the super fast response! I didn't realize I uploaded any crash report? MacOS didn't show me any crash report message..

Even if my Mac uploaded crash reports automatically, how'd you associate it with my personal Github account? its registered with my workplace license.

**Comment by huyphams** [comment]
Hi @Carmageddon we're using AppCenter as the crash report and it's pure technical data auto-deleted after 29 days. It does not link to any of the user info. If you don't want to send the report, you can disable it in the app preferences.

I think this one is related to your report, you can see one here:
[report-2517308351230009999-b29245ba-f8d8-4770-917c-26a86f9c9643.txt](https://github.com/TablePlus/TablePlus/files/10260945/report-2517308351230009999-b29245ba-f8d8-4770-917c-26a86f9c9643.txt)

**Comment by Carmageddon** [comment]
> Hi @Carmageddon we're using AppCenter ( a Microsoft product) as the crash report and it's pure technical data auto-deleted after 29 days. It does not link to any of the user info. If you don't want to send the report, you can disable it in the app preferences.
> 
> I think this one is related to your report, you can see one here: [report-2517308351230009999-b29245ba-f8d8-4770-917c-26a86f9c9643.txt](https://github.com/TablePlus/TablePlus/files/10260945/report-2517308351230009999-b29245ba-f8d8-4770-917c-26a86f9c9643.txt)
Thanks, but that's not mine - MacBookPro17,1 is not my model.

I dont see any crash logs in `~/Library/Logs/DiagnosticReports`, however there is a `Retired` directory which has a couple JSON files such as: `TablePlus-2022-12-13-175927.ips`
Two notable attributes in it:

>   "exception" : {"codes":"0x0000000000000001, 0x00000000000007fb","rawCodes":[1,2043],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000000007fb"},
>   "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":54219},


Would that explain the crashes without any user notice? Is there anything I can do to provide you any further information?

**Comment by huyphams** [comment]
> Thanks, but that's not mine - MacBookPro17,1 is not my model.
Yes, they're similar reports. and I just picked one as an example of the crash.

**Comment by huyphams** [comment]
I'm reading the MySQL code to see what was the root cause 
https://github.com/mysql/mysql-server/blob/a246bad76b9271cb4333634e954040a970222e0a/sql-common/client.cc#L1885

**Comment by huyphams** [comment]
Hi @Carmageddon if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you're still seeing the issue. Thanks
