### ISSUE TITLE
Autocomplete  inserts double quotes for a specific column name 

### ISSUE THREAD

**Issue by nshimbo** [TablePlus/TablePlus#2909]
Autocomplete inserts double quotes around the name in case of the column name is `table_name`. 
Is this intended behaviour?

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.18 (Heroku Postgres)
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.1.0 (468)
3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.
![autocomp_query](https://user-images.githubusercontent.com/90029992/208845637-55a0b645-6328-4cf2-9693-dd5b75450785.png)

**Comment by huyphams** [comment]
Yes, it is. The `table_name` is one of PostgreSQL's keywords so TablePlus adds the quote to make sure it works as expected.

**Comment by nshimbo** [comment]
Hi,
Thanks.
