### ISSUE TITLE
Database list empty for postgresql/redshift

### ISSUE THREAD

**Issue by eric88** [TablePlus/TablePlus#291]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    * PostgreSQL 9.4.7
    * Redshift (PostgreSQL 8.0.2)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
90

3. The steps to reproduce this issue:
    * Connect to a postgresql or redshift database
    * Click "Show Database List" or press CMD-k
    * List is empty

It's working fine for me on MySQL. Not sure if this problem is specific to me, but it would seem like a pretty big issue. In case it matters, the redshift clusters I tested on have ~30 to ~60 databases, and the postgres server I tested on has ~4 databases.

Let me know if there's any other information I can provide, thanks!

**Comment by huyphams** [comment]
Thanks @eric88 

Could you open SQL Query on Redshift and PostgreSQL 9.4.7 (Which have that bug) and run this query: `SELECT datname AS database_name,pg_database_size(datname) AS database_size FROM pg_database;`

TablePlus uses this query to get database listing.

**Comment by eric88** [comment]
@huyphams well, that explains it.

On PostgreSQL 9.4.7, I get "ERROR:  permission denied for database rdsadmin". This is an Amazon RDS database, so it's probably just the restrictive permissions they have for the `pg_database_size` function. 

On Redshift, I get "ERROR:  function pg_database_size(name) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.". Sounds like Amazon did not implement the `pg_database_size` function.

Note: A simple "SELECT * FROM pg_database" works on both. Hope this helps.

**Comment by huyphams** [comment]
Thanks @eric88 I will temporary disable `pg_database_size` until I have a new solution.
Here is the hotfix build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
