### ISSUE TITLE
Readonly mode for tab, window, or connection

### ISSUE THREAD

**Issue by necmettin** [TablePlus/TablePlus#2912]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8, but this is a feature request unrelated to drivers

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 472

3. The steps to reproduce this issue:

This is not an issue, so there are no steps to reproduce.

The feature I'm requesting can be explained simply as "readonly mode", which will disable editing of query results or running destructive queries (basically, anything other than SELECT and DESCRIBE):

Readonly mode for tab, window, or connection (this last one must be a connection-level setting).

**Comment by huyphams** [comment]
Hi @necmettin please give TablePlus safe mode a try.
<img width="1002" alt="CleanShot 2022-12-30 at 10 50 45@2x" src="https://user-images.githubusercontent.com/3654622/210032684-0d805f86-d3fd-41f0-84ad-a83c7a816d21.png">

**Comment by necmettin** [comment]
Thank you, but I'm looking for a feature that directly blocks the query instead of warning about it or asking for a password. A "block directly" mode if you will. TablePlus's lock icon still allows sending the query to the server, I'm looking for a way to not send it at all. It won't even prompt to send it; just block the query and report that with a single OK button.

Here is my reasoning: Dialog boxes have the unfortunate feature of becoming invisible after multiple uses. (i.e. When I set it to asking for password and it asks me for the password for the tenth time, I won't even think about which server I'm sending the query to, I'll just use my fingerprint and run the query without thinking.)

What I mean when I say read-only mode is an ACTUAL read-only mode, that will NEVER allow the query to pass thru.

Hope this makes what I mean more clear.
