### ISSUE TITLE
Improve selected row color pattern after un-focusing with Dark theme

### ISSUE THREAD

**Issue by alexitaylor** [TablePlus/TablePlus#292]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**PostgreSQL 9.6.6**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Build 90**

3. The steps to reproduce this issue:

- Select Dark Theme.
- Select a row (blue focus color pattern is fine).
- But when focusing on another area of the app, the grey color schema of the once focused row becomes hard to read. A grey background with a grey font makes it almost unreadable. 

![screen shot 2018-02-27 at 7 57 21 pm](https://user-images.githubusercontent.com/3086807/36769516-85981230-1bf9-11e8-87ed-32b788b9ba1b.png)

**Comment by huyphams** [comment]
It's fixed now 😄 
<img width="1162" alt="screen shot 2018-02-28 at 11 40 59 am" src="https://user-images.githubusercontent.com/3654622/36770328-47b5d0a0-1c7c-11e8-9492-0035215eaceb.png">

**Comment by alexitaylor** [comment]
Awesome! 👍
