### ISSUE TITLE
Bug of Beautify Mysql variable

### ISSUE THREAD

**Issue by HardyLi9999** [TablePlus/TablePlus#2920]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Mysql 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 210, version 5.0.1, win10 x64

3. The steps to reproduce this issue: 
**Original Query:** 
select @test_variant := 15 as test;
**After beautify:**
select
    @test_variant: = 15 as test;

**Issue**
When run the query being beautified, it return error "Query 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ': = 15 as test' at line 2",  the bug is should not add a space between ":" and "="

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
