### ISSUE TITLE
Feature Request: Tabbed Connections Toggle

### ISSUE THREAD

**Issue by SijanC147** [TablePlus/TablePlus#2922]
Hi, 

just a suggestion, is it possible to have the option to open all active connections in one window with tabs to the side as a toggle-able setting? Speaking for myself i often want to have the different connections visible side-by-side.

However, more pressingly, for some reason, opening tableplus and then manually right-clicking and separating out all my open connections from my previous session into separate windows seems to break tiling window managers like yabai. 

I understand this is a very particular issue though, just wanted to make the suggestion. 

Thanks, and keep up the great work with this, tablePlus and the features it offers is leagues ahead of any database app i've tried on mac 👏

**Comment by SijanC147** [comment]
ah sorry, maybe i missed it then, is there an option to always open connections as separate windows when restarting tableplus from a closed session?

**Comment by huyphams** [comment]
TablePlus is a native app, it follow standard behavior where you can right click on the tabbed icon and select move to new window or go to main menu Help > search for move to window...
