### ISSUE TITLE
Grouping Tables doesn't work

### ISSUE THREAD

**Issue by Johann01** [TablePlus/TablePlus#2924]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    doesn't work with any driver, tried mysql and postgres
3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
  Build 475
4. The steps to reproduce this issue:
https://user-images.githubusercontent.com/37617663/211488014-93074e84-5bfd-4b4a-a7e1-0b707c33131e.mov

**Comment by huyphams** [comment]
Hi @Johann01 please upgrade the app to build 477. The issue should be fixed. Thanks.
