### ISSUE TITLE
Browse postgresql pg_catalogue schema.

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#2926]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgresql 13

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 477

It would be nice to be able to (optionally?) browse the table in the postgresql pg_catalogue schema, did you ever consider adding that possibility?

**Comment by huyphams** [comment]
Hi @BFJonk i just saw you private message. You can enable this by click the settings drop down at the bottom of the left sidebar and choose "Show system schema"
