### ISSUE TITLE
Help >> Changelogs - not inlcuding last build 

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#2927]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 477

3. The steps to reproduce this issue:
- click Help >> Changelogs

Observed behaviour: 
- page opens:  https://tableplus.com/blog/2017/02/changelogs.html last available change Build 472

Expected behaviour: 
- page opens:  that includes last available change Build 477

**Comment by huyphams** [comment]
Hi, the 477 is the beta release (you can change it back in the peferences) so it won't be shown in the official release changelogs.

**Comment by BFJonk** [comment]
haha, great! 
Thanks for the quick reaction!
