### ISSUE TITLE
Native functions for databases

### ISSUE THREAD

**Issue by Shimakuchi** [TablePlus/TablePlus#293]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Microsoft SQL Server 2016**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Version 1.0 (87)**

3. The steps to reproduce this issue:
- Klick "Add new Row" or use the shortcut `CMD+ALT+I`
- in a date column use `NOW()` from the context menu

`NOW()` is no MSSQL function ... use `getdate()` or `getutcdate()` for example

**Comment by huyphams** [comment]
Thanks for the feedback, I'm fixing it.
