### ISSUE TITLE
App is getting slower after some time of using it until restarting

### ISSUE THREAD

**Issue by chrisbujok** [TablePlus/TablePlus#2932]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **PostgreSQL 14.5**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **486**

3. The steps to reproduce this issue:

It doesn't seem to be related to any specific data since I'm regularly working on multiple databases, but whenever I keep TablePlus open (with active connection(s)) the interface as well as queries are way slower than at the beginning. I wouldn't say it totally prevents from using the app, but is noticeably downgrading the whole experience.
Problem is gone every time I kill the app and reconnect to the same database, the same table and run the same query.
Lazy loading schema doesn't solve the problem either.

**Comment by huyphams** [comment]
Hi @chrisbujok you may want to try this patch, it should fix the issue: https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0

Please let me know if you're still seeing it.
