### ISSUE TITLE
System keyboard shortcut broken

### ISSUE THREAD

**Issue by jfedyczak** [TablePlus/TablePlus#2933]
In recent release switching between instances of TablePlus on macOS using Cmd + backtick shortcut, is broken. When SQL editor is visible, the shortcut causes to toggle results view instead of standard behaviour of switching to another TablePlus window.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Not relevant, but experienced with Postgres driver

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 5.1.2 (472)

5. The steps to reproduce this issue:

 - open SQL editor
 - press Cmd + backtick
 - shows/hides result section instead of switching to another instance of TablePlus

**Comment by huyphams** [comment]
Hi @jfedyczak please upgrade to our latest release, it would resolve this issue.
Thanks
