### ISSUE TITLE
Not able to work with any connection if one does not connect

### ISSUE THREAD

**Issue by tapz** [TablePlus/TablePlus#2937]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

4.6.0 (406)

3. The steps to reproduce this issue:

Have multiple connections open. If connecting one takes forever, the other are not connected either (no multithread connecting?)

**Comment by huyphams** [comment]
It is multiple thread @tapz could you show us the step to reproduce the issue please?

**Comment by huyphams** [comment]
You could open multiple connections here, the small tab will not open a new connection, it re-use them.
<img width="554" alt="Screenshot 2023-02-02 at 4 40 41 PM" src="https://user-images.githubusercontent.com/3654622/216288461-4fb4df6a-c57c-4201-8904-e4e07ef5792f.png">
