### ISSUE TITLE
Connection from URL

### ISSUE THREAD

**Issue by Shimakuchi** [TablePlus/TablePlus#294]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Microsoft SQL Server 2016**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Version 1.0 (90)**

3. The steps to reproduce this issue:
I tried to connect with a connection string like this
`jdbc:sqlserver://vm-sql.domain.local:1433;databaseName=MYDATABASE`

and get the error `Invalid URL` How does the URL need to be? Do I get asked for Username/Password in a second step, if needed?

**Comment by huyphams** [comment]
I don't know the `;` is valid for URL or not but TablePlus uses URL parser to parse the URL.
It should work if you replace `;` with `/`.

**Comment by Shimakuchi** [comment]
no unfortunately not. still get `Invalid URL`

**Comment by huyphams** [comment]
Did you include the `jdbc`? Hmmm looks like I should preprocess the URL first to replace `;` and `jdbc`

**Comment by Shimakuchi** [comment]
oh, ok ... nevermind :D overlooked the `jdbc:` sorry.

anyway. I come from the java world where a sql connection string always looks like this `jdbc:sqlserver://vm-sql.domain.local:1433;databaseName=MYDATABASE` Maybe you can enhance the support for those url types?

thanks for helping me, kind Regards

**Comment by huyphams** [comment]
I already fixed this issue by replacing `jdbc:` and `;` it will be included in next update 91 on Friday 😄 
Thank you for the reporting.
