### ISSUE TITLE
"X" prepended on MySQL queries on 'uuid'

### ISSUE THREAD

**Issue by blackjak231** [TablePlus/TablePlus#2942]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. _Which driver are you using and version of it (Ex: PostgreSQL 10.0):_
MySQL 8.0.29

2. _Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):_
Build 486

3. _The steps to reproduce this issue:_

- Open a table which has a uuid column
- Click Cmd + F to add a filter
- Select the column "uuid", "=", and the uuid string as comparison value
- The resulting query is the following, which causes error due to the prepended "X" : 
   ```SELECT * FROM database.items WHERE (`uuid` = X'11111111-2222-3333-444444444444') ORDER BY `id` LIMIT 300 OFFSET 0;```

Notes : 
The uuid is of `binary(36)` type and nullable and has a BTREE index.
```
CREATE TABLE `items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` binary(36) NOT NULL,
  `reference` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` smallint NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `listings_reference_unique` (`reference`),
  KEY `listings_property_id_foreign` (`property_id`),
  KEY `listings_uuid_index` (`uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by huyphams** [comment]
Thanks @blackjak231 if you have a chance, please try this patch: https://www.dropbox.com/s/q18htnq1r0n6ysl/TablePlus.dmg?dl=0
