### ISSUE TITLE
Semicolon missing when copying CREATE TABLE statement

### ISSUE THREAD

**Issue by simube** [TablePlus/TablePlus#2944]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.15.16

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
486

3. The steps to reproduce this issue:
- right-click a table in the sidebar
- "Copy Script as"
- "CREATION"
The semicolon at the end of the statement is missing.

**Comment by huyphams** [comment]
The query is returned by the server so we keep it. I also added an extra check where it missing the semicolon and add it if needed.

From new future release, we add the Copy Script as a native function, no need to install the plugin.
Thanks.
