### ISSUE TITLE
Feature request: Copy the "ALTER TABLE"-statement for a single column to a table

### ISSUE THREAD

**Issue by simube** [TablePlus/TablePlus#2945]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.5.16

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
486

4. The steps to reproduce this issue:

I often have to add columns to tables on my local installation and then insert these columns to a production database.
It would be nice to have a possibility to copy the "ALTER TABLE" - statement for a single column (e.g. by right-clicking in the structure-view)

**Comment by huyphams** [comment]
Hi @simube you can do that by pressing Command + Shift + P (preview the SQL) before committing. If you commit the change, then you can find the change logs in History tab or in the Console. So I don't think we need the copy ALTER TABLE for single column.
