### ISSUE TITLE
when I open a new tab it appears with some content as opposed to being empty

### ISSUE THREAD

**Issue by tinoargentino** [TablePlus/TablePlus#2947]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @tinoargentino you can turn off the recent queries here:
<img width="1511" alt="Screenshot 2023-02-16 at 9 17 50 AM" src="https://user-images.githubusercontent.com/3654622/219251077-8497ea56-b96d-4c6f-99b7-11c99f4811ce.png">

Also you can change the tab behaviour in the app preferences with an empty tab (not an SQL tab).

**Comment by tinoargentino** [comment]
ohhh thank u!
