### ISSUE TITLE
Feature request: LIKE option in filter comparison list

### ISSUE THREAD

**Issue by coxmi** [TablePlus/TablePlus#2948]
(MySQL 8.0.27 / TablePlus build 490)

In the filter comparison select list, there is 'has prefix' and 'has suffix', which gets transformed to:

```WHERE `column` LIKE 'myprefix_%'```

But I'd like to be able to place multiple `%` placeholders in the middle of the string (e.g. `foo_%_bar_%_baz`). Is it possible to add a `LIKE` option, so I could enter a more complex comparison value?

<img width="202" alt="image" src="https://user-images.githubusercontent.com/1307085/219336929-e8854977-59ee-4815-b31b-6da6c267ddbc.png">

Thanks!

**Comment by huyphams** [comment]
great idea @coxmi thank you for the suggestion

**Comment by huyphams** [comment]
If you have a chance, please try this patch: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0 it should include the LIKE operator.
Thanks

**Comment by coxmi** [comment]
That works a treat, thank you!
