### ISSUE TITLE
Passwords are not included in export connections for non-open connections in nested groups

### ISSUE THREAD

**Issue by MaximeLaurenty** [TablePlus/TablePlus#2953]
When exporting a group which contains a group which itself has some connections, passwords are only included for the connections which have been manually open / edited since TablePlus started.

- This is not happening when exporting a single connection.
- This is not happening when exporting a group which has connections, even if this group belongs itself to a group
- This is happening as well at 3 and 4 levels of nesting at least (I didn't test more)

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any (MySQL & PostgrSQL)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
490

3. The steps to reproduce this issue:
- Create a group A
- Create a group B in this group A
- Create a connection C with a password in group B
- Create a connection D with a password in group B
- Close TablePlus and re-open it
- Right-click on the connection C, open the edit menu and close it
- Export the group A and import it: password is present for C but missing for D

**Comment by huyphams** [comment]
Hi @MaximeLaurenty if you have a chance, please try this patch https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0 Please let me know if you're still seeing the issue.
Thank you!

**Comment by MaximeLaurenty** [comment]
@huyphams this is fixed with this patch!
I have tested 2 and 3 levels of nesting.
