### ISSUE TITLE
Request: Support scram-sha-256 password authentication for PostgreSQL

### ISSUE THREAD

**Issue by x4fingers** [TablePlus/TablePlus#2957]
What I'm using:
- PostgreSQL 14.0 run on a Docker container.
- TablePlus build 490.

The steps to reproduce this issue:
- Connect to PostgreSQL database with needed informations.
- A error message will show: `connection to server at ..., port 5432 failed: FATAL:  password authentication failed for user "..."`

At [postgres Docker hub](https://hub.docker.com/_/postgres), they said:

> If unspecified then [scram-sha-256 password authentication](https://www.postgresql.org/docs/14/auth-password.html) is used (in 14+; md5 in older releases)

**Comment by huyphams** [comment]
HI @x4fingers TablePlus use PostgreSQL 14 Lib, so I believe it supports that feature (if the docker docs are correct).

**Comment by x4fingers** [comment]
Sorry for this unrelated problem. Actually it was because my port property order in Docker Compose file, so PostgresSQL container can't expose its public port.

For folks who come after, you can see [here](https://stackoverflow.com/questions/35928670/docker-container-for-postgres-9-1-not-exposing-port-5432-to-host/48975970#48975970).
