### ISSUE TITLE
Stop executing SQL query

### ISSUE THREAD

**Issue by phuchle2** [TablePlus/TablePlus#296]
#### 1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres

#### 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (90)

#### 3. The steps to reproduce this issue:
For example, I accidentally execute the following query
![screen shot 2018-02-28 at 4 16 05 pm](https://user-images.githubusercontent.com/28104592/36779483-b625b50c-1ca2-11e8-952e-062ca869df24.jpg)
It turns out that the query returns 200k rows and it takes unexpected time to finish. I want to stop executing it immediately. How can I do so? I try to hit the refresh workspace button on the right corner but it does not do anything. Most of the time, I have to close the app and reopen it again to stop the query.

**Comment by huyphams** [comment]
It's duplicated:

https://github.com/TablePlus/TablePlus/issues/198
