### ISSUE TITLE
Problem when change database window in left sidebar

### ISSUE THREAD

**Issue by bagus-anjari** [TablePlus/TablePlus#2964]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Tableplus Version 5.3.2 (490), Mac os Ventura 13.2 (b) Beta

2. The steps to reproduce this issue:
Problem when change database window in left sidebar, sometime it just blink when selecting open database but it's not changing the window. For more clear understanding, see the video below

https://user-images.githubusercontent.com/31723338/222530001-4bae67e7-b006-4c12-a626-9a56c0685d2f.mov

**Comment by rez0n** [comment]
Hi, same thing, it is a bit annoys (a lot)

**Comment by huyphams** [comment]
TablePlus support dragging. We're using the default macOS for click & drag to detect it. I believe that the mouse has been drag a bit so macOS assume it was dragging. I will hack into it.

**Comment by huyphams** [comment]
It should work better now: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0
