### ISSUE TITLE
[Feature Request] Add Connection Name in the left most pane

### ISSUE THREAD

**Issue by hpaliwal4** [TablePlus/TablePlus#2965]
![Screenshot 2023-03-06 at 12 13 16 PM](https://user-images.githubusercontent.com/27217725/223038203-97867b4b-f4fd-43fe-8e5c-22897d3a5279.png)
connection name should be shown below the DB name, it makes it more easy to choose where to go, sometimes there are different types of enviornments where db name is common, it'll surely help in that case

**Comment by huyphams** [comment]
It's here @hpaliwal4 
<img width="298" alt="Screenshot 2023-03-06 at 1 49 38 PM" src="https://user-images.githubusercontent.com/3654622/223038643-2fa26914-6366-4a54-bac7-935d4d23a56e.png">
