### ISSUE TITLE
[Feature Request]: Adjust tag color and/or ability to hide the tag on Database selection page.

### ISSUE THREAD

**Issue by webdevnerdstuff** [TablePlus/TablePlus#2967]
1. Driver: n/a
2. TablePlus: Version 5.3.4 (492)
3. The steps to reproduce this issue: n/a

Please add the ability to adjust the color of the `tag` on the Database selection page. I specifically set my `Status color` for the environment I am using and have been doing so for years. A major reason for this was because there was no color selection for the `tag` and I want a visual hint to assure that I know which database connection I am using to avoid making changes in the wrong database. The difference in colors between the two is not only ascetically annoying (as I HATE the `development` color), it is also throwing me off visually to the env it actually is. I also realized that you changed the colors around, so this behavior was taught by the application, and has now changed.

Another solution would be to add the ability to hide the tag completely. I always label my database connections (Dev, Stage, Prod) because the tag was never displayed there before. Having these tags adds no value to display them other than redundancy, which is further an annoyance because the color does not match the `Status` color I specifically set for the connection. I wouldn't mind it as much if it matched the status color I selected as I could stop adding my own labels and just go by the tag.

Unfortunately I will have to reinstall an older version as this is really an annoying change that could lead to careless mistakes (especially in emergencies/in a rush) on my part, even though I do have some safeguards in place (requiring passwords to make changes to prod db's), etc.

![tags](https://user-images.githubusercontent.com/14927668/223191694-3e30c913-cc6b-42e0-af8f-b481a8d8b1ec.png)

**Comment by webdevnerdstuff** [comment]
Another reason I find this change very annoying is that you actually changed the colors that you had set years ago.

![image](https://user-images.githubusercontent.com/14927668/223194781-eec23793-545b-47d3-9b20-1ba8020d721b.png)

**Comment by huyphams** [comment]
Hi,
Thank you for reaching out. It's already on our roadmap. We will allow the user to add the custom tag with their custom colors in the up coming releases.

P/S the current design isn't new. This UI has been implemented on the TablePlus windows for 4 years and we now decided bring to to macOS because with this design, we can allow the users to add their custom tag with custom colors.

**Comment by huyphams** [comment]
Please wait for the next update!
<img width="606" alt="Screenshot 2023-03-07 at 9 23 20 PM" src="https://user-images.githubusercontent.com/3654622/223450162-c30b0d46-1939-47ac-bcdb-575e5bea705e.png">

**Comment by webdevnerdstuff** [comment]
Awesome, thank you!
