### ISSUE TITLE
[HELP NEEDED] SQL for trigger output by TablePlus is not executable

### ISSUE THREAD

**Issue by nnahito** [TablePlus/TablePlus#2968]
## 1. Which driver are you using and version of it (Ex: PostgreSQL 10.0)
MySQL 5.7

## 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Probably `Version 5.3.4 (492)`.
Perhaps it is an earlier version, as I updated after the problem arose.

## 3. The steps to reproduce this issue:
First, set up a trigger on the MySQL table in the TablePlus GUI.
Next, click on the eye icon in TablePlus and copy the SQL to be executed.
Then cancel the change.
Finally, in TablePlus, paste the trigger creation SQL you just copied into the SQL editor and execute it.
Then a syntax error occurs.

I would like to get the SQL for a trigger, but is this not possible with the current TablePlus?

**Comment by huyphams** [comment]
Hi @nnahito could you show us the SQL Code and the table creation please?

**Comment by nnahito** [comment]
Sorry, I'm not sure how to reproduce this and will create an issue when I know more.
