### ISSUE TITLE
Support change TablePlus font

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#297]
it would be great if TablePlus allows user pick their font instead of the current `Menlo` font.

**Comment by timster** [comment]
For the table list as well. I prefer to use a fixed-width font.

**Comment by huyphams** [comment]
We called it is mono fonts, mono fonts are very popular in programming and it's using in editors because it has fixed-width.

**Comment by ngocphamm** [comment]
Looking forward to this! You've made an incredible app, guys!

**Comment by pieterclaerhout** [comment]
+1

Also changing the font size of the SQL editor window would be handy…

**Comment by huyphams** [comment]
Thanks for the suggestion, I will improve it in the future updates 👍

**Comment by clozed2u** [comment]
+1
Need to use another font in SQL editor.

**Comment by tonylegrone** [comment]
Would be awesome if we could choose any available installed font instead of the pre-defined list. Supporting fonts with ligatures would be a great bonus!

**Comment by can-artuc** [comment]
+1
SQL Editor font customization

**Comment by mcchrish** [comment]
Would like to have an option to use SF Mono for Mac as well.

**Comment by allochi** [comment]
Seriously, if the editor allows for:
1. Choose my own font (I use `PragmataPro Liga` everywhere)
2. Save queries in a specific folder e.g `~/Documents/TablePlus/Queries/MY_DATABASE_NAME` and list them in the tree (like what Navicat does)

I will ditch Navicat and buy TablePlus immediately

**Comment by huyphams** [comment]
All those are work in progress @allochi but please wait for the release before making any purchase 👍

**Comment by allochi** [comment]
Thanks a lot, I'm so excited about TablePlus, well done!

**Comment by huyphams** [comment]
it will be supported on the next release. TablePlus allows the user to select all installed font in macOS.
