### ISSUE TITLE
Multiple keyboard shortcut suggestions

### ISSUE THREAD

**Issue by necmettin** [TablePlus/TablePlus#2974]
It would be nice to have keyboard shortcuts for the following actions:

- Next Row
- Previous Row
- Focus Table View
- Focus Data View
- Focus Left Pane

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8 (should not matter though)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 492

3. The steps to reproduce this issue:

This is not a bug report, so no steps to reproduce.

**Comment by huyphams** [comment]
1. Next now/previous: I think you want the next page (because the next and previous row...are up and down) cmd + arrow left/right.
3. Focus Table View/Data View: Command + Up/Down.
5. Left Pane: Command + Shift + F to focus on search entry but I would recommend you using the Command + P.

**Comment by necmettin** [comment]
> 1. Next now/previous: I think you want the next page (because the next and previous row...are up and down) cmd + arrow left/right.

Not really, I want to move to the next record, Id#278 in the screenshot without leaving the rightmost pane. (In the SS, my cursor/ the focus is in the Id field on the rightmost pane.

![Screen Shot 2023-03-13 at 11 30 18](https://user-images.githubusercontent.com/51944/224647943-c8324733-018e-4ab5-9e56-abceb71947c3.png)



> 2\. Focus Table View/Data View: Command + Up/Down.

Does not work when you are in a field in the rightmost pane.



> 3\. Left Pane: Command + Shift + F to focus on search entry but I would recommend you using the Command + P.

What I was really aiming for was a shortcut that lets me move between the three panes (the leftmost list, the center records listing and the rightmost edit view).
