### ISSUE TITLE
Feature request: refresh current query

### ISSUE THREAD

**Issue by tianhao** [TablePlus/TablePlus#298]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 90

3. The steps to reproduce this issue:
add a button or shortcut to refresh the data window
not execute current cursor sql

**Comment by huyphams** [comment]
Hi @tianhao , there is a refresh button here:
<img width="180" alt="screen shot 2018-02-28 at 11 34 11 pm" src="https://user-images.githubusercontent.com/3654622/36799494-e619feb6-1cdf-11e8-8de2-b8478f80d4a0.png">

The short cut key is: command + R.

**Comment by huyphams** [comment]
Btw I just make the refresh button more visible:
<img width="218" alt="screen shot 2018-03-01 at 12 10 28 am" src="https://user-images.githubusercontent.com/3654622/36801523-fb6177a4-1ce4-11e8-8290-c3c34ac31a06.png">

**Comment by tianhao** [comment]
command + R is "Reload Workspace", not refresh current query of data window

**Comment by huyphams** [comment]
What is `data window`? Reload workspace also refresh all the data.

**Comment by tianhao** [comment]
![qq20180302-190108](https://user-images.githubusercontent.com/365540/36896075-2bb18d8c-1e4c-11e8-8c93-f9ba98abf039.png)

**Comment by huyphams** [comment]
Hmm, I think this request is hard because statements are unexpected.

Ex: `UPDATE "public"."comments" SET "created_at" = NOW() WHERE "id" = '7';`
If user enter this command and TablePlus refresh it automatically maybe gernerate unexpected result.

It can be an expected behaviour with you because if aware it but most of the TablePlus user didn't know that.

**Comment by tianhao** [comment]
only work on select statements

**Comment by huyphams** [comment]
I know it would be a select statement only but that can be weird behaviour. How does user know that the result was refresh and when they're not? I need to put something in SQL Query screen that shows `Only select statement can be refreshed when pressing: cmd + R` it's small improvement but can cause many hidden behaviours (and hard to implement too, the fact that detects the statement is read-only is a real challenger in every drivers that TablePlus support).

**Comment by tianhao** [comment]
Ok
