### ISSUE TITLE
Export hangs

### ISSUE THREAD

**Issue by cipriancaba** [TablePlus/TablePlus#2989]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 5.3.5 (494)

3. The steps to reproduce this issue: Try to export any table on an M1 PRO just hands

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by cipriancaba** [comment]
This happens even on tables with 2 entries. Ran the queries manually and it's all fine

**Comment by cipriancaba** [comment]
I am using a bastion host to connect to the db, but not sure how that would affect anything

**Comment by huyphams** [comment]
Could you show me a gif or a screencast? I believe it's a rarely case (if not we would be flooded with issue report.)

**Comment by cipriancaba** [comment]
Funny enough, did a video, tried to export the file and it just hanged. All fixed after a restart. Really weird, thx for the help
