### ISSUE TITLE
[FEATURE REQUEST] Pre-populate backup filenames

### ISSUE THREAD

**Issue by mikejoseph** [TablePlus/TablePlus#299]
When dealing with a large number of development, staging and production databases it's really helpful to know which exports are which, having a consistent naming structure is really key.

It'd be really nice to have some sensible defaults when naming the database dump file name when running a backup, even if it's just something like SERVERNAME-DATABASE-YYYYMMDD.dump that would be a HUGE help.

**Comment by huyphams** [comment]
Great idea 👍
