### ISSUE TITLE
Can't open app after update to Build 496 on Mac Catalina 10.15.7

### ISSUE THREAD

**Issue by marko-x** [TablePlus/TablePlus#2990]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 494

3. The steps to reproduce this issue:
Update to the newest version (496)

There's no Tableplus error displayed: just the default MacOs alert that the app can't be open with possibility to send a report to apple.

Current solution
Downgrading to 494 via installer from https://tableplus.com/blog/2017/02/changelogs.html

**Comment by marko-x** [comment]
@huyphams i installed this patch and it is working.

**Comment by huyphams** [comment]
Thanks

**Comment by huyphams** [comment]
Thanks, we're going to bump the release again.
