### ISSUE TITLE
TablePlus.app cannot be opened because of a problem.

### ISSUE THREAD

**Issue by mavci** [TablePlus/TablePlus#2991]
After the latest update, TablePlus stop working. I guess it's related upgraded snowflake driver. I am using macOS Big Sur 11.7.4

```
Process:               TablePlus [21895]
Path:                  /Applications/TablePlus.app/Contents/MacOS/TablePlus
Identifier:            com.tinyapp.TablePlus
Version:               5.3.6 (496)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           TablePlus [21895]

Date/Time:             2023-04-03 15:27:42.107 +0300
OS Version:            macOS 11.7.4 (20G1120)

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: __ZTTNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /Applications/TablePlus.app/Contents/MacOS/../Frameworks/Snowflake.framework/Versions/A/Snowflake
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/TablePlus.app/Contents/MacOS/../Frameworks/Snowflake.framework/Versions/A/Snowflake

```

![image](https://user-images.githubusercontent.com/841613/229509506-2736b737-0c3e-423d-a3c3-6a592ab6c0d8.jpeg)
> Check with the developer to make sure TablePlus.app works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.
> 
> Click Report to see more detailed information and send a report to Apple.

**Comment by huyphams** [comment]
Hi @mavci please download this hotpatch and see how it goes: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0

**Comment by mavci** [comment]
> Hi @mavci please download this hotpatch and see how it goes: https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0

Yes it's working, thank you!
