### ISSUE TITLE
TablePlus crash on open macOS Big Sur (11.7)

### ISSUE THREAD

**Issue by khoahuynhdev** [TablePlus/TablePlus#2993]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Not important
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
5.3.6 (496)
3. The steps to reproduce this issue:
Open TablePlus

Noted: If the bug is related to data, please attach an example SQL data.

<img width="996" alt="Screen Shot 2023-04-06 at 2 41 38 PM" src="https://user-images.githubusercontent.com/25905574/230308456-2eac8c21-d0eb-411f-b5de-606faafd2bd6.png">

**Comment by huyphams** [comment]
Hi @khoahuynhdev please download this patch it will resolve the issue:
https://tableplus.com/release/osx/tableplus_latest
Thanks

**Comment by huyphams** [comment]
Hi @rtuin it's the release so you can keep using it.
