### ISSUE TITLE
[Bug UI] result query update?

### ISSUE THREAD

**Issue by und3fined** [TablePlus/TablePlus#3]
It has no style.

![It has no style.](https://1.downloader.disk.yandex.ru/preview/63438c1e647ea500b09d894d921f5cdef4f9059c898c98d40496498e77c193ac/inf/Sv-X_3tZJ0Tw_p8DbO3W5il4gaNvU4-9IvcgbgoLZmMKP_OyZGqALbHo9CewctwpioAHXlMS5BQJvT3vWmWBJQ%3D%3D?uid=0&filename=Screen%20Shot%202017-06-21%20at%2011.53.16%20AM.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=XXL&crop=0)

**Comment by huyphams** [comment]
It's issue of alternating rows, will be fixed in the next build

**Comment by huyphams** [comment]
Fixed in the build 45. Please check it out.
