### ISSUE TITLE
Ability to view 'Favorite Tables'

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#30]
Even though a database can contain hundreds of tables from many different schema, I find for some applications I only need 5 - 10 tables.  But to alternate between these requires a few seconds of hunting and searching.  This time spent can add up and lead to lost productivity.  A quicker way to alternate between most frequently used tables in a DB is needed.

Would it be possible to right click a table and say "Add to Favorites...,"  then be able to view a list of my Favorite Tables.  Any other methods of being able to quickly access tables via keyboard shortcut could also be a good solution.

I understand this functionality is a want, not a need, so is not extremely urgent.

**Comment by huyphams** [comment]
Hi @brian-crane , I think it's nice idea. Have you ever try open anything (command + P)?

**Comment by brian-crane** [comment]
@huyphams, yes I like ⌘+P but it still can take 7-8 keystrokes to get to a desired table.  One thing that could help is that:

⌘+P will only search table name as far as I can tell, but not schema name.  Maybe if i start to type in a schema name, the most commonly used table would be suggested.

Also I think expanding the settings could be nice.  A way to remap shortcuts could be useful.  ⌘+P for me is a little hard to reach with one hand so I may want to remap certain shortcuts.

Thanks!
-Brian

**Comment by huyphams** [comment]
@brian-crane sure, Remap short is nice and will be done in future but it needs a lot of work (I have plan to remap key in preferences).

Marking table as favorite is nice and can be done shortly.

**Comment by huyphams** [comment]
I added it in next update.
<img width="1314" alt="pinned" src="https://user-images.githubusercontent.com/3654622/37070576-adabecfa-21ea-11e8-860e-00fe08cf2c85.png">
