### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by lee-40square** [TablePlus/TablePlus#300]
Am I missing something or are SSL connections not supported?

**Comment by huyphams** [comment]
Are you using MySQL @lee-40square? we supported SSL MySQL and PostgreSQL

**Comment by lee-40square** [comment]
Using Postgres on Heroku but I don't see anywhere where I can just select SSL like I can in Navicat.

**Comment by Tungtono** [comment]
You can simply select from Custom TLS
<img width="612" alt="ssl" src="https://user-images.githubusercontent.com/10219818/37500936-aa54d5ba-28fe-11e8-9a2d-95897b9faf22.png">

**Comment by lee-40square** [comment]
Sorry, maybe I'm missing something obvious but I don't want to add certs or keys or anything. I just need the connection to be ssl=true (or ssl:true).

**Comment by huyphams** [comment]
Hey thanks, probably we should make it a little bit more obvious. This is PostgreSQL form, I think it better with the options:
<img width="465" alt="screen shot 2018-03-22 at 8 12 59 am" src="https://user-images.githubusercontent.com/3654622/37745703-dab512b6-2da8-11e8-9445-7b8552d7cc5f.png">

**Comment by lee-40square** [comment]
OK. The problem may only be with Postgres then. But here's what I get.

<img width="503" alt="screen shot 2018-03-22 at 8 37 48 am" src="https://user-images.githubusercontent.com/683267/37789097-46cd870a-2dc0-11e8-9dca-84be58dfa1ea.png">

When I click on the `Select TLS cert,` button I get a modal to download the file with no option for SSL mode.
<img width="885" alt="screen shot 2018-03-22 at 8 38 10 am" src="https://user-images.githubusercontent.com/683267/37789174-784bc3e6-2dc0-11e8-80ca-faf7dfcb2bed.png">

**Comment by huyphams** [comment]
Hey @lee-40square and @dgomer got it, I will improve this form next update 👍 thanks, you guys.

**Comment by huyphams** [comment]
I just update the form to allows set TLS mode:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Questions, do you guy need full options?

- disable:  only try a non-SSL connection
- allow: first try a non-SSL connection; if that fails, try an SSL connection
- prefer (default): first try an SSL connection; if that fails, try a non-SSL connection
- require: only try an SSL connection. If a root CA file is present, verify the certificate in the same way as if verify-ca was specified
- verify-ca: only try an SSL connection, and verify that the server certificate is issued by a trusted CA.
- verify-full: only try an SSL connection, verify that the server certificate is issued by a trusted CA and that the server hostname matches that in the certificate.

Currently, I only add: disable, prefer and require.

**Comment by Jastrzebowski** [comment]
Thx @huyphams for sharing this version, better (I can select my .pem files :D) but still failing for me (using GCP), I guess my custom naming of files could cause problems. Dropdown with SSL mode is Awesome but imo having explicit fields for each needed file would be better than a single button:

![image](https://user-images.githubusercontent.com/598806/38150542-b29472a0-345f-11e8-9e2b-4b6513dc9b0a.png)

Enabling hidden files by default would be also nice, or even better a checkbox to enable it, or a simple note that user can do so using `cmd` + `shift` + `.`

**Comment by huyphams** [comment]
Hey @Jastrzebowski I just updated the form. Can you give it a try 😄 
Link: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by Jastrzebowski** [comment]
Working great @huyphams, thanks 😃

**Comment by lee-40square** [comment]
Just gave it a try and it works great for Postgres on Heroku! You rock! Thank you!

**Comment by dgomer** [comment]
@huyphams Sorry for the time it took for me to get back to you on this, but it's working perfectly with my RDS Postgres instance as well - Thanks so much!

**Comment by bryanrrez** [comment]
Hi @lee-40square, I was wondering if this functionality of setting the SSL mode is supported for Microsoft SQL Server instances.

**Comment by bryanrrez** [comment]
Hi @huyphams, I was wondering if this functionality of setting the SSL mode is supported for Microsoft SQL Server instances.

**Comment by talhane** [comment]
i have the same problem
