### ISSUE TITLE
Vertical scroll freeze

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#301]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.4
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Latest Build 91
3. The steps to reproduce this issue:
Just scroll table data content with horizontal and vertical scroll
Recorded example in GIF: [link](https://giphy.com/gifs/1n8D4k0mwrqPVgwEGF/fullscreen)

**Comment by huyphams** [comment]
Hey, could you go to preferences and set: Auto hide scrollers on. Is it solve the bug?

**Comment by PVGrad** [comment]
I have only "Always show scrollers" and scroll freezes in any case - enabled or disabled state of this setting.

**Comment by huyphams** [comment]
Ah sorry this build 😄it's on this build : https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by PVGrad** [comment]
No - same freezes with build from zip

**Comment by huyphams** [comment]
Is it freezes in all tables or only in this table? 
Currently, TablePlus can be frozen in some cases:  big JSON column, and text with one line but a very long line.

**Comment by PVGrad** [comment]
Yes - this table contains text column with big json-string.
And I think that this behavior is still a UI-bug.

**Comment by huyphams** [comment]
That's right, I'm working with Cocoa Core text to optimize this. It's a bug of Apple that needs some tricks to improve 😄 A lot of text isn't a problem but a lot of text in one line is a problem.

**Comment by huyphams** [comment]
Hey, @PVGrad could you try this build and let me know if it's fixed?
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by PVGrad** [comment]
Yes, thanks, with release from last zip it works almost smooth as it should be!

**Comment by huyphams** [comment]
It's released in the recent update, so I can close this issue now, thank you 👍
