### ISSUE TITLE
Feature request: Form builder

### ISSUE THREAD

**Issue by M-Rick** [TablePlus/TablePlus#3011]
What is really missing in most database software is a great form builder in order to have a GUI to handle data. Currently, only FileMaker or Access can do this. FileMaker is expensive and cannot be used under Linux, Access is Windows only and both are closed platforms. LibreOffice is not intuitive and cannot unstable. There are several little form databases softwares under macOS, but none of them provide a serious connection with at least SQLite, and forget PostgreSQL or MariaDB/MySQL.

**Comment by huyphams** [comment]
Hi @M-Rick you can use our metrics board feature, where you can build form and charts.
https://twitter.com/TablePlus/status/1576577748084043777

**Comment by ebastidas** [comment]
hi @huyphams, a question/request. Is it possible to somehow password protect the "metrics board" so someone can only use it in "read-mode" (i.e. not be able to modify the SQL queries). Or even better is there a way to easily share this metrics to someone who's has no access to TablesPlus (ex. some stakeholders just need to see the metrics board, but not access to the database itself). Thanks.
