### ISSUE TITLE
[Bug] "You're behind x updates" number wrong

### ISSUE THREAD

**Issue by vassyz** [TablePlus/TablePlus#3016]
My license expired while I was on Build 496. Now that Build 500 got released, the message I'm seeing is `You're behind 4 updates`. I'm assuming this is wrong as it should be just one update.

<img width="200" alt="Screenshot 2023-05-24 at 10 00 35" src="https://github.com/TablePlus/TablePlus/assets/1636476/7965a825-a6d3-4648-b190-0f08cc0a9e3f">

**Comment by huyphams** [comment]
Hi, those build are alpha and beta releases😅

**Comment by vassyz** [comment]
So then why show 4 updates to the end user? I've never had an alpha or beta installed.
