### ISSUE TITLE
Feature suggestion: better connection management, esp. duplicate/clone connections

### ISSUE THREAD

**Issue by inspiredearth** [TablePlus/TablePlus#3019]
This is a feature suggestion.

Currently there appears to be very minimal features in the management of connections. One feature that would be very helpful and time saving is the ability to clone a connection. I have many DBs on one server, and I connect to that server over SSH. Having to set up each DB in Tables is currently repetitive and time-consuming. The same SSH details have to be set up for each one. 

It would great to be able to just clone an existing connection, and then change the name and DB details.

Keep up the great work.

**Comment by inspiredearth** [comment]
Ignore the above.
I see that upon quitting and relaunching the app, the start screen allows for better connection management. 

So I simply have a question ... How can I return to the "Welcome to TablePlus" window, without closing the connection window I might have open? There seems to be no way to do it.

In which case, my feature suggestion would be to add a way to bring up the welcome dashboard (with its better range of connection options via the context menu), without having to close the current connection / SQL window.

**Comment by huyphams** [comment]
Hi, you can do it by press Command + N

**Comment by inspiredearth** [comment]
> Hi, you can do it by press Command + N or also Command + shift + K or click the connection item on the top left > right click > open in new window.

Great. Thanks. `COMMAND + N` does what I am looking for. Much appreciated.
