### ISSUE TITLE
Closing the app logs you out

### ISSUE THREAD

**Issue by catskull** [TablePlus/TablePlus#302]
1. Driver: N/A

2. Build 91

3. The steps to reproduce this issue:

I bought a license and logged in. Closing the app and reopening it, I am now logged out. Can I have it remember my login and auto log me in?

**Comment by huyphams** [comment]
Hi @catskull how many devices you logged in?

**Comment by catskull** [comment]
I think this was a bug that has been fixed in version 92. Release notes haven't been published so I can't confirm. I bought 5 seats.
