### ISSUE TITLE
No database selected

### ISSUE THREAD

**Issue by createdByCrg** [TablePlus/TablePlus#3022]
Query 1 ERROR: No database selected
1. MySQL 5.7.32
2. Version 5.3.6 (496)
3. Executing any SQL after opening the database in the window will get this result.
![image](https://github.com/TablePlus/TablePlus/assets/55863425/6e866d8b-c222-4a56-ade6-4a6d9dd5fee4)

**Comment by huyphams** [comment]
Hi @createdByCrg thank you for the feedback, but i'm not sure how to reproduce the issue with the step above.

**Comment by huyphams** [comment]
I believe that you didn't select a database or put the database name into the form. Please try again and let me know if you're still seeing the issue.
Thanks

**Comment by createdByCrg** [comment]
The connection information in the screenshot has shown that the target database has been selected, and the database table on the left has also been displayed. For some reasons, I have hidden it.

**Comment by huyphams** [comment]
Could you show me the steps to reproduce? I think it is an edge case as no other users report this issue and I couldn't reproduce it.

**Comment by createdByCrg** [comment]
1. Connect to the database instance, no database specified.
2. Manually open the target database.
3. Execute sql select * from target_table; to get this wrong result. At this point I have to manually specify the database select * from target_db.target_table; on SQL to get the correct result.
I remember that in the previous version I never encountered the need to specify the target database on sql.

**Comment by huyphams** [comment]
2. Manually open the target database
=> How did you do that? Click the database button and select a database in popup or select it using command + P?

**Comment by createdByCrg** [comment]
yes
![image](https://github.com/TablePlus/TablePlus/assets/55863425/11da8407-7267-4547-92cd-df300f611b68)

**Comment by huyphams** [comment]
I did but couldn't reproduce it, please see the gif.
![CleanShot 2023-05-30 at 10 50 25](https://github.com/TablePlus/TablePlus/assets/3654622/2f432dd5-4766-4330-b748-bdc0eeb8cf79)

**Comment by createdByCrg** [comment]
I did the same, but I got wrong results.
Is the version being used Version 5.3.6 (496)?

**Comment by huyphams** [comment]
No, I'm using the latest release but I don't think it has anything different.

**Comment by createdByCrg** [comment]
Ok, let me solve this problem by manually specifying the database on SQL, but it is not convenient to use.
