### ISSUE TITLE
Changing both column_name and data_type in postgres at the same time results in error

### ISSUE THREAD

**Issue by xtj7** [TablePlus/TablePlus#3033]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 15.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 5.3.8 (500)

3. The steps to reproduce this issue:

Open the structure view on any table, change the column_name and data_type to something else and try to commit the changes, then you get the error `ERROR:  column "yyy" of relation "zzz" does not exist`
It does not matter which table, which column or which data_type, if you change both the column_name and data_type at the same time (for the same column), you get this error. Changing them in separate commits works fine though, if you first change the name and then the data type or the other way round, there is no problem.

**Comment by huyphams** [comment]
Hi,
Thanks for letting me know. If you have a chance. please try this patch https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0
Let me know if you are still seeing the issue.

**Comment by xtj7** [comment]
> Hi, Thanks for letting me know. If you have a chance. please try this patch https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0 Let me know if you are still seeing the issue.

Thank you very much, that does indeed fix the issue!
