### ISSUE TITLE
TablePlus is asking for some strange permissions: access to Desktop, access to Reminders.

### ISSUE THREAD

**Issue by jolipixel** [TablePlus/TablePlus#3035]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

TablePlus is asking for some strange permissions: access to Desktop, access to Reminders.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3.37

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 424

3. The steps to reproduce this issue:
<img width="359" alt="image" src="https://github.com/TablePlus/TablePlus/assets/1130836/1efaeaf8-422a-419e-820a-3477c741c5b4">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I'm not sure how to reproduce the issue but I believe you have click add to reminder or something similar
<img width="279" alt="Screenshot 2023-06-30 at 2 04 45 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/47d6706d-d824-4a65-932f-3950a8427416">

The second permission is normal, from the new macOS version (maybe from macOS 11 or 12) Apple will show that popup every time the app want to read data from any folder.
