### ISSUE TITLE
Can not save changes to the definition of existing views in Sqlite3 databases

### ISSUE THREAD

**Issue by pbastowski** [TablePlus/TablePlus#3036]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Sqlite3 driver that comes with TablePlus for MacOS Intel version

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

5.3.8 on an i7 MacBook with macos Ventura 13.3.1

3. The steps to reproduce this issue:

- create a blank sqlite db at the command line : "sqlite3 temp.db"
- in TablePlus add a new connection for temp.db and open it in a workspace
- add one table called table1, doesn't matter what columns you add
- add some data to the table, again doesn't matter what data
- add a view on the table called view1 and then save it
- it will save just fine
- close the tab
- open the view for editing and add a table alias "as A" or any other edit
- press Cmd+S to save. 

This time it does not save and instead restores the previous version

I can provide a video or do a live screen share to show the issue.

Noted: If the bug is related to data, please attach an example SQL data.

It is not related to data.

**Comment by huyphams** [comment]
Thanks @pbastowski let us check it

**Comment by huyphams** [comment]
Hi @pbastowski I think that we can not change that view data, here is the result
<img width="1367" alt="Screenshot 2023-06-30 at 10 14 20 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/fc176c57-cc79-4d0a-a8de-80169cc83c8d">

In other clients
<img width="1341" alt="Screenshot 2023-06-30 at 10 14 09 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/af0f0b64-03a9-49f4-bb56-f290d17df72b">

**Comment by pbastowski** [comment]
You misunderstand. I don’t want to change the data. I want to change the view definition. The SQL source code. 

When I change it and then try to save it that’s what does not work. 

Of course I don’t want to save the data, because it’s a view :)

**Comment by pbastowski** [comment]
Perhaps we can do a screen share and then I can show you the error I am referring to?

**Comment by pbastowski** [comment]
Here is a screen recording showing the problem. After I change the view structure I press Cmd+S to save and this is when the code reverts instead of saving.

https://github.com/TablePlus/TablePlus/assets/5649024/c8198e91-17a9-40ea-8fcf-227822bf2c5a

**Comment by huyphams** [comment]
Hi @pbastowski if you have a chance, please try this patch https://www.dropbox.com/s/3rbnoo74s03ekam/TablePlus.dmg?dl=0
Thanks

**Comment by pbastowski** [comment]
The patch works very well 👍

**Comment by pbastowski** [comment]
Is this change incorporated into the latest release?

I want to update but don't want to loose the ability to save changes to views.
