### ISSUE TITLE
How to add comment to the entire database table

### ISSUE THREAD

**Issue by antlcl** [TablePlus/TablePlus#3037]
How to add comment to the entire database table?

**Comment by huyphams** [comment]
<img width="330" alt="Screenshot 2023-07-04 at 10 07 21 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/b06805ad-08c6-47e8-92ac-e081203d63b7">

You can click the section table and then you will be able to alter the table comment.

**Comment by antlcl** [comment]
ok！thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TablePlus/TablePlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TablePlus/TablePlus] How to add comment to the entire database table (Issue #3037)





  
You can click the section table and then you will be able to alter the table comment.
