### ISSUE TITLE
`info` line number display

### ISSUE THREAD

**Issue by shenghui0779** [TablePlus/TablePlus#3038]
<img width="350" alt="image" src="https://github.com/TablePlus/TablePlus/assets/67535398/3d17c188-9c16-4f90-8d9e-fef42e9833fa">

<img width="185" alt="image" src="https://github.com/TablePlus/TablePlus/assets/67535398/7e45a90e-689f-4b60-85cf-aebee25a7670">

**Comment by huyphams** [comment]
Hi @shenghui0779 please fill the issue template questions. Thanks!
