### ISSUE TITLE
Add new View Tables Group? (Feature request)

### ISSUE THREAD

**Issue by mhmmd-ysf** [TablePlus/TablePlus#3039]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 13.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 236

3. The steps to reproduce this issue:

- Create 2 tables
- Create a view table named between the two tables

As i create several view tables i realized that they are automatically sorted and mixed between regular tables and view tables, can i request a new group of view tables so it's easier to organize them (for me at least)?
![image](https://github.com/TablePlus/TablePlus/assets/46883609/b57aa6f8-9a55-4417-a4d4-fc5e9a100c14)

**Comment by huyphams** [comment]
You can do that @mhmmd-ysf 
<img width="445" alt="Screenshot 2023-07-05 at 9 46 33 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/a63fcc8e-bd93-429b-a01d-6de293bcc10c">
