### ISSUE TITLE
Copy SQL Query Data results INCLUDING the header

### ISSUE THREAD

**Issue by paulpitoiset** [TablePlus/TablePlus#3044]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Don't know what it is, sorry.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.3.6 (496)

3. The steps to reproduce this issue:
SQL Query > Run > Results > Data > Right click > Copy

My issue for suggestion is: 
`THERE SI NO WAY TO COPY DATA INCLUDING THE HEADER. THAT WOULD BE SO HELPFUL.`

Noted: If the bug is related to data, please attach an example SQL data.
<img width="881" alt="Capture d’écran 2023-07-06 à 09 44 22" src="https://github.com/TablePlus/TablePlus/assets/37080277/79f7e294-79f2-4d84-83b3-d7c2018fc9aa">

**Comment by huyphams** [comment]
Hi @paulpitoiset you can copy row with header by use `Copy Rows As >`

**Comment by paulpitoiset** [comment]
Hello!
No I can't. I don't want to export.
Then the only option is `Copy Row as >` `Plain text`
Therefore, header is excluded again, just like a simple `Copy`

**Comment by huyphams** [comment]
The Copy as CSV with header is exactly the "copy" but with header.

**Comment by paulpitoiset** [comment]
Totally right, the only one I didn't tried because I thought it was CSV export....
Sorry for this and thank you very much
