### ISSUE TITLE
Column/Table Comments

### ISSUE THREAD

**Issue by SergeySmile** [TablePlus/TablePlus#305]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (92)

3. The steps to reproduce this issue:
Open Table Structure

I don't found any options to display column/table comments.
It makes tableplus less comfortable to use =\

**Comment by huyphams** [comment]
I'm going to add column length and column comment for this, depend on the driver. Please keep the app up to date and you will see it soon.

**Comment by SergeySmile** [comment]
Nice! I look forward to it.

**Comment by SergeySmile** [comment]
Hello, what about the deadlines? Are there approximate?
Every time i install update with hope to see column comments(

**Comment by huyphams** [comment]
Hey! The table strucute will be remake in build 97, that means this feature will be release as apart of this update :+1:

**Comment by SergeySmile** [comment]
So 98 build now. But i can't see description....

**Comment by huyphams** [comment]
Hi @SergeySmile i released this build early because there are some hot fixes. The structure is remaking and will be mergered in next update soon 👍

**Comment by SergeySmile** [comment]
Ok, nothing remains 😞. I will wait next update...

**Comment by huyphams** [comment]
Please check out this issue: https://github.com/TablePlus/TablePlus/issues/237

**Comment by aldo** [comment]
Hi @huyphams what about table comment?

**Comment by huyphams** [comment]
Please checkout this issue https://github.com/TablePlus/TablePlus/issues/1941
