### ISSUE TITLE
beautify turns ":=" into ": =" which is illegal plpgsql

### ISSUE THREAD

**Issue by MaximilianTyrtania** [TablePlus/TablePlus#3059]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 15.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 5.3.8

3. The steps to reproduce this issue: create an plpgsql function that contains an assignent vSomeVariable:=...
Then beautify. The code now looks like this: vSomeVariable : =... Those spaces get rejected by Postgres

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @MaximilianTyrtania thanks for letting me know. I've fixed that bug in this build. If you have an chance, you an download it here: https://www.dropbox.com/scl/fi/amzcn1l47ibkz81xl8a0n/TablePlus.dmg?rlkey=uxq5tu45u2z0hndvcg7ynr4i9&dl=0

**Comment by MaximilianTyrtania** [comment]
Hi Henry,

Looks good, thanks for the fix!

Best wishes from Berlin,

Max
