### ISSUE TITLE
Unable to open SQL Query editor

### ISSUE THREAD

**Issue by vunhuanh** [TablePlus/TablePlus#306]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
92

3. The steps to reproduce this issue:
The SQL Query editor suddenly stopped working (I was able to edit and run queries previously), it just displays a blank page now even though I can still view tables and the external editor. This is happening both on my local server and via SSH; any help would be appreciated!
<img width="1213" alt="screen shot 2018-03-05 at 4 52 48 pm" src="https://user-images.githubusercontent.com/23581350/37001877-e4af5512-2095-11e8-99bf-4dba7980b580.png">

**Comment by huyphams** [comment]
Hi @vunhuanh Looks like it was collapsed. You can hover the mouse on top (or bottom) and drag it back. Hmm, I should not allow collapse pane here.

**Comment by vunhuanh** [comment]
Wow thank you so much, I knew it would be something simple like that..... It might be more intuitive to keep showing the top of the panel when you collapse (where it says Beautify, Run, etc), if you ever get round to this tiny issue? Either way, thanks for the quick response haha

**Comment by vunhuanh** [comment]
Awesome, thank you!
