### ISSUE TITLE
Main window does not refresh with any content on database connection

### ISSUE THREAD

**Issue by nicklo** [TablePlus/TablePlus#3066]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.0.31 (localhost on M1 Macbook Air) and MariaDB 10.6.12 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

504 (version 5.4.0) running on M1 Macbook Air via Setapp subscription (this happened after last update via 
Setapp).

3. The steps to reproduce this issue:

Open a connection, then Open a database.

Main window shows no content:

![CleanShot 2023-08-15 at 10 32 58@2x](https://github.com/TablePlus/TablePlus/assets/492898/3dd20609-e481-47cc-a57c-c4391ff134f3)

**Comment by huyphams** [comment]
Hi @nicklo please toggle the sidebar on the left by clicking the button on the top right corner.
Thanks

**Comment by nicklo** [comment]
@huyphams so obvious! How stupid of me! I've been using the app up for weeks and it must've reset in a recent update and caught me off guard on a busy morning.

Anyway, thanks, you can close this ticket quickly and leave me to my shame.
