### ISSUE TITLE
Error modal becomes too large to close out when its based on a large data import, showing all items that could not be imported

### ISSUE THREAD

**Issue by bradfilip** [TablePlus/TablePlus#3068]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): mySql 5.7.38

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 358

3. The steps to reproduce this issue:
- Import a large CSV of data (7000 rows used in example)
- In this example, I forgot to auto increment the ID column, so its producing an error about duplicate entry, however this issue would happen for any scenario where the import would fail and produce a notice about not being able to perform the insert.
- You will see that the notice produces a large modal that goes behind the dock with no way to close it out, leaving the only option to force quit the app and possibly losing any other unsaved changes. Suggestion might be to truncate the results and show a preview in a smaller window or simply make it have a max height that scrolls

Noted: If the bug is related to data, please attach an example SQL data.

<img width="2020" alt="Screenshot 2023-08-15 at 9 37 58 AM" src="https://github.com/TablePlus/TablePlus/assets/13893390/bb457cf0-ed26-4af4-a267-5ed7b0a1bcdb">

**Comment by huyphams** [comment]
Hi @bradfilip i think it has been fixed on our latest release

**Comment by bradfilip** [comment]
Confirmed its fixed after updating to latest version - that was my fault for not realizing I was not up to date. thanks!
