### ISSUE TITLE
[feature request] tiling tabs

### ISSUE THREAD

**Issue by chonla** [TablePlus/TablePlus#3071]
When I use multiple tabs, they are same schemas but different environment (dev, uat, ...). I want to compare them, copy content between them. If there is a tiling tabs feature, it should help a lot.

~~When I use multiple workspaces, they are same schemas but different environment (dev, uat, ...). I want to compare them, copy content between them. If there is a tiling workspaces feature, it should help a lot.~~

Thanks.

**Comment by huyphams** [comment]
I'm not sure what you mean, there is already environment label on the title already.

**Comment by chonla** [comment]
@huyphams  I have updated my request. It is actually multiple tabs in the same workspace. Comparing them by switching tabs sometimes make me confuse. Tiling tabs and comparing data between tabs side by side is what I mean.

Thanks.

**Comment by huyphams** [comment]
I'm confused, if you are in the same workspace, how does that every tab has different env?

**Comment by chonla** [comment]
I mean the connection tabs, on the left side. They are different env.

**Comment by huyphams** [comment]
I have no idea what you're talking about, maybe you could use some image.
If you want to compare two different env. I would recommend you to open two separated windows and place them side by side.

You can open separated window by press Command + N.

Please do not remove our issue tracker questions. It helps us tracking and reproduce the issue.

Thanks

**Comment by chonla** [comment]
It is actually what you mentioned. I want to compare different env, without opening a new window. The app offers a connection tab feature. I just want to compare the already opened connections without creating a separate connection and want to keep all connections in place.

**Comment by huyphams** [comment]
I think you could change the tittle colour (by clicking it and change the colour). It will also change the icon colour on the left sidebar.
