### ISSUE TITLE
User parameter regex breaks Postgres Typecast Operator

### ISSUE THREAD

**Issue by scrawfor** [TablePlus/TablePlus#3076]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

Postgres Typecast operators are broken by the user paramater regex syntax.  

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 15.1.0.103 (but should apply to all versions)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 501

3. The steps to reproduce this issue:

- Enable Query Params with regex `star`.
- Issue a query using Postgres type cast operator `::` (ex: `SELECT 'test'::TEXT;)
- Prompted for parameter :TEXT, if not supplied with `:TEXT` then this error is received.

```
Query 1 ERROR: ERROR:  syntax error at or near ":"
LINE 1: SELECT 'test':;
                     ^
```

#### Possible Fix
Update regex syntax to `(?<!:):[\w.]+`

___________

As an aside, it would be nice to define our own regex for user parameters and/or have multiple user parameter regexes active at the same time.  Datagrip lets you control this list completely

**Comment by huyphams** [comment]
Hi @scrawfor you can change the regex here.
<img width="557" alt="Screenshot 2023-08-29 at 8 16 23 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/ad5c446f-3794-4e06-ae24-e6e83a4d1f08">

**Comment by scrawfor** [comment]
> But only to predefined options. I want to use the `:param` syntax, I just don't want it to clash with the `::typecast` operator

@huyphams - Any update?  This is the only thing holding me back from purchasing a license.

**Comment by huyphams** [comment]
Please follow this issue https://github.com/TablePlus/TablePlus/issues/2914#issuecomment-1708886899
Thanks!
