### ISSUE TITLE
Feature Request: Hover Render for GeoJson

### ISSUE THREAD

**Issue by al-hicks** [TablePlus/TablePlus#3079]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

Can the current hover feature for Postgres GIS types be extended to support GeoJSON rendering -  (see geojson.io)

![image](https://github.com/TablePlus/TablePlus/assets/46931766/d14615b0-ac3f-4df0-b48b-84605dd9f6ea)

**Comment by rowbot-weisguy** [comment]
Hello! Just want to chime in that my team would appreciate similar functionality to what's described. Specifically, we'd appreciate a base map layer underneath geometry previews.

Thanks!

**Comment by huyphams** [comment]
Did you try to press command + return or using the Quick Look @rowbot-weisguy ?

**Comment by kevinlacaille** [comment]
@huyphams that works really well, thanks! Is there a way to visualize multiple geometries at once on the map? When I highlight multiple geometries then press command + return it only returns the last geometry in the column. 
<img width="902" alt="Screenshot 2024-07-05 at 20 49 12" src="https://github.com/TablePlus/TablePlus/assets/29231903/366de503-af0c-460c-ad70-86bd72426042">

Though, the hacky way to do this would be to perform `ST_Collect(geom)` on these geometries, which is also fine!
