### ISSUE TITLE
Do you want to download the build which support Oracle

### ISSUE THREAD

**Issue by wzlstudy** [TablePlus/TablePlus#3080]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 11g
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 500
3. The steps to reproduce this issue:
我想连接Oracle 11g，但是提示”Do you want to download the build which support Oracle“，是当前版本不支持吗
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by 54kw7** [comment]
How was this problem finally solved?
