### ISSUE TITLE
User Management - Database Privileges

### ISSUE THREAD

**Issue by brysem** [TablePlus/TablePlus#3081]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
504

3. The steps to reproduce this issue:
```
1. Connect
2. Tools -> User Management
3. Select User -> Database Privileges
```

**PROBLEM**
When trying to assign privileges for specific databases, the database name is not legible. This happens when the name of a database is very long. Resizing the window does not fix the issue as it only increases the size of the Users list. The list of databases remains too small.

This is a real headache to work with.

**POSSIBLE SOLUTIONS**
1. Make it possible to resize the list of databases.
2. Make it possible to scroll horizontally (not very user friendly but will fix it)
3. Show the full database name in a tooltip when hovered over with the mouse. (not user friendly but makes it at least usable.)

<img width="1429" alt="image" src="https://github.com/TablePlus/TablePlus/assets/2829285/bc345103-d608-4072-8de8-a751b08c4c5a">

**Comment by huyphams** [comment]
Hi @brysem thanks you. It should be fixed.

**Comment by huyphams** [comment]
Hi @brysem we're improving but it should be handled better in this build, if you have a chance, you can download the patch here  https://www.dropbox.com/scl/fi/amzcn1l47ibkz81xl8a0n/TablePlus.dmg?rlkey=uxq5tu45u2z0hndvcg7ynr4i9&dl=0

**Comment by brysem** [comment]
Hi @huyphams,
This works much better. Thank you!
