### ISSUE TITLE
Allow to manage connections when other connections are already open

### ISSUE THREAD

**Issue by kamil-rudnicki** [TablePlus/TablePlus#3082]
Righ now it's not possible to edit, add new connection when other connections are open.

Allow to manage connections when other connections are already open.

**Comment by huyphams** [comment]
Hi @kamil-rudnicki you could be press Command + N or use the main menu on the top.
Thanks

**Comment by huyphams** [comment]
You can create a new connection directly from here.

<img width="696" alt="Screenshot 2023-09-06 at 3 23 16 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/a27830cf-3aa1-4b26-9fb2-b971a0cdaf36">
