### ISSUE TITLE
Keyboard shortcuts to switch between Data and Structure don't work in Spanish keyboards

### ISSUE THREAD

**Issue by djibarian** [TablePlus/TablePlus#3088]
Current shortcuts are `Cmd+Option+[` and `Cmd+Option+]` (in Mac). The `[` and `]` symbols in a Spanish keyboard are accessed pressing `Option+<the keys on the right of the P key>`, so the shortcuts are useless. It would be good to have them changed.

**Comment by huyphams** [comment]
Hi @djibarian please change it in the preferences.
<img width="899" alt="Screenshot 2023-09-12 at 9 54 28 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/e300cd0c-bd32-4770-b8ce-2b3dc4bf11ca">

**Comment by djibarian** [comment]
It doesn't work. I see the Select Next Pane and Select Previous Pane keys as `Cmd+Option++` and `Cmd+Option+``, which are the corresponding keys in the Spanish keyboard, but they don't work. Even if I change them to something else they don't work. I presume is because the Data and Structure options don't "switch panes"?

Also to note that hovering over the Data and Structure buttons the tooltip always show the original shortcut.

**Comment by djibarian** [comment]
I tried Cmd+Option+9 and Cmd+Option+0, which should be fine, but still don't change the views. They do something (change the focus in the Tables list, but nothing else).
