### ISSUE TITLE
Feature Request - Export "null" with empty string

### ISSUE THREAD

**Issue by am-webdev** [TablePlus/TablePlus#309]
Knowing from other SQL Clients during the export to CSV/Json it would be very nice to export "null" values from the database by checkbox either as the string "null" or as empty string "".

This will replace the manual IFNULL checks for every selected field which is kind of ugly on larger select statements.

Best regards

**Comment by huyphams** [comment]
It's done on build 96, which will be released tomorrow 👍

**Comment by am-webdev** [comment]
Wow thank you very much

**Comment by ilyaskarim** [comment]
@huyphams I am still having this problem when exporting large databases!
