### ISSUE TITLE
cannot connect to ClickHouse by any protocol

### ISSUE THREAD

**Issue by movy** [TablePlus/TablePlus#3091]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Clickhouse

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
506

3. The steps to reproduce this issue:

I'm using clickhouse cloud (connection via https) and also running my own clickhouse instance on a remote server with port forwarded by my localhost (http connection). Both services work fine, I'm using them daily using other interface, such as Tabix or SQLTools. Unfortunately, when it comes to simple table formatting (esp. columns autosizing) every solution out there is just pain to use. 

Decided to try TablePlus today, I __cannot even connect__ to any of my instances. 

## Using https

Connection config:
![image](https://github.com/TablePlus/TablePlus/assets/4336560/44f73c03-625f-4b9c-ade3-b5b536ccc6a2)

WIth SSL validation I get the following error which totally does not fit the screen and pushes main TablePlus window beyond screen boundary:
![image](https://github.com/TablePlus/TablePlus/assets/4336560/0f730268-0cce-46ed-846e-86c368b5635c)

![image](https://github.com/TablePlus/TablePlus/assets/4336560/d29a8f30-ee39-4ec1-a5a8-99272a2bd0c9)

__Without__ SSL validation I get simple error:
![image](https://github.com/TablePlus/TablePlus/assets/4336560/5bf15f47-6a47-4fe5-a660-47edfa65f76a)

Needless to say, you can open agkkgw2896.eu-central-1.aws.clickhouse.cloud in a browser and see that it works fine. 

## Using http

Next attempt was to connect to a remote instance using port forwarding to localhost (normal mode of work from within VSCode). 

<img width="505" alt="image" src="https://github.com/TablePlus/TablePlus/assets/4336560/ce56e820-5515-414c-8b6a-a557d7117a17">

![image](https://github.com/TablePlus/TablePlus/assets/4336560/c6ac3370-a16d-4204-994c-8c84d6ba849f)

Once again, http://localhost:8124 in a browser returns 'Ok'

So, did I come at wrong time when the CH connector is broken or I missed some crucial checkbox I needed to tick to make everything magically work? 

Thank you.

**Comment by huyphams** [comment]
Hi @movy TablePlus use the native driver with native protocol (not http) so you must you the native port.

**Comment by armedgorillas** [comment]
Hi @movy -- Did you ever get this to work? I am running into the identical issue, and I'm wondering what you did to fix the issue. Clickhouse Cloud + TablePlus 6.0.8

**Comment by movy** [comment]
as mentioned by @huyphams , using native port blabla.ap-southeast-1.aws.clickhouse.cloud:9000 worked, but I ended up using clickhouse cloud console. It does decent job for most tasks + uses Monaco editor which matches most keybinds with VSCode, for anything else I use directly vscode SQLTools + clickhouse driver

**Comment by weeebdev** [comment]
> Hi @movy TablePlus use the native driver with native protocol (not http) so you must you the native port.

I do not think this is a viable solution. I do not have an access to the native port (9000) only HTTP (8123). What can I do in this case?

**Comment by movy** [comment]
you can probably change ports in Clickhouse config as described here: https://clickhouse.com/docs/en/guides/sre/network-ports, or setup a simple port-forwarding proxy. Latter can be done even easier if you're using VSCode remote as it offers port forwarding out of the box.

**Comment by weeebdev** [comment]
> you can probably change ports in Clickhouse config as described here: https://clickhouse.com/docs/en/guides/sre/network-ports, or setup a simple port-forwarding proxy. Latter can be done even easier if you're using VSCode remote as it offers port forwarding out of the box.

As I mentioned, I do not have access to Clickhouse at all. Should I port forward locally on my client device?

**Comment by weeebdev** [comment]
@movy why is this still closed? You should be able to configure the port on tableplus.

**Comment by piggybox** [comment]
Anyone successfully connecting to Clickhouse cloud instance from TablePlus? I've tried both 9440 and 8443 and neither worked. Why is this so hard...
