### ISSUE TITLE
Filters query very slowly

### ISSUE THREAD

**Issue by NothingOnYouWl** [TablePlus/TablePlus#3092]
Using tableplus filters to query the data in the table, the query takes more than ten seconds, and using sql takes only tens of milliseconds. Similarly, using navicat filters takes only tens of milliseconds

**Comment by huyphams** [comment]
Maybe you are using the contains operation instead of equal? @NothingOnYouWl

**Comment by huyphams** [comment]
If not, please fill the issue template questions so we can reproduce the issue and fix it.
Thanks
