### ISSUE TITLE
MacOS Chart y-axis dropdown does not show any fields

### ISSUE THREAD

**Issue by pbastowski** [TablePlus/TablePlus#3099]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
sqlite 3.39.2

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
5.4.2 (506)

4. The steps to reproduce this issue:

<img width="581" alt="image" src="https://github.com/TablePlus/TablePlus/assets/5649024/043899a1-8415-4f56-afac-21be0049b6df">

- Run the SQL below. It should return 3 lines of columns x and y.

```sql
with input (x, y) as (values (1,1), (2,2), (3,3))
select * from input
```

- Click the Chart button. 
- Click x-axis, select "x" from the dropdown list and click Apply
- Click y-axis, open the drop down list and see that it is empty, as in the attached image
- Manually enter "y" in the text area below the dropdown and press enter. This registers Y as the field to use for the y-axis

Why does the dropdown not show any fields?
This happens for every SQL I try, not just the sample above.

Note that this is not a show stopper, just annoying :)

**Comment by huyphams** [comment]
Fixed! thanks.

**Comment by pbastowski** [comment]
Thank you very much, Henry.
