### ISSUE TITLE
Be able to view full table namespace in tab, in form of {schema}.{table}

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#31]
Maybe have an option to view full table namespace in the tab.  Right now only the table name is shown so for the table animal.cat, 'cat' will be shown.

I am suggesting an option for that same tab to show the long form 'animal.cat'

notice below it only says 'users' - more descriptive name would be 'allUsers.users', where allUsers is schema name

![screen shot 2017-08-02 at 1 09 44 pm](https://user-images.githubusercontent.com/7946786/28892795-f97c0d02-7783-11e7-8df5-12c13dc363e2.png)

**Comment by huyphams** [comment]
I will and a tooltip for every tabs.

**Comment by huyphams** [comment]
You can view it when hover mouse over the tab

**Comment by brian-crane** [comment]
@huyphams this should work fine - thank you!  Having an option in the Prefences window to toggle the display of the full namespace could be an option in addition.

**Comment by huyphams** [comment]
Hi @brian-crane 

TablePlus build 72 includes tab title in the end, this helps you easy track what is current schema and table. See the attachment bellow:
<img width="1300" alt="nice" src="https://user-images.githubusercontent.com/3654622/32977172-7c0810e2-cc5a-11e7-8135-8bf11bdc94b8.png">

- Huy.
