### ISSUE TITLE
TablePlus crashes when opening a table that that has a Geometry column (MSSQL)

### ISSUE THREAD

**Issue by matthewmclean** [TablePlus/TablePlus#310]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **Microsoft SQL Server 2008**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **92**

3. The steps to reproduce this issue:
- connect to a database with a table that that has a column with the Geometry data type.
- select that table in the left-hand panel under "Items".
- TablePlus will crash instantly.

**Comment by huyphams** [comment]
Thanks, @matthewmclean I will take a look at this bug, now.

**Comment by huyphams** [comment]
It's fixed in release 96 👍
