### ISSUE TITLE
MacOS Chart disappears when I re-run the query

### ISSUE THREAD

**Issue by pbastowski** [TablePlus/TablePlus#3100]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
sqlite 3.39.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
5.4.2 (506) on MacOS

3. The steps to reproduce this issue:

In a SQL window use the code below 

```sql
with input (x, y) as (values (1,1), (2,2), (3,3))
select * from input
```

- Run the query
- The results should look something like this

| x | y |
|---|---|
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |

- Make a chart of it.
- Re-run the query
- The chart is replaced with the query results instead of being updated
- I have to re-create the chart from start if I want to see it

This is very annoying, as I use this feature a lot when I do data analysis.

I have a kind of work around, where I add the chart to the Metrics board using the "Add to Metrics Board" button.

This works, and I would probably not be making an issue of it if the SQL editor in the Metrics Board was able to be resized to a decent size, but it can not and it is very small for the purpose of editing SQL. It's difficult to edit the code in there.

Again, not a show stopper, but very annoying for me personally.

Thanks for listening.

**Comment by huyphams** [comment]
Ah thanks @pbastowski I agree with you that TablePlus should keep the chart if the result columns are the same as the previous.

**Comment by huyphams** [comment]
All fixed: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
Thanks

**Comment by pbastowski** [comment]
Thank you very much, Henry.

I see you also fixed the other issue I reported. It's brilliant 🚀

**Comment by huyphams** [comment]
Hi @pbastowski you may like this feature as well

https://twitter.com/TablePlus/status/1707535074017862140
