### ISSUE TITLE
The time in the Console window shows the incorrect hour

### ISSUE THREAD

**Issue by theadin** [TablePlus/TablePlus#3106]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **Not relevant**.

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **5.4.5 (240)**

4. The steps to reproduce this issue:

Using **Windows 10**
When the time is in the PM (from 13:00 to 23:59) then the time shown for when the query ran in the Console log window will be in the AM.
For example, if the current time is 15:30, the time shown in the console window will be 03:30.
See screenshot of the issue:
![TablePlus time issue](https://github.com/TablePlus/TablePlus/assets/46445608/e22e8a01-7495-4690-846b-921c7b32e77c)

**Comment by huyphams** [comment]
Hi, thanks. We fixed it, it will be included in the next update.
