### ISSUE TITLE
No autocompleted columns for table aliases

### ISSUE THREAD

**Issue by stanislau-pamaleika** [TablePlus/TablePlus#3108]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
I've tried it on MariaDB 10.4.31 and MySQL 5.7.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.4.2 (506)

3. The steps to reproduce this issue:

For example, I have the following SQL:
`SELECT
	*
FROM
	barcodes as 'main_table'`
if I write "barcodes." then I have suggest columns:
<img width="621" alt="image" src="https://github.com/TablePlus/TablePlus/assets/9305670/9aecf21e-6dc1-469b-8bcb-3266c1b2765a">
But if I use "main_table.", then there is nothing:
<img width="257" alt="image" src="https://github.com/TablePlus/TablePlus/assets/9305670/85f65544-b32e-49eb-af4d-fd6dcbb877e1">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I think the correct way to do it as remove the single quote from 'main_table' because it would lead to an syntax error in MySQL.

**Comment by stanislau-pamaleika** [comment]
Hi @huyphams, ups, I've accidentally replaced the correct one "`" with "'" while editing the example. Here is the full example without editing:
<img width="876" alt="image" src="https://github.com/TablePlus/TablePlus/assets/9305670/d6ae4d02-f87e-479d-a192-fe1dba2523e9">

```
SELECT
	`main_table`.*,
	`dsi_item`.*,
	`request`.`track_id` AS `dsi_track_id`,
	`track`.`track_number`,
	`track`.`carrier_code`
FROM
	`barcodes` AS `main_table`
	LEFT JOIN `dsi_request_item` AS `dsi_item` ON dsi_item.barcode_id = main_table.entity_id
	LEFT JOIN `dsi_request` AS `request` ON dsi_item.request_id = request.entity_id
	LEFT JOIN `sales_flat_shipment_track` AS `track` ON track.order_item_id = main_table.sales_order_item_id
WHERE (`track`.`created_at` >= '2021-01-01')
	AND(`request`.`track_id` IS NOT NULL)
	AND(`track`.`track_number` LIKE 'BTZL%')
	AND(`track`.`carrier_code` LIKE 'dhl%')
	AND(`main_table`.`warehouse_address_id` != 1437916)
```

And it doesn't work in TablePlus, while works perfectly in, for example, DataGrip. Also, it works fine without an alias in TablePlus. And please don't suggest removing the"`" symbol because it's added automatically by a platform, and it's not an option to remove such things every time manually.

Btw., I'm not sure how it happened, but I've got twice within one day such a picture with memory:
<img width="539" alt="Screenshot 2023-10-06 at 19 39 12" src="https://github.com/TablePlus/TablePlus/assets/9305670/d6b9fb39-f00e-4bb7-8654-d60bd73e084d">

**Comment by huyphams** [comment]
Hi, if you have a chance. please try this patch and see how it goes: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

Regarding the issue, I think there is a memory leak but not sure how to reproduce it.

**Comment by stanislau-pamaleika** [comment]
Autocomplete works with this version for aliases, thanks.
