### ISSUE TITLE
beautify mishandles comment above CTE

### ISSUE THREAD

**Issue by harrykao** [TablePlus/TablePlus#3119]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 14.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 5.5.2

4. The steps to reproduce this issue:

If I have the following in an SQL window:

```sql
-- comment
WITH foo AS (
	SELECT
		*
	FROM
		bar
)
SELECT
	*
FROM
	foo;
```

Pressing the Beautify button results in this:

```sql
-- comment WITH foo AS (
	SELECT
		*
	FROM
		bar
)
SELECT
	*
FROM
	foo;
```

If I select just the SQL statement (without the comment) before pressing Beautify, it doesn't mess up the query. But I'd rather not have to make the selection first.

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
