### ISSUE TITLE
Filters not in order

### ISSUE THREAD

**Issue by marianperca** [TablePlus/TablePlus#3125]
Hello. After the last update the filters are not in the correct order. For example when I click on the filters select box, I expect the ID to be the first one, as per table columns.
I'm using MySQL 8.0.31 and the build is 512.

![image](https://github.com/TablePlus/TablePlus/assets/673596/4ee45f37-f7d4-41d5-bac4-8df3fb26f440)

**Comment by huyphams** [comment]
Hi, we added an option in the next update so you can choose ordinal or alphabet.
Workaround: You can always type the column name and it will navigate you to the column

**Comment by huyphams** [comment]
if you want to try the patch, you can download it here: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
