### ISSUE TITLE
Server upgraded to MySQL 5.7 (from 5.6), can't connect.

### ISSUE THREAD

**Issue by imattjc** [TablePlus/TablePlus#3126]
We updated our MySQL server from 5.6 to 5.7 (on the way to 8.x), but all my connections stopped working. I tried changing the driver version, but I didn't see what I expected for the driver versions (see screenshot). I tried editing existing and creating new connections, etc.
![Screenshot 2023-10-23 at 6 36 26 AM](https://github.com/TablePlus/TablePlus/assets/3384011/607553d2-34a4-40ea-b38d-bf130454bf7a)
![Screenshot 2023-10-23 at 6 38 14 AM](https://github.com/TablePlus/TablePlus/assets/3384011/b4e695f1-64ba-4039-ae15-f136886287b9)

### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Using MySQL driver. I've tried Default, Old-Older, and SingleStore DB). I've tried all 3.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 512

3. The steps to reproduce this issue:
Trying to connect to a working server. I get: Lost connection to MySQL server at waiting for initial communication packet', system error: 60

**Comment by huyphams** [comment]
Hi @imattjc I don't think this is the TablePlus issue, please check your server info again. Thank you!
