### ISSUE TITLE
Was there an update today? Filter dropdown is suddenly sorted alphabetically.

### ISSUE THREAD

**Issue by Fossil01** [TablePlus/TablePlus#3132]
Opened TablePlus and everything suddenly is a different font (looks like Consolas / Courier New) and the dropdown with columns in the filter pane is not sorted in the right away anymore either.

Loos like everything changed from `System` to `System Mono`, only the SQL Editor was using the `System Mono` font at first.

I changed these fonts back which "fixed" it. But not sure what to do with the weirdly ordered column names in the filter dropdown? Seems to be alphabetical now instead of using the order used in the table itself.

**Comment by huyphams** [comment]
Hu @Fossil01 please follow this issue to change the sort https://github.com/TablePlus/TablePlus/issues/3125
