### ISSUE TITLE
Error connecting to an RDS database

### ISSUE THREAD

**Issue by thiagosil** [TablePlus/TablePlus#3137]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MYSQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 514

3. The steps to reproduce this issue:
Connect to any mysql RDS hosted database, that requires a ssh server tunneling and the following error occurs.
This error is occuring to different database that I was able to test. And was not happening until I updated to Mac Sonoma

<img width="454" alt="image" src="https://github.com/TablePlus/TablePlus/assets/18500/d46a5c45-8e83-4b6a-9476-9d3c2c85db49">

**Comment by davideprevosto** [comment]
Few days ago we updated the CA of one of our RDS: rds-ca-ecc384-g1 (as per AWS instructions). We downloaded the `pem` bundle here https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html and we're still getting the same error.

<img width="264" alt="image" src="https://github.com/TablePlus/TablePlus/assets/28837345/fafd2d74-1057-4eb6-9c0d-a2360b3e1bdc">

**Comment by huyphams** [comment]
So it works with MariaDB? MariaDB support TLS 1.3 so I think it is the reason.

**Comment by huyphams** [comment]
This build should fix the issue: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
Thanks
