### ISSUE TITLE
Bug in "Result's column" dropdown selector at the "Search within results" pane

### ISSUE THREAD

**Issue by jugara** [TablePlus/TablePlus#3138]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **Microsoft SQL Server DBVERSION_74**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **Version 5.6.0 (515)**

3. The steps to reproduce this issue:

In the "Search within Results" pane, the "Result's column" dropdown selector lists column's name alphabetically but it performs the search by the column position in the query.

In the attached video you will see that "DirPrvCod" is the 6th column in the query results set but the 9th in the column's name dropdown selector. To perform a search by "DirPrvCod" you have to choose "DirObs" instead, which appears in the 6th position in the dropdown selector.

Noted: If the bug is related to data, please attach an example SQL data.

https://github.com/TablePlus/TablePlus/assets/2505085/4e712a31-54d8-4260-b2a6-b258c0a9e55d

**Comment by huyphams** [comment]
Hi @jugara , Thank you for letting me know. If you have a chance, please try this patch and see how it goes: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
