### ISSUE TITLE
AI Assistant doesn't work. 

### ISSUE THREAD

**Issue by dstorozhuk** [TablePlus/TablePlus#3139]
Does AI Assistant suppose to work in TP? 
I don't see any documentation about it, and it is not listed ad feature of TP. 
Is it in testing mode?

**Comment by huyphams** [comment]
Hi @LushS-io if you have a chance, please try this patch: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
I think it fix the crash issue.

**Comment by nodeGarden** [comment]
I've used the patch, but it crashes for me as well. I'd get some simple things working, but any time I try and paste multi-line prompts it dies. I think multi-line is essential for real usage.

Additionally, what is the expectation of Context? Should the Assistant know what SQL query is open, and refer to "this query" in my requests? Does it have access to the tables and schema? Last results? etc.

**Comment by dstorozhuk** [comment]
So does this feature suppose to work or not? 
Just curious. It looks like it does not work but exists in interface.

**Comment by NebulusIO** [comment]
It still doesn't work?

**Comment by pythoninthegrass** [comment]
Also interested in this feature. After the OpenAI key is resolved, please add support for Anthropic 🙏

**Comment by pythoninthegrass** [comment]
Related https://github.com/TablePlus/TablePlus/issues/3147
