### ISSUE TITLE
Snowflake: Open Item in New Tab Fails

### ISSUE THREAD

**Issue by taolmsted** [TablePlus/TablePlus#3140]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Snowflake 7.39.4

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 514

4. The steps to reproduce this issue:  Right click > Select "Open in new tab" or double click database item.  The issue results in the application to hang on "Loading Rows", which never materialize.  A new database connection needs to be created to clear the issue.  The underlying query to create the table (e.g. `SELECT * FROM table1 LIMIT 300 OFFSET 0`) is never actually sent to Snowflake per the query logs.

<img width="192" alt="Screenshot 2023-11-06 at 6 53 17 PM" src="https://github.com/TablePlus/TablePlus/assets/12519388/325f25f3-282b-44f4-8d10-48f2a40b41bd">

<img width="173" alt="Screenshot 2023-11-06 at 6 55 08 PM" src="https://github.com/TablePlus/TablePlus/assets/12519388/a35fee53-c359-44c4-b1d3-37422597503d">

**Comment by guillaumelachaud** [comment]
I can reproduce on TablePlus build 515.

Running SQL statements work, only loading tabs hangs. The only query that gets sent to Snowflake when opening a tab is a `SELECT 1;` as per the Snowflake logs.

**Comment by leonard-henriquez** [comment]
I also get the same problem on build 516

**Comment by leonard-henriquez** [comment]
Any updates ?
Snowflake is completely unusable, and I can't go back to a previous build because I'm using Table through SetApp which doesn't allow to use an older version

**Comment by taolmsted** [comment]
As a workaround, I right click on the object, select “Open Structure”, let that load, and then click the “Data” tab on the bottom section of the preview.

It’s still cumbersome and I often have to reload the connection if I forget to follow that path.

Agreed that TablePlus has become very hard to work with in this capacity.

Tom

**Comment by huyphams** [comment]
Hi guys, I will look into this issue today and fix it. Sorry for the hassle

**Comment by huyphams** [comment]
Hi, if you have a chance, please try this patch (Setapp will receive update via the Setapp Store)
https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

**Comment by huyphams** [comment]
Setapp approved the build so it should available shortly.

**Comment by leonard-henriquez** [comment]
I can confirm that it works ! Thank you !
