### ISSUE TITLE
How to view `dbstat` and virtual tables in TablePlus?

### ISSUE THREAD

**Issue by SidSethi** [TablePlus/TablePlus#3142]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite 3.39.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.6.0 (514)

3. The steps to reproduce this issue:
- connect to SQLite DB
- run any query against `dbstat` eg `select * from dbstat`

I confirmed this table exists via `sqlite3` in terminal.
Every sqlite table has this table (https://www.sqlite.org/dbstat.html). see below:
> The DBSTAT virtual table is available on all [database connections](https://www.sqlite.org/c3ref/sqlite3.html) when SQLite is built using the [SQLITE_ENABLE_DBSTAT_VTAB](https://www.sqlite.org/compile.html#enable_dbstat_vtab) compile-time option.

Thank you for your support!

**Comment by huyphams** [comment]
Hi @SidSethi if you have a chance, you can download this patch, it support dbstat: https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0
Thanks
