### ISSUE TITLE
Bytearray viewer (site bar) doesn't show fully the file

### ISSUE THREAD

**Issue by talalong** [TablePlus/TablePlus#3146]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 14

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.6.2 (516)
4. The steps to reproduce this issue:
 - save any document as byte array(bytea) type
 - open the site bar (see foto)
Note: The option "Quick Look Editor" does show the file correctly and the previous TablePlus version worked fine.
 
![Screenshot 2023-11-13 at 11 00 16](https://github.com/TablePlus/TablePlus/assets/24271207/52efabe3-575b-4a53-b0b8-72d06f196d34)

**Comment by huyphams** [comment]
Hi @talalong if you have a chance, please try this patch: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
I fixed the issue and also made it resizeable to fit the sidebar.
Thanks.

**Comment by talalong** [comment]
Hi, @huyphams. It works like a charm. Thanks.
