### ISSUE TITLE
Crash when switching between functions quickly

### ISSUE THREAD

**Issue by ambentzen** [TablePlus/TablePlus#315]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 93

3. The steps to reproduce this issue:
Select a function and hit up and down to switch between the two quickly a few times.

The crash report is reporting a segfault

**Comment by huyphams** [comment]
Hey, thanks. Let's me see.

**Comment by huyphams** [comment]
It's fixed on this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0 👍

**Comment by ambentzen** [comment]
Certainly looks like its fixed. 👍

This is easily the best graphical DB tool I've ever used.
