### ISSUE TITLE
My license has disappeared.

### ISSUE THREAD

**Issue by nnahito** [TablePlus/TablePlus#3153]
I have purchased "Standard" licenses in the past.
However, I renewed only one license, as I thought it was unnecessary for one PC.

I recently purchased another PC and tried to use an older version of TablePlus, but only one license exists in the license manager.
The Standard Plan is marked as a perpetual license.
Currently I only have a license key for one.
What happened to the other license key?

Please let us know.
Thank you in advance.

<img width="371" alt="image" src="https://github.com/TablePlus/TablePlus/assets/8242648/e776d1f4-1f4c-4352-9ca7-98a4a2487091">

**Comment by huyphams** [comment]
Hi @nnahito I think when you renew the license, you choose to reduce the number of seat. TablePlus was warned you that it will delete the other seat and could not be undone.

![Screenshot 2023-11-22 at 1 48 36 PM](https://github.com/TablePlus/TablePlus/assets/3654622/f1b2e9a3-d447-4c65-958b-7566803f2df0)

**Comment by nnahito** [comment]
I see.
I am not good at English, so I misunderstood that statement.
I see that I can't go back.
I understand.
