### ISSUE TITLE
Vertica system schemas are missing 

### ISSUE THREAD

**Issue by yakirgb** [TablePlus/TablePlus#3156]
Hi,  
I created Vertica connection but Vertica system schemas are missing on schema list.
Based on [Vertica docs](https://docs.vertica.com/12.0.x/en/sql-reference/system-tables/)
Should be the following schema on list:  `v_monitor` and `v_catalog` on this list:
![image](https://github.com/TablePlus/TablePlus/assets/12082308/ae289d1b-8220-4b65-9bad-5ebc30b22a8e)

Auto complete is working :
![image](https://github.com/TablePlus/TablePlus/assets/12082308/63df11a4-3e47-4c7b-88e6-5fadf9d5c19a)

I'm on Vertica V11 and V12.
TablePlus version 5.6.2 (516) with license . 

It's not a permission issue,
Example from same user on DBVis:
![image](https://github.com/TablePlus/TablePlus/assets/12082308/84490dfd-a6c4-47aa-b34a-e2a1eaae22ce)

**Comment by huyphams** [comment]
Hi @yakirgb have you enabled show system schemas?
<img width="401" alt="Screenshot 2023-11-26 at 2 22 53 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/5d7b7675-18d5-4b20-a2d1-d2b31593625a">

**Comment by yakirgb** [comment]
Thank you for super fast response!! this was the issue .
