### ISSUE TITLE
Restore DB is not working

### ISSUE THREAD

**Issue by vnazarenko** [TablePlus/TablePlus#3158]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. PostgreSQL 16.0

2. build 516

3. Backup DB on one laptop
4. Resotre on onthen and get this error:
![CleanShot 2023-11-27 at 13 50 34](https://github.com/TablePlus/TablePlus/assets/54346/77d6120b-1242-44bf-ae8b-9af240920cd1)

**Comment by huyphams** [comment]
Hi @vnazarenko thank you for letting me know. I fixed the issue in this patch: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

If you have a chance, please give it a try. Thanks!
