### ISSUE TITLE
Vertica export_objects function is not working

### ISSUE THREAD

**Issue by yakirgb** [TablePlus/TablePlus#3159]
Using Version 5.6.5 (521). 
Unable to run : `SELECT export_objects('', 'lab.table_1');` , it's built-in Vertica command to see table DDL . 
The error is : `Query 1 ERROR at Line 1: : ERROR:  Unsupported use of LIMIT/OFFSET clause`
So, i changed to `No limit` , getting `Query 1 OK` with without any Data.
![image](https://github.com/TablePlus/TablePlus/assets/12082308/bb9fc01b-30be-45a1-b953-fcf5798c6b79)
![image](https://github.com/TablePlus/TablePlus/assets/12082308/0d9108cd-fac1-4a18-bf1a-412bf2ad0972)

Docs: https://docs.vertica.com/12.0.x/en/sql-reference/functions/management-functions/catalog-functions/export-objects/

TablePlus doesn't provide Vertica Projection info, this is why need export_objects.

**Comment by huyphams** [comment]
Hi @yakirgb I think there is a new line in the result. You may want to click on the row and view it on the right sidebar or you can right click on the row > Quick look (shortcut command + return).
I also supported view table info in the new update.

**Comment by yakirgb** [comment]
Correct, right click on the empty row and "quick look" show the output 
![image](https://github.com/TablePlus/TablePlus/assets/12082308/1ad5f7bf-89f6-4e3a-8b3a-fe3133ffa688)
![image](https://github.com/TablePlus/TablePlus/assets/12082308/4eaae44f-35fd-44f8-a6ab-585ee8f98197)
Thank you .
