### ISSUE TITLE
Feature Request: Ctrl+Tab to cycle through tabs

### ISSUE THREAD

**Issue by marcusmoore** [TablePlus/TablePlus#316]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **Mysql**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **92**

3. The steps to reproduce this issue:
I would like to be able to use `ctrl`+`tab` and `ctrl`+`shift`+`tab` to cycle through tabs since I am accustomed to doing this in most applications that utilize tabs (like Chrome). Is this something that can be added in addition to `ctrl`+`[` and `ctrl`+`]`?

Thank you!

**Comment by huyphams** [comment]
Currently, we can move between tabs by shortcut key: command + [ or command + ] and the windows by: Control + Tab and Control + Shift + Tab.

**Comment by marcusmoore** [comment]
Hm...`Control + Tab` and `Control + Shift + Tab` don't seem to navigate windows for me while `` Command + ` `` does...

"Windows" and "Workspaces" mean the same thing correct?

**Comment by huyphams** [comment]
It only supports in sierra and above.
<img width="1129" alt="aaaa" src="https://user-images.githubusercontent.com/3654622/37322728-f9aa15e8-26b1-11e8-9390-d3620ccd8bca.png">

**Comment by marcusmoore** [comment]
Oh I see! I had been making new workspaces via `command + n` instead of keeping it in the same window. Thank you!

**Comment by jayshepherd** [comment]
It seems standard within macOS for movement between tabs to be `command + shift + [` or `command + shift + ]` (See chrome, safari, finder, sublime, etc)

Would it be possible to change the navigation to that or at least provide a way to set it to the standard?

**Comment by huyphams** [comment]
Hey @jayshepherd it already in our plan, see https://github.com/TablePlus/TablePlus/issues/327

**Comment by georgexsh** [comment]
@huyphams  use <kbd>Control-Tab</kbd>/<kbd>Shift-Tab</kbd> to cycle between tabs is pretty the standard in macOS, see safari, chrome, sublime, and macOS HIG (https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/):
> Tab
> Shift-Tab	
> ●
> Navigate through controls in a reverse direction.
> Command-Tab	
> 
> Control-Tab	
> ●
> Move focus to the next group of controls in a dialog or the next table (when Tab moves to the next cell).

**Comment by georgexsh** [comment]
@huyphams is there any update on this issue?

**Comment by georgexsh** [comment]
@huyphams ping, is there any plan for this tweak?

**Comment by georgexsh** [comment]
if change the current behavior is too hard, could you offer an option for this?
