### ISSUE TITLE
Filter Column <> {Empty Value} is passing that literally as bad SQL

### ISSUE THREAD

**Issue by devtimi** [TablePlus/TablePlus#3160]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.33

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 516

3. The steps to reproduce this issue:
Filter a table on a column, select <> and then leave the value empty

NOT EMPTY and NOT NULL are different things, and since there is no NOT EMPTY in the popup menu, I went about it by this method. TablePlus generated the bad SQL
```
SELECT COUNT(*) as count FROM `TheDB`.`TheTable` WHERE `TheColumn` <> ;
```

It can be worked around by passing `""` as the search value, but since this isn't the Raw SQL option I would expect this search to have been protected from SQL injection.

**Comment by huyphams** [comment]
Hi @devtimi I think you are filtering the none-text field. If you filter the text field, it would be an empty quote.

**Comment by devtimi** [comment]
Thanks for the pointer. I'll mark this as closed.
