### ISSUE TITLE
PostgreSQL sni error on backup or restore

### ISSUE THREAD

**Issue by AzSiAz** [TablePlus/TablePlus#3169]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 15.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
520

3. The steps to reproduce this issue:
Import or backup a neon hosted database (sni)

`pg_dump` and `pg_restore` work fine in CLI, but using TablePlus backup/restore make it not use sni so it result in an error. 
I tried the workaround using `dbname=backend options=endpoint=ep-cool-darkness-123456` but this doesn't seem to be used either, probably because we need to manually select the database

```
Backup database 'backend'
Dumping...
dump_pg_15.1: error: 
ERROR:  Endpoint ID is not specified. Either please upgrade the postgres client library (libpq) for SNI support or pass the endpoint ID (first part of the domain name) as a parameter: '?options=endpoint%3D<endpoint-id>'. See more at https://neon.tech/sni

Backup database completed
```

**Comment by huyphams** [comment]
Thanks, let me check and fix it.

**Comment by huyphams** [comment]
Hi @AzSiAz in the meantime, you can try to backup with the version 14.0, it should work.

**Comment by huyphams** [comment]
Or you can download the hotpatch build here: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

**Comment by AzSiAz** [comment]
Hi, sorry Europe timezone 

I unfortunately can't backup with version 14, since I am using PostgreSQL 15.1, because I will get a version mismatch
I can still use the CLI so I can wait for the next build, but thanks for the very quick fix 😄
