### ISSUE TITLE
[Bug] "Unkonown Error" when connecting using build 514+

### ISSUE THREAD

**Issue by musa11971** [TablePlus/TablePlus#3172]
<img width="444" alt="unkonown" src="https://github.com/TablePlus/TablePlus/assets/21341801/f2bcdc7a-cf12-45fd-847a-f33878c1e4c9">

# "Ukonown Error"
A strange error gets thrown whilst connecting to a MariaDB server.

## Versions used
- macOS 14.1.2 (23B92)
- mariadb from 11.2.2-MariaDB, client 15.2 for osx10.19 (arm64)

## How to replicate
On TablePlus 5.5.1 (510):

1. Connect to our production or acceptance MariaDB server.
2. ✅ The connection succeeds and TablePlus works fine.

On any higher version, for example build (514):
1. Connect to our production or acceptance MariaDB server.
2. The connection instantly fails and shows *"Unkonown Error"* (yes, the typo is in the error message itself)
3. There is no way to connect to the remote MariaDB server.

Please let me know any other useful details I could share. I think the best lead would be to find out where the typo'd error comes from ("Unkonown Error"), which I myself have not been able to figure out.  

Multiple colleagues are affected and this bug forces us to downgrade to build 510. An annoying side-effect: [we can not activate our TablePlus license on build 510](https://i.imgur.com/g72kUCx.png)...

**Comment by dudelisius** [comment]
Have run into this issue as well. Would very much see this resolved. We have active licenses for TablePlus.

**Comment by huyphams** [comment]
Hi @dudelisius @musa11971 I think the "Unkonown Error" is the typo from the MariaDB team (not from TablePlus).

We upgrade MariaDB lib to the newest release to support TLS 1.3 so I think it has something todo with your SSL config. Could you post your connection form here or send it to nick@tableplus.com?
Thank you.

**Comment by huyphams** [comment]
Hi @dudelisius @musa11971 could you please try again with the build 524, if it does works, please try again with MySQL driver and see how it goes?
