### ISSUE TITLE
Support ClickHouse Maps

### ISSUE THREAD

**Issue by coelho** [TablePlus/TablePlus#3173]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
ClickHouse server version 23.11.1.2711 (official build)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 520

3. The steps to reproduce this issue:
a. Create a table:
`CREATE OR REPLACE TABLE test
(
    pk String,
    test Map(String, Uint8)
)
ORDER BY pk;`
b. Browse the table in TablePlus:
`Unable to parse type: Map(String, UInt8)`

**Comment by huyphams** [comment]
Hi @coelho if you have a chance, please try this patch: 
https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

it should support decode Map.
