### ISSUE TITLE
table-->Structure-->Info，table sql BUG

### ISSUE THREAD

**Issue by an0na** [TablePlus/TablePlus#3175]
There are two semicolons at the end of the SQL statement for creating a table
<img width="440" alt="image" src="https://github.com/TablePlus/TablePlus/assets/15793432/faa6bebe-31ec-4635-a45d-9b32701467ce">

**Comment by huyphams** [comment]
Hi @an0na I just fixed this issue, please wait for the next update or download hotpatch here: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
