### ISSUE TITLE
Driver Error - Invalid SSL

### ISSUE THREAD

**Issue by rivatove** [TablePlus/TablePlus#3177]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it: MySQL 8.0.34

2. Which TablePlus build number are you using: 254

3. The steps to reproduce this issue: 

I'm getting **Driver Error** _Invalid SSL_ when trying to connect to my RDS instance. The SSL mode is set to PREFERRED. I've tried every other mode and only DISABLED works. The CA used by my RDS is [rds-ca-ecc384-g1](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html).

I'm not getting such issue on MySQL Workbench. I'm able to use any SSL mode there with the cerificates supplied by AWS.

**Comment by huyphams** [comment]
Hi @rivatove due to the fact that MySQL on RDS requires TLS 1.3 (but TablePlus on Windows only support 1.1 and 1.2) so it won't work.
We will support TLS 1.3 in the next update. Thank you.

Btw, you submitted the issue on wrong repo: https://github.com/tablePlus/tableplus-windows/issues

**Comment by huyphams** [comment]
If you have a chance, you can install this path: https://www.dropbox.com/scl/fi/hqi17lg3wrg74deuqxpmb/TablePlusUpdate.exe?rlkey=ap8at4ntmuw4wpgas4b46797y&dl=0 it should support TLS 1.3

**Comment by rivatove** [comment]
> If you have a chance, you can install this path: https://www.dropbox.com/scl/fi/hqi17lg3wrg74deuqxpmb/TablePlusUpdate.exe?rlkey=ap8at4ntmuw4wpgas4b46797y&dl=0 it should support TLS 1.3

Thanks, it works now.

Are the extra modes such as VERIFY-CA and VERIFY-FULL not finished yet? They work even with no key files attached.
