### ISSUE TITLE
Pagination Issue: Switching Tables Does Not Reset Pagination, Resulting in Empty Records

### ISSUE THREAD

**Issue by hendurhance** [TablePlus/TablePlus#3178]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 520 

3. The steps to reproduce this issue:
- Open TablePlus and connect to a database.
- Navigate to a table with a large number of rows (over 500k records).
- Paginate through the results by clicking the "Next" button multiple times until you reach around 27k rows.
- Click on another table.
- Observe that the new table does not display any records, as TablePlus still thinks you are on the previous table.
- To resolve the issue, you have to click the "Previous" or "Back" button until you reach the initial set of records (first 300 rows).
- The correct action is meant to be, when you click on another table, the pagination resets to the initial set of records (first 300 rows).

**Comment by huyphams** [comment]
Hi, it is a bug. TablePlus should open that item in new tab

**Comment by hendurhance** [comment]
I figured. It took me a while to realize what was going on, because my records weren't empty but I didn't see any record.

**Comment by huyphams** [comment]
I could not reproduce the issue, could you show me a screencast or a gif @hendurhance thanks

**Comment by hendurhance** [comment]
Tried reproducing the error with a quite small database, but I couldn't. It is probably a glitch.
