### ISSUE TITLE
where is my email account???

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#318]
why can i not login with my normal briancrane email account???? says 'email not found'!

**Comment by huyphams** [comment]
Hi @brian-crane just register an account and it will be fine. I’m working with new CD-key system, it will be release in build 94.

**Comment by huyphams** [comment]
Can you email me, I just checked the database and saw your account was associated with the email: begin with `bcr***`

**Comment by brian-crane** [comment]
ah i was using wrong email address! so sorry huy false alarm but now it is saying "You are out of seats. The oldest device was removed from this license.
If you want to use TablePlus on multiple devices, please add more seats."

and cannot get past the login screen....

**Comment by brian-crane** [comment]
It is saying I have only the free plan, where is my Happy Plan?

**Comment by brian-crane** [comment]
![screen shot 2018-03-12 at 3 50 53 pm](https://user-images.githubusercontent.com/7946786/37313784-f834fd4e-260d-11e8-9f1e-f2f2b1e5432d.png)

**Comment by huyphams** [comment]
Hi @brian-crane just ignore the message `out of seats` and it should be fine.

Btw, from build 94 I changed the way activate TablePlus to Cd-Key. I will send CD-Key to all customer. I think it will solve all activation issue.
<img width="632" alt="screen shot 2018-03-13 at 11 26 59 am" src="https://user-images.githubusercontent.com/3654622/37322649-75c6ba74-26b1-11e8-83e6-282a3d9904e2.png">

**Comment by brian-crane** [comment]
hm, even when i ignore you can see it has me on free plan, not happy plan :(

**Comment by huyphams** [comment]
Let's me double check, it should not be a free plan. Can you send me the email?
Your license email is: `bcr***@**ates.com`

**Comment by brian-crane** [comment]
yep thats the email! thanks huy

**Comment by huyphams** [comment]
I updated the new system activation that uses license keys. This is the final version and will not change anymore.
If you lost license key please visit here to recovery: [License manager](https://tableplus.io/license-manager/access-link)

**Comment by brian-crane** [comment]
Hi Huy!! I am back to using TablePlus again, but I am not working at ebates anymore.  I registered as bcrane@ebates.com - is there anyway I can get this email updated to my new email?

Thanks!

**Comment by huyphams** [comment]
Hi @brian-crane please email me at nick@tableplus.com then I will change the license email for you!
