### ISSUE TITLE
can't show emoji

### ISSUE THREAD

**Issue by BinaryAlan** [TablePlus/TablePlus#3180]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.6.8 (524)
3. The steps to reproduce this issue:

My data cannot be displayed properly in TablePlus, but it can be displayed correctly in other database software such as Sequel Pro.
Definition of field
`title varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''`

It is like this in TablePlus.
![image](https://github.com/TablePlus/TablePlus/assets/37968794/49ae83be-ddc9-43cd-b3a9-778c121ec818)

It's like this in sequel pro.
![image](https://github.com/TablePlus/TablePlus/assets/37968794/e5b6b128-07b0-4069-b76c-34e5f8214518)

**Comment by BinaryAlan** [comment]
Adjusting to use UTF8 Full Unicode will display correctly. By the way, why aren't emoji expressions displayed by default? I believe there are others who are also confused about this. Other software displays them by default, and I think it would be more user-friendly that way.

**Comment by huyphams** [comment]
Hi @BinaryAlan you can change the viewer encoding buy select it here, it will remember for the next time you open the connection.
<img width="535" alt="Screenshot 2023-12-21 at 12 24 20 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/b10455f7-4354-4bfd-8f0c-b1bf42875c0d">
