### ISSUE TITLE
Export chart?

### ISSUE THREAD

**Issue by fabswt** [TablePlus/TablePlus#3181]
Is there any way to export charts generated by TablePlus?

In the Chart tab, the "Export" button does nothing. I click on it and nothing happens. So I don't know if it's because it's broken or not supposed to do anything.

**Comment by huyphams** [comment]
Hi @fabswt if you have a chance, you could try this, it should support this feature by now:
https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0
Thank for the suggestion!
