### ISSUE TITLE
Issue on Vertica: TablePlus not sending client info to Database

### ISSUE THREAD

**Issue by yakirgb** [TablePlus/TablePlus#3184]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Vertica V12 or Vertica V12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.6.7 (525)

3. The steps to reproduce this issue:
Connect to Vertica using LDAP connection

TablePlus not sending to Vertica client and driver info .
When selecting from `sessions` table on Vertica that following column are missing:

- client_type
- client_version
- client_os
- client_os_user_name

Should be something like:
- client_type: JDBC Driver
- client_version: 23.03.0000
- client_os: Mac OS X 14.1.2 aarch64
- client_os_user_name: yakir.g

On other IDEs or vertica-python i see this info in `sessions` table.

Thank you, 
Yakir Gibraltar.

**Comment by huyphams** [comment]
Thanks, let me see how to submit these info with the current driver.

**Comment by yakirgb** [comment]
BTW, what the current driver version? how can i see this info on TablePlus ?

**Comment by huyphams** [comment]
it's not possible to set the value 
client_type
client_version
client_os
client_os_user_name

as I don't see in the documents but I could set the client_label to TablePlus, so you could know which connections are made by TablePlus

**Comment by huyphams** [comment]
If you want to try it, you could download the hotpatch here: https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0
