### ISSUE TITLE
Issue on Vertica: Unable to see items on v_internal schema

### ISSUE THREAD

**Issue by yakirgb** [TablePlus/TablePlus#3185]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Vertica V12 or Vertica V12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.6.7 (525)

3. The steps to reproduce this issue:

- Connect to Vertica with enabled "show system schemas" 
- Choose schema v_internal
- "items" is empty and auto complete isn't working 

On v_monitor for example i don't see this issue. 

Example from DataGrip:
![image](https://github.com/TablePlus/TablePlus/assets/12082308/232ff9d5-b3e4-46cb-9765-af798438030b)
Example for the issue from TablePlus:
![image](https://github.com/TablePlus/TablePlus/assets/12082308/bd12bfde-57dc-483d-b0b2-7a6690afe295)
![image](https://github.com/TablePlus/TablePlus/assets/12082308/461684f9-95f8-4aa2-a63e-deb63e664edf)
![image](https://github.com/TablePlus/TablePlus/assets/12082308/1a23b03b-ad29-4e7a-b7ea-d51f8d57a1dc)

**Comment by huyphams** [comment]
I don't see any tables from v_internal with the query 

SELECT table_name,schema_name FROM all_tables;

Maybe we have another way to list those table?

**Comment by yakirgb** [comment]
I'll check tomorrow

**Comment by yakirgb** [comment]
**List of tables in v_internal:**
`select table_id as id, table_name as name, table_description as comment, is_view from v_internal.vs_system_tables where table_schema = 'v_internal';`
**Columns details per table  of schema v_internal:**
`select table_id, column_name, data_type, ordinal_position from v_internal.vs_view_columns where table_schema = 'v_internal' order by table_id, ordinal_position;`
**Columns with more details per table of schema v_internal:**
`select t_oid as table_id, attname as column_name, typname as data_type, attnum as ordinal_position, not attnotnull as is_nullable, adsrc as column_default, attisidentity as is_identity from v_internal.vs_columns where nspname = 'v_internal'` order by table_id, ordinal_position;
**Source view creation for views of schema v_internal:**
`select view_name as name, query_string as src from v_internal.vs_system_views where view_schema = 'v_internal';`

**Comment by sweemyn** [comment]
The second query is for views columns and not tables columns

**Comment by huyphams** [comment]
Hi @yakirgb you could try this patch: https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0 it should show the v_internal tables and views.

**Comment by yakirgb** [comment]
Tested, works perfect !!
