### ISSUE TITLE
No way to see if column is computed/generated or regular

### ISSUE THREAD

**Issue by kokoshneta** [TablePlus/TablePlus#3186]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Microsoft SQL Server 2019

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

5.6.6 (520)

3. The steps to reproduce this issue:

Create or open a table that you know has one or more computed/generated columns (whether virtual or stored) – then try to use the GUI to find out which columns are in fact computed/generated. Unless I’m missing something (which I might be), you can’t.

There’s a note in #2480 that “TablePlus will show "VIRTUAL GENERATED" in the 'extra' column in the structure-editor for the column 'task_id'”, and this seems to be correct for MySQL databases – but for SQL Server databases, **there is no `extra` column** (no idea why not?), so the information is not shown anywhere.

Not sure if this counts as a bug or a feature request, but I would say it should definitely be possible to see not only _if_ a column is computed/generated, but also its _definition_.

**Comment by huyphams** [comment]
Hi @kokoshneta https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0 if you have a chance, you could try this patch, it should show you the generated column status!
Thanks

**Comment by kokoshneta** [comment]
Yes, it works! At least inasmuch as it shows whether the column is computed as a boolean yes/no value – still can’t see a way to see what the actual definition of the computation is, but that doesn’t seem to be possible with MySQL databases either, so it’s at least consistent now.
