### ISSUE TITLE
App hanging (CPU usage 100%) after an update

### ISSUE THREAD

**Issue by kubaczer** [TablePlus/TablePlus#3189]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mostly MySQL 5, can't check the details right now.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Unable to check. Latest

3. The steps to reproduce this issue:
Earlier today noticed "You're behind by 4 updates" message, so updated TablePlus by clicking on "Check for updates".
Immediately after that I noticed "You're behind by 2 updates" message, so updated again, but this time app was hanging after it got restarted.
What I mean by hanging: basic view was visible, but "busy wheel" was turning, and nothing worked. After I switch to another window, I can't go back (TablePlus doesn't show). Activity Monitor shows TablePlus using 100% of CPU and being unresponsive. 
After 20 minutes I force-quit the app. Starting it again results in the same issue.

Then I downloaded latest version from your website, but doesn't help.

I really don't want to have to remove application local settings. Have set up many connections, queries etc over the years.

**Comment by huyphams** [comment]
Hi, thank you for letting me know. You can rollback to earky version here https://tableplus.com/osx/changelog


Are you using restore closed workspace feature?

**Comment by kubaczer** [comment]
Hi,
thanks, rolling back to "Build 524" helped.

>Are you using restore closed workspace feature?
Yes, "Reopen closed workspaces at startup" is enabled.

**Comment by huyphams** [comment]
Do you opening any large query? Let me try to fix it and send you a hotpatch

**Comment by kubaczer** [comment]
Well, depends on what you mean. I have a bunch of connections with a bunch of tabs each, hard to tell what's there. But app hangs immediately, before I have a chance to actively run any query.

**Comment by huyphams** [comment]
Got it, i will send you the patch asap.

**Comment by huyphams** [comment]
Hi @kubaczer could you download this patch and see how it goes? https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

**Comment by kubaczer** [comment]
Same issue as before

**Comment by huyphams** [comment]
How about this patch @kubaczer https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
and please check the version of the build which should be 5.8.1

**Comment by huyphams** [comment]
How about this patch @kubaczer https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0
and please check the version of the build which should be 5.8.1

**Comment by kubaczer** [comment]
Same issue

**Comment by huyphams** [comment]
Hi @kubaczer if you have a chance, please try this patch: https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0

it it works, we can push a new update to address this issue.

Thanks!

**Comment by kubaczer** [comment]
Same issue, CPU at 100%, app unresponsive.
Also I'm not super comfortable testing it this way, outside of default distribution channel (which I realize is trust-based anyway)

**Comment by huyphams** [comment]
I could not reproduce the issue no matter how many SQL tabs or how much text was in those tabs. Could you please give me more details about your macOS version and how you reproduce the issue?

> which I realize is trust-based anyway

All builds are signed under the company certification and submitted to Apple to notarize, if we are not doing that, the macOS won't let you open the app. We also are fixing a very small SQL Editor layout issue so it will not get into trouble that could lead to data loss or something.

Anyway, thank you again, and happy new year.

**Comment by huyphams** [comment]
thank you for your patience,

I've reverted the app to the pre-optimize: https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0

And the newest attempt to fix the issue: https://www.dropbox.com/scl/fi/s0h7186qtnzbfogqd4nfm/TablePlus.dmg?rlkey=r6bdngvyr3wq6abwc10t5nm8b&dl=0

If you have a chance, please try these builds and see how it goes, if you prefer another way to try the patch, please let me know!

**Comment by kubaczer** [comment]
Hey, appreciate your effort and happy new year.
I'm afraid none of these two links work for me. Both lead to app hanging + 100% CPU usage.
Another thing I just noticed is that when app is left hanging its memory (ram) usage keeps growing. Few gigabytes within a minute and not stopping.

Am I the only one who runs into this issue?

My MacOS version is 14.1.2 (23B2091)

> and how you reproduce the issue?

I mean I just install the app the usual way, by dragging into apps directory. Then I access apps directory using finder and open TablePlus. A skeleton view of the app loads, I do nothing, app hangs.

I'm a programmer, lmk if there's sth technical I could do to help debug it on my end.

**Comment by huyphams** [comment]
at this point, I'm pretty it has nothing todo with the code. It could be the Apple bug or something else with the compiler.

> Am I the only one who runs into this issue?

Yes

> I'm a programmer, lmk if there's sth technical I could do to help debug it on my end.

like, how many SQL Query tab you open, and how much text in it.

**Comment by kubaczer** [comment]
So I went over all my db connections and there's only one visible SQL Query tab open (with one line of sql).
I obviously don't count tabs previously hidden by clicking "x".

Where can I find local application data? If I back up directory + remove default local data path + try to run TablePlus w/ no prior local data, will I later be able to restore backup successfully by just simply copying it back?

**Comment by huyphams** [comment]
Hi @kubaczer you could send me the settings ~/Library/Preferences/com.tinyapp.TablePlus.plist

Such as windows size, position of view frames, tableplue preferences settings etc...

This file only contains app settings, it does contains any of your database info, no connection info or anything else. Could you send it to me via nick@tableplus.com 
Thank you!

**Comment by kubaczer** [comment]
Appreciate you wanting to spend more time on this issue, but that file contains many of my db/table names, I'm not comfortable sharing it.
Looks like we've hit a wall. Too bad, but I can use old build for the next few months and then will see. Will likely try removing local data, imagine it'll help.
Thanks again for your time

**Comment by huyphams** [comment]
So you can try to remove that file (copy it to desktop and then remove the original file) and see how it goes?

**Comment by huyphams** [comment]
Hi @kubaczer please update to our latest release 528 it should fix this issue.
Thanks!

**Comment by kubaczer** [comment]
It does, awesome, thanks! 🎉 🥳
