### ISSUE TITLE
Feature Request: CTRL + P/N select automatic completion menu

### ISSUE THREAD

**Issue by tianhao** [TablePlus/TablePlus#319]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
  9.6
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
  build 93
3. The steps to reproduce this issue:
  `CTRL + P/N` can move the cursor on the editor, but when the automatic completion menu appears, `CTRL + P/N` cannot select menu item.

**Comment by huyphams** [comment]
Hi @tianhao, I don't get it, could you please clarify it again? it would be great if you can make a gif or an image. Thank you so much 👍

**Comment by tianhao** [comment]
gif: 
![default](https://user-images.githubusercontent.com/365540/37252587-4774649a-255e-11e8-87e8-bcca0edd7b69.gif)

**Comment by huyphams** [comment]
Hi, any reason why we don't use the arrow keys to move? I just curious because this is the first time I see some application use control + P/N?
btw thanks for the gif, it's much easier for me 😄

**Comment by tianhao** [comment]
Most apps in mac support `ctrl+a(beginning of line)`,`ctrl+e(end of line)`, `ctrl+f(forward)`, `ctrl+b(back)`, `ctrl+p(prev line)`, and `ctrl+n(next line)` by default, because your hands do not need to leave the main area of the keyboard. These shortcuts are inherited from emacs.

gif(10M):
![default](https://user-images.githubusercontent.com/365540/37264434-4412b222-25e8-11e8-9483-cad625dbaa4b.gif)

**Comment by huyphams** [comment]
Hey, thanks for the clarification, I will try it out now.

**Comment by huyphams** [comment]
Done in next update 👍
