### ISSUE TITLE
Feature - When filtering guess filter operator based on column type, or set default

### ISSUE THREAD

**Issue by adampatterson** [TablePlus/TablePlus#3192]
When filtering data it would be nice if I could choose the default filter operator.

I don't typically need to use contains, and switch to equals.

A possible solution would be to dynamically default to equal if the column is an int, or contains if the column is a string.

Or maybe just use the previously selected operator.

Cheers!

**Comment by huyphams** [comment]
You can click the settings button on the bottom left  od the filter to change the default
