### ISSUE TITLE
[Feature Request] Support HTTP Proxy based SQLite (like rqlite)

### ISSUE THREAD

**Issue by jmordica** [TablePlus/TablePlus#3193]
With new DB services emerging and more serverless edge databases becoming more popular, most of them are http proxy based. They speak the same SQL dialect under the hood but just over an HTTP layer vs the native access layer.

rqlite, Turso, LifeFS, Cloudflare D1, etc.. are good examples of this. They each have their own HTTP implementation and they are not all the same (which is a problem). However, rqlite is probably the most mature and sane when it comes to accessing the actual data layer itself (SQL).

**Comment by huyphams** [comment]
Hi, we supported Turso in this build, if you have a chance you can try it here: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0

**Comment by vabatta** [comment]
Is it possible to have rqlite implementation?
