### ISSUE TITLE
Text unreadable on status bar

### ISSUE THREAD

**Issue by doei** [TablePlus/TablePlus#3194]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 13.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.8.2 (528)

3. The steps to reproduce this issue:

The text on my status bar suddenly became barely readable

![image](https://github.com/TablePlus/TablePlus/assets/9954985/e59591f6-d497-4f96-af7d-6632ce972810)

I intentionally use a very aggressive shade of red when connecting to my production database, however today when opening the db I noticed how difficult to read the text had become, probably just a question of font styling (make it bold maybe ?)

The red I'm using is #FF0000 (all red no blue or green basically)

**Comment by huyphams** [comment]
I could not reproduce the issue, it is the same colour as your. Are you using macOS 13 or 14?
<img width="296" alt="Screenshot 2024-01-08 at 9 51 32 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/f3a6cd9f-c3ea-4e43-be03-2a4584c77f29">

**Comment by huyphams** [comment]
Oh never mind, I can reproduce it now :D

**Comment by huyphams** [comment]
Hi @doei if you have a chance, please download this hot patch, it should fix the issue: 
https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0
Thanks
