### ISSUE TITLE
Optimization: Grouping Feature on the Homepage

### ISSUE THREAD

**Issue by an0na** [TablePlus/TablePlus#3195]
Optimization: I would like to request an optimization for the grouping and rearranging feature on the homepage, as it is not very user-friendly.
thanks~

**Comment by huyphams** [comment]
TablePlus already has that feature @an0na

**Comment by an0na** [comment]
Apologies for the misunderstanding caused by my previous statement. Currently, there is a grouping feature on the homepage with the ability to rearrange the groups. However, the functionality for moving and categorizing the groups is not very user-friendly. Additionally, it would be greatly appreciated if the feature could support selecting multiple connections for group repositioning. Thank you.
