### ISSUE TITLE
[Bug] Clickhouse throws error when rendering empty map column

### ISSUE THREAD

**Issue by tpoll** [TablePlus/TablePlus#3196]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- I've testes this on clickhouse 2.8.x and 23.10.1.1396

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- I'm on build 528. I have verified this broke in build 524 (build 520 and lower don't have this issue).

3. The steps to reproduce this issue:

Create a clickhouse table like:

```sql
CREATE TABLE default.test1
(
    `queryId`                  String CODEC(ZSTD(1)),
    `stringAttributes`         Map(LowCardinality(String), String) CODEC(ZSTD(1))
) ENGINE = MergeTree()
ORDER BY(queryId)
```
insert data like:

```sql
INSERT INTO `default`.test1 (`queryId`, `stringAttributes`) VALUES ('yourQueryId', {})
````

run:
```sql
select * from "default".test1
```

I get an error like `Query 1 ERROR at Line 1: : vector`. If the map has data in it, everything seems to work ok.

**Comment by huyphams** [comment]
Hi @tpoll if you have a chance, please try this patch: https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0
It should fix the issue.

**Comment by tpoll** [comment]
Thanks for the fast response @huyphams! That patch did fix my issue.
