### ISSUE TITLE
Add option to middle click a table to have it open in a new tab

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#32]
Currently, you can right click a table and say 'Open in new tab'. 

Would be nice if there was an option to mouse middle wheel click on a table to open it in a new tab.

**Comment by huyphams** [comment]
Hi @brian-crane I'm on a flight. Bb later 😁

**Comment by brian-crane** [comment]
Fly safe!

**Comment by huyphams** [comment]
This feature will be available in next build (build 58). 😁

**Comment by huyphams** [comment]
@brian-crane done, checkout new build
