### ISSUE TITLE
Primary Index missing

### ISSUE THREAD

**Issue by cschaba** [TablePlus/TablePlus#320]
Hi, 

I discovered TablePlus 2 days ago and I really love it 👍 

I am using it with MySQL and found out that in the structure view the primary index are missing.

See attached screenshot from SequelPro

<img width="447" alt="screen shot 2018-03-09 at 21 42 33" src="https://user-images.githubusercontent.com/938141/37228976-d0dedc1a-23e2-11e8-84d9-f09242a0f4b1.png">

**Comment by huyphams** [comment]
I just enabled primary in in indexes section, thanks for the feedback. 👍
