### ISSUE TITLE
New integrated DB and Metrics board window and new left side toolbar are worse UX than the two separate windows previously

### ISSUE THREAD

**Issue by pbastowski** [TablePlus/TablePlus#3201]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
The issue I have is with the new user interface and not related to any driver.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.8.4 (532) 15 Jan 2024

Guys, I love TablePlus and use the Metrics Board extensively. It sits on a separate monitor for me... oh wait, it no longer does that since this new version. It is now integrated into the same window as the Database views. 

<img width="97" alt="image" src="https://github.com/TablePlus/TablePlus/assets/5649024/8cf10039-ae54-4b44-8495-12ee6c80c685">

Also, because there is this wider toolbar on the left to switch between the database and the metrics board, my carefully crafted charts no longer fit horizontally in the window on my monitor. I have more than 30 of these charts that I would have to adjust due to the new toolbar width, which for me does not add any real value. Sorry if you had to work hard to code it and implement it, but for me it just takes away horizontal space and removes previously used functionality.

Now the right side of my charts looks like below, part of it hiding and not visible without scrolling horizontally.

<img width="51" alt="image" src="https://github.com/TablePlus/TablePlus/assets/5649024/09c555a7-9794-450d-bfad-3aa91e7f1c95">

It used to look much better in the previous version.

<img width="77" alt="image" src="https://github.com/TablePlus/TablePlus/assets/5649024/e3b91760-653f-427a-8ccb-dc5f89228c35">

For me, unfortunately these two changes are a step back. If it has to be this way, could these new changes please be made an option, as I very much miss the previous version where I could put the metrics board on a separate monitor.

Can I download the previous version and install it over this update?

**Comment by huyphams** [comment]
Hi @pbastowski you can turn off those dots for cleaner. Also you can right click on the tab and select move to new window.
<img width="303" alt="Screenshot 2024-01-16 at 11 11 59 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/f7e0fc27-ae66-46fe-abc1-d198d1c63d48">

**Comment by huyphams** [comment]
It's a trade-off, where the mini tools designed on the metrics board can be more accessible.

**Comment by pbastowski** [comment]
That's great news :)

Thanks for explaining how to do it.
