### ISSUE TITLE
Table list: sorting breaks when filtered

### ISSUE THREAD

**Issue by bryan-ash** [TablePlus/TablePlus#3204]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.35

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 5.6.8 (524)

3. The steps to reproduce this issue:
  - Show the Items list
  - Observe that tables are sorted alphabetically
  - Type to filter the table list
  - Observe that tables are sorted by length of name (it appears that underscores are not considered)

#### No filtering - sort alphabetical
<img width="521" alt="image" src="https://github.com/TablePlus/TablePlus/assets/24777/e2f73934-112b-44bc-adfd-bdabd6517a6f">

#### Filtered - sort by name length(ish)!
<img width="502" alt="image" src="https://github.com/TablePlus/TablePlus/assets/24777/08a055d0-f3cc-4870-91ea-585a9ebe5eac">

**Comment by huyphams** [comment]
Bi @bryan-ash it is not sort by alphabet, it is sorted by fuzzy score, you can change the strategy here
<img width="334" alt="Screenshot 2024-01-16 at 2 41 06 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/2be207e7-fe9b-4ad8-bc7a-85c1ab01a428">

**Comment by huyphams** [comment]
But I would recommend you to use fuzzy as it will be much faster. For example you can search the table affordable housing hud detail by typing "ahhdd"

**Comment by bryan-ash** [comment]
@huyphams why does the filter matching strategy change the output sorting order?

**Comment by huyphams** [comment]
Because the matching strategy is how the app finds and sorts the results, isn't it? Fuzzy matching is the method where the strings are scored fuzzily and then sorted based on that score. So, you can see that matching and sorting cannot be separated.

The "contains" is much more simple, it just filter the string which contains the key word and sort it alphabet.

**Comment by bryan-ash** [comment]
@huyphams My issue is with how the results of the filter are displayed. This is purely a presentation issue, not related to the filtering mechanism.

- Apple
- Bannana
- Dog
- Orange

Filter this^^^ list for "a" any way you like, what should the list be?

**Comment by huyphams** [comment]
I don't think you understand how fuzziness works, so it's better to change to the "contains" method, where it should function as you expect.

**Comment by huyphams** [comment]
The purpose of fuzziness is to prioritize results with higher scores at the top; it is not based on the alphabet but rather on the score.

Therefore, if we filter by fuzziness and sort alphabetically, it contradicts the essence of fuzziness and undermines the convenience that many people expect.

**Comment by bryan-ash** [comment]
If we're getting personal, I don't think you understand the difference between a filtering algorithm, and a result presentation algorithm.

I totally understand how fuzzy matching works in my editor, I use it all day every day. The results are presented in alphabetical order.

**Comment by huyphams** [comment]
<img width="241" alt="Screenshot 2024-01-16 at 3 51 43 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/0bcdd916-e476-4aaa-99b3-bd6e3ccdf94a">

**Comment by huyphams** [comment]
In your list of tables, it's challenging to locate a specific table since they all share the same prefix, "affordable_housing....." However, employing fuzzy matching and entering only "ahb" or "ahc" makes the process much faster, as these are just some characters within the terms.

**Comment by bryan-ash** [comment]
OK, let's see if I can reframe the issue. The sort order of the Table List is bound to the matching strategy. Please provide a way to toggle the output sorting, separately from the matching strategy.
