### ISSUE TITLE
keywords automatically add back quotes

### ISSUE THREAD

**Issue by shdm2d** [TablePlus/TablePlus#3206]
1. PostgreSQL 16.0 on x86_64-apple-darwin20.6.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit:

2. Table plus Version 5.5.2 (512):

3. The steps to reproduce this issue:
keywords automatically add back quotes
<img width="990" alt="Снимок экрана 2024-01-24 в 22 25 47" src="https://github.com/TablePlus/TablePlus/assets/103522489/ab7c874c-bbb9-40bb-8345-e0d10e458317">

**Comment by huyphams** [comment]
Hi @shdm2d you should try out latest release, I think it should fix this issue. Let me know if you're still seeing it.
