### ISSUE TITLE
App crashes when I click on "close other connections"

### ISSUE THREAD

**Issue by nnahito** [TablePlus/TablePlus#3207]
## 1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL, PostgreSQL, others

## 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.8.4 (532)

## 3. The steps to reproduce this issue:
App crashes when I click on "close other connections".
Please correct it if possible, as I use it often.

**Comment by huyphams** [comment]
Hi @nnahito if you have a chance, please try this patch https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0 it should fix the issue. Please let me know if you're still seeing the bug.
Thanks

**Comment by nnahito** [comment]
A brief look at the operation showed that it worked fine.
Thank you.

**Comment by my2ter** [comment]
@huyphams 

Where is offical release for this bug fix, please?

**Comment by huyphams** [comment]
Newest release? @my2ter :/

**Comment by evolution7-developer** [comment]
AFAIK no release has fixed this issue for me. Build 568 (Version 6.1.2) still crashes when I close connections, and ends up with the app not responding


![Screenshot 2024-07-09 at 11 33 38 AM](https://github.com/TablePlus/TablePlus/assets/6734514/464ea7a2-c6e0-4639-9a17-ce4afd908315)

**Comment by my2ter** [comment]
AFAIK no release has fixed this issue for me. Build 568 (Version 6.1.2) still crashes when I close connections, and ends up with the app not responding

![Screenshot 2024-07-09 at 11 36 22 AM](https://github.com/TablePlus/TablePlus/assets/52558/a73641e8-17d2-451b-beb9-a4345a8c6613)
