### ISSUE TITLE
close other connections behaves strangely.

### ISSUE THREAD

**Issue by nnahito** [TablePlus/TablePlus#3209]
## 1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL, postgreSQL, others

## 2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.8.4 (532)

## 3. The steps to reproduce this issue:
I previously created the following issue:
https://github.com/TablePlus/TablePlus/issues/3207

I received a new build of the application here, but it did not work properly.
Clicking "Close other connections" does not work properly.

If I open multiple tabs and click on close other connections except the top tab, nothing happens.
However, when I click close other connections on the top tab, the application crashes and exits.

Please correct this one.
Thank you.

**Comment by huyphams** [comment]
Could you please try this and see how it goes?
https://www.dropbox.com/scl/fi/hnm7thxakh676o9zzlr0j/TablePlus.dmg?rlkey=d7owts2c3xe4e0pme95q2rona&dl=0
Thanks

**Comment by nnahito** [comment]
A brief look at the operation showed that it worked fine.
Thank you.
