### ISSUE TITLE
Feature Request: create SQL

### ISSUE THREAD

**Issue by cschaba** [TablePlus/TablePlus#321]
I like to have a feature like in SequelPro: print the SQL statements required to create a table (including indexes etc.)

Similar to "Table Info" in SP:

<img width="665" alt="screen shot 2018-03-09 at 21 44 49" src="https://user-images.githubusercontent.com/938141/37229171-60d233f8-23e3-11e8-807a-a9c575a90191.png">

**Comment by huyphams** [comment]
Hi, currently I have a temporary solution for this. Please press: Command + L and install the table dump. It will add a menu in the left sidebar, you can copy creation statement of the object.
More detail here: https://github.com/TablePlus/tabledump

**Comment by huyphams** [comment]
This feature will be released as a part of the build 101. You can try it here: 
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

It's duplicated with https://github.com/TablePlus/TablePlus/issues/257
