### ISSUE TITLE
[Bug] ClickHouse Maps only showing a single key pair value

### ISSUE THREAD

**Issue by tpoll** [TablePlus/TablePlus#3219]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): ClickHouse 24.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 534

3. The steps to reproduce this issue:

```sql
CREATE TABLE default.test1
(
    `queryId`                  String CODEC(ZSTD(1)),
    `stringAttributes`         Map(LowCardinality(String), String) CODEC(ZSTD(1))
) ENGINE = MergeTree()
ORDER BY(queryId)
```
insert data like:

```sql
INSERT INTO `default`.test1 (`queryId`, `stringAttributes`) VALUES ('yourQueryId', {'k1' : 'v1', 'k2' : 'v2'})
````

run:
```sql
select * from "default".test1
```

the default map in the UI shows only a single key value pair.

Running a command like `select stringAttributes.keys from "default".test1` shows the multiple keys do exist in the column.

**Comment by huyphams** [comment]
Hi @tpoll it is fixed https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0 

Thanks!
