### ISSUE TITLE
Reconnect seems to not clear certain cache and not showing tables

### ISSUE THREAD

**Issue by hyouuu** [TablePlus/TablePlus#322]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 93

3. The steps to reproduce this issue:

a. Have a few tables in database
b. Delete them
c. Recreate the same tables
d. Refresh TablePlus - they're not shown in Items
e. Close and restart TablePlus, reconnect - they're still not shown in Items
f. They may show up in Recent tab, but not Items, and do a search e.g. Users still only show in recent but not Items

I'm guessing there are some caching mechanism used and not cleared correctly

**Comment by huyphams** [comment]
Hi, @hyouuu thanks for letting me know. Did you check that tables were created successful or failed? If it was created it should show in items section. TablePlus didn't cached items if you refresh or reconnect.

**Comment by huyphams** [comment]
Close because I can't reproduce it looks like a UX misunderstood. (forgot to commit the changes)
Thanks.
