### ISSUE TITLE
Save changes to the currently opened SQL file

### ISSUE THREAD

**Issue by jolipixel** [TablePlus/TablePlus#3220]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.6.8 (424)

3. The steps to reproduce this issue:
<img width="513" alt="image" src="https://github.com/TablePlus/TablePlus/assets/1130836/4fbbd247-87f1-4511-933f-6a2f4d583f11">

It seems it is not possible to save changes to the currently opened SQL file. There is no button "save", we need to "save as" and re-select the originally opened file on MacOS : 

<img width="103" alt="image" src="https://github.com/TablePlus/TablePlus/assets/1130836/2ff8f806-bcca-4b94-b490-51c940360204">

... or maybe am I missing something?

**Comment by huyphams** [comment]
Hi @jolipixel please upgrade to our latest release.

**Comment by huyphams** [comment]
it will save automatically by default, or you can hit command + S to save it
