### ISSUE TITLE
Column Name should get populated while importing CSV instead of DO NOT IMPORT

### ISSUE THREAD

**Issue by Sampath76** [TablePlus/TablePlus#3221]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
-- PostgreSQL 14.6
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
-- Build 538
3. The steps to reproduce this issue:
-- File > Import > From CSV > Select the CSV file > Select the table
Once the table is selected, all the columns in the table should be listed on top instead of DO NOT IMPORT. 

If the table has 20+ columns it is very difficult to select each column name individually. Please check and make this enhancement, it will help a lot. 

<img width="714" alt="image" src="https://github.com/TablePlus/TablePlus/assets/20612702/1fc93ceb-34b8-49a7-a921-e6032677b988">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @Sampath76 it does not make any sense to populate those column name, you may select match with order to see the column as your describe in the issue.
<img width="356" alt="Screenshot 2024-02-14 at 3 13 22 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/b4d6cb2a-2d40-4843-b6d3-95142ca74c4d">
