### ISSUE TITLE
add message output (raise notice) for plpgsql procedures

### ISSUE THREAD

**Issue by markope** [TablePlus/TablePlus#323]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
93

3. The steps to reproduce this issue:

```
DO
$$
BEGIN
	raise notice 'test';
END
$$;
```

Where can I see the output 'test'. (It would be great to get the message output async while the plpgsql function is still running as it was in the old pgadmin3)

Very promising db client by the way, thanks!

**Comment by huyphams** [comment]
I see, thanks. I'm going to add the result message to TablePlus 👍

**Comment by jgallinari** [comment]
Hello,
I'm using PostgreSQL 9.4.4 and TablePlus build 113, and I still cannot see "raise notice" working like mentioned in the above example.
Is it normal ?
Thanks.

**Comment by huyphams** [comment]
Sorry @jgallinari when migrating to Aysnc mode for all the functions, I forgot to support raise notice.
Now it's supported: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by jgallinari** [comment]
Incredible, you're blazing fast!
Thanks a lot.

**Comment by jgallinari** [comment]
It works as expected now 👍 
There is one little issue though: the message area at the bottom is not scrollable, which is a bit annoying to see what's printed at the end.
Maybe this can be fixed in a next version ?

**Comment by huyphams** [comment]
Ah, I see, thanks @jgallinari 
I just made it scrollable: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0 👍

**Comment by jgallinari** [comment]
With such a support, I'll definitely stick to use TablePlus! :)
Thanks @huyphams
