### ISSUE TITLE
[feature request] Start the search from current location instead of "this mac"

### ISSUE THREAD

**Issue by ussher** [TablePlus/TablePlus#3230]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySql

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.8.4 (532)

4. The steps to reproduce this issue:
Go to FILE -> IMPORT -> FROM SQL DUMP 
Navigate to the location where all your SQL dumps are stored.
Attempt to use the SEARCH box to find some tables in the lower directories.

EXPECTED:
That the search will begin from the current folder and search any lower folders for the search term

ACTUAL: 
The search begins at the "this mac" level and has no way to navigate to where you currently are when not searching.

The options are "This Mac" followed by recent folders which are absolutely not very recent.

Noted: If the bug is related to data, please attach an example SQL data.
This but is not related to data
<img width="1229" alt="want" src="https://github.com/TablePlus/TablePlus/assets/1817411/34b98297-33ce-4460-b784-e05a8d3ad484">
<img width="1200" alt="where-am-i" src="https://github.com/TablePlus/TablePlus/assets/1817411/b34276a6-62cb-41ff-b783-006b2cd7d551">

**Comment by ussher** [comment]
Even if there was a way to enter the current directory into the "recently used" list that would be good.  I use Forklift as a file navigator and it looks like those "recent places" are taken from the last time i used 'finder' which was a very long time ago.

Thanks for the consideration.

**Comment by huyphams** [comment]
it's not possible to do from app. It is the macOS settings, you can change it here:
https://discussions.apple.com/thread/253688405?sortBy=best

**Comment by ussher** [comment]
That did seam to be the solution but that setting does not take effect within TablePlus:
<img width="1170" alt="this" src="https://github.com/TablePlus/TablePlus/assets/1817411/98f8e3ca-c756-41a3-b698-9740720223c4">

**Comment by huyphams** [comment]
I just tested and it works on my setup (it search from the current folder). I'm using macOS Ventura.

**Comment by ussher** [comment]
hmmm, wonder whats different about mine.  are you trying:
TABLE PLUS -> FILE -> IMPORT -> FROM SQL DUMP... -> NAVIGATE TO A SUB FOLDER -> TYPE "res" 
in order to get files beginning with "res" from the list of sql files?

For me when I do that I expected it to start searching from the sub folder but it starts from "my Mac" still.  

I'm on "MacOS Sonoma 14.3.1"

**Comment by ussher** [comment]
Found it, Thanks for your help.

On the line below the selector there is a navigation type bar that defaults to "my mac".  Next to that is the current folder, selecting it by clicking on it will get you to the current open folder.  Not obvious to me, but it solves the issue.

<img width="1205" alt="found" src="https://github.com/TablePlus/TablePlus/assets/1817411/dcfac916-3848-4264-8042-84943db20079">
