### ISSUE TITLE
Unable to connect to ANY Postgres DB after update to Version 5.8.6 (534)

### ISSUE THREAD

**Issue by MikeNatty** [TablePlus/TablePlus#3231]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Local Postgres in Docker postgres:12 container. Heroku Ec2 postgres.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.8.6 (534)

4. The steps to reproduce this issue:
Was prompted to update. Chose Update and restart.

Now I can't connect to any of my production servers on Heroku:
Error: failed: Bad file descriptor. Is the server running on that host and accepting TCP/IP connections?

Locally via Docker:
failed: fe_sendauth: no password supplied

If I re-add password:
failed: FATAL:  password authentication failed for user "theusername"

**Comment by huyphams** [comment]
Hi @MikeNatty you may check the database password, or restart the macOS it could be the key chain issue.

**Comment by MikeNatty** [comment]
Yup - a reboot worked. Cheers.
