### ISSUE TITLE
Inconsistency in whether a new tab is created or an existing tab is replaced when browsing tables

### ISSUE THREAD

**Issue by noblepreplan** [TablePlus/TablePlus#3237]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Driver: Postgres 14.3

2. TablePlus 5.9.0, build 538

3. The steps to reproduce this issue: Just click around on tables in the lefthand column, background the application for a while, come back, browse more tables.

TablePlus is very inconsistent when browsing around tables in the lefthand column. Sometimes it will open a new tab to view the table and sometimes it will replace the current tab. I cannot for the life of me determine any consistent pattern to it. This kind of unpredictable behavior does get irritating after a time. TablePlus needs to be more consistent with this, perhaps even exposing a setting to control this behavior (if one exists then I haven't seen it), maybe even being able to disable tabs all together and have only a single window for browsing table data.

**Comment by huyphams** [comment]
Hi @noblepreplan the tab behaviour just likes any other editors out there where the modified tab will be pinned. So basically if you modify its content, it will keep the tab. It will also keep the tab if you double click the item or the tab title (italic font vs normal font).
