### ISSUE TITLE
Table structure view cannot show any data?

### ISSUE THREAD

**Issue by JoeZing** [TablePlus/TablePlus#3238]
DB Server: MySQL 5.6
Version 5.9.0 (538) in macOS 14.31(Silicon)

Open any table structure view it cannot show data, it's empty, but the Info button can show the table schema.
<img width="1176" alt="image" src="https://github.com/TablePlus/TablePlus/assets/5292292/2a086cab-51e6-45e3-b104-67f5a6a29212">

**Comment by huyphams** [comment]
Hi @JoeZing currently TablePlus does not support MySQL < 5.7
