### ISSUE TITLE
Editing 40-50+ rows at once makes TablePlus freeze for up to several minutes

### ISSUE THREAD

**Issue by Fossil01** [TablePlus/TablePlus#3239]
Whenever I query some rows and need to edit the same column on all rows to a new value I select all rows and then use the sidepane (detail row) to edit the rows all at once. After doing so, pressing enter or just moving to a different column I get the beach ball for 10 seconds to several minutes to forever.

This should normally be instantaneous I think? It already happens at around 50 rows and gets worse if you edit 3000 rows for example. This has been happening for years now so not tied to a specific recent version number.

**Comment by huyphams** [comment]
Just tested with 300+ and it is instantaneously. So I think it is relate on your data or setup...

**Comment by huyphams** [comment]
Thanks, so it is only happens with the menu? btw, please don't remove our issue template questions. It helps us reproduce/track the issues.

**Comment by huyphams** [comment]
Fixed if you use the menu: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
It won't happen if you edit it directly on the text field.

**Comment by huyphams** [comment]
I couldn't reproduce the issue @Fossil01

**Comment by huyphams** [comment]
No, everything has been included in Setapp, there is no different between those builds.

**Comment by huyphams** [comment]
How to reproduce this issue @Fossil01 you still using the default in the dropdown menu?
> Has this bugfix been released yet? I just updated TablePlus via Setapp (Version 5.9.7 (547)) and it's still slow when editing one column on (in this case) 500 rows.

**Comment by huyphams** [comment]
This issue would be resolved in the build 548 on Setapp. Thanks.
