### ISSUE TITLE
[feature request] Add VACUUM and VERBOSE to postgresql reserved keyword 

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#3243]
very small request

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
15.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
 Version 5.9.0 (539)

4. The steps to reproduce this issue:

`VACUUM FULL VERBOSE ANALYZE star.fact_content_reach;`

`VACUUM` and `VERBOSE` are not colored as keyword. They should be. 

Please add. Thanks!

**Comment by huyphams** [comment]
Thanks, added!
