### ISSUE TITLE
Creating a table through the interface does not allow you to add fields and table comments.

### ISSUE THREAD

**Issue by qubaolai** [TablePlus/TablePlus#3246]
1. In the interface to create a table can not add fields and table comments, field comments can only be created after modifying the table to add, table comments seem to be only through the sql to change, I do not know if I did not find the way to use the

2. I would like to add columns to copy the table data, although you can use sql to query separately, but sometimes you do need to check a few columns and then copy a column of the situation

<img width="1137" alt="image" src="https://github.com/TablePlus/TablePlus/assets/56188459/2fe93083-c933-477b-87de-0963a7bd0826">
<img width="1358" alt="image" src="https://github.com/TablePlus/TablePlus/assets/56188459/97cd122c-d416-4abd-8889-f3881203a9e0">
<img width="799" alt="image" src="https://github.com/TablePlus/TablePlus/assets/56188459/06552b3a-ca94-4c87-8770-d612054f47e6">

**Comment by huyphams** [comment]
Hi @qubaolai, you can only add a comment to a column after the table is created. It is not possible to add it during creation.

**Comment by zookao** [comment]
This problem persists; I don't understand why such a simple function needs to be made so complicated.

**Comment by huyphams** [comment]
Not sure why it was not allowed in the first place. I think the initial issue is that database does not allow it, but now we can just append the command to add a comment after the creation.
