### ISSUE TITLE
Copy script as creation on a view really copies over a table creation, not the view creation

### ISSUE THREAD

**Issue by hanoii** [TablePlus/TablePlus#3247]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 15.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 5.9.0 (538)

4. The steps to reproduce this issue:

Right click on a view  -> Copy script as -> Creation

Maybe related to #2187

**Comment by huyphams** [comment]
currently, it does, but it is not actually view creation but table creation. Let me take a look at it.

**Comment by huyphams** [comment]
You can try this patch, it will copy the view creation correctly: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
Thanks
