### ISSUE TITLE
Add Mariadb Configuration

### ISSUE THREAD

**Issue by sebathi** [TablePlus/TablePlus#325]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

**Comment by huyphams** [comment]
Hi @sebathi you can use MySQL driver to connect to MariaDB.

**Comment by sebathi** [comment]
I know, but it is nicer to have them identified.

**Comment by ManjotS** [comment]
Also starting with MySQL 8 and MariaDB 10.3 and especially 10.4 there are differences in authentication and database workings. 

You would ideally be using each databae's own driver for their connections. ie, don't rely on the mysql connector/driver for MariaDB.

**Comment by huyphams** [comment]
Thanks @ManjotS for the information, I will add it on the build 196

**Comment by Operatives** [comment]
Definitely having trouble connecting to MariaDB v10.4

**Comment by bcorcoran** [comment]
Status on this? We still only have Mysql 5.x and Mysql 8.x as options.

**Comment by huyphams** [comment]
I added it on WIP @bcorcoran I hope that I can make it in the next update.

**Comment by huyphams** [comment]
it's implemented on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks all.
