### ISSUE TITLE
Currently open tabs close when switching between schemas

### ISSUE THREAD

**Issue by droully** [TablePlus/TablePlus#3250]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 13.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Buld 260 

3. The steps to reproduce this issue:

Open multiple data table tabs within a single schema in TablePlus.
Switch to a different schema within the same database.
Observe that previously opened tabs are now closed.

4. Expected behavior:

Open tabs should be kept between schema switching.

I haven't updated nor changed any settings that could've caused this change in behavior. A troublesome workaround I found is to edit a table and then, when switching schema, it's tab remains open. 

Please help, this has a really negative affect on my workflow.

**Comment by ekuzovlev** [comment]
Also encountered such behavior. Very inconvenient.

**Comment by coltonbrugger** [comment]
I'm noticing this in TablePlus Version 5.9.2 (542) on Mac as well when using SQL Server.

Additionally, I see that opening two windows for the same DB connection (something I never thought to do before) doesn't even help me to be able to maintain visibility on objects from multiple DB schemas.

TablePlus has been my go-to tool for years now. This has upended my workflow.

I'm eager to see a fix for this. I am willing to provide a tip if it helps complete it in short order.

**Comment by huyphams** [comment]
You can download this patch and then disable this option, it won't close the item.
https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
<img width="467" alt="Screenshot 2024-03-28 at 3 22 15 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/6704f621-e679-4103-bc48-d870d4e2daae">

**Comment by droully** [comment]
is there any chance for a fix for windows?

**Comment by huyphams** [comment]
The TablePlus Windows will be fixed in the next update.

**Comment by coltonbrugger** [comment]
@huyphams 

This is still occurring for me.

I am using TablePlus Version 5.9.6 (546) on macOS Sonoma 14.4.1.

Steps to reproduce:
- open new connection to MSSQL database
- open a table ("TableA") on the default schema (in my case, "dbo" schema) by double-clicking the object's name in left sidebar
  - the table opens in a new tab (tab #1) as expected
- switch to another schema (in my case, "web" schema)
- open a stored procedure from "web" schema by double-clicking the object's name in left sidebar
  - the object definition opens in a new tab (tab #2) as expected
- switch back to original schema ("dbo")
  - *unexpected side effect/bug*: the tab #2 (with definition of web.StoredProcedureExample) closes unexpectly and only Tab #1 remains open 

Thanks for your consideration of this issue!

**Comment by huyphams** [comment]
Oh I see @coltonbrugger there is a bug with function tab. Let me fix it.

**Comment by huyphams** [comment]
You can download the patch here @coltonbrugger https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0

it won't close function/sequence tab anymore!
