### ISSUE TITLE
[Feature request]: Show include columns of an index

### ISSUE THREAD

**Issue by aiai-guenz** [TablePlus/TablePlus#3252]
Some DBMS (PostgreSQL, MS SQL, ...) allow columns to be included into an index, e.g.
```
CREATE INDEX ix_demo
ON public.demo_table (column1, column2)
INCLUDE (column3);
```

It would be nice to see these columns (`column3` in the example above) in the `Structure` view of a table, maybe next to the `condition` column.

**Comment by huyphams** [comment]
Already added, will be released in the next update!
