### ISSUE TITLE
[Linux] Binary columns are not displayed correctly

### ISSUE THREAD

**Issue by janpetto** [TablePlus/TablePlus#3253]
On Linux, binary values are displayed as garbled text instead of hex. On MacOS, this just works as expected and shows hex-encoded text. See also the attached image.

#### How to reproduce

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 1.1.4 (246) on Ubuntu 22.04.4

3. The steps to reproduce this issue:
Create any table with a column with type binary, insert something, and select it.

![image](https://github.com/TablePlus/TablePlus/assets/6023552/91657ea0-0112-43bd-a023-f817945be83d)

**Comment by huyphams** [comment]
Fixed now!
