### ISSUE TITLE
Messages/logs are cleared

### ISSUE THREAD

**Issue by fabswt** [TablePlus/TablePlus#3254]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Postgres

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 5.9.0 (538)

3. The steps to reproduce this issue:

Run, for examples, 160 queries and see the issue.

My issue is that the messages/logs output automatically clears previous messages.

I ran a long series of queries (160 total) and, as the execution progressed, older messages in the 'Message' tab were automatically removed. This is annoying, because some of those messages were error messages, other were notices. In any case, they were gone. So I had to restore the database and start over to see the messages again and be able to act on them.

I did not find a setting in the preferences that would explain this. If there's a hard-coded limit to the number of messages, it would be nice to be able to adjust it and set it to unlimited.

P.S.: it's also worth noting that the queries (mostly types and tables creation, and index creations) all resulted in a SINGLE Query tab being opened.

**Comment by huyphams** [comment]
so in your queries has `RAISE NOTICE`? it is an edge case I think

**Comment by huyphams** [comment]
You can download the patch here, it should fix the issue: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
