### ISSUE TITLE
[Bug]: Safe mode doesn't warn on update when running a few queries.

### ISSUE THREAD

**Issue by yeysman** [TablePlus/TablePlus#3257]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **SQL Server 2019 (DBVERSION_74)**
Notice: this issue might affect other drivers.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **Version 5.9.2 (542)**

3. The steps to reproduce this issue:
Select both queries and run them with chosen safe mode "Alert mode 2"
`select top 10 * from table1 order by 1 desc`
`update table1 set columnName='some value' where tableColumnId=1`

TablePlus will not alert the update action.

**Comment by huyphams** [comment]
it's fixed now, if you have a chance, you can download the test build here: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0

**Comment by yeysman** [comment]
@huyphams 
From my check seems works fine.
Thank you!
