### ISSUE TITLE
Metrics Board Connectors Issue

### ISSUE THREAD

**Issue by PH7-Jack** [TablePlus/TablePlus#3258]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): LATEST 538

3. The steps to reproduce this issue: 
   - Create a metrics board with a input field
   - Close the app
   - Open again
   - All the connected items will not be working anymore until re-connect them again

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @PH7-Jack if you have a chance, you can download this patch, it should fix the issue: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
Let me know if you're still seeing the bug.
