### ISSUE TITLE
"Open anything" does not search across schemas anymore

### ISSUE THREAD

**Issue by evolkmann** [TablePlus/TablePlus#3259]
- Before my last upgrade, I was able to open tables etc. from other schemas using the CMD + P "Open anything" search
- Now, this is not possible anymore; I can only find things in the current schema
- I do not not the exact version before the update, but it can only be a few builds

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 14.10

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 542

5. The steps to reproduce this issue:

Open a database with multiple schemas and search for a table in another than currently opened schema. It will not be there (unlike in previous versions)

**Comment by kez** [comment]
Also confirmed in Version 5.9.2 (542) on PostgreSQL 15.4.  I *believe* I have only just upgraded 1 version but can't prove it.

**Comment by stevencch99** [comment]
The same issue from build 545, this became so much more painful 🙇🏻‍♂️

**Comment by huyphams** [comment]
Thanks, we bring back prefetch all items settings, just uncheck this settings on the sidebar.
https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
<img width="428" alt="Screenshot 2024-03-27 at 12 06 32 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/7cd730b2-be00-4e20-b853-09244fbc11d0">

**Comment by wit3** [comment]
Any patch for window realease?

> Thanks, we bring back prefetch all items settings, just uncheck this settings on the sidebar. https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0 <img alt="Screenshot 2024-03-27 at 12 06 32 PM" width="428" src="https://private-user-images.githubusercontent.com/3654622/317132456-7cd730b2-be00-4e20-b853-09244fbc11d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDAyODQsIm5iZiI6MTcxMTY5OTk4NCwicGF0aCI6Ii8zNjU0NjIyLzMxNzEzMjQ1Ni03Y2Q3MzBiMi1iZTAwLTRlMjAtYjg1My0wOTI0NGZiYzExZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMDgxMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU1NTBlMTc1M2RiNTVkMDA0MWNkMTBlY2Y5NjY4MDlkOTBkNDM3Mzg3YWRkMDFhYTljMTdmMDI4NzBlMGZjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ETHCWg-HkLbhAI6qacP5ppjyzKX0LcCDFiEZkL3DMuw">

**Comment by huyphams** [comment]
Please upgrade the Windows app to latest release, you will see this option @wit3
