### ISSUE TITLE
Set value NULL cause crash

### ISSUE THREAD

**Issue by khachin** [TablePlus/TablePlus#3260]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MariaDB 10.11.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 4.5.0 (396) on macOS Big Sur 11.6

3. The steps to reproduce this issue: connect to a database, open a table, choose a record, right-click on a column, "Set Value" -> "NULL", and repeat this action to other records, TablePlus will crash when doing this 3-5 times 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @khachin your build is too old, the bug has been fixed for a long time, please upgrade to our newest release.
