### ISSUE TITLE
PostgreSQL - table sequences - incorrect list when name is same in different schemas

### ISSUE THREAD

**Issue by jvyoralek** [TablePlus/TablePlus#3261]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 16.2 running in docker from official image

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.9.2 (542)

3. The steps to reproduce this issue:
- create schema with any name, e.g. `schema1`
- create table with name e.g. `table1` and with one column id using sequence
    
```sql
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS schema1.table1_id_seq;

-- Table Definition
CREATE TABLE "schema1"."table1" (
    "id" int4 NOT NULL DEFAULT nextval('schema1.table1_id_seq'::regclass),
    PRIMARY KEY ("id")
);
```

- create another schema, e.g. `schema2`
- create table inside second schema with same name as in first schema `table1` and same column + sequence

```sql
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS schema2.table1_id_seq;

-- Table Definition
CREATE TABLE "schema2"."table1" (
    "id" int4 NOT NULL DEFAULT nextval('schema2.table1_id_seq'::regclass),
    PRIMARY KEY ("id")
);
```

Issue is in list of sequences in items list where **both sequences are included** despite it should show objects only from one schema. Sequences are correctly created in different schemas.

<img width="1127" alt="image" src="https://github.com/TablePlus/TablePlus/assets/15640266/683c28c9-28bb-40d9-b89a-e15084009a41">

Detail of sequence not showing correct data for one of duplicates
<img width="915" alt="image" src="https://github.com/TablePlus/TablePlus/assets/15640266/e7662f02-25c7-4e91-bbda-cde59c91c22a">

**Comment by huyphams** [comment]
Hi @jvyoralek if you have a chance, could you try this build and see how it goes? https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0

**Comment by jvyoralek** [comment]
Hi @huyphams,

it's almost perfect. Duplicity is gone, but i see issue in owner:
<img width="1127" alt="image" src="https://github.com/TablePlus/TablePlus/assets/15640266/7929ea6c-f490-4cd2-95e6-5b46a394727e">

According to [PostgreSQL docs](https://www.postgresql.org/docs/current/sql-createsequence.html) it should be in form `OWNED BY { table_name.column_name | NONE } ]`

```sql
CREATE [ { TEMPORARY | TEMP } | UNLOGGED ] SEQUENCE [ IF NOT EXISTS ] name
    [ AS data_type ]
    [ INCREMENT [ BY ] increment ]
    [ MINVALUE minvalue | NO MINVALUE ] [ MAXVALUE maxvalue | NO MAXVALUE ]
    [ START [ WITH ] start ] [ CACHE cache ] [ [ NO ] CYCLE ]
    [ OWNED BY { table_name.column_name | NONE } ]
```

**Comment by huyphams** [comment]
Hi @jvyoralek I fixed it: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
Thanks
