### ISSUE TITLE
Option to select default search - Any column, instead of raw SQL

### ISSUE THREAD

**Issue by GregaUNK** [TablePlus/TablePlus#3264]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MYSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
542

3. The steps to reproduce this issue:
I would like to have globally selected Any Column, for search in table.

**Comment by huyphams** [comment]
Here @GregaUNK 
<img width="418" alt="Screenshot 2024-03-29 at 3 58 36 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/e17ea14c-c690-40cd-871a-9e77f6b342f9">

**Comment by GregaUNK** [comment]
Thanks! I have never noticed that 🙄 😄
