### ISSUE TITLE
pgsql DDL has no index statement

### ISSUE THREAD

**Issue by shenghui0779** [TablePlus/TablePlus#3265]
### Structure

![image](https://github.com/TablePlus/TablePlus/assets/67535398/ada4cf9a-738a-4860-9e8b-314a734e72d8)

### DDL

![image](https://github.com/TablePlus/TablePlus/assets/67535398/17672a7b-cfa6-4bea-9676-79e78f652c0d)

### DDL from Postico

![image](https://github.com/TablePlus/TablePlus/assets/67535398/3e1d0519-36dc-47d4-af04-74efb4f221bb)

**Comment by huyphams** [comment]
Thanks, we added this feature in the up coming release.
