### ISSUE TITLE
Delay in startup on Mac

### ISSUE THREAD

**Issue by imoby** [TablePlus/TablePlus#3266]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
547
3. The steps to reproduce this issue:
- Hard to reproduce, it happens randomly but often when I restart my mac or have not opened TablePlus in a couple of days it hangs on the dock loading for like a good 20 seconds before opening
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @imoby you're using beta build, which is intel only and require rosetta (becuase it supports Oracle)
Please do not use beta build and rollback to official release. It is faster 25-50%
(You can download the build on website and turn off beta updates)
We will move away fron oracle native to another lib which support arm.
Thanks
