### ISSUE TITLE
How can i add or change mysql table comments with tableplus

### ISSUE THREAD

**Issue by xuanyan** [TablePlus/TablePlus#3269]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.9.6 (546)
3. The steps to reproduce this issue:
cant find the operation to change the table comment.

Noted: If the bug is related to data, please attach an example SQL data.
ALTER TABLE my_table COMMENT='my private table';

**Comment by huyphams** [comment]
You can click the section here and then edit the comment of the tables

![Screenshot 2024-04-05 at 9 13 29 AM](https://github.com/TablePlus/TablePlus/assets/3654622/e4aaae6a-18c6-4e4c-9596-680372d4142b)

**Comment by huyphams** [comment]
![Screenshot 2024-04-05 at 9 14 44 AM](https://github.com/TablePlus/TablePlus/assets/3654622/5e89337e-b4c7-46cd-b0ff-676a32f8f658)

**Comment by Im-SAMW** [comment]
Too troublesome. This does not conform to the usage habits of normal people.

**Comment by huyphams** [comment]
"Because we are currently not promoting this feature @Im-SAMW, it is a trade-off for a simple UI, and we have not yet found a way to improve it. However, we may have an elegant idea in the future.

**Comment by Im-SAMW** [comment]
I hope it will become more and more good! @huyphams
