### ISSUE TITLE
Feature request - Please allow for customisable hotkeys / shortcuts

### ISSUE THREAD

**Issue by hdra** [TablePlus/TablePlus#327]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Irrelevant

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 93

Hi, first of all, 👍 on the awesome app!

That said, please allow for hotkeys customisation. 

I would very much prefer the standard `ctrl+tab` and `ctrl+shift+tab` for navigating around tabs since thats what I'm used to and my `ctrl+]` is taken up for windows management. 

P.S. I have just bought the happy plan just for this feature alone. I thought the preference panel was greyed out because I was on the free plan. Thats how much I want/need this feature. 🙏🙏🙏

**Comment by huyphams** [comment]
Hi @hdra we are working on it and it will be allowed to customize soon 👍Thanks for the purchasing.

**Comment by huyphams** [comment]
I added it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Or you guy can check for update (with beta build enable in the preferences).
Thanks all!

**Comment by georgexsh** [comment]
@huyphams it is still (build 226) impossible to customize tab switching to use `ctrl+tab`.

**Comment by jim256** [comment]
> @huyphams it is still (build 226) impossible to customize tab switching to use `ctrl+tab`.

I'm also experiencing this and would *really* like to see it made possible.

**Comment by johanrosenson** [comment]
@huyphams Is there any plans to make it possible to set ctrl+tab and ctrl+shift+tab as custom hotkeys? right now it is impossible to do so.
