### ISSUE TITLE
Upgrade the 'beautify' function

### ISSUE THREAD

**Issue by jpike88** [TablePlus/TablePlus#3271]
The beautify function is barely usable, it formats the query into a big mess.

I use this VSCode extension for formatting my queries before I paste them into table plus:

https://marketplace.visualstudio.com/items?itemName=adpyke.vscode-sql-formatter

It uses the below library to perform the formatting.
https://github.com/kufii/sql-formatter-plus?tab=readme-ov-file

It would be nice to either bundle the above formatter into your application, or allow for a custom formatting so I can override the beautify command to run a custom terminal command to perform the beautify step.

**Comment by huyphams** [comment]
I think the formatter plugin did a better job. Install via command + L

**Comment by jpike88** [comment]
ah yes way better. Should be packaged as default I think, cause now I have to get all my devs to do this step too

**Comment by huyphams** [comment]
Yup, we will replace the default SQL formatter with the plugin in the future release, it is already on our backlog.

**Comment by jpike88** [comment]
ah ok... we're all apple boys
