### ISSUE TITLE
Unable to detect table

### ISSUE THREAD

**Issue by haykoyk** [TablePlus/TablePlus#3272]
1. Microsoft SQL Server
2. Version 5.9.6 (546). MacOSX

For instance I have a query SELECT * FROM Marketplace.ConnectionEntity WITH(NoLock) where Id = 329;
When I open TablePlus my environment is opened and also my Tabs where this query is.
The first time I execute it I can not edit field. Neither in the grid or right side bar.
Then I change the Query by typing again Marketplace.ConnectionEntity (the same and with the right cases) and execute the query and no I can edit the data everywhere. In other cases this is also a problem. You need to seriously look into this please, 
because the last versions its buggy and doesn't work properly. Editing is just one of the major feature I use for my environment though.

Thank you!

**Comment by haykoyk** [comment]
I reverted back to Version 5.9.0 (538) and every query even combinations like these
SELECT top(500)Description, ShopId, * FROM Marketplace.ConnectionEntity WITH(NoLock) WHERE Description LIKE '%xxx%' 
work properly! So it's definititely something wrong in the latest versions.

**Comment by huyphams** [comment]
You may disable this feature on the newest release and it should work, I think
<img width="592" alt="Screenshot 2024-04-11 at 3 46 51 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/3872ff14-20a3-4922-8afd-b818967ab1ce">

**Comment by haykoyk** [comment]
Thank you this works with the latest version :-) But maybe this should be disabled by default because people are used to certain functionality and they don't know how to find this option. I also searched for the sliders button to get these options :-) 

Thank you for your quick answer. You can close this.

**Comment by robertn702** [comment]
@huyphams I am getting the same error and I'm not seeing a settings option in the context menu. I'm connect to a `libSQL` db and am on version `Version 5.9.7 (547)`.

<img width="224" alt="image" src="https://github.com/TablePlus/TablePlus/assets/8119609/da27d4c4-be1c-4530-ab19-ebc2f93f80bd">

**Comment by huyphams** [comment]
it's fixed on the latest release @robertn702 thanks for letting me know
