### ISSUE TITLE
PostgreSQL universal search no longer searches for tables across schemas

### ISSUE THREAD

**Issue by sean-goodlab** [TablePlus/TablePlus#3277]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 13.13 (using AWS RDS—not Aurora)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 546

3. The steps to reproduce this issue:
a. Connect to a DB with multiple schemas to which you have access
b. Open Search Anything (Command + P)
c. Search for a table on a different schema
d. Observed: the table doesn't appear in the search (even though it did a few versions ago)
e. It works as expected if I open the other schema, then switch back to a different schema (i.e., it seems to pull the table information into a cache of some kind)

Notes:
1. It is also an issue when writing queries, the schema doesn't autocomplete (even though I have the setting enabled), unless I navigate to the other schema and back again first
2. It is also an issue when clicking the arrow next to a foreign key cell of data, unless I navigate to the other schema and back again first

**Comment by huyphams** [comment]
Due to the performance issue, this feature was turned off  by default. You can enable it by uncheck this.
<img width="442" alt="Screenshot 2024-04-19 at 11 59 14 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/8013d0e7-657a-4dcc-bd0f-564223a41d12">

**Comment by sean-goodlab** [comment]
That solved it. Thank you.
