### ISSUE TITLE
[Bug]: SQL server -  3 issues in "All results in one tab"

### ISSUE THREAD

**Issue by yeysman** [TablePlus/TablePlus#3278]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**SQL server 2019 (DBVERSION_74)**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Version 5.9.8 (548)**

3. The steps to reproduce this issue:

- Run two queries.
- Click column name to sort values - **issue 1**: sorting doesn't work!
Try to open right bar - **Issues 2**: all values will be replaced with "EMPTY"
Repeat first two steps, but instead of opening right bar, simply switch screen and then back - **issues 3**: all values are replaced to "EMPTY"

Noted: If the bug is related to data, please attach an example SQL data.

https://github.com/TablePlus/TablePlus/assets/3490139/8b7d42ee-4fb4-40b2-944c-c8af6226948f

In addition:
Tried to reproduce this issue with MySQL - seems it works as expected. So, i can assume the issue doesn't affect all available types of servers.

**Comment by huyphams** [comment]
Hi @yeysman you can temporary fix the issue by putting the` ;` at the end of the query.

**Comment by yeysman** [comment]
Hi @huyphams,
Nope. It doesn't help.
I tried semicolon after each query, and one after all of them - same result. Cells value become "empty"

**Comment by huyphams** [comment]
Could you show me a screencast when you put the semicolon?

**Comment by yeysman** [comment]
@huyphams, sure. Please see the chapter 2 below. :)

https://github.com/TablePlus/TablePlus/assets/3490139/0823cc27-5bf5-4419-8a3f-35897cec4d98

**Comment by huyphams** [comment]
Ah I think I know the issue. it only happen in SQL Server as TablePlus wrap all the queries into one transactions (because SQL Server has variables support).

**Comment by yeysman** [comment]
@huyphams,
Seems so. As i mentioned above, i was not able to reproduce it with mysql.

Too many issues TP has with SQL server support :(

**Comment by huyphams** [comment]
Which version of macOS are you using @yeysman I could not reproduce the issue on the macOS Ventura.

**Comment by yeysman** [comment]
Hello @huyphams,
I recorded videos on macOS Catalina.
But I have the same behavior in my second Mac which works on Sonoma.

**Comment by huyphams** [comment]
Hi @yeysman thank you for letting me know. The bug has been fixed, youc an download the build here: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0

Let me know if you're still seeing the bug.

**Comment by yeysman** [comment]
@huyphams,
Thank you! This build solves this issue.
