### ISSUE TITLE
SQL tabs not visible on startup

### ISSUE THREAD

**Issue by mrmkrs** [TablePlus/TablePlus#3279]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.9.8 (548)

3. The steps to reproduce this issue:
* Open a workspace
* Open a few SQL tabs with queries in them
* Make sure "Restore recent queries" is on
* Command+Q
* Open TablePlus, open the same connection

Expected:
I should see every SQL tab that was open before closing the workspace

Actual:
No tabs are visible. But, if I click on the SQL button, a tab appears with the original query in it. When I hit Command+T, a new tab is visible which also contains the queries I left earlier.

I can reproduce this on every connection.
I have a Macbook Pro M3, MacOS version 14.4.1 (23E224)

**Comment by huyphams** [comment]
Hi, it's not supposed to work like that. You can enable the option to open recently closed workspaces here.

![Screenshot 2024-04-22 at 1 51 18 PM](https://github.com/TablePlus/TablePlus/assets/3654622/86c6a034-920e-4676-b4fe-ce79728be81b)

**Comment by huyphams** [comment]
"Restore recent queries" mean TablePlus will save the queries to temporary files and will show them the next time you open the SQL tab. it does mean that the app will open those tabs next time you startup. But the option in the app settings does.

**Comment by mrmkrs** [comment]
Thank you for the fast response and clarification!

I use different connections on a daily basis and find the 'Reopen closed workspaces' option not helpful because changes are I want to open different connection the next time I open TablePlus. But, when I do want to open a previous connection, I would like to 'start were I left off' so it would help to view all sql tabs that have content in them in advance. Kind of like an IDE remembering the exact state of a project after you close and open it.
