### ISSUE TITLE
request operation backward OS compatibility: OS 10.5 - 11, or at least 9 - 11

### ISSUE THREAD

**Issue by ninetreesdesign** [TablePlus/TablePlus#328]
My newest system is 10.10.x

I would request operation across my machines; 
backward OS compatibility: OS 10.5 - 11, or at least 9 - 11. 
More and more new software has a tree of conditional dependencies of OS/driver/CPU that add user stress and slow adoption and extra integration support.

**Comment by huyphams** [comment]
Hi @ninetreesdesign 
TablePlus is using a lot of modern APIs, that means if we support old OS, it may break many things.
I'm afraid that TablePlus will not available for OS < 10.11 for a long time.

**Comment by huyphams** [comment]
We can't support OSX < 10.11, see this issue: https://github.com/TablePlus/TablePlus/issues/37
