### ISSUE TITLE
Unable to find table in PostgreSQL via CMD + P before opening the schema

### ISSUE THREAD

**Issue by meijdenmedia** [TablePlus/TablePlus#3286]
#### Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 15.6

#### Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 6.0.0 (550)

#### The steps to reproduce this issue:
1. Open TablePlus
2. use CMD + P to search a table in a schema which you have not yet opened
3. (You will not find it.)
4. Open the schema in which the table is living via the switch select (left bottom)
5. Switch back to the previous schema
6. Use CMD + P to search the table, you can now find it

**Comment by huyphams** [comment]
Hi @meijdenmedia 
Turn off this option you will be able to search in all schema without preloading it.
<img width="472" alt="Screenshot 2024-05-01 at 4 23 29 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/184ab366-6ae7-44ac-83b6-4f102014f3a6">

**Comment by meijdenmedia** [comment]
Life saver! Thanks. Maybe it's better to implement this the other way around? 
Seems to me like this feature is annoying for a small portion of big power users?
