### ISSUE TITLE
When renaming a table or a column, square brackets are added to the name.

### ISSUE THREAD

**Issue by polypressure** [TablePlus/TablePlus#329]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 93

3. The steps to reproduce this issue:
Rename a table or a column, save/commit the change, and refresh. The table or column name will have square brackets. For example, when renaming a table named `old_table` to `new_table`, the name will be `[new_table]` rather than just `table`. Same for a column.

To workaround this and remove the square brackets from the table or column name, I have to manually type in the following SQL (this example is for a renamed column that has had the square brackets added):

```
sp_rename 'my_table.[[new_column_name]]]', 'new_column_name', 'COLUMN'
```

**Comment by huyphams** [comment]
Hey thanks, it will be fixed and released at the end of this week.
