### ISSUE TITLE
Tables do not appear in Items sidebar

### ISSUE THREAD

**Issue by aaronsharff** [TablePlus/TablePlus#3291]
1. PostgreSQL 15.3
2. TablePlus Version 6.0.0 (550)
3. Issue:
 - No tables appear in sidebar
![image](https://github.com/TablePlus/TablePlus/assets/24624865/adf2d267-bf8c-441d-a466-243c5aefc053)

 - `(SELECT table_name, table_schema, table_type FROM information_schema.tables) UNION (SELECT c.relname AS table_name, n.nspname AS table_schema, 'MATERIALIZED VIEW' FROM pg_catalog.pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = 'm');` returns results as expected
 - Refreshing TablePlus does not fix the issue
 - Only one schema available in schema dropdown

**Comment by huyphams** [comment]
Hi @aaronsharff are you sure that the public schema has items?

**Comment by aaronsharff** [comment]
> Hi @aaronsharff are you sure that the public schema has items?

Yes, `table_schema = 'public'` has items

**Comment by huyphams** [comment]
We use this query to get the item list, can you run it and show me the result?

> SELECT table_name, table_schema, table_type FROM information_schema.tables WHERE table_schema='schema_name'


SELECT table_name, table_schema, table_type FROM information_schema.tables WHERE table_schema='public'

**Comment by aaronsharff** [comment]
<img width="697" alt="image" src="https://github.com/TablePlus/TablePlus/assets/24624865/d5f0dbb9-0f74-4867-88f2-9d162354c78e">

**Comment by aaronsharff** [comment]
Yes, thank you, that's my mistake. For posterity, I had chosen a "Redshift" connection but it was actually a Postgres database. All good here now.

**Comment by huyphams** [comment]
Thanks, redshift has a different structure so you should use the correct driver. Closing this issue for now.
