### ISSUE TITLE
Cyrillic symbols aren't shown in the table

### ISSUE THREAD

**Issue by VadimMuhtarov** [TablePlus/TablePlus#3292]
<img width="370" alt="Screenshot 2024-05-06 at 21 36 51" src="https://github.com/TablePlus/TablePlus/assets/17072773/85b62080-5d76-4ab3-8246-3c8c554bba88">

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 19

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 6.0.0 (551), Sonoma 14.4.1 (23E224)

3. The steps to reproduce this issue:
Open any table with Cyrillic symbols, "?" will be shown instead of actual letters

**Comment by huyphams** [comment]
Hi @VadimMuhtarov You could change the settings here and see how it goes?
<img width="221" alt="Screenshot 2024-05-07 at 1 42 59 AM" src="https://github.com/TablePlus/TablePlus/assets/3654622/04134e9d-ea89-4b5c-b764-a81ca6eb6670">

**Comment by VadimMuhtarov** [comment]
It helped, thanks!

**Comment by VadimMuhtarov** [comment]
@huyphams Hi again. On the latest beta build for ARM I can't set any other encoding, "Default" is always chosen after restart and I get "Decode error" in the table

**Comment by huyphams** [comment]
Hi @VadimMuhtarov can you give me an example of the table creation so I can test the new encoding? Thanks

**Comment by VadimMuhtarov** [comment]
-- Create table
CREATE TABLE names (
    name VARCHAR2(50)
);

-- Insert values
INSERT INTO names (name) VALUES ('Альмира');
INSERT INTO names (name) VALUES ('Асхат');

**Comment by huyphams** [comment]
Hi @VadimMuhtarov can you try this patch and see how it goes? https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0

**Comment by VadimMuhtarov** [comment]
Hi, I tried both WIN1252 and UTF8 and still get this error
<img width="387" alt="Screenshot 2024-06-28 at 07 58 04" src="https://github.com/TablePlus/TablePlus/assets/17072773/41d0f954-c975-468f-a4cd-b97e34340079">
<img width="323" alt="Screenshot 2024-06-28 at 07 58 21" src="https://github.com/TablePlus/TablePlus/assets/17072773/6c562f58-dc3f-4383-9629-28335ec665fb">

**Comment by VadimMuhtarov** [comment]
Looks like this error is not only for VARCHAR2
<img width="976" alt="Screenshot 2024-06-28 at 09 08 14" src="https://github.com/TablePlus/TablePlus/assets/17072773/f4c6364e-3e00-49c4-abde-caa30e0838b6">
<img width="267" alt="Screenshot 2024-06-28 at 09 08 31" src="https://github.com/TablePlus/TablePlus/assets/17072773/778c6b7f-a479-485d-8f76-f221af13415e">

**Comment by huyphams** [comment]
Ah okie so it only error with NULL values and you can actually see the none null values?

**Comment by VadimMuhtarov** [comment]
Yes

**Comment by huyphams** [comment]
Can you try this patch and see how it goes: https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
Thanks!

**Comment by VadimMuhtarov** [comment]
It's fixed now, thanks
