### ISSUE TITLE
Unable to create backup of mysql 8.0 database

### ISSUE THREAD

**Issue by Palindromordnilap** [TablePlus/TablePlus#3295]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.35
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 550
3. The steps to reproduce this issue:
Open the backup window, select the connection, a database and start a backup.
The backup finishes instantly, and the created file only contains the following error message:

```
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
```

I've tried it both with the default option and no options
The MySQL version in the backup window is set to 8.0, but using 5.7 results in the same error (which is to be expected)

**Comment by huyphams** [comment]
Hi @Palindromordnilap please try to clear the invalid flag and try agian, you may entered an invalid flags.

**Comment by Palindromordnilap** [comment]
Thanks for the quick reply! I've tried it with no flags/options at all, and still get the same error
<img width="205" alt="Screenshot 2024-05-08 at 10 38 46" src="https://github.com/TablePlus/TablePlus/assets/125550563/aa1c8203-d5a0-4241-830e-468275bca241">

**Comment by huyphams** [comment]
Do your database name has any special characters @Palindromordnilap ?

**Comment by Palindromordnilap** [comment]
Huh, I just realized there was no username set in the connection settings. Setting a value there fixed the issue.

**Comment by alxndrmlr** [comment]
I know this was closed but it would be better if TablePlus gave an error instead of saying "Backup database completed"

<img width="454" alt="image" src="https://github.com/user-attachments/assets/ac7931ac-7f7b-45c8-a2ce-701e2fd53f93">

Ideally whatever is running under the hood should require the username be set instead of just running the command and piping the output in to the xyz.dump file.
