### ISSUE TITLE
Require DB password to lock DB

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#33]
Currently no password is required to lock DB, so sometimes I lock the DB by accident, then have to take time to enter password to unlock.

Perhaps require password to lock / unlock.  In the settings maybe you could have 4 options:

a. Require password on Unlock only.
b. Require password on Lock only.
c. Require password on Lock and Unlock.
d. Require **NO** password to Lock and Unlock

**Comment by huyphams** [comment]
@brian-crane I think the most safe way to lock/unlock database is follow Apple UX. Go to Apple Preferences > Security & Privacy you can see Apple do the same way with TablePlus.
