### ISSUE TITLE
Metrics board multiple input field / dropdowns possible?

### ISSUE THREAD

**Issue by Maddoc42** [TablePlus/TablePlus#3302]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostreSQL 14.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 550

3. The steps to reproduce this issue:

- In the metrics board tool, create a line chart with query `SELECT $range as range, $input as input;`
- Attach one Input Field (`range`) and one Dropdown to the chart (`input`)
- Input field is configured to "Submit value on change", input field "Submit on Enter"
- Graph will always throw a syntax error

It looks like only one of the two input values is being submitted to the query, the other is empty, hence the syntax error.

Is it not possible to have multiple inputs connected to a single chart?

**Comment by huyphams** [comment]
Ops it looks like a bug, you should be able to chain multiple inputs like this. But somehow it does not work as expected. Going to fix it.
<img width="973" alt="Screenshot 2024-05-16 at 5 14 27 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/048d3617-f527-4600-aba2-4fab9445b367">

**Comment by huyphams** [comment]
The event in Metrics board is push only (not pull), so you can have more than 2 signal to chart at a time. Instead of doing that, you can chain multiple inputs as above.
@Maddoc42

**Comment by Maddoc42** [comment]
Thanks for taking the time @huyphams ! 🙏 I was able to create a input chain as you suggested. This requires all inputs except the last in the chain (2 in your example) to be configured as "Submit on Event", is that correct? As a result the chart will only update when submitting the last input. This works, just a bit unintuitive to use.

Happy to say the charts are the reason we renewed our license btw., love this! 😊

**Comment by huyphams** [comment]
Hi @Maddoc42 we fixed that bug too, please wait for the next update!

**Comment by Maddoc42** [comment]
Thank you so much, this is awesome! 🙏 

<img width="311" alt="Screenshot 2024-05-16 at 16 10 13" src="https://github.com/TablePlus/TablePlus/assets/1794729/e025bf30-cf37-414e-b3cb-997b24edb0aa">

Hijacking this thread (happy to open another if that's better), a small QOL improvement request if possible: when clicking on a data point in a chart, the selected point is highlighted with dotted lines. Any chance to see the numeric values for that point? Right now getting the value means zooming in the chart until only the single data point is visible.

**Comment by huyphams** [comment]
the chain inputs issue is fixed on production now!
