### ISSUE TITLE
Labeling "SQL Query" tabs

### ISSUE THREAD

**Issue by sam-gronblom-rj** [TablePlus/TablePlus#3303]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

Sometimes when investigating a DB issue I will open up multiple tabs and run various queries and then jump between the tabs. It would be nice you could double click or right click the "SQL Query" tab and type in a custom label to more easily jump to the right tab.

**Comment by huyphams** [comment]
You can right click and rename any tab with TablePlus macOS already.

**Comment by huyphams** [comment]
<img width="507" alt="Screenshot 2024-05-17 at 12 37 39 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/d250754a-62e0-4aa9-b315-952af04b4183">
