### ISSUE TITLE
cmd-P no longer searches in multiple schemas

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#3309]
After one of the latest updates the search function (cmd-P) is behaving different. Is there a setting so I can get back to "search in all schemas". I'ts really annoying to have to switch schema just be be able call upp something from this schema with cmd-P.

**Comment by huyphams** [comment]
Hi @msageryd You can uncheck the lazy load schema and the cmd + P will search all schemas. 
<img width="433" alt="Screenshot 2024-05-24 at 2 07 00 PM" src="https://github.com/TablePlus/TablePlus/assets/3654622/2d2596e3-5db8-4942-b298-353b970006c1">

**Comment by msageryd** [comment]
Thank you!
I have searched for this setting, but failed.

**Comment by BFJonk** [comment]
I did found the setting, but it's failing me anyway. (cmd-P) only searches in the current schema

![Image](https://github.com/user-attachments/assets/a7a33343-6b61-4c50-b342-d4ac5217274c)

Version 6.3.5 (593)

**Comment by huyphams** [comment]
Also if you have a chance, please update the app to the latest version 6.3.9 (597)

**Comment by BFJonk** [comment]
@huyphams 
1. Updated
2. Consistenly does not work

**Comment by huyphams** [comment]
Hi @BFJonk can you make a demo? because it works on my setup, also confirmed by other users.

**Comment by BFJonk** [comment]
The blue database is development
The red one production 

The have a similar structure

https://github.com/user-attachments/assets/048391bc-7310-44ce-b391-67d8a68f9a9a

**Comment by BFJonk** [comment]
schema structure of prod: 

![Image](https://github.com/user-attachments/assets/e1daf1a8-7682-4d8e-b5c8-86e34baf91f0)

schema structure of dev1:

![Image](https://github.com/user-attachments/assets/27bc5114-ff9a-4401-8d3e-26c28bc7841a)

**Comment by huyphams** [comment]
I can see that in the result, there are at least two schema "star" and "load", so I'm not sure If I understand you correctly on this issue.

**Comment by BFJonk** [comment]
In the beginning of the recording I'm showing the blue connection `dev1`, schema `datastore`. you see a number of tables starting with `ds_`

Then I'm switching to the `prod` database, focus is on schema `load`. I press cmd-P, search for tables starting with` ds_` and nothing shows up....

**Comment by huyphams** [comment]
It's fuzzy matching, can you try with the ^ds which search prefix @BFJonk ?

**Comment by BFJonk** [comment]
![Image](https://github.com/user-attachments/assets/57c8923e-4c91-4c9d-86cb-c11277fd4193)

no results

**Comment by BFJonk** [comment]
any clue?
