### ISSUE TITLE
Table Plus app on Mac crash when I select a row with mediumtext data

### ISSUE THREAD

**Issue by neoshiva** [TablePlus/TablePlus#3311]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
   
    MySQL 8.3

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

    Version 6.0.4 (556) on Mac(M1)

5. The steps to reproduce this issue:

    - Select a table on the left.
    - Data (rows) appears in the center.
    - Click on a row containing a large mediumtext field. The size is only 108 kB.
    - The app crashes before the data is shown.

[table]
CREATE TABLE `test` (
  `date` date NOT NULL,
  `memo` mediumtext NOT NULL,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

[1.txt](https://github.com/TablePlus/TablePlus/files/15478162/1.txt)

Set text from 1.txt file to `memo` column. then click the row. Crash.

**Comment by arne-kroeger** [comment]
Same for me.
