### ISSUE TITLE
Code beautification breaks PLPGSQL code

### ISSUE THREAD

**Issue by MaximilianTyrtania** [TablePlus/TablePlus#3313]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):16.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 6.0.4 (556)
3. The steps to reproduce this issue:
This PLPGSQL Code:

If vClient.followupofclient_id is null Then--//some comment
  If vClient.paymentofficetype_id=3 Then --Firma
    textBlockIDOfEMailToClient=204;

when beautified gets turned into:

IF vClient.followupofclient_id IS NULL THEN
	--//some comment IF vClient.paymentofficetype_id = 3 THEN
		--Firma
		textBlockIDOfEMailToClient = 204;

The 2nd line is now surprisingly part of the comment.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
