### ISSUE TITLE
Connection is lost on SSH after a few minutes of no usage

### ISSUE THREAD

**Issue by kprimdal** [TablePlus/TablePlus#332]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 93

3. The steps to reproduce this issue:
I'm connecting over SSH, and then after maybe 10 minutes of none usage I have lost connection to the database and I have to close the tab and connect again.

I recorded a video showing it here:
https://drive.google.com/a/primux.dk/file/d/18ND3YuVS8Oa1xICdZCNMjXqEHcxYkKYT/view?usp=drivesdk

**Comment by huyphams** [comment]
Hey, thanks. Can you check in preferences if option keep connection alive is on or off?

**Comment by kprimdal** [comment]
It was off, so I will set it to on, and that is properly going to solve it
