### ISSUE TITLE
UI Bug - Cannot See Multi Line Database Names in UI

### ISSUE THREAD

**Issue by jjjrmy** [TablePlus/TablePlus#3325]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 532

4. The steps to reproduce this issue:
- Create a database with multi line name

<img width="415" alt="Screenshot 2024-06-08 at 3 03 53 PM" src="https://github.com/TablePlus/TablePlus/assets/1609800/fa2da6bc-c86c-4ae5-b48e-e7e8b87edde5">

<img width="762" alt="Screenshot 2024-06-08 at 3 04 08 PM" src="https://github.com/TablePlus/TablePlus/assets/1609800/cf39171c-e3f2-45b5-bc0f-00a155133a6f">

It's only possible to see that a database name is multi-line when you open more than one database.
You can't see it when looking at the database list or the in the top bar.

**Comment by huyphams** [comment]
Hi @jjjrmy thanks for letting me know. Just fixed the issue, will be included in the next update.

**Comment by huyphams** [comment]
Just note that it also fails to display multiple lines table as well.
