### ISSUE TITLE
⌘ + P should search over schemas

### ISSUE THREAD

**Issue by BFJonk** [TablePlus/TablePlus#3327]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **Postgresql 15**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **Version 6.0.5 (559)**

3. The steps to reproduce this issue:

    1. ⌘ + P
    2. enter a table name
    3. Observed behaviour: Only tables from within the schema are returned
    4. Expected behaviour: Even if the table name is in a different schema it should be returned

**Comment by huyphams** [comment]
Reason:

To optimize loading, TablePlus only loads the items in the currently selected schema. Therefore, the command + P only searches within the current schema.

However, we have found that this approach has some limitations. One of them is that the "open anything" feature is not cross-schema.

**Comment by BFJonk** [comment]
Thanks, this really helps!
