### ISSUE TITLE
[feature request] The 'Toggle Panels' toolbar item as individual items.

### ISSUE THREAD

**Issue by ussher** [TablePlus/TablePlus#3337]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 5.8.4 (532)

4. The steps to reproduce this issue:
In the menubar at the top right click then choose "Customze Toolbar".
Its possible to drag an item called "Toggle Panels" into the toolbar.  
This item contains 3 icons
* toggle left
* toggle bottom
* toggle right.

The request is to have each of these 3 icons available as individual icons.

WHY:
Because i use the toggle left all the time but always keep the right and the bottom closed.

Currently the only option is to have all 3 showing or none showing.  Ideally I would like to just have the 'toggle left' icon in the menu bar.
<img width="409" alt="icons" src="https://github.com/TablePlus/TablePlus/assets/1817411/8eac4a03-9a95-4104-aaf9-ca0ca97e14ea">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Or you can remove the button and use Command + 0 to toggle the sidebar @ussher

**Comment by huyphams** [comment]
Tip: Hover on the buttons to see shortcuts.

**Comment by huyphams** [comment]
So I don't think it is necessary to make it separately.
