### ISSUE TITLE
Export Page CSV/JSON not working

### ISSUE THREAD

**Issue by Crityk** [TablePlus/TablePlus#334]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
n/a

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
V1.0 Build 94

3. The steps to reproduce this issue:
Upon clicking multiple rows. The option to export page is not available.

**Comment by huyphams** [comment]
Hi sorry, it's UI bug. I fixed it in this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
