### ISSUE TITLE
Support DuckDb read-only access mode

### ISSUE THREAD

**Issue by nauxliu** [TablePlus/TablePlus#3345]
## Background
When developing progress writing to DuckDB and using TablePlus for viewing data, the following error occurs:

```
Runtime Error
  IO Error: Could not set lock on file "xxxx.duckdb": Conflicting lock is held in /Applications/Setapp/TablePlus.app/Contents/MacOS/TablePlus (PID 77370) by user xxxx. See also https://duckdb.org/docs/connect/concurrency
make: *** [transform] Error 2
```

This is because only one process can both read and write to the database. 

Ref: https://duckdb.org/docs/connect/concurrency.html

## Prososed Soulution
Please allow TablePlus to open the database with [access_mode = 'READ_ONLY'](https://duckdb.org/docs/configuration/overview.html#configuration-reference).

**Comment by huyphams** [comment]
Agree and also memory mode.

**Comment by daveycope** [comment]
+1

**Comment by huyphams** [comment]
If you have a chance, you can use this patch: https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0
Thanks

**Comment by huyphams** [comment]
Did you enable to read only @nauxliu ?

**Comment by nauxliu** [comment]
yes, I have.
