### ISSUE TITLE
Inability to render DB stats due to wrong quotation marks

### ISSUE THREAD

**Issue by slashequip** [TablePlus/TablePlus#3349]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

**Driver:** MySQL 8
**Build:** Version 6.0.8 (562)

Using a default, MySQL 8, DigitalOcean managed database, the follow global settings are provided in the DO UI;

![SCR-20240701-mojt](https://github.com/TablePlus/TablePlus/assets/2316916/d3a80a53-4da5-4f58-9523-d0a249543367)

When opening a particular table or looking at all tables, there are no statistics on table, and index, sizes.

Noting that when looking at an individual table I can see the following query being run, in the query log;

```
SELECT
  data_length AS `data_size`,
  index_length AS `index_size`,
  (data_length + index_length) AS `total_size`,
  table_comment AS `comment`
FROM
  information_schema.TABLES
WHERE
  table_schema = "my_db"
  AND table_name = "my_db_table";
```

Against default DigitalOcean managed databases, this query fails when run manually;

```Query 1 ERROR at Line 29: : Unknown column 'my_db' in 'where clause'```

Switching the double quotes used in the query to single quotes allows the query to run as expected;

```
SELECT
  data_length AS `data_size`,
  index_length AS `index_size`,
  (data_length + index_length) AS `total_size`,
  table_comment AS `comment`
FROM
  information_schema.TABLES
WHERE
  table_schema = 'my_db'
  AND table_name = 'my_db_table';
```

**Comment by huyphams** [comment]
Fixed! Thank you!

**Comment by slashequip** [comment]
My hero, @huyphams! Working great in the latest build!
