### ISSUE TITLE
DuckDB schemas other than main do not show up

### ISSUE THREAD

**Issue by AlexanderVR** [TablePlus/TablePlus#3351]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): DuckDB 1.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 562
3. The steps to reproduce this issue:
- open an empty DuckDB database within TablePlus.
- `create schema a`
- `create table a.t as from range(5)`
- refresh the connection -- no tables or schemas will show up on the left pane.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I do not know that DuckDB also has schema. let me add it to the app.
