### ISSUE TITLE
Running Queries No longer Works

### ISSUE THREAD

**Issue by mt404** [TablePlus/TablePlus#336]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Postgres

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 94.

3. The steps to reproduce this issue:

* Open a connection to a db
* Enter a query 
* hit CMD-E to run it.

Expected Result:  The query results show beneath the query

Actual Result:  The query seems to run but no results are visible - so basically the app is useless.  

Is it possible to downgrade to the last build?

**Comment by huyphams** [comment]
Hi, I just tested and it works fine. Can you make a gif or something that I can reproduce the bug?

**Comment by huyphams** [comment]
Btw you can download the old build with this link: https://s3.amazonaws.com/tableplus-osx-builds/93/TablePlus.zip

Replace the number with the build number you need.

**Comment by mt404** [comment]
My apologies - error was my misunderstanding.  After installing the latest update the results panel was fully collapsed/dragged down to the bottom.  So it looked like nothing was happening.  Wasn't clear to me that it was there, but noticed it when making a gif to send you.

Sorry about that.

**Comment by mt404** [comment]
appreciate the quick response!

**Comment by mt404** [comment]
btw.  love the product :)
