### ISSUE TITLE
connection and tab

### ISSUE THREAD

**Issue by redvex** [TablePlus/TablePlus#337]
Build 93 connected to MySQL (various versions)

I have multiple connection: Localhost, Production server, customer box
1) Open a new connection to connect to my local database (named UNO_hgo for example)
2) Open a new connection to connect to my remote database (same name)
3) Table plus redirect me to my local connected database UNO_hgo istead of the remote one.

I've notice that the "switch" and "new window" button open a new tab instead of do what they should have to do.

**Comment by huyphams** [comment]
Thanks, got it 👍

**Comment by huyphams** [comment]
Hey @redvex this build will fix your bug: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Thanks for letting me know. I'm working to improve this tab by grouping all the database in the same connection.

**Comment by redvex** [comment]
I'll wait for setupp update to test it, thanks 🙂

**Comment by redvex** [comment]
I've tested it with the build linked above... connection tab bug is solved, "switch" button stil open a new tab. Thanks for your support 🙂
