### ISSUE TITLE
Metrics board lost all charts and tables and TablePlus won't import from exported copy

### ISSUE THREAD

**Issue by pbastowski** [TablePlus/TablePlus#3373]
One of my Metrics boards lost all of the charts and tables in it suddenly. One moment they were there, I clicked on another metrics board, the charts showed, clicked back again and the metrics board was completely empty.

I have an exported version, so, I tried to import it, but that does not appear to do anything. Import does not work. I do not want to try other boards, because I may also loose my other charts.
- Import Metrics Board
- File dialog appears
- double click the exported board file 
- dialog appears asking for password
- I haven't set one, so, I click OK
- Nothing happens
- I repeat the process
- Nothing happens

Is there another way to import the exported metrics board? I am happy to send you a copy of it for testing purposes, but don't want to share it with everyone here.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):  SqLite 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  MacOS 6.1.2 (568)

Update: I tried the latest beta version 569. No change, still can't import the metrics board

**Comment by huyphams** [comment]
Hi @pbastowski metrics board data is a json file, so it could be a file issue. Can you try to restart macOS and see how it goes?
If it does not work, can you rename the backup file and then reimport it again?

**Comment by pbastowski** [comment]
The Metrics board export files are not JSON. Here is a screenshot of the export file I am trying to import.

<img width="401" alt="image" src="https://github.com/user-attachments/assets/4ab3634a-4a48-4e37-bc79-4fa3dbe8c860">

Perhaps when you refer to the "backup file"s you are thinking of different files? Where are they located on MacOS please?

**Comment by huyphams** [comment]
wait, how did you import the metrics board?

**Comment by pbastowski** [comment]
Like this 
<img width="439" alt="image" src="https://github.com/user-attachments/assets/d29bee3c-bbf9-4d07-84ab-1b4e11fc10a2">

**Comment by huyphams** [comment]
Yeah you can rename the Weekly char... to something, for example abc_xyz.tableplusmetricsboard and then reimport it again.

**Comment by pbastowski** [comment]
But that does not work. The dialogs open, I select a file and click ok to import and then nothing happens.

**Comment by pbastowski** [comment]
It does. I did not set a password, so, I click ok.

**Comment by pbastowski** [comment]
I could screen share to show you

**Comment by huyphams** [comment]
I see, so the issue is that the app allows you to export without password but it won't let you import without a password. (the app should not allow to export without password). Let me see if we can solve this issue.

**Comment by pbastowski** [comment]
Yes, indeed that could be the case.

**Comment by huyphams** [comment]
Okay I remove the requirement password when import metrics board, it will available in the next update!

**Comment by pbastowski** [comment]
Great, thanks. When can I expect to be able to download it?

**Comment by pbastowski** [comment]
It's just that my most useful charts were in the board that disappeared.

**Comment by huyphams** [comment]
Hi @pbastowski you can try this patch https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&dl=0

**Comment by pbastowski** [comment]
It works 🎉

Thank you for the super fast support!

**Comment by gpmcadam** [comment]
Is therea reason they're encrypted/binary? It would be great to share these amongst a team with source control. Given they're just queries, what's the reasoning to encrypt/encode them with a password?
