### ISSUE TITLE
DB Auto-Refresh Feature

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#338]
Perhaps add a feature so i can watch a table, and see the changes reflected on the fly (refreshing every 5 seconds, etc)

**Comment by huyphams** [comment]
Hey @brian-crane thanks for the suggestion! I will consider it.

**Comment by geoffreywiseman** [comment]
I'd want this for a query rather than a table, so I can filter the data based on where I'm expecting to see a change, but I'd still like this.

**Comment by mattprivman** [comment]
Would love this as well, for both tables and queries.

**Comment by erashdan** [comment]
+1

**Comment by hiddenlucas** [comment]
+111111

**Comment by shoemoney** [comment]
+999999

in the mean time you can use a macro.

**Comment by o1dnik** [comment]
@shoemoney can you provide the macro which you use?

**Comment by roberts91** [comment]
+1

**Comment by matteing** [comment]
+1

**Comment by hannyramzy** [comment]
+1

**Comment by NathanRDN** [comment]
+1

**Comment by hroland** [comment]
+1

**Comment by matteing** [comment]
Still +1

**Comment by samhotchkiss** [comment]
+1

**Comment by mdellen** [comment]
+1

**Comment by matteing** [comment]
+1

**Comment by huyphams** [comment]
We can now do it with the new metrics board.

**Comment by abhishekgahlot2** [comment]
@huyphams whats the metrics board.

**Comment by huyphams** [comment]
You may want to read this @abhishekgahlot2 
https://tableplus.com/blog/2023/12/how-to-design-mini-tools-using-tableplus.html
