### ISSUE TITLE
[Feature Request] CTRL-C/CMD-C should be copy cell instead of Record

### ISSUE THREAD

**Issue by RaffiOl** [TablePlus/TablePlus#3381]
It would be nice if CTRL-C/CMD-C copies only the aktiv cell instead of the complete line in table view.

Maybe a config option.

Thanks in advance!

**Comment by huyphams** [comment]
You can copy the current cell value with command shift C @RaffiOl

**Comment by RaffiOl** [comment]
Ui. Yes. Perfect.... Thanks!
