### ISSUE TITLE
Data Types FLOAT, DATE and INTERVAL are not supported for DuckDB

### ISSUE THREAD

**Issue by spren9er** [TablePlus/TablePlus#3382]
Thanks for adding DuckDB support!

However, FLOAT, DATE and INTERVAL columns are not working for me!

For FLOAT and DATE columns, there are only `NULL` values showing up, even though none of the values are `NULL` in table.
INTERVAL data shows incorrect number (most of the time it's `0`).

### Table in TablePlus

<img width="256" alt="Bildschirmfoto 2024-06-15 um 09 12 02" src="https://github.com/TablePlus/TablePlus/assets/5602551/2683dbc7-a760-4e16-8095-b2d728f82a46">

### Table in DuckDB

<img width="484" alt="Bildschirmfoto 2024-06-15 um 09 13 44" src="https://github.com/TablePlus/TablePlus/assets/5602551/4d692e99-e8e3-4eed-bc88-4f18bcd41f35">

Can be easily reproduced by running following SQL queries in TablePlus:

```
SELECT 1::FLOAT;
```

```
SELECT current_date;
```

```
SELECT INTERVAL '1 day';
```

Other types like DOUBLE, TIME and TIMESTAMP seem to work fine:

```
SELECT 1::DOUBLE;
```

```
SELECT current_time;
```

```
SELECT current_timestamp;
```

### Specs

DuckDB Version: v1.0.0 (1f98600c2c)
TablePlus Version: 6.1.2 (568)
macOS: Sonoma 14.6.1

**Comment by tim-x-y-z** [comment]
how were you able to update your table plus duckdb ? i am stuck with v0.10.3 so far

**Comment by huyphams** [comment]
Hi @tim-x-y-z the team DuckDB did not release version 1.0 on macOS or Swift (their official driver) and we do not want to build it from source.
Let me ping the duckdb team and request the release (as they released it on other platforms)

**Comment by huyphams** [comment]
Hi, we added the DuckDB 1.1.0 official in this patch: https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=1261idxa&dl=0

**Comment by tim-x-y-z** [comment]
amazing - any update on the extensions side of things?

**Comment by huyphams** [comment]
Hi, we have considered the extension, and the best solution is to publish a build exclusively for DuckDB users.

**Comment by voidexpr** [comment]
I have tried the Dropbox link above and I still get version Version 6.1.6 (570) and see nulls for dates and floats. The database is created on the cli with:  v1.1.0 fa5c2fe15f
Here is a comparison with what I downloaded from Dropbox and what I had downloaded from the website earlier today:

Version 6.1.6 (570)

size date filename
103669145 Sep 27 13:45 TablePlus (1).dmg // dropbox
100614186 Sep 27 07:43 TablePlus.dmg // website

Does the fixed binary have a different version than  6.1.6 (570) ? i.e. do I have the wrong binary or is the issue still there ?

**Comment by huyphams** [comment]
Hi,

I just updated DuckDB to 1.1.1 and fix the date, internal and float issue: 

https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=chhbzeox&dl=0

**Comment by voidexpr** [comment]
seems to work, thank you !

**Comment by benjaminbauer** [comment]
Is there a planned release date for this?

**Comment by huyphams** [comment]
It's released now! Thanks!

**Comment by huyphams** [comment]
Fixed @benjaminbauer the new update will be released next month (beta first this month).
