### ISSUE TITLE
Not able to UPDATE after having datatype FLOAT in row

### ISSUE THREAD

**Issue by l1nk-16** [TablePlus/TablePlus#3389]
Hello guys

1. Which driver are you using and version of it: MySQL 8.0.33

2. Which TablePlus build number are you using: 570

3. The steps to reproduce this issue:

My table structure looks like this:

CREATE TABLE `user_offer_invoices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `offer_id` bigint unsigned DEFAULT NULL,
  `offer_type` tinyint unsigned DEFAULT NULL,
  `offer_address` json DEFAULT NULL,
  `contact` json DEFAULT NULL,
  `price` smallint unsigned DEFAULT NULL,
  `duration` smallint unsigned DEFAULT NULL,
  `discount` float unsigned DEFAULT NULL,
  `is_free` tinyint unsigned NOT NULL DEFAULT '0',
  `is_promoted` tinyint unsigned NOT NULL DEFAULT '0',
  `is_paid` tinyint unsigned NOT NULL DEFAULT '0',
  `create_date` datetime DEFAULT NULL,
  `last_update` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `id (PRIMARY)` (`id`) USING BTREE,
  UNIQUE KEY `uuid` (`uuid`),
  KEY `user_id` (`user_id`),
  KEY `offer_id` (`offer_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

I have changed the column `discount` from "smallint unsigned" to "float unsigned". Now it's no longer possible to update the row.

**Comment by l1nk-16** [comment]
Hi @huyphams Thanks for your advice. The column `id` should have a primary key in this example.

**Comment by huyphams** [comment]
I'm unable to create the table with the syntax, are you sure it's correct?
<img width="1258" alt="Screenshot 2024-09-12 at 3 30 28 PM" src="https://github.com/user-attachments/assets/1de87b9f-35fc-4568-a258-5980c4033dc0">

**Comment by l1nk-16** [comment]
I got the same error, so I shortened the Code:

CREATE TABLE `test` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `discount` float unsigned DEFAULT NULL,
  UNIQUE KEY `id (PRIMARY)` (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

This example should work and reproduces the same error. As soon as you enter a float as value, an update is no longer possible.

**Comment by huyphams** [comment]
I think I still have the same error
<img width="1163" alt="Screenshot 2024-09-12 at 4 55 12 PM" src="https://github.com/user-attachments/assets/4270c24c-df3d-4a06-8edf-9bb7390a6282">

**Comment by l1nk-16** [comment]
Ah I see the problem. The editor removes the apostrophes. Please use the code in this file: [test.txt](https://github.com/user-attachments/files/16977473/test.txt)

**Comment by l1nk-16** [comment]
I found out: it only happens if the float is lower than 1. So 1.1 works fine, but 0.9 breaks the update query.

**Comment by huyphams** [comment]
Hi @l1nk-16 your table does not have the primary, instead the index named `PRIMARY` so technically, it is not a primary.

Close as it's not a TablePlus issue.

You should use the syntax below

```
CREATE TABLE `asd` (
  `id` int NOT NULL AUTO_INCREMENT,
  `content` float unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
