### ISSUE TITLE
Wrap selected text in quotes

### ISSUE THREAD

**Issue by sam-jg** [TablePlus/TablePlus#339]
In most text editors if you highlight some text and then press a bracket or quote key it will surround the text with that symbol. It would be nice if the sql editor did that as well. This is useful when working with tables and attributes that with uppercase letters that need to be quoted with "".

It would also be great if there was an option for the editor to auto quote table names and attributes. I can make a seperate issue for this if you want.

**Comment by huyphams** [comment]
Hey, thanks! It would be better if we have a separate issue for each feature, it's easy to keep track the progress.

**Comment by MrLoh** [comment]
Yes, wrapping selected text in parenthesis and quotes is essential and probably not too hard to implement. Would love to see this.

**Comment by huyphams** [comment]
It's released in the beta update! (the official will come later.)
