### ISSUE TITLE
IO Error: The file "file.duckdb" exists, but it is not a valid DuckDB database file!

### ISSUE THREAD

**Issue by kenn** [TablePlus/TablePlus#3391]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. DuckDB CLI v1.1.0

2. Version 6.1.6 (570)

3. Repro:

Convert CSV to PARQUET file, then connect with TablePlus:

```sql
% brew install duckdb
% duckdb

COPY (SELECT * FROM read_csv_auto('file.csv')) TO 'file.duckdb' (FORMAT 'PARQUET')
```

Now, connect to this file via DuckDB:

<img width="612" alt="Screenshot 2024-09-15 at 3 50 27 PM" src="https://github.com/user-attachments/assets/ca1b2678-9b4e-49fa-9324-0dfa0d05c108">

and get this error upon connect to the file:

```
IO Error: The file "file.duckdb" exists, but it is not a valid DuckDB database file!
```

**Comment by huyphams** [comment]
Hi @kenn I'm still waiting for DuckDB team to release the update version of macOS driver (I don't want to use the beta release).

**Comment by huyphams** [comment]
Hi, we added the DuckDB 1.1.0 official in this patch: https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=1261idxa&dl=0

**Comment by huyphams** [comment]
Hi @kenn you can check the duckdb version by create any dummy connection. If it shows 1.1.0 it should be a different issue.
<img width="379" alt="Screenshot 2024-09-21 at 12 44 36 PM" src="https://github.com/user-attachments/assets/7bc48206-3306-4602-a904-5e4b456be50b">

**Comment by kenn** [comment]
Ha, I just found a better tool — and it was from you!

https://tabletool.io/
