### ISSUE TITLE
⌘+I does not format SQL query

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#34]
Hitting ⌘+I does not format the SQL query, I have to hit the Format button manually.

![2017-08-02 11_16_01](https://user-images.githubusercontent.com/7946786/28888074-22a2ede6-7774-11e7-8a70-2d07498b48b9.gif)

**Comment by huyphams** [comment]
Hi @brian-crane you should selected command before hit comman + i or control + I.
Hit the button means format all command.

**Comment by brian-crane** [comment]
ah I see now, yes this will work fine. thank you!
