### ISSUE TITLE
duckdb commit doesn't work, ddl neither

### ISSUE THREAD

**Issue by voidexpr** [TablePlus/TablePlus#3400]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

built-in duckdb

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 6.1.6 (570)

4. The steps to reproduce this issue:

* open a duckdb db and try to edit data, commit doesn't persist the change and  the row is reverted, no error reported
* creating a table doesnt work, error reported

**Comment by huyphams** [comment]
Hi @voidexpr can you show us the error message?

**Comment by voidexpr** [comment]
![Screenshot 2024-09-29 at 7 23 14 AM](https://github.com/user-attachments/assets/4c8bc666-a285-4bef-a114-135b6821b75b)
thank you for the fast reply, sorry for omitting it. Maybe it's a user error ? Tried to select different schema but not sure what I'm missing, I'm new to duckdb too. 
I also noticed that changes show in green for DDL and in orange for data changes, should it be the same if they need to be committed ? or maybe DDL are not supposed to be committed ?

**Comment by voidexpr** [comment]
and just to clarify: I'm mostly blocked by updates not working (no error message there, just reverted silently). 
DDL (in the screenshot) was just to try to figure out what was going on. No problem creating table structure outside of TablePlus. But data edit + charts is what I'm after.

**Comment by huyphams** [comment]
Did you enable the read only mode? I could not reproduce the issue? 
<img width="268" alt="Screenshot 2024-09-30 at 8 54 49 AM" src="https://github.com/user-attachments/assets/76499e6e-ffd3-4e75-898d-8e3ae5918d3c">

**Comment by voidexpr** [comment]
It's not read-only (I'm still confused by the connection/schema management but I tried many times to make sure it wasn't a read-only issue).
I did more digging. The problem might have nothing to do with updates. On a simple example updates seem to work. 
I've attached a database file but you can recreate the data yourself:

```
create table t1 (c1 date, c2 date, text varchar);
insert into t1 values ( date '2022-12-31', date '2023-01-01', 'row 1 - 2022-12-31');
insert into t1 values ( date '2022-12-31', date '2023-01-01', 'row 2 - 2022-12-31');
select * from t1;
┌────────────┬────────────┬────────────────────┐
│     c1     │     c2     │        text        │
│    date    │    date    │      varchar       │
├────────────┼────────────┼────────────────────┤
│ 2022-12-31 │ 2023-01-01 │ row 1 - 2022-12-31 │
│ 2022-12-31 │ 2023-01-01 │ row 2 - 2022-12-31 │
└────────────┴────────────┴────────────────────┘
```

If within TablePlus (only) I run `select * from t1;` or `select *, strftime(c1, '%d/%m/%Y %Z %z') from t1;` instead of 2022-12-31 I see 2022-12-12. That's one issue I found with my data I couldn't get update to work with. Because there is 19 days difference it doesn't seem to be a locale/timezone issue (I create the database and run TablePlus on the same machine). Really not sure what it is. Maybe TablePlus uses a specific setting so dates are not yyyy-mm-dd but something else ? TablePlus shouldn't do any formatting or at least shouldn't use formatted data to generate the update/delete statements as it might make the predicate not match the data displayed (what is happening here so it looks like updates don't work, they just don't find the rows).
I've included a screenshot.
![Screenshot 2024-09-30 at 2 29 27 PM](https://github.com/user-attachments/assets/8a1b885d-71b8-4899-a7d9-035853a52c5c)
[repro.db.zip](https://github.com/user-attachments/files/17196710/repro.db.zip)

**Comment by huyphams** [comment]
Hi @voidexpr you should have a primary key, if you don't have the primary key it won't work sometimes because it requires comparison in all fields.
TablePlus also does not format anything (we do not want) but the library and they way DuckDB returns the result has no standard.

**Comment by voidexpr** [comment]
I don't understand how it explains the date change `2022-12-12` in TablePlus instead of `2022-12-31` in the table and queried from CLI.

Note that the issue I point out doesn't involve update/delete/insert (which yes would behave funny without a primary key, in part something I was curious about, if TablePlus requires a primary key for update then it should return an error without it).

The issue I'm seeing is that the date inserted and that can been seen from the CLI is different from when I run a query in TablePlus.
But just to be sure I created another table with a primary key (which should not be needed anyway):
```
 create table t2 (k1 int primary key, c1 date, c2 date, text varchar);
 insert into t2 values (1, date '2022-12-31', date '2023-01-01', 'row 2 - 2022-12-31');
 insert into t2 values (2, date '2022-12-31', date '2023-01-01', 'row 2 - 2022-12-31');
 select * from t2;
┌───────┬────────────┬────────────┬────────────────────┐
│  k1   │     c1     │     c2     │        text        │
│ int32 │    date    │    date    │      varchar       │
├───────┼────────────┼────────────┼────────────────────┤
│     1 │ 2022-12-31 │ 2023-01-01 │ row 2 - 2022-12-31 │
│     2 │ 2022-12-31 │ 2023-01-01 │ row 2 - 2022-12-31 │
└───────┴────────────┴────────────┴────────────────────┘
```

If you run `select * from t2` in TablePlus you again get `2022-12-12` instead of `2022-12-31`.

**Comment by huyphams** [comment]
There is a typo in the parser, you could try this patch as it should fix the date: https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=20mvnk8t&dl=0

**Comment by voidexpr** [comment]
Perfect, fixes the issue thank you.
I tried again update, it works as expected there too (some dup rows get updated if they have the same value as expected). I'll skip the ddl part for now. I'll re-open an issue if needed later if I revisit it. Thank you.
