### ISSUE TITLE
tableplus quit unexpectedly!

### ISSUE THREAD

**Issue by francisborge** [TablePlus/TablePlus#3402]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oracle from Build 573

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 573

3. The steps to reproduce this issue: 
1-Open the connection
2- Open company table as an example (it could be any random table) then I receive a message saying "tableplus quit unexpectedly" in macOS 15.0 (24A335)

Also I have the following crash report:
Process:               TablePlus [83353]
Path:                  /Applications/TablePlus.app/Contents/MacOS/TablePlus
Identifier:            com.tinyapp.TablePlus
Version:               6.1.7 (573)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-30 16:26:35.6116 +0200
OS Version:            macOS 15.0 (24A335)
Report Version:        12
Bridge OS Version:     9.0 (22P353)
Anonymous UUID:        64E05E0F-01D2-305A-16A7-3E182C098CCC

Sleep/Wake UUID:       F22B236B-0FA1-4A1C-A385-E48420DEBC01

Time Awake Since Boot: 56000 seconds
Time Since Wake:       20287 seconds

System Integrity Protection: enabled

Crashed Thread:        11  Dispatch queue: nio.nioTransportServices.connectionchannel

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [83353]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80106de0e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80107c622 mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff801074f16 mach_msg_overwrite + 649
3   libsystem_kernel.dylib        	    0x7ff80106e0ff mach_msg + 19
4   CoreFoundation                	    0x7ff801194c48 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff8011936cd __CFRunLoopRun + 1393
6   CoreFoundation                	    0x7ff801192b6c CFRunLoopRunSpecific + 536
7   HIToolbox                     	    0x7ff80c872fe3 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	    0x7ff80c8789c4 ReceiveNextEventCommon + 646
9   HIToolbox                     	    0x7ff80c878b62 _BlockUntilNextEventMatchingListInModeWithFilter + 66
10  AppKit                        	    0x7ff804ac6d8b _DPSNextEvent + 902
11  AppKit                        	    0x7ff8054e34c8 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1290
12  AppKit                        	    0x7ff804ab7eb7 -[NSApplication run] + 610
13  AppKit                        	    0x7ff804a8b234 NSApplicationMain + 823
14  TablePlus                     	       0x1067ea8b9 0x10633b000 + 4913337
15  dyld                          	    0x7ff800d212cd start + 1805

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff8010aabcc start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff8010aabcc start_wqthread + 0

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff80106dd8a semaphore_wait_trap + 10
1   libdispatch.dylib             	    0x7ff800f07cb2 _dispatch_sema4_wait + 16
2   libdispatch.dylib             	    0x7ff800f081a7 _dispatch_semaphore_wait_slow + 98
3   Oracle                        	       0x10868db0b 0x10866e000 + 129803
4   Oracle                        	       0x108690b28 0x10866e000 + 142120
5   Oracle                        	       0x10867bb51 0x10866e000 + 56145
6   Oracle                        	       0x1086837d1 0x10866e000 + 88017
7   Oracle                        	       0x10868d0b1 0x10866e000 + 127153

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff80106de0e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80107c622 mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff801074f16 mach_msg_overwrite + 649
3   libsystem_kernel.dylib        	    0x7ff80106e0ff mach_msg + 19
4   CoreFoundation                	    0x7ff801194c48 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff8011936cd __CFRunLoopRun + 1393
6   CoreFoundation                	    0x7ff801192b6c CFRunLoopRunSpecific + 536
7   AppKit                        	    0x7ff804c1cd6d _NSEventThread + 127
8   libsystem_pthread.dylib       	    0x7ff8010af253 _pthread_start + 99
9   libsystem_pthread.dylib       	    0x7ff8010aabef thread_start + 15

Thread 5:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	    0x7ff80106de0e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80107c622 mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff801074f16 mach_msg_overwrite + 649
3   libsystem_kernel.dylib        	    0x7ff80106e0ff mach_msg + 19
4   CoreFoundation                	    0x7ff801194c48 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff8011936cd __CFRunLoopRun + 1393
6   CoreFoundation                	    0x7ff801192b6c CFRunLoopRunSpecific + 536
7   CFNetwork                     	    0x7ff8068de8ea +[__CFN_CoreSchedulingSetRunnable _run:] + 447
8   Foundation                    	    0x7ff8021b2bf3 __NSThread__start__ + 1007
9   libsystem_pthread.dylib       	    0x7ff8010af253 _pthread_start + 99
10  libsystem_pthread.dylib       	    0x7ff8010aabef thread_start + 15

Thread 6:
0   libsystem_kernel.dylib        	    0x7ff801070876 __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff800f5ecf1 nanosleep + 199
2   libsystem_c.dylib             	    0x7ff800f691ba sleep + 41
3   TablePlus                     	       0x1069047a8 0x10633b000 + 6068136
4   libsystem_pthread.dylib       	    0x7ff8010af253 _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff8010aabef thread_start + 15

Thread 7:: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib        	    0x7ff80106de0e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80107c622 mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff801074f16 mach_msg_overwrite + 649
3   libsystem_kernel.dylib        	    0x7ff80106e0ff mach_msg + 19
4   TablePlus                     	       0x10690fb29 0x10633b000 + 6114089
5   libsystem_pthread.dylib       	    0x7ff8010af253 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff8010aabef thread_start + 15

Thread 8:: io.sentry.app-hang-tracker
0   libsystem_kernel.dylib        	    0x7ff801070876 __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff800f5ecf1 nanosleep + 199
2   Foundation                    	    0x7ff802237cf8 +[NSThread sleepForTimeInterval:] + 151
3   TablePlus                     	       0x1068f11b9 0x10633b000 + 5988793
4   Foundation                    	    0x7ff8021b2bf3 __NSThread__start__ + 1007
5   libsystem_pthread.dylib       	    0x7ff8010af253 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff8010aabef thread_start + 15

Thread 9::  Dispatch queue: Operations.DatabaseService.ExecuteQueue (QOS: UNSPECIFIED)
0   libsystem_kernel.dylib        	    0x7ff80106dd8a semaphore_wait_trap + 10
1   libdispatch.dylib             	    0x7ff800f07cb2 _dispatch_sema4_wait + 16
2   libdispatch.dylib             	    0x7ff800f081a7 _dispatch_semaphore_wait_slow + 98
3   Oracle                        	       0x10869002f 0x10866e000 + 139311
4   TablePlus                     	       0x1066aeb22 0x10633b000 + 3619618
5   TablePlus                     	       0x1066afb5e 0x10633b000 + 3623774
6   TablePlus                     	       0x1066b3754 0x10633b000 + 3639124
7   TablePlus                     	       0x10661df79 0x10633b000 + 3026809
8   Foundation                    	    0x7ff80219c889 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
9   Foundation                    	    0x7ff80219c787 -[NSBlockOperation main] + 94
10  Foundation                    	    0x7ff80219c725 __NSOPERATION_IS_INVOKING_MAIN__ + 17
11  Foundation                    	    0x7ff80219b9d5 -[NSOperation start] + 726
12  Foundation                    	    0x7ff80219b6e7 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
13  Foundation                    	    0x7ff80219b5b8 __NSOQSchedule_f + 182
14  libdispatch.dylib             	    0x7ff800f144ac _dispatch_block_async_invoke2 + 85
15  libdispatch.dylib             	    0x7ff800f077e2 _dispatch_client_callout + 8
16  libdispatch.dylib             	    0x7ff800f0a36d _dispatch_continuation_pop + 511
17  libdispatch.dylib             	    0x7ff800f099ff _dispatch_async_redirect_invoke + 696
18  libdispatch.dylib             	    0x7ff800f16c92 _dispatch_root_queue_drain + 328
19  libdispatch.dylib             	    0x7ff800f17431 _dispatch_worker_thread2 + 147
20  libsystem_pthread.dylib       	    0x7ff8010abc3e _pthread_wqthread + 261
21  libsystem_pthread.dylib       	    0x7ff8010aabdb start_wqthread + 15

Thread 10:
0   libsystem_pthread.dylib       	    0x7ff8010aabcc start_wqthread + 0

Thread 11 Crashed::  Dispatch queue: nio.nioTransportServices.connectionchannel
0   libswiftCore.dylib            	    0x7ff81267b800 _assertionFailure(_:_:file:line:flags:) + 496
1   Oracle                        	       0x1086dd1a6 0x10866e000 + 455078
2   Oracle                        	       0x1086d9704 0x10866e000 + 440068
3   Oracle                        	       0x108706ba5 0x10866e000 + 625573
4   Oracle                        	       0x108707a74 0x10866e000 + 629364
5   Oracle                        	       0x108708e81 0x10866e000 + 634497
6   Oracle                        	       0x1087094fa 0x10866e000 + 636154
7   Oracle                        	       0x108710108 0x10866e000 + 663816
8   Oracle                        	       0x1087109d7 0x10866e000 + 666071
9   Oracle                        	       0x1086e6ca2 0x10866e000 + 494754
10  Oracle                        	       0x1086e621c 0x10866e000 + 492060
11  Oracle                        	       0x1086e5ff7 0x10866e000 + 491511
12  Oracle                        	       0x1086e7209 0x10866e000 + 496137
13  Oracle                        	       0x1087eac57 0x10866e000 + 1559639
14  Oracle                        	       0x1087eaa3d 0x10866e000 + 1559101
15  Oracle                        	       0x1087eb230 0x10866e000 + 1561136
16  Oracle                        	       0x1087ddd0b 0x10866e000 + 1506571
17  Oracle                        	       0x1087dcca1 0x10866e000 + 1502369
18  Oracle                        	       0x1088e0b97 0x10866e000 + 2567063
19  Network                       	    0x7ff808892e95 0x7ff8087e1000 + 728725
20  Network                       	    0x7ff808895411 0x7ff8087e1000 + 738321
21  Network                       	    0x7ff808892cc9 0x7ff8087e1000 + 728265
22  libdispatch.dylib             	    0x7ff800f144ac _dispatch_block_async_invoke2 + 85
23  libdispatch.dylib             	    0x7ff800f077e2 _dispatch_client_callout + 8
24  libdispatch.dylib             	    0x7ff800f0d95b _dispatch_lane_serial_drain + 739
25  libdispatch.dylib             	    0x7ff800f0e3e2 _dispatch_lane_invoke + 377
26  libdispatch.dylib             	    0x7ff800f0d7ba _dispatch_lane_serial_drain + 322
27  libdispatch.dylib             	    0x7ff800f0e3e2 _dispatch_lane_invoke + 377
28  libdispatch.dylib             	    0x7ff800f180db _dispatch_root_queue_drain_deferred_wlh + 271
29  libdispatch.dylib             	    0x7ff800f179dc _dispatch_workloop_worker_thread + 659
30  libsystem_pthread.dylib       	    0x7ff8010abc7f _pthread_wqthread + 326
31  libsystem_pthread.dylib       	    0x7ff8010aabdb start_wqthread + 15

Thread 12:
0   libsystem_pthread.dylib       	    0x7ff8010aabcc start_wqthread + 0

Thread 11 crashed with X86 Thread State (64-bit):
  rax: 0x000000008fee783b  rbx: 0x0000000108ceb4d0  rcx: 0x000000008fee783b  rdx: 0x0000000000000000
  rdi: 0xe000000000000000  rsi: 0x0000000000001cf0  rbp: 0x0000700002d4da20  rsp: 0x0000700002d4d980
   r8: 0x00000000000003ff   r9: 0x00000000900e81d0  r10: 0x0000000090000000  r11: 0x000000000000003b
  r12: 0x0000000108ce9290  r13: 0x0000000000000000  r14: 0xe000000000000000  r15: 0x000000000000000b
  rip: 0x00007ff81267b800  rfl: 0x0000000000010286  cr2: 0x0000000000000000
  
Logical CPU:     4
Error Code:      0x00000000 
Trap Number:     6

Thread 11 instruction stream:
  6a 01 68 94 00 00 00 6a-02 6a 18 50 e8 3f 02 00  j.h....j.j.P.?..
  00 4c 89 f6 48 c1 ee 38-83 e6 0f 48 b8 ff ff ff  .L..H..8...H....
  ff ff ff ff 00 4c 21 f0-4c 89 6d c0 48 89 45 c8  .....L!.L.m.H.E.
  48 83 ec 08 44 0f b6 c1-48 8d 7d c0 4c 89 e2 48  H...D...H.}.L..H
  8b 4d 10 49 89 d9 8b 45-28 50 ff 75 20 41 57 e8  .M.I...E(P.u AW.
  9c 0d 00 00 48 83 c4 20-4c 89 f7 e8 70 95 35 00  ....H.. L...p.5.
 [0f]0b 48 83 ec 08 48 8d-05 a3 c6 47 00 48 8d 3d  ..H...H....G.H.=	<==
  50 c6 47 00 48 8d 0d 65-c6 47 00 be 0b 00 00 00  P.G.H..e.G......
  41 b8 2d 00 00 00 ba 02-00 00 00 41 b9 02 00 00  A.-........A....
  00 6a 01 68 7f 0d 00 00-6a 02 6a 14 50 e8 ae 01  .j.h....j.j.P...
  00 00 48 83 ec 08 48 8d-05 43 c8 47 00 48 8d 3d  ..H...H..C.G.H.=
  10 c6 47 00 48 8d 0d 05-c8 47 00 be 0b 00 00 00  ..G.H....G......

Binary Images:
       0x10633b000 -        0x106b08fff com.tinyapp.TablePlus (6.1.7) <3485e73f-6a26-3d24-bc77-78ef732ea025> /Applications/TablePlus.app/Contents/MacOS/TablePlus
       0x106dfb000 -        0x106e3efff org.sparkle-project.Sparkle (2.6.4) <20455c43-b2c0-32d7-b538-9727a87a4f90> /Applications/TablePlus.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x1071fd000 -        0x107350fff com.tableplus.Redis (1.0) <797a4d54-3adf-3ed1-91cb-1503629a25b3> /Applications/TablePlus.app/Contents/Frameworks/Redis.framework/Versions/A/Redis
       0x10866e000 -        0x108d88fff com.tableplus.Oracle (1.0) <ff5673fe-2b02-39bf-b9dc-bc2e4cea8960> /Applications/TablePlus.app/Contents/Frameworks/Oracle.framework/Versions/A/Oracle
       0x106e63000 -        0x1070effff com.tableplus.PostgreSQL (1.0) <e8763dfa-24f1-3815-a053-1630e12b98d8> /Applications/TablePlus.app/Contents/Frameworks/PostgreSQL.framework/Versions/A/PostgreSQL
       0x106d27000 -        0x106d9bfff - (1.0) <e73c0cf7-b158-3e73-bbae-6259470fa61a> /Applications/TablePlus.app/Contents/Frameworks/LibSQL.framework/Versions/A/LibSQL
       0x107543000 -        0x1075b9fff - (1.0) <25e636f9-89c4-3c30-9c0f-f62aae676b01> /Applications/TablePlus.app/Contents/Frameworks/CloudflareD1.framework/Versions/A/CloudflareD1
       0x1073d9000 -        0x1074aefff com.tableplus.SQL (1.0) <0008c6e6-91b3-366c-b021-d9f6b86758ce> /Applications/TablePlus.app/Contents/Frameworks/SQL.framework/Versions/A/SQL
       0x1075f7000 -        0x107ca1fff - (1.0) <5d67acc9-4dae-3f58-91fd-22d65bd4cab7> /Applications/TablePlus.app/Contents/Frameworks/MySQL.framework/Versions/A/MySQL
       0x108132000 -        0x108378fff com.tableplus.Snowflake (1.0) <e251011f-c95d-3d5a-a83f-1458605c43e4> /Applications/TablePlus.app/Contents/Frameworks/Snowflake.framework/Versions/A/Snowflake
       0x10844e000 -        0x108559fff - (1.0) <eb22d1bb-d338-364c-93ea-1a577f39e54f> /Applications/TablePlus.app/Contents/Frameworks/BigQuery.framework/Versions/A/BigQuery
       0x109606000 -        0x109847fff com.tableplus.MicrosoftSQLServer (1.0) <7f56588c-88b0-35ed-9107-d7b4da87cc5c> /Applications/TablePlus.app/Contents/Frameworks/MicrosoftSQLServer.framework/Versions/A/MicrosoftSQLServer
       0x109024000 -        0x109393fff com.tableplus.Cassandra (1.0) <775a0e33-d035-341e-9a31-dc9c1331e4a5> /Applications/TablePlus.app/Contents/Frameworks/Cassandra.framework/Versions/A/Cassandra
       0x109d86000 -        0x109f34fff com.tableplus.SSH (1.0) <2fa03a19-0843-39fa-a46c-24ccc142dc3a> /Applications/TablePlus.app/Contents/Frameworks/SSH.framework/Versions/A/SSH
       0x109b64000 -        0x109c3afff com.tableplus.Mongo (1.0) <58261bac-61f1-344a-a8e9-793f692b5a4a> /Applications/TablePlus.app/Contents/Frameworks/Mongo.framework/Versions/A/Mongo
       0x10f8a2000 -        0x111338fff com.tableplus.DuDB (1.0) <01a3d081-8f7c-30fe-8b70-d1742d794852> /Applications/TablePlus.app/Contents/Frameworks/DuDB.framework/Versions/A/DuDB
       0x10a8f3000 -        0x10aca9fff com.tableplus.MySQL8 (1.0) <c4119459-fa9c-3041-be38-918e8db78868> /Applications/TablePlus.app/Contents/Frameworks/MySQL8.framework/Versions/A/MySQL8
       0x109910000 -        0x109a2ffff com.tableplus.SQLite (1.0) <23c4e6c1-3168-367c-b82d-a95ceb36abfa> /Applications/TablePlus.app/Contents/Frameworks/SQLite.framework/Versions/A/SQLite
       0x10ad93000 -        0x10affcfff com.tableplus.ClickHouse (1.0) <cae8409e-6084-3afd-a196-5bf041ff17c2> /Applications/TablePlus.app/Contents/Frameworks/ClickHouse.framework/Versions/A/ClickHouse
       0x10b11a000 -        0x10b36afff com.tableplus.MariaDB (1.0) <4f4b8b10-7ad0-312a-9ba1-58088d27fc08> /Applications/TablePlus.app/Contents/Frameworks/MariaDB.framework/Versions/A/MariaDB
       0x1071d5000 -        0x1071d9fff libgssapiv2.2.0.18.so (*) <b6248c62-5df8-3dec-891b-8e2a2cbdc942> /usr/lib/sasl2/libgssapiv2.2.0.18.so
       0x1071e4000 -        0x1071e6fff shadow_auxprop.so (*) <554c9123-e6ac-352d-a0e6-51d635febde9> /usr/lib/sasl2/shadow_auxprop.so
       0x10751a000 -        0x10751dfff mschapv2.so (*) <05b8a49c-9ba6-3cff-be36-1dc9fa31f411> /usr/lib/sasl2/mschapv2.so
       0x1071f1000 -        0x1071f2fff atoken.so (*) <b10a027c-b488-3f3f-95e9-7945511b0c90> /usr/lib/sasl2/atoken.so
       0x107528000 -        0x10752afff login.so (*) <680b0481-aaee-34fe-8317-7d66521c7d80> /usr/lib/sasl2/login.so
       0x1074f8000 -        0x1074fefff srp.so (*) <46bec25e-2487-3e76-a4e1-c7d353966dd9> /usr/lib/sasl2/srp.so
       0x107509000 -        0x10750bfff smb_ntlmv2.so (*) <86361813-8798-3da0-a600-84a7175ee9ad> /usr/lib/sasl2/smb_ntlmv2.so
       0x1085ff000 -        0x108607fff libdigestmd5.2.so (*) <c0d24e70-a438-3051-9dd9-8009e2adcb69> /usr/lib/sasl2/libdigestmd5.2.so
       0x108612000 -        0x108616fff libntlm.so (*) <a06e8989-6c6b-3999-be7f-4a349197040a> /usr/lib/sasl2/libntlm.so
       0x107535000 -        0x107536fff plain-clienttoken.so (*) <460682f2-4a18-3cdf-9dda-19eef18a5aa6> /usr/lib/sasl2/plain-clienttoken.so
       0x1085ef000 -        0x1085f1fff libcrammd5.2.so (*) <eddb4552-b214-3100-88ee-15c9ca79281f> /usr/lib/sasl2/libcrammd5.2.so
       0x1085cd000 -        0x1085d5fff digestmd5WebDAV.so (*) <8c7381e0-f8fa-32c8-a23f-ac9b42a37ef2> /usr/lib/sasl2/digestmd5WebDAV.so
       0x1085e0000 -        0x1085e2fff apop.so (*) <00749095-9e37-3a41-83a3-a938db444288> /usr/lib/sasl2/apop.so
       0x108643000 -        0x108644fff oauthbearer.so (*) <910faaa0-8856-3787-b7bc-81dcd20d0646> /usr/lib/sasl2/oauthbearer.so
       0x10864f000 -        0x108651fff pwauxprop.so (*) <9a6766bd-2371-371e-a359-e6e0f7330eba> /usr/lib/sasl2/pwauxprop.so
       0x10865c000 -        0x10865efff libplain.2.so (*) <70bbee5d-938d-350b-be66-31e3384a4cd6> /usr/lib/sasl2/libplain.2.so
       0x109536000 -        0x109538fff libanonymous.2.so (*) <eb0209e8-f9f1-311f-83a2-297c8bf89954> /usr/lib/sasl2/libanonymous.2.so
       0x109596000 -        0x1095a6fff dhx.so (*) <86fc7152-30f6-37f1-9747-6cbfa23148dc> /usr/lib/sasl2/dhx.so
       0x109b34000 -        0x109b40fff libobjc-trampolines.dylib (*) <a732c7f4-a3c1-39e5-9fc3-5e1deb73a584> /usr/lib/libobjc-trampolines.dylib
       0x11ddea000 -        0x11de00fff com.apple.security.csparser (3.0) <729c6b61-9676-3a96-af3a-8c141dfac50b> /System/Library/Frameworks/Security.framework/Versions/A/PlugIns/csparser.bundle/Contents/MacOS/csparser
       0x11ddac000 -        0x11ddb0fff com.apple.FileProviderOverride (2732.0.85) <c71158e7-09ff-3ab7-ac94-d97d8ae45f36> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FileProviderOverride.bundle/Contents/MacOS/FileProviderOverride
       0x11e0c9000 -        0x11e0e5fff com.apple.findersync.fileprovideroverride.FinderSyncCollaborationFileProviderOverride (15.0) <23ba3863-0bfc-3ed3-a641-ab797f088304> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride
       0x11dd99000 -        0x11dd9bfff com.apple.icloud.drive.fileprovider.override (1.0) <24fa320c-5590-325d-938a-2fd90ea97be0> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/iCloudDriveFileProviderOverride.bundle/Contents/MacOS/iCloudDriveFileProviderOverride
    0x7ff80106d000 -     0x7ff8010a8fff libsystem_kernel.dylib (*) <a0aee5ca-4298-3070-82f9-ea72229f36e5> /usr/lib/system/libsystem_kernel.dylib
    0x7ff801118000 -     0x7ff8015b7ff2 com.apple.CoreFoundation (6.9) <a7324227-eb88-3393-8efe-10a9f3d28064> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff80c784000 -     0x7ff80ca5fff4 com.apple.HIToolbox (2.1.1) <98a58f35-29b9-32ce-b1ba-5bde0bfe5ae2> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff804a87000 -     0x7ff805f21ffd com.apple.AppKit (6.9) <55408426-52c7-3b83-9097-0a12aa2620e1> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff800d1b000 -     0x7ff800da732f dyld (*) <e6056c94-fc2d-3517-b1e1-46d8eb58a10e> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff8010a9000 -     0x7ff8010b4fff libsystem_pthread.dylib (*) <c0db9cf9-86ec-31d4-a557-2c07945fd8f2> /usr/lib/system/libsystem_pthread.dylib
    0x7ff800f04000 -     0x7ff800f4bff9 libdispatch.dylib (*) <6c0ff4e0-6f75-36fa-b45f-0075a398132d> /usr/lib/system/libdispatch.dylib
    0x7ff8066a3000 -     0x7ff806a43ffa com.apple.CFNetwork (1.0) <7c0dcafc-02f3-3b80-8b9d-2912d38a1888> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7ff80215d000 -     0x7ff802f96ff0 com.apple.Foundation (6.9) <b54a23dd-8603-361b-ad2e-54ac2cd8ac39> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff800f4f000 -     0x7ff800fd7ff7 libsystem_c.dylib (*) <2d4e63ef-e31c-3cc1-94ec-2b7e28b9782f> /usr/lib/system/libsystem_c.dylib
    0x7ff800cd8000 -     0x7ff800d1afeb libobjc.A.dylib (*) <a3fef4cb-4302-3a38-9075-ef032041dabb> /usr/lib/libobjc.A.dylib
    0x7ff81264d000 -     0x7ff812b32ff1 libswiftCore.dylib (*) <9c453e52-d393-35f2-a539-4e8b81d89a8b> /usr/lib/swift/libswiftCore.dylib
    0x7ff8087e1000 -     0x7ff80984bffb com.apple.Network (1.0) <ee0a9deb-49e2-3d36-933b-c6735cf899b5> /System/Library/Frameworks/Network.framework/Versions/A/Network

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=723.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=723.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG image                           496K       32 
ColorSync                          248K       30 
CoreAnimation                     8508K      371 
CoreGraphics                        20K        4 
CoreUI image data                 4208K       37 
Foundation                          40K        2 
Image IO                           100K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           691.3M      110 
MALLOC guard page                   80K       20 
SQLite page cache                  384K        3 
STACK GUARD                       56.0M       13 
Stack                             14.1M       13 
VM_ALLOCATE                        268K       30 
__CTF                               824        1 
__DATA                            32.8M      752 
__DATA_CONST                      73.2M      737 
__DATA_DIRTY                      2019K      253 
__FONT_DATA                        2352        1 
__LINKEDIT                       210.9M       45 
__OBJC_RO                         76.1M        1 
__OBJC_RW                         2354K        2 
__TEXT                           917.5M      773 
__TPRO_CONST                       272K        2 
libnetwork                         640K       16 
mapped file                      473.6M       73 
owned unmapped memory             7196K        1 
shared memory                     1328K       25 
===========                     =======  ======= 
TOTAL                              2.5G     3353

**Comment by francisborge** [comment]
This error is very frustrating and it seems that plenty users have the similar problems.

**Comment by bjkemp** [comment]
Yes, the new Oracle driver is extremely flakey. I crash multiple times a day.

**Comment by huyphams** [comment]
please follow this issue as we will bring back on driver https://github.com/TablePlus/TablePlus/issues/3342
