### ISSUE TITLE
Impossible to create table

### ISSUE THREAD

**Issue by arnouxor** [TablePlus/TablePlus#341]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.39-log

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 1.0 (94)

3. The steps to reproduce this issue:

A lots of bugs when I want to create a table : 
- Create a simple table with an id (INT) PRIMARY in autoincrement is impossible (when you add data it will always be 0 in the primary field)

- Add varchar field to a table doesn't work (because it tries to do this query): 
ALTER TABLE `db`.`mytable` ADD COLUMN `label` VARCHAR  AFTER `id`;  

Please fix all that

**Comment by huyphams** [comment]
Hey, @arnouxor thanks for the feedback. Currently, TablePlus support very well for PostgreSQL but many features for MySQL user is still missing (encode, data length, enum, seq...). We already know that and will improve it in the future updates. All of your issues are on our roadmap.

**Comment by huyphams** [comment]
It's fixed in the newest build. When creating a varchar, please also add the length of it. For example: varchar(20).
