### ISSUE TITLE
'Search for item' regexp support

### ISSUE THREAD

**Issue by kiakimov** [TablePlus/TablePlus#342]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7.19
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
94
3. The steps to reproduce this issue:
Search for item input box
It would be good to support regexp there like `table1|table2` like SequelPro does

Thank you for the good product!

**Comment by huyphams** [comment]
Hi @kiakimov I added this feature in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks.

**Comment by huyphams** [comment]
it's supported now in build 118.
