### ISSUE TITLE
In the official software, the Oracle database driver cannot be downloaded

### ISSUE THREAD

**Issue by leyulv3** [TablePlus/TablePlus#3424]
In the official software, the Oracle database driver cannot be downloaded. 
When attempting to download the driver, it shows “starting download” but does not complete, even after a long wait. 
The current version in use is the latest version of TablePlus.

**Comment by huyphams** [comment]
Hi @leyulv3 please restart the app and try again, could be a slow network.

**Comment by leyulv3** [comment]
I have tried restarting, uninstalling and reinstalling, and waiting for an extended period, but the download still does not complete successfully. However, in the testing version, I can connect to the database directly using the Oracle driver.

**Comment by leyulv3** [comment]
> Hi @leyulv3 please restart the app and try again, could be a slow network.嗨，请重新启动应用程序并重试，可能是网络速度较慢。
I have tried restarting, uninstalling and reinstalling, and waiting for an extended period, but the download still does not complete successfully. However, in the testing version, I can connect to the database directly using the Oracle driver.

**Comment by huyphams** [comment]
The Oracle version is actually the beta release, so you're using the test build, that's correct build.

**Comment by leyulv3** [comment]
> The Oracle version is actually the beta release, so you're using the test build, that's correct build.Oracle 版本实际上是 beta 版本，所以你使用的是测试版本，这是正确的版本。

Oh, thank you! May I ask when Oracle will be fully supported in the official release?

**Comment by huyphams** [comment]
Not anything soon. Oracle official driver is full of bugs and heavy (bloated).

**Comment by huyphams** [comment]
the app with 200MB could goes up to nearly 1GB because of Oracle Driver. so not anytime soon, it will be in beta for a long time.

That's why it take time to download too.
