### ISSUE TITLE
When previewing data in Oracle, a large dataset causes the software to crash and close unexpectedly.

### ISSUE THREAD

**Issue by leyulv3** [TablePlus/TablePlus#3425]
In the latest version of TablePlus, when using Oracle (version 12.2), the “Preview Data” feature and SQL query execution are not functioning correctly. If the dataset is large, the software crashes immediately.

**Comment by leyulv3** [comment]
@huyphams Please take a look at this issue.

**Comment by huyphams** [comment]
please check this out @leyulv3 https://github.com/TablePlus/TablePlus/issues/3342
