### ISSUE TITLE
Feature: DB process list as a plugin

### ISSUE THREAD

**Issue by kiakimov** [TablePlus/TablePlus#343]
DB process list with ability to kill particular one
For MySQL at least :)

**Comment by huyphams** [comment]
Thank @kiakimov, It's on our roadmap 👍

**Comment by sunkaiqin** [comment]
We are starting to use TablePlus as well and really like this feature to be implemented. 

I also would like to recommend the functions below:
1. Add auto refresh functions, refresh 5, 10, 15... seconds
2. Filter sleeping thread

**Comment by stefnats** [comment]
What @sunkaiqin - we are switching vom Sequel Pro to TablePlus right now and this is the only feature we're missing.

**Comment by sunkaiqin** [comment]
@huyphams Although I have the license from TablePlus, I still use DBeaver most of time since it has that feature as well. I need it because I need monitor some huge DB table migration process. With that feature I could see the process list  and replication lag information easily and make some decision quickly.

**Comment by huyphams** [comment]
Hi guys, thank you for taking the time to give me feedback. I appreciate, without the feedback, I have no insight on how people are using TablePlus at work. (I'm using TablePlus at work too, but clearly, my need are not as the same with your).

DB Process aims to be a feature that can control connections/queries which are taking too long to respond, or it can be used to kill a running query on the server. So I think it should be an advanced tool and uses a different connection (not share with the current connection), so it can't be affected by the current app state (hang, freeze...)

I will put this feature into our backlog as an advanced tool.

We have got a big and long term plan with TablePlus and surely, this feature is a part of it.

**Comment by shaynem** [comment]
> DB process list with ability to kill particular one
> For MySQL at least :)

+1

**Comment by huyphams** [comment]
It's supported for months, you guys can show the process list by pressing command + . or go to menu Connection > Process List...

**Comment by shaynem** [comment]
How is this supposed to work. 

It flashes up a query when spamming the refresh button, but you end up missing it. 

Otherwise it stays blank. 

Meanwhile other apps can show the process list without issues.
________________________________

**Comment by kiakimov** [comment]
No, this is not supported, I initially requested `SHOW PROCESSLIST` not the list of queries app is running ... Check how SequelPro does it...

**Comment by huyphams** [comment]
The process list and running queries are the same @kiakimov the main difference is TablePlus only shows the queries came from itself and ignores the query/connection from other clients.

When designing this feature, I want to limit the ability of TablePlus (for safety), but it seems people want to use TablePlus to kill queries from other clients as well. We will consider to remove the filter and show all the queries/connections from other clients (maybe a checkbox).

**Comment by shaynem** [comment]
Perfect, this will allow monitoring and debug of other connections to the server, I'm not certain the current functionality is of any use. 

It will also mimic functionality of other applications we are all migrating from. 
________________________________

**Comment by juanpebalsa** [comment]
I think my issue (#3289) might be related to this thread.
