### ISSUE TITLE
Charts do not support multiple statements

### ISSUE THREAD

**Issue by mbStavola** [TablePlus/TablePlus#3430]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

570

4. The steps to reproduce this issue:

In the metrics view, create a chart backed by a query which utilizes multiple statements:

```sql
SET @x = 'a';
SET @y = 5;

SELECT @x AS x, @y AS y;
```

The chart will not populate nor will the x-axis and y-axis dialogs populate possible column choices.

<img width="1017" alt="Screenshot 2024-11-01 at 5 49 21 PM" src="https://github.com/user-attachments/assets/e0c5500d-3a6b-4cad-a278-6ea8f026c82a">

**Comment by mbStavola** [comment]
Pretty dumb workaround, but you can abuse sub-queries and the assignment operator to compact things into one select statement:

```sql
SELECT 
	@foo AS first_column, 
	@bar AS second_column, 
	@foo + @bar AS third_column
FROM (
	SELECT
		@foo := 1,
		@bar := @foo + 2
) var_setup;
```

This makes the charts work as expected, but its still annoying to do.

**Comment by huyphams** [comment]
Hi @mbStavola if you have a chance, you can try this patch https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=vq16rrz1&dl=0
It should resolve the issue.

**Comment by mbStavola** [comment]
@huyphams I've been testing this for the last few days and it seems to work well, thanks for the fix!

Now that this is fixed, I do notice that sometimes charts do not populate properly after execution... however I don't think it's related to this issue, but rather something I now see since my charts are working. If I keep seeing that behavior I'll open up a separate issue.
