### ISSUE TITLE
Latest build installed but still old version number shown

### ISSUE THREAD

**Issue by pkalusek** [TablePlus/TablePlus#3438]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 8

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
clientBuild=256 version=1.2.1

4. The steps to reproduce this issue:
install 1.2.2 
open tableplus
version 1.2.1 shown

I have updated table plus via the cli on my fedora maschine. It says that the latest build is installed
![image](https://github.com/user-attachments/assets/1242eab3-3624-40a9-8860-078637382418)

But when opening table plus the old version is still the one it starts with:
![image](https://github.com/user-attachments/assets/0e9a4bf5-4fdd-43b7-b798-8bbcf6380dca)

I tried to remove the package and install it again. Doesnt matter. 
Is there some caching problem?

**Comment by huyphams** [comment]
Hi @pkalusek I'm sorry for the issue. You can remove TablePlus and install it again, it should solve the issue.

**Comment by pkalusek** [comment]
Tried that already. 
Tried it now, but the install failed
![image](https://github.com/user-attachments/assets/f65bfd06-9bf0-49fe-a218-ed0190244895)

**Comment by huyphams** [comment]
Please do the sudo yum dnf update tableplus then sudo dnf install tableplus 

it will invalidate the cache

**Comment by pkalusek** [comment]
sudo dnf clean all for clearing the cache & and installing it worked.
Thank you for your quick help!
