### ISSUE TITLE
Add support for two-factor auth with ssh

### ISSUE THREAD

**Issue by bdougherty** [TablePlus/TablePlus#344]
I'm trying to connect to MySQL over ssh with build 94 but I get an error: "Invalid host password".

I have two-factor authentication set up on my server, so when I ssh with my ssh key, there is an additional prompt to enter the verification code. I have successfully connected this way with both Querious and Sequel Pro, both of which will prompt me for the verification code. It would be great if TablePlus was able to support this as well!

**Comment by huyphams** [comment]
Thanks @bdougherty I will take a look and implement it in TablePlus.

**Comment by huyphams** [comment]
Hey @bdougherty I have implemented keyboard-interactive support in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
But I haven't a host with ssh two-factor authentication setup. It would be great if you can test it and let me know if it works for you.
Thanks.

**Comment by huyphams** [comment]
Thanks for the feedback. I have changed the method keyboard interactive. Can you give it a try: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
I hope it will work.

**Comment by bdougherty** [comment]
That build works perfectly! Thank you!

**Comment by loopdtw** [comment]
@huyphams will this build be integrated into the official release?

**Comment by huyphams** [comment]
@loopdtw it's already released. Does the build 110 work for you?
