### ISSUE TITLE
Hung on big table How to prevent TablePlus to count a table or make it configurable for all table

### ISSUE THREAD

**Issue by yusufmalikul** [TablePlus/TablePlus#3442]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Linux 1.2.0 (254)

3. The steps to reproduce this issue: Click on a table, Tableplus will send count(*) query which make it hang on big table.

Noted: If the bug is related to data, please attach an example SQL data.

![image](https://github.com/user-attachments/assets/7fa0d584-36cb-494d-904e-c364349ae5f6)

**Comment by yusufmalikul** [comment]
sorry wrong repo

**Comment by nangtrongvuon** [comment]
@yusufmalikul Can you run the query above the `SELECT COUNT(*)` to see what the estimated row count is?
