### ISSUE TITLE
Chart seems incorrect in metric board

### ISSUE THREAD

**Issue by scolestock** [TablePlus/TablePlus#3447]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySql 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 6.1.8 (574)

3. The steps to reproduce this issue:

I have the identical query running for the two visuals below, but the graph doesn't seem to show values correctly for the "waiting" line - it is showing the line at zero instead of the values in the table. 

<img width="1458" alt="image" src="https://github.com/user-attachments/assets/ffdec272-56c2-4076-8463-d84dff3004af">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
hi @scolestock it seems you enter the wrong column name, should it be waiting_jobs instead of waiting?

**Comment by scolestock** [comment]
Well that's embarassing - thanks @huyphams
