### ISSUE TITLE
MySQL Connection - Views are not displayed separately from the Tables.

### ISSUE THREAD

**Issue by lcallif** [TablePlus/TablePlus#3449]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    - 

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
   6.2.0 (576)

5. The steps to reproduce this issue:
    Create 1 or more views.
    Display all the tables
    There should be a list of items for:
           - Functions
           - Tables
           - Views
    There is currently only "Functions" and "Tables" displayed.

This is not a bug, but an expected result. There should either be a way to display the views separately from the Tables & Functions OR by qualifying the type of Tables to be displayed when clicking on "Tables".

The attached is from PhpStorm, but it works very similar to phpadmin.
![Screen Shot 2024-11-24 at 11 33 52 AM](https://github.com/user-attachments/assets/735f7813-4f46-482c-8675-3da89a6c2d8d)

**Comment by huyphams** [comment]
Hi @lcallif this is the current design not an issue. We're redesign new version 7.0 with a option and new sidebar. You may want to follow us to get more updates https://x.com/TablePlus/status/1859789036099076571

**Comment by lcallif** [comment]
I should have had "VIEW" as the table's prefix which would have resolved this wayyyyyyy before I found it.  The prefix will work great.

As to the view, I am running into an issue when the view is created via TablePlus.  I will make a new entry for it.

So far, the product looks like it will work VERY nicely for me.  Thank you to the team for their hard work!
