### ISSUE TITLE
⌘E is a dangerous shortcut

### ISSUE THREAD

**Issue by richardpenner** [TablePlus/TablePlus#345]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgres 8.0.2
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 (94)
3. The steps to reproduce this issue:
Hit ⌘E. The expected Mac app behaviour is that this copies the selected text to the Find buffer. 

I typically keep hundreds of lines of recent SQL in my editor, and just highlight what I want to run at the moment. But in the current setup, each time I hit ⌘E I end up running stuff that shouldn't be run.

**Comment by davidolrik** [comment]
You can make it a bit more safe by changing the option in the selector in the bottom right of the query window from `Run All` to `Run Current`.

**Comment by richardpenner** [comment]
Thanks – did not see the option to change the default.

**Comment by huyphams** [comment]
Hey! thanks @davidolrik
@richardpenner I will make a popup that says `we can change the config Run All > Run Current` at the first time user hit Run Query.

**Comment by richardpenner** [comment]
Would you consider changing the default to ⌘ Enter?

**Comment by huyphams** [comment]
Hi @richardpenner TablePlus supports both command + e and command + return/enter.

**Comment by richardpenner** [comment]
Thanks, I do use command return/enter. I find myself switching between Sublime Text and TablePlus a lot, and while most mac keyboard shortcuts work in both, I'd love to see consistency for this one too, i.e. command enter is how you run SQL, and command E is to put the selected text into the find buffer.

**Comment by huyphams** [comment]
I didn't know that the `command + E` was used for putting the selected text into the finder 👍

**Comment by huebs** [comment]
I was surprised by this behavior as well.  Specifically, Sequel Pro uses `⌘ + E` for "Use Selection For Find".  Is keyboard shortcut parity a design goal?

**Comment by keithslater** [comment]
I would opt for command + R to be default.. And if something is selected, it should run that without a modifier. If nothing is selected then it runs everything.

**Comment by huyphams** [comment]
Hi guys, TablePlus will allow remapping shortcut key in future updates, that means you can change cmd + R, cmd + return or disable a shortcut key easily.

**Comment by huyphams** [comment]
Hi, I've added an ability to change the hotkey so it should not be a problem anymore, you can download the hotpatch here: https://www.dropbox.com/s/bskp6rf1julta52/tableplus.dmg?dl=0
