### ISSUE TITLE
"Beautify" command doesn't do anything anymore

### ISSUE THREAD

**Issue by ahtinurme** [TablePlus/TablePlus#3455]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 576

3. The steps to reproduce this issue: 
Paste SQL below into app and try to run "Beautify" command - nothing happens.

Noted: If the bug is related to data, please attach an example SQL data.
``
select`A` .`object_id`,`A` .`StartTime`,`objects` .`categoryID`,`objects` .`tank_vol`,`objects` .`barrel_type`,DATE_FORMAT(CONVERT_TZ(A.MaxTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS`key`,DATE_FORMAT(CONVERT_TZ(A.StartTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS tmStart,COUNT(A.fr_id)AS fuel_times,SUM(A.after)-SUM(A.before)AS fuel_litres,0 AS loss_times,0 AS loss_litres from`fuel_report1` as`A` where`A` .`after`>`A` .`before` and`A` .`object_id`='622LSX' and`MaxTime` between'2024-11-30 22:00:00' and'2024-12-01 21:59:59' and`A` .`object_id`='622LSX' group by`key`)union(select`A` .`object_id`,`A` .`StartTime`,`objects` .`categoryID`,`objects` .`tank_vol`,`objects` .`barrel_type`,DATE_FORMAT(CONVERT_TZ(A.MaxTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS`key`,DATE_FORMAT(CONVERT_TZ(A.StartTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS tmStart,0 AS fuel_times,0 AS fuel_litres,COUNT(A.fr_id)AS loss_times,SUM(A.after)-SUM(A.before)AS loss_litres from`fuel_report1` as`A` where`A` .`after`<`A` .`before` and`A` .`object_id`='622LSX' and`MaxTime` between'2024-11-30 22:00:00' and'2024-12-01 21:59:59' and`A` .`object_id`='622LSX' group by`key`
``

**Comment by huyphams** [comment]
Hi @ahtinurme your query contains an error missing the `(` at the beginning and the `)` at the end
```
(select`A` .`object_id`,`A` .`StartTime`,`objects` .`categoryID`,`objects` .`tank_vol`,`objects` .`barrel_type`,DATE_FORMAT(CONVERT_TZ(A.MaxTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS`key`,DATE_FORMAT(CONVERT_TZ(A.StartTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS tmStart,COUNT(A.fr_id)AS fuel_times,SUM(A.after)-SUM(A.before)AS fuel_litres,0 AS loss_times,0 AS loss_litres from`fuel_report1` as`A` where`A` .`after`>`A` .`before` and`A` .`object_id`='622LSX' and`MaxTime` between'2024-11-30 22:00:00' and'2024-12-01 21:59:59' and`A` .`object_id`='622LSX' group by`key`)union(select`A` .`object_id`,`A` .`StartTime`,`objects` .`categoryID`,`objects` .`tank_vol`,`objects` .`barrel_type`,DATE_FORMAT(CONVERT_TZ(A.MaxTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS`key`,DATE_FORMAT(CONVERT_TZ(A.StartTime,'UTC','Europe/Tallinn'),'%d.%m.%Y')AS tmStart,0 AS fuel_times,0 AS fuel_litres,COUNT(A.fr_id)AS loss_times,SUM(A.after)-SUM(A.before)AS loss_litres from`fuel_report1` as`A` where`A` .`after`<`A` .`before` and`A` .`object_id`='622LSX' and`MaxTime` between'2024-11-30 22:00:00' and'2024-12-01 21:59:59' and`A` .`object_id`='622LSX' group by`key`)
```

**Comment by huyphams** [comment]
However, TablePlus should show an error instead of doing nothing.
