### ISSUE TITLE
Feature Request: Shortcut for toggling panes

### ISSUE THREAD

**Issue by strokirk** [TablePlus/TablePlus#3465]
Hello, and thanks for such a wonderful database client as TablePlus!

To my mind, the right sidebar is one of the "killer features" of TablePlus, and something I use all the time. But sometimes it's useful to hide the sidebars quickly to get more space.

It would be great if there was a configurable hotkey for `View > Toggle Sidebars > Toggle Right/Left/Bottom Sidebar`.

I suggest Cmd+Opt+N/M for toggling left and right sidebars!

**WORKAROUND**
As a workaround, it's possible to add a MacOS App shortcut from `Keyboard > Keyboard Shortcuts... > App Shortcuts`. But that is time consuming and error prone, since you have to match the spelling Exactly.

**Comment by huyphams** [comment]
Hi @strokirk you can hover the mouse on the button to see the shortcut

**Comment by strokirk** [comment]
@huyphams Sorry, my mistake - since I've done the remapping in MacOS App shortcuts I must have forgotten about the default shortcuts for these.

It would still probably be nice if it was configurable from within TablePlus, but that's a separate request. Closing this one.
