### ISSUE TITLE
Set default schema to 'main' for DuckDB instead of information_schema

### ISSUE THREAD

**Issue by voidexpr** [TablePlus/TablePlus#3468]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

duckdb

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 6.2.0 (576)

5. The steps to reproduce this issue:

Just open any duckdb instance

--

So not sure if this is DuckDB only or for all databases but the default schema/tablespace in "item" is "information_schema" which isn't useful. It would be much nicer to default to "main" or at least remember the choice made and use it as a default.

**Comment by huyphams** [comment]
Hi @voidexpr, if you create a connection, it will automatically remember your choice the next time you open it.

**Comment by voidexpr** [comment]
That's good. Any chance to change the default to not be information_schema ? it seems to be the wrong default.

**Comment by huyphams** [comment]
Thanks, will do.
