### ISSUE TITLE
[BUG] Autopreview doesn't work for next record after deleting

### ISSUE THREAD

**Issue by boringpapa** [TablePlus/TablePlus#3469]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MS SQL 2019 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 6.20 576

3. The steps to reproduce this issue:
Delete a record , next record is highlighted but not previews. Please see video attached below highlighting 

https://www.loom.com/share/b5edd958cee74fedb6c40f0861ceeb14?sid=e5f59c0d-0818-40c7-b5a4-f5c854673e97

**Comment by huyphams** [comment]
Thanks @boringpapa we just fixed this issue, will be available next month!
