### ISSUE TITLE
SQLite3 ( Encrypted )

### ISSUE THREAD

**Issue by l41lt0n** [TablePlus/TablePlus#347]
@huyphams,

Do you have any news about support to open encrypted database ( using SQLCipher for example ).

Thanks, It is very important for me. :)

**Comment by huyphams** [comment]
Hey, good news, I just added support cipher for SQLite. 
1. Download this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0 
2. Create an SQLite connection.
3. Check on load resource and add the execute script when starting the connection.
For example this script:
PRAGMA key = "x'2DD29CA851E7B56E4697B0E1F08507293D761A05CE4D1B628663F411A8086D99'";

**Comment by l41lt0n** [comment]
Hi Huy,

Excellent! Works like a charm.
You only need to make it more friendly. add the key to be applied to the config. look like this:

![screen shot 2018-03-27 at 9 56 55 pm](https://user-images.githubusercontent.com/32529405/38002635-d10a388a-3209-11e8-818b-3f9eff926275.png)

And next that connection is opened and the key is applied, it should to reload workplace to show table.

Thank you.

**Comment by l41lt0n** [comment]
@huyphams,

Please rethink about it. all the database manager has it.
and for me no make sense dont add it if all connection has password fields.

![screen shot 2018-03-28 at 8 23 35 am](https://user-images.githubusercontent.com/32529405/38026198-9768fdca-3261-11e8-9c86-7887aaa9ad0d.png)
![screen shot 2018-03-28 at 8 23 50 am](https://user-images.githubusercontent.com/32529405/38026199-97a51bac-3261-11e8-99d3-950c9dc1200e.png)
![screen shot 2018-03-28 at 8 24 05 am](https://user-images.githubusercontent.com/32529405/38026200-97d4b61e-3261-11e8-90e0-3720f91b3f8d.png)
![screen shot 2018-03-28 at 8 24 29 am](https://user-images.githubusercontent.com/32529405/38026202-98073602-3261-11e8-8d13-8d219a82f66e.png)

So, I don't see reason for you don't add it.
It will only make it better.

Thanks.

**Comment by huyphams** [comment]
Hey @l41lt0n thanks, I think we have a misunderstood here. I thought we are talking about the preferences. it's no problem with putting the config in SQLite connection form.

**Comment by l41lt0n** [comment]
Hi @huyphams 
That's it.
Sorry, maybe I was not so clarify.

my english is in progress 👍

**Comment by l41lt0n** [comment]
@huyphams,

Can you provide the new field to set password to SQLITE ( encrypted )??

I have updated and it was missed 👎 

Please check it

**Comment by huyphams** [comment]
Sure, but I have to refactor the form a little bit, you can expect it in the next update 👍

**Comment by l41lt0n** [comment]
@huyphams,

Okay, thank you! 👍
