### ISSUE TITLE
When run Beautify, comment and query get merged together

### ISSUE THREAD

**Issue by bannnn511** [TablePlus/TablePlus#3476]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 17.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 6.0.0 (550)

3. The steps to reproduce this issue:
When I use the beautify feature, the comment and query get merged. **This happens when the cursor is in the first query after the comment**.

Before beautify (**cursor at line 76**)
<img width="461" alt="image" src="https://github.com/user-attachments/assets/070f4aa4-a38d-42c7-8ba9-a3dfe6e66fd0" />

After beautify
<img width="511" alt="image" src="https://github.com/user-attachments/assets/34695c82-bba9-48cb-81fa-d91403997112" />

**Comment by huyphams** [comment]
hi @bannnn511 I think the issue has been fixed in our latest release
