### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by l41lt0n** [TablePlus/TablePlus#348]
There's no way to create a new database from GUI ?

I have executed the query directly to create the database to be able to create tables.

![screen shot 2018-03-22 at 12 07 20 am](https://user-images.githubusercontent.com/32529405/37749075-09782cb2-2d65-11e8-9bdd-591861e71b32.png)

**Comment by Tungtono** [comment]
Two ways to create a new database using TablePlus:
1. From the welcome screen, click restore, choose the connection, then you'll see "New database" button on the right.
<img width="772" alt="screen shot 2018-03-22 at 10 11 53" src="https://user-images.githubusercontent.com/10219818/37749226-97c951d6-2db9-11e8-8383-002c15d7e166.png">

2. While you're connecting to a database, click the database icon ("show list database" or command + K) near the top left of the window, right-click to a database and choose "new"
<img width="922" alt="screen shot 2018-03-22 at 10 13 21" src="https://user-images.githubusercontent.com/10219818/37749246-b08fe37e-2db9-11e8-9979-eead51e559a2.png">

**Comment by l41lt0n** [comment]
Thanks 👍
