### ISSUE TITLE
MySQL Query Execute.

### ISSUE THREAD

**Issue by l41lt0n** [TablePlus/TablePlus#349]
Why if I execute for example:

SELECT * FROM tab_one;
SELECT * FROM tab_two;

It show me message on the top 2 query

![screen shot 2018-03-22 at 12 17 30 am](https://user-images.githubusercontent.com/32529405/37749543-27e7a64e-2d67-11e8-84b1-286ae3ab6e1a.png)

It will show me only the last.

Other example:

SELECT * FROM tab_one;
INSERT INTO tab_one ( id, nome ) VALUES ( 1, "TablePlus" );

![screen shot 2018-03-22 at 12 25 26 am](https://user-images.githubusercontent.com/32529405/37749625-8d916494-2d67-11e8-8b11-4de1ca3b5418.png)

Expected to be like this:

![screen shot 2018-03-22 at 12 27 14 am](https://user-images.githubusercontent.com/32529405/37749680-daf288d0-2d67-11e8-8feb-a3fa356647de.png)
![screen shot 2018-03-22 at 12 27 34 am](https://user-images.githubusercontent.com/32529405/37749688-df12ee32-2d67-11e8-959f-04426c107a56.png)

So, no matter how much query (select, insert, update, delete etc), it should show the results.

![screen shot 2018-03-22 at 12 28 39 am](https://user-images.githubusercontent.com/32529405/37749768-50adbf9a-2d68-11e8-9b44-659e4bbcfd46.png)

Thanks.

**Comment by Tungtono** [comment]
Hey, we do have the option to split results into tabs, please check whether it's on or off:
<img width="507" alt="screen_shot_2018-03-22_at_10_46_06" src="https://user-images.githubusercontent.com/10219818/37750235-90d08f2a-2dbe-11e8-8a37-2189345bb5c4.png">
Then result from each query will be split into different tabs.

**Comment by l41lt0n** [comment]
Hi @Tungtono,

That's it! thanks. 

Sorry it was disabled.
