### ISSUE TITLE
In main DB select window, add option to replace '127.0.0.1' with the Host Name

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#35]
'127.0.0.1' is my local IP address.  But many of these endpoint DBs are not local at all, and have Host Names that are remote processes.  But it still says '127.0.0.1'.  Perhaps add option to replace this text with Host Name.

![screen shot 2017-08-03 at 2 39 32 pm](https://user-images.githubusercontent.com/7946786/28945168-3ac08050-785a-11e7-9170-81451c3c73d8.png)

**Comment by huyphams** [comment]
I came back to my hometown. I will offline in couple next days.

**Comment by huyphams** [comment]
I confirmed. it's bug. It should be hostname or host IP.

**Comment by huyphams** [comment]
Hi @brian-crane if you connect to database on server , I suggest you using Table SSH feature. It's more safe for your database and server.
You can read more here: [using ssh tunneling to connect database](https://medium.com/@huyphams/how-using-ssh-tunneling-in-database-tools-might-leak-your-connection-forever-c6d48ff18746)
