### ISSUE TITLE
Can't see SQL unless connected

### ISSUE THREAD

**Issue by richardpenner** [TablePlus/TablePlus#352]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
8.0.2
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
94
3. The steps to reproduce this issue:
If you lose your connection, your options are to Close, Edit the Connection, or Try Again. But none of these options let you see your SQL, so your editor is not available unless you are connected. In my case I use SSH tunnelling and am not in a constantly connected state, but would like to reference the SQL editor.

**Comment by Tungtono** [comment]
Hi @richardpenner,
Because without the connection, you'll not be able to access your database, so I'm not sure the purpose of seeing the SQL editor here. But there's one so-called SQL editor that lets you write the query in case you are not connected, that you can open it using shortcut key **Cmd + Shift + O**
Is that what you are looking for?

**Comment by richardpenner** [comment]
Not exactly. I often get the SQL I want sorted in TablePlus, then switch to Sublime Text to write it in my code. I am only connected to our data warehouse when I have an SSH tunnel open, but there are times when I don't have that tunnel open, but want to reference the SQL that I've written in TablePlus while writing code (and not connected).

As a side note, I have a few hundred lines of SQL in my editor from various queries throughout the past week or so, and I occasionally want to reference that SQL when I am not connected.

**Comment by keithslater** [comment]
I'm curious as to which sql client you previously used. It seems like you're more use to a SQL IDE like DataGrip as opposed to something like Sequel Pro.

**Comment by richardpenner** [comment]
Postico mainly

**Comment by huyphams** [comment]
Hi @richardpenner I read the issue again and understood the situation 👍 I will improve it.
Connected -> Write SQL -> Lose connect -> Can't see the SQL untill reconnect (but it should allow).

**Comment by richardpenner** [comment]
That’s exactly right, thank you!

**Comment by huyphams** [comment]
This feature is released in build 107.

**Comment by richardpenner** [comment]
It works just as I'd hoped. Thank you!
