### ISSUE TITLE
Please support AUTO_INCREMENT columns for MySQL

### ISSUE THREAD

**Issue by natesilva** [TablePlus/TablePlus#354]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **MySQL 5.6.10 (Amazon Aurora)**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **build 95**

3. The steps to reproduce this issue:

* Connect to a MySQL database
* Create a table
* Try to set the `auto_increment` attribute for the `PRIMARY KEY` column: can’t find that option.

**Workaround:** Right now you can create an `auto_increment` column by using the `SERIAL` data type, but that may not be appropriate:

* `SERIAL` creates a `BIGINT` column, but at my company many of our tables use `INT(10) UNSIGNED`.
* If you already created a column, there is no way to change it to add the `auto_increment` attribute.

**Comment by huyphams** [comment]
Hi @natesilva sure, we are working to upgrade UI of table structure that supports encode, seq, and much more... please keep the app up to date because it will be released soon 👍

**Comment by natesilva** [comment]
Thank you!

**Comment by huyphams** [comment]
Hey @natesilva I just added support set extra (include auto increasement) in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

You can check out that build until the official release.

**Comment by natesilva** [comment]
It work. Thank you!

**Comment by blaasvaer** [comment]
And where do I find the auto increment feature?

**Comment by huyphams** [comment]
Hi @blaasvaer which driver are you using @blaasvaer if you are using MySQL there is a column `extra`. If you are using PostgreSQL it sequence (using column_default).

**Comment by blaasvaer** [comment]
This I don't get: If you are using PostgreSQL it sequence (using column_default).

Could you be more specific (where in the interface, what tab, what view ... )?

**Comment by blaasvaer** [comment]
I need to make the 'id' column auto increment:

![screen shot 2018-05-16 at 15 01 31](https://user-images.githubusercontent.com/1193257/40118389-16f0fd8e-591a-11e8-8d2f-5fabe921832b.png)

**Comment by blaasvaer** [comment]
It's certainly NOT intuitive ...

**Comment by huyphams** [comment]
Hi @blaasvaer each driver has difference implement. I always follow the native implement. PostgreSQL uses sequence for auto_increment. So you can set the sequence as the default value for the column like this:
<img width="649" alt="nice" src="https://user-images.githubusercontent.com/3654622/40118647-b3be1a46-5944-11e8-9e5c-d30500cd42c5.png">

**Comment by blaasvaer** [comment]
I cannot set sequence to ANYTHING and save it. It just fails ...

**Comment by blaasvaer** [comment]
Ok, and WHAT is the_sequence_name representing (what would a proper name be in relation to auto incrementing an id field)?

**Comment by blaasvaer** [comment]
Great, thanks a lot!
