### ISSUE TITLE
History timestamps all show current time

### ISSUE THREAD

**Issue by nickhandel** [TablePlus/TablePlus#356]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Happens on both PG and mySQL - suspect this is a local app thing.
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 (95)
3. The steps to reproduce this issue:

Execute some SQL queries
Look at the history - all the timestamps show as the current time.

I am running MacOS High Sierra with all the latest stuff.

**Comment by huyphams** [comment]
It's perfect now, thank you 👍 
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by nickhandel** [comment]
Cool.  Thank you!

altoDATA
nick@altodata.co.uk<mailto:nick@altodata.co.uk> ∙ +44 (0)7880 736080

On 25 Mar 2018, at 19:37, Huy Pham <notifications@github.com<mailto:notifications@github.com>> wrote:


It's perfect now, thank you 👍
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
