### ISSUE TITLE
Home and end keys

### ISSUE THREAD

**Issue by nickhandel** [TablePlus/TablePlus#357]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
95 
3. The steps to reproduce this issue:

Really like the app - thanks for fixing the history time stamps!

Feature request:

I've got used to the way many editors (pgAdmin, IDLE, mySQL Workbench etc.) treat "home" and "end" on an extended keyboard as beginning of line and end of line.  At the moment they don't do anything in the SQL editor.  Would be great to allow them to be used instead of ⌘-← and ⌘-→.  Either as a customisation or as a checkbox in prefs or similar.

Thanks!

Nick

**Comment by huyphams** [comment]
Hey @nickhandel thanks for the suggestion. We will support it in the next update 👍
