### ISSUE TITLE
Sort table by multiple columns

### ISSUE THREAD

**Issue by jeremistadler** [TablePlus/TablePlus#358]
1. Which driver are you using and version of it: MySQL

2. Which TablePlus build number are you using: 91

3. The steps to reproduce this issue:
I want to sort on locations_location_id, locations_service_id, day 

![image](https://user-images.githubusercontent.com/3100817/37897056-87f18dda-30e5-11e8-8d46-35136f95b07d.png)

**Comment by JohnRomanski** [comment]
FYI, in case you need some inspiration, there is a cloud based data tool that enables you to sort by multiple columns by shift-clicking on subsequent column headers.

**Comment by huyphams** [comment]
Hi guys, we are considering this feature, I will try to implement it in the next update. If it is good, I will be released in the build 104.

**Comment by stefensuhat** [comment]
is this implemented?

**Comment by michaelhogg** [comment]
@huyphams: Thank you for all your awesome work on TablePlus! :smiley: :clap:

It looks like this feature isn't yet implemented (I'm using build 156). Do you have any news about when it'll be available?

**Comment by huyphams** [comment]
I have thought about it a couple of times. There are some possible solutions.
1. Add an operator that sort a column.
2. Click multiple columns.

<img width="1212" alt="solution" src="https://user-images.githubusercontent.com/3654622/49265624-7c6ac580-f485-11e8-8c43-5385dd4acf76.png">

**Comment by michaelhogg** [comment]
@huyphams: Many thanks for your quick reply and your annotated screenshot :slightly_smiling_face:

I think your Solution 2 would be great, as @JohnRomanski described [above](https://github.com/TablePlus/TablePlus/issues/358#issuecomment-385375877):

> sort by multiple columns by shift-clicking on subsequent column headers.

So it could work like this:

* Clicking on a column header would make it the primary sorting column.
    * Subsequent clicks on that same column header would cycle through the sorting modes for that primary column (ASC, DESC, unsorted).
* Once a primary sorting column has been chosen, then shift-clicking on a different column header would make that the secondary sorting column.
    * Subsequent shift-clicks on that same column header would cycle through the sorting modes for that secondary column (ASC, DESC, unsorted).
    * Shift-clicking on another different column header would make that the tertiary sorting column, and so on.
* The next "normal" click (ie: not a shift-click) on any column header would:
    * make it the primary sorting column
    * and clear/reset any secondary/tertiary sorting columns.

What do you think?

(By the way, today I [bought a TablePlus license](https://tableplus.io/pricing) :grin:)

**Comment by huyphams** [comment]
I'm working on solution 2, it will be released in the next update.

**Comment by huyphams** [comment]
Hi guys, please check out this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Hold Command + Right click on the column to multiple columns sort
<img width="1448" alt="multiplesort" src="https://user-images.githubusercontent.com/3654622/53813724-e2894c00-3f90-11e9-8704-377a5d07f247.png">

**Comment by aik099** [comment]
The `Option+Click` shortcut would actually be more Mac-alike, because `Option` means alternative behavior.

**Comment by huyphams** [comment]
I think command + click should be better @aik099 because it's a convention of macOS. You can select multiple files but hold command + click. All the mac apps can hold command + click to select multiple objects.
The only issue here is I couldn't find a way to override the command + click (or even option, I'm still trying.

**Comment by marin246** [comment]
Has this feature been implemented? I can't get it to work with the trial version.

**Comment by huyphams** [comment]
Hi @marin246 please read my previous comment
`Hold Command + Right-click on the column to multiple columns sort`

**Comment by marin246** [comment]
ah, my bad! thank you very much! Also, you need to select ASC or DESC after the right click. Maybe document this great feature on https://docs.tableplus.com ?
