### ISSUE TITLE
New, empty schema not showing up

### ISSUE THREAD

**Issue by thenaturalist** [TablePlus/TablePlus#359]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.0 
 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
95

3. The steps to reproduce this issue:
`CREATE SCHEMA xyz;`
No tables. The schema does not show up in the drop down list and it can't be queried (after refresh or even restart of TablePlus, when I would expect a new inspection to definitely take place). Postico and other clients show the schema.

**Comment by huyphams** [comment]
Hey @thenaturalist thanks for the feedback. It’s fixed in this build https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
👍

**Comment by thenaturalist** [comment]
Perfect, thanks! :)
