### ISSUE TITLE
Switch to database with search

### ISSUE THREAD

**Issue by adisos** [TablePlus/TablePlus#36]
I'd like to see switch to database with search function. It would be killer feature.

**Comment by huyphams** [comment]
Sure, we have a plan to improve `open anything` (command + P) to preview table, run sql and switch database as well

**Comment by huyphams** [comment]
Hi @adisos please checkout new build
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by adisos** [comment]
Cool!
