### ISSUE TITLE
Table Design

### ISSUE THREAD

**Issue by l41lt0n** [TablePlus/TablePlus#361]
Hello,

I have one suggestion to make the table design ( structure ) more friendly.

Look this:

![screen shot 2018-03-27 at 10 28 57 pm](https://user-images.githubusercontent.com/32529405/38003559-6479692a-320e-11e8-8438-243a75e2a825.png)

TablePlus,

I need to set the type ( INT ) and next I need set again INT( 10 ).

Why not only a field to select type and another to the size like the editor bellow?

I think that it is more friendly to edit.

only a suggestion.

Thanks

**Comment by huyphams** [comment]
It's already on our roadmap. The next version of table structure is more friendly than this version 👍

**Comment by l41lt0n** [comment]
Thanks!

**Comment by huyphams** [comment]
It's released in the newest build, if you found any bug, please create a separated issue for each them.
