### ISSUE TITLE
Filter not usable after a using it the first time

### ISSUE THREAD

**Issue by juice** [TablePlus/TablePlus#362]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL/MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 Build 96

3. The steps to reproduce this issue:

- Start a filter on a table.
- In my case, select a field name, asset_id = 23425
- Apply Filter
- Try to change the filter and apply again.
- The Filter is not working the second time and the Field list is empty except for RAW SQL
<img width="347" alt="screen shot 2018-03-28 at 07 49 21" src="https://user-images.githubusercontent.com/179705/38011247-f95f7d7e-325c-11e8-8a8a-11987183904f.png">

**Comment by huyphams** [comment]
Hey @juice thanks, we will fix it now :+1:

**Comment by huyphams** [comment]
Hey, @juice I just discovered that this bug happened when you enter an invalid data. (that generated invalid query)
Result return 0 columns => filter column empty.
I will handle this case 👍

**Comment by huyphams** [comment]
it's fixed: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by juice** [comment]
I tested this build an it still happens when i set a filter, update a row, click commit changes. After that the dropdown is empty.

**Comment by huyphams** [comment]
Hi @juice all the issues should be fixed on now on this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
I tested all the cases above. Thank you again 👍
