### ISSUE TITLE
Save Window State, open connections and filter

### ISSUE THREAD

**Issue by juice** [TablePlus/TablePlus#363]
Hello

i really **love** the new features. But this also means restarting the app with every update and reopen and connecting to all servers and sometimes setting many filters.

Every Mac App i use serializes its window state and tries to bring me back where i left off.

Could you bring me back to the days where i focus on the work and not on the app ;)

**Comment by huyphams** [comment]
Thanks and yup, this will be improved after table structure update 👍

**Comment by ndastur** [comment]
Is it possible to re-open this. It's especially annoying after doing an update. Even just re-opening by connections would be good

**Comment by huyphams** [comment]
You can turn on this feature in TablePlus prefs @ndastur
