### ISSUE TITLE
Trigger

### ISSUE THREAD

**Issue by juice** [TablePlus/TablePlus#364]
Hello

i'm not sure if i just overlook this feature, but i'm looking for a way to edit the triggers set in a Database.

Here is a Sequel Pro with this feature, i would like to switch once and for all to TablePlus, can you add this feature in the future?

<img width="216" alt="screen shot 2018-03-28 at 08 04 32" src="https://user-images.githubusercontent.com/179705/38011693-b7716b8c-325e-11e8-943b-816863dc2748.png">

**Comment by huyphams** [comment]
Hi @juice rebuild structure is already on our roadmap. The next big update is about table structure.
- Support data length.
- Support encode.
- Support enum.
- Support column comment.
And of course, triggers.

**Comment by juice** [comment]
Great News. 

I looked into the Work in Progress Section, but i have no Idea that "Remake structure view" includes all this. I read you guys on twitter, i read the blog, i look into the project view and the Issues, but i'm still clueless what will happen and when.

Is it possible to make a lightweight Roadmap, maybe in a Blog Post. So i get a Idea what your plan is for the next three month?

**Comment by huyphams** [comment]
It's here @juice https://github.com/TablePlus/TablePlus/projects/1

**Comment by juice** [comment]
Yes, i looked into the Projects Section, but i'm still not sure what this means and includes.

 "Remake structure view" was not clear to me that this includes Triggers :)

I would like to see a something like this: https://github.com/Microsoft/vscode/wiki/Roadmap

**Comment by huyphams** [comment]
It's supported now. Please check out the release 104.

**Comment by juice** [comment]
@huyphams Hi, great news! I tried it with MSSQL and PostgreSQL, thanks for that. But it looks like it is not working with MSSQL Server (2012)?

**Comment by huyphams** [comment]
Currently TablePlus only supports trigger in MySQL and PostgreSQL, I will added more driver in next release.
The next driver is MSSQL.

**Comment by bshea5** [comment]
@huyphams , did a MSSQL driver ever get introduced? I'm looking at a table that has a trigger, but that button is disabled for me. Using SQL 2012.

<img width="282" alt="Screen Shot 2019-09-11 at 12 23 12 PM" src="https://user-images.githubusercontent.com/3984775/64727992-f3aa9c80-d48e-11e9-86ad-b610c9fb043d.png">

**Comment by fgcui1204** [comment]
Hi  @huyphams , how does MSSQL process? looking forward to using it.

**Comment by mbet-boka** [comment]
HI @huyphams, any update on the MSSQL support for triggers?

**Comment by marcejohnson** [comment]
In 2018 @huyphams wrote:
> "Currently TablePlus only supports trigger in MySQL and PostgreSQL, I will added more driver in next release.
> The next driver is MSSQL."

This was three years ago.  Did support for MSSQL get released?  Thanks!
