### ISSUE TITLE
⌘` should cycle between windows

### ISSUE THREAD

**Issue by dsego** [TablePlus/TablePlus#365]
On macs with US-keyboards   ``⌘ ` ``  ( cmd+backtick ) is the common way to cycle through all open windows of the current application. TablePlus hijacks this for running custom scripts instead.  
<img width="252" alt="screen shot 2018-03-28 at 1 36 33 pm" src="https://user-images.githubusercontent.com/578557/38026826-d9904a06-328d-11e8-8257-39cf42fbb9a7.png">

**Comment by huyphams** [comment]
Hi, @dsego  thanks for the feedback. Since the custom script is not important now, we will remove this shortcut in next update 👍

**Comment by huyphams** [comment]
if you can't wait for the next update, you can get the hot-patch build here, I just removed the shortcut key: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by dsego** [comment]
Great job, it works! 🎉
