### ISSUE TITLE
OSX 10.11 - EL Capitan. TablePlus crashes opening SQL Editor.

### ISSUE THREAD

**Issue by adrianxplay** [TablePlus/TablePlus#366]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 9.5.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 96

3. The steps to reproduce this issue:

- Open TablePlus
- Use any connection
- Click on SQL button or ⌘ + E

**Comment by huyphams** [comment]
Hi @adrianxplay are you on OSX 10.11? it's been fixed in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by adrianxplay** [comment]
Hi @huyphams Is that an older version?

Thanks.

**Comment by huyphams** [comment]
No @adrianxplay , it's hot patch for OSX 10.11. I just discovered an issue related to El Capitan and build a hotfix build. It will be included in next update. You can use that build until it's official release.

**Comment by adrianxplay** [comment]
Well, thank you @huyphams. I appreciate it.
