### ISSUE TITLE
Cant delete row in SQLite db

### ISSUE THREAD

**Issue by matheus2740** [TablePlus/TablePlus#368]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQLite 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 96

3. The steps to reproduce this issue:

Open any table, delete a row and try to commit.

Error message is "no such module: rtree" and nothing gets deleted.

**Comment by huyphams** [comment]
Hey thanks for letting me know, I will check this error 👍

**Comment by matheus2740** [comment]
Just FYI, this bug is still present in build 98.

**Comment by huyphams** [comment]
I figured out that this bug has occurred when you have a table with rtree index (which was disabled default by SQLite3). So the only solution is rebuild the SQLite driver with rtree enable. I will update it in future update. Thank you 👍

**Comment by matheus2740** [comment]
Thanks man, I appreciate it :)
Nice work on TablePlus btw, I'm using it as my daily driver for a couple of weeks so far, it's been great.

**Comment by matheus2740** [comment]
Oh, I forgot to mention it, I'm using spatialite extensions for this project, and the problematic table have a POINT column.
![screen shot 2018-04-06 at 17 10 48](https://user-images.githubusercontent.com/1382666/38442103-8559aebe-39bd-11e8-87d9-a0266d055a00.png)

**Comment by huyphams** [comment]
Hey @matheus2740 I enabled rtree index in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

I also added an ability to edit data directly in custom query screen.
<img width="1114" alt="screen shot 2018-04-17 at 2 29 35 pm" src="https://user-images.githubusercontent.com/3654622/38854780-cc05d00e-424b-11e8-9136-e22883013987.png">

**Comment by matheus2740** [comment]
Thank you @huyphams ! I tested it and it worked flawlessly, thanks for that!
