### ISSUE TITLE
Keyboard shortcuts not working as intended on Dvorak

### ISSUE THREAD

**Issue by joen-mauritzon** [TablePlus/TablePlus#369]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 (97)

3. The steps to reproduce this issue:
Dvorak Keyboard shortcuts seems to override eachother.
For example to open the shortcut for "Open SQL Query" is listed (in the preferences pane) as "⌘ + ." but that seems to be the same shortcut as "Cancel running queries" uses. When pressing it the "Edit" menu item flashes, making me believe that its actually issuing the "Cancel running queries" command. 
This makes it impossible to Open SQL Query from the keyboard for me.
Also the highlight for the button "Open SQL Query" states that the shortcut is "⌘ + e", which doesn't work either.

To me it would just make more sense to keep the normal shortcuts when using an alternative layout, so it would still be "⌘ + e" (instead of "⌘ + .", where "." is in the same place as "e" is on a Qwerty layout) to Open SQL Query instead of trying to remap each one for other layouts.

**Comment by huyphams** [comment]
Hi @joen-mauritzon the tab shortcut in preferences is WIP that why you can't change the shortcut. We will update it in some next update.
Currently, you can open SQL Query by keyboard by `command + E` or `command + return`.
Cancel a running query by press: `Command + .`

**Comment by joen-mauritzon** [comment]
⌘ + E isn't working for me (might be some other app that has hijacked it). But ⌘ + return works, that nice to see :)

**Comment by joen-mauritzon** [comment]
One related problem is that alot of shortcuts in the preference pane seems to be wrong, for example: 
<img width="381" alt="screen shot 2018-03-29 at 14 15 16" src="https://user-images.githubusercontent.com/400342/38088335-be7a5134-335b-11e8-8466-2cfef2d84440.png">

Those two doesn't work, but the "normal" shortcuts for those work (⌘ + t for open new tab and ⌘ + , for opening preferences)

**Comment by huyphams** [comment]
Hey @joen-mauritzon yup, because it is currently WIP. we will update it soon, no worries.

**Comment by alexreid** [comment]
I've just run into this – Ctrl-P/N to select completions from the list in the query editor do not work when using a Dvorak keyboard (or presumably any layout where these keys are not in the same place) – they still expect you to press the Qwerty P and N keys rather than the Dvorak location. I've also noticed that Cmd-I for 'Beautify' suffers from the same problem. I assume this is because the implementation is checking key codes directly rather than taking the user's keyboard layout into account.

**Comment by huyphams** [comment]
I've added the keyboard preferences, please create a separated issue to request new keybinding.
Thanks all.
