### ISSUE TITLE
Not a bug or feature: could it run on MacOS 10.9?

### ISSUE THREAD

**Issue by cbertelli** [TablePlus/TablePlus#37]
The title says almost all. I see it doesn't, I beg it could.

**Comment by huyphams** [comment]
We developed TablePlus with modern API, currently we only support OS X from 10.11. When TablePlus official release and stable, we will make it available for older platform.

**Comment by huyphams** [comment]
OSX has changed a lot of on 10.11, so back compatible is nearly impossible. So I'm closing this issue because TablePlus can't support it.
