### ISSUE TITLE
Editor gets stuck after error

### ISSUE THREAD

**Issue by hrdblzs** [TablePlus/TablePlus#370]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.2
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
96
3. The steps to reproduce this issue:
The SQL Editor is stucked after an error message. After the pop up message appears the code is not editable anymore. The waiting counter runs in lower left corner which stops with cancel (Cmd+.) but you still cannot edit anything in that Tab anymore (new and other open Tabs work well).

**Comment by huyphams** [comment]
Hi @hrdblzs it's fixed in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Can you give it a try and let me know if it fixes?

**Comment by hrdblzs** [comment]
Thanks for the qick answer @huyphams . It's fixed.
