### ISSUE TITLE
App Crashes on Editor

### ISSUE THREAD

**Issue by dyeje** [TablePlus/TablePlus#371]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Not sure what this means.  I'm running Postgres 10.
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
96
3. The steps to reproduce this issue:
Open the app.
Open a connection.
Click on the code editor.
App crashes.

http://g.recordit.co/MyngUlhWox.gif

**Comment by huyphams** [comment]
Hi @dyeje are you on OSX 10.11? it has been fixed in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
