### ISSUE TITLE
Mysql column comment 

### ISSUE THREAD

**Issue by jason13** [TablePlus/TablePlus#372]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
96
3. The steps to reproduce this issue:
No column comment show / edit

**Comment by Tungtono** [comment]
Hey @jason13, The table structure will be remade in the next build, which means this feature will be released as apart of the next update. Stay tuned 🤗

**Comment by huyphams** [comment]
Please check out this issue: https://github.com/TablePlus/TablePlus/issues/237
