### ISSUE TITLE
sqlite extra id column displayed in data view

### ISSUE THREAD

**Issue by richcorbs** [TablePlus/TablePlus#373]
I see this in builds 97 and 98. I didn't notice in any other build.

The first time I click into a table there are two "id" columns. Clicking another table and coming back to the first table removes the extra "id" column.

Refreshing the data view (Command-R) brings back the extra "id" column.

I've attached two screenshots showing both scenarios.

![screen shot 2018-04-02 at 9 42 50 am](https://user-images.githubusercontent.com/437167/38202837-62d9292a-365a-11e8-8491-53a0fb06deab.png)
![screen shot 2018-04-02 at 9 43 03 am](https://user-images.githubusercontent.com/437167/38202838-62f72380-365a-11e8-9671-e7369e2f2830.png)

**Comment by huyphams** [comment]
Hey thanks, let me check.

**Comment by huyphams** [comment]
It's fixed @richcorbs you can try this build until the official release.
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by richcorbs** [comment]
New build works great.
