### ISSUE TITLE
Amount of rows is not updated

### ISSUE THREAD

**Issue by mdrobny** [TablePlus/TablePlus#375]
1. Which driver are you using and version of it
PostgreSQL 9.6.6

2. Which TablePlus build number are you using
build 98

3. The steps to reproduce this issue:
In the bottom of  "data" view of some table it says how many rows the table has. I wrote down this amount of rows ~5 days ago and today I open this table again and the amount of rows displayed is still the same which is unexpected. I ran `select count(*) from "tableName";` and it returns higher number of rows. Restarting TablePlus doesn't help - the number is still the same.

**Comment by huyphams** [comment]
Hi @mdrobny there is an option in preferences can help. If you turn offestimate  (or better increase the number of rows) TablePlus will count exactly the number of rows:

- Pros: Count exactly.
- Cons: Slow when TablePlus has a million rows (or depend on memory limit).

We suggest you turn on this feature or increase the limit number for better performance.

**Comment by mdrobny** [comment]
@huyphams thanks for response. I understand this behaviour now
