### ISSUE TITLE
Select the database list by default?

### ISSUE THREAD

**Issue by marcusmoore** [TablePlus/TablePlus#376]
The smallest nitpick in the world but it would make me so happy to see it added: When I open TablePlus I would love if the first group was highlighted by default so I could hit the down arrow a couple times to highlight the database I want to open, then hit enter and not have to use the mouse or hit tab multiple times to get to the database list.

I know it's a small nitpick but I think it would be a nice improvement!

Thanks!

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 98

3. The steps to reproduce this issue:
Open TablePlus...

**Comment by huyphams** [comment]
Nice idea, but have you tried: cmd + P, we have `Open Anything` and it can open database/table very quickly.

**Comment by marcusmoore** [comment]
That would work too but `Open Anything` doesn't work on this screen does it?
![screenshot 2018-04-03 10 10 16](https://user-images.githubusercontent.com/1141514/38264255-4ab5deb0-3727-11e8-970e-ed4c8a6a406a.png)

By default the Twitter icon is selected but it would be nice if the `Local` group was. Does that make sense?

**Comment by huyphams** [comment]
Ha, I got it, I will update it . sorry, I am not getting you at the first time 😄

**Comment by marcusmoore** [comment]
No worries! You're awesome! Thank you.

**Comment by huyphams** [comment]
I fixed this bug in build 99 👍

**Comment by marcusmoore** [comment]
Awesome! Thanks again!
