### ISSUE TITLE
Cancel queries is very slow

### ISSUE THREAD

**Issue by Sennahoi** [TablePlus/TablePlus#377]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Azure MSSQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
98
3. The steps to reproduce this issue:
- Connect to azure mssql instance, run a long running query like "select * from some_long_table" and hit Cancel. On my system, it takes about 30 seconds to cancel the operation and in the meantime, I can't execute other queries.

**Comment by huyphams** [comment]
Hi @Sennahoi, SQL Server driver didn't support cancel query directly. Depend on the drivers, they have implemented its own method:
Currently, TablePlus works great with PostgreSQL and MySQL in canceling the running query.

The other solution for SQL Server is disconnected and reconnect after that but it's seems not a good idea IMO.

**Comment by huyphams** [comment]
Hey @Sennahoi can you test this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
I improved the canceling time in this build.

**Comment by Sennahoi** [comment]
You are amazing! Works like a charm. Thanks a lot.
