### ISSUE TITLE
Create SQL statements from sql query result view

### ISSUE THREAD

**Issue by Sennahoi** [TablePlus/TablePlus#379]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Azure MSSQL 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
99
3. The steps to reproduce this issue:
Query some table from within an sql query view, select a row in the result and make a right click. Would be great to have a "copy as sql insert" when you query single table (I love this feature in sqlpro).

**Comment by huyphams** [comment]
Yeah sure, it will be added to TablePlus build 100 👍 thanks for reporting.

**Comment by Sennahoi** [comment]
Great, one of few little things that currently keep me from buying a license for work.

**Comment by huyphams** [comment]
Hey! I just release build 100, but unfortunately. TablePlus only support copy as insert statement for MySQL and PostgreSQL in this build.

You can work around by using the table filter, we have a `copy as insert statement` here.

We will and support for `SQL Server` in the next build `101` next week.

**Comment by Sennahoi** [comment]
"TablePlus can't detect the table of this query result. This probably because of the limitation of current version. We will improve it in the future." doesn't really solve this but I hope to see an improved version of this function in a future version.

**Comment by huyphams** [comment]
@Sennahoi  can you give me your example? If the result from multiple tables, TablePlus can't copy it as insert statement.

**Comment by huyphams** [comment]
Hey @Sennahoi look like you are on the old version, please update to build 101.

**Comment by Sennahoi** [comment]
Just "select * from some_table". Using MSSQL in Azure.

**Comment by Sennahoi** [comment]
You were right, it seems that I didn't restart TablePlus after the update. Not I get a different message for "select * from some_table": TablePlus couldn't detect the table of this result. This probably because of the limitation of current version or the result is from multiple tables.

**Comment by huyphams** [comment]
I have tested with the similar syntax: select * from [Group];

and it works. Can you show me the full select query (please change the syntax and blur sensitive information)?
INSERT INTO [dbo].[Group] ([id], [nice], [join], [from], [from nice]) VALUES ('1', 'ss', 'dasdasd', 'asdaddsdasdasd', 'd');

**Comment by Sennahoi** [comment]
I just tried this on a local MSSQL server with the same error message:

`CREATE TABLE t1 ( c1 int );
insert into t1 (c1) values (1);
select * from t1;`

and I double-checked the version. It is 1.0 (101).

**Comment by huyphams** [comment]
Hey @Sennahoi sorry my bad, I have a bug on that build. Here is the fix version: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by Sennahoi** [comment]
Awesome, that works! Thank you very much.

**Comment by thirstyfish** [comment]
Not sure if you're aware of this particular flavour of this issue @huyphams so I thought I mention it:

TablePlus throws this same error ("TablePlus couldn't detect the table of this result.") when trying to Copy Rows As > SQL Insert Statement from a Postgres 10.6 **partitioned table**.

When copying the row from the individual partition directly it works as expected.

The partitioned table was created with the new declarative partitioning introduced in PG 10.

Thanks
