### ISSUE TITLE
Missing acknowledgements for MySQL

### ISSUE THREAD

**Issue by zydeco** [TablePlus/TablePlus#380]
The acknowledgements for MySQL are missing, instead it shows [acknowledgements for Sparkle](https://github.com/sparkle-project/Sparkle/blob/master/LICENSE).

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
n/a
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 99
3. The steps to reproduce this issue:
 * Open about screen
 * Click Acknowledgements
 * Scroll down and compare MySQL to Sparkle

**Comment by huyphams** [comment]
Hey thanks, this my mistake. Let's me update it.
