### ISSUE TITLE
Unable to change order of columns

### ISSUE THREAD

**Issue by ashfame** [TablePlus/TablePlus#381]
1. Which driver are you using and version of it: MySQL 5.7.21

2. Which TablePlus build number are you using: Build 99

3. The steps to reproduce this issue: Try to drag one column selects multiple columns in the direction of the drag. Possible to implement this?

**Comment by huyphams** [comment]
Hey @ashfame you can change the column order link by edit the first column in table structure (#)

**Comment by ashfame** [comment]
Cool, thanks!

**Comment by aar0nr** [comment]
@huyphams is it possible to create an internal representation of the column order *for display purposes only* for databases that don't support altering column position i.e. PostgreSQL? That would be sweet! 👍

**Comment by texelate** [comment]
Could this be implemented by drag-and-drop? It's time-consuming to do more complex sorts.

**Comment by martingalovic** [comment]
drag&drop would be great

**Comment by damiantoczek** [comment]
Marked as done? Almost 2020 and I can't see that it's done...
