### ISSUE TITLE
MSSQL Server messages not shown

### ISSUE THREAD

**Issue by 0x3333** [TablePlus/TablePlus#383]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL Server 2016

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (99)

3. The steps to reproduce this issue:
Run a query

When I run a query, SQL Server may return several messages. Those messages aren't been displayed. They are fundamental to debug the issue.

In Microsoft SQL Server Management Studio the output is:

```
Msg 3098, Level 16, State 2, Line 1
The backup cannot be performed because 'COMPRESSION' was requested after the media was formatted with an incompatible structure. To append to this media set, either omit 'COMPRESSION' or specify 'NO_COMPRESSION'. Alternatively, you can create a new media set by using WITH FORMAT in your BACKUP statement. If you use WITH FORMAT on an existing media set, all its backup sets will be overwritten.
Msg 3013, Level 16, State 1, Line 1
BACKUP DATABASE is terminating abnormally.
```

In TablePlus is:

```
BACKUP DATABASE is terminating abnormally.
```

**Comment by huyphams** [comment]
Hey thanks, we will improve it in next update 101.

**Comment by huyphams** [comment]
It release in build 104 can you check it @0x3333, thanks
