### ISSUE TITLE
Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled

### ISSUE THREAD

**Issue by kimus** [TablePlus/TablePlus#384]
Can't connect over SSL to MySQL.

*Connection Error*
Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled

**Comment by kimus** [comment]
workaround:
```
> export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1
> open -a TablePlus
```

**Comment by huyphams** [comment]
Hey @kimus thanks for letting me know, I will take a look at this bug.

**Comment by huyphams** [comment]
After reading the documents and some related topics.
- This is a runtime option of SQL lib.
 - We can enable it by an environment variable (just like you did).
The main problem is this option allows MySQL Send plain password => it's not safe at all.

So TablePlus will not enable it by default, probably we should have a dialog asking user allow it when connecting to server.

**Comment by rohitsrivatsav** [comment]
Do we have a timeline for this enhancement to be included as a feature ?

**Comment by huyphams** [comment]
Hi guys, please try out this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 with `MariaDB` driver, I've rebuilt it with clear password plugin. let me know if you're still seeing it then I will reopen this issue.

**Comment by t5n** [comment]
Any chance we can include LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN as a option in the preferences menu?

**Comment by huyphams** [comment]
Have you tried the MariaDB @t5n it's compatible with MySQL as well.

**Comment by michaeljstack** [comment]
I do not see how this is closed. I am getting the same issue with a newer build and its 4/18/2020. Has their been any fix to this issue?

**Comment by huyphams** [comment]
It was disabled default by Oracle (the maintainer of MySQL) because it's insecure, you can enable it by, let me see if I can add it as an option.
```
export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1
open -a TablePlus
```

**Comment by huyphams** [comment]
I just added it in the up coming release @t5n thanks.
<img width="579" alt="Screen Shot 2020-07-28 at 1 06 11 PM" src="https://user-images.githubusercontent.com/3654622/88625537-21162e00-d0d3-11ea-9872-306f1cdda2e5.png">

**Comment by atwoodjw** [comment]
The "Enable CLEARTEXT_PLUGIN" option doesn't seem to be working for MySQL. I can select the option, but it doesn't seem to do anything.

<img width="705" alt="Screen Shot 2021-02-19 at 9 33 48 AM" src="https://user-images.githubusercontent.com/362805/108517788-d722ae80-7295-11eb-97f3-abf0daa505c4.png">

<img width="1478" alt="Screen Shot 2021-02-19 at 9 34 52 AM" src="https://user-images.githubusercontent.com/362805/108517803-ddb12600-7295-11eb-9929-d24089630fd2.png">

It works if I open TablePlus like this.

```
export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1
open -a TablePlus
```

But missing this step frequently trips up our end users.

For reference, we're doing this to use access RDS w/ IAM DB Auth.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html

**Comment by huyphams** [comment]
Hi @atwoodjw could you please give this build a try and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks

**Comment by atwoodjw** [comment]
Thanks! Same error though.

**Comment by atwoodjw** [comment]
For anyone else running into this issue... until there's a fix, set the `LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN ` environment variable via launchd.plist.

http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-launchd-plist/

**Comment by juliangovender** [comment]
> Thanks @atwoodjw , what also worked for me is to export it directly to an environment variable (for testing/short term purposes):
`export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1`

**Comment by paulrosania** [comment]
Any chance of a fix? We are running into this too, I think this issue might need to be reopened.

**Comment by chrickso** [comment]
the 'enable CLEARTEXT_PLUGIN' option is definitely not working on version 4.7.1 (428) of TablePlus on macOS 12.4. whether its enabled or not I get this error when testing a connection to mySQL:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/808828/176548042-d7ef0b7c-c9ba-4df4-b374-20cf19b5f9e8.png">

but setting the environment variable and launching TablePlus thru the terminal via
```
export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1
open -a TablePlus
```
works just fine

**Comment by huyphams** [comment]
Hi guys, if you have a chance, please try this patch https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

Please make sure that you have enabled CLEARTEXT_PLUGIN

**Comment by chrickso** [comment]
> Hi guys, if you have a chance, please try this patch https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
> 
> Please make sure that you have enabled CLEARTEXT_PLUGIN

whatever you did to get this working on the primary connection, can you also apply to the backup/restore functions...hopefully asap?

![image](https://user-images.githubusercontent.com/808828/179293285-9abc8086-23b5-45fc-b640-5c39f298cb06.png)

**Comment by chrickso** [comment]
@huyphams any chance of getting the backup/restore patch anytime soon?

**Comment by huyphams** [comment]
If you have a chance @chrickso please give this build a try https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
Please let me know if you have any questions.

**Comment by rogiervanstraten** [comment]
@huyphams this seems to be an issue again. I'm not able to run the command line password generation while checking the "enable cleartext". However when starting TablePlus with export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1 works.

**Comment by raelgc** [comment]
Am I missing something or this option to "Enable CLEARTEXT_PLUGIN" is missing on the Ubuntu client?

**Comment by rogiervanstraten** [comment]
I would love to test a patched version 🙏🏽
