### ISSUE TITLE
Execute query shortcuts reversed in build 100

### ISSUE THREAD

**Issue by kez** [TablePlus/TablePlus#385]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Postgres 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

100!

3. The steps to reproduce this issue:

Write 2 queries in a query editor (I've tried a `select` then `update` and 2 `selects`); terminate each query with a semi colon.  Hit the `Execute All` shortcut (Command + Return) and only the selected query will run.  Now hit the `Execute Selected Query` shortcut (Shift + Command + Return) and *both* queries will be run.

**Comment by huyphams** [comment]
Hi @kez you can change back the default by click the drop down near execute button. We changed the default in build 100. Thanks.

**Comment by kez** [comment]
Thanks @huyphams - I checked the Shortcuts panel of Preferences which still refers to them as separate shortcuts, but not that little dropdown.  Heartily approve of the change (or the ability to set it); will read the release notes next time ;)
