### ISSUE TITLE
BLOBs in sqlite column values render as `EMPTY`

### ISSUE THREAD

**Issue by dbkaplun** [TablePlus/TablePlus#387]
* TablePlus Version 1.0 (99)
* sqlite 3.20.1

Thanks!

**Comment by huyphams** [comment]
Thanks @dbkaplun let's me check it.

**Comment by ruoshan** [comment]
mysql BLOB data has the same issue

**Comment by huyphams** [comment]
Hey @dbkaplun @ruoshan, it would be great if you can give a SQL file (Or SQLite file) for testing. I checked on my build but it works.
MySQL.
<img width="1163" alt="screen shot 2018-04-19 at 11 50 22 pm" src="https://user-images.githubusercontent.com/3654622/39006231-a92dc55e-442c-11e8-8814-474406ec2a34.png">

SQLite.
<img width="1163" alt="screen shot 2018-04-19 at 11 50 32 pm" src="https://user-images.githubusercontent.com/3654622/39006235-ab8682e6-442c-11e8-8b23-2359b0481bdc.png">

**Comment by dbkaplun** [comment]
@huyphams here you go: https://nofile.io/f/pR3C27UUWjv/preimage.sqlite

You can run the following SQLite query to see the data stored in the 4th byte of `preimage_hash`:
```sql
SELECT COALESCE(UNICODE(SUBSTR(preimage_hash, 4, 1)), 0)
FROM preimage;
```

**Comment by huyphams** [comment]
I found it, looks like it's an attachment (not a plain text). I will try to load it as binary.

**Comment by dbkaplun** [comment]
Has this been fixed?
<img width="1136" alt="screen shot 2018-05-02 at 12 08 34 pm" src="https://user-images.githubusercontent.com/1765130/39535324-96c86660-4e01-11e8-89cd-ea61e402bef0.png">

TablePlus 1.0 (103)

**Comment by huyphams** [comment]
No, not yet. I'm still working on it.

**Comment by huyphams** [comment]
it was improved on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
