### ISSUE TITLE
Error using manual input in column_default

### ISSUE THREAD

**Issue by buremba** [TablePlus/TablePlus#388]
1. PostgreSQL 10.0

2. TablePlus version 1.0

When I try to create a JSONB column with the default `'{}'::jsonb` value, TablePlus fails to create the column. Here is the SQL output it tries to execute:
```
ALTER TABLE "public"."project" ADD COLUMN "tags" text[] NOT NULL DEFAULT '''{}''::text[]';
```

**Comment by huyphams** [comment]
Hey @buremba  you can work around by with input `{}`
<img width="591" alt="json" src="https://user-images.githubusercontent.com/3654622/38926727-da8d15c8-432d-11e8-84e9-b5000e91321d.png">

**Comment by huyphams** [comment]
I updated the column default in new release 105. this bug is fixed, thanks for the contribute 👍
