### ISSUE TITLE
cockroachdb: Database I'm connected to not appearing in list, nor any tables

### ISSUE THREAD

**Issue by mholt** [TablePlus/TablePlus#389]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

CockroachDB CCL v2.0.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 100

3. The steps to reproduce this issue:

I simply make a connection to my local (insecure) CockroachDB instance, and I can't see any tables on the left side, and the database doesn't appear in the list in the bottom-left (it does at first, but then somehow it disappeared, I don't remember what I did to cause that).

In this screenshot, I am connected to my database:

<img width="560" alt="screen shot 2018-04-15 at 8 32 05 pm" src="https://user-images.githubusercontent.com/1128849/38787603-33ed167a-40ec-11e8-873a-c98239a545ca.png">

Notice that a query succeeds and shows me the one row in the `accounts` table. But all the items in the left pane are not mine! I think they belong to one of Cockroach's internal/system databases. Also, my database is not visible in the dropdown list in the left.

It is very weird and inconsistent behavior. Anyone else experienced this, or do you have any idea what is going on?

**Comment by huyphams** [comment]
Hi @mholt please choose public schema and all table will be there.

**Comment by mholt** [comment]
Oh! There they are. Thanks. (Sorry, I wouldn't have expected that. I'm not very experienced with relational databases.) Why is my schema, which is not called "public", listed as "public"? 🤔

**Comment by huyphams** [comment]
Hmm, I don't know how cockroach stored data but in PostgreSQL, every table belongs to a schema, and the default schema named public. You can create a new schema as well.

You can found more information here: https://www.cockroachlabs.com/docs/v2.0/sql-name-resolution.html#logical-schemas-and-namespaces

**Comment by mholt** [comment]
I should read that page 😅  -- thank you!

I'm going to buy this as soon as I have the funds (hopefully I can sell this thing I'm building). Thanks for your fast response!
