### ISSUE TITLE
Ability to view SQL Query history

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#39]
It would be very useful to have a powerful way to view previous SQL queries executed via TablePlus.  There used to be a history button near the DB Lock button, but it has disappeared.  However, I thought that this old history feature was flawed, because if a very large query is run it makes it hard to find other, smaller queries I have ran in the past.  Also you could not search for old queries and no temporal data was provided.

I think a good starting point would be to simply export every query executed to a text file, which the user can specify it's location.  Then I can open the text file and view all queries.

The most important thing for me is the ability to have _all queries_ log to a file that I can view in a text editor.  Maybe create a new file for each new day, to prevent file size from growing too large.

This will allow me to search my old queries efficiently.  What is also nice about exporting to a text file is that you don't have to deal with how to display this text effectively in the native app.  Maybe you can even have timestamps like shown below, to further add to the information provided (now I can know exactly what queries I ran and when).

![screen shot 2017-08-16 at 2 58 04 pm](https://user-images.githubusercontent.com/7946786/29387129-7f149898-8293-11e7-8ebb-2aa2bb542f1a.png)

I understand I can use the Snippet functionality but I often forget to press Add ('+') button,
-Brian

**Comment by huyphams** [comment]
Hi @brian-crane there are query history in View > Show logger.

But export query history to file is nice and sure, I will consider to add it in preferences.

**Comment by brian-crane** [comment]
Ah I didn't know about View -> Show Logger - this should be enough for now.

Thanks @huyphams

**Comment by brian-crane** [comment]
In the future, can we add a Shortcut to launch the Logger?  Something like ⌘+L could work

**Comment by huyphams** [comment]
Sure, i will create an other issue for shortcut key.
