### ISSUE TITLE
SET NULL on delete foreign key not available even when column is nullable

### ISSUE THREAD

**Issue by spaceisstrange** [TablePlus/TablePlus#391]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
100

3. The steps to reproduce this issue:

   - Create table
   - Create column and set is_nullable to **YES**
   - Create foreign key on column and try to set the _ON DELETE_ option, _SET NULL_ is not available
   - Close tab and reopen again, try to add a foreign key and this time the _SET NULL_ option is indeed available

Here's a screenshot when first creating the table:
<img width="549" alt="captura de pantalla 2018-04-19 a las 18 09 19" src="https://user-images.githubusercontent.com/6024783/39004383-7bb0eb62-43fd-11e8-830e-ca484bfa2bb4.png">

And right after closing an reopening:
<img width="502" alt="captura de pantalla 2018-04-19 a las 18 18 14" src="https://user-images.githubusercontent.com/6024783/39004631-234c63ba-43fe-11e8-9bf4-d90902e22d39.png">

**Comment by huyphams** [comment]
Hey, @spaceisstrange thanks for the reporting. I have fixed it in this bug build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Let me know if it works for you 👍

**Comment by spaceisstrange** [comment]
Working perfectly, @huyphams! Thank you so much for such a quick response!
