### ISSUE TITLE
Support MySQL 8.0

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#392]
TablePlus must be compatible with MySQL 8.0

**Comment by huyphams** [comment]
It's supported in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by linkdesu** [comment]
THX ! What a impressive response speed. I can continue my trial now !

**Comment by huyphams** [comment]
1.  index is not working when creating table. => Currently, TablePlus doesn't allow to create index during creating a new table, you can only create the index after creating a table.
2. Table structure should support for sorting columns like 1, 2, ... , 10, 11 but not 1, 10, 11, 2, .... => It's bug, looks like it treats # as string.
3.  table structure resort columns after save changes. => it's reloaded, but you're right, it should keep the sorting.
4. I can't reproduce the bug.

**Comment by huyphams** [comment]
All the issues were fixed in build 106.
