### ISSUE TITLE
Does not seem to follow Foreign Key constraints for SQLite

### ISSUE THREAD

**Issue by ngocphamm** [TablePlus/TablePlus#393]
1. Which driver are you using and version of it
SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
101

3. The steps to reproduce this issue:

- Open the attached sqlite database file. It has 2 tables `acconnt`, and `post`. Table `post` has a FK to table `account`.
- Try to insert a record to `post` table, with a non-existing `account_id`. For example
```
insert into post(account_id, post_title, post_body) 
values (2, 'Test post 1', 'Content')
```

Expected result: The record is not inserted due to failing FK
Real result: The record is inserted by TablePlus

TablePlus seems to recognize that there's a foreign key, according to table definition it shows.
<img width="526" alt="2018-04-20 at 9 03 pm" src="https://user-images.githubusercontent.com/395123/39078902-014b0104-44df-11e8-9c15-ead2750dd0a2.png">

[test.sqlite3.zip](https://github.com/TablePlus/TablePlus/files/1934027/test.sqlite3.zip)

**Comment by huyphams** [comment]
Hey thanks for the reporting, it's fixed: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by ngocphamm** [comment]
That was fast! However I just updated to build 102, and it display the foreign keys properly (really properly!), but still allows an invalid to be inserted. Can you please check it again @huyphams?

**Comment by huyphams** [comment]
"Allows an invalid to be inserted" I think this is not related (or it's not what TablePlus supposed to do). It's related to the database. (SQLite is quite open, it allows to insert anything into its database).
Tell me if I'm wrong 😄

**Comment by ngocphamm** [comment]
Sorry. "Allows an invalid record to be inserted". I meant it's a foreign-key related kind of invalid (look at the query I provided in the first post). It should not be allowed from the SQLite engine itself, thus must be reported by TablePlus.

**Comment by ngocphamm** [comment]
According to the section "2. Enabling Foreign Key Support" from the link below, I think you probably have to enable foreign key support for each database connection you make from TablePlus. It can be an option in connection settings, I guess.

http://www.sqlite.org/foreignkeys.html

**Comment by huyphams** [comment]
You can do it with this option: 

<img width="612" alt="resource" src="https://user-images.githubusercontent.com/3654622/39091235-2886b6a0-461a-11e8-9feb-c1b0c62a6b06.png">

```
Resource file
The sqlite3 tool has a resource file called .sqliterc. It is located in the home directory. If there is no such file, we can simply create it. The resouce file can contain meta commands, or regular SQL statements. However, we should avoid using SQL in the file.

$ cat .sqliterc 
.mode column
.headers on
.nullvalue NULL  
Here is a simple example of a resource file. It has three meta commands. With a resource file, we do not have to execute meta commands all over again when we start the sqlite3 tool. They will be executed automatically at the start of the tool.

$ sqlite3 test.db 
-- Loading resources from /home/janbodnar/.sqliterc
SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.
We have a message saying that the tool loaded resources upon the beginning.
```
http://zetcode.com/db/sqlite/tool/

**Comment by ngocphamm** [comment]
I created the `.sqliterc` file with `PRAGMA foreign_keys = ON` and it seems to be applied using command line `sqlite3 test.db`, but TablePlus still doesn't regard the foreign key, and let me insert the record just fine.

**Comment by ngocphamm** [comment]
This is the behavior I'm seeing now.

Command line
```
»  sqlite3 test.sqlite3
-- Loading resources from /Users/ngoc/.sqliterc
SQLite version 3.19.3 2017-06-27 16:48:08
Enter ".help" for usage hints.
sqlite> insert into post (account_id, post_title, post_body) values (3, 'Test', 'test');
Error: FOREIGN KEY constraint failed
sqlite>
```

The connection settings in TablePlus
![2018-04-22 at 11 22 am](https://user-images.githubusercontent.com/395123/39096573-bc31136e-461f-11e8-84d0-a188da16a4e2.png)

Open the database with TablePlus and run `insert into post (account_id, post_title, post_body) values (4, 'Test', 'test');`

Result
<img width="466" alt="2018-04-22 at 11 25 am" src="https://user-images.githubusercontent.com/395123/39096587-f249439a-461f-11e8-898e-58ed9bf9c521.png">

**Comment by huyphams** [comment]
I believe that the default `~/.sqliterc` it isn't working. Please set it directly (by clicking the button).

**Comment by ngocphamm** [comment]
That's it! Thank you!

Do you want another issue for the default `~/.sqliterc` not working?

**Comment by huyphams** [comment]
I just updated the SQLite form:

<img width="612" alt="screen shot 2018-04-22 at 10 37 31 pm" src="https://user-images.githubusercontent.com/3654622/39096707-c13dc466-467d-11e8-8c16-06148a40b19a.png">

I think we must force the user to choose the config file (follow Apple guideline sandbox app).

**Comment by ngocphamm** [comment]
That's okay for me, even though for many, browsing for a "dot" file might be a bit difficult if they do not know of the `Cmd + Shift + .` for toggling hidden files display in that file browser window.

I will close this issue for now. Thank you so much for getting this fix!!!
