### ISSUE TITLE
Insert favorites via keyboard / placeholders in snippets

### ISSUE THREAD

**Issue by aheidelberg** [TablePlus/TablePlus#395]
The only two things I'm missing from Sequel Pro are the possibility to insert favorites / snippets via a keyboard trigger and placeholders in favorites. 
For the insert via keyboard for example, one could assign a keyword to a snippet which will then be available via auto-complete or tab trigger.

Are there any plans to implement this?

See the [Sequel Pro Documentation](https://sequelpro.com/docs/ref/core-features/query-favourites) for more information.

**Comment by huyphams** [comment]
Thanks for the suggestion, I will take a look into it.

**Comment by fairchild** [comment]
I'd find this very useful also.  This seems related to #430.  Only having placeholder in favorites would work great for the use case I run into.  In general, ways to make it easier to create and use favorites would be useful.

**Comment by huyphams** [comment]
I'm working on this feature, you guys can expect it in the next build 119 next week.

**Comment by huyphams** [comment]
it's supported now (will release soon):
![keywordbinding](https://user-images.githubusercontent.com/3654622/43891009-7c917d6a-9bf2-11e8-8fd5-ed319b45cc86.gif)
