### ISSUE TITLE
Please trim spaces and new lines (\n) while registering license

### ISSUE THREAD

**Issue by imWildCat** [TablePlus/TablePlus#396]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
102

3. The steps to reproduce this issue:
 3.1. Copy a license number from the email (with new line before the license string and spaces)
 3.2. Paste the license number into the text field of the registration window
 3.3. The license number in the text field looks right but it will show `invalid license`

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
We have trimmed it on the server side, it's invalid because you have pasted the keys multiple times (We didn't trim it on the client side so some users have this mistake).

**Comment by imWildCat** [comment]
I see. Thank you for you prompt reply!
