### ISSUE TITLE
Possible to not open tab on every single click?

### ISSUE THREAD

**Issue by mholt** [TablePlus/TablePlus#397]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Cockroach 1.0  (I think)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

1.0 Build 102

3. The steps to reproduce this issue:

I would just like to NOT open a new tab every time I click on a table along the left. Or when I down-arrow to browse through the tables, I usually just want to replace the current tab. If I double-click, then sure, open a new tab, but having so many tabs open is kind of distracting. Is there a way to do this?

**Comment by huyphams** [comment]
Hey @mholt  are you using mouse? if you click by middle mouse, it's always opened in new tab.

**Comment by mholt** [comment]
No, I have a trackpad. I'm just "normal" clicking. :P

Huh, it only happens sometimes. Now I can't get it to do it.

I'll close this and if it happens again I'll try to pinpoint it.

**Comment by mholt** [comment]
Aha, I think I figured it out -- at least a little bit.

When you open a connection and nothing is in the main content pane, you click an item on the left and it shows that table. Then if you double-click another table (or any other "item") on the left, it will open in a new tab. Then, _single-clicking or using the arrow keys up and down_ will open each one in a new tab.

Is that expected? I don't like that behavior, since I expect only the item I double-clicked to open in a new tab.

**Comment by mholt** [comment]
Hi @huyphams  -- thanks for the explainer! That's starting to make sense. But I think it misses the point that there's a bug where a single click in the table list will open the table in a new tab, even though no changes were made to the current table (i.e. it's pinning a table when it shouldn't be). You can reproduce this by double-clicking a table on the left, then double-clicking a different one, then _single-clicking_ a different one, and it will still open that in a new tab, even though it wasn't a double-click.

**Comment by huyphams** [comment]
Yup, I forgot to mention that `double-click` will also pin the table.

**Comment by mholt** [comment]
Okay -- I think that's fine.

However, after double-clicking to pin a table (maybe have to do it twice), _single-clicking_ another table will also pin it. Which opens a lot of tabs. :-/

**Comment by huyphams** [comment]
It's not open a new table if you click on the item (on the left-side bar). TablePlus will find the tab which can be replaced and replace the content in it.

**Comment by mholt** [comment]
Ah, okay. Yeah, I'm still on the free version (as soon as I launch this new product I hope to be able to afford the paid version) -- so maybe if the logic could be reordered in the free version, that'd be nice, but I can see how you'd want to remind the user to upgrade... either way I guess.

**Comment by tchartron** [comment]
Would it be possible (or is it already possible ?) to open a tab in "pinned" mode (i mean not italic) when using the open anything (Command + P) shortcut ?

**Comment by gmariani** [comment]
Just ran into this as well. I'm using the free version and it drives me CRAZY that every single click opens a new tab. Often I'm running through tables to find the one I want to work on. I am constantly closing tabs so it stops harassing me about needing to buy the pro version for more tabs. But i don't WANT more tabs, I'm only working on one table, I'm just trying to find what I'm looking for. It's a big distraction. It should really work like VS Code, clicking it opens a preview but if i go somewhere else it automatically closes it. Then if I make a change it will pin it.

**Comment by bdrelling** [comment]
+1, this is super frustrating to deal with.

**Comment by jlwalkerlg** [comment]
+1

**Comment by Dannymx** [comment]
Opening a new tab every time I click on a table is super annoying. This is not like Sublime or VSCode (as someone described above). Hopefully this behavior can be changed in the future.

**Comment by cotfas** [comment]
For me I use 1 click from trackpad and it is overriding my tabs.. (it does not open in a new tab) and it is frustrating.. I saw it works when I double click it opens in new tab, but it is not ux for me.

**Comment by cotfas** [comment]
> No, The TablePlus tab behaviors are more like sublime text or vs code.
> 
> 1. If you open a table and make a change, the table will be pinned.
> 2. When a table is pinned, it can't be replaced. That means if you click on another table, it will be opened in a new tab.
> 3. You can force to open it in a new tab by clicking the middle mouse or use the right-click menu context.
>    The best solution is we should improve the (x) icon in the tab, it's a small UX but use can make it more clear.
> 
> Btw, you can look at the tab title. If it's italic font => it can be replaced.

If is pinned, will be nice to have an icon or something to diferentiate maybe :S

**Comment by Dannymx** [comment]
I don't get the overriding behavior on Windows.

One left click: opens new tab
Two left clicks: opens new tab
Mouse middle click: opens new tab
Right click: context menu

**Comment by esbenboye** [comment]
@Dannymx 
> If is pinned, will be nice to have an icon or something to diferentiate maybe :S
I just found this thread and this might help (I'm on Mac v 3.12.8 (368), trial)... If you single click a table and it opens as not-pinned, the tab name is in _italic_. If the tab is pinned, then it is not in italic. 

But I do agree that it would be nice with a more clear indication (maybe a padlock?) and way to un-pin the tab (context-menu option, perhaps?)

**Comment by tural-esger** [comment]
The same problem. And it is irritating.

**Comment by hannahfmtc** [comment]
Pretty sure its designed to be super annoying so that people will buy the pro version. I'm about ready to dump TablePlus and go back to bugging Sequal Pro just to avoid this bug.
