### ISSUE TITLE
Add column through "Open Structure" tab broke table

### ISSUE THREAD

**Issue by l2ysho** [TablePlus/TablePlus#398]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    PostgreSQL 10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
     build 102
3. The steps to reproduce this issue:

     Adding new column type bool (tested several of type with same result) to  table in "Open Structure" tab broke a table. App generates this query 
```ALTER TABLE "public"."media" ADD COLUMN "test_column" bool```

After commit, progress bar stop in middle and it is unable to retrieve any data from any table (window with results is blank). After restart cant retrieve data from updated table, not even in terminal (psql).

**Comment by huyphams** [comment]
Hey @l2ysho thanks for the feedback, I will check and fix it now.

**Comment by l2ysho** [comment]
I will try it in few hour, also I’ll try reproduce bug on some testing DB outside my localhost. If I will find something I let you know.

**Comment by l2ysho** [comment]
Sorry for being late, I tryed build you send, not it works. Good job. When can you realease this build in stable version?

**Comment by huyphams** [comment]
I have updated the build to production, so you can keep it. It’s official release build.
