### ISSUE TITLE
Ability to hide 'Plugin' button

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#40]
This is a very small request, and is not a deal-breaker.  However, I find for most uses I do not use Plugins, but it is always taking 25% of my main menu bar.  If possible, can we have an option to hide buttons in the 'Preferences' window?  This is part of the goal of expanding number of options that can be set via 'Preferences' window.  Having lots of options to set in Preferences can allow greater versatility and usability.

![screen shot 2017-08-16 at 3 08 08 pm](https://user-images.githubusercontent.com/7946786/29387396-bb218458-8294-11e7-87f4-6adb1113dca3.png)

Thanks, Huy!

**Comment by huyphams** [comment]
It was hidden from build 84 :D
