### ISSUE TITLE
Feature Request: Export All History

### ISSUE THREAD

**Issue by JohnRomanski** [TablePlus/TablePlus#401]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Redshift

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 103
______

Feature request: A way to export all SQL history into one file. (After using the tool for a week to compose queries, I have about 100 I need to export to a file. It would be nice if there were a way to export them all at once. Alternatively, if these are kept in a .plist somewhere, maybe I can just open that.)

**Comment by huyphams** [comment]
It’s saved in a temporary folder. Yup, I support the way to export all of them (or navigate to the folder).

**Comment by JohnRomanski** [comment]
I have found the Temporary folder, thanks. it's `/Users/<user>/Library/Application\ Support/com.tinyapp.TablePlus/Cache/History/` and there is a folder for each connection. then there is a folder for each day, and then a file for each query. A quick `cat *.sql` does the trick I needed. Thanks, closing.
