### ISSUE TITLE
Fix redis filters

### ISSUE THREAD

**Issue by davidbonnet** [TablePlus/TablePlus#402]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redis 2.8.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 103

3. The steps to reproduce this issue:

- Open a redis connexion
- Set filters
- Filters do not filter at all

**Comment by huyphams** [comment]
It's released on the build 194. Thanks

**Comment by bocharsky-bw** [comment]
I still have this problem in 212 build, any suggestions?

**Comment by huyphams** [comment]
Could you explain it a little bit @bocharsky-bw a screenshot or gif would be great
