### ISSUE TITLE
fuzzy text on dark theme

### ISSUE THREAD

**Issue by silverbux** [TablePlus/TablePlus#403]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 103
3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

![image](https://user-images.githubusercontent.com/1888261/39559571-d6e511f8-4ec9-11e8-9be5-e4533df93bf2.png)

![image](https://user-images.githubusercontent.com/1888261/39559589-00244098-4eca-11e8-81cb-75fa906abb3a.png)

**Comment by huyphams** [comment]
Hey thanks for the reporting 😄

**Comment by huyphams** [comment]
it's fixed on build 106.
