### ISSUE TITLE
SQL Server length and precision

### ISSUE THREAD

**Issue by martenlindblad** [TablePlus/TablePlus#405]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server 2014
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
103

3. The steps to reproduce this issue:
Check structure of table

Want to see the max_length and precision of the columns, like in this query:
SELECT
    c.name
    ,t.name
    ,c.max_length
	,c.precision
    ,c.is_nullable
FROM
    sys.columns c
    INNER JOIN sys.objects o ON (o.object_id = c.object_id)
    INNER JOIN sys.schemas s ON (s.schema_id = o.schema_id)
    INNER JOIN sys.types t ON (t.user_type_id = c.user_type_id)
WHERE
    s.name = 'x' and o.name = 'xxx'
ORDER BY
   c.object_id

**Comment by huyphams** [comment]
Sure, I will add the option to turn it on the table structure.

**Comment by huyphams** [comment]
it's supported @martenlindblad thanks for the suggestion
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
