### ISSUE TITLE
Backup not working with SSH connection to MySQL

### ISSUE THREAD

**Issue by pieterclaerhout** [TablePlus/TablePlus#406]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 1.0 (103)

3. The steps to reproduce this issue:

    1. Create a MySQL connection which is using an SSH tunnel

    2. Click on the backup button in the main screen

    3. Select the connection you have just created

    4. Select a database you want to backup

    5. Start the backup

    6. You'll get the following error:

```
Create tunneling...
Dumping...
mysqldump: [Warning] Using a password on the command line interface can be insecure.

mysqldump: Got error: 2003: Can't connect to MySQL server on '127.0.0.1' (61) when trying to connect

Dump database done
```

**Comment by huyphams** [comment]
it's fixed in recent builds. Please let me know if you're still encountering this issue.
