### ISSUE TITLE
Running 'Find' always adds a new line to the search

### ISSUE THREAD

**Issue by lewishowles** [TablePlus/TablePlus#408]
When running Find on a table, any previous search displays, but a new line is then added to the search.

This line must then be deleted, since an error occurs if you leave it blank.

Ideally, a new line should only be added if no previous search was found, otherwise let me add new lines manually.

An example:

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/1140753/39627400-a78c76ec-4f9d-11e8-91e7-53dd64d4cbe1.png">

**Comment by huyphams** [comment]
Hey, @lewishowles thanks for the reporting, 
This is an expectation behavior. I will improve it in next update. it should only be added if there are no filter.

**Comment by huyphams** [comment]
It was changed in release 104 @lewishowles thanks for the suggestion.
