### ISSUE TITLE
Hyphens in index names are not handled properly

### ISSUE THREAD

**Issue by fabiospampinato** [TablePlus/TablePlus#409]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 103
3. The steps to reproduce this issue:
    1. Delete an index named `foo-bar`
    2. The query produced would be: 
         ```
          ALTER TABLE `mydb`.`mytable` DROP INDEX foo-bar;
         ```
    3. Which throws an error because of the hyphen in the index name.

**Comment by huyphams** [comment]
Hey, @fabiospampinato thanks for the reporting, I just fixed it in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
👍

**Comment by fabiospampinato** [comment]
Nice, thanks!
