### ISSUE TITLE
In SQL Query window, we need ability to Copy 

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#41]
Currently we have no way to quickly copy data from a SQL query to my clipboard.  When viewing a row in a normal table, we have this nice right-click option, shown below.

![screen shot 2017-08-16 at 3 20 10 pm](https://user-images.githubusercontent.com/7946786/29387821-c586c028-8296-11e7-9239-d51dc6bb7137.png)

However, when I get data from a SQL query I am only able to get the data by exporting it to an external .csv file, then open that file, then copy necessary lines to my clipboard.  This is too time consuming.

If we could have this menu available when looking at rows of a SQL query, would be very very helpful.

**Comment by huyphams** [comment]
I can add the menu here but we can only copy as JSON and CSV, copy as Insert Statement will not be available.

**Comment by brian-crane** [comment]
Sounds good, Huy.  This is the #1 feature needed for my personal use.  Exporting data to a text file, then copying it is eating up time.

Hope all is well,
-Brian

**Comment by huyphams** [comment]
Just released new update 😁

**Comment by brian-crane** [comment]
Just checked,  this feature looks good! 

Will there be a changelog for 59 release?

**Comment by huyphams** [comment]
Just updated the changelogs 😁
