### ISSUE TITLE
Set timezone when connect to database

### ISSUE THREAD

**Issue by wd** [TablePlus/TablePlus#411]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Postgresql 9

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
104

3. The steps to reproduce this issue:
Noted: If the bug is related to data, please attach an example SQL data.

Connect a database, run a sql, if the table have a column with `timestamptz` type, the time will display as timezone 'UTC' .

I have set timezone at `.psqlrc` file, it works connect through command line.

**Comment by huyphams** [comment]
Hey thanks @wd, we will take a look at it.

**Comment by 1jason1** [comment]
Can we have this added for mysql. hate having to run SET time_zone='US/Central'; to be able to view dates/times correctly for timestamp fields.

**Comment by huyphams** [comment]
<img width="1034" alt="Screen Shot 2020-05-01 at 8 35 30 PM" src="https://user-images.githubusercontent.com/3654622/80809248-7d100a00-8beb-11ea-9af7-b5f6fc4430b5.png">

it will be released in the next official update or you can use the beta build here: https://www.dropbox.com/s/ndn8m23p7fbvwcq/TablePlus.dmg?dl=0

**Comment by blaaat** [comment]
I have a single connection with multiple databases with different timezones. Is there a way to run SET timezone commands after switching databases?

**Comment by kevnk** [comment]
> <img alt="Screen Shot 2020-05-01 at 8 35 30 PM" width="1034" src="https://user-images.githubusercontent.com/3654622/80809248-7d100a00-8beb-11ea-9af7-b5f6fc4430b5.png">
> 
> it will be released in the next official update or you can use the beta build here: https://www.dropbox.com/s/ndn8m23p7fbvwcq/TablePlus.dmg?dl=0

For MySQL, I used: `SET GLOBAL time_zone = '+00:00';`

Here are a bunch of other examples/commands you can run: https://stackoverflow.com/a/19069310/622287
