### ISSUE TITLE
Search History

### ISSUE THREAD

**Issue by jayshepherd** [TablePlus/TablePlus#413]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
9.4.15

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
104

3. The steps to reproduce this issue:
Click the history tab and attempt to search

----

I would like to search my history for a recent sql statement I ran.

**Comment by huyphams** [comment]
Currently, TablePlus only support search favorites (by name) and items. Search history requires full-text search, which is hard to implement (but I want to implement it). We already added this feature on our roadmap.
Thank you.

**Comment by jayshepherd** [comment]
Any suggestions on how I could search the history manually?

**Comment by huyphams** [comment]
Hey @jayshepherd you can search it manually here: `~/Library/Application\ Support/com.tinyapp.TablePlus/Cache/History/`

**Comment by linjunpop** [comment]
It would be great to have a full-text search on the history.

**Comment by younanjo** [comment]
this will be an awesome! hope to see it soon

**Comment by pmxjason** [comment]
I don't see this feature on the roadmap. Do you have any idea where this stands on the roadmap? This is the only thing blocking me from recommending the software at my workplace at the moment.

**Comment by thecorz** [comment]
I would be great to see this feature implemented

**Comment by huyphams** [comment]
TablePlus store history into files, locally. I think I can implement a system call that can search the content of history.
Just added it into the backlog.

**Comment by georgexsh** [comment]
the current UI is misleading, you see a search box with history tab, but it doesn’t work...

**Comment by huyphams** [comment]
After two years, TablePlus finally supports this feature. It will be released in the next update (first in beta release).

**Comment by huyphams** [comment]
After two years, TablePlus finally supports this feature. It will be released in the next update (first in beta release).

**Comment by timscott** [comment]
If history is not searchable, the search box should not be enabled when History tab is chosen, otherwise it seems as a bug.

**Comment by huyphams** [comment]
It's supported in the beta build, thanks all.
