### ISSUE TITLE
Errors setting different delimiter

### ISSUE THREAD

**Issue by andretti1977** [TablePlus/TablePlus#414]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7.22
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 104
3. The steps to reproduce this issue:
When i set the simple SQL command:

DELIMITER $$

i get this error:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$' at line 1

![image](https://user-images.githubusercontent.com/856429/39745600-fe02107e-52a7-11e8-9ae2-476033cebf52.png)

**Comment by huyphams** [comment]
Hi, thanks for the feedback.
But what's your purpose in setting the delimiter? Are you trying to create a function? I just tried in Sequel Pro and it did nothing (Looks like it ignores the command.).

**Comment by andretti1977** [comment]
Yes i'm trying to create a store procedure. The same code in SequelPro doesn't produce any error and it's standard code (at least on mysql) so i don't understand why it doesn't work on TablePlus.
How can i create stored procedures if i can't change delimiter?
Thanks in advance

**Comment by huyphams** [comment]
Hi @andretti1977, I'm sorry because of the late response. Sequel Pro simply ignores the `DELIMITER`
You can create a function by two way:
1. Right click on the left panel > create function.
2. Use SQL Query without delimiter code for example:

In Sequel Pro:
```
DELIMITER $$

CREATE FUNCTION `nice_function` (id INT, nice INT)
    RETURNS char(50) CHARSET utf8 RETURN 'fafasfasssssf'    
    END$$
    
DELIMITER;
```

In TablePlus:

```
CREATE FUNCTION `nice_function` (id INT, nice INT)
    RETURNS char(50) CHARSET utf8 RETURN 'fafasfasssssf'    
    END;
```

**Comment by andretti1977** [comment]
Ok, i looked for delimiter in context help but didn't find any entry.  
For me it's ok but since it is a mysql standard command, i do expect it to work fine . What i mean is that i think that TablePlus should execute any command that is supported by the underlining db without any exception. That said your software is really really good. I do expect to find some little features and then it will be a mature product (at least a better alternative to the beautiful sequel pro).

**Comment by manospasj** [comment]
@huyphams I really think this should be implemented. Let's say I want to create a trigger with more than one statements. [MySQL documentation](https://dev.mysql.com/doc/refman/5.6/en/trigger-syntax.html) suggests to change the delimiter in order to do that.

My syntax is:
```
delimiter //
CREATE TRIGGER test_trigger AFTER UPDATE ON `test_table`
  FOR EACH ROW
  BEGIN
    IF (OLD.date != NEW.date) THEN
      BEGIN
        INSERT INTO `audit` (
          `new_date`,
          `previous_date`
        )
        VALUES (
          NEW.date,
          OLD.date
        );
      END;
    END IF;
  END;
//

delimiter ;
```
This works fine in MySQL Workbench but throws the following syntax error in TablePlus:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER //' at line 1

**Comment by huyphams** [comment]
@manospasj it's implemented a long time ago, please check it out and let me know if you're still seeing the issue.

**Comment by manospasj** [comment]
@huyphams it wasn't working at the time I posted the comment. I have already posted the error message I was getting. I don't know if this has been fixed now since I uninstalled TablePlus as this is a must feature for me

**Comment by aliadhillon** [comment]
@huyphams when this fix is coming for Windows version? I am on windows version 3.1.9 (114) and delimiter issue is still there and I have to switch to MySQL Workbench for procedures and functions.

**Comment by Chain-of-Trust** [comment]
It's not working for me either. 
there is no problem to store the function without a custom delimiter. 
It also runs into an error if i just use DELIMITER ; in the syntax 

working on the latest osx version 3.1.3 (296)

**Comment by borisbrue** [comment]
It's not working for me either. I only can store the function without a custom delimiter.
Im working on the latest osx version 3.1.2 (296)
