### ISSUE TITLE
SELECT * JOIN query result displays incorrect field for duplicate field names

### ISSUE THREAD

**Issue by tylerrasor** [TablePlus/TablePlus#415]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Microsoft SQL Server 2017

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 104

3. The steps to reproduce this issue:

`CREATE TABLE testType (testTypeID INT, typeDesc VARCHAR(10), createdby VARCHAR(10), PRIMARY KEY (testTypeID));`
`CREATE TABLE test (id INT, testTypeID INT, createdby VARCHAR(10), PRIMARY KEY (id), FOREIGN KEY (testTypeID) REFERENCES testType (testTypeID));`
`INSERT INTO testType VALUES(1, 'type1', 'testuser');`
`INSERT INTO test VALUES(1, 1, 'otheruser');`
`SELECT * FROM test JOIN testType ON test.testTypeID = testType.testTypeID;`

The createdBy field from the test table is overwritten in the query return by the createdBy field from the testType table.

**Comment by huyphams** [comment]
Thanks @tylerrasor, it's fixed in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
it will be officially released in the next Monday.
