### ISSUE TITLE
Add SequelPro like "Show/Copy create table syntax)

### ISSUE THREAD

**Issue by andretti1977** [TablePlus/TablePlus#416]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.7.22
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
104
3. The steps to reproduce this issue:
Using sequel pro, right click a table and see contextual menus appear

**Comment by huyphams** [comment]
Hi @andretti1977 you can press: command + L and then install tabledump plugin. it being developed but the copy creation is functional now.
