### ISSUE TITLE
Simplify adding relationships among tables

### ISSUE THREAD

**Issue by andretti1977** [TablePlus/TablePlus#417]
How can i add relationships? For me it's unclear.

**Comment by huyphams** [comment]
Hi, I think it's similar with Sequel Pro?

This is in Sequel Pro.
<img width="391" alt="screen shot 2018-05-10 at 10 09 41 am" src="https://user-images.githubusercontent.com/3654622/39850214-550e2e96-543a-11e8-8bb3-9f23faff559b.png">

In TablePlus.
<img width="383" alt="screen shot 2018-05-10 at 10 09 49 am" src="https://user-images.githubusercontent.com/3654622/39850215-570b2a3c-543a-11e8-8780-c7c6f482bde0.png">

It's the same except TablePlus uses the default name for the foreign key.

**Comment by andretti1977** [comment]
So sorry, i was working with a reduced size window and didn't see the foreign key field!
