### ISSUE TITLE
Provide SequelPro export capabilities

### ISSUE THREAD

**Issue by andretti1977** [TablePlus/TablePlus#418]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql 5.7.22
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
104
3. The steps to reproduce this issue:
In sequelpro i can export all db or just a selection of tables and even decide to export structure or data or both. I wasn't quickly able to understand how to do that in TablePlus
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Currently, TablePlus doesn't support export the whole database. We will let you know when it supported.
Btwm you can use the backup/restore function in the welcome screen to dump database. It uses the MySQL binary to do the job.

**Comment by Nemo64** [comment]
It is not only dumping entire databases that was extremely convenient.
Dumping just a few tables and not even bothering with naming was awesome.
![may-14-2018 12-30-34](https://user-images.githubusercontent.com/1749936/39992343-c0e51acc-5772-11e8-956f-d096091e9438.gif)

**Comment by rico** [comment]
I totally agree with @andretti1977 & @Nemo64 - this is the only functionality I'm missing in TablePlus and why I have to switch to SequelPro regularly.

**Comment by fgilio** [comment]
Would be great to have this in TablePlus

**Comment by huyphams** [comment]
Hey guys, I just made this feature on this build, it would be great if you guys can give it a try and let me know if anything needs to be improved before release: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by weyert** [comment]
Looks like it's working! Only you can not  set the name of the exported SQL file

**Comment by huyphams** [comment]
Thanks, I want to make it works first, then improve it later 😄

**Comment by andretti1977** [comment]
Sorry to say months ago i switched to the database plugin of my ide (IntelliJ Ultimate) but if you have implemented it i'm sure it is a really desired feature.

**Comment by horo42** [comment]
TablePlus⁩/⁨Contents⁩/Frameworks⁩/Oracle.framework⁩/Versions⁩/A⁩/⁨Resources⁩/libociei.dylib - 126,4MB
TablePlus⁩/⁨Contents⁩/Frameworks⁩/Oracle.framework⁩/Versions⁩/A⁩/⁨Resources⁩/libclntsh.dylib.12.1 - 86.7MB

What happened?

Plus this build is not signed digitally.

I tested it and SequelPro on the same 3 tables from a database. Apart from spacing and comments they generated the same output, except one thing. The TablePlus export included an extra `SET NAMES utf8mb4;`

Looking forward to see this feature landing in a future release. This is great news! Thanks so much.

**Comment by huyphams** [comment]
@horo42 that is beta build, which supports Oracle `libociei.dylib` and `libclntsh.dylib.12.1` came from the Instant Client, the driver provides by Oracle. Let me check the sign again and fix a few issues 😄 
Thank you so much for testing.

**Comment by texelate** [comment]
This is great. However, not having control over the file name means you can easily overwrite a file without realising.

**Comment by jaspertandy** [comment]
This functionality doesn't really replicate what SequelPro offers - that UI allows you to be so specific when it comes to exporting structure only down to specific tables that this approach alone could never replace it. It also seems to be incredibly slow. It's not really a problem since I can just use Sequel Pro for these exports, but given the situation that project appears to be in now, it'd be good to be able to support its replacement so that it has a bit more longevity.

**Comment by huyphams** [comment]
I understood that @jaspertandy and we already have a plan to make an advanced table tool, which at least has the same feature set of Sequel Pro and other competitors.
The current export tool is focusing on simplicity not feature rich. and it becomes a problem with advanced users.

**Comment by jaspertandy** [comment]
@huyphams 👍 the only reason I mention is because this issue is closed, so to me that seems like this is complete. Apologies, as that appears to not be the case.
