### ISSUE TITLE
why have not scroll bar

### ISSUE THREAD

**Issue by cevin** [TablePlus/TablePlus#419]
![image](https://user-images.githubusercontent.com/338110/39873067-828e7a94-549c-11e8-93fe-a31c64b793a9.png)

if have lots of functions ……  oh no.

**Comment by huyphams** [comment]
You make me laugh 😄
Yeah, I think not many users out there have many functions like yours (it looks more like you have enabled some plugin) so I didn't put a scrollbar here.
I will think about it.

**Comment by huyphams** [comment]
As you wish: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0 👍 enjoy.

**Comment by cevin** [comment]
🤣🤣🤣🤣🤣  i like you
