### ISSUE TITLE
'Master' Close and Open DB connection Button

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#42]
There are times when I want to completely sever connection to the DB I am accessing.  For example;

1. After running a very large query, or requesting to view all rows of a very large table, the entire app will hang, and refreshing the DB takes many minutes for a response.  Consequently I normally need to restart app to get this under control.  If I could hit a 'Close Connection' and 'Open Connection' button I would not need to restart.
2. When rebuilding my local databases, it is necessary that I close all applications accessing the databases being used.  But this causes me to lose my current open windows and queries.  If I could hit a 'Close Connection' button it would sever TablePlus' connection with postgres, which would allow me to build my DB.  Then I can hit a 'Open Connection' button to re-establish connection, this way I do not have to reopen the windows that I had closed in past.

![screen shot 2017-08-16 at 3 32 36 pm](https://user-images.githubusercontent.com/7946786/29388095-26b97c9a-8298-11e7-99d0-8570234d4f13.png)

Once again, this is just a suggestion.

**Comment by huyphams** [comment]
I think this can be solved by adding cancel query button, and it is already in my plan.
