### ISSUE TITLE
"target lists can have at most 1664 entries" SQL error

### ISSUE THREAD

**Issue by markedmondson** [TablePlus/TablePlus#422]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
104

3. The steps to reproduce this issue:
Opening the application against a large (sharded) database causes a "target lists can have at most 1664 entries" error on the server. 

Presumably it's trying to retrieve all the table names on load and there doesn't appear to be an effect on the functionality of the app but it does throw a rather large error into the logs (including the full SELECT statement).

**Comment by huyphams** [comment]
Hey thanks, @markedmondson I will optimize it in the near future update (planing in build 106). Currently, TablePlus tries to load some metadata, I think that is the problem.

**Comment by huyphams** [comment]
I believe this build should fix the issue: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
It will be released soon.

**Comment by markedmondson** [comment]
Wow, thanks for the quick response! I'll give that build a go.
