### ISSUE TITLE
Inputs port 22 in SSH automatically

### ISSUE THREAD

**Issue by anotherdevs** [TablePlus/TablePlus#423]
**Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
_MySQL_

**Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
_104_

**The steps to reproduce this issue:**
1. Open TablePlus
2. 'Create a new connection'
3. Select MySQL
4. Write in: 
- Name: Test
- Host: 127.0.0.1
- Port: Leave it blank
- User: test
- Password: test
- Database: Leave it blank
5. 'Over SSH'
6. Write in:
- Server: 127.0.0.1
- Port: Leave it blank
- User: test
- Password: test

When pressing save, it will save the connection with port 22 in SSH - even though it clearly states that: "TablePlus uses .ssh/config by default".

I use other ports in my config file.

**Comment by huyphams** [comment]
Hi @anotherdevs it's no problem because when you're using the config. TablePlus alway priority the properties in the config. That means if you set the port in the config, TablePlus uses it first.

**Comment by anotherdevs** [comment]
Hi @huyphams 

I have just tested it again, and what you're saying is not correct.

Do you mind testing it yourself?

**Comment by huyphams** [comment]
I have tested before reply your comment. I changed the port to a random number (which is not correct) and set up the port in the config 2223. it works. So I think the bug is not related to it.
Could you post your connection form here ( pleasechange the sensitive data to dummy data).

**Comment by huyphams** [comment]
I also check the code:
The code logic is:
1. I have set up the port environment
2. Load the config.

=> if the user uses config, it should override the port from step 1.

**Comment by huyphams** [comment]
You can see the gif below.
![2018-05-11 16 45 04](https://user-images.githubusercontent.com/3654622/39918464-b7018322-553a-11e8-821b-340f08e8256f.gif)

**Comment by huyphams** [comment]
Have you checked the box Use ssh keys @anotherdevs ?

**Comment by huyphams** [comment]
I closed this because of no response. Feel free to commit or reopen if you still have this bug.
