### ISSUE TITLE
Feature request: Option to customize toolbar

### ISSUE THREAD

**Issue by eivindml** [TablePlus/TablePlus#424]
Hi,

love TablePlus. One feature I'm missing is the option to right click the toolbar and customize the items appearing in the toolbar. This is default for most Mac apps, and I like to just remove all buttons I'm not using to get a cleaner interface.

Would love to see something like this:

<img width="286" alt="skjermbilde 2018-05-12 kl 16 04 03" src="https://user-images.githubusercontent.com/202450/39958093-429172f8-55fe-11e8-85ba-0c1c20b56dce.png">

**Comment by huyphams** [comment]
Hi, @eivindml thanks for the suggestion. I want it too ( Just like sublime text, no need the button). The reason I put the button here because I want people know the functions.

I will add an ability to remove icon in the next update 👍

**Comment by huyphams** [comment]
Mine after removing some icons.
<img width="1144" alt="screen shot 2018-05-14 at 10 31 47 am" src="https://user-images.githubusercontent.com/3654622/39977151-11627366-5762-11e8-80ec-8cba3cd4dee9.png">
You can try it at: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by eivindml** [comment]
Great work. :) Looks good.

But I think you forgot to add the `flexible_space` item to the toolbar panel.

It's very useful.

<img width="1108" alt="skjermbilde 2018-05-14 kl 22 12 23" src="https://user-images.githubusercontent.com/202450/40021015-fcc88a00-57c3-11e8-80ae-9a49e8562acd.png">

**Comment by huyphams** [comment]
It's released in build 106 including flexible space, thanks for reporting the issue.
