### ISSUE TITLE
Full text search in whole database

### ISSUE THREAD

**Issue by Nemo64** [TablePlus/TablePlus#425]
It would be awesome to just search an entire database or just a selection of tables for a word, a number etc..
This feature exists in phpmyadmin but could use some ux-improvement.

**Comment by huyphams** [comment]
Hey, are you looking for this? We have a filter with contains operation, which is likely full-text search.<img width="1209" alt="fulltext" src="https://user-images.githubusercontent.com/3654622/40005931-59b3152e-57c3-11e8-9b9d-a3ffc3f6da0b.png">

**Comment by Nemo64** [comment]
kind of. That is already a really nice feature. But I'm searching for this:
![may-15-2018 10-29-35](https://user-images.githubusercontent.com/1749936/40045562-f29c61ca-582a-11e8-85d0-f3dade358067.gif)

**Comment by tarasyyyk** [comment]
This whole-database search also implemented in MySQL Workbench. It's open source, so you can look at realization of this search.
It will be awesome having this feature in TablePlus!

**Comment by bambamboole** [comment]
Is there any progress on this feature?

**Comment by sebfie** [comment]
Also need this !

**Comment by basepack** [comment]
Well add my +1 too!

**Comment by ebelinski** [comment]
I think such a feature would be very convenient, though I understand that it is not something easy to implement. Currently, I am trying to search through a database for certain inappropriate words, and it would be much easier for me if I could search all columns at once for a specific word. 🙂

**Comment by jak-kal** [comment]
Any plans to develop this feature?

**Comment by JasonTheAdams** [comment]
Just spent 10 minutes hunting around for this exact feature. Bummed to see it exists in phpmyadmin but not a quality product like this.

**Comment by dyaskur** [comment]
Any update on this?

**Comment by richterd** [comment]
+1 <3

**Comment by dyaskur** [comment]
Hi @huyphams  and @Ivoah ,

**Comment by Fleisch** [comment]
+1 for this!

**Comment by conschneider** [comment]
+1 pleeeaasee  💌

**Comment by LiamMcArthur** [comment]
+1 on this feature! It works very nicely in HeidiSQL.

**Comment by dertuman** [comment]
Yes please! I was also looking for this feature and it's a pity it isn't there. I just bought the full license too... :(

**Comment by terrance-orletsky-d7** [comment]
+1 please and thanks!!! Premium subscriber here

**Comment by steveolotu** [comment]
@huyphams Please remove the label "waiting-user-feedback". There was feedback, the suggestion did not solve the problem and the feature request remains open and valid.

**Comment by andreasemer** [comment]
+1 This feature would be very helpfull!

**Comment by rodrigo-arias** [comment]
+1 for this!

**Comment by davidpesce** [comment]
This would be nice...

**Comment by krubenrc** [comment]
Is the only feature what i need for replace completely to mysql workbench.
And i will dont care pay premium version, if the feature will be there.

**Comment by jak-kal** [comment]
Look at all the +1s! @huyphams - is this on the roadmap?

**Comment by falko100** [comment]
+1

**Comment by juretopolak** [comment]
+1

**Comment by parthjani7** [comment]
+1

**Comment by jak-kal** [comment]
Please can you give us a yes or a no, @huyphams.

**Comment by gkssjovi** [comment]
this will be the best feature :)

**Comment by brandon-9** [comment]
Would be amazing @huyphams

**Comment by RSk099** [comment]
+1

**Comment by fatherofinvention** [comment]
Still no response on this in over 2 years?

**Comment by gkssjovi** [comment]
I have created this cli tool that allow you to search into the entire mysql database, if this is helpful.
https://github.com/gkssjovi/mysqlsearch

**Comment by EarthmanWeb** [comment]
Certainly not rocket surgery...truly odd that this is still in queue....

PHP: https://stackoverflow.com/a/5234937

Bash:  https://dba.stackexchange.com/questions/34856/how-to-search-whole-mysql-database-for-a-particular-string/86812#86812

Python: https://stackoverflow.com/questions/40473673/loop-over-all-tables-in-mysql-databases/40474159#40474159

What language do you folks at TablePlus code in?

**Comment by michaeldhopkins** [comment]
+1. I'd really like this feature as well. It'd keep me from having to write a script or dump the sql file to find strings in unfamiliar databases.

**Comment by rorych** [comment]
+1

**Comment by kaldesigns** [comment]
I get the impression the developer has ditched any further updates for MySQL. I can clearly see a bunch of commits for PostgreSQL. Not convinced I'll renew.

**Comment by jak-kal** [comment]
I get the impression the developer has ditched any further updates for MySQL. I can clearly see a bunch of commits for PostgreSQL. Not convinced I'll renew. 👎

**Comment by phifa** [comment]
need this for mariadb as well. any updates?

**Comment by lancaster-coder1991** [comment]
+1 this would be useful, at least an update on whether this is on the roadmap would be nice

**Comment by Ken-vdE** [comment]
+1

**Comment by MissYeh** [comment]
+1

**Comment by alnitaka** [comment]
+1

**Comment by JocelynTuohy** [comment]
+1

**Comment by huyphams** [comment]
WIP

**Comment by huyphams** [comment]
If you have a chance, please try this patch: https://www.dropbox.com/s/q18htnq1r0n6ysl/TablePlus.dmg?dl=0
Here is how to use it: https://twitter.com/TablePlus/status/1621376288509542401

Please let us know if you have any feedback!

**Comment by yunosh** [comment]
It's a bit hidden, but works like a charm, thanks!

**Comment by brandon-9** [comment]
@huyphams where is this setting? I can't find it. I just updated TP to the latest version. There is no icon next to the "Search for item..." bar.

**Comment by brandon-9** [comment]
@huyphams ah I understand, thanks!
