### ISSUE TITLE
Cannot See SQL Query in Query Window

### ISSUE THREAD

**Issue by dldereklee** [TablePlus/TablePlus#426]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.19, but I tested with other databases as well (MS SQL)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 105

3. The steps to reproduce this issue:
Go to the SQL Query screen. I can type into the query field, but I can't see what I'm typing. 

![image](https://user-images.githubusercontent.com/20377366/40018688-dbae08ba-5771-11e8-93c4-6a722c4ededd.png)

If I type a couple random characters, the numbering changes at the top, but I still can't see what I'm typing. 

![image](https://user-images.githubusercontent.com/20377366/40018855-5e4f1e94-5772-11e8-8510-5cd9912f3104.png)

**Comment by huyphams** [comment]
Hi @dldereklee, it's not a bug. It's because the split view was collapsed. You can drag it back.
<img width="1115" alt="qlquery" src="https://user-images.githubusercontent.com/3654622/40032869-174e7ac2-5820-11e8-89fa-8547c82c7f7a.png">

**Comment by huyphams** [comment]
I think we can improve it a little bit. The editor will always be visible when opening.

**Comment by huyphams** [comment]
I just improved it in the next update, TablePlus will auto resize the SQL Query if it is invisible for the first time.
