### ISSUE TITLE
Escape column names in search queries to avoid collisions when reserved keywords are used as column names

### ISSUE THREAD

**Issue by juicyarts** [TablePlus/TablePlus#428]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
ANY
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 (105)
3. The steps to reproduce this issue:
* eg. create a table containing a column with the name 'select/create/ANY_SQL_RESERVED_KEYWORD' 
* run a search {cmd+f} > Any Column > Contains > 'foo'
* getting `Invalid usage of the option NEXT in the FETCH statement.`

i ran into this while working on a database provided by a client.. i guess it's rarely exceptional to have an issue like this but escaping the values in the generated SQL statement should do it.

**Comment by huyphams** [comment]
Hey @juicyarts thanks for the reporting, I just fixed it in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by juicyarts** [comment]
Thanks for taking care that fast!
