### ISSUE TITLE
Add new row in SQL query editor

### ISSUE THREAD

**Issue by johnbona** [TablePlus/TablePlus#434]
Would be great to be able to add a new row in the SQL query editor (similar to MySQL Workbench) instead of having to switch to the table's data view to add a row.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 106

**Comment by huyphams** [comment]
it's supported on the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Press command + I to insert a new row.
