### ISSUE TITLE
Copying results should not include quotes.

### ISSUE THREAD

**Issue by jmfederico** [TablePlus/TablePlus#435]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 106

3. The steps to reproduce this issue:

When copying results from a query, the results should not be copied with quotes around them, That breaks changes the actual results.

For instance, when running the following query:

```sql
SELECT CONCAT('DROP DATABASE `', SCHEMA_NAME, '`;')
FROM `information_schema`.`SCHEMATA`
WHERE SCHEMA_NAME LIKE 'ss_%';
```

The results should look like this (assuming it matches two databases):
```sql
DROP DATABASE `ss_db1`;
DROP DATABASE `ss_db2`;
```

But, when copying from the results view, this is what actually gets copied:

```sql
"DROP DATABASE `ss_db1`;"
"DROP DATABASE `ss_db2`;"
```

Now, the results is unusable.

**Comment by huyphams** [comment]
Hi @jmfederico default, TablePlus copy content as `CSV`, you can change the behavior (such as Quote, Terminate, line break...) in preferences:

<img width="562" alt="nice" src="https://user-images.githubusercontent.com/3654622/40399878-d65c6556-5e69-11e8-9d55-a97c43fa72d5.png">

**Comment by jmfederico** [comment]
Ah, whold have never thought of looking in preferences.

Thanks.
