### ISSUE TITLE
Applying current_timestamp and on update changes produces wrong sql

### ISSUE THREAD

**Issue by andretti1977** [TablePlus/TablePlus#438]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
ver 1.0 (107)
3. The steps to reproduce this issue:
tried to apply current_timestamp and on update current timestamp to two timestamp fields, it produces incorrect sql (problem is with first alter you can see in preview)
Noted: If the bug is related to data, please attach an example SQL data.

![image](https://user-images.githubusercontent.com/856429/40539949-a8aeac1e-6016-11e8-98c8-69802f1f30c2.png)

**Comment by huyphams** [comment]
Hi, sorry because of the late response. I will fix it in the next update 108.

**Comment by huyphams** [comment]
It was fixed on the build 188. Thanks!
