### ISSUE TITLE
How to Draw Diagrams with Plugin feature

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#44]
In another [comment thread you mentioned](https://github.com/TablePlus/TablePlus/issues/21#issuecomment-317310983) you could 'draw diagrams' with the plug-in feature.

How would one go about doing this?  I only see examples to populate / select data and nothing to draw any diagrams.

Being able to generate a diagram of my existing schema / table structure sounds very interesting.  

-Brian

**Comment by huyphams** [comment]
Yup, the plugin feature is being developed. I will add it onto plugin market when it done.

**Comment by eternalBlast** [comment]
Hi @huyphams is the plugin feature available now

**Comment by huyphams** [comment]
Some of theme, you can press command + L to install it. Currently, it does not support third-party plugin.

**Comment by eternalBlast** [comment]
Thanks @huyphams. How about plugin or other tools to generate diagram of a schema?

**Comment by huyphams** [comment]
We have a plan to public document and API for developers but it was delayed after `encoding`, `exporting` and `user managerment` features.

**Comment by eternalBlast** [comment]
Okay, thanks. I'll be waiting for that feature.

**Comment by karocksjoelee** [comment]
any update on this ?

**Comment by zongzhiliu** [comment]
+1 on the wish to draw diagrams. even better if relationship notation is customerizable.

**Comment by JohnRomanski** [comment]
Any updates or tips for developing plugins?

**Comment by huyphams** [comment]
We're working on the plugin system, I will update it asap.
Thanks all.

**Comment by akiratuti** [comment]
Any update on this? For me, only this plugin for TablePlus is missing

**Comment by JacekJMMJ** [comment]
I am also waiting for the ER Diagram plugin.

**Comment by jfturpin** [comment]
This would be incredibly useful. Also waiting for the ER Diagram plugin.

**Comment by yanlimin9** [comment]
waiting on the ER Diagram +1.

**Comment by aesyondu** [comment]
There just isn't enough demand for this feature. Similar feature has also been requested for [Azure Data Studio](https://github.com/Microsoft/azuredatastudio/issues/94) since Nov 2017 but no progress has been made.

**Comment by huyphams** [comment]
Nope @aesyondu we are working seriously on this feature

**Comment by vvo** [comment]
Just want to say I am really looking forward such a feature, even in its most simplistic form. Right now most SQL => diagram tools are very hard to install/use or bloated with myriad of features and buttons. Usually I just want to visually check my schema.. Thanks and keep us posted!

**Comment by joriswvanrijn** [comment]
I second this, really looking forward to this plugin!

**Comment by huyphams** [comment]
The object and arrow can be changed from a standard <-> show off diagram 👀
![2020-05-24 17 35 45](https://user-images.githubusercontent.com/3654622/82752377-d1239e00-9de7-11ea-9cb2-ccf11135bba5.gif)

**Comment by JacekJMMJ** [comment]
Is this feature available in the current version? How can I see this diagram view?

**Comment by JonestownPunch** [comment]
@huyphams Hi Henry, I'm a new user and wonder if this plugin is something that I can start using today? I'm new to GitHub, so not sure how to acquire or install the plugin for TablePlus 3.5.0(3.08). Could you help?

**Comment by huyphams** [comment]
@JacekJMMJ  It will be released soon!
@JohnRomanski you can install plugins by press command + L

**Comment by nachoal** [comment]
When this will be released? This will be a serious consideration for me to upgrade

**Comment by leventtunc** [comment]
Looking forward to it 🤤 . Don't want to push but please hurry up @huyphams  😄 .

**Comment by nickreynke** [comment]
Is there already more to say about this? 😊

**Comment by guillermogfer** [comment]
This is already available [installing the plugin](https://github.com/TablePlus/diagram-plugin)

You can install the plugin by clicking Command + L (Mac) or through the Plugins menu:
![image](https://user-images.githubusercontent.com/11395867/89193243-0269d880-d5a6-11ea-9b2b-0a25602df956.png)

Then you select Diagram Generator
![image](https://user-images.githubusercontent.com/11395867/89193158-dfd7bf80-d5a5-11ea-9fe6-cc2487449298.png)

After that, you can go to your database, choose the tables you want and right-click and you'll see the Generate diagram > Generate diagram option. 
![image](https://user-images.githubusercontent.com/11395867/89193619-88861f00-d5a6-11ea-833e-c3d2a3465beb.png)

Also you can create an empty diagram and build from scratch.

**Comment by jfturpin** [comment]
Thank you for the feedback, but where is this option for the Plugin Manager in the Windows version of TablePlus?

Regards,


Jon Turpin  |  Sales Engineer  |  DirectEmployers Association
p 317.874.9119  |  e jturpin@directemployers.org  |  DirectEmployers.org<https://directemployers.org/>

Connect with me: LinkedIn<http://www.linkedin.com/in/jonftech>

[Title: DirectEmployers | Recruit Rooster]

**Comment by huyphams** [comment]
We're working on an update of the Diagram and also the Plugin on Windows Version. We will release it within this week.
Thanks all.

**Comment by jfturpin** [comment]
Bless you Henry, thank you for all your hard work, I LOVE your software.

Regards,


Jon Turpin  |  Sales Engineer  |  DirectEmployers Association
p 317.874.9119  |  e jturpin@directemployers.org  |  DirectEmployers.org<https://directemployers.org/>

Connect with me: LinkedIn<http://www.linkedin.com/in/jonftech>

[Title: DirectEmployers | Recruit Rooster]

**Comment by vvo** [comment]
Woah, just tried the plugin: amazing! This almost feels like a second product inside the main product :)

**Comment by Haarolean** [comment]
It doesn't work for me, I get an empty window instead.
![image](https://user-images.githubusercontent.com/1494347/89270315-d9982080-d643-11ea-86c3-91b8b0863b9e.png)

**Comment by slopezm** [comment]
Great work! Thank you

**Comment by Errindel** [comment]
@Haarolean try to update TablePlus first. Got the same issue and it seems that I was 16 versions behind ;)

**Comment by iammohsinar** [comment]
@huyphams  I am loving it after seeing this plugin <3

**Comment by jkvgo** [comment]
@huyphams just came here to say I love this plugin and this is seriously making me consider upgrading!

**Comment by saikrishnakethan** [comment]
How can I know the kind of relationship here ?. Is it one to one (or) one to many ?

**Comment by CemYil03** [comment]
For me the generate diagram option does not auto-generate depending on my selected tables, neither does the import file function seem to work for me. Am I the only one having this issue?

Love your software anyways man :)

**Comment by mapleroyal** [comment]
Any update on whether this will be updated to show the relationships (e.g. one to many and so on) instead of just the references? It's an entity-**relationship** diagram...?

**Comment by neanda** [comment]
this is a great feature, and no.1 thing  i've been looking for, however, where's the option to 'Generate from Database' like it says in your web app?  I see the option to generate from tables if i select a few tables and right click, but it's

It be great if it could directly import and export to, or sync with, the database like luna modeler does as everything else is great
