### ISSUE TITLE
Add the LIKE and ILIKE comparison operators to the filter

### ISSUE THREAD

**Issue by ndastur** [TablePlus/TablePlus#440]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Latest

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @ndastur you can use `contains`, `not contains`, `has prefix`, `has postfix` for `LIKE` operation.
<img width="546" alt="screen shot 2018-05-29 at 9 18 32 am" src="https://user-images.githubusercontent.com/3654622/40634854-641502ac-6321-11e8-8944-0566ef117b8a.png">

**Comment by ndastur** [comment]
Thanks @huyphams but ILIKE in order to do case insensitive search would be a real plus

**Comment by huyphams** [comment]
Hey guy, I added ILIKE for the advanced filter: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for the suggestion!

**Comment by boesbo** [comment]
I can not find it. Version 2.11.2

**Comment by huyphams** [comment]
Are you using MySQL? @boesbo I just googled, and see that we can do case insensitive in MySQL with 
SELECT * FROM `a_table` WHERE BINARY `a_column` LIKE '%a_pattern%' let me check it more carefully and see if we can add it into TablePlus.

**Comment by boesbo** [comment]
> WHERE

Yes, Mysql

**Comment by huyphams** [comment]
It's supported now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks @boesbo

**Comment by boesbo** [comment]
> It's supported now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
> Thanks @boesbo

Will it be released in a standard release?

**Comment by huyphams** [comment]
it's released officially on the build 282 now @boesbo
