### ISSUE TITLE
Cannot view other schemas on PostgreSQL 

### ISSUE THREAD

**Issue by anfieldleung** [TablePlus/TablePlus#442]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.1.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
107

3. The steps to reproduce this issue:
Opened a connection to DB, in the left bottom corner, I couldn't find other schemas on the selected db. 
<img width="250"  src="https://user-images.githubusercontent.com/34707680/40696060-a6ffa2ea-63f6-11e8-9e16-35ee11886ab4.png">
But when on click command + P, I am able to search the items (table, views, functions ... etc) 
<img width="400" src="https://user-images.githubusercontent.com/34707680/40696059-a6caf6bc-63f6-11e8-96f2-fb6231114d74.png">

**Comment by huyphams** [comment]
Hi @anfieldleung probably acm was created by the system user. Can you go to preferences and stick on this option:
<img width="218" alt="nice" src="https://user-images.githubusercontent.com/3654622/40696233-2be18f44-63ef-11e8-8768-3ba8b10287aa.png">

**Comment by anfieldleung** [comment]
Awesome!

**Comment by huyphams** [comment]
Hi @anfieldleung I just optimized the code filtered system schema. Now, TablePlus only filters schema was created by PostgreSQL (not by the user).

You can download the hot patch here:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
