### ISSUE TITLE
Item side panel jumps to fixed width when trying to resize

### ISSUE THREAD

**Issue by thenaturalist** [TablePlus/TablePlus#443]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

107

3. The steps to reproduce this issue:

Open new DB connection, search for table in items, try to resize left side panel by pulling it to the right. Upon releasing the cursor, the panel jumps back to a fixed width making long item names unreadable. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by thenaturalist** [comment]
@huyphams I realized now that this behavior is caused by the # of open tabs in relation to screen width. So above a certain critical number, the side panel jumps to a fixed width, arbitrarily shortening some table names. When trying to resize it, the panel will always jump back to that size. Only closing tabs allows resizing. I guess this is due to the fact that tabs have a fixed width, but it's really annoying at times if I need to either open/close/open tabs to check facts or resize temporarily to navigate well.

**Comment by huyphams** [comment]
Yeah, now I can reproduce it, thanks @thenaturalist

**Comment by huyphams** [comment]
Hey @thenaturalist please go to Preferences > Receive Beta Builds (Don't worry, it's pretty stable for production) and update to the build 124, let me know it was fixed. I tested and it works as expected on my setup.

**Comment by alvint** [comment]
This fix also seems to fix the enhancement from issue #579 acting wonky.

**Comment by huyphams** [comment]
Awesome! 😄
