### ISSUE TITLE
Nice to have: CoreData sqlite right click to open

### ISSUE THREAD

**Issue by agiguere** [TablePlus/TablePlus#444]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
107

3. The steps to reproduce this issue:

It would be nice to be able to right click on an sqlite file directly and choose TablePlus to open it

right now when I tried to right click and choose TablePlus to open my iOS CoreData file, it does not work

thanks

**Comment by huyphams** [comment]
Hey @agiguere You can double click on SQLite file to open in TablePlus. TablePlus support file with extensions: .db, .sqlite, .sqlite3

**Comment by agiguere** [comment]
no, you can't do that, Apple CoreData file in the simulator have extension .sqllite

if I right click the file and choose open with program TablePlus you gave me this error

<img width="854" alt="screen shot 2018-06-01 at 10 55 56 am" src="https://user-images.githubusercontent.com/8300810/40847595-d18b84f8-658a-11e8-9411-d02c7a6cbc32.png">

**Comment by agiguere** [comment]
Apple core data file extension is sqllite and not sqlite

**Comment by huyphams** [comment]
That made sense, TablePlus doesn't support sqllite (double l) at this time. Probably I should add it in next update. Thanks.

**Comment by huyphams** [comment]
You can try the new build here, it supports sqllite extension: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by agiguere** [comment]
thanks, I could wait until the next update, that would be a nice addition for iOS developers

funny fact, if I create a new connection and select the sqllite file, it works

it's juste the right click to open that does not work
