### ISSUE TITLE
Bug: Edit two tabs

### ISSUE THREAD

**Issue by ruanltbg** [TablePlus/TablePlus#445]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
107

3. The steps to reproduce this issue:
When I have two tabs open and I try to save data on both tab the SQL is wrong, it tries to save data from table A in table B and the data from table B in table A.

![image](https://user-images.githubusercontent.com/237136/40854477-9d3b3e0e-659f-11e8-8406-90b880ff4db0.png)

![image](https://user-images.githubusercontent.com/237136/40854508-bbcc91ec-659f-11e8-9de3-b1a324172fcf.png)

- I do not know how to reproduce as it does not happen always, but when it happens I need to close both tabs.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @ruanltbg thanks. But in the next time it happens, could you take a screenshot this screen? it helps me a lot to reproduce the bug.
<img width="896" alt="screen shot 2018-06-02 at 9 13 30 am" src="https://user-images.githubusercontent.com/3654622/40869451-73b4ddc8-6645-11e8-9074-609524e5372f.png">

**Comment by ruanltbg** [comment]
@huyphams the red one is the wrong query.

![image](https://user-images.githubusercontent.com/237136/40926170-9028f1b0-67e9-11e8-9c6a-4edea535c2ba.png)

**Comment by huyphams** [comment]
Hey @ruanltbg I can reproduce the bug and it's fixed now in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

You can reproduce the bug by following this gif.
![2018-06-05 11 19 29](https://user-images.githubusercontent.com/3654622/40955133-5f4bc6de-68b2-11e8-9bc9-dc02a6335c8d.gif)
