### ISSUE TITLE
Can not set varchar field back to NULL

### ISSUE THREAD

**Issue by telcy** [TablePlus/TablePlus#446]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 108

3. The steps to reproduce this issue:
Create a table with a varchar column. Add some text and try to set it back to NULL.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @telcy there are two ways to set NULL for varchar field (and other fields).
- Hold option + Click on the cell.
- Use the right panel.
See the picture below.
<img width="1002" alt="null" src="https://user-images.githubusercontent.com/3654622/40885892-419c98b6-6759-11e8-8511-3c4d9823254d.png">
