### ISSUE TITLE
Import from gzipped file

### ISSUE THREAD

**Issue by welcoMattic** [TablePlus/TablePlus#447]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
All

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 108

It will be useful to allow import of gzip files that contains .sql files instead of unzip them and import as text. Espacially when unzipped files are about tens of Go.

Thanks for your work 👍

**Comment by effectjared** [comment]
+1 for this

**Comment by huyphams** [comment]
It's released on the build 182.
