### ISSUE TITLE
Autocomplete not appearing for objects outside of the default dbo schema in SQL Server

### ISSUE THREAD

**Issue by keithmullins** [TablePlus/TablePlus#448]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
SQL Server 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
109

3. The steps to reproduce this issue:
In the SQL Editor the autocomplete doesn't appear for objects that are outside of the default dbo schema. For example, I have a table called `Products` in both the `dbo` schema and a schema named `Archive`. When I type `SELECT * FROM dbo.Pro` I get autocomplete suggestions but when I type `SELECT * FROM Archive.Pro` I get no autocomplete suggestions.

![image](https://user-images.githubusercontent.com/6208822/41171193-84d7b53a-6b04-11e8-9847-428187bc12f4.png)

![image](https://user-images.githubusercontent.com/6208822/41171207-8c5583aa-6b04-11e8-9465-dcc903f7014a.png)

**Comment by huyphams** [comment]
I have fixed this issue in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for the reporting.

**Comment by keithmullins** [comment]
Thank you for looking at this so quickly. I have tried out the new build and it works great for `SELECT` statements but I do not have the autocompletion when running `FUNCTION`s or `STORED PROCEDURE`s - I am not sure if this functionality is in TablePlus though. 

For example, if I type `SELECT * FROM Archive.Pro` I now get autocompletion but if I type `EXEC Archive.spArc` I don't receive any autocompletion. 

If I type `spArc` by itself I get autocompletion, and the autocompletion window tells me that the proc is in the `Archive` schema, however when I press ENTER to select the autocompletion all that gets outputted to the screen is `EXEC spArchiveProducts` instead of `EXEC Archive.spArchiveProducts`.

**Comment by keithmullins** [comment]
Hey @huyphams - thanks again for looking at this so quickly. This is now working in the newest version! 

I am really enjoying using your product. I have found a few other issues but I will log them separately! More work for you :-)
