### ISSUE TITLE
Unable to create or edit connections once any connection is open (UX/Flow issue)

### ISSUE THREAD

**Issue by CliffWMiller** [TablePlus/TablePlus#449]
1. Which driver are you using and version of it: PostgreSQL 10.1

2. Which TablePlus build number are you using: 109

3. The steps to reproduce this issue:

I don't think this is a bug so much as it is a UX/Flow issue.

The only place I seem to be able to add or edit a connection is the welcome splash window when I first open TablePlus. Once I've connected to a database and am inside the full application I can only open saved connections. It's possible there is a way and I'm just not finding it but I've looked through all the menus and dialogs that make any sense to me. The problem is that, right now, if I want to add or edit a connection I need to close the application out completely and reopen it. This can be incredibly disruptive. 

So steps would be:
1. Open application
2. Open a connection
3. Try to create or edit a connection
Result: Feature doesn't exist.

It's possible this is a bug and the feature is supposed to exist in the Open Connection dialog. In that case I'm not able to right click a connection to edit it (like I can in the welcome window) and there is no option to add a connection there. If this is the case, I'm on MacOS 10.13.4 as that might be relevant. 

If the feature does exist somewhere, I feel it is too hidden for such a common task. I've spent a fair amount of time making sure I'm not crazy before submitting this.

**Comment by huyphams** [comment]
Hey thanks, you can do it by pressing Command + N. I will improve this ux by adding the menu in next update 👍

**Comment by huyphams** [comment]
I just added it to the menu bar in this build:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

<img width="318" alt="screen shot 2018-06-09 at 12 31 26 pm" src="https://user-images.githubusercontent.com/3654622/41188015-0ebe199c-6be1-11e8-91db-25fdb29e4376.png">

**Comment by CliffWMiller** [comment]
Awesome! That's perfect. 

Sorry I didn't realize that New Workspace would get me what I need. For some reason it just didn't sound like what I was looking for.
