### ISSUE TITLE
MySQL: The content of functions (procedures) is not displayed when its name has a point

### ISSUE THREAD

**Issue by SolomatovS** [TablePlus/TablePlus#450]
Percona MySQL 5.7.22-22
TablePlus 1.0 (109)

The steps to reproduce this issue:
0. Create a test data base:

```
create database test;
use test;
```

1. Create a function (or stored procedure) which name has a point:

```
CREATE DEFINER=`root`@`%` FUNCTION `Datetime.To.UnixTimestamp`(`From` datetime) RETURNS int(10)
    NO SQL
    DETERMINISTIC
    SQL SECURITY INVOKER
BEGIN
  RETURN (TIMESTAMPDIFF(SECOND, '1970-01-01 00:00:00', `From`));
END;
```
2. Make sure that the function exists on the server:
```
show create function `Datetime.To.UnixTimestamp`;
```
3. Entering TablePlus, we open data base `test`, and see that TablePlus doesn't display the function content because the function name has a point
![tableplus 2](https://user-images.githubusercontent.com/9378822/41194471-16f9670e-6c24-11e8-8a6f-a9edb87294ac.gif)

**Comment by huyphams** [comment]
Hey @SolomatovS thanks for the reporting and the awesome gif, I fixed it in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
I forgot to add brackets when getting function definition.

**Comment by SolomatovS** [comment]
very fast fix it, thnx!

**Comment by huyphams** [comment]
@SolomatovS you can change the title bar color by clicking on the title bar
