### ISSUE TITLE
[not important] too many connection error dialog when disconnect multi connection

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#452]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
> MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
> Build108

3. The steps to reproduce this issue:

* open multi connections
* disconnect network (close mac book)
* then there will have multi connection error dialog

![image](https://user-images.githubusercontent.com/5211881/41215905-0322d0f0-6d85-11e8-9802-9c82e468f36a.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @bulletRush thanks for the reporting. I will optimize this behavior.

**Comment by bulletRush** [comment]
@huyphams so you change this to a warning dialog now.....
![image](https://user-images.githubusercontent.com/5211881/46717389-53eef800-cc9a-11e8-9af2-258aad72840b.png)

**Comment by huyphams** [comment]
This popup will show when the server taking too long to respond. There is no error reported, so the best thing TablePlus can do is showing it, and ask user want to reconnect or keep waiting.

**Comment by bulletRush** [comment]
@huyphams there is too many warning dialog when my ssh tunnel is closed.
