### ISSUE TITLE
update procedure uses drop function instead of drop procedure so fails

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#454]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ayalbelling** [comment]
As per title - i.e. existing procedure, make change, run commit and it uses DROP FUNCTION and so fails. Microsoft SQL Server, version 1.0 (109) Mac.

**Comment by huyphams** [comment]
Thanks, it will be fixed in the next release.

**Comment by ayalbelling** [comment]
Thanks for all of these fixes!

**Comment by ayalbelling** [comment]
Actually, this one isn't fixed I'm afraid. Delete from the menu and then
commit works, but editing a procedure then commit still uses drop function.

**Comment by huyphams** [comment]
Thanks, I missed that case. Just fixed it: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
