### ISSUE TITLE
clustered indexes not always showing in index pane

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#455]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ayalbelling** [comment]
Microsoft SQL Server, v1.0 (109) Mac

Used this in the SQL pane, opened table, viewed the structure and the primary key index isn't in the index pane but does exist. Tested its existence by trying to add it in the pane and the error returned shows the index exists.

CREATE TABLE [dbo].[TempTable] (
    [oID] bigint IDENTITY (1, 1) NOT NULL,
	[Name] nvarchar (256) not null,
    PRIMARY KEY CLUSTERED ([oID] ASC)
    );

**Comment by huyphams** [comment]
Thanks @ayalbelling for the helpful detail. I will take a look into it.

**Comment by huyphams** [comment]
I checked @ayalbelling currently, TablePlus hide primary index. I just enabled it on this build:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thank you so much.
