### ISSUE TITLE
Keep "filters" open by default

### ISSUE THREAD

**Issue by arliber** [TablePlus/TablePlus#457]
Apologies if there is already a way to do that but it will be super nice if TablePlus would remember that I opened the "filters" bar so I won't have to click the button at the bottom of screen each time I open a new tab.

Thank you

**Comment by huyphams** [comment]
Hi, there is a shortcut key: command + F and many other shortcuts:
<img width="638" alt="screen shot 2018-06-12 at 3 02 29 pm" src="https://user-images.githubusercontent.com/3654622/41277534-b13b477c-6e51-11e8-9d37-5759089b222f.png">
We won't show filter by default because it reduce the view size of table content.

**Comment by huyphams** [comment]
But probably, we can remember the last state of the filter (show/hide) of the table.

**Comment by arliber** [comment]
cmd + f is good enough - should've looked at shortcuts first.
Thanks for making this - big fan :)

**Comment by huyphams** [comment]
Table now support save the state of the filter, column sizing, position and many more:
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feedback!

**Comment by johnbwoodruff** [comment]
@huyphams this seems to only save the state of the filter per-table? Is that correct or am I seeing this wrong? Is there a way to set that I ALWAYS want that filter row to be open when opening a new table? Not just tables I've previously opened it on.

**Comment by huyphams** [comment]
Hi @johnbwoodruff yep, it will restore the last filter state (show/hide) and when you open a new table, it's closed by default.
However, I added a new filter config on the beta build. I think I could one more option `Default filtr state: alway close, alway hide, restore the last filter state`
<img width="438" alt="Screen Shot 2019-09-13 at 4 56 06 PM" src="https://user-images.githubusercontent.com/3654622/64891089-66f70e80-d647-11e9-8ddf-9ba29075352d.png">

**Comment by johnbwoodruff** [comment]
Always show/always hide would be amaaaaazing! 😄 If it's not too much trouble.

**Comment by huyphams** [comment]
it will be available in the next update 👍 
<img width="575" alt="Screen Shot 2019-09-15 at 4 03 12 PM" src="https://user-images.githubusercontent.com/3654622/64926306-6b036780-d7d2-11e9-8ad5-a743158a900f.png">
