### ISSUE TITLE
Default dump names without spaces, or configure a default pattern for dump filenames

### ISSUE THREAD

**Issue by coisnepe** [TablePlus/TablePlus#458]
Right now, when backing up a database, the default name generated looks like this: `my_database-12 June 2018`. Restoring a dump from the command line will fail because words after the first space are parsed as arguments. Generating `my_database-12_June_2018` would be safer.

Even better would be configuring a default name pattern from the Preferences pane: `[db_name]_[YYYY][MM][DD]`, `[YYYY][MM][DD]:[HH][SS]_[db_name]` etc...

**Comment by huyphams** [comment]
Hey thanks @coisnepe for the reporting. I will fix it in the next release.
