### ISSUE TITLE
Modifying default constraint created add constraint script which fails

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#459]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ayalbelling** [comment]
Ms SQL Server, v1.0 (109) Mac. This was attempted on an NVARCHAR(10). Also, setting an existing default constraint to null created an ADD CONSTRAINT script rather than dropping the constraint.

**Comment by huyphams** [comment]
Hi @ayalbelling thanks for the feedback. it should be fixed in the next update.
Btw, when adding support database driver, I find out that Microsoft always has weird syntax. That needs a lot of time to work around.

**Comment by huyphams** [comment]
I closed this because it's duplicated with: https://github.com/TablePlus/TablePlus/issues/512
