### ISSUE TITLE
ERR wrong number of arguments for 'get' command for Redis DB for keys with spaces

### ISSUE THREAD

**Issue by josser** [TablePlus/TablePlus#460]
1. Redis 3.2.6

2. Build 109

3. Values of keys with spaces are not displayed. 

Here is screenshot:
![screen shot 2018-06-13 at 15 52 59](https://user-images.githubusercontent.com/103639/41352338-e2664f7e-6f21-11e8-900a-019543419c99.png)

**Comment by huyphams** [comment]
Hi that because there are spaces in key, I find out that the current Redis lib is not supported space. I will find the other way to do it. Thanks for the reporting.

**Comment by huyphams** [comment]
I'm starting to working on this issue, now you can get the value of the key with spaces. You can download here:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

Remaining: support custom query with space and command generate with space.

**Comment by josser** [comment]
Cool! Thank you! 
This is not very critical to my workflow so I can wait until next public build :)
