### ISSUE TITLE
OverSSH connection support ECDSA

### ISSUE THREAD

**Issue by alphatr** [TablePlus/TablePlus#461]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL  Ver 15.1 Distrib 10.0.21-MariaDB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

build 109

3. The steps to reproduce this issue:

I can't connection my server in overSSH ecdsa pubkey, and use rsa pubkey success. when I use ssh connect server over ecdsa still success

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey thanks @alphatr, I will look into it.

**Comment by huyphams** [comment]
It's supported on the lasted build.
