### ISSUE TITLE
Owner is not shown for functions (Postgres)

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#464]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
110

3. The steps to reproduce this issue:
Click on "Functions" in the sidebar to see a list of functions in the current schema. The owner column shows "--".

![image](https://user-images.githubusercontent.com/4483085/41459266-5e7e1340-7089-11e8-91d3-cc3ff8922602.png)

The functions are not ownerless (Is that even possible?)
`select proname, proowner::regrole from pg_proc where proname = 'acl_calc'`

![image](https://user-images.githubusercontent.com/4483085/41459331-9aca0b56-7089-11e8-8e0a-d8afc87c28f1.png)

**Comment by huyphams** [comment]
Hey thanks for the reporting @msageryd , I will fix it in the next update.

**Comment by msageryd** [comment]
Wow!
This was a fast reply. TablePlus does not quite cut it yet for me to get rid of SQLPro, but the potential is there. I'm very impressed with the speed of the product and the speed of the development.

I bought a TP licence to support your work. This will be very interesting.
