### ISSUE TITLE
[bug report] multi update only one history

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#467]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
> MySQL 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
> Bulid 109

3. The steps to reproduce this issue:

* update one record, then there will have one history log
* update other record, history window not refreshed
* update again, then there will have three history log

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @bulletRush TablePlus history is based on Connection-Database, so there are multiple histories.

**Comment by bulletRush** [comment]
@huyphams seems like history window not refreshed

**Comment by huyphams** [comment]
Ah, I was wrong, it's only based on connection. I will think about it.
