### ISSUE TITLE
need strict mode

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#469]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

> MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
> Build 109

3. The steps to reproduce this issue:

> I want TablePlus generate update sql like `UPDATE table SET status=1 where id=100 and status=2` instead  of `UPDATE table SET status=1 where id=100`

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @bulletRush does the column `status` is primary key? which is the primary key of the table?

**Comment by huyphams** [comment]
TablePlus generates update statement based on primary key, if the table has a compound index, it should be a compound condition.
<img width="1257" alt="screen shot 2018-06-15 at 4 55 27 pm" src="https://user-images.githubusercontent.com/3654622/41462398-ee986ca4-70bc-11e8-92ec-bf8658f02737.png">

**Comment by bulletRush** [comment]
@huyphams status is not primary key. I mean we should have a mode so that if anyone else have changed the status, our update operation should failed.

**Comment by huyphams** [comment]
TablePlus have safe mode. Is that the feature you’re looking for? (The lock icon on the toolbar)

**Comment by alvint** [comment]
Just my two cents, but this sounds like business logic that is too specific a use case. If included, it would cause more confusion than usefulness. -1.

**Comment by bulletRush** [comment]
@huyphams for example, If you have open a connection too long and not refreshed. Then you may see a invalid status of your record. If you use your table to record your customer money, you may see their balance is 1000. but their may have other program modify this record to 2000. Then you want discount their balance with 10. so you input 9990 and update it and success. but in fact, the balance should be 1990. If your have strict mode, your may generate a sql like `UPDATE table SET money=9990 where custom="aa" and money=1000` and update failed. but in alert mode or safe mode, you will generate a sql like `UPDATE table SET money=9990 where custom="aa"` and update success.
this maybe a rarely user case, your can refused, it's fine. and wish i can write my plugin to achieve my needs one day.

**Comment by huyphams** [comment]
Hey, @bulletRush Now, I understand your situation. But I think I can't add it (or at least in the near future). it's too specific and maybe not necessary with the other customer like @alvint
