### ISSUE TITLE
[bug] dark mode behavior error

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#470]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* build 109

3. The steps to reproduce this issue:
![image](https://user-images.githubusercontent.com/5211881/41462859-da1c6dfc-70c6-11e8-817a-2a3f0e2142e8.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It’s duplicated https://github.com/TablePlus/TablePlus/issues/466
