### ISSUE TITLE
SQLite: Changes to columns aren't saved

### ISSUE THREAD

**Issue by alvint** [TablePlus/TablePlus#473]
Possibly related is issue #242 

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite 3.23.1
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
110
3. The steps to reproduce this issue:
- connect to a DB
- create a new table
  - add a column.
- hit CMD-S to save. it saves correctly
- edit the added column (for example, rename it).
- hit CMD-S to save. the table reverts back to its previous saved state.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by alvint** [comment]
I'm not sure if this is related, but the preview SQL when editing a table is always blank.

**Comment by alvint** [comment]
I'm going to assume this is because you cannot use `alter table` to modify columns in SQLite.

**Comment by jamie1192** [comment]
Came here wondering why my SQLite database changes via the GUI weren't sticking in TablePlus..

Why not implement changes the same way SQLiteStudio does?

example of what queries it executes when changing a column data type-

    PRAGMA foreign_keys = 0;

    CREATE TABLE sqlitestudio_temp_table AS SELECT *
                                          FROM userAttempts;

    DROP TABLE userAttempts;

    CREATE TABLE userAttempts (
        ID         [INTEGER AUTO_INCREMENT] UNIQUE
                                            NOT NULL,
        ResponseID INTEGER                  REFERENCES userResponses (ID) ON UPDATE CASCADE,
        QuestionID INTEGER,
        Answer     INTEGER,
        UserScore  INTEGER,
        PRIMARY KEY (
            ID
        )
    );

    INSERT INTO userAttempts (
                                 ID,
                                 ResponseID,
                                 QuestionID,
                                 Answer,
                                 UserScore
                             )
                             SELECT ID,
                                    ResponseID,
                                    QuestionID,
                                    Answer,
                                    UserScore
                               FROM sqlitestudio_temp_table;

    DROP TABLE sqlitestudio_temp_table;

    PRAGMA foreign_keys = 1;

**Comment by huyphams** [comment]
Excellent suggestion @jamie1192, I think I can implement it this way.

**Comment by jamie1192** [comment]
hey @huyphams, is there any progress on this lately?

**Comment by huyphams** [comment]
Finally, TablePlus now support drop column: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Please let me know if you are still seeing the issue!
Thanks.
