### ISSUE TITLE
SQLite: when creating a table, default to the `integer` data type for the ID column

### ISSUE THREAD

**Issue by alvint** [TablePlus/TablePlus#474]
Currently, the default data type used for the ID column when creating a new table is `serial`. However, there use no `serial` datatype in SQLite. There is no error shown because SQLite simply assumes a data type of `number` if the given type doesn't match a type it knows.

The correct data type for SQLite primary keys is `integer` (not `int`). If a table has a single primary key column of type `integer`, SQLite knows to automatically assign an ID when adding a row.

A separate but related issue is that some users may require more stringent auto increment rules for the primary key. The proper syntax for creating a primary key column with the more stringent rules is `CREATE TABLE "my_table" ("id" integer primary key autoincrement)`.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite 3.23.1
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
110
3. The steps to reproduce this issue:
- create a new table. the data type of the generated ID column is `serial`.

**Comment by huyphams** [comment]
There are some strange behaviors:
1. if I keep the ID column to serial. After hitting the command + S, it will create an index.
2. If I change it to integer => no index:

<img width="1170" alt="screen shot 2018-06-16 at 8 27 10 am" src="https://user-images.githubusercontent.com/3654622/41494572-19b34e72-713f-11e8-8c12-535986ce3236.png">

I will research more and update it in next release.

**Comment by alvint** [comment]
SQLite always creates a special hidden `rowId` column when creating a table (unless you tell it not to). This column uniquely identifies every row in the table. When a single `integer` column is used as the primary key, SQLite doesn't actually add that column; it just creates an alias from your column name (`id` in this case) to that `rowId` column.

Since `rowId` is already unique, SQLite doesn't need to add a "unique" index for the primary key.
