### ISSUE TITLE
MySQL: Editing of the Procedure/Function forms an incorrect SQL Statement for DROP

### ISSUE THREAD

**Issue by SolomatovS** [TablePlus/TablePlus#475]
TablePlus 1.0 (110)
Percona MySQL 5.7.22-22

If editing procedure, a query for DROP will be performed, and after that CREATE of a new procedure
![2018-06-15 22 12 11](https://user-images.githubusercontent.com/9378822/41486702-458ef484-70ee-11e8-95da-d6319a8023ef.png)

1. pay attention that this query for drop has "DROP FUNCTION IF EXISTS" instead of "DROP PROCEDURE IF EXISTS";
2. The name of the deleted procedure is not escaped. When the name procedure has the "." symbol then DROP will fail:
> You have an error in your SQL syntax

There is a specialty while working with MySQL. MySQL doesn't have a transaction DDL, so while editing of a function/procedure we make a syntax error, and then apply changes with the button  "Commit your changes", MySQL will DROP then function/procedure without the possibility to recover and will not create a new one as it has a syntax error.
To see how it works please do the following:
1. CREATE a simple function
```
CREATE FUNCTION `test`() RETURNS INT
    NO SQL
    SQL SECURITY INVOKER
BEGIN
  RETURN 1;
END;
```
2. Edit it so that it has a syntax error, e.g.:
```
CREATE FUNCTION `test`() RETURNS INT
    NO SQL
    SQL SECURITY INVOKER
BEGIN
  R 1;
END;
```
<img width="833" alt="2018-06-15 23 14 23" src="https://user-images.githubusercontent.com/9378822/41487678-3e2094ec-70f2-11e8-82f6-02bdc21f80b4.png">

3. Click the button "Commit your changes", and the function "test" will totally be dropped from the MySQL server.
<img width="921" alt="2018-06-15 23 14 42" src="https://user-images.githubusercontent.com/9378822/41487691-471ff3da-70f2-11e8-96c2-900f813e87d1.png">

I offer to solve this problem as in DbForge MySQL:
1.  Create a copy of the function/procedure with a new name (e.g. with prefix)
2. DROP the old function/procedure
3. Try to create a new function/procedure
[4.] When the try failed we have to recover the old function/procedure from step one

**Comment by huyphams** [comment]
Hi @SolomatovS I have fixed it yesterday on this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for the reporting.

**Comment by SolomatovS** [comment]
thanks a lot!
