### ISSUE TITLE
Alternating grid row colors does not work in dark theme

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#476]
![image](https://user-images.githubusercontent.com/4483085/41507687-1a7572dc-7238-11e8-8780-f5e92eaebbd7.png)

With alternating row background:
![image](https://user-images.githubusercontent.com/4483085/41507688-22055846-7238-11e8-9201-546f3c485741.png)

Without alternating row background:
![image](https://user-images.githubusercontent.com/4483085/41507693-3ba11d08-7238-11e8-8ac1-7efb54314e04.png)

**Comment by huyphams** [comment]
It does work. You can see the first image, there are actually two colors. But, in the dark mode, the color is not much difference. This is one of the know issues, custom the native experience is very hard.
Btw, it looks better in Mojave:

<img width="1174" alt="screen shot 2018-06-18 at 10 03 46 am" src="https://user-images.githubusercontent.com/3654622/41516438-f2b6b920-72de-11e8-992c-8b7e740daf62.png">

**Comment by msageryd** [comment]
Thanks.
Is Mojave something I can switch to somehow?

**Comment by huyphams** [comment]
Nah, it's newest macOS 10.14 but still in beta.
