### ISSUE TITLE
Show server version instead of driver version

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#477]
It seems that TP shows the driver version in the connection line. I'd rather see the server version. Maybe the driver version in parenthesis?

I went ahead and looked for some error in my Dockerfile, but it turned out that the server had the correct version (10.3). I was just mislead by the version info in TP.

![image](https://user-images.githubusercontent.com/4483085/41507763-c04d0eee-7239-11e8-8984-74303425f4ed.png)

**Comment by msageryd** [comment]
Update.
I'm confused. After connecting to another server both the other server and the recently connected local server now shows 10.3. The local server had 9.6 a couple of days ago, so it definitely seems like a cached string that needs refreshing upon reconnect.

**Comment by huyphams** [comment]
it's a rare case. You upgraded the docker while TablePlus still connecting to the server. TablePlus only refresh the version after reconnecting. 
I have fixed the bug, TablePlus now always refreshes server version. Thanks for the reporting.
