### ISSUE TITLE
Combine "New connection" and "Show connection" forms

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#478]
I'll add from start that think most of the GUI is awesome. Everything is thought out from a developers perspective. Love it.

I think having two different forms with almost the same functions is bad UX.

### cmd-N (New connection)
- Shows a list of connections
- Can create new connections
- Backup/Restore buttons (haven't tried them)
- Double-click on existing connection opens connection in new window

### cmd-shift-K (Show connections)
- Shows a list of connections
- Double-click on existing connection opens connection in new tab
- I can open in new window by selecting a connection and clicking "New window"

### Proposed solution:
- Use "New connection" for both use cases.
- Add buttons for selecting window/tab

Here is "New connection"
![image](https://user-images.githubusercontent.com/4483085/41507944-b97bc4c2-723c-11e8-875e-48b9a7a0079b.png)

 And here is "Show connections"
![image](https://user-images.githubusercontent.com/4483085/41507945-cbf01f2c-723c-11e8-8627-ce05c2937a6e.png)

**Comment by huyphams** [comment]
The reason I have put it into the menu because I received a lot of emails/issues asking for "How to open a connection/ How to create a connection..."
They asked because they couldn't figure out how to do it. Many users use `Help > Search` for the first time they used the application, so I put it into the menu as a shortcut.

<img width="381" alt="screen shot 2018-06-18 at 9 07 02 am" src="https://user-images.githubusercontent.com/3654622/41515169-06b1ca4e-72d7-11e8-8f97-76ec29b1e9e4.png">

**Comment by msageryd** [comment]
I see no problem with having it in the menu as well. My point is that there are two different dialogues with almost the same functions. There should be only one form imo. This form could be reachable from any number of places, such as menus, shortcuts, buttons..

**Comment by huyphams** [comment]
That can make more sense if I rename it to "Show the main screen". The main difference between two functions is you can use tabbed mode when pressing command+shift+K.

**Comment by msageryd** [comment]
..and double-click has different behaviour
..and backup restore buttons is only in one of the screens
..and you can only create new connections on one of them

I still think it would be easier to obtain a good UX with only one screen. The argument for having two screens does not hold up against the confusion when you accidentally find the other screen and it behaves differently.

Well, well. I have learned how it works, so it's no biggie for me now.
