### ISSUE TITLE
Feature request: Add space after autocomplete

### ISSUE THREAD

**Issue by davidolrik** [TablePlus/TablePlus#480]
When autocompleting a keyword like `SELECT` it would be super nice if the autocomplete would also include a space after the keyword, to save time when typing the next item.

If a space already exists after the autocompleted item, just move the cursor to after the space.

This will mimic the behaviour of auto complete in most code editors and make the autocomplete functionality much smoother to use.

**Comment by huyphams** [comment]
I just tried VS Code, Sublime Text 3 and Sequel Pro. All of them don't add a space after keywords. I didn't try to do it before but I think it weird behavior and not all users want (I assume that there are 50-50).
For example:
```
Select * from comments order id desc;
```
can become
```
Select * from comments order id desc ;
```
and it's not necessary.
So think, I can't add it.

**Comment by huyphams** [comment]
It will be included as an option in the next update!
