### ISSUE TITLE
Crash when deleting something in Redis

### ISSUE THREAD

**Issue by Oscarteg** [TablePlus/TablePlus#481]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
redis_version:3.0.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 110

3. The steps to reproduce this issue:
Open a connection to a Redis instance, ope table and delete a row

**Comment by huyphams** [comment]
I can't reproduce the bug, let me check the crash log.

**Comment by Oscarteg** [comment]
Where can I find it? The application just closes and doesn't give me a crash log. I can email you a screen capture of what happens if you want?

**Comment by huyphams** [comment]
Hi @Oscarteg, could you make a gif for me? and an other extra info is what OSX are you on?.
Thank you 👍

**Comment by Oscarteg** [comment]
I figured something out. The crash happens when the value is set to something with multiple lines. I'm not sure if this is a TablePlus bug or that Redis doesn't allow multi lines as values.

**Comment by huyphams** [comment]
Hi @Oscarteg I just updated and added double quote when key/value have multiple lines
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Could try this build above and let me know the result? Thank you.

**Comment by Oscarteg** [comment]
Unfortunately the same problem. Are you able to recreate it?

**Comment by huyphams** [comment]
Sadly, I can't reproduce it. Looks like it only happens in some special situation.

**Comment by Oscarteg** [comment]
When I open a connection with Redis and add a key (doesn't matter what key), add below as the value and save the app shutdown. 

```json
{
    "testing": "testing"
}
```

Maybe now you can reproduce it.
