### ISSUE TITLE
Suggestion: cmd-T for new tab should always open a new query tab

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#482]
1. Open up a query tab (cmd-enter)
2. You want another query-tab so you press cmd-T
3. You also have to press cmd-enter in the new tab in order to make it a "query tab"

Step 3 is not needed IMO. Also, I'm not so sure about this cmd-enter to get a query tab. cmd-enter also executes the active sql command if you are in a query tab. This could get people in dangerous situations if they try to open a query tab and don't remember they are in such a tab already. This could result in execution of an sql command instead of opening a new tab.

**Suggested solution:**
Cmd-T should always give a new query tab, from wherever I am in TablePlus.
Cmd-Enter should be dedicated for running sql commands

BTW, I love the way TB works when running commands with cmd-enter. Highlighting the active sql command automatically is genius. It also forces me to not forget the semicolon, which otherwise could bite me when the query is pasted into my upgrade script.

**Comment by huyphams** [comment]
- Command + T is open an empty now has a purpose so I think I will not change it. (Open new empty tab then click to item => TablePlus will open that item on the tab and will not navigate to the exist so you can open 1 item in multiple tabs, this also works if you open with the middle mouse or using the menu).
and the next update will include this feature.

- Command + Enter now run SQL Commands.

**Comment by msageryd** [comment]
I understand your reasoning.

The concept of opening a function, tigger, etc in a view where cmd-S will replace the current version of this function is troublesome for me. I'll call this kind of tab for "edit object tab" below.

IMO, databases should be built by scripts to ensure repeatability of the changes in other environments (development, staging, production). To be able to just open an object and save it as a new version contradicts this.

I would really love if you'd create a setting to enforce a more strict scripting approach. It would:
1. Always open objects in SQL tabs
2. New tabs should always be SQL tabs

If I want to alter an object I almost always do this within a transaction along with some test INSERTS to try out the new behaviour of the object (function, trigger, etc). I always roll back these changes. When I'm satisfied I copy the script to a version handling script runner for upgrading staging and production environments. The enclosing transaction and the test data is not possible to achieve in the "edit object tab", so I usually open a function, copy the code and paste it into an SQL tab.

Am I alone to treat database structures in a strictly scripted way? I hope not. I think many with me would like a "strict scripting setting" in TP.

NB. Sorry for giving you a hard time with this. I'm only doing it because I love all other aspects with TP. TP has become an important tool to me.

**Comment by huyphams** [comment]
The design cannot satisfy all users, so I think the best solution is making an option where you can turn it on. 
But the real reason why I want it to be empty because it made sense, they know it can replace it with other items.

**Comment by davidharrison92** [comment]
Hi @huyphams 

I think this would be a great feature to have. I notice that key-mappings are something "coming soon". 

![screenshot 2019-02-19 at 11 06 35 am](https://user-images.githubusercontent.com/3440843/53010717-870a7a80-3436-11e9-982b-f85008fbb109.png)


This would be a great place to map ⌘ + T to "Open SQL Editor", the same as clicking the SQL button above the object list does now.

![screenshot 2019-02-19 at 11 07 26 am](https://user-images.githubusercontent.com/3440843/53010730-8d98f200-3436-11e9-91f8-de66c32f51cb.png)

Do you have any idea if/when this is likely to be included?

Regards,
Dave

**Comment by huyphams** [comment]
Sure @davidharrison92 many users have requested it so I will put an option into the preferences.

**Comment by huyphams** [comment]
TablePlus will open SQL Query with Command + T in the next update!

**Comment by eysikal** [comment]
@huyphams Just some feedback that I was pretty confused by the new behavior opening a SQL Query tab by default. I mostly use TablePlus to look through tables, so it doesn't make sense for me to want to be writing queries all the time. I thought I had inadvertently changed some setting. Glad I was able to figure out I could switch it back.
