### ISSUE TITLE
XML field causes dbbind error

### ISSUE THREAD

**Issue by tylerrasor** [TablePlus/TablePlus#483]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQLServer 2017

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
110

3. The steps to reproduce this issue:
`CREATE TABLE test (id INT, testField XML);`
`SELECT * FROM test;`
Aggregate functions seem to work:
`SELECT COUNT(*) FROM test;`

**Comment by huyphams** [comment]
Hi @tylerrasor I fixed this bug on this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for the reporting.
