### ISSUE TITLE
Copy column values as select in statement

### ISSUE THREAD

**Issue by BigAirJosh** [TablePlus/TablePlus#484]
I previously used Squirrel which has a copy to clipboard feature where one can select a single column from the result table and copy as a new line delimited list.  There is also a very useful option to copy as a select in block, where the values are added to the clip board as comma delimited, quoted values wrapped in brackets.

I use this feature all the time, since switching to TablePlus (which I love by the way) I am missing this most of all.  Now I have to export to a file and use an Emacs macro to format.

build (110)

**Comment by huyphams** [comment]
I understand your case, it's a great idea. I will try to implement it.
