### ISSUE TITLE
"Run all" in the SQL query view creates a tab for comments in the query

### ISSUE THREAD

**Issue by coisnepe** [TablePlus/TablePlus#485]
1.Driver : PG 9.6.8
2.TablePlus build number: 110
3. The steps to reproduce this issue:
	- Open an 'SQL Query' Tab
	- Write a normal query, ended with a semi-colon
	- On a newline, write a single comment
	- 'Run All' to execute all queries

Expected: a single results tab is opened
Actual: two tabs are opened: one with the query results, and a blank one.

![image](https://user-images.githubusercontent.com/13304454/41705588-b7d9c2b8-7539-11e8-80e0-9b55d8295e87.png)

**Comment by javierecf** [comment]
I tried to replicate this in the current build 2.0(200) and its looks solved, at least for SQL Server.
