### ISSUE TITLE
Support for mysql Pointers

### ISSUE THREAD

**Issue by alnorris** [TablePlus/TablePlus#487]
Mysql 5.7

110

Point data types show EMPTY, instead of the points.  Eg. `coordinates` point NOT NULL,

TablePlus
![image](https://user-images.githubusercontent.com/882627/41716167-7987f278-754d-11e8-8a8c-c79e52ea2113.png)

Sequal Pro
![image](https://user-images.githubusercontent.com/882627/41716170-7cd036ac-754d-11e8-9923-ba912d03a184.png)

**Comment by huyphams** [comment]
Sure @alnorris, we will support it, let me see.

**Comment by huyphams** [comment]
Hi @alnorris it's supported now: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
