### ISSUE TITLE
The best database client I've ever tried!

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#489]
This is not an issue, but I thought I'd leave it here anyway if others are considering TablePlus.

I've worked with RDBMs since 1998, SQL Server, (MongoDB), PostgreSQL. I've also been through countless database clients in an endless hunt for the perfect client. TablePlus will probably be perfect very soon, with the speedy development going on.

I'm already in love with TablePlus, because:
- speed (incredible speed compared to other clients)
- beauty
- well thought out UI (I find myself working a lot faster in TP than in other clients)
- fast response to issues

Keep up the good work. I will for sure be a loyal user.

**Comment by alvint** [comment]
Probably a better idea is to star the project on GitHub. I know I rely on the number of times a project has been starred when deciding which projects to take a closer look at.

**Comment by brunolemos** [comment]
Which one is the best for MongoDB?

**Comment by eberkund** [comment]
I especially like the Sublime-eque command palette and keyboard shortcuts. I am hoping to see this feature expanded on even more in the future with making everything accessible this way.

**Comment by haroldrandom** [comment]
Already buy a license to support.
Looking forward to more stable furtures

**Comment by IngenieroLata** [comment]
> Already buy a license to support.
> Looking forward to more stable features

So do I (specially mongo support) 😃

**Comment by joshhopkins** [comment]
TablePlus really is a fantastic app 👌🏼

**Comment by AndreFigueredo-Multilaser** [comment]
Hey guys, anyone can help me?

I'm try to run simple commands, but all returns this error and I don't know why.
Any ideas?

`db.createCollection("cars");`

> Query 1 ERROR: Got parse error at "d", position 0: "SPECIAL_EXPECTED"

**Comment by huyphams** [comment]
Hi @AndreFigueredo-Multilaser please create another issue for it, it related to Mongo driver.
The Mongo-Shell which is not supported at the moment so there is no way to run mongo shell. We're working on it.

**Comment by JohnnyWalkerDesign** [comment]
I can't believe someone praising the UI. It's a brilliantly solid app, and I use it every day, but the UI/UX is severely lacking :(

**Comment by Sunhat** [comment]
The UX is awful. The tab system is awful. The tab system was introduced as a way to add a pay wall. When I click between tables and new tabs open then a message harassing me to pay for their software comes up. I'm not paying for it because of the tab system that was introduced exclusively as a way to harass people to pay.
