### ISSUE TITLE
TablePlus crashes after trying to close a SQL Query window with many sub-tabs.

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#49]
When executing a fairly large query I get over 50 SQL query sub-tabs (as can be seen below).  

![screen shot 2017-08-17 at 11 36 14 am](https://user-images.githubusercontent.com/7946786/29427944-4bf65ae8-8340-11e7-9b6f-2cc773851909.png)

This is in and of itself a big issue but upon closing theSQL Query window, using ?+W, the app crashes.  I imagine this is due to the size of the query.

See below animated .gif.  @huyphams, is it true that all App Crashes are logged via an API?  just curious.

![2017-08-17 12_04_23](https://user-images.githubusercontent.com/7946786/29429084-3a288cc4-8344-11e7-81cb-c3d912359f0d.gif)

Below I've provided the Query I ran, obfuscating important technical details.

> ALTER TABLE EE.EE ADD COLUMN RawHide_tail_id bigint, ADD COLUMN profile_tail_id bigint;
CREATE SEQUENCE dog.tail_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE dog.tail_seq
  OWNER TO mustard;
GRANT ALL ON TABLE dog.tail_seq TO mustard;
GRANT SELECT ON TABLE dog.tail_seq TO pgadmin;
GRANT SELECT ON TABLE dog.tail_seq TO readonly;
GRANT ALL ON TABLE dog.tail_seq TO mustard_user;
GRANT SELECT, USAGE ON TABLE dog.tail_seq TO hadoop_reader;
GRANT ALL ON TABLE dog.tail_seq TO skyCloud;
GRANT SELECT, USAGE ON TABLE dog.tail_seq TO dw_reader;
GRANT SELECT, USAGE ON TABLE dog.tail_seq TO animal_skyCloud;
GRANT SELECT, USAGE ON TABLE dog.tail_seq TO batch_user;
GRANT SELECT, USAGE ON TABLE dog.tail_seq TO automation_user;
GRANT SELECT, USAGE ON TABLE dog.tail_seq TO Toot;
GRANT SELECT, USAGE ON TABLE dog.tail_seq TO oc_user;
CREATE TABLE dog.tail
(
  d2 bigint NOT NULL DEFAULT nextval('dog.tail_seq'::regclass),
  d2tity_id bigint NOT NULL,
  d2tity_type_id integer,
  d2rst_DDDD character varying(255),
  d2st_DDDD character varying(255),
  d2dre1 character varying(255),
  d2dr2 character varying(255),
  d2stDDDD character varying(24),
  d2untry_id integer,
  d2ty character varying(64),
  d2ate_id integer,
  d2ectronic_DDDD character varying(1000),
  d2dress_type_id integer NOT NULL,
  d2dress_DDDD character varying(50),
  d2ganizaDDDD character varying(512),
  d2cipient_type_id integer NOT NULL,
  d2stal_barDDDD character varying(255),
  d2ymd_id integer NOT NULL,
  d2eats timestamp with time zone NOT NULL,
  d2di timestamp with time zone NOT NULL,
  d2_creas timestamp with time zone DEFAULT now(),
  d2_modis timestamp with time zone DEFAULT now(),
  d2stDDDD character varying(64),
  d2w_status_id integer NOT NULL DEFAULT 1,
  d2eferred_RawHide_currency_type_id integer,
  d2cord_DDDD character varying,
  d2urce_ip_KK inet,
  d2urce_couKK text,
  d2owser_langKK text,
  d2notcontact_directmail boolean,
  CONSTRAINT pk_tail_id PRIMARY KEY (id))
  WITH (
  OIDS=FALSE
);
ALTER TABLE dog.tail
  OWNER TO mustard;
GRANT ALL ON TABLE dog.tail TO mustard;
GRANT SELECT ON TABLE dog.tail TO pgadmin;
GRANT SELECT ON TABLE dog.tail TO readonly;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE dog.tail TO mustard_user;
GRANT SELECT ON TABLE dog.tail TO hadoop_reader;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE dog.tail TO skyCloud;
GRANT SELECT ON TABLE dog.tail TO dw_reader;
GRANT SELECT, UPDATE, INSERT ON TABLE dog.tail TO animal_skyCloud;
GRANT SELECT, UPDATE, INSERT ON TABLE dog.tail TO batch_user;
GRANT SELECT, UPDATE, INSERT ON TABLE dog.tail TO automation_user;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE dog.tail TO Toot;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE dog.tail TO oc_user;
CREATE SEQUENCE RawHide.RawHide_tail_seq;
ALTER TABLE RawHide.RawHide_tail_seq OWNER TO mustard;
GRANT ALL ON SEQUENCE RawHide.RawHide_tail_seq TO mustard;
GRANT ALL ON SEQUENCE RawHide.RawHide_tail_seq TO Toot;
GRANT SELECT ON SEQUENCE RawHide.RawHide_tail_seq TO pgadmin;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO animal_skyCloud;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO Toot;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO animal_user;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO skyCloud;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO batch_user;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO automation_user;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO hadoop_reader;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO shopular;
GRANT SELECT, USAGE ON SEQUENCE RawHide.RawHide_tail_seq TO mustard_user;
CREATE TABLE RawHide.RawHide_tail
(
  d2 bigint NOT NULL DEFAULT nextval('RawHide.RawHide_tail_seq'::regclass),
  d2yment_id bigint NOT NULL,
  d2mber_id bigint NOT NULL,
  d2rst_DDDD character varying(255),
  d2st_DDDD character varying(255),
  d2dress1 character varying(255),
  d2dress2 character varying(255),
  d2stDDDD character varying(24),
  d2untry_id integer,
  d2ty character varying(64),
  d2ate_id integer,
  d2ectronic_DDDD character varying(1000),
  d2dress_type_id integer,
  d2cipient_type_id integer,
  d2dress_DDDD character varying(50),
  d2_created_ts timestamp with time zone DEFAULT now(),
  d2_modified_ts timestamp with time zone DEFAULT now(),
  d2eferred_RawHide_currency_type_id integer,
  CONSTRAINT pk_RawHide_tail_id PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RawHide.RawHide_tail
  OWNER TO mustard;
GRANT ALL ON TABLE RawHide.RawHide_tail TO mustard;
GRANT SELECT ON TABLE RawHide.RawHide_tail TO pgadmin;
GRANT SELECT ON TABLE RawHide.RawHide_tail TO readonly;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE RawHide.RawHide_tail TO mustard_user;
GRANT SELECT ON TABLE RawHide.RawHide_tail TO hadoop_reader;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE RawHide.RawHide_tail TO skyCloud;
GRANT SELECT ON TABLE RawHide.RawHide_tail TO dw_reader;
GRANT SELECT, UPDATE, INSERT ON TABLE RawHide.RawHide_tail TO animal_skyCloud;
GRANT SELECT, UPDATE, INSERT ON TABLE RawHide.RawHide_tail TO batch_user;
GRANT SELECT, UPDATE, INSERT ON TABLE RawHide.RawHide_tail TO automation_user;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE RawHide.RawHide_tail TO Toot;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE RawHide.RawHide_tail TO oc_user;
CREATE INDEX ix_RawHide_tail_dog_id
  ON RawHide.RawHide_tail
  USING btree
  (dog_id);
CREATE INDEX ix_RawHide_tail_RawHide_id
  ON RawHide.RawHide_tail
  USING btree
  (RawHide_id);
CREATE TRIGGER tg_RawHide_tail_update_db_modified_ts
  BEFORE UPDATE
  ON RawHide.RawHide_tail
  FOR EACH ROW
  EXECUTE PROCEDURE RawHide.fc_set_last_modified();

**Comment by huyphams** [comment]
Yup, this is the big issues. thank you @brian-crane

**Comment by brian-crane** [comment]
@huyphams Now I see what 'Split Result' setting is for.  This is a good solution for now thanks again.

**Comment by huyphams** [comment]
The crash bug was fixed. @brian-crane, new update will be released in the end of this month.

**Comment by huyphams** [comment]
Hi @brian-crane could you checkout this pre-release build, this build will be official released at the end of this month.
Features added:
- New open anything.
- Bugs fixes.
- Query Progress Bar.
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
