### ISSUE TITLE
MySQL Can't create connection

### ISSUE THREAD

**Issue by triggert** [TablePlus/TablePlus#490]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.6.34

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 110

3. The steps to reproduce this issue: Connecting over SSH to AWS RDS MySQL instance on port 3306.  Same connection works over DBeaver.

<img width="496" alt="screen shot 2018-06-21 at 4 04 12 pm" src="https://user-images.githubusercontent.com/12851159/41745552-e83f44f4-756c-11e8-9e5e-f5352643ee50.png">

<img width="477" alt="screen shot 2018-06-21 at 4 05 42 pm" src="https://user-images.githubusercontent.com/12851159/41745573-f89fe844-756c-11e8-9765-d1f06bf71b0d.png">

**Comment by huyphams** [comment]
It's fixed, now TablePlus reports more information about the error.
