### ISSUE TITLE
Be able to export database connection settings from group

### ISSUE THREAD

**Issue by eleijonmarck** [TablePlus/TablePlus#491]
![image](https://user-images.githubusercontent.com/7727602/41765754-51ebeb76-7605-11e8-8b7a-f00b5ecbd265.png)

I would like an option to export the groups connection settings to my colleague as we have alot (and i mean alot) of connections. So a new hire would come in and get all the connections straight up.

**Comment by huyphams** [comment]
Sure @eleijonmarck, I will list this in next release feature.

**Comment by huyphams** [comment]
It's released @eleijonmarck

**Comment by huyphams** [comment]
Hi @eleijonmarck due to some issue i need to verify, you can download the build which supports the export function here: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by eleijonmarck** [comment]
@huyphams sorry I did not see this until now.

Do you need testing? I am actually testing to export my connections to one of my colleagues as we speak.

**Comment by huyphams** [comment]
Hey, it's released on production already 👍

**Comment by eleijonmarck** [comment]
@huyphams It worked great. We had to make a new group for the `import` button to work.
