### ISSUE TITLE
TimeUUID data shows as null

### ISSUE THREAD

**Issue by getmetorajesh** [TablePlus/TablePlus#493]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
111

3. The steps to reproduce this issue:
value for TIMEUUID data type in GUI shows up null whereas cqlsh shows the timeuuid value correctly.

**Comment by huyphams** [comment]
Thanks for the reporting. I will be fixed in next update. Have a nice weekend.

**Comment by huyphams** [comment]
I have a quick fix on the build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0 Now it can load timeuuid field.
