### ISSUE TITLE
Table builder adding Foreign Keys?

### ISSUE THREAD

**Issue by mathewtrivett** [TablePlus/TablePlus#494]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 10.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 111

3. The steps to reproduce this issue: 

Noted: If the bug is related to data, please attach an example SQL data.
------
I want to use Table Plus to do some internal teaching to designers in my company on database design. How can I go about adding foreign keys constraints using the table builder interface with TablePlus Free?

**Comment by huyphams** [comment]
Hi @mathewtrivett you can create a foreign key by this popup:
<img width="1159" alt="screen shot 2018-06-24 at 6 28 30 pm" src="https://user-images.githubusercontent.com/3654622/41818597-724f934e-77dc-11e8-9e3a-f3bf52a44c59.png">

**Comment by huyphams** [comment]
it's available for all the build, but you can only create foreign key after creating a table.
