### ISSUE TITLE
Editing a sql server view creates no script

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#495]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ayalbelling** [comment]
v1.0 (111), MS Sql Server. Try CREATE VIEW TestView AS SELECT * FROM whatevertable. Once created, edit it and under structure. No script created so cannot edit.

**Comment by huyphams** [comment]
Thanks @ayalbelling, I just fixed it, it will be available in the next update.
