### ISSUE TITLE
Add Precision and Scale information to Numeric fields in PostgreSQL

### ISSUE THREAD

**Issue by ashishwadekar** [TablePlus/TablePlus#497]
Kindly add precision and scale for numeric columns.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 9.6.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 111

Sharing screenshot:
<img width="639" alt="ashish wadekar postgresql 9 6 6 2018-06-25 16-34-23" src="https://user-images.githubusercontent.com/13130213/41846913-e36af532-7895-11e8-9822-339bbf2e41c7.png">

**Implementation suggestion in sidebar:**

<img width="101" alt="ashish wadekar suugestion sidebar 2018-06-25 16-37-45" src="https://user-images.githubusercontent.com/13130213/41847068-699bdb3a-7896-11e8-8129-8948c2abc0e1.png">

Information can be displayed in Main table structure as **numeric(9,2)** if precision is 9 & scale is 2.

Cheers,
Ashish

**Comment by huyphams** [comment]
Hey sure @ashishwadekar we will support it.

**Comment by ashishwadekar** [comment]
@huyphams Thanks for the quick response. Eagerly waiting for this feature to be pushed 😇

**Comment by huyphams** [comment]
Hi @ashishwadekar it's supported in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by ashishwadekar** [comment]
Hi @huyphams 
Thanks for the swift action 🙌
It is now visible in the sidebar when viewing the record. Sharing screenshot:
<img width="222" alt="screen shot 2018-06-27 at 12 22 33 pm" src="https://user-images.githubusercontent.com/13130213/41957588-14afea06-7a05-11e8-917f-603891fa9298.png">

Can also add the same information to main table structure page as follows:
<img width="464" alt="precision scale on table structure 2018-06-27 12-26-20" src="https://user-images.githubusercontent.com/13130213/41957727-7c66fa2c-7a05-11e8-8c1e-23facbb79000.png">
This helps a lot while designing future tables based on similar functionality.

Cheers,
Ashish

**Comment by huyphams** [comment]
Ah sure, I forgot to add it into table's structure and definition tab.

**Comment by huyphams** [comment]
It's done: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
I also added the length for varchar in the right panel.
<img width="286" alt="screen shot 2018-06-27 at 3 00 12 pm" src="https://user-images.githubusercontent.com/3654622/41960829-f4e300ee-7a1a-11e8-8fb7-3d5bb19eb37c.png">

**Comment by huyphams** [comment]
I figured out that if you are not specific varchar length, it will show -1 (as max length). I hide it in the future update if the value is -1. Thanks for the reporting.

**Comment by ashishwadekar** [comment]
Sure! That will be great because **-1** raises a lot of questions 😝

**Comment by huyphams** [comment]
I'm pretty sure this build fixes all the issues: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
🙈🙈🙈Thanks for taking your time testing with me.

**Comment by ashishwadekar** [comment]
Yay! This fixes all the issues.
Thanks for the quick response. It was fun testing and making it better.

Have a great day ahead.

Cheers,
Ashish

P.S. You can close the issue.
