### ISSUE TITLE
Can't connect to MySQL 5.6.24 via password any more after upgrading to build 112

### ISSUE THREAD

**Issue by litao91** [TablePlus/TablePlus#498]
I can't connect to MySQL after upgrading build 112, prompting the error:

`Access denied for user '<user>'@'<ip>' (using password: YES)`

It works find before upgrading. 

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.24-72.2
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 112 
3. The steps to reproduce this issue:
Connect to the MySQL
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I have tested it and it's working. Could you try to re-fill the database password again?

<img width="1138" alt="screen shot 2018-06-26 at 12 01 29 pm" src="https://user-images.githubusercontent.com/3654622/41890234-c393f166-7938-11e8-8499-be52e51c33e0.png">

**Comment by litao91** [comment]
@huyphams No, it doesn't work.

**Comment by huyphams** [comment]
Thanks @litao91 while we're investigating you can rollback to the 111 build here: https://tableplus.io/blog/2017/02/changelogs.html

**Comment by litao91** [comment]
@huyphams It also works fine if I use the mysql command (the [mycli](https://github.com/dbcli/mycli)):

```bash
mycli -u <user-name> --password=<password> -h <host> --port <port>
```
I'm pretty sure that my ip, port and password are correct. 

![wx20180626-131025](https://user-images.githubusercontent.com/1422365/41890523-72c197f2-7942-11e8-8397-e899f2bdfe91.png)
![wx20180626-131219](https://user-images.githubusercontent.com/1422365/41890556-9759a01e-7942-11e8-85bd-31666a692b05.png)

**Comment by litao91** [comment]
Well, everything works after rolling back to 111, with zero config change made. 

![wx20180626-131808](https://user-images.githubusercontent.com/1422365/41890750-7e07c0e0-7943-11e8-9691-ac471edba288.png)

**Comment by huyphams** [comment]
Hey @litao91 I added a new version which supports both MySQL 8 and MySQL 5 
Download: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

<img width="612" alt="ver" src="https://user-images.githubusercontent.com/3654622/42012803-348a093c-7ac4-11e8-9fae-6a9de69c53e3.png">

**Comment by litao91** [comment]
@huyphams It works like a charm. Thanks for the quick response, it's the best support I've ever had.
