### ISSUE TITLE
MySQL Access denied

### ISSUE THREAD

**Issue by triggert** [TablePlus/TablePlus#502]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.34

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 112

3. The steps to reproduce this issue:
Connecting to AWS RDS MySQL 5.6.34 instance over SSH bastion using % as the host.  Tested working with DBeaver.

`Access denied for user 'username'@'bastion_ip' (using password: YES)`

**Comment by triggert** [comment]
Referencing https://github.com/TablePlus/TablePlus/issues/498 to test.

**Comment by huyphams** [comment]
Hi @triggert while this is an issue of MySQL 8 driver and we are investigating it, can you try the early build here: https://tableplus.io/osx/changelog
I believe the build 111 will work.

**Comment by triggert** [comment]
Thanks for the quick response.  Reverting to build 111 results in the previously reported "Can't create connection" issue from https://github.com/TablePlus/TablePlus/issues/490

**Comment by huyphams** [comment]
Thanks @triggert, I'm creating a Amazon RDS instance for testing now.

**Comment by huyphams** [comment]
I created an instance AMZ RDS MySQL 5.6.34 but can't reproduce the bug. How did you create the user which is using for login? I'm using root but it works.
<img width="1125" alt="screen shot 2018-06-26 at 11 18 25 pm" src="https://user-images.githubusercontent.com/3654622/41925640-5a4b8412-7997-11e8-9493-5601eba52705.png">

**Comment by huyphams** [comment]
Here is mine: 
<img width="612" alt="screen shot 2018-06-26 at 11 21 12 pm" src="https://user-images.githubusercontent.com/3654622/41925737-a479690a-7997-11e8-9a8f-7fd6a4c06092.png">

**Comment by triggert** [comment]
Thanks, the MySQL connection looks the same except we're going over SSH bastion.

**Comment by huyphams** [comment]
I can reproduce now but looks like it's not the same. In my case, TablePlus hangs on the connection screen (because it waiting for the connection over SSH).
<img width="612" alt="screen shot 2018-06-26 at 11 49 20 pm" src="https://user-images.githubusercontent.com/3654622/41927145-903a28d6-799b-11e8-86b8-51d45e98a36d.png">
I will try to fix it, thank you @triggert

**Comment by triggert** [comment]
Thanks - I also created another MySQL 5.6.34 RDS test instance and was able to connect over ssh.

I'll try to narrow down what might be causing issues on our Production instances.

**Comment by huyphams** [comment]
Hey @triggert can you try this build: https://www.dropbox.com/s/i3sgj3zem6zjnwx/TablePlus.zip?dl=0
With that server and let me know the result? Thanks.

**Comment by huyphams** [comment]
TablePlus supports both MySQL 8 and 5.X in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

<img width="612" alt="ver" src="https://user-images.githubusercontent.com/3654622/42012835-687788b4-7ac4-11e8-9ad6-946a61d2f6b0.png">

Thanks for the reporting.
