### ISSUE TITLE
Syntax error (PostgreSQL)

### ISSUE THREAD

**Issue by madebyherzblut** [TablePlus/TablePlus#503]
In our server logs I noticed syntax errors as soon as someone from our team connected with TablePlus:

```
sql_error_code = 42601 STATEMENT:  select reltuples::int8 as count from pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace where nspname=''public''AND relname='tenants'; 
```

```sql
select reltuples::int8 as count from pg_class c JOIN pg_catalog.pg_namespace n ON
n.oid=c.relnamespace where nspname=''public''AND relname='tenants'; 
```

The syntax error is caused by the extra quotes around the `public` schema. I think this is related to #43. The option "Estimate count when table has more than x rows" is enabled.

I am using Version 1.0 (112) and connect to PostgreSQL 10.3.

**Comment by huyphams** [comment]
Hey thanks @madebyherzblut let me check it.

**Comment by huyphams** [comment]
Hi @madebyherzblut I fixed the estimate row bug: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thank you so much 🙌

**Comment by madebyherzblut** [comment]
Wow, that was fast! I can confirm that the bug is fixed. Thank you for the amazing work on TablePlus 👍
