### ISSUE TITLE
Bad Handshake when connecting to certain MySQL Hosts

### ISSUE THREAD

**Issue by gerricom** [TablePlus/TablePlus#504]
First: TablePlus is awesome! It made so much things easy for me in my daily life! Thank you!

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.1.73 on CentOS 6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

112

3. The steps to reproduce this issue:

I'm using the german project uberspace.de as hosting provider for some of my projects. They are offering the default MySQL 5.1.73 on their CentOS6 Hosts. 
When I start a connection with TablePlus I get an error saying "Bad Handshake" (by the way: This error modal is huge. I mean - really huge!)
This error occurs to me since build 112 but I'm not totally sure, when was the last time I connected to one of those hosts. Sequel Pro is connecting fine.

I think, you could test it for yourself on one of their hosts if you visit <https://uberspace.de/register>, tick **off** Uberspace 7 (with this checkbox checked you would get an CentOS 7 with an updated MariaDB) and give yourself a fancy username. Short while after, you should be able to insert your public ssh key and go for it.

**Comment by huyphams** [comment]
Hi @gerricom this because MySQL < 5.1 uses old protocol (which is not supported by TablePlus at the moment).
I will investigate more to see if we can support it soon.
Btw, there are old builds here (you can try the early build in case you not sure the previous build is working or not): https://tableplus.io/osx/changelog

**Comment by gerricom** [comment]
Thanks for that swift response! Build 111 is working fine for me!

**Comment by huyphams** [comment]
I forgot to mention that you can resize the error popup, and it will remember the size in the future.

**Comment by huyphams** [comment]
Hi @gerricom I added a dropdown as a temporary solution
<img width="612" alt="ver" src="https://user-images.githubusercontent.com/3654622/42012771-feb81844-7ac3-11e8-8ba2-7d62afabfb59.png">
Download: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
This is clearly MySQL bug, ref: https://bugs.mysql.com/bug.php?id=90994
