### ISSUE TITLE
Enhancement - Tabs location

### ISSUE THREAD

**Issue by vyscond** [TablePlus/TablePlus#505]
I believe the best place to put the tabs are at the bottom. Lot more space to display the labels. Besides that everything seems to be good :)

Thanks for the app.

**Comment by huyphams** [comment]
The reason we put the tabs on the top because we want to avoid some unexpected behaviors in fullscreen mode. The most annoying behavior is when you drag the mouse to the bottom, it triggers showing the Dock.

**Comment by huyphams** [comment]
![2018-06-28 16 02 11](https://user-images.githubusercontent.com/3654622/42024546-a356d9a8-7aec-11e8-9008-34483d61ac98.gif)

**Comment by vyscond** [comment]
I see. That's a good UX point indeed. But for me i am seen the tabs on the left side of the main window instead of the top. Am i missing some configuration setting?

**Comment by huyphams** [comment]
Did you mention about the database tab? Yup, we have a plan to refactor it in the future release due to some UI/UX limitations.
<img width="1315" alt="abc" src="https://user-images.githubusercontent.com/3654622/42032663-7dc4b314-7b04-11e8-86c8-259d31b8deb9.png">

**Comment by vyscond** [comment]
Yup. Sorry for the confusion. Indeed i was talking about the Database tabs. Thanks for the clarifications.
