### ISSUE TITLE
Foreign keys associated with incorrect fields (ms sql)

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#507]
v1.0 (112), MS SQL. When there are two or more foreign keys on a table referencing the same FK table, then when deleting them individually it sometimes deletes the wrong one - i.e. it seems the FK name in the script delete is picking the wrong field's FK in this situation.

**Comment by huyphams** [comment]
Good catch, let me check it.

**Comment by huyphams** [comment]
It's fixed in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0.
Thanks for reporting
