### ISSUE TITLE
Group import not works correctly

### ISSUE THREAD

**Issue by ToBee94** [TablePlus/TablePlus#508]
1. Which driver are you using and version of it:  n. a.

2. Which TablePlus build number are you using: Build 112

3. The steps to reproduce this issue: Import an exported Group with Connections

BUG: When I import an exported group with connections, the group is not added and the connections are added as ungrouped.

**Comment by huyphams** [comment]
This is an expected behavior. Currently, TablePlus only imports connections from the export file.
Btw, import group is a good idea.
