### ISSUE TITLE
Reset to first page on search feature.

### ISSUE THREAD

**Issue by hariesnurikhwan** [TablePlus/TablePlus#51]
Steps to reproduce.
1. Choose any table. Dont select any row.
2. Use search feature and search something like user_id=2.
3. Go to next few pages.
4. Try select any row. The result will be reset to the first page.

**Comment by huyphams** [comment]
yeah, I got this bug, thank you

**Comment by huyphams** [comment]
Hi @hariesnurikhwan please checkout new build:
Features added:
- New open anything.
- Bugs fixes.
- Query Progress Bar.
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by hariesnurikhwan** [comment]
Cool @huyphams. The issue is fixed!
