### ISSUE TITLE
Export all tables/schema in SQL

### ISSUE THREAD

**Issue by weyert** [TablePlus/TablePlus#511]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgresSQL 9.6.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 112

I think it would be great to be able to dump or export table content in SQL format so it's easily archivable. Currently, you have to do for each table separately.

**Comment by weyert** [comment]
Ah, looks like you might be able to do it via Backup and then choose --format=plain in the options list

**Comment by huyphams** [comment]
Related to: https://github.com/TablePlus/TablePlus/issues/418
