### ISSUE TITLE
Changing an existing column default constraint to NULL fails (MS SQL)

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#512]
MS SQL, v1.0 (113). Script uses ADD DEFAULT NULL rather than dropping the constraint. Also doesn't delete a column with default constraint because it doesn't drop the constraint first.

**Comment by huyphams** [comment]
It's supported now: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for reporting.
