### ISSUE TITLE
[UX] need more recently table

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#513]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
* Mysql5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* Build113

3. The steps to reproduce this issue:
* open more than five table. TablePlus only records five recently table. can you increase this to ten or more?
![image](https://user-images.githubusercontent.com/5211881/42154897-82e8a0ae-7e19-11e8-832d-1b6a1811ce38.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Sure @bulletRush I will add an option allow to config the number of recent items.
