### ISSUE TITLE
Feature Request: Support ~/.ssh/ssh_config

### ISSUE THREAD

**Issue by ToBee94** [TablePlus/TablePlus#514]
It would be nice if the ~/.ssh/ssh_config would be supported to use default connection data to connect over ssh with keys, user and port and shorter Hostnames

For example:
```
Host *
        UseKeychain yes
        AddKeysToAgent yes
        IdentityFile ~/.ssh/id_rsa

Host build
        HostName build.devserver.com
        User root
        Port 4112
```

**Comment by huyphams** [comment]
Hi @ToBee94 it’s already supported by TablePlus, you need to check the use ssh key box.

**Comment by ToBee94** [comment]
okay last time it doesn't worked but now...
next time I should read better

thanks 👍
