### ISSUE TITLE
Feature request : UI polish - Foreign key links

### ISSUE THREAD

**Issue by windware** [TablePlus/TablePlus#516]
1. Which driver are you using and version of it : MySQL 8

2. Which TablePlus build number are you using : 113

* I'd like the foreign key marker to be easier to navigate, preferably by a single click on the arrow.

Currently, it's not so easy to get to the foreign key item as it's not clear if I should single or double click the arrow next to the value to get the popup and then click on the popup cell to get to the foreign key item, which is a bit tedious compared to how it's implemented in Sequel Pro which is just a single click on the arrow.

Sequel Pro

![sequelpro-foreign-key](https://user-images.githubusercontent.com/4352236/42235513-f239043e-7f32-11e8-9dd0-3bbbfa3b6502.png)

TablePlus

![tableplus-foreign-key](https://user-images.githubusercontent.com/4352236/42235514-f25e11ca-7f32-11e8-8f0c-bb0e82677b23.png)

**Comment by huyphams** [comment]
You can quickly access to foreign key link by hold option + Click. We need to add a dropdown because TablePlus support multiple foreign keys (the column can link to two or more tables at the same time).
The only thing we can consider is if there is only one link, we can go to the link directly (without popup.)

**Comment by huyphams** [comment]
I did a little bit change based on your comparison. Now the new UX is:
1. If you click on the icon (the arrow, the brackets), TablePlus will show menu directly (the old UX requires the second click.)
2. If there is only one link (Column has only one foreign key), TablePlus will go to the link directly (the old UX requires the second click and select on the drop-down).
Download: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by huyphams** [comment]
This update also fixes the issue https://github.com/TablePlus/TablePlus/issues/518 so I will close the 518

**Comment by windware** [comment]
Awesome! Thank you!
