### ISSUE TITLE
Feature request : UI polish - Menu activation

### ISSUE THREAD

**Issue by windware** [TablePlus/TablePlus#518]
1. Which driver are you using and version of it : MySQL 8

2. Which TablePlus build number are you using : 113

* When you click on the menu icon in various fields, it's not easy to trigger it as double clicking will trigger editing the value, instead I have to give it a small break between clicking to trigger the menu, which is a bit tedious.

I suggest the menu to open even if the row was not focused first when clicking on the menu icon.

![tableplus-menu1](https://user-images.githubusercontent.com/4352236/42236565-372b909a-7f36-11e8-9527-5909983d67bb.png)

![tableplus-menu2](https://user-images.githubusercontent.com/4352236/42236566-3753a4a4-7f36-11e8-98bd-f233b1835ab7.png)

**Comment by huyphams** [comment]
By holding option, the menu will be shown immediately.

**Comment by windware** [comment]
I see thanks. This feature may not be immediately obvious to users though.
