### ISSUE TITLE
When a column of a table is of a custom type the name of the type is shown instead of the name of the field. 

### ISSUE THREAD

**Issue by StefanoOrdine** [TablePlus/TablePlus#520]
1. Which driver are you using and version of it:
**PostgreSQL 9.5.12**

2. Which TablePlus build number are you using:
**TablePlus Version 1.0 (113)**

3. The steps to reproduce this issue:
Execute these queries:
```
CREATE TYPE a_custom_type AS ENUM ('VALUE1', 'VALUE2', 'VALUE3');

CREATE TABLE a_normal_table (
	uuid uuid PRIMARY KEY,
	a_field a_custom_type
);

INSERT INTO a_normal_table VALUES (
	'8cbde5c5-17c2-4919-8ea8-de56a57c24e9', 'VALUE2'
);
```
Looking at the column title of table data visualization you can see `a_custom_type` which is the type name instead of the column name `a_field`.

![bug report](https://user-images.githubusercontent.com/4438450/42272307-096a8850-7f86-11e8-8e37-75e21dd94d68.png)

PS: I really like TablePlus software, it is very awesome!

**Comment by huyphams** [comment]
Hey @StefanoOrdine thanks, I fixed the bug in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
(This build can self-update when the official release.)

**Comment by StefanoOrdine** [comment]
Thanks @huyphams, I'm waiting for the next release then :-) I'm closing this.

**Comment by StefanoOrdine** [comment]
Downloaded the last build (Version 1.0 build 114) and the fix is working as charm! Thank You all very much!
