### ISSUE TITLE
Truncate in PostgreSQL doesn't restart identity on all columns

### ISSUE THREAD

**Issue by abournier** [TablePlus/TablePlus#521]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**PostgreSQL 9.6**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Build 113**

3. The steps to reproduce this issue:
- create a table **that has a sequence on a field that is not "id"** (_server_id_ in my case)
- add a few items
- select the table => truncate => restart identity
=> the next record will not start at 1 in **server_id** field
=> seems to work on the **id** field in another table

Table structure example:

```
CREATE TABLE "public"."usr_photos" (
    "id" uuid,
    "id_server" int4 DEFAULT nextval('usr_photos_id_server_seq'::regclass),
    "created_at" timestamp,
    "updated_at" timestamp,
    PRIMARY KEY ("id")
);

```

EDIT: it seems to not work in another app, so I hope it's not a PostgreSQL behavior
In the doc, it's written:

> RESTART IDENTITY
> Automatically restart sequences owned by columns of the truncated table(s).

**Comment by huyphams** [comment]
Hi @abournier look like this issue it isn't related to TablePlus, it a PostgreSQL behavior, see here for more detail: https://stackoverflow.com/questions/24416533/postgres-truncate-restart-identity-doesnt-restart-identity

**Comment by abournier** [comment]
Thanks for the link and sorry for this issue that is not one.
I close the issue.
