### ISSUE TITLE
Row inserts/updates not indicated

### ISSUE THREAD

**Issue by triggert** [TablePlus/TablePlus#523]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 113

3. The steps to reproduce this issue:
```
BEGIN TRANSACTION;
INSERT INTO user (username, password) VALUES ('username', 'password');
ROLLBACK; or COMMIT;
```

Normally I would expect to see how many rows are affected but it shows 0 rows.

Example from SSMS:
`(1 row(s) affected)`

**Comment by huyphams** [comment]
Sorry, I made a mistake while parsing syntax. This build should fix the issue: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for the reporting.

**Comment by triggert** [comment]
Thanks!  I do see the row updates now but it opens a query tab for each statement now.

1.) for the begin
2.) for inserts/updates
3.) for the rollback

Is this the expect behavior?

**Comment by huyphams** [comment]
Yes, it's the expect behavior because there are 3 statements, and TablePlus actually received 3 results from the server.

**Comment by triggert** [comment]
Great - thanks for the quick response!
