### ISSUE TITLE
Feature request : UI polish - Reset conditions on foreign key access

### ISSUE THREAD

**Issue by windware** [TablePlus/TablePlus#524]
1. Which driver are you using and version of it : MySQL 8

2. Which TablePlus build number are you using : 113

* When I access the foreign key value by clicking the arrow button in another table's field, the condition seems to stack up if I repeat this step. While the value in the table shown is correct from the last click, the conditions look odd and clicking 'Apply Selected' will obviously give an empty result unless previous conditions are removed.

![foreign-key-access](https://user-images.githubusercontent.com/4352236/42337369-99b5eb20-80c1-11e8-99ce-cfbb9ab892d8.png)

**Comment by huyphams** [comment]
Maybe the UX was bad, the button title should be `Apply All` instead of `Apply Selected`, You can apply the current filter by hit return or click on the `Apply` button at the end of the filter.

**Comment by windware** [comment]
Ah I see, it's more like a history of conditions used previously. Maybe it's good as is. Thanks.
