### ISSUE TITLE
Make DDL definition sort by column order

### ISSUE THREAD

**Issue by j-ro** [TablePlus/TablePlus#526]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 1.0 (113)

3. The steps to reproduce this issue:

When I select definition for a table when viewing the structure, the columns are sometimes out of order (this is Redshift, so they don't care about ordering so much). Would be great to have it in order there by # column in the structure view, because otherwise the order needs to be corrected manually.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @j-ro sure, can you take a look at this build? https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for the feedback.

**Comment by j-ro** [comment]
Thanks @huyphams! I'm not seeing a difference in that one though. Here's some screenshots.

Here's how the definition loads up by default: https://www.evernote.com/l/AD_jf92KFQdAeoOBPS8VTfvqRA1LTZ2rabE

The DDL has the columns in the same order:
https://www.evernote.com/l/AD91Ke8WXbtKZIuGhccTg8-eujp66zr8L70

What I'd like is for the columns in DDL to load up in column order, like this if I sort by the # column:
https://www.evernote.com/l/AD_nGc6F5x1LgpU4P0EHSrUj6mWG4S82x_g

So id, the title, etc...

But DDL stays the same:
https://www.evernote.com/l/AD-jDQ4fBaxDuo6vqnEL-rUsBg3AiAiOe3o

**Comment by j-ro** [comment]
I'll note that this appears to be the same build as I have, 113.

**Comment by huyphams** [comment]
Hi @j-ro I have a typo when sorting the column 🙈 
Can you try again with this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks.

**Comment by j-ro** [comment]
It works! Awesome! This will save me so much time -- just bought a license as well! I'll send in some other thoughts I had to improve your great product when I have a chance, but thank you!

**Comment by j-ro** [comment]
Oh, one other question -- will my build autoupdate when you put out updates, seeing as this isn't on the official mainline?

**Comment by j-ro** [comment]
Awesome, thank you!
