### ISSUE TITLE
Index list is empty in Structure view for Cockroach DB

### ISSUE THREAD

**Issue by themartorana** [TablePlus/TablePlus#528]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Cockroach DB

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 114

3. The steps to reproduce this issue: Create a table, add a unique constraint, refresh the Structure view.

Additional info:

Indexes are creating, and can  be seen with `show indexes on <table>` but the view is empty. I reloaded and restarted the app to be sure. Example:

<img width="655" alt="image 2018-07-09 at 3 47 10 pm" src="https://user-images.githubusercontent.com/21433/42472657-20ac11c4-8390-11e8-961c-7af3a2ece259.png">

but

<img width="678" alt="image 2018-07-09 at 3 47 23 pm" src="https://user-images.githubusercontent.com/21433/42472667-2add07e8-8390-11e8-9e3b-740d50d17785.png">

**Comment by themartorana** [comment]
Here's the table syntax for testing. Using CockroachDB v2.0.2.

```sql
CREATE TABLE game (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  opponent_username STRING NOT NULL,
  data STRING NULL,
  CONSTRAINT "primary" PRIMARY KEY (id ASC),
  UNIQUE INDEX id_oun_unique (id ASC, opponent_username ASC),
  FAMILY "primary" (id, opponent_username, data)
)
```

**Comment by huyphams** [comment]
Thanks, I confirmed the bug. I'm working on it right now.

**Comment by themartorana** [comment]
Update - looks like the same issue for foreign keys:

<img width="698" alt="image 2018-07-10 at 11 41 42 am" src="https://user-images.githubusercontent.com/21433/42521203-3d0d7cc6-8436-11e8-8ad5-a61c6653d87b.png">

<img width="540" alt="image 2018-07-10 at 11 42 18 am" src="https://user-images.githubusercontent.com/21433/42521238-517b7866-8436-11e8-968a-ca609f553d36.png">

Potentially related? I can create a separate issue if not. Thanks!

**Comment by huyphams** [comment]
Thanks, @themartorana. No, you don't need to create another issue, I will fix this too.

**Comment by huyphams** [comment]
Hi @themartorana can you check this build https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
I fixed all the issues above. Thanks.

**Comment by themartorana** [comment]
@huyphams confirmed! Looks good, thanks!
