### ISSUE TITLE
Add warnings in critical areas/on critical actions

### ISSUE THREAD

**Issue by themartorana** [TablePlus/TablePlus#532]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Cockroach

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 114

I highlighted a table to open its contents, erroneously hit the "delete" key on my keyboard, and despite the table being highlighted in red, didn't understand hitting Cmd-S would commit a table drop and significant loss of data (yay backups). 

There are a few places like this where a warning dialog (Are you sure?) should be presented to acknowledge significant changes.

Examples: Drop table, delete row, etc.

Similar: #472

**Comment by huyphams** [comment]
Hey @themartorana  it's here
<img width="753" alt="screen shot 2018-07-10 at 9 40 35 pm" src="https://user-images.githubusercontent.com/3654622/42517424-e3ee6ea8-8489-11e8-80bb-d0e53534796e.png">

**Comment by themartorana** [comment]
Apologies! I would perhaps argue for "Safe mode" being the default, but otherwise, I just missed this.

**Comment by huyphams** [comment]
Enabled by default may cause a confusion and not easy to use for the newcomer. I think the tradeoff is not worth.

**Comment by themartorana** [comment]
Sorry, not "Safe Mode" but "Alert Mode." I agree prompting for a password every time is too much.

One last suggestion - "Alert Mode" only alerts on changing queries. Alerting when sending `select` queries is a bit noisy. Thoughts? Thanks!

**Comment by huyphams** [comment]
Even the `Alert mode` can also result in the same situation, I'm sure with you that if I enable it by default, I will receive a lot of email/issue report that how to turn it off (Many people will not looking for the solution or open preferences, they go straight to inbox/issue and submit for help).

I agree with you that  "Alert Mode/Safe more" only alerts on changing queries is a good idea but, it super hard to achieve. A query in SQL Query is the random statement. All I can do is ignore the query which generated by the app itself (show data/index/structure....).

**Comment by huyphams** [comment]
Probably, I will try to optimize for only simple `select` statement. It's not a full solution but it's the most frequency statement.

**Comment by themartorana** [comment]
> All I can do is ignore all queries which were generated by the app itself (show data/index/structure....).

Right
