### ISSUE TITLE
Support local-file option for MySQL in order to allow LOAD DATA LOCAL INFILE

### ISSUE THREAD

**Issue by joshdcollins** [TablePlus/TablePlus#533]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 114

3. The steps to reproduce this issue:
Execute a SQL statement using LOAD DATA LOCAL INFILE
Receive error "ERROR 1148: The used command is not allowed with this MySQL version"

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by ValiDraganescu** [comment]
too bad this feature is still not available, I have to struggle with the ugly MySQLWorkbench

**Comment by huyphams** [comment]
Hi, I'm adding it @ValiDraganescu  it will be available in the next update.

**Comment by huyphams** [comment]
You can enable it (in the next update) with the other options.
<img width="579" alt="Screen Shot 2020-07-28 at 1 06 11 PM" src="https://user-images.githubusercontent.com/3654622/88625566-34c19480-d0d3-11ea-860f-8304b8efa807.png">
