### ISSUE TITLE
Changing sort columns in data view produces annoying audio error "bonk".

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#535]

**Comment by huyphams** [comment]
Hi @mikebronner How can I reproduce the bug? I tried but didn't have any issue (bonk sound).

**Comment by mikebronner** [comment]
I made a little recording: http://share.genealabs.com/ROfPVru

**Comment by huyphams** [comment]
Hmm, weird, I tried but no luck. I have the same setup as you. I'm investigating more.

**Comment by mikebronner** [comment]
Thanks! I have a relatively new install (about a month old), mostly at default settings. 
<img width="663" alt="screen shot 2018-07-11 at 10 59 32 am" src="https://user-images.githubusercontent.com/1791050/42590756-8590de48-84f9-11e8-8978-a57f950f2239.png">

**Comment by wgormley** [comment]
I am having this same issue and also on 10.13.6

**Comment by huyphams** [comment]
Well, finally, I can reproduce this bug. gonna investigate fix it now.

**Comment by huyphams** [comment]
It was fixed on the build 176 recently. Thanks everybody.
