### ISSUE TITLE
how to export/import all my groups and connections?

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#536]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* build 114

3. The steps to reproduce this issue:
* in connections select window, I can't find a way to export all my connections configurations to a file. I want share all my TablePlus config to other.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It is just released in build 115.
