### ISSUE TITLE
Unable to delete table with Cascade on SQL Server

### ISSUE THREAD

**Issue by kakawait** [TablePlus/TablePlus#537]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQL Server 2014 Express

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 114

3. The steps to reproduce this issue:

* Select tables (could be 1 or more, both case bug) on left panel
* Right click 
* Delete...
* Enable Cascade

```
Msg: 156, Line 1, State: 1, Level: 15
Incorrect syntax near the keyword 'CASCADE'.
All changes were reverted.
```

**Comment by huyphams** [comment]
Thanks @kakawait I will check and fix it.

**Comment by kakawait** [comment]
If needed I use that vagrant box https://github.com/msabramo/vagrant_sql_server_express that host sql server 2014

**Comment by huyphams** [comment]
Looks like MS SQL doesn't support cascade. I disabled this option in the new update.
