### ISSUE TITLE
Cannot execute SQL script

### ISSUE THREAD

**Issue by cvachon-akivo** [TablePlus/TablePlus#538]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 114

3. The steps to reproduce this issue:

1 - Connect to local MySQL server and select any database.

2- Drag a .sql file to the TablePlus icon in the dock. The script opens in "SQL Viewer"

3- Notice it's not possible to run the script.

Please make it possible to edit, save and run .sql files in normal tabs (not in SQL Viewer).

SQL clients like MySQL Workbench and SQL Server Management Studio already allow this. It is an essential feature for developers.

**Comment by huyphams** [comment]
Hi, @cvachon-akivo you can run by drag the file into the SQL Query or press command + O when opening the SQL Query.

The `SQL Viewer` is used for editing the script not for running the script. Probably, we will and a button/function that allows you to import it into `SQL Query`.

**Comment by cvachon-akivo** [comment]
Hi @huyphams 

It would be really useful if an "SQL query" tab would:

1- Allow saving changes to the file (currently, Command + S does nothing)

2 - Display the name of the current file in the tab header.

Also, please consider:

3-  Pressing Command + T should open a new empty SQL query tab

4-  Double-clicking on a table should display a SQL query zone above the grid, like MySQL Workbench, prefilled with the SELECT command that was used to display the data.

**Comment by huyphams** [comment]
Sure @cvachon-akivo some of the feedbacks are good ideas (tab name based on file name, save the file by command + S), really nice.

**Comment by huyphams** [comment]
All are implemented on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
