### ISSUE TITLE
Feature request: ability to set a connection to read-only

### ISSUE THREAD

**Issue by moltar** [TablePlus/TablePlus#539]
It would be great to have the ability to lock down connections to read-only mode. This would be a good safety net for production databases. I know that most databases have the capability to use grants to achieve this, but it is tedious to setup, and sometimes actually impossible (e.g. Heroku). This could be a good generic way that works for all databases.

It could be an option to disable modifications completely, or prompt to confirm before executing a call.

Thanks.

**Comment by huyphams** [comment]
Hi @moltar we already have this feature. You have to click on the lock icon on the toolbar and choose a safe mode level.

**Comment by moltar** [comment]
Excellent. I never saw that lock there. Thanks!

**Comment by G33kNoob** [comment]
any update of this feature?

**Comment by huyphams** [comment]
hi @G33kNoob  do you have any issue with the safe mode feature?

**Comment by iloveitaly** [comment]
Safe mode doesn't work for me. I want to open up a read-only connection to a sqlite db.
