### ISSUE TITLE
Feature request : Add ability to copy table name from menu.

### ISSUE THREAD

**Issue by donbeave** [TablePlus/TablePlus#541]
The latest version of TablePlus doesn't provide any way to copy table name from sidebar menu:
![image](https://user-images.githubusercontent.com/139017/42710885-774aeae2-8718-11e8-847e-63428c183a3c.png)

It's one of feature what I always use in Postico and not allow me to migrate to TablePlus completely:
![image](https://user-images.githubusercontent.com/139017/42710948-c01c4432-8718-11e8-9ccd-7efee6eaf25b.png)

Will be happy to see this feature in TablePlus also.

**Comment by huyphams** [comment]
Hi @donbeave I just added it: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
You can copy multiple table names as well.

**Comment by donbeave** [comment]
Awesome! Thank you!
