### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by RoMoAmy** [TablePlus/TablePlus#542]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 115

When are you planning to work on user management? I saw a post from September 2017 that it was in the plans.

**Comment by selfagency** [comment]
i would totally switch to tableplus from a combination of sequelpro, postico, and everything else were it not for the fact that there's no user management.

**Comment by huyphams** [comment]
Hey @selfagency the user management is being developed, it will be released after the feature encoding and collation.

**Comment by joshua-turner** [comment]
So awesome to see this implemented.

Currently, it's only for MySQL - is there a timetable for bringing it to ~~superior~~ other database platforms, namely PostgreSQL?

**Comment by huyphams** [comment]
Hi @joshua-turner PostgreSQL is the next driver. It will be released soon.

**Comment by brdly** [comment]
Hi @huyphams is there a timetable for the PostgreSQL driver yet?
