### ISSUE TITLE
Unprofessional Images 

### ISSUE THREAD

**Issue by RoMoAmy** [TablePlus/TablePlus#543]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 115

Have you considered adding an option to remove the images (cartoons) that appear throughout TablePlus?

**Comment by huyphams** [comment]
Hi @RoMoAmy  I'm working on branch Quote of the day, you can choose quote instead of the image while loading connection. it will be available in some next updates.

**Comment by huyphams** [comment]
Temporary, @RoMoAmy you can turn it off by unchecking the `Use loading wallpaper` in preferences.
Download the build here: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by alvint** [comment]
Personally, I like the images.  :)

**Comment by RoMoAmy** [comment]
We think the images are cute too; however, there are times when we might pull up a DB screen in front of clients, and we'd prefer not to display the images. We're very happy with the option to turn them on/off.
