### ISSUE TITLE
This is awesome. 

### ISSUE THREAD

**Issue by nojvek** [TablePlus/TablePlus#546]
Just want to say I was going to quit my work to work on a tool like this full time. TablePlus is pretty solid. I’m sad it’s not open source. I would have paid even though it was open source. $49 is well worth the price. I would have paid $100 too. 

Sequelpro is a great tool, but being able to connect to other databases is super useful. 

I wonder how many devs you are? I’ve been thinking of making some sort of a tool and selling online to sustain myself. 

Not sure how easy or profitable TablePlus is but would love any advice on how I can quit my day to day corporate grind and build a self sustaining little business.

**Comment by huyphams** [comment]
Hi @nojvek if you want me to share my experience, feel free to ping me via email huy@tableplusapp.com
Continue reply this thread can cause an annoying for users who subscribe to the repository.
