### ISSUE TITLE
Feature Request: Add default rows count limit as MySQLWorkbench

### ISSUE THREAD

**Issue by yuqiang-yuan** [TablePlus/TablePlus#547]
1. Which driver are you using and version of it: MySQL 5.6

2. Which TablePlus build number are you using: Version 1.0 (115)

3. The steps to reproduce this issue:
    I hope you should add a returned rows count limitation in TablePlus just as MySQLWorkbench. You know, we often write SQL without the "limit n" part. If TablePlus would add a default limit to SELECT SQL that will be very appreciated and helpful.

**Comment by f0ntana** [comment]
this feature is missing, I have tables with lots of data those loads everything and then lets do anything.

**Comment by huyphams** [comment]
Hey, @f0ntana @yuqiang-yuan  you can press command + . to cancel the query, it works exactly the same way with MySQL Workbench. There is no such thing as `add rows count limit`, both TablePlus and MySQL Workbench didn't append any limit to the end of queries.

- MySQL Workbench: it does the paging.
- TablePlus: Continuing loading.

So you guy just need to press: `command + .`

**Comment by f0ntana** [comment]
I things that is a great features, all programs I use, I hasn't need cancel the query.. my ideia is like infinity scroll, that SQLDeveloper use...

its an ideia.. but u decide

**Comment by yuqiang-yuan** [comment]
Hi @huyphams I'm afraid I have different opinion with what you said: 
> "There is no such thing as `add rows count limit`"

Here are two screen captures from MySQL Workbench, one is from the SQL Query Editor, the other one is from the Preferences dialog:

![0787bb25-35f4-46a8-a683-56167f526663](https://user-images.githubusercontent.com/15667885/43818158-ed4a169a-9b0f-11e8-9d31-39b1b9552d4e.png)

![9503aeb2-9e7e-4829-9af2-ffdddb823903](https://user-images.githubusercontent.com/15667885/43818162-f391dfa6-9b0f-11e8-9a2f-cc46d6de2873.png)

You can find out there IS something like "limit rows".  Let me make myself clear, cancel a query is not my preference, what I want is  limit the returned result rows count, please do not fetch all of the rows into local client even I forget to add the `limit N` clause. For example, I have over 6M rows in a table and execute `select * from xxxx` sql statement without the `limit N` clause by mistake, all of the 6M rows are trying to retrieve to and display in TablePlus...

So If you could kindly consider adding this feature in TablePlus I will very glad to pay for it.

Regards,

**Comment by huyphams** [comment]
Hi @yuqiang-yuan I know it, I believe we misunderstood each other.
I'm talking about the method behind the limit row, but you're talking about the meaning of limit row.

As I mentioned about: There is no such thing as add rows count limit, both TablePlus and MySQL `Workbench didn't append any limit` to the end of queries.

They do paging, limit 1000 rows that mean they only fetch 1000 rows for the first page (MySQL allows to get row async).

Image, you have done the query, MySQL returns a pointer, you can use that pointer to get the result, instead of fetching all the rows, MySQL fetches it page by page.

TablePlus use the same method but it loads continuing.

**Comment by yuqiang-yuan** [comment]
Hi, @huyphams  Thank you for your reply. I think this is a convenient feature that I don't need to add `limit N` to every SQL query statement I execute in TablePlus just as what I do in MySQL Workbench.
So back to my feature request, would you please think about it? ^_^

Thanks and regards,

**Comment by huyphams** [comment]
Yeah, I think so, probably in the future TablePlus will support dual-mode: continuing loading and paging.

**Comment by yuqiang-yuan** [comment]
@huyphams What a great message! Thank you very much for your great job and I'm looking forward to the future release.

**Comment by Jammizzle** [comment]
Hi! Love the work,
wondering about the priority of this request? I'd have thought I would've learnt from my mistake and start adding limits to my query but apparently not!

Again, love this work and I'm a very happy user when I'm not accidently selecting all millions of rows 😄

**Comment by yanckst** [comment]
Any updates yet? 

I could be very interesting to limit data while doing a query. Sometimes, you just want to have "x" first results by default and you don't want to add the `limit` keyword in your query or a `select top`. 

It could be interesting having an settings for that.

Thanks ! 

And by the way good job! It's my best SQL client so far !! 😄

**Comment by max-asapp** [comment]
Agree with @yuqiang-yuan about this issue (and also strongly agree with @yanckst -- best SQL i have seen!)

Definitely need a default row limit! 200 or 300 is good... anything beyond that you could either allow no limit to be specified, or build an "export result set" to CSV / JSON [like DBeaver has](https://stackoverflow.com/questions/43329790/export-result-set-on-dbeaver-to-csv).

(Command + . doesn't even really work for me, it seems)

**Comment by huyphams** [comment]
I'm working on this issue, I will update you guys soon.

**Comment by huyphams** [comment]
Hi guys, please check out this build, I added limit result function: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="1261" alt="limit" src="https://user-images.githubusercontent.com/3654622/52609696-b78b6b00-2eb0-11e9-9d83-e3a9912bd3dd.png">

**Comment by max-asapp** [comment]
yay!!

**Comment by yuqiang-yuan** [comment]
Great! I have bought a 2-computers license~~
