### ISSUE TITLE
When duplicating a row the autoincrement is set to 0

### ISSUE THREAD

**Issue by jmfederico** [TablePlus/TablePlus#548]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
115

3. The steps to reproduce this issue:

When duplicating a row on an InnoDB tabel with an autoincrement, the autoincrement columns is set to 0 instead of the next available ID.

**Comment by huyphams** [comment]
@jmfederico how we can produce this issue? I tried and it works fine.

**Comment by jmfederico** [comment]
Hi, well it now works. Thanks anyway!
