### ISSUE TITLE
Vertical Views Not Displayed in the Sidebar

### ISSUE THREAD

**Issue by tland** [TablePlus/TablePlus#549]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Vertica Database 09.00.0104

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 115

3. The steps to reproduce this issue:
The Items sidebar only shows vertical tables, no Vertica views.

**Comment by huyphams** [comment]
Thanks, let me check and fix it.

**Comment by huyphams** [comment]
Hi @tland it's fixed now: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Please let me know if you need anything in Vertica (because of lack of support).

**Comment by tland** [comment]
Awesome. It works now. Thank you, @huyphams
