### ISSUE TITLE
SSL connection error protocol version mismatch

### ISSUE THREAD

**Issue by vojtasvoboda** [TablePlus/TablePlus#55]
Trying TablePlus for the first time and getting this error:

![snimek obrazovky 2017-08-25 v 22 23 49](https://user-images.githubusercontent.com/374917/29731287-2af3bd72-89e4-11e7-9b28-98b4558aa70b.png)

Same connection (over SSH) with Sequel Pro works fine. Any thoughts?

Thanks in advice :-)

**Comment by huyphams** [comment]
it would be great if you can give more enviroment info:
1. Database Driver (PostgreSQL or MySQL...)
2. Server OS (Ubuntu, Centos...).
This error tell us that SSL version of the server too old and the client is newer. I will try to support old SLL version. thank you.

**Comment by vojtasvoboda** [comment]
1. Database is MySQL 5.0.51a
2. Debian Lenny

**Comment by huyphams** [comment]
there is SSL mode config, have you try to change it to disabled?

<img width="495" alt="ssl" src="https://user-images.githubusercontent.com/3654622/35907080-6f07306c-0c1f-11e8-99da-ab6ea457aa3e.png">
