### ISSUE TITLE
Do not display value when column is BIT on mysql (5.7.17)

### ISSUE THREAD

**Issue by gdunghi** [TablePlus/TablePlus#550]
<img width="564" alt="screen shot 2561-07-17 at 10 57 49" src="https://user-images.githubusercontent.com/1131300/42795843-ba5d9c5e-89b0-11e8-818e-0ea942c8b2b2.png">
I use mysql 5.7.17
TablePlus build numbe : 1.0(115)

when i select bit column  , result table don't display value

**Comment by huyphams** [comment]
Hi, we recieved somebody feedback (maybe from you, we can’t reply because there is no email) from direct message. We’re fixing it, thank  you for the reporting.

**Comment by huyphams** [comment]
It's supported now: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks @gdunghi

**Comment by gdunghi** [comment]
Thank you very much
