### ISSUE TITLE
[UX]TablePlus window auto move to another screen(very low priority)

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#552]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

* Build 115

3. The steps to reproduce this issue:

**it's a very low priority requirement**

* open table plus in screen A and open an connection
* move table plus to screen B
* open new connection and TablePlus will be moved to screen A auto.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @bulletRush are you using an external display?

**Comment by bulletRush** [comment]
@huyphams  yes.  I' so sorry, I forgot to tell you I'm using TablePlus in mac os 10.13.3. and it seems like mac os's mechanism.
