### ISSUE TITLE
ENUM update problem. 

### ISSUE THREAD

**Issue by SananGuliyev** [TablePlus/TablePlus#553]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 115

3. The steps to reproduce this issue:

When I try to update `ENUM` column through the GUI, it does not show the dropdown of choices even I could not write it manually. It shows a dropdown like in the screenshot.

![screen shot 2018-07-18 at 10 45 04](https://user-images.githubusercontent.com/5057582/42870347-eadbd9e6-8a77-11e8-8074-d1cf587b9a2a.png)

**Comment by huyphams** [comment]
Thanks @SananGuliyev let me check it.

**Comment by huyphams** [comment]
Hey @SananGuliyev I fixed it: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for the reporting.

**Comment by SananGuliyev** [comment]
Thanks for the quick fix.
