### ISSUE TITLE
Redis not connecting?

### ISSUE THREAD

**Issue by cloudbluedigital** [TablePlus/TablePlus#555]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Redis

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 116

3. The steps to reproduce this issue:

Hi Guys,

So basically my issue is with redis. I am running redis on a vagrant machine and my configuration is:

<img width="480" alt="screen shot 2018-07-19 at 12 06 21" src="https://user-images.githubusercontent.com/22678404/42939012-2ef9c94c-8b4c-11e8-8486-1a8a16e7fe24.png">

And as seen on screenshot when I am testing connection, it is successful however when I connect to it I get:

<img width="1286" alt="screen shot 2018-07-19 at 12 07 45" src="https://user-images.githubusercontent.com/22678404/42939073-612bf2be-8b4c-11e8-9876-46f29a823564.png">

What could be the possible cause for this? It is saying it's reconnecting or collecting database information 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @cloudbluedigital which version of redis are you using?

**Comment by cloudbluedigital** [comment]
```
vagrant@incase-api2-0:~/incase$ redis-cli --version
redis-cli 4.0.9
vagrant@incase-api2-0:~/incase$ redis-server --version
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=1bc80a08306a3efd
```

**Comment by cloudbluedigital** [comment]
any update on this @huyphams

**Comment by huyphams** [comment]
I'm still investigating, I have the same setup and it works fine:
<img width="1208" alt="screen shot 2018-07-20 at 4 35 05 pm" src="https://user-images.githubusercontent.com/3654622/42995373-e8a5a156-8c3a-11e8-9c7c-6f6d2d889f7c.png">

**Comment by cloudbluedigital** [comment]
and is that running throught vagrant?

**Comment by huyphams** [comment]
No, I'm running it via homebrew and one other instance in docker, both of them work fine. I will try to install vagrant later. Currently, I'm focusing on JSON Editor so I will check with vagrant tonight.

**Comment by cloudbluedigital** [comment]
thanks for that, local redis works fine it's just the vagrant

**Comment by cloudbluedigital** [comment]
@huyphams did you have a chance to test it in vagrant?

**Comment by huyphams** [comment]
Hi @cloudbluedigital sorry because of the late response. I'm overwhelmed by tasks.
I just installed vagrant, which repo are you using to install Redis?

**Comment by cloudbluedigital** [comment]
No problem @huyphams I am using laravel/homestead image which comes with redis pre-installed. Image is an Ubuntu 18.04 so it's installed with sudo apt install redis. Let me know if you need more details

**Comment by huyphams** [comment]
I'm using the lasted build 117 and vagrant laravel/homestead, it works.

<img width="1254" alt="screen shot 2018-07-27 at 3 29 31 pm" src="https://user-images.githubusercontent.com/3654622/43310511-f05ab270-91b1-11e8-8def-71dda857e919.png">
Setup:
<img width="612" alt="screen shot 2018-07-27 at 3 30 20 pm" src="https://user-images.githubusercontent.com/3654622/43310526-fb353d28-91b1-11e8-99d3-47694fa33f99.png">

**Comment by cloudbluedigital** [comment]
it does work when you use ssh, I thought that because vagrant exports redis to localhost I will be able to use it but looks like I still need to ssh to it. That's fine, Thanks!
