### ISSUE TITLE
[Cassandra] deletion of tables doesnt work

### ISSUE THREAD

**Issue by lrecknagel** [TablePlus/TablePlus#556]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Homebrew installed Cassandra 3.11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
115

3. The steps to reproduce this issue:
connect to a Cassandra server, open a keyspace (database) and try to delete 1+ tables.
The table names are shown with red background but nothing happens.

**Comment by huyphams** [comment]
Hi @lrecknagel you must press command + s to commit or click on the commit button in the segment control (on the top left)

**Comment by lrecknagel** [comment]
Hi @huyphams thanks for you fast response, its totally fine as you explained. Sorry for that misunderstanding.
