### ISSUE TITLE
[Suggestion] Consistent Use Of System Highlight Color

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#557]
It appears that various sections of the UI aren't all using the same highlight color. This is especially evident when using custom highlight colors in macOS Mojave. As you can see below, the green is the custom highlight color, while blue is hard-coded in TablePlus (or perhaps remaining with the default system highlight color, not recognizing the user-chosen highlight color):

![screen shot 2018-07-19 at 2 31 48 pm](https://user-images.githubusercontent.com/1791050/42971267-7e5ff286-8b60-11e8-902f-30ac110b33cd.png)

Would you consider updating the highlights to work the same across the board? Thanks! :)

**Comment by huyphams** [comment]
Hi @mikebronner there are four colors for row:
- A selected row: blue.
- A new row: green.
- A modified cell (of row): yellow.
- A deleted row: red.

So the green row color in your screenshot must be the new row. There are two blue colors (but it's hard to see it different, one of them is hardcode because I can't figure out how to change it).

**Comment by mikebronner** [comment]
Ah, so it might only have been a coincidence! Let me verify next week -- I'm out of the office until then. Thanks for the quick follow-up.

**Comment by mikebronner** [comment]
@huyphams I can confirm that the green system color is being used to highlight existing rows. I think it would be preferable to use the user-selected system highlight color, rather than forcing a specific blue. In my mind that would be more consistent with the rest of the Mac. Thanks! :)

![screen shot 2018-07-25 at 9 10 29 am](https://user-images.githubusercontent.com/1791050/43213128-a375974a-8fea-11e8-8ded-df52b0e5581c.png)
![screen shot 2018-07-25 at 9 10 44 am](https://user-images.githubusercontent.com/1791050/43213129-a394a8b0-8fea-11e8-91b1-0bf49cfaf075.png)

**Comment by huyphams** [comment]
I got it, thanks @mikebronner for the confirmation. I will do it.
