### ISSUE TITLE
Mysql SSH

### ISSUE THREAD

**Issue by f0ntana** [TablePlus/TablePlus#558]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
116 - with oracle support
3. The steps to reproduce this issue:
I try connect to mysql using ssh
Noted: If the bug is related to data, please attach an example SQL data.

I try connect to mysql using ssh connect and app still in this page for more then 10 minutes,

![screen shot 2018-07-20 at 09 26 28](https://user-images.githubusercontent.com/6570783/43004856-03228c6a-8bff-11e8-97a2-8ad36739c670.png)

don't show any error,...

I use the same connection on sequel pro and works fine.

**Comment by huyphams** [comment]
Hi @f0ntana did you try to put 127.0.0.1 on host instead of the server ip? Sequel Pro always default 127.0.0.1 if you are using ssh.

**Comment by f0ntana** [comment]
In sequel pro I use the external IP, and works, here I use localhost and works.

thanks a lot!
