### ISSUE TITLE
MIddle Mouse Click the Sql Query Icon to open a new SQL query window

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#56]
Currently is difficult to open 2 SQL query windows, I reccomend middle clicking the below icon to open a new query window easily.

![screen shot 2017-08-25 at 4 45 37 pm](https://user-images.githubusercontent.com/7946786/29736328-f224ff9e-89b4-11e7-87b2-69a250e37342.png)

**Comment by huyphams** [comment]
Yeah sure. Thank you.

**Comment by huyphams** [comment]
It will be included in next release
