### ISSUE TITLE
Export All Results (Not just current Page)

### ISSUE THREAD

**Issue by jcohlmeyer** [TablePlus/TablePlus#560]
It is essential to have the CSV export of results export all pages of results, not just the current page in view.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 116

3. The steps to reproduce this issue:
Do a search that returns multiple pages of results, export results via right click.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I got your idea. Currently, you can copy the generated statement and paste it into SQL Query, run it and export result. But it would be more convenient for people to export directly in table data view.

**Comment by jcohlmeyer** [comment]
Oh, that ins interesting, nice to know, I do not think I would have been able to find this by myself. Also I think this would be a great enhancement. Thanks.

**Comment by carlittoer** [comment]
Hi,

Having powerful filters, It would be really handy to have an export of all filtered data. Would love to see this implemented.

**Comment by taniadaniela** [comment]
is there any plan of this happening?

**Comment by modernben** [comment]
@huyphams Checking the status on this one. It would be really nice to port the Export button from the SQL pane to the Table View pane.

**Comment by huyphams** [comment]
We added it a few weeks ago, please wait for the next update.
<img width="439" alt="Screen Shot 2021-02-10 at 8 44 59 AM" src="https://user-images.githubusercontent.com/3654622/107452702-456fbe80-6b7c-11eb-899e-d1ce334ac0b8.png">

**Comment by aussiebb** [comment]
Seems to be broken for CSV export.  It is not filtered, it exports all.
