### ISSUE TITLE
Feature Request: Transpose query/filter results

### ISSUE THREAD

**Issue by lcjury** [TablePlus/TablePlus#562]
Which driver are you using and version of it: MySQL 5.6

Which TablePlus build number are you using: Version 1.0 (116)

The steps to reproduce this issue:
A lot of time I end seeing just one row as a result of a query. I would love to be able to have a transpose feature, who allow me to change columns to rows to be able to watch the result scrolling down instead of scrolling to the right.

**Comment by huyphams** [comment]
I thought the right panel already did it:
<img width="1049" alt="nice" src="https://user-images.githubusercontent.com/3654622/43031834-18a42190-8cd4-11e8-8ec8-69dd707b5ef0.png">

**Comment by lcjury** [comment]
Sorry, I wanted it here :)
<img width="1275" alt="captura de pantalla 2018-07-21 a la s 00 09 29" src="https://user-images.githubusercontent.com/1194606/43031964-5f9a8558-8c7a-11e8-8155-dab2a3799966.png">

**Comment by huyphams** [comment]
You can still use the right panel here by clicking on the row and press `space`.

**Comment by lcjury** [comment]
Now I feel like an idiot :(

Thanks @huyphams !!! that was exactly what I want :)!. I was closing too much my mind to how other db ide's work and didn't see I already used that feature a lot of times before.
