### ISSUE TITLE
Expand result column width automaticaly on EXPLAIN queries

### ISSUE THREAD

**Issue by cjgu** [TablePlus/TablePlus#563]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgresSQL 9.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 116

3. The steps to reproduce this issue:

When doing EXPLAIN queries the output is in one column and that column is too narrow to read full output so every time one need to expand the column, would be nice if the column has maximized width for these queries.

**Comment by huyphams** [comment]
Hey @cjgu thanks for the feedback. We are improving it, it's related to this issue: https://github.com/TablePlus/TablePlus/issues/515

**Comment by cjgu** [comment]
@huyphams, awesome! Thank you for a great product.

**Comment by huyphams** [comment]
It's fixed. Please goto: Preferences > Receive Beta Updates.

**Comment by cjgu** [comment]
Thank you!
