### ISSUE TITLE
[Cassandra] SMALL_INT is always 0

### ISSUE THREAD

**Issue by HenriWallart** [TablePlus/TablePlus#566]
1. Which driver are you using and version of it : Cassandra 3.0.13

2. Which TablePlus build number are you using : 116

3. The steps to reproduce this issue:

I have a column of type SMALL_INT. 
TablePlus shows 0 for every lines even if it's > 0, verified via cqlsh.

**Comment by huyphams** [comment]
Thanks let me check.

**Comment by huyphams** [comment]
I fixed it @HenriWallart 
Can you give it a try: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks.

**Comment by HenriWallart** [comment]
It works !
Thank you for your reactivity !
