### ISSUE TITLE
JSON view not working to SQLite

### ISSUE THREAD

**Issue by l41lt0n** [TablePlus/TablePlus#568]
@huyphams,

The new feature JSON view is not available to SQLITE?

I am using the last version 117 but the field that contains the JSON string don't show me like the print screen that you send before on the Twitter.

Can you inform if is it a limitation to SQLite?

Thanks

**Comment by huyphams** [comment]
Thanks @l41lt0n let me check it.

**Comment by huyphams** [comment]
I forgot to enable JSON in SQLite, here is the build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks.

**Comment by l41lt0n** [comment]
@huyphams 

I am testing the new file but the result is the same:

<img width="1410" alt="screen shot 2018-07-27 at 11 17 59" src="https://user-images.githubusercontent.com/32529405/43326316-e449b33c-918e-11e8-95bd-7d50d2de1220.png">

Any idea?

**Comment by l41lt0n** [comment]
@huyphams,

I am trying to access via MYSQL ( mariaDB server ) and I can not see too the new JSON VIEW.

There is some change that I need to do to be able to see it ( as JSON VIEW )?

I think that I am missing something here.

**Comment by huyphams** [comment]
@l41lt0n TablePlus doesn't recognize blob field is JSON. Currently, It works when the data type is JSON. I will improve later to auto uniform all editor in one so you can choose the editor when previewing.

**Comment by l41lt0n** [comment]
@huyphams,

I got it!

There is a way to make a PLUGIN to add to this option:
<img width="732" alt="screen shot 2018-07-27 at 13 31 26" src="https://user-images.githubusercontent.com/32529405/43333690-769e391c-91a1-11e8-9f05-4e31446d2a92.png">

To select for example "View as JSON" ?

Thanks.

**Comment by l41lt0n** [comment]
@huyphams 

Can you adjust it to MariaDB also?

What about mariaDB ?

It dont have field JSON but "LONGTEXT"

How to use?

Thanks

**Comment by huyphams** [comment]
As I said, I will improve it, combine all editor in one, then you can change the edit when previewing.
I can't optimize for LONGTEXT or blob because it can be anything, it costs too much resource for parsing/detecting real-time.

**Comment by l41lt0n** [comment]
Ok, thank you.

**Comment by l41lt0n** [comment]
@huyphams,

For mySQL it looks amazing!

<img width="1678" alt="screen shot 2018-07-27 at 14 34 21" src="https://user-images.githubusercontent.com/32529405/43337420-3fe06e3c-91aa-11e8-8fd9-a6793f4fc0ec.png">

Thanks
