### ISSUE TITLE
Download hashes?

### ISSUE THREAD

**Issue by MrSkinny** [TablePlus/TablePlus#569]
Are the MD5/SHA hashes provided anywhere on the releases?

**Comment by huyphams** [comment]
Currently, we don’t public it on website but every build has a secret sign in the update, to make sure it was distributed by a trusted source.
We will update it on our site shortly as your request.

**Comment by huyphams** [comment]
Hey @MrSkinny we added SHA hash in this page: https://tableplus.io/osx/changelog
We will update it when releasing a new build.
