### ISSUE TITLE
Update Splash Screen Unreadable In Mojave Dark Mode

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#570]
Hi, thanks for all your hard work on TablePlus! Wanted to share this one with you: in Mojave dark mode, the update splash screen can't be read, because of the low contrast between text and background:

![screen shot 2018-07-27 at 8 31 01 am](https://user-images.githubusercontent.com/1791050/43330312-a2735196-9177-11e8-9411-b22f4ecd50b6.png)

**Comment by huyphams** [comment]
Thanks, @mikebronner for reporting this bug, it is the issue when integrating with Setapp. I will work with them to improve it.

**Comment by mikebronner** [comment]
Ah, didn't know there were issues there. Any chance the Setap version will get cloud sync? Or are the two mutually exclusive? (I have SetApp, as well as purchased the app directly, the later came with cloud sync.) Thanks!

**Comment by huyphams** [comment]
There is a trick for you: https://github.com/TablePlus/TablePlus/issues/390

**Comment by huyphams** [comment]
I will close this issue because it's Setapp library bug.

**Comment by mikebronner** [comment]
I opened an issue with Setupp regarding this as well, and they said it was an issue with how it was implemented here. Sorry, not meaning to point fingers, just trying to highlight there seems to be a communication issue somewhere along the chain. :) Thanks for all the work you do!

**Comment by huyphams** [comment]
They gave us a static lib, which can't be modified and we just include that lib into TablePlus. And the bug probably can be fixed if they change the text color to white. TablePlus do have a theme manager but it won't change the label if it has a fixed color. Thank you @mikebronner I hope Setapp can fix it.
