### ISSUE TITLE
When changing NVARCHAR(MAX) field from NOT NULL to Nullable field becomes a single character NVARCHAR

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#571]
Mac V1.0 (116) SQL Server. When editing an existing table structure as in above description, the field changes to effectively NVARCHAR(1) i.e. single character and truncates entries. Would be good too if the table structure UI showed the length of the NVARCHAR field in the data_type column.

**Comment by huyphams** [comment]
I just added support it here:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for the feedback.
