### ISSUE TITLE
SQLite unable to Delete Column

### ISSUE THREAD

**Issue by aggarson** [TablePlus/TablePlus#572]
1. Sqlite 3.23.1:

2. build 117

3. Create a column (not primary key, etc) then try to delete it.  I couldn't using context menu.

\

**Comment by huyphams** [comment]
Hi, this is SQLite limtation itself Hi Philip, https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite
SQLite doesn’t support remove column. Only adding column is possible.

**Comment by aggarson** [comment]
Thank you for the response.  I understand; however, you should raise an error rather than leave the user in the dark.  Also, take a look at some of your competitors that permit deletion of sqlite columns (e.g., base).  They must run a background script that deletes and then recreates the table although I don’t believe you lose your data….


-- 
Adam Garson at Essentia
Sent with Airmail

On July 28, 2018 at 10:18:56 AM, Huy Pham (notifications@github.com) wrote:

Hi, this is SQLite limtation itself Hi Philip, https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite
SQLite doesn’t support remove column. Only adding column is possible.

**Comment by alvint** [comment]
Related to issue #473.

**Comment by huyphams** [comment]
Hi! it's supported now! If you have a chance, you can download the hotpatch here:
https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks!
