### ISSUE TITLE
Filter multiple tables using Regex

### ISSUE THREAD

**Issue by Matej-Petrla** [TablePlus/TablePlus#574]
When using table filter in left column would be nice if we can search using regex or just multiple tables like this:
- `app_users|app_roles`
- `app_.*|^page$`
- ect...

This feature is used in other successfull free apps like HeidiSQL or SequelPro.

**Comment by huyphams** [comment]
it's duplicated with https://github.com/TablePlus/TablePlus/issues/342
And it is supported now in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0 
Thank you for the suggestion.
