### ISSUE TITLE
Feature Request: Add ability to copy column name from response result

### ISSUE THREAD

**Issue by donbeave** [TablePlus/TablePlus#575]
Hello!

I would like to see the small but quite useful feature, add an ability to copy column name from the result window, like what's already exist in Postico client before I have migrated to TablePlus:

This is how it looks like in TablePlus now:

<img width="1211" alt="xnip2018-07-30_18-32-18" src="https://user-images.githubusercontent.com/139017/43392904-b8e48fd2-9427-11e8-94ce-81d807cf5add.png">

And this is how it was before in previous Postgres client:

<img width="1119" alt="xnip2018-07-30_18-38-57" src="https://user-images.githubusercontent.com/139017/43392946-df6a2ac2-9427-11e8-863b-fbc4be982a6f.png">

Will be happy to see this feature in TablePlus also, if it possible.

**Comment by huyphams** [comment]
Hey, it's here: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
😉

**Comment by donbeave** [comment]
Amazing! Awesome! Love it!
