### ISSUE TITLE
Feature Request: Add ability to open SQL query editor in new tab

### ISSUE THREAD

**Issue by donbeave** [TablePlus/TablePlus#576]
Small, but useful feature, I think.

When I have opened one table through click on it and view some data, I would like to do some separate sql queries, but don't want to replace this tab with sql query, just want to check these data in another tab. I think the best and with good UX way is add "open in new tab" item to context menu on "SQL editor" icon, just here:

<img width="1210" alt="xnip2018-07-30_18-33-15" src="https://user-images.githubusercontent.com/139017/43393086-70a860da-9428-11e8-9538-1dad7849f509.png">

**Comment by huyphams** [comment]
Do you have any problem with command + D?
Btw, if you're using a mouse, you can do it easily with the middle mouse button. Let me know your thought.

**Comment by donbeave** [comment]
No mouse, only touch tab.

If I use "command + T" it will open a new empty tab, then I need to click on "SQL" icon. If I use "command + D" nothing will happen.

**Comment by huyphams** [comment]
Hmm weird, command + D does nothing probably because key binding bug (caused by language)
<img width="1171" alt="screen shot 2018-07-30 at 6 03 57 pm" src="https://user-images.githubusercontent.com/3654622/43393900-f0c6e990-9422-11e8-8926-0bc87da63667.png">

You can try it via shortcut menu:
<img width="529" alt="screen shot 2018-07-30 at 6 04 13 pm" src="https://user-images.githubusercontent.com/3654622/43394080-a4a08732-9423-11e8-9012-0d3527384412.png">

I will try to reproduce the bug, which keyboard language are you using?

**Comment by huyphams** [comment]
if you are on a table view, you can open SQL Query by:
Command + Return or Command + E (Hover on the button you will see the shortcut key, every button).

**Comment by huyphams** [comment]
Hey @donbeave let me know if it works for you 😄

**Comment by donbeave** [comment]
No, no, in my case it's different because I have opened `contracts` first. If I click on SQL icon it will replace my current tab, if I want to open a new tab to use sql query I need do it in two steps:
1) click on "Navigate", choose "New Tab"
2) click on "SQL" icon

I think it's better to have an ability to do it in one step directly. As I said in this issue (https://github.com/TablePlus/TablePlus/issues/577), it's not very UX friendly, I think.

"Command + Return" do nothing, just Refreshing current table view, "Command + E" is what I'm looking for. Probably better to have an option to do same without using a keyboard. But for me "cmd + E" is ok. Thank you!

**Comment by huyphams** [comment]
I forgot that if you selected a row, command + return trigger edit inline.

**Comment by huyphams** [comment]
Hey @donbeave I have a tip for you, instead of single click on a table, you can double-click on the table. After that, when you click the SQL Query button, it won't replace the view.

**Comment by donbeave** [comment]
It works for me.

**Comment by donbeave** [comment]
@huyphams do I need to close the ticket or maybe you will use some idea from this ticket to improve UI later?
