### ISSUE TITLE
Loading Database Time-out

### ISSUE THREAD

**Issue by RoMoAmy** [TablePlus/TablePlus#578]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQLServer 2012
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
117
3. The steps to reproduce this issue:
When connecting to a new large database, TablePlus tries to cache all table information, including triggers, which stalls it until it times out. We also use Navicat, and information is retrieved as needed. Can this be changed?

**Comment by huyphams** [comment]
Hey @RoMoAmy thanks, this is a serious issue, I will investigate and optimize it. Thanks for the feedback.

**Comment by huyphams** [comment]
Hi @RoMoAmy 
Here is the list of all statements which will be executed when connecting.
It would be great if you can run it and let me know which query was slow.

1. Get tables and views.
```
SELECT s.name AS table_schema,t.name AS table_name,'BASE TABLE'AS table_type FROM sys.tables AS t JOIN sys.schemas AS s ON t.schema_id=s.schema_id UNION SELECT s.name AS table_schema,t.name AS table_name,'VIEW'AS table_type FROM sys.views AS t JOIN sys.schemas AS s ON t.schema_id=s.schema_id;
```

2. Get primary indices.
```
SELECT ic.key_ordinal as ordinal_position, OBJECT_SCHEMA_NAME (ic.object_id) AS table_schema, i.name AS constraint_name, OBJECT_NAME (ic.object_id) AS table_name, COL_NAME (ic.object_id, ic.column_id) AS column_name FROM sys.indexes AS i INNER JOIN sys.index_columns AS ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id WHERE i.is_primary_key = 1 ORDER BY ic.key_ordinal ASC;
```

3. Get foreign keys
```
SELECT f.name AS constraint_name,f.update_referential_action AS on_update,f.delete_referential_action AS on_delete,OBJECT_SCHEMA_NAME(f.parent_object_id)AS child_schema,OBJECT_NAME(f.parent_object_id)AS child_name,COL_NAME(fc.parent_object_id,fc.parent_column_id)AS child_column,OBJECT_SCHEMA_NAME(f.referenced_object_id)AS parent_schema,OBJECT_NAME(f.referenced_object_id)AS parent_name,COL_NAME(fc.referenced_object_id,fc.referenced_column_id)AS parent_column FROM sys.foreign_keys AS f INNER JOIN sys.foreign_key_columns AS fc ON f.OBJECT_ID=fc.constraint_object_id;
```

4. Get schemas
```
SELECT name AS schema_name FROM sys.schemas;
```

5. Get functions

```
SELECT s.name AS function_schema,o.name AS function_name,m.definition AS create_statement,CASE WHEN o.type='P'THEN'PROCEDURE'ELSE'FUNCTION'END AS function_type FROM sys.sql_modules m INNER JOIN sys.objects o ON m.object_id=o.object_id INNER JOIN sys.schemas s ON o.schema_id=s.schema_id WHERE o.type!='V';
```

Thank you so much.

**Comment by RoMoAmy** [comment]
Hello Huy Pham,

I ran the queries you requested on the same database in Navicat. Here are my results:

1. Completed in 1.01 seconds

2. Completed in 3.87 seconds

3. Completed in 7.12 seconds

4. Completed in 0.06 seconds

5. Completed in 770.61 seconds

I hope this helps. Let me know if you need anything more.

Sincerely,

Amy Reindel
http://robotmorning.com
(513) 322-4831 x13

**Comment by huyphams** [comment]
Hi @RoMoAmy thanks for the helpful result.
Please update to the build 118 and turn off this option. I will disable loading functions which is 770.61 seconds. I think in the long term, I need to find the other way to load user functions.
<img width="612" alt="abc" src="https://user-images.githubusercontent.com/3654622/43640642-e020a484-974a-11e8-8db0-9481746c97be.png">

**Comment by RoMoAmy** [comment]
This option doesn't seem to be available any longer. Have you found a long-term solution?

**Comment by huyphams** [comment]
it's moved here: 
<img width="740" alt="Screen Shot 2019-03-29 at 9 21 28 PM" src="https://user-images.githubusercontent.com/3654622/55239139-a03dec80-5268-11e9-8bfd-03cc295a8a4f.png">

Reason: If we put the option into preferences, it would affect all connections.

So I decided to move it here, so you can turn off it per connection.

**Comment by huyphams** [comment]
Hey @RoMoAmy I'm not sure if you are still using the app but I've improved the app. TablePlus now can view the function much faster. It will available `next update`! thank you!
