### ISSUE TITLE
how can i change table collation?

### ISSUE THREAD

**Issue by AkemiHomuraa** [TablePlus/TablePlus#581]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.1.73

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 117

how can i change table collation?
i only can find the collation at Overview items ,but i can't edit

**Comment by huyphams** [comment]
Currently, TablePlus doesn't support change collation but it will support it soon.
Thanks for the reporting.

**Comment by patrick-fls** [comment]
Do we have an ETA for this? I just got bitten by it.
Thanks

**Comment by wadetregaskis-linkedin** [comment]
Likewise.  That it silently fails - it just claims the save worked, but immediately reverts the charset & collation changes - is particularly irksome.

**Comment by huyphams** [comment]
Hi guys, please check out this hot patch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 it supports changing encoding and collation now.

**Comment by mehov** [comment]
Hello, is the fix included with the most recent versions?

**Comment by checcoux** [comment]
@huyphams the link isn't working anymore and in the latest version this feature still doesn't work :(

**Comment by joshuapinter** [comment]
Forget about doing it in the UI, just use raw SQL to do it in the SQL tab of TablePlus. Here's what works for MySQL: 

```sql
ALTER TABLE my_table CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

This not only sets the table's default values but converts all of the existing columns as well.

![impressive very nice](https://user-images.githubusercontent.com/180819/110360156-99df5000-7ffb-11eb-8103-33b06b82de00.gif)

**Comment by djmtype** [comment]
Why is this issue closed? We still can't change the collation value.

**Comment by ronaldtveen** [comment]
I agree with @djmtype, this should not have closed. It has not been implemented yet and the only way to set the collation value is when you create a _new_ database.

Since WordPress' `Site Health Status` is now more aggressive about this, it would be great to be able to change this on a higher level than altering the tables manually via queries.

>**utf8mb4 requires a newer client library**
>
>UTF8MB4 is the character set WordPress prefers for database storage because it safely supports the widest set of characters and encodings, including Emoji, enabling better support for non-English languages.
>
>Your MariaDB version supports utf8mb4.
>
>WordPress’ utf8mb4 support requires MySQL client library (libmysql) version 5.5.3 or newer. Please contact your server administrator.
