### ISSUE TITLE
Be able to use `NULL` or `NOW()` in (datetime) columns

### ISSUE THREAD

**Issue by Ilyes512** [TablePlus/TablePlus#582]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL (but this is not relevant...)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
117

3. The steps to reproduce this issue:
When I edit a nullable datetime field. I expect to be able to type in `NULL` or `NOW()` and have it behave as expected instead of filling in `0000-00-00 00:00:00`. I know you can click the arrows and choose it from the menu, but I still would like to see the above added.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @Ilyes512 
I can optimize this, the reason I keep NULL and NOW() as a string because it can be a default value (as string) in other driver (like PostgreSQL).
But in MySQL or with datetime field, it can be optimized.

**Comment by shahzeb1** [comment]
It would be cool to be able to use `NOW()` in an SQLite3 database context as well.

**Comment by CyrilMazur** [comment]
+1, it's something I miss doing from SequelPro

**Comment by drewroberts** [comment]
I also would enjoy having this feature.

**Comment by billriess** [comment]
Is this really not a feature of Table Plus still? Coming from Sequel Pro and Datagrip I expected this to work.

**Comment by huyphams** [comment]
it was supported on the beta build. it will be released in the next update. Meanwhile, you have to choose it on the options dropdown: Hold Option + Click the cell.

**Comment by billriess** [comment]
Ok, great. I just committed to moving over and purchased a license then realized this was missing. Glad to see it being added. Thanks!
