### ISSUE TITLE
How to edit or delete a connection?

### ISSUE THREAD

**Issue by fuzzthink** [TablePlus/TablePlus#583]
Don't see option to do.

**Comment by huyphams** [comment]
Hi, all you need to do is right click on it.

**Comment by eclewlow** [comment]
Connection Menu... -> New Connection ... ->  (Hit cancel on popup, this will leave the database connection window open)
Now you can right click and delete.

**Comment by kathgironpe** [comment]
Terrible UI but it worked

**Comment by huyphams** [comment]
@eclewlow @kathgironpe or you can press cmd + N

**Comment by bdrtsky** [comment]
There's no such option as delete connection in my TablePlus. made right click, there's only open in new tab/window. How to delete connection? I have a list of 20 connections that I will never use again

**Comment by bdrtsky** [comment]
Yeah this UI is super weird. Like you hidden it for some reason.

**Comment by mayanksaurabhLiv** [comment]
> Connection Menu... -> New Connection ... -> (Hit cancel on popup, this will leave the database connection window open) Now you can right click and delete.

this really helped but why this feature is so weird, anybody from tableplus team reading this, please change it

**Comment by huyphams** [comment]
> Connection Menu... -> New Connection ... -> (Hit cancel on popup, this will leave the database connection window open) Now you can right click and delete.

Cmd + N to show the Welcome screen again then, you can delete it.

**Comment by huyphams** [comment]
We just added all the menu from the welcome screen to the connection window too, please wait for the next update!
