### ISSUE TITLE
Field/Tables/Database collation and encoding.

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#584]
It would be great if TablePlus can support all of these features.

**Comment by pqr** [comment]
Support this issue, very useful for me!

For example how it looks in Sequel Pro:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/451007/54670807-8af8ed80-4b05-11e9-9e1b-dd5a938db1a3.png">

<img width="909" alt="image" src="https://user-images.githubusercontent.com/451007/54679581-b0432700-4b18-11e9-8dbd-664e93eb5316.png">

I prefer TablePlus, but when I need to change collation or encoding, I have to run Sequel Pro just for this one task.
