### ISSUE TITLE
Regression: Unable to connect to database using ProxyJump (ProxyCommand)

### ISSUE THREAD

**Issue by davidolrik** [TablePlus/TablePlus#586]
Trying to connect over ssh through a jump host with `ProxyCommand` but the config in `~/.ssh/config` is not respected.

When trying to connect to a remote database via ` jumphost.my.tld`, TablePlus is connecting directly to ssh on the database host, and not through ssh on the jump host.

The relevant ssh config:

```
Host *.my.tld
    ProxyJump jumphost.my.tld
```

TablePlus 1.0 (118)

**Comment by davidolrik** [comment]
Did you change ssh library since you added the `enhancement` label instead of `bug`?
(In a few versions before 118 this actually worked)

**Comment by huyphams** [comment]
Wait, so it actually works before version 118?

**Comment by altinkonline** [comment]
I'm using ProxyCommand and that's also not respected. I'm a new user, zo I don't know if it worked before.

**Comment by huyphams** [comment]
Actually, you can download and try all the old build here: https://tableplus.io/osx/changelog

**Comment by altinkonline** [comment]
No, it's not working for me. I'm running on Mac OS Mojave.

**Comment by huyphams** [comment]
Yup, because TablePlus currently, doesn't support `ProxyCommand`, but @davidolrik said that build 118 works for him so I'm confused.

**Comment by altinkonline** [comment]
OK, is it on the roadmap to support ProxyCommand? This is the moment to get users from Sequel Pro because that's not working on Mojave;)

**Comment by huyphams** [comment]
Yep, we do have that plan. I'm working on that, hopefully, it can be released in the next beta.

**Comment by altinkonline** [comment]
Nice, I will use that if it is available 👍

**Comment by davidolrik** [comment]
> Yup, because TablePlus currently, doesn't support `ProxyCommand`, but @davidolrik said that build 118 works for him so I'm confused.

No, I said it broke for me with build 118, but worked for me in a build *before* 118.
I don't remember which build I upgraded from, but it was a few builds prior to 118.

**Comment by huyphams** [comment]
Hey @davidolrik and @altinkonline I have updated the libssh recently, in the new version, they said that it supports ProxyCommand, please try the newest build and let me know the result 👍 
Thanks all.

**Comment by henrikbjorn** [comment]
Not sure if this is the same feature request.

At work we have a jump server. So I have a bunch of Host aliases in `~/.ssh/config` with `ProxyJump` set. TablePlus does not respect that `ProxyJump` and seems to not see the aliases.

**Comment by davidolrik** [comment]
Works like a charm!

**Comment by Crytiqal** [comment]
It doesn't work for me?
I have ~/.ssh/config with a configured jumphost but it is not respected

Please advise

**Comment by alexschwarz89** [comment]
Came here to figure out if this is working in TablePlus and how, tried the thingy with ssh config and everything works like a charm. 

OS X 13.14
TablePlus 5.6.2 (516)

SSH config looks like:

```
Host any-name
    HostName 1.2.3.4
    HostName web-001
    User anyusername
    ProxyJump ubuntu@2.3.4.5
```

In TablePlus i just use the "any-name" as a server.

**Comment by shiskeyoffles** [comment]
> Came here to figure out if this is working in TablePlus and how, tried the thingy with ssh config and everything works like a charm.
> 
> OS X 13.14 TablePlus 5.6.2 (516)
> 
> SSH config looks like:
> 
> ```
> Host any-name
>     HostName 1.2.3.4
>     HostName web-001
>     User anyusername
>     ProxyJump ubuntu@2.3.4.5
> ```
> 
> In TablePlus i just use the "any-name" as a server.

I've setup and similarly in my mac, and if I go to terminal and type

> ssh any-name 

then it correctly logs into the server. But it still doesn't work via TablePlus

How are you accessing it ?

**Comment by alexschwarz89** [comment]
@shiskeyoffles I simply put the Alias in the "Server" field of SSH configuration. Nothing else going on here. Are you using the same TablePlus version? If it works on your CLI it shouldn't be a ssh-config issue. Do you use SSH keys also? Maybe without a key it does not look in .ssh/config? Just ideas…
