### ISSUE TITLE
Unusable when connecting to database with large number of tables

### ISSUE THREAD

**Issue by nguyenmv2** [TablePlus/TablePlus#587]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 1.0 ( 118 )

3. The steps to reproduce this issue:
- Connect to a database with large amount of tables ( in my case it's ~2000 tables )
- Stuck on the loading screen.

**Comment by huyphams** [comment]
Thanks, @nguyenmv2 I will try to optimize it, but can you tell me how many schemas in your database?
All table in one schema or in a separated schema?

**Comment by nguyenmv2** [comment]
I have a little over 3000 tables. Is it possible to have access to the SQLQuery window before fetching he metadata of all the tables?

**Comment by huyphams** [comment]
Please follow this issue: https://github.com/TablePlus/TablePlus/issues/2520
