### ISSUE TITLE
Ability to integrate with source code editor (VS Code)

### ISSUE THREAD

**Issue by goodwill** [TablePlus/TablePlus#588]
I am very interested to see if there is a possibility to integrate TablePlus with VS Code - basically allow me to keep all my SQL scripts inside VS Code but trigger run on the tableplus UI, as I love TablePlus but its not the most ideal way to keep track on SQL coding.

**Comment by japsu** [comment]
Does TablePlus have an API that could be used to send queries to it?

What I'd like from a VS Code extension is to be able to select a query in VS Code and send it to TablePlus using a keyboard shortcut or palette command so that I could edit the SQL in VS Code but execute it in TablePlus.

**Comment by japsu** [comment]
A workaround for now is to symlink `~/Library/Application Support/com.tinyapp.TablePlus/Cache/Favorite` under the project I'm working on. Changes to SQL files thereunder seem to be propagated to TablePlus with little or no delay.

**Comment by huyphams** [comment]
Hi @japsu you don't have to do that, just right click > add folder to Queries and it done!

**Comment by huyphams** [comment]
<img width="549" alt="CleanShot 2022-11-18 at 14 50 46@2x" src="https://user-images.githubusercontent.com/3654622/202649473-a09da58e-8106-4e29-813c-9b853c0e44a7.png">

**Comment by japsu** [comment]
@huyphams That's useful, thanks for the tip!

**Comment by davidbehan** [comment]
Great tip indeed. This changes how I use TablePlus... makes it even better. Thanks

**Comment by QuangTran304** [comment]
Can anyone explain to me what or where should I right-click on? I need execute my SQL queries from inside VSCode as well.
