### ISSUE TITLE
Why query whole table when showing structure?

### ISSUE THREAD

**Issue by ipchikin** [TablePlus/TablePlus#589]
When I try to show the structure of a huge table, it will query the whole table
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql and postgresql
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
118
3. The steps to reproduce this issue:
click the show structure on the table
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @ipchikin TablePlus won't query the whole table. It performs this query `SHOW CREATE TABLE table_name;` to get table definition.
In PostgreSQL, tableplus sends `select obj_description(OID, 'pg_class') as comment;` to get comments.
Why did you think that it query the whole table?

**Comment by ipchikin** [comment]
@huyphams because when I clicked the show structure on a table with many rows, it couldn't be loaded. I tested on some other medium size tables, it took a while to be loaded and when I switched to data tab, the data was already loaded. I will check it again tmr thanks!

**Comment by huyphams** [comment]
In both MySQL and PostgreSQL? Probably these queries have a performance issue. I will take a look into it.
Thank you for the reporting.

**Comment by ipchikin** [comment]
@huyphams yes, I will give you more details tmr

**Comment by ipchikin** [comment]
@huyphams I have tested more tables on redshift today, whenever I switch the table under the structure tab and I switch to the data tab, the data is already loaded. Also is it a good idea to add limit when clicking into a huge table under data tab?

**Comment by huyphams** [comment]
Hey @ipchikin it's optimized in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Can you give it a try?
Thanks

**Comment by ipchikin** [comment]
@huyphams Can confirm that the show structure is working now. Nice work!
