### ISSUE TITLE
SQLite driver

### ISSUE THREAD

**Issue by pascalandy** [TablePlus/TablePlus#59]
Hi,
I'm opening this issue only to follow the progress of this feature. Can't wait to try it :)
Cheers!

**Comment by huyphams** [comment]
Thanks 😁

**Comment by huyphams** [comment]
I have a beta build for SQLite driver

![screen shot 2017-09-01 at 3 47 57 pm](https://user-images.githubusercontent.com/3654622/29962307-ffe17a68-8f2c-11e7-94f6-726dc1ad15da.png)
![screen shot 2017-09-01 at 3 48 15 pm](https://user-images.githubusercontent.com/3654622/29962312-016fccea-8f2d-11e7-8d97-ac6de484c63b.png)

**Comment by huyphams** [comment]
Hey @pascalandy you can download beta version here: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by pascalandy** [comment]
Thanks for letting me know. I was looking under the release section but it's empty.

**Comment by huyphams** [comment]
We have 2 updates each month (15 and 30), so there are 12 days remaining before official release.
