### ISSUE TITLE
Multi-line Query Strips Whitespace Between Lines

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#591]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
10.3
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
118
3. The steps to reproduce this issue:
```SELECT
    *
FROM
    orders
WHERE
    1 = 1
    AND created_at >= '2017-01-01 00:00:00'
    AND created_at >= '2017-08-09 00:00:00'
    AND created_at <= '2017-12-31 23:59:59'
    AND created_at <= '2018-08-08 00:00:00';
```

I have to manually add a space either before the `AND` or after the date string to make it work. Whitespace should not be stripped completely, but reduced to one space.

Thanks! :)

**Comment by huyphams** [comment]
I can't reproduce it. I have tested with:
```
SELECT
    *
FROM
    orders
WHERE
    1 = 1
    AND created_at >= '2017-01-01 00:00:00'
    AND created_at >= '2017-08-09 00:00:00'
    AND created_at <= '2017-12-31 23:59:59'
    AND created_at <= '2018-08-08 00:00:00';
```
And TablePlus sent exactly the same query to server, can you tell me more? What is the error reported by TablePlus, syntax error or different results?

**Comment by mikebronner** [comment]
I can't reproduce it anymore either. It was a Postgres error that said invalid character or something like that. I should have captured the output. Sorry. I'll re-open if it happens again.

**Comment by huyphams** [comment]
I have faced serveral times, mostly because i pressed option + some keys and it inserts an invalid character, it looks like a space so I don’t know it until I remove and insert again.
