### ISSUE TITLE
[Suggestion] Saved SQL favorites should not auto-save upon editing

### ISSUE THREAD

**Issue by Jailyard90Grad** [TablePlus/TablePlus#592]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Using PostgreSQL
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 118
3. The steps to reproduce this issue:
Edit any SQL Favorite

I often will use a query I've already created as the basis for new ones. Doing this for the first time, I lost a complex query because as I edited it the new query auto-saved over my existing query. There was no option to revert or Save As... It would be great if there was or if I needed to commit the save as I do changes to the db.

**Comment by huyphams** [comment]
If you edit an SQL Query in Favorite but not press: command + S, it won't save. Did you rename that favorite to the same name as another favorite?

**Comment by Jailyard90Grad** [comment]
Huy,

I had a saved query. I opened it, edited it, and ran it. I copied it so I could save it as it’s own query favorite...but when I double-clicked on the named favorite, there was no change. The query had been saved as my new query so I lost my previously saved favorite.

Cheers,

Mark
www.markdoerr.com

Sent from my iPhone
My apologizes for typos and lunacy

**Comment by huyphams** [comment]
I think favorite doesn't work that way,
The only way to edit Favorite is using the Favorite editor (right-click > Edit/Rename).

If you edit the query after insert in SQL Query, it won't be saved/changed. If you ran it, it will be recorded in the History, you can go there and recovery it in case you lost the query.

**Comment by huyphams** [comment]
We changed it as your suggestion on build 200 thanks @Jailyard90Grad

**Comment by CyrilMazur** [comment]
I am still experiencing this behaviour in 228.

**Comment by aramando** [comment]
I am still experiencing this in build 234, and furthermore it also does it for SQL files opened from disk. I have opened a new issue: #1254
