### ISSUE TITLE
date issue on result display with mmsql

### ISSUE THREAD

**Issue by vinceofdrink** [TablePlus/TablePlus#594]
1. MMSQL 2017

2. TablePlus build 119 

3. Create a table with a date field (not a datetime)

4 On the display in TablePlus those date will be display as 'Jul 25 2018 12:00:00:AM' instead of '2018-07-25' there should not be any HH:MM:SS

**Comment by huyphams** [comment]
This is one of know issues. I’m still finding the way to change it, it default by the driver. Thanks for the reporting.

**Comment by huyphams** [comment]
I just fixed it, it will be released on Monday.
