### ISSUE TITLE
Autocomplete for multiple database.

### ISSUE THREAD

**Issue by alecaserez** [TablePlus/TablePlus#595]
with multiple database autocomplete only work in connection database.

example: 

connection database: datadb1

```
select table1.field, table2.¿?
from datadb1.table as table1
       join datadb2.table as table2

```

**Comment by huyphams** [comment]
TablePlus doesn’t supprot autocomplete in multiple database because it’s hard to optimize, we will consider it.
Thanks for the suggestion.
