### ISSUE TITLE
Mojave Dark Mode + TablePlus Dark Mode: Selected Inactive Row Not Readable

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#596]
When using TablePlus in Mojave in dark mode, the selected row is not readable if the pane is not active. This has caused confusion for me several times over the past few weeks, especially when the last row is selected, causing me to believe the row was missing.
![screen shot 2018-08-13 at 10 51 40 am](https://user-images.githubusercontent.com/1791050/44048768-2f9e4dd8-9ee7-11e8-91e9-7c9078269d7d.png)

**Comment by huyphams** [comment]
Thanks, I will improve it and this one https://github.com/TablePlus/TablePlus/issues/557

**Comment by huyphams** [comment]
It's fixed both issues 👍 thanks @mikebronner
