### ISSUE TITLE
Access denied for user on Vagrant

### ISSUE THREAD

**Issue by robinbertram** [TablePlus/TablePlus#597]
I'm trying to connect to my Vagrant machine but I'm getting the error `Access denied for user 'vagrant'@'192.168.10.1' (using password: YES)`

---

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
119

**Comment by huyphams** [comment]
Looks like `192.168.10.1 ` is your IP address, and MySQL says that it won't allow connection from local IP.
There are two possible solutions:
1. Change MySQL config that allows connecting from `192.168.10.1`. https://www.barrykooij.com/connect-mysql-vagrant-machine
2. Using the SSH method, checkout this issue: https://github.com/TablePlus/TablePlus/issues/555

**Comment by robinbertram** [comment]
Thank you!
