### ISSUE TITLE
Structure view: case-insensitive sorting

### ISSUE THREAD

**Issue by alexjurkiewicz** [TablePlus/TablePlus#598]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 119

3. The steps to reproduce this issue:

Please change TablePlus so that when sorting `column_name` or `foreign_key` columns in structure view, the sorting is case-insensitive.

Example of incorrect sorting:
![screen shot 2018-08-15 at 3 34 00 pm](https://user-images.githubusercontent.com/379509/44133024-ad2533ec-a0a0-11e8-80f4-0eb9adbb5525.png)

**Comment by huyphams** [comment]
Thanks @alexjurkiewicz, it's fixed now.

**Comment by alexjurkiewicz** [comment]
So fast!! 😍
