### ISSUE TITLE
Query database based on search query for a new workspace

### ISSUE THREAD

**Issue by eleijonmarck** [TablePlus/TablePlus#599]
To be able to query based on search for the different databases one has setup. 

1. Opening a new workspace
2. Getting into the search field
3. Preferably to query and get the most relevant db connection based on search string.

For example:
test-db

Would suggest test-db, over local-db.

**Comment by huyphams** [comment]
Hi, can you tell me more detail?
2. Search field but which search field: on the left sidebar, right sidebar or open anything or advanced filter?

**Comment by eleijonmarck** [comment]
2. ![image](https://user-images.githubusercontent.com/7727602/44212078-b0d2a400-a16a-11e8-818e-3eb160ddbba6.png)

**Comment by eleijonmarck** [comment]
Oh awesome! @huyphams keep up the great work. It's an amazing product

**Comment by eleijonmarck** [comment]
Want me to close it?

**Comment by huyphams** [comment]
No, please keep it open until the feature released.

**Comment by eleijonmarck** [comment]
@huyphams Is this released already?
