### ISSUE TITLE
Possibility to change socket location

### ISSUE THREAD

**Issue by tswestendorp** [TablePlus/TablePlus#60]
I'm using MAMP PRO to run a local databaseserver, which creates a socket at `/Applications/MAMP/tmp/mysql/mysql.sock` instead of the default `/tmp/mysql.sock`.

It would be great if we could change this default path for specific connections

**Comment by huyphams** [comment]
Hi @tswestendorp , I just created a task to support socket for MAMP PRO.
We will have this feature in the next release.
https://github.com/TablePlus/TablePlus/projects/1?

**Comment by huyphams** [comment]
Supported socket now,
You can try here: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

![socket](https://user-images.githubusercontent.com/3654622/29993556-a0b45f98-8fe4-11e7-976d-b7e566e7d003.png)
