### ISSUE TITLE
Apparently not possible to connect to cassandra over ssl

### ISSUE THREAD

**Issue by rafaelkarst** [TablePlus/TablePlus#600]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- Cassandra 3.4.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- Build 119

3. The steps to reproduce this issue:
- Cannot connect to cassandra using SSL pem certificate. It feels like the app is not even trying, it fails instantaneously with a message: "No hosts available for the control connection" which is also missleading. I can normally connect using cqlsh command line. If i telnet to the server, it responds normally, which means it is accessible from my end. Here is the example of the command i am using to connect via cqlsh without any problems:
- `$ ./cqlsh <MY_CASSANDRA_HOST> <MY_CUSTOM_PORT> --ssl --cqlshrc=/<USER_HOME>/cqlshrc --cqlversion="3.4.4"`
- My `/<USER_HOME>/cqlshrc` looks like this:
```
[authentication]
username = <CASSANDRA_USERNAME>
password = <CASSANDRA_PASSWORD>

[ssl]
certfile = /<FULLPATH_TO_MY_CERT>/fullchain.pem
validate = false
```
- My `/<FULLPATH_TO_MY_CERT>/fullchain.pem` looks like this:
```
-----BEGIN CERTIFICATE-----
<THE KEY>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<THE KEY>
-----END CERTIFICATE-----
```

This is really not a big deal, its a normal cassandra cluster running on prod.

Any help is appreciated! 

Thanks!

**Comment by huyphams** [comment]
Hi, I'm not if helpful but here is mine, I connect to Cassandra with port 32771 (Which is forward to 9042 by Docker).

`No hosts available for the control connection ` => probably wrong port.

<img width="563" alt="port" src="https://user-images.githubusercontent.com/3654622/44209239-146dc900-a18d-11e8-98ef-36504d3b0b00.png">

**Comment by be-ez** [comment]
Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3.4.4

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 132

The steps to reproduce this issue:

exactly the same as @rafaelkarst - I can connect via cqlsh but not via TablePlus. I get the `No hosts available for the control connection` message. I'm connecting to the load balancer of my cluster @ 9042.

**Comment by slieker-d** [comment]
I also have the exact same problem, and exact same version numbers as @be-ez

**Comment by shadabfaizi** [comment]
+1

**Comment by slieker-d** [comment]
This is still an issue. How can I help to debug?

**Comment by snayakie** [comment]
I have the same problem.

**Comment by huyphams** [comment]
Hi guys, I'm sorry because of the late response, here is a new build which support SSL, let me know if you are still facing the issue.
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by huyphams** [comment]
cc @rafaelkarst @slieker-d  @snayakie @be-ez thank you
<img width="523" alt="ssl" src="https://user-images.githubusercontent.com/3654622/55484408-a3fbb580-5652-11e9-93bd-50470281f0db.png">
