### ISSUE TITLE
Cassandra: changes are not committed

### ISSUE THREAD

**Issue by raelmax** [TablePlus/TablePlus#603]
1. Driver Version: Cassandra 3.11.2

2. TablePlus build: 120

3. The steps to reproduce this issue:
- Connect to cassandra
- Choose a table
- Edit/Add a row
- Commit changes
- Changes are discarted (interface rollback to state before changes)

**Comment by huyphams** [comment]
Hi @raelmax, Currently, Cassandra driver has an issue that if there is an error in the statement it will rollback all the changes. I'm working on it now. I will update the build asap on this thread for you.

**Comment by huyphams** [comment]
Hi @raelmax I fixed the bug that TablePlus doesn't report error message in this build: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks for letting me know.

**Comment by raelmax** [comment]
Thank you @huyphams! This is a official release? I saw that the build number don't changed.

Now I can understand why my changes can't be commited. When I try commit my changes I get the message: "Invalid STRING constant (902c22e8-2f2f-4c2e-9d89-edfaa2610e24) for "id" of type uuid. All changes were reverted."

This is because TablePlus are putting quotes around my UUID value. Copying the generated query, removing the quotes and executing in SQL tab works fine.

TablePlus generated query:
`UPDATE "kong"."apis" SET "name" = 'oidc-test-3' WHERE "id" = '902c22e8-2f2f-4c2e-9d89-edfaa2610e24';`

Fixed query:
`UPDATE "kong"."apis" SET "name" = 'oidc-test-3' WHERE "id" = 902c22e8-2f2f-4c2e-9d89-edfaa2610e24;`

**Comment by huyphams** [comment]
That made sense. This is hotfix build so you can keep using it until the next update (it can self-update as the official release).
I will update support for the case above, TablePlus should not add the quote for UUID. Wait for me a couple mins.

**Comment by huyphams** [comment]
This build supports update UUID: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thank you.

**Comment by raelmax** [comment]
It worked! Thank you!
