### ISSUE TITLE
PostgreSQL and datetime type without milliseconds

### ISSUE THREAD

**Issue by abournier** [TablePlus/TablePlus#605]
When editing the structure of a PostreSQL table, I can't force a timestamp to not manage milliseconds in the table form: timestamp(0).

When creating a new table, it works with CREATE TABLE...

`"created_at" timestamp(0) without time zone`

It could be cool if we can edit the table schema to add timestamp(0) in the form at right. Actually I can add it but when validating the modification, the schema doesn't change.

**Comment by huyphams** [comment]
Sorry because of the delay, I missed the notification.
You can set or edit the timestamp to timestamp(0) by double click or using the right panel. The only thing is missed that TablePlus doesn't show the (0) (but it's there). I will improve it in the next update.
Thank you so much!

**Comment by abournier** [comment]
OK. That's right.
It's working (new column or old column with the change to (0)).

Note that it's not shown in the table definition too. ;)

Thanks
