### ISSUE TITLE
[Suggestion] Maintain Table Selection

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#606]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSql
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
120
3. The steps to reproduce this issue:
Select a table, then edit a row in the data window.
Note that the table selection has been removed when the table list looses focus.
Would love to see the selection retained, so I can easily find the table I'm working on in the list, especially if I scroll the table list without refocusing it.

Thanks! :)

**Comment by huyphams** [comment]
Great idea, I will do it.
