### ISSUE TITLE
No hosts available for the control connection for Cassandra db

### ISSUE THREAD

**Issue by MightyPixel** [TablePlus/TablePlus#609]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra [cqlsh 5.0.1 | Cassandra 2.1.17.1439 | DSE 4.8.12 | CQL spec 3.2.1 | Native protocol v3]

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
120

3. The steps to reproduce this issue:
Try to connect to the db over ssh. Enter host 0.0.0.0 (blank, localhost, 127.0.0.1 does not work either), port 9042, username and password, SSH credentials. When I try to connect or test the connection I receive the following error:
`No hosts available for the control connection`

* I am able to connect to the database using the same credentials using cqlsh using 127.0.0.1:9042 after ssh-ing to the server

Cheers!

**Comment by huyphams** [comment]
Thanks @MightyPixel I will check it.

**Comment by huyphams** [comment]
Hi @MightyPixel I can't reproduce the bug, the only way to reproduce it is... turn of the server.
Could you double check the connection for me again (by using the other tool)?
About the features, TablePlus will not support every database features, we only focus important features and keep the client minimal.
`define new keyspaces or manage current ones` are important features, I will add it soon.

**Comment by MightyPixel** [comment]
Hello @huyphams,

After some investigation I saw that I'm able to connect to my test cassandra cluster that runs on 2.1.19.1484 (Native protocol v3) using http://squirrel-sql.sourceforge.net/ + https://github.com/zhicwu/cassandra-jdbc-driver. A colleague of mine assumed that there could be a problem when the driver is negotiating down .
Also I saw that locally I use 2.2.12 (Native protocol v4) and I do not receive the no hosts error, but I do not see any keyspaces. Or if I explicitly specify the keyspace I do not see tables. 

Thanks!

**Comment by huyphams** [comment]
Hi, I'm going to release a new official build 130 which is compatible with Cassandra 2.
Or you can try it now here: https://www.dropbox.com/s/xmxq4i0t4b6zhyg/TablePlus.zip?dl=0

**Comment by MightyPixel** [comment]
Hi @huyphams Thanks for the fast response!

I tried with the version from the dropbox and I can successfully log in into the server  and after pressing Cmd + K shows me all the databases as expected.
However I can't connect to any database, because I get Upgrade to open Unlimited Workspace error. What is "Unlimited Workspace". Is there a way to open a keyspace without unlimited workspace?

**Comment by huyphams** [comment]
There are 3 options.
1. Specify the keyspace in connection form.
2. Right click on the keyspaces list and select switch.
3. Buy a license 😁

**Comment by MightyPixel** [comment]
I managed to connect using ssh with the latest update (132 build); I'll consider the third option :) 

Closing this issue. Thanks for the support!

**Comment by kernant** [comment]
Hi, I have the same issue. Is build 132 available for download?

**Comment by huyphams** [comment]
Yes @kernant https://tableplus.com/osx/changelog
Please let me know the result

**Comment by kernant** [comment]
I have the same error with the latest version download.

of the 3 options:

1) I have the correct keyspace
2) where do I right click? What does this mean?
3) is the commercial license more up to date?
