### ISSUE TITLE
Port issues in connections

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#61]
Build 59 - port setting saves well, but after **save** or **edit** actions Connection Edit form shows empty value on **port** field.
Also after **connection duplicate** action **port** sets to default empty field(22).

**Comment by huyphams** [comment]
I got the bug, thank you 🔍🐞

**Comment by huyphams** [comment]
Hi @PVGrad I just added a update and also fixed the bug above.
Update includes:
- Added foreign key viewing.
- Added new menu in index/structure.
- Support copy field.
- Many other bugs fixed.
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by PVGrad** [comment]
@huyphams , thx - will it be included in next build?

**Comment by huyphams** [comment]
Yup, it will be included in the next build. and you can use this build until the next build release.
