### ISSUE TITLE
Insert/Update SET column in Cassandra table

### ISSUE THREAD

**Issue by lutomas** [TablePlus/TablePlus#610]
1. Cassandra 3.11.2

2. Version 1.0 (120)

3. The steps to reproduce this issue (**when INSERTING)**:
a) In 'SQL Query' Create simple table 
`CREATE TABLE abc1 (pk int, names set<text>, PRIMARY KEY (pk));`
b) Open table 'abc1' 
c) Try to insert row with values:
     pk=1, names={'TablePlus'} 
d) Commit changes (Cmd+S)

PROBLEM:
Row not inserted.

INVESTIGATION:
Click button 'Preview your changes as SQL statements'
`INSERT INTO "<db-name>"."abc1" ("pk", "names") VALUES (1, '{'TablePlus'}');`

Should be:
`INSERT INTO <db-name>.abc1 (pk, names) VALUES (1, {'TablePlus'});`

> NOTE: there are no quotes (`"`) in the valid statement and value for 'names' is not `'{'TablePlus'}'`, but `{'TablePlus'}` (surrounding single-quote `'` causes the problem).

**when UPDATING**
If you have existing row and want to change it in 'abc1' table view, then `UPDATE "<db-name>"."abc1" SET "names" = '{"TablePlus updated"}' WHERE "pk" = 1;` needs to be like `UPDATE <db-name>.abc1 SET names = {'TablePlus updated'} WHERE pk = 1;`
> NOTE: `"` and `'` similar to INSERT statement.

I think it is two issues of the same kind. Looking forward for the fix ;)

p.s. Nice product, thanks for the effort.

**Comment by huyphams** [comment]
Hey @lutomas thank you for the detail report. I'm fixing it now.

**Comment by huyphams** [comment]
Hey @lutomas, I just fixed all the issues above including SET, LIST, and MAP.
You can download the build here: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
The binaries size has been increased a lot because it includes Oracle support.

**Comment by huyphams** [comment]
Oops, I forgot a double quotes case. I'm fixing it.

**Comment by huyphams** [comment]
I updated the build to support transform LIST and SET (currently not support MAP).
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
