### ISSUE TITLE
User Defined Type (UDT) not-displayed/displayed-unclear in Cassandra

### ISSUE THREAD

**Issue by lutomas** [TablePlus/TablePlus#612]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3.11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (120)

3. The steps to reproduce this issue:
If table contains 'User Defined Type' - it is not displayed properly or it is NULL. 
**PREPARE DB:**
```
DROP TYPE IF EXISTS software_type;
CREATE TYPE software_type (
    name text,
    version text    
);

DROP TYPE IF EXISTS person_type;
CREATE TYPE person_type (
    name text,
    age int    
);

drop table if exists abc1;
create table abc1 (
	pk int,
	program software_type,
	author person_type,
	PRIMARY KEY(pk)
);
```
**INSERT DATA**
`insert into abc1 (pk, program, author) values (1, {name: 'TablePlus', version: '1.2.0'}, {name:'Huy'});`

1. Results from `select * from abc1;` contains both problems (NULL and unclear UDT format).
2. Table preview does not show data properly too. 

### Possible solution
UDT could be displayed in JSON format. e.g:
`
{name:'Huy',age:NULL} and {name:'TablePlus',version:'1.2.0'}
`

### Thats a major problem IMHO!

**Comment by huyphams** [comment]
Thanks, @lutomas Your report is extremely helpful, it contains enough data to reproduce the bug. I'm fixing it.

**Comment by huyphams** [comment]
All issues were fixed. We're going to release a new update tomorrow including all the fixes 🙌🙌🙌

**Comment by lutomas** [comment]
Looking forward for release.
Thanks!
