### ISSUE TITLE
int/double column values displayed as '0'/'0.0' instead of 'null' in Cassandra

### ISSUE THREAD

**Issue by lutomas** [TablePlus/TablePlus#613]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3.11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (120)

3. The steps to reproduce this issue:
'int' and 'double' columns are '0', but it should be 'null' 
PREPARE DB:
```
drop table if exists abc1;
create table abc1 (
	pk int,
	name text,
	age int,
	balance double,
	PRIMARY KEY(pk)
);
```
INSERT DATA
`insert into abc1 (pk, name) values (1, 'Huy');`

'age' and 'balance' values from `select * from abc1;` shows '0' and '0.0'.
Table preview shows '0' and '0.0'.

Should be:
'age=null' and 'balance=null'

## Thats a major problem!

**Comment by huyphams** [comment]
Thanks @lutomas , it's fixed.
