### ISSUE TITLE
Cannot See Connected Database in Dark Theme Mode

### ISSUE THREAD

**Issue by dldereklee** [TablePlus/TablePlus#614]
If you switch to dark theme, the connected database in the top row is no longer visible (light font on a light background). Not a deal-breaker, but it would be nice if the font color could be fixed. 

![image](https://user-images.githubusercontent.com/20377366/44549557-51c6df00-a6d6-11e8-854d-86a1ec9bdda4.png)

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
120

3. The steps to reproduce this issue:
Switch to dark theme

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by Tungtono** [comment]
Hey @dldereklee, actually, you can click on that status bar and change the color from the popup
<img width="701" alt="color" src="https://user-images.githubusercontent.com/10219818/44559965-758e3180-a777-11e8-868a-3a5440ed3a31.png">

**Comment by dldereklee** [comment]
Didn't know that was a functionality. Thanks!
