### ISSUE TITLE
No functions displayed

### ISSUE THREAD

**Issue by gotsour** [TablePlus/TablePlus#615]
1. Driver: PostgreSQL 8.2.15

2. TablePlus build: Version 1.0 (121)

3. The steps to reproduce this issue: Well after being connected to my database, all the tables are loaded but not the functions. I can't see any functions in all my schemas.

**Comment by huyphams** [comment]
PostgreSQL 8.2, looks like you are using redshift? Let me take a look and fix it. Thanks for letting me know.

**Comment by gotsour** [comment]
Hi. Did you managed to fix the problem?

**Comment by huyphams** [comment]
Hey @gotsour please update to build 122 to get the fixes 👍
