### ISSUE TITLE
Cancelling a query hangs the UI

### ISSUE THREAD

**Issue by anentropic** [TablePlus/TablePlus#619]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v1.0 (122)

3. The steps to reproduce this issue:
Start a long running query
Press the cancel button
The button text changes to 'Cancelling...' and it goes greyed out
The query window no longer accepts input

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @anentropic, This is one of know issue, canceling query over ssh in PostgreSQL Driver was not optimized. 
It works when connect directly but not work over SSH. I'm still trying to optimize it.

**Comment by anentropic** [comment]
I'm not using an ssh connection though

**Comment by huyphams** [comment]
Thanks @anentropic looks like a bug, I will check it.

**Comment by anentropic** [comment]
Our postgres db is in AWS RDS in case that is significant

**Comment by tylerb** [comment]
I am experiencing this as well. It's exceptionally frustrating not being able to kill the running query.

Not only does the UI hang, the query continues to run until it is completed.

**Comment by davidADSP** [comment]
Also getting this bug against a MSSQL DB

**Comment by alvint** [comment]
Similar with Oracle, although just the tab hangs.

**Comment by huyphams** [comment]
Hey @alvint I made a mistake in Oracle when canceling a query. I have fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 Could you give it a try?

**Comment by alvint** [comment]
Yep, works fine!

**Comment by alvint** [comment]
...Something odd, though. I tested by creating a recursive CTE that doesn't end:

```
with foo(n) as (
  select 1 from dual
  union all
  select n + 1 from foo where n > 0
)
select * from foo;
```

When I cancel, the number of actual rows doesn't line up with the row count at the bottom:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/622202/46551666-57533f80-c8a6-11e8-94dc-a585b6d92d36.png">

**Comment by alvint** [comment]
@huyphams Hmm, the row count is still off. It does seem much faster though.

**Comment by alvint** [comment]
In fact, if I cancel the query very quickly, I can get a very large difference. At the bottom I've gotten "260 rows" while only 11 were displayed. No big deal though.

**Comment by alvint** [comment]
@huyphams I'm now also getting a `ORA-01742: comment not terminated properly` error on queries with comments in them, for example `select * from client_users where id = 1 /* foo */ ;`.  This works fine in previous versions.

**Comment by huyphams** [comment]
Ops my mistake when adding support PL/SQL https://github.com/TablePlus/TablePlus/issues/785
I have fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Now TablePlus supports PL/SQL Syntax:
```
DECLARE 
   message  varchar2(20):= 'Hello, World!'; 
BEGIN 
   dbms_output.put_line(message); 
END;
/;
```

**Comment by alvint** [comment]
@huyphams Yep, comments work fine.

**Comment by jaslo** [comment]
Has this fix been incorporated into the release? I'm running 2.2 and I am seeing this postgres 9.6 (RDS) without SSH connection.  The connection seems to be unusable after killing a query.

**Comment by huyphams** [comment]
TablePlus now can kill unresponsive query on both PostgreSQL and redshift
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if anyone encounters any problems.

**Comment by mtami** [comment]
> TablePlus now can kill unresponsive query on both PostgreSQL and redshift
> Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
> Let me know if anyone encounters any problems.

Hi @huyphams ,
Is this patch part of TablePlus Version 3.12.8 (369) now ?
Thanks.
