### ISSUE TITLE
Connection is not allowed with empty password field

### ISSUE THREAD

**Issue by arsenicoco** [TablePlus/TablePlus#62]
When trying to connect to a PostgreSQL database, connection is not allowed with empty "password" field.
This should be allowed.

**Comment by huyphams** [comment]
Connecting without a password is a convenient way to connect to local database. I will add this feature.

**Comment by huyphams** [comment]
Update is coming.
![nopassword](https://user-images.githubusercontent.com/3654622/29993238-a23a1384-8fdb-11e7-9c21-00575c1bdb30.png)
