### ISSUE TITLE
Maybe a bug: Different execution plan vs MySQLWorkbench

### ISSUE THREAD

**Issue by yuqiang-yuan** [TablePlus/TablePlus#620]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 122

3. The steps to reproduce this issue:
    I have a sql statement which has named parameters in it (I have set the named parameters' value in the same database session), and I use `explain` in TablePlus and MySQLWorkbench (they connect to the same database), I got different results, please see the attached screen captures for detail.  I am not sure if this is a bug or something else happened. Would you please have a try?

`explain` sql statement in TablePlus:

![5f0dc902-46a8-4352-9809-4d6f734efdc5](https://user-images.githubusercontent.com/15667885/44763375-9393d180-ab7d-11e8-8390-f4c48c837160.png)

Explain button in MySQLWorkbench:

![99f3e077-e069-4d5a-9029-bbbde17d628c](https://user-images.githubusercontent.com/15667885/44763397-aa3a2880-ab7d-11e8-857c-2697168e3c9a.png)

The key in the table `itr` is not the same in TablePlus and in MySQLWorkbench.

Thanks and best regards,

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
In TablePlus, we use the async method to fetch data, maybe it's different with workbench, but I will investigate more. Thank you.

**Comment by huyphams** [comment]
I can't reproduce the issue, let me know if you still encounter this issue.
