### ISSUE TITLE
Undo in SQL window can crash TablePlus

### ISSUE THREAD

**Issue by samsamai** [TablePlus/TablePlus#622]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.3 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
122

3. The steps to reproduce this issue:
- Open an SQL window
- Pick something out of your SQL history
- Delete the last line of the query, which in my case was `AND ....`
- run the query
- undo twice results in a crash

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey, I've tried, but no luck to reproduce this issue, maybe it only happens in some special situations. 'til trying.

**Comment by samsamai** [comment]
Ok I did a bit more testing and it seems to be if undo is tapped a few times while the query is still going on.

Here is the query I was using which would take about 28s to get about 16,000 results from the remote DB:

```
SELECT
    *
FROM
    bookings
    JOIN billables ON billables.booking_id = bookings.id
WHERE
    billables.type = 'booking_cash'
    AND billables.description LIKE '%** Reschedule%'
```

So I:
- paste the query in
- delete the last line
- use shortcut key to run the script
- while the query is running and still fetching stuff I tap undo a few times

**Comment by huyphams** [comment]
Thanks for your explain, I just disabled undo/redo during execution time of the query. It's not the best solution but at least it prevents the crash.
TablePlus disable the editor because it wants to report exactly the error position after the result returned.

**Comment by samsamai** [comment]
👍 
Keep up the good work. I never liked working with SQL but TablePlus has actually made it enjoyable!

**Comment by huyphams** [comment]
Hey @samsamai you can access the build: Preferences > Receive Beta Updates (it's pretty stable for production).
