### ISSUE TITLE
Create Syntax on structure view

### ISSUE THREAD

**Issue by silverbux** [TablePlus/TablePlus#623]
It would be nice to have create syntax on structure view, just like on sequel pro.
Dump Item -> Copy Creation is nice but sometimes you just want to check or copy a specific column,
also you dont have to copy / paste the whole create syntax in a editor.

![image](https://user-images.githubusercontent.com/1888261/44913837-0f9a3f00-ad61-11e8-8b6b-429962d63eb5.png)

**Comment by huyphams** [comment]
Hey @silverbux did you try the definition button on the top right?

**Comment by silverbux** [comment]
got it! haha thank you!
