### ISSUE TITLE
Set search_path on connecting?

### ISSUE THREAD

**Issue by j-ro** [TablePlus/TablePlus#624]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Redshift

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

122

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

I'm looking for a way to set the search path for postgres/redshift when you establish a connection, so I don't have to run that sql command every time I log in. Is there a way?

**Comment by huyphams** [comment]
Currently, there is no way to do it. The best solution we're considering is put an option that load search path when switching between schemas.
We will inform you when its ready.

**Comment by huyphams** [comment]
Now, we can set the search path with bootstrap commands (the beta build supports this feature), thanks.
