### ISSUE TITLE
Restore fail to MySQL in Docker

### ISSUE THREAD

**Issue by Vesninandrey** [TablePlus/TablePlus#625]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
122

3. The steps to reproduce this issue:
- Create connection to local mysql (in docker) http://take.ms/xllt3
- Backup any database from this connection
- Try to import this backup back
- Got error: http://take.ms/tHYyP

Pay attention to IP in the error message. It's different from connection IP.

**Comment by huyphams** [comment]
Thanks @Vesninandrey let me check it.

**Comment by huyphams** [comment]
@Vesninandrey do you still experience this issue on the newest build 200? Thanks

**Comment by huyphams** [comment]
I can't reproduce the issue anymore.
