### ISSUE TITLE
Respect ENUM casing

### ISSUE THREAD

**Issue by MaartenGeraedts** [TablePlus/TablePlus#626]
1. Mysql 5.6.10-log
2. TablePlus build 122
3. 

TablePlus automaticly converts all enum values as UPPERCASE, ignoring the case they are in. Only when adding a new row, is the drop down with the possible values showing the true values. First, this conversion is only in the interface of TablePlus, but when changing the type, TablePlus will change the original values to the uppercase.

**Comment by huyphams** [comment]
thanks. It must be a bug. We will fix it.

**Comment by huyphams** [comment]
Hey @MaartenGeraedts TablePlus respects the casing, this bug probably because of the `collation`
Here is my setup, it shows enum with its casing.
<img width="470" alt="screen shot 2018-09-04 at 8 59 54 pm" src="https://user-images.githubusercontent.com/3654622/45035987-7ed7a200-b085-11e8-9bbb-0be19812ff18.png">
Let me check with another collation.

**Comment by huyphams** [comment]
I see, thank you!

**Comment by huyphams** [comment]
It's fixed, please update to build 125 :D

**Comment by MaartenGeraedts** [comment]
Thanks, just tested it and it works perfect now!

**Comment by neoshiva** [comment]
This was critical. When I changed is_nullable of the column and saved, the column data_type was also saved with UPPERCASE. As the result, all data in the column became UPPERCASE. 
It might have caused big problem in app using the lowercase value of the column. 
I wish you release this fix asap.

**Comment by huyphams** [comment]
Hey @neoshiva which build are you using?

**Comment by neoshiva** [comment]
Sorry, I used Build 122 because it was latest stable release in Changelogs page.
The latest one seems 125, right? 
Before to know that, I temporarily turned on Beta channel and updated to 127. 
Thanks.

**Comment by huyphams** [comment]
The current stable release is 125, I forgot to update the changelogs, I will do it tonight.
