### ISSUE TITLE
Tab issue

### ISSUE THREAD

**Issue by AndyTsneg** [TablePlus/TablePlus#629]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    MAC
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
     1.0
3. The steps to reproduce this issue:
     not big deal. When I saw tabs, I didn't know which tab I am using. Because there is no color or thing to tell me which tab I am working on. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's has been fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
TablePlus now shows tab color correctly when the workspace is inactive.
