### ISSUE TITLE
MSSQL issue

### ISSUE THREAD

**Issue by AndyTsneg** [TablePlus/TablePlus#630]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    MAC
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    1.0
3. The steps to reproduce this issue:
     I will get his message "DBPROCESS is dead or not enabled", when I query something. And then I can't query anything until I closed app completely and reopen. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I just added re-connect on the new build, it should fix this issue, feel free to re-open it if you still have this bug.
