### ISSUE TITLE
User experience recommendations

### ISSUE THREAD

**Issue by tarunkurma** [TablePlus/TablePlus#632]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oralce 12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 126

3. The steps to reproduce this issue:
My recommendations for improving user experience: 
 (1) Run Current sql based on cursor location (instead of closing the sql using the semicolon ';')
 (2) Balanced Parentheses to highlight open/close brackets
 (3) Allow use of colon ':' as sql parameter and ampersand '&' as Substitution parameter
 (4) Easier way to open and close tabs
 (5) Options to size columns in data grid based: Column Name width/Data size/Auto
 (6) Option to not highlight current selection. Personally, I do not like the gray background highlight in dark mode
 (7) Expand/Collapse subqueries
 (8) Add a space after autocomplete - When I type SE and press tab, the autocomplete converts to SELECT. For ease, it'd be great if a space is inserted after SELECT so I can continue typing. 

I like the product (I paid for it already 😁), so the above recommendations aren't necessarily negative feedback.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
1. Already, TablePlus detects current SQL based on cursor location, it can be everywhere in the SQL.
2. Already, but only when you move the cursor.
3.  
4. Does command + W, Command + T, Command + Return are the "easiest way"?
5. We're trying, the latest release has auto sizing column but it needs to be improved more.
6. Already, please click on the setting icon in SQL Query and choose 
<img width="407" alt="screen shot 2018-09-11 at 12 16 22 am" src="https://user-images.githubusercontent.com/3654622/45313049-ee530300-b557-11e8-8f6a-79990e13910e.png">

**Comment by tarunkurma** [comment]
Thank you for pointing me to Highlight query and pair brackets. 
Pair brackets does not seem to work from the open bracket side, or am I missing something?

Cursor location for current sql works only if prior query is closed with semicolon; i.e, it does not recognize an empty line as end of query:

![image](https://user-images.githubusercontent.com/43093425/45314293-5295a880-b4ff-11e8-8363-20161921410b.png)

**Comment by huyphams** [comment]
There are few issues need to be improved for Oracle. I will back to this issue tomorrow becauze it late in my timezone.
Good night and thank for the license 😁

**Comment by alvint** [comment]
If I can add something to the list, please consider adding the option not to select the text when using undo, redo, and CMD-/. When using CMD-/ especially, usually you just want to comment out a `where` clause and immediately rerun the query. But then the highlighted text is run instead, which is usually a syntax error*. Selecting the text only serves to add an extra step where you have to move the cursor to unselect it before rerunning the query.

* I'm embarrassed to admit how long it took me to figure out what was going on.

**Comment by huyphams** [comment]
Thanks @alvint very good point. I will improve it.

**Comment by alvint** [comment]
On (6) above, I like the highlight of the current query, but even in light mode it's a bit too noticeable for my taste. If customizing syntax highlighting is in the near future, can that be an option? If not, how about increasing the transparency or maybe just adding a vertical line to the left of the text to indicate the current query?

**Comment by huyphams** [comment]
Adding vertical line may be a good idea but it won't support this case, 2 queries in one line.
<img width="1146" alt="screen shot 2018-09-11 at 10 33 45 pm" src="https://user-images.githubusercontent.com/3654622/45370654-d42a2b00-b612-11e8-9523-e5474f96bfe9.png">

Changing color in preferences is possible.

**Comment by alvint** [comment]
Yep, good point!

**Comment by harryparkdotio** [comment]
This is somewhat relevant to this issue, so I thought I'd add it here.

The text cursor (the vertical line thing in between text) is hidden when moving it around using arrow keys in the latest update in the `SQL Query` tab

**Comment by huyphams** [comment]
Hi @harryparkdotio please download the build again here 
https://tableplus.io/release/osx/tableplus_latest

It should be fixed on that build.

**Comment by tarunkurma** [comment]
Could you please implement (8).
After pressing Tab/Enter for auto-complete, the cursor is placed at the end of the keyword and I have to insert an additional space or tab, and is annoying. May be because most of the other IDEs I use have this behavior and I have to unlearn it to use TablePlus.

**Comment by huyphams** [comment]
@tarunkurma maybe I can add an option, you're right, there are some editors have supported it and people might be used to it.

**Comment by martingalovic** [comment]
I still have issues with bracket highlighting on Postgres (version 204)

It works on the closing side of the bracket, but it just "blinks" and then the highlight is gone.

This is a problem when i have 200+ line query and try to match the brackets.

I would rather prefer something like `RubyMine` permanent highlight:
<img width="145" alt="Screenshot 2019-03-22 at 08 50 31" src="https://user-images.githubusercontent.com/6873980/54808131-9112d980-4c7f-11e9-8718-8c8303abf16f.png">

Thanks @huyphams - tableplus is a great tool for me despite this

**Comment by georgexsh** [comment]
matching parentheses highlight is a very helpful feature, please add it!
below is how sublime handle this:
<img width="147" alt="CleanShot 2019-04-30 at 10 44 43@2x" src="https://user-images.githubusercontent.com/32751/56938519-11f1aa80-6b35-11e9-9349-b95ac3944c55.png">

**Comment by mote0230** [comment]
Balanced brackets highlights does not work at all for me, on win10, both light and dark theme. Latest version

**Comment by huyphams** [comment]
Most of them are implemented, so I will close the issue
@mote0230 we will bring it to Windows soon.
