### ISSUE TITLE
Graphical overview of relationships

### ISSUE THREAD

**Issue by asjur** [TablePlus/TablePlus#636]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
125

3. The steps to reproduce this issue:
This is not a bug but a feature request.

I would like to see a graphical overview over a relational database like how Querious does it.
![Image of relationship overview](https://i.pinimg.com/originals/17/85/9f/17859f500a9ccc44fd0dcad2489f0810.png)

I find this extremely useful and keep both TablePlus and Querious around simply because of this one feature, I would love to be able to do this from TablePlus.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by daredrum** [comment]
I look forward to this feature too. Unfortunately in sake of graphical overview I have to use DBeaver tool for working with PostgreSQL :(

**Comment by JacekJMMJ** [comment]
2020 and we are still waiting...

**Comment by huyphams** [comment]
Soon! this year, for sure 😄

**Comment by huyphams** [comment]
It's supported via plugin system now (Command + L > Diagram)

**Comment by qiwang97** [comment]
> It's supported via plugin system now (Command + L > Diagram)

i find this plugin but hart to say ,how to use this plugin 😁？

**Comment by huyphams** [comment]
After installing the plugin, you can right click on the left sidebar and then select generate diagram

**Comment by SneX13** [comment]
@qiwang97 as @huyphams say, or 👇
<img width="508" alt="Screenshot 2020-09-11 at 12 53 28" src="https://user-images.githubusercontent.com/9866318/92916489-db68b700-f42d-11ea-9fdf-89df0813e5eb.png">

**Comment by qiwang97** [comment]
> @qiwang97 as @huyphams say, or if you want visual presentation of your tables with relationships 👇
> <img alt="Screenshot 2020-09-11 at 12 53 28" width="508" src="https://user-images.githubusercontent.com/9866318/92916489-db68b700-f42d-11ea-9fdf-89df0813e5eb.png">

thanks a lot

**Comment by rehan-cc** [comment]
It only works, for the tables that we select manually and click on "Generate Diagram selected Items". It would have been much better for reverse engineering purposes, if I could select a table and view all of its related tables in the diagrams without having to manually select each referenced table.

**Comment by Cerya** [comment]
> It only works, for the tables that we select manually and click on "Generate Diagram selected Items". It would have been much better for reverse engineering purposes, if I could select a table and view all of its related tables in the diagrams without having to manually select each referenced table.

@rehan-cc you can select all tables and then "Generate Diagram selected Items" 

<img width="723" alt="1" src="https://user-images.githubusercontent.com/8936063/193801717-9c911b9f-e7b7-4a23-bb1a-f6ee2e376a7d.png">

**Comment by JosephTLyons** [comment]
Just came in to say that the visualizer is extremely well done.  I'm blown away by the little animations when clicking on tables.  Quick question, what made you go with making it a plugin over a standard feature?
