### ISSUE TITLE
[Dark Theme] Black text on black background in SQL editor

### ISSUE THREAD

**Issue by johnbona** [TablePlus/TablePlus#637]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): 
PostgreSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 128

3. The steps to reproduce this issue:
When typing in the SQL editor using the dark theme, the text starts as black and only after a pause, does the text change to white or the color appropriate for the token making it hard to read what I've typed until syntax highlighting kicks in. With the dark theme enabled, text should start as white by default.

**Comment by johnbona** [comment]
Awesome! Thanks Huy for the quick fix.

**Comment by huyphams** [comment]
If it's an annoying bug, you can download the hotfix build here: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
