### ISSUE TITLE
can't open new connection by command + N

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#638]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* Build 128

3. The steps to reproduce this issue:
* when i try to make a new connection, TablePlus now open a new window instead of multi connection in one window. seem like you have change hot key from command+N to shift+command+k?

![image](https://user-images.githubusercontent.com/5211881/45489910-4d9f5600-b798-11e8-99e8-cd443eb2b574.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hmm, command + shift + K was used from the beginning and the command + N always open new windows as it should be.
