### ISSUE TITLE
Feature Request: Open new connection if existing connection is busy

### ISSUE THREAD

**Issue by tylerstillwater** [TablePlus/TablePlus#639]
If I have a long-running query going in one tab, then create another tab and try to run another query, the second tab hangs until the first tab has completed.

I would love to see TablePlus open a new connection if the existing connection is busy, so I can continue working in other tabs while one is occupied.

The current workaround for this is to open an entirely new window to the same server.

**Comment by alvint** [comment]
Related to issue #456?

**Comment by davidharrison92** [comment]
Is this expected soon? Currently this is really slowing me down (I'm using SQL Server)
