### ISSUE TITLE
150k line SQL query is extremly slow to edit and use

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#64]
I am not sure if this is an issue specific to Build 60, but now noticing if I have a 150k line length SQL query the app will be very slow, but in text editors and PgAdmin, I can paste SQL of such length no problem.

Enterprise users will often have queries of this length, we will need to be able to handle them

Thanks huy!
-Brian

**Comment by huyphams** [comment]
Sure @brian-crane it slow because parsing syntax function. I will focus on this issues. It is not about build 60.
