### ISSUE TITLE
[Feature Request] Save and automatically reopen workspace configuration

### ISSUE THREAD

**Issue by mrjones2014** [TablePlus/TablePlus#640]
I always open the same 2 database connections in my workspace; it would be great to have an option to automatically open your last opened "workspace"; essentially, instead of clicking the first connection on the splash screen, then adding a 2nd connection to the workspace, there should be an option to skip the splash screen altogether and automatically open the workspace with the same 2 connections I always open. Sort of like how IntelliJ IDEA has an option to automatically open your last opened project on startup.

Love the product so far, other than this!

**Comment by shanke** [comment]
This would be a nice feature.

**Comment by aik099** [comment]
@mrjones2014 , how you can open 2nd+ database in same workspace?

When I search & open database using `Command+P` shortcut it always puts it into new workspace. I can verify that by pressing `Show all workspaces` button on the toolbar.

**Comment by mrjones2014** [comment]
@aik099 sorry, I don't use this app anymore so I don't have it installed to look at. Maybe @shanke can tell you? ¯\_(ツ)_/¯

**Comment by huyphams** [comment]
it's released in the build 235. Thanks.

**Comment by vvo** [comment]
@huyphams Is there documentation on how to use this? Right now I have two databases opened in my workspace, as tabs on the left. But when I quit Table Plus and reopen it, it does not reload the two databases.

Where's the "save workspace" option? Thanks!

**Comment by oz-richardson-reclique** [comment]
We need this for Windows as well.
