### ISSUE TITLE
MSSQL date issue

### ISSUE THREAD

**Issue by AndyTsneg** [TablePlus/TablePlus#641]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MAC
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0(128)
3. The steps to reproduce this issue:
There is a column and the type is datetime. the value should like "2017-04-21 13:51:43.000". But on this. It shows "Apr 21 2017 01:51:43:000PM"
It's no a bug. But maybe you can provide a option and let us can decide what format is.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by AndyTsneg** [comment]
Actually you don't need to customize it. You just show origin value for datetime. Maybe the language you are using will format the datetime automatically.

**Comment by huyphams** [comment]
The value `Apr 21 2017 01:51:43:000PM ` is the original value returned by the driver. I was implemented in the driver, by have provided a config file but I don't want to include the text config in TablePlus. I'm still finding the way to change it (re-compile the driver for example).

**Comment by AndyTsneg** [comment]
OK. still try to fix it. Because it's not big deal. But important for engineer. Thanks.

**Comment by huyphams** [comment]
Duplicated with: https://github.com/TablePlus/TablePlus/issues/594
It's fixed and will be released on Monday.
