### ISSUE TITLE
"open connection" window should add a search filter?

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#643]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* Build 128

3. The steps to reproduce this issue:
* use command + shift + k open "open connection" window, can you add a filter here, so i can find my db quickly.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's added on the build 200! Thanks for the suggestion!
