### ISSUE TITLE
The test connection on postgresql is working but the "connecting to database" message keeps appearing when click connect

### ISSUE THREAD

**Issue by eternalBlast** [TablePlus/TablePlus#644]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
128
3. The steps to reproduce this issue:
- Create 2 databases in a single server
- Try connect to the fiirst one. It can connect and load all database tables.
- Try connect to the second. You can test and it shows green of required fields. But, When you click connect, the "Connecting to Database" keep appearing and won't show the database tables.

**Comment by huyphams** [comment]
Hey thanks, let me check it.

**Comment by eternalBlast** [comment]
ok @huyphams. Thanks, please notify me when this issue has been fixed.

**Comment by huyphams** [comment]
Hi @eternalBlast sorry for the late response but I can't reproduce it, I have a lot of databases in a single server.
I have tried with localhost, amazon ec2, and some vps, none of them having trouble.

**Comment by eternalBlast** [comment]
Do you try Postgres? FYI, i am using nginx server. The first database can connect and not having issue. When i try the second database using same server using test, it's success. However, when you click connect the connecting message keeps appearing. It don't show another popup too.

**Comment by huyphams** [comment]
Could you send me a screenshot or a gif via huy@tableplusapp.com?

**Comment by eternalBlast** [comment]
Hi @huyphams I have sent it.
