### ISSUE TITLE
Can not restore database for MySQL 8

### ISSUE THREAD

**Issue by jmfederico** [TablePlus/TablePlus#645]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8 on macOS
MySQL installed via HomeBrew

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
128

3. The steps to reproduce this issue:
I have a connection to a MySQL 8 database.
When restoring a database to that connection the restore window won't let me select version 8, and the restore then fails because of that.

Attaching screenshots

- Connection set as MySQL 8:

![screen shot 2018-09-14 at 11 01 38](https://user-images.githubusercontent.com/237977/45561727-09e73380-b80e-11e8-9621-f5360c1ad50d.png)

- Restore won't let me select version 8

![screen shot 2018-09-14 at 11 03 32](https://user-images.githubusercontent.com/237977/45561909-77935f80-b80e-11e8-8114-fa2d8c5c78c7.png)

- Restoration fails

![screen shot 2018-09-14 at 11 02 15](https://user-images.githubusercontent.com/237977/45561743-123f6e80-b80e-11e8-9de4-dbc62d6c2ae3.png)

**Comment by huyphams** [comment]
It's fixed on build 142.

**Comment by abrambailey** [comment]
I am on build 156 and cannot select mysql 8 on the backup prompt. 

![image](https://user-images.githubusercontent.com/978462/48642975-06a22c80-e9a4-11e8-9ca9-5d2913799a31.png)

**Comment by huyphams** [comment]
Hi @abrambailey TablePlus only contains MySQL 8 driver but not binaries, that's why it won't be in the dropdown, You can use MySQL 5.7 to perform backup, it works just fine.
