### ISSUE TITLE
Restoring database with no password fails

### ISSUE THREAD

**Issue by jmfederico** [TablePlus/TablePlus#646]
Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5 via Docker

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
128

3. The steps to reproduce this issue:

I have a connection to a MySQL 5 database with root user and no passwors.
When trying to restore a database, it fails with  "**Access denied for user 'root'@'172.17.0.1' (using password: YES)**"

It should NOT have used a password. The connection has no password set.
Attaching images.

![screen shot 2018-09-14 at 11 46 15](https://user-images.githubusercontent.com/237977/45563724-d8716680-b813-11e8-8082-4a9770260dea.png)

![screen shot 2018-09-14 at 11 41 17](https://user-images.githubusercontent.com/237977/45563659-a6f89b00-b813-11e8-8db0-59edb493fa81.png)

**Comment by huyphams** [comment]
We're working on this issue and https://github.com/TablePlus/TablePlus/issues/645
it will be released in the next update.
