### ISSUE TITLE
CSV+Cockroach 2.1.0: Create table error, please check your mapping type

### ISSUE THREAD

**Issue by pouledodue** [TablePlus/TablePlus#647]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cockroach CCL v2.1.0-beta.20180910

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
128

3. The steps to reproduce this issue:
Import any CSV file

---

same CSV file works ok when importing into Postgres

**Comment by huyphams** [comment]
Thanks, let me check it.

**Comment by huyphams** [comment]
Hey, @pouledodue it would be great if you can give me an example of CSV, around 5~10 rows. I can't reproduce the bug. I suppose it only happens with some special column type.

**Comment by pouledodue** [comment]
hi!
Seems to be the error message that is misleading.
When I check "Create new table" and the table already exists it should print "table already exists" instead of "check mapping types".
The reason I thought the table did not exist is because of #648

**Comment by pouledodue** [comment]
Also, currently if I have a CSV file named "allo.csv" it tries to create "allo" table. Maybe  it could try to increment name "allo_1", "allo_2" when "allo" already exists.
Or better, the name of the table should be editable at import, with a default of "allo_1", "allo_2"...

**Comment by huyphams** [comment]
Thanks for pointing it out, I will improve it.
