### ISSUE TITLE
Can't list tables with Cockroach CCL v2.1.0-beta.20180910

### ISSUE THREAD

**Issue by pouledodue** [TablePlus/TablePlus#648]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cockroach CCL v2.1.0-beta.20180910
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
128
3. The steps to reproduce this issue:
connect to a CR db and try to list tables in the left pane; the pane keeps being empty;

**Comment by huyphams** [comment]
Thanks @pouledodue let me check it,
btw, can you take a look at this issue? https://github.com/TablePlus/TablePlus/issues/647

**Comment by pouledodue** [comment]
and when importing CSV, the `Select a table...` dropdown is empty even when there is tables in the db

**Comment by huyphams** [comment]
I fixed the bug on CockroachDB beta: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Now, I only have 199 issue remaining lol.

**Comment by pouledodue** [comment]
downloaded the zip but the .app fails to start
```
18-09-20 04:10:29,703 com.apple.xpc.launchd[1]: assertion failed: 15G17023: launchd + 188572 [9EA1B2C3-81E9-3CDE-A414-C029FC3DBBE8]: 0x5
18-09-20 04:10:29,703 com.apple.xpc.launchd[1]: Host-level exception raised: pid = -1, thread = 0x74253, exception type = 0xd, codes = { 2097152 }, states = { 0 }
18-09-20 04:10:29,703 com.apple.xpc.launchd[1]: (com.tinyapp.TablePlus.281312[29766]) Service exited due to signal: Trace/BPT trap: 5
```

**Comment by huyphams** [comment]
I built it with Xcode 10 (just updated Xcode yesterday), probably there's some compatible bug, are you using High Sierra?

**Comment by pouledodue** [comment]
El Capitan

**Comment by huyphams** [comment]
Are you using MacBook Pro with HDD, I'm using Parallels EL Capitan but it works?
<img width="1097" alt="screen shot 2018-09-20 at 3 16 49 pm" src="https://user-images.githubusercontent.com/3654622/45805167-40c6b900-bce8-11e8-8432-300bfc59ec6a.png">

**Comment by huyphams** [comment]
I updated the build with Xcode 9, can you give it a try @pouledodue? 
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Thanks.

**Comment by huyphams** [comment]
Wait, I figured out the problem.

**Comment by huyphams** [comment]
I fixed the build, it will work now, you can download it with the same dropbox link above.

**Comment by pouledodue** [comment]
works
