### ISSUE TITLE
App crashing after hitting 'SQL query' button

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#65]
After hitting the button to open a new SQL query my app is crashing.  

Something seems less stable about using SQL queries in the 60 release.

**Comment by brian-crane** [comment]
yes something terrible has happened, and now even in old builds I cannot run SQL queries.

TablePlus is unusable and nonfunctional for me right now...

**Comment by brian-crane** [comment]
Oh, I see the issue - Since the last query I used was 150k lines in length, when opening SQL Query window it tries to bring up this same 150k line query, which breaks the app.

Like mentioned in other post, there must be a more efficient way to display this text, other editors dont have this issue handling long Queries.

**Comment by huyphams** [comment]
Sorry for the crash :( @brian-crane I will try to fix this bug and release hotfix for you today.
The  `SQL Query` was crashed because of 150k lines is too much for SQL syntax parsing.

**Comment by brian-crane** [comment]
thanks for quick response Huy - this is not too big of a deal since I only need to run a query that large very rarely.  Don't stay up all night with the hotfix! 

Thanks,
--Brian

**Comment by huyphams** [comment]
Hi @brian-crane maybe you don't know, It 10:47 AM (+7) at my country now. Coding and make customer happy is my hobby 😁

**Comment by huyphams** [comment]
I just temporary disable query > 50k characters to prevent crash.
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

Then I will optimize parsing function and streaming query for the next build.

**Comment by brian-crane** [comment]
Oops didn't mean to close: 

Also wanted to say I love this new feature, where you can click on the arrow to the see the table linked.  You have no idea how useful this is for my team, because we have a lot of mappings between different tables.  Well done again Huy!

![screen shot 2017-08-30 at 2 06 59 pm](https://user-images.githubusercontent.com/7946786/29895080-a012bba2-8d8c-11e7-8757-37e091954f19.png)
![screen shot 2017-08-30 at 2 06 46 pm](https://user-images.githubusercontent.com/7946786/29895091-aa43b5ae-8d8c-11e7-9dd8-56bf223a81f3.png)
