### ISSUE TITLE
[Feature Request] History of filtering

### ISSUE THREAD

**Issue by yazumoto** [TablePlus/TablePlus#650]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0(128)

SQL has history. But record filtering of Table has no history now.
Please add this feature.

**Comment by huyphams** [comment]
It now remembers all the filters. Thanks.
