### ISSUE TITLE
Unable to view a table without an "id" - column "id" does not exist

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#651]
Which driver are you using and version of it (Ex: PostgreSQL 10.0): __PostgreSQL 9__
Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): __1.0 (128)__

**The steps to reproduce this issue:**

Click on the sidebar for a table that does not have an `id` field. It Shows this error message

![screen shot 2018-09-19 at 11 36 56 am](https://user-images.githubusercontent.com/125599/45764334-7d1eea00-bc00-11e8-933f-4f40b5aa2d68.png)

I assume you're explicitly querying this in order to allow inline updates. However, some tables just don't have an ID and we'd still like to view the data within it.

**Comment by huyphams** [comment]
I think something weird just happened, I'm not explicitly querying with ID.
<img width="1093" alt="screen shot 2018-09-19 at 10 42 03 pm" src="https://user-images.githubusercontent.com/3654622/45764589-3d3a2000-bc5d-11e8-92c2-1eb0c6079249.png">

**Comment by huyphams** [comment]
I think TablePlus has failed to detect primaries key of `settings` table, that's the bug. If there is no id field, but your image shows that it has `key,id` as primary. I will try to reproduce this bug.

**Comment by nathanpalmer** [comment]
If it helps, here is the schema

![screen shot 2018-09-19 at 11 48 17 am](https://user-images.githubusercontent.com/125599/45764993-ebb07780-bc01-11e8-8957-67e3caea600d.png)

```sql
/*
This script was generated by TablePlus. It only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.
*/

-- Table Definition
CREATE TABLE "public"."settings" (
    "key" text,
    "value" jsonb,
    "created_at" timestamp DEFAULT '2017-09-30 03:45:28.479605'::timestamp without time zone,
    "updated_at" timestamp DEFAULT '2017-09-30 03:45:28.479605'::timestamp without time zone,
    PRIMARY KEY ("key","id")
);
```

But the primary key doesn't have ID in our SQL structure. Here is the statements from our app

```sql
--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key text NOT NULL,
    value jsonb NOT NULL,
    created_at timestamp without time zone DEFAULT '2017-09-30 03:45:28.479605'::timestamp without time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT '2017-09-30 03:45:28.479605'::timestamp without time zone NOT NULL
);

--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);
```

**Comment by huyphams** [comment]
There is a case that can lead to this scenario>
1. Using TablePlus connect to the database.
2. Drop ID from that table by the terminal or some other application.
=> TablePlus still cached the result but the ID was gone.

But I don't think it's the case above. Did you close the app and reconnect to the database?

**Comment by nathanpalmer** [comment]
I just quit the app entirely, started back up, and then clicked that table. Still comes up with the error.

**Comment by nathanpalmer** [comment]
Now.. depending on how you're using schemas. There are two `settings` tables in this same database. One of them *does* have an id field. But it's in a separate schema. 

```sql
/*
This script was generated by TablePlus. It only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.
*/

-- Sequence
CREATE SEQUENCE IF NOT EXISTS "app"."app.settings_id_seq";

-- Table Definition
CREATE TABLE "app"."settings" (
    "id" int4 DEFAULT nextval('app.settings_id_seq'::regclass),
    "registry_id" int4,
    "project_id" int4,
    "data" jsonb DEFAULT '{}'::jsonb,
    "enabled" bool DEFAULT false,
    "created_at" timestamp,
    "updated_at" timestamp,
    CONSTRAINT "fk_app_settings_registry_id" FOREIGN KEY ("registry_id") REFERENCES "app"."registry"("id")
);
```

I wonder if it's finding the wrong table here when building that query. These both exist:

```sql
select * from app.settings
select * from public.settings
```

**Comment by huyphams** [comment]
hmmm, I have handled this case, I always append schema when getting primary. Let me check it again.
Thank for the detail, it's super helpful.

**Comment by huyphams** [comment]
It seems to be fixed for me on this build, thanks @nathanpalmer 
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by nathanpalmer** [comment]
thanks! i’ll test it out when i’m near a computer
