### ISSUE TITLE
Table filtering regex issue

### ISSUE THREAD

**Issue by m8rge** [TablePlus/TablePlus#657]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
129

3. The steps to reproduce this issue:
- filter tables by "ing$" to find all tables end with "ing". Works:
![2018-09-21_18-05-10](https://user-images.githubusercontent.com/575777/45882921-0c76f980-bdc9-11e8-950d-dd46bb7b45cf.png)
- filter tables by "^ing$". I except to see empty filtered table list. Reality:
![2018-09-21_18-05-23](https://user-images.githubusercontent.com/575777/45882969-2e707c00-bdc9-11e8-9363-05260107650f.png)

**Comment by huyphams** [comment]
Hi sorry because of the late response. I fixed this issue, it will be released on the next update. Thank you so much for the feedback!
