### ISSUE TITLE
SQL query window syntax highlight/formatting issue

### ISSUE THREAD

**Issue by greggomalley** [TablePlus/TablePlus#658]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 10.4

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
123

**3. The steps to reproduce this issue:**
One of the queries that I regularly use in the sql query tab window seems to cause an issue with the syntax highlighting and formatting of all further queries in the window. The problem seems to stem from the failure to identify the character `'` as starting a string in the text `ARRAY['["whatever"]']` of the query. You should be able to reproduce the problem by placing the query below in a SQL query window.

```
SELECT
    path
FROM
    groups
WHERE data -> 'group_tags' @> ANY (ARRAY ['["whatever"]']::jsonb[])))
```

**Comment by huyphams** [comment]
I know the reason, because I have handled the highlight syntax for SQL Server so `[ ]` are treated as beginning a quote.
TablePlus should use different rules for a different driver it supports.
