### ISSUE TITLE
In data preview window, column name is unnecessarily short

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#66]
Hi Huy, 

Noticed when viewing data column names are shortened but they don't need to be! There is plenty of space.

For example, below it should continue try to show as much of "store_to_tenant_exchange_rate" as possible before getting too near to the "numeric" part.

![screen shot 2017-08-30 at 2 20 32 pm](https://user-images.githubusercontent.com/7946786/29895589-82bb3aa0-8d8e-11e7-8a3f-bf2e0663843e.png)

Thanks,
-Brian

**Comment by huyphams** [comment]
I just increased width of row viewer 👍 
<img width="277" alt="screen shot 2017-08-31 at 10 24 35 am" src="https://user-images.githubusercontent.com/3654622/29905069-9d779b56-8e36-11e7-89c4-64ed21db6491.png">

**Comment by brian-crane** [comment]
Im excited about that b/s I am seeing in the corner of the image.

Would be very nice to see the rate at which I am downloading information from server.
