### ISSUE TITLE
Feature Request: Auto-select table name in sidebar after using Search Anything

### ISSUE THREAD

**Issue by kennonb** [TablePlus/TablePlus#662]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 130

3. The steps to reproduce this issue:

* Open Connection
* Press CMD+P to open Search Anything
* Type table name
* Press enter
* Tab opens with table, but sidebar doesn't reflect the table you're viewing

–

This is just to help me with visually seeing where I'm at while hopping around a database. 😊 

Thanks for the great app!

**Comment by huyphams** [comment]
Great idea.
