### ISSUE TITLE
Feature Request: Mount a directory of sql files

### ISSUE THREAD

**Issue by bsramin** [TablePlus/TablePlus#663]
It would be nice to have the possibility to mount an external directory of sql files, with the possibility to commit on git, to manage all the snippets.
Useful for sharing snippets in a team.

**Comment by huyphams** [comment]
We already supported it.
Please use this command:
```
ln -s link_to_your_repo  ~/Library/Application\ Support/com.tinyapp.TablePlus/Cache/Favorite
```
