### ISSUE TITLE
Invalid host private key

### ISSUE THREAD

**Issue by Puller** [TablePlus/TablePlus#664]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
132

3. The steps to reproduce this issue:
Create a connection using SSH as root and use a private key (ecdsa).
Login via SSH directly in terminal works...

It seems, we can't use elliptic ssh keys.

**Comment by huyphams** [comment]
Hi @Puller currently, TablePlus doesn't support `ecdsa`. I tried to update the lib the newest version which supports `ecdsa` but unfortunately, it caused some unexpected crash bugs.
I will come back to it later.

**Comment by huyphams** [comment]
Hey @Puller I just updated the ssh lib, now it supports ecdsa key: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Can you give it a try?

**Comment by huyphams** [comment]
It was released on the build 149 beta.
