### ISSUE TITLE
Authentication plugin 'mysql_old_password' cannot be loaded

### ISSUE THREAD

**Issue by rspreafico-sgi** [TablePlus/TablePlus#665]
Get this error when trying to connect to MySQL 5.x DB:

Authentication plugin 'mysql_old_password' cannot be loaded: dlopen(/usr/local/Cellar/mysql/5.7.22/lib/plugin/mysql_old_password.so, 2): image not found

Looks like it's trying to use mysql from Homebrew, but this is long gone on my laptop. Sequel Pro can connect to the mySQL database from the same Mac laptop TablePlus is running on.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Attemping connection to mySQL database 5.x.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 132

3. The steps to reproduce this issue:

- Create connection
- Select mySQL 5.x, add host, user and password (the same as I have those working in Sequel Pro)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @rspreafico-sgi  please select this:
<img width="603" alt="screen shot 2018-09-26 at 7 01 48 am" src="https://user-images.githubusercontent.com/3654622/46049705-0f237700-c15a-11e8-9c38-3c0c3a62edcc.png">

**Comment by rspreafico-sgi** [comment]
Hi @huyphams 

thanks for your response. Yes I do have selected MySQL 5.x (see above steps to reproduce the issue).

Now, if I try to connect to the local DB (127.0.0.1), the connection appers to work (I get an access denied error I guess for wrong psw). However, when I try to connect to a server reachable via Sequel Pro, I get the error above.

Thanks

**Comment by huyphams** [comment]
It because we used the MySQL from the homebrew. I will try to compile it myself next time 😁

**Comment by huyphams** [comment]
@rspreafico-sgi can you try this build and let me know the result?
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by rspreafico-sgi** [comment]
Will gladly do, but Dropbox is firewalled by my organization, can you share by another mean?

**Comment by huyphams** [comment]
Ok, I uploaded it to my amazon S3: https://s3.amazonaws.com/tableplus-osx-builds/beta/TablePlus.zip

**Comment by rspreafico-sgi** [comment]
Similar error, but path is now slightly different: `/usr/local/mysql/lib/plugin/mysql_old_password.so`

**Comment by huyphams** [comment]
I have researched about this issue and looks like it was removed by Oracle (the maintainer of MySQL).
```
Passwords that use the pre-4.1 hashing method are less secure than passwords that use the native password hashing method and should be avoided. Pre-4.1 passwords are deprecated and support for them (including the mysql_old_password plugin) was removed in MySQL 5.7.5. For account upgrade instructions, see Section 6.5.1.3, “Migrating Away from Pre-4.1 Password Hashing and the mysql_old_password Plugin”.
```
I customized this build with the MySQL lib 5.6, I haven't tested it but I think it will work. The same link about.
https://s3.amazonaws.com/tableplus-osx-builds/beta/TablePlus.zip

**Comment by rspreafico-sgi** [comment]
Thanks for going to the length of making a custom build. Given the issue as you describe it, I think the database itself will need to be upgraded on our end, such that we can use the latest tools and not have to rely on deprecated features. Thanks again!
