### ISSUE TITLE
[BUG]commit update will launch "open connection" window auto

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#668]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
* MySQL 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* Build 133

3. The steps to reproduce this issue:
* modify some record
* commit change
* then "Open connection" window will be launched auto（can not reappear steady）

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's fixed in recently build!
