### ISSUE TITLE
Support for MacOS Mohave dark theme

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#669]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
any

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 132

3. The steps to reproduce this issue:
Install MacOS Mohave, choose system dark theme

**Comment by huyphams** [comment]
You can switch to the dark theme by press: `command + ,`
it's the Mojave theme, from the new version, we will add an option that allows TablePlus to switch theme auto based on the OS.

**Comment by PVGrad** [comment]
Oh! Cool.
Thanks

**Comment by huyphams** [comment]
it's exactly the same with Mojave theme.

<img width="1188" alt="screen shot 2018-09-26 at 3 32 43 pm" src="https://user-images.githubusercontent.com/3654622/46067597-6c8ee680-c1a1-11e8-8ed4-9acdc61baecc.png">

**Comment by huyphams** [comment]
I added auto support on the build 135 (beta).
