### ISSUE TITLE
Feature request: ClickHouse support

### ISSUE THREAD

**Issue by oatiz** [TablePlus/TablePlus#670]
[ClickHouse](https://github.com/yandex/ClickHouse)

**Comment by resure** [comment]
@huyphams hi :) Is there any plans on [ClickHouse] support? It is quickly gaining popularity.

It has [ODBC driver][driver] and HTTP interface.

[ClickHouse]: https://clickhouse.yandex/docs/en/
[driver]: https://github.com/yandex/clickhouse-odbc

**Comment by mikejmills** [comment]
Yes please incorporate ClickHouse.

**Comment by mv200580** [comment]
Really desired feature!

**Comment by fartek** [comment]
Is this in the roadmap? 🙏  🙏

**Comment by mRs-** [comment]
This would be awesome!

**Comment by Flamefork** [comment]
ClickHouse supports MySQL protocol, and TablePlus works using it, but not quite.
- SQL queries work, which is awesome!
- tables sidebar is empty, which is a pity.

**Comment by bun4uk** [comment]
waiting for it

**Comment by sstubbs** [comment]
Support for this would be great.

**Comment by objque** [comment]
Yeah, this should be definitely useful!

**Comment by davidbirchmier** [comment]
+1 for this request 🙏

**Comment by arikai** [comment]
Crave this feature!

**Comment by cristaloleg** [comment]
Any updates? Can we help you somehow? Kindly ping @huyphams

**Comment by qoega** [comment]
Hi! 
We know many ClickHouse users that will be grateful for this feature.
By the way ClickHouse supports MySQL interface: https://clickhouse.tech/docs/en/interfaces/mysql/
and PostgreSQL https://github.com/ClickHouse/ClickHouse/pull/10242

You can ask for help from ClickHouse community in any convenient way from here
https://clickhouse.tech/#community

**Comment by carldunham** [comment]
@Flamefork did you have to do anything special to get this to work? Just taking a naive approach didn't work for me. Will keep trying.

**Comment by massyah** [comment]
@carldunham my table plus can connect to clickhouse when clickhouse exposes a mysql compatible interface. I've just added the fragment 
```
<mysql_port>9004</mysql_port>
```
to the primary clickhouse config. 
However I cannot get tablePlus to browse the database, I can only run queries and retrieve the results.

**Comment by vgocoder** [comment]
any progress？

**Comment by izaakschroeder** [comment]
+1

**Comment by mfridman** [comment]
+1

**Comment by ciarans** [comment]
+1

**Comment by jahilliard** [comment]
+1

**Comment by zain-bahsarat** [comment]
+1

**Comment by yuekun0707** [comment]
+1

**Comment by klokare** [comment]
would love this as well. thanks!

**Comment by egor-pisarev** [comment]
+1

**Comment by nikneroz** [comment]
Waiting since 2019. Please add this feature.

**Comment by patgu9** [comment]
+1

**Comment by huyphams** [comment]
Hi guys, I'm playing with ClickHouse right now, but not sure how popular it is, do you have any insight?

**Comment by blinkov** [comment]
@huyphams see https://clickhouse.com/docs/en/introduction/adopters/

**Comment by jahilliard** [comment]
It's the OLAP DB of the future. :)

https://clickhouse.com/blog/en/2021/clickhouse-raises-250m-series-b/

- https://blog.sentry.io/2019/10/25/how-to-mutate-data-in-a-system-designed-for-immutable-data
- https://blog.cloudflare.com/http-analytics-for-6m-requests-per-second-using-clickhouse/

**Comment by qoega** [comment]
If you will have some issues or questions, feel free to create issues on GitHub ClickHouse/ClickHouse.

**Comment by gebrits** [comment]
@huyphams can attest to above. Go-to already in some industries

general feel: Google trends against vertica / greenplum: TLDR: clickhouse trending up 

https://trends.google.com/trends/explore?date=today%205-y&q=clickhouse,vertica,greenplum

**Comment by alisalahio** [comment]
+1 🙋🏻‍♂️

**Comment by kilingzhang** [comment]
+1 🙋🏻‍♂️

**Comment by windware-ono** [comment]
I think these [names](https://clickhouse.com/use-cases/) are convincing enough. I never heard bad words about ClickHouse.

Also supported by data pipelines tools like [Telegraf](https://docs.influxdata.com/telegraf/v1.21/plugins/#clickhouse), [LogAgent](https://sematext.com/docs/logagent/output-plugin-clickhouse/), [Vector](https://vector.dev/docs/reference/configuration/sinks/clickhouse/), [RudderStack](https://www.rudderstack.com/docs/data-warehouse-integrations/clickhouse/) and [Jitsu](https://jitsu.com/docs/destinations-configuration/clickhouse-destination).
And graphing through [Grafana](https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/) and [Metabase](https://github.com/enqueue/metabase-clickhouse-driver).

(Those are just open source solutions.)

**Comment by huyphams** [comment]
I'm working on it, hopefully, we can have a beta this week.

**Comment by huyphams** [comment]
<img width="1475" alt="Screen Shot 2022-03-31 at 6 54 17 PM" src="https://user-images.githubusercontent.com/3654622/161049091-749758ca-9340-4cbf-97a1-c41053987165.png">

**Comment by huyphams** [comment]
If you want to download an early access build, please download it here: 

https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

Let me know if you have any issues with it.

**Comment by gauvins2** [comment]
Looks like a mac version -- you'd have a Linux version in the works? (Or am I missing something?)

**Comment by fredliang44** [comment]
> If you want to download an early access build, please download it here:
> 
> https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
> 
> Let me know if you have any issues with it.

I'm using tableplus to connect my clickhouse instance on M1 mac. I've validate the right port(9000 for clickhouse-client program), host, username, password, etc. But tableplus shows "unknown error" as img below

<img width="491" alt="image" src="https://user-images.githubusercontent.com/22412638/161592642-6c2bd132-c51d-48c8-a993-3053af445bde.png">

**Comment by huyphams** [comment]
It's on your M1 local but why does the IP begin with 16? Should it be 127.0.0.1? or localhost?

**Comment by fredliang44** [comment]
> It's on your M1 local but why does the IP begin with 16? Should it be 127.0.0.1? or localhost?

Sorry I haven't made it clear. I means I was using TablePlus on M1 mac, but the clickhouse instance is running on the cloud server.

**Comment by huyphams** [comment]
Are you sure that your server accepts public IP also your server exposes port 9000? Furthermore, are you sure that your ClickHouse server accepts connection from outside?

**Comment by gebrits** [comment]
@huyphams Just curious which protocol is used? Clickhouse's PG compatible wire protocol or it native protocol

**Comment by huyphams** [comment]
TablePlus ClickHouse Driver uses the native protocol (if you want to use PG or MySQL protocol, you must use PG or MySQL driver, of course ).

**Comment by fredliang44** [comment]
> Are you sure that your server accepts public IP also your server exposes port 9000? Furthermore, are you sure that your ClickHouse server accepts connection from outside?

Yeap, currently I'm using grafana connecting to the same CH instance with same native protocal. And I could connect to clickhouse with the DataGrip either. Is there anything further I could provide for you to debug the problem?

**Comment by huyphams** [comment]
Where is your grafana installed, is it in the same server with ClickHouse? I think DataGrip is using http protocol (port 8123) which is different from the native protocol. TablePlus is using native protocol on port 9000.

**Comment by fredliang44** [comment]
> 



> Where is your grafana installed, is it in the same server with ClickHouse? I think DataGrip is using http protocol (port 8123) which is different from the native protocol. TablePlus is using native protocol on port 9000.

On another server, what I intend to declare here is that the ClickHouse native 9000 port is working as expected and the connection works great when connecting from another host(including current device). But when trying to using TablePlus seems some problem occured. 

I'm using this grafana plugin(this one using the native clickhouse protocol): https://github.com/grafana/clickhouse-datasource?utm_source=grafana_add_ds

I have tried using tableplus debug mode, but nothing shows up when the "Unknow Error" shows up.

**Comment by huyphams** [comment]
So there is only 1 issue left, Does the ClickHouse server has an allowed IP list? your Grafana Server could be in the allowed list, please check it.

**Comment by fredliang44** [comment]
> So there is only 1 issue left, Does the ClickHouse server has an allowed IP list? your Grafana Server could be in the allowed list, please check it.

nope, I've already double checked.

**Comment by windware-ono** [comment]
Is it possible to also add the HTTP version of the protocol? This will allow reverse proxied instance to be accessed without SSH tunneling.

**Comment by huyphams** [comment]
We have improved the error message, now TablePlus will report the correct connection issue, download patch at: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by huyphams** [comment]
> Is it possible to also add the HTTP version of the protocol? This will allow reverse proxied instance to be accessed without SSH tunneling.

Unfortunately, the native driver does not support http protocol.

**Comment by fredliang44** [comment]
> We have improved the error message, now TablePlus will report the correct connection issue, download patch at: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

I've tried the release, it shows that my username or password is not correct. But I tried the same credentials in mysql port & protocol, it works as expected.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/22412638/162610448-befd3e7e-4ffb-4f2c-9f3f-0bb75311ebeb.png">

And I extracted the ClickHouse user configs as below, you could see there is no specific config about connection protocol

<img width="849" alt="image" src="https://user-images.githubusercontent.com/22412638/162610439-0607ab85-5cb1-48f9-a96c-67d0631665a6.png">

**Comment by fredliang44** [comment]
By the way, Import from URL seems not working for clickhouse connection, here is the sample url: clickhouse://username:password@clickhouse.example.com/database

<img width="642" alt="image" src="https://user-images.githubusercontent.com/22412638/162610679-ce41c44b-334e-48ef-a178-9f80dc69f321.png">

**Comment by huyphams** [comment]
Hi @fredliang44 thank you for the feedback. If you have a chance, please download this patch and see how it goes:
https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

**Comment by fredliang44** [comment]
> Hi @fredliang44 thank you for the feedback. If you have a chance, please download this patch and see how it goes: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0

Great! It works fine now, and Import from URL works as expected either~

**Comment by mdkraft** [comment]
Hi @fredliang44, I had the same authentication issue as @huyphams so I downloaded your patch. The authentication error went away and was replaced with a VERSION error:

`DB::Exception: Unknown function VERSION. Maybe you meant: ['version']: While processing VERSION()`

Is this a known issue?

**Comment by huyphams** [comment]
Hi @mdkraft could you run these queries and see how it goes?

SELECT version()

vs 

SELECT VERSION()

**Comment by mdkraft** [comment]
> Hi @mdkraft could you run these queries and see how it goes?
> 
> SELECT version()
> 
> vs
> 
> SELECT VERSION()

Lowercase "SELECT version()" returns 20.12.4.5.

Uppercase "SELECT VERSION()" returns:

`Query 1 ERROR: Code: 46, e.displayText() = DB::Exception: Unknown function VERSION. Maybe you meant: ['version']: While processing VERSION() (version 20.12.4.5 (official build))`

**Comment by harryhan1989** [comment]
query too slower than clickhouse-client,
same query"SELECT * FROM stock.a_minute_15 where date='2022-05-12' and time='2022-05-12 15:00:00'"
from tableplus: 
<img width="954" alt="image" src="https://user-images.githubusercontent.com/2442117/168549792-cfccdb9e-c212-4d1d-b087-a72aeaae7880.png">
from clickhouse-client
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/2442117/168549909-53a14b86-67c8-4d2a-8d52-f58228227962.png">

**Comment by harryhan1989** [comment]
the same query using dbeaver :
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/2442117/168551268-7a278cfb-814a-4dcb-b24e-174ddf529db9.png">
