### ISSUE TITLE
Bug: restoring with PG on an external drive containing a path with spaces

### ISSUE THREAD

**Issue by abournier** [TablePlus/TablePlus#671]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
10.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
132

3. The steps to reproduce this issue:
Restoring a Postgres dump located on an external drive containing one space in path.

Example path:
`/Volumes/Caviar\ Red\ 1To/iMac/25_septembre_2018.dump`

The error obtained:
![capture d ecran 2018-09-26 a 20 46 58](https://user-images.githubusercontent.com/6143197/46102061-b8578500-c1cd-11e8-9979-77f3ea320bb3.png)

**The same file copied to an internal drive, so with another path, works fine ! So I suppose it's a "path with spaces" bug.**

**Comment by huyphams** [comment]
It's fixed on build 142.
