### ISSUE TITLE
Newlines in JSON export are incorrectly escaped

### ISSUE THREAD

**Issue by dtkaias** [TablePlus/TablePlus#672]
Exports to JSON by both the *Copy Rows As* and *Export Results* features incorrectly escape newline characters with two backslashes instead of one. Eg. `\n` is rendered as `\\n`.

Database: PostgreSQL 10.4
TablePlus v1.0 Build 132

Steps to reproduce:
1. Run a query that includes newline charaters (\n or \r) in the  output, eg:
```
SELECT 'new
line' AS test
```
2. Right click the output row, and select *Copy Rows As* > *JSON*

3. Check the text copied to the clipboard:
Expeded:
```
  {
    "test": "new\nline"
  }
```

Actual:
```
  {
    "test": "new\\nline"
  }
```

**Comment by huyphams** [comment]
Thanks, I fixed it on build 135.
If you want to access the build before everyone. TablePlus > Preferences > Receive Beta Update. Then go check for updates...
