### ISSUE TITLE
code completion for tables not working if case doesn't match

### ISSUE THREAD

**Issue by alvint** [TablePlus/TablePlus#673]
oracle 12.x
build 133

This was working fine in earlier builds. For example, I have a table named `VENDORS` (all caps). Code completion at the end of the below fragments don't work:

`select * from vendors v where v.`
`select * from "vendors" v where v.`
`select * from vendors where vendors.`
`select * from vendors where `

However, code completion for the below works correctly:

`select * from VENDORS v where v.`
`select * from "VENDORS" v where v.`
`select * from VENDORS where VENDORS.`
`select * from VENDORS where `

**Comment by huyphams** [comment]
Thanks @alvint let me check what's happened. recently, I don't change anything in the completion module.

**Comment by huyphams** [comment]
I just fixed it. I'm going to release the build 135.
The auto-suggestion in Oracle is slow because there are a lot of tables.
Do you have any idea on these schemes, which schema should be ignored in the auto-suggestion?
 
<img width="343" alt="screen shot 2018-09-27 at 11 07 57 pm" src="https://user-images.githubusercontent.com/3654622/46159308-30937880-c2aa-11e8-9eab-90b9f9f2aa1e.png">

**Comment by alvint** [comment]
Thanks!

I'm pretty sure APEX_* and CTXSYS can at least get last priority or make loading them off by default. IIRC the APEX stuff is some sort of web framework that Oracle pushes but no one actually uses because of its tight coupling to the DB, and CTXSYS is data for Oracle's fuzzy text searches and you usually don't need to access them directly.

I think MDB is for message driven bean data and I've never seen them accessed directly in SQL either.

Of the remainder, the only ones I've seen used (occasionally) are SYS and SYSTEM.

**Comment by huyphams** [comment]
the build has been released with a ton of improvements:
<img width="812" alt="screen shot 2018-09-27 at 11 49 41 pm" src="https://user-images.githubusercontent.com/3654622/46161562-1066b800-c2b0-11e8-8959-6c1bf5611a9b.png">
