### ISSUE TITLE
Problems Displaying Fields/Columns with Money Attribute

### ISSUE THREAD

**Issue by farizzed** [TablePlus/TablePlus#675]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL Server 2016

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 132

3. The steps to reproduce this issue:
I have no idea how this happened. I just ran queries for fields that have money attribute and they show 2 digit decimal precision (0.00)

Noted: If the bug is related to data, please attach an example SQL data.

This is so infuriating, the update before Mojave (build 128) shows that queries for money include the normal 4 digits decimal precision (0.0000), but after updating to build 132, the display for Money changed into 2 digits decimal precision (0.00). The problem is, my current database I am working with, has fields with money attribute with 4 digits precision. When I tried to query with select, update, and insert. The queries successfully ran, but the display for money attributes only shows 2 digit precisions. Please, could you look into this matter? Or at least, if you could, please add the configuration for displaying money decimal precision. Thank you.

Note: I tried querying a simple select query
select cast(12.0012 as money) as disp_money. It shows 12.00. Normally (build 128), it shows 12.0012;

**Comment by farizzed** [comment]
![image](https://user-images.githubusercontent.com/11038943/46197804-ffac5580-c334-11e8-8cdb-f7abf3c926e8.png)

**Comment by huyphams** [comment]
@farizzed thanks for letting me know. Let me check this issue.

**Comment by huyphams** [comment]
Looks like it has happened a while ago now. I will try to figure out why it was rounded.
<img width="996" alt="screen shot 2018-09-28 at 3 58 39 pm" src="https://user-images.githubusercontent.com/3654622/46198903-bf020b80-c337-11e8-995a-04b6d22fc7a1.png">

**Comment by farizzed** [comment]
Okay thanks, I hope it will be resolved soon enough.

**Comment by farizzed** [comment]
I think you should check the free version. Because I just noticed, I got this rounding issue after upgrading my license. Before upgrading, the query result shows unrounded 4 digit precision money.

**Comment by huyphams** [comment]
@farizzed I fixed that bug, I will release it Monday. It's not related to the version or something, I just custom and recompile the SQL Server driver.

**Comment by farizzed** [comment]
Nice, Thanks for your swift reply
