### ISSUE TITLE
Bug: Cursor disappears when moving with the cursor keys in SQL editor

### ISSUE THREAD

**Issue by josefeg** [TablePlus/TablePlus#676]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (132)

3. The steps to reproduce this issue:
Write a query in the SQL editor, and the move around with the cursor keys to try and change the query. The cursor key disappears until it stops moving. This happend on OSX Mojave

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I fixed that issue a few days ago. it will be released in the next update (release on Monday).

**Comment by josefeg** [comment]
Thanks @huyphams
