### ISSUE TITLE
How do I create a new SQLite database?

### ISSUE THREAD

**Issue by m-thomson** [TablePlus/TablePlus#677]
This window wants me to select an *existing* SQLite database file but I'm trying to create a new one.

<img width="500" alt="screenshot_4bd55d" src="https://user-images.githubusercontent.com/5273016/46239606-6474a980-c34f-11e8-89ab-1c09d97f7a6d.png">

**Comment by Tungtono** [comment]
@m-thomson, you can create a SQLite database on Mac this way, it's quite easy:

- Open Terminal
- Navigate to the folder to store the database file
- Run **SQLite3 db_name.db** or **touch db_name.db** to create a new database file.

**Comment by m-thomson** [comment]
Yes, I know how to create one from the command line :-).

With respect, I don't think your app can claim to support SQLite databases if it *can't even create one*. 

I mean, come on. Thats the very first thing it needs to be able to do. What a frustrating experience.

**Comment by alvint** [comment]
@m-thomson I understand your argument because it would be trivial to support creating the file, but your logic is flawed. The app also supports Oracle. Are you saying that in order to **truly** support Oracle then TablePlus must be able to install an Oracle instance/create a new schema or DB on your computer?

**Comment by m-thomson** [comment]
You're right, the logic doesn't apply across the board, but it all comes down to **reasonable expectations**.

SQLite is known for its simplicity. That's its primary feature. When I read "supports SQLite" I have certain expectations. Like being able to create, open, read and write SQLite databases.

I'm not familiar with Oracle (but I know it's pretty enterprise-y). If I read "supports Oracle" I honestly don't know what to expect. Should a $50 app created by a small team support creating Oracle DB's? I have no idea if that is a reasonable expectation or not.

>The argument against this is the app's handling of different database systems would be inconsistent.

I'm able to create a MySQL DB in the App without issue so this is already the case.

**Comment by huyphams** [comment]
It's supported in some recent updates.

**Comment by mhkeller** [comment]
@huyphams what is the procedure for doing this now?

**Comment by mhkeller** [comment]
The way to do this is to navigate to a folder and select "Open." From there TablePlus will prompt you for what you want the name of the file to be.

**Comment by limkuncui** [comment]
I'm new user with TablePlus for windows 11 and I got to say that i have hard time using tableplus to create new sqlite database! I try search around online and come to this page. Why it doesn't let us simply name the new database file and browse where we want the file to be located? "Select SQLite database file" serve no purpose in creating New database file.
