### ISSUE TITLE
Changelogs and releases

### ISSUE THREAD

**Issue by weyert** [TablePlus/TablePlus#678]
Looks like the changelog aren't being updated when new beta releases are available via Check for Updates. I would like to know what has changed in the latest release e.g. build 137

It's not listed here: https://tableplus.io/blog/2017/02/changelogs.html

**Comment by huyphams** [comment]
I just updated changelogs up to the stable build 136. I will do for the build 137 when I back to the office 😸

**Comment by weyert** [comment]
Thank you :)
