### ISSUE TITLE
Cannot connect to Microsoft SQL Server 2014 on Azure

### ISSUE THREAD

**Issue by vlki** [TablePlus/TablePlus#681]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 136

3. The steps to reproduce this issue:

* Create connection to Microsoft SQL Server 2014 (NOT over SSH)
* Either click "Test" or "Connect"
* After about 10 seconds it shows either empty or "NULL DBPROCESS pointer passed to DB-Library" error (see attached screenshots)

Empty:
![screen shot 2018-10-01 at 17 20 11](https://user-images.githubusercontent.com/116486/46298046-6da78580-c59e-11e8-889b-8fb9f2b0a1f6.png)

"NULL DBPROCESS pointer passed to DB-Library":
![screen shot 2018-10-01 at 17 20 48](https://user-images.githubusercontent.com/116486/46298053-7435fd00-c59e-11e8-9e3e-b6f4ba3ad439.png)

----

Additional notes:

I am able to connect via [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-2017) or via [SQLPro for MSSQL](https://www.macsqlclient.com/), but when putting the same credentials into TablePlus, it fails with the errors above.

I tried various tips from #209 like adding `/SQLEXPRESS` after the hostname or using IP address, but none of them helped.

Full Microsoft SQL Server version obtained via `SELECT @@VERSION`: `Microsoft SQL Azure (RTM) - 12.0.2000.8 	Aug 31 2018 20:17:59 	Copyright (C) 2018 Microsoft Corporation`.

----

Any idea what might be the issue?

**Comment by huyphams** [comment]
Hey @vlki can you send the screenshot of your form to email huy@tableplusapp.com? Please change the ip address random and change username, database name etc.. if needed.
Thanks.

**Comment by huyphams** [comment]
Just let you know that I can be able to reproduce the bug, it's late so I will back to this bug tomorrow.
Good night.

**Comment by huyphams** [comment]
Hi @vlki I just fixed it: https://www.dropbox.com/s/ush8fss0ekr5u05/TablePlus.dmg?dl=0
Thanks for report the issue.

**Comment by vlki** [comment]
Can confirm that I can connect with the linked build. Thanks!
