### ISSUE TITLE
"File | Open" permanently replaces SQL query editor contents without warning

### ISSUE THREAD

**Issue by alvint** [TablePlus/TablePlus#682]
Oracle 12.x
build 137

1. open a query tab
2. add some SQL
3. ! use "File | Open" to open an existing SQL file--the original contents are replaced without warning

To make things worse, you can't use "undo" to get the original contents back. I guess I could have used the history to get the last executed SQL back (I didn't think of it), but any changes since then would still be lost.

How about always creating a new tab if there is already a SQL tab open with stuff in it? I guess things would get tricky if the user already has two tabs open in the free version, though.

**Comment by huyphams** [comment]
Thanks, I will think about this.

**Comment by jmadkins** [comment]
Yeah, this is a pretty annoying issue. It should be opened into a new tab.

**Comment by huyphams** [comment]
Thanks, I think it should open a new tab if the current query is not empty.

**Comment by huyphams** [comment]
it's fixed now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
cc @alvint @jmadkins Thanks all.
