### ISSUE TITLE
Feature Request: Allow SQL queries to be saved/remembered per workspace/database

### ISSUE THREAD

**Issue by d3vild06** [TablePlus/TablePlus#683]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): **9.5.12**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): **137**

3. The steps to reproduce this issue: 

**Switch to or open a new database connection and open the sql editor. I want to be able to re-open or switch to any of my database connections and have it remember the sql queries. It appears it shares or remembers the same queries across databases on the same connection and overwriting any previous ones I had saved for a different database.**

**It should isolate and remember the queries to the specific workspace/database. I want to be able to save them within the editor as well.**

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @d3vild06 it depends on the use case. Not all users want this feature. Some of them using the same query for multiple databases (analytics purpose). I will think about this feature.
We do have a favorite panel on the left. You can save any query here, have you used it?

**Comment by d3vild06** [comment]
@huyphams I have but that only saves **one** query at a time. My use case is that I want (and typically do) to save a bunch of queries in one file that I can re-use. I don't want to hunt down individual saved/favorited queries. Hope that makes sense.

**Comment by huyphams** [comment]
1. You can save whatever you want on the favorite section, and `not only one query`.
2. You don't need to hunt down and click to the query to import if you are using key-binding like this:
![2018-10-06 09 38 23](https://user-images.githubusercontent.com/3654622/46566591-a1423100-c94b-11e8-8942-65772a31663f.gif)
