### ISSUE TITLE
Input IP address not used - switches to WAN IP

### ISSUE THREAD

**Issue by jaythegeek** [TablePlus/TablePlus#684]
1. Which driver are you using and version of it:
MySQL 5.7.14

2. Which TablePlus build number are you using:
136

3. The steps to reproduce this issue:
Add new remote connection, when it tries to connect it says access denied and the IP address it is using to connect is my WAN IP address and not the remote address specified in the field.
Local connections work fine so I am thinking there is a bug somewhere.

**Comment by huyphams** [comment]
Hey thanks, but may I ask you that why did you think that it should be a public IP address? Are you using other application before TablePlus?

**Comment by jaythegeek** [comment]
I am using Sequel Pro to connect to a Google Cloud SQL Server and it works perfect, no SSL and with SSL. I have had issues with Sequel Pro so purchased TablePlus... Anyway, I need to connect to an IP such as 34.123.123.22 but when I do, it does not use this to connect to it says access denied using the public IP address of my router??

**Comment by huyphams** [comment]
I just read the sequel pro code, they have a fall back to 127.0.0.1 if the public IP has failed. So that no difference between TablePlus and Sequel Pro except this one.

**Comment by jaythegeek** [comment]
ok but I have no idea why this would fail and switch as I am have multiple connections from sequel pro and other live applications to that IP address. It is only TablePlus doing that.

**Comment by huyphams** [comment]
If you connect over SSH tunneling and the database server is on the ssh server, it's always 127.0.0.1 (local address). We should not use the public IP here because of the security reason. Are you really want to allow connections from the public IP? that means anyone can brute-force your database password from the outside.

**Comment by huyphams** [comment]
Please send me your connection form to my email huy@tableplusapp.com I will look into it and see what happen, if it was a bug, we will fix it, definitely.
Thanks for the details.

**Comment by jaythegeek** [comment]
I just sent them over now 👍 thanks for helping, hopefully you will see what I mean.

**Comment by huyphams** [comment]
I got your email, but I want to clarify this `So you are saying that it is not possible for me to connect to a public IP address with TablePlus?`
1. It's possible for sure, TablePlus can connect to any IP address.
2. I just said that in the case using SSH tunneling, it should be the local address. I think we misunderstood here, but after you sending me the form, I can see that you are not using SSH. I will investigate it.

**Comment by jaythegeek** [comment]
Sorry, miscommunication, I am not using SSH tunnelling.

**Comment by jaythegeek** [comment]
Also, just as additional information, I have tried switching the MySQL versions 5.x or 8.x - no difference, still cannot connect, tried with and without SSL too - no difference

**Comment by huyphams** [comment]
While I'm investigating, can you help me to run these queries?
```
use mysql;
SELECT host FROM user WHERE user = 'your_username';
```
it shows that which IPs are allowed to connect to the server.

**Comment by jaythegeek** [comment]
As I said, all IPs are allowed.

**Comment by jaythegeek** [comment]
Oh, it would appear there was something odd going on my end, on my local connection. My apologies, I just encountered it with Sequel Pro too and figured it out. Closing this now. Thank you for your help.

**Comment by huyphams** [comment]
Yay! I’m confused too, That’s why I thought you’re using ssh. Btw, I’m glad that you’ve resolved it.
