### ISSUE TITLE
Increase- and Decrease font keyboard shortcuts not working

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#686]
Pressing "cmd +" should increase font size, but it actually decreases

Pressing "cmd -" should decrease font size, but instead it toggles line remark (putting double dashes at the start)

**Comment by huyphams** [comment]
Hey @msageryd which keyboard layout are you using? I'm using US Keyboard and it works as expected.

**Comment by msageryd** [comment]
I'm using Swedish 105 key layout.

I thought that key bindings where done with character codes, i.e. a "+" is a "+" whatever physical key it was generated from. Are your shortcuts bound to physical keys?



On 2 October 2018 at 12:34:00, Huy Pham (notifications@github.com<mailto:notifications@github.com>) wrote:

Hey @msageryd<https://github.com/msageryd> which keyboard layout are you using? I'm using US Keyboard and it works as expected.

**Comment by huyphams** [comment]
I don't that Apple solution works that way. This is one of the know issues and it should be done with a preference that allows users to customize their shortcuts key.

**Comment by msageryd** [comment]
I haven't encountered any other app that seems to mix up keys in shortcut definitions.

"cmd +" works as it should from my keyboard in every other application I have.



On 2 October 2018 at 12:40:30, Huy Pham (notifications@github.com<mailto:notifications@github.com>) wrote:

I don't that Apple solution works that way. This is one of the know issues and it should be done with a preference that allows users to customize their shortcuts key.

**Comment by huyphams** [comment]
Hey @msageryd TablePlus now supports customize shortcut key, so this is no longer be an issue.
You can download the build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 or check for beta update.
Let me know if you still have an issue with the shortcut key.
