### ISSUE TITLE
MySQL connection regularly times-out when idle 

### ISSUE THREAD

**Issue by alexanderkoehlerkun** [TablePlus/TablePlus#687]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MySQL 5.7.21 w/ SSH Tunnel 
macOs Mojave 10.14 (18A391)

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
137

**3. The steps to reproduce this issue:**

- in Settings "Keep connection alive" and "Auto reconnect connection" enabled
- Run Query, wait around 5-10 minutes 
- Suddenly, all queries take forever, workspace Refresh also, no Table information etc.
- only option to resolve is restarting TablePlus

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Probably because of the timeout setting, let me see if we can increase it. Thanks for the feedback.

**Comment by alexanderkoehlerkun** [comment]
Maybe you could add a setting for adjusting the timeout :)

**Comment by huyphams** [comment]
Yep, but as a temporary I increased the MySQL timeout to 3000 second (50 mins), it would be great if you can give it a try: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by alexanderkoehlerkun** [comment]
Hi! 50 minutes is WAY better than before :) 👍 

Thank you!

**Comment by ekirkland** [comment]
Did this enhancement make its way into the main release?  We started using TablePlus recently and we often get timeouts on queries that take longer than 5 minutes.

**Comment by huyphams** [comment]
Sure @ekirkland I will add a config for it.

**Comment by huyphams** [comment]
I added a timeout configuration on the build 209. you can check the beta update or download it here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks

**Comment by ekirkland** [comment]
I set the timeout to 1 hour (3600 seconds) but my queries are still timing out right on 900 seconds.
