### ISSUE TITLE
Better maintaining of database connections

### ISSUE THREAD

**Issue by delpiersos** [TablePlus/TablePlus#69]
Presently database connections drop out fairly frequently - my feeling is that the app should manage it better - e.g. if the connection is lost, and the user is still trying to do something (such as bringing up a table) then manage the reconnection without getting the user to confirm; or better yet, just continually keep the connection open as long as the user is still in the app with that database open.

**Comment by huyphams** [comment]
Database connections drop out depend on server config. But nice idea, the app should manage it better.
I will try to improve it.

**Comment by delpiersos** [comment]
Yeah - understand the server manages how long connections to it can last; unfortunately _some_ of my projects are using Heroku; where we get little control of the server config.  Postico does the connections management pretty well - but the rest of their user experience is not as good as TablePlus

**Comment by huyphams** [comment]
Hi @delpiersos, could you try if this build solve your problem?
https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

**Comment by delpiersos** [comment]
Hi @huyphams - this is working pretty well - thanks for the quick turnaround!
