### ISSUE TITLE
Allow color theme customizations for SQL Query editor 

### ISSUE THREAD

**Issue by darioup** [TablePlus/TablePlus#690]
I get a bit confused on dark mode, when I place the cursor on a query it is like gray highlighted and almost all the times is confusing for me, maybe others would agree with this highlight.

Also there would be helpful to have opening/closing parentheses highlighted when they are selected or the cursor is next. Now it only flashes for 1 sec in yellow and only for the closing parentheses

I love Dark Mode, these customizations will make it better :)

**Comment by msageryd** [comment]
I'm having problem with this as well. I do think i't valuable to see exactly what will be executed when I press cmd-enter. But the highlight in dark mode has two problems:

1. contrast is lowered to a problematic level
2. the highlight is easily mistaken for a selection highlight (making me think that I have it on clipboard after ctrl-c)

I suggest that the highlight is exchanged for a gutter mark spanning the length of the active statement.

**Comment by huyphams** [comment]
We can now fully customize the text color in the preferences.

**Comment by crydotsnake** [comment]
What is the format of the theme ? .json dont work.
