### ISSUE TITLE
Missing MSSQL session default configuration

### ISSUE THREAD

**Issue by vitiokss** [TablePlus/TablePlus#691]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**Microsoft SQL Server 2016 - 13.0.4466.4 (X64)** 

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Build 137**

3. The steps to reproduce this issue:
The problem with **TablePlus** client is that it is not setting the recommended SQL server client default settings (options). Which leads to misalignment and bugs as if you create the table with the following default settings they keep remain after the session.

You can follow the article which explains that, also follow SQL Server documentation.
https://www.mssqltips.com/sqlservertip/1415/determining-set-options-for-a-current-session-in-sql-server/
and 
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-statements-transact-sql?view=sql-server-2017

The not set **ascii_padding** option created lot of trouble, and it was difficult to find out what is happening. It turned out, that it is TablePlus problem, which is not following the recommendations.

The rest similar clients don't have that problem: **SQLPro**, **DataGrip**, **SQL Server Management Studio** etc.

More suggestion for improvement:
1. Currently in table structure view, you are not able to see data length, which is quite important is many situations. It would be nice if you can add this to the view.
2. There is some problems either with rendering of data in SQL Server or fetching data through the driver. As if you are selecting bigger amount of data, it takes ~10-20 times slower than **SQLPro**, **DataGrip** or native. (this problem doesn't exist in MySQL). And we are not talking about milliseconds, instead of 10 seconds its taking more than 100 seconds and so on. So it is clear that something wrong is left behind.

**Comment by huyphams** [comment]
I just checked the SQL Server Management and see that they use: 
OPTIONS 5496,
Which means
```
SET ANSI_WARNINGS ON;
SET ANSI_PADDING ON;
SET ANSI_NULLS ON;
SET ARITHABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULL_DFLT_ON ON;
SET CONCAT_NULL_YIELDS_NULL ON;
```
Probably TablePlus will use this default setting, I think SQL Server Management is standard.
Thanks for pointing it out.

**Comment by huyphams** [comment]
I made that changes in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 It would be great if you can give it a try and let me know if there is anything left.
Thanks.

**Comment by vitiokss** [comment]
@huyphams seems the options set correctly now. Seems working just fine :) Are you planning to include it in a weekly update ?

**Comment by huyphams** [comment]
Yes, that one will be included in the weekly update.
