### ISSUE TITLE
Comment Syntax Highlighting issue in MySQL

### ISSUE THREAD

**Issue by alexanderkoehlerkun** [TablePlus/TablePlus#693]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
MySQL 5.7.21 w/ SSH
macOS Mojave 10.14 (18A391)

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**
137

**3. The steps to reproduce this issue:**
`-- Comment`
`/* Comment */`
`# Comment`
First two will be correctly highlighted as comment, third not. 

Noted: If the bug is related to data, please attach an example SQL data.

![image](https://user-images.githubusercontent.com/20554186/46488263-77c9be00-c802-11e8-84f4-fe2ede81a88d.png)

**Comment by huyphams** [comment]
This is one of the know issues. Currently, TablePlus uses the same set of rules for SQL Server, MySQL, and PostgreSQL. That means I have to ignore some rules for each driver. I will improve it in the future.
