### ISSUE TITLE
Add possibility to import Sequel Pro connections and groups

### ISSUE THREAD

**Issue by fgilio** [TablePlus/TablePlus#694]
The title says it all :) It'll be awesome to have this feature built in, in the meantime I guess I'll do it manually.

PD: TablePLus is awesome, keep the nice work 🚀

**Comment by fgilio** [comment]
Related https://github.com/TablePlus/TablePlus/issues/285

**Comment by brandonjjon** [comment]
Hi there, I built an importer here: https://github.com/brandonjjon/tp-importer

Let me know if there are any issues!

**Comment by anchovy** [comment]
Wicked - thanks. I've got TablePlus via setapp so had to replace all occurrences of `/com.tinyapp.TablePlus/` with `/com.tinyapp.TablePlus-setapp/` and it worked like a charm!

**Comment by touson** [comment]
@brandonjjon you are a bloody legend!  Thank you for making the effort  ;o)

**Comment by hosnyben** [comment]
> Hi there, I built an importer here: https://github.com/brandonjjon/tp-importer
> 
> Let me know if there are any issues!

Thank you so much. Saved me from at least one hour of useless work. Thank you so much

**Comment by ingageco** [comment]
@brandonjjon Thank you! Works like a charm.
