### ISSUE TITLE
Auto-complete dropdown cuts off long identifiers

### ISSUE THREAD

**Issue by christianharrington** [TablePlus/TablePlus#696]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x, but I presume it's the same for others.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 136

3. The steps to reproduce this issue:

Create several tables with long names, e.g.
```sql
CREATE TABLE `really_long_table_name_should_be_shorter_but_it_isnt` (
  `also_just_a_too_long_column_name_im_sorry` int(11) NOT NULL,
  PRIMARY KEY (`also_just_a_too_long_column_name_im_sorry`)
);

CREATE TABLE `really_long_table_name_should_be_shorter_but_it_isnt_2` (
  `also_just_a_too_long_column_name_im_sorry` int(11) NOT NULL,
  PRIMARY KEY (`also_just_a_too_long_column_name_im_sorry`)
);
```

<img width="453" alt="Screenshot" src="https://user-images.githubusercontent.com/251914/46570834-ede93480-c96a-11e8-9f7c-72a465ca527f.png">

I am stuck dealing with some very long table names with identical prefixes. 
Because the names are cut off around 38 characters, it makes it impossible to tell them apart when trying to auto-complete them. [MySQL seems to limit identifiers to 64 characters][1], so maybe that's a good value.

[1]: https://dev.mysql.com/doc/refman/8.0/en/identifiers.html

**Comment by huyphams** [comment]
I have changed it to truncate tail and increased the width of the table name. Does it helps?
<img width="1357" alt="screen shot 2018-10-06 at 7 59 37 pm" src="https://user-images.githubusercontent.com/3654622/46571625-72a37500-c9a2-11e8-94b9-19c4b2614330.png">

**Comment by christianharrington** [comment]
That looks great!
