### ISSUE TITLE
[Win][1.0(16)][Azure SQL]Cant view stored procedures

### ISSUE THREAD

**Issue by Webrow** [TablePlus/TablePlus#697]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Azure SQL Server 12.0.5000

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0(16) Windows

3. The steps to reproduce this issue:
Whenever I use MSSMS I can view stored procedures in the Programmatibility folder, but in TablePlus I can only see the Tables and Views.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey thanks, I will fix it on the next update. But you report the issue in the wrong repo, it should be there: https://github.com/TablePlus/TablePlus-Windows/issues
