### ISSUE TITLE
Copy as ASCII Table

### ISSUE THREAD

**Issue by nojvek** [TablePlus/TablePlus#698]
Trying to figure out if I can write a simple plugin as a quick workaround but it seems there isn't great documentation on the plugin api.

Basically I am looking for something like this

![image](https://user-images.githubusercontent.com/1018196/46637846-d77ddd00-cb12-11e8-8b67-393028de3589.png)

But with an option of 'ASCII Table'

that would output something like

```
+----------------------------------+---------+------------------------+----------------+
|               Col1               |  Col2   |          Col3          | Numeric Column |
+----------------------------------+---------+------------------------+----------------+
| Value 1                          | Value 2 | 123                    |           10.0 |
| Separate                         | cols    | with a tab or 4 spaces |       -2,027.1 |
| This is a row with only one cell |         |                        |                |
+----------------------------------+---------+------------------------+----------------+
```

**Comment by nojvek** [comment]
Kind ping on this.

**Comment by nojvek** [comment]
Kind ping on this @huyphams

**Comment by huyphams** [comment]
it's supported on build 200 @nojvek thanks!

**Comment by nojvek** [comment]
OMG! Yessssss!
