### ISSUE TITLE
Removing primary key column

### ISSUE THREAD

**Issue by marcbrayman** [TablePlus/TablePlus#699]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

136

3. The steps to reproduce this issue:

Create a primary key column (via SQL or create new table in GUI) and then try to delete it via GUI.

Solution is decribed here:
https://stackoverflow.com/questions/43549413/alter-table-drop-column-failed-because-one-or-more-objects-access-this-column#43549456

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @marcbrayman let me fix it.
