### ISSUE TITLE
suggestion: middle click a value to initialize quick look

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#70]
Just a suggestion, maybe we can have a way to quicker enter the quick look for a value: 

Maybe middle clicking here could be initialize the quick look window.

![screen shot 2017-09-05 at 4 14 06 pm](https://user-images.githubusercontent.com/7946786/30087409-6678de44-9255-11e7-9e65-7abd67d34edf.png)

-Brian

**Comment by huyphams** [comment]
Yup, it should be force touch on Macbook and middle click on mouse (y)
