### ISSUE TITLE
Feature request: define primary with identity (SQL Server)

### ISSUE THREAD

**Issue by malsama** [TablePlus/TablePlus#700]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

138

3. The steps to reproduce this issue:

n/a

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
We just put this feature in our roadmap. it will be released soon.

**Comment by johndutchover** [comment]
Thank you everyone!

**Comment by malsama** [comment]
> We just put this feature in our roadmap. it will be released soon.

ETA?

**Comment by huyphams** [comment]
Thanks for reminding me, I will try my best on the next build 168.

**Comment by malsama** [comment]
I've just checked build 171 in which somehow IDENTITY is supported. I personally hope that it will be a bit more user friendly than just adding the column default "IDENTITY". I was hoping for a checkbox "Identity" and an additional setting controls for defining the auto increment number.

**Comment by huyphams** [comment]
Hi @malsama thanks for the feedback but this is just the initial support. We will improve it later.
Currently, you can create a table with an identity easily with TablePlus.
<img width="625" alt="screen shot 2019-01-02 at 5 34 42 pm" src="https://user-images.githubusercontent.com/3654622/50588455-b419c280-0eb4-11e9-92b9-700c1011f8ee.png">
Only for a new table, next next build will support adding a column with identity.

**Comment by NobodyButMe-Haiya** [comment]
> I've just checked build 171 in which somehow IDENTITY is supported. I personally hope that it will be a bit more user friendly than just adding the column default "IDENTITY". I was hoping for a checkbox "Identity" and an additional setting controls for defining the auto increment number.

i just check it out table plus ? where the heck auto increment field we need add in ?
