### ISSUE TITLE
Request to Add Prompt When Running Dangerous Queries

### ISSUE THREAD

**Issue by farizzed** [TablePlus/TablePlus#704]
Inspired by famous DBeaver SQL Client, it would be nice adding such prompt when trying to run dangerous queries such as running delete or update without where statement.

`delete from table_name`
`update table_name set a = 1`

This could minimalize the human error when updating/deleting many rows/tables.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MS SQL Server 2016

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 136

3. The steps to reproduce this issue:
-

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Currently, TablePlus supports `safe mode` you can enable it by click on the clock icon (on the toolbar).
Detect a query without a where condition is difficult.  I know that the limitation of the safe mode is it will warning all the query, includes a simple select statement.

**Comment by farizzed** [comment]
![image](https://user-images.githubusercontent.com/11038943/46775263-b1ce1f00-cd30-11e8-9b0f-d0504f18f6d4.png)

Can you help me with turning on the safe mode? It seems the lock icon (safe mode) is turned off and I cannot toggle it on.

**Comment by huyphams** [comment]
Hmm, I didn't have that bug, please close and re-open the app, if it won't help, please let me know.

**Comment by farizzed** [comment]
Ah for some reason, after adding a new database toolbar icon for 1st database is disabled, while 2nd database's toolbar is normal.

1st database
![image](https://user-images.githubusercontent.com/11038943/46775430-6ff1a880-cd31-11e8-9aa9-e04fc524f135.png)

2nd database
![image](https://user-images.githubusercontent.com/11038943/46775436-78e27a00-cd31-11e8-80cd-49afb50f8a50.png)

**Comment by huyphams** [comment]
Do you remember how to reproduce it? I opened 2 databases but it's the same. The toolbar is enabled.

**Comment by farizzed** [comment]
1. Open a database
![image](https://user-images.githubusercontent.com/11038943/46775652-52710e80-cd32-11e8-84c2-5c0bf45812de.png)

2. Open the second database
![image](https://user-images.githubusercontent.com/11038943/46775678-6b79bf80-cd32-11e8-9550-b419d961b4f7.png)

3. The toolbar of 1st database is disabled, while the 2nd database is normal.

**Comment by huyphams** [comment]
I can't reproduce the bug (with the step above), looks like it only happens in some special case. I gonna go, will be back in 40 mins, I will try to reproduce it again.
Thank you.

**Comment by farizzed** [comment]
When opening the 2nd database the toolbar is disabled. Maybe its state doesn't change after I opened 2nd database.
![image](https://user-images.githubusercontent.com/11038943/46775796-f8bd1400-cd32-11e8-84f2-ce24102e613e.png)

**Comment by huyphams** [comment]
Hey @farizzed can you try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
and let me know the result.

**Comment by farizzed** [comment]
![image](https://user-images.githubusercontent.com/11038943/46779450-0a59e800-cd42-11e8-8ced-6d1647a8f821.png)
Still disabled for 1st database

**Comment by farizzed** [comment]
Perhaps I will be making a gif later after work. Will get back to you later.

**Comment by huyphams** [comment]
Thanks, I'm waiting for it.

**Comment by huyphams** [comment]
I made a small change on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
TablePlus always enables toolbar when the windows become active.
