### ISSUE TITLE
Exists any version that work with MySQL old password  ?

### ISSUE THREAD

**Issue by togro** [TablePlus/TablePlus#705]
Hi

I'm trying to connect to mysql with old password (5.1 ), but Tableplus show this message:

**_Authentication plugin 'mysql_old_password' cannot be loaded: dlopen(/usr/local/mysql/lib/plugin/mysql_old_password.so, 2): image not found_**

How can fix that ?

Tableplus version 136

**Comment by huyphams** [comment]
We removed support old_password because it's unsafe and recommends removed by Oracle (the maintainer of MySQL).

https://dev.mysql.com/doc/refman/5.7/en/account-upgrades.html
