### ISSUE TITLE
Typo / translation error in "Thank you for buying Tableplus" dialog

### ISSUE THREAD

**Issue by timkimber** [TablePlus/TablePlus#706]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 16 (windows)
3. The steps to reproduce this issue:

Trivial issue but fixing them would make the product look more professional

Licence product and/or press the 'Register' button to view current licence

![tableplus - registration text](https://user-images.githubusercontent.com/15785928/46797028-f87a4400-cd45-11e8-8544-07951441050c.png)

* Thank you for buying TablePlus and *supporting* the team!
* License is *managed* by email
* Updates available *until*

**Comment by Tungtono** [comment]
Hey @timkimber, thanks for reporting. We are fixing it now.
