### ISSUE TITLE
PLEASE DO NOT pop too many error or warning dialog

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#707]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
* MySQL5.X

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* Build 139 Mac OS

3. The steps to reproduce this issue:
* I use TablePlus with Proxifier(allow TablePlus connect db with ssh tunnel)
* open multi connections
* then close my laptop
* open my laptop in some other place. then ssh tunnel will hang.
* and TablePlus will pop many many warning dialog tell me to retry my connect. and when I close one warning dialog, a open connection dialog will pop up, when I close open connection dialog, another warning dialog will pop up..... if I open ten connection before, I need close twenty dialog!
![image](https://user-images.githubusercontent.com/5211881/46843849-3ab78a00-ce07-11e8-85ef-a0a917b8d6e5.png)
![image](https://user-images.githubusercontent.com/5211881/46843908-620e5700-ce07-11e8-8318-4554b1dc541e.png)

---

* TablePlus was a great db GUI client once, not now!
* **PLEASE DO NOT pop open connection dialog automatic**. I now when I need open it.
* **PLEASE DO NOT pop too many error or warning dialog if they are all same thing**

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hey @bulletRush can you  try this build? https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
