### ISSUE TITLE
Suppress quotes when auto complete

### ISSUE THREAD

**Issue by ntw6tori** [TablePlus/TablePlus#709]
Is there any way to suppress the quotes when auto complete column names from mysql tables?
They are not really needed for mysql syntax and for me it makes SQL code harder to read

**Comment by huyphams** [comment]
TablePlus only adds quote when it needed. If we remove the back sticks, it will have a syntax error.
1. table's name contains space.
2. table's name is also a keyword (Ex: update).
3. table's name has an upper case.
Looks like that case 3 is not necessary for MySQL, let me check it if it won't effect the syntax, we can remove this rule safely.

**Comment by ntw6tori** [comment]
In my case the tables names are all lower cases but the columns names contains upper cases.
But the backticks are definitely not needed in case 3 for mysql database

**Comment by huyphams** [comment]
Hey @ntw6tori I removed the rules 3 after checking the documents. it will be released in the next update.
