### ISSUE TITLE
View/export BLOB data in HEX

### ISSUE THREAD

**Issue by ntw6tori** [TablePlus/TablePlus#710]
It would be nice if we could view raw binary BLOB data as hex data and export it to a file

**Comment by tphipps** [comment]
Fully agree with this request. At least as an interim step, showing some sort of placeholder or marker for cells containing binary data rather than an empty cell would disambiguate things.

**Comment by timfennis** [comment]
I absolutely need to view VARBINARY and BINARY(16) columns as HEX. I use these to store UUIDs and currently these are completely unusable because they are displayed as text. To make matters worse if they contain \0 they are truncated. Showing BINARY data as text is not a good default IMO

**Comment by huyphams** [comment]
Thanks guys, I will look into this issue tomorrow, we will support HEX

**Comment by tarieli1** [comment]
Hi @huyphams, any updates on this enhancement?

**Comment by huyphams** [comment]
I've implemented it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Hold option + left mouse click.

**Comment by nilsE** [comment]
is this working already? i still get some ugly binary characters when viewing binary(16) ids.
thanks

**Comment by peritpatrio** [comment]
> is this working already? i still get some ugly binary characters when viewing binary(16) ids.
> thanks

Looks like you need to option click (like @huyphams mentioned above) and then click `Edit hex…` to view it as hex.

<img src="https://user-images.githubusercontent.com/729565/62521642-b7a16d80-b838-11e9-8138-eaabcbbcc46b.png" width="170" />
 
---

It would be nice to have a setting for this so UUIDs for example are always shown as hex in the list.

**Comment by kagia** [comment]
I wouldn't agree that it would be a good idea to display entire blobs as hex, but at least smaller types like varbinary. Also the menu option shown above doesn't work for me I just get an empty popup.

having to go through a menu doesn't help when you are visually scanning the table for a specific value. Here is a screenshot of how SequelPro does it, and does it wonderfully:
![image](https://user-images.githubusercontent.com/13535082/63246066-1071fc80-c262-11e9-914d-f1c92aa406c5.png)

So at a glance you can see your UUIDs! This can be enabled and disabled via preferences.

I think something along this lines is what the original poster was looking for

**Comment by timfennis** [comment]
@kagia this is exactly what I meant to suggest. 

[Example of button in HeidiSQL](https://www.heidisql.com/uploads/26321-1-binary-astext.png)
[View of data](https://camo.githubusercontent.com/2e2b39c5c8e49f59ebe5d4239291eb5ce44cd015/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f353739333836342f313930323434312f62333262613632342d376337322d313165332d383130332d6536356437663834356563372e706e67)

**Comment by jaikdean** [comment]
This is the clincher for me switching over from Sequel Pro :)

**Comment by madmanmax** [comment]
Indeed we need a way to view binary data, a lot of people are storing UUIDs as binary. The ability to have a quick overview would help tremendously. Something as it was suggested in https://github.com/TablePlus/TablePlus/issues/710#issuecomment-522497985

**Comment by ntw6tori** [comment]
In fact, I also switched from Sequel Pro to Table Plus and miss that feature

**Comment by huyphams** [comment]
Thank guys for reminding me, I will improve it. I have some ideas.

**Comment by huyphams** [comment]
I've improved binary support for MySQL in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 please give it a try, I would like to hear your thoughts

**Comment by kagia** [comment]
hi @huyphams, I'm guessing the handling of `var_string` columns hasn't changed in that release? because I tried it out and didn't see any difference.

**Comment by huyphams** [comment]
Hi, could you please guide me the step to reproduce the issue @kagia

**Comment by huyphams** [comment]
Sorry, I've updated the wrong hot patch, please try this: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by kagia** [comment]
@huyphams great work 🎉 , the tables look and behave as expected!

**Comment by peritpatrio** [comment]
Awesome, this is exactly what I’ve been looking for! 👍

**Comment by filipac** [comment]
@huyphams is there a way to revert it? For example, in one db i have a blob column but i want to see the contents not the hex. there is no way to do that currently.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/271155/67272394-2059c700-f4c5-11e9-840b-b9a5b81260ca.png">

**Comment by huyphams** [comment]
Please try this build @filipac TablePlus now try to view the data in quicklook MySQL correctly: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by SkylerLS** [comment]
@huyphams That patch fixed the issue for me. Now the BLOB type fields are showing the complete JSON I'm storing in them instead of the hex values.
