### ISSUE TITLE
SQL Server: CHAR type isn't showing size

### ISSUE THREAD

**Issue by marcbrayman** [TablePlus/TablePlus#712]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

141

3. The steps to reproduce this issue:

Create a CHAR column with a certain size; eg. CHAR(8). The structure view doesn't show its size; only "CHAR" is displayed; not "CHAR(8)". F.e. with VARCHAR you *can* see its size.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I added support it in the beta build 143. Thanks for reporting.
