### ISSUE TITLE
Chinese display exception

### ISSUE THREAD

**Issue by hongxiao-liu** [TablePlus/TablePlus#714]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by hongxiao-liu** [comment]
In the original database table, the Chinese content of the field is displayed as a question mark, and the correct Chinese is not displayed.

**Comment by huyphams** [comment]
This issue is duplicate with https://github.com/TablePlus/TablePlus/issues/713
