### ISSUE TITLE
In PostgreSQL, when bytea is PRIMARY KEY, it is not updated.

### ISSUE THREAD

**Issue by gitboo** [TablePlus/TablePlus#715]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
->  PostgreSQL 9.6.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
-> Version 1.0 (142)
3. The steps to reproduce this issue:

In PostgreSQL, if bytea is a PRIMARY KEY, it can not be changed.

Example, 

1) Defines the bytea data type as the PRIMARY KEY.

CREATE TABLE "public"."device" (
    "mac" bytea NOT NULL,
    "name" varchar(100) NOT NULL,
    PRIMARY KEY ("mac")
);

2) Insert test data
    INSERT INTO device2 ("mac", "name") VALUES ('\x702c1ffffe3caf74', 'test');

3) Open the data tab of device table.
    
3) Modify the name directly in the data tab.

4) 
I expected the following query to be executed.
UPDATE "public"."device2" SET "name" = 'test5125125' WHERE "mac" = '\x702c1ffffe3caf74';

However, tablePlus did not actually change the value of name because it was actually executed as shown below.

UPDATE "public"."device2" SET "name" = 'test5125125' WHERE "mac" = '8 bytes';

Please fix it. 
Thanks.

**Comment by huyphams** [comment]
Thanks, @gitboo this is one of the known issues, we're working on it. Not only the primary key, but also the foreign key.

**Comment by brianhiss** [comment]
@huyphams Do you have an update on this, I see the tag is marked "Done". 

I'm on Version 2.2 and still see the same issues as @gitboo where my primary key's are bytea and TablePlus breaks.

Do you plan to cast the bytea as a string when displaying the query results? I know a lot of SQL clients do this, specifically the CockroachDB CLI does it.

**Comment by huyphams** [comment]
Hi @brianhiss, which is the issue are you facing? updating row with the bytea primary is not working or decode and show the bytea primary key as String?
if it's the first, could you please send me an example? if it's the second, it would be a different issue.

**Comment by brianhiss** [comment]
@huyphams When I used a `bytea` as a Primary Key, and I try to delete, or update the data in the row, nothing happens.

The logs show why:
![Screen Shot 2019-04-22 at 10 11 54 AM](https://user-images.githubusercontent.com/1640257/56507526-328f8400-64e7-11e9-951b-c761b528f897.png)

It's trying to delete from the row `WHERE "id" = '20 bytes';`, instead of the actual ID. Same happens for updates, etc.

Also, in relation to this, I am sending it a 20 character string as a `bytea`, but it's actually 16 bytes, not the "20 bytes" TablePlus is reporting...(i.e. https://github.com/rs/xid/issues/14)

**Comment by huyphams** [comment]
Thank @brianhiss, but could you send me the script which I can create that table? I've tried with my table but it works
<img width="1653" alt="Screen Shot 2019-04-22 at 10 17 08 PM" src="https://user-images.githubusercontent.com/3654622/56507727-7072c380-654c-11e9-8e37-eb9432e2ce0c.png">

**Comment by brianhiss** [comment]
@huyphams 

```
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
	id BYTES PRIMARY KEY,
	username STRING NOT NULL,
	name STRING NULL
);
```

`INSERT INTO users (id, username, name) VALUES (b'bi0qh6f3mj07bierogq0', 'brian', 'Brian');`

This works if I write the query myself:
`DELETE FROM users WHERE id='bi0qh6f3mj07bierogq0';`

Using the GUI to `DELETE` does not work (Clicking on a row, 'DELETE' key, Command + S to save). It generates:
`DELETE FROM "public"."users" WHERE "id" = '20 bytes';`

**Comment by huyphams** [comment]
Made sense, you're using Cockroach, not PostgreSQL. I will fix it now.

**Comment by huyphams** [comment]
I've fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thank you for reporting the issue 👍

**Comment by brianhiss** [comment]
@huyphams That was fast! 😮 Tested and works now.

Per my earlier question on casting to a string, do you plan on supporting that down the line?

In CockroachDB CLI, they show the id as a string (even when `BYTEA`) when running a query:
```
select * from users where id='bi0qh6f3mj07bierogq0';
           id          | username | name   
+----------------------+----------+-------+
  bi0qh6f3mj07bierogq0 | brian    | Brian  
(1 row)
```
Right now I just see "20 bytes" in TablePlus.
![Screen Shot 2019-04-22 at 11 27 55 AM](https://user-images.githubusercontent.com/1640257/56511260-c9f9d480-64f1-11e9-9a07-151959643d88.png)

**Comment by huyphams** [comment]
I've thought about it a couple of times. Byea is a wide range of data, it can be anything (image, pdf, sound, string, etc...). If we force it to show as text, it could be wrong in some cases. I want to avoid a solution which won't work 100%.
If I can add this feature, it would be a view option, where user can choose the decoder for the column, and they can choose string for this bytea column.

**Comment by brianhiss** [comment]
@huyphams That makes sense. Thank you for your quick support. Great product, keep it up 👍
