### ISSUE TITLE
export not working for Oracle

### ISSUE THREAD

**Issue by alvint** [TablePlus/TablePlus#716]
Oracle 11.x and 12.x
build 143

I'm not sure if this is supported yet, but the export function does not seem to work for Oracle for any file type (SQL/JSON/CSV).

**Comment by huyphams** [comment]
Thanks @alvint let me check and fix it.

**Comment by huyphams** [comment]
Hi @alvint I have fixed the bug: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Sorry because of the delay, I have a lot of tasks 😄

**Comment by alvint** [comment]
Now it exports CSV and JSON ok, but SQL still has issues. It exports the `insert` statement for the data but not the DDL for creating the table. If you don't select "Include table content" it doesn't create a file at all.

**Comment by alvint** [comment]
If related, the Definition section on the Structure tab is blank:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/622202/47097088-a3837580-d1fe-11e8-8f99-d73adf3c4307.png">

**Comment by prwhitehead** [comment]
Hello, if this is not related, I'm happy to open another issue. 

Exporting for Remote MySQL databases is also disabled from the menu. 

<img width="209" alt="screenshot 2018-10-19 11 53 32" src="https://user-images.githubusercontent.com/1199977/47214527-1d019c00-d396-11e8-9ea3-63b9589998dc.png">

**Comment by huyphams** [comment]
@prwhitehead you must select a table the menu will be enabled. another way, you can right click and select `Export...` in the menu context.

**Comment by alvint** [comment]
Hi @huyphams, just a reminder that export to SQL is still not working. It is working for JSON and CSV though.

**Comment by huyphams** [comment]
Thanks @alvint I will check and fix it.
