### ISSUE TITLE
Shortcut-key Delete rows

### ISSUE THREAD

**Issue by rokity** [TablePlus/TablePlus#72]
Hi

I think we need a shortcut-key for delete rows like ⌘ ^ Delete .
it's possible?

**Comment by huyphams** [comment]
We already have a shortcut key for delete row, you can select rows and press delete button

**Comment by huyphams** [comment]
Which build are you using @rokity ?

**Comment by huyphams** [comment]
I think we have delete shortcut key in build 61, isn't it?

**Comment by rokity** [comment]
So sorry but I didn't see inside the docs about shortcut-keys.

**Comment by huyphams** [comment]
Yeah, maybe I will include it in app but here:
on Github wiki: https://github.com/TablePlus/TablePlus/wiki/Shortcut-keys
on our site: https://tableplus.io/faq

**Comment by rokity** [comment]
yes I think it's better to insert this in the docs.

**Comment by huyphams** [comment]
@rokity I just realized we can only delete by backspace, the delete button on full-layout keyboard is not working.
I confirmed it should work on the up coming build 💃
