### ISSUE TITLE
Edit a connection

### ISSUE THREAD

**Issue by mohamednagy** [TablePlus/TablePlus#720]
- Version 1.0 [MySql]
- BuildNumber 142

I'm trying to edit an already added connection but i couldn't find a proper way for that i have to click on a new connection to open the connections window then edit the connection. Is there something to edit  a connection without doing this long steps.
If this is not implemented i think it would be better to add this.

**Comment by huyphams** [comment]
Hey thanks, I think so, it also helps when you open connection by a URL and want to save it. I will add it in the next update.

**Comment by huyphams** [comment]
it's released on the beta build 145.
