### ISSUE TITLE
Can not filter - Invalid STRING constant (<some uuid>) for "user_id" of type uuid

### ISSUE THREAD

**Issue by MightyPixel** [TablePlus/TablePlus#721]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
2.1.19.1484

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
142

3. The steps to reproduce this issue:
- Have Cassandra table with a column with type of UUIDType
- Try to filter by that column = some existing uuid
- The resulting SQL wraps the search string with single quotes which results in an error
- If you copy the SQL query and use the Raw SQL option then paste the query without the single quotes around the searched uuid everything works

For example if we use the filter by uuid = we get the following query:
```
SELECT * FROM "db_name"."table_name" WHERE ("uuid_column_name" = 'some_uuid') LIMIT 300;
```

The correct query should be:
```
SELECT * FROM "db_name"."table_name" WHERE ("uuid_column_name" = some_uuid) LIMIT 300;
```

I think this is just a question to not put quotes if the type is UUIDType.

Cheers :)

**Comment by huyphams** [comment]
Thanks, that's my bad, I will fix it then release in the weekly updates (Beta build)
Thanks for pointing it out 👍

**Comment by MightyPixel** [comment]
Hi. About the beta builds, are they publicly accessible?

Thanks!

**Comment by Tungtono** [comment]
Hey @MightyPixel, you can go to preferences (cmd + ,) > check "Receive Beta Updates", then update the app to get the new beta build.
<img width="319" alt="beta" src="https://user-images.githubusercontent.com/10219818/47226166-0b49e400-d3ea-11e8-892a-60b70507ef49.png">

**Comment by saintpepsicola** [comment]
I have switched to beta build but I am still experiencing this error? :/

**Comment by huyphams** [comment]
it's fixed now!
