### ISSUE TITLE
Feature Request: Allow option to default filtering to "Any Column"

### ISSUE THREAD

**Issue by kule** [TablePlus/TablePlus#722]
I love the "Any Column" filter option and quite often the first thing I want to do is find some relevant data quickly - could we have an option to make it the default rather than "Raw SQL" here?

**Comment by huyphams** [comment]
Hey @kule TablePlus remembers the filters, you just need to create your favorite filter and will be saved for the next time. Set `Any Column` as default may be a good idea but there are other users are using the Raw SQL with auto-completion for quick lookup. If I change the default, they will create an issue request to change it back 😄 

<img width="1106" alt="screen shot 2018-10-16 at 9 14 27 pm" src="https://user-images.githubusercontent.com/3654622/47022797-798f6c00-d188-11e8-8073-c149086a5cac.png">

**Comment by kule** [comment]
Ha yeah I didn’t mean change the default (I can well imagine some people prefer raw sql first) - I just wondered if we could have a preference setting for the default?

**Comment by ruudk** [comment]
I really want the same. I never want to type Raw SQL. Most of the time I just want to search the table by Primary Key with Equals (`=`). Sequel Pro does alway select the first column in the table with `=` and that's super handy.

**Comment by joshhudnall** [comment]
Agreed, it would be incredibly useful to be able to choose the default.

**Comment by huyphams** [comment]
Agreed! I will add it soon.

**Comment by FoxxMD** [comment]
Also looking forward to this!

**Comment by nicosayer** [comment]
Would love to see this !

**Comment by huyphams** [comment]
You will be able to set the default operator and also the default column in the next update. Next update 💃 
<img width="942" alt="default" src="https://user-images.githubusercontent.com/3654622/64399291-3bb86200-d03e-11e9-9f6a-110a300bcf92.png">

**Comment by ruudk** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🔥🔥🔥🔥❤️❤️❤️❤️❤️❤️
