### ISSUE TITLE
Column names in viewer didn't support Cyrillic symbols

### ISSUE THREAD

**Issue by xFixx** [TablePlus/TablePlus#724]
Hi! 
ver. 1.0 (142)
My db table columns has names in Cyrillic. This is how they showed:
http://joxi.ru/eAOYEpwf9w8Yjm

Meanwhile, in other fields they seem to be ok 
http://joxi.ru/nAyxpEyugyq1B2

**Comment by xFixx** [comment]
It's mssql, Azure :)

**Comment by xFixx** [comment]
![image](https://user-images.githubusercontent.com/44024660/47917357-481ddc80-deba-11e8-8d12-0d0d8804f6f0.png)

Mac 10.14.1
Azure
TablePlus 1.0 (146)

Still the same

**Comment by huyphams** [comment]
It's fixed in the build 233. Thank you!
