### ISSUE TITLE
Don't show table list for Mysql driver

### ISSUE THREAD

**Issue by voeurnchy** [TablePlus/TablePlus#726]
- it won't show table list for all MySQL database, PGSQL work as normal
- TablePlus version: 1.0 (142)
- view data by running SQL query also work as normal

Note: I'm using macOs Hight Sierra v 10.3.6

![screen shot 2018-10-17 at 5 29 54 pm](https://user-images.githubusercontent.com/16317127/47080685-dd6e6f00-d232-11e8-846f-7018e914e5eb.png)

**Comment by huyphams** [comment]
Hi @voeurnchy can you run this statement and let me know the result?
`SELECT table_name as table_name,table_schema as table_schema,table_type as table_type FROM information_schema.tables WHERE table_schema = 'your_database_name';`
Replace your_database_name with the database name.

**Comment by voeurnchy** [comment]
I got this

The user specified as a definer ('mysql.infoschema'@'localhost') does not exist

**Comment by huyphams** [comment]
Are you upgrade from MySQL 5? I find some helpful resource here:
https://stackoverflow.com/questions/49992868/mysql-errorthe-user-specified-as-a-definer-mysql-infoschemalocalhost-doe

and here:
https://stackoverflow.com/questions/51155026/mysql-8-0-11-cant-find-mysql-infoschema-after-update-from-5-7
