### ISSUE TITLE
Can't connect to (local) SQL Server instance

### ISSUE THREAD

**Issue by malsama** [TablePlus/TablePlus#727]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

 SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Windows, build 15

3. The steps to reproduce this issue:

Connection to local SQL Server seems not to be supported (yet). I'm using the same settings as with Management Studio. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, we have the Windows repo here: https://github.com/TablePlus/TablePlus-Windows/issues
Btw, you're using the outdated of the Windows build, could you please update to build 16 and try again?
if it won't help, please email me the screenshot of the connection form, so I can reproduce the bug easier.

**Comment by marcbrayman** [comment]
I'm using the following settings:
Name: Test
Type: local
Host: PC\SQLEXPRESS
Port: 1433

Testing with 32 and 64 bits and latest build 16. I'm on Windows 10, 64 bits and SQL Server 2014 bits.

**Comment by huyphams** [comment]
Have you tried put 127.0.0.1\SQLEXPRESS instead of PC?

**Comment by marcbrayman** [comment]
Yes, I tried that. Also localhost. Problem is that the error message isn't informative; only "Cannot connect". A more detailed log would be helpful here.

**Comment by malsama** [comment]
Has anyone managed to connect to a local MSSQL instance (so not a remote SQL Server)? If so, please share your settings, because I still can't.

**Comment by AbdulhakimAwad** [comment]
please how did you solve thr problem?
