### ISSUE TITLE
Update row detail when refreshing workspace

### ISSUE THREAD

**Issue by rbngzlv** [TablePlus/TablePlus#729]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

```
MySQL 5.x
```

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

```
Version 1.0 (142)
```

3. The steps to reproduce this issue:

```
- Open database
- Select table to view their data
- Select a row to view their detail
- Change the value for any column outside TablePlus
- Click "Refresh workspace" button

The new value is shown in the table but isn't refreshed in the opened row detail sidebar.
```

**Comment by huyphams** [comment]
Hey @rbngzlv I got the bug 😄 very clear instructions 👍

**Comment by rbngzlv** [comment]
Works perfectly, thank you!
