### ISSUE TITLE
SQL tab content should be saved/loaded unique to database

### ISSUE THREAD

**Issue by safetypins** [TablePlus/TablePlus#731]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
NA

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
142

3. The steps to reproduce this issue:
NA

Noted: If the bug is related to data, please attach an example SQL data.
Currently, it appears the SQL tab loads a record of some SQL statements previously written associated with the database where I'm opening the SQL tab. If I open another SQL tab on a different database, it opens the same SQL statements that were opened previously. However, this initial SQL tab content appears to change based on the first database that I use to open the SQL tab. This seems to indicate to me that TablePlus is saving a backup copy of each SQL tab open, but on relaunch, it only loads a single SQL tab content backup, and then reuses that same backup instead of accessing the unique backup that was saved for a different database connection.

**Comment by huyphams** [comment]
I got it, thanks for pointing it out, I will consider making it unique.

**Comment by safetypins** [comment]
Is there an explanation of how the SQL tabs currently work in the docs?

Thanks for making such a great SQL interface!

**Comment by huyphams** [comment]
Currently, it is unique per connection not per database.

**Comment by huyphams** [comment]
it's per database now! thanks!
