### ISSUE TITLE
Moving a connection from one group to another, opens all the hovered groups

### ISSUE THREAD

**Issue by jmfederico** [TablePlus/TablePlus#734]
2. Which TablePlus build number are you using: 142

3. The steps to reproduce this issue:

When moving a connection from one group to another, all the groups one hovers on to get to the desired group end up being opened.

Only the group that the connection was dropped into should be opened.

![screen recording 2018-10-22 at 15 39 46 2018-10-22 15_43_48](https://user-images.githubusercontent.com/237977/47318312-58f46580-d611-11e8-8f8d-d5d40e13c05e.gif)

**Comment by huyphams** [comment]
Thanks, I just fixed it 👍
