### ISSUE TITLE
Oracle query Chinese gibberish

### ISSUE THREAD

**Issue by coralandbill** [TablePlus/TablePlus#736]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by coralandbill** [comment]
MacOS mojave
Oracle 12
TablePlus Version 1.0(143)

**Comment by fordguo** [comment]
I got the same problem.

**Comment by coralandbill** [comment]
The official reply said I would fix the problem in a later version

**Comment by Blacate** [comment]
Oracle 11.2.0.3.0
build 229
MacOS mojave

Any progress? I got the same problem.

**Comment by huyphams** [comment]
Hey guys, please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="1189" alt="utf8" src="https://user-images.githubusercontent.com/3654622/63312331-98461e00-c2d7-11e9-82e2-7b6276658765.png">
Let me know if you're still seeing the issue then I will reopen the issue.
