### ISSUE TITLE
Open same connection after update

### ISSUE THREAD

**Issue by Chris1904** [TablePlus/TablePlus#738]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Irrelevant

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
145

3. The steps to reproduce this issue:
I just had 2 connections open and some tables I was working in and after I updated the program through the update prompt, it took me back to the initial "Welcome to TablePlus" screen. It would be nice if it took me where I left off of :-)

Thanks for this awesome tool.

**Comment by huyphams** [comment]
It's already in our roadmap 👍
