### ISSUE TITLE
Big Problem executing large queries

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#74]
It seems in build 61 I am not allowed to even run large queries.  Now when I try to I get a message saying you are rebuilding the SQL parsing technology.  But in the mean time I cannot run any important queries.

i am losing functionality with the upgrade and now I cannot downgrade.

**Comment by huyphams** [comment]
I disabled it because it cause performance issues and crash the app. I'm working on `build 62` with optimization for large queries and history, grouping connection. I will be released in 20-Sep-2017

**Comment by huyphams** [comment]
New update will solve this problem + new design for SQL Query status bar
![largequery](https://user-images.githubusercontent.com/3654622/30242949-d1694c34-95ca-11e7-96e5-533166073c2f.png)
