### ISSUE TITLE
Can't import connections when connections list is empty

### ISSUE THREAD

**Issue by KaidenR** [TablePlus/TablePlus#740]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
n/a

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (142)

3. The steps to reproduce this issue:
- Remove all connections from the connections list
- Right-click the empty space. 
- The "Import" option is disabled but it should not be. To import something I have to create a new connection or group and right-click that.
- This is also a problem when the list is not empty and I right-click in the empty space. I should be able to import by right-clicking anywhere in the list whether it's empty or not.

**Comment by huyphams** [comment]
Thanks, I will fix it now 👍
