### ISSUE TITLE
Delete multiple rows in cassandra table

### ISSUE THREAD

**Issue by msandim** [TablePlus/TablePlus#741]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3.11.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 (142)

3. The steps to reproduce this issue:
Select multiple rows in a cassandra table, delete them and 'Commit your changes'. An error will appear because I think TablePlus is building the wrong CQL statement to delete multiple rows (using an 'or' condition in the WHERE part for the table's primary key).

The correct version should use the keyword 'in', as in:
```cql
DELETE FROM db.example_table
WHERE email IN ('email1', email2')
```

**Comment by huyphams** [comment]
Thanks @msandim, I just fixed this bug.

**Comment by msandim** [comment]
Nice, thanks for the quick fix! When can we expect a new release with this?

**Comment by huyphams** [comment]
We release a beta update every week, the next beta release will be on this weekend.
If you wish to receive a beta update, please go to preferences and turn on: Receive beta updates.
The stable build release once a month.
