### ISSUE TITLE
"Split result into tabs" and "Run all" doesn't work together ?

### ISSUE THREAD

**Issue by DrLuthor** [TablePlus/TablePlus#742]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostregreSQL 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 142

3. The steps to reproduce this issue:
I have scripts with many (100+) INSERT lines. The split tabs result is not very convenient to my needs as I have to make sure every single line worked. I learned via the FAQ you can disable the "Split results into tabs" option. Which I did. I changed the "Default" option to "Run all" at the same time. But then, the "Run all" command only execute the last query.
I tried changing "Default" back to "Run current" but it didn't work.
I try the good old quit and relaunch but it didn't change anything. 
The only way the "Run all" command seems to work is with the "Split results into tabs" enabled.
Did I missed something.

Bonus : 
I take this opportunity to tell you TablePlus has the best UI for a DB GUI running on macOS I've ever seen. It's a bit early to use it as my main and only tool but I hope it to be one day. Keep up the good work!

**Comment by huyphams** [comment]
Hey please follow this setup.
1. Turn of split result into tabs.
2. If the button execute is Run current. You cab press command + shift + return to execute all the query, however it only shows the last result. 

TablePlus default return on error, that means if there is an error, it will stop on that statement.

**Comment by DrLuthor** [comment]
Thanks.
So it worked but if the number of inserts is to low, the process is so short that I had to select query a record to make sure the data was inserted.
It would be great if in that case you could display at least the nb of successful queries, at best the line of the querie which failed.
