### ISSUE TITLE
improve selected table color contrast/pattern when unfocused (similar to issue #292)

### ISSUE THREAD

**Issue by technigit** [TablePlus/TablePlus#744]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (142)

3. The steps to reproduce this issue:

- Select Dark Theme
- Select a table (blue focus color pattern is fine, as in issue #292).
- When the window is not focused, the table name becomes hard to read.  It is something like medium gray on light gray.  It needs to be the same color pattern as the fix for issue #292, preferably with a black font across the board.

In the first attached screenshot, "roles" is hard to read.  The data row where it says "general" is better, but the foreground color should ideally be black in every column instead of a shade of gray.  Note that some data such as "NULL" is more black.  The inconsistency is rather puzzling.

![image](https://user-images.githubusercontent.com/9996410/47446758-895b1180-d781-11e8-86f4-73ab48490f62.png)

![image](https://user-images.githubusercontent.com/9996410/47446985-100fee80-d782-11e8-8717-b524cda78106.png)

**Comment by huyphams** [comment]
This issue is related to the macOS version, it looks better on Mojave (10.14) but on the old macOS 10.11~10.13 it has some issues.
<img width="1349" alt="screen shot 2018-10-24 at 11 47 16 pm" src="https://user-images.githubusercontent.com/3654622/47447232-3e73e500-d7e7-11e8-9200-5c11387b80a8.png">

**Comment by technigit** [comment]
I almost forgot to mention that the same goes for Open Anything.

![image](https://user-images.githubusercontent.com/9996410/47448141-e99f8280-d784-11e8-8713-803cf58b1cf9.png)

I assume this is also related to the old MacOS versions too.  Thanks!

**Comment by vgoloviznin** [comment]
@huyphams may be it's possible to make the colors adjustable? As on dark Mojave theme, the 'green' color indicating a new row added is just killing my eyes

**Comment by huyphams** [comment]
it's on our roadmap @vgoloviznin
