### ISSUE TITLE
TablePlus crashes when handling 64k line SQL query

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#745]
There must be a way to make TablePlus powerful enough to handle a 64k line SQL query! just editing this will slow my pc down.  I do understand it is a giant query though.  same issue with tables with > 10k rows showing

**Comment by brian-crane** [comment]
looks like pgadmin4 can handle 64k line query!

**Comment by huyphams** [comment]
Hi @brian-crane which build are you using? recently, I have improved the query editor which can handle more lines.
I have sent you a gift, please restart the app and update to build 146 👍

**Comment by alvint** [comment]
@brian-crane My curiosity is getting the better of me. What makes that query so large? Are you injecting data, and is that data random enough that you can't generate it with a recursive CTE?
