### ISSUE TITLE
Small UI tweaks for columns in SQL mode

### ISSUE THREAD

**Issue by mikerogne** [TablePlus/TablePlus#746]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**

MySQL, or anything really.

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**

Build 147

**3. The steps to reproduce this issue:**

In SQL mode, it would be nice if the columns were automatically sized so that they didn't wrap.

Also, if I resize the columns and re-run query, I'd really prefer they stay positioned where they were at after resizing.

I created a demo video here: https://d.pr/v/yMMjFq

**Comment by huyphams** [comment]
TablePlus remembers the column size in table but not in query result because it refresh everything and can't predict.

**Comment by mikerogne** [comment]
Surely it wouldn't be too challenging to remember the column names of the previous query & the currently executed query -- if they are the same, keep the column sizes the same?

**Comment by webdestroya** [comment]
Navicat does this and it's the 1 feature I miss in TablePlus :(

When you adjust the column size it will remember for all subsequent runs of that query in the same tab. It's super useful when trying to view the process list (and see the query). Right now in tableplus everytime I refresh the query i have to go and readjust the `query` column size because it wraps.

**Comment by ssoroka** [comment]
Would love to see this feature. It's super annoying that TablePlus:
A) Can't check the max-width of the first 30 results and come up with a guess at what the column width should be.
B) doesn't remember the column widths I set for re-running the same query.

Example query where this is really annoying: `SELECT pid,usename,query_start,wait_event_type,wait_event,state,query FROM pg_stat_activity`

**Comment by huyphams** [comment]
Thanks @ssoroka I have time for those small UI issues now 😄

**Comment by huyphams** [comment]
This improvement will be included on the next update, actually, it was released on the beta build.

**Comment by mikerogne** [comment]
Ahh, much better. Thanks :)
