### ISSUE TITLE
Field values are displayed as question marks

### ISSUE THREAD

**Issue by pavelvolkov** [TablePlus/TablePlus#748]
There is a problem with cyrrilic symbols in TablePlus when database stores data in cp1251.

TablePlus 1.0 (build 147)
<img width="434" alt="2018-10-29 11 37 49" src="https://user-images.githubusercontent.com/695020/47629677-2695bb80-db6f-11e8-86e6-f75c91eb2b93.png">

**Comment by huyphams** [comment]
Hi @pavelvolkov can you please run this command: 
show variables like "character_set_database";
And let me know the result? is it latin1?

**Comment by pavelvolkov** [comment]
@huyphams , when I try to run the command in SQL Query tab it returns:

`ORA-00900: ??????? ??????????? ?? ????? SQL`

The error message is also in question marks :/

**Comment by huyphams** [comment]
TablePlus support Unicode for Oracle, please let me know if you're still seeing it.
