### ISSUE TITLE
Locks database while dumping

### ISSUE THREAD

**Issue by fgilio** [TablePlus/TablePlus#750]
Hi!

This is more of a question and not a bug report. I'm used to exporting databases in SequelPro, it gives me a .sql file and the DB is still responding to other requests during the export. I've just tried exporting with TablePlus and 2 things happened:
- I got a .dump, which I think is not a big deal at all.
- The DB got locked and wouldn't respond to other requests during the dump process. This basically made our app inaccessible and users started to get 502s.

Is there any way to replicate SequelPro behaviour?

Thanks!

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.16
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
146
3. The steps to reproduce this issue:
Dump a database from AWS RDS

**Comment by huyphams** [comment]
Hi @fgilio please add this option: --lock-tables=false
Ref: https://stackoverflow.com/questions/104612/run-mysqldump-without-locking-tables

**Comment by fgilio** [comment]
Like this?
<img width="258" alt="screen shot 2018-10-29 at 12 40 52" src="https://user-images.githubusercontent.com/6857732/47661477-e424ac80-db77-11e8-86aa-c85a84813518.png">
I'll test it later when there are less users connected.

**Comment by huyphams** [comment]
Yep, TablePlus supports all the flag or mysqldump, full list here: https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html

**Comment by fgilio** [comment]
Awesome, thanks!

**Comment by fgilio** [comment]
It's working perfectly with this flags `--single-transaction,--compress,--lock-tables=false`
