### ISSUE TITLE
UI workplaces and windows

### ISSUE THREAD

**Issue by kliment-toshkov** [TablePlus/TablePlus#755]
Would like the option to have separate windows (option to detach workplace to another window). In such configuration I would be able to easily switch between two specific tables when working on multiple models at the same time.

**Comment by alvint** [comment]
@kliment-toshkov I know you can hit cmd-n to open a whole new app window. Then you can log in to the same DB. I'm not sure that's what you're looking for, though...

**Comment by kliment-toshkov** [comment]
Hi. I’ve tried it before posting but it did not work at the time of the test. Maybe my fault because it works now. it is exactly what I need.
