### ISSUE TITLE
UI - filtering values 

### ISSUE THREAD

**Issue by kliment-toshkov** [TablePlus/TablePlus#757]
When applying filter on large table, it takes time for the server to return response. Would be very nice to have visual indication that the program is waiting for return data on the newly applied filter values. Currently when I have to filter some data repeatedly (checking a list for some reason) I press enter and don’t know if I am viewing old data or the new data.

**Comment by huyphams** [comment]
There are two indicators in TablePlus.
1. Progress bar.
2. Cancel button. 
<img width="1514" alt="screen shot 2018-10-29 at 11 09 56 pm" src="https://user-images.githubusercontent.com/3654622/47663563-e61a5a00-dbcf-11e8-8906-95263a0d3c41.png">

**Comment by kliment-toshkov** [comment]
Thanks for that. Cancel/refresh button does not change here, icon always staying in “refresh” mode. You should look into this.
Progress bar by itself is fine, but when used as indicator that something is going on it is very subtle. I really prefer something more visual.

**Comment by kliment-toshkov** [comment]
Also please note that the progress bar is not accurate. It has disappeared but the results changed a few seconds after that. Not reliable at all. Something spinning and more visual would be far better.

**Comment by huyphams** [comment]
I fixed the button state bug, now it can report correct state when applying filters.
