### ISSUE TITLE
Text box to edit large fields instead of inline.

### ISSUE THREAD

**Issue by kliment-toshkov** [TablePlus/TablePlus#760]
Shortcut to access “quick view” mode on a given field? Double clicking or other control on text fields to open a box to edit. Inline editing long text is absolutely inconvenient.

**Comment by huyphams** [comment]
You can use the right pane or using quick look to edit the cell:
<img width="735" alt="screen shot 2018-10-29 at 11 00 48 pm" src="https://user-images.githubusercontent.com/3654622/47662947-83748e80-dbce-11e8-94fd-a750fbfcc917.png">
<img width="1235" alt="screen shot 2018-10-29 at 11 01 21 pm" src="https://user-images.githubusercontent.com/3654622/47662995-98512200-dbce-11e8-86f3-afffd518e0ea.png">

**Comment by kliment-toshkov** [comment]
Thanks! Had no idea that it is editable. Excellent for the purpose.
