### ISSUE TITLE
UI - count of filtered results

### ISSUE THREAD

**Issue by kliment-toshkov** [TablePlus/TablePlus#761]
Filter is applied on the table, bottom counter does not change and still shows total count of rows. There is no information on how many results the filter returned.

<img width="1278" alt="screenshot 2018-10-29 at 22 03 10" src="https://user-images.githubusercontent.com/10902296/47677024-c16db480-dbc6-11e8-88e4-5dbe07e6413c.png">

**Comment by kdambekalns** [comment]
Works for me now (with build 165)

**Comment by huyphams** [comment]
Sorted out via email.
