### ISSUE TITLE
Korean character appears as a question mark

### ISSUE THREAD

**Issue by m8928** [TablePlus/TablePlus#764]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Oracle 11g

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

146

3. The steps to reproduce this issue:
Korean character appears as a question mark.

"NLS_CHARACTERSET","AL32UTF8"
"NLS_NCHAR_CHARACTERSET","AL16UTF16"
"NLS_LANGUAGE","AMERICAN"

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="1189" alt="utf8" src="https://user-images.githubusercontent.com/3654622/63312331-98461e00-c2d7-11e9-82e2-7b6276658765.png">
Let me know if you're still seeing the issue then I will reopen the issue.
