### ISSUE TITLE
UI - keyboard shortcut to insert NULL value

### ISSUE THREAD

**Issue by kliment-toshkov** [TablePlus/TablePlus#765]
How to insert NULL value with keyboard shortcut, not by using right pane?

**Comment by huyphams** [comment]
Currently, you can only insert with mouse. Hold option + click on the cell to quick access.
P.s if you have any question, free free to ping us on chat or email customer support at nick@tableplusapp.com
Issues tracker is not a good place to ask/answer.

**Comment by kliment-toshkov** [comment]
I will check the chat. Reported here as you may qualify the question as “feature request” which is invaluable when having relatively new project and receiving feedback from users that are used to very mature programs like Sequel PRO. Of course will take incon sideration your preferences. Thanks

**Comment by huyphams** [comment]
Thanks @kliment-toshkov I appreciate your help, it helps me improve TablePlus better.

**Comment by gregblass** [comment]
+1. Would argue that this is pretty important. For instance, I have a query that checks for a null value. I changed it in a row to something else for testing - and now I have no way to get it back through the GUI.
