### ISSUE TITLE
Connect over SSH on Port 222 fails

### ISSUE THREAD

**Issue by wazum** [TablePlus/TablePlus#766]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 (146)
3. The steps to reproduce this issue:
Server: somehost.com
Port: 222
Using username and password.
Everything else filled out correctly.

SSH works `ssh -p222 user@somehost.com`
and Sequel Pro (another macOS SQL client) has no problem either …
I get no concrete error message, so I'm a bit lost with further support for this issue.

**Comment by huyphams** [comment]
Thanks @wazum which is the step that TablePlus hangs on?

**Comment by wazum** [comment]
@huyphams  When I press the Test button, hostname and port appear in red (immediately):

![screenshot 2018-10-31 at 08 59 33](https://user-images.githubusercontent.com/146727/47773736-54a00a80-dceb-11e8-9240-b97ba01967fc.png)

Here's some debug output for a working SSH connection:
```debug1: Local version string SSH-2.0-OpenSSH_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8 pat OpenSSH_6.6.1* compat 0x04000000```

**Comment by wazum** [comment]
Doesn't work either, but it takes longer before the error appears (so … in the background there's some connection trial going on I guess…).

Any possibility to get a more detailed error message, some log or so?

**Comment by huyphams** [comment]
Yep, there is a debug build.
1. Download the build: https://www.dropbox.com/s/qdijo59365vsl97/TablePlus-Debug.dmg?dl=0
2. Open the DMG and drag out the app on Desktop. Do not open the app.
3. Open Terminal.
```
cd Desktop/
./TablePlus-Debug.app/Contents/MacOS/TablePlus
```
4. Click connect or hit the test button, you will see the log in the terminal.

**Comment by wazum** [comment]
Hm, very strange … I used this build and it worked out of the box and now when I use the other version I downloaded before it works too … but still only with the IP address and not the hostname …

**Comment by huyphams** [comment]
Hmm, looks like there's some invisible character (inserted by mistake). I justed with the IP address + a whitespace and it raises an error.
TablePlus should trim whitespace from the beginning and ending automatically.
