### ISSUE TITLE
Schemas and their tables not visible in SQL Server on Azure

### ISSUE THREAD

**Issue by adamshaylor** [TablePlus/TablePlus#767]
**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**

Microsoft SQL Server

**2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):**

146

**3. The steps to reproduce this issue:**

a. Connect to a SQL Server instance on Azure.
b. Open the menu in the lower-left corner.

_Expected:_ Schemas should appear in the menu.
_Saw:_ Standard meta-schemas, but none of ours.

c. Open the “open anything” search palette and start typing the name of a table in a schema.

_Expected:_ Matching tables should should appear in the results.
_Saw:_ Nothing.

This is not a problem in SQLPro for MSSQL. DM me if you’d like to see this over a screen share.

![screen shot 2018-10-30 at 10 35 24 am](https://user-images.githubusercontent.com/673870/47738228-f4985e00-dc2f-11e8-89d2-a595b0ba3b32.png)

**Comment by huyphams** [comment]
Hmm looks like azure stores schemas in sys.users.
```
select s.name as schema_name, 
    s.schema_id,
    u.name as schema_owner
from sys.schemas s
    inner join sys.sysusers u
        on u.uid = s.principal_id
order by s.name
```

**Comment by adamshaylor** [comment]
Funny thing: I didn’t start seeing this bug until a few days ago.

**Comment by huyphams** [comment]
Or you can upgrade to the build 149 (preferences: Receive Beta Updates), that should fix the issue as well.
