### ISSUE TITLE
SQL Server, duplicate row with Identity column (int) set to DEFAULT cannot commit

### ISSUE THREAD

**Issue by DHFW** [TablePlus/TablePlus#768]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server 2014. (MacOS)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0, build 146

3. The steps to reproduce this issue:
Create a table with identity column (type int). Have a record in the table (with insert it works fine). Duplicate that row, the identity column will list DEFAULT as the "value" for the int column. SQL Server indicates that you cannot insert DEFAULT or NULL.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
it's fixed now, thanks!
