### ISSUE TITLE
Ability to resize starting window

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#77]
Currently start window cannot be resized - I think maybe we should be able to resize it and if it can remember the dimensions for future startups that would be a plus.

**Comment by huyphams** [comment]
Hello @brian-crane nice Monday 😁
I will make it resizable and hope it is not ugly

**Comment by huyphams** [comment]
it is ok @brian-crane 😂
![screen shot 2017-09-18 at 9 42 48 am](https://user-images.githubusercontent.com/3654622/30527705-c0b8d10c-9c55-11e7-867a-eafa5a49a2e8.png)

**Comment by huyphams** [comment]
I think we can keep this design, will release this feature in update 63
![screen shot 2017-09-18 at 10 50 43 am](https://user-images.githubusercontent.com/3654622/30528654-3da72ea8-9c5f-11e7-84ad-acc6f24c9649.png)
