### ISSUE TITLE
[BUG]  Data not reflecting of Cassandra DB in TablePlus Version 146

### ISSUE THREAD

**Issue by vktafs5309** [TablePlus/TablePlus#772]
1. I have installed cassandra in MACBOOK.
2. Now i created a keyspace named dev and created emp table with the below mentioned query:
     a. INSERT  KEYSPACE Dev WITH replication = {'class':'SimpleStrategy','replication_factor': 1 };
     b. CREATE TABLE emp(emp_id int PRIMARY KEY, emp_name text, emp_city text, emp_sal varint,  
         **emp_phone** varint);

3. Now in TablePlus i have given the url as localhost and port as 9042.
4. Now i inserted the data in the emp table by below shown query:
     INSERT INTO emp (emp_id, emp_phone, emp_sal, emp_name, emp_city) VALUES( 1, 9848022338, 
      50000, ’ram',   @@'Hyderabad');
5. Now when i am seeking the data in the table of Dev keyspace only emp_id,emp_city,emp_name is 
    reflecting other like **emp_sal,emp_phone are not reflecting.**

Please resolve it asap as i found TablePlus very easy to use and simple.
Want to use it further.

**Comment by huyphams** [comment]
Thanks @vktafs5309 let me see the bug.

**Comment by huyphams** [comment]
Hey @vktafs5309 this build should fix your issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Now TablePlus supports varint and decimal.

**Comment by huyphams** [comment]
It's released on the beta build 149.
