### ISSUE TITLE
[Feature request] view table relations

### ISSUE THREAD

**Issue by CrixuAMG** [TablePlus/TablePlus#773]
https://www.araelium.com/querious

Querious 2 has a feature wherein you can view the foreign key links between tables, giving an easy overview of how the database is setup.
Clicking on one of the tables highlights it and the direct links (such as `users => posts` or `cars => makes`).
It would also be useful to have a button that toggles showing all columns for that table, or to have a count of the total amount of rows for that table.

**Comment by huyphams** [comment]
Hi,
I'm not sure if this is the feature that you mentioned:
<img width="1453" alt="nice" src="https://user-images.githubusercontent.com/3654622/48570475-0586e600-e937-11e8-9aa0-2b482c8617a9.png">

**Comment by CrixuAMG** [comment]
Not exactly what I meant, I know clicking the arrow will show the row the id is linked to via the foreign key.

In the screenshot below you can see an example of how it looks in Querious 2, where the arrows indicate the direction of the foreign keys.

![](https://d2l5v8ibvnnoh9.cloudfront.net/assets/querious/main_relationships-18010174306bfb84dcc72a8d131d517eed818cb6bce1cffce5b45e3e87e4a52f.jpg)

**Comment by huyphams** [comment]
It's supported now via Plugin System Command + L > Diagram.

**Comment by charleshsb** [comment]
I just discovered this thread as I am trying to find this feature on table plus. However diagram generates a schema of the table but does not include relation tables. Is there something I am missing here?
