### ISSUE TITLE
Redis connection too slow

### ISSUE THREAD

**Issue by shirshak55** [TablePlus/TablePlus#776]
Redis driver is too slow to access over ssh tunnel on remote server. It takes 5 min to load full redis database. Is it default behaviour?

**Comment by huyphams** [comment]
Thanks, @shirshak55, but TablePlus takes time to database listing or load content of a database?
If it was content of a database, please change this value:
<img width="442" alt="screen shot 2018-11-02 at 4 41 23 pm" src="https://user-images.githubusercontent.com/3654622/47907671-448c5480-debe-11e8-97b5-190f0f125d05.png">

**Comment by shirshak55** [comment]
hmm it loads like 1 row per second instead of loading all of them at once

**Comment by huyphams** [comment]
Let me see if I can do bulk loading, currently, TablePlus sends separated command to load each row, and the I/O and latency are the bottleneck.

**Comment by shirshak55** [comment]
hmm mysql loads fine all at once but redis has some issue. Yea i live abit far from digital ocean server.

**Comment by danielpavone** [comment]
I’ve got the same problem 😕

**Comment by shirshak55** [comment]
its unusable actually.

**Comment by huyphams** [comment]
As I mentioned above, Redis doesn't have bulk loading, so if you want to view the database, please change the default value-key, 300 is too many.

I also checked rdm (another Redis client) they're using the same method with TablePlus. (load key by key).

**Comment by shirshak55** [comment]
even loading 20-30 takes 1 minute

**Comment by huyphams** [comment]
Okay, I will try to optimize it but not for sure it can be improved.

**Comment by shirshak55** [comment]
There are some apps in mac which loads too fast. I used to use it like 1 years ago it loads too fast.

There should be way for bulk loading like I can load all keys etc 

https://chartio.com/resources/tutorials/how-to-get-all-keys-in-redis/

**Comment by huyphams** [comment]
Get key with a pattern is not a good idea, it can lead to some performance issue. The bottleneck here is when TablePlus tries to load value of the keys. I think TablePlus should not load value by default or it needs to be smart when loading values.

**Comment by huyphams** [comment]
Hey guys, I just optimized Redis, now it would load 100x faster if all your Redis key are STRING type.
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by shirshak55** [comment]
@huyphams should we download it or tableplus update is coming?

**Comment by huyphams** [comment]
You can download and keep using it, if the new version is released, it can self-update, no worries.
