### ISSUE TITLE
Mysql Common Keywords Missing In Autocomplete

### ISSUE THREAD

**Issue by xingtianyoulong** [TablePlus/TablePlus#777]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.x
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 150
3. The steps to reproduce this issue:
When Type 'convert_tz'，no keyword found in autocomplete list.
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @xingtianyoulong let me add it to TablePlus.

**Comment by xingtianyoulong** [comment]
@huyphams ，thanks very much! 
Tips：You are doing a great software -_-
