### ISSUE TITLE
Single quotes not being escaped in Cassandra

### ISSUE THREAD

**Issue by msandim** [TablePlus/TablePlus#778]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3.11.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.0 (150)

3. The steps to reproduce this issue:
Create a table with a text field with a random string, without single quotes (e.g. `mariah`).
Try to change the field to a value with single quotes (e.g. `this is 'maria'`) and commit your changes. You will get an error.

**Comment by huyphams** [comment]
Thanks @msandim it's fixed, it will be released on the next beta release (weekly update).
