### ISSUE TITLE
Escape name of foreign key when deleting

### ISSUE THREAD

**Issue by steffendsommer** [TablePlus/TablePlus#779]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.19

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 150

3. The steps to reproduce this issue:
- Create a foreign key e.g. `_some_foreign_key.table-users.id`
- Delete the foreign key using the UI
- Before committing the changes, have a look at the generated SQL statement: 
```
ALTER TABLE `db`.`table` DROP FOREIGN KEY _some_foreign_key.table-users.id;
```
- Commit and note the error saying something along the lines of `Incorrect table name '_some_foreign_key'
All changes were reverted.`

If you manually change the SQL statement to 
```
ALTER TABLE `db`.`table` DROP FOREIGN KEY `_some_foreign_key.table-users.id`;
```
then it works.

**Comment by huyphams** [comment]
Thanks @steffendsommer let me fix it.
