### ISSUE TITLE
Trim connection detail inputs, plz.

### ISSUE THREAD

**Issue by coolcorey** [TablePlus/TablePlus#781]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
N/A
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
142
3. The steps to reproduce this issue:
Create or Edit a connection.
Noted: If the bug is related to data, please attach an example SQL data.
None of the input fields (Host/Socket, Database, ...) seem to trim() the input text. Trailing spaces are pretty common with copy+paste, so errors like "No such database" due to trailing spaces are pretty confusing.

**Comment by huyphams** [comment]
Hi @coolcorey I've added this function to build 150 already. TablePlus will trim trailing whitespaces in host and server address but not in database name because a whitespace is a valid character for the database name.
