### ISSUE TITLE
Multi SQL Tab Function

### ISSUE THREAD

**Issue by xingtianyoulong** [TablePlus/TablePlus#782]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 5.x
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 150
3. The steps to reproduce this issue:
There is no multi tab for SQL query，it's so inconvenient for us to write diff modules SQL.All SQL in one tab is so long and a little slow when edit.The split panel can't save and the window is so small，we need a add+ tab for SQL query, please think about this，thanks.

**Comment by Tungtono** [comment]
This can do the trick:
- Open the first Query editor.
- Click to open any table
- Click on the Query Editor icon. 

TablePlus will replace the current table with another SQL query editor. You can also open as many editors as you want this way.

**Comment by xingtianyoulong** [comment]
ok，your trick is working ，thanks very much!

**Comment by xingtianyoulong** [comment]
@Tungtono ，But I think it's a little complex，I suggest give a add icon somewhere to add tab directly，it's an important & common function used very frequently，thanks

**Comment by xingtianyoulong** [comment]
@Tungtono ，The most importantly，when I create multi tab，close software and reopen，there is only one tab now...my next tab & sql is lost...

**Comment by huyphams** [comment]
Hi @xingtianyoulong On the new build, I changed the behavior, now every time you pressed the SQL Button, TablePlus will create a new SQL Tab.

Regarding to reopen tabs, it hasn't been supported yet.

**Comment by xingtianyoulong** [comment]
Hi @huyphams ，that's cool，looking forward to add reopen tabs later，thanks.

**Comment by huyphams** [comment]
"reopen tabs later" would be the other issue. so I will close this one for now.
