### ISSUE TITLE
Lost connection not flagged, 'reconnect' not working

### ISSUE THREAD

**Issue by thecorz** [TablePlus/TablePlus#784]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 150
3. The steps to reproduce this issue:
After a few hours using the program, I loose connection with the server, but the program  would not flag it or indicate that the connection is lost, the queries look like they are running but they are not which is obviously quite annoying. Then the only way to see if the connection is alive is to run a query that I know for sure runs very quickly and wait to see if it returns something quickly. If that quick query fails to return I try to 'Reconnect' from the 'Edit' menu but it failed several times. 
The only way to reconnect then is to open a new connection, which means I have to copy and paste all my queries, which is very inconvient. 
Please notice that the 'Auto reconnect connection' and 'Keep connection alive' options from the 'Preferences' menu are ticked.
We adqured three licences recently cause 

We adquired three licenses recently in the company but obviously the program has some issues that need to be addressed

**Comment by huyphams** [comment]
Thanks @thecorz for the supporting. I will investigate this bug. We also have the shortcut for force-reconnect: Command + Shift + R.
