### ISSUE TITLE
[Feature request] PL/SQL support

### ISSUE THREAD

**Issue by Ilyumzhinov** [TablePlus/TablePlus#785]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
OracleSQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Beta (151)

I've been doing some PL/SQL programming using SQLDeveloper for mac. I know, you are only beta testing Oracle SQL support (thank you for that!) but is it possible you would add PL/SQL support as well? Currently, the app would not run the code at all, even though it manages to recognise exiting PL/SQL functions. Thank you.

**Comment by huyphams** [comment]
@Ilyumzhinov thanks, let me see if I can add it to TablePlus, is this a good place to getting started?
https://www.tutorialspoint.com/plsql/plsql_basic_syntax.htm

**Comment by huyphams** [comment]
Hey @Ilyumzhinov it's supported on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 feel free to give me feedback.
