### ISSUE TITLE
Opening too many databases relative to screen size indents top side

### ISSUE THREAD

**Issue by thenaturalist** [TablePlus/TablePlus#786]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
153

3. The steps to reproduce this issue:
Open TablePlus on a small screen (happened on 13" MBP). 
Open a connection to a server with many DBs on it. 
Connect to multiple DBs (~7-8 on 13"). 
As soon as the number of DBs exceeds the height of the screen, the left panel where the DBs are listed does not become scrollable. Instead, the top window just resizes automatically hiding all critical icons and control elements. It's impossible to open a SQL console or open another DB or connection. 
This also happens if you open many DBs on a big monitor and pull the TablePlus window onto a smaller screen. 

The entire program is indented from the top like so:
<img width="799" alt="bildschirmfoto 2018-11-09 um 17 35 07" src="https://user-images.githubusercontent.com/8865167/48276108-7ca81000-e447-11e8-853f-7e3a9cf24358.png">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, @thenaturalist this is one of the know issues, I gonna improve it with a scrollbar.

**Comment by huyphams** [comment]
Hi, sorry for the late response. it has been fixed now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
