### ISSUE TITLE
[Snowflake] Freeze when Opening Table Data without Selecting Warehouse

### ISSUE THREAD

**Issue by andyoneal** [TablePlus/TablePlus#787]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake 3.3.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
150

3. The steps to reproduce this issue:
* Create a Snowflake connection with Warehouse left blank
* Connect using connection
* Select a schema, click a table/view from list
* Data view is opened by default
* Error message appears: "No active warehouse selected in the current session. Select an active warehouse with the 'use warehouse' command.
* App hangs forever (beachball). Can't click Ok on error. Must force quit.

Opening structure works fine. If I specify a warehouse in the connection, it works fine.

<img width="1274" alt="screen shot 2018-11-09 at 12 55 43 pm" src="https://user-images.githubusercontent.com/2807932/48282580-b7964d80-e41f-11e8-8153-f27103701a49.png">

**Comment by huyphams** [comment]
I will close this one because it is the same issue with https://github.com/TablePlus/TablePlus/issues/788
