### ISSUE TITLE
[Snowflake] Freeze on SQL Error

### ISSUE THREAD

**Issue by andyoneal** [TablePlus/TablePlus#788]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake 3.3.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
150

3. The steps to reproduce this issue:
* Run a SQL query that will cause an error to be returned.
* Error is returned, query text is highlighted red.
* App hangs for a few seconds.
* Click within in the query window and red highlight will disappear.
* App hangs again, this time forever.

Activity monitor shows TablePlus 200% cpu until force quit.

**Comment by huyphams** [comment]
Hi @andyoneal thanks, I fixed this bug: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
