### ISSUE TITLE
Redis data error

### ISSUE THREAD

**Issue by LeaMem** [TablePlus/TablePlus#789]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
   reids 5.0.0
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
   build 150
3. The steps to reproduce this issue:
   i used jedis and switched to db 15, then inserted some data into redis.
but when i opened tableplus, there were no data in db 15.
however there were data in other GUI client
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I've tested and it shows correctly, I don't think it related to redis version.
<img width="1579" alt="screen shot 2018-11-10 at 4 08 08 pm" src="https://user-images.githubusercontent.com/3654622/48299678-e2a59d80-e502-11e8-8b67-1535cbf48900.png">

**Comment by huyphams** [comment]
Hmm, I got the bug, thanks

**Comment by LeaMem** [comment]
ok, thanks a lot
