### ISSUE TITLE
Duplicated column in structure cannot be committed.

### ISSUE THREAD

**Issue by FedericoBiccheddu** [TablePlus/TablePlus#79]
Step to reproduce the issue:

1. Click "Structure"
1. Click "Duplicate" in the contextual menu
1. Change the column name
1. Click "Commit"

The given error will be:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AFTER `changed_name`' at line 1
All changes were reverted
```

After a bit of attempts the problem seems to be the `ordinal_position` that is not incremented and stays the same as the original copied column. 
This is not a major issue, but from an UX perspective can be a nice enhancement. 

By the way thank you for the hard work.

**Comment by huyphams** [comment]
Yeah thank you, This issue should be fixed

**Comment by huyphams** [comment]
@FedericoBiccheddu can you provide me which build are you using?

**Comment by FedericoBiccheddu** [comment]
Hi @huyphams,

yes, of course. I'm running v1.0 (63) on macOS 10.12.6.

**Comment by huyphams** [comment]
@FedericoBiccheddu sorry for delaying reply,
I checked build 63 on my Laptop and it works, `ordinal_position ` wasn't the problem, it's using for sort column position and not included in generate statement.
it would be great if you can copy for me the SQL Statement in preview window.
You can send it to me via support email support@tableplus.io if you don't want to public it.
Thank you

**Comment by FedericoBiccheddu** [comment]
Hi @huyphams, sorry for the delay.

With the last version, v1.0 (65), the problem seems to be fixed.

Thanks for the support and the amazing product.
