### ISSUE TITLE
[Feature Request] Whether the backup database has the option to select the output file compression (Gzip, etc.)

### ISSUE THREAD

**Issue by tinghom** [TablePlus/TablePlus#792]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 150

Whether the backup database has the option to select the output file compression (Gzip, etc.), and restore the database can directly select the compressed file, in order to reduce the disk space occupied by the backup and increase the convenience of restore, thank you for your efforts.

**Comment by huyphams** [comment]
It's released on the build 182.
