### ISSUE TITLE
[Feature Request] Additional keyboard shortcuts under the ⌘F menu

### ISSUE THREAD

**Issue by heathyboyj** [TablePlus/TablePlus#793]
(I've only used MySQL 8.* with TablePlus, but I assume most drivers offer this list of functions)

For clarity, I'm talking about this menu / set of shortcuts:
![image](https://user-images.githubusercontent.com/20686879/48339236-a0de3980-e65f-11e8-9cc1-4e0320cefe22.png)

As someone who hates using a mouse when keyboard shortcuts are available, there are a few keyboard shortcuts I'd love to see:

- "Apply All" shortcut (⌘⇧Enter, maybe?)
- Remove the current filter row
- Enable/Disable the current filter row

Thanks!

**Comment by huyphams** [comment]
1. Apply All: Command + Return 
2. Remove current filter: Command + Shift + I.
3. I will add this shortcut in the next update.
Thanks for the feedback.

**Comment by heathyboyj** [comment]
Aha, thanks for the info on the first two :D 

It currently says "Apply Selected" for Command+Return, which I would assume to be the current highlighted (a.k.a selected) row - could I suggest updating the UI to say "Apply All" instead then? And showing the **⌘⇧I** shortcut on the UI so that other people don't ask this in future?

Thanks again!

**Comment by huyphams** [comment]
yeah, change the title to Apply All will make more sense. I will update it 👍
