### ISSUE TITLE
Since Postgres 11.0: Function List not displayed

### ISSUE THREAD

**Issue by nicowolf91** [TablePlus/TablePlus#794]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.0 (server version)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
150

3. The steps to reproduce this issue:
- Connect to a existing database using PostgreSQL version 11 (server-side)
- Navigate to a schema containing functions
- no functions will be shown anymore

I think it's the result of the following error (from the logs):

`2018-11-12 17:50:02.576 UTC [163] ERROR:  column p.proisagg does not exist at character 343`

`2018-11-12 17:50:02.576 UTC [163] HINT:  Perhaps you meant to reference the column "p.prolang".`

`2018-11-12 17:50:02.576 UTC [163] STATEMENT:  SELECT p.oid AS oid,pg_get_function_identity_arguments(p.oid)AS args,p.procost AS function_cost,CASE WHEN p.provolatile='v'THEN'VOLATILE'WHEN p.provolatile='s'THEN'STABLE'WHEN p.provolatile='i'THEN'IMMUTABLE'ELSE'VOLATILE'END AS function_volatility,l.lanname AS function_lang,n.nspname AS function_schema,p.proname AS function_name,CASE WHEN p.proisagg THEN'agg'WHEN p.proiswindow THEN'window'WHEN p.prorettype='pg_catalog.trigger'::pg_catalog.regtype THEN'trigger'ELSE'normal'END AS function_type FROM pg_catalog.pg_proc p LEFT JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace LEFT JOIN pg_catalog.pg_language l ON l.oid=p.prolang WHERE n.nspname<>'pg_catalog'AND n.nspname<>'information_schema';`

**Comment by huyphams** [comment]
Thanks, it will include this fix in the next release. The beta version will be patched first.
