### ISSUE TITLE
Index Manager?

### ISSUE THREAD

**Issue by tfreedman** [TablePlus/TablePlus#795]
I started using the Windows version of TablePlus yesterday, to connect to a Postgres server I have. This so far looks to be exactly what I want (essentially a Windows version of Postico), though I don't see any way to view / manage the indexes that the DB has. Does the Mac version of TablePlus have this, and is this scheduled to come to Windows any time soon?

**Comment by huyphams** [comment]
Hey @tfreedman I have added index support on the build 28, not all features were supported but I will add more in the future.

<img width="1375" alt="screen shot 2018-11-16 at 5 28 24 pm" src="https://user-images.githubusercontent.com/3654622/48616061-1b42ec80-e9c5-11e8-9933-78fbf904f709.png">

If you need anything else, feel free to open another issue in the [TablePlus Windows Repo](https://github.com/TablePlus/TablePlus-Windows/issues) . This repo is using for the Mac version.
