### ISSUE TITLE
Cannot connect over SSH

### ISSUE THREAD

**Issue by madmanmax** [TablePlus/TablePlus#796]
1. MySQL 5.x
2. Version 1 (build 150) (Licensed version)

We're evaluating TablePlus as an alternative to Sequel Pro however it seems that it's not working over SSH. Connecting through SSH via terminal to the same IP and username in the console works. Same configuration in Sequel Pro works as well. In TablePlus however when pressing the `Test` button the User field turns red:

<img width="467" alt="table_plus_ssh_user_20181112" src="https://user-images.githubusercontent.com/1675195/48378941-ba6c9900-e6d2-11e8-9716-eb28adf1f1c8.png">

When pressing the `Connect` button the following error message pops up:

```
Connect error
Invalid host password
```

<img width="635" alt="table_plus_ssh_password_20181112" src="https://user-images.githubusercontent.com/1675195/48379000-f6076300-e6d2-11e8-9ff5-304b558ff4cf.png">

When using the debug version the following error message is output in the console:

```
ssh_packet_userauth_failure:  Access denied. Authentication that can continue: publickey
```

**Comment by huyphams** [comment]
Hey @madmanmax if you’re using the ssh config, you must check the Use SSH key in the form.

**Comment by madmanmax** [comment]
It was that easy... I always tried to import a key with that option checked. Thanks!

**Comment by geoffreywiseman** [comment]
I did the same thing without seeing that checkbox, FWIW.
