### ISSUE TITLE
Don't quote a output of EXPLAIN queries while copying it out

### ISSUE THREAD

**Issue by deepj** [TablePlus/TablePlus#797]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.0
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
150
3. The steps to reproduce this issue:

Run any `EXPLAIN` with any query and see the output.

When I run this SQL command (the SELECT is just my example)

```sql
EXPLAIN (ANALYZE, FORMAT JSON)
SELECT * FROM countries
```

And then I copy the output using `Command` + `c`. It's quoted

```
"[
  {
    ""Plan"": {
      ""Node Type"": ""Seq Scan"",
      ""Parallel Aware"": false,
      ""Relation Name"": ""countries"",
      ""Alias"": ""countries"",
      ""Startup Cost"": 0.00,
      ""Total Cost"": 5.54,
      ""Plan Rows"": 254,
      ""Plan Width"": 55,
      ""Actual Startup Time"": 0.025,
      ""Actual Total Time"": 0.065,
      ""Actual Rows"": 254,
      ""Actual Loops"": 1
    },
    ""Planning Time"": 5.266,
    ""Triggers"": [
    ],
    ""Execution Time"": 0.093
  }
]"
```

But I would expect:

```
[
  {
    "Plan": {
      "Node Type": "Seq Scan",
      "Parallel Aware": false,
      "Relation Name": "countries",
      "Alias": "countries",
      "Startup Cost": 0.00,
      "Total Cost": 5.54,
      "Plan Rows": 254,
      "Plan Width": 55,
      "Actual Startup Time": 0.025,
      "Actual Total Time": 0.065,
      "Actual Rows": 254,
      "Actual Loops": 1
    },
    "Planning Time": 5.266,
    "Triggers": [
    ],
    "Execution Time": 0.093
  }
]
```

I use this JSON output on http://tatiyants.com/pev to visualize query plans. It's always annoying  for me to remove the double quotation mark.

BTW: Visualizing query plans in TablePlus would be wonderful.

**Comment by deepj** [comment]
@huyphams that's confusing and doesn't make sense to me to set it there. This is not CSV. So it's very weird to set this in CSV default options. And spaces aren't that what I would wish to be added to copied output.

I just want to copy the row without the quotes (or at least to have another option from the right-click menu or some shortcut). Just plain-text without any modifications.

**Comment by huyphams** [comment]
There is an other option.

Instead of copy Cmd + C you can Copy Cell, because of the default behavior is `copy as CSV` so there is no way to not include the quote (which is required by CSV),

<img width="318" alt="screen shot 2018-11-14 at 8 36 29 am" src="https://user-images.githubusercontent.com/3654622/48454059-66ec6f00-e7e8-11e8-8f72-762aa3948c5c.png">

**Comment by huyphams** [comment]
Copy cell does exactly what you want, I will close this issue because we will not change the default behavior (many users are using it daily).
Feel free to reopen this issue if you still have the problem with Copy Cell. I will look into another solution.

**Comment by deepj** [comment]
@huyphams Yes, thanks for the workaround. But the issue with this is, that won't work for regular `EXPLAIN` query (without changing it to JSON format).

What I get:

```
"Sort  (cost=1515.71..1553.96 rows=15303 width=177) (actual time=264.571..266.666 rows=15303 loops=1)"
"  Sort Key: name"
"  Sort Method: quicksort  Memory: 4089kB"
"  ->  Seq Scan on cinemas  (cost=0.00..452.03 rows=15303 width=177) (actual time=0.009..3.695 rows=15303 loops=1)"
"Planning time: 0.058 ms"
"Execution time: 267.536 ms"
```

What I would like to achieve:

```
Sort  (cost=1515.71..1553.96 rows=15303 width=177) (actual time=264.571..266.666 rows=15303 loops=1)
  Sort Key: name
  Sort Method: quicksort  Memory: 4089kB
  ->  Seq Scan on cinemas  (cost=0.00..452.03 rows=15303 width=177) (actual time=0.009..3.695 rows=15303 loops=1)
Planning time: 0.058 ms
Execution time: 267.536 ms
```

In this case, I can't use Copy Cell. There are plenty requires which don't return "table" data, just text output. I think it would be useful to consider some kind of way, how just copy it as a plain text.

**Comment by huyphams** [comment]
Maybe I will and an option in Copy Row As > Plain Text. That's the easiest way.

**Comment by huyphams** [comment]
Hi @deepj please download this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It supports copy as Raw, it should work as expected.

**Comment by deepj** [comment]
@huyphams tried. Thank you for your work 👍

**Comment by deepj** [comment]
I may change `Raw` => `Plain text`. But the final decision is up to you.
