### ISSUE TITLE
Enhancement Request - Add "Rows Affected" 

### ISSUE THREAD

**Issue by ngurney** [TablePlus/TablePlus#798]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2014
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
150
3. The steps to reproduce this issue:
After running a query it would be great to see the number of rows affected in the console (or anywhere else it makes sense). Helps me to confirm what I have just done was correct. 
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It's already supported, but only in SQL Query screen. I'm not sure what you want but please see the image below.
<img width="1260" alt="update" src="https://user-images.githubusercontent.com/3654622/48456236-db2b1080-e7f0-11e8-8c98-e4d954a24072.png">

**Comment by ngurney** [comment]
Yeah, I just jumped in here to remove this issue. I was trying a specific query and it wasn't showing, but now I am not sure why...Feel free to close this out and I'll reach out again if I come across it again.

**Comment by huyphams** [comment]
So I will close this issue if you're still encountering this issue, feel free to reopen it.
