### ISSUE TITLE
*BUG*: Unable to delete rows in Cassandra

### ISSUE THREAD

**Issue by nixgadget** [TablePlus/TablePlus#799]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3.11.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 155

3. The steps to reproduce this issue:
Cant delete rows.
Getting the following error,
```
line 1:106 mismatched input 'AND' expecting ')' (... WHERE ("createdtime" = '2018-11-14 07:01:38 +0000' [AND]...)
All changes were reverted.
```
A typical DELETE command looks like `DELETE FROM "local_onboarding"."user_onboarding_state" WHERE ("createdtime" = '2018-11-14 07:01:38 +0000' AND "state" = 'VERIFY_EMAIL' AND "userid" = 'TESTb3fb5aac-7504-45df-8681-b39764c304a3');` which doesnt seem right.

**Comment by nixgadget** [comment]
@huyphams Also how does TablePlus handle `timestamp` columns ?

`cqlsh` shows the timestamp as `2018-11-14 07:01:38.586000+0000` but TablePlus seems to truncate this and uses that in the deletion.

**Comment by huyphams** [comment]
I have fixed bug compound primary keys @nixgadget 
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Regarding the truncating, I'm using the standard timestamp in macOS but look like it was truncated. I will check it.
