### ISSUE TITLE
Camel case column names

### ISSUE THREAD

**Issue by krzysztof-miemiec** [TablePlus/TablePlus#8]
When I try to sort by clicking on column header, I get an error because of missing quotes in generated query. Here's the error screenshot:
![error](https://user-images.githubusercontent.com/396693/27983961-474275a8-63ca-11e7-8544-b2fbcce87183.png)

**Comment by huyphams** [comment]
It would be better if you can give me more info:
- TablePlus Build Number:
- Database Driver (MySQL or PostgreSQL):
I can fix it in the next release

**Comment by huyphams** [comment]
I got the bug. Thank you.

**Comment by krzysztof-miemiec** [comment]
* Version 1.0 (49)
* PostgreSQL

**Comment by huyphams** [comment]
Fixed @krzysztof-miemiec 
Please go to:
TablePlus > Check for update... 
to upgrade to build 50. That bug should be fixed.
