### ISSUE TITLE
ASCII Control Characters unusable in SQL Queries

### ISSUE THREAD

**Issue by davidarmstronglewis** [TablePlus/TablePlus#801]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 156

3. The steps to reproduce this issue:
Try copying the ASCII Unit Separator control character from Vi (or similar) into the SQL Query editor. Note that a newline character is inserted instead. This breaks attempts to run queries such as:

```sql
COPY table
FROM 's3://mybucket/csv/'
IAM_ROLE '...'
DELIMITER '^_';  -- note that this isn't actually the control character, Github doesn't support it either :(
```

This isn't part of my usual workflow, so I'm not sure what is standard - but I figured being able to use an ASCII standard control character as a delimiter in a sql query would be a "normal" thing to do. Correct me if I'm being silly :)

**Comment by huyphams** [comment]
I'm not sure how to reproduce/fix the issue also it's a weird delimiter to me "^_" so maybe we could close this issue for now.

**Comment by davidarmstronglewis** [comment]
Hey, no worries. What you'd want to do is poke around at the standard ascii table (`man ascii` in your terminal usually has some fast results) and look for the Record Separator character (`rs`, #30 in the decimal set or U+001E in its unicode representation). Characters like these don't have a visual representation as they are used to describe control-flow at the character level.

In my case I was using it as a separator for rows in a CSV-like document (RSSV?) as input in these rows consisted of user-input, so in my case it made sense to use characters that a user wouldn't input. It's not something you'd probably do unless you get frustrated with not being able to use tabs, commas or the `|` character as field separators in your "csv" 😄 

Terminal programs like Vim usually represent such characters as something like `^_` as a stand-in, which is why I used it above.
