### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by lipengyu** [TablePlus/TablePlus#803]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by lipengyu** [comment]
Chinese support

**Comment by huyphams** [comment]
Hi, please answer the questions in the issue template above, TablePlus supports many drivers, whout the information, I can’t help.

**Comment by huyphams** [comment]
If you're using the Windows build, the text editor will support Chinese next build.
