### ISSUE TITLE
Color of tabs on Dark Mode

### ISSUE THREAD

**Issue by enkota** [TablePlus/TablePlus#805]
Hey, this is a small issue but when more than one tab is open I find it confusing to understand which tab is open. I feel that the active tab should be the lighter black than the dark. 

If you compare to how dark mode looks on Safari, you can see the active tab is lighter and the inactive is darker. Even an option to switch this would be perfect!

Thanks,
Scott

**Comment by joshbrw** [comment]
Glad I'm not the only person who thinks this. :)

**Comment by huyphams** [comment]
Hi @joshbrw and @enkota I've improved it on this build: https://www.dropbox.com/s/4033rlop6eov1ur/TablePlus.dmg?dl=0

**Comment by joshbrw** [comment]
@huyphams Amazing, thank you so much for being so responsive!

**Comment by enkota** [comment]
@huyphams excellent! thanks you
