### ISSUE TITLE
Unable to import CSV into table on Windows 10

### ISSUE THREAD

**Issue by alexluong1** [TablePlus/TablePlus#806]
I am unable to import CSV's into my table. I clicked around but couldn't find it. Is this feature available on Windows, and if so how can I access it?

![tableplusissue](https://user-images.githubusercontent.com/41758508/48740608-f93bab00-ec0c-11e8-9015-8f2d021da4be.png)

I am using PostgreSQL 11.1 with TablePlus Build 1914 (or Version 1.0 (28))

My OS is Windows 10 Home 64-bit.

**Comment by huyphams** [comment]
Hi @alexluong1 it was supported, please submit the issue in the Windows tracking issues next time:
https://github.com/tableplus/tableplus-windows/issues

**Comment by alexluong1** [comment]
Thanks

**Comment by alexluong1** [comment]
Thanks, I did not know about that. How do I import the csv? I've clicked around and can't find the function.

**Comment by huyphams** [comment]
Sorry because of the typo. It hasn't been supported, yet. We will add it in the future release.
