### ISSUE TITLE
[Feature Request] Closing server connections on middle mouse click

### ISSUE THREAD

**Issue by heathyboyj** [TablePlus/TablePlus#807]
[MacOS]

As was added with https://github.com/TablePlus/TablePlus/issues/25 for tabs, it'd be good to be able to close connections from the lefthand sidebar with a middle mouse click as well.

Thanks,

**Comment by huyphams** [comment]
Hi @heathyboyj thanks for the suggestion. I can add a close connection feature but using a middle mouse might not a good idea. Some users will not aware of it.
1. I will add disconnect option in the menu.
2. In this popup.
<img width="738" alt="screen shot 2018-11-20 at 10 30 50 pm" src="https://user-images.githubusercontent.com/3654622/48783845-f37cbd00-ed13-11e8-9cff-0d8cffb46f6d.png">

**Comment by heathyboyj** [comment]
Could there be a Close Connection option in the File menu too, beneath New Connection & Edit Connection? That way I can just bind a keyboard shortcut/mouse shortcut to it if needs be!

![image](https://user-images.githubusercontent.com/20686879/48783954-7e8c9180-ecd9-11e8-9eba-3a1b11d48330.png)

**Comment by huyphams** [comment]
Sure, I will do option 1, 2 above, and the option 1 is the one you mentioned.

**Comment by huyphams** [comment]
Hey @heathyboyj 
I just added disconnect function. shotcut key: cmd + option + .
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
