### ISSUE TITLE
[Feature Request] Preferences option for new SQL query tabs to be blank by default

### ISSUE THREAD

**Issue by heathyboyj** [TablePlus/TablePlus#808]
It's cool (presuming that it's intended and not a bug, of course!) that opening a new SQL query tab starts with recently run queries, but more often than not I'm looking for a blank canvas. Since we can get the history from the lefthand sidebar if we need it, it'd be a nice quality of life change to be able to default to blank tabs!

Thanks,
James

**Comment by huyphams** [comment]
Great I idea, I like it 👍 Thanks.

**Comment by huyphams** [comment]
It's implemented.
