### ISSUE TITLE
Feature Request: Add keyboard short to toggle between connections

### ISSUE THREAD

**Issue by mattcdavis1** [TablePlus/TablePlus#809]
Here is a screenshot of what i'm referring to: [Screenshot](https://www.dropbox.com/s/k3qh14bx7s5uiqs/2018-11-22_01-01-51.png?dl=0)

As far as i'm aware there is no way to toggle between the items referenced by the arrows in the screenshot using a keyboard shortcut.  This would be helpful for quick comparisons of tables on different connections.

**Comment by huyphams** [comment]
Hi @mattcdavis1 TablePlus is using mac standard key binding, you can switch between windows by:
- Next: Control + Tab.
- Previous: Control + Shift + Tab.
TablePlus also supports switch database using `Open Anything`: Command + P.

**Comment by mattcdavis1** [comment]
got it - thanks!  Maybe you could add this to the navigate menu to highlight this navigation option / keyboard shortcut?
