### ISSUE TITLE
[ISSUE] Connection lost 

### ISSUE THREAD

**Issue by ovaqlab** [TablePlus/TablePlus#810]
1. Mysql Version 8.0

2. build number 156
3. The steps to reproduce this issue:
    The issue occurred when right click on the tables in the left sidebar. 
   and the issue started after update to the build number 156. 
![screenshot 2018-11-23 at 1 48 51 pm](https://user-images.githubusercontent.com/33068920/48933631-061b1000-ef27-11e8-92f5-359d3989ba5a.png)

**Comment by huyphams** [comment]
Thanks @ovaqlab but it happens every time or just one time, can you reproduce it?

**Comment by huyphams** [comment]
I think this issue is resolved in recent builds, please let us know if you're still seeing it.
