### ISSUE TITLE
Open a second tab on same table

### ISSUE THREAD

**Issue by ntw6tori** [TablePlus/TablePlus#811]
It would be very useful to open several tabs on each table.
Sometimes you need to discover different data sets on the same table and you want to easily switch between these two views. Right now you can only do this by opening different workspaces.

**Comment by michaelhogg** [comment]
@ntw6tori: I agree. If I already have a table open in a tab, I'd hoped that right-clicking on the table in the left sidebar and choosing _"Open in new tab"_ from the popup menu would open a second tab for the same table.

**Comment by alvint** [comment]
As a workaround, you can open a new window with CMD-N and view the same table from there. While it's not quite as convenient as having multiple tabs, I imagine there's also less potential for confusion.

**Comment by huyphams** [comment]
Hi, I'm working on it, it will be included in the next update.
<img width="1333" alt="update" src="https://user-images.githubusercontent.com/3654622/51360954-57e3af00-1b00-11e9-8250-3000c195f187.png">
