### ISSUE TITLE
Sequelize generated foreign key constraints are not picked up from the database

### ISSUE THREAD

**Issue by dekdekbaloo** [TablePlus/TablePlus#812]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**MySQL 5.7**
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**build 156**
3. The steps to reproduce this issue:
  **1. Create a table using Sequelize migration with referencing column (foreign key):**
  **2. Also define association in the model file**
  **3. Notice that the foreign key contraints show up when using an SQL query**
    In this case, find all constraints related to `Industries` table.
```SQL
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_NAME = 'Industries';
```

    Result showed up having `ShopIndustries_ibfk_2` found.

<img width="956" alt="screen shot 2561-11-24 at 12 22 43" src="https://user-images.githubusercontent.com/8069477/48964871-b4848b00-efe3-11e8-873b-40913eba31a4.png">

  **4. Notice that in the `structure` view, no foreign key constraints are picked up**

![image](https://user-images.githubusercontent.com/8069477/48964889-2a88f200-efe4-11e8-9791-a67856d07533.png)

Note: Not sure if this is `sequelize` related problem because when I tried adding constraints with a defined name through `sequelize` then it showed up correctly in TablePlus.

**Comment by huyphams** [comment]
Hi @dekdekbaloo thanks for the report, it would be great if you can give me the table creation statement of these tables, so I can reproduce and fix it quickly.

**Comment by dekdekbaloo** [comment]
@huyphams Thanks for fast reply. I'm a fan of TablePlus. I really appreciate your work.

Anyway, all the models are generated through sequelize but I can also reproduce this with pure SQL.

Steps:
1. Create tables
```sql
CREATE TABLE Shops (
  id int,
  name varchar(255),
  PRIMARY KEY (id)
);
```

```sql
CREATE TABLE Industries (
  id int,
  name varchar(255),
  PRIMARY KEY (id)
);
```

2. Create n:m relation tables
```SQL
CREATE TABLE ShopIndustries (
  shopId int,
  industryId int,
  PRIMARY KEY (shopId, industryId)
);
```

3. Add foreign key constraints
```SQL
ALTER TABLE ShopIndustries
ADD FOREIGN KEY (shopId) REFERENCES Shops(id);
```

```SQL
ALTER TABLE ShopIndustries
ADD FOREIGN KEY (industryId) REFERENCES Industries(id);

**Comment by huyphams** [comment]
Hmm, looks like it work for me, I think it related to MySQL case sensitive mode, let me investivate more.
<img width="1458" alt="screen shot 2018-11-24 at 1 12 28 pm" src="https://user-images.githubusercontent.com/3654622/48965156-a4bc7500-efea-11e8-9036-d08173e9ef61.png">

**Comment by dekdekbaloo** [comment]
@huyphams 
![image](https://user-images.githubusercontent.com/8069477/48965309-24e3da00-efed-11e8-9c9d-cd04abde05ac.png)

**Comment by dekdekbaloo** [comment]
Oh pardon my mistake, Using SQL alone works, must be something with Sequelize. @huyphams Would you be able to reproduce it sequelize way? I can share with you example steps.
