### ISSUE TITLE
cmd F on Mac doesn't bring up Find

### ISSUE THREAD

**Issue by ayalbelling** [TablePlus/TablePlus#813]
TablePlus 1.0 (156) on Mac OS 10.13.3, SQL Server. In SQL Query using cmd F doesn't always bring up the find dialogue so have to go to Edit Find instead.

**Comment by hanoii** [comment]
This is also still happening for me on latest 2.7 (246). It works the first time, and then doesn't work any more until you close the tab and start over.

**Comment by huyphams** [comment]
I've fixed this issue, it happened after the result is returned.
