### ISSUE TITLE
Site: Plugins, Developer and Job links are broken - misleading feature list

### ISSUE THREAD

**Issue by cjke** [TablePlus/TablePlus#814]
On the public site, the plugins, developer and job links are broken. This isn't a huge issue, but the plugin/developer section is a little misleading, especially the feature section: 

"You can vastly extend TablePlus to fit your needs by installing plugins written by others or writing your own in JavaScript." but with broken links/missing documentation on _how_ to do this, it can't really be listed as a feature can it?

Kind of the same as this line: "You can choose the appearance & config the shortcuts that best match your personal taste." But according to this open issue https://github.com/TablePlus/TablePlus/issues/327 you can't currently edit shortcuts, so saying "config the shortcuts" might be seen as not entirely correct. 

I love the app btw and have just recently purchased it (and even without the above, I would still purchase it for that price). I'm just a tad concerned that the landing page and its listed features are not quite what is available and may cause some people to be disgruntled. 
Again awesome app (I'm migrating from SequelPro) and loving it so far

**Comment by huyphams** [comment]
Hi @cjke sorry for the misleading. Currently, TablePlus supports a few plugins (Cmd + L) but the document isn't ready for the third party, it also supports change some short key, and not all the shortcut keys are configurable.
We will update the sites to make it clearer.

**Comment by cjke** [comment]
Hey @huyphams no worries at all. I'm fine with it, I can just imagine some people kicking up a fuss. It's a great app and happy to have purchased it. 
Did you want me to close this issue? Or leave it open until the site is fixed up?

**Comment by huyphams** [comment]
Thanks, @cjke let me close it after the fixes are deployed.

**Comment by cjke** [comment]
Easy, will leave as is - cheers mate
