### ISSUE TITLE
view error messages from queries

### ISSUE THREAD

**Issue by Sijoma** [TablePlus/TablePlus#817]
PostgreSQL 11
build 156

I cannot see any error messages when querying the database. I already have seen a similar issue which was resolved (#29).

TabePlus output:
![image](https://user-images.githubusercontent.com/8970764/49007729-75357600-f16c-11e8-90a6-be5b6de15323.png)

PgAdmin 4 output:
![image](https://user-images.githubusercontent.com/8970764/49007768-8c746380-f16c-11e8-8112-5631cae5ccaf.png)

**Comment by huyphams** [comment]
I got the bug, TablePlus only shows the message when there is no returned row.
The possible solution is adding a button that can toggle between rows and messages.

**Comment by huyphams** [comment]
Hi @Sijoma please try this build and let me know the result, thanks for the feedback.
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="1320" alt="nnice" src="https://user-images.githubusercontent.com/3654622/49010360-923a6b00-f1a5-11e8-9039-8bfb11b2b50f.png">

**Comment by Sijoma** [comment]
Yes, it works! Great. That was quick.
