### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by jonlorusso** [TablePlus/TablePlus#820]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 1.0 (156)

3. The steps to reproduce this issue:

Try to login:

![image](https://user-images.githubusercontent.com/458108/49092426-ff92de00-f22f-11e8-953c-98b46a2054c2.png)

Note: This username/password pair works fine via psql.  

Perhaps TablePlus is not handling certain special characters in my password?

**Comment by huyphams** [comment]
Thanks @jonlorusso but, clearly I can't reproduce the bug with the information, can you give me an example of the special character that you're using in the password?

**Comment by jonlorusso** [comment]
It could be any of:  ,?&=#

Note:  I am able to login to the same database with a different user (and different password obv.) using TablePlus.

**Comment by huyphams** [comment]
It shouldn't be a problem (I have tested it), Can you double check the root password again, by copy pass it to a text editor to make sure there wasn't a copy-paste mistake.

**Comment by jonlorusso** [comment]
Closing issue. I'm no longer able to replicate.
