### ISSUE TITLE
Cannot duplicate rows with empty value and column not nullable

### ISSUE THREAD

**Issue by drpiou** [TablePlus/TablePlus#822]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.23

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
TablePlus 1.0 (161)

3. The steps to reproduce this issue:
- create table with varchar column not nullable
- add row with empty string
- duplicate row

![screenshot 2018-11-29 at 10 18 55](https://user-images.githubusercontent.com/474368/49211592-3992ea00-f3c0-11e8-87a0-a7f7c97b3841.png)

![screenshot 2018-11-29 at 10 12 34](https://user-images.githubusercontent.com/474368/49211325-9cd04c80-f3bf-11e8-8e3f-a83442df2ebd.png)

**Comment by huyphams** [comment]
Thanks @drpiou it was fixed on this build: https://www.dropbox.com/s/4033rlop6eov1ur/TablePlus.dmg?dl=0
