### ISSUE TITLE
Authentication via SSL Broken for MySQL 5.x

### ISSUE THREAD

**Issue by mpash** [TablePlus/TablePlus#824]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
160

3. The steps to reproduce this issue:
Login to any MySQL 5.x server using PAM authentication plugin via SSL.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @mpash please use MySQL 8.x to connect to MySQL, MySQL 5.x was added for people who want to connect to the old MySQL (MySQL < 5.1).

**Comment by huyphams** [comment]
Btw, which MySQL version are you using on the server?

**Comment by mpash** [comment]
@huyphams I'm working with Nick J. to get this resolved. I'll close the issue here.
