### ISSUE TITLE
Console log shows queries that do not actually run

### ISSUE THREAD

**Issue by natesilva** [TablePlus/TablePlus#827]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL (Amazon Aurora) 5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): build 161

3. The steps to reproduce this issue:

* Open the Console log (Shift-Cmd-C)
* Open a very large table from the list of tables on the left

In the log it shows something like:

```sql
-- 2018-11-29 22:07:30.4600
SELECT * FROM `db_name`.`table_name` ORDER BY `id` LIMIT 300 OFFSET 0;

-- 2018-11-29 22:07:30.5340
SELECT COUNT(*) as count FROM `db_name`.`table_name`;
```

…but, thankfully, it doesn’t actually run the `SELECT COUNT(*)`.

I opened the log, accessed a table that has over 2 billion rows, and noticed this `COUNT(*)` query and had a bit of a scare. 😅 When I checked the server, fortunately, it wasn’t actually running the query.

Pretty sure it doesn’t run the query unless you are under the “Estimate count” limit that can be set in preferences.

If it doesn’t run the query it shouldn’t show it.

**Comment by huyphams** [comment]
Thanks @natesilva for pointing it out, TablePlus detects that the table has a large number of rows so it runs the estimate instead of count(*)

**Comment by natesilva** [comment]
I don’t know when it was fixed but I can confirm that the console now shows a lightweight query like
```sql
SELECT table_rows as count FROM information_schema.TABLES WHERE TABLE_SCHEMA='db_name'AND TABLE_NAME='table_name';
```
Thanks!
