### ISSUE TITLE
List of connections just dissapeared

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#83]
Build 65
![Screenshot](https://i.imgur.com/mdlx9Od.png)
Only group still exists where were all connection elements.

**Comment by huyphams** [comment]
Hmm, you lost all connections?

**Comment by PVGrad** [comment]
Yes

**Comment by huyphams** [comment]
Hmm weird, TablePlus stores connections in user default. it is disappeared, that mean user default has been reset.

**Comment by PVGrad** [comment]
Do you know when and how can it be (user default reset)?

**Comment by huyphams** [comment]
it happened to me one before, but very long time ago.
Thank for your feedback, I will take a look at the code handle connections.
btw could you give more info (step by step) that how you lost all the connection?

**Comment by PVGrad** [comment]
Actually I can't say for sure about steps - I just opened the TablePlus app and saw no connections.
Maybe I can send some dumo or logs for investigations?

**Comment by huyphams** [comment]
I did not track users or record application log because I respect user privacy. No problem, I will try to reproduce this bug. Keep follow this issue.

**Comment by PVGrad** [comment]
It just happened again on build 66 👎 
Just after I closed TablePlus via cmd+q and opened it again after some time.
macOS version - latest 10.13
Here you can see what TablePlus files AppClearen found on my notebook:
![App files](https://i.imgur.com/rI28hED.png)

**Comment by huyphams** [comment]
I didn't upgrade to OS X 10.13, did you clean TablePlus plist?

**Comment by PVGrad** [comment]
No - I don't have software to clean something **automatically** and i didn't clean it manually - in screenshot I just showed all TablePlus-related files and folders that AppCleaner found, because I thought it can help somehow n investigation.

**Comment by huyphams** [comment]
Thank you, I'm trying to reproduce this bug, I will keep you posted. 👍

**Comment by karimelm** [comment]
Same thing just happened with my install. Have not modified any files manually nor do i have anything that could or would do it automatically.

**Comment by huyphams** [comment]
Hi guys, I just updated the candidate build, including an attempt to fix this issue. Please give a try with this: https://github.com/TablePlus/TablePlus/issues/94

**Comment by PVGrad** [comment]
@huyphams beta release didn't help - missed all connections again - it's more and more annoying bug for me!

**Comment by huyphams** [comment]
Thank you, I will try an other way to fix this bug

**Comment by huyphams** [comment]
I have refactored code and there are only two simple functions handle save/load connections. If it still happen (probably some application change the plist file or bug of OSX 10.13). I will update to High Sierra next week to debug this bug.

**Comment by karimelm** [comment]
Up until now, the new release has resolved this issue for me.

**Comment by huyphams** [comment]
Hi @PVGrad 
Just upgrade to OS X 10.13 and confirmed this bug. Now I can reproduce the bug lost all connections.

**Comment by huyphams** [comment]
Hi @PVGrad @karimelm 
Could you please download and test this build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
==============
This build include:
1. Search part of word (Fuzzy matching + recently matching): SQL Query, Open Anything.
2. Fix lost all connections bug.
3. Performance improvement.

**Comment by karimelm** [comment]
I dont seem to have this bug anymore in build 67, but what I also did was save the connection in its own group, perhaps that has something to do with it. Will download the new build and test regardless.

**Comment by huyphams** [comment]
Hi guys,
After waste many hours debug on this issue. I found some interesting things (on OS X 10.13):
After save data to NSUserDefault and try to load it, NSUserDefault returns value nil `until restart application`. If we ignore and save data to NSUserDefault again => lost all connection except the new one.
I decided not to use NSUserDefault from now, in TablePlus, please keep waiting the update 68 and this bug will be resolved.
Thanks,
Huy.

**Comment by karimelm** [comment]
Have not yet experienced loss of connection since my last comment. Still resolved for me!

**Comment by everdaniel** [comment]
Hi there,

just had this issue happened to me, I just opened TablePlus and all of my groups and connections are lost, I'm running Build 296 with Locations set to Dropbox folders:
![Screenshot 2020-02-16 22 27 44](https://user-images.githubusercontent.com/218794/74617387-984e9b80-510b-11ea-992b-4a3e3e1ceb96.png)
![Screenshot 2020-02-16 22 27 48](https://user-images.githubusercontent.com/218794/74617392-9b498c00-510b-11ea-9575-c09ce77d6689.png)

both `ConnectionGroups.plist` and `Connections.plist` show up empty:
![Screenshot 2020-02-16 22 28 46](https://user-images.githubusercontent.com/218794/74617418-b74d2d80-510b-11ea-900e-acf062935021.png)
![Screenshot 2020-02-16 22 28 51](https://user-images.githubusercontent.com/218794/74617421-b9af8780-510b-11ea-9129-1074217a6ecf.png)

Is there any way to fix this issue? I just migrated everything from Sequel Pro.

Thanks in advance.

**Comment by huyphams** [comment]
Hi,
TablePlus does not move the connections automatically, so you have to export and then import it after changing location. If you want to see the old connections, just click restore defaults

**Comment by ggolda** [comment]
Happened to me on Windows today after BSOD 😄 Looks like file got corrupted and I lost all my connections, but groups are still visible btw.

**Comment by rufhausen** [comment]
This just happened to me twice in a week. I had to rely on Time Machine backups to restore the connections list. The connection group are unaffected. Screenshot is after after restored. Prior to that Connections.plist was gone in place of this new Connections(1) file. Looking at that file, I think it might just be the plist file renamed for some reason.
<img width="508" alt="Screen Shot 2022-01-25 at 11 48 57 AM" src="https://user-images.githubusercontent.com/43862/151039884-0e01c021-f930-49fa-a2ae-7032a4b1f6e2.png">

**Comment by progcode** [comment]
today all my connections were lost without any reason. it was still good in the morning then everything was gone.

Apple M1, MacOS 11.6.1

**Comment by huyphams** [comment]
Are you using any cleanup app? @progcode

**Comment by tomerikpaulsen** [comment]
Great, just lost over 60 connections ..

**Comment by leochoo** [comment]
This happened to me just now.... why...? how...?

**Comment by pranjaldaffodil** [comment]
This happened to me today too, last evening my system lost power suddenly/abruptly and today when I booted it up, tableplus doesn't have any connections (groups and individual connections, lost all of em).

OS: Ubuntu 22.04.5 LTS
Device: Lenovo ThinkPad L14 Gen2

TablePlus build: 0.1.302

**Comment by utviklerno** [comment]
Happened to me 3 years ago. Stopped using it.

Kind regards
-------------
Utvikler.no
Tom-Erik Paulsen
Mobile: 93 21 73 56

Sent from [Proton Mail](https://proton.me/mail/home) for iOS.

-------- Original Message --------

**Comment by pranjaldaffodil** [comment]
I too am switching to DBeaver CE
