### ISSUE TITLE
Mysql: Invalid uuid() handling with replace() function

### ISSUE THREAD

**Issue by ntw6tori** [TablePlus/TablePlus#830]
When i do the following select on a table containing multiple columns
**select uuid(),replace(uuid(),'-','') from anytable;**
i would expect to get a list with two columns containing individual ids where the only difference is that the first column contains dashes and the second column does not.
But TablePlus results always the same ID in the second column.
It does not matter wether the replace() function does any replacement at all or not.

Since mysql command line does the expected behaviour i assume that this is a bug in TablePlus.

**Comment by ntw6tori** [comment]
<img width="1629" alt="bildschirmfoto 2018-12-04 um 06 23 51" src="https://user-images.githubusercontent.com/44088773/49420955-197f7400-f78e-11e8-830d-2d3dbb08ad67.png">

**Comment by huyphams** [comment]
Hi @ntw6tori I don't see any difference between of the two screenshots.
TablePlus is using officially native MySQL lib C/C++

**Comment by ntw6tori** [comment]
I have marked the differences in the next screenshot.
In this example i replaced 'X' by 'Y' which does not occur in an uuid() to show that it does not make any difference wether the string is replaced or not.
Marked in green, a couple of different uuids so as you have in your screenshot
Marked in red they don't alternate anymore.

<img width="916" alt="bildschirmfoto 2018-12-04 um 06 23 51 kopie" src="https://user-images.githubusercontent.com/44088773/49421424-1f765480-f790-11e8-9ce5-79323cbe0497.png">

**Comment by huyphams** [comment]
I got it, but your statement has data racing, which means if TablePlus executes faster (or lower) than the console, it can generate a different result. The uuid() generates a random string in a delta time, if the fetching process lower than that delta, the uuid() will generate difference rows each time.

**Comment by ntw6tori** [comment]
What?!?!
Sorry, i did non understand that. I just want to make it work like it should and like it did before i switched to TablePlus.
The main reason why i need this problem to be solved is that i want to insert rows in a table using a select. And that insert generates an sql error because it can not insert the same primary twice. 

I have to switch to MySQL workbench or the command line to execute these kind of insert statements.

**Comment by huyphams** [comment]
I mean that your query has a problem itself.  Read more about data racing: https://blog.regehr.org/archives/490

In short: the uuid() will generate different ID each time it called if the delay > delta. The reason console and workbench work for you because the time executes too fast (< delta).
 
You can use this query instead of the old query, it 100% work: 

```
select @unique_id := uuid() as `unique_id`, replace(@unique_id,'-','') as `formatted_unique_id` from <your_table_name>;
```
