### ISSUE TITLE
Can’t change default value for a DATETIME or TIMESTAMP column (MySQL)

### ISSUE THREAD

**Issue by natesilva** [TablePlus/TablePlus#831]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.6 (Amazon Aurora)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 161

**Steps to reproduce:**

1. Create a table: `CREATE TABLE t1 (d DATETIME NOT NULL)`
2. In TablePlus Structure view, try to set the default value for that column to `NOW()`.

Expected results:

* Should change the default value

Actual results:

* “You have an error in your SQL syntax”

This happens because TablePlus tries to run the following query:

```sql
-- doesn’t work
ALTER TABLE `db_name`.`t1` ALTER `d` SET DEFAULT NOW();`
```

MySQL doesn’t like it for some reason. This works:

```sql
-- works
ALTER TABLE `db_name`.`t1` MODIFY `d` DATETIME NOT NULL DEFAULT NOW();
```

*Warning:* when using `ALTER TABLE…MODIFY` you must specify the entire column definition, you can’t just specify the default value.

**Comment by huyphams** [comment]
Thanks, @natesilva for posting it out. It works with the INT columns but doesn't work with DATETIME, and I don't why. I will try to fix it tomorrow because it's very late now. Good night ;-D

**Comment by natesilva** [comment]
When you get a chance to look at this, here’s a related issue -- if you want I can move it into a separate issue:

* If the column definition has fractional seconds (`DATETIME(6)`) the default needs to have the same number of fractional seconds (`NOW(6)`).

**Comment by huyphams** [comment]
I have fixed it on the next update @natesilva thanks for the feedback.

**Comment by natesilva** [comment]
Thank you, and happy new year.
