### ISSUE TITLE
Request: Better Support for Maintaining SQL Files

### ISSUE THREAD

**Issue by andyoneal** [TablePlus/TablePlus#833]
My workflow is mostly editing large sql files that do batch analytics jobs on a nightly basis. That means I am frequently opening these saved queries, making small changes, saving, then pushing those updates to the box that runs them. TablePlus seems to treat sql queries as transient with its treatment of sql files as more of an import/export flow. It feels like the expectation is that the SQL Query tab is just for "scratch-work" or one-off queries.

Changes to TablePlus that would make this easier:

- When opening a file, change the label on the tag from "SQL Query" to the filename
- Support saving the edited file, rather than forcing the Save As flow which can be error prone if the wrong file is selected. This becomes a bigger issue when multiple files are opened at once.
- A confirmation dialog if you attempt to close a tab with unsaved changes, even if the tab began as a blank SQL Query and not a file. Too easy to accidentally lose work.

Essentially I'm asking for behavior closer to Sublime Text with query tabs representing files. As a data analyst (rather than a DBA or a developer), developing and running large queries is 90% of my usage. I prefer TablePlus over any other client (especially for Postgres and Snowflake) but I'm having a difficult time making it work for my use case.

**Comment by troycurtisjr** [comment]
I second this.  It is currently my main hesitation in upgrading to Pro and moving my full workflow over to using TablePlus.  If this is going to be in the roadmap for future releases, I think I can live with the "Save As" method in the meantime. :smile:

**Comment by javierecf** [comment]
I was just about to make the same request as this, this is a deal breaker that keeps me using SQL Management on a VBOX, I work mostly with large SQL files that have StoreProcedures code (SQL Server), and every version of the SQL files are on a Git Repo so having the hability to just open it, run it and save it (to the same source path) is 90% of all I do with SQL Management.

TablePlus has incredible structure and potential, it can easily replace hundred of sql management solutions with this kind of support.

**Comment by huyphams** [comment]
I decided to redesign this feature, TablePlus will have a better favorite editor.

**Comment by huyphams** [comment]
Hi guys please check out this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
TablePlus now saves favorite automatically.

**Comment by javierecf** [comment]
I just checked the build, maybe is because I haven't use the favorites options yet, but i still find it troublesome to organize and keep track of files there, personally I have all my SQL files inside a folder and just been able to open it directly into the editor and run it into the current connection would be sufficient for my workflow. I'm guessing this kind of request clashes with the fact that the free versions allows up to 2 query tabs at the same time, and I will be happy to upgrade if something like that would be included though.

Also maybe this is not the place to ask because of the closed source nature of the app but I will be glad (and I'm guessing others too) to help in development if needed.

**Comment by huyphams** [comment]
I have a plan which allows the user to add custom folder/git repo to the favorite. Basically, it works like macOS Finder on the left.

**Comment by javierecf** [comment]
> I have a plan which allows the user to add custom folder/git repo to the favorite. Basically, it works like macOS Finder on the left.
That will most likely be sufficient for my kind of workflow, will be glad to try it though, It will be nice to hear from @andyoneal and @troycurtisjr and see if they think the same.

IMO having the files list from a folder and be able to open it directly from favorites would be very comfortable to maintain SQL files on the daily basis.

**Comment by huyphams** [comment]
You can try redownloading the build above (I updated the dropbox), it should allow you to add a custom folder, open/edit/run/save directly in SQL Editor.
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by javierecf** [comment]
Nice so far!, will be testing a lot during the day, will report if something comes up

Also I have a question, maybe i need to open a new issue for this? but lets say i do this query

begin TRANSACTION
print 'xx'
rollback TRANSACTION

none of these querys will ever respond with rows, but after running the whole query three tabs of query results appear, and just the first one shows the messages, the messages also don't have the number of rows affected (very important!), I did not find an option on settings to adapt this, maybe I'm missing something?, anyway maybe this is a topic for another issue.

**Comment by javierecf** [comment]
To clarify, It would be nice to have all the messages from the outputs in a single tab.

**Comment by huyphams** [comment]
Hi @javierecf that is the next big update, append all result in a single tab. so the user can choose their favorite mode.

**Comment by javierecf** [comment]
> Hi @javierecf that is the next big update, append all results in a single tab. so the user can choose their favorite mode: single tab or multiple tabs.

Nice!, would this update prevent the showing of query tabs with rows from results that don't need them and only show the messages?

**Comment by huyphams** [comment]
Hey @javierecf you can try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by javierecf** [comment]
Hi, it still shows query tabs as rows from only message statements and I cannot see the number of rows affected

![kapture 2019-03-02 at 9 19 51](https://user-images.githubusercontent.com/2164798/53684613-ba69c680-3ccc-11e9-99c7-c3ded37873aa.gif)

**Comment by huyphams** [comment]
There are a lot of configs here, the split result into tabs was added a year ago
<img width="344" alt="screen shot 2019-03-02 at 11 23 44 pm" src="https://user-images.githubusercontent.com/3654622/53684635-41a55180-3d42-11e9-87a9-afe4e3277fe0.png">

**Comment by javierecf** [comment]
If I uncheck the option "Split the result into Tabs (max 100)", the three results tabs from 1 query still shows up, is that normal?

![kapture 2019-03-02 at 9 27 49](https://user-images.githubusercontent.com/2164798/53684678-8d69e380-3ccd-11e9-8845-de01bf9b3deb.gif)

**Comment by huyphams** [comment]
Hmm, it looks like that you ran some function that returns more than one result, so TablePlus will render it into separated tabs.

**Comment by javierecf** [comment]
If print is changed to select
begin transaction
select 1
rollback transaction

still 3 tabs appear, so the problem might be the transactions begin ,commit and rollback statements, which I find odd since I'm pretty sure they don't return any kind of row result, maybe just messages, on SQL Management on windows transaction statements dont return any kind of row or message output

**Comment by huyphams** [comment]
Thanks @javierecf but it should be another issue. I will close this issue because it's resolved.
