### ISSUE TITLE
CSV Export causes strange behavior and requires Force Quit

### ISSUE THREAD

**Issue by MrSkinny** [TablePlus/TablePlus#834]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql  Ver 14.14 Distrib 5.7.22, for osx10.13 (x86_64) using  EditLine wrapper

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v1.0 160

3. The steps to reproduce this issue:
Select table from mysql database
Choose Export to CSV
Leave all settings at default
Upon clicking "Export", there are different behaviors:

1 - 
About 50% of time or after loading TablePlus without much usage
Works as expected

2 
25% of time after TablePlus has been open and used a while
"Open Connection" dialog appears. Clicking Close reopens dialog box several times. Eventually it stops appear and "Exporting..." dialog appears.  This hangs on 0/x rows and never finishes.  Force Quit required. Actual CSV file is created but unverified if it's corrupt (I usually just Force Quit and do the process when no errors occur)

3 - 
25% of time after TablePlus has been open and used a while
"Open Connection" dialog appears. Clicking Close reopens dialog box seemingly infinite times. Force Quit required.

**Comment by huyphams** [comment]
Thanks @MrSkinny let me check it.

**Comment by huyphams** [comment]
it's fixed in recent builds, Thanks!
