### ISSUE TITLE
Feature Request: persistent column reordering

### ISSUE THREAD

**Issue by brandondrew** [TablePlus/TablePlus#836]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 
161

It is nice that we can reorder columns in the Data view, but when we leave that table and return, the order we set is gone.  It would be very nice if we could persistently change the order of columns.

**Comment by huyphams** [comment]
It's supported now on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks
