### ISSUE TITLE
Keep crashing after hitting "save sql as" or "save"

### ISSUE THREAD

**Issue by hathaaaway** [TablePlus/TablePlus#838]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.12
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (160)
3. The steps to reproduce this issue:
Creating a database based on the csv, then inserting the data into the database. The crash occurs after trying to save the sql file.

Noted: If the bug is related to data, please attach an example SQL data.
[music.zip](https://github.com/TablePlus/TablePlus/files/2646455/music.zip)

**Comment by huyphams** [comment]
Hi @hathaaaway I can't reproduce the bug.
I created a table with that CSV (it has some duplicated columns). and export to SQL file, it works fine.
