### ISSUE TITLE
editing multiple fields in sidebar requires multiple clicks

### ISSUE THREAD

**Issue by marcroberts** [TablePlus/TablePlus#84]
If I've edited a field in the row detail sidebar and I click in another field to edit that, the first click takes focus away from the first field but doesn't focus the second field. A second click is required.

I sometimes don't click the second time and start trying to delete the text, and now the whole row is going to be deleted!

It would also be nice if we could tab to the next field in the sidebar.

**Comment by huyphams** [comment]
Hi @marcroberts sorry because of the delay, I will take a look at this issue and fix it in new release, thank for you feedback 😁

**Comment by huyphams** [comment]
Fixed, now I'm working on `move focus to the next field when tab key pressed`
