### ISSUE TITLE
Improve contrast of "active statement"

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#840]
In dark mode the active statement is quite washed out contrast wise. It's great to get visual information of what will be executed on cmd-enter, but when the statement is large (when authoring a stored procedure for example) the lowered contrast is a problem to me.

It would be great if the kind of visualisation of *active statement* could be selectable. I'd prefer some kind of gutter marking for active statement instead of having it almost look selected (as in copy/paste selected).

**Comment by alvint** [comment]
Dup of issue #690 and some other issue I'm not finding at the moment, I think...

**Comment by msageryd** [comment]
Thanks.
I'll close this and add my thoughts to #690 instead.
