### ISSUE TITLE
Feature Request: Quick connect

### ISSUE THREAD

**Issue by sixlive** [TablePlus/TablePlus#841]
Would love to see a "quick connect" feature. Sometimes I want to connect to a one-off data store and don't necessarily want to save the connection. Didn't see it suggested already and don't seem to see it in the UI anywhere.

**Comment by huyphams** [comment]
It's here @sixlive
<img width="612" alt="gonnect" src="https://user-images.githubusercontent.com/3654622/49655813-44a7e300-fa6e-11e8-9a28-b9d9acfe828d.png">

**Comment by sixlive** [comment]
I'm interested in something similar to Sequel Pro's "Quick Connect" where I can just put in connection information and connect to the data store without having to actually save the connection information to Table Plus.

**Comment by huyphams** [comment]
Please see the attachment above @sixlive there is an option Prompt the input form. it should work as your expectation.

**Comment by sixlive** [comment]
It looks like that still requires a reference to a saved connection. I guess I was looking for purely transient data.

**Comment by sixlive** [comment]
I guess I can set up a dummy connection and just not save the data after I'm done.

**Comment by huyphams** [comment]
Hmm, you can click the connect directly without saving it. Btw, TablePlus also supports open by URL, just create a link and double on that link or open by terminal.
open postgresql://<something>

**Comment by sixlive** [comment]
The prompt for input is unavailable unless you select an existing saved connection.

<img width="253" alt="screen shot 2018-12-07 at 1 39 28 pm" src="https://user-images.githubusercontent.com/5108034/49666289-98daa500-fa25-11e8-86d1-e1a156fb671b.png">


I'll try working with URLs.
