### ISSUE TITLE
Support update/delete queries for cassandra tables with compound primary keys

### ISSUE THREAD

**Issue by MightyPixel** [TablePlus/TablePlus#843]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra [cqlsh 5.0.1 | Cassandra 2.2.13 | CQL spec 3.3.1 | Native protocol v4]
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
v1. build 163
3. The steps to reproduce this issue:
Create a table with:
```
CREATE KEYSPACE killrvideo WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
use killrvideo;
CREATE TABLE videos_by_tag (
  tag text,
  added_date timestamp,
  video_id uuid,
  title text,
  PRIMARY KEY ((tag), added_date, video_id))
  WITH CLUSTERING ORDER BY (added_date DESC);
INSERT INTO "killrvideo"."videos_by_tag" ("added_date", "title", "tag", "video_id") VALUES ('2018-12-08', 'Application Connectivity', 'cassandra', uuid());
```
Try to update the title of the newly created row. The generated Query is: `UPDATE "killrvideo"."videos_by_tag" SET "title" = 'Node1' WHERE "tag" = 'cassandra';` This query is not sufficient in when the table has such PRIMARY KEY. In order for the query the query needs to specify all fields in the PRIMARY KEY: `UPDATE "killrvideo"."videos_by_tag" SET "title" = 'Node' WHERE tag = 'cassandra' and added_date='2018-12-09 00:00:00 +0000' and video_id = eb8cb6e7-1a16-49b1-96a9-59c2c2b87ee2;`

Thank you!

**Comment by MightyPixel** [comment]
I just found that even more problematic is the delete statement.

Doing a delete in such table with compound primary key is Extremely dangerous:
`DELETE FROM "killrvideo"."videos_by_tag" WHERE "tag" = 'cassandra';` 
It deletes all records with that partition!!!

I think that this issue is critical.

**Comment by huyphams** [comment]
Thanks @MightyPixel I will fix it now.

**Comment by huyphams** [comment]
I have checked the current build, it generates this statement:
`
DELETE FROM "killrvideo"."videos_by_tag" WHERE ("added_date" = '2018-12-08 00:00:00 +0000' AND "tag" = 'cassandra' AND "video_id" = c16cafac-8901-48be-a4c3-b20cbc20e635);
`
But it was wrong.

I have fixed the syntax error, the new build:
`DELETE FROM "killrvideo"."videos_by_tag" WHERE ("added_date" = '2018-12-08 00:00:00 +0000') AND ("tag" = 'cassandra') AND ("video_id" = c16cafac-8901-48be-a4c3-b20cbc20e635);`

Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by MightyPixel** [comment]
I tested with build 163 and the delete query is still `DELETE FROM "killrvideo"."videos_by_tag" WHERE ("tag" = 'cassandra');` and the update one is `UPDATE "killrvideo"."videos_by_tag" SET "title" = 'Node1' WHERE ("tag" = 'cassandra');`

**Comment by huyphams** [comment]
Can you show me the structure? Here is mine
<img width="1451" alt="screen shot 2018-12-09 at 7 17 16 pm" src="https://user-images.githubusercontent.com/3654622/49697204-139eee00-fbe7-11e8-9e65-d46f641da20e.png">

**Comment by huyphams** [comment]
Hey @MightyPixel 
It's fixed now https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by MightyPixel** [comment]
Yes I confirm that it works here as well. Thanks @huyphams !
