### ISSUE TITLE
Encoding problems when Importing from URL

### ISSUE THREAD

**Issue by ilessiivi** [TablePlus/TablePlus#845]
1. Which driver are you using and version of it:
MySQL (issues are during the import of a new connection)

2. Which TablePlus build number are you using:
Build 164

---

There are some problems with the URL import when the password (or any other field I suppose) contains special characters.

Consider this URL, for a connection with `p@ssword` as its password:
```
mysql://dbuser:p@ssword@dbserver.com
```

That can't of course work since `@` is the separator for the user and the server. The standard way of handling this is by percent encoding the parameters, so the correct URL is:
```
mysql://dbuser:p%40ssword@dbserver.com
```
However the URL is not decoded when pasted into the import window and instead of 8 characters, the password input gets filled with 10 characters. Confirming from the Keychain Manager, the encoded password is saved and shouldn't work for connecting.

There's more. Let's add an SSH connection to the URL:
```
mysql+ssh://sshuser@sshserver.com/dbuser:p%40ssword@dbserver.com
```

Interestingly the password is now properly decoded, but the DB host is parsed incorrectly and contains the part of the password after the `@`:
<img width="612" alt="nayttokuva 2018-12-10 kello 12 30 54" src="https://user-images.githubusercontent.com/848786/49729017-f61c6380-fc7c-11e8-8368-f8173b66fb0d.png">

With a `%` character in the password there's something else going on. The URL input does not allow an unencoded percent sign at all, and the percent sign isn't decoded without having the SSH connection there, so the URL now looks like this (with the `@` of the previous examples removed for clarity):
```
mysql+ssh://sshuser@sshserver.com/dbuser:passw%25rd@dbserver.com
```
<img width="612" alt="nayttokuva 2018-12-10 kello 12 59 13" src="https://user-images.githubusercontent.com/848786/49729037-00d6f880-fc7d-11e8-832a-4d3384b2cd6a.png">

The SSH details are correct, but for the server address there is seems to be a fallback to 127.0.0.1, and the DB user and password are missing entirely.

Let me know if there's a workaround for having these characters in the URL or if you need more info.

**Comment by huyphams** [comment]
Hi, there is another way to import and export connection.
<img width="610" alt="screen shot 2018-12-10 at 10 34 05 pm" src="https://user-images.githubusercontent.com/3654622/49742732-b892f700-fccb-11e8-87c2-6081f3307011.png">

I will fix the bug escape character in database password in the next update (encoding URL).
Thanks for the detailed feedback.

**Comment by JiaboHou** [comment]
Hmm, I'm having permissions issues editing the file. Even `chmod` didn't help. I appreciate the suggestion but I think I'll wait for #845 to be resolved as the `open <url>` would be very suitable for my use case

**Comment by MattGrundy** [comment]
Is this still a known issue? 
Would be a big help for getting setup with AWS IAM DB Auth because of the format the token is in.

**Comment by ilessiivi** [comment]
Importing connections from a URL containing special characters is still problematic. I can confirm that the behavior is the same on build 266 as it was in 164.

**Comment by huyphams** [comment]
Hey guys, I think the only solution is we should encode the URL for the link. meanwhile, you guys can share the connection by right click > export connection.

**Comment by MattGrundy** [comment]
Ah for the IAM DB Auth the password gets generated on the fly via an aws cli command so it isn't a predefined connection password we can export or import. The hope is to script it kind of like they do for Workbench or the cli in the AWS examples (https://aws.amazon.com/blogs/database/use-iam-authentication-to-connect-with-sql-workbenchj-to-amazon-aurora-mysql-or-amazon-rds-for-mysql/) but obviously wrapping around TablePlus. But also by doing the url link with the token means we can also set the ENV for the --enable-cleartext-plugin workaround here https://github.com/dbcli/mycli/issues/550 in the shell script to start up TablePlus

**Comment by huyphams** [comment]
I've enabled clear password plugin in MariaDB, which compatible with MySQL and Amazon Auora as well, if you have a chance, please try with MariaDB url schema:
`mariadb+ssh://[ssh_user]:[ssh_pass]@[ssh_host]/[database_user]@[database_host]:[darabase_port]/[database_name]?statusColor=686B6F&enviroment=local&name=[connection_name]&tLSMode=0&usePrivateKey=false&safeModeLevel=0&advancedSafeModeLevel=0`

**Comment by MattGrundy** [comment]
The mariadb connection url doesn't seem to be available on my mac (running from the CLI), it's been updated to 2.9.1 Build 264 (and a check for updates says that's the latest).

Either way the main thing blocking this for us at the minute is the problem with the way the url encoding on the password is being interpretted.

**Comment by huyphams** [comment]
Ops sorry @MattGrundy I just checked and found out that I forgot to handle MariaDB schema. Let me build a hotfix. Please wait for me a min.
`Either way the main thing blocking this for us at the minute is the problem with the way the url encoding on the password is being interpretted.` I'm not sure if this helps: https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command

**Comment by huyphams** [comment]
I've added MariaDB URL schema in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 if you have a chance, please try it @MattGrundy

**Comment by ilessiivi** [comment]
Hi @huyphams and thanks for your reply.

Using the connection export/import via a file method works well for an existing connection. However for importing a completely new connection (one that has never been opened in TablePlus before), using a URL would be the easiest method for me. I have a web portal for database management which has a convenience link with a `mysql+ssh://` formatted URL. Clicking that link opens the TablePlus window and usually it connects automatically.

It's only when the randomly generated database passwords have special characters such as `@` in them, the TablePlus GUI gets stuck, even if the symbols are properly encoded as `%40` for example. Then pasting the same URL in the import dialog, the credentials get split in the way described in my original comment. 

I don't think reading the credentials from ENV vars would work for my situation, or it would be equally cumbersome to use than to manually copy/paste them in, but for CLI users that would probably be great option to have too.

**Comment by huyphams** [comment]
Thanks @ilessiivi I've improved the parsing URL function, if you have a chance, please try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Example:
`postgresql+ssh://maverick:%40somepassword%40@192.168.1.1/postgres:%40password%40@127.0.0.1/katonice?statusColor=686B6F%26enviroment=local%26name=MemeGoo%26tLSMode=0%26usePrivateKey=false%26safeModeLevel=0%26advancedSafeModeLevel=0`

**Comment by ilessiivi** [comment]
That build works perfectly for me 👍

**Comment by nghhoese** [comment]
this is still a problem im getting %23 instead of the character when copy as url
