### ISSUE TITLE
[Feature request] Filter tables using regex with ^, $,| signs

### ISSUE THREAD

**Issue by Matej-Petrla** [TablePlus/TablePlus#847]
Build 160, mac

When filtering tables is already available to use pipe sign | to filter multiple tables.

What is missing is option to use ^ to start table name and $ sign to end table name,
this way, users will be able to filter out unwanted tables from search.

Example:
- existing tables:
    - user
    - user_profile
    - article
    - article_comment

If i want filter only article comments and and their users:
^user$|^article_comment$

When are users working in databases with many many tables, this feature is priceless

Please consider adding this feature.

**Comment by huyphams** [comment]
Thanks, @Matej-Petrla for the suggestion.

**Comment by dasraab** [comment]
i need this feature so bad. please consider adding it

**Comment by ZurabWeb** [comment]
It might actually be more useful to always assume `^` unless `*` is provided in the beginning of the search string.

So a search keyword of `user` would only return tables like `user_addresses` and `user_avatars`, but wouldn't return addresses like `active_users` (doesn't begin with the search keyword).

If you wanted to also include the tables like `active_users` then could change your search keyword to `*user`.

What do you think @Matej-Petrla ?

**Comment by Matej-Petrla** [comment]
@ZurabWeb : I was inspired by Sequel Pro and HeidiSQL.
If you search always from begining of table name, it might not be so user friendly I think.

**Comment by huyphams** [comment]
I added this feature, it will be released on the next release!

**Comment by joshdavenport** [comment]
Would it be possible to support full regex expressions @huyphams?

Evidently right now it's regex like but not actual regex:

![image](https://user-images.githubusercontent.com/757828/67211211-470af580-f412-11e9-90b5-795203fdfde5.png)

Obviously that is a silly expression, but I got here by testing some legit regex expressions that I use to exclude some external integration tables from application tables in a particular clients DB, i.e something like `^(?!(From|To)?Sage)` which excludes any table with name starting FromSage or ToSage. I then use this to dump only tables that aren't matched, so I can do a DB transfer without transferring those tables (which are huge.)
