### ISSUE TITLE
Change backup file names to `DBNAME_YYYY-MM-DD.sql`

### ISSUE THREAD

**Issue by seelensonne** [TablePlus/TablePlus#848]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 8.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 164

3. The steps to reproduce this issue:

Currently, the files generated via the "Backup Database" feature are named as follows (at least for MariaDB/MySQL):

- Pattern: `DBNAME_LONGMONTH_DAY_YEAR.dump`
- Example: `mydb_december_1_2018.dump`

This naming convention makes for long filenames which are not sorted chronologically when displayed in a file manager. In addition, the `.dump` extension is a bit non-standard.

Ideally, the dump files would instead be named like so:

- Pattern: `DBNAME_YYYY-MM-DD.sql`
- Example: `mydb_2018-12-01.sql`

The proposed format does not have the aforementioned issues.

**Comment by Chris1904** [comment]
I would maybe even allow it to be more granular, so we can easily create 2 backups per day and see the whole timestamp including hours & minutes.

**Comment by joshbrw** [comment]
I'd also like to see `.gz` backups retain the `.sql` extension, for example:

`20190429-122449-table.sql.gz`

**Comment by chrschmitz** [comment]
The most flexible approach would be a file name, which can be custom built using parameters, e.g. for %date, %time, %dbname, and so on...

**Comment by huyphams** [comment]
That’s what i’m going to add on the next update @chrschmitz compatible with sequel pro naming pattern

**Comment by andrewmcnaughton** [comment]
> That’s what i’m going to add on the next update @chrschmitz compatible with sequel pro naming pattern

ETA on that update? Sounds amazing!

**Comment by huyphams** [comment]
I'm working on it, it will be released in the next update!

**Comment by huyphams** [comment]
<img width="772" alt="Screen Shot 2019-05-24 at 7 26 34 PM" src="https://user-images.githubusercontent.com/3654622/58327466-e3c46980-7e59-11e9-85fc-87019f3855c8.png">

**Comment by jsgv** [comment]
Where is this option? I am unable to set the filename on backup.

**Comment by knynkwl** [comment]
Did this update ever make it in? kind of weird that this paid app doesn't have this feature but SequalPro which is free, does.

**Comment by knynkwl** [comment]
> I'd also like to see `.gz` backups retain the `.sql` extension, for example:
> 
> `20190429-122449-table.sql.gz`

Any chance this will be added?

**Comment by huyphams** [comment]
Hi @knynkwl  you can type the .sql into the template field directly

**Comment by knynkwl** [comment]
oh okay! thanks
