### ISSUE TITLE
Beautifying SQL doesn't respect the "Tab width" preference

### ISSUE THREAD

**Issue by bforst** [TablePlus/TablePlus#849]
I have set the "Tab width" in the preferences to be "2 spaces", but when I run Beautify on a SQL query, it comes back formatted as four spaces. I expected that it would come back formatted as two spaces. Is this the correct behaviour?

**Comment by huyphams** [comment]
Yup, it's the correct behavior, but, you're right, it should respect the tab width.

**Comment by chrisdeeming** [comment]
Let me know if you'd prefer a separate issue for this. I came to report it as a new issue when this came up 🙂 

In a similar way, beautifying also does not respect the tabs vs spaces setting (it always beautifies with spaces).

**Comment by huyphams** [comment]
Hi @bforst I've fixed this bug and it will be released on the next update.

@chrisdeeming it should be another issue because the current script doesn't support tab (space only), I need to implement it. Thank you for the feedback.
