### ISSUE TITLE
[Feauture Request] Authenticate safe mode with Touch ID

### ISSUE THREAD

**Issue by meijdenmedia** [TablePlus/TablePlus#851]
When you setup "Safe mode" for a production database and make changes to the database you have to enter the database every time. This password obviously shouldn't be easy to remember. I have to either dive into my production servers or search for them in 1Password every time I need to update my production database.

It would be nice if I could just authenticate by placing my finger on the Touch ID scanner from my MacBook.

**Comment by huyphams** [comment]
Hi @meijdenmedia thanks for the suggestion. I added it in this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please go to preferences and enable it.
