### ISSUE TITLE
Add user to connections list sidebar.

### ISSUE THREAD

**Issue by kevinmarx** [TablePlus/TablePlus#852]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Any/PostgreSQL 10.5
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
164
3. The steps to reproduce this issue:
Open multiple connections in the same window to the same database with different users. 
![](https://s3.amazonaws.com/kmarx-screenshots/tableplus.png)
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by alvint** [comment]
I think if issue #723 is implemented simply creating a connection for each user would cover this.

**Comment by kevinmarx** [comment]
Looks like it, missed this issue when I did my search.
