### ISSUE TITLE
Add Documentation Please

### ISSUE THREAD

**Issue by shirshak55** [TablePlus/TablePlus#853]
I have used table plus for like 1 year. Today i found i can do ctrl + P to search anything . Up to now i was using sidebar etc.

I think there are many such hidden gems. I cannot find any docs etc related to it can you please add it ? If I had known there are such things i would have created a new docs myself but as it is closed source i don't know properly.

**Comment by alvint** [comment]
This sounds like a good crowd-sourcing opportunity. Maybe create a "TP tips and tricks" wiki page and let us users document our favorite features until more robust documentation can be made?

**Comment by shirshak55** [comment]
yea . Today i used this cmd + P feature and it is so good. Like there may be various such hidden gems 👍

**Comment by HeyItsMario** [comment]
Yes, a documentation page would be nice. I could not connect to sql server using windows domain and did not know how to set the driver to jTds, set the domain and use NTLM authentication. Turns out it was as simple as logging in with DOMAIN\username.

**Comment by shirshak55** [comment]
Yea I think docs is must as this software has so many hidden things and feature :) Hiding it behind curtain will just cause pain to people like us .

**Comment by shirshak55** [comment]
it seems tp devs are too busy so i am closing this off. If they need help i can do it though :) :)
