### ISSUE TITLE
Add support for autocomplete on table aliases

### ISSUE THREAD

**Issue by kutchar** [TablePlus/TablePlus#854]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
166

3. The steps to reproduce this issue:

`select * from some_table where some_table. ` autocomplete suggests the columns in the table

`select * from some_table as st where st. ` autocomplete doesn't suggests the columns in the table

`select * from some_table st where st. ` autocomplete doesn't suggests the columns in the table

**Comment by huyphams** [comment]
It’s supported. I believe it’s a bug. Let me check it.

**Comment by huyphams** [comment]
Hi @kutchar could you please give me more infor about your setup, table dump etc... I can't reproduce the bug.
<img width="748" alt="screen shot 2018-12-18 at 9 45 06 am" src="https://user-images.githubusercontent.com/3654622/50128979-bf140680-02a9-11e9-9c76-8517044dd486.png">
<img width="704" alt="screen shot 2018-12-18 at 9 45 15 am" src="https://user-images.githubusercontent.com/3654622/50128980-bfac9d00-02a9-11e9-97b3-d42ad904060f.png">

**Comment by kutchar** [comment]
You're right, it works! The issue is that I have a table called `event` which I was using to evaluate TablePlus.

`select * from "event" e where e.` works

`select * from event e where e.` doesn't work

**Comment by deepj** [comment]
@huyphams I guess, there is more problems with aliases auto-complication. I use PostgreSQL 11 and for prototyping reports I use subqueries (PostgreSQL requires having aliases for them)

![screenshot 2019-02-07 at 17 29 05](https://user-images.githubusercontent.com/33736/52426594-25711480-2af6-11e9-8804-a463c4c8d1fd.png)

I would expect `cinema_name` to be hinted in the list.

![screenshot 2019-02-07 at 17 33 10](https://user-images.githubusercontent.com/33736/52426595-2609ab00-2af6-11e9-9631-d3e88577a96f.png)

Here is nothing hinted even I used different aliases but the original name of the table.

**Comment by alvint** [comment]
I'm experiencing similar issues with Oracle on recent builds. There's no column completion available after `m.`:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/622202/52487748-4f751600-2b8c-11e9-919d-dfae83688bd1.png">

**Comment by huyphams** [comment]
Hi @deepj understood.
@alvint I think it's a bug let me check it.

**Comment by huyphams** [comment]
This bug is resolved on this issue: https://github.com/TablePlus/TablePlus/issues/1314
