### ISSUE TITLE
sqlite: Errors are hidden

### ISSUE THREAD

**Issue by mholt** [TablePlus/TablePlus#855]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

SQLite 3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

1.0 (166)

3. The steps to reproduce this issue:

```
CREATE TABLE "mytable" (
	"id" INTEGER NOT NULL,
	"myfield" TEXT
);

INSERT INTO "mytable" ("myfield") VALUES ("foobar");
```

The insert fails because "id" is missing, but no error is shown and the query appears to succeed.

**Comment by huyphams** [comment]
It's resolved: https://github.com/TablePlus/TablePlus/issues/1405
