### ISSUE TITLE
[Feature Request] Implement better support for SSH connections

### ISSUE THREAD

**Issue by mattcdavis1** [TablePlus/TablePlus#856]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 166

I would like to see the following support added for SSH:

* Store ssh key passwords for a given ssh key globally so that the password does not need to be re-entered for each connection.
* Default to id_rsa.pub if no key is entered (possibly make the default key configurable globally)

**Comment by huyphams** [comment]
Hey @mattcdavis1 in this case. I would recommend you to use ssh config. It meets all your requirements

**Comment by mattcdavis1** [comment]
@huyphams - i do use SSH config but i don't think that's the best solution for repetitive information.  I would have to add the same thing to almost every entry.   The whole point of having defaults for anything is to avoid this sort or repetition. 

The functionality i'm requesting is the same as normal ssh - when i want to ssh into a remote server it will default to id_rsa.pub and i'm able to store the password for a give key one time via `ssh -K`.  For information that is different per host (such as username), i use ssh config.

Also, using ssh config for storing the key password is not a good solution because it means i would need to store the password in plain text rather than in encrypted form.

**Comment by mattcdavis1** [comment]
Ok nm - i see what you're saying.  I forgot about setting defaults in SSH config rather than setting the same thing per host.  Also, it does save the password if i used it this way.  

Thanks!
