### ISSUE TITLE
View refresh  before commit when column value is changed

### ISSUE THREAD

**Issue by ashishwadekar** [TablePlus/TablePlus#857]
Greetings @huyphams,

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 166

3. The steps to reproduce this issue:
Change a value in any columns after scrolling horizontally to access, preferably with lots of columns which do not fit in a single view.
That table name is highlighted as expected but the view is refreshed to the original state losing the track of changed column. Now need to scroll horizontally to reconfirm changed value.

This becomes frustrating when a table is having a lot of columns & you need to toggle boolean values when testing stuff.

Let me know if you need more inputs.

Cheers,
Ashish

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, thanks @ashishwadekar. This is one of the known issues and we're working on it.

**Comment by ashishwadekar** [comment]
Noted @huyphams Cheers.

**Comment by huyphams** [comment]
Hi @ashishwadekar, Are you using an external display?

**Comment by ashishwadekar** [comment]
Hi, @huyphams No. Using it only on MacBook display.

**Comment by huyphams** [comment]
I've fixed this issue on the release 174.
