### ISSUE TITLE
Problems with connecting to remote servers over SSH since last update

### ISSUE THREAD

**Issue by polarpixel** [TablePlus/TablePlus#859]
Since last update (Build 166) I cannot connect to remote servers anymore.
I use MySQL.
Local connections are ok, but when trying to connect over SSH I just get the message "Connecting to the server all the time".
See screenshot of my settings.
![2018-12-21_10-55-56](https://user-images.githubusercontent.com/330160/50336745-28e11a00-050f-11e9-89e8-b223abc768f4.png)

**Comment by huyphams** [comment]
Hi, have yoy tried to change the sever ip to 127.0.0.1 and try agian?
Btw you can download the old build in our changelogs: https://tableplus.com/blog/2017/02/changelogs.html

**Comment by polarpixel** [comment]
Hi, yes I tried. You mean as mysql host, right?
Now I tried all the builds to find out, wich changes might be responsible.
Build 146 works, all Builds newer than 150 not.
Any idea what might be wrong?

**Comment by pjwilliams2** [comment]
I'm having the same issue. Unfortunately, the server IP address is not available since I'm using an AWS RDS cluster. My specific use case is I'm trying to connect to RDS through an EC2 SSH server. This works for my Sequel Pro client, so I know the server setup is correct.

**Comment by huyphams** [comment]
Thanks, i will check the commit from build 146 to 150. I will back later. In the meantime, please downgrade to the build 146 🙌

**Comment by josephsiefers** [comment]
Hrmmm...build 146 doesn't seem to be working for me. Similar config to above. Sequel Pro is able to connect with same config.

**Comment by polarpixel** [comment]
Well ... I use Little snitch, but build 146 works and Sequel Pro or PHP Storm too. So I don't believe that it's caused by Little snitch. But I can test it by installing a new version again, if you want.

**Comment by huyphams** [comment]
FYI: From the build > 146, I upgraded the SSH Lib and dropped support `deprecated SSHv1 protocol` maybe it's problem.

**Comment by pjwilliams2** [comment]
@thenaturalist I'm running ESET and have the both the Mac and ESET firewalls turned off.

I made a boneheaded mistake in my config and didn't have the correct ssh server for our dev database, so my issue has since been resolved (build 170).

**Comment by polarpixel** [comment]
Sorry for my late reply. Everything works fine so for me we can close this issue.

**Comment by huyphams** [comment]
Thanks guys!
