### ISSUE TITLE
Copy as... with an empty column name

### ISSUE THREAD

**Issue by zanmato** [TablePlus/TablePlus#860]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server Web 14.0.1000.169

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
166

3. The steps to reproduce this issue:
```sql
SELECT CONCAT('does not', 'work');
SELECT CONCAT('does', 'work') AS bla;
```
Trying to use "Copy as plain text" on results of the first query will not work, anything you paste afterwards will just be empty. However it will work for the second one because of the column name.

**Comment by huyphams** [comment]
Thanks, i will check and fix it in the next release.

**Comment by huyphams** [comment]
I fixed it, it will be included in the next build 168.
