### ISSUE TITLE
Passwords are not being stored in Keychain

### ISSUE THREAD

**Issue by varyform** [TablePlus/TablePlus#864]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySql 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
170

3. The steps to reproduce this issue:
Create a connection with password and quit the app – "Access denied for user ... (using password: NO)

**Comment by huyphams** [comment]
Have you resolved it @varyform ?

**Comment by haric655** [comment]
@varyform Do you solved problem?

**Comment by maxgalbu** [comment]
Still having this issue...

**Comment by coilnovasince1985** [comment]
issue still exists on mac os majove

**Comment by maxgalbu** [comment]
@huyphams found out that if I change database driver, it saves them correctly. Weird?
