### ISSUE TITLE
Copy Rows As SQL Insert Statement not excluding filtered columns.

### ISSUE THREAD

**Issue by martingalovic** [TablePlus/TablePlus#866]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mysql 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 170

3. The steps to reproduce this issue:
- Choose only some columns from table, not all of them
- Right-click > Copy Rows As > SQL Insert Statement

The SQL Insert Statement (imo) should include only filtered columns, but it includes all of them

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @martingalovic I will improve it.

**Comment by huyphams** [comment]
Done! it will be included in the next update, along with all the Copy As...
