### ISSUE TITLE
Add `Generate UUID (v4)`option

### ISSUE THREAD

**Issue by ruudk** [TablePlus/TablePlus#867]
It would be really handy if there was a way to quickly generate a UUID (v4) when you are inserting new rows. 

Now I quickly go to https://www.uuidgenerator.net/ and copy a new ID.

**Comment by huyphams** [comment]
Hi @ruudk please follow this issue: https://github.com/TablePlus/TablePlus/issues/1499 I've added support for it.

**Comment by huyphams** [comment]
Actually, it was UUID v1, but you can change it to v4 easily.
