### ISSUE TITLE
PostgreSQL: DROP STORED PROCEDURE

### ISSUE THREAD

**Issue by petersirka** [TablePlus/TablePlus#868]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
__PostgreSQL v11.1__

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
__170__

3. The steps to reproduce this issue:
__Create a stored procedure and try to remove it directly from the `Functions` list. The app tries to `DROP FUNCTION` instead of `DROP PROCEDURE`.__

![dropprocedure](https://user-images.githubusercontent.com/2414252/50654810-522d8b80-0f8e-11e9-96d0-b2af2cca5989.gif)

**Comment by huyphams** [comment]
Thanks @petersirka I will fix it.

**Comment by huyphams** [comment]
It's fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
it will be included in the next update thanks for the feedback.

**Comment by petersirka** [comment]
Great! Thank you, it was fast!
