### ISSUE TITLE
TablePlus asking for access to very unrelated keychain item

### ISSUE THREAD

**Issue by thibmaek** [TablePlus/TablePlus#87]
This does not seem OK.
![image](https://user-images.githubusercontent.com/6213695/31632526-7f032478-b2bd-11e7-849a-036eb5c66e3a.png)

**Comment by huyphams** [comment]
Hi @thibmaek, thank you for your feedback. I have an user report this problem before but I can't figure out why TablePlus require this keychain.
I'm trying to figure out this problem, please keep follow this issue.

**Comment by huyphams** [comment]
I think I found the problem, TablePlus load user token in keychain, but TablePlus and Pocket App save token with the same key (Keychain is key-value dictionary) then when you have Pocket  and TablePlus app, the key will be conflict and override.
Solution: I will change TablePlus key in Keychain and it will never ask again.

**Comment by huyphams** [comment]
Hi @thibmaek the bug was fixed in new release, please check it out.
