### ISSUE TITLE
[Enhancement] - Edit results in SQL query result window

### ISSUE THREAD

**Issue by martingalovic** [TablePlus/TablePlus#870]
I'm coming from Sequel PRO where i can easily do something like
```select * from webhosting_domains where id=975;```
and then edit columns like `reg_status` right in result window.

I'm missing this feature in TablePlus, and it would be great addition.

**Comment by huyphams** [comment]
It's already supported, which driver are you using @martingalovic, please fill out the template issue questions for the detail.

**Comment by martingalovic** [comment]
@huyphams When I'm using driver MySQL 8.x and the development server (MariaDB 10.2.12) I'm not able to see or even commit the changes. See gif:
(https://media.giphy.com/media/24FRXKt64jToCKNnos/giphy.gif)

When I'm using same driver and the production server (MySQL 5.7.24) column changes color and I'm able to commit changes afterwards.

**Comment by huyphams** [comment]
Thanks @martingalovic it helps me a lot, I will try with MariaDB 10.2.12 (I've tested with 10.3.4 but it works).

**Comment by huyphams** [comment]
Hey @martingalovic could you please check out this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
I have added a small improvement for MariaDB as an attempt to fix this issue.

**Comment by martingalovic** [comment]
@huyphams that one works, thanks.
