### ISSUE TITLE
A bug with formatted "Paste" data from clipboard

### ISSUE THREAD

**Issue by petersirka** [TablePlus/TablePlus#872]
When I copy some formatted e.g. SQL quries from web browser then Table Plus keeps the format according to the website. Look to my __GIF__.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
__It doesn't matter.__

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
__170__

3. The steps to reproduce this issue:

![copy_paste](https://user-images.githubusercontent.com/2414252/50726991-fc372000-1114-11e9-8b15-6faca7dedd69.gif)

**Comment by martingalovic** [comment]
Try this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It's not happening to me though.

**Comment by huyphams** [comment]
I confirmed the bug and it's fixed now. It only happens in function editor (query editor works fine).
