### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by donbeave** [TablePlus/TablePlus#874]
Hello guys!

Happy New Year!

I just want to know, do you have any plans for releasing iOS version of TablePlus, something much better than current solutions. I'm pretty sure you guys can do it better a lot, same as what you did with releasing TablePlus.

There is only two decent PostgreSQL client for iOS:
1) https://itunes.apple.com/us/app/postgres-client-by-sqlpro/id1273366655?mt=8
2) https://itunes.apple.com/us/app/navicat-for-postgresql/id954677642?mt=8

But still very far from what I can call convenient application, but better than nothing.

Hope TablePlus can make an iOS app in this year!

**Comment by huyphams** [comment]
Yep, we do have that plan.
1. Design: Done.
2. TablePlus iOS database frameworks (70% done).
3. We started the iOS GUI App a week ago.
Thanks for pointing out some other apps on the App store but TablePlus will not aim to be the same with it, please patient. Happy new year! ;-D

**Comment by huyphams** [comment]
Hi guys!
![IMG_3860](https://user-images.githubusercontent.com/3654622/56079098-e7f07680-5e19-11e9-990a-9598fe5e5152.jpeg)

**Comment by donbeave** [comment]
**AMAZING**!!!

**Comment by Milhound** [comment]
Looks great, and looking forward to trying it out

**Comment by marcsantiago** [comment]
Super excited

**Comment by kiliankoe** [comment]
I'm happy to volunteer for any TestFlight Betas if you're ever in need 😜

**Comment by huyphams** [comment]
The beta is now released: https://testflight.apple.com/join/vGBHpbO3
I will close this thread, new issue tracker for iOS: https://github.com/TablePlus/TablePlus-iOS/issues
