### ISSUE TITLE
error in postgreSQL connection

### ISSUE THREAD

**Issue by manieshablakey** [TablePlus/TablePlus#875]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): postgreSQL 11.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 170

3. The steps to reproduce this issue: Clicked on TablePlus icon --> Clicked on create new connection --> Clicked on postgreSQL, added info  & then connect(image file attached)

My problems are as follows:
- I get a connect error message (image attached) saying 'FATAL: role "Maniesha" does not exist. It then proceeds to the tableplus platform but message in pink at the top says 'Database is disconnected. Tap to reconnect.' However, when I try to reconnect, I keep getting the same error message:  'FATAL: role "Maniesha" does not exist.
- if I start over and click on my TablePlus icon again, I see the following: the server1 I tried to set up before seems to be there but if I click on it, I still get the  'FATAL: role "Maniesha" does not exist. message. (image attached)

I'm very confused. Do I need to set up new server connections every time? Why am I getting  the FATAL role "Maniesha" does not exist message? What is the part that's not connecting/working here and how do I fix it? How do I connect to my database? And import a csv file? Thanks for your help.

<img width="483" alt="screen shot 2019-01-08 at 9 21 28 am" src="https://user-images.githubusercontent.com/40118442/50804205-d723e800-12a1-11e9-8801-b9eee75237c4.png">
<img width="499" alt="screen shot 2019-01-08 at 9 22 10 am" src="https://user-images.githubusercontent.com/40118442/50804208-d9864200-12a1-11e9-9a3f-7e97356fa7df.png">
<img width="521" alt="screen shot 2019-01-08 at 9 20 57 am" src="https://user-images.githubusercontent.com/40118442/50804234-f3278980-12a1-11e9-9678-4bff95212a62.png">

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @manieshablakey are you new with PostgreSQL Database?
1.  'FATAL: role "Maniesha" does not exist. => That means you haven't created a "Maniesha" user/role yet.
The solution, please create it first. https://www.postgresql.org/docs/9.5/sql-createrole.html

2. Do I need to set up new server connections every time?  => No, you can save connection and double to open it, no need to create a new connection each time.

None of the issues is related to TablePlus so you can email me at huy@tableplusapp.com or using or chat to get faster support.
