### ISSUE TITLE
error in connecting to postgreSQL server

### ISSUE THREAD

**Issue by manieshablakey** [TablePlus/TablePlus#876]
<img width="546" alt="screen shot 2019-01-08 at 9 23 55 am" src="https://user-images.githubusercontent.com/40118442/50805895-35a09480-12a9-11e9-9fdd-83ab0263168f.png">
<img width="521" alt="screen shot 2019-01-08 at 9 20 57 am" src="https://user-images.githubusercontent.com/40118442/50805898-3802ee80-12a9-11e9-8957-e9a6511ac3f5.png">
<img width="499" alt="screen shot 2019-01-08 at 9 22 10 am" src="https://user-images.githubusercontent.com/40118442/50805899-39ccb200-12a9-11e9-8c0e-95c77455ed1e.png">

Which driver are you using and version of it (Ex: PostgreSQL 10.0): postgreSQL 11.0

Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 170

The steps to reproduce this issue: Clicked on TablePlus icon --> Clicked on create new connection --> Clicked on postgreSQL, added info & then connect(image file attached)My problems are as follows:I get a connect error message (image attached) saying 'FATAL: role "Maniesha" does not exist. It then proceeds to the tableplus platform but message in pink at the top says 'Database is disconnected. Tap to reconnect.' However, when I try to reconnect, I keep getting the same error message: 'FATAL: role "Maniesha" does not exist.if I start over and click on my TablePlus icon again, I see the following: the server1 I tried to set up before seems to be there but if I click on it, I still get the 'FATAL: role "Maniesha" does not exist. message. (image attached)

I'm very confused. Do I need to set up new server connections every time? Why am I getting the FATAL role "Maniesha" does not exist message? What is the part that's not connecting/working here and how do I fix it? How do I connect to my database? And import a csv file? Thanks for your help.
--

**Comment by huyphams** [comment]
I have answered your question in the last issue.
1. "FATAL role "Maniesha" does not exist" => It's not related to TablePlus, it came from PostgreSQL, and it means that you've created a database role, please read the database docs for more detail.
2.  Do I need to set up new server connections every time => No.
I've also attached a screenshot on the old issue to show you how to setup please check it.

**Comment by huyphams** [comment]
Duplicated with: https://github.com/TablePlus/TablePlus/issues/875

**Comment by manieshablakey** [comment]
Thank you for your help! I've got the connection to work. Will work through doc to figure out the rest
