### ISSUE TITLE
Table definition does not follow Azure SQL Serve schema for varchars

### ISSUE THREAD

**Issue by MrMathias** [TablePlus/TablePlus#877]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Azure SQL Server

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
164

3. The steps to reproduce this issue:
- connect to Azure SQL Server
- create table with a varchar(MAX) field
- go to structure -> definition
- definition uses varchar(-1)

**Comment by huyphams** [comment]
Interesting @MrMathias I will fix it now.

**Comment by huyphams** [comment]
Hey @MrMathias I fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by MrMathias** [comment]
Good stuff, thanks!
