### ISSUE TITLE
Export To Laravel Migration

### ISSUE THREAD

**Issue by PyaeSoneAungRgn** [TablePlus/TablePlus#879]
It is possible to export laravel migration file from tables?

**Comment by joshbrw** [comment]
There are plenty of packages out there that can do this for you - I don't think this should be a part of the TablePlus app itself.

**Comment by huyphams** [comment]
It's supported by install plugin table dump: https://github.com/TablePlus/tabledump

**Comment by fgilio** [comment]
Awesome
