### ISSUE TITLE
Alter View never saves

### ISSUE THREAD

**Issue by davidharrison92** [TablePlus/TablePlus#881]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MS SQL 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

1.0 / Build 170

3. The steps to reproduce this issue:

Open an existing view, edit the structure, try to save the change back (⌘ + S).

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
TablePlus doesn't support edit view's struct, it will show you an alert except you edit it by the right panel (I will fix this issue).
You can only edit view definition.

**Comment by huyphams** [comment]
Thanks @davidharrison92  did you see any error popup? Have you renamed the view before? I faced an issue when remaning a view, then i can’t change the view definition because it was not updated.

**Comment by davidharrison92** [comment]
@huyphams No changes to the name, no error messages. In the most recent build I have not experienced this issue.

**Comment by caesarsamsi** [comment]
Open Structure on a View does not show a "Definition" in the top pane as would for opening a structure for Tables.

This means there is no way to Alter a View ? How would you do that?

Am I missing something here?
![Table has Definition button can ALTER VIEW](https://user-images.githubusercontent.com/8953119/79806776-11da5400-831e-11ea-800d-c017f6e6e4b1.png)
![Table has Definition button can ALTER VIEW](https://user-images.githubusercontent.com/8953119/79806786-17379e80-831e-11ea-882b-90cd3a229fd6.png)

**Comment by huyphams** [comment]
You can double click to the table content and edit the field right on the UI, then press command + S to save @caesarsamsi
