### ISSUE TITLE
Boolean values displayed confusingly on Snowflake

### ISSUE THREAD

**Issue by johnmastro** [TablePlus/TablePlus#885]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Snowflake 3.8.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 174

3. The steps to reproduce this issue:

Execute this query

```
select true as x, false as y
```

Expected result:

| X         | Y          |
| ------ | ------- |
| TRUE  | FALSE  |

Observed result:

| X         | Y          |
| ------ | ------- |
| 1         | EMPTY |

The result is the same if the data comes from `BOOLEAN` columns instead of literals.

**Comment by huyphams** [comment]
Hey thanks @johnmastro I closed my trial account at Snowflake, I will request a new account and fix this issue asap.

**Comment by johnmastro** [comment]
Thanks! Much appreciated. My team started using TablePlus with Redshift and have really enjoyed it. We switched over to Snowflake this week and will continue to report any Snowflake issues we run into :)

**Comment by huyphams** [comment]
Hey @johnmastro I made a change based on your feedback that can map 1 to TRUE and EMPTY to FALSE, I didn't have any Snowflake connection so I'm not sure the build works or not.

There is a case that I need to test to make sure it works correctly. Does boolean have NULL value? and how it shows in TablePlus? Could you give it a try? Thank you so much.

Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by johnmastro** [comment]
I did a quick test and it appears to work as expected. Boolean values are now displayed as `TRUE` or `FALSE`.

Booleans can be `NULL`, and that appears to be handled correctly too - they're displayed as `NULL` in a lighter text color.

Thanks for working on this.
