### ISSUE TITLE
Application unresponsive during larger queries on Snowflake

### ISSUE THREAD

**Issue by johnmastro** [TablePlus/TablePlus#887]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Snowflake 3.8.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Build 174

3. The steps to reproduce this issue:

Run this query

```sql
select seq4() as col1
from table(generator(rowcount => 100000))
```

The first result rows are displayed quickly, but TablePlus then becomes unresponsive ("spinning beach ball") for approximately 40 seconds. During this time, pressing `⌘-.` to abort the query has no effect.

When I run an equivalent query via TablePlus on Redshift, like

```sql
select *
from generate_series(1, 100000, 1)
```

TablePlus stays responsive the whole time.

I'm encountering this problem in practice with much larger queries (in terms of both row counts and columns) where the delay is much longer and I eventually end up "force quitting". The Snowflake web query interface stays responsive when running the same large queries.

I noticed [a similar issue](https://github.com/TablePlus/TablePlus/issues/837) already exists but that one is for MySQL.

**Comment by johnmastro** [comment]
@huyphams Anything I can do to help diagnose this?

**Comment by huyphams** [comment]
Hi I don't have any Snowflake instance, so I can't try it out, but I just added and updated a few features on this build for Snowflake: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
1. Upgrade SnowflakeDB Lib with bug fixes and more features.
2. Supported limit returned rows in Query Editor.

Could you please give it a try? Thanks!

**Comment by johnmastro** [comment]
The SnowflakeDB Lib upgrade doesn't seem to help with the responsiveness issue - TablePlus still locks up for ~40 seconds with my test query above (and significantly longer on some queries my team works with).

The row limit is helpful. If possible, it would be great if we could pull in additional rows on-demand. A UI idiom I've seen for this before would be to pull in another ~500 (or whatever) upon scrolling to the bottom of result set window.

Thanks!

**Comment by foundinblank** [comment]
I have been running into this exact same issue a lot more lately with the recent builds, but only if I forget to set the row limits. It'd be good to just be able to stop the query instead of having to force-quit and restart/reconnect.

**Comment by huyphams** [comment]
it's hard to cancel a query if the driver doesn't support it, meanwhile, you can workaround by using the built-in query limitation in TablePlus @foundinblank 
<img width="614" alt="limit" src="https://user-images.githubusercontent.com/3654622/55948280-5bf41880-5c7a-11e9-90a6-714169ce9bc5.png">

**Comment by dornby** [comment]
Hello, we're running into the same issue @ drivy with Snowflake.

As soon as the query hits more than 100K lines it freezes.

We'll use the query limitation meanwhile but it doesn't fix the issue > more than often, you want all your rows returned.

**Comment by huyphams** [comment]
Thank you guys, I will investigate and update the snowflake support on the next release.

**Comment by foundinblank** [comment]
It still hangs even if I set the built-in TablePlus query limitation to 100, if the overall result set would be >100k rows. The only way to make it not hang is to actually write `LIMIT 100` in the query. 

I wonder if it has something to do with calculating the row count displayed at the bottom of the window...

**Comment by huyphams** [comment]
Thank @foundinblank 
it hangs when viewing data by clicking the item on the left sidebar or by running query in SQL Query? yes, possible because of the count query if you view the item by clicking it on the sidebar.

**Comment by foundinblank** [comment]
By running the query in SQL Query.

**Comment by huyphams** [comment]
Please turn on the console (command + shift + C) and run a query, does TablePlus append a limit in the end?
<img width="1393" alt="limit" src="https://user-images.githubusercontent.com/3654622/56355834-85282200-6201-11e9-9bb5-af8309e94362.png">

**Comment by foundinblank** [comment]
Oo...nope! It isn't appended at the end. 

![image](https://user-images.githubusercontent.com/31513760/56356213-167ea080-61d0-11e9-8d19-88bf5b47d0cc.png)

**Comment by huyphams** [comment]
Made sense. Thank you so much @foundinblank I think TablePlus skipped the limit because of the order by 2 (it's clearly a TablePlus bug). I will fix it.

**Comment by foundinblank** [comment]
Thank you. Glad I can help! I tried it both with a `;` at the end and without, just to see if the semicolon was causing problems. The query hangs both times so it isn't the semicolon.

**Comment by huyphams** [comment]
can I have the full version of that query @foundinblank? my email is huy@tableplusapp.com please remove/obfuscate sensitive data before sending.

**Comment by dornby** [comment]
This is becoming a pressing issue, not only the mandatory `LIMIT` hurts our productivity because often we want all our data rows returned but also we end up Force Quitting every single time we forget it, which happens *a lot*.

**Comment by huyphams** [comment]
the problem with Snowflake is they don't give us a demo connection, so every time I want to fix/or take a look into it, I need signup a new account, add a credit card and set up everything from scratch.

Thank you guys for the feedback and the patient, I will create a new account and investigating this issue.

**Comment by dornby** [comment]
Any news on this one @huyphams ?

**Comment by huyphams** [comment]
Hey guys, I upgraded Snowflake lib to the latest build, and also resolved several issues.
- unresponsive during larger queries.
- Show view/materialized view and table correctly.
Download here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
If you still seeing this issue, please let me know.

**Comment by johnmastro** [comment]
@huyphams thanks so much, from some brief testing it seems like a huge improvement for us on Snowflake! :)

One thing I noticed is that typing `⌘.` results in a message window saying "TablePlus doesn't support showing process list on this driver", whereas clicking the `Cancel` button in the SQL window successfully cancels the query. I believe typing `⌘.` should have the same effect as clicking the button.

**Comment by dornby** [comment]
@huyphams it seems like it fixed the problem indeed! Thanks a lot
@johnmastro agreed but this should probably get an issue of its own: https://github.com/TablePlus/TablePlus/issues/1440
