### ISSUE TITLE
UI freezes completely when hitting ctrl+a followed by ctrl+k in the `Open anything search` box.

### ISSUE THREAD

**Issue by ckm2k1** [TablePlus/TablePlus#888]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.17

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
OSX - Version 1.1 (174)

3. The steps to reproduce this issue:
  1. Hit command+p (open anything dialog appears)
  2. Type the name of any table (results appear)
  3. Hit ctrl+a and then ctrl+k
  4. UI becomes unresponsive and the application has to be restarted completely.

The reason for ctrl+a/k is because on OSX those keys are bound, respectively, to `go to beginning of line` and `yank from cursor until end of line` which effectively deletes the line and starts over. This key combo works in many if not most text boxes on OSX. It would be nice to be able to use it inside of the `Search anything` dialog as well.

**Comment by huyphams** [comment]
I have fixed it on the release 176.

**Comment by ckm2k1** [comment]
@huyphams Thank you, this is awesome!
