### ISSUE TITLE
[Website] Recovery password does not work.

### ISSUE THREAD

**Issue by FedericoBiccheddu** [TablePlus/TablePlus#89]
I can't reset my password because the request forms returns an error, in the console only, without giving any feedback:

```json
{"Ok":false,"Data":{"fullName":"","email":"","country":"","city":"","state":""},"Error":{"fullName":"Invalid Name"},"Message":"Invalid Name"}
```

The url requested is `https://tableplus.io/order/paypal/form`.

Even if I try to register a new account to know if my email is already registered (maybe this is the reason because I can't recovery my password?), I receive a general error "Invalid Input Errors".

**Comment by huyphams** [comment]
Hi @FedericoBiccheddu thank for feedback, I'm fixing it.

**Comment by huyphams** [comment]
Hi @FedericoBiccheddu , the bug was fixed, please try again 👍

**Comment by FedericoBiccheddu** [comment]
Hi @huyphams, thank you for the fast fix; it seems to be resolved.
