### ISSUE TITLE
Workspaces Button / New workspace

### ISSUE THREAD

**Issue by jjernberg** [TablePlus/TablePlus#892]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): N/A

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):  176

3. The steps to reproduce this issue:  Click on workspaces button

Was there a "+" in the workspaces screen in a previous build?   A colleague and I swear there was a "+" to create a new workspace, but it's not longer there.   Also, creating a new from the menu creates a new window and not a workspace in the current window.

**Comment by huyphams** [comment]
Now, it's back.
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks @jjernberg

**Comment by jjernberg** [comment]
Great, Thanks!
