### ISSUE TITLE
ÅÄÖ disappear when beautifying

### ISSUE THREAD

**Issue by lasseedfast** [TablePlus/TablePlus#893]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 174

3. The steps to reproduce this issue: Write query where one of the letters åäö is included.

`SELECT DISTINCT avsändare, mottagare
FROM mönstermejl`

becomes 

`SELECT
    DISTINCT avs ndare,
    mottagare
FROM
    m nstermejl`

A workaround is of course not to use åäö but sometimes the tables comes with column namnes including those and it would be nice not to have to change them in order to use beautify.

**Comment by huyphams** [comment]
Hi if you have a chance, you could try this patch, it fixes all the issues:
https://www.dropbox.com/scl/fi/rnzl329j9llknuoj0c0h1/TablePlus.dmg?rlkey=fykl1eshbl1ylnn48s5ic7rau&st=00mt04zi&dl=0
