### ISSUE TITLE
Export current page to SQL File

### ISSUE THREAD

**Issue by arnotae** [TablePlus/TablePlus#894]
It is possible to export current page to SQL file (currently only JSON & CSV)?

**Comment by huyphams** [comment]
Hi, the easiest way is Command + A > Right click > Copy Rows As > Insert statements.

**Comment by huyphams** [comment]
Btw, I'm going to add SQL Tab into the export result windows, if TablePlus can't detect the table, it will use `untitled`.

**Comment by arnotae** [comment]
Thanks !
