### ISSUE TITLE
Cannot use windows authentication in MSSQL using windows client.

### ISSUE THREAD

**Issue by moxplod** [TablePlus/TablePlus#896]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL Sql express.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows build 44.

3. The steps to reproduce this issue:
tried putting the database, user as domain\username and host as localhost\sqlexpress.

It gives an error user not found.

**Comment by son11592** [comment]
@moxplod, can you capture your new connection screen for more information?

**Comment by huyphams** [comment]
Hi @moxplod currently, we experienced an error with the escaped characters.
Have you tried to escape it manually? 
`domain\username => domain\\username`

**Comment by moxplod** [comment]
I am able to use SSMS, on TablePlus tried both - 

![image](https://user-images.githubusercontent.com/4554395/51405851-502a0780-1b0c-11e9-923f-2252625e6699.png)

![image](https://user-images.githubusercontent.com/4554395/51405878-63d56e00-1b0c-11e9-8cfa-60446bab9cba.png)

Neither worked.

**Comment by moxplod** [comment]
I got a different error when i tried to escape both host and user - 
You cant see host in the image - its - localhost\\sqlexpress

![image](https://user-images.githubusercontent.com/4554395/51406025-c890c880-1b0c-11e9-8297-689aabba1c7f.png)

**Comment by huyphams** [comment]
We fixed that bug @moxplod, thank you so much! it will be included in the next update next week.
Have a nice weekend.

**Comment by huyphams** [comment]
it was fixed on the build 46.
