### ISSUE TITLE
Feature request - redis support for windows client.

### ISSUE THREAD

**Issue by moxplod** [TablePlus/TablePlus#898]
I was sold as soon as i opened TablePlus as this is going to be my GUI tool of choice. (OMG all the other Postgres and redis gui's really suck!)

This would make this the most epic DB GUI tool for me if i could have redis on windows client as well, since it does not look like its supported as well.

**Comment by huyphams** [comment]
Hi thanks @moxplod I will pass your request to our Windows team. But, sure we will support it.

**Comment by huyphams** [comment]
Sorry, I accidentally press the close issue.
Our Windows issue tracker here: https://github.com/TablePlus/TablePlus-Windows/issue
