### ISSUE TITLE
Feature request: beautify JSON

### ISSUE THREAD

**Issue by ffxsam** [TablePlus/TablePlus#899]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Postgres 10.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 1.1 build 176

It would be nice to have a nicely formatted JSON view (indented, maybe colorized) to make this data easier to view.

<img width="272" alt="screen shot 2019-01-18 at 1 55 31 pm" src="https://user-images.githubusercontent.com/12532733/51410035-0a2f6c80-1b29-11e9-9a9f-3e3ba53a7adc.png">

**Comment by Mutahhar** [comment]
> Agree, TablePlus should beautify the JSON on the detail pane by default.

@huyphams 
any progress on this?
