### ISSUE TITLE
Windows and Linux releases. 

### ISSUE THREAD

**Issue by pavinthan** [TablePlus/TablePlus#9]
When will be available for windows and Linux?

**Comment by huyphams** [comment]
Hi @pavinthan,
Team are working with Windows Version and will release a beta in couple month, but we didn't have plan for Linux at this time.

**Comment by philbritton** [comment]
Any update on beta version for windows?

**Comment by coreylenertz** [comment]
I'd be interested in providing feedback for a windows beta.

**Comment by huyphams** [comment]
Sorry you guys because of the delay, We have an issues when compile library for Window version, we need to rewrite some driver and it takes time more than our expectation.
We will let you know when we have a beta version

**Comment by krekas** [comment]
Linux version would be really great

**Comment by eberkund** [comment]
@huyphams Any chance you could tease us with some screenshots of the UI of the Windows version?

**Comment by huyphams** [comment]
We will have an engineer join our Windows team at 15-Feb.

![screenshot 2018-02-07 22 23 15](https://user-images.githubusercontent.com/3654622/35925189-aceb5560-0c57-11e8-92d2-d89bd8c0a481.png)

**Comment by eberkund** [comment]
Thanks, I can't wait, I'm sure it's going to be awesome!!

**Comment by ozairasim** [comment]
@huyphams Do you guys have an approximate release date in mind for the windows version?

**Comment by arandilopez** [comment]
I'd love a linux version

**Comment by eberkund** [comment]
For anyone who comes across this, there was a lengthy update posted to [their blog](https://tableplus.io/blog/2018/04/tableplus-windows-version-when-is-it-coming-out.html)

**Comment by rendom** [comment]
Linux :+1:

**Comment by akalongman** [comment]
Linux please

**Comment by MariusVB** [comment]
"At the moment, we do not have a plan for a Linux version. Because Linux has too many distros."

Release it as a Snap package or Flatpak, and you will reach a lot of distros.
https://snapcraft.io/
https://flatpak.org/

**Comment by huyphams** [comment]
Thanks @MariusVB flatpak is very interesting, I will try it out.

**Comment by rahacker2006** [comment]
@huyphams Here I am if you need my help (schedule, test, document, etc.), for te linux version of course.

**Comment by eberkund** [comment]
I can help with snap packaging if needed

**Comment by MariusVB** [comment]
News?

**Comment by dagoodma** [comment]
A linux version would be great!

**Comment by ShawnMcCool** [comment]
I'm in the market for this software. But I only develop on Linux. Would love to be notified of a Linux release.

I have much experience participating in software betas and I provide a lot of feedback if you need some help there.

**Comment by LeonAlvarez** [comment]
any news on Linux realese?

**Comment by jacurtis** [comment]
Just throwing my support out there for Linux as well. I love TablePlus on Mac. Unfortunately I am moving away from Mac to Linux for development and miss not having TablePlus in Linux

**Comment by dnl-jst** [comment]
Same here. Moving away from Mac to Linux. Would love having TablePlus there.

**Comment by huyphams** [comment]
The Windows is released, please follow the issue https://github.com/TablePlus/TablePlus/issues/1056
for Linux.

**Comment by alif-bae** [comment]
While we're holding our breath for Linux support, checkout dbeaver as a great alternative: https://github.com/dbeaver/dbeaver

**Comment by hieuhlc** [comment]
@alif-bae why are you holding your breath? Linux support is already released and people are loving it

https://tableplus.com/linux

This is not a good place for advertising though.

**Comment by alif-bae** [comment]
@hieuhlc my bad, I should've done due diligence before commenting. Thanks for the info!
