### ISSUE TITLE
Search by part of the name in Open Anything

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#90]
When you type from the word start - it works correctly
![Works fine](https://i.imgur.com/K2XtuAP.png)
But if you will try to search by the substring in the middle of the word - you won't find anything
![Doesn't work](https://i.imgur.com/f9FQpZ2.png)

Can't imagine usage of Open Anything feature without this abiliity.
Thanks.

**Comment by huyphams** [comment]
Hi @PVGrad 
Open Anything supports open table by prefix search, It's very hard to complete word by `substring in the middle of the word`.

Apple spotlight has the same behaviors, you can open chrome by type `chro` but can't not be `hrome`

For enhancement, I will include result search  by `middle of the word` in an other section but can't in search field.
Like this:
![nice](https://user-images.githubusercontent.com/3654622/31846505-cf402270-b636-11e7-9632-4351b24a5321.png)

**Comment by PVGrad** [comment]
So then you should take as example of great implementation Goto anything feature in Sublime Text 3 text editor and not Apple spotlight:
![cmd+p](https://camo.githubusercontent.com/ae4da342a09900b3c3682416595b30eca758ca6b/687474703a2f2f692e696d6775722e636f6d2f737737487273702e6769663f31)
here is description of it's possibilities:
![st3_goto](https://i.imgur.com/meVIdL8.png)

And YES - it would be great to do `include result search by middle of the word in an other section`
Thanks a lot!

**Comment by huyphams** [comment]
Hi @PVGrad I think we can apply Fuzzy search (like sublime text) for open anything. I will release a beta for next build so we can see how it improved 👍

**Comment by huyphams** [comment]
Supported fuzzy search (just like sublime text)

![screen shot 2017-10-29 at 1 49 17 pm](https://user-images.githubusercontent.com/3654622/32141320-0b47e2f6-bcb0-11e7-938c-339c0578dd92.png)
