### ISSUE TITLE
Column width wrongly calculated

### ISSUE THREAD

**Issue by hyperknot** [TablePlus/TablePlus#901]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostgreSQL 9.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.2 182, macOS 10.14.2

3. The steps to reproduce this issue:

Run a query like the following:
```
select col1, count(distinct col2) from table group by col1;
```

I'll split the screen in such a way that col1 is absolutely wide, and the count column's values won't even be visible. 

What's funny is that no matter how large I resize the main window, the second column's values will always be exactly just hidden.

<img width="782" alt="uibug" src="https://user-images.githubusercontent.com/494223/51447583-f732bd00-1d1f-11e9-8b2c-83f95640a095.png">

(In the screenshot above, all strings in the first column are max 6 characters long, there really is no need to have that wide column.)

**Comment by huyphams** [comment]
Thanks @hyperknot We will fix it on the next build, we're improving the column sizing, it needs to be smarter.

**Comment by erikbos** [comment]
Any update on this one?

**Comment by huyphams** [comment]
Please download this build @erikbos https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
TablePlus remember the size you've changed so it will be the same column size after re-run or reopen table. it's much better.

**Comment by erikbos** [comment]
Thanks for the rapid response! With the 203 version it's still the same behaviour. 

A query that returns two columns on cli:

![Screenshot 2019-03-13 at 11 38 59](https://user-images.githubusercontent.com/1421163/54278219-11f01800-4592-11e9-8631-1a122e8607ec.png)

first column is character varying(8), second double precision.

is shown as:

![Screenshot 2019-03-13 at 11 39 15](https://user-images.githubusercontent.com/1421163/54278235-1caaad00-4592-11e9-8eb4-fbe5ef491092.png)

**Comment by erikbos** [comment]
The width behaviour of the second column can also be observed with a single column and single row. A query that outputs a large value does not get the right column width.

e.g:

**Comment by huyphams** [comment]
Yep, the last piece is column sizing which based on the resulting content but as the explanation in the issue: https://github.com/TablePlus/TablePlus/issues/1046
I will come back when I figure out the way to optimize it.

**Comment by huyphams** [comment]
I just released the beta 2017 which includes these fixes. Let me know if you're still seeing it.
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
