### ISSUE TITLE
Query Editor Performance

### ISSUE THREAD

**Issue by davidharrison92** [TablePlus/TablePlus#902]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MS SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

1.2 (182)

3. The steps to reproduce this issue:

Typing queries, creating procedures, views, etc. is incredibly slow (1 second for each character to appear). It appears to be a little overzealous with auto-complete suggestions. This is making the app almost unusable. 

(The database I'm running against is large, it's a Dynamics GP 2015 install, with 10,000s of database objects).

**Comment by huyphams** [comment]
Hi @davidharrison92 this is one of the know issues, we will optimize it on the future releases.
You can turn off this feature as a temporary solution. 
<img width="533" alt="screen shot 2019-01-21 at 5 22 35 pm" src="https://user-images.githubusercontent.com/3654622/51468289-289f9d00-1da1-11e9-8b9e-c308452f706f.png">

**Comment by davidharrison92** [comment]
> Hi @davidharrison92 this is one of the know issues, we will optimize it on the future releases.
> You can turn off this feature as a temporary solution.
> <img alt="screen shot 2019-01-21 at 5 22 35 pm" width="533" src="https://user-images.githubusercontent.com/3654622/51468289-289f9d00-1da1-11e9-8b9e-c308452f706f.png">

@huyphams , this option isn't available when editing a view (clicking Structure)

![screenshot 2019-01-21 at 10 33 23](https://user-images.githubusercontent.com/3440843/51468939-ff164f80-1d67-11e9-92e4-bae6cb008022.png)

**Comment by huyphams** [comment]
Hi thanks, @davidharrison92 for the suggestion. If you turn off that option on query editor, it will apply globally. I know it doesn't make sense. We should put it on preferences.

**Comment by huyphams** [comment]
THe newest release 382 should fix this issue even the option Enable Autocompletion > Table is turned on. Please let me know if you are still seeing the issue.
