### ISSUE TITLE
Latest build broke index manager in latest postgres

### ISSUE THREAD

**Issue by paulmillr** [TablePlus/TablePlus#904]
When I click Add new Index, nothing happens. It adds query to the "list" but there is no way to edit it.

**Comment by huyphams** [comment]
Hi @paulmillr thanks for the feedback but can I ask, which driver are you using? I'm using PostgreSQL and everything is fine. See my gif.
![2019-01-22 01 32 19](https://user-images.githubusercontent.com/3654622/51492792-98377b80-1de5-11e9-8128-a99e2a40dca7.gif)

**Comment by paulmillr** [comment]
1. Open Structure, you'll see index area.
2. Decrease window height, make the window small.
3. Increase window height back — index area would stay hidden. This would happen until software is restarted.

**Comment by huyphams** [comment]
Thanks, @paulmillr for the response but did you hover the mouse over the pane and drag it up?
