### ISSUE TITLE
The tables cannot be displayed immediately after the table is created

### ISSUE THREAD

**Issue by smxknife** [TablePlus/TablePlus#907]
The tables cannot be displayed immediately after the table is created！！！！

I need to reopen the software!!!!

**Comment by smxknife** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi,
        I know this , but I feel this is very strange，why i create a table by the create button , it can show immediately
    
        
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                smxknife
                            
                    
                        
                            
                                    smxknife@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 01/22/2019 16:26，Huy Pham<notifications@github.com> wrote： 


Hi @smxknife you only need to press. Command + R
If you create a table via GUI it would be displayed immediately. I guess that you create it via SQL Editor. Currently, TablePlus will not analyze user statement to detect create table statement.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by huyphams** [comment]
Because TablePlus knows that you're creating a table. if you run by query Editor, it can be whatever. 
It can be a select statement, it can be a delete statement, it can be a create statement.
Force reload everytime user run statements is not a good idea.

I know that there are some client do this, they use heuristic to detect the current statement is  
 `a create statement` but currently, we don't.

**Comment by smxknife** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Do you have any plane to add this function?In my view, cmd + R, this takes me one step further. There may be some risks for newcomers

**Comment by huyphams** [comment]
You can do it by using TablePlus GUI for creating Table/View @smxknife
