### ISSUE TITLE
Manage user access per-database

### ISSUE THREAD

**Issue by joshbrw** [TablePlus/TablePlus#908]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
182

3. The steps to reproduce this issue:
* Connect to server
* Go to User Management
* Add a user
* You can only assign global privileges - not per-database privileges as per the likes of Sequel Pro.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks @joshbrw we will improve this feature 👍

**Comment by stefanbauer** [comment]
+1 :)

**Comment by huyphams** [comment]
it's supported on build 200! thanks all.

**Comment by joshbrw** [comment]
Great - thanks @huyphams!
