### ISSUE TITLE
Maintain table selection after collapsing "Tables" list.

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#910]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
182

3. The steps to reproduce this issue:
- select table
- collapse "Tables"
- reopen "Tables"

The selected table is not selected anymore.
This is a slight variation on #606.

**Comment by huyphams** [comment]
Fixed, it will be included in the next update. Thanks.
Hotpach: https://www.dropbox.com/scl/fi/jqjjqi6y4qlua49l07wb8/TablePlus.dmg?rlkey=kvh9my6jx330ydj464edyyuad&dl=0
