### ISSUE TITLE
Cannot resize main window if sidebars turned off

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#911]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
182

3. The steps to reproduce this issue:

- turn off left/right sidebars
- try resize main window on left/right side

It's not possible to resize window, dragging the mouse turns on sidebars...
This is not the case with the bottom log window btw.

**Comment by huyphams** [comment]
Actually, I can but it's a bit harder 😄 btw, you should resize by hovering the mouse at the corners
![2019-01-22 19 56 42](https://user-images.githubusercontent.com/3654622/51537024-f31db100-1e7f-11e9-922d-77a6355b3245.gif)

**Comment by minusf** [comment]
ah yes, it is possible with some pixel surgery :}
i think resizing is more useful than turning on the sidebars... there is also an icon for that.
but feel free to close if you are happy with current state.
thank you.

**Comment by huyphams** [comment]
Thanks, so I will close this issue for now because it is the default behavior of native components.

**Comment by christoph-kluge** [comment]
@huyphams I stumbled across the same issue. As soon as your turn of the left/right sidebar or bottom bar -> You have to do sime pixel-based mouse-movements to get the right "resize" icon.

Is it possible to unmount the sidebar/bottom-bar when they are off? In that case they wouldn't add their sidebar drag-and-drop handles.
