### ISSUE TITLE
Highlighted error in SQL Query unreadable

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#912]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
182

3. The steps to reproduce this issue:

- have a query with an error:

<img width="162" alt="screenshot 2019-01-22 at 14 38 07" src="https://user-images.githubusercontent.com/3632883/51539200-b50a9800-1e53-11e9-89f1-20b6e3e2aca4.png">

red on red is not readable.

**Comment by huyphams** [comment]
Thanks @minusf I've fixed it.
