### ISSUE TITLE
TablePlus crashes while editing a function.

### ISSUE THREAD

**Issue by jonlorusso** [TablePlus/TablePlus#915]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 10.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Version 1.1 (176)

3. The steps to reproduce this issue:

  a. Open a function editor. 
  b. Position the cursor somewhere in the text of the function.
  c. Hold down the shift key. While holding the shift key, press option and left arrow.

**Comment by huyphams** [comment]
I think this bug is fixed on the new update 190, could you please check it? feel free to let me know if it's still happening and I will reopen this issue.
