### ISSUE TITLE
Table Plus appears to swallow MySQL errors

### ISSUE THREAD

**Issue by chrisdeeming** [TablePlus/TablePlus#916]
Note, this appears as though it could be a regression. See #817.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 182

3. The steps to reproduce this issue:
* Open any database
* Open SQL Query
* Type the following query and hit Run Current:
```sql
SELECT CAST(0 AS UNSIGNED) - 1
```
The list of rows is shown with an empty result set. Clicking "Show message" is empty.

Expected behaviour:

![image](https://user-images.githubusercontent.com/2158514/51603416-aa0e4100-1f01-11e9-84da-5b7ed30ebc6d.png)

Actual behaviour:

![image](https://user-images.githubusercontent.com/2158514/51603471-cd38f080-1f01-11e9-871b-5d1e346df3a8.png)

![image](https://user-images.githubusercontent.com/2158514/51603481-d4f89500-1f01-11e9-9889-e89a75c7aefd.png)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, it is fixed now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feedback.
