### ISSUE TITLE
Copy Rows As - SQL Insert Statement messes up values

### ISSUE THREAD

**Issue by maximbashevoy** [TablePlus/TablePlus#918]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.5, for the table in question: ENGINE=MyISAM, CHARSET=latin1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

182, MacOS 10.14.2 (via SetApp)

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

Right click on a row in a table, Copy Rows As -> SQL Insert Statement, expect:

```sql
INSERT INTO `settings` (`name`, 
`user_id`,
`priority`,
`value`,
`client_type`,
`group_name`) VALUES (
'mgt_allow_other_reports', 
'test1', 
'500', 
'1', '', '');
```

instead get:

```sql
INSERT INTO `settings` (`name`, 
`user_id`,
`priority`,
`value`,
`client_type`,
`group_name`) VALUES (
X'6d67745f616c6c6f775f6f746865725f7265706f727473', 
X'7465737431', 
'500', 
X'31', X'', X'');
```

It's been like that for good several weeks, maybe a couple of months.

**Comment by huyphams** [comment]
TablePlus converts it to binary because some of the users are using binary as a primary or foreign key. But it only affects char(length) data type.
Example:
```
CREATE TABLE `examples` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `chars` char(10) NOT NULL,
  `varchars` varchar(256) NOT NULL,
  `texts` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
);
```
will produce
```
INSERT INTO `untitled_table_5` (`id`, `chars`, `varchars`, `texts`) VALUES ('1', X'73616d706c65', 'sample', 'sample');
```

**Comment by maximbashevoy** [comment]
Great, thank you for quick reply! It used to work very well in the past, part of the reason why I switched. Any chance to have a "Plain text" option in addition to binary? Thx

**Comment by huyphams** [comment]
I updated my comment above, it's possible! and we will improve it. Currently, it works correctly but of course, ugly and unreadable.

**Comment by huyphams** [comment]
Hi, I've improved TablePlus, this build should sort out the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if you're still seeing it.
Thanks
