### ISSUE TITLE
Windows - Table data view left and right arrows not working.

### ISSUE THREAD

**Issue by moxplod** [TablePlus/TablePlus#919]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MSSQL express latest

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows 46

3. The steps to reproduce this issue:
Press on left or right arrow keys they refresh the data grid back to the first page always. Not sure the intent behind this, looks like a grid pager but its not working.

Noted: If the bug is related to data, please attach an example SQL data.

![image](https://user-images.githubusercontent.com/4554395/51627744-f05ea280-1ef7-11e9-976b-58ac6767422d.png)

**Comment by huyphams** [comment]
it should work now, please let me know if you're still seeing the issue.
