### ISSUE TITLE
Cannot run any queries with new build

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#92]
With the new build, build 66 I cannot run a single query on any database.  Major malfunction I will need to use older version for now.

For every query it says "executing 0/1 queries" indefinitely, which causes the application to be non-functional....

Also I do not think the Silent - Alert - Safe mode should apply to running queries.  If I am in Alert mode I get a warning before I send every query, but it says this only applies to committing changes, not executing queries.

This is the 2nd or 3rd time the entire app has lost functionality after an update...    :(

**Comment by huyphams** [comment]
Hi @brian-crane, if you are on `warning mode`, that mean you should confirm whatever you send command to sever (include queries in SQL Query tab). I will update the title in next build, but warning/safe mode is for production to prevent mistakes.

**Comment by huyphams** [comment]
About the bug: `For every query it says "executing 0/1 queries" indefinitely` I'm not sure what happened, can you please provide me more information?

**Comment by brian-crane** [comment]
Thanks for quick reply like always Huy :) Yes even with it in Silent mode i was having this issue.  It is probably a quick fix!

get good rest,
-Brian

**Comment by huyphams** [comment]
I will post the release candidate on github issues, so everybody can test new build before it released. And you never lost functionality after update 😁
