### ISSUE TITLE
uuid/jsonb fields always create horizontal scroller in sql results table

### ISSUE THREAD

**Issue by minusf** [TablePlus/TablePlus#921]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 11.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
182

3. The steps to reproduce this issue:

- have a table with uuid and/or jsonb field
- execute a query
- no matter how wide the main windows is, the presence of these fields will always create a horizontal scroller for the output table.

the built-in width of the uuid field is a bit too wide i think.

**Comment by minusf** [comment]
i just noticed that double clicking on the column bars gives the same width to every column type..

i also noticed that when there are many more columns, the widths are distributed differently.

but the bug is still there in the sense, that if there is for example only 2 columns: uuid, jsonb, the result table for this will always create a horizontal scrollbar.

**Comment by huyphams** [comment]
I think it's fixed now, could you please try the build 282 and see how's it going? Thank you!
