### ISSUE TITLE
Feature Request: UI polish - Postico-like foreign key preview

### ISSUE THREAD

**Issue by jhartman86** [TablePlus/TablePlus#923]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
CockroachDB 2.1.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
182

3. The steps to reproduce this issue:
This is just a "nice to have" feature that Postico provides, and wanted to put it on the radar for down the line: when clicking the foreign-key icon, a preview window (really a small, fully functional inline editor window) pops up showing the table and the foreign-key-linked record. Its really handy, and would be a great addition to TablePlus someday. Thanks for the great work so far guys.

**Example:**
![postico](https://user-images.githubusercontent.com/725280/51730448-c8c12480-2034-11e9-8e49-ca8dcc5bac07.gif)

**Comment by huyphams** [comment]
The current version has that feature but a little bit different UI/UX. it will open a new tab instead of show a popup. Maybe I can add it into a quick look preview.

**Comment by davydkov** [comment]
@huyphams please, add the inline preview of the FK record.
Current "another tab" UX is not great for investigating (switching between tabs back-and-forth) 😭

**Comment by huyphams** [comment]
Hey, it is my current task. You will see it soon.

**Comment by huyphams** [comment]
It's supported now (command + return or middle mouse, open quick look), you can download the patch [here](https://www.dropbox.com/s/nlj228p2qaul3v7/TablePlus.dmg?dl=0) or wait for the next update.
![2020-06-01 20 01 23](https://user-images.githubusercontent.com/3654622/83411616-ce0d5b00-a442-11ea-8e9f-d64804f089af.gif)
