### ISSUE TITLE
SQLServer paging bug

### ISSUE THREAD

**Issue by ydq** [TablePlus/TablePlus#925]
1. Which driver are you using and version of it:**SQL Server 2008**

2. Which TablePlus build number are you using:**Build 185 (MacOS)**

3. The steps to reproduce this issue:
![tableplus](https://user-images.githubusercontent.com/8097340/51795601-45185b00-2221-11e9-840b-a4fb10257929.gif)

**Comment by huyphams** [comment]
Thanks @ydq but your database version is too old (10 years ago), Microsoft just added support for paging recently, so if you're using Azure or SQL Server 2017, it will be supported.

**Comment by ydq** [comment]
> Thanks @ydq but your database version is too old (10 years ago), Microsoft just added support for paging recently, so if you're using Azure or SQL Server 2017, it will be supported.

HaHa.. I get it now. Thanks for your reply . And thanks for your TablePlus. It's very nice database manage tool~

**Comment by bwat47** [comment]
@huyphams 

I'm seeing this issue even with a SQL express 2017 instance
