### ISSUE TITLE
MySQL adding auto_increment issue

### ISSUE THREAD

**Issue by joshcalloway** [TablePlus/TablePlus#927]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 8.0.12
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 182
3. The steps to reproduce this issue:
Insert new column into existing table with data_type INT and column_default auto_increment

It seems to add the keyword DEFAULT to the sql statement.
<img width="493" alt="screenshot 2019-01-28 09 05 58" src="https://user-images.githubusercontent.com/16376397/51841191-0693a680-22dc-11e9-8cb0-d4bb65dfeda7.png">
<img width="383" alt="screenshot 2019-01-28 09 06 22" src="https://user-images.githubusercontent.com/16376397/51841198-0a272d80-22dc-11e9-921f-493d35942632.png">

**Comment by huyphams** [comment]
Hi @joshcalloway it was fixed on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by joshcalloway** [comment]
Confirmed.  Thanks
