### ISSUE TITLE
Question: Is it possible to export table structure?

### ISSUE THREAD

**Issue by PVGrad** [TablePlus/TablePlus#93]
I didn't find in UI such feature - only data export :(
If TablePlus doesn't have this feature, i think - it's a **must have**

Thanks.

**Comment by huyphams** [comment]
Hi @PVGrad 
This feature can be done easy in MySQL, I will include a menu to copy table struct. But PostgreSQL native lib didn't support. The only way is export data as struct.

I see pgAdmin can show table structure statements and it's open source. I will take a look.

Huy.

**Comment by huyphams** [comment]
I checked code pgadmin and they have their own reverse function, it's pretty complex
`https://github.com/postgres/pgadmin4/blob/8d248dab4c09a5c637569e3b4fb166c02ebff17a/web/pgadmin/browser/server_groups/servers/databases/schemas/tables/utils.py#L817`

**Comment by huyphams** [comment]
Hi @PVGrad 
I decided to develop this feature. This feature will come with data transfer. That means you can transfer data between 2 data cents very easy. There are some options allow you only fetch top of table (in case table has a million of rows).

- Huy.

**Comment by huyphams** [comment]
Hey @PVGrad I just have done this feature on MySQL. PostgreSQL and other drivers are in progress.

1. Install newest TablePlus: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
2. Press command + L and install table dump plugin.
3. Right click on left panel: there is new menu dump item > copy creation.

If you are interested in this feature, you can take a look at this repo:  https://github.com/TablePlus/tabledump

**Comment by leeola** [comment]
Thanks for this feature!

**Comment by huyphams** [comment]
This feature will be released as a part of the build 101. You can try it here, please let me know your thoughts: 

https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

- TablePlus only supports extract creation for a single table, if you want to export all the tables at the same time I think you should use pg_dump.

I closed it because It's duplicated with https://github.com/TablePlus/TablePlus/issues/257

**Comment by johndatserakis** [comment]
@huyphams I just tried this and it worked great! Nice job will all this.

**Comment by jakequade** [comment]
Hi there - dropbox link is broken. Can you please post a preview link or explainer? :) thank you.

**Comment by huyphams** [comment]
Hi this feature is released 2 years ago. It should be included in the production now @jakequade

**Comment by lcsqlpete** [comment]
Late to this but I need to export a table structure in JSON format.  I followed the instructions to install the plugin but can find nowhere to run it, nor can I find anything that is part of the actual app and the docs are silent on it.  Does this feature exist?
