### ISSUE TITLE
Can't connect to Redis after recent update

### ISSUE THREAD

**Issue by randallmlough** [TablePlus/TablePlus#930]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Redis 3.2.12 (Heroku's managed Redis)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
188

3. The steps to reproduce this issue:
Grab any heroku redis URL (or parse credentials from it) and attempt to connect. Connection fails.

Prior to the most recent update build 188, I was able to connect to my Heroku Redis DB without any issues. Since updating I can no longer connect. I even created a random project and attached a fresh redis instance and tried to create a new connection. It did not work.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by randallmlough** [comment]
It seems like tableplus is having trouble if Redis requires a password to connect. I switched my local redis instance to require a password and tableplus is failing to connect to this instance now as well

**Comment by conspireagency** [comment]
@huyphams was the solution to this added to future versions?  I'm on Build 468 (full license) and I get an error trying to connect to any Heroku Redis instance I've tried.

**Comment by huyphams** [comment]
@conspireagency I think your issue is not related to this. Please post the error message or any details. Please also try with other clients to confirm your credentials.

**Comment by conspireagency** [comment]
@huyphams the error is "Connection reset by peer".  

To reproduce grab any Redis datastore credentials URI from Heroku, select Redis in TablePlus and hit import by URL.

I tried 3 different Redis stores in different projects under my Heroku account and none of them worked (despite functioning properly for the applications which use them).

Thanks for looking into this!

![Screen Shot 2022-11-21 at 6 26 14 PM](https://user-images.githubusercontent.com/29992361/203203358-e519be13-97b7-4bdc-bdc5-ccd5d6d0c258.png)
![Screen Shot 2022-11-21 at 6 23 25 PM](https://user-images.githubusercontent.com/29992361/203203362-de59aa4e-7360-45d4-9f08-a97c9503db94.png)

**Comment by huyphams** [comment]
Does it work with any other Redis clients?  The connection is exposed without SSL, which I think is a bit insecure.

**Comment by conspireagency** [comment]
@huyphams so I was able to get it to connect setting SSL mode to VERIFY_NONE.  Not sure the implications/best practice here?  Heroku doesn't seem to give any access to a cert etc.

Heroku is a pretty widely used service and Table Plus is a really great tool - so I'm sure I won't be the only one to run into this =)

**Comment by huyphams** [comment]
Does it work with any other Redis clients or does only TablePlus fail?

**Comment by conspireagency** [comment]
@huyphams I can try with another Redis client if you'd care to recommend one as I'm not currently using another.

**Comment by conspireagency** [comment]
From what I’m reading verify none is an insecure connectionSSL mode flags - verification of certificates: is it safe to use :none?stackoverflow.comOn Nov 21, 2022, at 7:10 PM, Henry Pham ***@***.***> wrote:﻿
I'm glad that it works. Basically, we should use SSL encryption when making a connection over the internet to prevent a MitM (man in the middle) attack.

**Comment by huyphams** [comment]
It would not be a problem if you know the destination is a trusted source (which is Heroku).

**Comment by samcdona** [comment]
I have free version of TablePlus 5.4.0 (build 234) and don't see an option to specify CA cert in SSL mode for Redis Connection.  Is it disabled for latest free version of TablePlus?

![TablePlus_v5 4 0-NoSSLCertOption](https://github.com/TablePlus/TablePlus/assets/57971101/e4753a8c-6d52-48d0-821e-ad17518f63bf)
