### ISSUE TITLE
Error dialog when import fails

### ISSUE THREAD

**Issue by sietzekeuning** [TablePlus/TablePlus#933]
I am using MySql and the latest version of TablePlus 1.4 (188). When I import an sql statement with a JSON field type, my production MySql doesn't accept it. But when importing the full statement of all tables, only the first 2 tables are imported and no error is shown. 

Could you please show an error dialog when an import fails?

**Comment by huyphams** [comment]
it should report the error, let me check it @sietzekeuning thanks for the feedback.

**Comment by huyphams** [comment]
Hi @sietzekeuning This is a critical bug, I fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Bug details:
When import, MySQL execute queries with a chunk size and the server return one by one but TablePlus skip the last one. that why the error wasn't reported.
Thanks again!
