### ISSUE TITLE
Insertion Points for Favorite Queries

### ISSUE THREAD

**Issue by vatthikorn** [TablePlus/TablePlus#934]
As a feature request, I'd like the ability to specify cursor insertion points in my favorite queries. This would work in such a way that when I type out my favorite query using a shortcut (e.g "order" + `<tab>`), the cursor would be placed at a certain location in the queries instead of at the end.

A nice-to-have for this is also the ability to specify multiple insertion points in the favorite, and allowing for tabbing to navigate down those points.

Please take a look at how this is done in [Sequel Pro](https://sequelpro.com/docs/ref/core-features/query-favourites)

**Comment by huyphams** [comment]
Thanks @zackva I will check it and reply to you later.

**Comment by zackva** [comment]
Thank you for a quick response @huyphams.

Here is a quick example of this in action: 
![example](https://user-images.githubusercontent.com/5591523/51942498-37133780-23e5-11e9-9047-04b843df1c70.gif)

Thanks again for all you do with this app! By far my favorite MySQL client that I've used on macOS

**Comment by huyphams** [comment]
TablePlus has a very similar function called variable, you guy can turn it on in the settings,

![2019-10-10 21 49 49](https://user-images.githubusercontent.com/3654622/66616617-f42a7600-eba7-11e9-998e-d9d437313c42.gif)

<img width="643" alt="Screen Shot 2019-10-10 at 9 44 23 PM" src="https://user-images.githubusercontent.com/3654622/66616467-3e5f2780-eba7-11e9-956c-0ab793800011.png">

 from the new version, you will be able to custom the regex (such as `?` or `%variables%` or `${variables}` ) the current default variable is `:variable`

![2019-10-10 21 47 45](https://user-images.githubusercontent.com/3654622/66616558-a1e95500-eba7-11e9-8458-db7d997df537.gif)

**Comment by huyphams** [comment]
By doing this way, you can also reuse the variables.

**Comment by lasergoat** [comment]
@huyphams thank you. however, I saw the enable query params option, but it wasn't embedded into a sub menu. Also, I'm not sure how you are pulling up the variable editor drop down.

**Comment by huyphams** [comment]
Could you please try again with the beta build (it can self-update to the official build, so you can replace the current TablePlus) https://www.dropbox.com/s/4033rlop6eov1ur/TablePlus.dmg?dl=0
Thanks @lasergoat

**Comment by lasergoat** [comment]
@huyphams I downloaded the beta and found the feature, thank you. So, in my favorites, I added a variable like :id but in your gif it's hard to see how you are pulling up the menu. I select my favorite name out of the auto complete, but then, I'm not sure how to get the variable editor to show up. Thanks
<img width="611" alt="Screen Shot 2019-10-14 at 5 10 45 PM" src="https://user-images.githubusercontent.com/15964/66786327-964aa680-eea5-11e9-83bd-cd3dafb057d9.png">

**Comment by huyphams** [comment]
It will show up right after you execute the query (command + Return or click the Run current button).

**Comment by lasergoat** [comment]
ah i see now. ok thank you. next question, for strings, do I need to enter the quotes as part of the variable, or do I need to choose a non-default regex for the variables?

**Comment by huyphams** [comment]
TablePlus variable has some rules.
1. Variables must be placed outside a string.
2. All variables will be replaced with the value in the variable table.

For example
SELECT * FROM users where email = ":email" => will not work.
You should do something like this:
SELECT * FROM users where email = :email => and enter the "someuser@somedoimain.com" (include the quote).

**Comment by lasergoat** [comment]
@huyphams i see. is there a way to not type the quotes everytime?

**Comment by huyphams** [comment]
No, it's not (because there is no way to know it was a string, a number, a hex etc...), however, TablePlus saves the old value in the table, so you do need to type it everytime.

**Comment by huyphams** [comment]
Hi @lasergoat 
We added this option, I think it would help (next release):
<img width="610" alt="CleanShot 2022-09-26 at 11 35 22@2x" src="https://user-images.githubusercontent.com/3654622/192194647-59789230-7de8-4005-af21-a08ef88f53cc.png">
