### ISSUE TITLE
Hide partition tables by default

### ISSUE THREAD

**Issue by tmeisel** [TablePlus/TablePlus#935]
Hi there,
I'm currently using TablePlus `v1.4 (188)` for PostgreSQL. One feature I would like to suggest are collapsible tables when using partitioning. Right now it looks like this:

![like this](https://user-images.githubusercontent.com/1716371/51909820-d62c3500-23cd-11e9-9403-af12fc8dec12.png)

Which is only the beginning of our partitioned log tables. We create a new partition every week and keep them for some time. Would nice to only show the parent table `request_log` and hide everything inheriting by default.

**Comment by huyphams** [comment]
Hi @tmeisel the partitioned log tables were created automatically or by your application?

**Comment by tmeisel** [comment]
Hi @huyphams, our application creates these tables according to https://www.postgresql.org/docs/9.6/ddl-partitioning.html 

Cheers

**Comment by anishpateluk** [comment]
Would it be possible to allow tableplus to use a full regex so we can use search to exclude tables ending with a number such as this `.*(?<!\d+)$`?

**Comment by thecatontheflat** [comment]
Can we please please have this? This is how it looks like for me presently :D 

![Screenshot 2021-07-29 at 16 42 48](https://user-images.githubusercontent.com/727581/127512556-899dfae1-bf43-475a-bf84-125a62f22e44.jpg)

**Comment by huyphams** [comment]
We're working on it 👍

**Comment by ccyrille** [comment]
Hello @huyphams, any on this feature?

**Comment by huyphams** [comment]
Update: we're working on this feature, along with many other group rules, please wait for the next update!

(You can group table by rules, not only partitioned tables - which have the same prefix)

![2022-09-03 16 19 06](https://user-images.githubusercontent.com/3654622/188264627-d51b530e-0058-4bfa-bc82-1469832b138c.gif)

**Comment by huyphams** [comment]
Hi guys, if you have a chance, please try this patch: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
It supports group items with rules.

If you have time, please give me some feedback.

**Comment by thecatontheflat** [comment]
Exciting!

@huyphams If there's a Windows test build, I could give it a try!

**Comment by jamesdh** [comment]
@huyphams just tested this and works great! Time to become a paying customer I guess!

**Comment by Oliver-Saer** [comment]
@huyphams 

It's not clear how this can be used to filter out the partitioned tables.  Is it possible that you could add a filter option for this?

**Comment by huyphams** [comment]
Hi @Oliver-Saer I guess we can create a group with a filter "Has prefix" because I think all the partitioned tables have the same prefix?

**Comment by Oliver-Saer** [comment]
@huyphams

Yes, that would work.  However, that requires a fair amount of configuration on the part of the user.  Especially true in my case, where there are several schemas, each with several different tables being partitioned.

It would be ideal if there were options for 'Is Partition' & 'Is Not Partition'.  But this is maybe a future development consideration - the methodology you've described works fine!

**Comment by huyphams** [comment]
Many users have tables with the same prefix and we don't want TablePlus to group them wrongly.

Of course, we can check the table info by doing an extra query to know where are partitioned, but maintaining database features is harder than TablePlus features, and much more complex.  Creating a group is only one time, so I think we can live with it.

Adding a filter  'Is Partition' & 'Is Not Partition' is not a good idea, because one group should only contain 1 type of partitioned table, so "Is Partition" could group all the partitioned tables which is clumsy.
