### ISSUE TITLE
Issues when exporting/importing enum types

### ISSUE THREAD

**Issue by Sharcoux** [TablePlus/TablePlus#936]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

10.1

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

188

3. The steps to reproduce this issue:

1) Create a database declaring enum types

`CREATE TYPE enum_Appointments_appointeeAnswer AS ENUM ('pending', 'accepted', 'refused');`

2) Create a table with a column extending the enum type with a default value

```
CREATE TABLE "public"."Appointments" (
    "id" uuid NOT NULL,
    "bookable" varchar(255),
    "bookableId" uuid NOT NULL,
    "appointeeId" uuid,
    "appointeeAnswer" enum_Appointments_appointeeAnswer DEFAULT 'pending'::"enum_Appointments_appointeeAnswer",
    "createdAt" timestamptz NOT NULL,
    "updatedAt" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
```

3) Export the data and try to import it in a new database

**First error**

```
ERROR:  type "enum_appointments_appointeeanswer" does not exist
LINE 10:     "appointeeAnswer" enum_Appointments_appointeeAnswer DEFA...
```

4) Execute manually this SQL into the new database and try to import again

`CREATE TYPE enum_Appointments_appointeeAnswer AS ENUM ('pending', 'accepted', 'refused');`

**Second error**

```
ERROR:  column "appointeeAnswer" is of type enum_appointments_appointeeanswer but default expression is of type "enum_Appointments_appointeeAnswer"
HINT:  You will need to rewrite or cast the expression.
```

**Comment by Sharcoux** [comment]
Ok. I could solve the problem manually:

I just needed to edit the dump and add for every enum:

`CREATE TYPE "enum_Appointments_appointeeAnswer" AS ENUM ('pending', 'accepted', 'refused');`

(Notice the double quote needed for case preservation)

I also had to edit every column using this enum by adding double quotes around it:

```
CREATE TABLE "public"."Appointments" (
    "id" uuid NOT NULL,
    ...
    "appointeeAnswer" "enum_Appointments_appointeeAnswer" DEFAULT  'pending'::"enum_Appointments_appointeeAnswer",
...
```

**Comment by huyphams** [comment]
Hi @Sharcoux it's supported on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feedback.
