### ISSUE TITLE
Text and Table Resize

### ISSUE THREAD

**Issue by SRserves85** [TablePlus/TablePlus#938]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
- Postgres
- sqlite
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
- 188
3. The steps to reproduce this issue:
- There is absolutely no issue.

My company and colleagues love your product, but I wanted to open an enhancement ticket. I would love the ability to resize text and tables. Some of us currently find current the default text size to be too small to use the tool for long periods of time.

If you add this, we all work for US Foods, and you could get a lot of new license purchases!!

Thanks for making a great product.

**Comment by huyphams** [comment]
Hi @SRserves85 thanks for the suggestion, it's already reported here: https://github.com/TablePlus/TablePlus/issues/905
and yes, we're going to add this option.
