### ISSUE TITLE
Build 67 beta build

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#94]
Hi all,
Please come and test build 67 before it released, your feedback help us improve TablePlus faster and better.

Link download: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0
Changelogs: https://github.com/TablePlus/TablePlus/projects/1?

If you found a bug, please report it to me (include environments, database info... what is need to reproduce the bug).

Thank you,
Huy.

**Comment by karimelm** [comment]
Switching databases (postgresql 10) produces a connection error for me: 
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

**Comment by huyphams** [comment]
Hi @karimelm, could you hit the test button when using ssh? if it's all green that means the connection was setup correctly. Like this.
![screen shot 2017-10-26 at 8 54 01 pm](https://user-images.githubusercontent.com/3654622/32056804-cf0a81a8-ba8f-11e7-933b-b27b9719ea22.png)

**Comment by karimelm** [comment]
It all tests fine prior to connecting. It also connects properly at first but when i switch database the connection drops. The change I can observe (looking at the connection status symbols in the brief moment the loading screen is displayed) is that while connected through an ssh tunnel, switching database also reconnects to the host. This doesnt seem to be the case if not connecting over ssh.

**Comment by huyphams** [comment]
Thanks, I can reproduce the bug now 👍

**Comment by huyphams** [comment]
Hi @karimelm the bug was fixed 👍 thanks
