### ISSUE TITLE
Beautify doesn't respect "Tabs vs Spaces" preference

### ISSUE THREAD

**Issue by chrisdeeming** [TablePlus/TablePlus#941]
Under Preferences > Behaviors I have `Indent with` set to `Tabs` instead of `Spaces`.

Ideally, the Beautify feature should respect that. Currently it will indent with spaces, regardless of the preference.

Thanks :)

**Comment by huyphams** [comment]
I've implemented it on this build, could you please give it a try?
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for feedback.

**Comment by chrisdeeming** [comment]
That was quick which is very appreciated.

However, it inserts multiple tabs. e.g. if it's tab size 4, then it will insert 4 tabs. It also uses tabs where spaces are more appropriate (e.g. `col1    =    'thing'` instead of `col1 = 'thing'`)

Uglified:
```sql
SELECT col1,col2 FROM table1 WHERE col1='thing' ORDER BY col1 DESC LIMIT 10
```

Beautified:
```sql
SELECT
				col1,
				col2
FROM
				table1
WHERE
				col1	=	'thing'
ORDER	BY
				col1	DESC
LIMIT	10
```

Expected:

```sql
SELECT
	col1,
	col2
FROM
	table1
WHERE
	col1 = 'thing'
ORDER BY
	col1 DESC
LIMIT 10
```

**Comment by huyphams** [comment]
Hi, thanks for the feedback, this build should fix the issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
