### ISSUE TITLE
[Feature Request] Display notification when backup/restore is finished 

### ISSUE THREAD

**Issue by dimsav** [TablePlus/TablePlus#942]
It would be very helpful to have a notification when the backup/restoring of a database ends.

While waiting for TablePlus to complete the restore, I am doing other tasks and it is easy to miss it when the restore is finished unless I constantly look at the tiny text on the popped up window.

I'm using v1.5 (190) with MySQL 5.7.

**Comment by huyphams** [comment]
Hi @dimsav great suggestion, I will add it 👍
