### ISSUE TITLE
Pretty JSON on the right sidebar escape '/' chars

### ISSUE THREAD

**Issue by ProgMaq** [TablePlus/TablePlus#943]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 10.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
190

3. The steps to reproduce this issue:

Put this JSON in a JSONB column:
{"type": "object", "$schema": "http://json-schema.org/draft-07/schema#"}

Then, press PRETTY button and return this:
{
  "type" : "object",
  "$schema" : "http:\\/\\/json-schema.org\\/draft-07\\/schema#"
}

**Comment by huyphams** [comment]
Hmm, I got it, we should not escape character
