### ISSUE TITLE
Connected but nothing is displayed

### ISSUE THREAD

**Issue by doughng** [TablePlus/TablePlus#944]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.18

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 190

3. The steps to reproduce this issue: 
Created connection, Tested connection, All green. Clicked Connect. Nothing shows.
Repeated steps for remote MySQL, Cassandra. Same result. 

- FYI, All connections; Local mysql, remote mysql, Cassandra  were working until couple of days.
- Tableplus trial version

**Comment by huyphams** [comment]
I don't understand "nothing shows"? did you mean nothing like this? If yes, please toggle the button on the top right, it should be back.
<img width="1401" alt="screen shot 2019-02-04 at 9 22 35 pm" src="https://user-images.githubusercontent.com/3654622/52213946-050d4400-28c3-11e9-9258-62a4c59f2fb5.png">

**Comment by doughng** [comment]
Yes, that works! thank you

**Comment by huyphams** [comment]
Hmm, so I think we can close this issue, right? 😄

**Comment by doughng** [comment]
yes!
