### ISSUE TITLE
[Feature Request] Naming New SQLite DB

### ISSUE THREAD

**Issue by bt** [TablePlus/TablePlus#947]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 190

3. The steps to reproduce this issue:

- Choose "Create a new connection...
- Choose SQLite
- Can specify an existing database but cannot name a new SQLite database (will always be called untitled.sqlite3 if choosing a directory).

Would be great if we can give a filename to the SQLite database being created!

**Comment by huyphams** [comment]
it's implemented on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks!

**Comment by chrschmitz** [comment]
I have not been able to find the option to create a new SQLite database. It seems to be well hidden. Can you give me a hint?

**Comment by huyphams** [comment]
You can do it by 2 ways:
1. Using command + K:
<img width="1477" alt="Screen Shot 2019-05-28 at 4 24 54 PM" src="https://user-images.githubusercontent.com/3654622/58467249-7ec48880-8165-11e9-855e-a37a7770018c.png">

2. Create a new connection and select a `folder`:
<img width="612" alt="select" src="https://user-images.githubusercontent.com/3654622/58467268-85eb9680-8165-11e9-8d0f-d7c79eea37ba.png">

**Comment by huyphams** [comment]
ops, it's a bug, it will show up on the next time you press command + K
