### ISSUE TITLE
[Feature request] Search in open connection

### ISSUE THREAD

**Issue by christian-kolb** [TablePlus/TablePlus#948]
It's great, that there's a shortcut to open a new connection. What would improve the speed of choosing a connection (especially if there are a lot) is if any key you type would automatically open a search which filters the existing connections by name.
It should be possible to select the filtered ones the the arrow up and down keys. And then opening the selected one with the enter key.

**Comment by huyphams** [comment]
I think we should add search field in.
1. Welcome screen.
2. Open anything.
3. Open new connection (command + shift + K)
Thanks for the suggestion.

**Comment by godbout** [comment]
+1

i've tried tableplus a couple of months ago and i'm getting serious now about it. love it so far. but i'd love it more if i could do everything from the keyboard! and yes, that definitely includes being able to select a connection from like the `goto anything` panel. also would be nice to be able to close dialogs through the keyboard. some get stuck and require a mouse click (like if can't connect to db for example).

**Comment by Vmadmax** [comment]
This would be great. We have much favourites in our list. It's so confusing to find the right connection.

**Comment by huyphams** [comment]
It will be included in the next update (Toggle with command + F).
<img width="757" alt="Screen Shot 2020-09-22 at 11 40 06 PM" src="https://user-images.githubusercontent.com/3654622/93911870-30a9a000-fd2d-11ea-83c5-ae4cd1b69df0.png">
