### ISSUE TITLE
Make force touch do quick preview

### ISSUE THREAD

**Issue by krm87** [TablePlus/TablePlus#95]
Title says it all, unless its already doing something else im not aware of.

**Comment by huyphams** [comment]
Hi @karimelm you mean `quick preview` is `quick look`?
<img width="492" alt="screen shot 2017-10-27 at 10 09 13 am" src="https://user-images.githubusercontent.com/3654622/32086373-e805f4ac-bafe-11e7-941e-a8e0203191b8.png">

**Comment by karimelm** [comment]
Yes

**Comment by huyphams** [comment]
Yeah, let's me try 😁

**Comment by huyphams** [comment]
Apple didn't support detect force touch by default.
I will look into this solution: [link](https://eternalstorms.wordpress.com/2015/10/24/how-to-receive-force-touch-events-from-an-nstableview/)

**Comment by karimelm** [comment]
Something you would expect to be easy, isn't ;) Thanks for looking into it though, by all means; it isn't a mission critical thing, just thought it'd be cool to have.

**Comment by huyphams** [comment]
Hi @karimelm,
There are an other solution. If you are using mouse you can press `middle mouse` to open `quick look`
Huy.

**Comment by PVGrad** [comment]
> Hi @karimelm,
> There are an other solution. If you are using mouse you can press `middle mouse` to open `quick look`
> Huy.

So, are there any other ways to open Quick look if i'm not using mouse at all and right button click and choose Quick look from menu is too unhandy?
Thanks

**Comment by huyphams** [comment]
Hi, you can open Quicklook quickly with command + enter from this build: https://www.dropbox.com/s/1m4ro31q15kcgnj/TablePlus.dmg?dl=0
