### ISSUE TITLE
CockroachDB not showing all foreign key relationships

### ISSUE THREAD

**Issue by digitalpros** [TablePlus/TablePlus#950]
1. CockroachDB CCL v2.1.4

2. Build 190

3. The steps to reproduce this issue: 
Create 3 tables. For example users, comments, posts
posts and comments both have a foreign key on a userId column
comments will show the foreign key relationships to the users table. But then when you add the foreign key to the posts table it will create it but will not show in the interface that there is a foreign key.
It will list the index that it created but not the foreign key.

if you change the column from userId to something like postCreatorId still using the users table as the foreign key it will show it in the interface. 

<img width="684" alt="screen shot 2019-02-06 at 9 40 02 pm" src="https://user-images.githubusercontent.com/13974088/52391057-b0033680-2a58-11e9-9557-eb5097b0ca30.png">

**Comment by huyphams** [comment]
Hi @digitalpros thanks for the feedback, I will check it now.

**Comment by markuswustenberg** [comment]
Also seeing this in build 194.

**Comment by markuswustenberg** [comment]
@huyphams did you get around to looking at this? :) Still seeing the bug in build 200.

**Comment by huyphams** [comment]
Hi @markuswustenberg if it’s possible, can you send me an example script where i can reproduce the issue? Thank you so much!

**Comment by markuswustenberg** [comment]
@huyphams sent, thanks.

**Comment by huyphams** [comment]
Hi @digitalpros @markuswustenberg I just updated the build with new a foreign key parser, I hope it fixes this issue: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Please let me know the result, thank you!

**Comment by digitalpros** [comment]
Yes this looks like it fixed the issue.
<img width="671" alt="Screen Shot 2019-03-14 at 10 22 52 AM" src="https://user-images.githubusercontent.com/13974088/54378304-402e3000-4644-11e9-9176-98741a96d8a8.png">

**Comment by markuswustenberg** [comment]
Works for me too! Thanks. :)
