### ISSUE TITLE
Error: no such module: FTS4

### ISSUE THREAD

**Issue by vkosmirak** [TablePlus/TablePlus#955]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
I'm opening local SQLite file (.db)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.5(190)

3. The steps to reproduce this issue:
Open table that was created with Full-Text Search
(When I try to open it with DB Browser for SQLite - opens successfully)

![screen shot 2019-02-08 at 1 16 09 pm](https://user-images.githubusercontent.com/6514929/52475288-bce07100-2ba3-11e9-94b5-f3f285beea6d.png)

Is it something I may miss while configuration, or is it not supported by TablePlus?

**Comment by huyphams** [comment]
it looks like that the current version is not supported, let me try to add it.

**Comment by huyphams** [comment]
Hi @vkosmirak I just added fts4 support on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0 let me know if it works for you.

**Comment by vkosmirak** [comment]
@huyphams Sorry for the late response.
Thanks, It's working! FTS table is successfully opened
