### ISSUE TITLE
Store password to macOS Keychain issue

### ISSUE THREAD

**Issue by mohamednagy** [TablePlus/TablePlus#956]
Version 1.5 (build 191)
TablePlus saves the passwords to KeyChain but the name is just `TablePlus`, in my case i have many connections saved, so it's really hard to determine which password related to which connection, i think it the KeyChain name should be something like a combination of the `TablePlush + connection name or host`

**Comment by huyphams** [comment]
Thanks for the suggestion but we have an easy trick, you can go to welcome screen and copy as URL, it would be included the password (if you have safe mode protected, please enable touch ID to unlock in prefs)

**Comment by MikeGarde** [comment]
I second this, I am just getting started with TablePlus and have been very impressed but I have 9 db's setup so far (and I have more to go) so easily retrieving a password is needed. But I don't want it to be too easy. Maybe a future release requires the system password (or Touch ID) to retrieve the URL as the KeyChain requires the system password. But thanks for a great product.

**Comment by huyphams** [comment]
it's already implemented @MikeGarde please turn on the safe mode (the highest level) and you can turn on the touch ID in the preference to unlock it.
<img width="940" alt="Screen Shot 2019-05-13 at 7 55 27 PM" src="https://user-images.githubusercontent.com/3654622/57623020-126c5580-75b9-11e9-8cac-1a2eac923f24.png">

**Comment by jorisatabix** [comment]
@huyphams Would it be possible to store the passwords in Keychain with a more readable name? 

![image](https://user-images.githubusercontent.com/36499489/63155988-05299180-c014-11e9-9637-14e1ad8e091b.png)


It would be nice to see the database name, so I can identify the password.

**Comment by huyphams** [comment]
Hey @jorisatabix you can copy the URL from the welcome screen to see the password.
<img width="381" alt="Screen Shot 2019-08-16 at 10 54 06 AM" src="https://user-images.githubusercontent.com/3654622/63172481-2ee2b880-c014-11e9-8158-9d558ff7f75f.png">

**Comment by coilnovasince1985** [comment]
@huyphams I got hundreds of connections so does it mean every time i need to Copy as URL now ?!
