### ISSUE TITLE
Unable to connect to database with message: "Collecting database information..."

### ISSUE THREAD

**Issue by dangson** [TablePlus/TablePlus#958]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.5 (190) on macOS 10.14.1

3. The steps to reproduce this issue:
Connect to a previously saved database. 
The loading screen shows with this message: Collecting database information...

The database does not load even after 10 minutes of waiting. The database works fine from my application and Sequel Pro. It also worked fine in TablePlus until today. I have not made any changes to my computer recently.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by pbreit** [comment]
I am experiencing this. It seems to stall on "Collecting database information..."

MacOS 10.14.5
TablePlus 2.7 (247)

It's an Oracle database which I have no trouble connecting to with Navicat or DBeaver.

**Comment by hadimazalan** [comment]
I am experiencing the same issue when connecting to Oracle Database.

MacOS 10.14.6
TablePlus 2.8.2 (257)

**Comment by hammadsaj** [comment]
I have the same problem

**Comment by mojitoming** [comment]
I have the same issue for the Oracle DB connection which I have no trouble connecting to with DataGrip.

MacOS  10.15.2
TablePlus  3.0.0(288)
JDK 11.0.5

**Comment by veics** [comment]
same issue, still
