### ISSUE TITLE
Exporting table content/data

### ISSUE THREAD

**Issue by karimelm** [TablePlus/TablePlus#96]
Hi,

When exporting table content, both json and csv options produce the same output, and its invalid csv or/and invalid json for that matter, it also wraps json in double quotes like this:

"values"
"{""x"": 

values is the column name, and the data is just dumped per row on new lines with double quotes.

**Comment by huyphams** [comment]
Hi @karimelm thanks for the feedback. Could you try the beta build? I have fix some export issues on that build and updated it 5 minute ago.

**Comment by karimelm** [comment]
Export seems to work fine now, but json field name quotes are escaped, csv looks good too, ssh connection is also fixed. Good job, ill look at the exported data more closely later on.

Ill let you know if the connection disappears from my list again. Thanks
