### ISSUE TITLE
Incorrect SQL being generated for renaming MySQL columns

### ISSUE THREAD

**Issue by ffxsam** [TablePlus/TablePlus#961]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.6.10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 190

3. The steps to reproduce this issue:

I have a table which has a `created_at` timestamp that I wanted to rename to `createdAt`. I tried, and I got an error due to invalid syntax. The SQL generated was this:

```sql
ALTER TABLE `mytable`.`tracks` CHANGE `created_at` `createdAt` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '';
```

The default value is wrong. I had set this to `NOW()`, which got changed somehow to `CURRENT_TIMESTAMP`. The correct SQL to rename this field was:

```sql
ALTER TABLE `mytable`.`tracks` CHANGE `created_at` `createdAt` timestamp NOT NULL DEFAULT NOW() COMMENT '';
```

**Comment by huyphams** [comment]
Hi @ffxsam, I fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feedback
