### ISSUE TITLE
Toggle Table data view

### ISSUE THREAD

**Issue by tarasyyyk** [TablePlus/TablePlus#963]
When working with table which have many columns it's hard to view interesting column because need to scroll horizontally a lot.
![image](https://user-images.githubusercontent.com/20100011/52638599-fb936580-2eda-11e9-8bc4-1f11d5b62d67.png)
Would be great to switch table data into "vertical" view:
![image](https://user-images.githubusercontent.com/20100011/52638677-2382c900-2edb-11e9-8bfa-b13fdca8bbc0.png)
The greatest this in this view can be sorting by column name.
I know it's hard to impletent, but this feature can be great "pro" feature.
P.S. Maybe someone suggested this idea. If so, you can freely close this issue.

**Comment by huyphams** [comment]
How about this @tarasyyyk 
<img width="1519" alt="detailpane" src="https://user-images.githubusercontent.com/3654622/52705280-1afec100-2fb5-11e9-877e-7300a5c2eaa3.png">

**Comment by tarasyyyk** [comment]
@huyphams this is what I want. Thanks.
