### ISSUE TITLE
Error: no such module: fts5

### ISSUE THREAD

**Issue by uberteck** [TablePlus/TablePlus#966]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQLite

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.5 (190)

3. The steps to reproduce this issue:
Create a FTS5 virtual table and try to open the table in TablePlus.
I get the above error when trying to open a FTS5 table.  Full text search is an optional module for SQLite and is not compiled in by default.  I noticed a similar issue a few days ago #955 for fts4 support.  fts5 is the latest version.  Please could you do whatever you did for fts4 support for the fts5 module?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
But did you check that build too? I've added FTS 3-4-5 into that build already.

**Comment by uberteck** [comment]
I did an update in the app as I thought that would pull down the latest, hadn't realised the changes in that build hadn't been merged in yet.  The build linked in the other issue works with FTS5, thanks!
