### ISSUE TITLE
[Feature Request] Cloud Syncing

### ISSUE THREAD

**Issue by drummin** [TablePlus/TablePlus#968]
I work on the same DBs on multiple computers. Would love it if the environment, favorites, or windows with queries in them could sync across devices. Over iCloud, DropBox, or your own service.

**Comment by huyphams** [comment]
Hi, We're working on the preferences that allow the user to change the data path to their Dropbox.
But you can use Dropbox to link TablePlus data folder on two Macs as a temporary solution.

Mac 1: ln -s ~/Library/Application\ Support/com.tinyapp.TablePlus/Data ~/Dropbox/apps/TablePlus 
Mac 2: ln -s ~/Dropbox/apps/TablePlus/Data/ ~/Library/Application\ Support/com.tinyapp.TablePlus/

**Comment by FCO** [comment]
isn't it almost the same issue as #390?
