### ISSUE TITLE
syntax error when some text has quotes

### ISSUE THREAD

**Issue by pouledodue** [TablePlus/TablePlus#969]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
CockroachDB CCL v2.1.4
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
190
3. The steps to reproduce this issue:
insert any value containing a quote (`'`)  then go in the UI and change the row. Like below where I try to save when a column textual value is `j'aime les chats`
```
ERROR:  syntax error at or near "aime"
DETAIL:  source SQL:
UPDATE "public"."c2" SET "client" = '1' WHERE "name_fr" = 'j'aime les chats' AND "client" IS NULL;
```

**Comment by huyphams** [comment]
Hi @pouledodue thanks for the report. I fixed it: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by pouledodue** [comment]
beautiful
