### ISSUE TITLE
Default value on SET() includes apostrophes; error on saving

### ISSUE THREAD

**Issue by blaaat** [TablePlus/TablePlus#970]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MariaDB 10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

190

3. The steps to reproduce this issue:

Column: 
  `permissions` set('a','b'') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',

Then; try to change column to SET('a','b','c'). 
==> **Invalid default value for 'permissions'
All changes were reverted.**

ALTER TABLE x CHANGE `permissions` `permissions` set('a,'b','c') NOT NULL **DEFAULT ''''''** COMMENT '';

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @blaaat could you please try again with this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks.

**Comment by blaaat** [comment]
Issue still persists in that build, same query with ''''''' is generated.

**Comment by huyphams** [comment]
Hi, I see that you've made a mistake in set('a,'b','c'), it should be set('a','b','c'). I tested with the build 195 and it works.

**Comment by huyphams** [comment]
<img width="874" alt="screen shot 2019-02-14 at 3 21 09 pm" src="https://user-images.githubusercontent.com/3654622/52772866-2bbe3e00-306c-11e9-80c8-5334624b782a.png">

**Comment by blaaat** [comment]
> Hi, I see that you've made a mistake in set('a,'b','c'), it should be set('a','b','c'). I tested with the build 195 and it works.

That was just a typo here as example. Please try adding; 'd' now without changing the default.

**Comment by huyphams** [comment]
So you want to set the column default to empty? if yes, you must select the EMPTY in the dropdown or let it empty. the '' is the valid string, it's an empty value.

**Comment by blaaat** [comment]
After selecting empty and saving; this happens: 

<img width="772" alt="schermafbeelding 2019-02-14 om 09 24 26" src="https://user-images.githubusercontent.com/277820/52773092-6c9d5f00-303a-11e9-83cd-ffa7d3902b60.png">

Then try adding 'd' as set-option: 

<img width="218" alt="schermafbeelding 2019-02-14 om 09 25 23" src="https://user-images.githubusercontent.com/277820/52773128-8048c580-303a-11e9-8d8c-41d9e2364403.png">

**Comment by huyphams** [comment]
Well, maybe the root of the problem is you're using MariaDB. let me install it.

**Comment by huyphams** [comment]
I confirm this, I will fix it now. it was MariaDB.

**Comment by huyphams** [comment]
Hi @blaaat it handles correctly now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks for the feedback. it's awesome.

**Comment by blaaat** [comment]
Works perfect now. Thanks for the quick fix!

**Comment by blaaat** [comment]
Now when I change the length on a varchar with empty default: this happens: 

ALTER TABLE `x`.`x` CHANGE `name` `name` varchar(151) NOT NULL DEFAU**LT  CO**MMENT '';

**Comment by huyphams** [comment]
I'm not sure how to reproduce it @blaaat could you show me a screenshot as above?

**Comment by blaaat** [comment]
<img width="930" alt="schermafbeelding 2019-02-14 om 13 16 56" src="https://user-images.githubusercontent.com/277820/52786320-daf21980-305a-11e9-9dbf-80219ecf7bc5.png">

Change to: 

<img width="915" alt="schermafbeelding 2019-02-14 om 13 17 43" src="https://user-images.githubusercontent.com/277820/52786361-efcead00-305a-11e9-8b28-38244c66d47a.png">

**Comment by huyphams** [comment]
Hi, I'm not so sure why your column default is a space (not empty value), but I disallow it on this build: 
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by blaaat** [comment]
It was not a space; definition of the table: 

> CREATE TABLE `untitled_table_118` (
>   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
>   `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
>   PRIMARY KEY (`id`),
>   UNIQUE KEY `id` (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

New build does not fix the issue. (This is on MariaDB 10.1, not tested on 10.3)

**Comment by huyphams** [comment]
Hey, sorry my dropbox didn't sync on time, please try again.

**Comment by blaaat** [comment]
Perfect! Thank you!

**Comment by blaaat** [comment]
This issue isn't completely fixed; Still works correct on MariaDB 10.3, but now on MariaDB 10.1 this happens: 

`ALTER TABLE `klikjezakgeld`.`import_queue` CHANGE `xx` `xx` set('a','b','c') NULL DEFAULT a COMMENT '';`

The single quotes around the default 'a' are missing. Same thing happens for an Enum column. 

Build 212

**Comment by huyphams** [comment]
Hey @blaaat how to reproduce the issue? I've tried it and if I set it as a constant. it will work correctly.
<img width="750" alt="Screen Shot 2019-04-12 at 2 31 48 PM" src="https://user-images.githubusercontent.com/3654622/56019776-b8fdd600-5d2f-11e9-8c04-cc89083b1b12.png">

**Comment by blaaat** [comment]
save default a first with set('a','b'); then change set('a','b') to set('a','b','c')
