### ISSUE TITLE
Alter table drop/create index should be in 1 query.

### ISSUE THREAD

**Issue by blaaat** [TablePlus/TablePlus#971]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MariaDB 10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
195

3. The steps to reproduce this issue:

> CREATE TABLE `cpm_user_site` (
>   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
>   `cpm_user` int(10) unsigned DEFAULT NULL,
>   `site` mediumint(8) unsigned DEFAULT NULL,
>   PRIMARY KEY (`id`),
>   KEY `cpm_user` (`cpm_user`),
>   KEY `site` (`site`),
>   CONSTRAINT `cpm_user_site_ibfk_1` FOREIGN KEY (`cpm_user`) REFERENCES `cpm_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
>   CONSTRAINT `cpm_user_site_ibfk_2` FOREIGN KEY (`site`) REFERENCES `site` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
> 

Now try to change

>  KEY `cpm_user` (`cpm_user`)

 to 

> UNIQUE INDEX `cpm_user` ON `affiliate_v2`.`cpm_user_site` (`cpm_user`,`site`)

Because two separate queries are run; the DROP INDEX errors (required for foreign key). 

<img width="829" alt="schermafbeelding 2019-02-14 om 16 34 13" src="https://user-images.githubusercontent.com/277820/52797558-64fbab80-3076-11e9-9341-2f36cf12560d.png">

One query should run instead: 

> ALTER TABLE `affiliate_v2`.`cpm_user_site` DROP INDEX `cpm_user`, ADD UNIQUE `cpm_user` (`cpm_user`,`site`) USING BTREE;

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Thanks, it should be done that way!

**Comment by huyphams** [comment]
Hi @blaaat it should work now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
thanks for the suggestion!

**Comment by blaaat** [comment]
> Hi @blaaat it should work now: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
> thanks for the suggestion!

Thanks! Works!
