### ISSUE TITLE
UI icons not switching between dark/light mode

### ISSUE THREAD

**Issue by joshhopkins** [TablePlus/TablePlus#974]
Some icons fail to switch properly between light/dark mode on MacOS 10.14

<img width="79" alt="screen shot 2019-02-18 at 12 24 02 pm" src="https://user-images.githubusercontent.com/11452674/52947956-77c4f780-3378-11e9-8f9c-8e9cc11d00c6.png">

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Appears on all drivers

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

190

3. The steps to reproduce this issue:

1. Open connection
2. Switch between dark/light mode

**Comment by AndreasSchantl** [comment]
![image](https://user-images.githubusercontent.com/9936988/57448796-8d9cd700-725a-11e9-9c71-32622aa60296.png)
Same for me. This is really annoying.

**Comment by huyphams** [comment]
it uses the bar tint color. I've updated it. If the theme is light and the bar color is the default. TablePlus will not use the title bar color for the database icon.
