### ISSUE TITLE
Too many updates

### ISSUE THREAD

**Issue by KevinColemanInc** [TablePlus/TablePlus#976]
It feels like every time I run TablePlus (1-5x per week) it asks me to do an update. This is disruptive for me because when I open it I want to run my query, not wait 45s for an install.

I see you can turn off update notifications, but maybe there could be a middle ground.

1. Only update once per month
2. Update on next run. meaning next time I run it doesn't ask me anything, it just updates automatically.

**Comment by huyphams** [comment]
Congrats @KevinColemanInc  🎉, build 194 is the last build to end of the milestone 1.
TablePlus is 1-year-old now and have no urgent update anymore, we plan to release a new update only 1-2 months.
