### ISSUE TITLE
Feature Request: Ability to reorder table columns in "Structure view"

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#983]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

194

3. The steps to reproduce this issue:

When attempting to drag a column into new position in table definition I instead see multiple columns being selected. Until #981 is implemented combination of "add column at the end of the table" + "drag column into desired position" is the only way to make it happen.

**Comment by aik099** [comment]
My apologies. I've found 2 other issues about same thing:

* #836
* #607

Which one I should be voting for? Maybe it's best to close all other duplicate issues.

**Comment by huyphams** [comment]
Think we can keep it opening, I've put those tasks into the backlog already. I will close all the issue after the feature is released.
