### ISSUE TITLE
Mongo connection support SSL

### ISSUE THREAD

**Issue by mrnonz** [TablePlus/TablePlus#984]
1. Which driver are you using and version of it :
- mongo 3.4

2. Which TablePlus build number are you using :
- 194
3. The steps to reproduce this issue:
- Try to connect MongoDB only use SSL

I think you should have option for SSL and add `&ssl=true` into connection string

**Comment by huyphams** [comment]
Hi @mrnonz it's supported on the build 200, could you give it a try?

**Comment by huyphams** [comment]
feel free to reopen this issue if you have any trouble with SSL.
