### ISSUE TITLE
Fulltext index wrong query

### ISSUE THREAD

**Issue by blaaat** [TablePlus/TablePlus#985]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
195

3. The steps to reproduce this issue:

Create fulltext index on column; 
<img width="618" alt="schermafbeelding 2019-02-21 om 09 23 23" src="https://user-images.githubusercontent.com/277820/53154135-57847b00-35ba-11e9-92b5-efa98a5b859c.png">

> CREATE INDEX `name` ON `x` (`name`) USING FULLTEXT;

is generated;
should be: 

> CREATE FULLTEXT INDEX name ON x (`name`);

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @blaaat thanks for the feedback. I just fixed it on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It will be included in the March release.

**Comment by aik099** [comment]
Thanks.

@huyphams , could you please use milestones for issue grouping. This way we can see what's coming in next release.

**Comment by aik099** [comment]
Also maybe you can apply compression to the builds shared via Dropbox. The Dropbox version is 302MB vs 75MB usual. I might be wrong about compression, because new version indeed could have 4x more features than we currently have.

**Comment by huyphams** [comment]
Hi, that build is fat because contains Oracle support. The official is not contains it.

**Comment by huyphams** [comment]
You can follow upcoming feature here @aik099 https://github.com/TablePlus/TablePlus/projects
