### ISSUE TITLE
Feature Request: Ability to increase records per page (and/or disable pagination)

### ISSUE THREAD

**Issue by bwat47** [TablePlus/TablePlus#987]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server (various versions, usually 2014)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 52 (Windows version)

Presently when you select a table, TablePlus will display the first 500 rows.

There is a limitation with SQL Server (prior to 2017) where pagination is not supported: #925

In my case, I do have a SQL 2017 instance, however, I'm often working with user databases that were backed up from older versions of SQL (and hence have an older SQL compatibility level, even after restoring into 2017, so paging in tableplus still doesn't work). Having to alter the compatibility of every database I'm working with would not be ideal.

Would it be possible for tableplus to have options to either increase the records shown per page (and/or disable pagination altogether)?

**Comment by huyphams** [comment]
Thanks @bwat47 I will add ability to change paging limit, next time please submit feature request for the Windows version here: https://github.com/TablePlus/TablePlus-Windows/issues

**Comment by bwat47** [comment]
Thanks!

I didn't realize there was a separate tracker for the windows version, I'll make sure to use that in future :)
