### ISSUE TITLE
Show total number of matched rows beyond 1-300 rows

### ISSUE THREAD

**Issue by lukeb** [TablePlus/TablePlus#989]
When performing a table records filter, the status at the bottom shows 1-300 rows. 

It is fine to only display up to 300 rows in the view, but the **total number of matching rows** should be displayed as well.

1. Which driver are you using and version of it:
MYSQL 8

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.6 (194)

3. The steps to reproduce this issue:
Filter listings for records matching value

**Comment by judgej-owadigital** [comment]
In case other people come across this issue looking for exact counts, there another way to get them. Clicking once on the estimated count will pop up a box with a button to do a full count of filtered rows. If an exact count for larger tables is something you only need occassionally, then this method id ideal.

![image](https://github.com/user-attachments/assets/b04af0c2-ebe1-4c0b-9e72-29af5a39ceb5)
