### ISSUE TITLE
Allow option to group queries by DESC date

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#99]
Currently oldest queries are on top, I think newest queries should be on top, or at least an option should be in place.

![screen shot 2017-10-30 at 11 12 03 am](https://user-images.githubusercontent.com/7946786/32187794-465e9016-bd63-11e7-8042-4fbfeee4bffb.png)

-Brian

**Comment by brian-crane** [comment]
also just noticed it looks like its unordered as well

**Comment by brian-crane** [comment]
I also wanted to say Build 67 is looking great- queries seem to be running faster than ever! Keep it up Huy

**Comment by huyphams** [comment]
Hi @brian-crane `also just noticed it looks like its unordered as well` => it's bug, it should be ordered.

Not many features include in build 67-68 but but fixes and performance improved.
