### ISSUE TITLE
Feature request: auto-complete column names in query editor (SELECT ... FROM part)

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#990]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

194

3. The steps to reproduce this issue:

I've noticed, that in query editor when I've typed `SELECT `, then I'm getting no auto-complete of column names until I've specify `FROM table_name` part. In that scenario having auto-complete from all table columns (with duplicates removed) would be a good idea considering that column name could be typed using fuzzy-search (type `twt` to show `ThisWeekType` column).

**Comment by huyphams** [comment]
If you're using the build 194, it should be supported, please see the attachment.
<img width="1344" alt="column" src="https://user-images.githubusercontent.com/3654622/53192786-e12b5b80-3641-11e9-8eff-248e6325fa6e.png">

**Comment by huyphams** [comment]
I found a bug, it won't work if you missed the semicolon, I'm not sure why

**Comment by aik099** [comment]
In my case I type `SELECT ` (select + space) and then attempt to auto-complete. This way `FROM` part is missing and without no table name for auto-complete is picked.

I've also tried `SELECT ... ;` scenario (I start typing column name instead of `...`) and it also doesn't work.

**Comment by huyphams** [comment]
hey @aik099 could you please give this build a try? https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Let me know if it works

**Comment by aik099** [comment]
Doesn't work. Here is the video of what I'm doing: 

[TablePlus_SelectAutoCompleteIssue.mp4.zip](https://github.com/TablePlus/TablePlus/files/2892543/TablePlus_SelectAutoCompleteIssue.mp4.zip)

**Comment by huyphams** [comment]
I think we misunderstood each other, TablePlus only supports suggest column for a table which exists on the statement.

For example: select <type_here> from comments

=> TablePlus will suggest column from table `comments`. 

TablePlus will not suggest a random column from all tables because some users have many tables (thousands), if we fetch all metadata, it would extremely slow.

**Comment by aik099** [comment]
Ah, then this is expected behavior. I'll try to add `FROM` and then start listing column names in `SELECT ...` part.

Thank you.
