### ISSUE TITLE
Don't add an empty comment to ALTER statement

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#992]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

194

3. The steps to reproduce this issue:

When `comment` column value in table structure view during new column adding has `DEFAULT` or `EMPTY` value the ALTER statement in preview pane would have `COMMENT ''` part. I think, that it should be added, because it doesn't help much.

**Comment by huyphams** [comment]
This build should fix the issue: https://www.dropbox.com/s/kjeon87wr82g2ps/TablePlus.dmg?dl=0
Thanks
