### ISSUE TITLE
The "Manual input..." context menu does nothing

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#993]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

194

3. The steps to reproduce this issue:

When I select `Manual input...` context menu from dropdown of `data_type` or `extra` columns (likely others as well) in structure view nothing happens. I'm not sure what should happen, maybe manual input textbox/textarea with auto-complete should show up.

**Comment by huyphams** [comment]
Hi, Manual input shows the right detail sidebar!

**Comment by aik099** [comment]
I have it always enabled and that's why I saw no difference.

What can be done additionally is to:

* either focusing input in right panel corresponding to the column for which the `Manual input...` context menu option was selected
* or having some kind of blinking effect (not sure what effect is native to Mac)
* or combination of both

.

**Comment by huyphams** [comment]
it now does focus on the right sidebar after clicking.
