### ISSUE TITLE
Missing semicolon in preview pane/history

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#994]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

194

3. The steps to reproduce this issue:

When planning several changes (e.g. adding multiple columns to a table or doing different updates to a table data) all SQLs go into preview pane and that's cool. Unfortunately none of SQLs have `;` at the end of them. When committing changes via `Cmd+S` they are also stored on `History` tab and also without `;`.

This becomes a problem, when I want to copy paste these changes and say paste into database migration script. Because SQLs aren't separated by `;` whole block of text is considered as large SQL error.

**Comment by huyphams** [comment]
Hi @aik099 how can I reproduce this issue, it seems right on my setup?
<img width="801" alt="screen shot 2019-02-22 at 12 45 56 am" src="https://user-images.githubusercontent.com/3654622/53189974-3a43c100-363b-11e9-8293-0594a9c6846b.png">

**Comment by huyphams** [comment]
Ah, I got it, my bad! I'm fixing it now.

**Comment by huyphams** [comment]
Hi @aik099 I fixed this bug on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
and also the https://github.com/TablePlus/TablePlus/issues/988

**Comment by aik099** [comment]
Thanks.
