### ISSUE TITLE
Cannot see any procedures or functions on SQL Server 2008

### ISSUE THREAD

**Issue by javierecf** [TablePlus/TablePlus#995]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
SQL Server 2008

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
1.6 (194)

3. The steps to reproduce this issue:
Just open the connection, all the tables are shown for what i can see, but the database has multiple store procedures and scalar and table functions (it is a very big DB), but i cannot see any under the functions section, also there is no procedures section, not sure if that's normal.

I'm new to the app, i was just wondering if maybe I'm doing something wrong.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @javierecf 
<img width="492" alt="screen shot 2019-02-22 at 9 55 33 am" src="https://user-images.githubusercontent.com/3654622/53216696-0478f980-3688-11e9-8c06-21cf6464135f.png">
Did you enable this section? After enabling it, please press command + R to reload the data. Please let me know the result

**Comment by javierecf** [comment]
Excellent, that was it, thank you so much, I will report anything for sure, the app looks very promising i will buy the upgrade for sure (even if the exchange rate bites a little) if it works for my job.

**Comment by alvint** [comment]
@huyphams Can you also add the contents of Item Sections to the View menu? I'm always forgetting where those options are.

**Comment by neha-sri** [comment]
@huyphams Could you add this to the FAQs please? I was about to create a new issue until I landed on this one. Fantastic app by the way!
