### ISSUE TITLE
Don't use database name in preview / history

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#998]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

195

3. The steps to reproduce this issue:

Not sure how it's supposed to work, but I have:

1. one database per workspace
2. each workspace have it's own preview pane

Considering above observed is how it's supposed to work it doesn't make sense to put database name in front of every SQL in preview pane (these SQLs then are added to the History).

My workflow is like this:

1. make changes to database structure
2. see preview pane is populated
3. press `Command+S` to see SQLs executed
4. copy/paste SQLs from history to database migration script in my application

Because of database name is always present in SQLs I have to manually remove it from every SQL.

**Comment by huyphams** [comment]
I don't think that we can remove the database name. MySQL allows the user to query crossing database and the user can change the database themselves by run user <database_name>.

If TablePlus don't use database name, it can update data incorrectly. TablePlus suppose to be a trusted/accurate client. So I think we can't fix it.

If you agree with me, please close this issue. Thanks for the suggestion!

**Comment by aik099** [comment]
> ... and the user can change the database themselves by run user <database_name>.

Can you explain a bit more about this? I know the `USE database_name;` statement. But it would also work from within query editor to permanently change current database in the workspace?

> If TablePlus don't use database name, it can update data incorrectly....

Is it possible to change database used within current workspace? If it's not possible, then even without using database name in preview pane you can guarantee, that they're executed on correct database.

**Comment by huyphams** [comment]
For example:
1. User makes a change in table x in database A.
2. User run command: use B (B is the production database).
3. User press command + S.
Without database prefix, it will submit the change to database B (instead of A).

**Comment by aik099** [comment]
I see. I wasn't aware, that `USE ...` statements, executed in Query Editor change current database globally and not for particular query call.
