### ISSUE TITLE
Make each workspace have it's own query history

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#999]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

195

3. The steps to reproduce this issue:

Right now it seems, that `History` tab contains all SQLs ever executed no matter workspace/database. 

That makes history pane less useful (even with search capabilities), when I just want to see SQLs executed in a particular database/workspace (are workspace & database the same?), because SQLs executed from Query Editor likely will never have database name in them, because they work anyway.

**Comment by huyphams** [comment]
Currently, History is separated per connection but not database in the connection.

**Comment by aik099** [comment]
What you think about changing that behavior to per-connection + per-database? Or make it configurable?

**Comment by huyphams** [comment]
Well @aik099 that's what I thought when design History but then I realized that the user can change the database name any time, anywhere (by running a command, drop database, command line, other application... etc..) and TablePlus will never know the new name, so all the history can be lost or never be accessed. So I decided to use connection ID instead.
You can work around by creating multiple connections or keep them on the favorite section.

**Comment by aik099** [comment]
Ah, that makes sense. Thank you.
